### PR TITLE
[MIRROR] Adds fishnets [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/72541
--------------------

## About The Pull Request

Adds fishnet socks in knee, thich and stocking lengths

image

## Why It's Good For The Game

More cosmetic choices, allows everyone to wear fishnets when they're currently only found as part of very specific clothing items

## Changelog
:cl:
add: Added new fishnet style socks, in a choice of three lengths
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
sex

**Comment by RatFromTheJungle** [comment]
sex

**Comment by SpaceVampire** [comment]
sex

**Review by Zonespace27 — APPROVED** [review]

**Comment by ghost** [comment]
Will make sure this actually works in my other underwear PRs (we have a modular underwear file)

**Pull request merged**
