### PR TITLE
[Modular] Better Employment Contracts, Again

### PR DESCRIPTION
**Pull request by Stalkeros2**
## About The Pull Request
Replaces /tg/'s "slave"-"MotherFucking DemiGod" contracts with a more sane ones that no longer mention that. The entire implementation is relatively barebones as it doesn't feature any new information such as character records or whatnot, so if you want them to be more expanded then be my guest and do that; unless I do that sometime later.

## How This Contributes To The Skyrat Roleplay Experience
Nanotrasen being comedically evil is an overdone trope and is straight up just a bad idea for muh high roleplay environment.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

image

</details>

## Changelog

:cl: Stalkeros
add: Saner employment contracts that no longer mention slavery and deity corporations.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
I would enjoy the contract being nicely and more officially formatted :3 but I know that papercode is limited/hellish so it's just an ask

**Comment by Stalkeros2** [comment]
I really wish I knew how to do this.

**Comment by Plejek** [comment]
> I really wish I knew how to do this.

What's your discord? I could try to help ya out with formatting!

**Review by lessthnthree — APPROVED** [review]

**Comment by lessthnthree** [comment]
Ping someone when the formatting is done.

**Pull request merged**
