### PR TITLE
[BUG FIX] Medical borgo fix

### LINKED ISSUE #9479: Medical borg models are shifted to the right.
Reporting client version: 514.1557

## Round ID:
3602

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[NonModular] Rebalances, and makes >just vampires< available year-round.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9144)
- [zephyr's admin mark PR](https://github.com/Skyrat-SS13/Skyrat-tg/pull/7959)
- [[TM-ONLY] Disabling 911 until it's fully fleshed out](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9267)
- [Making kudzu more utilitarian](https://github.com/Skyrat-SS13/Skyrat-tg/pull/9217)

## Reproduction:

Seemingly all medical dogborg modules are shifted to the side about 16-17 pixels as it can be seen in this screenshot
Screenshot_39
Screenshot_38

### PR DESCRIPTION
**Pull request by SpookyTheFox**
## About The Pull Request

This fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/9479 which is caused by the game not understanding that specific medical borgs are "dogborgs" and thus need a sprite offset, their rest verbs, and the ability to accept the affection module. This applies only to medical dogborgs. Note that the files in question have recently been through a few refactors and improvements, and unfortunately, this fix throws out those improvements. Only medical borgs were brought to the new system, which is why only those were broken. This fix effectively undoes several improvements, but they are not player facing. The bug is player facing.
## How This Contributes To The Skyrat Roleplay Experience
This is fixes a player facing bug.

## Changelog

:cl:
fix: fixed medical dogborg sprites in a laborious way
/:cl:

### CODE REVIEW

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
Converting this to a draft because, even though that's technically functional, I'd rather we use that system that was designed specifically for it, and figure out why SKIN_TRAITS aren't working properly.

**Review by Gandalf2k15 — CHANGES_REQUESTED** [review]
Please don't revert improvements, can you make it so they work with the new system?

**Comment by SpookyTheFox** [comment]
I wish I could, but I can't. It's not exactly an improvement if it breaks stuff. I have spent considerable time staring at the skin traits version, and can't find where it's not working. I agree, the new system is much nicer to look at code wise. Unfortunately, it's slightly beyond my coding skills, and significantly beyond the time I can put in right now to fix it. Medical borg has been bugged in one way or another since the beginning of last month. Out of frustration, I have put up this fix which just copies and pastes the old version, with updated paths following the modularization audit.

**Comment by SpookyTheFox** [comment]
Closing this in favor of https://github.com/Skyrat-SS13/Skyrat-tg/pull/9701 which is not only a better solution but covers even more bugs, and ports the entire system.

**Pull request closed without merging**
