### PR TITLE
Blob Enhancements 1

### PR DESCRIPTION
**Pull request by Zergspower**
With the current state of SR Blob being so... sad.... we've discussed it in the admin circle and will be giving teeny tiny buffs. The first here is a simple Point rate boost.

## About The Pull Request

The blob hasn't been touched in quite some time whereas we've had many revisions to weapons since, notably how the current state of armament has made it to where only 1 or 2 strains have even a small chance at surviving since all the other ones are shut down instantly. This is the first test to bring Blobs up to a fighting chance against a crew that spends a lot more time in maintenance than our TG Parents.

## How This Contributes To The Skyrat Roleplay Experience

Blobs are often caught before they can really even stand a chance, the past 15 monitored blob events only 1 got near critical mass where all others failed to even reach 50 tiles. The goal of this change is to give a small boost and see how it pans out before addressing the strains themselves and/or other parts if this doesn't give the desired results.

## Changelog

:cl:
balance: Changes the point generation from 2 to 2.5
/:cl:

### CODE REVIEW

**Comment by SpookyTheFox** [comment]
We had a blob victory what, last week? It's not that rare.
Blob buffs, even small ones, have been tried before. And they went very very badly. The offered justifications in the past of high population and powerful weapons are not constant factors and bear very little on blob performance, which is primarily determined by crew attention span. The trick to balance is to put antagonists on a reversed exponential curve to ensure that they can start easily but can never win, by putting a huge drop off in power at the end. This is not possible with linear stat changes.
If you want to improve blob's early performance, you just give them more starting points, and then chop down the total number of factories they can make to compensate, rather than touching the one magic win/loss decider stat.
Further, we really do not want blob to do well, it's a highly disruptive antag that degrades the remaining portion of the round even when the crew wins, and generates a lot of lag in the process.

**Comment by Zergspower** [comment]
> We had a blob victory what, last week? It's not that rare. Blob buffs, even small ones, have been tried before. And they went very very badly. The offered justifications in the past of high population and powerful weapons are not constant factors and bear very little on blob performance, which is primarily determined by crew attention span. The trick to balance is to put antagonists on a reversed exponential curve to ensure that they can start easily but can never win, by putting a huge drop off in power at the end. This is not possible with linear stat changes. If you want to improve blob's early performance, you just give them more starting points, and then chop down the total number of factories they can make to compensate, rather than touching the one magic win/loss decider stat. Further, we really do not want blob to do well, it's a highly disruptive antag that degrades the remaining portion of the round even when the crew wins, and generates a lot of lag in the process.

That's the point on why we're approaching this small, we agreed on just a generation buff to see how it plays out before going different routes. Even before MCR's came about they were struggling but now it's a plain joke, Blobs by design are meant to be station-wide shift-ending threats - but their current state is weaker than moldies.

**Comment by Zergspower** [comment]
I moved it to 2.5 as that's a 25% increase - though i'm really unsure if that will be felt at all since high TDI can make point regeneration stop completely.

**Comment by Draganfrukts** [comment]
> Blobs by design are meant to be station-wide shift-ending threats

You mean kind of like the thing we actively try to avoid unless it's roundstart?

**Comment by RatFromTheJungle** [comment]
> > We had a blob victory what, last week? It's not that rare. Blob buffs, even small ones, have been tried before. And they went very very badly. The offered justifications in the past of high population and powerful weapons are not constant factors and bear very little on blob performance, which is primarily determined by crew attention span. The trick to balance is to put antagonists on a reversed exponential curve to ensure that they can start easily but can never win, by putting a huge drop off in power at the end. This is not possible with linear stat changes. If you want to improve blob's early performance, you just give them more starting points, and then chop down the total number of factories they can make to compensate, rather than touching the one magic win/loss decider stat. Further, we really do not want blob to do well, it's a highly disruptive antag that degrades the remaining portion of the round even when the crew wins, and generates a lot of lag in the process.
> 
> That's the point on why we're approaching this small, we agreed on just a generation buff to see how it plays out before going different routes. Even before MCR's came about they were struggling but now it's a plain joke, Blobs by design are meant to be station-wide shift-ending threats - but their current state is weaker than moldies.

Blobs by design are meant to lose, like, before you can even move onto other points they're /not meant to win/, they're meant to show up, break a bit of the station, get killed, that's their inherent loop.

Blob actually /winning/ is a sign somethings wrong, it's why it immediately ends the round and kills everyone, as compared to dragons that just get a buff

**Comment by Aether217** [comment]
This is not an issue of making blob "win", it was not the point and it will not be. It's an issue of making blob more menacing in the face of an ever expanding powercreep of security gear and average joe crew being expected to be able to carry weaponry, and especially ballistics which notoriously give the blob a very rough time.

It's small changes to give it a bump and make blob a threat, not a round ender.

**Comment by tf-4** [comment]
> If you want to improve blob's early performance, you just give them more starting points, and then chop down the total number of factories they can make to compensate, rather than touching the one magic win/loss decider stat.

^^^ I'm not sure why point generation is what is being changed to compensate for poor early performance when point gen is more so a mid-game affecting stat when you've had time to build up some points.

**Comment by Iamgoofball** [comment]
If you wanted to improve their starting performance, give them a higher point cap and more starting points.

**Comment by Gandalf2k15** [comment]
ok

**Pull request merged**
