### PR TITLE
[modular][fix][FUCK] FUCK I MIXED UP SOME ICON STATE STUFF

### PR DESCRIPTION
**Pull request by thestubborn**
FUCK FUCK FUCK

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
confikts

**Comment by thestubborn** [comment]
someone musta updated between me making this aaaa

**Comment by Funce** [comment]
Yes

**Comment by thestubborn** [comment]
working on it
https://github.com/Skyrat-SS13/Skyrat-tg/pull/5053

**Pull request closed without merging**
