### PR TITLE
fixes ghost cafe sleepers

### PR DESCRIPTION
**Pull request by tf-4**
image

## Changelog
:cl:
fix: Ghost cafe sleepers work again
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
Weak solution: Skyrat edit the check

Strong solution: Uses = INFINITY

**Comment by tf-4** [comment]
Eh, editing the check rather than having the uses be a big number seems more 'proper' to me, even if less modular, though I can do it either way.

**Comment by vinylspiders** [comment]
> Eh, editing the check rather than having the uses be a big number seems more 'proper' to me, even if less modular, though I can do it either way.

Another modular option would be to change this to some number greater than 1

https://github.com/Skyrat-SS13/Skyrat-tg/blob/9465310dfa666860e0dcd88e9e33cc296f4c0355/modular_skyrat/modules/ghostcafe/code/ghost_role_spawners.dm#L11

https://github.com/Skyrat-SS13/Skyrat-tg/blob/9465310dfa666860e0dcd88e9e33cc296f4c0355/modular_skyrat/modules/ghostcafe/code/ghost_role_spawners.dm#L42

and then override 
```

/obj/effect/mob_spawn/ghost_role/robot/ghostcafe/attack_ghost(mob/dead/observer/user)
. = ..()

uses += 1
```
```

/obj/effect/mob_spawn/ghost_role/human/ghostcafe/attack_ghost(mob/dead/observer/user)
. = ..()

uses += 1
```

so that the uses are just immediately incremented after getting decremented, so 0 is never reached.

That is how I would do it anyway, if I were trying to avoid a Skyrat edit. I don't really see the big deal of having one for this though personally.

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
I feel like this could easily be taken upstream, I'm sure that they'd appreciate it, even if only for the admins being able to have a proper way to make spawners infinite.

**Pull request closed without merging**
