### PR TITLE
Forging changes (mostly the weapons and armor) : The removal of reagent imbuing, and the rebalancing of everything that's left

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

The big ticket item here, the removal of reagent imbuing from forging armor, weapons, tools, shields, the components are just gone.

To go alongside this, all of the weapons have been given a pass for balance and changed to suit the fact that the reagent bit doesn't exist anymore, lemme break it down for you:

- The sword -

The sword used to do 15 damage and have 10 armor penetration, alongside a 25 block chance.

With the update, swords will do 18 damage, have no armor penetration, and keep their block chance.

- The katana -

The original plan was to remove this but looking at it compared to the rest of the rebalanced weapons, I think it still has a good role to fit into.

The only change that actually happened to it is that it has a bit of a wound chance increase, even higher if you have no clothes to protect yourself.

- The dagger -

The dagger lost its almost doubled attack rate.
Damage has gone from 8 -> 10

The reagent dagger in this case is equivalent to the hunting knife that the curator can get, or that you can find on icebox sometimes. Something that is in all forms but path a knife I don't think needs to be much stronger than the other knives you can get through other means. The doubled attack rate made it competitive with the other forging weapons sure, but as something that could be concealed very easily that was /very/ strong.

- The spear & staff -

Why are you grouping these together paxil, that makes no sense, what are you doing man!!!!

The spear and the staff now serve similar jobs, they are both weapons that will do 10 damage when not wielded, however will do 18 damage if you use both of your hands. The big difference between the two is that the spear will do piercing wounds like a spear ought to do and can be thrown for good damage, while the staff is extra good at breaking limbs with wound bonus.

I removed the two tile reach of spears because as its been stated by a good number of people, fighting someone who can spear you from two tiles away isn't really fun for any party except sometimes the one /with/ the spear. To keep it in line with all the other melee weapons, and to downgrade the MASSIVE buff to melee combat that is reach, its no more.

- The axe -

The axe is no longer the main throwing weapon of forging, losing its high 22 throwing damage. The axe does 15 damage and lacks armor penetration, but will have a non-insignificant wound bonus against unarmored targets. Not to mention, its still a pretty good throwing weapon despite the debuff, with 18 throwing damage and all of the benefits to throwing that a spear gets (like speed, and embedding characteristics)

- The bokken -

The bokken I've seen to removing for not really having a good place with all the other forging craftable equipment. The first reason for that is you didn't even need the forging part to begin with, since you could spam out bokkens with just some wood at the crafting bench. The other part comes to the whole projectile deflection and blocking bit it was build around. The role of protecting yourself with blocks is already being done by the shields and two of the weapons, it didn't seem fully right to had a weapon who's sole purpose was to do that role in a worse manner.

- The hammer -

Functionally, the hammer is identical to the katana in what it does aside from the fact it will do blunt wounds rather than sharp ones. This one goes out to all my bone crushing enjoyers out there.

- The armor -

The armor has had one really big change, and one kinda small one.

The ability to stick goliath plates on the armor has been removed, because you could get some pretty powerfully high levels of melee protection over every other option available for little more than a collection of goliath plates. I believe with the chestplate for example, you could get up to 70 melee armor (not small!) and that's the conservative estimate given I don't remember exactly how many plates it could take.

Armor levels have also been made a single standard amount between all of the armor pieces (fixing the boots not having the same armor as the other armor pieces), with 40 melee armor, 30 bullet armor, 50 fire armor, and 20 wound armor, which for a vest you can make just about anywhere, is pretty good. For reference, it bests security armor in melee and wound protection, and not much else.

## How This Contributes To The Skyrat Roleplay Experience

Maintainers pretty much all agree that reagent combat as a concept really is not all that fun for the players partaking (especially those at the mercy of it). The unreliability of balancing around what chems have been added/exist/become the meta/you name it really, is really holding forging weapons back.

Now, I also wasn't going to just leave forging stuff in its balanced-around-reagents state, this makes forging weapons be in line with a lot of other comparable weapons, and more than glorified toolboxes.

## Proof of Testing

Gimme a bit I wanted to publish this first

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
balance: Forged weapons have been rebalanced to be all sidegrades of each other (aside from the knife which behaves like a knife), with each having different strengths over the others.
balance: Forged armor can no longer have goliath plates applied to them, and every piece of forged armor now uses the same armor values (which technically fixes the boots having less armor than the rest of the set)
del: Horseshoes have been removed due to being nothing but invisible armoring, which I do not want us to have.
del: Bokkens have been removed due to just being weird, if projectile protection is required then hammer yourself up one of the shields!
/:cl:

### CODE REVIEW

**Comment by kittysmooch** [comment]
the real advantage of the bokken is that you could make them ridiculously fast because they didnt require the forge or anvil, or even extra iron beyond making a workbench and a hammer. i would have loved to see them stay and get transmogrified into like, melee riot darts with pitiful or no brute but a respectable smack to stamina.

**Comment by YakumoChen** [comment]
Are those armour values the only ones the armour has or does it inherit any other armour stats?
Good physical armouring makes sense but if there's some energy protection as well I might question the validity of a better security armour with no clear downsides.

**Comment by Paxilmaniac** [comment]
> Are those armour values the only ones the armour has or does it inherit any other armour stats? Good physical armouring makes sense but if there's some energy protection as well I might question the validity of a better security armour with no clear downsides.

The four armours I listed are the ONLY ones it gets

**Comment by Knouli** [comment]
I was quiet when they decided to undo mechanical differences for different materials, but this isn't something I can just stand by on.

I will be upfront here and challenge the notion - why must we go nuclear on removing regent imbuing? I find the system not just novel, but engaging. The bandwagon for anti-chemical combat is an easy one to jump onto - but I, at least in my personal experience, don't see why it must be totally struck from existence, I've just not seen it ever really come up in-game on station to any degree that says it ought be.

Further, I disagree with the notion that a blacklist must imply its removal - if anything, its all the more reason not to, and instead focus on curating that list rather than going right for feature removal. The mechanical framework is already in place, let's make use of it.

I also went on and complied the numbers for the proposed weapon balances and my comments . . .

All Weapons
-Sharp
-Throw force: 10
-Resistance: Fire Proof

Sword
-Force: 15 > 18
-Block Chance: 25 > 25
-Armor Pen: 10 > 0
-Bare Wound Bonus: 0 > 10

Jack of all trades, and a prefect complement for the defensive oriented sword-and-board. Three more force for minus ten armor pen reads as a nerf in my eyes - but all in all I'm alright with the sword's role as a defense oriented weapon.

Katana
-Force: 15 > 15
-Armor Pen: 25 > 25
-Wound Bonus: 0 > 5
-Bare Wound Bonus: 0 > 15

The weeb's choice. Higher wounding at a reduced force. I never much cared for the katana's armor pen bonus as I always saw it more as the weapon you want to us against unarmored combatants or if you're wanting to inflict wounds. You didn't touch armor pen in your proposed change, but I feel like it could be further oriented towards that role of wounding and unarmored combat as opposed to armor penetration - a role I feel is more fitting for the hammer.

Dagger
-Force:  8 > 10
-Bare Wound Bonus: 0 > 10
-Attack Speed: 2x > 1x
-Slots: Belt/Back > Belt

The dagger, the poor thing. I very much liked the idea of the 2x attack speed, and would rather see the force taken lower to preserve that speed rather than a higher force. I feel it fulfilled a very fun role as the assassin's poisoned blade, allow you to get in and inject a lot of chemicals if it were imbued, but at the cost of keeping you in melee because of its damage being contingent on it's attack speed rather than force. And why did you remove the back slot holster?

Staff
-Force: 0/0 > 10/18
-Wound Bonus: 0 > 10
-Bare Wound Bonus: 0 > 15
-Size: Normal > Bulky

From pacifist weapon to blunt weapon. I suppose this is stat-ed out to be effective in non-armored combat where you're wanting to deal bone wounds rather than bleeding? I can get behind the idea, as that would make it essentially the blunt complement to my envisioned use-case for the katana. But where I want to keep regent imbuing, I'd want to keep a pacifist means of application.

Spear
-Force: 10/17 > 10/18
-Throw force: 15 > 20
-Armor Pen: 10 > 10
-Wound Bonus: -15 > -15
-Bare Wound Bonus: 15 > 15
-Embedding: 0 >  Pain 2, remove pain 4, jostle 2.5
-Reach: 2 > 1
-Jousting: No > Yes

The most egregious offender in my opinion. This isn't a balance, it's an assassination. These are glass shard spear stats. Who is going to go through building a whole ass workshop to make a spear that is mechanically the same as a glass shard spear? No, I don't think removing the range and buffing it's throw force is a proper complement, either. The spear was always supposed to be the 'weak but safe' option you could use to poke from a range in my mind, leaving you open to counterattack if you let that range close because you did not take a shield. Removing that range is removing its defined role.

Axe
-Force: 15 > 15
-Throw Force: 22 > 18
-Armor Pen: 10 > 0
-Bare Wound Bonus: 0 > 20
-Embedding: Pain 2, remove pain 4, jostle 2.5 > Pain 2, remove pain 4, jostle 2.5

The throwing axe. I haven't had much experience with it, truth be told, but the idea of a dedicated throwing weapon was neat. I'm not sure why you felt the need to dethrone it as 'the' throwing weapon, as removing the armor pen only further removes its viability in melee combat, leaving me scratching my head at what case you would use it in.

Hammer
-Force: 19 > 15
-Armor Pen: 0 > 25
-Wound Bonus: 0 > 5
-Bare Wound Bonus: 15 > 15

The hammer. I agree fully with giving it armor pen. It should be, in my mind, the choice for armor penetration. But as it is now, it's just the katana but blunt? As I mentioned before, I feel the katana should emphasis wound combat against unarmored foes, and the hammer should focus more on anti-armor dealing consistent, but lower, damage.

Bokken
-Force: 15/7 > 0/0
-Block Chance: 20/40 > 0/0

The weeb's other choice. Another that I haven't done much with. I'll concede that the projectile deflect was out there - even if I really do like the aesthetic of samurai cutting bullet. It let you go back and forth between offense and defense, holding it in both hands upping your deflect, while lowering your force - a neat concept. I agree with kittysmooch here - there is a great opportunity to make it a less than lethal weapon focusing in on stamina damage. You know, using it like the proper training weapon it is.

Armor
-Melee: 40 > 40
-Bullet: 40 > 30
-Fire: 50 > 50
-Wound: 30 > 20
-Goliath Plates: Yes > No

I really, really, really don't like the idea of removing goliath plate upgrading. If someone wants to spend half an hour hunting out goliaths to upgrade their hand-crafted armor, I think that they should be able to. I would be so much in favor of just dropping the starting values of the armor and allowing for upgrading up to a higher value than just dropping out the upgrade mechanic as a whole. Punish Joe McGrey Tide that wants a free metal armor vest on the fast, but allow our tribal buddies opportunity to make something worth a damn.

**Comment by Nerev4r** [comment]
> 



> I was quiet when they decided to undo mechanical differences for different materials, but this isn't something I can just stand by on.
> 
> I will be upfront here and challenge the notion - why must we go nuclear on removing regent imbuing? I find the system not just novel, but engaging. The bandwagon for anti-chemical combat is an easy one to jump onto - but I, at least in my personal experience, don't see why it must be totally struck from existence, I've just not seen it ever really come up in-game on station to any degree that says it ought be.



It really, really isn't novel or engaging. The only real things you can put in a reagent weapon are either things that are already blacklisted (because they're fightwinners that avoid our usual means of keeping them out like thick clothing), things we haven't blacklisted yet because nobody's coughing them up, or things that are uninteresting enough (few-damage toxins that get blocked by the liver, meds you can just apply using a hypospray) you start to wonder why they're even there. Reagents take away from the idea of blacksmithing because we have to keep the stats minimal *while* keeping in mind that you can amp them up or do goofy shit w/ them.

That being said, I do agree with some of this comment that a lot of the balance here seems to be kind of conservative. We could go a bit harder on making these more worthwhile.

**Comment by Paxilmaniac** [comment]
The balance has been 'conservative' because I've balanced them around how easy they are to get, in comparison to other weapons on station. My baseline for the creation of all of these was chaplain weapons. Chaplain weapons are usually one only for a round and are a good middle ground between "the stuff that's strong" and "the stuff that you picked up out of a locker to swing at me". They are weapons that you can 100% use in a fight over most things in the game because they have strengths that you can't usually get otherwise. I do not make them much stronger than that because stronger weapons are gated behind either cargo or thievery, both of which are a bit more effort and oversight than a maint room with a few materials.

**Comment by Zergspower** [comment]
Does this affect the bone spear? Kinda the only useful weapon ashies have for a good part of their life

**Comment by Gandalf2k15** [comment]
Ensure you discuss this with the creator before continuing.

**Comment by YakumoChen** [comment]
Hi. I wrote the damage numbers for forge weapons.

The intended balance for a lot of these weapons hinges on the fact you can't hide most of them, which usually means security asking for your permit or taking the weapon.

Trying to balance these by arguing cargo should be "better" is a bit of a hard sell. The cargo options trade time for money, most of them can fit in your backpack as well.

Chaplain's weapon doesn't require a permit, and the most reliable, basic option fits in a pocket. And protects against a couple common antags on station.

**Comment by Paxilmaniac** [comment]
I've just had an incredible idea for how to do these changes better

**Pull request closed without merging**
