### PR TITLE
Plasmamen Are Able to Select Sex (Pronouns) on Character Preferences Screen

### LINKED ISSUE #12123: Plasmaman race lacks gender options
Reporting client version: 514.1575

## Round ID:
4766

## Testmerges:
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)
- [[NON-MODULAR]Fixes corrupt photo records](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10346)
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[TM-ONLY] Disables speech circuit](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12024)
- [[HOST] [MODULAR] New character customization option, Headshots.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11860)
- [[SEMI-MODULAR] Medical Smartdarts](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11836)

## Reproduction:
In character preferences, after selecting the Plasmaman race, the button to choose your characters gender from Male, Female or Other isn't available. I believe it defaults to the last selected gender of the character in that slot/the last gender chosen on a different race, as without the option, I spawned into the round with a female gender given all my equipment was prefixed wit 'She is' or 'She has'. 

I imagine this isn't intentional, as lacking the choice to change your gender or not being fixed into a 'They' option seems buggy.

### PR DESCRIPTION
**Pull request by malleyeno**
## About The Pull Request

This PR Fixes #12123 by allowing players using the Plasmamen species to select their sex on the character preferences screen. Doing this will allow players to choose which sets of pronouns their character uses. This is accomplished by setting the sexes tag on plasmamen to TRUE.

Note: Plasmamen players are also able to choose which body type their character uses, but it defaults to using the defined sex. So if a plasmaman uses the female sex, the character will have she/her pronouns but also have a female body type -- so their clothes will look like they have breasts. Users may change their body type to male to get around this, should they choose. 

(In testing, pronouns and body type were the only changes I noticed were made for plasmamen by making this switch. DNA scanning, medical scanners, and variable checking did not seem to find any difference between which gender a plasmamen was set to, so I believe this change to be safe.)

## How This Contributes To The Skyrat Roleplay Experience

This PR allows players to choose which pronouns their character uses. This change keeps in line with the roleplay philosophy established in the issue this PR addresses, and also with the revert of #9884.

## Changelog

:cl: Morgan Yeeno
fix: Plasmamen users may change their character's sex and pronouns; Plasmamen sexes tag set to TRUE.
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
😳

**Comment by Gandalf2k15** [comment]
Did you check to see if this breaks bodytypes for plasmamen?

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/11094

**Comment by Gandalf2k15** [comment]
Oh yeah, we had this before, I think the same applies still.

**Pull request closed without merging**
