### PR TITLE
Departmental Guards now have their own beret heirlooms.

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request

Departmental Guards now have their own beret heirlooms.

## How This Contributes To The Skyrat Roleplay Experience

Five departments, yet they all have a red beret. 
image
The Cargo badge is silver. I just forgot to recomp during this screenshot, it was yellow by mistake.

## Changelog

:cl:
add: Departmental Guards now have their own beret heirlooms. Non-heirlooms in their lockers.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
what the fuck is that commit history

**Comment by theselfish** [comment]
> what the fuck is that commit history

I have no idea.

**Comment by theselfish** [comment]
You hit merge from master, get a bunch of weird commits. Revert. And it's all fine.

**Comment by theselfish** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/13007

**Pull request closed without merging**
