### PR TITLE
bluesec inventory sprites

### PR DESCRIPTION
**Pull request by cheapcents**
## About The Pull Request

adds inventory icons, replacing the placeholder sprites from eris that we had for them
changes belt sprites to look a bit better
image
image
image

## How This Contributes To The Skyrat Roleplay Experience

somehow

## Changelog

:cl:
imageadd: Added inventory icons for the security clothes
/:cl:

### CODE REVIEW

**Comment by desertmote** [comment]
screenshots would be preferred

**Comment by Iamgoofball** [comment]
check the icondiffbot

**Review by tf-4 — CHANGES_REQUESTED** [review]
Needs pictures of in game

**Comment by theselfish** [comment]
Also, for the changelog imageadd is more accurate.

**Comment by cheapcents** [comment]
done

**Comment by desertmote** [comment]
That kneepad thing on the belts is going to clip with skirts. I personally also don't like more clutter i cant avoid having on my character's outfits

**Comment by cheapcents** [comment]
> That kneepad thing on the belts is going to clip with skirts. I personally also don't like more clutter i cant avoid having on my character's outfits

the kneepad thing has always existed

**Comment by desertmote** [comment]
i probably didnt know because its already clipping with my characters attire. i still do not see why a kneepad is included with a belt

**Comment by coffeecoffeecoffee** [comment]
I am not sure why belts need to give us shortstack-tier babymaking hips. I like the art, but scaling the edges of it back a pixel or two would be so, so nice. It reaches "up" to create depth that isn't there on the base character sprites, so it just looks like a really tall garment that goes up a person's torso some. please god i just want to see my outfits that're under the belt

**Comment by theselfish** [comment]
Did you change the in-hand sprites?

**Comment by ghost** [comment]
The Uniform Object sprites arent actually in any files, are those included in this PR?

**Comment by H0gberg** [comment]
I really like the sprites! But I think the current belt and this one is just a pixel or two too thick, but hey that's just my opinion. Either way great work!

**Comment by hugmeorelse** [comment]
a

**Comment by Gandalf2k15** [comment]
update from master and resolve conflicts

**Comment by cheapcents** [comment]
someone called lukaster42 has volunteered to remake the helmet sprites, please dont merge this until ive added his sprites here

**Comment by Gandalf2k15** [comment]
reopen as a new pr once it is done

**Pull request closed without merging**
