### PR TITLE
Tweaks and opens up Science on Icebox, adds new SciChem area

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Makes some small QoL changes to science, opens it up into a more publically accessible department, and adds a SciChem area.

lobby
Most noticeably, makes the science corridor publically accessible, letting people walk in and around deeper in science, to additional desks.

rnd
Adds the RnD console back to RnD, as well as a roundstart autolathe.

scichem
South of RnD is the new SciChem. Basically a slightly more reinforced chemistry, to be focused more on "chemical research" (read: making great big fuck off grenades), as well as providing robotics with the chems they need. Grenade stuff removed from chemistry roundstart.

robotics
Expands surgery in robotics, moves the fabs to a less space-consuming area, generally brings it in line with Michael's robotics changes on the oldbase. I did remove one of the mech chargers, because I wanted more space in surgery and honestly nobody ever uses both, even on the rare high-intensity rounds.

xenobio1
North of xenobiology. Added a desk and fridge for slime cores. Moved the xenobio consoles to be in line with each other so you actually have some vague level of interaction with your coworker.

xenobio2
South of xenobiology. Expanded the area for cytology, including a small pen so your blobbernauts don't go on a rampage (or at least a delayed one)

testinglab
Testing lab, all the way at the bottom. Moved nanites down here, giving them a monkey pen for testing whatever wacky shit they want _rather than doing it on the public cloud_. Also adds a drone dispenser so drone players can continue to ~~give admins headaches~~ repair the station.

## Why It's Good For The Game

One of the biggest problems in science is isolationism. They sit in their lab, ignore the RnD desk, and generally just ~~ERP~~ ~~powergame~~ do their own thing. Opening up science will do two things - it will encourage interaction as people don't have to go sit at the front desk that nobody checks for 20 minutes, ignoring the radio. It'll also hold scientists a little more accountable, as it's gonna be harder to sit in your lab accruing power if everyone can see what you're doing.

Various QoL improvements including but not limited to - RnD console in RnD, tier 2 canisters in toxins, the various things that Michael improved in robotics (roundstart posis, insuls), cytology actually having room to work rather than being crammed in the corner of xenobiology.

SciChem will give chemist antags a little more leeway, as destructive chems won't lead to sec unga rushing main chem instantly. Also lets them focus on plumbing and healing, as making grenades will *ideally* be the sole responsibility of SciChem - science has access to the testing lab after all, whereas chemists don't particularly have anywhere to test whatever they make.

## Changelog
:cl:
tweak: Various QoL changes within all areas of science.
tweak: Science is for the people - you can now enter science, with more desks for you to stand at waiting for scientists.
add: SciChem is here for production of totally scientific grenades and other dangerous substances, moving the focus away from chemistry-proper.
/:cl:

### CODE REVIEW

**Comment by LimblessLayabout** [comment]
These changes all look super-agreeable. I particularly enjoy the chem-research addition (with admittedly strong bias - I'mma park my ass in there _immediately_ )

**Comment by ShadeAware** [comment]
Don't forget to return the Circuit Omniprinter to Robotics, and replace the currently gimped one.

**Comment by ShadeAware** [comment]
also
image

**Comment by tf-4** [comment]
> also
> image
> 

Oop good catch.

**Comment by SpookyTheFox** [comment]
> 
> 
> Don't forget to return the Circuit Omniprinter to Robotics, and replace the currently gimped one.

This.

Currently engineering has the good imprinter. Robotics had it on the old base, not because they are better at building machines than engineers, but because they have a service counter, and are usually able to hand out boards. I don't mind making my own chemistry set in robotics, as long as the imprinter has the boards.

**Comment by RatFromTheJungle** [comment]
ok ill allow it because your char is very handsome

**Comment by atakiya** [comment]
ae

**Comment by Gandalf2k15** [comment]
Hello, feel free to open this again once you've started working on it!

**Pull request closed without merging**
