### PR TITLE
[MIRROR] Replaces the current, unreasonably long tram whiteship, with a shorter and more compact one

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/62585
--------------------

## About The Pull Request
As the title would imply, this replaces the current tram whiteship, which while a funny reference to the [REDACTED] event when the tram bugged out and killed everyone, is just way too long and especially when compared to the other ships, is massively larger.

image

(Imaged above is the map editor view of the new shuttle, which is a cool 13x27)

## Why It's Good For The Game
Greatly reduces the amount of things that has to be moved whenever someone uses the tram whiteship, while still mostly keeping the original reference.
The original was 13x41, and this new one is 13x27, just to give a better idea of how much it was cut down.

## Changelog

:cl:
qol: the whiteship of tram station has been made much shorter, allowing for less lag on movement and easier docking
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Wait what.

**Comment by Paxilmaniac** [comment]
did you delete the tram whiteship, lol?

**Comment by GoldenAlpharex** [comment]
> did you delete the tram whiteship, lol?

Not that I'm aware, lemme check.

**Comment by GoldenAlpharex** [comment]
I want to generate the MDB to see what happened.

**Comment by GoldenAlpharex** [comment]
Well, the map just had a stroke I guess.

**Comment by GoldenAlpharex** [comment]
> did you delete the tram whiteship, lol?

So, what happened is that we didn't merge https://github.com/Skyrat-SS13/Skyrat-tg/pull/9315 yet, so the mirror bot must've freaked out. Hah.

**Comment by ORCACommander** [comment]
All Stock /tg/ maps reset to upstream in https://github.com/Skyrat-SS13/Skyrat-tg/pull/9393

**Comment by ORCACommander** [comment]
should be safe to close, only a map file edit

**Pull request closed without merging**
