### PR TITLE
voidrap airlock access change

### PR DESCRIPTION
**Pull request by SpaceVampire**
## About The Pull Request

Edits the map to place down mapping helpers that better reflect the zones. It was a bit too heavy on the brig access, when that really should have only been the hallways leading over into the perma area. Now detectives can enter the main room and access the evidence lockers as intended on every other map. I also updated the courtroom door because it seemed like it was also using the wrong thing. 

## How This Contributes To The Skyrat Roleplay Experience

People being able to go proper place good.

## Changelog

:cl:
fix: VoidRaptor security made more accessible to the inquisitively inclined on their staff.

### CODE REVIEW

**Comment by Jolly-66** [comment]
Proof of testing?

**Comment by SpaceVampire** [comment]
> Proof of testing?

What do you want to see there? I could include an image showing what doors had their access updated, but there really isn't anything to test with it.

**Comment by YakumoChen** [comment]
Probably need to just remap the main brig sometime but I wouldn't know where to start with that. Some of the room placements are just goofy (looking at you interrogation)

**Comment by softcerv** [comment]
That is a very verbose title

**Comment by Zergspower** [comment]
> Probably need to just remap the main brig sometime but I wouldn't know where to start with that. Some of the room placements are just goofy (looking at you interrogation)

you need to show the changes functioning in game - e.g. map edit screenshots

**Comment by Jolly-66** [comment]
> you need to show the changes functioning in game - e.g. map edit screenshots

Map editor screenshots are not sufficient proof of testing.

**Comment by SpaceVampire** [comment]
> Map editor screenshots are not sufficient proof of testing.

Could you say what is sufficient proof of testing? I asked above what you wanted to see, and didn't really get an answer.

**Comment by Jolly-66** [comment]
You spawn in as a detective and then prove the doors function. Shrimple as.

**Comment by SpaceVampire** [comment]
> You spawn in as a detective and then prove the doors function. Shrimple as.

https://github.com/Skyrat-SS13/Skyrat-tg/assets/46720418/53aa23d2-6838-4d00-bee3-eb7911e79536

There you go!

**Review by Jolly-66 — DISMISSED** [review]
The sec changes are fine.

Revert the engineering changes. I don't agree with them at all.

**Comment by SpaceVampire** [comment]
> Revert the engineering changes. I don't agree with them at all.

I'll put the engineering changes in a separate PR so we can talk about it there.

**Comment by SpaceVampire** [comment]
Should be all ready for merge now.

**Review by GoldenAlpharex — APPROVED** [review]
Looks fine to me.

**Pull request merged**
