### PR TITLE
[MODULAR] NSS Journey Prison Overhaul

### PR DESCRIPTION
**Pull request by ForrestWick**
## About The Pull Request

The first in a small series of prison reworks I'm doing. Essentially, this changes the whole prison wing for NSS Journey and makes it a bit more like a proper prison. It's no longer a donut loop and instead has proper deadends and whatnot, as well as removes the curtains from cells. Instead, prisoners can go ERP in little hidden rooms. The pool is also gone and the communal showers are replacing it. It still retains the overall space and feel of current prison but without the more "luxury resort" aspect people complained about. Also they get a cargo bounty pad now

image

## Why It's Good For The Game

A lot of people complain that the prison is too much of a resort instead of a prison, so now the prisoners will have a bit less "luxury" and more of a proper prison feel. This should encourage a bit more proper prison RP as well as make sec players happy too.

## Changelog
:cl:
add: Overhauled the entire prison for NSS Journey to be more like a proper prison instead of a luxury resort; added a cargo bounty pad and console, removed private cells and made hidden ERP rooms instead.
/:cl:

### CODE REVIEW

**Comment by FlamingLily** [comment]
isolation shutters broked

**Comment by ForrestWick** [comment]
After seeing another project I did for this server that I spent weeks of communication, time, and effort on get overwritten in a single day with 0 player input or communication with me, I've decided to no longer contribute to this server.

**Comment by ForrestWick** [comment]
The decision was hasty. I'm going to communicate with Xyel on something first before I make a decision regarding this

**Comment by FlamingLily** [comment]
> image
> Carpet immediately makes this a 4 star semi-luxury hotel and isn't allowed in Skyrat prison. Prisoners should have titanium caltrops welded into the plating in their rooms, not carpet. I'm saving you a big headache here. (optional)

Nah, nah, this is isolation, it's like, padded flooring

**Pull request merged**
