### PR TITLE
[NONMODULAR] Adds a manual override to firelocks

### PR DESCRIPTION
**Pull request by FlamingLily**
## About The Pull Request
Title says it all.

## Why It's Good For The Game
Icebox.

But seriously, being trapped behind a firelock because of depressurization sucks, and as scummy as NT is lore-wise, they probably wouldn't skimp on a really cheap way to prevent deaths. 

## Changelog
:cl:
add: After repeated incidents on their "Icebox" line of standardized research stations, NanoTrasen has added a manual override lever to their emergency shutter designs!
add: Added flavour text when attempting to crowbar (or manual override) a welded firelock.
/:cl:

### CODE REVIEW

**Comment by FlamingLily** [comment]
oh uh if I should PR this upstream lemme know cuz I asked and got a "eh, should be fine down here"

**Comment by SpaceVampire** [comment]
Honestly, making it so you could open up firelock's using only your hands would be a better change. Make it so there is a delay of like 3-5 seconds, so that crowbars are still better, but you don't NEED to have one to avoid getting stuck. I feel like the internals boxes are getting pretty bloated already, and this is a better fix to the actual issue.

**Comment by FlamingLily** [comment]
> 
> 
> Honestly, making it so you could open up firelock's using only your hands would be a better change. Make it so there is a delay of like 3-5 seconds, so that crowbars are still better, but you don't NEED to have one to avoid getting stuck. I feel like the internals boxes are getting pretty bloated already, and this is a better fix to the actual issue.

mmmmmmmmmmmProbably!

Fuck if I know how to do it!

I'll see what I can do, maybe I can figure it out

**Comment by SpookyTheFox** [comment]
> 
> 
> > Honestly, making it so you could open up firelock's using only your hands would be a better change. Make it so there is a delay of like 3-5 seconds, so that crowbars are still better, but you don't NEED to have one to avoid getting stuck. I feel like the internals boxes are getting pretty bloated already, and this is a better fix to the actual issue.
> 
> mmmmmmmmmmmProbably!
> 
> Fuck if I know how to do it!
> 
> I'll see what I can do, maybe I can figure it out

Something to look at might be the set of two red airlocks coming off every door to the arrivals shuttle. If you attempt to open those with no power, it starts an action bar and your character will eventually push them open, without tools. If you could bring that same functionality to firelocks, that would be perfect.

**Comment by FlamingLily** [comment]
> 
> 
> > > Honestly, making it so you could open up firelock's using only your hands would be a better change. Make it so there is a delay of like 3-5 seconds, so that crowbars are still better, but you don't NEED to have one to avoid getting stuck. I feel like the internals boxes are getting pretty bloated already, and this is a better fix to the actual issue.
> > 
> > 
> > mmmmmmmmmmmProbably!
> > Fuck if I know how to do it!
> > I'll see what I can do, maybe I can figure it out
> 
> Something to look at might be the set of two red airlocks coming off every door to the arrivals shuttle. If you attempt to open those with no power, it starts an action bar and your character will eventually push them open, without tools. If you could bring that same functionality to firelocks, that would be perfect.

I FORGOT THAT WAS A THING, THANK YOU!

**Comment by FlamingLily** [comment]
I did it. I'm a  fucken genius.

also this still applies

> 
> oh uh if I should PR this upstream lemme know cuz I asked and got a "eh, should be fine down here"

**Comment by FlamingLily** [comment]
Actually I might go and ask upstream, just to be sure

**Comment by FlamingLily** [comment]
Okay, I asked and the 'resident atmos coder' said they'd rather not have it, so here we are!

I'm also suddenly getting anxious that there's a modular way to do this, and if so, please do tell me cause I am a dumb babby coder.

**Comment by FlamingLily** [comment]
Ok this is a learning experience, I'ma close this, go modularise it like I've been taught, and come back to it when it's ready!

**Comment by FlamingLily** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/4385

**Pull request closed without merging**
