### PR TITLE
[DRAFT] The Great GAGSification

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
**REPENT, SINNERS! FOR THE GAGS-TIME HAS COME!!**
Big ol' overhaul to lots of our modular outfits to make them both more customizable and cleaner, using a very fun system.
For the sake of not conflicting, I'll hold on moving the icons into the modular dmi until the very end, so any other clothing additions shouldnt cause massive issues.

To-Do:
- Hawaiian Shirts
- Flannels
- Formal Suits
<details>
<summary>IMPORTANT: find out how to have clean template-based .jsons without THIS happening</summary>

image
Being able to select ANY icon state also mentioned in the .json for preview. No actual effect, but its annoying
</details>
<details>
<summary>Conversion of our obsolete Polychromicc outfits</summary>

```
/obj/item/card/id/advanced/polychromic
/obj/item/clothing/head/turb
/obj/item/clothing/head/keffiyeh
/obj/item/clothing/head/hijab
/obj/item/clothing/head/polyflatc
/obj/item/clothing/head/flowerpin
/obj/item/clothing/mask/gas/polyclown 
/obj/item/clothing/neck/human_petcollar
/obj/item/clothing/suit/urban/polychromic
/obj/item/clothing/suit/duster/colorable
/obj/item/clothing/suit/toggle/peacoat
/obj/item/clothing/suit/toggle/jacket/cardigan
/obj/item/clothing/suit/jacket/leather/polychromic - Repathed to /obj/item/clothing/suit/jacket/leather/greyscale, Not Yet Complete
/obj/item/clothing/shoes/wraps/poly
/obj/item/clothing/under/misc/poly_kilt
/obj/item/clothing/suit/hooded/wintercoat/polychromic
/obj/item/clothing/head/hooded/winterhood/polychromic
/obj/item/clothing/neck/cloak/polychromic
/obj/item/clothing/neck/cloak/polychromic/veil
/obj/item/clothing/neck/cloak/polychromic/boat
/obj/item/clothing/neck/cloak/polychromic/shroud
/obj/item/clothing/neck/cloak/polychromic/rscloak
/obj/item/clothing/neck/cloak/polychromic/rscloak_cross
/obj/item/clothing/under/dress/skirt/polychromic
/obj/item/clothing/under/dress/skirt/polychromic/pleated
/obj/item/clothing/under/misc/poly_shirt 
/obj/item/clothing/under/misc/polyshorts
/obj/item/clothing/under/misc/polyjumpsuit
/obj/item/clothing/under/misc/poly_bottomless
/obj/item/clothing/under/misc/polysweater 
/obj/item/clothing/under/misc/poly_tanktop
/obj/item/clothing/under/misc/poly_tanktop/female
/obj/item/clothing/under/shorts/polychromic
/obj/item/clothing/under/shorts/polychromic/pantsu
```
</details>
- (Pairs with above) Rework /datum/map_template/ruin/space/skyrat/polychromicfacility to work with new non-poly items, as a reference to the old system but not requiring it to exist
- Outdated Sprites (Such as our custom prison jumpsuits, which can use GAGS now)
- Unimportant: color variant items (Fannypacks, (more here)) condensed into single loadout items?
- IMPORTANT: UPSTREAM AN EQUIVALENT FOR SCARVES/BANDANAS/(more here)? ((OPTIONAL, ~~upstream scary~~))
- To-Do: add more to this list

- FINAL: map changes
- FINAL: merge all icons into a centralized location (I'm still using beret.dmi, for christs sake)

Completed:
Move GAGS Beret config into the Customization module
<details><summary>Hoodies</summary>(https://gyazo.com/de68786c245a6d4bb3d559cf5470f45a) </details>
Protective/Min/Max/Supermax Prison Jumpsuits (No visual change)

## How This Contributes To The Skyrat Roleplay Experience
Cleaner icons, more customization, blahblahblahblahblah

## Changelog

:cl: Orion_the_Fox (add others here if it happens)
qol: Hoodies, Alt-Custody Prisoner Jumpsuits,(LIST ALL HERE) have been converted to GAGS grey-scaling system, along with our old Polychromic items as well! Enjoy the added customization and cleaner recoloring!
imageadd: added greyscale sprites for the above
imagedel: deleted outdated, duplicate, and old polychromic icons
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
bitch i literally gave you the free Palestine hat gagfiles

**Comment by ghost** [comment]
> 
> 
> bitch i literally gave you the free Palestine hat gagfiles

then i'll add them to this 4head
this is gonna cover quite a few more things dont worry;
(added yours to to-do list)

**Comment by CalamaBanana** [comment]
Can I sneak the Cardigan (/obj/item/clothing/suit/toggle/jacket/cardigan) on your list? It's wonky since the prefrework. It can't be colored in the loadout anymore right now, and spawns in as solid white. Though a spraycan does bring out the texture, I am not really sure what is broken with it.

**Comment by softcerv** [comment]
If you'd like something else to look into converting! https://github.com/Skyrat-SS13/Skyrat-tg/pull/5760

**Comment by CalamaBanana** [comment]
(Thanks for the Cardigan)
Not sure if it is out of scope, but it does feel like half the loadout menu is just precolored variants of something right now, that could be compressed into one colorable GAGS thing.

The ones jumping out are the "belt" category that consists of mostly different colors of the fannypack, "mask" has a lot of bandanas, and "neck" a lot of scarves. (At least the white scarf was colorable in the old menu, that button went missing with the prefrework, sadly.)

**Comment by ghost** [comment]
> 
> 
> (Thanks for the Cardigan) Not sure if it is out of scope, but it does feel like half the loadout menu is just precolored variants of something right now, that could be compressed into one colorable GAGS thing.
> 
> The ones jumping out are the "belt" category that consists of mostly different colors of the fannypack, "mask" has a lot of bandanas, and "neck" a lot of scarves. (At least the white scarf was colorable in the old menu, that button went missing with the prefrework, sadly.)

bandanas and scarves are something i wanna look into, but the main issue is: 'how much of this belongs upstream?'
so I'll add them to the list but have to do a collective upstream pass too before doing them here

I agree though that the pre-colored variants probably CAN be removed; though thats not up to me, people might hate having to find the specific color they want; if a maintainer approves the idea though I can cut lots of that stuff down

**Comment by CalamaBanana** [comment]
Yeah, agree. Though even if you do not end up removing the old ones, adding a GAGS-ready colorable version of them would be great. (I personally only use the scarf, tbf, old loadout menu allowed me to color the white one. That fixed purple is not my taste, yet I am too lazy to spraycan the white one every round)

**Comment by ghost** [comment]
im gonna break this up a bit more instead of all at once; plus i need to find out whats upstream and what isnt. dont worry, GAGS stuff will be done, just not this big of a scale cuz WEW

**Pull request closed without merging**
