### PR TITLE
YOU'RE A KID, YOU'RE A SQUID, YOU'RE A KID, YOU'RE A SQUID, YOU'RE A.. squidward..?

### PR DESCRIPTION
**Pull request by jinxynii**
2y399sywrop21

## About The Pull Request

 This PR adds the Squidpeople as a species into the game. What are they? They were a tg April Fools species that I think is pretty cool and should be a playable species for real. What do they do? They're Squids. They can't wear shoes, and they hate fried food. 

## Why It's Good For The Game

 More customization for players is always really nice. Also, I mean squids are like.. really cool too so like yeah.

## Changelog
:cl:
makes squid people a reality and not just a dream
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
Day 1 is going to be people attemping to make spongebob shitposts in SR

**Comment by Ziiro** [comment]
>from jinxynii:master

uh oh

**Comment by FlamingLily** [comment]
> 
> 
> > from jinxynii:master
> 
> uh oh

Jeez imagine using your master branch, ahaha what a silly mistake am I right fellas?

On a more serious note, this feels.... like, bad for the tone of the server.

`Skyrat-tg/squidpeople.dm`

Also

That feels.... against all contribution guidelines

**Comment by jinxynii** [comment]
> > > from jinxynii:master
> > 
> > 
> > uh oh
> 
> Jeez imagine using your master branch, ahaha what a silly mistake am I right fellas?
> 
> On a more serious note, this feels.... like, bad for the tone of the server.
> 
> `Skyrat-tg/squidpeople.dm`
> 
> Also
> 
> That feels.... against all contribution guidelines

Actually, it's not my actual master branch, it's a copied folder within the actual master branch.

**Comment by unit0016** [comment]
Bad PR. All files are within the root folder, no newline at the end of the .dm, and it's not integrated with the customization module at all. Not to mention it's jarring as fuck to have 18 bald ass squidwards running around compared to the rest of the server.

**Comment by Gandalf2k15** [comment]
If you actually wanna make an attempt at this, please do it properly.

**Pull request closed without merging**
