### PR TITLE
Adds Blueshield/Captain/Chief engineer to veteran crew - AWARENESS PR

### PR DESCRIPTION
**Pull request by Gandalf2k15**
# This is a prospective PR, take it with a grain of salt. 

To apply for this role, see: https://forum.skyrat13.tk/viewforum.php?f=78

## Changelog
:cl:
add: Blueshield, Captain and Chief Engineer now require you to be a veteran crew.
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
nooooooooooooooooo

**Comment by Gandalf2k15** [comment]
image

**Comment by Guidesu** [comment]
literally NOO i am main CE RIP

**Comment by FlamingLily** [comment]
Blueshield yes, for the same reasons as vanguard, I don't think CE should, Captain I'm neutral on

**Comment by Guidesu** [comment]
WHY CE THO I PLAYED SO MUCH ENGINEER TO BECOME CE

**Comment by Guidesu** [comment]
I Crying... but things needs to be made i guess..

**Comment by Gandalf2k15** [comment]
No spam.

**Comment by Arctaisia** [comment]
Cap seems fine to me, makes sense, same with Blueshield, and I can get why CE would be whitelisted, but I feel we should make heads more consistent if we do. I know I'll be disliked for this, but; I'm starting to feel alot of the heads need a whitelist, much like Vorecode has, because lately the RP levels and competency of some heads of staff have been abysmal, but I support this PR, weh!

**Comment by FlamingLily** [comment]
> Blueshield yes, for the same reasons as vanguard, I don't think CE should, Captain I'm neutral on

Just to elaborate, for CE, I can very much see the basis behind it, that it's to stop funny meme SM setups that instantly delam and kill half the station, but the problem there is people will still do those setups if they're CE or not

And as for Captain, I can understand it comes from a similar place as bs, they they're not sec and shouldn't be being sec, but at the same time, it's a very important role and I'm not entirely sure they should be restricted

But yes, I 100% agree with making the Blueshield a veteran role

**Comment by FlamingLily** [comment]
> Cap seems fine to me, makes sense, same with Blueshield, and I can get why CE would be whitelisted, but I feel we should make heads more consistent if we do. I know I'll be disliked for this, but; I'm starting to feel alot of the heads need a whitelist, much like Vorecode has, because lately the RP levels and competency of some heads of staff have been abysmal, but I support this PR, weh!

I honestly agree with the sentiment, but I don't think this solution is the right course of action. Namely because no one plays heads. Like, ever. At all. it's been picking up lately, but I think making all heads veteran will only compound the issue.

**Comment by Gandalf2k15** [comment]
> > Blueshield yes, for the same reasons as vanguard, I don't think CE should, Captain I'm neutral on
> 
> Just to elaborate, for CE, I can very much see the basis behind it, that it's to stop funny meme SM setups that instantly delam and kill half the station, but the problem there is people will still do those setups if they're CE or not
> 
> And as for Captain, I can understand it comes from a similar place as bs, they they're not sec and shouldn't be being sec, but at the same time, it's a very important role and I'm not entirely sure they should be restricted
> 
> But yes, I 100% agree with making the Blueshield a veteran role

No captain is better than a shit captain.

**Comment by FlamingLily** [comment]
> No captain is better than a shit captain.

I disagree, to be honest. Also, acting captaincy will still be a thing

**Comment by FlamingLily** [comment]
I feel that all this is going to do for captains is make captain a special rare role and I don't feel that that's something we should do to core gameplay roles like the captain or CE

**Comment by SpaceVampire** [comment]
Just to give my two cents.
I only support Blueshield being added.
Just because I feel like it is in a poor place in general.
Like, on the BoxStation map the office is directly outside of brig.
Pretty much asking them to go around and Redshield people.
Captain and CE are much more core to the actual game.
The issue with stupid engine setups is something that normal engis can already do.

**Comment by NullDagaf** [comment]
Blueshield and Captain I can understand, but why chief engineer? And if so, why not more heads? I don't know about you, but I don't exactly want to have an incompetent, say, head of personel.

**Comment by YakumoChen** [comment]
> No captain is better than a shit captain.

While true, admins frequently do nothing to punish shit captains, even from an IC context, even with other heads of staff begging for Centcom punish them, which does not help matters and would do little to mitigate the problem if we whitelisted them.

I feel the quality of heads of staff is simply a product of the roleplaying game rather than something we should heavily restrict and can even make rounds more interesting, assuming admins actually stepped in or captains actually put their foot down

 If the heads are being shit, administration should do more to actually remedy this in-round. From the perspective of someone who plays captain infrequently, admins do absolutely nothing to help me deal with shit heads of staff until it is far too late to do so (usually the answer is 'demote them yourself, you're the captain). As someone who frequently plays heads of staff, admins will frequently sit idly by while I beg for a shit captain to be demoted, or will actively impede me if I attempt to do so myself.

**Comment by FlamingLily** [comment]
Tbh the solution to shit heads isn't to restrict them, it's to introduce accountability, and I think we should do that in the form of a dedicated role.

**Comment by Weblure** [comment]
As a veteran crew, I strongly disapprove of this.

**Comment by Vizoplez** [comment]
As someone who has
image

this many hours ingame,

no.

It wont fix any of the issues we have.

**Comment by Deek-Za** [comment]
It's a bad move.  It's punishing the many for the mistakes of the few.  
Punish players who perform badly in these roles instead of restricting good people. It's only going to stifle newcomers interest in the server when they see how much is required to unlock jobs that are much more easily obtained on other servers.

**Comment by hugmeorelse** [comment]
We don't have the playerbase yet for this. Blueshield, I think is acceptable for this, as it's an optional role. However, captain and chief engineer should not be considered, until we have 10% to 20% of the active playerbase integrated into the Veteran Crew system.

**Also, this PR is just up, just for the sake of being up. It's not guaranteed to be a sure thing, so panicking over this is moot.**

**Pull request closed without merging**
