### PR TITLE
[MDB IGNORE] Rough draft: Flandstation

### PR DESCRIPTION
**Pull request by Mintybea**
## About The Pull Request
This is a rough draft from my currently ongoing plan to port Flandstation from Beestation to Skyrat. Flandstation is an unconventional station with a vague (and I mean _vague_) resemblance to birdshot. Most of the station post-conversion is 1:1 with its beestation counterpart, but some departments (science, medical, and bridge) have had major changes to be better suited for Skyrat's experience.

## How This Contributes To The Skyrat Roleplay Experience
A large complaint from other maps is that other maps tend to not have a lot going for them. Flandstation, being both unconventional and having a vast maintenance system, provides a lot of opportunities for player interaction and gimmicks. Antagonists also have the benefit of more hiding areas and places to do their dirty work.

## Proof of Testing

This rough draft was submitted for Jolly and other maptainers to review

### CODE REVIEW

**Review by Jolly-66 — COMMENTED** [review]
I still have Blueshift to get through before I can properly review this.

However, you're missing the station .json file. Please look at the other .json files to understand how they're written. If you need help please reach out to me.

Secondly, you have linters issues. Please investigate them.

**Comment by Mintybea** [comment]
Gonna work through all these errors, once that's done I'll get back to designing the map.
I fixed all the misplaced S', so now it's time to fix everything else.

**Comment by Mintybea** [comment]
All updates past this point now will be for getting the map to a second draft.

**Comment by Mintybea** [comment]
Just leaving this for any reviewers
Very close to graduating college, also going through some mental health stuff, I'm gonna be going on a short hiatus while I work through all of this, then once that is done I'm gonna clean the place up.

**Comment by Mintybea** [comment]
WE ARE SO BACK

**Comment by Mintybea** [comment]
I'm requesting a review solely on the basis of wanting to find any glaring issues before moving to finish the map

**Comment by W4rd3nn** [comment]
*krakz kunuckles* time 2 bully Kirith

General review from my POV :3 

<details>
<summary>Find a sprite for the map sign or remove</summary>

image

</details>

**This is gonna be PAIN but**
<details>
<summary>Please use directional subtypes for wallmounts. Fire alarms, air alarms, intercoms, etc.</summary>

image

</details>

**This is best achieved by searching for the objects and just going thru them one by one and using the replace tool. Shouldn't take more than an hour or so.**


<details>
<summary>Access helper is on the wrong air alarm. I would also just move the alarm into the airlock.</summary>

image

</details>

<details>
<summary>Set filter next to me's filter_type to list(/datum/gas/nitrogen)</summary>

image

</details>

**Engine Also needs a delam stopper and a delam counter**

<details>
<summary>Your SM is hotwired. Make sure power goes to SMES's FIRST before anywhere else</summary>

image

</details>


**Your Centcomm Ferry (the one ERTs arrive on) does not work. Copy the docking helper from voidraptor**

**Your whiteship is not defined. Look at my PR on where to put shuttle definitions**


<details>
<summary>This is not the proper area to use. Make a new one. Make sure it's a area/station subtype, not area/centcomm</summary>

image

</details>


<details>
<summary>Cryogenics is ??? also funny window firealarm</summary>

image

</details>


<details>
<summary>Backwards sink and also remove disk compartment thing</summary>

image

</details>

<details>
<summary>Put da moonlight greatsword back NOW!!! >:(</summary>

image

</details>


Just some stuff I noticed. Also take with a grain of salt since i'm not a maptainer :3 

Also the automapper ignored this map properly when I forked it. Try changing the map to a different one, clicking "Reboot World", fully loading the new map, then switching back to Fland.

Oh also remove those vs files. slnx.sqlite and VSWorkspaceState.json

**Comment by Mintybea** [comment]
Hey there!
Considering Skyrat's dead now, there is no reason to keep this PR open. I'm grabbing what I have of it and am going to continue work on Nova Sector.

**Pull request closed without merging**
