### PR TITLE
Retires the Vore pref, replaces it with a Hypno pref

### PR DESCRIPTION
**Pull request by desertmote**
## About The Pull Request

It simply removes one preference and replaces it with another, the hypnotization preference.
It has the options:

- Always
- Gameplay Only*
- ERP Only
- Never

*This means being brainwashed ala hypnoflash or surgery, and getting given commands like 'defend me with your life' or 'subdue the Captain'.

## How This Contributes To The Skyrat Roleplay Experience

We haven't had vore content OR mechanics in years, so I'm retiring the preference for one that I think has been gaining relevance.
It is easy to still figure out someone's preference for vore via LOOC, or an f-list link in their OOC.

I think the hypnotization preference is a better suit because it exists as a mechanic in our core traitor gameplay, and recently it has been made more accessible outside of gameplay with the hypno NIF.
While it may share similarities with the NC preference, I still think this separated preference existing is a better fit. It can lead to more certainty when an instigator be it tot or ERPer wants to play with brainwashing commands.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
dreamseeker_Y7HmnuJrB6

</details>

## Changelog
:cl:
del: The vore ERP preference has been retired.
add: In its place a new ERP preference has been added, the hypnotization preference.
/:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
Vore: Yes - Pred

**Comment by Nerev4r** [comment]
This stuff is surprisingly accessible nowadays (thru the NIFsoft and Hypno Goggles) and there's been more people around with it as kind of a central theme. I'd like this.

**Comment by Zergspower** [comment]
i gotta admit the hypno NIF is a strong RP tool compared to clunk goggles

**Comment by lessthnthree** [comment]
Hypno pref vores vore pref

**Comment by tf-4** [comment]
I mentioned removing vore prefs recently but was shot down, just as a forewarning.

**Comment by StrangeWeirdKitten** [comment]
To be completely honest, with the gameplay potential. The Hypno preference would be much better suited as a quick look if they want to brainwash someone, interrogation chamber them, hypno flash, etc. It opens up much better RP versus the vore pref which realistically has zero gameplay mechanics.

**Comment by Cyprex** [comment]
Hypno pref sure I guess, but removing vore? Why? It's a popular kink that is very divisive similar, just keep it in there?

**Comment by Nerev4r** [comment]
> Hypno pref sure I guess, but removing vore? Why? It's a popular kink that is very divisive similar, just keep it in there?

Vore isn't mechanically possible.
Hypno is as mechanically possible as it's ever been.

**Comment by Cyprex** [comment]
For reference Bubber is currently commissioning/bountying vore. Skyrat might grab this as well.

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
I don't think we should remove that pref, it isn't really harmful for it to be there, it just helps people looking for that, to know who to ask, because I'm pretty sure it's not something you necessarily want to be asked if you have it set to No normally.

**Comment by GoldenAlpharex** [comment]
I'm not against an hypno pref, but I don't think that it needs to be related to mechanics either. Not being targetable by hypno flashes and the likes sounds more like an antag-related pref, a-la Opt-In, and not something that should be handled by ERP prefs.

**Comment by StrangeWeirdKitten** [comment]
> I'm not against a hypno pref, but I don't think that it needs to be related to mechanics either. Not being targetable by hypno flashes and the likes sounds more like an antag-related pref, a-la Opt-In, and not something that should be handled by ERP prefs.

I've been running this PR as an early test on bubber, and I'd have to come to an agreement regarding this. There shouldn't be a 100 percent opt-out on getting targetted by something like brainwashing. There are legitimate mechanical uses, and if it's kept non-sexual, people shouldn't argue that you're *technically* pref-breaking them. (Though I've yet to run into this) Realistically if it's a preference, it should just be kept to hypnosis-related stuff that isn't exactly Mr. Bad syndicate brainwashing you.

**Comment by desertmote** [comment]
This'll be something I'll revisit once my TGUI skill improves. I know what I want to do with it, (avoiding the clutter brought by having multiple ERP prefs), but I don't yet know how.

**Pull request closed without merging**
