### PR TITLE
Fixes disabler SMG having 20x more shots and remove energy weapons cell redefines

### PR DESCRIPTION
**Pull request by Iajret**
## About The Pull Request
Disabler SMG got 800 shots instead of 40. Why? https://github.com/Skyrat-SS13/Skyrat-tg/pull/8524/ changed disablers to have 20k energy cell (probably to offset the ability to swap said cells) then https://github.com/Skyrat-SS13/Skyrat-tg/pull/9638 removed the ability to change cells, but havent removed increased power capacity and increased power cost for firing so it was unnoticed by everyone (except when smoothbore disabler was introduced). Also removed redefines for every energy weapon introduced in https://github.com/Skyrat-SS13/Skyrat-tg/pull/1346 because they are too unnecessary and nonmodular.

## How This Contributes To The Skyrat Roleplay Experience
Fixes bug, eases life for maintainers a bit (probably).

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  smg uses about 2% charge for firing

image

and disabler still uses 5%

image

also i checked smoothbore and it uses 100%, just trust me, i have forgotten to screenshot it.
</details>

## Changelog

:cl:
fix: fixed new disabler smg having 20x more shots
/:cl:

### CODE REVIEW

**Comment by Iajret** [comment]
also, https://github.com/Skyrat-SS13/Skyrat-tg/pull/1346 changed every laser weapon to have standard cell, which they already have in their basetype, so i could remove them too while im at it.

**Comment by lessthnthree** [comment]
> also, #1346 changed every laser weapon to have standard cell, which they already have in their basetype, so i could remove them too while im at it.

Are you including that in this PR?

**Comment by Iajret** [comment]
Only if you want me to

**Comment by vinylspiders** [comment]
> Only if you want me to

Feel free, or make it a separate PR if you want the extra gbp

**Review by vinylspiders — APPROVED** [review]

**Pull request merged**
