### PR TITLE
Avoids ragnarok by fixing the single most devastating typo to ever exist in skyrat's history

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

Title. Gives the female [FUN BITS] the correct name.

## How This Contributes To The Skyrat Roleplay Experience

I'm shaking in my seat right now. I can't believe this went overlooked for so long. Im seriously shaking and crying rn

To be serious, though, this is a very common misconception. If you look at the sprite yourself, its pretty clear this isnt the [REPLACED FUN BIT]. The [REPLACED FUN BIT] is actually a PART of the [NEW FUN BIT], specifically, a tube within it. 

It's good to inform people of the difference, since some people dont even know what the [NEW FUN BIT] is.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
i literally cant. not on github
</details>

## Changelog

:cl:
spellcheck: The female [FUN BITS] has been renamed.
/:cl:

### CODE REVIEW

**Review by GoldenAlpharex — COMMENTED** [review]
I'm not sure if this is a good idea, considering it makes it less coherent with its typepath, and then everywhere else in the game where it's named the previous name you're changing away from.

**Comment by nikothedude** [comment]
> I'm not sure if this is a good idea, considering it makes it less coherent with its typepath, and then everywhere else in the game where it's named the previous name you're changing away from.

is this a challenge to repath and redefine everything? damn well might im driven by spite

**Comment by vinylspiders** [comment]
I think you're reading just a little bit too much into this. What's visible in the sprite is just that. Yes you aren't technically seeing the rest of it, but that doesn't mean it's not there...

I think the intent was originally to refer to it as a whole. Which in everyday vernacular, people tend to use the current naming.

Doesn't really seem worth it to me for a technicality, tbh, given how much has to be repathed.

**Comment by vinylspiders** [comment]
If anything, you could make an alternate name for the visible portion for examine purposes, I guess?

**Comment by nikothedude** [comment]
yeah this h onestly doesnt matter that much lmao, i dont really care

not like this is actually ragnarok. or is it? we'll see

**Pull request closed without merging**
