### PR TITLE
[MIRROR] Removed Deprecated Config Options from game_options.txt

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/61283
--------------------

## About The Pull Request
A Whole bunch of config flags were left behind in game options when game modes were removed and replaced soly with dynamic. whenever enabled they were throwing errors into the game logs wasting hdd space and wasting init time.

```
[2021-09-07 16:25:58.005] Running /tg/ revision: 2021-09-07
 - origin/master: ab0c5ee1935728645f95d6791ba7f1720ec1cfc6
[2021-09-07 16:25:58.011] Loading config file config.txt...
[2021-09-07 16:25:58.013] Loading config file game_options.txt...
[2021-09-07 16:25:58.015] Failed to validate setting "TRAITOR 5" for probability
[2021-09-07 16:25:58.016] Failed to validate setting "TRAITORBRO 2" for probability
[2021-09-07 16:25:58.017] Failed to validate setting "TRAITORCHAN 4" for probability
[2021-09-07 16:25:58.020] Failed to validate setting "INTERNAL_AFFAIRS 3" for probability
[2021-09-07 16:25:58.022] Failed to validate setting "NUCLEAR 2" for probability
[2021-09-07 16:25:58.025] Failed to validate setting "REVOLUTION 2" for probability
[2021-09-07 16:25:58.027] Failed to validate setting "CULT 2" for probability
[2021-09-07 16:25:58.028] Failed to validate setting "CHANGELING 2" for probability
[2021-09-07 16:25:58.031] Failed to validate setting "WIZARD 4" for probability
[2021-09-07 16:25:58.033] Failed to validate setting "MONKEY 0" for probability
[2021-09-07 16:25:58.035] Failed to validate setting "METEOR 0" for probability
[2021-09-07 16:25:58.038] Failed to validate setting "EXTENDED 0" for probability
[2021-09-07 16:25:58.040] Failed to validate setting "SECRET_EXTENDED 0" for probability
[2021-09-07 16:25:58.042] Failed to validate setting "CLOWNOPS 0" for probability
[2021-09-07 16:25:58.044] Failed to validate setting "SANDBOX 0" for probability
[2021-09-07 16:25:58.047] Unknown setting in configuration: 'continuous'
[2021-09-07 16:25:58.049] Unknown setting in configuration: 'continuous'
[2021-09-07 16:25:58.050] Unknown setting in configuration: 'continuous'
[2021-09-07 16:25:58.053] Unknown setting in configuration: 'continuous'
[2021-09-07 16:25:58.055] Unknown setting in configuration: 'continuous'
[2021-09-07 16:25:58.057] Unknown setting in configuration: 'continuous'
[2021-09-07 16:25:58.059] Unknown setting in configuration: 'continuous'
[2021-09-07 16:25:58.062] Unknown setting in configuration: 'continuous'
[2021-09-07 16:25:58.063] Unknown setting in configuration: 'continuous'
[2021-09-07 16:25:58.065] Unknown setting in configuration: 'continuous'
[2021-09-07 16:25:58.068] Unknown setting in configuration: 'midround_antag'
[2021-09-07 16:25:58.069] Unknown setting in configuration: 'midround_antag'
[2021-09-07 16:25:58.071] Unknown setting in configuration: 'midround_antag'
[2021-09-07 16:25:58.074] Unknown setting in configuration: 'midround_antag'
[2021-09-07 16:25:58.076] Unknown setting in configuration: 'midround_antag'
[2021-09-07 16:25:58.078] Unknown setting in configuration: 'midround_antag'
[2021-09-07 16:25:58.081] Unknown setting in configuration: 'max_tickets_per_roll'
[2021-09-07 16:25:58.084] Unknown setting in configuration: 'midround_antag_time_check'
[2021-09-07 16:25:58.086] Unknown setting in configuration: 'midround_antag_life_check'
[2021-09-07 16:25:58.089] Loading config file dbconfig.txt...
[2021-09-07 16:25:58.091] Loading config file comms.txt...
[2021-09-07 16:25:58.095] Loading config file resources.txt...
[2021-09-07 16:25:58.097] Loading config file interviews.txt...
[2021-09-07 16:25:58.101] Loading config file maps.txt...
[2021-09-07 16:25:58.106] Loading config file in_character_filter.txt...
[2021-09-07 16:25:58.171] SQL: Database is not enabled in configuration.
[2021-09-07 16:40:31.681] Running /tg/ revision: 2021-09-07
 - origin/master: ab0c5ee1935728645f95d6791ba7f1720ec1cfc6
[2021-09-07 16:40:31.688] Loading config file config.txt...
[2021-09-07 16:40:31.691] Loading config file game_options.txt...
[2021-09-07 16:40:31.695] Failed to validate setting "TRAITOR 0" for min_pop
[2021-09-07 16:40:31.697] Failed to validate setting "TRAITOR -1" for max_pop
[2021-09-07 16:40:31.699] Failed to validate setting "TRAITORBRO 0" for min_pop
[2021-09-07 16:40:31.700] Failed to validate setting "TRAITORBRO -1" for max_pop
[2021-09-07 16:40:31.702] Failed to validate setting "TRAITORCHAN 15" for min_pop
[2021-09-07 16:40:31.704] Failed to validate setting "TRAITORCHAN -1" for max_pop
[2021-09-07 16:40:31.706] Failed to validate setting "DOUBLE_AGENTS 25" for min_pop
[2021-09-07 16:40:31.707] Failed to validate setting "DOUBLE_AGENTS -1" for max_pop
[2021-09-07 16:40:31.708] Failed to validate setting "NUCLEAR 0" for min_pop
[2021-09-07 16:40:31.710] Failed to validate setting "NUCLEAR -1" for max_pop
[2021-09-07 16:40:31.711] Failed to validate setting "REVOLUTION 20" for min_pop
[2021-09-07 16:40:31.713] Failed to validate setting "REVOLUTION -1" for max_pop
[2021-09-07 16:40:31.715] Failed to validate setting "CULT 24" for min_pop
[2021-09-07 16:40:31.717] Failed to validate setting "CULT -1" for max_pop
[2021-09-07 16:40:31.718] Failed to validate setting "CHANGELING 15" for min_pop
[2021-09-07 16:40:31.720] Failed to validate setting "CHANGELING -1" for max_pop
[2021-09-07 16:40:31.721] Failed to validate setting "WIZARD 20" for min_pop
[2021-09-07 16:40:31.723] Failed to validate setting "WIZARD -1" for max_pop
[2021-09-07 16:40:31.724] Failed to validate setting "MONKEY 20" for min_pop
[2021-09-07 16:40:31.726] Failed to validate setting "MONKEY -1" for max_pop
[2021-09-07 16:40:31.727] Failed to validate setting "METEOR 0" for min_pop
[2021-09-07 16:40:31.729] Failed to validate setting "METEOR -1" for max_pop
[2021-09-07 16:40:31.730] Failed to validate setting "EXTENDED 0" for min_pop
[2021-09-07 16:40:31.732] Failed to validate setting "EXTENDED -1" for max_pop
[2021-09-07 16:40:31.734] Unknown setting in configuration: 'show_game_type_odds'
[2021-09-07 16:40:31.738] Loading config file dbconfig.txt...
[2021-09-07 16:40:31.740] Loading config file comms.txt...
[2021-09-07 16:40:31.742] Loading config file resources.txt...
[2021-09-07 16:40:31.744] Loading config file interviews.txt...
[2021-09-07 16:40:31.748] Loading config file maps.txt...
[2021-09-07 16:40:31.752] Loading config file in_character_filter.txt...
[2021-09-07 16:40:31.818] SQL: Database is not enabled in configuration.
```

## Why It's Good For The Game

Increases maintainability of the config files

## Changelog

:cl:
fix: fixed as slew of failed to validate config setting errors
del: Removed deprecated config flags
server: game_options.txt has been updated
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
@Gandalf2k15 requires possibly to scrub that off of the config server-side too.

**Comment by ORCACommander** [comment]
i thought @Useroth managed the server configs...

**Comment by GoldenAlpharex** [comment]
> i thought @Useroth managed the server configs...

Yes and no, but Xyel does the Dynamic configs.

**Comment by GoldenAlpharex** [comment]
> > i thought @Useroth managed the server configs...
> 
> Yes and no, but Xyel does the Dynamic configs.

I'm an idiot this isn't the PR I thought it was.

**Pull request merged**
