### PR TITLE
Culls the big uniform.dmi master files (part 1)

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
As you can probably guess from all my past PRs trying to cut this big-ass file apart into TG-esque icon standards, I hate uniform.dmi.
This is a bit of rage against it. Just trimming some of the stuff I've done, the stuff I'll never do, and the stuff I hate (OVER HALF OF THE OBJECT .dmi WAS 4-DIRECTION STATES. ITS AN OBJECT. ITS 1 DIRECTION. I HAD TO CLICK THROUGH EVERY SINGLE ONE TO CHANGE IT TO 1 DIRECTION.)
I'd say "hur dur icon freeze" but dont have the authority, just gotta hope this is merged before anyone starts dumping more icons into that hellish .dmi

## How This Contributes To The Skyrat Roleplay Experience
Its impossible to read these files. I'm trying to fix it. It'll take a while, but this is a sign of progress.

## Changelog

:cl:
imagedel: deleted LOTS of hopefully unused uniform icons. Ping @orion_the_fox#1915 in a public dev channel if any sprite issues occur.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Opening this early so I can mooch off CI to see if I remove any used icon_states :)
At least, I THINK we have a test for that. I remember it somewhere, maybe we didnt take it..

**Comment by ghost** [comment]
NOOO [IT ](https://github.com/tgstation/tgstation/pull/64403) WAS NEVER MERGED DARN
Testmerge it is

**Comment by ghost** [comment]
I think this PR killed Icondiffbot2
As such, I think its ready to open :)

**Comment by AffectedArc07** [comment]
Ignore the IDB2 fail.

PR is still fine.

**Pull request merged**
