### PR TITLE
Pride Pins Resprite - Double Modular

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

image

(screenshot looks a bit wacky because of stretch to fit ignore it)

FIRST PR OF PRIDE MONTH HAH (going by AEST +10)

Resprites Pride Pins modularly, and adds mlm/gay, genderqueer, genderfluid, and aromatic.

"wahh it's a override" well i got permission and they look good so like.

I should have a bigger pride PR coming up later in the month, probably involving actual flags.

## How This Contributes To The Skyrat Roleplay Experience

uhh. pride good :). give players more options, and it's pride month so.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

wowie i already put in a DIFFERENT part so weird!!

</details>

## Changelog

:cl: axietheaxolotl / viro
image: brand new pride pin sprites! Also adds a couple more options: mlm/gay, genderqueer, genderfluid, and aromatic
/:cl:

### CODE REVIEW

**Review by Ebin-Halcyon — APPROVED** [review]
Gayboy.

Freeze exempt or smthn.

**Comment by Elli-Skala** [comment]
The object looks more rectangular but the on mob sprite is still a circle?

**Comment by ghost** [comment]
This was denied on TG (https://github.com/tgstation/tgstation/pull/75041) as the sprites appear disproportionately big, some have confusing perspective (mainly the intersex one), and "look like rugs and not pins and **clash with the style of literally everything else**". They're entirely unchanged from that as well, and the points still stand honestly.
I strongly urge that you rework them to account for the reviews and try again on TG. They liked the concept, and would have likely gone through with merging if changes had been addressed rather than closing the PR.

**Comment by desertmote** [comment]
the scale doesnt bother me. there is item code in the game to downscale items on the floor by a %, (and is fullsize in hands) maybe look into that though

**Pull request merged**
