### PR TITLE
lets roboticists wear mech suits in loadout (yeah its fucking modular i guess, its just a loadout addition)

### PR DESCRIPTION
**Pull request by CandleJaxx**
## About The Pull Request

adds the mech suit to roboticist locked loadout gear

normally its only accessable thru contraband for some reason (it's literally a costume) no armor, etc, just a modifiable fit

## How This Contributes To The Skyrat Roleplay Experience
free clothes baybeee

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
Screenshot_001
Screenshot_002
Screenshot_003

</details>

## Changelog

:cl:
add: roboticists can now wear more clothing? yeah
/:cl:

### CODE REVIEW

**Comment by W4rd3nn** [comment]
Shinji get in the fucking robot

**Comment by YakumoChen** [comment]
Add the other two mech suits

**Comment by HoodMilk** [comment]
The other two mech suits are just alt-click reskins of the original suit, they aren't unique suits anymore.

**Comment by CandleJaxx** [comment]
> Add the other two mech suits

yeah it's an alt click reskin version- do try to check the relevant code before commenting on changes please x

**Comment by burgerenergy** [comment]
this probably could go without being joblocked. netrunners might like the drip too, or any miners that go that route like masochists.

**Review by vinylspiders — APPROVED** [review]

**Pull request merged**
