### PR TITLE
Changes the security channel colours for tgui

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request

Security doesn't seem to be able to listen to the radio well, at all, chronically. I'm wagering it being that half the messages that can ever show up share the same colour - red. Let's change it to something unique, like blue-white, like our security is right now. 

## Dark Mode
dreamseeker_mpSA39j1Cy

## Light Mode
dreamseeker_KR8Z7tQLQr

I'm also considering the inverse of black and white on dark and light modes, respectively. 

## How This Contributes To The Skyrat Roleplay Experience

Readability improvement?

## Changelog

:cl:
qol: Changes the security channel colour. 
/:cl:

### CODE REVIEW

**Comment by desertmote** [comment]
We tried this before, it didn't work. (IMO, but it got changed back for a reason (probably))

**Comment by nevimer** [comment]
also consider...
dreamseeker_GIhHs1gww4
dreamseeker_BlzJjN44cf

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
I'm a fan of cyan usually, but it really doesn't work well in this scenario.

Changing the color of their radio frequency won't change whether or not they pay attention to it, if they're not paying attention to it as is, they won't pay more attention to it if the color is different.

Definitely a "no" from me.

**Comment by nevimer** [comment]
> 



> I'm a fan of cyan usually, but it really doesn't work well in this scenario.
> 
> Changing the color of their radio frequency won't change whether or not they pay attention to it, if they're not paying attention to it as is, they won't pay more attention to it if the color is different.
> 
> Definitely a "no" from me.

The issue is nearly every message in the game shares the same colour as security comms. Something has to change, cause I find it's very easy to pay attention to engi comms or medical comms, but NOT security comms.

**Comment by nevimer** [comment]
dreamseeker_hxegSFR5dz

Spot the security comms.

dreamseeker_rRdkCyJCbk

**Comment by nevimer** [comment]
Honestly, we need to have a conversation about the absolute mess that is the chat box. It's impossibly cluttered with giant red meme messages that are largely irrelevant, and make the channels that are not an eye catching colour - in fact sharing the same colour- red, impossible to notice.

**Comment by GoldenAlpharex** [comment]
If you find Security to be hard to spot, just add `[Security]` to your highlight filter and they'll get highlighted. Simple as that, really.

None of the colors you proposed fit security as-is, however.

**Comment by YakumoChen** [comment]
I have no trouble spotting security channels and I have hundreds of hours in the role.

Cyan looks noticably ugly and nonsensical for the department, the green-blue on dark clashes with [Centcom] and is equally bad.

White / Black isn't a colour, sorry, and just is confusing.

This would be something to take upstream, and I doubt they're going to agree any more.

**Comment by twilightwanderer** [comment]
I've been playing the Skyrat build for over a year. Still can't understand why the security department has such a dislike for all things red.

**Comment by TwinIndifferent** [comment]
> I've been playing the Skyrat build for over a year. Still can't understand why the security department has such a dislike for all things red.

Love for tacticool, I guess. Or _someone special_ hates it and requests removing all the red that was that special grain sec had from SS13 aestetics...

Imo changing color of comms for sec won't help with barely seen text. The major problem is amount of text clutter you must scan with your eyes in middle of combat, not the color. Might creating spaces between combat logs and normal chat could help?

**Comment by YakumoChen** [comment]
You don't even need to look at the chat log during combat most of the time, TGcode actually has decent enough design almost everything important is conveyed through visuals or sounds already.

**Comment by nevimer** [comment]
> You don't even need to look at the chat log during combat most of the time, TGcode actually has decent enough design almost everything important is conveyed through visuals or sounds already.

You should be communicating and listening to the radio no matter the job- just security has a very hard time doing so. You need to say the same thing to people multiple times, and you still get people asking you something you just said. Why? A variety of reasons, but this targets one. Too often security screams for help, or lone wolfs, and receives no backup or anything. Then players go "where is X?" 30 minutes later, completely not reading the multiple attempts to ask for help. This is just how it is.

**Comment by YakumoChen** [comment]
> > You don't even need to look at the chat log during combat most of the time, TGcode actually has decent enough design almost everything important is conveyed through visuals or sounds already.
> 
> You should be communicating and listening to the radio no matter the job- just security has a very hard time doing so. You need to say the same thing to people multiple times, and you still get people asking you something you just said. Why? A variety of reasons, but this targets one. Too often security screams for help, or lone wolfs, and receives no backup or anything. Then players go "where is X?" 30 minutes later, completely not reading the multiple attempts to ask for help. This is just how it is.

This has nothing to do whatsoever with my comment (I explicitly stated "during combat")

On top of that, it's pure conjecture. Security has always functioned well enough with its chat colour. I do not believe changing it will have any noticable difference whatsoever aside from pissing sec mains off, especially in terms of what you've speculated. The problems you're listing are endemic to players, not a result of chat colouring.

**Comment by theselfish** [comment]
> I've been playing the Skyrat build for over a year. Still can't understand why the security department has such a dislike for all things red.

Most of us don't.
It's mainly non sec players who want sec to not be red.

**Comment by theselfish** [comment]
> > > You don't even need to look at the chat log during combat most of the time, TGcode actually has decent enough design almost everything important is conveyed through visuals or sounds already.
> > 
> > 
> > You should be communicating and listening to the radio no matter the job- just security has a very hard time doing so. You need to say the same thing to people multiple times, and you still get people asking you something you just said. Why? A variety of reasons, but this targets one. Too often security screams for help, or lone wolfs, and receives no backup or anything. Then players go "where is X?" 30 minutes later, completely not reading the multiple attempts to ask for help. This is just how it is.
> 
> This has nothing to do whatsoever with my comment (I explicitly stated "during combat")
> 
> On top of that, it's pure conjecture. Security has always functioned well enough with its chat colour. I do not believe changing it will have any noticable difference whatsoever aside from pissing sec mains off, especially in terms of what you've speculated. The problems you're listing are endemic to players, not a result of chat colouring.

This. Thank you.
Making sec's channel red, blue, white, green, magenta or rainbow isn't going to make them listen to the radio more or less.
This change is just a nonmodular one that has zero benefit.

**Comment by nevimer** [comment]
> > I've been playing the Skyrat build for over a year. Still can't understand why the security department has such a dislike for all things red.
> 
> Most of us don't. It's mainly non sec players who want sec to not be red.

https://link.springer.com/article/10.3758/BF03202679

Security can be whatever the fuck colour it wants to be, it doesn't matter, as long as its unique. The issue is, too much colour sharing is going on. There is little to catch your eyes with security comms when nearly every other span_ message is also sharing that shade of red. If the other span_ messages were not red, that would be fine too. This isn't an attack of red security, it's just chat changing the channel is the least amount of edits to keep the colours seperate.  

For the record, I have a LOT of hours in sec.
DCYCeaAXyT

**Comment by nevimer** [comment]
We should honestly run an experiment - Remove all the large messages, and remove all colour from all chat messages, and see how attentive people are. It'll be awful.

**Comment by ghost** [comment]
On top of what's been said, TG already solved this with chat tabs. Move all those red messages to another tab like any sane person who dislikes chat spam does.

If this really, truly is an issue, perhaps something more subtle, like an audio cue whenever a message comes through security comms? We already have an audio cue when someone speaks into it, so having it also be when someone hears something isnt too far of a stretch, and is better than not-at-all-departmentally-related cyan

**Comment by Gandalf2k15** [comment]
In this case, I think the points have been made against it, and I'm not so sure about it either. For now, we'll be closing this, 👍

**Pull request closed without merging**
