### PR TITLE
Special Examine System

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Alright so this was a bounty request from Grunnyyy, and it makes sense for our server. 

This adds a system for examining things that we want to be meta protected. For now it is only the system for doing it + 1 example. I may return to this and update all uplink items to use the system for special descs.

The way it works is by checking a few conditions depending on the special_desc_req and will display custom extra examine information. 

When reworking an item, make sure to set the standard desc to something normal and the name too! Then set the special_desc_reqs to what you want, and then set the special_desc to the syndicate/whatever description. It's a bit of manual labour but will be worth it for our upcoming antag rework.

It can be expanded as time goes on, I may incorporate an upgraded security hud to bypass the syndicate checks.

## Current settings
```
EXAMINE_CHECK_NONE		//Displays the special_desc regardless if it's set.
EXAMINE_CHECK_SYNDICATE 		//For displaying descriptors for those with the SYNDICATE faction assigned.
EXAMINE_CHECK_SYNDICATE_TOY  //Ditto, only instead of displaying nothing for heathens, it shows "The src looks like a toy, not the real thing."
EXAMINE_CHECK_MINDSHIELD	//For displaying descriptors for those with a mindshield implant.
EXAMINE_CHECK_ROLE	//For displaying description information based on a specific ROLE, e.g. traitor. Remember to set the special_desc_role var on the item.
EXAMINE_CHECK_JOB	//For displaying descriptors for specific jobs, e.g scientist. Remember to set the special_desc_job var on the item.
EXAMINE_CHECK_FACTION		//For displaying descriptors for mob factions, e.g. a zombie, or... turrets. Or syndicate. Remember to set special_desc_factions.
```

Setting an item up correctly, here's an example:
```
/obj/item/storage/backpack/duffelbag/syndie
	name = "duffel bag"
	desc = "A large duffel bag for holding extra supplies."
	special_desc_requirement = EXAMINE_CHECK_SYNDICATE
	special_desc = "This bag is used to store tactical equipment and is manufactured by the syndicate."
```

This results in (if you are a traitor or other syndicate role):
image

## The detective!
This makes the detective fuckin' useful as hell! They're able to see the descriptions because of their brilliant detective skills.
This is what THEY see:
image

## Changelog
:cl:
add: Added a new in-depth examine system that will be used for future antag reworks.
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
Finnaly , we neeeded a mechanic to let sec know what or  what they can't know .

**Comment by GoldenAlpharex** [comment]
That's a great feature, I'm really looking forward to it!

**Comment by unit0016** [comment]
Holy shit, this is... incredibly awesome. God. Speed.

**Comment by hugmeorelse** [comment]
Oh wow, all it took was a bounty to get this started. XD I actually laid out my idea for this exact thing this last year to Gandalf and Azarak, but I was told it would be too difficult.

Good work, @Gandalf2k15. >:v Should have told me all you needed was a bounty, LOL! Would have had this sooner.

**Edit:** I reviewed the code. I think this will need a more advanced setup later to allow for certain edge cases to be handled properly, particular a tiered system that's easy to modify. Security will rely more on the actual code to identify what is and isn't suspicious, so this may add to the confusion for some of the more stealth-oriented items. I recommend a Part Two later, pending what the Policy Committee dictates.

**Comment by Gandalf2k15** [comment]
> Oh wow, all it took was a bounty to get this started. XD I actually laid out my idea for this exact thing this last year to Gandalf and Azarak, but I was told it would be too difficult.
> 
> Good work, @Gandalf2k15. >:v Should have told me all you needed was a bounty, LOL! Would have had this sooner.
> 
> **Edit:** I reviewed the code. I think this will need a more advanced setup later to allow for certain edge cases to be handled properly, particular a tiered system that's easy to modify. Security will rely more on the actual code to identify what is and isn't suspicious, so this may add to the confusion for some of the more stealth-oriented items. I recommend a Part Two later, pending what the Policy Committee dictates.

I'll do this at a later date, and add all of the new descriptors. I know some people already want to add stuff with this system!

**Comment by RatFromTheJungle** [comment]
maybe pre-emptively change Syndicate to more vague terms, or something of the like?
"used to store tactical equipment by several fringe para-military groups"
it would go a long way in stopping "evil S man bad"

**Comment by Oscari-pog** [comment]
If I get my bag taken away purely for the reason "It is syndicate" I will probably have a breakdown

**Comment by H0gberg** [comment]
Fantastic stuff!

**Comment by KasparoVy** [comment]
This is fucking awesome. Great job with the spans too.

**Comment by Jungling** [comment]
Better wording would go a long way.. The less times you have to write the word "Syndicate" in any description of anything actually syndicate.. The better you're doing. Syndicate are known for their colors of black and blood red. That's their "thing" so sticking to that biome of ideas.. you can use a lot of other words that would be way more colorful... and allow the community to pitch in for item descriptions :)

**Comment by Azarak** [comment]
Shouldn't this be a component? 4 lists is a lot of overhead for all items

**Comment by Gandalf2k15** [comment]
> Shouldn't this be a component? 4 lists is a lot of overhead for all items

I thought about a component system but adding a component to loads of items seems redundant as this will only really run if the special desc is set.

**Comment by Azarak** [comment]
Lots of different items sharing one behaviour is exactly what components are for. If you dont want to make a component then atleast dont initialize the lists on everything

**Comment by Gandalf2k15** [comment]
> Lots of different items sharing one behaviour is exactly what components are for. If you dont want to make a component then atleast dont initialize the lists on everything

Ah good catch, that was for testing

**Comment by hugmeorelse** [comment]
Yeah, traitors can be other things besides be Syndicate-sponsored.

**Comment by YakumoChen** [comment]
The example is fine but the special description lacks the detail that the bag is made of lighter materials (no slowdown) which is an actual feature of the item. It's just an example but it's a nitpick you shouldnt gloss the current standard over for.

**Comment by Gandalf2k15** [comment]
> The example is fine but the special description lacks the detail that the bag is made of lighter materials (no slowdown) which is an actual feature of the item. It's just an example but it's a nitpick you shouldnt gloss the current standard over for.

Yeah these descriptions will need to be set manually over time. I may do them myself.

**Pull request merged**
