### PR TITLE
[modular] cyclops eye marking

### PR DESCRIPTION
**Pull request by Nerev4r**
## About The Pull Request
always struck me as weird we didn't have this. i figure there's some usecase in it somewhere.

## How This Contributes To The Skyrat Roleplay Experience
image
image
easier ability to make one-eyed cuties.

image
here's how it would look on a human, colors may vary.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
 
 above PR desc should be sufficient.
  
</details>

## Changelog
:cl:
image: Adds a cyclops head marking, located right between the eyes.
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
Finally.
Vortigaunt sex.

**Comment by Jolly-66** [comment]
No way
The binding of Issac item 

b04e0e23a50728838586780e58cb0923196b7bd4r1-300-271v2_hq

**Comment by HoodMilk** [comment]
My name is nobody

**Comment by Iamgoofball** [comment]
👎 

don't make this a marking, make this an actual eye organ you can select, so we can do funny shit like removing depth perception during parallax

**Review by Ebin-Halcyon — APPROVED** [review]
Sure.

**Review by lessthnthree — APPROVED** [review]

**Pull request merged**
