### PR TITLE
Blueshift balance pass

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Oh boy, this is a fun one. I spent my precious GBPs on this pls merge.

I probably missed various things, but this is a start. I didn't even look at how the map structure is balanced, this is just items.

Replaced with toy
image

Removed free insuls from maint
image

Removed stasis bodybags from medbay
image

Replaced
image

Nitriles
image

With
image

Latex
image

Oh for-
image

Please no more...
image

God so many nitriles (also removes round start drugs and chem dispenser)
image

Will this ever end?
image

Replaced real cult dagger with toy
image

Removes RPD from spot without access restrictions
image

Removes roundstart guns in cargo
image

Removes round start power tools in engineering. We had this with Delta and it was agreed to be shit.
image

Something something item scarcity
image

Removes spare RD skillchip, we have a machine for this anyway
image

Removes roundstart bluespace cells in atmos
image

Sec HUD and mask in da robo locker
image

Removes donator's plushie from the map, kinda odd idk. Sets a weird precedent.
image

Removes mosin and bodyarmour from maint
image

Removes chef-CQC skillchip from HoP locker
image

Removes spare laserpointer from curator office
image

Removes medical skillchip from library
image

God dammit more insuls
image

Removes night-vision mesons from tech storage
image

Cuts these two belts down to one, in maint
image

Removes police baton and flashbang from maint. Belt is meh. Knife is.. Questionable but I decided to leave it.
image

Please look at what you're adding.
image

Magic is heretical
image

Makes armoury contraband random
image

Removes extended O2 tanks from sec. Get them from engi like everyone else.
image

Replaces amputation arcade machine with a regular one
image

Removes sunglasses from clothing shop
image

Replaces alien table with plasmaglass - I don't actually know if you can get alien alloy from this but I think you might be able to, and we lose nothing by changing it
image

Removes soap from secmed, no more nice things
image

Oh you thought I was done with the insuls huh...
image

## Changelog
:cl:
balance: Removed a lot of unbalanced loot from Blueshift.
/:cl:

### CODE REVIEW

**Comment by Seris02** [comment]
oh my god
why was all that in the map
holy shit

**Comment by IsaacTheSharkWolf** [comment]
Hey i'm a mapper not a balancer, thanks for passing over the stuff that my silly mind thought was ok.

**Comment by RatFromTheJungle** [comment]
image
mans really circled an empty box...

**Comment by Stonetear** [comment]
Not a fan of this one at all, honestly.  There's no reason to remove all of this.  With this train of thought, blueshift might as well just be a bigger version of the other maps.

**Comment by tf-4** [comment]
> Not a fan of this one at all, honestly.  There's no reason to remove all of this.  With this train of thought, blueshift might as well just be a bigger version of the other maps.

Feel free to have a go yourself

**Pull request merged**
