### PR TITLE
Adds Short tail override and mutant color alt

### PR DESCRIPTION
**Pull request by whataboutism-alos**
## About The Pull Request

This is the SR downstream patch of [79990](https://github.com/tgstation/tgstation/pull/79990) on TG, also by me. They are intended to be rolled out concurrently. This will make it safe to mirror 79990 and prevent invisible tails. It will not cause conflicts and can be preemptively merged, ~~but won't do anything on its own.~~ but will add in addition to 79990 a two-tone variant of the upstream version.

> This PR adds a short tail for lizard characters called Short. It is about half the length of the other tails. This tail has been fully sprited in 9-frame animation in accordance with the sprite style in use by other lizard tails. Hope you like my work; this is my first PR, let me know if I am missing anything.

For reasons unknown to me, SR has an override on the lizard tails to turn their TG steel-blue grayscale palette into a true grayscale. This accounts for the override file and matches the SR lizard grayscale palette. Thgvr's tweak of my spriteset for Shiptest [2542](https://github.com/shiptest-ss13/Shiptest/pull/2542) has been retweaked so the two-tone variant he created conforms to this true greyscale and shows more lateral movement within the wag.

## How This Contributes To The Skyrat Roleplay Experience

I did this because a few lizard players requested it of me; clearly there is a desire to more accurately express their characters and this will help them do so. Anything that can do that is a boon for roleplay experience in my book.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
dreamseeker_LXSuKnOkgt

sogtail
(L-R wag only looks faster because it accounts for the tail getting higher at either edge of its swing)

sogtail_tg
(Smooth for comparison)

</details>

## Changelog

:cl:
code: Skyrat sprite override updated to reflect upstream lizard tail
add: Adds two-tone version of short lizard tail
/:cl:

### CODE REVIEW

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
The side animations are nice, but it just looks as though it doesn't match the front and back animations, as if it was different movements entirely, which is going to make it feel a little jarring in-game.

I know this just a greyscale recolor, but it's also probably something I'd recommend changing it upstream as well, so that it looks from the side that it's still wagging from left to right too, instead of up and down. I saw someone upstream mention something pretty similar anyway, even if it might not be a maintainer there.

**Comment by whataboutism-alos** [comment]
> The side animations are nice, but it just looks as though it doesn't match the front and back animations, as if it was different movements entirely, which is going to make it feel a little jarring in-game.
> 
> I know this just a greyscale recolor, but it's also probably something I'd recommend changing it upstream as well, so that it looks from the side that it's still wagging from left to right too, instead of up and down. I saw someone upstream mention something pretty similar anyway, even if it might not be a maintainer there.

Sure, I can look into what that would take. I replied to that one upstream too, with some extended reasoning for why it’s like this out the gate.

**Comment by whataboutism-alos** [comment]
Ready for merging 👍

**Comment by vinylspiders** [comment]
Look good to you @GoldenAlpharex ?

**Comment by whataboutism-alos** [comment]
Oops, looks like I forgot to switch branches for a private server with erp disabled. Thanks for catching that @vinylspiders

**Review by GoldenAlpharex — APPROVED** [review]
Yeah, let's go!

**Pull request merged**
