### PR TITLE
New horn, snout, wing sprites. [WIP]

### PR DESCRIPTION
**Pull request by C0rva1r**
## About The Pull Request
Made some additional cosmetic sprites for character creation. Some are currently experimental but that will change later.

## Why It's Good For The Game
Nothing significant to note other than adding some additional customisation.

One thing to note that the Flying state of Canadair wings will consume a significant amount of visual space than megamoth. This is still experimental and may be changed.
## Changelog
:cl:
add: Unicorn sprites
add: Snout sprites
add: Wing sprites
imageadd: Horn sprites updated
imageadd: Snout sprites updated
spellcheck: fixed a few typos
/:cl:

### CODE REVIEW

**Comment by C0rva1r** [comment]
First PR in awhile and probably screwed something up related to git. Thought to mention that.

**Comment by Gandalf2k15** [comment]
Can we have piccies of it in game?

**Comment by Azarak** [comment]
obraz
I'm not a fan of those, they're hardly customizable either.

**Comment by C0rva1r** [comment]
> obraz
> I'm not a fan of those, they're hardly customizable either.

Still figuring out how the game handles head sprites. Made the pr just to review changes over time.

**Comment by Azarak** [comment]
@C0rva1r Regarding how the system works, You either make an accessory matrixed or grayscaled. Matrixed will take from RED/GREEN/BLUE and will allow for 3 colors in the customization, grayscaled is all colors (so white) and only allows for 1 color. 

I still dont want to approve such sprites though, they're too bizarre. @hugmeorelse can overturn me

**Comment by C0rva1r** [comment]
ooooh ok, never knew what a matrix was till now. So thank you. I'll be doing some changes further. That wing you see is just an overkill flying state with the Canadair wings. I was mainly using it to get familiar some spriting practice. Not sure if that would get added however.

**Comment by KasparoVy** [comment]
Ohhh Caaanadaaa.

**Comment by Gandalf2k15** [comment]
This PR will be held to a vote for approval or denial. Please stand-by.

**Comment by Gandalf2k15** [comment]
I have voted **yes with requested changes**; Remove the wings but keep the rest as the wings may be a big distraction to other players.

For my vote to count towards **yes**, the above changes must be made, otherwise, my vote will default to **no**.

**Comment by atakiya** [comment]
Also voting **yes, but with requested changes**.

My approximate max would be ¾ covered on each side of the character tile. So in total, 2.5 tiles including the character tile itself.
The megamoth wings for example currently cover 3 tiles including character if I remember right.

So -
If wings >2.5 tiles including character, no.
If wings removed or fixed, yes.

**Comment by C0rva1r** [comment]
Just to give everyone an update. I have created more additional sprites and going to push them.

For the large wings that are comparable for the megamoth will be removed and replaced with a normal shape of wings. The massive wings will be adjusted and I'll see for changes be made to it in time.

**Comment by hugmeorelse** [comment]
a

**Comment by Gandalf2k15** [comment]
Hello, feel free to open this once more once you've completed the work, thanks!

**Pull request closed without merging**
