### PR TITLE
Void Raptor Security Access Fixes

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

There was a lot of inconsistency in what access was where in void raptor sec. Namely,

<details>
<summary>This area was all set to `security/entrance`, despite it leading to the lathe room. It's all updated to `security/general`</summary>
 
image

</details>

<details>
<summary>All access into the locker room is now `security/brig`. The interview room is kinda weird to access but that's not an access helper issue, it'd need more of a remap.</summary>
  
image

</details>

## How This Contributes To The Skyrat Roleplay Experience

Consistency = good.
Not having trespassers = good.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
It's access helpers. There's not really anything to test here.
</details>

## Changelog
:cl:
fix: Security on Void Raptor now has access levels consistent with other maps.
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
Merge master into this branch? That may resolve compile maps.

**Comment by tf-4** [comment]
I hate maps

**Comment by Zergspower** [comment]
can you get rid of that jukebox that's near departures while you're in there? save an extra PR and review

**Comment by tf-4** [comment]
that has nothing to do with this PR

**Comment by tf-4** [comment]
OK idk what I did but this branch is fucked I hate it

**Pull request closed without merging**
