### PR TITLE
Added GoldenAlpharex' donator item

### PR DESCRIPTION
**Pull request by Useroth**
Added GoldenAlpharex's donator item. Changelog not needed here.

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
After all this time........... My life will finally be complete.

**Review by GoldenAlpharex — APPROVED** [review]
Code looks good, I'll add a bit more to it like tomorrow or something.

**Comment by softcerv** [comment]
Wait, are these full functioning welding goggles?

**Comment by tf-4** [comment]
> Wait, are these full functioning welding goggles?

No.

**Comment by GoldenAlpharex** [comment]
> Wait, are these full functioning welding goggles?

No, the plan is to code a simple way to add the welding capabilities by hitting it with welding goggles, which would be pretty neat if you ask me.

**Comment by GoldenAlpharex** [comment]
Anyway, I'll make the changes on my own PR.

**Comment by softcerv** [comment]
> 
> 
> > Wait, are these full functioning welding goggles?
> 
> No, the plan is to code a simple way to add the welding capabilities by hitting it with welding goggles, which would be pretty neat if you ask me.

ah, makes sense!

**Pull request merged**
