### PR TITLE
Blueshift hydroponics fixes

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

- Fixes windoor access
- Fixes duplicate door
- Replaces doors with hydroponics-styled ones
- Makes some door names more accurate
- Replaces the botanical chem dispenser in maints behind hydro with a regular one. The botanical one is not really intended for actual gameplay - it not only is kind of overpowered, giving you mostly any chem you could want for botany at the press of a button no actual work required, but it also is not deconstructable. This means you can't even open the panel. So you can't even move it. Once it's built, it's  in that spot forever, no way to deconstruct or otherwise move it. Which is kinda jank.
- replaced most interior rwindows with regular ones, except the test chamber ones
- un-var-edited the seed vendor to have a unique slogan delay (why did it have this??)

## How This Contributes To The Skyrat Roleplay Experience

fixes uhhhhhhhh good

## Changelog
:cl:
fix: Various access/airlock related fixes for Blueshift hydroponics.
fix: The chem dispenser board in maintenance behind Blueshift hydroponics has been replaced with a more functional one.
/:cl:

### CODE REVIEW

**Review by Jolly-66 — COMMENTED** [review]
Mind hitting this door too?

image

**Comment by tf-4** [comment]
> Mind hitting this door too?
> 
> image
> 

This is meant to be a secure area so I kinda figured a more secure door works, but if you'd rather it be a hydroponics one I don't have an issue. Will do tomorrow

**Comment by Jolly-66** [comment]
>T reply

No, just asking if you could rename it too! I have no qualm with the door being used, just the name.

EDIT: I suppose while I'm here and as I was glancing over Hydroponics, can you replace any **in** department full-tile windows to regular instead of reinforced? I don't think we really need reinforced windows in there, nor is it a super high-security zone (the ones going to the lab are fine, keep them reinforced).

**Comment by tf-4** [comment]
- renamed the door to "Hydroponics Test Chamber"
- replaced most interior rwindows with regular ones, except the test chamber ones
- un-var-edited the seed vendor which had a unique slogan delay (why did it have this??)

**Review by Jolly-66 — APPROVED** [review]
Thank you!

**Pull request merged**
