### PR TITLE
Adds midround assault ops

### PR DESCRIPTION
**Pull request by Zonespace27**
## About The Pull Request
Adds a 5 weight, 20 cost midround ruleset to dynamic to allow assault ops to come aboard.

## How This Contributes To The Skyrat Roleplay Experience
May as well make this ruleset on-par with nukeops, letting them spawn in the round as well.

## Todo

- [ ] Figure out if the cost is fine considering our dynamic settings
- [ ] Confirm that it works
- [ ] ideally get a round or two of TMing to make sure the balance isn't whack

## Changelog

:cl:
add: Assault ops can now spawn in the middle of the round
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
assops are to heavy for a midround roll, especially when the midround-rolling hasn't exactly been 'good' for a good two weeks,

they're based, and mostly, balanced for being on their own, them + a changeling is going to be unhandlable, it takes one guy with an MG to wipe sec, plus cargo and med on the way past for good measure

**Comment by YakumoChen** [comment]
I don't see completion being super feasible with 6 different objectives to complete if they spawn in the middle of the round, unless they forego all RP and rush heads and cards.

**Comment by tf-4** [comment]
I really don't see this working. Ass. Ops' success as a gamemode is already tenuous when it's roundstart

**Comment by Jolly-66** [comment]
If we really go through making them a potential mid-round, please evaluate their threat cost better

**Comment by Zonespace27** [comment]
some other time

**Pull request closed without merging**
