### PR TITLE
Removes Tramstation

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Celebrate PR 20000 in style.

## How This Contributes To The Skyrat Roleplay Experience

I hate Tramstation.

:cl: LT3
del: Removed Tramstation
/:cl:

### CODE REVIEW

**Review by tf-4 — APPROVED** [review]

**Comment by softcerv** [comment]
20,000th PR

**Comment by Jureiia** [comment]
u better not

**Comment by DriftingSkies** [comment]
WE'RE FINALLY FREE

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
https://www.youtube.com/watch?v=f8mL0_4GeV0

**Comment by Jolly-66** [comment]
image

image

trolljh

**Comment by Paxilmaniac** [comment]
complete waste of pr 20000 can we ban this guy

**Comment by lessthnthree** [comment]
Interlink is next,

> complete waste of pr 20000 can we ban this guy

Merek was gibbed for our sins.

**Comment by axietheaxolotl** [comment]
Finally, a good PR

**Comment by Jolly-66** [comment]
Remove Interlink and I'll find where you live and drop a nuclear atomic bomb on your house.

As a treat, of course.

**Comment by lessthnthree** [comment]
> Remove Interlink and I'll find where you live and drop a nuclear atomic bomb on your house.
> 
> As a treat, of course.

This salt PR started because we couldn't find a tree to hide behind in the Interlink, so it's technically your fault.

**Comment by Jolly-66** [comment]
> Couldn't find a tree to hide behind

image

**Comment by Paxilmaniac** [comment]
Speedclosing this pr

**Pull request closed without merging**
