### PR TITLE
[PORT] One Tail From Chomp

### PR DESCRIPTION
**Pull request by Nerev4r**
## About The Pull Request
Hi, I didn't make any specific characters for this one because I was lazy.

image
This PR adds a new two-color very-long 'ring' tail. You could probably make a cute lemur gf with these.

## How This Contributes To The Skyrat Roleplay Experience
I love customization.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  The image in the description.
</details>

## Changelog
:cl:
image: One new long ring tail!
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
need to commit one last act of interserver burglary hang on

**Comment by Nerev4r** [comment]
nevermind

**Review by lessthnthree — APPROVED** [review]

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
The first tail looks really different from the sides, versus from behind. Looks a bit weird to me. The second one looks a bit odd shading-wise, but it's also not the worst thing in the world.

**Comment by Nerev4r** [comment]
> The first tail looks really different from the sides, versus from behind. Looks a bit weird to me. The second one looks a bit odd shading-wise, but it's also not the worst thing in the world.

Trimmed the first one from the PR.

**Review by GoldenAlpharex — APPROVED** [review]

**Pull request merged**
