### PR TITLE
[MODULAR] Makarovs no longer require a multitooled cargo console to order.

### PR DESCRIPTION
**Pull request by Zonespace27**
## About The Pull Request
Makes Makarovs not require a multitooled cargo console, and adds a makarov ammo pack (One 10mm auto ammo box and two extra magazines) for 800 credits.

## How This Contributes To The Skyrat Roleplay Experience
We've already got a shitton of guns in the goodies tab, why not add the skyrat one as well?
Cobalt's approval:
image

## Changelog

:cl:
qol: Makarovs can now be ordered without a multitooled cargo console
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
I don't agree with this.
 Makarovs are contraband, not even light contraband like pepperballs or forge swords, they are just straight up illegal antagonist guns.

If you have to make yourself look suspicious as hell taking apart the request console to multitool it to get an antag gun, that seems fairly reasonable.

**Comment by Zonespace27** [comment]
> I don't agree with this. Makarovs are contraband, not even light contraband like pepperballs or forge swords, they are just straight up illegal antagonist guns.
> 
> If you have to make yourself look suspicious as hell taking apart the request console to multitool it to get an antag gun, that seems fairly reasonable.

It's not an antag gun, it just bears an unfortunate name similarity to the traitor makarov. (traitor makarov is overall stronger in most cases)
And also, you can get, through goodies:

- Energy Guns
- WT-550s
- Thermal Pistols
- Shotguns
- Detective Revolver
- Stingbangs
- Pepperballs
- Hellfire Laser Kit
- .38 Ammo
- WT-550 Ammo
There's already a *wide* range of options available to you if you want guns, why not make it consistent for all goody pack guns?

**Comment by YakumoChen** [comment]
- It's a gun in the uplink

- It has no access restrictions

**Comment by Zonespace27** [comment]
> * It's a gun in the uplink

image
Traitor one:
image
Skyrat one:
image
The cargo crate gunset contents:
image


> * It has no access restrictions

Neither does any other goody

**Comment by YakumoChen** [comment]
> Neither does any other goody

Have you checked that? All the goody guns have security department access locks except the pepperball

**Comment by RatFromTheJungle** [comment]
> > Neither does any other goody
> 
> Have you checked that? All the goody guns have security department access locks except the pepperball

unrelated to the PR, the goody guns /cannot/ have access locks, none do.

As for the PR, the makarov was supposed to be bigly illegal, hence why it's behind the multitool, the other stuff not being so is just because well uhhhh TG, and no one getting around to it. I'm impartial to it being added to the main-list, i'm just noting why it was behind it.

**Comment by Zonespace27** [comment]
> > Neither does any other goody
> 
> Have you checked that? All the goody guns have security department access locks except the pepperball

image
They don't!

**Comment by YakumoChen** [comment]
> > > Neither does any other goody
> > 
> > 
> > Have you checked that? All the goody guns have security department access locks except the pepperball
> 
> image They don't!

That's a bug, however. It has an armoury access lock in the code.

**Comment by Zonespace27** [comment]
> That's a bug, however. It has an armoury access lock in the code.

it's a feature so that you can't order them through the express console as easily

**Comment by MassacreDemigirl** [comment]
@YakumoChen private orders always override access restrictions. So an assistant can private order a wildcat crate and open it

**Comment by YakumoChen** [comment]
Makarovs are also pocket-sized items, unlike most guns from cargo they can also easily be concealed. They were intended to be illegal contraband.

**Comment by Zonespace27** [comment]
> Makarovs are also pocket-sized items, unlike most guns from cargo they can also easily be concealed. 

If this is a maintainer's breaking point for the PR, it can be changed.

> They were intended to be illegal contraband.

Intentions can change over time, especially when these existed pre-having this many guns in goodies.

**Pull request merged**
