### PR TITLE
[MODULAR][MY-FIRST-PR] Ports the Janitor Arm Implant

### PR DESCRIPTION
**Pull request by SpookyTheFox**
## About The Pull Request
What it says in the title. This is a port of the janitor arm implant from old base. It is almost a direct copy and paste. Material cost, tools, and emag function are carried over.

My only changes from that are putting it on the already modularized medical research node, alongside the botany implant. This prevents having to modularize more tech nodes or create new ones, which would be well outside the scope of this PR.

I have also added the ability to print the implant from the service lathe. This is mainly to give the rare traitor janitor the chance to get and emag the implant prior to installation, since chances are they won't get to hold it before it's installed if they go to medical or robotics for it. It is not prevented from printing at those locations however.

I am aware of a potential upcoming major implant overhaul from upstream that includes a janitorial arm implant. I am sending this one in anyway, because I believe this carries more skyrat flavor and it's ready to go, modular and everything.

## Why It's Good For The Game

A fun novelty arm implant from the oldbase. It retains it's non-lethal emag mode for the enterprising traitor as well.

## Changelog
:cl:
Added some lines to three files.
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
looks peachy on a glance over
image

**Review by Gandalf2k15 — APPROVED** [review]
Code seems fine!

**Comment by SpookyTheFox** [comment]
> 
> 
> Code seems fine!

Thanks! This was my first attempt doing anything for SS13, I was thrilled that I got it working on the first try on my local test. I checked it with both admin spawning and playing Runtime Station. I'll try it in game as soon as possible. If all goes well, I have a handful of other things I'd like to try to port or build from scratch.

**Comment by KasparoVy** [comment]
Badass, cleanermen everywhere approve

**Pull request merged**
