### PR TITLE
[MDB IGNORE] Costumes Spritefile Cleanup

### PR DESCRIPTION
**Pull request by ghost**
## This still requires some testing due to it having been Drafted so long. DNM until the title says [READY].
Yeah it fell behind while I was on vacation. Sue me.

Todo:

- [ ] Move dress/westernbustle, dress/flamenco to Costume
- [ ] Find more flaws with my month-old code
- [ ] Testing

## About The Pull Request
Wow. This cleanup was...
Wow.
I didn't ever need to know this much about Japanese cultural outfits. Nor see this much Victorian stuff.

**Changes/Additions**
- DMI cleanup
- Removes Victorian, Western, and Cowboy clothing (1, its 2567. 2, the dresses ruined a ton of stuff bc of their size. 3, use the Buttondown clothing to recreate the rest ffs they're all recolors anyways)
- Removes Croptop (Same as above, can be made with an Undershirt and the recolorable shorts.
- Removes unused items and duplicate items (God damn that NostalgiaCritic uniform holy shit)
- Repaths anything left to costume/skyrat
- Kimono is now a Yukata (Less formal)
- Yukata, Cheongsam, Qipao, and Bathrobe are now resprited and GAGS
- Christmas costumes are resprited, and appear automatically during the Christmastime (we were expected to manually set the Uniforms. Loadouts already has seasonal-only settings. The REST of the Christmas stuff used this setting, just not the uniforms...)
- Digitigrade for ALL costumes in TG's costume.dmi - even the Drip Hoodie

## How This Contributes To The Skyrat Roleplay Experience
image
(Bathrobe, Bathrobe, Qipao, Cheongsam, Yukata, and unchanged Kamishimo)
(Christmas Croptops and Christmas Costumes)

image
(Every single costume is digitigraded (skirts excluded, also the gladiator idk why thats in it))
(There'd be more but I had an accident testing and blew up the holodeck)

Our spritefiles are still a mess, but GOD the uniforms one is almost ready to be taken out back and put out of its misery. We're SO close.

## Changelog

:cl:
imageadd: Costume's icons have all been updated and moved into a costume.dmi file in a continued organization effort. Please report any relevant uniform icon issues on the github, and mention OrionTheFox!
imageadd: Bathrobes, Qipaos, Cheongsams, and Yukatas (Previously Kimonos) have all been Greyscaled!
imagedel: Removed all Western, Cowboy, Rancher, or Victorian uniforms - many can be recreated with the Button-Downs, which is greyscaled and ready for you to color to your heart's content!
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
DNM UNTIL #15257
Open early so I can get some sprite review

**Review by Ebin-Halcyon — COMMENTED** [review]
bsing and ysing obj sprites have 4 dirs. Might wanna drop that down to just the front.

**Comment by ghost** [comment]
> bsing and ysing obj sprites have 4 dirs. Might wanna drop that down to just the front.

TG wtf r u doin these r ur sprites u fools!!

**Comment by ghost** [comment]
Opening to avoid falling horribly out of date. It should be ready for review while I get around to testing

**Comment by glitchbow** [comment]
Been really mixed on this PR, the recolorable new items are nice but it removed two of my favorite dresses. "It's 2567" isn't a good reason whatsoever, we still have other historic items like the Plague Doctor Mask and the Monocle. It makes very little sense to force someone to use their underwear slot for a full dress combo, especially given we don't have very many skirt bottoms. ~~It also means feminine characters can't have a bra in that slot, which is sad and not very realistic.~~

Don't remove inoffensive historic items. If we have to add them back as donor items, we will.
I'd like to contribute a better resolution to these items.

**Pull request merged**
