### PR TITLE
[MIRROR] Ethereal Pirates (Re-pr) [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/76554
--------------------

Other pr had some weird check failure, making a new pr to see if it fixes it.

## About The Pull Request
After he ended up finishing his pirate pr before I could, SethLafuente graciously offered to let me roll my in-progress pirate pr into his overall pirate expansion project.

This pr essentially adds a new faction of pirates, along with a new subspecies of Ethereals a-la silverscales.

- The Lustrous:

A unique subspecies of Ethereal, with years of exposure to bluespace dust mutating them into crystalline abominations sporting a new pointy head, pressure resistance, and a permanent bluespace prophet brain trauma. They're still as fragile as ever, but far more capable of getting in and out of sticky situations.

- Geode Pirates:

A hollowed out asteroid manned by three Lustrous, equipped with switchblades, traitor PKAs, jump boots, two teleporting turrets, and an upgradable bluespace launchpad.

However, they lack proper armor and ship defenses, forcing them to adopt a coordinated hit-and-run playstyle.

asteroid
shuttle
piratas
## Why It's Good For The Game

When I started working on this project, I wanted to implement this faction to cover for the loss of psykers and as a means of creating a "rock-paper-scissors" system to how standard pirate playstyles would work; with default pirates being offensive, Silverscales defensive, and Lustrous mobile.

With Seth's pr, things are a little different now, but I still believe a glass cannon mobility-focused pirate faction would be a welcome addition to the pirate roster.
## Changelog
:cl:
add: Adds the Lustrous, ethereal pirates in a big bluespace geode!
sound: Unique scream sound for the Lustrous species.
image: Unique head icon for the Lustrous species.
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
Needs species nuking PR (head stuff)

**Review by vinylspiders — APPROVED** [review]

**Comment by Nechronom** [comment]
wait we lost the psyckers?? awe what lame... either way seems like a cool concept!
gonna miss the blind gunslingers though

**Comment by vinylspiders** [comment]
> wait we lost the psyckers?? 

Only as Pirates, they're still in the game. They were referring to this PR:

https://github.com/Skyrat-SS13/Skyrat-tg/pull/20951

**Comment by Nechronom** [comment]
> > wait we lost the psyckers??
> 
> Only as Pirates, they're still in the game. They were referring to this PR:
> 
> #20951

Oh that makes sense. Thanks a lot

**Comment by Toastgoats** [comment]
Wow I did not expect skyrat to merge this, afaik you guys have higher standards than my tg player shitcode lol

I'm assuming the issue with the new color list for the Lustrous not working still stands, so just a heads up for that, because I probably wont get around to fixing it for a bit.

**Comment by vinylspiders** [comment]
> Wow I did not expect skyrat to merge this, afaik you guys have higher standards than my tg player shitcode lol
> 
> I'm assuming the issue with the new color list for the Lustrous not working still stands, so just a heads up for that, because I probably wont get around to fixing it for a bit.

I think it's a fun PR. I haven't seen any complaints about it so far at least!

As for your color issue, you can fix it by making this small change:

Code_aDIwzlrmkB

**Comment by Toastgoats** [comment]
> > Wow I did not expect skyrat to merge this, afaik you guys have higher standards than my tg player shitcode lol
> > I'm assuming the issue with the new color list for the Lustrous not working still stands, so just a heads up for that, because I probably wont get around to fixing it for a bit.
> 
> I think it's a fun PR. I haven't seen any complaints about it so far at least!
> 
> As for your color issue, you can fix it by making this small change:
> 
> Code_aDIwzlrmkB

Oh shit thanks!

**Pull request merged**
