### PR TITLE
[MIRROR] Adds the Venom Antagonist [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/72346
--------------------

## About The Pull Request

adds the venom antagonist

dont review this its not worth it

## Why It's Good For The Game

venom they wont know what hit em
image

## Changelog

:cl:
add: Venom antag
/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
El selfmerge momento

**Comment by Paxilmaniac** [comment]
valve add this

**Comment by dawsonkeyes** [comment]
they wont know what hit em

**Review by Zonespace27 — APPROVED** [review]
I fucking *pray* that I removed this correctly

**Pull request merged**
