### PR TITLE
[modular] MORE AND MORE AND MORE LOADOUT SHIT

### PR DESCRIPTION
**Pull request by thestubborn**
## About The Pull Request

i am a god above men, I have became a god of cloth, all I can do is add cloth, again and again and again

## Why It's Good For The Game

clothing nice
image
stuff in here
image
image
image

## Changelog
:cl: Linkara, the Lightbringer
add: One hat for those cold icebox guard shifts.
add: One coat for loyal quartermasters.
add: Two formal dresses
add: One tracksuit
add: One tactical beer suit
add: One ridiculous tie
add: One formal suit, by the Order of the Court we are issuing you a cease and desist.
add: the will to live, I've been told I need that
imageadd: even more stuff oh boy
/:cl:

RIGHT SHIT BEFORE I FORGET
Sprites are from...fulp, desert rose, WW13, Desert Rose, Civ 13 (maybe, I cant remember), Burgerstation, Yog(maybe) Tau...whatever, the Russian server.

obligitory dm me and ask for them to get removed, or I can buy em or whatever I dunno

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
HYESLL YES

**Comment by thestubborn** [comment]
hmm?
i also added back old base stuff, not codewise, but the icons are there for whoever wants the metro cop and hecu back
(me)
(I may have missed the masks)

**Comment by Sethnov** [comment]
also if you want to wear a coat on the icebox, it going to need values to keep you warm, if not it won't protect you from the cold, which I experienced from all these new coats in the loadout.

**Comment by thestubborn** [comment]
oh yeah i'll add that code line hold on

**Comment by Gandalf2k15** [comment]
Can yah add the enclave stuff?

**Comment by thestubborn** [comment]
i can code it, maybe not for the loadout, but I can make it

want armor?

> 
> 
> Can yah add the enclave stuff?

**Comment by thestubborn** [comment]
> 
> 
> Can yah add the enclave stuff?

not in the loadout as I feel giving a) armor out
and b) nazi costumes 
out in the loadout would be...bad
if I figure out hardsuits, maybe the nukies will get some visits from their neo American friends

**Comment by Gandalf2k15** [comment]
image
 add these and I'll merge

**Comment by thestubborn** [comment]
> 
> 
> image
> add these and I'll merge

i did, not to the loadout, unless you want em there

**Comment by thestubborn** [comment]
image
see?

**Comment by thestubborn** [comment]
image
image

**Comment by NopemanMcHalt** [comment]
### Saying Just In Case:

Although you didn't use danger-color-coded prisoner uniform in game/loadout (yet?), there's proper dropped/inventory/on-hud sprites in the old code. Same could be said about Civil Protection uniforms, I think.
Also, are prisoners able to get loadout items in this one? Could add it in job-related category and restrict  it to prisoners.
~~t. cannot test properly local server keeps crashing after a certain time running - thanks vscode very cool~~

**Comment by thestubborn** [comment]
> 
> ### Saying Just In Case:
> 
> Although you didn't use danger-color-coded prisoner uniform in game/loadout (yet?), there's proper dropped/inventory/on-hud sprites in the old code. Same could be said about Civil Protection uniforms, I think.
> Also, are prisoners able to get loadout items in this one? Could add it in job-related category and restrict it to prisoners.
> ~t. cannot test properly local server keeps crashing after a certain time running - thanks vscode very cool~

just woke up, those are sprites from the old base, and prisoners get loaadout stuff yeah

**Pull request merged**
