### PR TITLE
Removes clown mobs from cytology

### PR DESCRIPTION
**Pull request by Azarak**
## Changelog
:cl:
del: Cytology can no longer grow clown mobs
/:cl:

### CODE REVIEW

**Comment by SpaceVampire** [comment]
Can we get something in the "Why It's Good For The Game" on this? I just think its nice to be able to see the reason something was removed.

**Comment by Azarak** [comment]
> 
> 
> Can we get something in the "Why It's Good For The Game" on this? I just think its nice to be able to see the reason something was removed.

Those dont belong in a roleplay server. Plus some of them can spam banana peels so hard the server has a stroke

**Comment by hugmeorelse** [comment]
> Can we get something in the "Why It's Good For The Game" on this? I just think its nice to be able to see the reason something was removed.

I asked for it. As for why it's good for the game, it doesn't fit with the setting at all. We already have issues of LRP. 

That's it. End of story. Nothing more to be discussed here.

**Comment by Owai-Seek** [comment]
People actually do cytology?

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
