### PR TITLE
Remove "Clunky fingers" trait from the Station engineer job quirks blacklist.

### PR DESCRIPTION
**Pull request by Stonetear**
## About The Pull Request
This disables the trait/quirk job blacklist for clunky fingers.
## Why It's Good For The Game
There is no reason why Station Engineers shouldn't be able to have the clunky fingers quirk.  I have never used my tablet once, and I wear my insulated gloves the entire shift.

## Changelog
:cl: Stonetear
balance: Station engineers can now have the clunky fingers trait.
/:cl:

### CODE REVIEW

**Comment by AlinaStarkova** [comment]
uhhhhhh, clunky fingers messes with more than tablets uhhhhhh

**Comment by FlamingLily** [comment]
Having chunky fingers means you are physically incapable of ever using CIMS, Canary, Ampcheck

*You know, the biggest tools for an engineer*

**Comment by KasparoVy** [comment]
Maybe if there was an engineering assistant or construction tech role 🤔

**Comment by Gandalf2k15** [comment]
Sorry, can't have this.

**Pull request closed without merging**
