### PR TITLE
[SEMI-MODULAR] Makes Allstar Energy Weapons hitscan

### PR DESCRIPTION
**Pull request by MassacreDemigirl**
## About The Pull Request
Makes Allstar Energy Weapons in game hitscans. Hitscan lasers have a limited range and their damage decays over a certain range. MCR's still use shot based lasers in order to create a difference in application.
Along with the hitscans, this PR imports the beam sprites from Sojourn and moves the beams.dm to modular in order to edit the laser effect better.

_This was based upon tgstation/tgstation#57080_

## How This Contributes To The Skyrat Roleplay Experience
With the upcoming addition of Gun Cargo and our split from TG Balance, It is time we take bold and new steps forward. Creating a distinct difference between lasers and ballistics other then just pure damage and damage type is I believe a good addition to the flavor of the game and also creates more reasons for playerbase to have an actual choice when getting guns.

This also opens the path for more energy based weapons with different profiles as well as more mods for the MCR.

## Changelog

:cl: ErdinyoBarboza, SojournStation - Beam Sprites, Sparkezel - Original PR on TGstation 
balance: Allstar Energy Weapons have switched to a new proprietary laser beam module, making their lasers travel in an instant. All magazineless lasers are now hitscan. MCR's are still shot based lasers.
balance: Hitscan Lasers base damage is now 17 (was 22)
imageadd: Imported hitscan laser sprites from Sojourn
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
Not this _again_. This has been tried, was fucking awful, and was promptly un-tried. Both on tg AND on Skyrat.

**Comment by Gandalf2k15** [comment]
We tried this before. What you can however do is create a hitscan MCR upgrade.

**Comment by Gandalf2k15** [comment]
we can test it

**Comment by Zonespace27** [comment]
Guess we'll probably test it sometime

**Pull request closed without merging**
