### PR TITLE
[TM-ONLY] [MDB IGNORE] Overmap system, traders and planets, crash the mining shuttle into some asteroids [PORT FROM HORIZON] 

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

Entirely changes how space exploration and shuttles function, moving everything from randomly linked z-levels that you can access by going to the edge of the map, to a large "overmap" that can be accessed through ships. Complimenting this, a plethora of features from buyable shuttles, to randomly generated planets, to even a system of trading stations and interstellar shops, you could even shoot lasers at space rocks if you're so inclined.

## What All Does This Add

To quote Gandalf, "A fucking lot", see pr #7982 if you want the full rundown

The changelog is absolutely an understatement, there's a LOT of stuff here

## What Still Needs To Be Done

- [x] Make sure planets are actually generating right after being reworked for ruin generating changes
- [x] Either remove the Titan or make it so the lower class cannot dock with it (RIP Hubert)
- [ ] Document EVERYTHING
- [ ] TGUI all of the interfaces
- [ ] Do a quality pass over all of the maps
- [ ] Refactor and improve whatever there is, mining lasers in particular could use a look over by myself
- [ ] See if there's more that can be modularized here (There is)
- [ ] Fix all the things this inevitably breaks
- [ ] Find more things to add to this list

## Gallery (Now Includes Cooler Shuttles)
image
image
image
image
image

## Changelog

:cl: Paxilmaniac; Gandalf2k15; Azarak
add: Overmap system, complete overhaul of space exploration
add: Planets system, randomly generated planets to travel to and explore
add: Trader system, trade stations with buyable goods and delivery missions
add: Mining drills, machines for extracting resources from planets
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
No way.

**Comment by Paxilmaniac** [comment]
remind me to never put a #(number) in a commit name again

**Comment by softcerv** [comment]
oh nice, I'm glad to see this PR open again

**Comment by Paxilmaniac** [comment]
I couldn't tell you why linters is failing, because linters can't tell me why its failing

**Comment by gonenoculer5** [comment]
> I couldn't tell you why linters is failing, because linters can't tell me why its failing

[screams in linters]

I HATE CI
I HATE CI
I HATE CI

Thank you Continious Integrations, very cool.

Other than that, damn this looks sick.

**Comment by Paxilmaniac** [comment]
While not done by any means, I did pick this up already in a state where it can be tested if so desired, I just beg that the maintainers heed the bigass [TM-ONLY] sign.

Also, 
image

We found how the bsa works guys

**Comment by TetrakoHateThis** [comment]
OVERMAP MY BELOVED YOU CAME BACK

**Comment by Paxilmaniac** [comment]
As promised, now that it is the weekend, I will remake this all to be upstream. It'd be better implemented with a lot less non-modular stuff, and it gives me a lot more time to work out the kinks.

**Comment by Ebin-Halcyon** [comment]
:eye:

**Pull request closed without merging**
