### PR TITLE
ashwalkers now with borers (ritual)

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
we have bileworms... we have ashwalker eggs... lets have borers?

## How This Contributes To The Skyrat Roleplay Experience
gives ashwalkers an opportunity to deal with borers-- so new scenes and experiences!

## Changelog

:cl:
add: added a summon borer egg ritual
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
we’re reaching levels of giving things to ashwalkers that i didn’t know was possible, and i’m not sure about this one

**Comment by Zonespace27** [comment]
Eh, I dunno about this one really, borers are strong and this seems... kinda eh? overall

**Comment by GoldenAlpharex** [comment]
Yeah I'm not really convinced this is a good idea either. It feels like putting two things that don't really have a purpose being together, together.

**Comment by Elli-Skala** [comment]
As ash walkers lack any form of brain healing chemicals its highly expected this will lead to alot of tribal brain surgery

**Comment by tf-4** [comment]
Giving them things because you can, not because you should

**Comment by jjpark-kb** [comment]
> Giving them things because you can, not because you should

ashwalkers deserve everything, duh.

**Comment by jjpark-kb** [comment]
hehehehe, I have made a compromise.

**Pull request closed without merging**
