### PR TITLE
[MODULAR] Dim Lights

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Just use this to play about with the light settings, will be TM'd.

### CODE REVIEW

**Comment by CameronWoof** [comment]
Considering I _specifically_ made the PR that brightened up Citadel's lighting from "sad and pissy" to "actually lit" I'm not hugely happy about dimming it back down to sad depresso town

**Comment by Gandalf2k15** [comment]
> Considering I _specifically_ made the PR that brightened up Citadel's lighting from "sad and pissy" to "actually lit" I'm not hugely happy about dimming it back down to sad depresso town

https://preventblindness.org/blue-light-and-your-eyes/

**Comment by Gandalf2k15** [comment]
Not stale.

**Comment by Gandalf2k15** [comment]
This is now OK for fullmerge.

**Review by Azarak — APPROVED** [review]

**Pull request merged**
