### PR TITLE
[MODULAR]Give all skyrat roundstart races TRAIT_LITERATE,give primal podperson TRAIT_PLANT_SAFE

### PR DESCRIPTION
**Pull request by Sonic121x**
## About The Pull Request
due to #14128 all skyrat round start race are now illiterate,despite not having the quirk or brain trauma,causing them unable to read,write or interact with machine and handheld devices.
All speices down here have TRAIT_LITERATE add to their inherent_traits

- /datum/species/pod
- /datum/species/pod/podweak
- /datum/species/akula
- /datum/species/aquatic
- /datum/species/dwarf
- /datum/species/ghoul
- /datum/species/hemophage
- /datum/species/humanoid
- /datum/species/insect
- /datum/species/mammal
- /datum/species/skrell
- /datum/species/tajaran
- /datum/species/unathi
- /datum/species/vox
- /datum/species/vulpkanin
- /datum/species/xeno
- /datum/species/robotic
- /datum/species/teshari

these races are also affected by the /datum/species/robotic
- /datum/species/robotic/synthetic_mammal
- /datum/species/robotic/synthliz
- /datum/species/robotic/synthetic_human
- /datum/species/robotic/ipc

roundstartslime don't have their own inherent traits so they are not affected

also give primal podperson TRAIT_PLANT_SAFE

## How This Contributes To The Skyrat Roleplay Experience
not forced into illiterate is nice
podperson their TRAIT_PLANT_SAFE back,since it just make them don't require the botanist glove to work,so why not?

## Changelog

:cl:
fix: skyrat round start races being illiterate
fix: give the missing TRAIT_PLANT_SAFE to primal podperson
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
Are you sure? No one's reported this as an issue, and testing over the last day has revealed that, no, these races are not illiterate.

**Comment by mcmeiler** [comment]
Isn't illiteracy a trait given by the illiterate quirk? Seems sort of pointless and might cause issues if both traits are present, but, this is just my opinion.

**Comment by Gandalf2k15** [comment]
ye its broken

**Comment by tf-4** [comment]
> Are you sure? No one's reported this as an issue, and testing over the last day has revealed that, no, these races are not illiterate.

server isn't updated

**Pull request merged**
