### PR TITLE
Reworks Miasma Potency and Visibility

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Miasma is now 6 times more visible than before.
Miasma can now be purged when the atmos is hot enough to start a fire.
Miasma can now only give diseases when there are at >=5 moles of it breathed in instead of >0.

## Why It's Good For The Game

All it takes is 0.01 moles of Miasma in order to cause a disease. The chance to gain a disease is based on the amount of moles breathed in multiplied by some variable. In most cases you'd be safe but there is a very real chance that you can win the miasma lottery and gain a virus just by breathing in a micromole of miasma.

## Changelog
:cl: BurgerBB
balance: Rebalances Miasma
/:cl:

### CODE REVIEW

**Comment by Elli-Skala** [comment]
> Miasma production of corpses and gibs are now doubled. 
wait i thought tg fully removed miasma from thoses sources? did that get changed?

**Comment by BurgerLUA** [comment]
> > Miasma production of corpses and gibs are now doubled.
> > wait i thought tg fully removed miasma from thoses sources? did that get changed?

Considering there were references to it and still variables of it, I thought it wasn't removed. This now only affects corpse flower production.

**Comment by Elli-Skala** [comment]
also i think the rare lavaland and space vines, i dont think lavaland rnd atmos will reach the seeable cap thought but unsure

**Comment by Gandalf2k15** [comment]
As far as I'm aware TG stripped corpses of Miasma due to performance concerns. Other than that the only real place it can be found is in vines, so why the steep changes?

**Comment by BurgerLUA** [comment]
> As far as I'm aware TG stripped corpses of Miasma due to performance concerns. Other than that the only real place it can be found is in vines, so why the steep changes?

Which changes are steep?

**Comment by Gandalf2k15** [comment]
Those values are double what they used to be

**Comment by BurgerLUA** [comment]
> Those values are double what they used to be

They're doubled because that's what I did on the previous PR when it was merged to Oldbase skyrat in order to compensate for the fact that you now need to breathe in more miasma to actually get a disease.

**Comment by Gandalf2k15** [comment]
-1 from me

**Comment by tf-4** [comment]
-1, already went over the issues with Burger in discord

**Comment by hugmeorelse** [comment]
+0

@BurgerLUA I appreciate the work you do, but miasma can absolutely wreck the station on low population. Please keep in mind this is the consideration I'm following and making sure people during those times are represented. So, I'm not sure if I'm a fan of double miasma production. With that said, it does seem like you're pushing this as a sort of debuffing rework for miasma. Is that correct? 


Everything else here: 

Miasma is now 6 times more visible than before.
Miasma can now be purged when the atmos is hot enough to start a fire.
Miasma can now only give diseases when there are at >=5 moles of it breathed in instead of >0.

This is fine. I can understand the reasoning.

**Comment by hugmeorelse** [comment]
@Gandalf2k15 @tf-4 Any quick reason why we're doing -1? Personally, I'm at a +0.

What @Gandalf2k15 says:

"There's no reason to change it since it just adds to the issues with dead bodies and stuff. TG has it on point. I dislike changes to atmospheric like this since there's no reason to do it."

**This is a fair point.**

**Comment by tobjv** [comment]
+1

**Comment by BurgerLUA** [comment]
> +0
> 
> @BurgerLUA I appreciate the work you do, but miasma can absolutely wreck the station on low population. Please keep in mind this is the consideration I'm following and making sure people during those times are represented. So, I'm not sure if I'm a fan of double miasma production. With that said, it does seem like you're pushing this as a sort of debuffing rework for miasma. Is that correct?
> 
> Everything else here:
> 
> Miasma is now 6 times more visible than before.
> Miasma can now be purged when the atmos is hot enough to start a fire.
> Miasma can now only give diseases when there are at >=5 moles of it breathed in instead of >0.
> 
> This is fine. I can understand the reasoning.

The reasoning why I made this PR is because of these two cases here.

image

The brown represents miasma concentration, while the red circle represents the area inside which you can reasonably obtain a disease. On the left, is what we currently have where even the smallest trace of miasma can lead to a disease as the chances are not gated. On the right is the proposed changes. With miasma being more plentiful and more visible, it is now obvious that areas where miasma exists in them can lead to disease.

I can remove the double production if needed.

**Comment by BurgerLUA** [comment]
To say there is no reason to do this is silly. The reason why this PR exists is to make miasma easier to remove from the environment as well as makes the danger more visible to crew.

As for the dead bodies stuff, I did not re-add the functionality to give corpses miasma production. I only changed the leftover define that was not removed for some reason, so I assumed that dead bodies produce miasma. The doubling change only affects one object, and it's the corpse flower as its the only object that uses this define.

image

No other object uses the gibs define. I did not know this at the time and I just assumed that corpse miasma production was still in.

**Comment by Gandalf2k15** [comment]
Still not seeing a reason to change it, it's never been an issue.

**Comment by BurgerLUA** [comment]
> Still not seeing a reason to change it, it's never been an issue.

I literally made this PR because there were 2 shifts in a row and a bunch of previous shifts where someone received a deadly virus from miasma.

**Comment by hugmeorelse** [comment]
Is there a way you can make it so that it does not put **any** stress on atmos? It's finicky enough as is in general. If you can address that, you have my +1 (I can also veto the votes if I wanted :^), but I won't be doing that here.)

**Comment by SpaceVampire** [comment]
-1
I'm currently in agreement with TF4 and Gandalf about this.
Both in terms of the current balance not seeming to be a real issue.
Mixed with not wanting to touch the atmos code in general.

**Comment by BurgerLUA** [comment]
> Is there a way you can make it so that it does not put **any** stress on atmos? It's finicky enough as is in general. If you can address that, you have my +1 (I can also veto the votes if I wanted :^), but I won't be doing that here.)

There is no additional stress being added to atmos.

**Comment by BurgerLUA** [comment]
I removed the doubling change to make the above statement undoubtedly true instead of subjectively true.

**Comment by jinxynii** [comment]
it's a no from me

**Comment by Gandalf2k15** [comment]
Majority head admin disapproval reached. This will be closed in ~3 days.

**Pull request closed without merging**
