### PR TITLE
(mostly) [modular] adds a language for xeno hybrids via culture

### PR DESCRIPTION
**Pull request by thestubborn**
## About The Pull Request

An alternate to https://github.com/Skyrat-SS13/Skyrat-tg/pull/6574

## Why It's Good For The Game

While I personally was fine with 6574, it's been a tad controversial internally, so I'm making what I hope is the best of both worlds.
Please murder me in the comments.

## Changelog
:cl:
add: A Xeno hybrid language! Someone somewhere is gonna hate this!
add: But they may also love it!
/:cl:

### CODE REVIEW

**Comment by CameronWoof** [comment]
Please make sure cyborgs get this language as well.

**Comment by thestubborn** [comment]
> 
> 
> Please make sure cyborgs get this language as well.

do they get russian?

**Comment by CameronWoof** [comment]
> > Please make sure cyborgs get this language as well.
> 
> do they get russian?

They currently do not, but since it's a language crew can speak at roundstart, they should.

**Comment by thestubborn** [comment]
> 
> 
> > > Please make sure cyborgs get this language as well.
> > 
> > 
> > do they get russian?
> 
> They currently do not, but since it's a language crew can speak at roundstart, they should.

ok save it for all one PR then

**Comment by FranklinRipley** [comment]
Thank you for this PR. One thing I'll ask of you to change is the part that says "Hybridization of Xenomorph and Human", as not every Xenohybrid character is from a human, and there's no official lore suggesting they can only be from humans.

**Comment by hugmeorelse** [comment]
This is better than #6574

**Comment by FranklinRipley** [comment]
> This is better than #6574

Arguably yes, they made this PR because mine got too controversial among staff for some reason. I would've done something similar if I had the coding ability. It's a compromise solution more than anything.

**Review by Gandalf2k15 — APPROVED** [review]
lgtm

**Pull request merged**
