### PR TITLE
Granite's Love pass 5 of X - Whiteship edition

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

I'll be honest, i went a bit overboard and regret nothing

## How This Contributes To The Skyrat Roleplay Experience

Today we do a complete rebuild of the crashed medical NT whiteship, brought into modern(ish) style of our ships it features a fair bit more loot that before (including an atmos hardsuit and a few modules) and an extra gun.

Whiteshipruin_box_skyrat or just Crashed NT Medical ship

Old
--
image

New
--

## Changelog

:cl:
qol: massive overhaul to make the Crashed medical ship be less ugly and loot starved
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
looks good but I've some somethings I notced/concerns, review to come soon (tm)

**Comment by Zergspower** [comment]
> looks good but I've some somethings I notced/concerns, review to come soon (tm)

aye - the grill with cables ending there with pipes is fluff - and not meant to be hooked into anything

**Comment by YakumoChen** [comment]
not really feeling good about this one either. It's a TG ruin for starters (take it upstream?). 

The crashed white ship is also supposed to be game relic of white ships past, not just another blobby freighter ruin. It serves a historical reference like the abandoned satellite, rusky station, and the spaceman ship.

Don't really agree with tons of extra free loot for no reason either..

**Comment by Zergspower** [comment]
> not really feeling good about this one either. It's a TG ruin for starters (take it upstream?).
> 
> The crashed white ship is also supposed to be game relic of white ships past, not just another blobby freighter ruin. It serves a historical reference like the abandoned satellite, rusky station, and the spaceman ship.
> 
> Don't really agree with tons of extra free loot for no reason either..

this is actually SR's version, i dont know the context as to _why_ but yeah. The loot is actually something that was requested by a few different people and a couple headmins, giving a few exotic things like a modsuit upgrade here and there 

this ship was frankly an afront to god design wise let's be real

**Comment by YakumoChen** [comment]
ships back then did look pretty funky, but I'm pretty sure the tg version is almost the same.

**Comment by Zergspower** [comment]
> 

actually I think i know what ship you're talking about - 
image

**Comment by YakumoChen** [comment]
nah that's like, a different reference ship, to 2006 BYOND. I think we have a different white ship ruin map than TG's to add more loot already.

**Comment by YakumoChen** [comment]
image

Something something loot creep, something something removing history

**Comment by Zergspower** [comment]
> looks good but I've some somethings I notced/concerns, review to come soon (tm)

still needed?

**Review by Paxilmaniac — DISMISSED** [review]
Yes, many things.

If this is a whiteship, did you test to see if it can actually dock at any of our stations without damaging them? I'm going to require in game screenshots of this thing docking to at least one of the station's auxilary docks.

Second, the shape of the ship is all kinds of just... wrong? It's very jagged, and random looking, and the asymmetry of the ship itself isn't really done well.

The asteroid part itself shouldn't be a part of the shuttle, especially with how big it is. I haven't checked the areas locally but if that asteroid is using the shuttle's area and not just area passthrough then it'll fly around with the shuttle, and that'll both look and function poorly.

**Review by Paxilmaniac — CHANGES_REQUESTED** [review]
My point still stands on the shape of the ship itself though, it feels very random and not shuttle-like at parts, like the bits that randomly jut outwards around the sleeper room and mass driver.

Secondly, loot starved is not a term we should ever be using with space ruins, and the loot other skyrat space ruins have should not be taken into consideration, because they're all severely over geared as well.
- Change the atmos modsuit to be either a civilian modsuit, or a regular eva suit of some kind
- Remove the mini energy gun, the retro one can stay

**Comment by Zergspower** [comment]
I can take the mini egun out but i dont really see an issue with an atmos suit, we only ever see the syndie modsuit in ruins currently so this just makes it different.

As for the shape, i'm kind of liking the non-symmetrical designs as of late given how they're able to be so - i can tighten the sides up to be more streamlined if needed but the _before_ was a much bigger eyesore

**Comment by Paxilmaniac** [comment]
If you look around tg ruins you will find that the amount of loot they have is related to how much danger there is, every ruin like this that has no threat and is easy to just explore will only have a basic eva suit, because even an atmos modsuit is basically a free upgrade for anyone starting space exploration in a round.

**Comment by Zergspower** [comment]
ahh I see your point there - since this ruin doesnt really fit adding baddies either the med modsuit is too OP to really add here so a civvy will work

**Comment by Zergspower** [comment]
> If you look around tg ruins you will find that the amount of loot they have is related to how much danger there is, every ruin like this that has no threat and is easy to just explore will only have a basic eva suit, because even an atmos modsuit is basically a free upgrade for anyone starting space exploration in a round.


updated

**Review by Paxilmaniac — APPROVED** [review]
that's definitely better, thank you

**Pull request merged**
