### PR TITLE
[Semi-Modular] Techarmor Port, take 2

### PR DESCRIPTION
**Pull request by ShadeAware**
## About The Pull Request
Ports over Techarmor and HOS Techarmor, makes them the roundstart gear Officers get.

## Why It's Good For The Game
Stuff from the old base that was received well and its more required here than it was there on account of TG being much more lethal, and the fact that normal secvests amount to net-0 actual armor since people can just aim for your limbs and kill you, bypassing it entirely.

## Changelog
:cl:
Add: Techarmor is back, Security rejoice!
Balance: Due to budget cuts on Lopland's Border Security department, Techarmor will now be manufactured using cheaper materials. End users should not notice any difference in functionality or protective quality, but should note that locking hinges on the built in helmet may be weaker against sudden hugging. Additionally, Techarmor visors will no longer support UV shielding.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
I am suggesting a 1 week test merge before full merge for this one.

**Comment by Azarak** [comment]
Blocks smoke? Is thick material?
```more required here than it was there on account of TG being much more lethal```
Didn't you complain that it's too hard to kill people?

**Comment by KathrinBailey** [comment]
To continue with what Azarak is saying, why is this so inconsistent?

Roundstart Vest - Jack-of-all-trades chest protection with a separate helmet.
Armoury Riot Gear - Full body coverage melee-focused protection with separate helmet.
Armoury Bulletproof Gear - Bullet-focused protection for chest with separate helmet.
Roundstart Techarmor - Full body coverage jack-of-all-trades protection **WITH A RETRACTABLE HELMET, BUILT-IN INTERNALS GAS MASK AND A BUILT-IN SECHUD THAT CAN BE STACKED WITH OTHER HUDS. ALSO ROUND-START AND IN UNGUARDED LOCKERS ALL OVER THE MAP!!**

I'm going to say what I said before: Security here isn't Nanotrasen, it's Lopland security. They're akin to a private police force. There's no way **techarmor exosuits** would be standard-issue equipment. They're cheap, and that's expensive. This makes sense as an armoury item, not standard-issue gear that's given roundstart.

**Comment by ShadeAware** [comment]
> 
> 
> Blocks smoke? Is thick material?
> `more required here than it was there on account of TG being much more lethal`
> Didn't you complain that it's too hard to kill people?

This was made before your combat rebalance, Azarak. You know that as well as I do. Im simply putting the PR up so I can make changes as they come, and because my previous branch was broken beyond repair.

**Comment by Azarak** [comment]
> 
> 
> > Blocks smoke? Is thick material?
> > `more required here than it was there on account of TG being much more lethal`
> > Didn't you complain that it's too hard to kill people?
> 
> This was made before your combat rebalance, Azarak. You know that as well as I do. Im simply putting the PR up so I can make changes as they come, and because my previous branch was broken beyond repair.

PR was posted 20 hours ago. Blocking smoke and thick material is denying antagonists creative ways to fight secoffs

**Comment by ShadeAware** [comment]
> 
> 
> > > Blocks smoke? Is thick material?
> > > `more required here than it was there on account of TG being much more lethal`
> > > Didn't you complain that it's too hard to kill people?
> > 
> > 
> > This was made before your combat rebalance, Azarak. You know that as well as I do. Im simply putting the PR up so I can make changes as they come, and because my previous branch was broken beyond repair.
> 
> PR was posted 20 hours ago. Blocking smoke and thick material is denying antagonists creative ways to fight secoffs

image

as for the smoke/thick material, it also blocks some forms of quick healing (Including the new Hyposprays :eyes:), which worked as a fine trade off on the old base.

I want to see how it works as is first, but it will be changed swiftly if it turns out to be an actual problem on the new base. Additionally, Security Officers always spawn with a Security Gasmask, which **also** blocks Gas/Smoke, making this a bit of a moot point.

**Comment by ShadeAware** [comment]
Also as another aside, Im fairly certain items such as the Traitor Chempen penetrate Thick_Material. If not, I think it would be better to change them to do that, since that would make the item a bit more appealing as a tool beyond a one-stop short sleep.

**Comment by Azarak** [comment]
People dont wear gas masks at all times, fair point with the healing injections though

**Comment by ShadeAware** [comment]
> 
> 
> People dont wear gas masks at all times, fair point with the healing injections though

Security Officers wear their masks _essentially_ 24/7, although there are a few edge cases. Still, I don't believe its an issue while the mask exists as a roundstart item aswell. I could be wrong! But I want to see how it plays out first as-is.

**Comment by ShadeAware** [comment]
Also, to touch upon the consistency issue, Techarmor was supposed to be one addition in a line of PRs to update armor in complexity (read: coolness factor) with Techarmor variants. However, with the feature freeze, I was unable to do so. Im hoping to put in new armor variants after this PR goes through.

**Comment by ShadeAware** [comment]
> 
> 
> People dont wear gas masks at all times, fair point with the healing injections though

Oh, also, people don't wear their helmets 24/7 either when it comes to the Techarmor, when it was on the Oldbase. Its essentially the same thing with a different coat of paint.

**Comment by SpookyTheFox** [comment]
"that was received well and its more required here"

Whoa there, bucko! I don't know where you got that impression. This was a balance destroyer on the old base, and never should have seen the light of day. It would be even worse over here.

Security can do bounties and order better gear like everyone else if they want to dress up like power rangers, we are not giving them round start mechanics avoidance suits.

**Comment by ShadeAware** [comment]
> 
> 
> "that was received well and its more required here"
> 
> Whoa there, bucko! I don't know where you got that impression. This was a balance destroyer on the old base, and never should have seen the light of day. It would be even worse over here.
> 
> Security can do bounties and order better gear like everyone else if they want to dress up like power rangers, we are not giving them round start mechanics avoidance suits.

We seem to have very different experiences, as a majority of this is a downright lie. It was not a "balance destroyer", and the rest of this is just plain-faced insults. If you don't have anything intelligent, or for that matter, **factual** to say, don't try to say something.

**Comment by ShadeAware** [comment]
Oh for FUCKS SAKE

**Comment by ShadeAware** [comment]
image

**Pull request closed without merging**
