### PR TITLE
[READY] Ghost roles can now be configured to allow people using their prefs character. Allows this for a good chunk of ghosties

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
It will warn you not to use your station characters, or only use them if you have a strong reason on why would they'd be in the ghost role. 

Added backend for species restrictions on jobs, aswell as customizing jobs that are not for station, such as ashwalkers and pod people for the purposes of spawning them as a ghost role. Also gave the species choice window an overhaul

[X] Make this functionality
[X] Make it so you can choose non-station species in prefs for the purposes of event or ghost spawner configurations

## Why It's Good For The Game
good for RP

## Changelog
:cl:
add: You can join as lots of ghost roles as your customly created character.
/:cl:

### CODE REVIEW

**Comment by hugmeorelse** [comment]
Can you confirm that it uses randomized names?

**Comment by Azarak** [comment]
> 
> 
> Can you confirm that it uses randomized names?

It does not, would you want them to? If so which spawners in particular. 

Some spawns have a choice to choose an alias, all syndies do. So they can name themselves their ops name

**Comment by Arctaisia** [comment]
👀 I can finally make Arvai properly now

**Comment by SpookyTheFox** [comment]
This is great, I've used it for cybersun and hotel staff, and have a dedicated character for ghost roles now. I've seen a lot of other people take those ghost roles as well.

Despite clear warning text and multiple layers of prompts, I've seen a lot of people play their station characters for non station ghost roles, and not even bother to take the randomized name option. If that is to be a rule, as the text implies, it might need a discord announcement and some bwoinks for those who can't read.

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
