### PR TITLE
Whoops! Almost gave medbay hope! (Re-remaps medbay to have new stasis units)

### PR DESCRIPTION
**Pull request by FlamingLily**
## About The Pull Request
Also maps water kilo-ver and die

## Why It's Good For The Game
fix from map reset

## Changelog
:cl:
fix: Stasis units once again are stasis units and not beds.
/:cl:

### CODE REVIEW

**Comment by Trubbl3** [comment]
stasis pods are useless, just remove them all together

**Comment by FlamingLily** [comment]
Hey man, I tried, people said no 🤷

**Comment by Trubbl3** [comment]
> Hey man, I tried, people said no 🤷

then why make stasis beds so useless that they don't are even used anymore?

**Comment by FlamingLily** [comment]
Balance

**Comment by Trubbl3** [comment]
> Balance

stasis beds are balanced, they are part of a working medbay, they aren't unbalanced in any way. they are meant to used for certain types of issues

**Comment by FlamingLily** [comment]
They are meant to be used for certain types of issues, sure

But beds, practically, are used for _everything._

**Comment by Trubbl3** [comment]
> They are meant to be used for certain types of issues, sure
> 
> But beds, practically, are used for _everything._

being used for everything its a rookie issue with new doctors, its part of the learning curve. just because people don't know how medbay fully work doesn't mean that you just gut it for them

**Comment by FlamingLily** [comment]
Except there is literally no downside to using it for everything.

**Comment by Trubbl3** [comment]
> Except there is literally no downside to using it for everything.

its slow and has lower success rate, hell even lower it more if you want but again this is for the players sake, making the patient doctor experience worse for no reason or gain feels like not the best way to go at the problem

**Comment by FlamingLily** [comment]
Those downsides aren't pronounced enough to have an effect. Lower surgery success rate? literally who cares they're actively on stasis it does not matter. Slower? Sure, but inexperienced doctors will get used to the slowness, learning that surgery is just slow, instead of "oh it can be faster"

A learning curve only works if said learning curve actively demonstrates it's negative impact.

Plus, I highly doubt this makes the doctor/patient experience worse.

For one, stasis still exists for crit patients. Two, death is not bad, if you die, you're no longer stuck in hardcrit with no interaction with the game, while dead you can observe and chat with deadchat. Three, it smothers med gameplay and med rp less than stasis beds did.

**Comment by Trubbl3** [comment]
>Plus, I highly doubt this makes the doctor/patient experience worse.

It does because it will make doctor shrug off dying people and put them on a pod and forget about them 



> death is not bad, if you die, you're no longer stuck in hardcrit with no interaction with the game

If you are hardcrit and you are bored you can always deathgasp if you want to die that badly, i have hardly ever seen someone take that route



>For one, stasis still exists for crit patients

With pods you cannot treat people who are hard crit making them stay that way even longer

**Comment by FlamingLily** [comment]
> It does because it will make doctor shrug off dying people and put them on a pod and forget about them

This happens with stasisbeds too

> If you are hardcrit you and bored you can always deathgasp if you want to die that badly, i have hardly ever seen someone take that route

Sure, but that doesn't change the fact that death is not bad

> With pods you cannot treat people who are hard crit making them stay that way even longer

> If you are hardcrit you and bored you can always deathgasp if you want to die that badly

**Comment by Trubbl3** [comment]
>This happens with stasisbeds too
 
if that happens its because medbay is overwhelmed and he will be treated when someone is avalaible 


>Sure, but that doesn't change the fact that death is not bad

Then let the player choose instead of forcing them to die

**Comment by FlamingLily** [comment]
> 

> if that happens its because medbay is overwhelmed and he will be treated when someone is avalaible

Yes. the same goes for stasis pods.

> Then let the player choose instead of forcing them to die

Why? Hell, in many cases death is better cause sometimes a dead patient is easier to revive than a crit one is to save, just let what happens happen.

**Comment by Trubbl3** [comment]
>Yes. the same goes for stasis pods.

Thats a bad argument because you can actively treat someone on crit while they are on a stasis bed, unlike a pod


>Why? Hell, in many cases death is better cause sometimes a dead patient is easier to revive than a crit one is to save, just let what happens happen.

Again forcing someone to die for no reason its just making things worse for no gain, and no if it that was the case, no doctor would let a patient die because "it would be easier that way"

**Comment by FlamingLily** [comment]
> Thats a bad argument because you can actively treat someone on crit while they are on a stasis bed, unlike a pod

Crit is easy to treat. Flip the pod open, jab 'em with epi and whatever chem lowers the damage that put 'em in crit.

> Again forcing someone to die for no reason its just making things worse for no gain, and no if it that was the case, no doctor would let a patient die because "it would be easier that way"

I mean that's literally happened to me, they've let me die cause it'd be easier to revive but whatever

**Comment by Trubbl3** [comment]
>Crit is easy to treat. Flip the pod open, jab 'em with epi and whatever chem lowers the damage that put 'em in crit.

If it was that easy we would use stasis beds in the first place, people choke, might be bleeding or have chems making him stay in crit or other shenanigan

>I mean that's literally happened to me, they've let me die cause it'd be easier to revive but whatever

Its a very niche solution to let someone die to make it easier, mostly happens when theres a subpar medbay equiptment and suchs

**Comment by FlamingLily** [comment]
> people choke, 

CPR

> might be bleeding

Gauze/Bandages/Sutures

> or have chems making him stay in crit

Purge chem like penetic/multiver

**Comment by Trubbl3** [comment]
>CPR,Gauze/Bandages/SuturesPurge chem like penetic/multiver

All of those that you could do on stasis without risking the patient dying in the process now you doing a coinflip if the patient dies the moment they come out of the pod

**Comment by FlamingLily** [comment]
> All of those that you could do on stasis without risking the patient dying in the process now you doing a coinflip if the patient dies the moment they come out of the pod

Yes.

**Comment by Trubbl3** [comment]
> Yes.
So making medbay worse for no gain, making the patient die and the doctors work harder for no reason, thats not a good way to pull a PR, Medbay affects other peoples round direcly which will end up in ghost saltying in dchat for being dead

**Comment by FlamingLily** [comment]
Again, people dying is not a bad thing.

A higher rate of on-the-table casualties is, really, not a bad thing.

**Comment by Trubbl3** [comment]
> Again, people dying is not a bad thing. A higher rate of on-the-table casualties is, really, not a bad thing.

If you say that its because you don't play medbay enough, because if something happens that ends up with more than 2 dead people at once the whole system will collapse

**Comment by FlamingLily** [comment]
> If you say that its because you don't play medbay enough, because if something happens that ends up with more than 2 dead people at once the whole system will collapse

Medbay has two states. "Man this is boring there's like one guy who needs us" and "OH DEAR GOD THERE'S 40 DEAD BODIES"

Stasis pods make the "man this is boring" a little less boring, without negatively impacting the corpse-flood much more.

And if you've got two bodies, and both stasis pods are occupied with those bodies, then _you're using stasis pods wrong._ Use formaldehyde, cryostalene, or stasis bodybags for corpses.

**Comment by Trubbl3** [comment]
>Medbay has two states. "Man this is boring there's like one guy who needs us" and "OH DEAR GOD THERE'S 40 DEAD BODIES"

Which is fine because this is server its RP-Action, its bound to happen

>Stasis pods make the "man this is boring" a little less boring, without negatively impacting the corpse-flood much more.

No it doesn't its just makes things worse, stasis pods are a glorified formaldehyde patch

This PR negatively affects the action part of medbay making it worse for doctors or anyone else unfortunate enough to die when the action starts

**Comment by YakumoChen** [comment]
I still heavily disagree with the school of thought that letting people die in medbay is better (it's not actually easier to revive people than to heal from crit, and organ rot timers make death very debilitating, failing to save a life is demoralizing for medbay staff) but this isn't really the PR to make this fight once again.

**Comment by FlamingLily** [comment]
> 
> 
> I still heavily disagree with the school of thought that letting people die in medbay is better (it's not actually easier to revive people than to heal from crit, and organ rot timers make death very debilitating, failing to save a life is demoralizing for medbay staff) but this isn't really the PR to make this fight once again.

Organ rot timers are fairly debilitating.

Unless you're, y'know

competent, and fomaldehyde your corpses.

**Comment by FlamingLily** [comment]
> No it doesn't its just makes things worse, stasis pods are a glorified formaldehyde patch

If you're putting corpses in stasis pods, you're _doing it wrong._ There's your rookie learning curve for you.

Stasis body bags, on the otherhand, that is the intention
> This PR negatively affects the action part of medbay making it worse for doctors or anyone else unfortunate enough to die when the action starts

Harder =/= worse. The only complaints I've heard are that it makes medbay harder, which is fine, because stasis beds were overpowered and bad for gameplay.

**Comment by FlamingLily** [comment]
I will also add https://github.com/Skyrat-SS13/Skyrat-tg/pull/5942 is open, and aims to make it less of a random tossup and give medbay more of an ability to use stasis as a diagnosis time before the healing starts.

**Comment by YakumoChen** [comment]
> > I still heavily disagree with the school of thought that letting people die in medbay is better (it's not actually easier to revive people than to heal from crit, and organ rot timers make death very debilitating, failing to save a life is demoralizing for medbay staff) but this isn't really the PR to make this fight once again.
> 
> Organ rot timers are fairly debilitating.
> 
> Unless you're, y'know
> 
> competent, and fomaldehyde your corpses.

Formaldehyde doesn't last forever, and theres no useful way to tell when it does run out. Chem scanning isnt even functional half the time for no clear reason.

Medipens are not infinite in supply either.

**Comment by YakumoChen** [comment]
> Harder =/= worse. The only complaints I've heard are that it makes medbay harder, which is fine, because stasis beds were overpowered and bad for gameplay.

Honestly this is kind of an insult to medbay players the more I think about it.

 Stasis beds are incredibly useful for things other than managing corpses, they're needed for blood loss and toxin loss, neither of which you can treat in a pod bed, and I would MUCH rather treat someone on stasis then revive them repeatedly on a surgery table due to blood or toxin damage.

"Harder" in this case just means you're keeping people out of the round longer, which has not been the goal at all for TGs numerous medbay changes over the last few years. 

This doesnt add depth to medbay, it just replaces one crutch for another, and "just use chems" is arguably the much worse crutch. TG moved away from chem healing for a good reason.

**Comment by YakumoChen** [comment]
If you want more complaints about these other than "medbay is hardwr" here are a few:

-occupied beds are less clear than having someone on a bed. People are easily forgotten about in stasis pods because you dont see an actual body.
-Reviving people is annoying and shouldnt be an extra step because people are dying more frequently. Adding an extra required surgery (defibbing is not preferable to revival surgery and you will have to account for brain damage either way)
-the beds were already balanced since chems dont work in stasis and surgery is slower. Chems also dont work on corpses, making that treatment a moot point if they die
-Chems add depth with tradeoffs and the only chems that work on a dead body just extend the rot timer, which is not depth for medbay.

**Comment by YakumoChen** [comment]
-I cannot roleplay with a body. I cannot discuss patient treatment with a body and they cant refuse if I just fix all their problems and revive them.
-patients cant tell me what is wrong with them if they are dead, making treatment more annoying.
-this doesnt stop me from just defibbing someone and parking 12 medibots next to them, which is the bigger crutch of medbay.

**Comment by YakumoChen** [comment]
-encouraging death over stasis fosters a "just clone them" mentality where players trade a willingness to enjoy a round in a less than optimal state by giving them an out the moment they die, releasing them from responsibility like permanent brain trauma or antagonists consequences from security.

**Comment by FlamingLily** [comment]
> 
> 
> -encouraging death over stasis fosters a "just clone them" mentality where players trade a willingness to enjoy a round in a less than optimal state by giving them an out the moment they die, releasing them from responsibility like permanent brain trauma or antagonists consequences from security.

Cloning doesn't exist anymore.

**Comment by YakumoChen** [comment]
You missed the point entirely

**Comment by YakumoChen** [comment]
Chem scanning also doesnt work half the time like I said, right clicking people with an analyzer just doesnt do anything a lot of the time.

**Comment by FlamingLily** [comment]
> Chem scanning also doesnt work half the time like I said, right clicking people with an analyzer just doesnt do anything a lot of the time.

Just right click again 
> You missed the point entirely

Then please, help me get it cause frankly I genuinely don't know what you mean

**Comment by FlamingLily** [comment]
Either way, this isn't a feature, this is a fix from the map reset, discussion to be had on said feature has been had, and we came to the conclusion that stasis beds with closing lids are ideal as opposed to outright removal.

**Comment by YakumoChen** [comment]
> 
> 
> > Chem scanning also doesnt work half the time like I said, right clicking people with an analyzer just doesnt do anything a lot of the time.
> 
> Just right click again

You're quoting me like I haven't tried that before. The health scanner is buggy and doesn't work no matter how many times I click them. It working is very erratic at best.

> > You missed the point entirely
> 
> Then please, help me get it cause frankly I genuinely don't know what you mean

Letting people die gives them a chance to just exit the game or DNR, especially if reviving them just takes too long (which is often the case since revival inflates the amount of time they're staying in medbay). If they're an antagonist or they have some sort of brain trauma, it's a free excuse to just exit out and not have to deal with the consequences of the round they're in. There's no possibility of a sense of enjoyment or fun you can get out of being in a less than optimal game state or being made to roleplay things out when things go bad.

**Comment by FlamingLily** [comment]
> Letting people die gives them a chance to just exit the game or DNR, especially if reviving them just takes too long (which is often the case since revival inflates the amount of time they're staying in medbay). If they're an antagonist or they have some sort of brain trauma, it's a free excuse to just exit out and not have to deal with the consequences of the round they're in. There's no possibility of a sense of enjoyment or fun you can get out of being in a less than optimal game state or being made to roleplay things out when things go bad.

This is a problem, yes, I agree.

I'm not exacerbating it. They can still do that. They DO still do that. We've entirely axed features of the game because of this issue, that people don't RP out when things go bad or get enjoyment from it. Just because revival takes longer doesn't mean there'll be any more of that issue than there is already. Cryopods exist, people will just disconnect if something happens to them that doesn't fall within their narrow scope of enjoyment. Hell, if dying is enough to encourage you to stop playing, the amount of time taken won't matter.

If an antag gets killed and decides they don't want to deal with the consequences and just D/C, they'll do it anyway, amount of time it takes to revive notwithstanding.

**Comment by YakumoChen** [comment]
The point is being brought up since this will increase the mortality rate in medbay. It certainly does excaberate the issue. I also again disagree with the notion we want to make medbay be a more tedious process.

Theres another small point to be made that this will have to be done with every map reset and we only have a few map changes that get this treatment as a standard. Features have been axed before (from medbay no less) since we tend to only reserve hard map changes for larger stuff like security.

**Comment by FlamingLily** [comment]
honestly, I've still yet to see how it increases mortality rates to medbay's detriment at any time where it's not super mega death wave, cause death rates are high then anyway

> map reset

ok? I'm happy to maintain the maps wrt this, though

what do you think this PR even is?

**Comment by sqnztb** [comment]
So since this is still open, I'm just gonna copy/paste my comments from the initial PR.

How do you plan to address a patient who comes in with an active allergic reaction happening? The /tg/ method is to put them on stasis and blood filter for a few minutes.

And before you say...
> Diphenhydramine, pentetic, syriniver, blood filtering. [...]

Yeah none of those are actual options to keep someone alive.

Blood filtering does not work fast enough to save someone by itself. Period. Full stop. It is too slow of a surgery.

Pentetic purges the histamine and heals toxin at the roughly the same rate as the allergy reaction. It doesn't do anything for brute or oxyloss. Though if it's administered IMMEDIATELY after the allergen (e.g. the first ~8 seconds), it can save the patient just on the basis of it purging out the allergen before the histamine overdose kicks in.
Epinephrine pauses the allergy proc but any histamine in system already continues to tick away.
Syriniver/musiver does not do enough healing to counteract the toxin buildup. It doesn't do anything for the brute or oxyloss.
Diphenhydramine purges histamine at the same rate as it's produced by the allergy reaction. It doesn't do anything for the toxin, brute, or oxyloss.
Multiver (by itself) purges the histamine and heals toxin at the same rate as the allergy reaction. It doesn't do anything for brute or oxyloss.
An advanced medibot with upgrades sitting right next to you can amusingly keep your damage numbers down enough for you to survive. Until you die of multiple organ failures.

The only thing that I've found that'll keep someone from keeling over due to an allergic response is a cocktail of 100% pure 1000K seiver, salicylic/libital, multiver, atropine, and diphenhydramine. Epinephrine can also be added in, for what it's worth, but it's not required, it just makes the purging faster. And this all assumes that the patient _isn't allergic_ to any of the aforementioned. Granted it's been a long time since I've experimented, but if someone else has an easier method that:

Purges only histamine at a rate equal to or greater than 3u/tick.
Heals 5+ toxin/tick (3 from allergen processing, 2 from histamine OD)
Heals 2+ brute damage/tick
Heals 2+ oxyloss/tick

And does it all fast enough before a vital organ dies... I'm open to discussion.

**Comment by FlamingLily** [comment]
Going to work this into a much bigger general map reset fix

**Comment by FlamingLily** [comment]
> How do you plan to address a patient who comes in with an active allergic reaction happening? The /tg/ method is to put them on stasis and blood filter for a few minutes.

Put them on stasis, gather your mateirals, in this case, Diphen and an IV drip, loosen the valve on the drip to flood their system with it, un-stasis and attach.

I've tested locally, it was able to purge 30+ units of histamine in not that long of a time, much less than enough to kill. Furthermore, allergies outside of medical mis-treatment, I believe, are highly rare.

**Pull request closed without merging**
