### PR TITLE
Nerfs space dragon

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Space dragon has had our buffs removed and reverted.

They can no longer eat people.

The weight has been slashed.

And renabled.

## Changelog
:cl:
balance: Space dragons have been nerfed and renabled. They can no longer eat people.
/:cl:

### CODE REVIEW

**Comment by Arctaisia** [comment]
No more space dragon vore :waa:

Good PR though! :petpet:

**Comment by Oscari-pog** [comment]
How is the dragon gonna heal aside from the extremely slow rate on the portal though

**Comment by YakumoChen** [comment]
If you're removing the vore give them the horror ling thing where they can bite a chunk off someone for a health refill

**Comment by RatFromTheJungle** [comment]
1984

**Pull request closed without merging**
