### PR TITLE
[NONMODULAR] - Removes bananas from the game

### PR DESCRIPTION
**Pull request by SpaceVampire**
Bananas are bad because they remind me of clowns
I thought I should do my part as well

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
What?

**Comment by SpaceVampire** [comment]
> What?

What part of this do you need clarification about?

**Comment by Vizoplez** [comment]
Improper title conventions, lack of SKYRAT EDIT comments. Please rectify or close PR
-Intern dev

**Comment by GoldenAlpharex** [comment]
This makes no sense.

**Comment by SpaceVampire** [comment]
> Improper title conventions, lack of SKYRAT EDIT comments. Please rectify or close PR
> -Intern dev

Ah, sorry. I just styled it after the other PRs I was looking at here.
Can you explain how I can improve the formatting of it?

**Comment by Vizoplez** [comment]
> > Improper title conventions, lack of SKYRAT EDIT comments. Please rectify or close PR
> > -Intern dev
> 
> Ah, sorry. I just styled it after the other PRs I was looking at here.
> Can you explain how I can improve the formatting of it?

To format any nonmodular change (anything outside of the modular_skyrat folder) please firstly title the PR either [NONMODULAR] - meaning it only changes core files with no new additional edits, or [SEMIMODULAR] if it both changes core files, and creates new modular ones.
To do a skyrat edit, the usual method is to have a clear beginning and ending. For example
/* SKYRAT EDIT START - BLAH BLAH BLAH
code
*/ //SKYRAT EDIT END

**Comment by SpaceVampire** [comment]
> 
> 
> > > Improper title conventions, lack of SKYRAT EDIT comments. Please rectify or close PR
> > > -Intern dev
> > 
> > 
> > Ah, sorry. I just styled it after the other PRs I was looking at here.
> > Can you explain how I can improve the formatting of it?
> 
> To format any nonmodular change (anything outside of the modular_skyrat folder) please firstly title the PR either [NONMODULAR] - meaning it only changes core files with no new additional edits, or [SEMIMODULAR] if it both changes core files, and creates new modular ones.
> To do a skyrat edit, the usual method is to have a clear beginning and ending. For example
> /* SKYRAT EDIT START - BLAH BLAH BLAH
> code
> */ //SKYRAT EDIT END

Is that better? I think I did both of the changes that you requested.

**Comment by SpaceVampire** [comment]
> 
> 
> This makes no sense.

Again, if you can explain what part if it confuses you.
I would be happy to elaborate on it.

**Comment by tf-4** [comment]
I don't think they need to be removed. They need a nerf, sure, but not outright removal. Maybe turn down how yellow they are? something like #f9e998 would lead to much more balanced gameplay without needing to remove them totally

EDIT: Thumns up on your own PR = based

**Comment by SpaceVampire** [comment]
> 
> 
> I don't think they need to be removed. They need a nerf, sure, but not outright removal. Maybe turn down how yellow they are? something like #f9e998 would lead to much more balanced gameplay without needing to remove them totally
> 
> EDIT: Thumns up on your own PR = based

I'm willing to go ahead with your more moderate solution for the moment.
I'll reopen this if it doesn't work.

**Pull request closed without merging**
