### PR TITLE
Alien Embryos no longer grow in dead bodies 

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Alien Embryos no longer grow in dead bodies 

## How This Contributes To The Skyrat Roleplay Experience

image

Alien Embryos no longer grow in dead bodies 
## Changelog
:cl: BurgerBB
balance: Alien Embryos no longer grow in dead bodies 
/:cl:

### CODE REVIEW

**Comment by FlamingLily** [comment]
I'm sorry this wasn't already a thing??????

**Comment by SpaceVampire** [comment]
You might want to think about making them grow faster normally to compensate.
Because I see a lot of people killing the hosts by mistake, due to the fact that like.
Xenos are space-immune but they aren't, and nests tend to get depressurized.
Plus they don't have any easy way to move hosts around anymore.
Feel like I could see a lot of people death-gasping right away to avoid bursting.

**Comment by BurgerLUA** [comment]
lets not bikeshed this, please

**Comment by SpaceVampire** [comment]
> lets not bikeshed this, please

I'm not really sure what you are getting at there.
I just suggested a very minor change, that might be good to make with this.
Then stated the reasons for it.

**Comment by GoldenAlpharex** [comment]
@BurgerLUA It's failing CI, read the Integration Tests for more details.

**Comment by ForrestWick** [comment]
I like xenos tbh, but even I think this change is completely and absolutely needed. Far too often, I'll see xenos start murdering people for no reason after facehugging them, and worse I'll see them strip the person naked and remove headsets. 

Xenos steamroll a bit too hard, and I'm gonna very boldly say that larva should grow a bit slower instead of faster like Vampire suggested.

**Comment by SpaceVampire** [comment]
> Xenos steamroll a bit too hard, and I'm gonna very boldly say that larva should grow a bit slower instead of faster like Vampire suggested.

I mean, if this change is made a **lot** more people are already going to end up dying without hatching.
At the moment, it takes like at least five minutes already.
Plus the fact that if you ever end up in Crit, you can just like.
Succumb and ruin the day of the benos.

**Comment by BurgerLUA** [comment]
> @BurgerLUA It's failing CI, read the Integration Tests for more details.

Fixed, this is actually hilarious because the proc is called even if there is no owner. It was entirely possible for a larva organ to "evolve" even with no host.

**Comment by KathrinBailey** [comment]
> lets not bikeshed this, please

That isn't what a bikeshed is.
This is far too easy to gamer to get around and it encourages just murdering everyone the xenos took hostage with flamethrowers, floods and bombs.
It also means as a xenomorph, you can't crit anybody, or you've lost the larvae before they're even impregnated, because they'll just die. Even if they have a healing virus, they're just going to... succumb, gg. You've just expended an incredible amount of risk for no reward.
This will be closed unless embryo growth time (1-line change also) is drastically reduced so xenomorphs don't become less of a threat than brand intelligence.

**Comment by ForrestWick** [comment]
> > lets not bikeshed this, please
> 
> That isn't what a bikeshed is.
> This is far too easy to gamer to get around and it encourages just murdering everyone the xenos took hostage with flamethrowers, floods and bombs.
> It also means as a xenomorph, you can't crit anybody, or you've lost the larvae before they're even impregnated, because they'll just die. Even if they have a healing virus, they're just going to... succumb, gg. You've just expended an incredible amount of risk for no reward.
> This will be closed unless embryo growth time (1-line change also) is drastically reduced so xenomorphs don't become less of a threat than brand intelligence.

They will still absolutely be a threat even with this change, xenos need to not be critting people as much. They may be lethal, but they have a million ways to stun lock people as is, they dont need an extra assist.

**Comment by GoldenAlpharex** [comment]
> > lets not bikeshed this, please
> 
> That isn't what a bikeshed is.
> This is far too easy to gamer to get around and it encourages just murdering everyone the xenos took hostage with flamethrowers, floods and bombs.
> It also means as a xenomorph, you can't crit anybody, or you've lost the larvae before they're even impregnated, because they'll just die. Even if they have a healing virus, they're just going to... succumb, gg. You've just expended an incredible amount of risk for no reward.
> This will be closed unless embryo growth time (1-line change also) is drastically reduced so xenomorphs don't become less of a threat than brand intelligence.

Alternatively, we could make it so people can't succumb when they have an embryo in them. Not like if it matters anyway, they could always ghost if they really don't want to be there anymore, for one reason or another. That way, there's incentive to not go away and see if you can't get saved, and Xenos aren't too imbalanced, and actually need to use strategy instead of just doing whatever and being absolute killing machines like they are currently.

**Comment by Gandalf2k15** [comment]
Xenos currently don't win very often. Once every so often. Given the points above, I do not think this is a good change. As people have said, they will deathgasp and you know it. This makes being a xeno even more painful than it already is, given you have to wait 5 minutes to get anywhere. Assuming you catch someone as a queen without being found out in the first place. And chest bursting no longer gibs because it let's xenos use a host more than once before they die. They are already incentivised to keep them alive, and even in the most recent round, with an ERT, xenos were wiped out. And admins will normally send an ERT if requested.

**Comment by BurgerLUA** [comment]
If people are succumbing in critical condition so they don't burst, then that's an issue with the succumb verb as well as metagaming. I literally cannot believe that there are paragraphs discussion about how this is somehow a massive nerf to xenos because of [theoretical bad faith situation] here.

**Comment by SpaceVampire** [comment]
> If people are succumbing in critical condition so they don't burst, then that's an issue with the succumb verb as well as metagaming. I literally cannot believe that there are paragraphs discussion about how this is somehow a massive nerf to xenos because of [theoretical bad faith situation] here.

I mean, I pointed out how it adds a large logistical problem that didn't exist before.
Like how Xeno nests often end up getting spaced, as they aren't space proof.
But the people they drag back to it aren't, along with not having any easy way to transport people.
So. I think is is a pretty big nerf outside of [theoretical bad faith situation], as you put it.

**Comment by ForrestWick** [comment]
I feel like if Liuvik of all people is requesting this change, it should be considered. He has had a good grasp on how things work for a while.

Xenos should be punished for critting people, and I feel this does a good job of balancing them all things considered

**Comment by thestubborn** [comment]
> 
> 
> If people are succumbing in critical condition so they don't burst, then that's an issue with the succumb verb as well as metagaming. I literally cannot believe that there are paragraphs discussion about how this is somehow a massive nerf to xenos because of [theoretical bad faith situation] here.

we've removed less for theoretical bad faith situations
but, my only real question is; did you check to see if this is accurate with chestburster lore? https://avp.fandom.com/wiki/Chestburster

edit: from a quick skim...yeah, this PR seems waaaaay more in line with how xenomorphs work in their setting, facehuggers have air sacks, drones and warriors risk dragging people away in the middle of combat, dead isn't an option for them

editedit: yeaaaaaaaaaaaaaah...i think the only use xenomorphs have for corpses in their setting is eggmorphing...which is out of the scope of this pr

**Comment by KathrinBailey** [comment]
Alright, I'm not at all bothered by Xenomorph lore. I'd rather you mix MLP and Alien™ lore together if doing so made good gameplay changes.
For the following reasons I'm saying hard pass:
• Invalidates hunting away from nest entirely. You cannot stop victims screaming your location on the radio. As a hit-and-run glass cannon, pulling someone with the huge dragging slowdown is a death sentence. You're forced to stay within one tile of the victim once every ten seconds for an entire five minutes. Once you're that slow, you can't escape.
• Critting any victim, or simply allowing them the opportunity to put themselves into crit, means you have lost the larvae. You can't heal them, so they'll just succumb just before the burster is ready, because they're going to die anyway.
• Encourages killing captured crew. Not only is this a good strategy for medical, kill whoever is pregnant, epipen them, surgery, defib, it's going to result in people just shooting victims into crit just so they can deathgasp or throwing explosives into the nests specifically to kill the victims/allow them to deathgasp. Admins will have a hard time proving that they weren't aiming for the xeno. You can also just space a nest to deny xenomorph larva with ease.

Xenomorphs get absolutely slaughtered on the regular as is. They don't need a colossal nerf like this. Even if all the bad faith situations don't happen, as it stands it's still a giant nerf considering you have to drag and protect someone and stay by their side for 5 minutes, and they have already told the entire crew of your location. If you actually want this change, do a larger rework to make this not just essentially a soft xeno removal by making them less of a threat than brand intelligence.

**Comment by jjpark-kb** [comment]
Staff has discussed this and wanted this as a change.

There are additional changes that will happen in the future regarding xenos.

Also, to dispel anything: the code itself says if the stat isnt dead, stage up. Crit is not dead.

**Comment by hugmeorelse** [comment]
I don't want this to get too heated. This will be moved to an internal discussion.

**Comment by hugmeorelse** [comment]
> > If people are succumbing in critical condition so they don't burst, then that's an issue with the succumb verb as well as metagaming. I literally cannot believe that there are paragraphs discussion about how this is somehow a massive nerf to xenos because of [theoretical bad faith situation] here.
> 
> we've removed less for theoretical bad faith situations
> but, my only real question is; did you check to see if this is accurate with chestburster lore? https://avp.fandom.com/wiki/Chestburster
> 
> edit: from a quick skim...yeah, this PR seems waaaaay more in line with how xenomorphs work in their setting, facehuggers have air sacks, drones and warriors risk dragging people away in the middle of combat, dead isn't an option for them
> 
> editedit: yeaaaaaaaaaaaaaah...i think the only use xenomorphs have for corpses in their setting is eggmorphing...which is out of the scope of this pr

We don't go by canon lore, rather we go by what works gameplay-wise. For instance, in Skyrat, chest-bursters don't burst chests here, so more than one larva may be produced per person before they expire. This is to help facilitate the start of Xenomorphs, since that is the most challenging part.

Based on what I am hearing though, dead bodies may be needed for Xenomorphs, since their starts are difficult and they often times get squashed more than not at the start. So, I think some redesign of how the start works needs to be reconsidered for Xenomorphs.

**Review by Gandalf2k15 — CHANGES_REQUESTED** [review]
As Xyel stated. Xenomorphs do not need a nerf to their start, this will literally just incentivise people that roll larva to go hunter and kill as many as they can.

Their start is by far the worst part given they need hosts to spread and start actually doing xenomorph things, and to get a host you need to be incredibly lucky. Stopping them from using hosts past death means you will have scuffed them entirely and they will revert to killing people instead of working on a base. I don't know if you've ever tried playing as queen, but it is absolutely abhorrent.

As I've also already stated, the round that is in question was on Selene station, a station that had never been run before and is a xenomorph heaven. 

This is not a change that is beneficial to the direction we'd like to take Xenomorphs. Instead what I suggest is making it so if a host dies, they eject the larva in a critical condition state, where the queen must move it to one of the nests so that it can complete its growth. Restricting deathgasp is also not an option and should not be considered. This only angers players by the fact they need to go catatonic to escape the hell.

The use of an ERT does not mean the antag is overpowered. The station is allowed to lose sometimes, but a lot of the time admins will send in an ERT to nudge a station win. 

We will make any neccessary modifications to Xenomorphs internally, this request is out of scope as well.

**Comment by Gandalf2k15** [comment]
Given all of the above points, we will be closing this and discussing any changes that are required internally.

**Pull request closed without merging**
