### PR TITLE
[MIRROR] Big chungus

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/55938
--------------------
image

### CODE REVIEW

**Comment by Aphast** [comment]
big chungus

**Comment by unit0016** [comment]
big chungus

**Comment by Mothblocks** [comment]
i know a skyrat player and theyd love this change

**Comment by AlinaStarkova** [comment]
ignore this, it was a joke in the tg-coder discord channel about how maintainers speedmerge without reading the PR, it got reverted manually on tg's end

**Comment by IndieanaJones** [comment]
image

**Comment by actioninja** [comment]
> 
> 
> ignore this, it was a joke in the tg-coder discord channel about how maintainers speedmerge without reading the PR, it got reverted manually on tg's end

slander

**Comment by LemonInTheDark** [comment]
lies?

**Comment by wesoda25** [comment]
> ignore this, it was a joke in the tg-coder discord channel about how maintainers speedmerge without reading the PR, it got reverted manually on tg's end

shut up

**Comment by LemonInTheDark** [comment]
Merge this now it's a highly important fix to a hellish bug stemming from the repo name in a random md file

**Comment by SpaceVampire** [comment]
big chungus is the HRP content we need

**Comment by SweptWasTaken** [comment]
@Akrilla Merge

**Comment by dawsonkeyes** [comment]
big big chungus big chungus big chungus

**Pull request closed without merging**
