### PR TITLE
[NONMODULAR] Increases sniper projectile speed

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Sniper shots become hilariously slow at the TIDIs we tend to run at, so the speed they travel has been doubled.

## Why It's Good For The Game

Sniper is supposed to be an incredibly accurate and deadly weapon, but if people can just fucking sidestep the bullets it's uhhhhhhhhhh not as much of a precision gun?? 

## Changelog
:cl:
balance: Increased sniper projectile speed
/:cl:

### CODE REVIEW

**Comment by Ziiro** [comment]
I actually wonder if you should try this upstream. They might me amenable to the change, seeing as now ballistics suck ass compared to hitscan lasers

**Comment by Swiftfeather** [comment]
> I actually wonder if you should try this upstream. They might me amenable to the change, seeing as now ballistics suck ass compared to hitscan lasers

I can, but remember they don't generally have the same TIDI issues that we have since their servers have a much more restrictive playercap, making high pop shifts less taxing on the bullet speed

**Comment by KathrinBailey** [comment]
**YOUR INTEGRATION TESTS HAVE BEEN RUMMAGED BY MONKEY BUSINESS**
image
**PAY THE BANANA TAX OR NO COMPILE FOR YOU, OOH OOH OOH!!**

**Comment by KathrinBailey** [comment]
**OOH OOH OOH, YOU MAY PASS THROUGH CONTINUOUS CUSTOMS AND INTEGRATE, TRAVELLER.**
image

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
