### PR TITLE
The rave of the crab (Bye bye CRAB-17)

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
## About The Pull Request
It's run its course, it's not particularly funny, it doesn't add much to the experience, spams the chat of all of those that simply don't want to deal with it, and also creates a bunch of GC failures that I honestly don't feel like investigating, for a lack of caring for the feature in general.

Closes https://github.com/Skyrat-SS13/Skyrat-tg/pull/13085, because it's not necessary as we wait for a fix from upstream.

## How This Contributes To The Skyrat Roleplay Experience
Honestly, I can see the appeal for /tg/. But on here? Not a lot of roleplay comes out of worming your way in to tap a machine with your card and go back on your merry way. It might have *potential* for roleplay, but that potential basically never becomes reality. It's just... Boring, really.

## Changelog

:cl: GoldenAlpharex
del: Nanotrasen managed to stabilize its assets, so much so that market crashes related to massive asset movements are no longer possible, even through crab-related phones.
/:cl:

### CODE REVIEW

**Comment by softcerv** [comment]
This is a good change, especially because It is incredibly difficult to deal with the CRAB-17 on Blueshift.

**Comment by tf-4** [comment]
It seemed to be re-enabled entirely as an oversight from progtot so good change

**Comment by theselfish** [comment]
The purpose of the CRAB-17 is to distract the crew while a traitor does something.

Because *everyone* goes to the C-17.

**Comment by Zergspower** [comment]
> The purpose of the CRAB-17 is to distract the crew while a traitor does something.
> 
> Because _everyone_ goes to the C-17.

sadly it's never used like that, and only serves to just cause 40-50 people screaming on the radio about where is it. Causing all current RP situations to cease as we run there

**Comment by softcerv** [comment]
> The purpose of the CRAB-17 is to distract the crew while a traitor does something.
> 
> Because _everyone_ goes to the C-17.

The crab 17 also just directly filters that money into the account of however set it up, if I remember right. Which is a very powerful ability considering we now have guncargo.

**Comment by Tastyfish** [comment]
Good riddance. Money for most crew members it tight enough as it is without losing half of it before it's physically possible to get to the machine.

**Comment by Gandalf2k15** [comment]
fibe

**Pull request merged**
