### PR TITLE
Standardizes teleporter access for heads of staff

### PR DESCRIPTION
**Pull request by scrubs2009**
## About The Pull Request
The heads of staff have access to the main teleporter rooms on every station. Except for Delta and Icebox. This is....weird. Especially considering that some like the CE have access to the AI sat teleporter on **every** station. What's even stranger is that they can still get into the Delta station teleporter room by pressing the shutter button. Which he has access to....even though they can't use the door. 

## How This Contributes To The Skyrat Roleplay Experience
The tele isn't science equipment. It has never been used for experiments and during rounds it's treated just as infrastructure to be used by the heads. Even now the captain will just ask who wants the spare hand tele because it's a tool, not lab equipment. In a game without telescience keeping the teleporter locked to only the RD makes no sense ICly Or OOCly
 

Heads of staff having to hack into the teleporter room or wait for an AI to open it for them every round is just silly when it's treated as such a mundane thing. It's not something that's ever denied to them and it makes no sense to keep things working like this. Especially when it's not even consistent across maps. 
## Changelog

:cl:
fix: fixed a few things
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
no heads have tele access on these maps either.

**Comment by scrubs2009** [comment]
> no heads have tele access on these maps either.

image

RD does. Unless these maps use a different access for the teleporter rooms than "ACCESS_TELEPORTER"

**Comment by ORCACommander** [comment]
Should this not be a Map PR where the access values on the doors are changed instead of changing the baseline access list for the ce?

**Comment by thestubborn** [comment]
tbh this sounds like an upstream issue
and yeah, the access value sounds a lot cleaner

**Comment by YakumoChen** [comment]
:-1:
The RD is the head of staff in charge of the teleporter, a science-related machine, something that has been the case ever since Telescience existed and was removed. Heads of staff do not have teleporter access beyond this, aside from certain command access shutter buttons to give public use of the teleporter (generally for emergencies). The main use for this is giving the RD roundstart access to the Hand Teleporter, which is generally within their purview to take.

The CE on the other hand gets AI sat access because part of their job duties is maintaining the integrity of the AI's satellite (like other station infrastructure). This includes the teleporter and the maint room, and the exterior but not the AI chamber (RD is in charge of actual AI maintenance). The CE is not meant to have general teleporter access, and especially should not be given roundstart access to the Hand Teleporter.

**Comment by nevimer** [comment]
some maps have all the heads getting tele, others specific ones. It's agenda based of the mappers, it seems.

**Comment by YakumoChen** [comment]
The only maps I can think of that allow that sort of thing would be like Meta where heads can raise the shutters, but only the RD/Captain can use the door.

All of the TG standard maps conform to teleporter access being RD-only.

**Comment by scrubs2009** [comment]
> The only maps I can think of that allow that sort of thing would be like Meta where heads can raise the shutters, but only the RD/Captain can use the door.
> 
> All of the TG standard maps conform to teleporter access being RD-only.

Is delta not /tg/ standard? Because there CE has access to the door and shutters.

**Comment by scrubs2009** [comment]
> 👎 The RD is the head of staff in charge of the teleporter, a science-related machine, something that has been the case ever since Telescience existed and was removed. Heads of staff do not have teleporter access beyond this, aside from certain command access shutter buttons to give public use of the teleporter (generally for emergencies). The main use for this is giving the RD roundstart access to the Hand Teleporter, which is generally within their purview to take.
> 
> The CE on the other hand gets AI sat access because part of their job duties is maintaining the integrity of the AI's satellite (like other station infrastructure). This includes the teleporter and the maint room, and the exterior but not the AI chamber (RD is in charge of actual AI maintenance). The CE is not meant to have general teleporter access, and especially should not be given roundstart access to the Hand Teleporter.

Why? It's always given to either the blueshield to teleport to heads in emergencies, CMO to get wounded back to med, HOS to get near the scenes of emergencies, or the CE to ferry atmos gear back and forth to breaches. The RD is ironically the only one without any kind of actual use for it and as such they never take it. If our reason for giving them sole access to something is based around a mechanic that's no longer in the game than it just seems kind of silly, no?

**Comment by YakumoChen** [comment]
It's the principle of the matter. The teleporter is not engineering equipment. It's science equipment.

You don't have a roleplay reason listed in the section that requires it, and you don't even have a proper change log.

> Is delta not /tg/ standard? Because there CE has access to the door and shutters.

CE doesn't as far as I know, or it has some special access allowing it, since other heads do not get access there normally.

**Comment by YakumoChen** [comment]
`"hMA" = (
/obj/machinery/door/firedoor,
/obj/machinery/door/airlock/command{
	name = "Teleport Access";
	req_access_txt = "17"
	},
/obj/effect/turf_decal/stripes/line,
/obj/effect/turf_decal/stripes/line{
	dir = 1
	},
/obj/machinery/atmospherics/pipe/smart/manifold4w/supply/hidden/layer4,
/obj/machinery/atmospherics/pipe/smart/manifold4w/scrubbers/hidden/layer2,
/obj/structure/disposalpipe/segment,
/turf/open/floor/iron,
/area/command/teleporter)`

After looking it up on the Delta mapfile, there is no special access given to the CE for the teleporter on Delta station. No heads aside from the Captain, HoP (HoP gets special access to pretty much every non-department command room), and RD get regular teleporter access. Other heads of staff get Teleporter access as an extra / skeleton crew access only.

**Comment by scrubs2009** [comment]
> It's the principle of the matter. The teleporter is not engineering equipment. It's science equipment.
> 
> You don't have a roleplay reason listed in the section that requires it, and you don't even have a proper change log.
> 
> > Is delta not /tg/ standard? Because there CE has access to the door and shutters.
> 
> CE doesn't as far as I know, or it has some special access allowing it, since other heads do not get access there normally.

I think we're seeing it fundamentally differently here. The teleporter never has been treated like science equipment. It's been treated as infrastructure. ICly it's not used for experiments, it's used for moving people around. And even now that's how it's treated. The only difference is that either someone asks the AI to be let in to use it or the HOP just asks who wants it. Hell if no one touches it the most common thing to hear a captain say is "Did someone secure the spare tele". It's not science gear. It's equipment to secure and then use around the station. I think I might actually modify this to give all heads teleporter access. 

Edit: Updated the commit.

**Comment by ORCACommander** [comment]
if you continue the scope of this to be globally and not on a map by map basis, it should be given the balance tag in the changelog

**Comment by YakumoChen** [comment]
> I think we're seeing it fundamentally differently here. The teleporter never has been treated like science equipment. It's been treated as infrastructure. ICly it's not used for experiments, it's used for moving people around. And even now that's how it's treated. The only difference is that either someone asks the AI to be let in to use it or the HOP just asks who wants it. Hell if no one touches it the most common thing to hear a captain say is "Did someone secure the spare tele". It's not science gear. It's equipment to secure and then use around the station. I think I might actually modify this to give all heads teleporter access.


That's not a good reason to change this. It is science equipment, just like all the other teleporting equipment on board that science can research and build. We don't give the RD telecomms access or the CMO AI sat access because "it's station infrastructure". It's relative to a department. Access is part of the game. 

All heads without teleporter access have it readily available to add to their trim. You could play this like a roleplaying game and just get the access instead of brute forcing this with code.

**Comment by nevimer** [comment]
> > I think we're seeing it fundamentally differently here. The teleporter never has been treated like science equipment. It's been treated as infrastructure. ICly it's not used for experiments, it's used for moving people around. And even now that's how it's treated. The only difference is that either someone asks the AI to be let in to use it or the HOP just asks who wants it. Hell if no one touches it the most common thing to hear a captain say is "Did someone secure the spare tele". It's not science gear. It's equipment to secure and then use around the station. I think I might actually modify this to give all heads teleporter access.
> 
> That's not a good reason to change this. It is science equipment, just like all the other teleporting equipment on board that science can research and build. We don't give the RD telecomms access or the CMO AI sat access because "it's station infrastructure". It's relative to a department. Access is part of the game.
> 
> All heads without teleporter access have it readily available to add to their trim. You could play this like a roleplaying game and just get the access instead of brute forcing this with code.

It's command equipment behind a command door in a command area. It only makes sense for all the heads to be able to grab it, as that's how it is on half the maps.

**Comment by KathrinBailey** [comment]
> Should this not be a Map PR where the access values on the doors are changed instead of changing the baseline access list for the ce?

No, the teleporter on maps should require teleporter access to enter, not teleporter access **or** CE office access.

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Try doing this on TG first.
Either make the PR there or ask a Maintainer on TG if they'd be for or against it. If they're against it, screenshot them saying it.
If it gets denied on TG I'm fine with it being here.

**Review by GoldenAlpharex — APPROVED** [review]
I thought this was a map edit. Lol.

Edit: Still take into consideration what Kath said, I'm just okay with it if upstream says no.

**Comment by GoldenAlpharex** [comment]
@scrubs2009 Did you try checking upstream?

**Pull request closed without merging**
