### PR TITLE
Metastation Prison Remap

### PR DESCRIPTION
**Pull request by Aurelien3189**
Expands metastation prison hydro, adds cell curtains and cryo cells (again) and adds 2 isolation cells.

image

1. Hydro expanded. Adds 3 more plots of dirt, smart fridge connected to kitchen, grinder, and a small grassy outlook. Also adds chanterelle for mushroom recipes.
2. Adds freezer with meatspike and moves fridges in there.
3. Redid all the grilles to have a comprehensive grid and two grille walls (because why not)
4. Isolation hall thing expanded to have 2 isolation rooms, escape pod moved to compensate.
5. Re-adds cryopods to the end of the hall, and cell curtains

image
image

### CODE REVIEW

**Comment by NullDagaf** [comment]
Looks great.
Too great. It's a prison, not a hotel nor a mini-station.

**Comment by NullDagaf** [comment]
To elaborate.
>1. Dirt trays are enough. We don't need real ones. Also it looks more like a mini-park rather than a "Plant some weeds so you don't die of boredom" garden.
>2. Meat spike in a prison housing capital offence prisoners. This can only end well.
>3. No issues here. Great job.
>4. Look at the isolation cells. Now look at the normal ones. See anything, uh.. "Odd"?
Seriously, if I was a prisoner there I'd get myself put in isolation just to have a better room.
>5. There's a reason prisons don't give curtains in cells. Imagine if I stashed a corpse there. (No, I don't care about ERP. Use the showers.) Good on the cryo cells though.

Overall, if you're gonna change the prison, make it less comfy please.

**Comment by Aurelien3189** [comment]
> Looks great.
> Too great. It's a prison, not a hotel nor a mini-station.

We have permabrigs like those on Delta and especially Icebox which look nice and have a lot of recreational areas. The idea of how a prison 'should' look is subjective, but generally we steer away from TG's theme of bland American style prisons. The permabrig should (of course) be expected to hold prisoners in a confined area for an entire round, and an effective way of keeping them in is to have all their needs met and keep them content enough not to cause trouble.

All prisons on oldbase reflect this and most of our current maps do too.

**Comment by Raxraus** [comment]
Looking great! Giving the prisoners more space to explore and just get creative is always nice and leads to less frustration! :)

**Comment by Aurelien3189** [comment]
> Looking great! Giving the prisoners more space to explore and just get creative is always nice and leads to less frustration! :)

Almost forgot actually, this is the one prison that lacks a canvas to draw art on

**Comment by maxymax13** [comment]
put a smuggler's satchel under a floor tile with a single tower cap seed so you can use meta knowledge to make baseball bats and break out as all brigs should, smh my head

fr this is a very soulful prison, if only ours could be a quarter as interesting to look at or spend 40 minutes n

**Comment by NullDagaf** [comment]
> All prisons on oldbase reflect this and most of our current maps do too.

Even on oldbase people complained that prisons look "too much like a hotel" so that's not really an argument.

> We have permabrigs like those on Delta and especially Icebox which look nice and have a lot of recreational areas. The idea of how a prison 'should' look is subjective, but generally we steer away from TG's theme of bland American style prisons.

Give me one instance of a prison being portrayed in media as a hotel. Films, games, you name it. It's not "TG's theme", it's "how prisons are portrayed".
Also, while these "nice-looking prisons" exist, **you don't throw mass murderers/terrorists in there. Perma is for these kinds of people specifically.**

> The permabrig should (of course) be expected to hold prisoners in a confined area for an entire round, and an effective way of keeping them in is to have all their needs met and keep them content enough not to cause trouble.

Yes, "content". Not satisfied, **content.**
You don't give them every single thing they need. You give them just enough not to riot.

**Comment by Aurelien3189** [comment]
> Yes, "content". Not satisfied, **content.**
> You don't give them every single thing they need. You give them just enough not to riot.

Again, that seems very subjective on how you think prisons should be, but boring and dull doesn't really match up with how this server's permabrigs are designed. 
They're made to be comfortable, creating multiple places and ways to relax encourages interaction between all parties, and incentivises prisoners to not SSD the moment they're detained. 
Having to babysit prisoners as a guard because they're causing trouble from being too bored is a chore, and being confined to a deliberately dull place either as a prisoner role, or an antag, isn't fun either.

**Comment by KathrinBailey** [comment]
I'm just going to make this """ruling""" on prison comfiness here and list out some of what I expect from prisons.
1. The prison **must** be adequately entertaining enough for one to spend their round in. It is **not** a glorified decadent cryo room.
2. Prisoners have extremely limited capacity to make their living space not look like a ghost town in Iraq (in space). This should be kept in mind before complaining about how it looks too pretty.
3. Abandoned areas and loot rooms (preferably with randomized loot) are highly encouraged.
4. There's a heavy distinction between giving prisoners better private en-suite 3/4 double bed rooms and giving prisoners very aesthetically pleasing cells that look nice. The only thing that I think looks like it might trigger the "too pretty" response here is the garden, which... yeah that's good. Green space is proven to reduce stress and has been proven to time and time again over and over. I'd oppose something like a full prison arboretum, but a garden? Yeah, they can have it. It's good.
5. Prisons should be constructed with the capacity to accommodate gang-style gameplay.

As an addendum to point 3...
image
This is my example of an 'abandoned' area within the prison. Looks trashed. If the whole prison looked like this, no one would want to spend their shift there. If only one or two hidden rooms looked like this? That's just some extra flavor.

I'd also like to say that:
```They're made to be comfortable, creating multiple places and ways to relax encourages interaction between all parties, and incentivises prisoners to not SSD the moment they're detained.```
Is absolutely spot on, and is a perfect description of why I made point 1. Perma should not be seen as the end of the round, it encourages unhealthy behaviour of treating being caught as a traitor or ling equal to being round removed.


## In regards to this PR itself:
My only requested change from a glance is to fix where the cell and garden connect so a box of walls is formed.
image
If you're willing to do more work on this prison, please DM me, because I'd like to discuss it, otherwise, make that change and I'll give it a more thorough look and approve.

**Comment by FlamingLily** [comment]
> 2. Meat spike in a prison housing capital offence prisoners. This can only end well.
> 5. There's a reason prisons don't give curtains in cells. Imagine if I stashed a corpse there. (No, I don't care about ERP. Use the showers.) Good on the cryo cells though.

I agree with these. Prisons, as comfy as they may be, should not include any form of weaponry, or anything that can be used as a weapon. No meatspikes, no knives, et cetera. (at least, not publically accessible, abandoned maint areas, go for it)

Curtains in cells are fine, BUT, they should only be for prisoner/prisoner comfort. What I mean by that is, put cameras in their cells if you're going to do that.

**Pull request merged**
