### PR TITLE
[MIRROR] [MDB Ignore] Unit Tests for Invalid Space Turfs (Area Bullshit Edition) [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/70967
--------------------
## About The Pull Request

So, there's some bullshit with the map loader(?) sometimes where it'll let space turfs spawn in spots where we REALLY don't want space turfs. Or, it could also just be a mapper screwing up. Anyways, we might miss these, so let's set up a broad Unit Test that checks and verifies that these round-ruining snagglers do _not_ exist.

In order to help me to do this, I standardized and fixed the nomenclature such that `/area/ruin/space` is default for any map file in `_maps/RandomRuins/SpaceRuins`, as well as it's subtypes. I also touched up how we handle shuttle areas in these scenarios. This got a lot of Unit Test noise filtered out, and is crucial for its functioning. It should also be how we did it from the start anyways. I added in an UpdatePaths for any compatible change, but it was completely non-workable for some of the area type updates.

I also fixed any organic bugs that didn't require an areas type update. Cool.

Placing space turfs on IceBox:
image

Organically found issues:
image

I also added a `planetary` variable to `/datum/map_config` because I didn't like the hack I was using to see if we had a planetary map, and I'd rather it just be an explicit variable in the map's JSON.

## Why It's Good For The Game

The less times we get Space Turfs showing up on IceBoxStation, the better. It also standardizes areas a bit more, which I like (we were using some incorrect ones in the wrong spots, so those were touched up in this PR as well). Like, if it's a space ruin, we don't need to use the lengthy `/area/ruin/unpowered/no_grav` when `/area/ruin/space` does the same thing.
## Changelog
Nothing in here should concern a player (unless I broke something)

Expect a few commits as I spam unit tests a few times and play whack-a-mole with bugs.

### CODE REVIEW

**Review by Jolly-66 — DISMISSED** [review]
This needs #17622 merged first so it can pass CI.

SOURCE: CI and I'm doing mirrors for my server as well.

**Comment by Paxilmaniac** [comment]
The pr jolly mentioned has been merged

**Review by Paxilmaniac — APPROVED** [review]
Fixed up the mapping related issues, none of the test failures should be because of this pr anymore

**Comment by Jolly-66** [comment]
What Paxil said.

**Pull request merged**
