### PR TITLE
[NON-MODULAR] Guts pierrot throat

### PR DESCRIPTION
**Pull request by NullDagaf**
## About The Pull Request

title
shuttle loan bottle got replaced with tuberculosis because i have no clue what else to replace it with, if you want sthing else comment away

## Why It's Good For The Game

LRP must go or sthing

## Changelog
:cl:
del: pierrot throat is gone
/:cl:

### CODE REVIEW

**Comment by NullDagaf** [comment]
> You currently have a negative Fix/Feature pull request delta of -6. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

epic
didn't think we had that bot here

**Comment by SpaceVampire** [comment]
We aren't actually going to be using a second code-base, so it should actually be linked to some kind of config instead of that.

**Comment by NullDagaf** [comment]
> We aren't actually going to be using a second code-base, so it should actually be linked to some kind of config instead of that.

death

**Comment by MLGTASTICa** [comment]
Bad PR ,  a trait that makes you swear is not LRP at all.

**Comment by NullDagaf** [comment]
> Bad PR , a trait that makes you swear is not LRP at all.

That's correct, and if it made you swear I'd be way more reluctant to remove it.
But it doesn't, it makes people honk and we all know clowns are the scourge of humanity.

...this is not a joke PR, just so we're clear.

**Comment by Owai-Seek** [comment]
Don't replace an easily cured disease with a nukie-spawn tier virus that can wipe the station/round in a couple minutes.

**Comment by NullDagaf** [comment]
> Don't replace an easily cured disease with a nukie-spawn tier virus that can wipe the station/round in a couple minutes.

Again. If you have a better idea for what disease to put in, shoot.

**Comment by NullDagaf** [comment]
> Don't replace an easily cured disease with a nukie-spawn tier virus that can wipe the station/round in a couple minutes.

Also, as a sidenote.
You already get a bottle of magnitis in there. Meanwhile, the corpses in that loan already have spanish flu, brainrot, and beesease (Hope I don't need to explain what these do)
A smart virologist could easily get the viruses from them.

**Comment by Gandalf2k15** [comment]
This isn't an appropriate way to go about this, if you want to just remove whatever words you consider to be LRP, you can try that.

**Comment by NullDagaf** [comment]
> This isn't an appropriate way to go about this, if you want to just remove whatever words you consider to be LRP, you can try that.

First off, I'm not interested in removing random words. I want to remove the many, and MANY retarded things that don't contribute to a roleplay environment. What good does it do if an item's description omits clowns when there's a literal pandemic that makes people honk? Sure, it would be good if it was changed, but removing this seems more important.

Second, what WOULD be the appropriate way then? Yes, I shouldn't replace it with a TB bottle, but if I just removed it outright you'd scream at me for "removing things without replacing them". I used the //SKYRAT EDIT comments, I made the PR properly - then where's the issue?

**Pull request closed without merging**
