### PR TITLE
[MIRROR] Mail sorting helper, and disposals fixes [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/70861
--------------------
## About The Pull Request

image

This PR adds a mail sorting map helper, which during Late Initialization will apply a sorting location index to the mail sorting disposals pipe under them. I have replaced the varedits with all mail sorters with the appropriate map helpers. I have thoroughly tested this, making sure packages arrived to every location, where possible.

I have also fixed a few issues with the disposals network:

**Tramstation**

- One of the random maintenance segments had a place with no disposal pipes. This has been fixed
- A sorter was looking for chapel and library packages, but it actually meant to look for engineering packages
- There was no dormitory mail sorter, I have added one

**Metastation**

- There was no dormitory mail sorter, I have added one

**Icebox**

- There is no experimentor lab in icebox, but there is an "experimentation" lab, which is good enough, so I have added it as a location

**Deltastation**

- There was no dormitory mail sorter, I have added one
- Virology was not connected to the disposals network. However, on every other map, it has a one way connection. I have hooked it up just like that, so virology mail will arrive safely, and virology trash will go into space as usual.

**Kilostation**

- Genetics packages were rerouted to the psychologist office

Unsolved issue on kilostation: there is no experimentor on this station, and there is no space for a disposals in the circuits lab, so sadly, if you send a package to this destination, it will come back to the mail sorting office.

**Future improvements**

The TAGGERLOCATIONS list, which is used to retrieve the labels of the various tags, is frankly unorganizable, and hard to expand. I have delayed fixing this for a future PR.

I kinda wish to remove the sortType variable, as it is no longer necessary to have it around with these helpers, but sadly, this would ruin downstream maps, so I have no plans for this at the moment.

## Why It's Good For The Game

While mapping, having to constantly compare a comment in flavor_misc.dm to figure out what to varedit a disposal mail sorter to is rather annoying. These map helpers, similar to the access helpers, will help with this issue.

Its also good if mail actually arrives.

## Changelog

:cl:
qol: added a mail sorting map helper, to allow mappers to create disposal networks faster 
fix: fixes several non working disposal mail targets that never received their packages
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
PAIN.

**Review by Jolly-66 — APPROVED** [review]
I updated Void Raptor, asked @Paxilmaniac to just make sure my work is correct and I didn't miss anything.

**Comment by lessthnthree** [comment]
This PR blocks https://github.com/Skyrat-SS13/Skyrat-tg/pull/17755 for Tram as well.

**Comment by GoldenAlpharex** [comment]
Blame Jolly.

**Comment by Jolly-66** [comment]
I want my maintainer promotion so we can start blaming Paxil.

**Pull request merged**
