### PR TITLE
[Ice Box] The stairs outside the barbershop are now OSHA compliant, you're welcome

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request
Fix cause Cobalt snipped this by accident.

## How This Contributes To The Skyrat Roleplay Experience
Insert an OSHA joke here. Also prevents people from haphazardly falling down a Z.

## Changelog

:cl: Jolly
fix: On Ice Box, you can now no longer fall to your death wanting to wait outside the barbershop, or going to see the NT Consultant. There is now a handrail.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
I mentioned this in the automapping PR and it was never addressed. 
I mentioned a few other issues with icebox such as the rep office wiring and maint ladder not being properly linked so those also need addressed.

**Comment by Jolly-66** [comment]
> Yak said something

Please make an issue report for issues. Commenting on other PRs as well as dropping them in the Discord are prone to being ignored due to being missed.

**Comment by YakumoChen** [comment]
It was commented before merging, I can't make issue reports on test merged prs

Regardless if you're going to fix one icebox map error it'd be nice if you fixed the others that were pointed out and never dealt with before the merge

**Comment by tf-4** [comment]
> It was commented before merging, I can't make issue reports on test merged prs

Why not?

> Regardless if you're going to fix one icebox map error it'd be nice if you fixed the others that were pointed out and never dealt with before the merge

Literally like what? Link the issue reports that you're talking about.

**Comment by YakumoChen** [comment]
> Why not?

That's what PR comments and reviews are for

> Link the issue reports that you're talking about.

see above

or don't, this all seems aimed just to belittle me or something so I'm going to just stop caring

**Comment by tf-4** [comment]
> > Why not?
> 
> That's what PR comments and reviews are for

You have two maintainers telling you that's not the case. 

> > Link the issue reports that you're talking about.
> 
> see above

You need to make issue reports if you want things to be fixed. There's zero guarantee if things will be fixed if they're not issue reports.

> or don't, this all seems aimed just to belittle me or something so I'm going to just stop caring

Weird take and incorrect.

**Pull request merged**
