### PR TITLE
Modularizes & restores legacy Teshari ears.

### PR DESCRIPTION
**Pull request by CliffracerX**
## About The Pull Request

Includes variations of the mane ears to fit the new chest mane option through Fluff.

This is added through a module, LEGACYPARTS (modular_skyrat/modules/legacy_parts) in order to avoid any potential merge conflicts.  Additionally, it includes variants of the two mane styles in order to allow use of the new chest fluff.  At some point, I'd like to split their ears and feather/hairstyles into two separate things- but that's a much bigger, more complicated spritework job.

## How This Contributes To The Skyrat Roleplay Experience

This restores legacy ear/hair styles for Teshari that weren't given replacements in #20694, allowing characters who depended on those styles to continue using them.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

image
image
  
</details>

## Changelog

:cl:
add: restores legacy teshari ear/hair options
image: mane and thinmane variants for chest fluff
/:cl:

### CODE REVIEW

**Comment by SylvetteSylph** [comment]
Merge please. The Mane ears weren't resprited at all, and there is no equivalent. The ears _were_ different from Upright and didn't just add the chest mane. Removing sprites without equivalent replacement for no good reason is in fact bad, especially when a large portion of players use said sprite.

**Comment by Ebin-Halcyon** [comment]
I'll put this as bluntly as I can.

No, i'm not let people leave 'legacy' variants behind. You had over a month to bring up complaints, questions and suggestions beforehand if you ever looked into the Spriting channel where I constantly posted my updates. Leaving every single old sprite in is not an option just cause a few people used them.

I'm not hard to get ahold of, ping me on the discord or look in the spriting channel where it's almost exclusively me posting my progress on things i've been doing for long periods of time.

If you want me to re add the ear style, i'll redo them and add them, just ping me.

**Comment by SylvetteSylph** [comment]
> You had over a month to bring up complaints, questions and suggestions beforehand if you ever looked into the Spriting channel where I constantly posted my updates. Leaving every single old sprite in is not an option just cause a few people used them.

With all due respect friend, expecting people to be constantly keeping up with the development of the game is not realistic. For everyone that isn't constantly checking dev chats, the fact that there was even a planned teshari resprite was only made apparent incredibly recently.

Please consider re-adding the teshari mane ears sprite. From what I've seen, it was a frequently used ears sprite (including myself) that was completely removed without replacement. The upright ears option is somewhat similar, but does not fill the same gap.

**Comment by Kraos052** [comment]
> With all due respect friend, expecting people to be constantly keeping up with the development of the game is not realistic. For everyone that isn't constantly checking dev chats, the fact that there was even a planned teshari resprite was only made apparent incredibly recently.

I agree with the above posted comment. Not everyone is constantly keeping track of the constant updates that are being dished out in dev chats. I understand that, yes updates are posted there as to keep people notified to changes, but an @ or some sort of heads-up could have been given or even a poll presented. You know, "Hey, to anyone that plays [Species Name], how do you feel about these specific set of ears being changed?" Atleast some courtesy would have been nice. I'm unable to play my character now due to the change as I relied heavily on the ears that were removed. I'd ask as well if you could reconsider, it'd be nice to play my main character again so I can continue relaxing and enjoying SR [Skyrat] once again.

**Pull request closed without merging**
