### PR TITLE
[MODULAR] Tramstation Pipe Fix

### PR DESCRIPTION
**Pull request by DuffCreeper**
## About The Pull Request

Adds pipes so HoP Office and Detective's Office has air

## Why It's Good For The Game

Fixes air pipes near the hop office to actually connect to something
Pipes near office

## Changelog
:cl:
fix: Connected HoP's office and Detective's on Tramstation to the piping network for fresh air
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
I believe it was 100% intended that you had to take a longer route to avoid taking the tram. This just makes it so the main point of the station becomes useless if you have maint access.

**Comment by GoldenAlpharex** [comment]
Also, if you want to move mechs, you could just go through the airlocks and get through the small distance of space that's normally where you put the walkways.

I know that it's frustrating right now to have to depend on the tram, but I'm sure that it'll get better optimized and less bloodthirsty in the future, and it probably will stop being possessed by the devil and instantly killing people that mount it when it starts glitching out at some point too.

**Comment by Swiftfeather** [comment]
The tunnels between stations are wholly uneccessary, they go completely against the idea and purpose of the map's design.

**Comment by Gandalf2k15** [comment]
Please remove the access tunnels.

**Comment by DuffCreeper** [comment]
> Please remove the access tunnels.

Okay it's all gucci now Gandalf *dab

**Pull request merged**
