### PR TITLE
[MODULAR] Adds missed legless taur variant: "Slime"

### PR DESCRIPTION
**Pull request by Syrox25**
## About The Pull Request

Names are hard...

Adds the second variant shown in #19604
Was going to wait for input before pushing but was just merged, no worries. 
This adds the red sprite sheet in the comments.

## How This Contributes To The Skyrat Roleplay Experience
More options
Thinner and smoother sprite compared to "Goop"
Legless taur that fits within pencil skirt dimensions.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
Previously shown testing:

  image

image

New testing with minor left facing offset fixed:

image

image

</details>

## Changelog

:cl:
add: Adds new Taur variant: "Slime"
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
fix merge conflict and reopen

**Comment by Syrox25** [comment]
Little unsure what im doing to be honest, might be a while.

**Comment by Syrox25** [comment]
Yeah.. I think I fked it... I still have the fork and branch but I cant re-open this nor will pushing throw commits here.. 
Really dont know what to do.

Auto resolve wasnt possible, tried following gitbash method but just wouldnt accept my local repo. 
Pulled to slime branch and asked to discard commit, only 6 lines and 4 copy paste images so no big loss. Just re-added my changes and pushed to origin.. and nothing.

Yeah... I shouldnt have bothered and just asked..
Sorry :/

**Comment by tf-4** [comment]
Try now

**Comment by Syrox25** [comment]
It automatically did.. thanks.. Wouldnt let me open myself. Just need to remove the redundant code that appeared

**Comment by Syrox25** [comment]
Good to go I think?
Surprised it worked.
noted for next time.

**Review by tf-4 — APPROVED** [review]
seems fine and got spritetainer approval in the last pr

**Pull request merged**
