### PR TITLE
[MODULAR] Triple cat tails

### PR DESCRIPTION
**Pull request by linnpap**
## About The Pull Request
Adds a new triple cat tail
image

## How This Contributes To The Skyrat Roleplay Experience
*nya

## Changelog

:cl:
add: Added triple cat tail
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
I don't know why, but I can't see anything in the IconDiffBot check, are you sure the sprites are fully in there?

**Comment by linnpap** [comment]
> I don't know why, but I can't see anything in the IconDiffBot check, are you sure the sprites are fully in there?

the icondiffbot is showing the changes for me, so yeah

**Review by GoldenAlpharex — COMMENTED** [review]
I'm not sure why it's necessary to go as far as three, the sprite is passable I guess, even if I'd rather have them more in line with the current "cat" type tail.

**Comment by CandleJaxx** [comment]
> I'm not sure why it's necessary to go as far as three, the sprite is passable I guess, even if I'd rather have them more in line with the current "cat" type tail.

not that i disagree, but can't really backdown when there're kitsune tails going everywhichway

**Comment by tf-4** [comment]
Seems unnecessary

**Comment by linnpap** [comment]
> Seems unnecessary

not for my Hubie Wubie..................................

**Comment by linnpap** [comment]
i hate github

**Comment by YakumoChen** [comment]
Abort before they find out I only made the 2 tail sprite by staggering the animation and pixel shifting one

**Comment by linnpap** [comment]
OH MY FUCKING GODDDDDDDDDDDDDDDDDDDDDDDDDDD

**Pull request merged**
