### PR TITLE
Civil Dispute Officers

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

One of two changes I plan on making to security, this is the first.

Welcome to the Civil Dispute Officer, this will hopefully address the multitude of concerns relating to the new security update, the number one complaint I get is that there are too many security officers, this is bad as it means antags have no chance when the whole squad get called.

Key facts:
They do not get access to lockers.
They do not get a proper gun.
They do not get much armor at all.
They have a pepperball gun.
They do not have a bowman.

Their basic loadout:
1x pepperball gunset
1x baton
1x flash
2x cableties

Due to all of the above, this role is severely limited in ways it can deal with threats, which, is great for roleplay purposes. Antags that come across a poor Civil Dispute Officer will always have the upperhand, unless they dont. But generally this meansCivil Dispute Officer will be compelled to run away and call for help, giving the antag time to react and actually put em down, or run away as well.

As stated above, this should replace 50% of the security jobslots meaning 2 Civil Dispute Officer and 6 full seccies.

image

They report to the HoS, sergeant, and any officers.

# The Pepper Ball Gun
image

This is a shitty 8 round gun that fires mini pepper balls at people and will blind them if they ain't wearing glasses. It's really bad.

# I've finally added the revolvers to the sidearm tokens, rejoyce.

## Changelog
:cl:
add: Civil Dispute Officers! Check https://github.com/Skyrat-SS13/Skyrat-tg/pull/4205
add: 2 new guns to the security sidearm token!
/:cl:

### CODE REVIEW

**Comment by Guidesu** [comment]
speed merge speed merge

**Comment by GoldenAlpharex** [comment]
It doesn't look too interesting to play as, tbh.

**Comment by Gandalf2k15** [comment]
> It doesn't look too interesting to play as, tbh.

This will replace half of the officer slots.

**Comment by Yawet330** [comment]
> > It doesn't look too interesting to play as, tbh.
> 
> This will replace half of the officer slots.

this literally seems like a lootcrate for antags

**Comment by Vizoplez** [comment]
also wtf telebatons are so strong you can permastun with 2 of them

**Comment by Swiftfeather** [comment]
Telescopic batons are head items for a reason, they're powerful. Give them sec's current batons

**Comment by Gandalf2k15** [comment]
Gave them the normal baton.

**Comment by KaiserBlackwood** [comment]
While idea is interesting, there is 95% chance that it will be boring as hell and we won't have enough secoffs to do the job.

**Comment by Swiftfeather** [comment]
> While idea is interesting, there is 95% chance that it will be boring as hell and we won't have enough secoffs to do the job.

This is the idea.

**Comment by DiscountDirtyDan** [comment]
Why replace sec officers with this? All it's gonna mean is that experienced officers will be joining as juniors because there aren't enough open slots. This is like, the exact last thing antags or sec needed in terms of restructuring for better play. Like Yawet said, they're just gonna have their gear and comms stolen by any antag worth their salt.

**Comment by YakumoChen** [comment]
What's stopping any decent Warden or HoS from giving Jrs a locker and a sidearm token?

This needs to come with some kind of reduction in antag power as well if the gearset is going to be enforced, 

To be honest I'd rather have a set of officers with a more classical loadout like a low-ammo disabler and baton if we're going to have officers not designed to deal with antags but to deal with more typical non-antag crimes.

**Comment by YakumoChen** [comment]
The main problem with antags on SR is that 90% of the time an antagonist and security will start doing a roleplay and within the span of a few minutes either backup will be called (not always by the same officer) or any officers who happen to be passing by will join in the standoff. 

There's also a pretty silly arms race and this doesn't really alleviate it except that it forces someone to buy them proper equipment.

**Comment by Gandalf2k15** [comment]
I don't think you guys realise how much this will alleviate the issue with the arms race and general balance of security. I'm probably going to make it so that these guys can't redeem sidearm tokens. And we're never going back to disablers. I'm going to follow this up with an IAA PR and an antag debuff PR.

**Comment by DiscountDirtyDan** [comment]
> I don't think you guys realise how much this will alleviate the issue with the arms race and general balance of security. I'm probably going to make it so that these guys can't redeem sidearm tokens. And we're never going back to disablers. I'm going to follow this up with an IAA PR and an antag debuff PR.

The arms race? You mean the one with the role that has projectile deflection and a delimbing gun?

**Comment by Gandalf2k15** [comment]
> > I don't think you guys realise how much this will alleviate the issue with the arms race and general balance of security. I'm probably going to make it so that these guys can't redeem sidearm tokens. And we're never going back to disablers. I'm going to follow this up with an IAA PR and an antag debuff PR.
> 
> The arms race? You mean the one with the role that has projectile deflection and a delimbing gun?

Scarp has always been a thing and silverhand gun Is a meme

**Comment by hugmeorelse** [comment]
While I did agree junior officers would be a good idea, I never agreed on 50%. I removed that from the description.

**Comment by YakumoChen** [comment]
> 
> 
> > I don't think you guys realise how much this will alleviate the issue with the arms race and general balance of security. I'm probably going to make it so that these guys can't redeem sidearm tokens. And we're never going back to disablers. I'm going to follow this up with an IAA PR and an antag debuff PR.

Disallowing certain roles from redeeming tokens doesn't really make sense and is bad for non-security roles who want to redeem tokens (antagonists)

also:

"Hey warden can you get me a sidearm token gun?"

**Comment by YakumoChen** [comment]
> 
> 
> I don't think you guys realise how much this will alleviate the issue with the arms race and general balance of security. I'm going to follow this up with an IAA PR and an antag debuff PR.

Honestly also I disagree pretty heavily on both points. I like the idea of "secoff only equipped to handle non-antag crimes" but inevitably they'll just be better equipped the moment there's a decent threat on the table.

I _strongly_. **Strongly** do not recommend IAA as someone who has seen multiple attempts over multiple codebases to do it. IAA always ends up more destructive than regular traitors, and doubly conflicts with the whole "open ambitions" thing going on with Skyrat.

An antag debuff I could get behind, but I would actually much rather see more strongly encouraged teamwork between antagonists alongside it, such as with the reinclusion of Changeling Hivemind and giving traitors better reasons to team up

**Comment by YakumoChen** [comment]
Also take away the baton, the flash does the same thing and the baton is a very strong weapon in its own right. A flash and a secHUD (not Sunglasses). Replace it with the pepperspray if you can.

**Comment by Ross-665** [comment]
I feel at a glance, the idea is so so, BUT if you dig deeper and have a longer think, cutting the sec team in half to make 4 people basically security specific assistants is going to make the balance of sec vs antags swing hard in favour of the antags, since it means they will have 4 people who can't respond to anything more than two people getting drunk and having a fight in the bar. All it would take is one competent traitor to beat their ass in a fight, disarm and strip them in maints.

**Comment by YakumoChen** [comment]
> 
> 
> I feel at a glance, the idea is so so, BUT if you dig deeper and have a longer think, cutting the sec team in half to make 4 people basically security specific assistants is going to make the balance of sec vs antags swing hard in favour of the antags, since it means they will have 4 people who can't respond to anything more than two people getting drunk and having a fight in the bar. All it would take is one competent traitor to beat their ass in a fight, disarm and strip them in maints.

I think that's the point

**Comment by Ross-665** [comment]
> I think that's the point

And I feel that would be counterproductive. Last time I checked, the game was for RP and fun, not "gamer" antag wins.

**Comment by GoldenAlpharex** [comment]
> > I feel at a glance, the idea is so so, BUT if you dig deeper and have a longer think, cutting the sec team in half to make 4 people basically security specific assistants is going to make the balance of sec vs antags swing hard in favour of the antags, since it means they will have 4 people who can't respond to anything more than two people getting drunk and having a fight in the bar. All it would take is one competent traitor to beat their ass in a fight, disarm and strip them in maints.
> 
> I think that's the point

Yeah, but that actually sucks for the other antagonists. If a singular antag can take out the entirety of security, 1. It's not fun for security, 2. It's not fun for the other traitors that would've enjoyed some action instead of just killing regular crew because all of security is already dead.

I'm not sure this is the proper way to tackle the issue.

I much more think something along the lines of Deputies would work better, where they _have_ to stay in their assigned department unless it's, like, Red alert or all of Security is dead. That way, there's three security officers that are just in their departments, making sure things are in order there, and the rest of the security team is actually roaming around. That way, departments feel a bit more secure to be in, and the antagonists still have a good chance at taking them out, as it's just one officer versus them, until they call for backup, I suppose. Or you could decide to attack them in Brig directly or anywhere that's not engineering, medbay or cargo, and have three less officers to worry about.

**Comment by YakumoChen** [comment]
> 
> 
> > I think that's the point
> 
> And I feel that would be counterproductive. Last time I checked, the game was for RP and fun, not "gamer" antag wins.

That doesn't make sense. This seems to be more of a role designed to actually do RP and fun as opposed to "gamer antag fighting". The PR states they're literally designed to not fight antags. Once you take away the baton (take away the baton Gandalf) the only "loot" they really have is a comms key, which you can get for a meagre 2 TC anyway (or steal)

**Comment by YakumoChen** [comment]
> I much more think something along the lines of Deputies would work better, where they have to stay in their assigned department unless it's, like, Red alert or all of Security is dead. That way, there's three security officers that are just in their departments, making sure things are in order there, and the rest of the security team is actually roaming around. That way, departments feel a bit more secure to be in, and the antagonists still have a good chance at taking them out, as it's just one officer versus them, until they call for backup, I suppose. Or you could decide to attack them in Brig directly or anywhere that's not engineering, medbay or cargo, and have three less officers to worry about.

Limiting where players can go is the direct opposite of fun and only works for roles like Warden who have a substantial role to do that involves staying in their assigned space.

(there's also four officer stations, not three)

**Comment by Ross-665** [comment]
> That doesn't make sense. This seems to be more of a role designed to actually do RP and fun as opposed to "gamer antag fighting". The PR states they're literally designed to not fight antags. Once you take away the baton (take away the baton Gandalf) the only "loot" they really have is a comms key, which you can get for a meagre 2 TC anyway (or steal)

Your probably right, it's just my gut feeling says this change it would make things less enjoyable, rather than more.

**Comment by GoldenAlpharex** [comment]
> > I much more think something along the lines of Deputies would work better, where they have to stay in their assigned department unless it's, like, Red alert or all of Security is dead. That way, there's three security officers that are just in their departments, making sure things are in order there, and the rest of the security team is actually roaming around. That way, departments feel a bit more secure to be in, and the antagonists still have a good chance at taking them out, as it's just one officer versus them, until they call for backup, I suppose. Or you could decide to attack them in Brig directly or anywhere that's not engineering, medbay or cargo, and have three less officers to worry about.
> 
> Limiting where players can go is the direct opposite of fun and only works for roles like Warden who have a substantial role to do that involves staying in their assigned space.

We could always find something to have them do in their department. The point is, at this point, if you only leave them with a gun-version of a pepper-spray and a flash, what's the point of not just having deputized assistants? They wouldn't have that sidearm token restriction or what not. I'm just really not sure how well this is going to work in practice.

**Comment by YakumoChen** [comment]
Deputized assistants can still be antags, whereas security-spawning players cannot. Sec has no incentive to deputize outside of extreme emergencies both OOC and IC (where security is literally made up of contracted private security)

"Giving security something to do in assigned departments" leads to slippery slopes where security is doing x-department's job instead of the actual x-department players.

**Comment by GoldenAlpharex** [comment]
My main gripe with this is, if security isn't fully-staffed (which happens more often than you'd think, lately), the antags will just breeze through them. They already can with the current amount of security, they just have to buy a few key items and they can easily wipe them out, I've seen it happen, and I'm sure I'm not the only one that's seen it happen.

Personally, I think that we're trying to hold the antagonists by the hand too hard and it's becoming a little crazy. They don't really have much of a reason to not just entirely rely on traitor items currently, as the gear from the uplink is just insanely strong. It just feels too easy for antagonists with Extreme ambitions to kill just about anyone, as long as they're even remotely good at combat.

I think that this would only go in that direction, instead of crippling security like this, just remove one or two slots from Security Officers and lower the amount of TC traitors have access to, and it should eventually even out.

**Comment by GoldenAlpharex** [comment]
> Deputized assistants can still be antags, whereas security-spawning players cannot. Sec has no incentive to deputize outside of extreme emergencies both OOC and IC (where security is literally made up of contracted private security)
> 
> "Giving security something to do in assigned departments" leads to slippery slopes where security is doing x-department's job instead of the actual x-department players.

I agree with you, and I don't pretend to know what would work the best, I just honestly think this is another step in the wrong direction.

**Comment by YakumoChen** [comment]
Stronger admin enforcement of ambitions (currently admins just seem to rubber stamp every single EXTREME ambition without checking, leading to 4/5 EXTREME traitors vs a half-staffed security), along with less single-antag power and more antags overall would be a step in a much better direction. 

Currently antags can get a laundry list of high power items and go to town, changelings are by default extremely difficult to fight and fully get rid of since their revive timer is very low.

On the other hand Gandalf is right that antags often get fucked by engaging in RP while The Boys are called in to gang up on lone antags until half the security department is on scene, but the solution to that is forcing security to stretch its resources more thinly with more problems, and give antagonists more teamwork-oriented encouragement to create less of a "one antag versus four sec" problem

**Comment by GoldenAlpharex** [comment]
> Stronger admin enforcement of ambitions, along with less single-antag power and more antags overall would be a step in a much better direction.
> 
> Currently antags can get a laundry list of high power items and go to town, changelings are by default extremely difficult to fight and fully get rid of since their revive timer is very low.
> 
> On the other hand Gandalf is right that antags often get fucked by engaging in RP while The Boys are called in to gang up on lone antags until half the security department is on scene, but the solution to that is forcing security to stretch its resources more thinly and give antagonists more teamwork-oriented encouragement.

Yeah, I agree with that. I mean, I'm trying to think of ways for antagonists not to get cucked every time they try to roleplay their way out of things, and it mostly boils down to player behavior, at this point. Some people will rather act in good faith, and that's sadly not the case for everyone, but I don't know how good of an impact gutting security in this way will have on the players, especially with a diminutive name like "Junior Officers".

**Comment by Ross-665** [comment]
> Stronger admin enforcement of ambitions (currently admins just seem to rubber stamp every single EXTREME ambition without checking, leading to 4/5 EXTREME traitors vs a half-staffed security), along with less single-antag power and more antags overall would be a step in a much better direction.
> 
> Currently antags can get a laundry list of high power items and go to town, changelings are by default extremely difficult to fight and fully get rid of since their revive timer is very low.
> 
> On the other hand Gandalf is right that antags often get fucked by engaging in RP while The Boys are called in to gang up on lone antags until half the security department is on scene, but the solution to that is forcing security to stretch its resources more thinly with more problems, and give antagonists more teamwork-oriented encouragement to create less of a "one antag versus four sec" problem

Then wouldn't the idea GoldenAlpharex mentioned earlier, where say, 3 officers who are treated like the warden and assigned to specific departments (medical, science and engineering for example) be better than 4 security assistants?

**Comment by YakumoChen** [comment]
>Then wouldn't the idea GoldenAlpharex mentioned earlier, where say, 3 officers who are treated like the warden and assigned to specific departments (medical, science and engineering for example) be better than 4 security assistants?

The Warden has their own set of interesting things to do in the brig (manage prisoners, manage equipment, manage detainees, play Overwatch with cameras and suit sensors). Confining security officers to departments does not confer any of those benefits. It is not fun.

>Yeah, I agree with that. I mean, I'm trying to think of ways for antagonists not to get cucked every time they try to roleplay their way out of things, and it mostly boils down to player behavior, at this point. Some people will rather act in good faith, and that's sadly not the case for everyone, but I don't know how good of an impact gutting security in this way will have on the players, especially with a diminutive name like "Junior Officers".

I like the idea in theory but I don't think it will actualize well, and would NEED to come with an immediate reduction of overall antagonist power.

I think 1-2 junior officers replacing security slots would be a better mix though.

**Comment by GoldenAlpharex** [comment]
> I like the idea in theory but I don't think it will actualize well, and would NEED to come with an immediate reduction of overall antagonist power.
> 
> I think 1-2 junior officers replacing security slots would be a better mix though.

As I said, or at least, tried to say, I'm not against giving it a try, but it DEFINITELY needs a better name. Deputies would probably be better than Junior Officers, so you don't actually sound like a security assistant.

**Comment by YakumoChen** [comment]
You know, it WOULD be fun thinking about having Security Officers pairing off with Jrs like some kind of buddy cop film

**Comment by MLGTASTICa** [comment]
> While I did agree junior officers would be a good idea, I never agreed on 50%. I removed that from the description.

I honestly believe that junior officers are not a good addition as long as players do not have the freedom to self-antag to some degree , it will just lead to people picking up junior officer then being armed as a normal officer as soon as the alert level hits blue.It would basically change very little in terms of security power unless the junior officers have their duties set clear.

**Comment by FlamingLily** [comment]
On the one hand, I like the idea of sec that's less unga and more RP, as well as sec that focuses more on the crew crimes and not validing the antags, but on the other...

I don't think mechanically enforcing that is the way to go.

I think this is a policy issue, not a code issue.

**Comment by Oscari-pog** [comment]
This just halves the size of the security team and adds a group of assistant wranglers

**Comment by dominuslucian** [comment]
to be honest adding more hierarchy isn't going to fix the issue with security; we learned that with the sarge role.  
if you really want to add junior officers go for it but don't make them consist of half the fucking security force, it's not going to go down well.

**Comment by Gandalf2k15** [comment]
# THE NEW RATIO IS GOING TO BE 75% E.G. TWO OF THE OFFICER ROLES WILL BECOME JUNIOR OFFICER ROLES

**Comment by bloons3** [comment]
BeeStation added these (as Deputies), and basically their entire use is to allow people to be promoted to Validhunters without actually requiring any trust in those people.

Hard pass.

**Comment by YakumoChen** [comment]
I still think you should take away the baton, and replace it with a flash. Batons are strong weapons.

**Comment by LeonY24** [comment]
lol wtf?
how about to tell antags go get good and robust enough? they've got a lot of shit to exterminate the whole crew, security is already castrated and you situation is getting worse (ammunition cutting, stunbaton removal, shitty gunpowder making guns jam like ass for 1 spent mag).

**Comment by DiscountDirtyDan** [comment]
So I'm coming around to this update, I like the sound of it after it was explained in better detail, what they'd do, how effective they'd actually be, and so on, but I have one problem. They barely look at all like law enforcement. Whether it's the point or not, having law enforcement that literally looks like assistants, like straight up assistants, is a problem in my opinion. I think something even as basic as some brighter colored blue stripes or something would help them stand out. Because sec is primarily identified by their armor and helmets ~~and validhunting~~ these "officers" are hardly going to stand out in my opinion.

**Comment by Gandalf2k15** [comment]
> So I'm coming around to this update, I like the sound of it after it was explained in better detail, what they'd do, how effective they'd actually be, and so on, but I have one problem. They barely look at all like law enforcement. Whether it's the point or not, having law enforcement that literally looks like assistants, like straight up assistants, is a problem in my opinion. I think something even as basic as some brighter colored blue stripes or something would help them stand out. Because sec is primarily identified by their armor and helmets ~and validhunting~ these "officers" are hardly going to stand out in my opinion.

Good point, I'll give em some brighter blue stripes and a brighter hat.

**Comment by SpookyTheFox** [comment]
Several major points jump out right away now that I have seen this in play. Security has two techfabs now, at least on Delta. Tech fabs outside the armory need to go. Another very prominent issue is department guards. It seems multiple officers can be assigned to a department right now. There does not need to be two medical guards and a security medic. Also, consider limiting the department guard slots to only the civil dispute officers. There's no reason to have a SWAT team member in every department booth. On the topic of the civil dispute officers, there is no reason for them to have ranged weapons. Especially not a pepper ball weapon, as those are balanced around eye protection, which is far too obvious and difficult to obtain for non-security. The pepper ball gun needs to go. About the only application it makes sense for, is the security medic, who might handle prisoners and really should not be armed anyway. Overall though, pepper mechanics are too strong, and this should really not exist.

**Comment by Gandalf2k15** [comment]
> Several major points jump out right away now that I have seen this in play. Security has two techfabs now, at least on Delta. Tech fabs outside the armory need to go. Another very prominent issue is department guards. It seems multiple officers can be assigned to a department right now. There does not need to be two medical guards and a security medic. Also, consider limiting the department guard slots to only the civil dispute officers. There's no reason to have a SWAT team member in every department booth. On the topic of the civil dispute officers, there is no reason for them to have ranged weapons. Especially not a pepper ball weapon, as those are balanced around eye protection, which is far too obvious and difficult to obtain for non-security. The pepper ball gun needs to go. About the only application it makes sense for, is the security medic, who might handle prisoners and really should not be armed anyway. Overall though, pepper mechanics are too strong, and this should really not exist.

This is overshot by a mile. The pepperball gun is completely non lethal and you're asking me to get rid of it. The department security officers are a TG change and I'm absolutely fine with it. Right now we're looking at CDOs being the minority. Techfabs being duplicated is because of a recent map reset. Not this 0R.

**Comment by DiscountDirtyDan** [comment]
CDOs should be able to set timers and issue fines. Otherwise, they're just kind of like, vaguely armed lawyers I guess?

**Comment by projectkepler-ru** [comment]
I remember when this was first test merged/merged at all.
It was surreal to think about that I was around at those time

**Comment by toontownlover54-create** [comment]
FUCK SKYRAT FUCK XYEL FUCK THIS PEDOPHILE!!

**Pull request merged**
