### PR TITLE
Ports pollution from Horizon - Original PR: https://github.com/hrzntal/horizon/pull/468 (Made by Azarak)

### PR DESCRIPTION
**Pull request by Gandalf2k15**
# This was not made by myself. Azarak made it and you can find it at the original PR: https://github.com/hrzntal/horizon/pull/468

## About The Pull Request

This is a direct port of https://github.com/hrzntal/horizon/pull/454 and all credits go to Azarak over there at Horizon.

It also includes the fixes from:
https://github.com/hrzntal/horizon/pull/468
https://github.com/hrzntal/horizon/pull/469
https://github.com/hrzntal/horizon/pull/488

I only ported and modulraized it. All credit goes to Azarak for the system.

Original PR description from Horizon:

Smoking cigarettes makes either smoke or cannabis smoke (if drugs are smoked)
Smoking vapes makes thicker, but more pleasantly flavored smoke
Turf fires and bonfires make smoke and deadly carbon pollution, which can be avoided by laying down to a degree
Grilling foods emitts related pollutants to them
Chemical reactions can make pollutants
Added perfumes which you can find in loadout
Janitor starts with air refreshers in his locker
The bartender starts with candle packs, and can purchase scented candle packs in his drobemat
Waste and garbage objects make an unpleasant scent
Spilling blood creates a subtle metallic scent
Lighting matches creates sulphur scent
Drills create thick dust as they drill
Vended tea, coffee and hot choco smell like it

Pollution dissipates slowly over time, twice as fast on planetary turfs

Admins have a Spawn-Pollution verb for bussing

image
image
image

## My comments
This is a very interesting and cool system, I think it could add a lot of potential for RP.

This has also adapted Azaraks liquids turf fire system to utilize this, upstream already has it, so I added it to this one.

You can use portable air scrubbers to dissipate the pollution faster.

https://github.com/hrzntal/horizon/pull/454

# DNM pending Test merges and stress tests.

## Changelog
:cl: Azarak
add: The sense of smell - Ported from Horizon
add: Added a pollution system, which is used for air pollutants, such as cigarette smoke, deadly carbon pollution, perfumes, food scents etc. See #7453 for all changes
/:cl:

### CODE REVIEW

**Comment by ForrestWick** [comment]
This sounds way too easy to grief with and more of a pain and annoyance than a feature that adds value to the game

**Comment by FlamingLily** [comment]
Rebase to horizon when :^)

**Comment by Gandalf2k15** [comment]
Some bars now have little ashtray-sized pollution scrubbers so you can smoke near em.

Washing items will now remove the associated smell.

Portable scrubbers now remove pollution in the air!

**Comment by Arctaisia** [comment]
Lovely PR, adds something I liked on Horizon code, and makes managing air quality an actual reason for trying not to smoke too much, to put out fires quickly, etc. And nice to see some collaboration between servers! :petpat:

**Comment by ReynTheLord** [comment]
This... has high odds of causing a mess.

**Comment by Gandalf2k15** [comment]
> This... has high odds of causing a mess.

nice pun

**Comment by ZephyrTFA** [comment]
This subsystem is still being refined at Horizon; given that Skyrat is a much larger and more active codebase make sure you report bugs originating from it or uses of it to Azarak.

**Pull request merged**
