### PR TITLE
Adds the Borb plushie

### PR DESCRIPTION
**Pull request by LeChatGuide**
adds the borb plushie 

## About The Pull Request
Adds the adorable Borb plushie to the station !

## Why It's Good For The Game

Because it's cute and we always need more plushies for our local snowflakes (me)
## Changelog
:cl:
add: Adds the borb plushie.
imageadd: adds the plushie_borb icon.
/:cl:

### CODE REVIEW

**Comment by LeChatGuide** [comment]
huh , looks like it's not good , I'm going to try and see what's wrong

**Comment by LeChatGuide** [comment]
all good now .

**Comment by Gandalf2k15** [comment]
Ahhh, see if someone in main code help can help you make this modular

**Comment by LeChatGuide** [comment]
oh , alrighty then , I'll take a look

**Comment by LeChatGuide** [comment]
alright , it's modular now and should work fine ...

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
