### PR TITLE
[Modular]Removes ERCD

### PR DESCRIPTION
**Pull request by Vizoplez**
## About The Pull Request
Maintainer request, makes killing malf AI and other AI based antagonists too easy (it works through cameras and w/ mesons)

## Why It's Good For The Game
AAAAAA

## Changelog
:cl:
del: Advanced/Experimental RCDs are gone :crab:
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
Nooo , how am i gonna cuck AI's that doomsday at round end and don't bother making a defense that is not more than just slap doors without putting protection or something.

**Comment by SpookyTheFox** [comment]
I did not even realize these were obtainable by the station. I don't think the industrial RCD had this functionality on old base. Note that borg and mounted RCDs can still decon Rwalls, by design, and for this reason. And a single case of it nailing an antag is not a reason to remove it, especially when malf AI has an ability to detonate RCDs.

**Comment by Gandalf2k15** [comment]
I requested this, and it's not about one scenario. This tool is far too powerful from a lot of balance stand points. Not sure why TG would allow it. This is infact more powerful than the admin RCD, absolutely unbased.

**Comment by SpaceVampire** [comment]
Late to the party, but this isn't something that TG did.
It was one of the broken items added by this PR.
https://github.com/Skyrat-SS13/Skyrat-tg/pull/2852/files

**Pull request merged**
