### PR TITLE
[MODULAR] Adds new trek loadout stuff, fixes old trek loadout stuff.

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Refactors the old trek stuff that was commented out for our loadouts since it hadn't been updated to the new format we do things, also adds more things that were missing from our files that were originally a part of the loadouts.

I renamed all of the "VOY uniform, medsci" etc to "VOY - Medsci", making the items 100% more readable in the list, which is in the uniform tab... so people should know they are uniforms in the first place... makes ya think doesn't it?

Clothing is working with digi sprites just fine, and is all under misc uniform and misc hats!

image

Also to clean up the code significantly and reduce clutter, I made a new trek uniform subtype, since tg HAS trek uniforms already, just not a lot of them. This makes it completely modular. 
```
/obj/item/clothing/under/trek/modular_skyrat
	icon = 'modular_skyrat/master_files/icons/obj/clothing/under/trek.dmi'
	worn_icon = 'modular_skyrat/master_files/icons/mob/clothing/under/trek.dmi'
	worn_icon_digi = 'modular_skyrat/master_files/icons/mob/clothing/under/trek_digi.dmi'
```
This should make adding more trek clothing incredibly easy in the future, in case anyone really *needs* to have that one outfit.

UPDATE: 
ALSO ADDS JACKETS! THE JACKETS ARE IN!
image
image
THEY EVEN HAVE WORKING BUTTON UP/DOWN options, via a right click option. This is only for the traditional style, modern style don't get button up options (the spirtes didn't exist). 

We're now fully prepared for anyone to use these items, ALSO the clothing was all moved to the job category in order to keep misc categories for loadouts cleaner. The hats can stay, hats are fine. 

Also adds paramedics to be able to take the medsci items as loadouts, it must have been an oversight on oldbase that they were forgotten in the inclusion list. 

We're now fully prepared for any nerds that might want to use the trek clothing!

image

Sprites from Citadel! 

😘 ~~This goes to you hartmann~~

## Why It's Good For The Game

More loadouts! and this shit was already in the code, just commented out! Quality of life as well, the code for this was messy and a big ugly comment block, now the formatting is much better

## Changelog
:cl:
add: Added a few new trek clothing items that were listed in the loadout but not present in code.
fix: Fixes old trek loadout to be up to date and work.
/:cl:

### CODE REVIEW

**Comment by Swiftfeather** [comment]
> You currently have a negative Fix/Feature pull request delta of -10. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

I'm gonna fucking destroy you

**Comment by Gandalf2k15** [comment]
Nice

**Comment by KasparoVy** [comment]
Bless mon bless, I love the trek uniforms and the digi sprites look dope too. Thanks much!

**Comment by Gandalf2k15** [comment]
Yo can we get enterprise ones too?

**Comment by Swiftfeather** [comment]
> Yo can we get enterprise ones too?

@Gandalf2k15 they're already in.
https://github.com/Skyrat-SS13/Skyrat-tg/blob/cde5785e59c31b4421cc53920a188bd6138c2d4d/code/modules/clothing/under/trek.dm

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
