### PR TITLE
[SEMI-MODULAR] EORG teleport, round 2

### PR DESCRIPTION
**Pull request by Kush1Push1**
## About The Pull Request

Added option in game preferences, which in toggled state teleports players after emergency shuttle's docking to Central Command in the CTF zone with random loadouts.

It's the second PR, since the previous (#15051) was closed and abondoned for too long to be reopened.

### How it works

1) Emergency shuttle undocks from the station. The game checks if EORG config is toggled on (which can be changed in config file or by admins in server tab). 
Players will recieve a message about coming round-end event and their current status of EORG preference. If a text at end of the message will be clicked, their status will be changed (be/not be at EORG).
2) After the shuttle's docking with CC, there will be the teleportation of all players. If the EORG config is still on and a player still has the preference, they will be moved to CTF area.
3) All wounds and restrains will be removed.
4) Their gear will be deleted and replaced with one of random presets (so there is no point to prepare for EORG).
5) All EORG banned players are still in rotation to marked zone.

## How This Contributes To The Skyrat Roleplay Experience

EORG can be a thing for players who wish to have it. After all, everyone want to fight in this game from time to time. Anyone else will have their round end at central command/their respected areas.

## Changelog

:cl: SishTis
add: Added EORG teleportation option in players game preferences. In toggled state, it teleports the player to CTF after round end with random loadout. Admins also have a button in Server's tab to disable it for some events.
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
EORG is removed.

**Comment by Kush1Push1** [comment]
There were issues with "early continue" from [Zonespace27](https://github.com/Zonespace27). I don't understand and ask for explanation what's the issue.

**Comment by Kush1Push1** [comment]
> EORG is removed.

Well, that was fast.
I added it back since many players still want to have some fun. Not everyone want to roleplay in the last two minutes of the round. Since there will be teleportations to CTF (moved from thunderdome), it shouldn't be an issue.

**Comment by Kush1Push1** [comment]
Some screenshots how it works:

<details>

In case of teleportation, a player gets a random loadout, full revive and a motivatonal message.
UQHL2gOq6s

In other case, a player stays where they are.
dreamseeker_Wz5HmBSc61

</details>

**Comment by Lukaster42** [comment]
Outstanding, however, I think the EORG arena needs a custom map.

**Comment by Kush1Push1** [comment]
> Outstanding, however, I think the EORG arena needs a custom map.

I don't think such thing as mass mayhem in the last 2 minutes of a round need a personal map, to be honest

**Comment by Lukaster42** [comment]
> > Outstanding, however, I think the EORG arena needs a custom map.
> 
> I don't think such thing as mass mayhem in the last 2 minutes of a round need a personal map, to be honest

I assure you it is, but maybe not now, maybe later.

**Comment by hugmeorelse** [comment]
We made our decision. No EORG in any form. We are not interested. I have repeated this time and time again.

**Comment by hugmeorelse** [comment]
I informed @Low3 about this PR, @Lukaster42 and @Kush1Push1. Hopefully, they can TM it downstream. However, this will not be merged into Skyrat proper, unless there is a config option to turn it on and off that way each server can choose. However, I will need to consult with my maintainers on how maintainable this is.

**Comment by Kush1Push1** [comment]
> We made our decision. No EORG in any form. We are not interested. I have repeated this time and time again.

I don't think all players have the same mind about one term.
The update will not harm those who want to roleplay after the round end and will help those who want to just have some fun. After all, the server is a mix of action and roleplay.

**Comment by Kush1Push1** [comment]
> I informed @Low3 about this PR, @Lukaster42 and @Kush1Push1. Hopefully, they can TM it downstream. However, this will not be merged into Skyrat proper, unless there is a config option to turn it on and off that way each server can choose. However, I will need to consult with my maintainers on how maintainable this is.

There IS an option to turn it off in configs and even in server's tab. I wrote it down in the description.

**Comment by Kush1Push1** [comment]
> I informed @Low3 about this PR, @Lukaster42 and @Kush1Push1. Hopefully, they can TM it downstream. However, this will not be merged into Skyrat proper, unless there is a config option to turn it on and off that way each server can choose. However, I will need to consult with my maintainers on how maintainable this is.

<details>

opera_StCx1bGBy0
opera_IA0UN2id7D
opera_G8vS8YgGUl
opera_N2rO32wTOo

</details>

**Comment by YakumoChen** [comment]
I could suggest again to switch this to an auto-CTF preference. CTF is in the game and a ghost role activity, respawning players onto a random ctf beacon I feel satisfies the goal of this without it being "EORG"

**Comment by YakumoChen** [comment]
Nothing stops players from ghosting as soon as the round end text appears and clicking a CTF beacon so automating it shouldn't be an issue under current policy.

**Comment by Kush1Push1** [comment]
> Nothing stops players from ghosting as soon as the round end text appears and clicking a CTF beacon so automating it shouldn't be an issue under current policy.

There is a difference between EORG and actual CTF.

**Comment by Kush1Push1** [comment]
Just in case: a short guide how to turn off EORG teleportation for all players with this PR in config.

1) Open config/scyrat/skyrat_config.txt
2) Find a lind with "ALLOW EORG"
3) Place before the words the # symbol. It should look like this: 
```
## Toggles round-end teleportation of players with checked EORG preference
#ALLOW_EORG
```
4) Save file. Wait for the restart.
5) You don't have EORG anymore. It can be turned on server-side with Server's tab before a round end.

A video-guide:
<details>

explorer_JKXNK7OYvz

</details>

**Comment by YakumoChen** [comment]
> There is a difference between EORG and actual CTF.

One is banned from the server, the other is not

**Comment by Kush1Push1** [comment]
> > There is a difference between EORG and actual CTF.
> 
> One is banned from the server, the other is not

I don't see any types of even potentional issues to a server's quality in case of my realisation.

**Comment by GoldenAlpharex** [comment]
After talking with Low3, it seems like Fluffy Frontier equally has no interest in this feature, so I sadly don't see any reason to have this. It'll just be dead code. Sorry.

**Pull request closed without merging**
