### PR TITLE
Black Executive Suitskirt Alt Undershirt Fix

### PR DESCRIPTION
**Pull request by Mryourface13**
## About The Pull Request
Adds a pixel to allow hiding of all undershirts under the uniform.
Broken:
Exec_suitskirt issue1

Fixed:
Exec_suitskirt issue fixed

## How This Contributes To The Skyrat Roleplay Experience
It allows my character and other characters to not have an errant pixel when trying to use the formal clothes with any size of undershirt.

## Changelog

:cl:
fix: Can now use Black Executive Suitskirt Alt with all undershirts
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
I was going to remove this item in #14491 due to being sprited on TG yet implemented here.  If you've an issue with that just say as much on that PR and I'll look into updating the sprite to modern standards and re-adding it fully as our own, but if you're fine using the normal executive suitskirt in place of the alt then, uh- dont, comment, I guess?

**Comment by Mryourface13** [comment]
> I was going to remove this item in #14491 due to being sprited on TG yet implemented here. If you've an issue with that just say as much on that PR and I'll look into updating the sprite to modern standards and re-adding it fully as our own, but if you're fine using the normal executive suitskirt in place of the alt then, uh- dont, comment, I guess?

So you'd delete it in Modular in order to make a new PR for /TG/ that updates it in their base?

**Comment by ghost** [comment]
> > I was going to remove this item in #14491 due to being sprited on TG yet implemented here. If you've an issue with that just say as much on that PR and I'll look into updating the sprite to modern standards and re-adding it fully as our own, but if you're fine using the normal executive suitskirt in place of the alt then, uh- dont, comment, I guess?
> 
> So you'd delete it in Modular in order to make a new PR for /TG/ that updates it in their base?

the opposite, i'd make it fully modular because god knows TG wont touch it for a while

**Comment by Mryourface13** [comment]
How about I close the PR and we talk about this in DMs. I'm new to coding and I'd love to just do some more stuff as practice and whatnot

**Pull request closed without merging**
