### PR TITLE
Reverts wall-mushroom outbreak, take 2

### PR DESCRIPTION
**Pull request by desertmote**
## About The Pull Request

Revets #20264

## How This Contributes To The Skyrat Roleplay Experience

https://github.com/Skyrat-SS13/Skyrat-tg/assets/77534246/0bab54f7-4136-4f9f-833d-f66efa17527e

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
Code_Fu2oN9oVgm

</details>

## Changelog

:cl:
del: Removed wall-mushroom outbreak event
/:cl:

### CODE REVIEW

**Comment by desertmote** [comment]
I mean come on, at least meteors can hit me and RR my sorry engineer ass. Wallmushroom is just doing the most agitating part of construction in spacestation 13. Assembling and disassembling walls and god forbid inaccessible corner walls. In a forced interaction that takes you away from what you want to do. RR meteor joke aside. AT LEAST I GET TO REBUILD AREAS, NOT WELD WALLS AND WELD AND WALLS.

**Comment by lessthnthree** [comment]
As the resident engineer coder, I agree with Reggie. The event has had adjustments but at the end of the day it doesn't seem to have any redeeming qualities. Other engineering type events are a better use of that event slot.

**Comment by ghost** [comment]
It had a custom announcer?? 😬 man wth

**Comment by chemistrymain2** [comment]
It hasn't been fun to deal with at all due to how it's designed-it interacts with no department and nothing works except for a welder.

Might as well go.

**Comment by SpaceLoveSs13** [comment]
With electric welders gone, and having the need to act first(without worrying about fuel), this should go away indeed, until there is a better way to combat wall fungi.

**Review by lessthnthree — APPROVED** [review]

**Pull request merged**
