### PR TITLE
[Semi-Modular] #7004 but Modularized and consistent with the ID cards.

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
you ever get so fed up with something stupid after you've been up for way longer than you ever should so you make a PR on github

yes

Recreates #7004 but makes it as modular as possible; and also making the icons consistent with card.dmi. Bluesec included!
image
image
image
image
~~No don't ask me why our perfectly fine blue centcom was beseetched by goon-green, that's for the nanotrasen rep coders to find out.~~

## Why It's Good For The Game
Same reasons as #7004 

## Changelog
:cl: Seris02 & Blu
qol: Hud icons extend to the rest of the skyrat-specific, onstation jobs.
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
Drafting this as I pulled the gun a little too early and
as they say
'that shit broke'

**Comment by unit0016** [comment]
I just realized I forgot to add one thing they had that I didn't

brain dumb

**Comment by Seris02** [comment]
Why does the security medic icon have red in it

**Comment by unit0016** [comment]
> Why does the security medic icon have red in it

It's actually unchanged from the file there I've replaced in doing this. No, I have no idea why it's like that.

**Comment by Seris02** [comment]
I'm gonna come right out and say, ahhh
these icons need to be changed
blue sec icons
really fuckin bad idea, they're meant to be a different color for a reason, I don't want to start mistaking regular officer for HoS
and also the security medical icon should be changed to a blue cross if we're actually going to be sticking with it, and the rep colour should be a nanotrasen colour + a different icon.

also, vanguard operative icons are needed too.

**Comment by Seris02** [comment]
All of which is provided in my PR, which I can just change to be modular.

**Comment by unit0016** [comment]
> All of which is provided in my PR, which I can just change to be modular.

Security is blue. The IDs are blue and grey, (The HUDs were too for a bit but that was changed for visibility and eventually just outright removed) The department is blue and grey, etcetera. ~~Also the cross has twinges of blue so this is /probably/ Intentional but Gandalf's on break so there's no point in asking. ~~
**While this is absolutely a problem with mindshields in play**; _(look at that 10ish pixel difference!)_ It's the design decisions that.. exist. ~~Whether they're stupid is another matter, but there's a reason I have my corner and stick to it when it comes to playing the game.~~
image

**Comment by Seris02** [comment]
Yeah I can't fucking tell the difference, I have no clue which one is HoS and which is a sec officer
I'm being completely serious

**Pull request closed without merging**
