### PR TITLE
[Modular] One Last, Last. LAST DS-1 Tweak.

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Adds Genetics per someone's suggestion. Tried looking into cargo code to make a syndie cargo, but sadly it's destinations are hardcoded - subtype isn't overriding that. Also fixes a stay airlock cyclelink helper, adds a training bomb in security, and a limbgrower in medical.

## Why It's Good For The Game
Stray cyclelink bad. Genetics.. convenient.

## Changelog
Omitted

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Why omit the changelog? It's there to document changes, and you made changes, even if it's for a ghost spawner, I still feel like it should be followed through.

**Comment by Ducky-Momo** [comment]
no cargo? shit. and i'm guessing if this is the last tweak then it's a hard no on getting the frigate back, netrunner's chamber, some type of way to safely interact with the station?

**Comment by GoldenAlpharex** [comment]
> no cargo? shit. and i'm guessing if this is the last tweak then it's a hard no on getting the frigate back, netrunner's chamber, some type of way to safely interact with the station?

It's not meant to interact with the station, that's the whole point.

**Comment by unit0016** [comment]
> Why omit the changelog? It's there to document changes, and you made changes, even if it's for a ghost spawner, I still feel like it should be followed through.

I have a habit of spamming out miniscule fix/tweak PRs, and don't want to inflate the changelog because I made 6 PRs for the same thing.

**Comment by Ducky-Momo** [comment]
> 
> 
> > no cargo? shit. and i'm guessing if this is the last tweak then it's a hard no on getting the frigate back, netrunner's chamber, some type of way to safely interact with the station?
> 
> It's not meant to interact with the station, that's the whole point.
just a _little_ would be nice though. i miss hearing them because when you're alone or there's only one person around doing something else, it gets lonely and too quiet

**Pull request merged**
