### PR TITLE
[modular]Proclamation of the Cheems Republic

### PR DESCRIPTION
**Pull request by thestubborn**
## About The Pull Request

restores cheems
any complaints are to be directed to [https://forum.skyrat13.tk/viewforum.php?f=77](https://pastebin.com/Q6pF74PF)

## Why It's Good For The Game

In the name of God and of the dead generations from which she receives her old tradition of nationhood, Cheems, through us, summons her children to her flag and strikes for her freedom.

Having organised and trained her manhood through her secret revolutionary organisation, the Funny Dog Brotherhood, and through her open military organisations, the Cheems Volunteers and the Skyrat Citizen Army, having patiently perfected her discipline, having resolutely waited for the right moment to reveal itself, she now seizes that moment and supported by her exiled children in America and by gallant allies in Europe, but relying in the first on her own strength, she strikes in full confidence of victory.

We place the cause of the Cheems PR under the protection of the Most High God, Whose blessing we invoke upon our arms, and we pray that no one who serves that cause will dishonour it by cowardice, inhumanity, or rapine. In this supreme hour the Cheems PR must, by its valour and discipline, and by the readiness of its children to sacrifice themselves for the common good, prove itself worthy of the august destiny to which it is called. 

or, to quote @Spc-Dragonfruits 
"Cheems saying stuff like "Shomtgun crate!" "Burbger.." etc. is part of what the pet represents. It's pretty much the only special thing about him as a pet."
"It's MRP-HRP, this is not BayStation either. Let people have fun. If you want 100% serious job simulator just pop in at one of the /fully serious HRP servers/"
"We're not a fucking fully serious MUH IMMERSHUN job simulator. This is Skyrat. We're TG-Based MRP-HRP. The server name is neither Aurora or Bay. It's established that we want silly stuff too, we want people to have fun."

## Changelog
:cl:
add: cheems :) has been resouled, he's been restored to his rightful place
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
This changelog is very poor. Besides that, I've already made my stance against this very clear.

> "Cheems saying stuff like "Shomtgun crate!" "Burbger.." etc. is part of what the pet represents. It's pretty much the only special thing about him as a pet."

If the only value in Cheems is him saying "hee hee bonk no hormy" then it should just be removed. You can call yourself a MRP-HRP server, or you can add shit like this. Can't do both.

**Comment by thestubborn** [comment]
> 
> 
> This changelog is very poor. Besides that, I've already made my stance against this very clear.

i mean changelog doesn't work anyway and shows no sign of being fixed
and I know
I heard your points
still disagree with em :)

**Comment by GoldenAlpharex** [comment]
I disagree with this PR, -1 from me.

**Comment by Arctaisia** [comment]
-1 from me aswell, because this isn't what the server is about. We're aiming for MRP-HRP by doing things like stopping people say poggers ICly, or other meme terms. This somewhat contradicts that by adding something into the game that itself is a direct reference to a meme, not a subtle one, or one that seems original/hard to find/achieve, but one that's out in the open. 

And Cargo already has a pet, we don't really need to give them even more. I usually offer constructive criticism where I can, but I'm finding it hard here without just.. Disagreeing.

**Comment by thestubborn** [comment]
i'm trying not to respond to stuff for...dunno, just felt like putting out a pr without that


i'd rather a pet have a personality over...not having one
cheems was a small part of oldbase that should be back
to quote Franz Kafka, "Don't bend; don't water it down; don't try to make it logical; don't edit your own soul according to the fashion. Rather, follow your most intense obsessions mercilessly."

**Comment by linnpap** [comment]
based pr

**Comment by theOOZ** [comment]
the dog's 'thing' is being overweight. what youre trying to restore is the meme picture, stop dancing around it. like 2/3 of the pets are nothing special, this one has dog AI which is relatively enough.

**Comment by Arctaisia** [comment]
> the dog's 'thing' is being overweight. what youre trying to restore is the meme picture, stop dancing around it. like 2/3 of the pets are nothing special, this one has dog AI which is relatively enough.

^
They're Markus now, glory to Markus,,,

**Comment by thestubborn** [comment]
i'm sorry
i'm sorry
i'm sorry

**Comment by hugmeorelse** [comment]
Can we have a discussion about this? @thestubborn I'm the host. I am always happy to work with developers to try to make things work, so give me a poke and let's see if we can come up with a satisfactory discussion.

**Pull request closed without merging**
