### PR TITLE
Ports Food Preferences from Nova Sector

### PR DESCRIPTION
**Pull request by theselfish**
Ports https://github.com/NovaSector/NovaSector/pull/352 .

## About The Pull Request

Adds food preferences back- mostly how they were before TGUI prefs, but now at least 80% more modular!

Has a few checks to make this less powerful and straight up better than the usual species food preferences like the version of yonder:

    You HAVE to pick one toxic food- that means something that your character absolutely detests, for whatever reason!
    You HAVE to pick three disliked foods- something that they'd rather not eat, but can stomach a bit of in a pinch!
    And you can pick three favorite foods- something your character very much enjoys eating, and will get mood buffs from!
    A points system as well.
        You start with 0 points.
        Default values are worth 0 points.
        Making something worse than default gives up to two points,
        Making something better than default takes up to six points.
        Extremely rare food types are worth 0 across the board, and also don't count towards likes.
            These were either part of a quirk, or are literally so rare, you'll (or the chef'll) have to go out of your way to get a hold of it.
        Disgusting food types have inflated values, so you have to trade in multiple more common foodtypes in order to be able to pick one!

I've done this in like... six hours overall now, so folk might want to talk this over with me to figure out a good set of point values.
Food is equally nutritious regardless of if you like or dislike something.

## How This Contributes To The Skyrat Roleplay Experience

Being able to represent varying food cultures is quite nice, no?

This time with hopefully less folk picking literal garbage as a like, cause they now have to declare two things they don't like in exchange!

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl: Some Random Owl
add: Added a food preference system! It has a few checks, but otherwise, gives you a huge amount of freedom to decide your tastes! Give it a peek in your character menu!
del: The quirks: Deviant Tastes, Pineapple Hater, Pineapple Liker, and Vegetarian have been hidden as a result meaning they will be removed from all characters who has taken these quirks to compensate for the fact you can set your preferences for food rather than take these quirks
/:cl:

### CODE REVIEW

**Review by Useroth — CHANGES_REQUESTED** [review]
image

**Comment by theselfish** [comment]
> image

No idea.

**Comment by Useroth** [comment]
Theirs is .tsx, you ported it as .jsx

**Comment by theselfish** [comment]
> Theirs is .tsx, you ported it as .jsx

Ahhhhh!

**Pull request merged**
