### PR TITLE
[MIRROR] Tatami [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/71288
--------------------
## About The Pull Request

We have a bamboo floor, but it has smoothing and looks more like a tribal mat. Meanwhile the hotel on the centcom map uses an iron floor with 4 overlays to resemble tatami. 

Now the bamboo floor has 3 new variants of tatami with different rim colors.

image

Also the hotel room tiles are replaced with proper tatami.

image

And the new tiles have no smoothing and can be rotated to make correct tatami layouts.

121732aea8e3d4f86bbb92e1a7479318

## Why It's Good For The Game

This was an absolute disgrace.

## Changelog

:cl:
fix: fixed bamboo floor tile in-hand icons not being used
imageadd: added tatami of 3 types to the bamboo floor variants
/:cl:

### CODE REVIEW

**Review by Tastyfish — APPROVED** [review]
Approving code

**Review by Jolly-66 — APPROVED** [review]
Map check out, we don't use CC as much anymore, but I don't see any issues.

Note to other maints: I reran Trams integration.

**Comment by Tastyfish** [comment]
> Map check out, we don't use CC as much anymore, but I don't see any issues.
> 
> Note to other maints: I reran Trams integration.

Trams is failing because of a bad cyclelink id in hydroponics.

**Review by Jolly-66 — APPROVED** [review]
map feex

**Review by Paxilmaniac — APPROVED** [review]
approval number 4

**Pull request merged**
