### PR TITLE
[MIRROR] Experi-Sci: Techweb nodes may now require you to perform "scientific" experiments

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/54093
--------------------
:cl: bobbahbrown, Qustinnus, MrDoomBringer, ArcaneMusic
 Add: Experi-sci. Some nodes in the techwebs will now require specific experiments to be done. Some will also give a discount to specific nodes
 del: Active point generation has been removed from techwebs
/:cl:

For anyone interested in contributing to this system heres some of the technical docs:

https://hackmd.io/iUPwl8eDRZeErurQ8lxS4Q

This PR adds a framework, and some content, for a new system called experi-sci. It's a semi-rework of how RnD works, and consists of the addition of experiments. These experiments consist of a specific task the player has to perform to complete the experiment, this can range from getting some specific slime extracts, getting a specific vatgrown creature, making a specifically sized bomb, making some specific furniture from specific materials, and more.

Some of these experiments, are set in stone, and are the same each round, but some are different each round.

These experiments can offer two things: Some are required to unlock specific tech nodes. And some offer a discount to tech nodes.

The plan is that I add a lot more types of experiments to this PR, both ones that can be performed by science, but also ones that can be done by people like botanists. For example, botany science might require a plant with a specific amount of traits. This is something the botanist needs to do, and it would end up benefiting the botanist as he would gain access to new tools.

Another thing is that this PR will remove active point generation, instead of working on point gen, scientists will now be working on experiments. In some situations, the experiments can give discounts to tech nodes, which still lets you save points by doing work.

Below is a picture of the UI of the experi-sci; a hand-held device for scanning objects for experiments. There's also going to be a machine that will be used to scan experiments that need to be taken apart, but that hasn't been finished yet.

image

Please post any suggestions you might have for experiments that you think could be fun, or that would fit specific tech nodes. Preferably, experiments are not too static, and can be fun in multiple rounds (For example, getting a sample from Ian would be a fun experiment; you'd always need to get it from the HoP, whether he agrees or not, which could make for some funny situations, but an experiment thats just busy work with no interaction is not as interesting.)

todo:

- [x] Add dissambly scanner

- [x] Add modular tablet RnD app

- [x] Improve RnD console UI for experiments

- [x] Add a looot more experiments

### CODE REVIEW

**Comment by Arctaisia** [comment]
I support this, gives a use for the Destructive analyzer like baycode does, and gives us a reason to reintroduce problem computers as well as other point-generators. That is,if they use the DA, and not some weirdnew machine. Either way, looks nice. And the botanic experiments mention gives me an excuse to keep xenobotany on my map :eyes:

Might need to remove LRP-sounding nodes, if not done yet

**Comment by unit0016** [comment]
> I support this, gives a use for the Destructive analyzer like baycode does, and gives us a reason to reintroduce problem computers as well as other point-generators. That is,if they use the DA, and not some weirdnew machine. Either way, looks nice. And the botanic experiments mention gives me an excuse to keep xenobotany on my map 👀

...It is a weird new machine. destructive_scanner and destructive_analyzer are different.
pain.

**Comment by Arctaisia** [comment]
> > I support this, gives a use for the Destructive analyzer like baycode does, and gives us a reason to reintroduce problem computers as well as other point-generators. That is,if they use the DA, and not some weirdnew machine. Either way, looks nice. And the botanic experiments mention gives me an excuse to keep xenobotany on my map 👀
> 
> ...It is a weird new machine. destructive_scanner and destructive_analyzer are different.
> pain.

:notlikethis:

**Comment by bobbah** [comment]
skyrat coders please observe my funny design document on hackmd i think it will assist you https://hackmd.io/iUPwl8eDRZeErurQ8lxS4Q?view (it was in the original PR but i am emphasizing its usefulness)

**Pull request merged**
