### PR TITLE
[MODULAR] Reverts the tool sprites for Engineering Borgs back to TG sprites

### PR DESCRIPTION
**Pull request by DuffCreeper**
## About The Pull Request

Reverts the aesthetic tool changes for engineering borgs back to TG sprites to maintain visual clarity

## Why It's Good For The Game

Currently the TauCeti icons are.. rather weird and make it hard to select the tool you want at first glace. So they are set back to TG sprites to help maintain visual clarity. Being too unique and not maintaining the style sucks, especially that screwdriver wtf

From
Before
To
After
## Changelog
:cl:
qol: Engineering Borgs now return to using the TG sprites for their tools
/:cl:

### CODE REVIEW

**Comment by Vizoplez** [comment]
I dont even know why we changed them

**Comment by Gandalf2k15** [comment]
Heya, just remove the lines of code you've changed there, those are overrides, removing them will simply revert the tools to using the standard filepath.

**Comment by DuffCreeper** [comment]
> Heya, just remove the lines of code you've changed there, those are overrides, removing them will simply revert the tools to using the standard filepath.

O i'm dum

**Comment by SpaceVampire** [comment]
Can the rest of us get the TG sprites for tools as well, please?
For you know, the exact same reason.

**Pull request merged**
