### PR TITLE
[SEMI-MODULAR] Persistent commendation hearts

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Save count of the amount of commendation hearts received

image

## How This Contributes To The Skyrat Roleplay Experience

You get to see how many times you've been hearted!

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

image

</details>

## Changelog

:cl: LT3
add: Commendation hearts are now recorded at the end of the round
/:cl:

### CODE REVIEW

**Comment by softcerv** [comment]
I wonder if this is something that could work upstream.

**Comment by lessthnthree** [comment]
> I wonder if this is something that could work upstream.

I offered it upstream, they didn't want it.

**Comment by softcerv** [comment]
> > I wonder if this is something that could work upstream.
> 
> I offered it upstream, they didn't want it.

rip

**Review by tf-4 — CHANGES_REQUESTED** [review]
I don't think there should be a leaderboard for this. General counting is fine as long as it's only shown to the player that receives it

**Comment by Elli-Skala** [comment]
One step closer to the rep system

**Comment by YakumoChen** [comment]
r/heartedcirclejerk

**Comment by lessthnthree** [comment]
I'll redo this without leaderboard when I have time.

**Pull request closed without merging**
