### PR TITLE
[WIP] Sol Common, Arabic, Spanish

### PR DESCRIPTION
**Pull request by Draganfrukts**
## About The Pull Request

This PR adds three new human-centered languages - two brand new, one from the old school.
WIP

## How This Contributes To The Skyrat Roleplay Experience

WIP. More character customization and backstory opportunities. WIP.

## Progress

- [x] Port code for Sol Common
- [x] Add icons for Sol Common, tie it to Humans
- [ ] Add fake space Spanish language I have to think the name of
- [ ] Add fake space Arabic I have to think the name of
- [x] Add icons for FSSLIHTTTNO and FSAIHTTTNO 

## Changelog

:cl:
add: Added Sol Common, a language naturally spoken by Humans.
/:cl:

### CODE REVIEW

**Comment by KathrinBailey** [comment]
Not gonna lie we already have a few languages for humans, why do they need more when the majority of players (anthromorphs) only get Galcom?

**Comment by SpaceVampire** [comment]
I'm a sucker for Sol Common, but I really do think this is just language bloat.
Most of the ones we already have don't even get used.
You have Common, Lizard (Helped by Ashwalkers existing), Vox (Metagang), and...
Sometimes people briefly speak the others for flavor, but never in any serious amount.
I really just don't see any need for Spanish or Arabic, or honestly Sol Common.
Race-linked languages are just better, because you can guess who can speak em.
Like if you see a Lizard, Vox, Felinid, Xeno, whatever. (Honestly, I think they should be granted by default.)
Genetic languages have the issues of being unclear in their presentation.

**Comment by thestubborn** [comment]
bet you wont make an "english" language that sounds like "tea, colour, armour" to nonspeakers

bitch
(I will literally speak nothing but that)

**Comment by thestubborn** [comment]
> 
> 
> Not gonna lie we already have a few languages for humans, why do they need more when the majority of players (anthromorphs) only get Galcom?

i mean, if you can get an alien or dog to educate us on their languages, go wild

**Comment by Draganfrukts** [comment]
> Not gonna lie we already have a few languages for humans, why do they need more when the majority of players (anthromorphs) only get Galcom?

All three languages will be available to anyone who chooses a human-related background, I know a good chunk of people who play anthros that are still heavily related to humans culturally.

**Comment by Funce** [comment]
Change to normal PR when no longer WIP

**Comment by GoldenAlpharex** [comment]
This hasn't been worked on in a while and is pretty much stale, either make a new PR or bug me to re-open it when you're ready to continue working on this.

**Pull request closed without merging**
