### PR TITLE
Adds the narcolepsy trauma as a pickable quirk

### PR DESCRIPTION
**Pull request by desertmote**
## About The Pull Request
Its a nerfed version of the existing narcolepsy trauma, pickable as a roundstart quirk.

## How This Contributes To The Skyrat Roleplay Experience

ZZZzzz...

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>

SgsDe2dID0

</details>

## Changelog
:cl:
add: Adds a -8 negative quirk called narcolepsy
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
now make heavy sleeper not be incompatible with all-nighter so i can take all 3 and be a tired anime girl

**Comment by HoodMilk** [comment]
honk shooooo mimimimimimimi

**Comment by SomeRandomOwl** [comment]
> now make heavy sleeper not be incompatible with all-nighter so i can take all 3 and be a tired anime girl

You just want to pretend you didn't want to go to work and just sleep through your whole shift instead of working, don't you.

**Review by vinylspiders — CHANGES_REQUESTED** [review]
This seems fine, but have you considered adding some way for medication to control it if desired? That would put it more in line with the other quirks that grant some kind of treatable condition.

See `/datum/quirk/insanity`, `/datum/quirk/item_quirk/allergic`, etc.

As it is now they get a glass of coffee in the mail (lol) which can help with preventing the increased drowsiness chance but there isn't actually a way to stop it altogether.

**Comment by desertmote** [comment]
Synaptizine and synaphydramine (mind regen virus) both full-stop the quirk, coffee halves the odds of falling asleep.

RatncoN7RN

dreamseeker_vEYN2j7YS1

**Review by vinylspiders — APPROVED** [review]
Cool, that works! Did you want to add the pill bottle to mail_goodies as one of the potential things that gets sent? Checking before I merge this.

**Comment by desertmote** [comment]
Ready to go!

**Pull request merged**
