### PR TITLE
Makes breakfast end at 35 minutes, as opposed to 15

### PR DESCRIPTION
**Pull request by RatFromTheJungle**
## About The Pull Request

Extends breakfast to end at 35 minutes, instead of 15, to accompany the longer round-times, maybe encouraging break-fast getting RP, instead of the mad-dash for a donut-and-dip, and with the small downside of,

 nothing really, a small mood buff isn't really that big of a deal
 
 the time was decided by me throwing a dice really hard at the wall and reading it's position in correlation with the stars, no, I will not elaborate on this

Someone made a suggestion for it, and I liked the idea, that aswell.
## How This Contributes To The Skyrat Roleplay Experience
see above

## Changelog

:cl:
qol: breakfast now ends at 35 minutes, instead of 15, giving the chef more time to get breakfast options out.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Was about to ask about the time, but can't argue with the PR body's explanation

**Comment by Paxilmaniac** [comment]
How do you have -72 gbp what the fuck

**Comment by RatFromTheJungle** [comment]
> How do you have -72 gbp what the fuck

young man been hustling lost the lottery but i'll be back 😩

**Review by GoldenAlpharex — APPROVED** [review]
Gotta break fast

**Pull request merged**
