### PR TITLE
blindfold to loadout

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
adds the blindfold to loadout

## How This Contributes To The Skyrat Roleplay Experience
xyel wants it, needs it.

## Changelog

:cl:
add: added the blindfold (REAL) to loadout
/:cl:

### CODE REVIEW

**Comment by Elli-Skala** [comment]
wasnt this removed prior due to being used to power game for shift start welding masks?

**Comment by KathyRyals** [comment]
We're a roleplay server, let's not let the big scary powergame reduce loadout and RP opportunities just because someone might use it to bypass welding eye damage.

**Comment by Gandalf2k15** [comment]
solution: make a blindfold without any welding protection.

**Comment by tf-4** [comment]
The cosmetic-only blindfold already exists. There's no reason to _require_ this one.

**Comment by Aether217** [comment]
> wasnt this removed prior due to being used to power game for shift start welding masks?

I don't think that really solved anything considering you can tear up bedsheets for cloth to make one

**Comment by tf-4** [comment]
> > wasnt this removed prior due to being used to power game for shift start welding masks?
> 
> I don't think that really solved anything considering you can tear up bedsheets for cloth to make one

Do that then

**Pull request merged**
