### PR TITLE
[DRAFT][WIP] Rockplanet Season Pass 2: Frying the Burrito. (Attempt 2)

### PR DESCRIPTION
**Pull request by ghost**
### Planned content includes:

- [ ] Functional weather, Dust Storms: relatively non-lethal, but you don't want to be caught unprepared in one.
- TODO: make this not a subtype of ashstorms
- TODO: add sprites
- TODO: stat tweaking to be less-lethal (50 cap on brute, maybe eye damage if there's no goggles/mask?)
- [x] Unique flora, 3 to be specific: Coyote Tobacco, Dagger-Plant Yucca, and Wine-colored Agaricus mushrooms.
- TODO: REVIEW/BALANCE
- TODO: Yuccaroot is unacquirable. I can't make the plant supply both the root and fruit as a drop. Need help coming up with a solution.
- [ ] Unique mobs, based around STALKER and PREY.
- TODO: All of it essentially (I've never coded mobs before this is so confusing)
- [x] New and Updated ruins using said assets.
- TODO: REVIEW/BALANCE
- [x] A whole load of custom assets for ruins and mapping. Not just for Rockplanet, but for anywhere that needs 'em!
- TODO: REVIEW/BALANCE
- TODO: Radiator and Breakerbox layering is wrong. Can't find the issue. Need help coming up with a solution.
- [ ] Redone aesthetic, including duller rocks and new ambient noise, and random clutter spawning.
- TODO: rock color
- TODO: 'still skipping comments at end of file' at the end of rockplanet worldgen file. no clue why
- OPTIONAL: add a few more clutter items? cans and scrap?
- [ ] Scavenger's Guild canonization, including items, clothes, and a wandering scav ghostrole (replacement for the escapepod ghost role)

**Credit to most sprites goes to Fortune13 and STALKER13, and the oldworld mech sprites to Ashen Sky - I've modified practically all of them to fit better, but the credit is still due. I'm no spriter, and having the sprites either as a base or just as-is has helped make this possible.**

```
Stuff to look for in Pass 3:
- Unique Megafauna
- Unique gamer-loot
- Other, more anomalous stuff :)
```

## Why It's Good For The Game
Rockplanet my beloved, you deserve this tender loving and care.

## Changelog
:cl:
expansion: Nanotrasen Terraforming Division is proud to announce that they've restarted the atmospheric cycle of LV-669! Sadly, due to the lack of water, all this has resulted in is terrible dust storms. However, with the sands shifting, more of the past has been uncovered, good and bad.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
help idk how to mark it as draft ;-;

**Comment by softcerv** [comment]
> 
> 
> help idk how to mark it as draft ;-;

image
when you make the PR, not sure how to change it a draft after

**Comment by softcerv** [comment]
> 
> 
> help idk how to mark it as draft ;-;

OH RIGHT, there is a convert to draft button on the right hand menu
image
"Still in progress? Convert to draft."

**Comment by ghost** [comment]
> 
> 
> > help idk how to mark it as draft ;-;
> 
> OH RIGHT, there is a convert to draft button on the right hand menu
> (image)
> "Still in progress? Convert to draft."

thank you you get 1(one) thumbs up

**Comment by gonenoculer5** [comment]
SCAF from DS3 when

**Comment by ghost** [comment]
I'm closing this until the Overmap is completed; probably entirely redoing the project to be a planet, with the ruins as a separate trait ALL Overmap Planets can have a chance of. It'll be much cleaner this way.
RIP Rockplanet, you always were shit, you'll be replaced and forgotten. _*pumps his fist in respect_

**Pull request closed without merging**
