### PR TITLE
Borgis + other borg sprites

### PR DESCRIPTION
**Pull request by werewolfboyfriend**
## About The Pull Request
OK so this is a little... different than I intended initially. I've ported over different colors of borgi (which now all use widerobot sprites) from VOREstation + a green service borgi I recolored, as well as a few other sprites, and a few borg sprites from /vg/station. I fixed the wreck sprite for sec zoomba, too.
borgs
There's almost all of them.
Additionally, this breaks up robot and widerobot files into types. I did this trying to get an idea of what was available for each type of borg, and initially intended to put the sprites back, but, uh, there's so many and they're a lot easier to deal with broken up so I was hopeful that this would be an okay change to keep.

## Why It's Good For The Game
Customization is a huge part of roleplay and can be especially important as a borg, since there's less specific customization. The right borg sprite can inspire a whole character, define limitations and roleplayed abilities, etc. Some more options are good.

## Changelog
:cl:
imageadd: added some more borg sprite options!
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Well, while you're at it, might be interesting to look into why Cyborgs cause memory issues (that lead to the infamous NTOS bluescreen of your chat window) when they have non-tg sprites :^)

**Comment by werewolfboyfriend** [comment]
> Well, while you're at it, might be interesting to look into why Cyborgs cause memory issues (that lead to the infamous NTOS bluescreen of your chat window) when they have non-tg sprites :^)

Well. See. I'm not sure I can, because I've never had that happen, likely due to the fact that my game crashes every 10-15 minutes or so due to potato PC regardless of what I'm playing. I.. can try?

**Comment by GoldenAlpharex** [comment]
> > Well, while you're at it, might be interesting to look into why Cyborgs cause memory issues (that lead to the infamous NTOS bluescreen of your chat window) when they have non-tg sprites :^)
> 
> Well. See. I'm not sure I can, because I've never had that happen, likely due to the fact that my game crashes every 10-15 minutes or so due to potato PC regardless of what I'm playing. I.. can try?

Don't worry too hard about it, I was mostly teasing. Although, if you do find something, it could be pretty neat. Something to look out for might be overlays that get created and just don't get deleted or something like that. I'm not sure. I might look into it eventually.

**Comment by werewolfboyfriend** [comment]
I have no idea why this is failing on cham gloves.

**Comment by FlamingLily** [comment]
I've been a long time contender that default TG borg sprites are best borg sprites.
But _whew_ that middle row.

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
