### PR TITLE
[Semi-modular] More barsigns

### PR DESCRIPTION
**Pull request by werewolfboyfriend**
## About The Pull Request

Brings a bunch of bar signs created or collected by /vg/station. I left out two that were exclusive to their content and one that's, uhhh, definitely against GitHub ToS. Includes descriptions where /vg/ had 'em, but I didn't feel like writing a bunch of new ones. I was going to try and turn it into a radial menu to select a sign from, but I'm terminally dumb of ass and couldn't figure it out. Maybe I'll try again later.
Here's the whole pile of signs now.
Screenshot 2021-04-10 163836 

## Why It's Good For The Game

Customization good. Old bar sign selection was small and kinda boring.

## Changelog
:cl:
imageadd: Central Command has authorized a wider selection of corporate-approved bar signs for use.
/:cl:

### CODE REVIEW

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by thestubborn** [comment]
/vg/station player here, what three signs are you talking about?

**Comment by thestubborn** [comment]
oh the nazi one

**Comment by ORCACommander** [comment]
please no more radial menus.

**Comment by werewolfboyfriend** [comment]
> /vg/station player here, what three signs are you talking about?

way late to seeing this, but: yes, the nazi one, plus the MoMMI and discount dan ones

**Pull request merged**
