### PR TITLE
[MODULAR] Reverts Air Alarm sprite to the aesthetic one

### PR DESCRIPTION
**Pull request by W4rd3nn**
## About The Pull Request
I HATE THE NEW AIR ALARMS!!! PATOOEY!!!

## How This Contributes To The Skyrat Roleplay Experience
The upstream ones are yucky and ugly. These ones are epicer.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image
image
image
image
image
image
image
image

</details>

## Changelog

:cl:Motho
image: NanoTrasen decided the new air alarms were butt ugly and returned to their previous supplier.
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
All sprite overrides are evil and bad.

**Comment by burgerenergy** [comment]
the future is now old man

**Comment by W4rd3nn** [comment]
the new ones are a BIG stupid TEAL BLOCK on the wall. They are ugly!!!!

**Comment by mikeomeh** [comment]
> the new ones are a BIG stupid TEAL BLOCK on the wall. They are ugly!!!

I am absolutely agrees.

**Comment by Nerev4r** [comment]
pull request

**Comment by ghost** [comment]
Go upstream and propose solutions to make their sprite better if you have issues with it.

**Comment by W4rd3nn** [comment]
> Go upstream and propose solutions to make their sprite better if you have issues with it.

U

**Comment by lessthnthree** [comment]
That's not the aesthetic one, that's the old TG one.

**Comment by W4rd3nn** [comment]
> That's not the aesthetic one, that's the old TG one.

but its... _a e s t h e t i c_

**Comment by GoldenAlpharex** [comment]
I think that, for now, we're good with the upstream ones. We can see if they end up improving them more upstream, personally I preferred when a bigger portion of the sprite was the color of the air alarm's alert state, but I feel like this one is a bit too... Long?

If we'd do an override, I'd personally rather have the ones we used to have as overrides instead.

**Pull request closed without merging**
