### PR TITLE
[Semi-Modular] Oldstation (Charlie station) Additions

### PR DESCRIPTION
**Pull request by Zenitheevee**
## About The Pull Request

This PR adds stuff to charlie station. 
What does it add?
4 Attempted tries at making paper for lorefluff. As there's no... Reasonably canon lore i can work on, I just went off the thought of the station being a large research station, and that a lot more people were testing than just sitting around and doing small work.

1 Reproductive grey and 3 grey extracts. While the 3 grey extracts might have been enough, I am aware there are some people who are unaware of the ability to inject plasma into them to get a slime, And are bound to try and inject blood and/or water.

Hydroponics restocking units so people can set up hydroponics vendors and actually make hydroponics work more than just the handful of seeds in the garden. TBH i dont understand why we didn't have it in the first place, But TG has some wonky decisions and lore behind it, I'm just working with scratch and paper.

A new cargo bay area between the Charlie and Delta station areas. While i labeled it under "Charlie" station, Its... Ehh... Hard to say where it belongs. This cargo bay holds a few goodies, Including the before mentioned hydro units, Vendor boards, Some toolbelts, 2 medkits, And a meatcrate in the research part of it. (I'm aware its missing an air alarm, I just hope people take "It got crushed by the meteor" as a valid excuse for me having that slight oversight)

A new take on guns. A hybrid between a Ballistic and Laser gun that switches based on which mag is loaded. (I'm aware there might be some problems with the laser mags as they currently exist because of some sort of micro-resource leak bug somewhere but i'm not sure how to fix it. Ballistic mag works perfectly.) 

I added like.. I think 3 more carp spawners and 4 more xeno spawners total. I know someone said it felt kinda unfun to spend a shift making kill tools only to realize there's only 1 or 2 xenos left. 

Replaces the duplicate engineer and science spawn with a medic and miner spawn. I did this entirely so that each role seems more... Dedicated to an area, But if i'm being honest i'm aware a lot of people go with survivor prodigism and just do whatever anyways.

I also contemplated adding a few things, Including a ship so people could use it to explore the Z level as a mining/salvage ship, An overseer/leader role that i quickly pushed out of thought as being "Too controlling of a shit situation", And at a few times i did think about expanding the size of the ruin map so i can seperate the AI satellite area and the main Research area, But i quickly realized if i did, I'd either have to make an extended hallway that would make it into a choke point via mechanical gaming, or it would become too hard because you'd have 0 reaction time and room to a xeno spawn camping near the transit door. 

## Why It's Good For The Game

Adds stuff to charlie station so theres more to do besides basically being a middle point for RP. I mean you can still use it as an RP middlepoint but like.. Now you can say you did some gardening...

## Changelog
:cl:
add: Added new things to charlie station, Including stuff to start doing xenobiology and botany
add: Added a new super cool hybrid gun to charlie station. I think ol' tinker joe left a note somewhere about it.
del: My sanity after trying to spend an hour getting some vending circuit boards to work for an hour.
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
Only flaw I can see with a passing glance is that none of the areas in oldstation are flagged as xenobiology compatible, which'd force charlie peeps to make a new room labelled "Xenobiology Lab" just to do it. Which is impractical given.. no gravity generator.

**Comment by Zenitheevee** [comment]
> 
> 
> Only flaw I can see with a passing glance is that none of the areas in oldstation are flagged as xenobiology compatible, which'd force charlie peeps to make a new room labelled "Xenobiology Lab" just to do it. Which is impractical given.. no gravity generator.

While True, It wouldn't be that hard for people to either just... Deal with the no-grav via 2x2 xenobio rooms for slimes, Or to use pre-existing rooms with changes (See: AI sat area thats literally just a giant mass of resin)

**Comment by unit0016** [comment]
> > Only flaw I can see with a passing glance is that none of the areas in oldstation are flagged as xenobiology compatible, which'd force charlie peeps to make a new room labelled "Xenobiology Lab" just to do it. Which is impractical given.. no gravity generator.
> 
> While True, It wouldn't be that hard for people to either just... Deal with the no-grav via 2x2 xenobio rooms for slimes, Or to use pre-existing rooms with changes (See: AI sat area thats literally just a giant mass of resin)

They can't use the latter. Again. None of the areas are flagged as xenobiology compatible. Making it obscure and something people will have to manually set up themselves will prevent it from being done a majority of the time. This is a problem the Free Golems demonstrate greatly.

**Comment by Zenitheevee** [comment]
> 
> 
> > > Only flaw I can see with a passing glance is that none of the areas in oldstation are flagged as xenobiology compatible, which'd force charlie peeps to make a new room labelled "Xenobiology Lab" just to do it. Which is impractical given.. no gravity generator.
> > 
> > 
> > While True, It wouldn't be that hard for people to either just... Deal with the no-grav via 2x2 xenobio rooms for slimes, Or to use pre-existing rooms with changes (See: AI sat area thats literally just a giant mass of resin)
> 
> They can't use the latter. Again. None of the areas are flagged as xenobiology compatible. Making it obscure and something people will have to manually set up themselves will prevent it from being done a majority of the time. This is a problem the Free Golems demonstrate greatly.

Unless there's some hardcoding in the system that prevents slimes themselves from living in non xeno-biology labs, you still technically can. 

You just wont be able to use the fancy console to make it 50x easier, and you'll more than likely have to do a lot of chancing until you can get a cerulean, In which you can construct a slime blueprint that marks an area able to use the console.

**Comment by Zenitheevee** [comment]
Alright, Xenobio thing done there seems to be an issue compiling the map thanks to an ID variable within... I think its a door button + Shutters? 

Edit: I see the issue, Give me a quick sec.

**Comment by Zenitheevee** [comment]
>Capitalising Nanotransen is apparently getting this linter denied

Wait, No i'm jsut being fucking stupid its nanotrasen what the fuck i've been mispelling it all my life

**Comment by Gandalf2k15** [comment]
We'll put this up for a TM. However, be aware this will likely start conflicting if changes are made to oldstation.

**Comment by Zenitheevee** [comment]
> 
> 
> We'll put this up for a TM. However, be aware this will likely start conflicting if changes are made to oldstation.

while i'm more than aware of this, I've got it backed up and i'm more than willing to put effort into doing a full, Modular re-do once we get modular maps in.

And i while i'm aware TG can do what they want whenever, I have a suspicion TG aren't going to change it anytime soon. It seems to fit their narrative as it is quite well, And any changes they make will either be small tiny fixes that i could personally paint the other stuff back over, Or it'll be larger overhauls that i could play around with a bit more.

**Comment by unit0016** [comment]
image
Charlie station medic/miner show up as the default unknown icon ATM.

**Comment by Zenitheevee** [comment]
> 
> 
> image
> Charlie station medic/miner show up as the default unknown icon ATM.

I'd like to note that this PR was started before the ID modularization and Icons were put in, So at the time of developement there wouldn't have been code to work with to put a custom ID in without VSCode getting angry because of unreachable codebits.

However, I'll take a look at it.

**Comment by Zenitheevee** [comment]
ok, That didn't fix it
But.. I'm gon' be completely honest
I dont know how or why, and honestly at this point its a case of minor aesthetics... That isn't a big-big problem.

**Comment by Zenitheevee** [comment]
Alright, I'm not *ENTIRELY* sure what the problem is **right now** with the new ID cards, But i'm going out on a limb and saying its probably because its testmerged from a state that didn't have them, and thus whatever code injection system is working *AFTER* the system reading for cards and injecting the modularized appearance.

**Comment by Zenitheevee** [comment]
Yes i'm aware of the merge conflict because TG's doing stuff but yeah being honest the PR Process is pain to me and i'm debating whether to drop it entirely, Or modularize it fully
But i have __No__ clue how to modularize maps and i'm kinda just... Wanting to pass it off fully, considering how many people recently are getting into mapping.

**Comment by Gandalf2k15** [comment]
I suggest you modularise this fully, make it a completely separate ruin. As this won't work. To make it fully modular, just add this map to the maps/skyrat map folder. :)

**Pull request closed without merging**
