### PR TITLE
[Modular] Pre-emptively adds armor to the new cargo modsuit, and adds it to a crate.

### PR DESCRIPTION
**Pull request by RatFromTheJungle**
## About The Pull Request

Adds armor to the new cargo loader module, trying to keep it balanced at around the 280-300 total value the other modsuits have in armor, while giving it slightly more melee so it can survive riding the disposals chutes.

Also adds it to a cargo crate, like the other modsuits.

## How This Contributes To The Skyrat Roleplay Experience

"Hold on, i'm on my way." _John Mitchell starts climbing into the disposal unit_

## Changelog

:cl:
I added armor to the cargo loader, I don't know what that'd be under
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
I feel like it should have protection entirely against disposals damage.

**Comment by Ebin-Halcyon** [comment]
balance would would be right for the changelog imo.

**Comment by RatFromTheJungle** [comment]
> I feel like it should have protection entirely against disposals damage.

it works off melee if I recall, and I don't wanna give it like 100 melee

**Comment by GoldenAlpharex** [comment]
> > I feel like it should have protection entirely against disposals damage.
> 
> it works off melee if I recall, and I don't wanna give it like 100 melee

Make code so there's a flag on mobs that prevents them from taking damage from disposals or something.

**Comment by tf-4** [comment]
oops, didn't realise this was PR'd to that branch like a dumbass
just do it in a follow-up pr

**Pull request closed without merging**
