### PR TITLE
Removes beepsky's racism 

### PR DESCRIPTION
**Pull request by Elli-Skala**
## About The Pull Request

beepsky won't raise the scum bag level on you if your not a human anymore

## Why It's Good For The Game

this effected 90% of our station population negatively 

## Changelog
:cl:
del: Removed beepsky hating on you for being non human
/:cl:

### CODE REVIEW

**Comment by Vynellin** [comment]
This is also good to avoid confusion for sec.

**Comment by Draganfrukts** [comment]
but in-game racism is encouraged

**Comment by SpaceVampire** [comment]
Just make it only effect you, if you are a lizard. Compromise.

**Comment by Vynellin** [comment]
> but in-game racism is encouraged

Yes but this also leads to confusion for sec cause ive heard multiple times "Wtf is a charge six" Then "Oh its a lizard"

**Comment by KathrinBailey** [comment]
Oh in-game racism is encourage?
Elli, better make it target humans instead.
We're all non-humans so...

**Comment by MLGTASTICa** [comment]
Its just a number  , and its funny, no reason to remove it.

**Comment by Low3** [comment]
Make beepski racist only to catgirls 24\7. We are a serious establishment after all.

**Comment by Arctaisia** [comment]
> Oh in-game racism is encourage?
> Elli, better make it target humans instead.
> We're all non-humans so...

I support this :>

> Make beepski racist only to catgirls 24\7. We are a serious establishment after all.

This too!

**Review by KathrinBailey — APPROVED** [review]
As funny as it'd be to remove that exclamation mark so it checks if you're human and adds threat there and just inverts the current behaviour, I'm not going to incite more crap.
Humans make up a small percent of the station, however, per capita, make up more shitters than most other groups /s

**Pull request merged**
