### PR TITLE
[MODULAR] Adds Flower Pin from Virgo

### PR DESCRIPTION
**Pull request by softcerv**
## About The Pull Request
Adds a polychormic flower pin that can be worn on the head. It is available as a loadout item. 
image
image

## Why It's Good For The Game
Adds another cosmetic item.

## Changelog
:cl:
add: Added flower pin object and textures
add: Added the pin to the loadout menu
Credit to VOREstation for the original textures that I modified to make this!
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
While you're at it, can you make it so it shows on top of mutant ears? All flowers currently have the issue of like, showing only one pixel on Felinids. It's probably a simple layering issue.

**Comment by softcerv** [comment]
> 
> 
> While you're at it, can you make it so it shows on top of mutant ears? All flowers currently have the issue of like, showing only one pixel on Felinids. It's probably a simple layering issue.

Sure thing! Do you know if there are already any hats that are layered like that?

**Comment by GoldenAlpharex** [comment]
> > While you're at it, can you make it so it shows on top of mutant ears? All flowers currently have the issue of like, showing only one pixel on Felinids. It's probably a simple layering issue.
> 
> Sure thing! Do you know if there are already any hats that are layered like that?

Hardsuit helmets do hide them, but I don't know about *layering* above them though.

**Comment by softcerv** [comment]
> 
> 
> > > While you're at it, can you make it so it shows on top of mutant ears? All flowers currently have the issue of like, showing only one pixel on Felinids. It's probably a simple layering issue.
> > 
> > 
> > Sure thing! Do you know if there are already any hats that are layered like that?
> 
> Hardsuit helmets do hide them, but I don't know about _layering_ above them though.

I looked at the code for the helmets and couldn't find any solution. It might be better to make a new PR to fix this and the other flower items once I figure out a method.

**Pull request merged**
