### PR TITLE
[MODULAR] Telebatons and Ammo pouches no longer give Illegal Tech

### PR DESCRIPTION
**Pull request by Zenitheevee**
## About The Pull Request

Didn't we disable this at one point? Like, It shouldn't be a round-after-round occurence, and i understand that y'know, so much cool stuff locked behind illegal tech, But this is roundstart, common gear. RD's would literally toss their telebaton for just about anything cool behind illegal tech, Like an Ebow.

## How This Contributes To The Skyrat Roleplay Experience

To be fair shouldn't illegal tech printed stuff be illegal? Shouldn't Sec be getting scolded for using the UltiShotgun MCR mod?

## Changelog

:cl:
balance: Made Ammo pouches and Telebatons not give illegal tech anymore.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
I'd honestly try this upstream first, this seems unintended at best and probably a worthwhile upstream addition at worst

**Comment by Zonespace27** [comment]
> I'd honestly try this upstream first, this seems unintended at best and probably a worthwhile upstream addition at worst

These are both an "us problem", ammo pouches don't exist and TG (understandably) doesn't let traitors buy the dumb strong telebatons

**Comment by Zenitheevee** [comment]
> I'd honestly try this upstream first, this seems unintended at best and probably a worthwhile upstream addition at worst

They are Modularly-added uplink items.
On TG they're not uplink items, so they wouldn't be illegal

**Comment by YakumoChen** [comment]
huh, I didn't think all uplink items were illegal tech just by virtue.

**Comment by ArdentSpark** [comment]
yeah the illegal tech just looks for anything that's individually purchasable in the uplink

**Pull request merged**
