### PR TITLE
Critical bugfix for employment contracts

### PR DESCRIPTION
**Pull request by FlamingLily**
## About The Pull Request
nukes the LRP *bug* from contracts.

this is a fix. definitely. don't  hurt me feature freezers

## Why It's Good For The Game
"haha nanotrasen owns your soul" is fucking stupid

## Changelog
:cl:
fix: Employment contracts now are uh good for RP and shit
/:cl:

### CODE REVIEW

**Comment by Seris02** [comment]
It wasn't originally meant to be stupid, it was made because y'know, demons stealing souls and stuff, lawyers had to show people their contracts with nanotrasen to remind them their souls couldn't be traded away in contracts.

Demons aren't really ever spawned anymore, don't even know if they're in the code, so I supppose it doesn't matter anymore.

**Comment by ZephyrTFA** [comment]
Employment contracts dont fit our 'lore' in any capacity and should really just be removed in general. Also; we're in a feature freeze and this is by no definitions even remotely a 'bug fix'

**Comment by FlamingLily** [comment]
> 
> 
> Employment contracts dont fit our 'lore' in any capacity and should really just be removed in general. Also; we're in a feature freeze and this is by no definitions even remotely a 'bug fix'

What lore?

Also, I wouldn't call it a feature either.

**Comment by GoldenAlpharex** [comment]
> > Employment contracts dont fit our 'lore' in any capacity and should really just be removed in general. Also; we're in a feature freeze and this is by no definitions even remotely a 'bug fix'
> 
> What lore?
> 
> Also, I wouldn't call it a feature either.

It's still not a bug and this isn't a fix :^)

**Comment by CandleJaxx** [comment]
this is a very good pr and i hope it gets pushed when the freeze is over

**Pull request merged**
