### PR TITLE
[NON-MODULAR] Reduces the charge cost on health analyzers

### PR DESCRIPTION
**Pull request by softcerv**
## About The Pull Request

Reduces the cost on using health analyzers from 50 to 30, also it makes it so that advanced analyzers only use 30 charge per use too.
## How This Contributes To The Skyrat Roleplay Experience
Having to constantly swap out cells on the health analyzer makes medical gameplay more tedious. This keeps in the charge component while making it less agonizing for doctors to deal with.

## Changelog

:cl:
balance: lowers the power cost of health analyzers.
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
i agree with the change but

honestly?

i'd just scrap analyzers having charges full stop

**Comment by tf-4** [comment]
Constantly? I find myself doing it once, maybe twice per round maximum.

**Comment by softcerv** [comment]
> Constantly? I find myself doing it once, maybe twice per round maximum.

It depends on what job you are playing and how you are using the analyzers. Doing a basic scan on someone while bringing them back to medbay as a paramedic is far different from a doctor having to scan someone multiple times while doing blood filtering to see if the chemicals are gone.

Right now, I don't think the power cost is good for the amount of scanning that medical doctors typically need to do. This gives doctors a bit more leeway.

**Comment by tf-4** [comment]
I play a lot of all medical roles (except viro) and I think it's pretty fine as it is.
I don't find myself having to constantly recharge by any means. In fact, once you have better cells you never need to recharge.

**Comment by YakumoChen** [comment]
Having battery charge on them feels pointless altogether and I've been having issues with health scanning ever since they got cells (the chem scanner doesn't work for me half the time but consumes charge anyway, I think it actually consumes charge if you click anything with it)


It's literally easier to print a new one and throw the old one away than find a bluespace cell for it

**Comment by softcerv** [comment]
> It's literally easier to print a new one and throw the old one away than find a bluespace cell for it

Basically this.

**Comment by SpaceVampire** [comment]
> > It's literally easier to print a new one and throw the old one away than find a bluespace cell for it
> 
> Basically this.

To be fair, I do the exact same thing with plasma cutters.

**Comment by YakumoChen** [comment]
> To be fair, I do the exact same thing with plasma cutters.

you can fill plasma cutters up with raw plasma ore you know

**Comment by SpaceVampire** [comment]
> you can fill plasma cutters up with raw plasma ore you know

Oh, I know. I'm just that lazy.
It also doesn't cost me any points to do it.
All about that bottom line, baby!

**Comment by ghost** [comment]
I thought the cell component was already modular; couldnt this be done modularly?

**Comment by tf-4** [comment]
> I thought the cell component was already modular; couldnt this be done modularly?

Yes, but it would be making a new file for `power_use = low` or whatever

**Comment by Gandalf2k15** [comment]
I'd say they're fine as is..., i don't wanna invalidate the existence of cells component

**Comment by YakumoChen** [comment]
It really isn't a good concept to begin with, but you do you.

**Pull request closed without merging**
