### PR TITLE
[MODULAR] Forging Item Resprites - ROCK AND STONE

### PR DESCRIPTION
**Pull request by dawsonkeyes**
### NEW INHANDS AND ONMOBS ENTIRELY SPRITED BY PAXILMANIAC (Paxilmaniac#3129)

This PR implements new object and inhand icons and icon states for weaponry, tools, and constituent components that make up the Reagent Forging module. This also adds onmob icons for all of said weaponry, and more verbose descriptions to better help define what certain weaponry is capable of.

Pictured below are the original icons
image

Pictured here are the new icons
image

## How This Contributes To The Skyrat Roleplay Experience

image

## Changelog

:cl:
add: All new object icons, inhands, and onmobs for forged weaponry and forging components.
/:cl:

### CODE REVIEW

**Comment by dawsonkeyes** [comment]
image

**Review by Ebin-Halcyon — APPROVED** [review]
Yeah.
Don't forget some ingame screenshot stuff and it'll be set to go on the sprite side.

**Comment by dawsonkeyes** [comment]
> Yeah. Don't forget some ingame screenshot stuff and it'll be set to go on the sprite side.

here's paxil's ((very awesomely formatted)) previews for the onmobs

image

**Comment by Paxilmaniac** [comment]
image
He do be fucking invincible tho

**Comment by Paxilmaniac** [comment]
image
image

**Comment by Ebin-Halcyon** [comment]
👍

**Pull request merged**
