### PR TITLE
[Modular] Yet even MORE DS-1 Tweaks.

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Follows up on my last PR. More bombastic, more wacky, more fun. A new easter egg, botany, a complete redesign of the common area and robotics. Makes more of the base fit the aesthetic. Adds more maintenance tunnels, department signs, pets, and more, and generally just OVERHAULS the entire place. ~~also the common area was unashamedly based on American Chinese restaurants, with their cool water displays.~~

Experimental Changes: **(These aren't dealbreakers, I can and will tweak these if feedback says no.)**
The turrets outside the bridge and in the central ex-cargo room are gone, giving prisoners who tackled the dungeon and got agent IDs a path of least resistance through science. 
The janitor has been given a one of a kind janitorial chem sprayer. It sprays space cleaner. He also has a fully upgraded janicart.
The easter egg. Just in general.

**Do note that the current material rewards in the dungeon from the last PR should be removed when asteroid mining is implemented, so DS-1 ghostroles don't feel the need to tide the place and to let prisoners properly arm themselves during assault ops rounds and not find a cleared out dungeon because some scientist wanted a tier 4 microwave.**
image

## Why It's Good For The Game
Should improve gameflow of assault ops rounds a bit while also making the place nicer for the ghostrole folk.

## Changelog
:cl:
tweak: Donk. Co has chosen to not renew their sponsorship of DS-1.
/:cl:

### CODE REVIEW

**Comment by NotRanged** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/2962

image

I will do it I swear

**Comment by unit0016** [comment]
> #2962
> 
> image
> 
> I will do it I swear

Hope yours gets merged soon man, sorry about this

**Comment by unit0016** [comment]
Moving to draft for more drastic changes.

**Comment by unit0016** [comment]
Opening PR. All spawners are functional and everything's in order.

**Comment by Gandalf2k15** [comment]
Fix dem errors and maybe readd the glass floors to sci, they're nice, with the decals.

**Comment by unit0016** [comment]
> Fix dem errors and maybe readd the glass floors to sci, they're nice, with the decals.

I removed them because they fucked up some cabling I was doing for an engineering project in-game one time (doing a whole supermatter in the uhh. big empty room.)
Readding in the hope that the maintenance tunnels are gonna be enough

**Comment by unit0016** [comment]
image

**Comment by unit0016** [comment]
Integration test failing, oh gosh.
It's either something to do with the Easter egg, the prison, or both. Debugging time!

**Comment by unit0016** [comment]
the water apparently is the problem.

**Comment by unit0016** [comment]
Fixed.
@KathrinBailey water/overlay causes errors when part of a centcom z-level. I'm 99% sure you did the code for them, can you do some checks onto why that is sometime? I'd prefer to have overlaid water effects here, at least eventually.

**Pull request merged**
