### PR TITLE
[Modular] Verb panel revamp - aka Granite's tired of scrolling 4 miles down a list

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

This will need a TM at first, mostly due to how the verbs in live react differently than how they do locally. This changes the verb panel to have a categorical interfact with dropdowns (the descriptions are there on hover dont worry).

## How This Contributes To The Skyrat Roleplay Experience

I'm kind of tired of accidentally sitting on someone's face when i meant to kiss them - or scrolling 50 miles to hug them

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  Categorizes the verbs
  
image

When we map the categories will look similar to this below
image

</details>

## Changelog

:cl:
qol: reworks the verb panel to be less of a CVS receipt
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
> I'm kind of tired of accidentally sitting on someone's face when i meant to kiss them - or scrolling 50 miles to hug them

""accidentally" ok sure pal

**Comment by lessthnthree** [comment]
Looks great.

Can you please organize it so misc/romance come first. The emotes should also be in alphabetical order.

Less important, the sex categories should all be in alphabetical order. (possibly with 'Other' at the end)

**Comment by Zergspower** [comment]
> Looks great.
> 
> Can you please organize it so misc/romance come first. The emotes should also be in alphabetical order.
> 
> Less important, the sex categories should all be in alphabetical order. (possibly with 'Other' at the end)

That's why i need a current copy of the verbs we have on top of needing the TM - since locally they behave differently than what it does on SR

**Comment by Zergspower** [comment]
(this is just an example, i categorized it on purpose)
Easier sorting via category now as before it was wild west based on the position of the file in the folder when it loads
image

**Review by lessthnthree — APPROVED** [review]

**Pull request merged**
