### PR TITLE
Quick n' Dirty Aesthetic Removals

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Following feedback on the new stuff (and to avoid headache from the security overhaul team, love ya'll) - This PR removes the following until I commission (or find from an appropriately licensed source again) replacements:
Closets! Got a lot of mixed feedback, but the general tone was "bad" - and I don't disagree, personally. We'll get to a new locker look one day, I'm not too bothered.
Folders! Something so unimportant shouldn't naturally draw your attention.
Mining Satchels! These didn't fit in AT ALL. As nice as new sprites for these dated ones are, feedback says nay, and again, I agree.
Canisters! Color changing could cause problems, this one I can fix on my own time later. Gameplay first.

Once again, the aesthetics module is comprised of CEV Eris, BeeStation, Unitystation, Tauceti, and Yogstation assets. Much love goes out to the contributors there.

## Changelog
Omitted.

### CODE REVIEW

**Comment by Mithrun** [comment]
I think the cans too have a little too much noise for my taste and i'd rather have the colours everyone is familiar with and the visual clarity.

**Comment by unit0016** [comment]
fair! I can see a mess coming from the canisters colors changing... sad as I am to admit it, it's probably best to let them go, too.

**Comment by CameronWoof** [comment]
These sprites look great! Their removal confuses me! I feel strongly, noted by the exclamation points!

**Comment by unit0016** [comment]
why're you being snooty? I closed the color overhaul PR because you had a point, there's no reason to be an ass.

**Comment by CameronWoof** [comment]
I'm not trying to be snooty, these are all really good-looking sprites. I don't understand why they're being removed. The main issue I had with the previous PR was the doors, but I don't think any of the sprites removed here have the same conflict issue. Sorry for any offense, that wasn't the intent.

**Comment by SpaceVampire** [comment]
My main issue is with the Canisters for sure. I know you are already aware of it, but having the stuff that used to be red suddenly turn green was just super strange.
http://prntscr.com/xvxrqm

**Comment by unit0016** [comment]
Yeah. I preserved the unitystation canister colors when porting them over. (you think that's confusing, look at the atmos DMI) Should be easy to correct. Tiered canisters being marked by the notches at the top was somewhat cute in my opinion, but hard for newer players to read.

**Comment by Draganfrukts** [comment]
> A contributor that actually listens to general feedback

Based & Spritepilled

**Comment by Gandalf2k15** [comment]
Holodeck issues

**Comment by unit0016** [comment]
what?

**Comment by Gandalf2k15** [comment]
Honestly have no issues with the new sprites.

**Comment by Cheshify** [comment]
The only real issue I have with the sprites are the cannisters. They're oddly confusing, slightly blurry, and most of them are the same boring green.

**Comment by Gandalf2k15** [comment]
Update this from master pls!

**Comment by unit0016** [comment]
done!

**Comment by Gandalf2k15** [comment]
Hmm, I like the folders, why remove em?

**Comment by GoldenAlpharex** [comment]
> Hmm, I like the folders, why remove em?

I think they feel a little too bulky and don't have enough visual feedback, maybe? Like, if I'm not mistaken, they look like they're full of paper from the get-go.

**Comment by YakumoChen** [comment]
Could we get the old tool sprites back? I don't feel the new ones fit very well, they don't have enough visual clarity and the changes felt honestly pretty jarring.

Too many tools have been turned into varying degrees of "yellow blinking thing" with no real visual indicator of what it does.

**Comment by Sir-Lagsalot** [comment]
Yeah, I'm gonna agree that the canisters, tools, and lockers look really out of place compared to the stuff around them. They definitely look like they were ripped from a different codebase. The holopads look a little funky, too.

Love the stock parts, though. You can actually tell what they're supposed to be, that's a nice change.

**Pull request merged**
