### PR TITLE
Removes what's left of blueshift for now

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
We don't run blueshift and its not coming back until Isaac finishes the rework. I've spoken to both them and other maintainers and we've decided that for our sake it can just go until that happens.

## How This Contributes To The Skyrat Roleplay Experience
I love maintaining maps we dont use at all dont you?

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

It compiled without errors and nothing broke when I tested it I forgot to get screenshots so you'll just have to trust me
  
</details>

## Changelog

Players will see no change from this

### CODE REVIEW

**Review by Jolly-66 — APPROVED** [review]
I want CI to pass thank you.

**Review by tf-4 — APPROVED** [review]
o7

**Comment by press-mark** [comment]
don't forget to bug affected abt the webmap

**Comment by axietheaxolotl** [comment]
https://user-images.githubusercontent.com/86872535/204115073-608ebc73-030e-4bf0-965f-707b5c939b62.mp4

**Comment by Zonespace27** [comment]
adios

**Comment by Paxilmaniac** [comment]
rip bozo

**Comment by Jolly-66** [comment]
Revert Any%

**Pull request merged**
