### PR TITLE
Makes void raptor no longer take place in Mexico : God damn the sun : void raptor light colors audit

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

A fun fact is that basically every light no matter the location is the warm lighting subtype on void raptor. While I can understand the intention behind it, having the entirety of the map orange doesn't look particularly good.\

Void raptor is also VERY overlit. Large light bulbs are placed less than three tiles from one another and in some places, two were next to each other on the same wall.

This pr addresses both of these issues:

Areas that should not be warmly lit are lit with either normal or cold lighting. This includes main halls, and literally anywhere that is inside a department. Areas where people are meant to gather and hang out, like the bar, the kitchen, dorms, the rec room, and even that little cafe by evac, are all left with warm lighting.

The number of lights across the map has been decreased by a non-insignificant amount, without compromising how lit the map is by any noticeable amount. When I say vr was overlit, I mean it was overlit to the point that many rooms lost upwards of six lights and still look the same.

## How This Contributes To The Skyrat Roleplay Experience

While warm lighting can make an area inviting to go to and hang out in, we should not be making entire maps nothing but warm lighting. Use lights appropriate to the area the lights are in. Medical shouldn't look like its taking place in a breaking bad mexico arc, but service shouldn't be lit like a hospital either.

Overlighting is a serious problem when it comes to not only how an area looks, but also the gameplay. Lights consume power, you know, and having way too many in every single room will make an impact on that power draw in a bad way.

## Proof of Testing

Given that I touched basically every part of the map there's bound to be areas I can't showcase, but I'll give some examples.

<details>
<summary>Screenshots/Videos</summary>

image

Library (warm lighting) vs main hall (normally lit)
image

image

Normally lit engineering (literally the rest of the department spawned with lights off)
image

Warm lit rec room, but the bathroom is a bit more cold looking.
image

</details>

## Changelog

:cl:
qol: The excess of lights in many areas of void raptor has been trimmed down, leading to reduced power consumption and less wrath of the sun.
qol: Void raptor has finally cleared the mexico sector, meaning that the entire station won't be warm lit and instead will have lighting colors appropriate to the various areas of the station.
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
# just rename it to mexico raptor thank u

**Comment by lessthnthree** [comment]
this is honestly the real solution instead of me fucking around more with the warm lighting hue trying to balance with other maps

**Comment by Jolly-66** [comment]
> this is honestly the real solution instead of me fucking around more with the warm lighting hue trying to balance with other maps

I won't lie I have enjoyed the color tweaks everyone has done.

Having things feel a bit more homey and roomy is very nice.

I'll get to this PR sometime within a week my life is super all over the place right now.

**Comment by HushTD** [comment]
Give a thumbs up, thank you, been meaning to do it myself too. Initially just wanted to make the lighting feel warmer and stand out a little, but agree later it should have been limited to more homey departments.

**Review by Jolly-66 — APPROVED** [review]
I trust Paxil has not blown up anything in relating to maps.

**Pull request merged**
