### PR TITLE
Added and edited new security hud icons. Almost all jobs now have their unique and friendly-looking icon. Life of quality for security and silicons + Quartermaster icon now with a head style

### PR DESCRIPTION
**Pull request by HelennaC**
## About The Pull Request

Added new security HUD icons for jobs without:
Blueshield, Bouncer, Security Medic, Correctional Officer, Security Sergeant, Customs Agent.
Edited security HUD icons:
Quartermaster (Quartermaster is considered a head, he/she deserves a head feels like icon.)
Security Officer working for science/engineering/cargo/medical deserves a kevlar painted to the department they are working it.
[This is also my first PR, do please point out if I did anything wrong or help me improve so future PRs can be as helpful as my intent.]
## How This Contributes To The Skyrat Roleplay Experience
Quality of life improviment for security players and personnel with security HUD such as sillicons.

## Changelog

:cl:
imageadd: added some icons for blueshield, bouncer, security medic, correctional officer, security sergeant, customs agent. 
imageedit: edited quartermaster and security officer working in departments icons
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Blueshield, Head QM, Sergeant, Corrections, and Medic already have icons. 

The SecMedic icon looks too close to HoS

Missing the Science Guard

The dept guard icons are just the names in letter form as opposed to a unique icon.

Overall I don't really like any of these

**Comment by GoldenAlpharex** [comment]
This PR needs to display an easy-to-view image of the sprite changes you made in the PR body.

Furthermore, most of the icons already existed, they just need to be re-hooked.

**Comment by GoldenAlpharex** [comment]
@HelennaC You still haven't fixed the conflicts or addressed the request for sprites in the PR body. I'll mark this as a draft for now.

**Comment by GoldenAlpharex** [comment]
@HelennaC Are you still going to work on this?

**Comment by Gandalf2k15** [comment]
We do not support non-modular icon changes.

**Pull request closed without merging**
