### PR TITLE
Yet more special description contraband

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request

Complicates the radio jammer - Security will require an engineer or silicon to identify it.
Added descriptions to emags. Does not change their outward appearance.
Emag toys were given SYNDICATE_TOY check, because they're still toys.
Airlock override given the "less identifiable contraband" treatment.
Syndie toolboxes and duffelbags were finally given actual metagame protection like that example in Gandalf's PR that never actually got realized

## Why It's Good For The Game

Same reason as the last 4 PRs.
The emag changes were the most actually superficial. They're arguably infamous at this point, especially as they have their own lookalike toy.

## Changelog
:cl: Yakumochen
tweak: A few more traitor devices have been given special descriptions or made slightly harder to identify.
tweak: Syndicate toolboxes and duffels are now tactical, for holding your tactical gear. Turtleneck not included.
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
I see you are following a trend of putting items in a neutral-zone , i don't feel like this is a good direction as it leads to unclarity and issues for admins frequently, situations such as "But it said suspicius" and so on .

**Comment by BrotherHangyul** [comment]
Actually some pretty good changes, just a suggestion for the radio jammer:

Originally, I believe it's meant to resemble the cargo exports scanner, maybe make the description identical to said scanner with the same examine check?

**Comment by YakumoChen** [comment]
> I see you are following a trend of putting items in a neutral-zone , i don't feel like this is a good direction as it leads to unclarity and issues for admins frequently, situations such as "But it said suspicius" and so on .

Since the item itself is actual contraband this isnt providing any real safety net. At best gives the chance for someone to overlook it when looking at your inventory instead of just spot and take it.

**Review by Gandalf2k15 — APPROVED** [review]
I do love the amount of inventive uses the examine system is getting. This is great. Good work.

**Pull request merged**
