### PR TITLE
[Semi-Modular] Boxstation

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Throws Icebox back in space. Not multi-z. Doesn't replace Icebox. Meant to be run alongside since I plan on heavily modifying it to be some unholy amalgam of newbase, oldbase, what I'd like, etcetera. For now it's just icebox squished down to one zee.
https://cdn.discordapp.com/attachments/808748724791803904/826581913107300372/spaceboxwip.png

## Why It's Good For The Game
Another map not tethered to tee-gee

## Changelog
:cl:
add: Throws Box back into space.
/:cl:

### CODE REVIEW

**Comment by DuffCreeper** [comment]
This is hella based as fuck. One thing I will say is probably remove this area due to the fact its uh, tad useless since we're in space
succ

**Comment by unit0016** [comment]
> This is hella based as fuck. One thing I will say is probably remove this area due to the fact its uh, tad useless since we're in space
> succ

Every other map still has a space hut, I figured why remove Kath's custom icebox one, it's still nice. Heck, we even had station z-level ruins on oldbase.

**Comment by DuffCreeper** [comment]
> Every other map still has a space hut, I figured why remove Kath's custom icebox one, it's still nice. Heck, we even had station z-level ruins on oldbase.
I'd say remove the APC, air alarm and pipes connecting them. Mostly due to the fact neither meta or delta have their space huts connected. I guess my worry is primarily a breach happening and having it add demand to distro ontop of wasting air to an area that people might not use.

Regardless it's up to you and idc. Having boxstation again is good enough to me *dab

**Comment by EerieDream** [comment]
Boxstation WITHOUT THE ICE? Already an instant upvote. I'm excited for this to get into rotation; I missed boxstation.

**Comment by alexv-ds** [comment]
Охуенно

**Comment by dominuslucian** [comment]
based, good pr

**Comment by Sethnov** [comment]
icebox is nice, cuz their never delams

**Pull request closed without merging**
