### PR TITLE
Security Redux [STAGE-4]

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

This is now in phase 3.

The main security area has now been reskinned too. Of course, none of this is set in stone and we'd like to get a feel for what fits our server. 

**All of this is liable to change.** Please keep this in mind when commenting, and do not abuse eachother.

We aim to balance security over a less laser/instant win loadout. To achieve this we will be changing the kind of equipment security has access to. As of now, security has items that completely remove the fun in combat. This aims to reverse that, while still allowing them to be somewhat capable. 

We will be:

- [x] Swapping out the batong with the classic baton.
- [x] Swapping out the Energy Carbine with something more ballistic.
- [x] Swapping out the disabler for alternative weapons.
- [x] Changing the uniform up a little.

The general aesthetic I am now going for with security is the "peacekeeper" look.  Think of the hunger games.

## New Uniform Set:
image

Officer:
image

Warden:
image

HoS:
image

Officers come with black beret variants too. **All old clothes are of course still available as well.** 

## New Armaments:
**G-17**
image
This is standard issue for all officers in place of the disabler.
You know the game with this one, it's chambered in 9mm, has a 16 round capacity, deals 10 damage+Stam.

**G-18**
image
This is the HoS's baby, it's the automatic version of the above.
Has a 3rnd burst and a 33 round capacity. Same damage.

**A-3 PCR**
image
The Automatik-3 Peacekeeper Cyclic Rifle is the replacement for the standard energy carbines in the armory. It uses WT550 ammo, including all the variants. 

**Peacekeeper Baton**
image
This is the replacement for the stun baton, all officers get one. It is worse than the classic baton, but should help with the issues we currently have with this being the go to. We want firefights, damn it!

## New Ammo Types

So you will have access to 4 different types of round for all guns that I make:
1. Standard: Normal lethal round. (Red). These are your bog standard normal damage copper slugs. Cheap, and in abundance. Locked behind autolathe hack.
2. Hollow point: Higher chance of wound and more damage. (Gold).  These are locked behind research, low grade weapons.
3. Rubber rounds: Low damage but high stamina damage. (Blue). These are cheap, and will down someone quickly. But beware, they still do a bit of damage. They're in the security section of any autolathe.
4. IHFD (Intelligent high-impact displacement foam) rounds. (Green). These are the pride and joy of this. They are essentially no damage disabling rounds. They hit a target and disintegrate on impact, transferring only the force into the body dealing a great amount of stamina damage leaving no bruises or damage! They are locked behind advanced weaponry in the protolathe.

## Why It's Good For The Game

We all enjoy SS13 for different reasons, and security has always been lacking somewhat in the department, we'll try to address this. It will evolve over time however I'd like to see how security copes with this.

Security is of course a touchy subject for people that never play it, for whatever reason, so we're going to change things up a little. 

## Changelog
:cl:
add: We've given our security department a new look. Hopefully this stuff won't attract bulls.
tweak: As a security officer, you are now equipped with an older style baton, we don't have the cash to keep sending you new state-of-the-art ones.
tweak: We've opted to use our surplus armory to stock up frontier stations. Expect varaing quality.
/:cl:

### CODE REVIEW

**Comment by BrotherHangyul** [comment]
Might want to buff lethal / normal rounds for the G17/18, that's all I've got to say (Lethal rounds do 10 brute, rubbers do 10 brute, seems bad)

**Comment by GoldenAlpharex** [comment]
I just... Don't get why you want to make security white? There's already two departments with a white theme, I don't see why we need to change security's color.

I'm curious to see how the use of ballistics will work out, however.

**Comment by Zenitheevee** [comment]
So
Can we just keep all the fucking bickering out of this one? 
Scrolling two miles because people are constantly quoting and arguing about shit is disgusting.

That asside, Good steps towards balancing sec, The one hit down for batons were bad because while it did take more hits to stun, The first down was a guaranteed chain.

**Comment by YakumoChen** [comment]
I still believe this anthemic to the game's design. 
Energy weapons are high visibility: you always know what kind of projectile is hurtling towards you. Red means dead, blue means stun. All ballistics conversely fire the same tiny projectile sprite and the only one who knows how lethal it is is the one shooting.

Second is that security is lethal only now with guns, which will piss off the tin cans and force a similar response from everyone else. Crew will shout "why are you harming me" and traitors are free to kill security as soon as bullets fly.

The baton is ironically stronger for 1 on 1 fights but makes security completely unable to do crowd control with the long delay on hitting with it. It also suffers from the game design flaw that nothing about it is visible to others any longer. No more throbbing orange in-hands or "bzzt" of activating Security Mode.

The HoS loses a lot of strength taking away their variable weapon in exchange for a gun that just spits the same bad bullets faster. Give them back the X-03

**Comment by FlattestGuitar** [comment]
An important balance concern is that energy weapons get used up quickly. If security is on your tail if you're good enough you can dodge a few shots and they need to recharge. But if they have a functionally infinite supply of ammo that stops being the case and security is much more relentless - whacking them instead of running away becomes a much better option. 

Also, wouldn't it be better to split cosmetic changes off into a different PR? These are two different discussions.

**Comment by Zenitheevee** [comment]
> The HoS loses a lot of strength taking away their variable weapon in exchange for a gun that just spits the same bad bullets faster. Give them back the X-03

X-03's in the locker, And HoS's locker wasn't touched, judging by the code.

My comment on the previous PR was a mention towards the potential fact it could be removed in the future for something.... Different.

**Comment by Draganfrukts** [comment]
From the word of a spriter and security player, all of this seems, and if I'm to be blunt, flat-out terrible. Normally white-black is a good mix of colors, but looking at this all the assets are just bright recolors save for the beret, the sunglasses clash extremely hard with the rest of the outfit, you can tell there's practically no new assets when you look at the HoS' new coat for example, which is just the russian coat. Calling stunbatons which need three to four consecutive hits to get rid of someone "state of the art" while the blueshield gets a /mindshield locked instant-knockdown stunbaton, that has a higher stamina damage output and fits in your pocket/ feels like it's just taking the piss. There will never be a reason to use non-lethal rounds with the 9mm guns because you can go to cargo, print real 9mm that does like 30 brute a pop and annihilate anyone in 4 shots (Due to sharing calibers with the makarov). Playing Warden, my only incentive to stunning someone will just be loading a peacekeeper with beanbags and downing them in 2 shots because that new nightstick is terrible if not useless. I don't particularly like the 100% pure white look with zero black contrast save for the odd accessory, and I don't think Hyperborean White Security is a good change. 

Also this renders techfab gun research useless as you need a readily available energy carbine to use the conversion kit.

**Comment by Gandalf2k15** [comment]
> From the word of a spriter and security player, all of this seems, and if I'm to be blunt, flat-out terrible. Normally white-black is a good mix of colors, but looking at this all the assets are just bright recolors save for the beret, the sunglasses clash extremely hard with the rest of the outfit, you can tell there's practically no new assets when you look at the HoS' new coat for example, which is just the russian coat. Calling stunbatons which need three to four consecutive hits to get rid of someone "state of the art" while the blueshield gets a /mindshield locked instant-knockdown stunbaton, that has a higher stamina damage output and fits in your pocket/ feels like it's just taking the piss. There will never be a reason to use non-lethal rounds with the 9mm guns because you can go to cargo, print real 9mm that does like 30 brute a pop and annihilate anyone in 4 shots (Due to sharing calibers with the makarov). Playing Warden, my only incentive to stunning someone will just be loading a peacekeeper with beanbags and downing them in 2 shots because that new nightstick is terrible if not useless. I don't particularly like the 100% pure white look with zero black contrast save for the odd accessory, and I don't think Hyperborean White Security is a good change.
> 
> Also this renders techfab gun research useless as you need a readily available energy carbine to use the conversion kit.

We were waiting for you, but you never came.

**Comment by Investigator77** [comment]
> 
> We were waiting for you, but you never came.
I got muted for telling someone I'd jump out of their mailbox to assault them for like a week so I couldn't give my opinion earlier

**Comment by GoldenAlpharex** [comment]
Also, another concern I'd like to bring up, now, the Detective won't really feel inclined to scan 9mm casings that are left on the floor, because it probably was Security firing them. Just thought I'd let that out, not sure how much it's worth in the grand scheme of things, but I always thought it was a fun thing for Detectives to do.

**Comment by hugmeorelse** [comment]
As I said on the previous iteration, I'm going to start removing people who choose to continue to be toxic. Consider this a final warning on the subject.

If you have a disagreement, speak like a normal human being. If you cannot be decent in public, you have no place in this community.

**Comment by hugmeorelse** [comment]
Anyhow, I'm going to talk with Gandalf about the changes needed base on what I've seen myself and heard from others.

Also, if you can't speak without being an asshole, your opinion will be disregarded. I will never advocate anyone who treats a developer like trash. If you have an issue, bring it up politely, and I will make sure your opinion is regarded in some way.

**Comment by Vynellin** [comment]
Why white? Theres already two deparments that walk in white this is gonna cause more confusion.
And removing secs non lethals is a horrible idea as it will lead to more unga and accidental killing.
While at the same time removing energy is silly for the same reason as removing ballistics is silly.
As lore wise its known there are threats that are weaker to the other and gotta be meet with lethal force.
Also the its a bit easier for a antag to deal with a officer with a EGUN that it is for a normal gun.
As in case one you can.
Emp them. Or you can make them run out.
While in case be.
You gotta wait and hope they run out of ammo and arent just reloading so when you pop out of cover you get spallted in the head.
The baton change I do support as batons were always the go to item. To the point of it being a cruch. Tho I think the best bet is to make it like the old TG version when you whacked. There was a delay. Then the person got knocked down.
My statment as a sec player.

**Comment by GoldenAlpharex** [comment]
> The baton change I do support as batons were always the go to item. To the point of it being a cruch. Tho I think the best bet is to make it like the old TG version when you whacked. There was a delay. Then the person got knocked down.
> My statment as a sec player.

I completely agree with the baton suggestion, I'm used to the baton only making you drop after a few seconds and I'd say it was better like that, felt a lot more balanced than what we could currently see.

**Comment by Vynellin** [comment]
Also another color combo idea would be Black/Blue
Blue/Red
Blue main white secondary
Red main white secondary
Black main white secondary.

**Comment by GoldenAlpharex** [comment]
> Also another color combo idea would be Black/Blue
> Blue/Red
> Blue main white secondary
> Red main white secondary
> Black main white secondary.

I mean, personally speaking... I think the red and black theme was fine, although, I must say, the greyish-blue look that I sometimes see on some officers really does look good, makes them stand out. Thinking of Neri Ventado, for example. I just think  that we should leave it up to the players to look how they want, more variety is good, swapping something for something else... Kinda eh, in my books, unless everyone agrees it's a good change.

**Comment by Gandalf2k15** [comment]
> Also another color combo idea would be Black/Blue
> Blue/Red
> Blue main white secondary
> Red main white secondary
> Black main white secondary.

BLACK/BLUE, YES!

**Comment by BrotherHangyul** [comment]
>  There will never be a reason to use non-lethal rounds with the 9mm guns because you can go to cargo, print real 9mm that does like 30 brute a pop and annihilate anyone in 4 shots

The glocks use custom 9x19mm, which deals 10 brute, just saying

**Comment by BrotherHangyul** [comment]
Anyway, avid sec-main here with feedback:

Red jumpsuit turns into blue now. Bad. We should have the option to go back to default if we don't like the new clothes.

Now onto the actual balancing:

Baton good.

After field-testing the glock, not so good.

10 brute / no rubbers is, as expected, bad for interactions with silicons and generally just bad in combat. It has massive potential, don't get me wrong, but it needs a little buff / rework. There should be rubber bullets like on old-base, printable magazines and a definite buff to ammunition (maybe 20-25 brute?)

**Comment by Gandalf2k15** [comment]
## **To everyone commenting on this PR with PURE salt, here is all I have to say:** 
You hated the rebase, now, no one talks about it.
You hated the new sprites, now, no one talks about it.
You hated assault ops, now, people beg for it.

This is the FIRST test of this, you must understand this will evolve GREATLY over time. See: Assault ops. 

So before posting with your pure salt, I suggest you give it some time, provide constructive feedback, and maybe, we'll get away from the arcade feeling.

**Comment by Vynellin** [comment]
Honestly my main two problems is starting gear with rubbers instead of disablers.
And the color scheme.
(Cum sec joke here after a while may end up leading to a massive amount of ahelps.)
Also the fact there is no detective love. Like COME OOON MAYBE I WANNA LOOK LIKE A SHERLOCK HOMES!

**Comment by MLGTASTICa** [comment]
I really really love this PR , my only issue is that the glock seems to be extremly unaffective . 10 Brute is the damage of a toolbox hit and i can't see any code mentioning stamina tied to the bullet . But this could be easily remedied if we get a auto-fire element..

**Comment by Draganfrukts** [comment]
Old security scheme reasoning: "NT made the clothes red to hide blood stains"
New scheme: "NT made the clothes white to hide cum stains"

**Comment by Vynellin** [comment]
> Old security scheme reasoning: "NT made the clothes red to hide blood stains"
> New scheme: "NT made the clothes white to hide cum stains"

NO BAD

**Comment by YakumoChen** [comment]
Dark blue and black security? Like real life? I'd be for that, actually. Maybe give atmos more orange and red themes. So long as I can still rock the charcoal HoS uniform.

 Anything but Spaceballs Security at this point.

**Comment by YakumoChen** [comment]
What I see when I walk into brig with this merged
(This shouldn't be taken as anything but a.dumb joke)

**Comment by Vynellin** [comment]
I just closed ss13 and saw the space balls image as soon as i closed it. First time ive ever been scared by space balls.

**Comment by DiscountDirtyDan** [comment]
Only 9mm? Where's the stopping powah?

**Comment by YakumoChen** [comment]
According to the combat rework currently testmerged, the batons are _also_ lethal (they deal a portion of their force on the knockdown), so security gets absolutely nothing they can't piss off the sillycons with.

**Comment by Gandalf2k15** [comment]
New Ammo Types
So you will have access to 4 different types of round for all guns that I make:

Standard: Normal lethal round. (Red). These are your bog standard normal damage copper slugs. Cheap, and in abundance. Locked behind autolathe hack.

Hollow point: Higher chance of wound and more damage. (Gold). These are locked behind research, low grade weapons.

Rubber rounds: Low damage but high stamina damage. (Blue). These are cheap, and will down someone quickly. But beware, they still do a bit of damage. They're in the security section of any autolathe.

IHFD (Intelligent high-impact displacement foam) rounds. (Green). These are the pride and joy of this. They are essentially no damage disabling rounds. They hit a target and disintegrate on impact, transferring only the force into the body dealing a great amount of stamina damage leaving no bruises or damage! They are locked behind advanced weaponry in the protolathe.

**Comment by GoldenAlpharex** [comment]
> New Ammo Types
> So you will have access to 4 different types of round for all guns that I make:
> 
> Standard: Normal lethal round. (Red). These are your bog standard normal damage copper slugs. Cheap, and in abundance. Locked behind autolathe hack.
> Hollow point: Higher chance of wound and more damage. (Gold). These are locked behind research, low grade weapons.
> Rubber rounds: Low damage but high stamina damage. (Blue). These are cheap, and will down someone quickly. But beware, they still do a bit of damage. They're in the security section of any autolathe.
> IHFD (Intelligent high-impact displacement foam) rounds. (Green). These are the pride and joy of this. They are essentially no damage disabling rounds. They hit a target and disintegrate on impact, transferring only the force into the body dealing a great amount of stamina damage leaving no bruises or damage! They are locked behind advanced weaponry in the protolathe.

Sounds really good! I'm glad to hear there's going to be some completely non-lethal shells, that sounds really fun to work with.

**Pull request closed without merging**
