### PR TITLE
Fresh New Brew (New Coffee Maker Sprites)

### PR DESCRIPTION
**Pull request by Youtubeboy139**
## About The Pull Request

Adds in a newly made Coffee Maker sprite for break rooms as well as adds in new Coffeepot sprites and Coffee Cartridge sprites for the new Coffee Maker sprite. The newly created sprites may be found below.

coffee_maker-showcase

## How This Contributes To The Skyrat Roleplay Experience

Brings better cohesion to the machine sprites that are currently in the game - the new Coffee Maker uses the same color pallet as most kitchen based appliances that are specific to Skyrat.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
 
Screenshot 2023-04-25 214555

https://user-images.githubusercontent.com/609886/234446430-77456c9d-8aeb-4f58-a1a4-b478dc741c66.mp4

</details>

## Changelog

:cl:
add: Adds in the new coffee based sprites in a dedicated .dmi file
code: Extends /kitchen.dm code to overwrite base TG code icons
/:cl:

### CODE REVIEW

**Review by Ebin-Halcyon — APPROVED** [review]
Sure, I guess.

**Comment by Jolly-66** [comment]
Take this upstream?

**Comment by ghost** [comment]
> Take this upstream?

Or not :/

**Comment by Youtubeboy139** [comment]
> > Take this upstream?
> 
> Or not :/

The coffee maker used the skyrat machine color palette that's used for all kitchen appliances. I would have had to make two separate sprites for each object changed and made two separate PRs.

**Pull request merged**
