### PR TITLE
[MIRROR] TGUI for Techfabs II: The Great Recategorizing (AND ICONS) (AND MECHFABS) (AND AUTOLATHES) [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/69990
--------------------

### HEY KID YOU WANT SOME ICONS? HOW ABOUT SOME CATEGORIES? IVE GOT ICONS AND NEW CATEGORIES

https://user-images.githubusercontent.com/12202230/190893973-07bcf1e6-4a58-424f-b4f9-e76e03be68ea.mp4

### I ALSO HAVE ICONS IN MECHFABS AND NEW CATEGORIES

https://user-images.githubusercontent.com/12202230/190894084-41217e85-447d-493c-a6db-03deec16acf1.mp4

### DO YOU OR A LOVED ONE SUFFER FROM AUTOLATHE CATEGORIES NOT EVEN LISTING EVERY ITEM YOU CAN PRINT IN AN AUTOLATHE? WELL DON'T WORRY I DID THAT TOO

https://user-images.githubusercontent.com/12202230/190894204-4663ee5d-3a7a-4a84-8652-4646a92e95c6.mp4

### SERIOUS TALK

- I recategorized **EVERY `/datum/design/` IN THE GAME** to be more UX friendly and **I HATE MYSELF FOR IT**
- I refactored techfab UI to **WORK ANYWHERE** for **ANY MACHINE THAT USES `/datum/design` as a SET OF MODULAR COMPONENTS**
- I moved a lot of **DESIGNS EXCLUSIVE TO THE AUTOLATHE** to also work **IN PROTOLATHES**
- I made **MATERIAL ICONS** animate between **ICON STATES** for **STACKS**
- **I PUT ICONS IN ALL OF YOUR FABRICATORS**
- I SOMEHOW DID ALL OF THIS **WITHOUT LOSING ANY PERFORMANCE**
- ALSO SUPPORTS COMPONENT PRINTERS AND MODULE DUPLICATORS

Other garbage:

- Fixed numerous spelling and consistency issues in designs
- Removed `Machine Design (<x>)` and `Computer Design (<x>)` from all relevant designs
- All designs are now in title case
- Numerous designs that were formerly autolathe exclusives can now also be printed at a protolathe (but not all); this is mostly just service equipment like drinking glasses and plates and silverware
- Circuits components can no longer be printed at a circuit imprinter (fixes #67758)
- Designs that are not sensible for a department to have are no longer accessible to that department (read: medbay printing turbine parts)

## Why It's Good For The Game

Improved UX for techfabs, but also for mechfabs and autolathes, and oh look it's pretty!

also I spent like eight hours doing nothing but categorizing `/datum/design`s and I'll cry if some version of this doesn't get merged eventually

## Changelog

:cl:
refactor: mechfabs, autolathes, component printers, and module duplicators now use techfab tgui components
refactor: every single design is now categorized and subcategorized
refactor: mechfabs and autolathes are now in typescript
qol: techfabs now have icons for what you're about to print
qol: techfab material icons are now animated
qol: techfab material icons now fade when no materials are available
qol: techfab searching no longer lags like hell
qol: techfab searching now searches all recipes instead of just the current category
qol: techfabs now have subcategorization (stock part users rejoice)
qol: techfabs now announce when new recipes are available
qol: numerous other techfab ui tweaks
balance: some designs that were formerly autolathe exclusive can now be printed at some departmental techfabs

/:cl:

### CODE REVIEW

**Comment by press-mark** [comment]
SICK

**Comment by RimiNosha** [comment]
Oh my god the madlad, doing the thing I wanted, now *this* is QoL.

**Comment by Zergspower** [comment]
Now just bring back the original sorting as an option hnnnnng

**Review by tf-4 — APPROVED** [review]
Ok

**Pull request merged**
