### PR TITLE
[MODULAR] Make drifting contractors come with a preloaded baton holster module

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

This PR makes drifting contractors spawn with their baton holster module already set up.

## How This Contributes To The Skyrat Roleplay Experience

I see this as a Quality of Life change so that Drifting Contractors don't have to turn off and disassemble their own MOD as soon as they spawn for little reason.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

Screenshot 2023-04-06 150944
_Ready to roll_

</details>

## Changelog

:cl: Gyran
qol: made drifting contractors come with their baton holster module already set up
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
This was specifically removed, the baton holster module should be removed from the default

**Comment by Zonespace27** [comment]
Will write out smth when i'm off work

**Comment by Gyrandola** [comment]
> This was specifically removed, the baton holster module should be removed from the default

You mean dritfting contractors shouldnt even come with the baton holster module?

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
The holster itself is fine (https://github.com/Skyrat-SS13/Skyrat-tg/pull/15510/commits/f420da6111487fc754a387b089885e40a9136f85), but this gives back the fully upgraded baton removed in https://github.com/Skyrat-SS13/Skyrat-tg/pull/15510.

Make the subtype of the holster given to the contractor not have any of the upgrades and this is good

**Comment by Gyrandola** [comment]
> The holster itself is fine ([f420da6](https://github.com/Skyrat-SS13/Skyrat-tg/commit/f420da6111487fc754a387b089885e40a9136f85)), but this gives back the fully upgraded baton removed in #15510.
> 
> Make the subtype of the holster given to the contractor not have any of the upgrades and this is good

Oh my bad my bad, that was not my intention at all.

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
Small nitpick: add that the baton is in your modsuit holster to the guide paper you're given, if it's not there already

Additionally, please change the preloaded baton holster on the upgraded admin-only suits to be the upgraded baton version

**Review by Zonespace27 — APPROVED** [review]

**Pull request merged**
