### PR TITLE
[modular] Some Dept Guard Banned Traits

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
Department Guards are banned from being blind, deaf, or unable to understand Common.

## How This Contributes To The Skyrat Roleplay Experience
Guards are Security Lite (they are equipped as and have security access) and should be able to do some minimum with their jobs regarding communication and not being loot piñatas. The banned traits aren't as stringent as normal sec roles

## Changelog

:cl:
balance: Department Guards need working ears, eyes, and Common literacy.
/:cl:

### CODE REVIEW

**Review by GoldenAlpharex — APPROVED** [review]
Sounds about right, and the code checks out.

**Comment by Iamgoofball** [comment]
@GoldenAlpharex This is a stupid idea., we shouldn't be stopping players from choosing to play at a disadvantage.

**Comment by YakumoChen** [comment]
Removed the wheelchair ban.

**Comment by softcerv** [comment]
You should lower it down to just a ban on deafness, people can still fight plenty well while being blind

**Comment by YakumoChen** [comment]
No thanks. Foreigner is for the same reason as deaf (radio communication is required), and guards need to be able to see (visually) who is in their department and identify them to do their job, generally.

Additionally some jobs require sight straight up in their job description, such as "Bouncer checking IDs" and "Customs checking cargo orders"

**Comment by hugmeorelse** [comment]
Blind, I can agree with blocking for Department Guards. Deaf, I can see either ways. However, I don't see the point of banning the Foreigner trait from Department Guards. Having had to deal with people who can't speak English, I don't think it's entirely necessary for someone to realize someone is trespassing. 

Furthermore though, I don't think this is entirely that necessarily. Department Guard are not that crucial and are not meant to be a replacement for security. They have their own function, so this is not that necessary and I don't want to set a precedent that they're equal to or under security at all. They are their **own thing.**

**So, no, they are not "security lite".**

**Comment by YakumoChen** [comment]
If a guard can't understand common on radio, it's no better than them being deaf. Being able to properly communicate is one of the policy-bound requirements to play them.

They are not a replacement for security, no, but their role is designed in a similar way. They also have access to a large amount of security gear and ID access, and having those traits make it a bit less trivial for someone to steal from them.

**Comment by YakumoChen** [comment]
@hugmeorelse

**Comment by YakumoChen** [comment]
@hugmeorelse

**Comment by YakumoChen** [comment]
who do I have to bug to get this merged though

**Comment by Gandalf2k15** [comment]
Remove them from the foreigner quirk restriction

**Comment by YakumoChen** [comment]
@Gandalf2k15 done

**Pull request merged**
