### PR TITLE
[MIRROR] Categorizes uncategorized items in techweb, also recategorizes others for sanity reasons [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/72689
--------------------

## About The Pull Request

Mostly did this for my own sanity in trying to find stuff that's mixed together in a blob of a subcategory (or completely not in one like the grinder). This primarily affected the Cybernetics and implants as a whole but touches some engineering stuff as well. I sort of universalized the code to make it easier to visually adjust things - i didnt touch existing stuff that i didnt need too however but if we want that i can do that.
image

If you see any verbiage changes/category changes or want more broken down (Security and Engineering have some i think that could be broken apart i just couldnt think of the best way) let me know

## Why It's Good For The Game

Making things uniform across the board in appearance makes it easier for people to find things, Now finding the organ you want will quickly show the most advanced one you have for example.

<details>
<Summary>Some Screenshots of the new look</Summary>

Cyber Organs are now tiered based on their coding (Ears are oddly named and i was thinking of fixing it to match but wanted input there)
image

The grinder now doesnt float in no-mans land at the top of protolathes
image

Electronics and Construction assemblies are segregated
image

Gas filters are no longer gas tanks and are just equipment now
image
</details>

## Changelog
:cl:Zergspower
qol: Protolathes and the like had their printable items categorized further
fix: fixes a few uncategorized items in protolathes and the like
refactor: Cleaner techweb code with more categories to break apart individual printable items at proto/mech fabs
/:cl:

### CODE REVIEW

**Comment by Zergspower** [comment]
same bucket as https://github.com/Skyrat-SS13/Skyrat-tg/pull/18673

**Comment by Zergspower** [comment]
#18673 has the fixes for the conflicts here

**Review by GoldenAlpharex — APPROVED** [review]
Should be good to go now!

**Review by GoldenAlpharex — APPROVED** [review]
Yes.

**Pull request merged**
