### PR TITLE
[MODULAR] MODsuit armour

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

PORT OF: https://github.com/MrMelbert/MapleStationCode/pull/136

adds old armour to MODsuits. MrMelbert did all the code, I just ported it

head maintainer approves

image

## How This Contributes To The Skyrat Roleplay Experience

Big fucking suit of armour shouldn't have actually no armour. It's dumb.

## Changelog

:cl: MrMelbert
balance: MODsuits now have their old armour values back.
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
Is the mining one upgradable with goliath plates, though?

**Comment by tf-4** [comment]
Why did you put it in the goofsec folder

**Comment by Iamgoofball** [comment]
1. why is this in the goofsec folder
2. maybe you should talk to the modsuits dev first

**Comment by CandleJaxx** [comment]
> 2. maybe you should talk to the modsuits dev first

i actually spoke to fikou about this a week ago and they said that was only at the request of oranges, tg's head maint, so as long as it was cleared here it's fine.

**Comment by Iamgoofball** [comment]
right but it might be a bad idea to do modsuit armor like this, part of the idea here is to make space dangerous again since space is frankly toothless atm and this was a way to make it more dangerous

**Comment by Zenitheevee** [comment]
> space is frankly toothless

>Carp, Xenomorphs, Simplemob syndicate, simplemob raiders, Other space-bound threats including those found in ruins like zombies, talon demons, and other entities, some capable of ranged combat with all fairly well suited to do formidable damage (I'd say quite frankly the _Opposite_ of toothless, Having witnessed even some DS-2 members die to space simplemobs with their 'superior' gear)

>The fact that Modsuits are _Metal_ and would otherwise add _Some_ resistance to any and most attacks at the minimum, alongside the fact that none of these outside of Mining (and research but lets be honest bomb armor is one of he few things it has going for it) give any specialized armor values of any high degree without a fair reason, ontop of the fact it also already provides a slowdown and a handful of downsides or upsides based on modsuit type.

**Comment by RatFromTheJungle** [comment]
if they look armored, it should be armored 👍 
Alot of the space mobs feel like they were balanced around people having armor, and having 0 armor in space or not is crippling, espiecally on a notably clunky to use suit (long timer for removal/equip)

**Pull request merged**
