### PR TITLE
35 TC

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Lowes TC to 35 and balances the existing items. 

## Changelog
:cl:
balance: Traitors now only get 35 TC. Bundles have been balanced accordingly.
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
cewl

**Comment by Mithrun** [comment]
Actually based, cool beans gandalf.

**Comment by GoldenAlpharex** [comment]
10 TC...?

**Comment by GoldenAlpharex** [comment]
They still have 35 TC according to the files, so...

**Comment by StarHorder** [comment]
... 10?

**Comment by StarHorder** [comment]
i mean lets see how this goes. worth a shot. Not sure if i like the wording you used. 'go ahead and salt' sounds like you aren't very open to criticism.

**Comment by Gandalf2k15** [comment]
> i mean lets see how this goes. worth a shot. Not sure if i like the wording you used. 'go ahead and salt' sounds like you aren't very open to criticism.

🥇

**Comment by DiscountDirtyDan** [comment]
Looking over the changes to item prices, this seems fair. I like that the bundles specifically have enough TC left over to grab maybe some ammo, healing, utility items, and so on. I think that moving forward this should be a good sweet spot between giving people flexibility while also not letting them be solo nuke teams, especially when coupled with the new antag policy.

**Pull request merged**
