### PR TITLE
[Ready] Maintenance Loot Overhaul

### PR DESCRIPTION
**Pull request by BurgerLUA**
This PR is a WIP. I added all the items but I need to add weights to the individual items.

## About The Pull Request

This PR deletes the entire maintenance list and replaces it with my own that I spent an entire day generating.

Some crazy stuff was added. It's extremely rare to occur, though. There was actually a lot of stuff in previous maint loot that could've occurred so it's not too far fetched.

## Why It's Good For The Game

More maint loot is good.

## Changelog
:cl: BurgerBB
add: Refactors maint loot.
/:cl:

### CODE REVIEW

**Comment by hugmeorelse** [comment]
Have any examples of crazy things that may spawn?

**Comment by BurgerLUA** [comment]
> Have any examples of crazy things that may spawn?

Here is the chances for crazy stuff:

```1 out of 10,000 would give metastation (180 spawns) a 2 in 111 chance of spawning an oddity per round, similar to xeno egg.```

Examples for crazy stuff:

A Christmas present that can contain anything.
Hulkmania AI Core
Laughter Demon Spawn
CMO's Medihud Implant
Mind batterer
Book of Babel
A spell book that grants any spell.
Combat Gloves Plus
A random cluster grenade.
Cursed Masks
Combat Banana Shoes
Laser Eyes DNA injector.


Previously the stuff was:

Cult Teleport Rune
Insulated Gloves
Abductor Helmets
Justice Helmet
Carp Hardsuit
Stealth D20
Cursed Stealth D20 (Gibs you instantly when used)
Jackboots that give a speed buff.
Reactive Table Armor
Donk Pockets that turn you into a Gondola when consumed.

From what I remember Skyrat TG now has like 400 rounds so out of those 400 rounds, it probably spawned maybe 2 items.

**Comment by Azarak** [comment]
There's a folder for our defines in code/_DEFINES/~skyrat_defines. Also capitalize the define

**Comment by Azarak** [comment]
Make sure to comment out all the overriden lists and document where their definitions were moved to.
Can you move the lists to master_files instead of the admin module? I dont see why it'd be in the admin module

**Comment by Azarak** [comment]
As for the contents of crazy stuff, I personally would prefer if it was more contraband/tech stuff and less magical/silly items.

**Comment by BurgerLUA** [comment]
> Make sure to comment out all the overriden lists and document where their definitions were moved to.
> Can you move the lists to master_files instead of the admin module? I dont see why it'd be in the admin module

It was a typo.

**Comment by BurgerLUA** [comment]
> There's a folder for our defines in code/_DEFINES/~skyrat_defines. Also capitalize the define

I can't really capitalize it because it's used elsewhere. It's not a define I created but a define that existed already in code.

**Comment by BurgerLUA** [comment]
> As for the contents of crazy stuff, I personally would prefer if it was more contraband/tech stuff and less magical/silly items.

The thing is that silly items existed in previous maint loot so I'm going with what currently existed. SS13 is a pretty silly game and I don't think it would hurt to add silly magical items to maintenance.

**Comment by Azarak** [comment]
> 
> 
> > There's a folder for our defines in code/_DEFINES/~skyrat_defines. Also capitalize the define
> 
> I can't really capitalize it because it's used elsewhere. It's not a define I created but a define that existed already in code.

Could you change those defines in the core file with them and properly comment them? The point is to know if core code is changed if you look by it, someone could be trying to modify it but would be having no effect due to it being re-defined later.
obraz
Like this here

**Comment by BurgerLUA** [comment]
sure

**Comment by YakumoChen** [comment]
I mean, basically half of those new items are ban bait, the old list was mostly stealthy items or silly items or items that should make you want to refrain from just touching/eating everything you find in maint (like floorpills).

Also all the items in your list are almost exclusively good (free traitor/wiz gear) items or free antag.

We shouldn't have maint loot that gives you basically free wizard gear or the chance to give you an instant kill gun, round balance is already hard enough as is without the random chance to completely destabilize a round.

**Comment by KathrinBailey** [comment]
Get rid of the Christmas present.
We're really just done with people getting debug nuclear uplinks as assistants and now the Captain has a shielded syndie hardsuit.

**Comment by SarmentiCampbell** [comment]
> Get rid of the Christmas present.
> We're really just done with people getting debug nuclear uplinks as assistants and now the Captain has a shielded syndie hardsuit.

Literally that, Peoples literally just abuse it or try to show off with it

**Comment by BurgerLUA** [comment]
The present is like a 1 in 700 chance to see it in a round, unironically.

**Comment by YakumoChen** [comment]
a 1 in 1000 chance to get a random AI module or a *laughter demon bottle* is just an invitation to get banned for grief, not "create an interesting round event" however. Why are items like this showing up in maint?

At least the other list you mentioned had stuff like the table armor or the carp suit, items I could actually call 'crazy' and not just 'powergamer's wet dream'.

Giving a round-killer item a low chance to appear doesn't make it any less shitty.

**Comment by BurgerLUA** [comment]
requested changes were implemented and it works with latest version

**Comment by Gandalf2k15** [comment]
Hello, any updates?

**Comment by Gandalf2k15** [comment]
I'm gonna put this up for a TM, with a 1-week count.

**Comment by Gandalf2k15** [comment]
Unable to test merge due to error codes. Please check: 
modular_skyrat/master_files/code/_globalvars/maint_loot_trash.dm:884:error: /obj/item/reagent_containers/pill/floorpill: undefined type path
modular_skyrat/master_files/code/_globalvars/maint_loot_trash.dm:922:error: /obj/item/storage/pill_bottle/floorpill: undefined type path

**Comment by BurgerLUA** [comment]
someone removed maint pills then, guess I'll fix

**Comment by BurgerLUA** [comment]
oh what the fuck happened

**Comment by hugmeorelse** [comment]
> The present is like a 1 in 700 chance to see it in a round, unironically.

1 in 700 is actually quite high. We'll see these every 1-2 months which is enough to cause a headache for players and staff.

**Comment by BurgerLUA** [comment]
> > The present is like a 1 in 700 chance to see it in a round, unironically.
> 
> 1 in 700 is actually quite high. We'll see these every 1-2 months which is enough to cause a headache for players and staff.

1 in 700 chance then a chance to get any item in the game. During the week of Christmas, every crew got a present with a chance to get more presents in maint. A headache was caused every round usually because of one item.

**Comment by hugmeorelse** [comment]
> > > The present is like a 1 in 700 chance to see it in a round, unironically.
> > 
> > 
> > 1 in 700 is actually quite high. We'll see these every 1-2 months which is enough to cause a headache for players and staff.
> 
> 1 in 700 chance then a chance to get any item in the game. During the week of Christmas, every crew got a present with a chance to get more presents in maint. A headache was caused every round usually because of one item.

Fair enough, but we really shouldn't invite people with ban bait. I do see what you're trying to go with. I just don't want people to get bapped because of this. It's unfair for both the players and staff.

**Comment by BurgerLUA** [comment]
Travis is failing because of something outside the PR.

```
[00:37:20] Runtime in blackmarket_uplink.dm,21: Cannot read null.categories
  proc name: Initialize (/obj/item/blackmarket_uplink/Initialize)
  src: Black Market Uplink (/obj/item/blackmarket_uplink)
  src.loc: the plating (131,176,2) (/turf/open/floor/plating)
  call stack:
  Black Market Uplink (/obj/item/blackmarket_uplink): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(Black Market Uplink (/obj/item/blackmarket_uplink), /list (/list))
  Black Market Uplink (/obj/item/blackmarket_uplink): New(1)
  2 x maintenance loot spawner (/obj/effect/spawner/lootdrop/maintenance/two): Initialize(1)
  2 x maintenance loot spawner (/obj/effect/spawner/lootdrop/maintenance/two): Initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(2 x maintenance loot spawner (/obj/effect/spawner/lootdrop/maintenance/two), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(22275)
  Master (/datum/controller/master): Initialize(10, 0, 1)
```

**Comment by BurgerLUA** [comment]
Wait, that's partially true. It only runtimes if a black market spawner is spawned via maint, which is an issue with the item itself but it's caused by this PR.

**Comment by H0gberg** [comment]
I think some of the items are a lil' itty bit iffy, but it's a wonderful overhaul!

**Comment by BurgerLUA** [comment]
TODO: Reduce the amount of money that spawns in maint.

**Comment by Gandalf2k15** [comment]
TM period starts now.

**Comment by Gandalf2k15** [comment]
Alright, the test merge phase is over on this one. It will be merged in a few hours.

**Pull request merged**
