### PR TITLE
Fixes screenshot unit test

### PR DESCRIPTION
**Pull request by Zonespace27**
## About The Pull Request
Someone forgor to change these

If the test passes then it works

### CODE REVIEW

**Comment by Tastyfish** [comment]
Are they supposed to be different? All of the mobs are paler for some reason.

**Comment by Zonespace27** [comment]
I don't quite know; leaving this up even if it's unintended for now

**Comment by Tastyfish** [comment]
I've confirmed that it's due to #18125 by test reverting it on my fork. Not sure what part of it makes the test characters pale.

**Comment by Zonespace27** [comment]
Fixed by https://github.com/Skyrat-SS13/Skyrat-tg/pull/18596

**Pull request closed without merging**
