### PR TITLE
Modern Guns Sprites (Guns Galore)

### PR DESCRIPTION
**Pull request by LeonY24**
## About The Pull Request

Now every single modern version of weapons (except MG34 because it doesn't have one) in Guns Galore has its own sprites, uncluding back, right and lefthanded icons. AKMS sprites are ported from Eris and edited. Ye.

## How This Contributes To The Skyrat Roleplay Experience

Isn't it immersive when your gun ain't invisible, when it shouldn't be so?

## Changelog

:cl:

imageadd: Modern PPSH sprites.
imageadd: Modern AKM sprites.
imageadd: Modern M16 sprites, for both versions.
imageadd: Modern MP40 sprites.
imageadd: Modern STG sprites.
imageadd: Modern FG42 sprites.

/:cl:

image
image
image
image

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
hell yea

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Follow the Pull Request standards
https://discord.com/channels/596783386295795713/654252460004737044/880194709316849736
https://github.com/Skyrat-SS13/Skyrat-tg/pull/7720

**Comment by Gandalf2k15** [comment]
[16:58:34] Runtime in unsorted.dm,1075: Invalid overlay: Icon object 'modular_skyrat/modules/gunsgalore/icons/guns/mg34/mg34.dmi' [0xc00111c] used in 'MG34 UBER' /obj/item/gun/ballistic/automatic/l6_saw/unrestricted/mg34/packapunch is missing icon state l6_mag.
  proc name: stack trace (/datum/proc/stack_trace)
  src: MG34 UBER (/obj/item/gun/ballistic/automatic/l6_saw/unrestricted/mg34/packapunch)
  src.loc: the floor (126,126,14) (/turf/open/floor/iron)
  call stack:
  MG34 UBER (/obj/item/gun/ballistic/automatic/l6_saw/unrestricted/mg34/packapunch): stack trace("Invalid overlay: Icon object \...")
  MG34 UBER (/obj/item/gun/ballistic/automatic/l6_saw/unrestricted/mg34/packapunch): build appearance list(/list (/list))
  MG34 UBER (/obj/item/gun/ballistic/automatic/l6_saw/unrestricted/mg34/packapunch): add overlay(/list (/list))
  MG34 UBER (/obj/item/gun/ballistic/automatic/l6_saw/unrestricted/mg34/packapunch): update icon(16777215)
  MG34 UBER (/obj/item/gun/ballistic/automatic/l6_saw/unrestricted/mg34/packapunch): update appearance(16777215)
  MG34 UBER (/obj/item/gun/ballistic/automatic/l6_saw/unrestricted/mg34/packapunch): Initialize(0)
  MG34 UBER (/obj/item/gun/ballistic/automatic/l6_saw/unrestricted/mg34/packapunch): Initialize(0)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(MG34 UBER (/obj/item/gun/ballistic/automatic/l6_saw/unrestricted/mg34/packapunch), 0, /list (/list))
  MG34 UBER (/obj/item/gun/ballistic/automatic/l6_saw/unrestricted/mg34/packapunch): New(0)
  /datum/unit_test/create_and_de... (/datum/unit_test/create_and_destroy): Run()
  RunUnitTest(/datum/unit_test/create_and_de... (/datum/unit_test/create_and_destroy), /list (/list))
  RunUnitTests()
  /datum/callback (/datum/callback): InvokeAsync()

**Comment by Gandalf2k15** [comment]
Can you make sure you fix up the MG34 sprites. They aren't supposed to be the L6

**Comment by LeonY24** [comment]
that's kinda odd since i haven't even looked on L6 sprites or something, give me one sec

**Comment by LeonY24** [comment]
turns out i haven't even touched the MG34 ._.

**Comment by LeonY24** [comment]
and yeah one more thing, MG34 doesn't seem to have any modern versions, only packapunch which is acquired with admin spawn only.

**Comment by KathrinBailey** [comment]
Are any of these sprites ported whatsoever?
The leftmost one looks like something from Eris or Tau Ceti.
If a single sprite is ported, even ported and edited, you need to give credit.

**Comment by thestubborn** [comment]
we have standards?- i mean...

modern guns, yuck

**Comment by LeonY24** [comment]
akms sprites were ported and edited, btw ported from the same eris

**Pull request merged**
