### PR TITLE
[AM] New Metastation prison

### PR DESCRIPTION
**Pull request by desertmote**
## About The Pull Request

metaprison screenshot

## How This Contributes To The Skyrat Roleplay Experience

Out of our most commonly played maps, MetaStation's prison has always been a bit lacking. We still fluctuate high amount of prisoners some shifts, and they are too cramped when it comes to Meta. The current prison also offers very little freedom in construction, which can be a fun part of playing prisoner.
This new design brings a fresh new lay-out with some unique features like isolation and execution's location. It also is not a summer resort yet offers some appropriate comfort.

I'll promise to maintain this to the best of my ability, like I do with the rest of my content.
Please forward issues to me directly at ghost sheep#5498 or make an issue report.

Note: This is my very first mapping project! Please do not hold back with giving critique, tips or advice.

## Changelog

:cl:
add: Adds an Automapper template for the Metastation prison
/:cl:

### CODE REVIEW

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
Hi. Few things.
I wrote this as you probably pushed a commit or two, please disregard any outdated information here.

<details>
<summary>Active turfs</summary>
Please use airless here.

image

</details>

<details>
<summary> Camera in Re-Education</summary>
There's a specific reason why cameras aren't in Re-Education chambers. The entire purpose of Re-Education is to "fool" the AI to think we're not commuting murder.
As an aside, not really a fan of putting it all the way up here, but I'll leave that to Pax to decide.

image

</details>

<details>
<summary> Nitpicks/aesthetic stuff</summary>
White trim seems redundant here.

image

On all the "corner" windows with shutters, the shutters look jarring and a tad obnoxious.

image

Ditto with trim going over glass tiles.

image

Cell doors should be solid, per a request Xyel made to me awhile ago about Deltas prison.

image

Areas without APCs, or too many APCs.

image

Intercom dead zones.

image

image

image

Please use `nearstation` here.

image

Grills do not generate lattice under them, they just spawn grills.

image

Give this airlock a name?

image

Prison access is `brig` not `general`.

image

Not a fan of areas just melding like this, separate them with doors please.

image

Add a Fax Machine to the brig officers office?

image


</details>

<details>
<summary>Camera var edits</summary>
Please go through all the cameras you've added to the prison and ensure they have the correct:

- Name
- c_tag
- Network

image

**Comment by press-mark** [comment]
Hey hey, found a couple of small things:

<details>
<summary>EVA storage thingo has the wrong name.</summary>

image
</details>

<details>
<summary>Should these be reinforced glass tiles instead?</summary>

image
</details>

<details>
<summary>Overlapping APC / air alarm on either side.</summary>

image
</details>

<details>
<summary>Ditto</summary>

image
</details>

<details>
<summary>Under these dark window's there's an extra space turf?</summary>

image
image
image

</details>

<details>
<summary>Missing an APC for the cells and those areas are missing air alarms.</summary>

image

</details>

<details>
<summary>The windows to the north here aren't connected to the grid.</summary>

image

</details>

**Comment by YakumoChen** [comment]
Ngl it's kinda oversized, a lot of the space is just badly used just looking at the shape of it, it just snakes around in leiu of having any order or literal space saving

Major concerns:
- This outright blocks the solars and makes them relatively useless except from one specific angle
- Execution should NOT require going through the prison. I'm not sure why it's tucked away in a maint tunnel either.

**Comment by desertmote** [comment]
> * This outright blocks the solars and makes them relatively useless except from one specific angle

It doesn't, the solars go out much further past what you think.

PaintDotNet_yjRo11VAZR

> * Execution should NOT require going through the prison. I'm not sure why it's tucked away in a maint tunnel either.

Its a feature, it is different. I have not been given a reason yet besides personal preference.

**Review by Paxilmaniac — COMMENTED** [review]
It looks alright for a prison, but I have concerns with actually putting this in. I'm not sure that I want to put in any more big automapper templates than we have already. The delta prison is a bad example of what to use automapper for and is on the chopping block as we speak, because automapper should really be reserved to changes that we actually need, like cryo, armory, NTrep office, so on.

**Comment by YakumoChen** [comment]
> > * This outright blocks the solars and makes them relatively useless except from one specific angle
> 
> It doesn't, the solars go out much further past what you think.
> 
> PaintDotNet_yjRo11VAZR [ PaintDotNet_yjRo11VAZR ](https://user-images.githubusercontent.com/77534246/192020919-1d5757f2-3272-45c4-b9bf-69a184f21678.gif) [ ](https://user-images.githubusercontent.com/77534246/192020919-1d5757f2-3272-45c4-b9bf-69a184f21678.gif)

That's like a whole 45 degree angle that the sun can't hit the entire solar array. Not mentioning the most inward one which gets maybe 45 degrees of sun in total.

The entire structure looks very inefficiently designed and bloated from a mapping perspective, not to mention other major changes you have not noted here such as the airlock and windows that make the armoury far more defensible.

**Comment by YakumoChen** [comment]
Minor other things

-The escape pod needs to point directly outwards towards space, for aesthetics (and IC sensibility) if there's an obstruction further down the Hull like towards engineering it would be invalid.

-Disposals pipes should not go through space, especially one designed to transport people, and should also be a straight line in that case as bends will do brute damage to people who go in it. 

-Execution SMES is not properly set up. On top of thr fact it does not need its own SMES unit.

Regular glass windows in prison cells are a bad idea

-There are entirely too many shutter windows. These are to defend against space rocks, the inner ones don't need it.

-As alluded to, the EVA airlock and hallway feels extremely bad. It is simultaneously very vestigial and pointless, and extremely bad for balance. An EVA airlock could be much better integrated like on the original map. It looks like wasted lounge space from a glance, as evidenced by the fact there's a bench there, it doesn't belong in the brig. At the same time it's very patently obvious it's to be used to look and shoot and chase anyone loitering or doing crime in space outside the armoury. It is VERY intended by design that the original map has four airlocks, and blast doors in the path to space access and the armoury is only viewable from prison entry, making sightings of people navigating there only coincidental.

**Comment by YakumoChen** [comment]
The visiting room and pod hall has a similar problem. It is poorly integrated into the department and feels too much like a lounge. Security should be compact and professional and the dead end is bad.


Secmed is larger than it needs to be. Prison access also invalidates the double sealed airlock that leads in properly.

ZDespite the huge new space for prison there are only three lockers?

**Comment by desertmote** [comment]
gonna keep it short since i dont think itll get merged anyway and it was just a fun thing to do



> -The escape pod needs to point directly outwards towards space, for aesthetics (and IC sensibility) if there's an obstruction further down the Hull like towards engineering it would be invalid.

its fine

> -Disposals pipes should not go through space, especially one designed to transport people, and should also be a straight line in that case as bends will do brute damage to people who go in it.

its designed for crates and has less bends than default meta

> -Execution SMES is not properly set up. On top of thr fact it does not need its own SMES unit.

it gets a smes because you can cut power off the rooms there as a prisoner with some elbow grease

> Regular glass windows in prison cells are a bad idea

little risk is fun

> -There are entirely too many shutter windows. These are to defend against space rocks, the inner ones don't need it.

afaik i did this?

> -As alluded to, the EVA airlock and hallway feels extremely bad. It is simultaneously very vestigial and pointless, and extremely bad for balance. An EVA airlock could be much better integrated like on the original map. It looks like wasted lounge space from a glance, as evidenced by the fact there's a bench there, it doesn't belong in the brig. At the same time it's very patently obvious it's to be used to look and shoot and chase anyone loitering or doing crime in space outside the armoury. It is VERY intended by design that the original map has four airlocks, and blast doors in the path to space access and the armoury is only viewable from prison entry, making sightings of people navigating there only coincidental.

i dont see how  new v old has any difference in this aspect. the space airlock is in virtually the same place. the window is in virtually the same place. i just added a bench because its a regular hallway now instead of processing

> The visiting room and pod hall has a similar problem. It is poorly integrated into the department and feels too much like a lounge. Security should be compact and professional and the dead end is bad.

comes down to personal preference

> Secmed is larger than it needs to be. Prison access also invalidates the double sealed airlock that leads in properly.

non impactful and if anythign the shutter can be a default down instead of default up

> ZDespite the huge new space for prison there are only three lockers?

only traitors thrown into jail use those. roundstarts dont use those, no point in having many but easily fixed

**Comment by YakumoChen** [comment]
You don't want me to hold back on critiques but you're being awfully flippant about any of my remarks.

Remember that the map is arguably the most important part of the codebase. It's the thing people play the game on. You have a huge, bloated map addition people are going to walk around in. Or around. Players don't like walking farther than they have to, and they don't like wasted space, and this has a lot of both. 

It brings a lot of balance changes that are either understated, or ignored. If you want to design something new, great. If it's your first map addition, great. But either redesign it. Or rebalance it. Not both.

**Comment by desertmote** [comment]
just in case it matters: this template probably has silly cameras now due to #16525.

**Comment by desertmote** [comment]
Needs more updating: #16939

**Comment by Zonespace27** [comment]
We just got rid of the excessively big delta prison, I don't think any maptainers are eager to get another.

**Pull request closed without merging**
