### PR TITLE
[MODULAR] [TOOLING] [PLAYERS SHOULD READ] RimiVoices V1 Tooling: Names are Hard Edition

### PR DESCRIPTION
**Pull request by RimiNosha**
# If you have feedback about the current voicelines on the server, or things you want to see, please direct it to the RimiVoices discord thread in #dev-code. I will not be monitoring this PR for suggestions. There, you've been told.
## About The Pull Request
So, this is a little system I've been working on for a little while now, on-and-off, dropping like maybe an hour into it's dev each time over the course of craptor's initial release. It initially started to just generate voices from a list, but then I discovered audacity macros, and then I discovered audacity has named pipe support, so here I am.

Okay, so this does a couple of things no one has done before (afaik):

**IT HAS DOCUMENTATION, FOR A FUCKING START, VOX AND ANNOUNCEMENT VOICELINE MAKERS. YOU KNOW WHO YOU ARE,**

Is extremely flexible, and *relatively* easy to understand for those who can grasp audacity's weird-ass macro crap.  
Though if you wanna actually generate voices, you're gonna need to have enough technical know-how to install docker too.

As the title suggests, this is JUST the tooling. Voicelines and effects, along with an actual configuration that isn't part of the demo to come, I'm just putting this up here so folk can poke at it and suggest little things like sound effects and shit.

## How This Contributes To The Skyrat Roleplay Experience

The current announcer voicelines aren't even for our server, shit's literally ripped from exodus. Wanna know how I know this? IT NAME DROPS THE FUCKING STATION.

Also means that when we need to add voicelines in the future, we're not relying on someone who left 0 documentation and has 0 interest in doing so when making their voices. This shit's about as open and easy as you can get without me just zipping up my entire windows install.

Anyways. Thank you for listening to my TED talk.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image
Oh look, it worked.
</details>

## Changelog

Not player facing. For now.

### CODE REVIEW

**Comment by theselfish** [comment]
I personally would have just reverted back to https://github.com/Skyrat-SS13/Skyrat-tg/pull/8562

But this seems very well done regardless.

I'd get @thestubborn to send over the effects they had gotten for https://github.com/Skyrat-SS13/Skyrat-tg/pull/6488 but I doubt they'd be willing.

**Comment by RimiNosha** [comment]
Yea, this is just the tooling. The current feature freeze won't allow me to do part 2. I'm happy enough with the code for now, though.

**Comment by RimiNosha** [comment]
Literally the whole of two people discussed anything about this with me, so I've no interest in PRing something with this many moving parts that no one cares for. Someone else is free to re-pull this and maintain it themselves, but I've since departed from SR.

**Pull request closed without merging**
