### PR TITLE
Item use power and cell component refactor

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## Changelog
:cl:
add: A way for atom items to use power.
refactor: A new cell component refactor for any uses where manual cell interaction is required.
/:cl:

## About The Pull Request
This PR does two things:
It Introduces a new item proc for sending signals to anything listening(the cell component for instance) to use x amount of power and return it to the proc, depending on the outcome. This opens up avenues for countless opportunities in regards to items that would normally need a lot of backend changes to use a cell. (attack self etc)

This also includes a cell component, which aims to refactor all instances of crappy jerry-rigged cell interactions and enables any item to use a cell and interact with it using simple callbacks. It enables you to produce items that require cells without the need to process cell insertion/removal, cell display, cell use etc. 

Instructions on making an item use this component:
If the item is action based then you simply `AddComponent(/datum/component/cell)` in component initialize, and then you can hook into it by using the new item proc, item_use_power. This returns a bitflag of the component status, or, if there isn't one, it returns none:

#define COMSIG_ITEM_POWER_USE "item_use_power"
	#define NO_COMPONENT NONE
	#define COMPONENT_POWER_SUCCESS (1<<0)
	#define COMPONENT_NO_CELL  (1<<1)
	#define COMPONENT_NO_CHARGE (1<<2)

It's very simple to use, here's an example:
if(!(item_use_power(power_use_amount, user) & COMPONENT_POWER_SUCCESS))
	return FALSE

Including user in the parameters will send an automatic message to them as to why the process failed(be it a cell running out of power, or removed.). Power is automatically drawn from the internalized cell.

We also enable passive power usage, to do this, simply process the item like you normally would, and add the item_use_power check there too. If you'd like an automatic callback for the cell being removed, we offer this too, simple add a callback referring to the proc you'd like to trigger when the cell is removed.

All items now have a power rating, the cell component will automatically use these to draw the assigned amount of power from the cell when item_use_power is called.

//General defines for items that use power and the cell component.
/// The minimal amount of power an item can use.
#define POWER_CELL_USE_MINIMUM 1
/// For items that barely use any power at all.
#define POWER_CELL_USE_VERY_LOW 10
/// For items that generally wouldn't use very much power.
#define POWER_CELL_USE_LOW 30
/// For items that use a average amount of power.
#define POWER_CELL_USE_NORMAL 50
/// For items that use a high amount of power.
#define POWER_CELL_USE_HIGH 70
/// For items that use A LOT OF POWER.
#define POWER_CELL_USE_INSANE 100

## Items this actually applies to
Power drills / JOL - These have two states, powered and unpowered, when unpowered, they still work like normal, however their toolspeed is equal to a normal crowbar.  When powered, their toolspeeed becomes 0.5! Fantastic. Uses power when on.
~~Testiculator~~Electrical welder - These are basically super welders in the fact they are incredibly fast and don't technically have an open flame. However of course they use a battery. These replace experimental welders. These don't cause fires and are relatively safe!
image
Flashlights - These now have a cell, however, they have 3 different modes, low, med and high!
Radio jammers - These have been given a cell and had their range upped from 12 to 20.
Decal painters/airlock painters - These have been given a cell instead of ink, and are now uncapped.

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Update on the usage situation:
Power drills / JOL - These have two states, powered and unpowered, when unpowered, they still work like normal, however their toolspeed is equal to a normal crowbar. When powered, their toolspeeed becomes 0.5! Fantastic. Uses power when on.
Multitools have had their cell requirement removed.

**Comment by Owai-Seek** [comment]
I just want to point out that the last PR about this had -20 downvotes, with tons of comments, and this one got reopened in its place. People very much don't like needing batteries in things. Even Useroth said this might be better to do upstream because it touches so many things.

https://github.com/Skyrat-SS13/Skyrat-tg/pull/4827

As for my opinion on it, IMO, it's way too far reaching. Every single small item in the game seems to have a battery attached now, and it feels really silly. I can see using this to like, limit the amount of things that can be abused, like jaws/flashlights, but for small stuff, it seems like, way too much.

I could see mildly interesting things being done with this if we still had a laser weapon focus, and you wanted to scrounge together/steal a battery for self defense, but as it is now, this just feels... really unnecessary?

**Comment by Gandalf2k15** [comment]
> I just want to point out that the last PR about this had -20 downvotes, with tons of comments, and this one got reopened in its place. People very much don't like needing batteries in things. Even Useroth said this might be better to do upstream because it touches so many things.
> 
> #4827
> 
> As for my opinion on it, IMO, it's way too far reaching. Every single small item in the game seems to have a battery attached now, and it feels really silly. I can see using this to like, limit the amount of things that can be abused, like jaws/flashlights, but for small stuff, it seems like, way too much.
> 
> I could see mildly interesting things being done with this if we still had a laser weapon focus, and you wanted to scrounge together/steal a battery for self defense, but as it is now, this just feels... really unnecessary?

Go ahead and post in the discord, thanks.

**Comment by Sethnov** [comment]
ok so let's talk about this, first thing I don't like is when you hit something with a tool it uses power, even when it does nothing. so slapping a glass window with jaws of life uses power or a pipe.

**Comment by Gandalf2k15** [comment]
> ok so let's talk about this, first thing I don't like is when you hit something with a tool it uses power, even when it does nothing. so slapping a glass window with jaws of life uses power or a pipe.

It was changed not to do this, in older builds, it did. In this build, you need to turn it on for it to be in the fast tool mode.

**Comment by Sethnov** [comment]
> > ok so let's talk about this, first thing I don't like is when you hit something with a tool it uses power, even when it does nothing. so slapping a glass window with jaws of life uses power or a pipe.
> 
> It was changed not to do this, in older builds, it did. In this build, you need to turn it on for it to be in the fast tool mode.

yes but in fast tool mode, it would use power if you just example hit something, using power when there was no action involved, like hitting a pipe with jaws of life or hand drill or any object would use power when being hit. different from putting up a window or wrenching a machine, as in intended use.

**Comment by Gandalf2k15** [comment]
> > > ok so let's talk about this, first thing I don't like is when you hit something with a tool it uses power, even when it does nothing. so slapping a glass window with jaws of life uses power or a pipe.
> > 
> > 
> > It was changed not to do this, in older builds, it did. In this build, you need to turn it on for it to be in the fast tool mode.
> 
> yes but in fast tool mode, it would use power if you just example hit something, using power when there was no action involved, like hitting a pipe with jaws of life or hand drill or any object would use power when being hit. different from putting up a window or wrenching a machine, as in intended use.

Yeah thats intended, you're supposed to switch it off/on when you're using it.

**Comment by Sethnov** [comment]
> > > > ok so let's talk about this, first thing I don't like is when you hit something with a tool it uses power, even when it does nothing. so slapping a glass window with jaws of life uses power or a pipe.
> > > 
> > > 
> > > It was changed not to do this, in older builds, it did. In this build, you need to turn it on for it to be in the fast tool mode.
> > 
> > 
> > yes but in fast tool mode, it would use power if you just example hit something, using power when there was no action involved, like hitting a pipe with jaws of life or hand drill or any object would use power when being hit. different from putting up a window or wrenching a machine, as in intended use.
> 
> Yeah thats intended, you're supposed to switch it off/on when you're using it.

is it possible to add a hotkey for it? I imagine it be tedious to turn it on and off a lot. which I just forget about the power mode. make life easier for my fingers.

**Comment by Gandalf2k15** [comment]
Could use a hockey for it sure

**Pull request merged**
