### PR TITLE
Deltastation Permabrig Remap (For real)

### PR DESCRIPTION
**Pull request by Aurelien3189**
Revamps the Deltastation permabrig to offer prisoners more things to do: Cells have windows and chairs, added a kitchen with griddle, freezer, and other equipment, expanded mess hall eating area and added library. Also added prisoner lockers, and made the security locker room bigger.

image
(copied region)
image

image
(copied region) 
image

🆑
add: Upgraded Deltastation permabrig, adding a kitchen, library, resting area and a bigger isolation cell. Made sec locker room bigger.
/🆑

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Awesome, thanks for putting the screenshots of the edited areas.

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
image
The flooring here looks like a bug and will be reported as such by players.  Give them bed sheets.
image
Same as above. Looks weird. Bed sheets. Also, don't have a bed where someone's feet would be at your head. Let's not appease Hubert.
image
Flooring again.
image
It's mostly fine but I'd like you to justify your moving of the sec hardsuits, it places them in a weird spot where they're unwatched and completely unguarded.
You're missing a camera in this room, though. AI might have some visibility but there may be blind spots.
image
Potential camera blind spots?

Address the above and It'll be an easy approval. 👍

**Comment by Aurelien3189** [comment]
> image
> The flooring here looks like a bug and will be reported as such by players. Give them bed sheets.
> image
> Same as above. Looks weird. Bed sheets. Also, don't have a bed where someone's feet would be at your head. Let's not appease Hubert.
> image
> Flooring again.

> image
> Potential camera blind spots?
> 
> Address the above and It'll be an easy approval. 👍

image
Here's a picture with all the new additions. Moved the beds and shows all the bedsheets added. I thought that giving the floor design a square border would be too bland, so I tried to give it some weird pattern. Changed it to a square border though.

> image
> It's mostly fine but I'd like you to justify your moving of the sec hardsuits, it places them in a weird spot where they're unwatched and completely unguarded.

> You're missing a camera in this room, though. AI might have some visibility but there may be blind spots.

My idea with putting the hardsuits there was to add more suits (this station only starts with 2 for security) and to place them near EVA. Metastation has something similar, with suit storage units in the main prep room that (as far as I'm aware) can't be accessed during green alert, and the map also has a suit storage room near EVA, as shown here. The door itself never has prisoners going through, and is only used to get to EVA, the escape pods, or execution, plus it can only be accessed by security. So I figured it would be fine that way, would be open to suggestions though. 
Also added a camera there.
Edit: What's Hubert?

**Review by KathrinBailey — APPROVED** [review]
Fixed conflicts for you and fixed a tiny gripe and made an improvement.

**Pull request merged**
