### PR TITLE
[modular] makes loom loop on stackable loomables

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
title

## How This Contributes To The Skyrat Roleplay Experience
community members don't usually enjoy having to click multiple times on things when it could just be a loop do_after... also, looms USED to do this but was lost "in translation" (read refactor).

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

</details>

## Changelog

:cl:
qol: loomable, stackable items will now loop the action of being loomed
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Upstream this, it's good QoL

**Review by vinylspiders — CHANGES_REQUESTED** [review]
What @OrionTheFox said -- this would be good to upstream, though if you don't want to do that then I would prefer a Skyrat Edit over a master file override here from a maintainability standpoint. 

This kind of proc copy paste override is to be avoided unless absolutely necessary, because from my experience no one ever remembers to update it when something in the overridden proc changes upstream.

**Comment by jjpark-kb** [comment]
When/if I get to it, I'll try to put it on /tg/

**Comment by vinylspiders** [comment]
> When/if I get to it, I'll try to put it on /tg/

Thanks! Sorry I know it's a pain. I just spend a lot of time nuking copy paste procs whenever I find them because they really are a maintaining nightmare compared to just skyrat editing or upstreaming.

**Pull request closed without merging**
