### PR TITLE
[MODULAR] Tramstation Prison Refurbishment

### PR DESCRIPTION
**Pull request by kannthus**
## About The Pull Request

I'll cut straight to the jig, the prison on TramStation is a bit of a shambles, it doesn't have half of the usual stuff most prisons have and it doesn't even have cultivators. This is a small refurbishment update where I moved some stuff around and gave a bit more room to certain areas.

Listed changes:
I have adjusted the workshop to be longer rather then wider, and added a small R&R area for the prisoners, which includes a games vendor and a few action figures.
**Before:** 
CleanShot 2022-01-21 at 09 25 29

**After:**
CleanShot 2022-01-20 at 11 24 02

The Kitchen now has a grinder, a freezer with space milk/ingredients, some egg boxes in their produce crate and finally the classic apron.
CleanShot 2022-01-20 at 11 25 43

The garden now has the basic tools neccesary for good plant growing, including: a spade, 2 cultivators, analyser, a bucket and a sink to get water from.
CleanShot 2022-01-20 at 11 27 20

## How This Contributes To The Skyrat Roleplay Experience

All of the changes are QoL, currently it is impossible to properly farm in the garden unless you pester guards for a cultivator else your plants all die from weeds, the games vendor allows prisoners to keep themselves occupied and the rest is really self-explanatory. Tramstation is in a sorry state for prisoners and it truly needs this.

## Changelog

:cl:
qol: TramStation Prison has been refurbished with basic prison necessities  
/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
Mind putting some more seeds in the crate while you're at it? the pickings for seeds are pretty slim atm

**Comment by MassacreDemigirl** [comment]
did you use mapmerge2?

**Comment by kannthus** [comment]
> did you use mapmerge2?

I always do. Why?

(Also adding the more seeds as we speak)

**Comment by MassacreDemigirl** [comment]
youre getting integration test error might wanna check it out

**Comment by kannthus** [comment]
Tram is no-longer in rotation and for some reason can't fix the merge conflict so I'll just be closing this  ❤️

**Pull request closed without merging**
