### PR TITLE
[Modular] The Roleplay Update: Revengeance

### PR DESCRIPTION
**Pull request by Nerev4r**
## About The Pull Request
Can someone post a cat picture in the comments?
Anyway, this is code ENTIRELY by @GoldenAlpharex that never made it in. This makes it so that the server now has autopunctuation on says, me's, and subtles.

## How This Contributes To The Skyrat Roleplay Experience:
It's preferable, as a roleplay server (naturally something that demands comprehension and adherence to (thank you Skyrat SS13 user PCPorterro) the English language) to have people punctuating their sentences. If we didn't have the game automatically capitalize the first letter of your say, we'd be in a complete disaster.

Note: Someone in the comments, along with your cat picture, please advise me on how to make this thing capitalize isolated i's. I don't know regex.

## Changelog
:cl:
add: Autopunctuation has been turned on.
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
Negative gbp :trollface:

**Comment by Nerev4r** [comment]
> Negative gbp :trollface:

GBP is an illusion.

**Comment by PCPort** [comment]
*adherence to

I'm sorry, I had to.

https://www.youtube.com/shorts/VlhLEhJEWpE

**Comment by Gandalf2k15** [comment]
I have already stated why this something I am fully against in a previous PR. The benefits of punctuation do not outweigh the drawbacks of performance in running a regex every single message that is sent. Again, nothing personal, just a decision I've made and will be sticking behind.

**Pull request closed without merging**
