### PR TITLE
Security Tallborg

### PR DESCRIPTION
**Pull request by Oxotnak**
## About The Pull Request
Meka in each department now! I know that currently sec borgs not available at Skyrat but who knows maybe after some time you will enable them? And you still can use it for events if you will have idea that requires sec Meka.

## How This Contributes To The Skyrat Roleplay Experience
Currently it brings only availability to Skyrat's admins and it will bring security Meka for players at Fluffy Frontier as Skyrat's downstream.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
Screenshot_382
Screenshot_383
Screenshot_384
Screenshot_385

</details>

## Changelog

:cl: Oxotnak
add: added security Meka
imageadd: added sprites for security Meka
/:cl:

### CODE REVIEW

**Comment by Lukaster42** [comment]
It also needs an bluesec alt version, you know exactly why.

**Comment by Oxotnak** [comment]
> It also needs an bluesec alt version, you know exactly why.

Yeah I have idea for bluesec version and I'll make it if PR will be accepted

**Comment by Strazyplus** [comment]
ezgif-3-80e63cd58b

**Review by Ebin-Halcyon — APPROVED** [review]
Yeah.

**Pull request merged**
