### PR TITLE
MAKE BLUESHIELD COOL!

### PR DESCRIPTION
**Pull request by Draganfrukts**
## About The Pull Request

This PR turns the Blueshield into less of some paramilitary freak and more like a professional agent.

## Why It's Good For The Game

"I have complete confidence in Secret Service. These guys and gals are unbelievably professional. They know what they’re doing and I basically do what they tell me to do. Now, sometimes I’m the first one to admit that it chafes a little bit being inside this bubble. It’s the hardest adjustment of being president, not being able to just take a walk."

## Changelog
:cl:
tweak: Central Command's fashion division has decided that the Blueshield must look professional while doing their job! The Blueshield is now equipped with an armored suit jacket and expensive designer formal clothes.
tweak: The Blueshield now spawns with upgraded combat gloves and an M1911 handgun, instead of common gloves and the Wildcat.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
I am happy to test merge this for a bit.

**Comment by H0gberg** [comment]
Heya! Just a lil' feedback, could we get a suit skirt version of it as well as some possible reskins? it would be really cool!

**Comment by KasparoVy** [comment]
I saw this today and it looked really fucking cool.
Great direction

**Comment by Gandalf2k15** [comment]
In light of the new security stuff coming, we'll allow this, but, the blueshield will get their own gunset.

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
