### PR TITLE
tail/ears addition and datashark ability to be used

### PR DESCRIPTION
**Pull request by Echopsychotic**
## About The Pull Request
This will add two variants of the snake tail, re-add datashark tail that had not been coded in (we had sprites for it) and deer ears

images time
image
image
image
image
image

In game images: 
data shark
deer
snake dual
snake stripe 2
tail stripe 1

## How This Con
tributes To The Skyrat Roleplay Experience
People like tails I think and more deer ears as well. 
Datashark is just for people who wanna be more sharky with their tail waggin up a storm

## Changelog

:cl:
add: Added new tails and ears
fix: Datashark was not on the select screen before it is now 
imageadd: Added addition snake tail sprites Striped and dual colored as well as deer ears from virgo
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
dont we already have these deer ears?

also, screenshots and all that

**Comment by Echopsychotic** [comment]
> dont we already have these deer ears?
> 
> also, screenshots and all that

Deer ears that have been added are not part of skyrats sprites list.

**Comment by Echopsychotic** [comment]
yeah I have no idea how to update this to the current codebase so I am closing it and opening another one when I get the things up to date

**Comment by GoldenAlpharex** [comment]
@Echopsychotic If you could put images of the sprites being used in-game that'd be nice.

**Comment by Echopsychotic** [comment]
@GoldenAlpharex  updated the description in-game sprites shown

**Pull request merged**
