### PR TITLE
[MODULAR] Mining MODsuit Armor Balance Alternative

### PR DESCRIPTION
**Pull request by MassacreDemigirl**
## About The Pull Request
This is an alternative to #11409

Makes the base melee armor of Mining MOD 5

## How This Contributes To The Skyrat Roleplay Experience
Mining Armor booster gives 50 Melee armor in ashlands. Currently this causes miners to have a whopping Melee 100 armor which should not be possible for players. This PR makes the mining MODsuits in line with civilian MOD's since miners are by design to not have weaponry and armor on station. Thus this makes Miniing MODsuit 55 Melee, while Drake Armor is 65, giving the miners choice between having the utility of a modsuit or the extra 10 armor of drake. 

After playing miner more, I can say while the modsuit has many nice gimmick modules, most are as named: gimmicks.
Most of the modules are already competing with already existing items. Therefor I decided not to touch its pricing to not make the modsuit redundant.

_`Also since our round times are the double of TG, doubling the point total of Kitted MODsuit to 5000 to make it achievable from a 20 minute to a 40 minute grind`_

## Changelog

:cl:
fix: Fixes the Melee Armor X (100) Mining MODsuits. Now they have a base Armor of I (5). They also have lower innate Laser, Bullet, Energy and Bomb Armor since they gain it from the ash module
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
To be frank, that's a better alternative to what I did.

**Comment by YakumoChen** [comment]
gonna leave what I said on the other PR, the values need tuned so that the energy, bomb, bullet, etc armours are not doubled on lavaland from the base due to the module.

**Comment by gonenoculer5** [comment]
I would say make it 3000-4000. 5k feels like a lil bit too more.

**Comment by softcerv** [comment]
This might be another PR, but has anyone considered adding the MODSuit Jetpack/Thrusters to the mining vendor?

**Comment by SpaceVampire** [comment]
I agree that the armor needs the rebalance to be more in line with what it should be normally.
That being said, the price increase really doesn't feel needed. You could apply that same logic to all kinds of stuff.
Why not just make all of the research on the station take 2x the points to unlock? Just to give an example.

**Pull request merged**
