### PR TITLE
High luminosity eyes now keep the eye colour they are set to

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request
Simply keeps the eye colour that you set them to when they're on and off. Also, remembers the said colour.

## Changelog
:cl:
qol: High luminosity eyes now remember the color you set them to, and keep it when you turn them off.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Also makes the eye sprite actually good, dnm till I do that,

**Review by GoldenAlpharex — APPROVED** [review]
Not sure about making the eyes glowing too much sprite-wise, but the code checks out.

**Comment by GoldenAlpharex** [comment]
Also the red version of the glowing eyes only is red on the side versions, from the front they look white it seems.

Also, can we have a picture of what they look like in-game?

**Comment by Gandalf2k15** [comment]
Eyes glow isn't used actually, and it's basically the same as it was, just less abrupt.

**Comment by GoldenAlpharex** [comment]
> Eyes glow isn't used actually, and it's basically the same as it was, just less abrupt.

Still show pics :)

**Comment by thestubborn** [comment]
i've seen quite a few people complaining about the eye thing
should prob merge this soon

**Pull request merged**
