### PR TITLE
[MODULAR] Adds Digi/Muzzle Sprites for the Plated Mining Hardsuit

### PR DESCRIPTION
**Pull request by ghost**
image
image
image
image
image

## About The Pull Request
Pretty simple, just adds sprites for goliath-plated mining hardsuits that work for digitigrade legs or muzzles.

## Why It's Good For The Game
No more furries being stripped to their underwear sprite-wise! Keep that suit on!

## Changelog
:cl:
fix: Adds proper goliath-plated mining hardsuit sprites for Muzzles and Digitigrade Legs
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
x-x why did it change more than the two things i selected ree

**Comment by GoldenAlpharex** [comment]
What's that red light? I thought it was supposed to be some kind of blue windshield at the front or something.

**Comment by MLGTASTICa** [comment]
gandalf pls mark this as a fix and give them GBP since it was made after someone noticed they had no sprites

**Comment by ghost** [comment]
idk its a cool light-visor that the human version had, tried to carry it over to the muzzle version and it turned out well enough

**Comment by ghost** [comment]
also i-
could have marked this as fix damn

**Comment by GoldenAlpharex** [comment]
Huh, I never knew about the visor, I'll have to look into that.

**Comment by ghost** [comment]
i am in genuine pain

**Comment by Sethnov** [comment]
does this add different tail sprites?

**Comment by ghost** [comment]
i did indeed forget tail sprites, i'll get them done

**Comment by ghost** [comment]
ok, i made a new fuckin branch, this.. should fix it being stupid?

**Comment by ghost** [comment]
okay, gonna be honest? no clue how the tail sprites work. doesnt even look like the armored suit are their own type, just a texture, so the tail sprite might need some code that i cant even comprehend right now

**Comment by Gandalf2k15** [comment]
What you gotta do is set hardsuit_tail_colors = list("XXX", "XXX", "XXX") on the type of hardsuit you want, set the colours accordingly, whichever fits best.

> okay, gonna be honest? no clue how the tail sprites work. doesnt even look like the armored suit are their own type, just a texture, so the tail sprite might need some code that i cant even comprehend right now

**Comment by ghost** [comment]
@Gandalf2k15 tail added, ready for full review

**Comment by ghost** [comment]
> 
> 
> gandalf pls mark this as a fix and give them GBP since it was made after someone noticed they had no sprites

also yes pls give me good boy points

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by Sethnov** [comment]
did you also make bird tail sprite and other tails ?

**Pull request merged**
