### PR TITLE
[MODULAR] Tarkon Firelock Cutbacks

### PR DESCRIPTION
**Pull request by Zenitheevee**
## About The Pull Request

We have deemed that Tarkon's firelock budget was too damn high for this fiscal quarter and an audit was filed. We appreciate your co-operation

## How This Contributes To The Skyrat Roleplay Experience

y'know having something yell _**AAAAAAAA, AAAAAAAAAAA, ERRRRRRRRRR, AAAAAAAAAA, ERRRRRRRRRRRR**_ at you when you're trynna go through a xenos infested area is kinda.... While true to form, annoying.

## Changelog

:cl:
fix: removed problematic firelocks from Tarkon
/:cl:

### CODE REVIEW

**Review by GoldenAlpharex — APPROVED** [review]
That CI failure wasn't because of you, you've got clearance from me in terms of code for a merge if it still fails Blueshift's CI again.

**Review by Jolly-66 — COMMENTED** [review]
I can't see where you remove the firelocks because MDB is nothing but pain.

Where you DID remove them, I would suggest opting to use REGULAR shutters, the ones you can open/close with a button.

Regardless if you choose to add them or not, I'm fine with this PR.

**Comment by Zenitheevee** [comment]
> I can't see where you remove the firelocks because MDB is nothing but pain.
> 
> Where you DID remove them, I would suggest opting to use REGULAR shutters, the ones you can open/close with a button.
> 
> Regardless if you choose to add them or not, I'm fine with this PR.

p.much every space-facing window and the atmos-block windows.

There is one that _does_ still have one but thats mostly because it wont trigger constant alarms.

And yeah it should be good to go. If people attract carp to the windows long enough for it to break, Thats their fault and problem.

**Comment by weesnaw-ops** [comment]
thank fuck

**Comment by Nep993** [comment]
praise be

**Pull request merged**
