### PR TITLE
[MIRROR] Winter coats: A brand new coat of paint [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/72983
--------------------
## About The Pull Request

Resprites/facelifts the winter coats. Did you know alot of them had transparent pixels in the middle of them?

Coats

## Why It's Good For The Game

New bunch of sprites for old sprites that haven't seen much attention.
## Changelog
:cl:
imageadd: Winter coats have been resprited.
/:cl:

### CODE REVIEW

**Comment by Ebin-Halcyon** [comment]
Fixing, removing and respriting skyrat specific coats now.

**Review by Ebin-Halcyon — APPROVED** [review]

**Comment by Ebin-Halcyon** [comment]
I am going to murder whoever made the skyrat subtypes of clothing the main one.

**Comment by ghost** [comment]
And now, my time has come...

**Comment by OrionTheFox** [comment]
Nevermind my github decided I'm not allowed to code for this codebase any more :D

**Pull request merged**
