### PR TITLE
Mince pies

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Adds mince pies.

Zydras made a less horrendous version of my codersprite, God bless.
image

They can be made from raisins, an apple, and a pastry base.
Mimce pies can be made from the same, plus 25u of nothing.

## How This Contributes To The Skyrat Roleplay Experience

They are tasty and it's Christmas. If you dislike this PR you dislike Christmas. Fact.

## Changelog
:cl: tf4, Sprites: Zydras
add: Mince pies are now available to create!
/:cl:

### CODE REVIEW

**Comment by Ebin-Halcyon** [comment]
Blessed codersprites.

**Comment by Stalkeros2** [comment]
salad olivier when

**Comment by hugmeorelse** [comment]
It has "soul" one would say, because it consumed mine.

**Comment by hugmeorelse** [comment]
This coder sprite has "soul" one would say, because it consumed mine. 

It may be worth pinging on the Discord for a better sprite. It looks like a starfish hanging on for dear life against the edges of the pan it's in.

**Comment by hugmeorelse** [comment]
This coder sprite has "soul" one would say, because it consumed mine. It looks like a starfish hanging on for dear life, so it won't get pulled out of the pan. It definitely has a place on the fridge. 🥇 

Just kidding, @tf-4. <3 Don't hurt me.

It may be worth pinging on the Discord for a better sprite. Alternatively, you could make an edit of existing pie sprites.

**Pull request merged**
