### PR TITLE
make cc have bar, dorms, and more

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
image
Adds a few accommodations to CC to make it more RP friendly (bar, games, dorms, better medical) 

## How This Contributes To The Skyrat Roleplay Experience
Give some peace to those who don't want to EORG and just relax at the end whilst still getting the satisfaction of leaving on the departure shuttle.

## Changelog

:cl:
add: added bar, dorms, and games to CentCom
add: added the eorg-banned arena to CentCom (more visible)
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
That's cute, I like it.

Do the pod bays still work, though?

**Comment by jjpark-kb** [comment]
> That's cute, I like it.
> 
> Do the pod bays still work, though?

yep, pod bays still work

**Comment by Sigmar-alkahest** [comment]
that reminds me of when there was an EORG-free area of centcomm ages ago. it looked kinda like that.

**Comment by MassacreDemigirl** [comment]
good now add the EORG arena teleport from TGCM and we are golden

**Comment by Gandalf2k15** [comment]
This requires massive policy changes first.

**Comment by jjpark-kb** [comment]
> This requires massive policy changes first.

What policy changes would be required? We already are trying to promote no EORG, this just further cements that.

**Comment by jjpark-kb** [comment]
Going to work on it in an alternative method.

**Pull request closed without merging**
