### PR TITLE
[MODULAR] Trait recodes

### PR DESCRIPTION
**Pull request by ArdentSpark**
## About The Pull Request
Recodes Monophobia, Mute and Joker to use a named variable instead of a one letter variable.
Relocates Mute from a file and folder that only contained Mute, to where the rest of the negative traits are located.
One letter variables bad

## How This Contributes To The Skyrat Roleplay Experience
It doesn't.
But it contributes to the Skyrat Coding Experience by improving readability.
Which contributes to the Skyrat Roleplay Experience.
Kinda.

## Changelog

:cl:
code: Renamed Monophobia, Mute and Joker variables for code readability, as well as correctly placing Mute with the rest of the negative traits.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Could you check the positive quirks and the neutral quirks as well? It wouldn't take you long and it'd kill more birds with the same stone.

**Comment by ArdentSpark** [comment]
I took a look at the ones in the similar file locations, because I had the same thought. Monophobia is the only one in modular_skyrat\master_files\code\datums\traits that uses single letter variables

unless theres somewhere else modular traits are stored as well

**Comment by ArdentSpark** [comment]
WAIT NO I'VE LIED. I'VE SPOTTED ONE.

**Comment by ORCACommander** [comment]
not sure why you are using the fuck label.....

**Comment by GoldenAlpharex** [comment]
> not sure why you are using the fuck label.....

What fuck label? Are you sure you're not seeing things? 😎

**Comment by ArdentSpark** [comment]
I don't know what you're talking about.
I think I must have pressed an unlabelled one letter hotkey on my keyboard which resulted in an undocumented chain of events which may or may not have resulted in strange things occuring. (get it?)

I don't know how github works I just press buttons and smile as they happen.

**Comment by GoldenAlpharex** [comment]
I'll mark this as a Draft because I just noticed that we seem to have more than one `negative.dm` modular file, and I'd like to have only one, which is the one you have in this PR.
As such, move the stuff that's in `modular_skyrat\modules\customization\datums\traits\negative.dm` and delete the file, and as well as the `traits/` folder that contains it.

If you need help, hit me up on Discord, but we're going to do this properly, and you'll feel proud of yourself 😎

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
I should have put my review in here. Whoops!

**Comment by ArdentSpark** [comment]
Review should be resolved with commits 8f7c543 and 0d8a48d

**Review by GoldenAlpharex — APPROVED** [review]
Thank you.

**Pull request merged**
