### PR TITLE
[modular]adds a red shirt and a toggleable suit jacket 

### PR DESCRIPTION
**Pull request by thestubborn**
## About The Pull Request

title
also a skirt since someone asked
also also a kilt digi version because it took like two seconds

## How This Contributes To The Skyrat Roleplay Experience

drip cool or something, whatever
they're more versatile than the scarface suit, as you can toggle the jacket, the jacket can be used for
dunno
whatever
also, a white suit jacket
and a red shirt with white pants, with a skirt varient, that's exactly what was added
image
image

## Changelog

:cl:
expansion: red shirt and a toggleable white suit jacket now in vendors
fix: oh yeah also a digi cap kilt now
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
@thestubborn You need a lot more pictures in your PR body, this isn't representative of what you're adding. Also, please be more descriptive with what you're actually adding.

**Comment by thestubborn** [comment]
> 
> 
> @thestubborn You need a lot more pictures in your PR body, this isn't representative of what you're adding. Also, please be more descriptive with what you're actually adding.

the kilt was a last minute thing
and, I think "red shirt and suit jacket" is pretty descriptive

**Review by GoldenAlpharex — APPROVED** [review]
Code checks out, I guess. Those clothes have weird names but I guess we can always change that when someone has better inspiration.

**Comment by thestubborn** [comment]
> 
> 
> Code checks out, I guess. Those clothes have weird names but I guess we can always change that when someone has better inspiration.

again, full confession 
I was kinda completely stumped in that department
and "director suit" doesn't go with the desc gag
and only like three people would be like "oh yeah jackie treehorn!"

**Comment by GoldenAlpharex** [comment]
The all-lowercase in the PR body annoys me but whatever I guess, lol.

**Comment by thestubborn** [comment]
> 
> 
> The all-lowercase in the PR body annoys me but whatever I guess, lol.

that's how I type

**Pull request merged**
