### PR TITLE
Slightly less important map reset of everything not in the map_files folder (so ruins, gateways, shuttles, and so on)

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
Gay ass why didn't you do the ENTIRE FOLDER.

**Comment by Paxilmaniac** [comment]
uhhhhh fuck you that's why

**Comment by Paxilmaniac** [comment]
I believe this has uncovered some missed mirrors

**Review by Jolly-66 — APPROVED** [review]
I can assure Paxil didn't break anything.

**Pull request merged**
