### PR TITLE
[NON-MODULAR] ""removes"" """"""LRP"""""" words from the code

### PR DESCRIPTION
**Pull request by Draganfrukts**
## About The Pull Request

This PR switches out the names of Cargonia for Cargoslavia.

## Why It's Good For The Game

i can't fucking say cargonia IC so let's go with the option everyone says it's okay

## Changelog
:cl:
tweak: After Central Command, with the support of Nanotrasen, banned Cargonia as a movement, the Free Trade Union's workers have been starting to use the newly-formed state of Cargoslavia as a term.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
The fastest close in the West

**Comment by Trubbl3** [comment]
speedrun closed merge WR any%

**Comment by hugmeorelse** [comment]
The IC filter is config-based. :)

**Comment by hugmeorelse** [comment]
Ah, I read the code. Hm, interesting.

**Comment by Draganfrukts** [comment]
Shaking my damn head.

**Comment by hugmeorelse** [comment]
> Shaking my damn head.

Free Trade Union

Free Trade Union

Free Trade Union

**Comment by Cheshify** [comment]
No lmao, at least make it modular

**Comment by Draganfrukts** [comment]
> 
> 
> No lmao, at least make it modular

I'm not making a modular folder and file for a 4 line change.

**Comment by Swiftfeather** [comment]
SMH imagine not following modularization guidelines

**Comment by FlamingLily** [comment]
> 
> 
> > No lmao, at least make it modular
> 
> I'm not making a modular folder and file for a 4 line change.

Can't you just put it in master_files?

**Comment by Gandalf2k15** [comment]
COMMENTS WHERE ARE YOUR COMMENTS

**Comment by Gandalf2k15** [comment]
imma see this merge conflict in 10 months and not know why it's conflicting and override it

**Comment by KathrinBailey** [comment]
talk about getting cargonia removed from the config word filter if it even exists as "cargo slavia" is just as "LRP" (I don't even think it's that bad at all to be honest) as "cargonia".

**Comment by Draganfrukts** [comment]
> talk about getting cargonia removed from the config word filter if it even exists as "cargo slavia" is just as "LRP" (I don't even think it's that bad at all to be honest) as "cargonia".

Nothing changed the config here. You can't say Cargonia IC.

When I talked with Xyel he said Cargoslavia was better, so, I guess I'll continue to use the term. Mechanical backing of it isn't crucial so

**Pull request closed without merging**
