### PR TITLE
Chrono legionnaire outfit fix

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request

Does what it says on the tin. It's broke when displaying the sprite, and missing the modules.

## How This Contributes To The Skyrat Roleplay Experience

Less broken things are cool.

## Changelog

:cl:
fix: Chrono legionnaires have fixed their suit's malfunctioning visual drive.
/:cl:

### CODE REVIEW

**Comment by Ebin-Halcyon** [comment]
how the fuck does it already have a merge conflict.

**Comment by theselfish** [comment]
Something something upstream?

**Comment by Ebin-Halcyon** [comment]
> Something something upstream?

SR specific.

**Review by tf-4 — APPROVED** [review]

**Review by GoldenAlpharex — APPROVED** [review]
I've seen this one before.

**Pull request merged**
