### PR TITLE
[Modular] Removes the Soul of the Inflatable Box, Circuit Assembly Printer

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Does what it says on the tin. Resprites both items to fit in with everything else.
I was gonna touch the assemblies themselves too, but I got cold feet about it. Ah well.

## Why It's Good For The Game
deletes soul, removes soul. soul bad

## Changelog
:cl:
imageadd: The Electronic Circuitry Printer and Inflatable Box have been resprited.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
image

**Comment by Gandalf2k15** [comment]
is that pixel supposed to be there

**Comment by Arctaisia** [comment]
> is that pixel supposed to be there

Shhh, he's just having some time to himself before he rejoins with the rest of the sprite

**Comment by unit0016** [comment]
> is that pixel supposed to be there

It's not. It isn't actually there in the DMI, either, IconDiffBot just has problems with animated sprites. The same effect is in the other sprite.

**Pull request merged**
