### PR TITLE
Random mining! [DOWNSTREAM IMPORTANCE LEVEL 1]

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

As part of the mining expansions, we bring you a system that will randomly load a mining map from a pool of available maps! 

We've currently only got two maps in the pool, your bog standard lavaland map and rock planet. If you are interested in adding more, please, feel free to make a 255,255 map, with gen turfs and a mining station. We're looking for perhaps a jungle-based map, or something else. It's fine if these maps are more exploration than mining as well. 

If you need help with this, check how lavaland/rockplanet do it.

The subsystem will avoid choosing a map that was previously selected!

# Instructions for adding a new map:
1. In _maps/map_files/Mining, create your new map file, and name it something unique. Ensure you follow the above map requirements. For this tutorial, we will have named it MyMining.dmm
2. Define your mining traits, or, pick from the existing ones(we'd prefer you created a new one) - To do this, open the maps.dm file in _DEFINES/~skyrat_defines/maps.dm and create a new entry. See ZTRAITS_ROCKPLANET in that file for guidance. We will name ours ZTRAITS_MYMINING
image
3. After you have chosen your ZTRAITS, head to _DEFINES/~skyrat_defines/mining_traits.dm and add your entry into the mining_traits global list, ensure you give it a unique key, we will name it mymining.
image
4. Head to config/skyrat/mining_levels.txt and add a new entry into the text file, format it like so: YourExactMiningFileName.dmm+YourExactMiningZtraitsKey - E.g: MyMining.dmm+mymining
5. Finally, add your exact map path to the _basemap.dm file list.
image

- Make sure you test it though, testing testing testing.

## Why It's Good For The Game

Enables us to add new and exciting new maps with different ruins!

## Changelog
:cl:
add: A new random mining map system - We are looking for people willing to create new maps, if you're interested, head to: https://github.com/Skyrat-SS13/Skyrat-tg/pull/4957
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
# Before you start any work, wait until this is merged.

**Comment by Gandalf2k15** [comment]
Due to the fact this loads 1 mining map, memory won't be an issue, as we're doing the exact same thing as before.

**Comment by KasparoVy** [comment]
Fuck yes man! Wow. Love seeing how this is being developed. Good way to work around the mining issue
The greed in me wishes I didn't have to share but there's plenty ore to be mined, ahaha.

Just gotta be wary on the rock planet we got megafauna but little to no way of getting hide plates or cores depending on sparse mob rng, and that mining actively requires a hardsuit so you don't get hurt by pressure of breaking rocks.

**Comment by Gandalf2k15** [comment]
> Fuck yes man! Wow. Love seeing how this is being developed. Good way to work around the mining issue
> The greed in me wishes I didn't have to share but there's plenty ore to be mined, ahaha.
> 
> Just gotta be wary on the rock planet we got megafauna but little to no way of getting hide plates or cores depending on sparse mob rng, and that mining actively requires a hardsuit so you don't get hurt by pressure of breaking rocks.

fixed! 
image

**Comment by KasparoVy** [comment]
> 
> 
> > Fuck yes man! Wow. Love seeing how this is being developed. Good way to work around the mining issue
> > The greed in me wishes I didn't have to share but there's plenty ore to be mined, ahaha.
> > Just gotta be wary on the rock planet we got megafauna but little to no way of getting hide plates or cores depending on sparse mob rng, and that mining actively requires a hardsuit so you don't get hurt by pressure of breaking rocks.
> 
> fixed!
> image

Oh you absolute chief, cheers! Really enjoyed the rock-planet and this is greatly appreciated QOL.

**Pull request merged**
