### PR TITLE
[SEMI-MODULAR] Draconic Necklace

### PR DESCRIPTION
**Pull request by softcerv**
## About The Pull Request

Adds a necklace to the game that grants the wearer knowledge of the Draconic language when worn, the wearer looses this temporary knowledge when the necklace is removed ((unless they already have innate knowledge of the language.)) This necklace can be acquired through the tribal crafting menu and requires the user to be an Ash Walker along with the following materials: one bone, two sinew, and a legion core.
image
image

((Please PM me at Bunny#5839 on discord, if you would like to redo the sprite art for the necklace!))
## Why It's Good For The Game

Ashwalkers are unable to speak common and integrated circuit translators are an iffy solution at best. This item gives an easy way for miners (or other lavaland roles) to more easily communicate with Ashwalkers, hopefully encouraging RP.
## Changelog
:cl:
add: Adds the Draconic necklace, an item craftable by ashwalkers through tribal materials that allows the user to speak Draconic so that they can communicate with Ash Walkers. 
imageadd: added Obj and Mob textures for the Draconic necklace. 
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
This is... stupid powerful and easy to make, perhaps make it megafauna loot or making it unique to ashwalker crafting the same way skeleton keys are?

**Comment by thestubborn** [comment]
yeah, agree w/ the ashwalker lock, it'd be great for "honorary tribe" shit

**Comment by softcerv** [comment]
> 
> 
> yeah, agree w/ the ashwalker lock, it'd be great for "honorary tribe" shit

It has been changed.

**Comment by softcerv** [comment]
*scream

**Comment by hugmeorelse** [comment]
> > yeah, agree w/ the ashwalker lock, it'd be great for "honorary tribe" shit
> 
> It has been changed.

This is a good change. I think this will introduce some interesting roleplay opportunities.

**Review by Funce — APPROVED** [review]

**Pull request merged**
