### PR TITLE
[non-modular] readds the custom say emote (ie. radio emotes)

### LINKED ISSUE #8288: radio emotes broken :mistake:
## Round ID:
3049

## Testmerges:
Capping Threat Level to 70 [Test Merge Only] 
[SEMI-MODULAR] [READY] Blueshift 

## Reproduction: 
emoting over radio nolonger works. to reproduce, simply say ";puffs air into their microphone obnoxiously and says*Testing testing one two one two"

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

Fixes #8288 

## How This Contributes To The Skyrat Roleplay Experience

now you can do stuff on the radio again

## Changelog

:cl:
fix: radio emotes are now a thing again
/:cl:

### CODE REVIEW

**Comment by Sir-Lagsalot** [comment]
🙏 bless you, glad to see this back. Which method of radio emoting does this readd, the one that uses "!" or the one that uses "*", or both, like we used to have?

**Comment by Seris02** [comment]
Uhhhhh, the *

**Comment by Gandalf2k15** [comment]
This affects mob say, I am not a fan of editing such core files down here, say.dm is one of them.

**Comment by Iamgoofball** [comment]
We still don't know what's causing byond to eat says occasionally,let's not add more fail points.

**Pull request closed without merging**
