### PR TITLE
[MODULAR] allows surgery caps to toggle hair visibility

### LINKED ISSUE #22489: Surgical caps delete hair + more
The new change to surgical caps does not look good. Not only does it not look like tucked hair, but rather your character being made bald, it also removes elements of your sprite that would not be tucked under a cap; such as large anthro ears, horns, frills and more. This change will simply mean nobody will wear the cap, anymore, with the end result being LESS people wearing appropriate medical garments than there were before. 
Screenshot 2023-07-16 092604
Screenshot 2023-07-16 092619
Screenshot 2023-07-16 092623

### PR DESCRIPTION
**Pull request by press-mark**
## About The Pull Request
Fixes #22489

allows doctors to choose between looking like a baldie and allowing hair & other head features like ears to actually be visible.

## How This Contributes To The Skyrat Roleplay Experience
good for player customisation and creativity.
it's a toggleable action through using the cap in your hand, should be a lot less jarring than suddenly losing your ears

### Before
dreamseeker_NvYxAtibfA

### Adjusting cap
dreamseeker_1pURvckQW6

### No longer bald
dreamseeker_SCTmEHsrYE

<details>
<summary>Screenshots/Videos</summary>
  see above screenshots

</details>

## Changelog

:cl:
add: You can now toggle the visibility for hair & other features on your noggin when wearing surgery caps
/:cl:

### CODE REVIEW

**Comment by lessthnthree** [comment]
Can you please try PRing this upstream first?

**Comment by lessthnthree** [comment]
If upstream doesn't want it, directions on how to make a PR modular are here: https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/modular_skyrat/readme.md or just shout out on Discord.

**Comment by press-mark** [comment]
done and done, i'll leave it drafted here in the meantime

**Comment by press-mark** [comment]
closing in favour of #22552

**Pull request closed without merging**
