### PR TITLE
[MODULAR] Restores Low End Space Icon & Randomness

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request

tgstation made (awful) changes recently that made space look like THIS
dreamseeker_YuYFvv77q1

Then like THIS (not live yet on skyrat).
dreamseeker_AgEEkhRDkR

For what? shaving a whole fraction of a second off, hypothetically, of init time? The job of the server is to pre-bake things as client-side rendering is pretty much non-existent beyond filters and other particular things. Not everyone likes the parralax, feels comfortable with the parallax or even otherwise can run it on their hardware at cost. We don't need to shave a fraction of a second off init because it's pretty damn fast anyways, and, once I am done BENCHMARKING on a CELERON TABLET I will prove it silly. I personally think init time saves like this are fetishized when it throws the user experience out of the fucking window, especially for broke/third world gamers who run systems with like, 2GB of memory. We have players running truly destitute systems. 
## Before
dreamseeker_vT1uJeDmgx
## After
dreamseeker_lBhaey7ZFd

I could brand this as saving 4 seconds of init time, to be deceiving. This is with 64GB of ram on a Ryzen 5800H, Samsung 980 EVO NVME with lowmememorymode defined. 
## How This Contributes To The Skyrat Roleplay Experience

This readds a decent looking space option for those seeking every ounce of performance in their client in exchange for the server using a fraction of a second more CPU during init.

Here is how the init speed differs on an actual potato PC, hosting the server (this CPU can't even run lighting updates in real time)
## Unticked, Celeron N4120
uNNkmmSv8E

## Ticked, Celeron N4120
2jbUNqo2rb

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
dreamseeker_lBhaey7ZFd

</details>

## Changelog

:cl:
add: Old space returns for those who choose it. 
/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
(You can't measure init time consistently without Tracy)

**Comment by dawsonkeyes** [comment]
okay but what if i actually really like near-fullblack space? i feel like it's not an awful option

**Comment by nevimer** [comment]
> okay but what if i actually really like near-fullblack space? i feel like it's not an awful option

It's broken like that unintentionally all the time if you turn down your parallax plane options, so, weh

**Comment by nevimer** [comment]
Fullblack space harms gameplay becuase:

- invisible light source
- can't see if you're moving, in space
- can be confused for click catcher
- black, and near black chosen, will shift greatly depending on monitor calibration and range and be  potentially be indistinguishable to all but the trained eye 
None of these issues existed with parralax, and none of these issues exist with old space sprites.

**Comment by nevimer** [comment]
> (You can't measure init time consistently without Tracy)

Can you test the rand define with Tracy, and then with the whole file unticked? And then the old define? IDK how to use that.

**Comment by Zonespace27** [comment]
> > (You can't measure init time consistently without Tracy)
> 
> Can you test the rand define with Tracy, and then with the whole file unticked? And then the old define? IDK how to use that.

yep, it's all entirely possible since tracy tracks execution time of individual procs

**Pull request closed without merging**
