### PR TITLE
[MANUAL MIRROR OF 9774 AND 9798] DELTASTATION: Complete service + arrivals revamp, cargo tweaks (some maintenance was harmed in the making of this pr)

### PR DESCRIPTION
**Pull request by ghost**
## Original PR: tgstation/tgstation#62972
CLOSE #9774 AND #9798 IF MERGED, MANUALLY MIRRORED HERE
## About The Pull Request

This PR completely revamps the service department and arrivals wing of Deltastation. Cargo received some tweaks as well to accommodate these changes.

image

Read the linked PR (or the closed mirror, #9774) for the rest of it

<hr>
Manually mirrors the changes to Deltastation to our modular map; minimal differences from the base map (surprisingly), with the most notable being the arrivals docks themselves being fit for our custom ships, an NT Rep office, and a few of the Teleporter Beacons being replaced with the random variant (as per TG):

image

## How This Contributes To The Skyrat Roleplay Experience
Saves time for the maptainer having to manually do these large-scale changes in the future, as well as the TG reasoning:

> Deltastation has always been a very samey map - Metastation, but larger. A lot of its design is a little antiquated by now and overall it could use some facelifts. This begins the process by re-doing Deltastation breathing some new life into it.
Service was chosen as it was largely pretty lacking and simple in its design. Every corner of service was a square connecting to either the bar or the main hallway.

## Changelog

:cl: Melbert, Orion_the_Fox
add: Deltastation - Service and arrivals complete revamp! Cargo tweaks! (Manually added to our Modular map as well, PLUS NT rep office! -Orion)
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Run an empty commit so we can get the Map Diff Render of Skyrat's Delta :)

**Comment by ghost** [comment]
> Run an empty commit so we can get the Map Diff Render of Skyrat's Delta :)

Actually, I'm gonna probably be adding a few modular things that were never added, so it can do the Map diff when I finish that

**Comment by ghost** [comment]
why so buggy grr

**Review by KathrinBailey — APPROVED** [review]
I think this is absolutely horrible and would much prefer to keep the old version, but I know it's not sustainable.
I declare the SR version of the map free game for reworking or reverting because this shit is **sinful**.
This entire thing is kind of a huge slap in the face for service mains, but I'm sure they'll be able to tolerate it since they must be used to it by now.

**Comment by ghost** [comment]
> I think this is absolutely horrible and would much prefer to keep the old version, but I know it's not sustainable. I declare the SR version of the map free game for reworking or reverting because this shit is **sinful**. This entire thing is kind of a huge slap in the face for service mains, but I'm sure they'll be able to tolerate it since they must be used to it by now.

but at least my arrivals ERT dock is neat, right? :)

**Comment by Iamgoofball** [comment]
You guys didn't use the map merger for this.

Use the map merger next time.

**Comment by Iamgoofball** [comment]
chrome_hLc4cUrbKg

**Pull request merged**
