### PR TITLE
[NON-MODULAR] tgui Say/Me/OOC/Whisper/Subtle/Subtler

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

https://user-images.githubusercontent.com/4081722/150669070-c232a68e-31f5-4114-a07a-49db79950113.mp4

Closes #10486
## How This Contributes To The Skyrat Roleplay Experience
tgui input good
plus we could set this up with callbacks and shit to like, actively turn on/off when they're literally typing letters lmao
## Changelog

:cl:
qol: Clientside input verbs have been moved to use tgui popups. People with tgui input disabled get normal inputs as usual.
qol: Typing Indicators should now be more reliable when they start/stop.
qol: Typing Indicators no longer disappear because you clicked on your screen.
qol: Typing Indicators now remain as long as you're using some form of typing input.
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
This is literally the worst possible solution.

Have fun having a fundamental game mechanic rely on external tooling that is prone to breaking for many users.

**Comment by Iamgoofball** [comment]
tgui functions normally for people who are using modern hardware, and you can always turn it off in preferences if you really hate tgui.

tgui also isn't "external tooling" and it's a hell of a lot more reliable than the interface.dmf file lmao

**Comment by Kapu1178** [comment]
> tgui functions normally for people who are using modern hardware, and you can always turn it off in preferences if you really hate tgui.
> 
> tgui also isn't "external tooling" and it's a hell of a lot more reliable than the interface.dmf file lmao

You are pushing an agenda and it shows. TGUI, is by definition, external tooling. It is not built into BYOND and relies on external updates to function. 

interface.dmf doesn't have issues. This is simply a lie. It is literally how all custom client-side interfaces even work, and has been that way for a decade. As far as I'm aware, this PR doesn't even fix lock time, and arguably *makes it worse*.

**Comment by Iamgoofball** [comment]
I'm pushing an agenda of "reasonable and good looking UX". Boomers upset that interfaces aren't raw html anymore are not a concern of mine. Literally everything we've ever coded for SS13 is "external tooling". We rely on external tooling to compile the video game via the juke build. That ship has sailed.

**Comment by Kapu1178** [comment]
> I'm pushing an agenda of "reasonable and good looking UX". Boomers upset that interfaces aren't raw html anymore are not a concern of mine. Literally everything we've ever coded for SS13 is "external tooling". We rely on external tooling to compile the video game via the juke build. That ship has sailed.

Im 19. I've been around BYOND for 2 years. I am the least "boomerish" person in this community. Jukebuild is not *required* to compile the game. If you disable the defines for it, it will compile just fine. Hell, you can even change the #ERROR to #WARN in Jukebuild itself. The only external tooling TG-base servers currently rely on is Auxtools for their atmospherics, and even then the game is technically playable. 

Why are you giving misinformation in regards to how Byond fundamentally works.

Also, please address my other comments.

**Comment by Iamgoofball** [comment]
I've been in this game for a very, very long time, about 10 years. Also, please don't randomly post your personal details on the internet because you're trying to win arguments about UI design.

I've seen every interface we've had for SS13, all the way back to the terrible html UIs and the godawful chemistry dispenser UI that used a custom .dmf interface, then NanoUI when it came and all the improvements it brought, and then NanoUI 2.0 when that got reworked and redone, and then tgui 1.0 when that came around and all the improvements it brought, and then tgui 2.0 when that came.

The absolute worst interfaces were always the .dmf ones.

tgui interfaces are the most responsive, the nicest looking, and the most usable interfaces we've had in this game. These tgui interfaces for speech provide a massive bonus over the default byond windows by showing an automatically updating character count, something that's *incredibly useful* for an HRP SS13 server like Skyrat where people regularly make long, detailed posts.

``Jukebuild is not required to compile the game. If you disable the defines for it, it will compile just fine.``

You're not entirely wrong, but you're also wrong in that tgui doesn't compile, which is critical for the game because it's our front end we use for UIs. I'm not interested in debating someone who doesn't realize that not compiling tgui is a problem while insisting on .dmf changes.

Arguing that "it technically compiles if you don't use the juke build" is arguing that technically, because the building didn't fall apart instantly when you cut a support beam, that the support beam wasn't essential. You can cut the support beam that is tgui and then tgui starts breaking, and tgui is our UI front end.

tgui isn't just some random external library we got off of pip or whatever, it's our in-house UI tooling we made for the express purpose of using in SS13, and it's frankly insulting to claim otherwise.

Also, no, we don't use auxtools for atmospherics, we use auxtools for quite a few other things, but not atmospherics.

**Comment by Kapu1178** [comment]
This is objectively a lie. The "command line" in every ss13 codebase relies on this to function. Also, no matter how hard you try, TGUI will never have non-sleeping inputs. This PR effectively wraps input(), instead of relying on completely client-side macros to handle all of it, cutting the middle-man of the server out entirely.

These aren't a new interface standard. This is using a fundamental byond functionality that has existed and worked for years, and is what basically the entire game relies on to do client-side work.

As for claiming you aren't interested in discussing with me, frankly? Im not interested in talking with you either. However, you are actively attempting to make the codebase worse and are lying about how byond works. Its disgusting, and you do not have the right to shut down discussion in this instance.

I have no interest in dealing with strawmans and straight up lies about BYOND as an engine. I have gone to the correct place to have this handled internally.

**Comment by Iamgoofball** [comment]
>I have no interest in dealing with strawmans and straight up lies about BYOND as an engine. I have gone to the correct place to have this handled internally.

what are you going to do, write lummox an email? that won't change the fact we don't like using .dmf files because they suck to work with, tgui is the future, move on, etc.

**Comment by Kapu1178** [comment]
TGUI is a *very fancer* wrapper for winsets and skins. And who is "we"?. The reason .dmfs haven't been used much is because they are completely undocumented in the DM Reference and are limited in functionality. What limited functionality they have is **EXTREMELY GOOD** because its practically the only way to do client-side work in Byond that completely cuts out the middle man that is your internet connection. Please stop lying.

**Comment by Iamgoofball** [comment]
I see absolutely no reason we should be writing UI elements in the .dmf file when we've got a perfectly capable javascript powered UI engine written explicitly for what we want to do with UIs in SS13, that's time tested and has worked just fine for our needs for years, along with helping us make the game's UI actually reasonable to use from the hell that it was before back in the day.

The actual editing tools for .dmf UIs are broken, with no labelling, missing icons, and are archaic due to being from the early 2000s with nearly zero changes to them since.

Pure .dmf UIs cannot do 90% of what we want from a modern UI in SS13 when it comes to development.

You're right in that we have to technically walk through the .dmf to do tgui work. We specifically do as little of this as possible and the average developer should never, ever have to touch the .dmf to make any form of UI for this game because .dmf sucks balls to work with, due to being undocumented and, surprise, still requiring some of the back and forth networking you're complaining about. winset is a sleeping proc, after all.

I had to go consult with some other boomer coders because it's been almost a decade since someone advocated for doing UI work in .dmf files because everyone else developing for this game is sensible and understands that modern js-based UI work is the correct approach to doing UI work.

**Comment by Kapu1178** [comment]
None of this is about TGUI vs Byond as a concept. TGUI is great for most things, yes, an incredibly basic text input box that is used hundreds of times a minute is not one of them. You have no interest in having an honest discussion, and as such I am simply leaving this be and letting maintainers deal with it.

**Comment by Iamgoofball** [comment]
I'm going to contact the person who made the PR you're copying around to other repos, since you don't seem to actually understand what the PR does based by all the "black magic" comments you've left on other repositories and all over the code for your say PR. 

I made this PR because I gave your PR a try, and the only change I noticed from your PR was that my hotkeys kept triggering during text popups, and I kept having issues with my messages constantly being prefaced with T or Y for talking and whispering simultaneously. There was absolutely no difference in popup lag from before or after your PR. I'm not convinced it's worth making such serious alterations to the .dmf file and how input works if you're not going to utilize it to actually improve on the UI of input.

**Comment by SplinterGP** [comment]
> This is literally the worst possible solution.
> 
> Have fun having a fundamental game mechanic rely on external tooling that is prone to breaking for many users.

TGUI is literally a webwindow, there's no secret on it and it works HTML, only case that it will break is on users that aren't having IE11(Linux users that use wine) and even then it can work sometimes. also how the fuck do you trust on BYOND ? literally every other update there's some regression due to breaking changes, i fail to see how something that we ourselves have the code of is better than something that relies on BYOND itself

Infact there's an actual reason here we should not use this for windows like that, UNLESS IT WAS MADE ALREADY TO NOT POOL TGUI INPUT BOXES, the case is that like all other TGUI windows it is pooled and once opening them alot causes them to take a while to open and other laggy shit, the way to fix that is to make them not pool, again it mightve already been done on /tg/ or here but it was on the list of to-do things so it is faster to open by the guy that made the boxes.

**Comment by Kapu1178** [comment]
Having faith in byond is *generally* not a great thing, yes. But skins and macros, are a core functionality of byond that has not and will not fail, because if skins break down *you're gonna have alot more problems than the input window breaking*. I trust byond's skins over TGUI any day, because they are core to Dreamseeker working at all. If you notice, hotkeys actually already call winsets, this is how input windows have worked in SS13 since the day it was created.

**Comment by MacBlaze1** [comment]
> Having faith in byond is _generally_ not a great thing, yes. But skins and macros, are a core functionality of byond that has not and will not fail, because if skins break down _you're gonna have alot more problems than the input window breaking_. I trust byond's skins over TGUI any day, because they are core to Dreamseeker working at all. If you notice, hotkeys actually already call winsets, this is how input windows have worked in SS13 since the day it was created.

Why are you splitting hairs over the possibility of TGUI breaking down. Every time a company upgrades their systems or software it comes with the risk of things being incompatible or breaking down. I think this nice UI is worth the risk. If TG was obsessed over stability and the impossibility of errors in tooling, it wouldn't be where it is today. Please try to accept the fact that no environment is risk free.

**Comment by Iamgoofball** [comment]
No, we're not doing this upstream. We don't do typing indicators upstream.

**Comment by Mothblocks** [comment]
We don't want this upstream FYI, at least not in this form.

**Comment by Gandalf2k15** [comment]
Critical input boxes should not be using TGUI at this time.

**Pull request closed without merging**
