### PR TITLE
Black Mesa: Xen

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

The next big Black Mesa update. It will include a whole new area and a refined boss fight!

https://user-images.githubusercontent.com/9026500/160964178-e6facad1-b7d8-4617-9148-51ba3ca1ca1d.mp4

To-do:

- [x] Add vortigaunts
- [ ] Add alien grunts
- [x] Add xen water
- [x] Add xen healing crystal
- [ ] Add portal keepers(mini nihilanths)
- [x] Add vortigaunt houses
- [x] Add lambda teleporter
- [x] Add fast headcrabs
- [x] Fix headcrabs and houndeyes jump manuver 
- [ ] Add gluon gun

## Changelog

:cl:
add: Black Mesa: Xen
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
Sex.

**Comment by GoldenAlpharex** [comment]
Would be nice to have some pictures of what you're adding, it's hard to tell with the Map Diff Bot alone.

**Comment by capsaicinz** [comment]
sounds tight, but this really is a contender for "worst pull request with largest content update of 2020"
i beg you give us something to see or talk about it or something
i beg you

**Comment by Gandalf2k15** [comment]
It's a big collaborative effort from myself and the Russians, it'll be done at some point.

**Comment by Gandalf2k15** [comment]
needs merged for map shit

**Comment by Stalkeros2** [comment]
Time to do a balance run.

**Pull request merged**
