### PR TITLE
Vesper Defense Presents: Slightly More Armed Contractors

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
So, major thing, here: this PR does three major things:
- Adds a drifting contractor-themed Gun to the uplink for 7 TC.
- Adjusts their three starter random equipment pieces to be more befitting a midround threat to be killed with your Cargo guns or whatever
- Replaces their jetpack with an emergency tether

The first major thing is the Gun. It's literally just a Wespe with a silencer.
<details>

- It has an integrated suppressor.
- Instead of a flashlight, it fires light-breaker bolts (see: the SC/FISHER, which I previously worked on) on RMB.
- It comes pre-loaded with .35 Sol Incapacitator ammo.
- It has a Syndicate firing pin.
- The case it comes in has...
    - The ~~Guêpe~~ Horzel itself, pre-loaded with .35 Sol Incapacitator.
    - Two pre-loaded short (12rnd) magazine, also of Incapacitator ammo.
    - Two empty short magazines.
    - A box of .35 Sol lethal.

I'm open to adjusting the contents of this case.
</details>

image

Second major thing is that I've taken the liberty of reshuffling a fair bit of the midround contractor kit's pick-three loot table.
Things I removed include:
<details>

- The mulligan. It's either useless or ban-bait, because of how it's probably poor form to hit someone with it mid-round, even with the SAD.
- The dart pistol. It's kinda useless without additional reagents/syringes, and I'm not going to put the poison kit in there. Chem combat sucks for everyone involved.
- The edagger. It, uh... it sure does exist! Sure, it's 3 more damage than your knife, and has some armor pen, but it's a pen with an energy blade. It's not great, and if you're stabbing people, you've either already won the fight or you're fighting for your life.
- The Syndicate sentience potion. For reasons that are hopefully self-explanatory.
- The radio implant. Because, at best, you're talking to one or two other guys.
- The guerilla/insulated tackler combat gloves. You're mostly going to be in a suit. You're not using those.
- The radioactive microlaser analyzer that sleeps people. Does it work for kidnapping? Probably! Is it particularly fun to work with? Probably not!
</details>

Things I added include:
<details>

- A box of random, limited grenades. It's smokes, mirages, or teargas. Mainly smokes. Sometimes mirages. Rarely teargas.
- Night vision meson health HUDs. Someone suggested it. I said okay.
- Changing the thermal goggles to a thermal visor, because you have a MOD.
- A removable variant of the power kick (very audible windup for funny dropkicks) MODsuit module.
- A doorjack. For doorjack...ing.

</details>

I'm also open to adjusting some of the things added/removed, but it was mainly put together under the thought of "if you're a midround, you're going up against a security team that's probably very armed and very happy to shoot you".

### The Gun:
It's a Wespe with a silencer and a gimmicky lightbreaker. It's not free anymore, but it's there. Go ahead. Do some contracts.

### The Equipment:
I don't think anyone particularly enjoys looking in their inventory and finding a mulligan, health analyzer, and a dart pistol. Some of the additions are probably overtuned, but they're going to be beholden to RNG's grace and their own skill (issue), so them's the breaks.

### The Tether:
Nobody likes playing against space-bound contractors. Incentivizing them to stay on-station by exploding their jetpack and replacing it with something less useful (the emergency tether) means they will have to learn to master the tunnels.

## Proof of Testing
There's a screenshot right there.

## Changelog

:cl:
add: Vesper Defense, a somewhat little-known firearms manufacturer, has secured a contract with the Syndicate to stock their telecrystal-based black markets (colloquially, uplinks), with what is, essentially, a Wespe with an underbarrel ranged light-breaker. Prospective field operatives are advised that the side-press trigger is labeled "RMB" on their new firearms operation diagrams.
balance: After some complaints from formerly-deployed and now mostly dead drifting contractors, the Syndicate has moved to a different section of their warehouse shelves to haphazardly pull equipment from to equip their contractors with.
balance: Citing budget reasons, the suit issued to drifting contractors had its jetpack replaced with an emergency tether launch system.
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
Get them the smoke grenade dispenser module. *nod

**Comment by ghost** [comment]
Mulligan is for self-use, not using on others. It's a disguise to change your face so you can't be identified. The reason for removal isn't relevant to it whatsoever.

Gloves are for people who don't depend entirely on their suit. Contractors already overly depend on it, making it even more required isn't a good idea.
Plus the suit doesn't have tackling. Tackle-gloves are the only way to get that.

On the same note, giving them the infiltrator-exclusive module isn't a good idea either. Mood isn't a fun mechanic to work with already, giving it to an antagonist that already has issues with being unfun and having a pretty overtuned modsuit is just going to make them even more disliked.

Chameleon Projector is always abused by antags like this, same as above: just going to make them more unfun, more likely to just be kill on sight.

Crypto Sequencer can break a lot of equipment that's meant to be far out of contractors' scope, including hijacking the evac shuttle.

**Comment by HoodMilk** [comment]
Gun is cool, breaking lights is an under-rated stealth tactic, can you buy extra ammo for it from your uplink though?

Also worried the gun and some of the new spawn items will make people think "Haha I am Syndicate man I must fight all of security" instead of trying to actually be a stealthy infiltrator. That's more of a playerbase mindset issue though.

**Comment by RatFromTheJungle** [comment]
the last thing they need, if they're still getting random items + the baton + the modsuit, is a gun too jetpack around in space with,  the baton being also-overpowered isn't a very good justification to give them a gun too

**Comment by desertmote** [comment]
The ammo in the gun case is a bit oddly supplied.

- `/obj/item/ammo_box/magazine/c35sol_pistol/incapacitator`
- `/obj/item/ammo_box/magazine/c35sol_pistol/ripper` (I know this doesn't exist yet, so add it using: `/obj/item/ammo_casing/c35sol/ripper` here: `modular_skyrat\modules\modular_weapons\code\company_and_or_faction_based\carwo_defense_systems\magazines.dm`
- `/obj/item/ammo_box/magazine/c35sol_pistol/starts_empty`

That'll be two incapacitator magazines, a ripper mag, and an empty one. These gimmicky bullets deal fuck-all damage, and the ammunition is plenty for the gun's use case. You're not going to be killing anyone with these unless they already had a deathwish.

**Comment by desertmote** [comment]
Here's a demo to back up my claim on how little damage it would do.

https://github.com/Skyrat-SS13/Skyrat-tg/assets/77534246/c88dce0b-27e4-48b3-b451-d313378afee0

**Comment by chemistrymain2** [comment]
> the last thing they need, if they're still getting random items + the baton + the modsuit, is a gun too jetpack around in space with, the baton being also-overpowered isn't a very good justification to give them a gun too

It's only a wespe, same as the crew can get, and it's not a very strong one at all.

Removing the jetpack would probably be a good idea, though. Nobody likes jetpack space contractors.

Likewise, @Hatterhat , might be more reasonable to remove the emag but keep the doorjack.

**Comment by Hatterhat** [comment]
> > the last thing they need, if they're still getting random items + the baton + the modsuit, is a gun too jetpack around in space with, the baton being also-overpowered isn't a very good justification to give them a gun too
> 
> It's only a wespe, same as the crew can get, and it's not a very strong one at all.
> 
> Removing the jetpack would probably be a good idea, though. Nobody likes jetpack space contractors.
> 
> Likewise, @Hatterhat , might be more reasonable to remove the emag but keep the doorjack.

the jetpack has been exploded and replaced with a tether
toying with the idea of making the armor booster more consistent with how it is on the standard syndicate suits (suit has base slowdown, booster strips the slowdown)

**Comment by RatFromTheJungle** [comment]
> The ammo in the gun case is a bit oddly supplied.
> 
>     * `/obj/item/ammo_box/magazine/c35sol_pistol/incapacitator`
> 
>     * `/obj/item/ammo_box/magazine/c35sol_pistol/ripper` (I know this doesn't exist yet, so add it using: `/obj/item/ammo_casing/c35sol/ripper` here: `modular_skyrat\modules\modular_weapons\code\company_and_or_faction_based\carwo_defense_systems\magazines.dm`
> 
>     * `/obj/item/ammo_box/magazine/c35sol_pistol/starts_empty`
> 
> 
> That'll be two incapacitator magazines, a ripper mag, and an empty one. These gimmicky bullets deal fuck-all damage, and the ammunition is plenty for the gun's use case. You're not going to be killing anyone with these unless they already had a deathwish.

killing doesn't matter, stamcrit is functionally dead as anyone can just walk up and kick you to death, or strip your modsuit and fling you into deepspace, contractor doesn't need a pistol, and especially not one for free, off the bat, and especially-especially not a syndie-pin locked one

**Comment by Hatterhat** [comment]
> > The ammo in the gun case is a bit oddly supplied.
> > ```
> > * `/obj/item/ammo_box/magazine/c35sol_pistol/incapacitator`
> > 
> > * `/obj/item/ammo_box/magazine/c35sol_pistol/ripper` (I know this doesn't exist yet, so add it using: `/obj/item/ammo_casing/c35sol/ripper` here: `modular_skyrat\modules\modular_weapons\code\company_and_or_faction_based\carwo_defense_systems\magazines.dm`
> > 
> > * `/obj/item/ammo_box/magazine/c35sol_pistol/starts_empty`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That'll be two incapacitator magazines, a ripper mag, and an empty one. These gimmicky bullets deal fuck-all damage, and the ammunition is plenty for the gun's use case. You're not going to be killing anyone with these unless they already had a deathwish.
> 
> killing doesn't matter, stamcrit is functionally dead as anyone can just walk up and kick you to death, or strip your modsuit and fling you into deepspace, contractor doesn't need a pistol, and especially not one for free, off the bat, and especially-especially not a syndie-pin locked one

just outdps them with a Real Gun lmao

**Comment by RatFromTheJungle** [comment]
or just don't'nt give them a gun at all, and prevent the issue before it pops up, one of these is alot simpler

this is just avoiding making comment on the random-gear-box, because like, none of that is anything they should have, especially an AOE mood debuff, it'd just be a speedrun to contractor getting disabled

**Comment by chemistrymain2** [comment]
> > The ammo in the gun case is a bit oddly supplied.
> > ```
> > * `/obj/item/ammo_box/magazine/c35sol_pistol/incapacitator`
> > 
> > * `/obj/item/ammo_box/magazine/c35sol_pistol/ripper` (I know this doesn't exist yet, so add it using: `/obj/item/ammo_casing/c35sol/ripper` here: `modular_skyrat\modules\modular_weapons\code\company_and_or_faction_based\carwo_defense_systems\magazines.dm`
> > 
> > * `/obj/item/ammo_box/magazine/c35sol_pistol/starts_empty`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That'll be two incapacitator magazines, a ripper mag, and an empty one. These gimmicky bullets deal fuck-all damage, and the ammunition is plenty for the gun's use case. You're not going to be killing anyone with these unless they already had a deathwish.
> 
> killing doesn't matter, stamcrit is functionally dead as anyone can just walk up and kick you to death, or strip your modsuit and fling you into deepspace, contractor doesn't need a pistol, and especially not one for free, off the bat, and especially-especially not a syndie-pin locked one

syndicate pin does need to go, so that they can be disarmed and have it used against them, but this also gets rid of their jetpack and replaces it with a tether

this is a very severe nerf that completely eliminates their ability to fly around in space and sax for 2 hours, meaning that they're forced to stay on station

i think you're overreacting here on the 'they have a gun now' thing, especially since they can already spawn _with_ a staminacrit gun (the riot foam c20r)

what we've got is a doorjack that lets them get into and go around the station (fits their role) thermals or nightvision mod upgrade for scouting out their target (fits their role) and a gun that primarily serves to subdue targets at long range while being comically ineffective against armored security officers who can outdps them with the sol smg they get in the armory at roundstart, as well as the cargo weapons such as the trappiste they usually order immediately

they cannot jetpack around in space anymore, too, which is their **biggest strength** negated-they no longer have toe to toe space dominance with security, who will have jetpacks, and instead are mostly forced to stay on the station once they enter it rather than flying around

this is more nerf than it is buff, but makes them more aggressive if they plan on balling around with the modsuit instead of disguising themselves

so what's the hangup here

**Comment by RatFromTheJungle** [comment]
> so what's the hangup here

that most of what you described is just, flatly wrong

with their armor, and the gun (non lethals), they can stamcrit an officer in a crisp 5 legshots

getting a jetpack takes 1 plasma sheet, and a maints exofab, (which spawns with iron+glass near it)

and everything else added, is stuff they flatly just shouldn't have off the bat, the night vision mod maybe, but thermals, an AOE mood-debuff, and shit like frag-grenades (even if on chance), (and all this, with the gun ontop of that) is just an absolute no go, contractor is not meant to be aggressive, they are meant to be stealthy first and foremost, not traitor*2, wanting them to ball-out every round is your personal want, and not at all what they're meant to be.

**Comment by radarseas** [comment]
There's a few important things to consider about drifting contractors currently, they do work quite nicely at what they're supposed to achieve by their current kit and design, a slightly stealthy hit and run antagonist that's more aggressive than their crew varient (OPFORs).


you can spawn rather late into the round with the clock ticking to do stuff where security is probably already stacked with equal or superior odds (teleshields that 50% block your baton and shots, implant locked guns (mindshields show on sechuds), modsuits that have your exact same ion thrusters, let alone armed crew with guns, combat stims, etc and the AI being able to bolt you down in a moment's notice... (you're not really going last long if this was over you trying to escape being shot)


You can get gear from crew but often you're set back by a limit of 1-2 hours or less to act plus you're not on records so every second of being unnoticed **matters** (especally if drifting contractor rolls multiple people) the clock is ticking and you're generally required to play aggressively once sec tracks you. (especally if they take olfraction, I need not explain why.)

Shift+click, no data log entry, **that's suspicious**, you're instantly getting noticed and pointed out, all forbid if there's several secoffs nearby and its gonna be hard to hide your equipment, let alone before you get changed out of your extremely conspicious insulated turtleneck and bowman. Also you don't have a NIF implant or any way to simulate having one via flavor, **_that can be a giveaway trying to impersonate people and killed lings as a stealth antag._**


Ions are **nessessary, you spawn late and need to put up a fight almost immedately sometimes.** unlike tethers you don't lose people you're dragging and it lets you actually have fights in open space instead of being forced to run and be shot at or fight the entire security team on the solars, fighting in open space was never a good idea though since you have less armor and have to get really close which is dangerous for a lot of reasons.

Unless sechuds get a rework or non-crew entry stowaways get normalised, they're not going to be able to be stealthy because on examine, everyone knows what's up and its entirely at the mercy of whatever secoff noticed them to be cool about it and let them carry on. _which is fine, GOOD RP IS **GOOD**_... but urm, why would you _not search_ someone or expect most of the security team let it side when they're someone who ain't crew during existing contractors with a very crew-like ID. **how DO you hide your illegal stuff when the sprite bugs and goes invisible while disguised so you can't actually clickdrag on your """bag""" half of the time anyway to "hand it over" for a check if you do stash your gear away.**

Remember, no chamelion mask, OR sign quirk to disguise your real name, copying someone from manifest as a doppleganger is going to be very, very suspicious once you start talking. That's fine, we have the...

oh wait, nevermind no TC on spawn, forget the cham kit... oh and you don't spawn with a mask either.


> with their armor, and the gun (non lethals), they can stamcrit an officer in a crisp 5 legshots

Stamcriting in 5 shots **MIGHT sound good**, but your pistol ammo is going to be pretty limited and most of it'll be blocked by a 50% chance on the teleshield anyway which most smart sec use vs contractors plus officer parrings. That's also assuming every single shot connects to the legs, you're better off using it sparingly. Besides, pirates already get M1911s and like 3 spare mags, _they get their asses kicked regularly even with that_.

anything that brings more interesting strats than cornerhug and baton like welder trickshots is nice.

Your armor is decent but its mostly your meds that make you seem invincible and hugging behind a wall to avoid being hit so you can batonshove to not get magdumped cause, solguns HURT if you slip up into a burst. Damage slowdown is what often gets me as a contractor and its why I often bail out of fights into space. Stamcrit needs you to actively keep people down and most contractors are pretty nonlethal and don't use their knife anyway. I will say one thing though, I'd be fine with a normal turtleneck instead of insulated, you really don't need that much extra armoring, if you're toting a gun.



If anything, the real balance issues are current ones; 
You get an awful lot of cash by doing contracts, bribery is GREAT... in theory, you're usually spawning past that window and you're better off buying gear with it (which means a gun anyway, anyone remember that time a contractor bought the old NRI rifle and wiped half of the sec team with it?) not to say them getting money is bad but... considering how buffed crew gear is and the fact it requires money...? you're better off using your uplink for escape, doorjacks, stimpacks and gear for reinforcements.

Until olfraction is gone (it was never healthy for 2+ hour rounds anyway, especally for antagonists that act early), they can't be stealthy unless security doesn't nab this (which they probably will if the contractor is hiding amongst the crew), you literally just need something they touched. The alternate is you uhh, you don't because you don't get enough TC for a soap that cleans fast enough to feasably outrun sec and not leave any trace... so yeah.


One single flukeup of another contractor you cannot do anything about which makes all non-crew immedately search worthy... That leads to urm, stealth not being a completely viable strat no more especally when you sacrifice a lot of armor to have that modsuit off.

Crew gets an **_immensively redicious power ceiling unlike you_**, from combat stimulants from cargo plus the ability to ignore having science need make you antigrav modules by just straight up buying them (which some caps have abused to powertrip in their superfast modsuit and wack antags at lightning speed), medical that's been buffed to the point you get revived in seconds flat if they know what they're doing plus mediguns that remove oxyloss faster and better than convermol and work on stasis, an AI that can just bolt you in and scream over loudmode non-stop making you unable to contract to begin with, reilable lack of other antagonists to distract them being excessively searchy, implant locked firearms that you cannot use without mindshielding yourself and showing up on huds, preventing disguising as general crew (we also lack revs for plasuable denability so mindshields **really** stand out)... yeah, that's just the tip of the crew's potental power without touching xenobio, buffs to crew cyborgs that lets them disguise as any other kind of borg, extra health for everyone before critting, combat implants like _**Thermals, or anti-drop**_ as well as surgeries like nerve splicing that are borderline undetectable.

Your baton holster is the least creative means of dealing with the problem of losing the baton... _why not make it like the ninja's recall instead with a long cooldown_, enough to recover their baton if they lose it immedately _but not enough they can spam recall it in a fight_ and can be wacked with it if they're not careful. (and if crew using it is a problem, could antag lock it like heretics or clockie... perhaps?)

**Review by Gandalf2k15 — CHANGES_REQUESTED** [review]
our contractors are gone, you can add these to the newly made TG ones!

**Pull request closed without merging**
