### PR TITLE
[SEMI-MODULAR] Ports the old food like/dislike system

### PR DESCRIPTION
**Pull request by NotRanged**
## About The Pull Request

Ports the old food like/dislike system. Tested locally and it works. Original code by Bob Joga.

## Why It's Good For The Game

More character customization, like letting anthros choose to eat and enjoy mice again.

## Changelog
:cl:
add: Added old skyrat's food like/dislike system to preferences.
/:cl:

### CODE REVIEW

**Comment by Draganfrukts** [comment]
>tfw maintainers refuse to merge this just because /SOMEONE/ coded it

**Comment by NotRanged** [comment]
10 days wooo

**Comment by NotRanged** [comment]
> > tfw maintainers refuse to merge this just because /SOMEONE/ coded it

I even changed a decent bit of it because old stuff didn't work lol

**Review by Gandalf2k15 — APPROVED** [review]
I cant see anything wrong with the code. I'll suggest a 1 week test merge. Effective when I can do it.

**Comment by hugmeorelse** [comment]
Please credit the original coder, even if it is from oldbase Skyrat, @NotRanged

**Pull request merged**
