### PR TITLE
Revert "Deep Space 2 Changes"

### PR DESCRIPTION
**Pull request by unit0016**
Reverts Skyrat-SS13/Skyrat-tg#6745

See #6773 on why this was a bad idea. Not to mention It's been suggested to trim it the fuck down.

### CODE REVIEW

**Comment by lyricalpaws** [comment]
Does this remove the vendors that were added to each department, the syringe gun in maints, sutters/controls for the hangar, and the recycler? If so those would need to be added back. (Including the chapvend but with the beacon removed)

**Comment by lyricalpaws** [comment]
Specifically the outfit vendors, since without them you literally can't get most departmental outfits. Similar issue with nanomed/chem, I'd rather not have to tide interdyne to be able to do my job on ds2.

The medidrobe in particular is the only way to get nitriles, the boxes of various things are extremely useful, and the bonus items in the chem and med closets are just helpful honestly. 

I can see why you want to remove things like the moff lantern, those are entirely fair.

**Comment by unit0016** [comment]
> Specifically the outfit vendors, since without them you literally can't get most departmental outfits. Similar issue with nanomed/chem, I'd rather not have to tide interdyne to be able to do my job on ds2.
> 
> The medidrobe in particular is the only way to get nitriles, the boxes of various things are extremely useful, and the bonus items in the chem and med closets are just helpful honestly.
> 
> I can see why you want to remove things like the moff lantern, those are entirely fair.

The nanomed and drug vendor were already there before this PR. The only other 'additional item' besides the wardrobes was the autosurgeon, which is.
No.

I will readd the nitrile boxes and epipens along with the hangar doors and disposals, but I'm going to make special care that it isn't linked to the station's like they /currently/ are.

**Comment by lyricalpaws** [comment]
the nitriles came from the medidrobe, the box was latex (inferior)

**Comment by hugmeorelse** [comment]
I recommend going with @unit0016's advice as they're the ones maintaining DS2 changes. @Varoxus of #6745 should talk to @unit0016.

**Comment by lyricalpaws** [comment]
The main issue I have with losing the medidrobe is no labcoat or nitriles

**Comment by hugmeorelse** [comment]
Please update from the Master branch. The integration test is failing during CI.

**Pull request merged**
