### PR TITLE
[Modular] Fixes OPFOR

### PR DESCRIPTION
**Pull request by SomeRandomOwl**
## About The Pull Request

This PR simply put fixes the opforce panel to work with the new react TGUI (Also i guess a prettier pass as prettier did some formatting on it)

## How This Contributes To The Skyrat Roleplay Experience

Less bugs, more antags

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
9thrd8Sy4o

</details>

## Changelog

:cl:
fix: OPFOR Panel no longer bluescreens, now you can submit your next iteration of murder, kill and theft
/:cl:

### CODE REVIEW

**Comment by KiriKaz** [comment]
#25692 just got merged, is this just a Prettier pass?

**Comment by SomeRandomOwl** [comment]
> #25692 just got merged, is this just a Prettier pass?

wait what, wow im only 7 minutes late on fixing this

**Comment by KiriKaz** [comment]
> > #25692 just got merged, is this just a Prettier pass?
> 
> wait what, wow im only 7 minutes late on fixing this

if only I had ahelped like 20 minutes earlier huh

**Comment by SomeRandomOwl** [comment]
> > > #25692 just got merged, is this just a Prettier pass?
> > 
> > 
> > wait what, wow im only 7 minutes late on fixing this
> 
> if only I had ahelped like 20 minutes earlier huh

literally as soon as i saw that ahelp i went oh, huh. And opened vs code

**Comment by KiriKaz** [comment]
> > > > #25692 just got merged, is this just a Prettier pass?
> > > 
> > > 
> > > wait what, wow im only 7 minutes late on fixing this
> > 
> > 
> > if only I had ahelped like 20 minutes earlier huh
> 
> literally as soon as i saw that ahelp i went oh, huh. And opened vs code

it sucks because i also knew it was a one-line fix but I just never opened vs code x_x

**Comment by Thlumyn** [comment]
> > > > #25692 just got merged, is this just a Prettier pass?
> > > 
> > > 
> > > wait what, wow im only 7 minutes late on fixing this
> > 
> > 
> > if only I had ahelped like 20 minutes earlier huh
> 
> literally as soon as i saw that ahelp i went oh, huh. And opened vs code

I think I saw that same ahelp which reminded me to send in the PR lol

**Comment by SomeRandomOwl** [comment]
Anyway, prettier somehow fucked up here and you where faster on the draw so ill close my own pr here

**Pull request closed without merging**
