### PR TITLE
[SEMI-MODULAR] [SHITCODE-IN-FIXING] Backgrounds V2!

### PR DESCRIPTION
**Pull request by RimiNosha**
<details>
<summary><i>Oh fuck. Sorry Golden.</i></summary>
<image src=https://user-images.githubusercontent.com/106692773/208539157-e2500d0f-692d-4dc2-9595-3d687cbf1c1a.png>
</details>

**READ THE DOC:** https://docs.google.com/document/d/1RQtNRcjTBzB10koqfdnAzl9OmV-3ndLUhty9FDIdvnQ/edit?usp=sharing

## Preamble
[Haha, It's not dead!](https://i.kym-cdn.com/photos/images/newsfeed/001/637/573/487.jpg)

Anyways, your favorite synth-breaking, prefs mutilating feline here, adding another thing to prefscode that'll break everyone's saves!

This stupid undertaking was done by yours truly, with help from numerous folk in the lore team. I'm not sure what drove me to make this code, and honestly- I don't even remember when I started it. I think it was before guncargo- actually, nope, before dep guards- oh, and before our... 20th<sup>(?)</sup> sec resprite!

So, big, massive warning to maintainers and potential code reviewers, this is unfinished. That means it contains unsorted, and possibly even non-functional code. Hence why this is a draft. Feel free to point out any blunders that I don't seem to have noticed, though.

### My first and final note to the playerbase for now. Keep discussion about the contents of this PR to discord. Please and thanks.
image
Direct feedback to this channel if you're not gonna ping.
Github is terrible as a forum, don't treat it as such, please. Feel free to ping me, by the by, I wanna hear what you have to say.

## About The Pull Request
Backgrounds V2. Or V3, to me. This has undergone a rewrite since I first started. Opening this draft to gain awareness, and to get folk who do lore to remember that I need their lore drops.

So, there's a crapton of folk who ask about "What's our current lore on X?", or "Do we even have lore?!". The answer to one is yes, sometimes, the other is very much yes.

Here is some of it in code form, and this time, it's not just a language restriction or pay increase!
<sub>Well, it does little but decide your passport, available roles, and paycheck amount right now, but if I were to add everything at once, we'd have a 3000 line diff- wait- fuck. 8000 line diff, then.</sub>

Featurelist includes:
- Employments of dubious legality!
- Social backgrounds! Who do you know and like or dislike?
- Origins! Where did you come from?
- Passports!
  - These are gonna be expanded on in later PRs.
- ID cards are no longer IDs, they are now just access cards for both doors and bank accounts!
- Squatters as a consistent role! Spawn in maints and try to survive sec's looming presence! Or ERP them, knowing you guys.
- A special employment type where your paycheck is instead semi-discreetly sent to the HoP to ~~steal~~ hand out to you!
- Some social backgrounds and employments can (and eventually all will) have special features tied to them!
  - Current special features are "penniless", "paid by hand", and "off-manifest"!

## How This Contributes To The Skyrat Roleplay Experience

Our old shit but not so shit and not completely incorrect about our lore!

I'll write something more when I'm not so tired.

## Proof of Testing

Oh my god, this'll be a long one. Won't test until I've got every feature sorted code-wise. Enjoy an image dump that I've sent in the past instead.

image
image
image
image
image
image
image

## Changelog

This one will take a while. Will fill out when not so tired.

:cl:
/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
As discussed on discord, please PR in parts to `backgrounds-v2-project`

**Comment by Stalkeros2** [comment]
YEEEEEEEES

**Comment by Iamgoofball** [comment]
CC me when these are merged so I can update Stories with them

**Comment by RimiNosha** [comment]
Closed cause of the project branch. Send hate to zone, and I'll nuke your house.

**Pull request closed without merging**
