### PR TITLE
Actually fixes common language. [Ready]

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request

Title. I'm  an idiot.

## How This Contributes To The Skyrat Roleplay Experience

Title. As before.

## Changelog

:cl:
fix: The Icon is FINALLY gone.
/:cl:

### CODE REVIEW

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
That's not the fix.

**Comment by theselfish** [comment]
> That's not the fix.

Hence why I intend to test it. If this doesn't work. I'm just going to delete our override of common.

**Comment by GoldenAlpharex** [comment]
I've got the fix, I'm about to PR it.

**Comment by theselfish** [comment]
I figured it out.

**Pull request closed without merging**
