### PR TITLE
Anti-EORG teleport

### PR DESCRIPTION
**Pull request by Kush1Push1**
## About The Pull Request

Adds option for OOC preferences, which in toggled state teleports players after emergency shuttle's docking to Central Command in safe location (ghost cafe).

### How it works
Firstly, after the shuttle's docking, there starts post round handle, which separates to EORG handle and EORG bans (forced pacification) handle.

#### EORG handle
After the emergency shuttle's undocking from the station, players will receive a notification about their current state of the preference. If they wish, next to the message will be a button to switch it until the end of round.
During process, handcuffs on mobs will be deleted - for teleported and and left one.
It doesn't teleport antagonists. So, if a traitor with an esword and a grenade is in the shuttle, they still can go wild for the last two minutes.
If a player turned on the preference (by default, the option is turned off), they will be teleported at a random spot in safe zone (ghost cafe).

Every teleported mob will be pacified to ensure no one will get hurt (basicly to defend players from themself and make job easier for admins).

#### EORG bans handle
Copy-pasted from respected modular file.
EORG ban process is after teleportation process, so banned one still will get in "hell".

#### Also
Changed a bit how description for darkened screen during flashes (and so for EORG teleport's description) looks.
Added a config to disable post-round EORG teleportation. It also can be changed with a button in Server's tab.

## How This Contributes To The Skyrat Roleplay Experience

EORG fans will not harm post-round RP enjoyers.

## Code

Feel like I break at least some of local guidelines with my changes, from making it modular to don't touch other contributors stuff. Would like to have feedback if I did something wrong .-.'
~~In draft state for now.~~
~~I also don't know at which point I managed to change deleted sprites.~~ (fixed)

## Changelog

:cl: SishTis
add: Added anti-EORG teleportation option in character setup's OOC preferences. If toggled on, teleports the player to a safe zone (ghost cafe) after round end. Admins also have a button in Server's tab to disable it for some events.
/:cl:

### CODE REVIEW

**Comment by Kush1Push1** [comment]
Pain

<details>

image


</details>

**Comment by Kush1Push1** [comment]
Yay
"Sprites" tag should be removed, I guess

**Comment by Kush1Push1** [comment]
Added to topic:
$ During process, handcuffs on mobs will be deleted - for teleported and and left one.
$ It doesn't teleport antagonists. So, if a traitor with an esword and a grenade is in the shuttle, they still can go wild for the last two minutes.
$ EORG ban process is after teleportation process, so banned one still will get in "hell".
$ Changed a bit how description for darkened screen during flashes (and so for EORG teleport's description) looks.
$ A config to disable post-round EORG teleportation. It also can be changed with a button in Server's tab. (SOON)

**Comment by GoldenAlpharex** [comment]
I just need to ask, does it do it for everyone on the server, or only those on the shuttle at round end?

**Comment by Kush1Push1** [comment]
> I just need to ask, does it do it for everyone on the server, or only those on the shuttle at round end?

It teleports _every_ mob with a player on the server right now.
So, not only the shuttle. I see a possibility of some unexpected teleport of some involved in local parties players pretty fun :D 
It worked in such way since old build and I had much from such situations

**Comment by GoldenAlpharex** [comment]
> > I just need to ask, does it do it for everyone on the server, or only those on the shuttle at round end?
> 
> It teleports _every_ mob with a player on the server right now.
> So, not only the shuttle. I see a possibility of some unexpected teleport of some involved in local parties players pretty fun :D
> It worked in such way since old build and I had much from such situations

Hmm. What I would likely do is split it into a three-state pref, or two different prefs. Regardless, this is going to need reworked when the pref menu PR is done, so stay tuned for that. Feel free to hit me up on the Discord if you need any help with that in the future.

**Comment by Kush1Push1** [comment]
> > > I just need to ask, does it do it for everyone on the server, or only those on the shuttle at round end?
> > 
> > 
> > It teleports _every_ mob with a player on the server right now.
> > So, not only the shuttle. I see a possibility of some unexpected teleport of some involved in local parties players pretty fun :D
> > It worked in such way since old build and I had much from such situations
> 
> Hmm. What I would likely do is split it into a three-state pref, or two different prefs. Regardless, this is going to need reworked when the pref menu PR is done, so stay tuned for that. Feel free to hit me up on the Discord if you need any help with that in the future.

I made a change. After the emergency shuttle's undocking, there will be a notification in chat about current state of their EORG preferences. If they wish, they can push a button next to the message to switch it (changes shouldn't save for the next round).

**Comment by Kush1Push1** [comment]
dreamseeker_dNlOtEMe8H

**Comment by ForrestWick** [comment]
> dreamseeker_dNlOtEMe8H

Hey so how does the teleportation work? Is it area based or a spawner? Cause theres plans right now to kinda wipe out the ghost cafe and interlink and shove them into the normal CC z level as one singular entity so we can reduce performance hits

**Comment by tf-4** [comment]
This isn't how this should be done, and the future of EORG is still in discussion amongst staff

**Comment by CandleJaxx** [comment]
despite the dnm, i'll suggest that if you wanna update this to be, like, it teleports people who WANT to eorg to the ghost cafe, and let centcom enjoyers vibe there

**Comment by faaaay** [comment]
> 
> 
> despite the dnm, i'll suggest that if you wanna update this to be, like, it teleports people who WANT to eorg to the ghost cafe, and let centcom enjoyers vibe there

Won't that cause issues between people vibing in the cafe and people there for EORG?

**Comment by Kush1Push1** [comment]
I follow the idea that in the last two minutes of a round there is no real possibilities for entertaining roleplay activities. In most of cases, where I was in such situations, people just walk around, sit at chairs in literally arena-like CC lobby and starts LRP talks. _I prefer_ to go away from EORG, but I don't like the idea of 2 last minutes of enforced roleplay without any fun content for roleplay.

Personally, I prefer current version, because, for me, there still will be no mandatory roleplay after round end (literally teleportation in other location) and overall atmosphere without grief-like actions of murderbone in the shuttle. Just relax after round with other peaceful players with free from possibility of your _precious character_ to die.

And of course, a scientist with 20 slime cores in backpack, an engineer with freon canister, security after red alert in full gear, roboticists in combat mechs, chemists with pack of grenades, gardener with blood tomato seeds will have their time with taken in last minutes tools for fun in shuttle. I don't like the concept of transfering players to other locations for EORG, since for such gameplay there is CTF arena.

**Comment by Kush1Push1** [comment]
> Hey so how does the teleportation work? Is it area based or a spawner? Cause theres plans right now to kinda wipe out the ghost cafe and interlink and shove them into the normal CC z level as one singular entity so we can reduce performance hits

It teleports players with turned on pref to marked in map file's turfs (which had landmarkers of safe zone at roundstart)

**Comment by Kush1Push1** [comment]
> I follow the idea that in the last two minutes of a round there is no real possibilities for entertaining roleplay activities. In most of cases, where I was in such situations, people just walk around, sit at chairs in literally arena-like CC lobby and starts LRP talks. _I prefer_ to go away from EORG, but I don't like the idea of 2 last minutes of enforced roleplay without any fun content for roleplay.
> 
> Personally, I prefer current version, because, for me, there still will be no mandatory roleplay after round end (literally teleportation in other location) and overall atmosphere without grief-like actions of murderbone in the shuttle. Just relax after round with other peaceful players with free from possibility of your _precious character_ to die.
> 
> And of course, a scientist with 20 slime cores in backpack, an engineer with freon canister, security after red alert in full gear, roboticists in combat mechs, chemists with pack of grenades, gardener with blood tomato seeds will have their time with taken in last minutes tools for fun in shuttle. I don't like the concept of transfering players to other locations for EORG, since for such gameplay there is CTF arena.

I can agree with variant of teleporting EORG players in empty area, like ghost cafe with their current gear, fully healed (?), in mech if they are piloting, pulled non-mobs (like canisters or some items) and maybe some same weapon for everyone on ground near teleporting points :?

**Pull request closed without merging**
