### PR TITLE
[FUCK] [SHIT] SHARK TAIL EMERGENCY FIX

### PR DESCRIPTION
**Pull request by Draganfrukts**
## About The Pull Request

WHAUUUUUUUGH

## Why It's Good For The Game

BABY PLEASE.
unknown

## Changelog
:cl:
fix: sharks are no longer double bladed
/:cl:

### CODE REVIEW

**Comment by Draganfrukts** [comment]
SPEEDMERGE CANDIDATE

**Comment by Gandalf2k15** [comment]
dumbass

**Comment by Draganfrukts** [comment]
SHUT UP GITHUB

**Comment by Draganfrukts** [comment]
> 
> 
> dumbass

unironically coder

**Comment by KasparoVy** [comment]
Man I knew I reviewed for a reason, this is why I asked for pictures aaaaaaaaaaaaaa

**Pull request merged**
