### PR TITLE
[MIRROR] Splits antag huds into their own .dmi file and de-hardcodes antag huds [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/62767
--------------------
## About The Pull Request

I suggested de-hardcoding the antag hud dmi in the PR that reworked them but it didn't happen, so I'm doing my own PR for it
I was also suggested to make antag huds use their own .dmi file since there's a ton of them now, so why not I suppose.

## Why It's Good For The Game

It's helpful mostly for us downstreams who has to deal with editing .dmi file pathings for our own antagonists, and it's less confusing to add a new antag hud now that it's not mixed in with every other hud in the game.

## Changelog

Not player facing.

### CODE REVIEW

**Comment by ghost** [comment]
I'll be working on this personally, so we keep our modular huds

**Comment by ghost** [comment]
I--
We dont need to change anything, upstream didnt **change** their damn HUD system, they split them pointlessly whyyyy

**Comment by ghost** [comment]
> 
> 
> I-- We dont need to change anything, upstream didnt **change** their damn HUD system, they split them pointlessly whyyyy

anyways yea if we just keep our half of the conflict, fundamentally nothing will change; the PR affects Team Antag huds and the like, but the conflict is just their new version of the same masterfile

**Review by GoldenAlpharex — APPROVED** [review]
Hopefully this doesn't bit us in the ass later, shouldn't, but oh well, I'll help someone if they need help with this, it should actually be better in the long run.

**Pull request merged**
