### PR TITLE
[Ready][kinda][Semi-Modular] Brig Officers, Prison guards that have one job, guard the prison

### PR DESCRIPTION
**Pull request by thestubborn**
image
bet you didnt think i would, huh?

- [x] do the base shit (uniform and structure) 
- [x] id trim
- [x] hud
- [x] map stuff (big boy one) (cera offered)
- [x] get eggs

- [ ] Randy Pitchford this, starting it then give it to someone else

## About The Pull Request

There's a place just outside of Lisburn
It's a place that's known to few
Where a group of Irish rebels
Are held by Faulkner's crew

They're forced to live in cages
Like the inmates of Bellevue
But the spirit of 1916
Will always see them through

## Why It's Good For The Game

"It would legitimately be better to have a brig officer role of some kind to help lighten the load on the warden in terms of Prisoners. People who play Prisoner to RP rely on other prisoners and the warden to make their round not boring. Having a role that ostensibly should be interacting with prisoners instead of being forced to by circumstance would help resolve the policy issue."
-DerFlammenwerfer#8421

"I think it would probably help if we had specific prison staff slots, It could be an entirely different slot like CDO.
If it's different gear, it may as well be a different job slot."
-Xye

image

image
image

## Changelog
:cl: B. S. Armour
add: Prisoner complaints were found at the bottom of a bin, requesting the Warden focus on them instead of doing his job, we have heard your complaints and will be sending a guard, just for you, you fussy dorks.
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
> 
> 
> You currently have a negative Fix/Feature pull request delta of -37. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

hate

**Comment by thestubborn** [comment]
WAIT SHIT WHAT

WHAT W

**Comment by hugmeorelse** [comment]
If you have sprites, please showcase them!

**Comment by thestubborn** [comment]
> 
> 
> If you have sprites, please showcase them!

updated to show em

**Comment by thestubborn** [comment]
right this is basically done, i just need to get the map stuff done

**Comment by thestubborn** [comment]
and map stuff is.....done

**Comment by Gandalf2k15** [comment]
nice

**Comment by Gandalf2k15** [comment]
fix conflix

**Comment by Gandalf2k15** [comment]
I'm just gonna send it

**Pull request merged**
