### PR TITLE
lets hemophages drink velvet kiss

### PR DESCRIPTION
**Pull request by plsleavemealon**
## About The Pull Request
This lets hemophages drink velvet kiss and allows it to restore blood levels at the same strength as Bloody Mary (weaker than bloodshot.)

## How This Contributes To The Skyrat Roleplay Experience
The drink is made with blood, is designed for vampires and the undead, and it gives hemophages an alternative to bloody mary and bloodshot for drinks to enjoy.
## Proof of Testing
Works flawlessly on my private server.

## Changelog

:cl:
fix: Hemophages can now drink Velvet Kiss without vomiting
balance: Velvet Kiss is now a race drink for Hemophages (in addition to the other races that were already present!)
balance: Velvet Kiss now restores blood at the same rate that Bloody Mary does
/:cl:

### CODE REVIEW

**Comment by plsleavemealon** [comment]
If you'd like, I can also go through and add the "chemical_flags_skyrat = REAGENT_BLOOD_REGENERATING" to all drinks made with blood (and drinks that use component drinks made with blood) to them

Edit: Which as far as I can tell, is just a flag that lets hemophages drink things without spewing, and doesn't actually restore blood levels on its own.

**Review by SpaceLoveSs13 — APPROVED** [review]
Looks good. And I think we are good. As for the flag, if you want to, that would be great!

**Comment by plsleavemealon** [comment]
Then sure, I'll work on another pull request with that then!

**Comment by plsleavemealon** [comment]
Alright, the other PR is done too :3
Can be found here:
https://github.com/Skyrat-SS13/Skyrat-tg/pull/28898

**Pull request merged**
