### PR TITLE
Void Raptor - Mapping fixes

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

A wall seems to have appeared in the doorway of Viro and finding the disposals recycle chute wasnt connected to anything. The vast majority of stray pipes were under tables/doors which made seeing them visually not easy, but thankfully someone showed me how to actually view filter and mind blown. Decided to expand to fine-tooth comb the whole map for disposal issues and found a lot of strays that were corrected.

<details>
<summary>Issues found</summary>

Wall in Viro
image

Disposals Recycler
image

Stray chute in cargo
image

Extra router in cargo
image

Stray pipe in departures
image

Stray pipe in Departures maintenance doorway
image

Two stray pipes in Security
image

Stray pipe in Arrivals Checkpoint
image

</details>

## How This Contributes To The Skyrat Roleplay Experience

Fewer weird mapping bugs the better, should also allow content recycling to route back to cargo properly as well as cargo mail sent from other departments to now go into their chute box rather than disposals.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
Recycle route: 1 wide maints forced me to do a wall pierce route

image

image

Viro wall: gone
image

Cargo stray: gone
image

Mail router in cargo
image

Stray departures pipe: gone
image

Stray pipe in Departure Maintenance under the door: gone 
image

Stray pipes in Security: gone
image

Stray Pipe in Arrivals Checkoint: gone
image

</details>

## Changelog

:cl:
fix: Void Raptor - Virology lost the wall inside the doorway, sorry no more extra privacy
fix: Void Raptor - Multiple stray disposals pipes in Cargo/Departures/Arrivals/Security are now gone
fix: Void Raptor - Missing cargo mailer is now no longer missing
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
change the doors under the altar in the chaplain sat to common access, it's supposed to be a common area with the garden/dorms

**Review by Paxilmaniac — DISMISSED** [review]
SDMM screenshots aren't proof that you tested it.

**Comment by Zergspower** [comment]
> SDMM screenshots aren't proof that you tested it.

i mean, do i need to go pull up all the tiles where the pipes were?

**Comment by Zergspower** [comment]
updated - cant really do anything about the mapping helper in game

**Comment by Zergspower** [comment]
image
changing that mapping helper here after i noticed the error - and removed the router since it's already routing to the chute and replace it with a junction.

**Comment by Zergspower** [comment]
> change the doors under the altar in the chaplain sat to common access, it's supposed to be a common area with the garden/dorms

i'll do a second PR for the Chapel as i already wanted to bring disposals there, but every door in there is the same access level of Chapel_office it seems

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
The fifth screenshot is an editor screenshot, not a playtested screenshot.

**Comment by Zergspower** [comment]
> The fifth screenshot is an editor screenshot, not a playtested screenshot.

that was due to removing the mailing router helper which doesnt show

**Comment by Zergspower** [comment]
image

**Review by Jolly-66 — APPROVED** [review]

**Pull request merged**
