### PR TITLE
[PR PR] Fixes up the TGUI Latejoin Menu!

### PR DESCRIPTION
**Pull request by RimiNosha**
Restores our current functionality!

- Adds the alert level bar, complete with colours!
- Resizes the window to properly show our custom jobs!
- Recolours sec to blue

image

Closes #18034

### CODE REVIEW

**Comment by RimiNosha** [comment]
I fucked the base branch and github isn't happy, one sec-

**Comment by RimiNosha** [comment]
Wait, no, I just forgot how to read diffs for a moment there, fuck.

**Comment by RimiNosha** [comment]
I FUCKING ACCIDENTALLY MERGED, GOD DAMN IT

**Comment by RimiNosha** [comment]
Holy shit this was a saga, here, take my changes before I break more shit

**Comment by Tastyfish** [comment]
Can you include the second fix changes in #18058 if applicable?

**Comment by RimiNosha** [comment]
Also includes a preemptive runtime fix which I'm PRing upstream.

**Pull request merged**
