### PR TITLE
Atmos QoL + Gas miners

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Adds gas miners, layer adaptors coming from tanks, and expands the HFR room a little.
(All maps other than Kilo have been done) 

Delta Upper

Delta Lower

Box main

Box HFR

Meta Main

Meta HFR

## Why It's Good For The Game

Quality of life changes are good. Running out of gas is bad.

## Changelog
:cl:
add: Gas miners are back in atmos
tweak: Added layer adaptors to the tank outputs
tweak: Expanded the HFR room
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
Good change.

**Review by RatFromTheJungle — CHANGES_REQUESTED** [review]
i dont know what qol means is it sex or something tel me what it means first

**Comment by Gandalf2k15** [comment]
Clear conflicts :P

**Comment by Gandalf2k15** [comment]
@KathrinBailey pls help the man

**Comment by Gandalf2k15** [comment]
Howdy, we're currently doing a map hard reset, all modular changes are being manually copied over. This PR will now be incompatable. It is also likely we will not have these issues once the map update has been completed. https://github.com/Skyrat-SS13/Skyrat-tg/pull/3219

**Pull request closed without merging**
