### PR TITLE
[READY] [BlueShift] [MODULAR] [MDB IGNORE] Updates BlueShifts airlocks to recent /TG/ conventions

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request
Brings BlueShift up to more (and recent) /TG/ map standards with the introduction of mapping access helpers.

## How This Contributes To The Skyrat Roleplay Experience
It doesn't (its code stuff).

## Changelog

:cl: Jolly
add: BlueShift airlocks have been updated to /TG/ mapping conventions through the means of mapped in airlock helpers. Mappers, stop var editing the doors!
add: Added the "Cent Com" access helpers as well as NT Reps access helper.
fix: Fixed some turfs not touching certain maintenance airlocks.
spellcheck: "Maintenance Access Hatch" has been reconverted back to its usual, de-capitalized name. This only applies to SOME airlock hatches.
spellcheck: "External Accesses" has been reconverted back to its usual, de-capitalized name. This only applies to SPECIFIC EXTERNAL airlocks.
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
I would like to note, since we don't have the new mapping integration test, I cannot assure that all the airlocks will be 100% scrubbed. Should they get merged while I'm still working on this, I can assure they'll be scrubbed, otherwise, I'm subjected to human error.

**Comment by Jolly-66** [comment]
I'll say this is finished, but would like to request a test merge of this if possible.

While the helpers are nice, scrubbing BlueShifts doors may yield some weird results. Player feedback would be greatly appreciated if I removed/added accesses to room(s) that should/shouldn't have them.

**Comment by Jolly-66** [comment]
Orderly and CMO cannot access the orderly office.
Double check how its done on Meta + access defines on orderly and CMO. May need to apply this to all dept guard offices.

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
This should be PRed to #13751 instead of master.

**Comment by Jolly-66** [comment]
Oh good god why

I have IMMENSE regret doing that

**Comment by BurgerLUA** [comment]
hey I think u have merge conflicts

**Pull request closed without merging**
