### PR TITLE
[MODULAR] Latejoin cyborgs are now linked to the station AI

### PR DESCRIPTION
**Pull request by FlamingLily**
## About The Pull Request
Once again, in the title.

**ALSO IMPORTANT NOTE:** I'm a dumb babby coder and for now, this only checks to latejoin link with AIs on z level 3 (the normal station Z-level). This means if there's ever an AI satellite on a multi-z level map that's on a lower, or not main z-level, this won't work. Luckily, that doesn't apply to any in rotation maps.

Except uh, ship station I suppose.

But really why would you become borg from menu on shipstation and not inhabit a posi that's on the ship?

2nd note, for the sake of modularity, spawning cyborgs get told their laws twice, once saying that they have no master AI, and once saying it correctly. It's a bit jank, but functional.

## Why It's Good For The Game
Realistic for the setting, NT wouldn't send easily subvertable unlinked AIs in. Doesn't fuck over traitor AIs anymore.

## Changelog
:cl:
add: NanoTrasen's silicon network has had it's firmware updated, meaning all late-shipped cyborgs now come pre-connected to the station's AI!
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
This is a codebase-wide bug, why only PR it Skyrat, and not to TG, which will then have it mirrored back to here?

**Comment by FlamingLily** [comment]
I'm not entirely sure it's a bug, maybe an oversight, but I can't see any intentions of this being the intended effect of the code.

Also, my code is shit baby tier and I doubt TG would accept my fix simply cause it's bad, but I guess I can ask.

**Comment by FlamingLily** [comment]
> 
> 
> I'm not entirely sure it's a bug, maybe an oversight, but I can't see any intentions of this being the intended effect of the code.
> 
> Also, my code is shit baby tier and I doubt TG would accept my fix simply cause it's bad, but I guess I can ask.

Also of note is that TG has 1 cyborg slot by default, not 3, so I doubt they run into this problem, tbh.

**Comment by JohnFulpWillard** [comment]
> > I'm not entirely sure it's a bug, maybe an oversight, but I can't see any intentions of this being the intended effect of the code.
> > Also, my code is shit baby tier and I doubt TG would accept my fix simply cause it's bad, but I guess I can ask.
> 
> Also of note is that TG has 1 cyborg slot by default, not 3, so I doubt they run into this problem, tbh.

Doesn’t change that it’s still a problem. The design doc in the readme does say to PR to TG if possible, this seems like a perfect example.

**Comment by FlamingLily** [comment]
Well apparently TG doesn't even have latejoins.

_shrug_

**Comment by Gandalf2k15** [comment]
We can TM this

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by Gandalf2k15** [comment]
Test merge has shown no issues.

**Comment by FlamingLily** [comment]
> 
> 
> Test merge has shown no issues.

aaaaaaaaaaaa I fouund oneeeee 11 hours too late

**Comment by FlamingLily** [comment]
*sigh*

**Pull request merged**
