### PR TITLE
[READY] [MOSTLY MODULAR] Vox sprite fixes, updates, and additions

### PR DESCRIPTION
**Pull request by CandleJaxx**
## About The Pull Request

This PR is made as to bring the Vox Species up to snuff with the other servers around on SS13. Vox as they are on Skyrat are weirdly humanized, following standard body variation and lacking the odd, more alien shape that other servers use.

## Why It's Good For The Game

Varied and different species are fun to play, and It'd be nice to spread out a bit from the standard human shape. It also makes things easier for Vox players shifting over from other servers, who might be turned off from trying out their favorite species' due to it looking like a pale comparison to the 'standard.'

## Changelog
:cl:
add: Added Vox clothing sprites that fit on their newly-adjusted sprite
add: vox suit / helmet additions to better fit their new sprites
add: vox-specific GAGS jumpsuits, skirts, shoes, berets, prison suits
add: gloves for vox-fucked-up-hands
add: modular species specific clothing section for future utilization on broader scope projects
qol: made something easier to use
change: Vox species parts and markings have been edited to appear more alien.

More to be posted as the PR progresses

/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
I bloody love you, wooooo!
There should be a boatload of sprites for most things (gloves, shoes, eyewear, masks, suits, uniforms, neckwear, all backpacks) over at para

**Comment by CandleJaxx** [comment]
there are, and i ported most of them! primary things rn are code, i'm in the progress of custom-making sprites for the different jumpsuits that sr uses

**Comment by KasparoVy** [comment]
> 
> 
> there are, and i ported most of them! primary things rn are code, i'm in the progress of custom-making sprites for the different jumpsuits that sr uses

You're an absolute chief, thanks so much!

**Comment by CandleJaxx** [comment]
it's mostly done, any maintainer / owner edits can be applied now, then it's set

**Comment by Useroth** [comment]
Nice stuff, but you need to make it more modular, where you can, or at least properly mark the non-modular parts where it's not possible.

**Comment by KasparoVy** [comment]
Hoooly shiiiit just getting more stoked as this is built out, great stuff integrating this with GAGS lmao, I wish that was always a thing so we didn't have to make unique sprites for each bloody colour of uniform 🤣

**Comment by CandleJaxx** [comment]
alright, most things are set up! only two non-modular, both marked.

**Comment by KasparoVy** [comment]
Fantastic work by you & Sabre

Been hilarious watching the antics of the Vox flock that came over from Para ahaha.
Thanks for modularizing

**Review by Useroth — COMMENTED** [review]
The modularisation is good now. Seems fine to me if it works proper and all.

**Comment by KasparoVy** [comment]
Looking forward to this kicking in for the next update! Stoked to rejig some loadouts and markings.

**Pull request merged**
