### PR TITLE
ook ook ack ack ack OOOOGHHHHKKKK

### PR DESCRIPTION
**Pull request by Gandalf2k15**
monkey-frustrated

### CODE REVIEW

**Comment by Zenitheevee** [comment]
least insane head maintainer

**Comment by Gandalf2k15** [comment]
fix but ci dumb

**Comment by ghost** [comment]
> only 2 changes are to engineering dmi's
> they replace an icon with a wholely different icon

I dont get it

**Comment by jjpark-kb** [comment]
sir, make a CL-- this is free GBP for you.

**Comment by GoldenAlpharex** [comment]
The error comes from a missing `icon_state` in the `obj` files, not the `mob` files. Although I guess it was probably missing from the `mob` file too, so having it there can't hurt.

**Comment by Gandalf2k15** [comment]
> > only 2 changes are to engineering dmi's
> > they replace an icon with a wholely different icon
> 
> I dont get it

fixed

**Pull request merged**
