### PR TITLE
Edits Deltastation SM to be less... wack

### PR DESCRIPTION
**Pull request by DuffCreeper**
## About The Pull Request

Edits the pipe network into the SM for delta to be more on par with ones found on Icebox/Box and Meta for less engine floor clutter
Also edits the exhaust pipes for the SM to be going to space by default instead of the scrubber network

## Why It's Good For The Game

Allows someone new to setting up the SM to not be as confused than they should be. Hopefully should prevent more SM delams from mistakes due to the weirdness of the delta SM in general

Also makes waste gas go into space by default instead of into the scrubber network which would cause gas not leaving the network fast enough in case of a delam for example due to the temp gate preventing hot gases leaving, causing a major clogging point that an inexperienced engineer might miss

(Changes marked in red ex de)
https://cdn.discordapp.com/attachments/788879168611024916/809983924054261790/unknown.png
## Changelog
:cl:
tweak: Reworks the pipe net to be more straight forward and on par with other SM base layouts
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
I've personally seen some of the Delta SM jank confuse new engineers, causing a delam. So... probably needed? Consider PRing to /tg/?

**Comment by NotRanged** [comment]
Please show mapping changes with a screenshot :/

**Comment by DuffCreeper** [comment]
> Please show mapping changes with a screenshot :/

The one thing I forget is the thing i've prepped for this
https://cdn.discordapp.com/attachments/788879168611024916/809983924054261790/unknown.png

**Comment by Cheshify** [comment]
Just a note: I had to deal with a Malf AI blowing the SM scrubbers to delam intentionally, this resulted in a number of the pipes beneath the SM being destroyed, meaning that there was literally no way to repipe and fix it as it is. In order to fix any interior damage to the SM chamber, you need to repipe it all to be more like what DuffCreeper is propositioning.

**Review by KathrinBailey — APPROVED** [review]
Sure why not.

**Pull request merged**
