### PR TITLE
New Fox emotes (Geckers and Fox purr)

### PR DESCRIPTION
**Pull request by izzyyes**
## About The Pull Request
Adds two new emotes. A "Gecker" for foxes and a unique purr for foxes. As foxes make really unique sounds :) To use the fox purr, the text would be *fpurr

## How This Contributes To The Skyrat Roleplay Experience
Adds two proper emotes to emote+ to use for fox-like characters. So the fox characters also have something to use instead of relying on emotes of others.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

https://user-images.githubusercontent.com/75942768/204135463-849d1623-beb3-4a08-93e2-35cd4f85951c.mp4

courtesy of The Death#3943 for the recording :)
</details>

## Changelog

:cl:
soundadd: Adds two new sound emotes for fox characters to use. A "Geckers" and a "Purr".
/:cl:

### CODE REVIEW

**Review by SpaceLoveSs13 — COMMENTED** [review]
As we discussed in DMs the binary file "modular_skyrat/modules/emotes/sound/emotes/foxgecker.ogg" is not needed. Make sure to remove that extra one, the voice one is sufficient for the PR. 
Also you should update the changelog to reflect exactly what changes you have made.

**Comment by UntoldTactics** [comment]
FINALLY THE FOX UPRISING BEGINS

**Review by tf-4 — CHANGES_REQUESTED** [review]
Really not a fan of that audio clip, is there another one that could be used?

**Comment by izzyyes** [comment]
like one of the only proper audio clips of a fox geckering. So, I'm gonna have to look pretty hard to even find something resembling this kind.

**Comment by izzyyes** [comment]
as most other fox noises i found either have the most loud background noise or they are just screaming with a pitch that can destroy ear drums. Fox noises are kind just that, screaming. so its a wonder i found anything where the mind does not scream "bloody murder"

**Comment by izzyyes** [comment]
but i may have found another, editing it now

**Pull request closed without merging**
