### PR TITLE
[NON-MODULAR] Rezadone can heal Ling Husks

### PR DESCRIPTION
**Pull request by LeChatGuide**
## About The Pull Request
Rezadone is used to heal normal husks. Following this logic, it should also be able to heal linghusks. also cleans the code for sythflesh a bit

## Why It's Good For The Game
Gives more options to heal the Ling Husk , while still being hard to make

## Changelog
:cl:
add: The ability to heal husks with 10u of rezadone
code: Cleaned some of my previous code regarding sythflesh
/:cl:

### CODE REVIEW

**Comment by LeChatGuide** [comment]
re-made this in a new branch cuz I think that's what was making it all buggy ? 
Also , like the previous one , big warning , wasn't able to test this cuz I can't start a shift on my private testing server. I'd appreciate if someone could test it or give feedback about it , as usual. Sorry for all this mess

**Comment by SpookyTheFox** [comment]
You might want to look around at lines 265 and 270 in medicine_reagents.dm since it looks like it has actions for both 5u and 10u with the edits you made. You might want to keep it at 5u and just add the ling husk to the normal action, so it stays in line with the TG wiki description of rezadone, which is:
`...If a husked corpse is treated with at least 5u and has under 50 burn damage it will be unhusked. ...`

**Comment by LeChatGuide** [comment]
> You might want to look around at lines 265 and 270 in medicine_reagents.dm since it looks like it has actions for both 5u and 10u with the edits you made. You might want to keep it at 5u and just add the ling husk to the normal action, so it stays in line with the TG wiki description of rezadone, which is:
> `...If a husked corpse is treated with at least 5u and has under 50 burn damage it will be unhusked. ...`

I was planning on doing that, but a coder on discord asked me to get it to 10u for the ling husk for balance issues, cuz the lings husks gotta be a bit more difficult to heal than the normal ones. I'm not sure about the 50 burn damage tho ... I took it out for the linghusk part cuz I figured that it's not the main form of damage you're taking when getting absorbed.

**Comment by SpookyTheFox** [comment]
10u is not a significant drawback for balance purposes. That's still grinding a single space carp, or clicking twice instead of once for a medical borg with infinite rezadone.

Initially I was all for it, but after thinking about it for a while, I'm not sure we need to be able to save ling husks. It just contributes to the mentality of everyone being entitled to survive the round, and that nothing bad ever happens.

**Comment by LeChatGuide** [comment]
> 10u is not a significant drawback for balance purposes. That's still grinding a single space carp, or clicking twice instead of once for a medical borg with infinite rezadone.
> 
> Initially I was all for it, but after thinking about it for a while, I'm not sure we need to be able to save ling husks. It just contributes to the mentality of everyone being entitled to survive the round, and that nothing bad ever happens.

Well , I'm not sure what to do tbh. We can already heal linghusks with sythflesh with https://github.com/Skyrat-SS13/Skyrat-tg/pull/4378 . The issue of healing linghusks was discussed at the time on that PR and it was accepted . This is mostly just code cleaning and extending it to rezadone cuz peoples thought it made sense. I could boost the rezadone cost up if needed I suppose ?

**Comment by Gandalf2k15** [comment]
I don't see this as a requirement given we can already do it.

**Pull request closed without merging**
