### PR TITLE
Reworks Icedyne (Icebox's Interdyne) to be more organically laid out

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

I hadnt been a fan of the 'stuff 9 sleepers into a closet' change that happened a while back and just only recently had the motivation to tackle it, this PR doubles the mining rooms and spreads the other spawners out across the ruin into various rooms while removing the 'closet'. I also got rid of the cargobay since it's an underground facility with no way for a shuttle to actually reach there, i instead replaced it with an observation deck that now includes interdyne's own external camera network along with a station facing one next to it. Additionally the room has a crew monitor as well.

Once policy v4 is pushed out i may swing back through here to redo slots

## How This Contributes To The Skyrat Roleplay Experience

The push to add a bunch of roles to the icebox map didnt really get mapped well, so i removed the room and gave all the miners their own room rather than the double-bunking they were doing. The other spawners are spread out in mostly logical locations such as RND/Engineering/medical etc. The observation post isnt a comms agent but more of a relay post, it houses the camera console for both the station and interdynes new internal network. I kept the interior cameras away for 'security reasons' and removed the completely useless cargo loading bay in favor of that.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

image

Since cargo's windows are gone i kept 1 to be able to peek out front.
image

Medbay Cryo
image

</details>

## Changelog

:cl:
add: Icedyne - Added external camera network to see what your perimeter looks like and what your turrets hate
add: Icedyne - New room! Observation deck, general access with both a station and internal camera consoles with crew monitor
add: Icedyne -  Medbay cryo offshot
qol: Icedyne - Spread out all the spawners and adjusted rooms accordingly, returned the missing welding tank to engineering.
/:cl:

### CODE REVIEW

**Comment by sqnztb** [comment]
If you want to address the few things dchat brought up to me yesterday (cryotube for medbay, ammo bench in the vault, and a secdrobe/extra handcuffs somewhere) then I'll revert my changes to this map that I have PR'd in #19992 so you don't get a conflict.

**Comment by Zergspower** [comment]
> If you want to address the few things dchat brought up to me yesterday (cryotube for medbay, ammo bench in the vault, and a secdrobe/extra handcuffs somewhere) then I'll revert my changes to this map that I have PR'd in #19992 so you don't get a conflict.

I can - but i'm not really sure on a couple things added like the secdrobe and cuffs?

**Comment by sqnztb** [comment]
> I can - but i'm not really sure on a couple things added like the secdrobe and cuffs?

The way I understood it, SecDrobe because DS-2 gets one and you can't exactly pop into DS-2 from Iceboxdyne. Cuffs in the event they have a few people drop in for a surprise visit a la wormholes (which happened a few days ago).

Made sense to me, at least.

**Comment by Zergspower** [comment]
> > I can - but i'm not really sure on a couple things added like the secdrobe and cuffs?
> 
> The way I understood it, SecDrobe because DS-2 gets one and you can't exactly pop into DS-2 from Iceboxdyne. Cuffs in the event they have a few people drop in for a surprise visit a la wormholes (which happened a few days ago).
> 
> Made sense to me, at least.

Granted i dont see any comments on the PR yet, but I feel interdyne has no need for secdrobe given it has no brig or anything of the sorts

**Comment by sqnztb** [comment]
> > > I can - but i'm not really sure on a couple things added like the secdrobe and cuffs?
> > 
> > 
> > The way I understood it, SecDrobe because DS-2 gets one and you can't exactly pop into DS-2 from Iceboxdyne. Cuffs in the event they have a few people drop in for a surprise visit a la wormholes (which happened a few days ago).
> > Made sense to me, at least.
> 
> Granted i dont see any comments on the PR yet, but I feel interdyne has no need for secdrobe given it has no brig or anything of the sorts

That's fair, yeah. The secdrobe/cuffs were very much the lowest priority on the list, just kind of thrown in at the very end. The tube and the ammo bench being the big asks. I'll go ahead and revert my change so we won't run into conflicts and the SecDrobe can be discussed separately if we need to.

**Comment by Zergspower** [comment]
> 

sounds good i'll add them in

**Comment by gamermomentum** [comment]
Way back before "Stuff 9 spawners into a closet" we had "just throw spawners randomly everywhere" and it wasn't much better. 

Unlike that time though, this one manages not to block a ton of useful stuff(poor single bookcase and physical access to one of the RTGs), but it's still kinda goofy to just have randomly placed spawners. 

"Yes, they make me sleep in the virology internals closet. Someday I'll get a bedroom of my own." 

This still doesn't solve the *actual* Icedyne problem; This base is absolutely way too small to house 14 people, and when all spawners are used it's a hyper-crowded fiasco.

**Comment by SpaceVampire** [comment]
maybe we should just remove some spawners?
that is a lot for a ghost role, way more then anything else

**Comment by Zergspower** [comment]
> maybe we should just remove some spawners? that is a lot for a ghost role, way more then anything else

i'm not against it - it's cramped for sure

**Comment by burgerenergy** [comment]
It's supposed to be a lot, it's an alternate station in most effects. Ideally the spawner clunkiness issue gets tackled someplace else, but I wouldn't recommend removing any.

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
Map linters

**Comment by Zergspower** [comment]
> 

image
image

**Comment by Zergspower** [comment]
CI errors are, shuttle related weirdly

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
