### PR TITLE
Cleans up the aesthetic gun folder and kills most of it off from overwriting things that have been resprited or do not need resprites.

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request

The PR originally started as just removing the aesthetic override for the Captain's laser since it was being overwritten by us and using the older worse sprite. Then turnt into a full blown clean up, removing duplicates, unused things, and others.

Our modular guns are fine, they still have their icons. This only removes most overwrites stolen from Eris.

Some standout differences are the Ballistics, which are still mostly overwritten mostly cause there are a few sprites that need to be redone manually. They're still slated for the chopping block sooner or later.

## How This Contributes To The Skyrat Roleplay Experience

Removes unused, and old sprites just taking up space in the files never being touched. Lets resprited guns (The captain's laser) actually be resprited, and slowly kills off the Eris guns that were haphazardly slapped in.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
Lefthand, ballistics, some unremoved overwrites, and our modular guns. Righthand, energy weapons that were almost entirely set back to TG standard.

Guns larger

</details>

## Changelog

:cl:
image: Cleaned up the aesthetic guns folder, removed some overwrites on guns back to TG standard namely: The basic e-gun, captain's laser, and the energy guns.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
most if not all of the reversions are inferior

**Comment by Ebin-Halcyon** [comment]
> most if not all of the reversions are inferior

They aren't, you just have an obsession with Eris.

**Comment by Gandalf2k15** [comment]
show both side by side, before and after.

**Comment by desertmote** [comment]
yessss the real c20r

**Comment by ghost** [comment]
Lots of missing inhand states, are they still overwritten somewhere?

**Comment by ghost** [comment]
Last CI failure I see:
```nix
/obj/item/gun/energy/laser/hellgun/blueshield in both 'modular_skyrat/modules/aesthetics/guns/icons/guns_lefthand.dmi' & 'modular_skyrat/modules/aesthetics/guns/icons/guns_righthand.dmi'.
  	inhand_icon_state = "laser" - Matching sprite found in: 'icons/mob/inhands/weapons/guns_righthand.dmi' & 'icons/mob/inhands/weapons/guns_lefthand.dmi'
  	FAILURE #1: Missing inhand sprites for /obj/item/gun/energy/laser/hellgun/blueshield in both 'modular_skyrat/modules/aesthetics/guns/icons/guns_lefthand.dmi' & 'modular_skyrat/modules/aesthetics/guns/icons/guns_righthand.dmi'.
  	inhand_icon_state = "laser" - Matching sprite found in: 'icons/mob/inhands/weapons/guns_righthand.dmi' & 'icons/mob/inhands/weapons/guns_lefthand.dmi' at code/modules/unit_tests/inhands.dm:88
  ```
hellgun/blueshield needs its inhand_icon_state re-defined, likely as `hellfirepdw`

**Comment by Ebin-Halcyon** [comment]
lol.

**Pull request closed without merging**
