### PR TITLE
[MANUAL MIRROR] Return to Tiny: Reworks heights to use filters, allows spacemen to have varying heights

### PR DESCRIPTION
**Pull request by Paxilmaniac**
Re-pr of #66644 with some changes to get it working

image

- [x] ~~Huds get cut off~~ Resolved
- [x] ~~Very tall helmets get cut off~~ Resolved
- [x] Hair gets cut off
- [x] ~~Needs optimization before releasing to the world as a pref~~ jk
lol

Look at that fella so cute

:cl: Melbert, That REALLY Good Soda Flavor, FatFat, AndreyGusev
add: Spacemen can now have varying height. (Admin only for now)
add: Dwarfs are now slightly shorter, but look way better.
/:cl:

### CODE REVIEW

**Comment by PCPort** [comment]
AT LAST.

BEGONE, SPRITE SCALING

**Comment by Paxilmaniac** [comment]
To prevent possible confusion for port's comment this does not actually remove sprite scaling or add this as a preference

**Review by lessthnthree — APPROVED** [review]

**Comment by RimiNosha** [comment]
I strongly suggest DNM on this one for now, due to a visual bug with reattaching limbs that seems to be related to this.

**Comment by Paxilmaniac** [comment]
there are other bugs i gotta squash unrelated to what rimi said

**Comment by Paxilmaniac** [comment]
#19451

**Pull request closed without merging**
