### PR TITLE
Adds big eyes as a marking, but this time I used the right version of the other_markings.dmi file.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Adds a new marking that makes your eyes bigger.

## Why It's Good For The Game
Special snowflake eyes.

## Changelog
🆑
add: Nanotrasen no longer refuses to hire people with larger than average eyes.
/🆑

### CODE REVIEW

**Comment by hugmeorelse** [comment]
These eyes are too large. I expected something like on Virgo or Cit RP where they have eyes that are two pixels tall. This is too much.

**Comment by ShadeAware** [comment]
image
This is rather ghastly...

**Comment by Azarak** [comment]
> 
> 
> These eyes are too large. I expected something like on Virgo or Cit RP where they have eyes that are two pixels tall. This is too much.

This, if you shave the pixels off of the sides and make it 1x2, lined up with the eyes then it could be much better

**Comment by ghost** [comment]
> These eyes are too large. I expected something like on Virgo or Cit RP where they have eyes that are two pixels tall. This is too much.

It's meant for alien species with larger eyes than humans.

**Comment by ghost** [comment]
> image
> This is rather ghastly...

That's the point.

**Comment by ghost** [comment]
I made the big eyes smaller and renamed the original big eyes to "bigger eyes" because apparently people want that.

**Comment by Azarak** [comment]
Could you remove the 2x2 bigger eyes? I dont think they should exist

**Comment by ghost** [comment]
> Could you remove the 2x2 bigger eyes? I dont think they should exist

No.

**Comment by Gandalf2k15** [comment]
I dont have anything against this.

**Comment by Azarak** [comment]
I know people will use that for "anime" eyes, and I have an issue with that

**Comment by hugmeorelse** [comment]
@Useroth I personally move to reject this. It's not a good fit for the server in terms of the vision set.

**Comment by hugmeorelse** [comment]
@Useroth I personally move to reject this. It's not a good fit for the server in terms of the vision set.

I am not a fan of rejecting user-created content, but we need to maintain standards fit to what we had in mind for the server.

@TheSpaghetti If you disagree, please post example screenshots of the eyes in question and on sprites that you see them best on. Use the PR description for that.

**Comment by ghost** [comment]
> @Useroth I personally move to reject this. It's not a good fit for the server in terms of the vision set.
> 
> I am not a fan of rejecting user-created content, but we need to maintain standards fit to what we had in mind for the server.
> 
> @TheSpaghetti If you disagree, please post example screenshots of the eyes in question and on sprites that you see them best on. Use the PR description for that.

...how do I get a screenshot of b e e g eyes if they aren't in the game?

**Comment by hugmeorelse** [comment]
> > @Useroth I personally move to reject this. It's not a good fit for the server in terms of the vision set.
> > I am not a fan of rejecting user-created content, but we need to maintain standards fit to what we had in mind for the server.
> > @TheSpaghetti If you disagree, please post example screenshots of the eyes in question and on sprites that you see them best on. Use the PR description for that.
> 
> ...how do I get a screenshot of b e e g eyes if they aren't in the game?

Run it locally?

**Comment by Gandalf2k15** [comment]
The host has spoken, please add your images and such and reopen this when you have time.

**Pull request closed without merging**
