### PR TITLE
adds the space assassin kit at 35 tc

### PR DESCRIPTION
**Pull request by dawsonkeyes**
sussy baka

## About The Pull Request

The Space Assassin kit from the original More Trairor Items PR, rebalanced in its cost and finally brought to light once more. This kit features only a combat knife, syndicate softsuit, and a book that teaches the user how to ventcrawl.

## How This Contributes To The Skyrat Roleplay Experience

More traitor versatility encouraging substandard playstyles without simply giving them ten new ways to beat someone to death or shoot them

## Changelog

:cl:
add: Space Assassin bundle
/:cl:

### CODE REVIEW

**Comment by Lauwma** [comment]
My only concern with this is people abusing vent system to steal things. Stealing things without hints doesn't lead to conflicts. As much as I'd like to see that PR get merged I'm worried with the potentially bad Antag RP flavor it would create.

**Comment by dawsonkeyes** [comment]
Please notice: neither the contortionist guide nor the bundle itself feature any written references to the hit video game “among us”

**Comment by dawsonkeyes** [comment]
> My only concern with this is people abusing vent system to steal things. Stealing things without hints doesn't lead to conflicts. As much as I'd like to see that PR get merged I'm worried with the potentially bad Antag RP flavor it would create.

Well, I can’t predict how the average traitor might use it. It fully sacrifices extra versatility like emags and the like, but beyond that I’m not the best at being able to tell

**Comment by GoldenAlpharex** [comment]
I don't know about this one. The whole thing makes little sense in and of itself, it doesn't involve any kind of interesting mechanic revolving around ventcrawling, it just makes normal people suddenly be able to fit in a pipe that's only four pixels wide. There's not much in terms of risk related to using the ability of vent crawling, no toggle, nothing that really indicates visually that "hey this person might be able to fit in a vent", unlike stuff like bat-form or what not.

**Comment by dawsonkeyes** [comment]
> I don't know about this one. The whole thing makes little sense in and of itself, it doesn't involve any kind of interesting mechanic revolving around ventcrawling, it just makes normal people suddenly be able to fit in a pipe that's only four pixels wide. There's not much in terms of risk related to using the ability of vent crawling, no toggle, nothing that really indicates visually that "hey this person might be able to fit in a vent", unlike stuff like bat-form or what not.

It allows you to ventcrawl- but it doesn’t make you immune to the contents of the vent. The provided pressure suit and another source of oxygen or otherwise is needed. It’s kind of like how monkeys can ventcrawl, rather than Xenos- Xenos are immune to pressure but not heat. Monkeys aren’t immune to either.

**Comment by dawsonkeyes** [comment]
There’s additionally the risk/reward factor- when ventcrawling you can’t see what’s outside. There’s no added tools besides your combat knife, so you’re blind if you want to try to get somewhere you shouldn’t be without pre-planning

**Comment by GoldenAlpharex** [comment]
> There’s additionally the risk/reward factor- when ventcrawling you can’t see what’s outside. There’s no added tools besides your combat knife, so you’re blind if you want to try to get somewhere you shouldn’t be without pre-planning

What I meant is, there's not much going on mechanics-wise between someone that has vent crawl and someone that doesn't. For instance, vampires had to turn into bats to be able to vent crawl, which meant you had to make yourself very vulnerable to get access to it. In general, I don't remember exactly why it was removed, but I know it was very meh as a kit in general, it's kinda underwhelming and a bit lame roleplay-wise. It was even commented out before getting fully merged, and just... In general, an Among Us-themed traitor kit isn't really something I'd like to see more of.

**Comment by dawsonkeyes** [comment]
> What I meant is, there's not much going on mechanics-wise between someone that has vent crawl and someone that doesn't. For instance, vampires had to turn into bats to be able to vent crawl, which meant you had to make yourself very vulnerable to get access to it. In general, I don't remember exactly why it was removed, but I know it was very meh as a kit in general, it's kinda underwhelming and a bit lame roleplay-wise. It was even commented out before getting fully merged, and just... In general, an Among Us-themed traitor kit isn't really something I'd like to see more of.

Fair enough. For future reference, what sorts of loadouts and items would you like to see more of?

**Comment by thestubborn** [comment]
image

**Comment by axietheaxolotl** [comment]
> [...] In general, an Among Us-themed traitor kit isn't really something I'd like to see more of.

wasn't this Metal Gear Solid, not Amogus?

**Comment by GoldenAlpharex** [comment]
> > [...] In general, an Among Us-themed traitor kit isn't really something I'd like to see more of.
> 
> wasn't this Metal Gear Solid, not Amogus?

It's a space suit of a random color and a knife to go kill crew members from the vents. If that's not an Among Us reference, I don't know what is.

**Pull request closed without merging**
