### PR TITLE
[MODULAR]Adds the Safekini

### PR DESCRIPTION
**Pull request by MacaroniCritter**
## About The Pull Request
Adds a High-Vis Bra to the tops section of underwear.

## How This Contributes To The Skyrat Roleplay Experience
Allows the community a new method of expressing themselves.

## Proof of Testing
Screenshot shows use of item in game.

<details>
<summary>Screenshots/Videos</summary>
  
75d6ec8e70f82f7198bbad916faed0e7
208278f14425df148e6da44e0fee294b

</details>

## Changelog

:cl:
add: new underwear
/:cl:

### CODE REVIEW

**Comment by Samf3232** [comment]
im so excited

**Comment by softcerv** [comment]
Hey there, I notice that this is your first PR, I appreciate you taking the time to contribute to our repository. 

However, before we look into merging your PR, we are going to need you to change your PR body to use the standard Skyrat PR template.

**Comment by Nerev4r** [comment]
The spriting is kinda scuffed; we should look into making it use the same palette and shading as hazard vests.

**Comment by Samf3232** [comment]
> The spriting is kinda scuffed; we should look into making it use the same palette and shading as hazard vests.

Hello, this sprite aas made to copy an image we found online (attached) 
tumblr_e4589e01e2fe3ee1f8b619d67d37a8b3_ba191677_1280

**Comment by MacaroniCritter** [comment]
> Hey there, I notice that this is your first PR, I appreciate you taking the time to contribute to our repository.
> 
> However, before we look into merging your PR, we are going to need you to change your PR body to use the standard Skyrat PR template.

I believe it now follows the standard PR template, right?

**Comment by vinylspiders** [comment]
Looks good!

**Review by vinylspiders — APPROVED** [review]

**Pull request merged**
