### PR TITLE
Removes a remnant of redsec

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Makes Lia blue

image

## How This Contributes To The Skyrat Roleplay Experience

We've had bluesec for a long time, there's no reason we should still have remnants of the old design. Lia is a part of security and has no excuse not to look the part.
It just makes people feel bad seeing the fish be red when they're unable, thus this will boost player morale additionally.

## Changelog
:cl:
fix: Lia is no longer a redsec separatist.
/:cl:

### CODE REVIEW

**Comment by Higgin** [comment]
repo ban this man

**Comment by tf-4** [comment]
> repo ban this man

It's important to have a consistent style, and ours is blue. Da ba dee.
I'll be using search and replace to swap out red hex codes for blue ones throughout the repo in the next few days.

**Comment by Jolly-66** [comment]
This blue is more offensive than this PR.

**Review by Zonespace27 — COMMENTED** [review]
The color of blue chosen seems unnecessarily deep and tbh doesn't look good

**Comment by ghost** [comment]
Why is Lopland painting the HoS's fish? Security is blue because they're armed and clothed by Lopland/Armadyne, recoloring the fish feels pointless and more to prove a point of some sort :/

**Comment by IgiariValkyr** [comment]
I better be able to spraypaint her back red

**Comment by tf-4** [comment]
GOOD point I'll come back to this with the ability to spray paint the fish any colour and perhaps a special rainbow paint job to be inclusive

**Pull request closed without merging**
