### PR TITLE
Fixes Azarak Combat: Suplexing, Headslams, Dislocation, and more.

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request

Did you know all these features were broken tgui say? https://github.com/Skyrat-SS13/Skyrat-tg/pull/14375
Since people are rewriting all these features instead of actually fixing the problem, I present fixing the problem that's existed for almost a year. 

## How This Contributes To The Skyrat Roleplay Experience

Broken features are bad. Maintaining things good. Technical Debt bad. 

## Proof of Testing

<details>

https://user-images.githubusercontent.com/77420409/228059971-63f43707-e0aa-454b-bcc4-e7ec863cc867.mp4

<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
fix: Wrestling fans rejoice. You can now do your wrestling moves again, such as suplexing and head slams. 
/:cl:

### CODE REVIEW

**Comment by softcerv** [comment]
hold up, doesn't https://github.com/Skyrat-SS13/Skyrat-tg/pull/19971 already handle some of the things in this?

**Comment by nevimer** [comment]
> hold up, doesn't #19971 already handle some of the things in this?

okay so Tgui say broke this because of a single line edit, where the arguments were in the wrong order. 

Instead of rewriting the whole thing, (they didn't fix the OG argument order issue) they just made it more complex to compensate for what was originally just an error in a SKYRAT EDIT when some variables were renamed.

Also correct me of I am wrong, but the two PR's don't seem complete.

**Comment by softcerv** [comment]
ah!

**Comment by Hatterhat** [comment]
> Also correct me of I am wrong, but the two PR's don't seem complete.

i'd rather get that mentioned followup pr merged, and then throw out a third pr to reinstate the lost strangling feature that someone else mentioned in passing, because i think that strangling, as something that would be reimplemented (as a feature) would rather get its own pr, rather than be patched into the vaguely-fix-ish vaguely-inconsistency-handling things that the pr already is. (it's been sitting there for a week. it'd be great if it was merged.)

codewise i'd like to think the separation of grabs into their own procs made the main chain more readable just at a glance, but if you want it to be a wall then i suppose to each their own

gameplay-wise you could argue that the blunt wound interaction thing is kind of just a weird afterthought, and putting grab interacts on alt click + combat mode makes it less usable in the flow of combat but they're Weird Grabs, they don't really have a great place in the flow anyway imo

also this pr (making the grab interacts accessible again) was already done with Skyrat-SS13/Skyrat-tg#19960

call me stubborn for advocating for my own pr, as suboptimal as it probably is, but it worked when i tested it and players aren't going to care about the args being in weird orders, they're going to care about if they can do it or not, which they *could* with the first pr.

**Comment by Gandalf2k15** [comment]
This appears to have already been corrected

**Pull request closed without merging**
