### PR TITLE
New brig for Icebox :)

### PR DESCRIPTION
**Pull request by cheapcents**
## About The Pull Request

A complete redesign of Icebox's brig with facilitation of roleplay in mind. Was partially done under Floof Ball#0798's instructions.
image
image

## How This Contributes To The Skyrat Roleplay Experience

In the middle of the brig can be seen the prison a floor below. Players who walk around in this brig will be constantly reminded that prisoners exist: They will see them walking around, maybe dying, maybe trying to riot, and might decide to interact more with them.

Every essential member of the department aside from the warden spawns inside the security office, stationed on chairs, giving the HoS an easy opportunity to setup a meeting at the beggining of the shift.

There are a few free spots and machine frames laid around the brig to allow for easy costumization.

It has a better suited courtroom, designed by someone who has hosted several IC lawsuits, that makes setting up a session easy. Witnesses can have their own quarters, lawyers have direct access to the courtroom through the entrance inside the brig, and it has a few useful tools inside like a photocopier and a megaphone for the judge. If needed, the courtroom itself can be reporpused into maybe an arena or a prison since almost everything inside it can be easily removed.

## Changelog

:cl:
add: Completely changed Icebox's brig.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Nice work. This is cool.

**Comment by Gandalf2k15** [comment]
Can you see into the cells from the gangway?

**Comment by Gandalf2k15** [comment]
Unfortunately these changes will only last until the next map reset, if you are able to, take this upstream

**Comment by Funce** [comment]
Maptainer has adjustments to make for this. (Not me), expect to hear from them soon.

**Comment by YakumoChen** [comment]
Don't like the maint escape from prison
Don't like how the armoury is needlessly hard to break into now (armouries always have a hull-exposed side to allow antags to smash in from behind, this forces antags to break into brig to get to the armoury)
Make sure that the execution plank actually leads to Z-2

**Review by KathrinBailey — APPROVED** [review]
Check the commit descriptions for info on changes.
A whole bunch of fixes have been pushed to this (with permission).
Some of the main non-fix changes are as follows;
• Techfab moved back to office.
• Maint around prison reinforced to make escape attempts a little more difficult, it's still move difficult than the previous prison to break out of.
Check mapdiffbot because the screenshots are out of date now. Leaving this up for a little longer before merging.

**Comment by cheapcents** [comment]
> 
> 
> Can you see into the cells from the gangway?

No. I made sure you couldn't.

> 
> 
> Don't like the maint escape from prison Don't like how the armoury is needlessly hard to break into now (armouries always have a hull-exposed side to allow antags to smash in from behind, this forces antags to break into brig to get to the armoury) Make sure that the execution plank actually leads to Z-2

The armory is alot easier to breach into once you're actually inside the department, considering there's a literal pathway into one of the very vulnerable windows. Even then, it requires a _little_ more effort and I'll gladly admit that it warrants some changes.

Even if you break out of the prison through the maintenance, all other exits will still only lead either outside into the wild or back inside the security department. It's still only as difficult as other prisons.

I made sure the hole on the execution plank was an icechasm tile, not an openspace tile.

**Comment by Fikou** [comment]
bring this upstream sweetie

**Comment by KathrinBailey** [comment]
Integration tests are failing on power armor.
This will need to be modularised even if its on TG, so it's coming here first.
After feedback has been given any remaining bugs have been found it can go to TG.

**Pull request merged**
