### PR TITLE
puts the newly resprited peacekeeper uniform in the sec clothes vendor and loadout, bc i forgot

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

I resprited these and you can't even get them anywhere what the flarp!!

## How This Contributes To The Skyrat Roleplay Experience

image

Look at her.

## Proof of Testing

image

## Changelog

:cl:
add: The newly resprited peacekeeper uniforms for security can now be gotten in the loadout and in the clothing vendor.
/:cl:

### CODE REVIEW

**Review by vinylspiders — APPROVED** [review]

**Comment by GoldenAlpharex** [comment]
Also seems like the outfit that was added by https://github.com/Skyrat-SS13/Skyrat-tg/pull/24118 were removed from your previous PR.

**Comment by W4rd3nn** [comment]
what the FLARP paxil!!! Mr Rizzlectric!! Send Paxil's GBP to the skibidi and have it set to -420!!!!

**Comment by CrimshonShine** [comment]
-1 ruins my drip for no discernible reason

**Review by GoldenAlpharex — APPROVED** [review]
Looks good!

**Pull request merged**
