### PR TITLE
[Modular] Talking Tay

### PR DESCRIPTION
**Pull request by linnpap**
## About The Pull Request
dreamseeker_KMYkU1Aqvs
Tay Fraser is now in plush form for you and your family to enjoy! He repeats everything you say when his talk-back function is activated. Makes a great friend for your little one to talk with at playtime. For ages 3 and up. 

dreamseeker_OiFMWweJ4C
Not at all possessed by demonic entities!

## How This Contributes To The Skyrat Roleplay Experience
my friends said that it would be funny

## Changelog

:cl:
add: Added Talking Tay
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
How horrifying.

**Comment by axietheaxolotl** [comment]
> 	//THE STUTTERSLUT ALGORITH

**_Amazing._**

**Comment by linnpap** [comment]
> 
> 
> How horrifying.

https://www.youtube.com/watch?v=fSfsWFUmaX8

**Comment by GoldenAlpharex** [comment]
This is funny and all, but I'm going to sadly have to close this because plushies are for donators only.

Oh and you don't have positive GBP either.

**Pull request closed without merging**
