### PR TITLE
[Modular] Undoes TG's shitty weapon size increases.

### PR DESCRIPTION
**Pull request by ShadeAware**
## About The Pull Request
Undoes TG's shitty weapon nerfs that made every Energy Weapon a bulky object for absolutely no logical reason. Nobody wanted this.
Completely modular, no custom code, simple few-line changes done in files located in **modular_skyrat/modules/projectiles**.

## Why It's Good For The Game
Shitty nerfs that do nothing of benefit for the sake of shitty nerfs that do nothing of benefit are not good for the game. This was wildly unpopular on TG, and I see no reason for us to have it either.

## Changelog
:cl:
balance: Gun sizes aren't asinine anymore.
/:cl:

### CODE REVIEW

**Comment by SpaceVampire** [comment]
Could we not start doing balance patches right away, and at least wait for a while to see how it plays out first?

**Comment by Azarak** [comment]
> 
> 
> Could we not start doing balance patches right away, and at least wait for a while to see how it plays out first?

This

**Comment by Draganfrukts** [comment]
You can still store energy weapons in your suit storage so long as you're wearing armour that permits it. The only exception I can think of is the combat shotgun.

TG Security lives with this change which forces them to only keep either small ineffective guns or use the essentials so *shrug

Let's see how it actually plays out in this environment before pushing balance changes.

**Comment by KathrinBailey** [comment]
> Let's see how it actually plays out in this environment before pushing balance changes.

This is pretty kneejerk. ~~TG's PR didn't touch disablers~~, you just now have to reserve your exosuit slot for the energy gun, which it'll neatly fit into, in exchange for two more shots. There are also much better ways to bring back NORMAL weight weapons than just doing a modular revert.

-edit: oh yeah disablers are the child of /e_gun

**Comment by necromanceranne** [comment]
Disablers are normal sized on tg. Thr change functionally is fine. You won't see as many one man armies with dozens of energy weapons in their bag but disablers have a dependable niche to fill as a smaller arm. That's a good role to fill in my view.

**Comment by ShadeAware** [comment]
Closed in favor of  #1346

**Pull request closed without merging**
