### PR TITLE
[MODULAR] Removes tacticool turtleneck and skirtleneck from the loadout.

### PR DESCRIPTION
**Pull request by SpaceVampire**
## About The Pull Request

Removes tacticool turtleneck and skirtleneck from the loadout.
You are still able to get them in the actual game.
Alternative to https://github.com/Skyrat-SS13/Skyrat-tg/pull/6445

## Why It's Good For The Game

Those items are pretty much low-level contraband, and are supposed to be a fun little reward if you track them down.
Being able to get them in the load-out removes all of that, and the fact that you could just show up to work with them is contradictory from a lore standpoint.

## Changelog
:cl:
del: Tacticool turtleneck and skirtleneck from the loadout.
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
on one hand: i dont use it and have added far cooler turtleneck esq costumes
on the other hand: its just a clothing item and I don't care that much

**Comment by Gandalf2k15** [comment]
I do feel like we need a better way or giving people clothing too. Since finding it on space exploration seems like a good idea. But yeah, casual syndicate outfits on board is a little bit sus.

**Comment by desertmote** [comment]
> I do feel like we need a better way or giving people clothing too. Since finding it on space exploration seems like a good idea. But yeah, casual syndicate outfits on board is a little bit sus.

we recently had a PR that allows ghostroles to have loadout items, no? maybe we could make some items ghostrole only

**Comment by dominuslucian** [comment]
tacticools arent contraband. those are tactical turtlenecks/skirtlenecks

this seems like a non issue tbh

**Comment by lyricalpaws** [comment]
He's just salty that I made a pr he didn't like

**Comment by hugmeorelse** [comment]
They're not contraband, and I quite like these outfits. I also don't see the point of taking away more and more from players for the sake of "exploration". If you want to add more to exploration, add new items instead of taking them away. Why should players explore for things they already have access to that offers no real benefit? If they do offer benefits, just have the loadout ones give no benefits.

**I also don't want people to validhunt folks just because of the fact they're wearing a turtleneck.**

**Comment by hugmeorelse** [comment]
> He's just salty that I made a pr he didn't like

You get one warning. Do not post anything that is not technical analysis or polite, neutral critique and feedback. This is not a place for gossip.

**Comment by SpaceVampire** [comment]
Just to be clear, they are counted as contraband in the clothing vender due to their associations.
You could still hack one of those to get them if you wanted it.
I just think that having everything available right away in the load-out really takes away from it.

**Comment by hugmeorelse** [comment]
> Just to be clear, they are counted as contraband in the clothing vender due to their associations.
> You could still hack one of those to get them if you wanted it.
> I just think that having everything available right away in the load-out really takes away from it.

Let's add new content for that then.

**Comment by lyricalpaws** [comment]
> 
> 
> Just to be clear, they are counted as contraband in the clothing vender due to their associations.
> You could still hack one of those to get them if you wanted it.
> I just think that having everything available right away in the load-out really takes away from it.

No they're not? TACTICAL Turtlenecks are, but TactiCOOL are not.

**Comment by SpaceVampire** [comment]
> > Just to be clear, they are counted as contraband in the clothing vender due to their associations.
> > You could still hack one of those to get them if you wanted it.
> > I just think that having everything available right away in the load-out really takes away from it.
> 
> No they're not? TACTICAL Turtlenecks are, but TactiCOOL are not.

Contra

**Comment by lyricalpaws** [comment]
Contraband vendor wire =/= contraband item to sec

**Comment by SpaceVampire** [comment]
> Contraband vendor wire =/= contraband item to sec

Yeah, I never claimed otherwise.
I'm just saying that are designed to look suspect in general, thus the "low-level" bit of it.

Also I made this after someone wanted to change the stats on them due to "balance" reasons due to the load-out status.
Which I think it kind of lame, because they are supposed to be something cool to get in the actual game.
And that works to kind of ruin the point of it. Like, if you put everything worth having at the start of the game for free.
You do lose out on some aspects.

**Comment by hugmeorelse** [comment]
> > Contraband vendor wire =/= contraband item to sec
> 
> Yeah, I never claimed otherwise.
> I'm just saying that are designed to look suspect in general, thus the "low-level" bit of it.
> 
> Also I made this after someone wanted to change the stats on them due to "balance" reasons due to the load-out status.
> Which I think it kind of lame, because they are supposed to be something cool to get in the actual game.
> And that works to kind of ruin the point of it. Like, if you put everything worth having at the start of the game for free.
> You do lose out on some aspects.

Again, why don't we add new items? Taking items away suddenly is not really kosher. I will support any bounties for new clothings that are cool and can be found by looking around in maintenance and so forth.

**Comment by hugmeorelse** [comment]
> > Contraband vendor wire =/= contraband item to sec
> 
> Yeah, I never claimed otherwise.
> I'm just saying that are designed to look suspect in general, thus the "low-level" bit of it.
> 
> Also I made this after someone wanted to change the stats on them due to "balance" reasons due to the load-out status.
> Which I think it kind of lame, because they are supposed to be something cool to get in the actual game.
> And that works to kind of ruin the point of it. Like, if you put everything worth having at the start of the game for free.
> You do lose out on some aspects.

Either that or we can find suitable replacements for these in the loadout and put the tactical turtleneck to be scavenged.

**Comment by dominuslucian** [comment]
you can hack a cig machine and get an e-cig. those arent contraband and sec isnt going to give you a citation for it. 
additionally, you can hack the security vendor and get (non hud) sunglasses. those are also not contraband. why is this an issue?

**Comment by SpaceVampire** [comment]
> you can hack a cig machine and get an e-cig. those arent contraband and sec isnt going to give you a citation for it.
> additionally, you can hack the security vendor and get (non hud) sunglasses. those are also not contraband. why is this an issue?

It's really just an issue because you shouldn't have access to them round-start for free.
You should have to put in the work of hacking it to unlock em. You wouldn't put sunglasses in the load-out.
That item also has additional implications that come with it, due to the style.
Hopefully that better explains my reasoning for it? Not that I plan to reopen this.

**Pull request closed without merging**
