### PR TITLE
make me codeowner

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
sets me to codeowner for my own content, so I can see whats being modified to work with the changes

### CODE REVIEW

**Comment by BurgerLUA** [comment]
obvious powergrab!!!!

**Comment by Iamgoofball** [comment]
This doesn't work without you being given commit access due to how github functions. Sorry.

**Comment by GoldenAlpharex** [comment]
> This doesn't work without you being given commit access due to how github functions. Sorry.

Broski, I don't know how to tell you this but Jake's a maintainer.

**Comment by GoldenAlpharex** [comment]
On that note, I really need to add myself to something in there too. Just don't have my own modules yet, I don't think. I'll figure something out later.

**Pull request merged**
