### PR TITLE
Scream selector

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

So I've had a lot of requests for this and a recent conflict of interest over lizard screams has arizen, so I thought it was time to finally add in selectable screams for chracters.

On the character creation menu, you will see a list of screams available for your character. Some screams are restricted to certain species(robotic one is only for robotic species!). You can also set your scream to nothing(why you'd want to do that I don't know.)

image

Donators get access to some custom screams too, it's amazing.

closes https://github.com/Skyrat-SS13/Skyrat-tg/pull/4300

## Changelog
:cl:
add: You can now select what scream your species has, check it out in the character creator!
add: Donators now get some cool custom screams, check them out!
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
Possible to add this to the slimeperson shapeshift button?

**Comment by Owai-Seek** [comment]
This seems to set your scream across all characters, not just one. At least, as of Round: 1112

**Comment by Gandalf2k15** [comment]
> This seems to set your scream across all characters, not just one. At least, as of Round: 1112

Just a load error. Set scream and save. Them move to a different character set scream and save

**Comment by Picothea** [comment]
Will xenohybrids get their race-specific xeno scream back? It got locked behind donators now, which seems bad.

**Comment by Dr-0range** [comment]
Do characters with robotic voiceboxes get access to robotic screams as well?

**Comment by Gandalf2k15** [comment]
> Do characters with robotic voiceboxes get access to robotic screams as well?

No they currently do not

**Comment by KasparoVy** [comment]
ffuuuuck yes dude that's badass

**Pull request merged**
