### PR TITLE
Ports the USP from Oldbase

### PR DESCRIPTION
**Pull request by zeratino**
## About The Pull Request

Gives the HoS and Sec-Officer the USP handgun from oldbase, each comes with two spare mags.

## Why It's Good For The Game

gun go brrt

## Changelog
:cl:
add: gave hos and sec officer usps
/:cl:

if it's a stupid idea but it works
it's not a stupid idea

### CODE REVIEW

**Comment by zeratino** [comment]
image

my favorite part of this
:ok_hand:

**Comment by YakumoChen** [comment]
Would be a major balance change. The codebase has already moved *heavily* away from crew-armed ballistics.

**Comment by SpaceVampire** [comment]
Yeah. It was already causing balance issues on the old base. This is really not needed.

**Comment by MLGTASTICa** [comment]
The USP was not a  issue on oldbase. What was a issue on old base was the stunbaton , and it still remains a issue on here too. Ballistics still have a trade off and the USP is clearly inferior to the disabler in most ways since it only has 14 shots , while disabler has 25.

**Comment by YakumoChen** [comment]
The USP can bypass through Reflection and the disabler doesn't keep two field reloads on hand

**Comment by zeratino** [comment]
> The USP can bypass through Reflection and the disabler doesn't keep two field reloads on hand

okay so i wanna point out that yeah, the usp has two reloads on hand, but as far as i've checked, there isn't a way to print out new ammo (at least for rubbers) in the first place, so i'm just leaving that up for people to add that in if they want to

i'm almost certain that there was discussion in the air about security moving away from lasers, at least, according to ironhawk, the GA who's working on sec policy or smth

**Comment by YakumoChen** [comment]
That would be a bit weird since Nanotrasen is all laser tech and the syndicate is all ballistic, but also TG has been removing ballistics the station can obtain pretty consistently.

That would really fuck with the balance of Traitor, etc as well because a lot of syndicate armor and the double sword are designed to counter the usual supply of weapons sec has.

**Comment by RatFromTheJungle** [comment]
> That would be a bit weird since Nanotrasen is all laser tech and the syndicate is all ballistic, but also TG has been removing ballistics the station can obtain pretty consistently.
 
every step away from tg lore is a step in the right direction, balance change is questionable because most traitor gear was balanced with shotguns in mind aswell

**Comment by YakumoChen** [comment]
> with shotguns in mind as well

Uh, since when? TG is actively removing the availability of shotguns right now so i would say its absolutely not the case. The shotgun is almost explicitly the counter to most traitor gear, in fact.

**Comment by RatFromTheJungle** [comment]
> 
> 
> > with shotguns in mind as well
> 
> Uh, since when? TG is actively removing the availability of shotguns right now so i would say its absolutely not the case. The shotgun is almost explicitly the counter to most traitor gear, in fact.

did they go back and comment out all the bullet armor they gave traitor items?

**Comment by BrotherHangyul** [comment]
Next person to say syndicate ballistics nt lasers gets a foot up their ass.

**Comment by YakumoChen** [comment]
It's lasers moreso. We have stuff like Reflection on well-known syndicate items made to counter laser weaponry. Ballistics go right through that, and shotguns are almost always seen as the counter to someone with reflective gear.

**Comment by YakumoChen** [comment]
Lore be damned, the game is _balanced_ around "NT lasers, Syndicate Ballistics"

**Comment by hugmeorelse** [comment]
@YakumoChen 

Please note we are not going to follow tg balancing strictly. We have different goals and emphasis when it comes to combat. We actually have an interest in going heavier on ballistics. I'll leave this up to @Azarak and @Gandalf2k15 both to decide, especially if we need any retweaks and balancing to go with this.

**Comment by Zenitheevee** [comment]
hmmm...
I mean, Once its in it probably wouldn't be hard to do testing and work the mags into seclathe, or... If you wanna go back to Oldbase... 3 usps and 6 usp rubber mags in the sectech.
Though, if i'm being honest, making refills gated behind cargo and a vendor, While definitely... *A* way to balance, I'd probably suggest something along hte line of 9mm rubber bullet boxes in security/goodies instead. You already have the magazines, so you should be expected to keep and maintain them.

**Comment by Gandalf2k15** [comment]
I'm not a fan of the USP, and we'll be reworking security soon enough anyhow. For now, hold off on this.

**Pull request closed without merging**
