### PR TITLE
Lowers stasis bed surgery efficiency by 5%

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Title

## Why It's Good For The Game

Nobody uses the damn operating tables, stasis beds are too strong. This just leads to 4 brain surgeries in one big open room in medical which is pretty LRP. Stasis beds need a little more tuning than just this, but it's a start.

## Changelog
:cl:
balance: lowers stasis bed efficiency by 5%
/:cl:

### CODE REVIEW

**Comment by Owai-Seek** [comment]
Surgery tables are for optional surgeries, stasis beds are so people don't actually die.

Making the surgery success chance lower doesn't promote any RP, it'll just make it so it takes longer for people to get fixed, and taken out of medbay.

**Comment by davidchan13** [comment]
Seems like a remap is in order if we want this to be more RP friendly, people are still going to use these because they are accessible for surgery (and rightly should be.)

Trauma Ward/Treatment Center is basically the emergency room for Medical, the exam rooms are effectively worthless mechanically and the only RP that happens in them is ERP. If you're trying to promote RP then cosmetic details like privacy curtains would make more sense than just nerfing an item being used as intended (for life saving procedures) until the alternative is used isn't accomplishing it.

**Comment by chesse20** [comment]
bruh just bring back cloning so we can keep medbay for rp and just use cyro pods to actually heal and cloning to actually revive rest is just for rp

**Comment by atakiya** [comment]
> 
> 
> bruh just bring back cloning so we can keep medbay for rp and just use cyro pods to actually heal and cloning to actually revive rest is just for rp

Cloning's been in for a month now... #151

**Comment by Gandalf2k15** [comment]
Hello, I don't think we require this. If you can think of a more intuitive way to change medbay, do so.

**Pull request closed without merging**
