### PR TITLE
Sensitive Snout Negative Quirk!

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request

Adds the Sensitive Snout quirk, which upon being booped, will cause someone with this trait to be knocked to the floor and take stamina damage. 

Edit: Wearing gasmasks and other protective face gear will prevent the boop from hurting, but boops hurt a lot more now.
Exacts Stats:
Maskless Boops do 30 stamina damage, and knock you down for 2 seconds.
Cost of the perk is -2, and it's a negative perk.

## Why It's Good For The Game

It's good for the game, because it adds more flavour, and comedic moments to the oft forgotten snout-booping mechanic. Also, it lets sharks canonically get floored by getting booped in the snoot.

## Changelog
:cl:
add: Added the Sensitive Snout quirk, for all you suffering sharks out there.
/:cl:

### CODE REVIEW

**Comment by NotRanged** [comment]
Nice PR :)

**Comment by GoldenAlpharex** [comment]
>When you don't bother writing literally anything in the Pull request

**Comment by Cheshify** [comment]
IM FIXING IT

**Comment by Cheshify** [comment]
> > When you don't bother writing literally anything in the Pull request

Alrgiht, I fixed it. Just had a 5-iq moment and pressed the "Make This PR" before I actually wrote anything down.

**Comment by SpaceVampire** [comment]
This really is just free points.
Given that you can both extra protect from the downsides of it.
Along with it not even being all that bad if it happens.

**Comment by YakumoChen** [comment]
Make it a neutral quirk

An extremely niche quirk based around a "oft unused" emote is on the same negative as disliking pineapples.

**Comment by Cheshify** [comment]
> Make it a neutral quirk
> 
> An extremely niche quirk based around a "oft unused" emote is on the same negative as disliking pineapples.

I don't think being able to be floored by anyone for a second with nothing but their bare hands is a neutral quirk. As well as 20 flat stamina damage per boop.

**Comment by YakumoChen** [comment]
You said yourself nobody does this emote. There's not even combat potential in it and even if there was that would assume they knew you had the quirk beforehand.

**Comment by YakumoChen** [comment]
Negative quirks are for traits that have wholly debilitating effects on your ability to play the game (like giving you strong medical needs or handicaps) or have severe mood debuffs

The only trait even remotely close to this is 'bad touch', which involves the most used emote in the game _and_ is _only_ worth one point.

**Comment by CameronWoof** [comment]
Agreed with Chen, this should be a neutral quirk. You could even axe the stamina damage at that point.

**Comment by NotRanged** [comment]
Nah, put it at 2 points and let the powergamers complain all they want

**Comment by Cheshify** [comment]
> Negative quirks are for traits that have wholly debilitating effects on your ability to play the game (like giving you strong medical needs or handicaps) or have severe mood debuffs
> 
> The only trait even remotely close to this is 'bad touch', which involves the most used emote in the game _and_ is _only_ worth one point.

no

**Comment by SpaceVampire** [comment]
Chen is completely correct.
There is no actual downside to this, its just a little funny thing.
Its going to just be two free points.
It should be a natural trait.

**Comment by CameronWoof** [comment]
Consider that knowing someone has this trait and using it as an antagonist to floor them would be an immediate issue.

**Comment by NotRanged** [comment]
2 points is half of the average positive trait, which provide **_huge_** powergaming benefits like:
- 'eat slightly faster' (4 pts)
- 'make your pray popup to admins slightly more blue' (4 pts)
- 'get slightly less drunk from alcohol' (4 pts)
- 'reduce time to climb table by 0.4 seconds' (8 points lol)

what the fuck people lmao

you guys are also bouncing between 'this is free trait points with no downsides' and 'this will let antags stun you and is too powerful :((('

I think this is fine as is, 2 points isn't a lot, the majority of positive traits are impactless, and if you're such a massive powergaming fuck that the fear of an antag booping you on the nose makes you not want to pick something that fits your species, then **_just fucking don't_**. Or wear something over your snout.

**Comment by YakumoChen** [comment]
The majority of positive traits have little impact explicitly because that is the design of the system. If a trait had good combat benefits people would always take it.

On the other hand, negative traits are always impactful by design both for "challenge" and for the reason those positive traits should require investment.

A stun requiring a niche emote and foreknowledge of said emote,and also requires the victims face is uncovered, is exactly along the lines of existing *neutral* traits. 

Its not likely to see combat use anyway because getting the jump on someone by booping them would probably break a combat etiquette on skyrat.

**Comment by Cheshify** [comment]
I won't be making any changes until a maintainer looks at this and says change it, merges it, or denies it.

**Comment by SpaceVampire** [comment]
> I think this is fine as is, 2 points isn't a lot, the majority of positive traits are impactless, and if you're such a massive powergaming fuck that the fear of an antag booping you on the nose makes you not want to pick something that fits your species, then **_just fucking don't_**. Or wear something over your snout.

I feel like you don't understand the claim being made at all for that bit of it. The powergaming part is TAKING the trait on everything, due to the fact that it would just be free points. Two points is also twice as much as the Bad Touch trait, which is a far more common scenario then a nose boop, and can't be blocked.

**Review by Gandalf2k15 — APPROVED** [review]
As far as I can tell this is a decent quirk, 2 points isn't very much at all. I don't have an issue with it as it does caus negative effects to being booped on the nose which happens a lot, which, could, eventually be used against your character. I'm happy with this being merged.

**Pull request merged**
