### PR TITLE
[NONMODULAR] Prevents randomly created humans from spawning with vox hair (Attempt 2)

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Attempt 2 because I pressed the wrong fucking button when trying to update the other PR and frankly I'm too lazy to find out how to fix whatever the hell I did there so I'm just gonna make a new branch

Title
ZERO EFFECT ON ANYTHING BUT RANDOMLY CREATED HUMANS, YOU STILL CAN USE THE DAMN CHARACTER CUSTOMIZATION AND HAIRCUTTING TOOLS

## How This Contributes To The Skyrat Roleplay Experience
No more hair sprites floating off their heads. Vox sprites really, REALLY dont fit non-vox.

## Changelog

:cl:
fix: Randomized Humans will no longer spawn with Vox hair/facial hair
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
I feel like the more optimised way to do this is by making a vox-less global list and instantiating it once instead of every time, we can't really afford to be clumsy with shit like this, especially on mob creation. So do that. Make a new vox-less global hair list, male and female, and on the initialise(copy it from the current hairstyle global list), remove the vox hair, this way it's only happening once on startup. Micro-optimisations.

**Comment by ghost** [comment]
> I feel like the more optimised way to do this is by making a vox-less global list and instantiating it once instead of every time, we can't really afford to be clumsy with shit like this, especially on mob creation. So do that. Make a new vox-less global hair list, male and female, and on the initialise(copy it from the current hairstyle global list), remove the vox hair, this way it's only happening once on startup. Micro-optimisations.

Makes sense. I was tempted to just remove it from the lists on init but that'd mean that character creation couldnt access it; It never crossed my mind to just... make a new list. I'll get to it.

**Comment by ghost** [comment]
oh
`	!!WARNING!!: changing existing hair information can be VERY hazardous to savefiles,
	to the point where you may completely corrupt a server's savefiles. Please refrain
	from doing this unless you absolutely know what you are doing, and have defined a
	conversion in savefile.dm`

**Comment by ghost** [comment]
Gonna draft this while I sort out how tf to do this without breaking save files 😢

**Comment by ghost** [comment]
I'll come back to this
Maybe
Someday

**Pull request closed without merging**
