### PR TITLE
[NON-MODULAR] Someone complained about non-RP friendly deathsquad names

### PR DESCRIPTION
**Pull request by Draganfrukts**
## About The Pull Request

Changes deathsquad names to be more believable for the setting.

## Why It's Good For The Game

Something about increasing RP quality or something. Also vidya references.

## Changelog
:cl:
tweak: A whole bunch of spiders in a SWAT suit (and others) can no longer be a Deathsquad Trooper.
/:cl:

### CODE REVIEW

**Comment by SpaceVampire** [comment]
Soul, Soulless.

**Comment by GoldenAlpharex** [comment]
Nooooo, don't kill Commander THAT DAMN GRIEFING TRAITOR GEORGE MELONS ;-;

**Comment by YakumoChen** [comment]
Most of the existing names are _also_ references, to MST3000

We put our faith in Blast Hardcheese. Keep the names.

**Comment by Gandalf2k15** [comment]
I don't think we need to change this honestly.

**Pull request closed without merging**
