### PR TITLE
[MIRROR] Resprites SpacePol Uniforms (And accessories) [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/80317
--------------------
## About The Pull Request
Hello ancient sprite how u doin today :)
image

One de-souling later: [Long Scream - Sound Effect - Youtube](https://youtu.be/qWaGVtBEt4g?si=TZ_x6h3MFi1_efau)
image

---
Full and in-depth Changelist since there's a bit of random semi-related digging:
- Removes redundant `/datum/armor/warden_red` and strip_delay from `/obj/item/clothing/head/hats/warden/red` - the armor values were the exact same as those of `/datum/armor/hats_warden`, which it'd inherit anyways alongside the strip_delay
- Removes a comment I left forever ago when I re-did Trek uniforms. I never actually pushed the commit referenced by the comment. It's just been sitting there, lying to anybody who read it. _I know this is 100% unrelated to the PR but it was a comment I left that's a lie. I don't mean to lie D:_
- Gives the Mafia Warden outfit the red hat, to match the red jacket it wears
- Adds an extra pixel to the `spacepol` mask so it actually covers the nose on the side-state
- Resprites `spacepol` uniform
- Removes entirely unused `police` uniform obj icon_state
- Recolors `policehelm` hat to match the new palette
- Tweaks and Recolors `warden_alt` suit to match the new palette and have more consistent shading with the other warden jacket
## Why It's Good For The Game
WOOP WOOP ITS DA SOUNDA DA POLICE (Screenshot is slightly outdated, missing the new buttons, but it's still mostly accurate)
image
image

And since the Warden reuses that hat, his jacket's been tweaked to match it's tweaks. Along with shading adjustments to have less 'banding' as somebody on discord put it (idk spriting terms I assume that I fixed it)
image
## Changelog
:cl:
image: the SpacePol bounty hunters have finally had a new run of Uniforms made, bringing them back to the forefront of enforcement fashion! Wardens will find their Police Jackets/Hats have been updated match SpacePol's new look as well.
fix: fixed the Mafia Warden having a hat that didn't match his jacket, and fixed SpacePol masks not covering the nose
/:cl:

### CODE REVIEW

**Comment by vinylspiders** [comment]
This will need a digi refit

**Comment by ghost** [comment]
> This will need a digi refit

~~I reused the pants on other TgSec outfits, you can get away with just cutting one of our digi versions of those at the waist, recoloring the legs, then pasting it in place below the belt~~
Scratch that, skyrat hasn't updated the TgSec outfits for digi in a long while

**Comment by ghost** [comment]
[spacepol_digi.zip](https://github.com/Skyrat-SS13/Skyrat-tg/files/13713929/spacepol_digi.zip)
Can't send .dmi files over github so I zipped it
image
image

**Comment by vinylspiders** [comment]
> [spacepol_digi.zip](https://github.com/Skyrat-SS13/Skyrat-tg/files/13713929/spacepol_digi.zip) Can't send .dmi files over github so I zipped it image image

Thanks! Added it

**Review by vinylspiders — APPROVED** [review]

**Pull request merged**
