### PR TITLE
[Modular] Removes a defaced Poster.

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request

Removes the Dogborg poster.

## How This Contributes To The Skyrat Roleplay Experience

The Poster references content that is no longer in the base (SecBorgs).

## Changelog

:cl: Cursor
del: Removed the Defaced Valeborg Advertisement.
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
I personally don't see why we should have to remove it. The poster can still be a subtle and/or funny nod to something that once existed, and could drum up an interesting conversation.

**Comment by theselfish** [comment]
> I personally don't see why we should have to remove it. The poster can still be a subtle and/or funny nod to something that once existed, and could drum up an interesting conversation.

It also makes some users uncomfortable, but it was thought that 'The Poster references content that is no longer in the base (SecBorgs).' was a more solid argument.

**Comment by YakumoChen** [comment]
its a good reminder why we have them gone

**Comment by theselfish** [comment]
I should also add that @thestubborn asked @Zonespace27 and they couldn't even tell what the poster _was_.

**Comment by Stonetear** [comment]
I know this isn't a democacy but I vote no.  I think Vale is a cool borg, and this is one of the posters I snip down to hang in robotics when I see it.

**Comment by theselfish** [comment]
> I know this isn't a democacy but I vote no. I think Vale is a cool borg, and this is one of the posters I snip down to hang in robotics when I see it.

You're right. This isn't a democracy.

**Comment by jjpark-kb** [comment]
we can have references to things that are no longer here.

**Pull request closed without merging**
