### PR TITLE
[MODULAR] Changes to *hiss1, adds *roar1 and *gnarl1

### PR DESCRIPTION
**Pull request by desertmote**
## About The Pull Request

I think it would be fun for non-alien species who are similar or have the actual xenomorph tongue to be able to imitate their emotes.

## How This Contributes To The Skyrat Roleplay Experience

Xeno person/tongue can make xeno sound.

## Changelog

:cl:
code: Allows the xenomorph emotes to be imitated, if conditions are met.
/:cl:

### CODE REVIEW

**Comment by EerieDream** [comment]
Sulfur roarsn't.

**Comment by tf-4** [comment]
Not a fan of that audio at all tbh

**Comment by desertmote** [comment]
> Not a fan of that audio at all tbh

its a sound every species could realistically make :>

**Comment by tf-4** [comment]
Didn't say it wasn't. It's practically cartoonish, a fairly low-quality clip with a bunch of fuzz, and will just lead to people running around spamming it. Zero interest from me.

**Comment by desertmote** [comment]
Just a xenohybrid PR now.

**Pull request closed without merging**
