### PR TITLE
[MIRROR] On monkey day, you can play as a monkey roundstart.

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/55838
--------------------
:cl: Qustinnus
add: On monkey day you can now play as monkey
/:cl:

return to monke on monke day

### CODE REVIEW

**Comment by EvilCrimsonWitch** [comment]
Yes. Please.

**Comment by KasparoVy** [comment]
Lmao amazing.

**Comment by Azarak** [comment]
nope im disabling this. it'll be a day of headaches, bugs and people going LRP because monkey meme.. we cant have nice things in skyrat

**Comment by KasparoVy** [comment]
Booo, why you gotta have our best interests at heart! 🐵👌🏼

**Pull request merged**
