### PR TITLE
[MIRROR] Lets vehicle abilties actually be removed

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/70151
--------------------

## About The Pull Request
Love when I try to remove abilities and someone only added a add proc 

This code is tested

### CODE REVIEW

**Comment by Tastyfish** [comment]
What, how and why is this touching one of our maps?

**Comment by Paxilmaniac** [comment]
That is an excellent question that I don't think I can answer

**Comment by Paxilmaniac** [comment]
Diffs show that... nothing changed? I guess it's fine?

**Comment by Tastyfish** [comment]
> Diffs show that... nothing changed? I guess it's fine?

Fixed

**Pull request merged**
