### PR TITLE
Cleans our Floor aesthetics module, re-sorting it and updating all the newer TG floors to our new palette

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Title

No changes to normal tiles

The downside: textured tiles are redundant, as by default all our floors had that texture

The upside: now all the new tiles actually match ours. No more glaring white cubes in medical.
(Old screenshot, these will appear textured now - the POINT is that its the same color)
image

## How This Contributes To The Skyrat Roleplay Experience
Cleaner and more matching sprites, rejoice

## Changelog

:cl:
imageadd: Updated floor tile overrides to include all of TG's newer tiles, so they now match ours
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
I really appreciate the effort, however the main reason I wanted to keep the slightly textured floors as a default is that /tg/'s textured floors are *too* textured for my taste, and the untextured metal floors make them look like plastic instead. Metallic flooring always has these kinds of notches in them to give you some grip, otherwise you'd constantly slip.

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
Just requesting some changes until we can have a longer discussion on it together.

**Comment by Gandalf2k15** [comment]
Seconding what Golden said, please keep the current style until TG removes plastic flooring.

**Comment by ghost** [comment]
~~honestly in agreement just wanted to see if it was a me thing or an everyone thing~~

I'll see if I cant flip it around so the textured tiles are the textureless ones

**Comment by ghost** [comment]
done 😎

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
There seems to be a few textures that were reverted to an older aesthetic, mind making sure that's not the case? Mainly talking of the bronze floors, the 80's floor, stuff like that.

**Comment by ghost** [comment]
> There seems to be a few textures that were reverted to an older aesthetic, mind making sure that's not the case? Mainly talking of the bronze floors, the 80's floor, stuff like that.

the bronze floor we actually didnt have a sprite change for, so I didnt have anything to replace the TG version with; though I got one now :crab: makes sense for a _filled floor to just be filled anyways

**Comment by ghost** [comment]
eh

**Comment by ghost** [comment]
I Hate Floors

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
