### PR TITLE
[Modular] Interdyne now has its own, unique techweb

### PR DESCRIPTION
**Pull request by Stalkeros2**
## About The Pull Request
Interdyne now has its own, independent, fully functional techweb and science equipment, independent (x2) from the station. ~~Getting cool screenshots brb.~~ They're in the proof of testing thingy.

## How This Contributes To The Skyrat Roleplay Experience
I wanted to write something cool here but I forgot what but I think it's obvious that less policy wrangling is a pretty good thing and stuff, among people now being able to engage in friendly scientific arms races without having to worry about other people getting mad at Interdyne doing science without doing experiments ig.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
Doing exactly that because I forgot to make screenshots the first time brb.  

Interdyne server console sees Interdyne servers only.

image

Point generation's perfectly functional.

image

Interdyne servers also show up if you have the interdyne network thingy. Station can see them too, among their own, but there's literally nothing I can do about that it's le code inheritance issue thing.

image

</details>

## Changelog

:cl: Stalkeros
add: Interdyne techweb, independent from the station's.
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
Fuck I forgot to change the PR's name.

**Comment by GoldenAlpharex** [comment]
My man, this is a feature, not a refactor.

**Comment by Elli-Skala** [comment]
Of course not allowed by policy but
If a ninja wanting to steel the server rnd server
Could they come here to do it instead?

**Comment by Stalkeros2** [comment]
> Of course not allowed by policy but 
If a ninja wanting to steel the server rnd server 
Could they come here to do it instead?

Yeah, servers're the same everywhere, with the exception of techwebs. And, that is also one of the things I can't do much about.

**Comment by Stalkeros2** [comment]
Waiting for https://github.com/tgstation/tgstation/pull/72944 to happen as it'll make this way easier.
It's all done and functional tho feel free to merge at any moment.

**Pull request closed without merging**
