### PR TITLE
[SEMI-MODULAR] Blindfold HUDs

### PR DESCRIPTION
**Pull request by softcerv**
## About The Pull Request
Adds in Blindfold huds, obtainable as reskins of the eyepatch huds. They mechanically function the same as the eyepatch huds and provide no extra form of protection or seeing impairment. There is also a non-hud version as a loadout item.

**_These are not actual blindfolds, they do not apply actual blindness or function as blindfolds in any way. The choice to make them into blindfolds is a purely visual one._**

In addition, reskinning code has been changed to accommodate for glasses that have swapable icon states. 

## Ingame Screenshots
image
image

**Non-HUD version**
image
image
image
image

**HUD version with Science HUD**
image
image
image
image

## How This Contributes To The Skyrat Roleplay Experience
Having more cosmetic items is good because it allows players more freedom to express their characters.

## Changelog

:cl:
add: adds in blindfold HUDs, functioning as reskins of the eyepatch HUDs
imageadd: added in icons for blindfold HUDs
code: changes reskinning code to allow for glasses with swapable icons to be reskinned.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
I... Really don't understand how you can have a heads-up display when you can't see. Like, that's kind-of counter-intuitive and defeats part of the purpose behind being blind in the first place.

**Comment by theselfish** [comment]
> I... Really don't understand how you can have a heads-up display when you can't see. Like, that's kind-of counter-intuitive and defeats part of the purpose behind being blind in the first place.

Most of the jobs being listed you can't be blind anyway.
I assume these are basically....
Like, everything being recorded back to you by the blindfold.

**Comment by softcerv** [comment]
> I... Really don't understand how you can have a heads-up display when you can't see. Like, that's kind-of counter-intuitive and defeats part of the purpose behind being blind in the first place.

These are effectively fake blindfolds, I stated such in the PR description.
"They mechanically function the same as the eyepatch huds and provide no extra form of protection or seeing impairment"

**Comment by theselfish** [comment]
I'd make these separate items if they don't apply the blindness effect.

As, not only should they *maybe* do that. The Eyepatch huds have no flash protection.

**Comment by desertmote** [comment]
now add the 2b outfit ;)

**Comment by softcerv** [comment]
> now add the 2b outfit ;)

wysi ;)

**Comment by softcerv** [comment]
> I'd make these separate items if they don't apply the blindness effect.
> 
> As, not only should they _maybe_ do that. The Eyepatch huds have no flash protection.

I have these as reskins of the eyepatch HUDs because I want to avoid loadout and crafting bloat. They mechanically function the same too.

**Comment by theselfish** [comment]
> > I'd make these separate items if they don't apply the blindness effect.
> > As, not only should they _maybe_ do that. The Eyepatch huds have no flash protection.
> 
> I have these as reskins of the eyepatch HUDs because I want to avoid loadout and crafting bloat. They mechanically function the same too.

It'd be weird for someone to be flashed with both of their eyes covered.

**Comment by Iamgoofball** [comment]
It would be really funny if these still blinded you but provided the heads up display icons anyways on the same triggers as the sound effects lmfao

**Comment by softcerv** [comment]
> It would be really funny if these still blinded you but provided the heads up display icons anyways on the same triggers as the sound effects lmfao

I could make a subtype that does this as a admin spawn item sometime later

**Comment by softcerv** [comment]
> > > I'd make these separate items if they don't apply the blindness effect.
> > > As, not only should they _maybe_ do that. The Eyepatch huds have no flash protection.
> > 
> > 
> > I have these as reskins of the eyepatch HUDs because I want to avoid loadout and crafting bloat. They mechanically function the same too.
> 
> It'd be weird for someone to be flashed with both of their eyes covered.

fake blindfolds are already a thing here, so I think it makes sense to have the fake blindfold huds as a thing.

**Pull request merged**
