### PR TITLE
[MIRROR] Stunbatons can now only be used during Red Alerts [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/73492
--------------------
## About The Pull Request
This prevents stunbatons being turned on to full stun mode if the station is not in a red alert emergency.

## Why It's Good For The Game

The decision to limit the use of stunbatons in TGStation to red alert emergencies is due to the general degradation of the melee combat design space in the game. The stunbaton's ability to stun and knock down opponents with ease has made it the go-to weapon for many players, leading to a lack of diversity in melee combat strategies.

This over-reliance on stunbatons has made other melee weapons, such as knives or clubs, obsolete in many situations. This not only limits player choice but also reduces the overall challenge and fun of melee combat in the game.

By restricting the use of stunbatons to red alert emergencies, players are encouraged to explore other melee weapons and develop new strategies, making the game more engaging and challenging. It also ensures that the use of stunbatons is reserved for critical situations, making combat encounters more meaningful and immersive.

## Changelog

:cl: oranges
add: Stunbatons now require a red alert to activate stun mode
/:cl:

### CODE REVIEW

**Review by lessthnthree — APPROVED** [review]

**Comment by Razurath** [comment]
So we're taking away Security's ability to respond non-lethally to a threat with a weapon, encouraging them to go with more lethal means to take people down if they get caught in a melee and can't use their disabler?

**Comment by Segalowitz** [comment]
Pick a direction you want to go with and go with it, please...

**Comment by dawsonkeyes** [comment]
> So we're taking away Security's ability to respond non-lethally to a threat with a weapon, encouraging them to go with more lethal means to take people down if they get caught in a melee and can't use their disabler?

### Yes.

**Comment by BubbleTrroubles** [comment]
A new age begins.

**Comment by ApplePlastic** [comment]
WTF is this

**Comment by DuffCreeper** [comment]
Yeah no this needs to be tuned for Skyrat big time

**Comment by HoodMilk** [comment]
The age of murder sec begins now

**Comment by Siefer21** [comment]
now the only stun option in melee is fists on non-red alert. Put your dukes up sec, beat those criminals to stam crit 🤣 yea this merge is wild even from upstream

**Comment by Zonespace27** [comment]
Dubiously based PR

**Comment by DuffCreeper** [comment]
Alright so I just checked, these are the batons that require **RED ALERT** to be used
image

**Comment by Zonespace27** [comment]
https://github.com/tgstation/tgstation/commit/8e5625918c4d90b73eb035e98418adf14021b7e2

**Comment by Lauwma** [comment]
You guys just mindlessly merged a troll PR do you even verify before merging...?

**Comment by tf-4** [comment]
counterpoint it's funny

**Comment by Iamgoofball** [comment]
@Lauwma owned

**Pull request merged**
