### PR TITLE
Database revision revert

### PR DESCRIPTION
**Pull request by Gandalf2k15**
It reverts database code

### CODE REVIEW

**Comment by axietheaxolotl** [comment]
🤨

**Comment by chizzyyyy** [comment]
What does this even do?

**Comment by GoldenAlpharex** [comment]
> What does this even do?

Basically reverts some telemetry stuff that the server didn't like.

**Comment by Gandalf2k15** [comment]
Fuck

**Comment by Gandalf2k15** [comment]
if this isn't fixed by now, I give up

**Comment by GoldenAlpharex** [comment]
We still haven't made it work so I'll re-open the PR.

**Comment by GoldenAlpharex** [comment]
Just so it's less annoying when doing test-merges.

**Comment by ORCACommander** [comment]
*table Flip*

**Pull request closed without merging**
