### PR TITLE
Organic interface fix

### PR DESCRIPTION
**Pull request by GemInee**
## About The Pull Request
Restored content of files with interface icons
for additional slots in the inventory.

Cleaned up organic interface vending machine's contents

## Changelog

:cl:
add: Added icons for additional slots in the inventory.
/:cl:

### CODE REVIEW

**Comment by Lamella-0587** [comment]
Don't merge yet, we need to fix some stuff

**Comment by Lamella-0587** [comment]
don't merge yet, need to fix maps too.

**Comment by Lamella-0587** [comment]
stuff done, can be merged

**Comment by Lamella-0587** [comment]
NO, NOT, FUCK, PREFS, FUCK!

**Comment by ORCACommander** [comment]
update your master to sklyrat master then merge your master into this. that should clear up the massive amount of extra commits

**Comment by Lamella-0587** [comment]
NO, WAIT, FUCK, I WANTED TO REMOVE CHANGES, NO THE MAP

**Comment by Lamella-0587** [comment]
fuck you, github. we're closing the pr if we don't figure out what happened

**Pull request closed without merging**
