### PR TITLE
Removes the .32, for being the same thing as the .34

### PR DESCRIPTION
**Pull request by RatFromTheJungle**
## About The Pull Request

what it says on the tin, the same bullet, used by two different guns, for no real reason, with literally the same stats, and it was bugging me.
image
image

## How This Contributes To The Skyrat Roleplay Experience

Players won't really notice,
## Changelog

:cl:
code: Removed, or replaced all instances of .32, with .34, as they are both, literally, the same bullet.
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
guncode and its consequences

**Comment by RatFromTheJungle** [comment]
i blame the russians for this one, because it seems the p90 was made .32, so in response, they made the wildcat .34 for being crew available, despite, no stats being changed

**Comment by Stalkeros2** [comment]
> i blame the russians for this one, because it seems the p90 was made .32, so in response, they made the wildcat .34 for being crew available, despite, no stats being changed

Both guns were always .32, but then whoever has decided to make Wildcat .34 for no reason whatsoever.

**Comment by Zonespace27** [comment]
The intention of making CFA weapons have wacky calibers was that their gimmick was "cheap company, cheap guns, expensive, proprietary ammo" but it seems the gimmicks that the companies had got filed off anyway 🤷

**Comment by Acer202** [comment]
Huh, why not keep the real and prevalent .32acp instead of the wildcat made-up .34?

**Comment by RatFromTheJungle** [comment]
> The intention of making CFA weapons have wacky calibers was that their gimmick was "cheap company, cheap guns, expensive, proprietary ammo" but it seems the gimmicks that the companies had got filed off anyway 🤷

I could trim it back out of the autolathe for the same-effect; if you'd prefer; but there's just two identical calibers, .32 isn't used crewside at all despite being in the lathe, and .34 was used, but wasn't in a lathe with both being identical, it'd be no bother to just take it back out of the lathe, though

**Review by tf-4 — APPROVED** [review]

**Pull request merged**
