### PR TITLE
Jukebox changes [SEMI-MODULAR]

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Refactors the jukebox to use the legacy sound system which was nice and echolike. Couple fixes here and there too.

## Why It's Good For The Game

Get those jams goin' eh?

## Changelog
:cl:
refactor: Changed the jukebox to use the legacy sound system, so it echos and stuff.
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
I'd have to hear the difference to put my finger down on this

**Comment by Gandalf2k15** [comment]
HOLD- let's make this work through internet sounds.

**Comment by Gandalf2k15** [comment]
nevermind we cant.

**Comment by Gandalf2k15** [comment]
Updated.

**Pull request merged**
