### PR TITLE
Bitrunner den for voidraptor (FOR #23865)

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

Adds a bitrunner den to voidraptor.

## How This Contributes To The Skyrat Roleplay Experience

We need a gamer girl containment room away from the rest of the station in cargo.

## Proof of Testing

image

## Changelog

:cl:
fix: fixes voidraptor not having a bitrunner den :)
/:cl:

### CODE REVIEW

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
needs to not require going through mining to enter as bitrunners don't have mining access

**Comment by kittysmooch** [comment]
we can go.... even filthier

**Comment by CandleJaxx** [comment]
needs a sign to say 'stay away, gamers at play' on the outside door /j

**Review by vinylspiders — APPROVED** [review]
Approving on behalf of the maptainers, who have said it looks good!

**Pull request merged**
