### PR TITLE
[MODULAR] Metastation Prison Rework 

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request

Community voted for perma changes, I deliver perma changes.
image

### What I've changed:
-Metastation perma now has a larger, more functional kitchen!
-Decals have been updated to match security's aesthetic
-Nanotrasen has found the budget to give the garden a single auto-tray
-Cells have been made slightly less nasty, larger restroom/showers to make up for this, mirror included
-New card games to help forget you're in here forever
-Motivational Nanotrasen:tm: approved posters to help remind you that you're in here forever
-Made sure garden actually has the tools they need
-Tom has been moved so he doesn't immediately eat a wire and die
-Why didn't we have Nanotrasen approved soap in the showers? That feels like an oversight, and has been changed.
newperma

## Why It's Good For The Game

Community requested Metastation perma changes, and these are relatively simple, but give the prisoners some more to do, and actually let them cook. Expect Deltastation to be next.

## Changelog
:cl:
add: Gave Metastation Perma some well-needed renovations
/:cl:

### CODE REVIEW

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
image
For now, delete the area marked in green and rebuild it completely, it really needs improvement and it's best to cut it out now and just rebuild.
Change the green area to have toilets and showers separate. It'd be better as a toilet stall and then shower cubicles.
In transfers/execution area, remove the decals under the reinforced windows and make it plating, then make sure wiring runs underneath it so those windows are electrified.

**Comment by Cheshify** [comment]
Updates have been made as requested, as few as some more QOL stuff.
-Added a little serving counter
-Added some more backup internals in storage, as well as inflatable wall box
-Added a loaded library
-Shower's been separated into shower cubicles and a bathroom

newperma

**Comment by H0gberg** [comment]
Very Pawsome rework, good job!

**Review by KathrinBailey — APPROVED** [review]
Now I'm done with work...
_It'll do._

Much better than the average map PR so I'm glad, well done.

**Pull request merged**
