### PR TITLE
Interlink banners no longer heal you

### PR DESCRIPTION
**Pull request by Hardly3D**
## About The Pull Request
This PR fixes an oversight where the command banners next to blueshield and NTC's office in interlink had the ability to heal you

## How This Contributes To The Skyrat Roleplay Experience
Letting command have access to a healing banner is an awful idea, and is more of an oversight if anything. These banners should only be obtainable through adminbus.

## Changelog

:cl: Hardly
fix: fixed an issue where interlink's command banners could heal people
/:cl:

### CODE REVIEW

**Review by GoldenAlpharex — APPROVED** [review]
Wait what? How did you even figure this out? You madlad. Nice catch.

**Review by Jolly-66 — APPROVED** [review]
Nerfing dumb stuff because it shouldn't exist gets my pass

**Comment by GuiltyNeko** [comment]
Banners not healing people should be the default state, honestly? That's kinda fuckin' silly.

**Comment by Iamgoofball** [comment]
you used the nations version

**Pull request merged**
