### PR TITLE
Removes the three improvised guns we added, because the purpose of two of them is served by an already existing improvised gun, and the third is just stupid.

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

The improvised shotgun, the improvised bolt action, and the improvised .38 revolver rifle are all being removed because:

image

THIS BABY exists!

The maint musket, the pipe gun, whatever you call it, it already fills the exact purpose of both the improvised rifle and shotgun we added.

"But wait!" I hear you thinking, "Sure the maint musket fires 12g, but what about the 7.62 part from the improvised rifle?"

Here is an incredible fact for you, if you use a wrench on the maint musket, it'll let you fire 7.62 rounds out of it rather than 12g!

Now, what about the improvised revolver rifle?

Like I said, it's just stupid. If you look at what the code comments were, it was literally just made as a craftable detective's revolver that didn't fit in bags. Bruh.

If you want a detective's revolver, rob the detective or buy one from cargo.

## How This Contributes To The Skyrat Roleplay Experience

These guns were either pointlessly stupid, or stupidly pointless, if you're in the mood for shooting people with improvised weapons get yourself a pipe gun and shoot some 12 guage or 7.62 at them. If you're in the mood for a detective's revolver, congrats buddy we've got either cargo, or the many option, robbing the detective for his gun!

## Proof of Testing

I could get screenshots of it not being in the crafting menu probably, I'll get a screenshot of it compiling once compile maps tells me all the ruins that had these guns in them for some reason.

## Changelog

:cl:
del: All three of the skyrat added improvised guns, the shotgun, the rifle, and the revolving rifle, have all been removed. If you want to shoot someone with 12 guage or 7.62, make the maint musket, it accepts both of those!
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
I'd rather just remove the TG one, honestly, the pipegun has always felt out of place, especially with it's 'missfire' mechanics (and the nonsense damage modifier)

**Comment by Draganfrukts** [comment]
> I'd rather just remove the TG one, honestly, the pipegun has always felt out of place, especially with it's 'missfire' mechanics (and the nonsense damage modifier)

Hard agree with this.
With gun cargo and licenses, there is absolutely ZERO REASON to make the pipe gun. Even in a pinch, it's better to do something else like making a plasma glass spear because this thing is useless on so many levels that it's embarrassing anyone thinks it's anywhere near worth it to make it.

**Comment by optimumtact** [comment]
> I'd rather just remove the TG one, honestly, the pipegun has always felt out of place, especially with it's 'missfire' mechanics (and the nonsense damage modifier)

Get thineself fucketh

**Comment by RatFromTheJungle** [comment]
> > I'd rather just remove the TG one, honestly, the pipegun has always felt out of place, especially with it's 'missfire' mechanics (and the nonsense damage modifier)
> 
> Get thineself fucketh

image

**Comment by capsaicinz** [comment]
yeah okay this is cool
honestly any subtraction from the literal scrap metal heap of guns we already have

**Comment by dawsonkeyes** [comment]
can we reduce the random shit on the tg pipe rifle or make the regal version not require a book to craft

**Review by GoldenAlpharex — APPROVED** [review]
We'll make the pipegun better once the freeze is over.

**Pull request merged**
