### PR TITLE
Fixing a few greyscale colors

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
## About The Pull Request
There's been a few kitsunes around lately and the fact the colors were off really threw me off, so I decided to fix that. :)

The ears were the worst, the inner fur was just incredibly dark for no good reason.

## How This Contributes To The Skyrat Roleplay Experience
It makes it look a lot better, much easier. It really help with whiter colors, as you can see here.

image

Compared to before:
image

## Changelog

:cl: GoldenAlpharex
fix: Fixed the greyscale gradient on the Tamamo Kitsune Tails and the inner part of the Fox ears, to be easier to work with color-wise.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
could we get a before and after for reference?

**Comment by RatFromTheJungle** [comment]
can you read this to me in italics

**Comment by GoldenAlpharex** [comment]
> could we get a before and after for reference?

Oh yeah, I forgot to add the before, hold on.

**Comment by GoldenAlpharex** [comment]
Done.

**Review by Funce — APPROVED** [review]

**Comment by GoldenAlpharex** [comment]
It's approved, I'll merge it so I can update the server for the next round.

**Comment by Funce** [comment]
_point_ self merging self merging!

**Pull request merged**
