### PR TITLE
[NON-MODULAR][QoL] Sterile Masks no longer hide your identity.

### PR DESCRIPTION
**Pull request by softcerv**
## About The Pull Request
Changes it so that the sterile masks don't hide your identity while worn. This has no appearance on how they look.

## How This Contributes To The Skyrat Roleplay Experience
image
I am making this PR downstream here first, because it helps solve what is a Skyrat RP issue.

## Changelog

:cl:
qol: sterile masks no longer hide your face.

### CODE REVIEW

**Comment by YakumoChen** [comment]
didn't we have a feature at one point where you could just disable the identity-hiding of masks? Could we just port that instead of adding a bunch of inconsistencies with what masks hide your face? We shouldn't mess with mechanics for stuff like this.

**Comment by softcerv** [comment]
> didn't we have a feature at one point where you could just disable the identity-hiding of masks? Could we just port that instead of adding a bunch of inconsistencies with what masks hide your face? We shouldn't mess with mechanics for stuff like this.

if someone ports that over I'd be happy to close this PR, but until then, I'm keeping it open.

**Comment by YakumoChen** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13581
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13713

Pr I was thinking of

**Comment by MassacreDemigirl** [comment]
Its sad because Its one of my go to identity hiders because its far subtler then walking around with a gasmask

**Review by GoldenAlpharex — APPROVED** [review]
I'm fine with this.

**Comment by GoldenAlpharex** [comment]
Although, if you could do what the other PRs said, it'd be very nice.

**Comment by softcerv** [comment]
> Although, if you could do what the other PRs said, it'd be very nice.

Yeah, I wouldn't mind looking into that as a project sometime. If I get around to it, I'll make sure to revert this PR

**Comment by YakumoChen** [comment]
formally against this now as I've found the mask does make a very good way to hide your identity without something more obviously suspicious like a bandana or a full face mask.

Used it very successfully as a doctor.

**Pull request closed without merging**
