### PR TITLE
[MODULAR i think] removes cme

### PR DESCRIPTION
**Pull request by NullDagaf**
fuck it
literally everyone agrees it's bad

also i said i think because the only thing that it touches outside of modularskyrat was removing a //SKYRAT EDIT in anomaly thingies

### CODE REVIEW

**Comment by NullDagaf** [comment]
"too complex to resolve in web editor" my ass

**Comment by NullDagaf** [comment]
okay for real though how the fuck am i to fix conflicts IF I DONT ENEN KNOW WHAT'S CONFLICTING

**Comment by Gandalf2k15** [comment]
Yeah no this is not how you do anything like this.

**Comment by NullDagaf** [comment]
> Yeah no this is not how you do anything like this.

oh well 🤡

**Pull request closed without merging**
