### PR TITLE
quenches the thirst for blood

### PR DESCRIPTION
**Pull request by Gandalf2k15**
image

### CODE REVIEW

**Comment by CandleJaxx** [comment]
can i get a poggers in chat please

**Comment by Lauwma** [comment]
image

**Comment by IgiariValkyr** [comment]
I do suggest leaving the blue stuff in as an alternative for people that _want_ to wear it.

**Comment by thestubborn** [comment]
please tell me all the peacekeeper wardrope additions got backported to the secdrobe

**Comment by FlamingLily** [comment]
Honestly? I prefer bluesec. A lot. It matches the vibe of what we've been doing. We should keep redsec as it is, an optional thing to buy from cargo.

**Comment by Sethnov** [comment]
What's the point of armydyne now with red security back? might as well return to lasers than ballistics. ballistics don't match red security, it feels out of place.

**Pull request closed without merging**
