### PR TITLE
sm cascade sea removal

### PR DESCRIPTION
**Pull request by jjpark-kb**
:cl:
del: removed sm cascade sea
/:cl:

### CODE REVIEW

**Review by GoldenAlpharex — APPROVED** [review]
Looks good, let's wait for CI to finish, just to be safe.

**Comment by scrubs2009** [comment]
"I no like round with this. I remove now"

**Comment by jjpark-kb** [comment]
> "I no like round with this. I remove now"

I was the one who added it to skyrat, I will remove it!

**Comment by scrubs2009** [comment]
> > "I no like round with this. I remove now"
> 
> I was the one who added it to skyrat, I will remove it!

But it's so damn cool!! Just turn down the speed it spreads at to like 1/5th so we can still have rounds.

**Pull request merged**
