### PR TITLE
[MODULAR] [CO-OP MODE] Adds A Few New Clothes

### PR DESCRIPTION
**Pull request by Nerev4r**
## About The Pull Request
PR description, code and basically all the groundwork by @Smol42, the incredible and lovely original author.
Adds few clothing items, nothing more or less. Each item of this PR is recolourable.

Special thanks to Nerev4r, OrionTheFox for the advice. 🙏 
<details>
<summary>Capes</summary>

Non-toggleable ^ Two different units v Toggleable

</details>

- Resprited capes, originally made by Imaginos16 (GH).

<details>
<summary>Face Scarf</summary>

</details>

- Added colourable face scarf, toggleable.
 _(please, contact me if you are aware of its original author.)_

<details>
<summary>Coats & Sweaters</summary>

</details>

- Adds two colourable sweater units with/without heart pattern.
- Resprited existing winter coat.

<details>
<summary>Maid Uniform</summary>

</details>

- Resprited four assets of existing maid uniform.

<details>
<summary>Bows</summary>

</details>

- Adds four new bows, made by bowlofsoup4ik (GH)

<details>
<summary>Skirts</summary>

image
Long Skirt

image
Medium Skirt

</details>

- Adds two new skirts by Smol42

## Changelog

:cl: Smol42, OrionTheFox
add: Added a few new clothing items.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Is that maid outfit colourable? The colors are a little bright

Also, take it upstream?

**Comment by Nerev4r** [comment]
The upstream that doesn't have a loadout.

**Comment by YakumoChen** [comment]
They have costume vendors and could probably handle something like GAGS maid outfit

**Comment by kittysmooch** [comment]
reiterating my carnal desire for a neck slot bow

image

**Review by vinylspiders — APPROVED** [review]
Looks good to me!

**Comment by HoodMilk** [comment]
Finally, a long skirt.

**Comment by Nerev4r** [comment]
image
Look how good that shit looks goddamn.

**Comment by W4rd3nn** [comment]
deez r hot but why did u pick the ugliest colors to show them off with

**Comment by comrade-dagmar** [comment]
hair bows and skirts just in time for halloween costuming, you get a kissy and a sticker

**Pull request merged**
