### PR TITLE
[NON-MODULAR] Restores Atmos mixing tank contents to intended Skyrat Values 

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request

Restores https://github.com/Skyrat-SS13/Skyrat-tg/pull/7443 that was undone by an upstream file split.

## How This Contributes To The Skyrat Roleplay Experience

TG values are good for 40 minutes of chaos and captains who instantly call shuttles the moment they can, but on a fast atmos (non-zas) this is depleted in minutes when there are any breaches on maps / newbie atmos techs going hard with volume pumps. 

## Changelog

:cl:

fix: restores an edit on a split file uptream that made atmos survive longer rounds

/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
Why not just re-add gas miners to the maps. I know that adds maintaining time but its arguably a better fix.

**Comment by nevimer** [comment]
> Why not just re-add gas miners to the maps. I know that adds maintaining time but its arguably a better fix.

I'd love to do that, but it's an uphill battle. Maintainers won't allow it as-is despite most atmos mains wanting it.

**Comment by gonenoculer5** [comment]
> > Why not just re-add gas miners to the maps. I know that adds maintaining time but its arguably a better fix.
> 
> I'd love to do that, but it's an uphill battle. Maintainers won't allow it as-is despite most atmos mains wanting it.

@GoldenAlpharex @Gandalf2k15 Why the resistance on gas miners?

**Comment by Gandalf2k15** [comment]
> 

Not maintaining that shit

**Pull request merged**
