### PR TITLE
Adds some new hairstyles

### PR DESCRIPTION
**Pull request by Smol42**
## About The Pull Request

 I ordered a hot dog today and while i was half way through, i tasted what was unmistakably a hair. I immediately took the sandwich out of my mouth and pulled the hair out. It was, without a doubt, a female hair. It was long and kind of blonde. I imagined the head of hair it came from, what shampoo and conditioners were used on it. A marvelous scalp if I had ever seen one. I took the strand of hair and wrapped, I mean, added some new hairstyles with a rather soft grayscale to the wonderful space station 13 build by the name of Skyrat.

## Proof of Testing

<details>
<summary>Screenshots/Videos 
(Includes unique hairstyles, without mirrored, shorter, longer length versions  for some of them.)
</summary>

  ezgif com-gif-maker (5)
ezgif com-gif-maker (4)
ezgif com-gif-maker (3)
ezgif com-gif-maker (2)
ezgif com-gif-maker
ezgif com-gif-maker (1)
ezgif com-gif-maker (21)
ezgif com-gif-maker (20)
ezgif com-gif-maker (19)
ezgif com-gif-maker (18)
ezgif com-gif-maker (17)
ezgif com-gif-maker (16)
ezgif com-gif-maker (15)
ezgif com-gif-maker (14)
ezgif com-gif-maker (13)
ezgif com-gif-maker (12)
ezgif com-gif-maker (11)
ezgif com-gif-maker (10)
ezgif com-gif-maker (9)
ezgif com-gif-maker (8)
ezgif com-gif-maker (7)
ezgif com-gif-maker (6)
</details>

## Changelog

:cl: Smol42
add: Added some new hairstyles
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
I love you.

**Comment by desertmote** [comment]
not a big fan of the checkerboard texture

**Comment by Awers855** [comment]
Those are absolutely great! Looking forward to see them in game.

**Review by GoldenAlpharex — APPROVED** [review]
I'm fine with these. The different kind of pattern in shading here can also represent a different way for the hair to be done (like, curly or wavy hair, for instance), so I've got nothing against this.

**Pull request merged**
