### PR TITLE
Latejoining AI now syncs unsynced borgs & All (non-posi) latejoining borgs are synced to the AI.

### PR DESCRIPTION
**Pull request by Zonespace27**
## About The Pull Request
Any AI who latejoins will automatically sync all unsynced borgs who joined before it will be forcibly synced to it. Emagged borgs and borgs synced to another AI are exempt.

After some maint discussion, all latejoining borgs (not posi-brained borgs) are now synced to the AI should there be one. Malfs get priority.

## How This Contributes To The Skyrat Roleplay Experience
I have seen many a borg announce to security/command/the station that the AI's malf because they can hear :b frequency. Also, this gives malfs more room for things to do, since they'll have more ~~helper minions~~ synced borgs to do their bidding
## Changelog

:cl:
balance: Latejoining AI will automatically sync all unsynced, un-emagged borgs to it
balance: Latejoining borgs now automatically sync to an AI
/:cl:

### CODE REVIEW

**Comment by desertmote** [comment]
this didnt go anywhere last time it was attempted to be added, hoping this time itll make it though!

**Comment by GuiltyNeko** [comment]
Can interdyne spawn on middle icebox, and if so, would this sync borgs there? Because if so, very very bad.

**Comment by Zonespace27** [comment]
> Can interdyne spawn on middle icebox, and if so, would this sync borgs there? Because if so, very very bad.

Icebox my beloathed

**Comment by Zonespace27** [comment]
Resolved

**Comment by GuiltyNeko** [comment]
I'd now complain about borgs hiding on the lower level to avoid syncing when an AI joins, but that is its own punishment, and there is nothing more to say.

**Comment by Zergspower** [comment]
> I'd now complain about borgs hiding on the lower level to avoid syncing when an AI joins, but that is its own punishment, and there is nothing more to say.

They'd have no way to know an AI is joining

**Comment by Zergspower** [comment]
Also it's a complete skill issue if the AI doesnt check that honestly

**Comment by GuiltyNeko** [comment]
> They'd have no way to know an AI is joining

This is why I said it's its own punishment, is because they would have to live down there to avoid syncing, which is, again, its own punishment.

**Comment by Zergspower** [comment]
this doesnt affect roundstart borgs when an AI is present yes? We dont force sync or allow the AI to have them force synced to begin with.

**Pull request merged**
