### PR TITLE
Actually for real de-cocks the cargo shuttles (#17786 alternative)

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

Does the same thing as #17786 but instead of just removing the cockpit it redesigns the shuttles to fit their new cockpit-less look.

Coincidentally, closes #17786 

On top of that, ALSO removes the skyrat edit in cargo code about the cockpits.

## How This Contributes To The Skyrat Roleplay Experience

The cockpit serves little purpose now other than to make cargo lose crates and orders and should have been removed when I remapped these shuttles however long ago.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

image
  
</details>

## Changelog

:cl:
del: The cockpit on cargo shuttles has been removed, rejoice for you will no longer have orders mysteriously lost under the chairs.
/:cl:

### CODE REVIEW

**Comment by RimiNosha** [comment]
Boxshuttle... I dunno, I think I prefer the other PR. Flying, featureless boxes don't exactly match our existing fancy (not sprited) shuttles.

**Comment by Paxilmaniac** [comment]
The cargo shuttle is an automated cargo hauler a flying box is exactly what it'd be. It doesn't match the other shuttles because the other shuttles are built with living people on board mid flight in mind. As the person who MADE the other shuttles I'm fairly certain I know what I'm doing.

**Comment by GuiltyNeko** [comment]
You know... is it technically possible to make the crates only spawn inside those big decal boxes? Because that'd be really cool. Not at all necessary, but very very cool.

**Comment by Paxilmaniac** [comment]
Could probably do something with like helpers as the crate spawn locations but its some code stuff im not gonna bother with

**Comment by sqnztb** [comment]
I'm surprised another maptainer hasn't shown up here to complain about the lack of the cockpits. Shame, shame.

For the record, I'm good with either.

**Comment by Jolly-66** [comment]
How do I Git mute someone

**Comment by dawsonkeyes** [comment]
For a brick, it flies pretty good!

use the angled titanium corner walls though, at least give it some curve, the nodiagonals do look bland

**Comment by GoldenAlpharex** [comment]
Unless the screenshot isn't accurate, is there any particular reason why you're not using the wall variant that has triangular walls in the corners, for the outside at the front of the shuttle? It'd look a lot better, I feel like.

**Comment by Paxilmaniac** [comment]
> Unless the screenshot isn't accurate, is there any particular reason why you're not using the wall variant that has triangular walls in the corners, for the outside at the front of the shuttle? It'd look a lot better, I feel like.

The screenshot isn't accurate I forgor to use the diagonal ones before and just didnt update the screenshot after fixing it

**Review by Jolly-66 — APPROVED** [review]
I'll miss my cockpit.

Also this is arguably better since its symmetrical.

**Pull request merged**
