### PR TITLE
[MODULAR] removes objectives

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request

This PR replaces all objectives except manually added ones with CREATE AN OPPOSING FORCE APPLICATION

I made this PR at work and in 10 minutes with 3 hours of sleep and four coffees. Let's see. 

## How This Contributes To The Skyrat Roleplay Experience

This removes the greentext mindset, and makes you have to do coherent things. 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
dreamseeker_VzeXoIRCeH

</details>

## Changelog

:cl:
code: all random objs are now instructions to make an opfor
/:cl:

### CODE REVIEW

**Comment by Higgin** [comment]
Legendary. Honestly, ship as-is, though is there a way to get it to not duplicate the line for every random objective it replaces (without making every individual antag only have one objective, at which point, you could just copy-paste this in for similar effort?)

Looks a little jank having three lines of "make an opfor" though, for antags that previously got like eight objectives (looking at you, ninja) maybe it helps get the point across with emphasis.

**Comment by YakumoChen** [comment]
This will either make traitor into a free for all since they have no direction to go in even if they lack a good gimmick

Or it will lead to traitors not knowing what to do

Reliance on admins to get objectives approved is a deal breaker and forces antags to either "sit and wait" potentially all round (admins aren't obligated to reply to opfor requests) or do their gimmick anyway and hope they don't get bwoinked in the process

Neither of these are good options

**Comment by Zonespace27** [comment]
This PR is gonna need some maintainer talk before it'll be considered

**Comment by Stonetear** [comment]
> forces antags to either "sit and wait" potentially all round (admins aren't obligated to reply to opfor requests) or do their gimmick anyway and hope they don't get bwoinked in the process

The problem with ambitions was that there was basically no antag stuff until at least the 35 minute mark.  Once I had an admin repeatedly deny my ambitions with no explanation besides " it's not enough RP" until I just broke at the hour mark and used one of the templates.

The OPFOR system is much better since there's a chat function.  You can actually ask _why_ your objectives are being denied.  Of course, an admin still has to answer it, but I've found the OPFOR system gets much faster responses than ambitions did.

As a policy document, perhaps admins should give examples of objectives that will _always_ be approved, letting players start antagging while they wait.

**Comment by RatFromTheJungle** [comment]
> This will either make traitor into a free for all since they have no direction to go in even if they lack a good gimmick

it already is because they just vaguely 'follow their objectives', using it as an excuse to get in as many fights as possible, or elsewise go 'stealth' ala, never interact with anyone, ever
> Or it will lead to traitors not knowing what to do

see: above
> Reliance on admins to get objectives approved is a deal breaker and forces antags to either "sit and wait" potentially all round (admins aren't obligated to reply to opfor requests) or do their gimmick anyway and hope they don't get bwoinked in the process

It's not a deal breaker unless you feel like you won't be able to write a convincing opfor, it wouldn't even be that hard to encourage staff to keep ontop of them; the only reason they don't at the moment, is because each round usually has 3-7 antags, and 3 opfors to do something very-loud, and everyone who gets told 'no' doomposts about the fact they can't do X, or Z that shift, like it was promised to them while we've still a horde of mechanics-first antags.
> Neither of these are good options

disagree

**Comment by nevimer** [comment]
> This will either make traitor into a free for all since they have no direction to go in even if they lack a good gimmick
> 
> Or it will lead to traitors not knowing what to do
> 
> Reliance on admins to get objectives approved is a deal breaker and forces antags to either "sit and wait" potentially all round (admins aren't obligated to reply to opfor requests) or do their gimmick anyway and hope they don't get bwoinked in the process
> 
> Neither of these are good options

The objective is to make an opfor. Traitors are not forced to do so, they are just told to do as as their objective. What they do with that prompt is up to them, but it's the implication they should do so.

**Comment by Iamgoofball** [comment]
before making antagonists rely entirely on every player on your server being a good writer with strong initiative and creativity, it would be best to make sure players are good writers with strong initiative and creativity

i totally understand the idea behind the PR, but this is putting a lot of the burden on players creativity wise and i'm not entirely convinced every player can handle that burden effectively based on the outcome of ambitions originally

some players operate significantly better when someone else gives them a goal and reason for that goal, others do not

**Comment by Higgin** [comment]
> this is putting a lot of the burden on players creativity wise and i'm not entirely convinced every player can handle that burden effectively based on the outcome of ambitions originally

no, they can't, but what you get from giving them a license to not try in the form of our current random objectives isn't worth saving.

If what was desired was only as much as mechanical challenges against people upgeared to do Something with absolutely zero content as to what, or why, we've got that - and it's tedious, and behind so many guardrails already that if that's what you were here for, primarily, it makes the case for instead going to somewhere like /tg/ where that version of the game is more what everyone's after.

for the players who aren't comfortable just doing their own thing, honestly, I'd hope making the opfor will serve as a much better in to getting some coaching. Creativity and initiative are muscles - it should help to have some support when trying to engage them and no cop out from scrutiny when you're not.

**Comment by TetrakoHateThis** [comment]
Ah, finally. The push to make antags actually use some degree of creativity and consider RP as a factor before they're granted their tot toys. No longer will we see an endless string of repeated gimmicks solely focused on being as efficient a killer as possible solely to engage in one-man wars vs security, and perhaps we'll see people now needing to conjure up somewhat charismatic ideas in their antagonism beyond "fuck you kill this random person for the contrived reason of we said so".

**Comment by Zonespace27** [comment]
We've decided to move forward with https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110 instead.

**Comment by nevimer** [comment]
based

**Pull request closed without merging**
