### PR TITLE
[😔] Adds a felinid scream

### PR DESCRIPTION
**Pull request by desertmote**
## About The Pull Request

It's a scream, I clipped it from a vtuber.

https://user-images.githubusercontent.com/77534246/130156016-5719854e-ef26-403a-ae2c-40f0cb58474c.mp4

## Why It's Good For The Game

It's better than the cat scream, maybe.

## Changelog
:cl:
add: Felinid scream
/:cl:

### CODE REVIEW

**Comment by desertmote** [comment]
i really just made this to see if _anyone_ wants it.

**Comment by GoldenAlpharex** [comment]
If you're going to add a scream, you should probably showcase it in your PR so we know if we want it or not.

**Comment by desertmote** [comment]
> If you're going to add a scream, you should probably showcase it in your PR so we know if we want it or not.

Good idea, it's added to the main topic. Personally would just download the .ogg from the changes, but I get it.

**Comment by GoldenAlpharex** [comment]
After having listened to it, I'm not very confident I really want to hear that on a regular basis, nor does it really sound like a humanoid making that noise.

**Comment by desertmote** [comment]
> After having listened to it, I'm not very confident I really want to hear that on a regular basis, nor does it really sound like a humanoid making that noise.

I don't mind at all, I really just whipped this up. But that critique hits harder on the actual Cat Scream we have, just saying.

Little edit: **It's also not default for felinids**. It has to be chosen in the menu, always.

**Comment by GoldenAlpharex** [comment]
> > After having listened to it, I'm not very confident I really want to hear that on a regular basis, nor does it really sound like a humanoid making that noise.
> 
> I don't mind at all, I really just whipped this up. But that critique hits harder on the actual Cat Scream we have, just saying.
> 
> Little edit: **It's also not default for felinids**. It has to be chosen in the menu, always.

I mean, I didn't mean it in a rude way. It's just that I don't think that it sounds like a sound someone would make realistically. It doesn't really fit in the atmosphere, it sounds like someone stepped on a comically small cat. I'm not defending the Cat scream, I just think that we'd need a proper replacement that sounds more believable.

**Comment by thestubborn** [comment]
why not
https://www.youtube.com/watch?v=yGztvJt5dRI
for felind screams?

**Comment by bluetshirtguy** [comment]
It's not bad but sounds like it's straight out of a microphone :b

**Comment by unit0016** [comment]
> It's not bad but sounds like it's straight out of a microphone :b

And you can hear the background music still.

**Comment by YakumoChen** [comment]
Make the male scream a Tom scream 

Also I thought the cat yowl was already the felinid scream?

**Pull request closed without merging**
