### PR TITLE
[MIRROR] adds structure spawners for electrified grilles, adds greps for some fulltile window spawners [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/69528
--------------------
Lets mappers find missing cables easier.

Also went through and replaced some windows that weren't using the proper directional spawners. (did these manually so waiting for mapdif bot to confirm it's all correct.)

```
"\w+" = \(\n[^)]*?/obj/structure/grille,\n[^)]*?/obj/structure/cable,\n[^)]*?/area/.+\)
```
```
"\w+" = \(\n[^)]*?/obj/structure/cable,\n[^)]*?/obj/structure/grille,\n[^)]*?/area/.+\)
```
```
"\w+" = \(\n[^)]*?/obj/structure/grille,\n[^)]*?/obj/structure/window[/\w]*?fulltile,\n[^)]*?/area/.+\)
```
```
"\w+" = \(\n[^)]*?/obj/structure/grille,\n[^)]*?/obj/structure/window/reinforced/fulltile/ice,\n[^)]*?/area/.+\)
```
```
"\w+" = \(\n[^)]*?/obj/structure/grille,\n[^)]*?/obj/structure/window/reinforced/plasma/plastitanium,\n[^)]*?/area/.+\)
```

### CODE REVIEW

**Comment by ShizCalev** [comment]
♥

**Comment by Jolly-66** [comment]
You're killing me Shiz

**Comment by Paxilmaniac** [comment]
what happened here

**Comment by Paxilmaniac** [comment]
naw bruh really about to make me go manually fix all that

**Comment by Jolly-66** [comment]
> naw bruh really about to make me go manually fix all that

Gotta go maptain, maptainer!

**Comment by Paxilmaniac** [comment]
Thank god for this because I was tired of people not using the window spawners

**Pull request merged**
