### PR TITLE
[MANUAL MIRROR] Return to Tiny: Reworks heights to use filters, allows spacemen to have varying heights (#72344)

### PR DESCRIPTION
**Pull request by tf-4**
https://github.com/tgstation/tgstation/pull/72344

:cl: Melbert, That REALLY Good Soda Flavor, FatFat, AndreyGusev
add: Spacemen can now have varying height. (Admin only for now) add: Dwarfs are now slightly shorter, but look way better.
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
This is the first PR in a string of PRs that depend on it in one way or another so this would be good to get merged ASAP.

**Comment by Paxilmaniac** [comment]
tf4 solving my problems for me, yippie!

**Comment by tf-4** [comment]
I am aware that there's a visual bug after reattaching limbs related to this but we need to merge it. It's holding up a number of other PRs.

**Review by GoldenAlpharex — APPROVED** [review]
Should hopefully be fine now.

**Pull request merged**
