### PR TITLE
Revert "[MIRROR] Moves help menu to end, fixes Hotkeys Help [MDB IGNORE]" because TGS is throwing a hissy fit

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
Reverts Skyrat-SS13/Skyrat-tg#12425

We just wanna updoot man

### CODE REVIEW

**Comment by Tastyfish** [comment]
The heck is TGS doin?

**Comment by Zonespace27** [comment]
TGS fucking dying over in the corner

**Comment by Tastyfish** [comment]
Oh right probably a test merge conflict with #12473. carry on

**Comment by Gandalf2k15** [comment]
Temp merging so we can update this fucking server.

**Comment by Tastyfish** [comment]
@Gandalf2k15 Fixed in https://github.com/tgstation/tgstation/pull/65870 which our bot didn't pick up for some reason.

**Pull request merged**
