### PR TITLE
[FIXED] [MOSTLY MODULAR] Alt titles

### PR DESCRIPTION
**Pull request by FlamingLily**
- [x] Make alt titles
- [x] On IDs/PDAs
- [x] On the crew manifest and records
- [x] Arrival announcements
- [x] Department head announcements
- [x] Sec IDs
- [x] Manifest sorting
- [x] Crew Monitor
- [x] Remove working comments, clean up code, modularise if possible
- [ ] Explorer corps titles, clown title.

## Reported Testmerge Issues
All fixed! For now! ohgodpleasejustwork!

## About The Pull Request
Ports everyone's favorite! Alternate titles to your jobs! Select them on the occupation preferences screen, they'll display on:
Your ID
Your PDA
The Crew manifest
Records systems
Automated announcements (NOT "Captain on deck!" (yet))
The crew monitor

PR is open for suggestions for more alt titles.

NOTE: Security officers who are assigned to a department and choose an alt title do not get their department appended to their ID. They still get their accesses, though.

## Why It's Good For The Game
Adds flavour, a more than welcome oldbase feature that has multiple times been requested to be returned.

## Changelog
:cl:
add: Alternate Job Titles for every job!
add: Framework for adding more titles in the future.
/:cl:

### CODE REVIEW

**Comment by FlamingLily** [comment]
> 
> 
> You currently have a negative Fix/Feature pull request delta of -32. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

Do I look like someone who cares what god thinks?

**Comment by Owai-Seek** [comment]
Personally, I'm not a fan of alternative titles, it's already pretty difficult to contact the people you need to contact, and with alternate titles, that probability goes even lower. You're basically forced to memorize three three different titles for most jobs and it's a bit overwhelming.

**Comment by thestubborn** [comment]
you should add differing prisoner security classes (supermax and so on), because thats what i was gonna do >:)

**Comment by thestubborn** [comment]
> 
> 
> Personally, I'm not a fan of alternative titles, it's already pretty difficult to contact the people you need to contact, and with alternate titles, that probability goes even lower. You're basically forced to memorize three three different titles for most jobs and it's a bit overwhelming.

the very hard issue of logically deducing ranks, yes
what ones specifically do you have issue with?

**Comment by thestubborn** [comment]
oh yeah, also

would there be a way to limit alt titles in jobs?
like if there's one butcher there cant be another and so on

**Comment by FlamingLily** [comment]
> 
> 
> oh yeah, also
> 
> would there be a way to limit alt titles in jobs?
> like if there's one butcher there cant be another and so on

That would be hard, and frankly not really necessary. Your alt title doesn't mean you get to shrug off work if you're needed. An engine technician can't be like "oh I only work with the engine, no need for me to help fix this breach" just like a butcher can't say "I don't need to cook, I'm just the butcher."

**Comment by LeonY24** [comment]
imagine being a chad Operative instead of virgin Security Officer..........

**Comment by Arctaisia** [comment]
Very nice! I have a few ideas for Secoff, Sergeant, Scientist, Virologist, Geneticist, and Chemist alt-titles, though I do recommend looking towards Vorecode for a few good ones, as well as Cit's, though I feel Virgo/Chomp has quite a few good ones.

**Comment by FlamingLily** [comment]
> 
> 
> Very nice! I have a few ideas for Secoff, Sergeant, Scientist, Virologist, Geneticist, and Chemist alt-titles, though I do recommend looking towards Vorecode for a few good ones, as well as Cit's, though I feel Virgo/Chomp has quite a few good ones.

Hell yeah, feel free to share them!

I want an absolutely inane amount of title options. Like, so god damn many.

**Comment by Gandalf2k15** [comment]
I'm not a fan of this considering the last time we did it most things still read their stock title.

**Comment by NullDagaf** [comment]
Good to see old features being ported.
On that note, would enjoy if the "explorer" title got replaced with a "mining foreman" or similar, considering we don't have these. Many people, myself included, found themselves using that title as a "haha, i'm not miner therefore time to kill fauna".

**Comment by thestubborn** [comment]
> 
> 
> Good to see old features being ported.
> On that note, would enjoy if the "explorer" title got replaced with a "mining foreman" or similar, considering we don't have these. Many people, myself included, found themselves using that title as a "haha, i'm not miner therefore time to kill fauna".

see that's the thing, like I said earlier, imagine if all the shaft miners were foremen
even if, like lilly says "Your alt title doesn't mean you get to shrug off work if you're needed", it fucks with my brain

**Comment by FlamingLily** [comment]
> 
> 
> Good to see old features being ported.
> On that note, would enjoy if the "explorer" title got replaced with a "mining foreman" or similar, considering we don't have these. Many people, myself included, found themselves using that title as a "haha, i'm not miner therefore time to kill fauna".

I'm definitely not going to give miners any titles that imply them not mining, but, "foreman" doesn't really make sense, because it implies a superior.

**Comment by NullDagaf** [comment]
> I'm definitely not going to give miners any titles that imply them not mining, but, "foreman" doesn't really make sense, because it implies a superior.

Mostly spitballing here, as I have no clue what other title to give to a miner, and didn't want to leave them title-less when every other job is supposed to have one. "Hunter" would fit VERY much, but no one would mine then, "explorer" runs into the same issue.

**Comment by drizzlemutt** [comment]
Would it be possible to have alt titles for Research Director as well? Not all Directors are in same in my eyes, as some can be leaders in the respective fields of research. It could allow for a more defined experience, instead of the broad stroke the RD title implies. 

Stuff like Silicon Administrator, Senior Researcher, Biorobotics Director, or Anomalous Materials Officer. 
 
As a side note, Anomalist and Experimentalist wouldn't be out of place for the scientist titles.

**Comment by Owai-Seek** [comment]
> > Personally, I'm not a fan of alternative titles, it's already pretty difficult to contact the people you need to contact, and with alternate titles, that probability goes even lower. You're basically forced to memorize three three different titles for most jobs and it's a bit overwhelming.
> 
> the very hard issue of logically deducing ranks, yes
> what ones specifically do you have issue with?

I thought I posted this yesterday but I must not have ever hit the comment button.

I'm not opposed to alt titles as a concept, I just find separating a single jobs title into three to be very disruptive to actual gameplay, because it's linked to the PDA system. So if you're searching for a janitor to call, you also need to search for, say, a Custodian, or Sanitation Technician. Spread this across every job in the game and now you need to memorize way, -way- too much, just to simply get in contact with people.

I feel like a lot of alt titles should be secondary job slots, or custom titles for assistants, rather than a replacement for the primary job title. IE: Nurse, for trainee medical doctors, much like we have Civil Dispute Officer, for minor crime.

**Comment by SarmentiCampbell** [comment]
> > > Personally, I'm not a fan of alternative titles, it's already pretty difficult to contact the people you need to contact, and with alternate titles, that probability goes even lower. You're basically forced to memorize three three different titles for most jobs and it's a bit overwhelming.
> > 
> > 
> > the very hard issue of logically deducing ranks, yes
> > what ones specifically do you have issue with?
> 
> I thought I posted this yesterday but I must not have ever hit the comment button.
> 
> I'm not opposed to alt titles as a concept, I just find separating a single jobs title into three to be very disruptive to actual gameplay, because it's linked to the PDA system. So if you're searching for a janitor to call, you also need to search for, say, a Custodian, or Sanitation Technician. Spread this across every job in the game and now you need to memorize way, -way- too much, just to simply get in contact with people.
> 
> I feel like a lot of alt titles should be secondary job slots, or custom titles for assistants, rather than a replacement for the primary job title. IE: Nurse, for trainee medical doctors, much like we have Civil Dispute Officer, for minor crime.

I..honestly do not see how that is a problem as you could just call for a janitor via the intercoms. You don't always have to use your PDA despite what you think. custom titles are horrible, even worse if they're only for assistants. As they would obviously be used horribly.

**Comment by Owai-Seek** [comment]
Calling people via intercomms, or common chat, is one of the least effective ways to get someone's attention. Everyone expects people to have some sort of ESP that rings a bell in their head when their job title is called out over common. It just, doesn't work.

**Comment by hugmeorelse** [comment]
I am closing the conversation. This is not a forum to discuss your opinions.

**Comment by hugmeorelse** [comment]
I have unlocked the comment section once more. Remember, this is not a public forum for stating your opinion. Please keep it to technical analysis and critique related to balance, code, and so forth. If you have a legitimate issue, bring it up firmly and politely.

I will give leeway to some words of encouragement, but **I do not want to see Github being used for debates or as a sort of "rally" as we have seen in the past.**

**Comment by alexv-ds** [comment]
You forgot to add an Electrician and Engine Technician for the Station Engineer.

**Comment by FlamingLily** [comment]
> You forgot to add an Electrician and Engine Technician for the Station Engineer.


`/datum/job/station_engineer`

	alt_titles = list("Emergency Damage Control Technician", "Electrician", "Engine Technician", "EVA Technician")

**Comment by Gandalf2k15** [comment]
As far as I can remember, didn't this cause issues with people abandoning their jobs to do whatever they wanted?

**Comment by FlamingLily** [comment]
> As far as I can remember, didn't this cause issues with people abandoning their jobs to do whatever they wanted?

I have heard similar concerns, however, all jobs with this system will get a warning that says "regardless of your title, your job is [real job], please perform that role"

**Comment by NopemanMcHalt** [comment]
> (...)all jobs with this system will get a warning that says "regardless of your title, your job is [real job], please perform that role"

Same thing was present in oldcode. Cannot, however, confirm whenever it did help or not.

**Comment by thestubborn** [comment]
fear me, i am the dreaded idea gremlin

uhhh titles
for warden;
Prison/Brig Governor (its the brit term for warden)
Gaoler
Jailer
for HoS;
Chief of Security
Chief Constable
Sherrif
for CDO;
Parole Officer
for SRG;
Security Enforcer
for blueshield;
Executive Protection Agent 
Personal Protection Specialist
for engineer;
Engineer
for the Lawyer;
Defence Attorney
Public Defender
Barrister
Prosecutor
for Assistant;
Freelancer
VIP/Investor (for donators)
Paroled Inmate/Ex-Convict

**Comment by Gandalf2k15** [comment]
OK. Good to go. People can make additions in other prs.

**Pull request merged**
