### PR TITLE
Fixes VoidRaptor's wacky area mismanagement - aka Granite's eye doesnt twitch anymore

### LINKED ISSUE #17331: Void Raptor missing Bluespace Sender in atmos
Reporting client version: 514.1589

## Round ID:
6889

## Testmerges:
- [Ghost Hotel Update](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16447)
- [Near complete refactor and rework of how forge crafting benches work](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17103)
- [Refactors like all of forge code, improves the functionality of using it like an oven, these two items are unrelated](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17056)
- [Fix/Refactor: MOD tails, tails use defines](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16778)
- [Gives the lavaland ashwalker den the same treatment I gave the icebox one](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17037)
- [Hemophagus: The Hemophage Revamp, Part Two: Blood Surge](https://github.com/Skyrat-SS13/Skyrat-tg/pull/17290)
- [[MDB IGNORE] Updates Departmental Guard icons, sorts files](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16892)
- [NuInterlink, or as I like to call it, the Evac Shuttle now docks at the Interlink](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16043)

## Reproduction: Bluespace Sender missing in atmos. had to spawn one in. put it bottom left of pic
bluespace

### LINKED ISSUE #17387: Brig doors in void raptor are set incorrectly.
## Round ID: 
N/A

## Testmerges:
N/A

## Reproduction:

The north doors in the brig on void raptor have the entrance access requirements, allowing anyone with entrance access to go straight into the security offices. 
dreamseeker_GwOP3obnkX

### LINKED ISSUE #17405: Void raptor missing evidence storage
## Round ID:

N/A

## Testmerges:

N/A

Void raptor does not have anywhere to store evidence, neither secure lockers nor otherwise.

### LINKED ISSUE #17406: Void Raptor missing solitary confinement
## Round ID:

N/A

## Testmerges:

N/A

There is no solitary confinement cell on Void Raptor to put perma inmates

### LINKED ISSUE #17434: Void Raptor Maint Tweaks and Fixes
## Round ID:
6934

## Reproduction:

Abandoned Robotics has extra Package Wrappers and Hand Labelers, the table they are on is partly reinforced.
Starboard Quarter Solars has a reinforced wall jutting out
Feels like theres a LOT of heaters and not enough Pacman units
Theres just.. some extra reinforced walls between the Night Club and the Vacant Office (why..?)
WhyTheseGasPricesSoHighWawa
Reinforced Walls on the south side of the Construction Area, no other reinforced walls on the other sides
Xenobiology Private Maint Room has a (by default) inaccessable curtain (Marked with blue), recommend making the curtains controlled by a button or move the dresser (Marked with red) (Also does that heater need to be there? Maybe make it a Personal Closet?
OhMyLordyLordIsThatABANANA
Theres no Security Warrant Console, woe be any assistants that get a fine and want to use a warrant console

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

I made a mistake and opened the map in SDMM 

A few examples

image
image
image

## How This Contributes To The Skyrat Roleplay Experience

Area management is far more uniform, sorry Janitors you dont own a chunk of maintenance anymore. Jokes aside maintenance is now split properly across the entire map, with department maint zones included to make it easier to find someone with sensors on.

fixes: https://github.com/Skyrat-SS13/Skyrat-tg/issues/17331
fixes: https://github.com/Skyrat-SS13/Skyrat-tg/issues/17387
fixes: https://github.com/Skyrat-SS13/Skyrat-tg/issues/17405
fixes: https://github.com/Skyrat-SS13/Skyrat-tg/issues/17406
fixes: https://github.com/Skyrat-SS13/Skyrat-tg/issues/17434

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image
image
image
image
image

</details>

## Changelog

:cl:Zergspower
fix: Void Raptor - fixes multiple areas across the entire station
fix: Void Raptor - added in the missing Secure evidence room
fix: Void Raptor - added in the missing isolation cell
fix: Void Raptor - Security access now appropriate inside the brig
fix: Void Raptor - fixes various maint room accessibility problems
fix: Void Raptor - missing Bluespace Sender in atmos is one again there
fix: Void Raptor - Unanchored the secure storage tesla's
qol: Void Raptor - balances reinforced Walls and windows throughout the entire map
/:cl:

### CODE REVIEW

**Comment by Zergspower** [comment]
I ended up standardizing all of maints as some were still mapped to departments and so forth as well

**Comment by Jolly-66** [comment]
>OH and i put the fix for: https://github.com/Skyrat-SS13/Skyrat-tg/issues/17331

Change this to: fixes: #17331 so this PR is linked to the issue and will be closed when this PR is merged.

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
You have no idea how hard it is to review these kind of PRs.
Anyway,

<details>
<summary> Few things I noticed </summary>
AI Sat solar controllers are both not given an area, and given the WRONG area.

image

The EVA sheds defines are incorrect. They're only for rooms. Please use a maintenance define for the adjacent hall. This goes for the other side as well.
image

Gross misusage of nearstation.
image

image

Nearstation this dock port so its inline and consistent with the rest of the other ports.
image

This entire side of maint needs to be broken up.
image

Missing nearstation.
image

Maint areas ending like this need to be separated with an airlock.
image

Another "please break this up".
image

As an aside, we **do** have department-based maint defines. I would try to use what isn't used already so you can essentially free up maint defines for other places. If needed, make a define or two.

</details>

**Comment by HoodMilk** [comment]
janitalia will rise

**Comment by Zergspower** [comment]
yeah it was in rough shape area wise even before i expanded it out
<details>
<summary>Feex</summary>
Few things I noticed
AI Sat solar controllers are both not given an area, and given the WRONG area.

image

The EVA sheds defines are incorrect. They're only for rooms. Please use a maintenance define for the adjacent hall. This goes for the other side as well.
image


Gross misusage of nearstation.
image

Nearstation this dock port so its inline and consistent with the rest of the other ports. 
image

This entire side of maint needs to be broken up. 
image

Missing nearstation. 
image

 Maint areas ending like this need to be separated with an airlock.
image

 Another "please break this up".
image
</details>

**Comment by HushTD** [comment]
Seems fine to me, just check if all the APCs are there.

**Comment by Zergspower** [comment]
added in missing isolation
image
added in missing Evidence Storage
image

**Review by Jolly-66 — DISMISSED** [review]
Please update your CL to reflect changes made in this PR.

**Comment by SomeRandomOwl** [comment]
@Zergspower might as well add on #17434 onto this as well as remove the jukebox located [here](https://files.ratchtnet.com/i/c188ca)

i was going to do it myself but noticed this PR

**Comment by SpaceLoveSs13** [comment]
Saw this in some feature requests and my personal request too. Could you add warrant consoles outside brig? All other maps have it and it's a nice useful machine for crew to pay their citations/fine with.

**Comment by Zergspower** [comment]
> Saw this in some feature requests and my personal request too. Could you add warrant consoles outside brig? All other maps have it and it's a nice useful machine for crew to pay their citations/fine with.

Ye already did, i think i twas in the bottom Issue fix

**Comment by SpaceLoveSs13** [comment]
> > Saw this in some feature requests and my personal request too. Could you add warrant consoles outside brig? All other maps have it and it's a nice useful machine for crew to pay their citations/fine with.
> 
> Ye already did, i think i twas in the bottom Issue fix

Ah amazing, thanks a lot.

**Comment by SomeRandomOwl** [comment]
I see you fixed the Rwalls in science but I want to ask why make the RD office also [less secure?](https://files.ratchtnet.com/i/165ab4)

**Review by Paxilmaniac — APPROVED** [review]
Granite said its ok it looks ok to me

**Pull request merged**
