### PR TITLE
[Semi-Modular] OutpostStation's Revengeance

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Remember the last time this was ran? I do.
New map, untethered from /tg/ like ship is. Based on OutpostStation from Unitystation, with some... well, several creative differences. Comes with it's own whiteship, arrivals shuttle, and emergency shuttle. Requires a minimum of 25 players, and should (hopefully) mitigate the problem of everyone being forced into iceboxstation with "I love democracy" moments.
Station:
image
Arrival Shuttle:
image
Emergency Shuttle:
image
Whiteship:
image

## Why It's Good For The Game
Icebox bad, and the people who say otherwise are masochists

## Changelog
:cl:
add: Outpost Station has been brought into the rotation.
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
Glad you finally got around to finishing it, super excited to look at it more closely!

**Comment by Gandalf2k15** [comment]
We can TM this for a few rounds!

**Comment by ghost** [comment]
Issues: 
- some unnamed airlocks around, such as bathrooms and whatnot
- only one set of vents/scrubbers in some large rooms, IE the halls outside cryo. Probably would be best to have more of them.
- lack of tools and equipment in robotics
- no feeding chutes in xenobio
- chemistry lab is very small, perhaps move the morgue and expand it into there?
- morgue has no outside entrance to the hall
- poorly optimized medbay (why so many waiting rooms? why is a surgical room connected to the outside hall - maybe make that into a proper checkup room without surgical beds, for less serious medical stuff?)
- chapel missing altar+vendor
- assorted consoles missing in several rooms (detective/law office for example)
- large, unbroken hallways means that fires/depressurizing are extremely dangerous. At least break them up with firelocks.
- viro lab missing Virus Food Dispenser
- bartender has no access to the service hall
- robotics is zoned improperly as Aft Maints
- tcomms is lacking in atmos, and should PROBABLY start out wired - or at least with easier-to-reach wires instead of hidden under the access tube (also the SMES terminal isnt actually wired)
- on the topic of tcomms, there's no seperate server boxes in this setup..
- grav gen being so close to the SM is a terrible risk in the event of even a tiny delam. it also cuts off tcomms. perhaps reorganize it to be at least a bit further away, or move the SM? consult engineering mains on how to best lay it out tbh

Minor Issues:
- library tidy-up: reorganize the bookshelves, curator room, window to the hallway, proper art gallery
- make sure to keep all named airlocks typed in a similar way (such as cryo being in full caps)
- move the beer nuke from security, give the crew their alcohol ;-;
- random wire jutting off under dorms, leading nowhere
- xenobio doors could probably be reinforced glass ones,like the other stations' chambers
- botany should have the biogen connected directly to the kitchen, considering the chef commonly uses it.
- botany also has no counter to give stuff out to the crew
- vault in prison gives antags a poor time with objectives involving it. perhaps renovate the maints directly below prison to give room for a vault - including space protection so people dont just disassemble it easily? This would also give the prison a nice big commonroom, or give reason to squish it down a bit so the warden gets a real office
- disposals looks backwards: lever on the opposite side of the room, shutter button too. also, no controller for the mass driver itself.
- cargo boarding arm is L O N G. maybe rotate the shuttle 180 degrees so it can be closer to the actual loading zone instead of a big annoying hall?
- as with most places, departures is pretty empty. along with benches and tables, brainstorming d-chat agreed that a statue might be neat.
- shuttle has no engineering room, might be worth cutting medbay/cargo section in half to put it in the back
- might be worth swapping Botany and the Kitchen, so the chef and bartender can interact better
- perhaps move the atmos pipes to the AI sat to be on the catwalk outside (similar to the wires) for aesthetic?
- dont forget to make sure the Meteor Catches around the station look actually connected (obligatory OCD post)
- very unimportant suggestion, maybe make the toxins launch path prettier: use catwalks and lights along it to give it a bit more of a strong look
--Will edit with more issues as found

**Comment by LeChatGuide** [comment]
Issues or minor stuff I found so far :
-The SM setup room is quite cold (enough to hurt), not sure if that's intentional or not . 
-The engi hardsuit storage is in the SM setup room . which mean to get them while the SM is on you either have to go under the emmiters or go around the SM chamber . I think it would be safer and easier to place those in the same room as the late , or in the solar crate storage.
-The arrows on the floor of the HoP line are backward, triggering my autism.
-this is more of an Idea than an issue , but since atmo is so big , it would be neat to add a few pre-made chambers, even better if they are easily customizable (like the ones on Delta , where you can directly access them through a sas)
-On the subject of atmos , adding some layer adapters on the gas chamber's outputs,would be really neat !these make it easier to customize and mix gases

**Comment by KathrinBailey** [comment]
image
dark spot is large as absolute sin
you can literally test this locally and just observe around and catch this.

image
eerrr?

image
doors to maint should be maint doors

image
"cloning lab"

image
needs more sinks, botany is already CBT enough, it really needs more sinks.

image
this bridge is a barren wasteland so vaste you can fit a fallout game in it, there is no need for it to be so needlessly gargantuan whilst also lacking most of the computers bridges usually have.

image
eerrrr what is this?

image
missing emitters
missing plasma canister

image
more missing lights

image
that's a bit _too_ janky, just move the blast doors a tile up.

image
C'mon you can't give the warden a 2x3 office that barely has walls.

image
this is far far far far too big for the blueshield's office, it only needs to be big enough to fit the essentials, not _this_ big.

image
how do you call the shuttle?

image
dark spot in centre

image
you don't need a separate meeting room if your bridge can fit two of them in and still have enough space leftover to function as a bridge.

image
this bar is woefully tiny

image
whilst I approve of having desks you can meet someone at, you have one in the office, which probably should be the one you keep, and another in the bedroom. "Let's take this one-on-one meeting to... the bedroom office."

image
pet park is a neat idea but it doesn't need the hallway surrounding it

image
maint rooms should run along existing rooms and not just be a block surrounded by hallways.
idea of maints should serve the purpose of being fire exits and storage areas as well as being tunnels to escape into if anything goes wrong (think star trek Jefferies tubes but standing instead of crawling)

image
missing many features of janitor.
no water tank
no sink
missing light tube/bear traps/mousetraps and other stuff the janitor usually has

image
nitpick that isn't really a huge issue, but there should be _something_ to mark that there's heavy machinery firing very deadly lasers and maybe you should watch your step lest you summon the OSHA Battleship and OSHA Deathsquad to drop pod in.

image
needs a sink for hygiene

image
gateway room far too empty for it's size, it needs either enough in it to justify its size or to not be that big.

image
missing flashers

image
no genpop lockers

image
after Fermi's pH stuff, this is far too small to do most plumbing in.

image
Way too many lights

image
Tech storage has nothing in it that's worth protecting with rwalls, needs normal walls

image
contrary to the too many rwalls, AI really needs rwalls around the core.

image
this is completely unwired

**Comment by KathrinBailey** [comment]
Blueshield should have the Captain's req access now, not 73.

**Comment by Jureiia** [comment]
Bartender literally cannot access the service hall, because it's behind maintanance and bartenders don't get maintanance access. Also I feel this whole map is flawed on an almost fundamental level with its design. Big is not always better.

**Comment by gummardgumphrey** [comment]
image
CMO can't access the stasis bay lol

**Comment by GoldenAlpharex** [comment]
> image
> CMO can't access the stasis bay lol

CMO's office is also in the middle of everything for some reason, and doesn't even have reinforced walls.

**Comment by gummardgumphrey** [comment]
> 
> 
> > image
> > CMO can't access the stasis bay lol
> 
> CMO's office is also in the middle of everything for some reason, and doesn't even have reinforced walls.

oh and apparently the door remote can't open the stasis bay either

**Comment by GoldenAlpharex** [comment]
I have to point out, all is not negative, I really like the use of decals, it really makes it look a lot more modern. Keep up the good work!

**Comment by misterreporter** [comment]
Here's my quick laundry list:
Geneticist cant access morgue
Genetics lab also needs its usual box of body bags and bottle of mutadone.

**Comment by Jureiia** [comment]
The path between the cargo office room and the mail room is needlessly long, just add another door. Or make the cargo office slightly bigger anad have it connect directly to the mail room. Also so many of the rooms are just boring boxes with little flare or thought put into design

**Comment by FlamingLily** [comment]
There's no gruel trays in perma
There's no intercoms or fire extinguishers, like, **anywhere**

**Comment by unit0016** [comment]
Holy fuck that's a lot of feedback.
Getting on it pronto. All will be adressed.

**Comment by FlamingLily** [comment]
> There's no gruel trays in perma

Actually I just was in metaperma and there were no gruel trays there, either, so I think maybe gruel trays just don't exist anymore.

**Comment by unit0016** [comment]
> The path between the cargo office room and the mail room is needlessly long, just add another door. Or make the cargo office slightly bigger anad have it connect directly to the mail room. Also so many of the rooms are just boring boxes with little flare or thought put into design

Imagine unironically thinking that boxy design is bad in a square tile based videogame.

**Comment by unit0016** [comment]
Updated with all suggestions.

**Comment by sergeirocks100** [comment]
Hello.

I would like to let you know that i'm currently porting this map to /tg/:

s24

Feel free to incorporate any of the improvements i made and will make to the map, this wouldn't be possible without your version of the map, after all:

https://github.com/sergeirocks100/tgstation/tree/OutpostStation

**Comment by Gandalf2k15** [comment]
I'm happy to FM this if you're happy to keep up maintenance on it.

**Pull request merged**
