### PR TITLE
[SEMI-MODULAR] Gives robotics bonesetters, non-medibot health analyzers, and some gauze

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

Title.

Adds 2 bonesetters, 4 stacks of gauze, and 2 "surplus" analyzers that cant be used for medibot assemblies to the robodrobe.

## How This Contributes To The Skyrat Roleplay Experience

As it stands, robo already has to deal with wounds (dislocations) and as such might need something to tell them how to handle them (bonesetters). A whole suite of synth wounds is also going to come from upstream, making this a downright necessity.

Robotics will be taken by surprise by a bunch of new wounds that NOBODY has experienced before. Gauze is universally used and can be a quick treatment option while they figure it out, and analyzers can tell them straight up how to do it.

The analyzers are blacklisted from being used in medibots because I dont want robotics wasting all their analyzers on bots when they really are going to need them for wounds + I dont want to give robo 4 extra medbots at roundstart.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

</details>

## Changelog

:cl:
add: 2 Bonesetters, 4 stacks of gauze, 2 health analyzers that cant be used for medibots, all in the robodrobe
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Why 4 health analyzers? Seems a bit overkill, especially if it's just to spit in their face when they try to use them to make medibots and just can't.

**Comment by trefoils** [comment]
Science can print health analyzers from their lathe. You can print bonesetters from the autolathe. both of these are fairly early research too. This feels a tad unneeded? besides maybe the gauze. Why not given science the ability to print advanced health analyzers instead for the new cyborg wounds

**Comment by nikothedude** [comment]
> Science can print health analyzers from their lathe. You can print bonesetters from the autolathe. both of these are fairly early research too. This feels a tad unneeded? besides maybe the gauze. Why not given science the ability to print advanced health analyzers instead for the new cyborg wounds

As the author of synth wounds, it's in my opinion that jobs who are supposed to treat wounds should have the tools to do so right from the start. Bonesetters and health analyzers, even though available early, aren't immediately available. The autolathe isn't guaranteed to exist either.

**Comment by nikothedude** [comment]
> Why 4 health analyzers? Seems a bit overkill, especially if it's just to spit in their face when they try to use them to make medibots and just can't.

Spitting in their face?? What a weird way to say it

If 4 is overkill I can lower it, I just kinda picked a random number that felt good

**Comment by nikothedude** [comment]
> Science can print health analyzers from their lathe. You can print bonesetters from the autolathe. both of these are fairly early research too. This feels a tad unneeded? besides maybe the gauze. Why not given science the ability to print advanced health analyzers instead for the new cyborg wounds


Also, you're assuming robos KNOW this. It's quite possible a robo might not know they can print them - but it's very likely for a robo to be aware they can just buy one, as it's pretty common for people to check their room's vendor when they try a job.

**Comment by nikothedude** [comment]
All around having a bonesetter and analyzer isnt REALLY important for the simple reason of they can just _print_ them, but in my opinion its best if those things are already in the room they are supposed to be used in.

**Comment by Zergspower** [comment]
would it benefit to instead make a robotics kit like how the syndiebase has?

**Review by lessthnthree — APPROVED** [review]

**Pull request merged**
