### PR TITLE
Revert "[modular] arachne borgs"

### PR DESCRIPTION
**Pull request by axietheaxolotl**
Reverts Skyrat-SS13/Skyrat-tg#16477

[Image Removed]

Author/my own request.

### CODE REVIEW

**Review by Ebin-Halcyon — APPROVED** [review]

**Comment by Zonespace27** [comment]
After discussion with other maintainers, we have come to the agreement to close this PR.

By PRing something to a license-compatible codebase, you as the author (and any co-authors) are giving up the license to fully control your own work. If this was brought up during the original PR, it is possible things may have turned out differently. As it stands, however, we have agreed that removal of content currently being used, for the wishes of an author who has shown nothing but disdain for the codebase, is not in our interests.

**Comment by ChungusGamer666** [comment]
> After discussion with other maintainers, we have come to the agreement to close this PR.
> 
> By PRing something to a license-compatible codebase, you as the author (and any co-authors) are giving up the license to fully control your own work. If this was brought up during the original PR, it is possible things may have turned out differently. As it stands, however, we have agreed that removal of content currently being used, for the wishes of an author who has shown nothing but disdain for the codebase, is not in our interests.

While you are legally allowed to do this, this does not make you morally correct in disrespecting the original author's wishes.

**Comment by GoldenAlpharex** [comment]
> While you are legally allowed to do this, this does not make you morally correct in disrespecting the original author's wishes. If they hate the codebase so much, why use their content huh?

If they want their work to be removed, then they're free to come and do so in a respectful manner. We're not tolerating toxicity in the community, especially if it's their reason for wanting the content they made to be removed.

We don't tolerate toxicity, we're not going to allow it because they're partially responsible for the sprites. That's just genuinely insulting to the community and what it stands for, they're not above our guidelines just because they're a spriter.

**Comment by hugmeorelse** [comment]
This has always been an interesting point of contention. While I do sympathize with the original author, picking and choosing which server, community, or people should be able to use what open source content sets a bad precedent.

The moment we start permitting this as a long-term trend, open source gradually becomes meaningless. Unless people are violating aforementioned licenses on which the content was released, I do not think we should start removing content based on passing whims.

I feel like the only reason why people think this is acceptable is due to the fact that art tends to be more unique and personable. Meanwhile, code can be interchangeable at times if not boilerplate. I mean, would anyone support a programmer that demands that their critical bug fixes be removed from a codebase for personal reasons? I doubt it would gain any traction or attention.

**Comment by hugmeorelse** [comment]
This has always been an interesting point of contention. While I do sympathize with the original author, picking and choosing which server, community, or people are not allowed to use the open source content you made sets a bad precedent going forward. Even though I personally think it's better to ask first due to it being good manners, I do not think there is nothing wrong from making use of open source content that's out there, given proper credit is due and that you are not taking false credit.

**The moment we start permitting this as a long-term trend, open source gradually becomes meaningless.** _Unless people are violating the associated license with the content, I do not think we should start removing content based on passing whims._

I feel like the only reason why people think this is acceptable is due to the fact that art tends to be more unique and personable. Meanwhile, code can be interchangeable at times if not boilerplate. I mean, would anyone support a programmer that demands that their critical bug fixes be removed from a codebase for personal reasons? I doubt it would gain any traction or attention. If anything, it'll be treated with ridicule.

However, even if the artwork of an artist is ubiquitous (This one in question is clearly talented), I don't believe it gives it any claim to be excluded from the principles of open source after it was released open source. Again, it sets a bad precedent going forward, despite my sympathies with the original author. 

**For example, I'm actually spending money currently on a major sprite overhaul which I am helping design.** It will cost me hundreds of dollar at minimum and plenty of my time and others. However, as much as it bothers me to see it possibly get used on servers that did not contribute to its development or are even anti-furry in nature, it would be a spit in the face of every single person that worked on Space Station 13 if I did not release it open source. **We're built on the backs of others after all.**

**Comment by hugmeorelse** [comment]
With that said, @axietheaxolotl, out of respect for you, even if you have little respect for us, I will see if we can make our own suitable replacement. However, please understand we do reserve the right to make use of open source content, just as you do.

**Comment by Draggeru** [comment]
Do people not understand what "open source" means or?

**Pull request closed without merging**
