### PR TITLE
[Modular] Simplistic plastic ID cards for the hardworking masses

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Bit of an aesthetics change, makes the ID cards and trims flatter and less unique - but introduces new trims for Armadyne and Solgov to make up for it. I see this one being a bit devisive, so feel free to take it to the THUNDERDOME and duke it out on why this should or shouldn't merged. I don't care either way, it was just fun to make.
image

## Why It's Good For The Game
Mechanically, easier to switch job trims on an agent ID. We have so many titles it feels like flipping through a Saturday catalogue, this should at least help by narrowing it down to just colors rather than icons, and a competent player quick slap in "Atmospheric Technician" when their trim is "Gunner", etcetera.
In-universe? Why in the seven hells is Nanotrasen splurging on ID cards that have a built in color e-ink display? That's... all kinds of insane!

## Changelog
:cl:
add: New (flat) ID cards, comrade! Viva la Nanotrasen!
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
I don't really like that aestethic, honestly. It just makes it much less friendly to the user.

**Comment by Arctaisia** [comment]
I feel I prefered it when the job's symbol was shown on the card, made them easier to differentiate, as well as giving them a better overall look. Also, I'd say they use the same equipment as Polychromatics, so easy to produce, and change colour, weh.

**Comment by unit0016** [comment]
Maybe, but there's something about the simple stripe design that gets me.
also there may be a reason for implementing solgov stripe but that's only hypothetical.

**Comment by GoldenAlpharex** [comment]
> also there may be a reason for implementing solgov stripe but that's only hypothetical.

I mean, you could just add that to the regular IDs too, no need to change the whole aesthetic for that.

**Comment by unit0016** [comment]
> > also there may be a reason for implementing solgov stripe but that's only hypothetical.
> 
> I mean, you could just add that to the regular IDs too, no need to change the whole aesthetic for that.

I am, there's a reason this is a separate module and not replacing the master_files ID tweaks.

**Comment by GoldenAlpharex** [comment]
> > > also there may be a reason for implementing solgov stripe but that's only hypothetical.
> > 
> > 
> > I mean, you could just add that to the regular IDs too, no need to change the whole aesthetic for that.
> 
> I am, there's a reason this is a separate module and not replacing the master_files ID tweaks.

Which ones are the Armadyne and SolGov ones anyway?

**Comment by unit0016** [comment]
> Which ones are the Armadyne and SolGov ones anyway?

Armadyne
image
Solgov
image

**Comment by unit0016** [comment]
I'm gonna see about improving the look of the ID cards a tad.

**Comment by GoldenAlpharex** [comment]
> I'm gonna see about improving the look of the ID cards a tad.

I mean, I'll be blunt, I prefer the current look of ID cards. These ones are neat, maybe fit the aesthetic better, but in the end don't really give as much information as the other ones and just look a bit more bland and generic.

Have you even tried asking around to see if people were interested by that change? I'd just hate to see you waste your time on something that people don't necessarily want in the first place.

On a side note, it could be a nice new look for the cargo budget cards, and other IDs that aren't used on-station.

**Comment by unit0016** [comment]
> > I'm gonna see about improving the look of the ID cards a tad.
> 
> I mean, I'll be blunt, I prefer the current look of ID cards. These ones are neat, maybe fit the aesthetic better, but in the end don't really give as much information as the other ones and just look a bit more bland and generic.
> 
> Have you even tried asking around to see if people were interested by that change? I'd just hate to see you waste your time on something that people don't necessarily want in the first place.
> 
> On a side note, it could be a nice new look for the cargo budget cards, and other IDs that aren't used on-station.

I understand current IDs give more information, but this was a simple catch-all for job trims. More of a backend friendly change rather than being a user-focused one.
I did get some positive feedback about them when I posted screenshots in developer channels, though I did straight admit this was mostly a for fun thing.
As for using these for more restricted IDs, offstation etcetera - The problem is simply how trims work. I can't lock trims to only work on a specific type of ID without some serious coderbus. They'd be static, which'd kinda ruin the point.

**Comment by FlamingLily** [comment]
While I very much like the new aesthetic, I think the job icons need to stay.

**Comment by KathrinBailey** [comment]
Not really a fan, the only reason I'd want ID cards to be changed is for them to be made smaller whilst retaining the job icons. And I'm not even sure we need to do that.
It's ugly, and now you have to guess which shade of blue is Command, Security or Medical.
No idea which shade of orange/yellow is cargo, engineering or atmos.
No idea what neon pink and pink is.
This is a slap in the face to our few colourblind players as well.

**Comment by unit0016** [comment]
> This is a slap in the face to our few colourblind players as well.

I completely forgot about that, I feel like a fuckin' dingus. Good point.

**Pull request closed without merging**
