### PR TITLE
[SEMI-MODULAR] [TESTING] All the borgs

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Adds lots of borgs, mostly dog-borgs. Added k69 and a couple of other special variants. 

TO-DO: add sleepers

## Why It's Good For The Game
Gives players the ability to choose lots of borgs.

MORE BORGS!!!

## Changelog
:cl:
add: Added all the borgs.

### CODE REVIEW

**Comment by Azarak** [comment]
Made the borg code less terrible, by a tiny bit

**Comment by Azarak** [comment]
Well I think this is as acceptable as is gets, considering that borg and module code is kind of a mess, and since we dont want to change core files too much, it is what it is. I changed the choice names so it's more clear

**Comment by Azarak** [comment]
I believe licking people doesn't work with the lick module? Have you waited for prefs for that to be a thing? @Gandalf2k15

**Comment by Gandalf2k15** [comment]
Fixed

**Comment by Azarak** [comment]
merging for the test's sake. This could use another look in the future though

**Pull request merged**
