### PR TITLE
Replace wardens Krav-Maga Gloves with a implanter

### PR DESCRIPTION
**Pull request by SomeRandomOwl**
## About The Pull Request

This PR modifies `code\game\objects\structures\crates_lockers\closets\secure\security.dm` to and removes `new /obj/item/clothing/gloves/krav_maga/sec(src) ` and replaces it with `new /obj/item/implanter/krav_maga(src)`

## How This Contributes To The Skyrat Roleplay Experience

It replaces a relatively powerful item that can be easily stolen off of the warden with something not so easily stolen, and also from what I recall there was talk about doing this replacement, but it was never done, so I am simply doing it now with this PR. 

## Proof of Testing

<details>
<summary>Screenshots/Videos

image

</summary>
  
</details>

## Changelog

:cl:
add: Replaced the the Wardens Krav Maga Gloves with a Krav Maga Implanter
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
What if the warden started with it as an implant by default, so the HOS (and other officers) cannot steal it and mess up a latejoin warden?

**Comment by SomeRandomOwl** [comment]
wait hold on my working Dir is dirty it shouldent have included that other change as it was already merged hold on

**Comment by SomeRandomOwl** [comment]
> What if the warden started with it as an implant by default, so the HOS (and other officers) cannot steal it and mess up a latejoin warden?

That could work but honestly people whouldent be raiding the warden locker and stealing job gear from it if there is no warden, same rules apply to Heads of staff too IIRC

**Comment by Bamhalazam** [comment]
so as if security wasn't OP enough with their batons, you want to give the Warden the ability to have basically martial arts with none of the downsides?

Imagine a warden wearing insuls and CQCing your ass.

**Comment by Spaghetti-bit** [comment]
What if a warden cryos out after using the implant? 
- New warden doesn't have any Krav Maga.
- There's no way to get it back unless an admin spawns it in.
- Implanted krav maga means you can't ever disarm the warden, making them a constant threat.

Doesn't this just create a new series of issues? 

I don't see many people stealing the krav maga gloves, it's a rare occurrence as is.
Krav Maga implant is ~8TC if I remember correctly (when it's on the uplink)
The gloves are a watered-down version, the same abilities but have the con of being worn.

As for the insulated gloves point; Insuls don't change much of actual combat. Most of the time if you're going to be in that situation, an officer will just grab an Insulated mutator/activator.

**Pull request closed without merging**
