### PR TITLE
makes roundstart podpeople not OP

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request
roundstart podpeople

## How This Contributes To The Skyrat Roleplay Experience
see title

## Changelog

:cl:
balance: roundstart podpeople don't heal anymore from light
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
Fill out the template pls. Why is this change a good thing, why is it necessary? And use a more descriptive title

**Comment by GoldenAlpharex** [comment]
While I think they were a bit too OP, I don't think this is the right way to go about it.

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
If you're going to nerf them, nerf the healing amount. Perhaps that it could also only be the damage type that they take when they're in the dark that they heal when in the light.

**Comment by softcerv** [comment]
a way that I could see tackling it that would make the healing much less passive is require water to be in the body of plant people for them to heal.

**Comment by jjpark-kb** [comment]
we merged already an alternative PR to nerfing podpeople weak

**Pull request closed without merging**
