### PR TITLE
[MIRROR] Feature: bitrunner, a new supply role (READY) [MDB IGNORE]

### LINKED ISSUE #24007: Bitrunner den on void not connected to power grid
Reporting client version: 514.1589

## Round ID:
9523

## Testmerges:
- [[TESTMERGE ME BEFORE MERGING] Armadyne Antitrust Act 2563 :: Disintegrates armadyne as a concept and replaces basically everything related](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23424)
- [[SEMI-MODULAR] [TEST-MERGE FIRST] Adds synth wounds and resets synth limb damage to 1x, other synth changes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23733)
- [[MIRROR] Feature: bitrunner, a new supply role (READY) [MDB IGNORE]](https://github.com/Skyrat-SS13/Skyrat-tg/pull/23865)
- [[Modular] HotFix for Crew Monitors](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24006)

## Reproduction:

Bitrunner den on void not connected to power grid

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/77259
--------------------
## About The Pull Request
[Design doc](https://hackmd.io/@ shadowh4nd/r1P7atPjn) 

Adds a new supply role centered on short dungeon-esque runs with a focus on unifying the job with the fun part. Some virtual domains are combat related, some are silly, some focus on "objectives". Avatar health is linked to your physical presence and retries are limited.

<details>
<summary>Photos, WIP</summary>

Net pod stasis
netpod

Server loaded

Server cooldown

the quantum console UI
Screenshot 2023-08-05 105742

Cyber police antag page
Screenshot 2023-08-16 205303

A safehouse
image

Domain info page, every domain gets this (and sometimes help text)
Screenshot 2023-08-04 141859

Me getting steamrolled in one of the missions
syndicant

Ghost roles getting notified that server is kicking them out
Screenshot 2023-08-04 135454

Players enjoying the new combat missions
Screenshot 2023-08-05 005727

Players exploring some of the virtual maps
Screenshot 2023-08-06 220919

(Not part of the PR, but)
Screenshot 2023-08-06 221527

New bitrunner vendor
dreamseeker_V62h2BGdEl

</details>

## Why It's Good For The Game
Content, firstly, and moreso being supply department content.

The framework that this implements is a great (preauthorized) replacement for two systems which are collecting dust: BEPIS and the gateway. They integrate into this system and it's a direct upgrade.

This adds a way for the players on station to generate materials (if that remains). The nice part about it is that I can throw balance and believability to the wind, as unlike its unrelated predecessor VR or away missions, bitrunning entirely washes its hands of the map and mobs each reboot.

It offers a very expandable map framework to add content and it's all fairly well documented.

I'd like to add a feature that represents the idea that jobs don't have to be mundane and "external" jobs can stay tied to the main gameplay loop.

## Changelog
jlsnow301, kinneb, mmmiracles, ical92, spockye
:cl:
add: Adds Bitrunning to supply department- a semi-offstation role that rewards teamwork.
add: Adds new machines to complement the job- net pod, quantum server, quantum consoles, and the nexacache vendor.
add: Adds several new maps which can be loaded and unloaded at will.
add: Some flair for the new bitrunning vendor.
add: Adds a new antagonist for the virtual domain only. Short lived ghost role that fights bitrunners.
del: Removes the BEPIS machine, moves its tech into the Bitrunning vendor.
/:cl:

EDIT: Includes digi resprites by CandleJaxx
Includes the hotfixes from https://github.com/Skyrat-SS13/Skyrat-tg/pull/23919
Includes https://github.com/Skyrat-SS13/Skyrat-tg/pull/23931
Includes https://github.com/Skyrat-SS13/Skyrat-tg/pull/23953
Includes https://github.com/Skyrat-SS13/Skyrat-tg/pull/23891 Voidraptor bitrunner den by Paxilmaniac
Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/24007

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Just putting this on so we do some test-merges before fully merging this, once it's ready.

**Comment by CandleJaxx** [comment]
> Just putting this on so we do some test-merges before fully merging this, once it's ready.

does it need edits?

**Comment by vinylspiders** [comment]
the bitrunner suit will need a digi refit

**Comment by CandleJaxx** [comment]
> the bitrunner suit will need a digi refit

i could crank one out rq if you dont have anyone on it

**Comment by vinylspiders** [comment]
> > the bitrunner suit will need a digi refit
> 
> i could crank one out rq if you dont have anyone on it

Feel free! I will probably end up doing it if no one else does and I would appreciate it. : )

**Comment by vinylspiders** [comment]
Voidraptor will also need a bitrunning den added to it but that's all that comes to mind other than things that we can add later.

**Comment by CandleJaxx** [comment]
> Voidraptor will also need a bitrunning den added to it but that's all that comes to mind other than things that we can add later.

i'll pop it out tomorrow after i wake up :) as for the mapping, that's wayy out of my knowledge, sorry!

**Comment by CandleJaxx** [comment]
i can't send the dmis over github so my discord is 'funksalot' if you wanna snag em <3

**Comment by StrangeWeirdKitten** [comment]
So Bubberstation has been running this pre-skyrat merge for around the day, and there are a few things we've noticed. But I'll mostly try to separate this between skyrat-specific stuff and a couple TG specific stuff.

- Certain areas (the red marked with a skull) are designed to kill you if you loose. You die in the game, you die in real life. It is balanced around TG's health, so it only actually puts you in soft crit where a simple medibot and brute kit will get you back up in a minute.
- Also the health percentage says 120% instead of 100% in the readout. (minor)
- You get random human-gen bit avatars. If you make it so your spawned avatar takes your current character preferences, you need to keep in mind that the bit avatar is connected to the pod that spawned it. So theoretically, you can hop out, and someone else can take control of your character inside the simulation. 
- Cyber police are also random-gen human mobs. They're also a random event in the event panel. All they get is sleeping carp, though. (They kill in style)

**Code specific things** (which can be addressed upstream)

- The boards for the computer, server, and netpods are not in the tech tree. You can spawn the boards and make a setup, but there are very specific downsides to this which I'll address.
- The rewards and credit are bound specifically to the bitrunner den area. If you make a bitrunner set up in the bar, as an example, you will not get the decrypted crates you recover **or** any credit for the completion (the purple stars) to buy more dangerous and rewarding simulations. You're basically locked only to playing the gondola astroid and beachbum simulation.

https://github.com/tgstation/tgstation/issues/78571

**Comment by vinylspiders** [comment]
> i can't send the dmis over github so my discord is 'funksalot' if you wanna snag em <3

Thank you, they've been snagged!

**Comment by vinylspiders** [comment]
> So Bubberstation has been running this pre-skyrat merge for around the day, and there are a few things we've noticed. But I'll mostly try to separate this between skyrat-specific stuff and a couple TG specific stuff.

@StrangeWeirdKitten I've just patched one of the health issues I think? There was a conditional that was checking `MAX_LIVING_HEALTH` (100) instead of `HUMAN_MAXHEALTH` (135) for whether or not to disconnect you.

image

As for the readout, that might be something specific to Bubberstation because it seems to be getting the right number here. It is based on the bitrunner's realspace body's `health` / `maxHealth` vars so it should be accurate regardless of mob type.

**Comment by vinylspiders** [comment]
This should be ready for a TM now

**Review by vinylspiders — APPROVED** [review]

**Comment by CandleJaxx** [comment]
Please

**Comment by Erol509** [comment]
Also keep in mind that deconstruting it, destroying it might lead to progress reset or total failure of it, and that needs admin intervention

**Comment by GoldenAlpharex** [comment]
Should be ready now, let's send it! There's plenty of mirrors waiting on it!

**Pull request merged**
