### PR TITLE
[MOSTLY MODULAR] Removes stunbaton crate from cargo, replaces with baton crate

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Removes stunbaton crate from cargo, and replaces it with a far cheaper crate that contains normal peacekeeper batons.

~~I was going to remove stunbatons from cargo outright, but I was assuming secmains would be incredibly salty, so I still gave them an option to purchase one on an individual basis.~~

## Why It's Good For The Game

I'm very unhappy with the way security will come and demand to use cargo funds to purchase one or two stun baton crates for the absurd price, also what was the point of removing stunbatons from their standard loadout if they just purchase them half the time anyways?

There's a reason we removed stunbatons from normal seccie loadout: because they suck. Security shouldn't have them, Period.

## Changelog
:cl:
del: Removed stun batons from cargo list, replaced with normal peacekeeper batons.
/:cl:

### CODE REVIEW

**Comment by Vizoplez** [comment]
Departmental Cards exist. This allows anyone to order stunbatons.
why

**Comment by Swiftfeather** [comment]
> Departmental Cards exist. This allows anyone to order stunbatons.

I tested this, turns out the access view doesn't do anything at all, funny.

> why

Stun batons were removed from the standard loadout, they shouldn't have them, but they purchase them half the time anyways.

**Comment by mazzinsanity** [comment]
> > Departmental Cards exist. This allows anyone to order stunbatons.
> 
> I tested this, turns out the access view doesn't do anything at all, funny.
> 
> > why
> 
> Stun batons were removed from the standard loadout, they shouldn't have them, but they purchase them half the time anyways.

Put it behind research then.

**Comment by Swiftfeather** [comment]
> > > Departmental Cards exist. This allows anyone to order stunbatons.
> > 
> > 
> > I tested this, turns out the access view doesn't do anything at all, funny.
> > > why
> > 
> > 
> > Stun batons were removed from the standard loadout, they shouldn't have them, but they purchase them half the time anyways.
> 
> Put it behind research then.

No, putting cargo behind research is stupid, and making stun batons printable is even more stupid than that. If security wants stun batons let them go spacetiding or cut up their beepskies

**Comment by mazzinsanity** [comment]
> > > > Departmental Cards exist. This allows anyone to order stunbatons.
> > > 
> > > 
> > > I tested this, turns out the access view doesn't do anything at all, funny.
> > > > why
> > > 
> > > 
> > > Stun batons were removed from the standard loadout, they shouldn't have them, but they purchase them half the time anyways.
> > 
> > 
> > Put it behind research then.
> 
> No, putting cargo behind research is stupid, and making stun batons printable is even more stupid than that. If security wants stun batons let them go spacetiding or cut up their beepskies

I dunno, forcing Security to cut up Beepsky or go spacetiding for a stun baton, wich let's be honest, just sounds like sec banbait, appears to me stupider than putting Stun Batons behind Sci Research.

This also removes the ability for Robotics to make Secbots.

I were to propose a sci weapons research experiment that allows Security to print Stun Baton Conversion Kits from their Protolathe, wich can then be used to convert their regular batons into Stun Batons.

Instead of amputating Stun Batons from the regular loop of the game, give an alternative way to acquiring them instead. Yeah, they stamcrit you in 3 hits, so why not make it something that is accessible to Security through mid-late shift Science research? All the other departments get fancy new toys like power tools and advanced surgical tools as the shift goes on, so why not give one to Security that isn't a Shield, Mindshield Pin, Ammo, Bolas and Tackle Gloves

**Comment by Swiftfeather** [comment]
> Instead of amputating Stun Batons from the regular loop of the game, give an alternative way to acquiring them instead. Yeah, they stamcrit you in 3 hits, so why not make it something that is accessible to Security through mid-late shift Science research? All the other departments get fancy new toys like power tools and advanced surgical tools as the shift goes on, so why not give one to Security that isn't a Shield, Mindshield Pin, Ammo, Bolas and Tackle Gloves

Look, stun batons dont' belong in security's hands 95% of the time. They don't fit in. They shouldn't get them. Yeah I could add a research node that requires 29 batons to be scanned, but they'd just fucking rush it, fuck em. They can live without them for now. They are doing just fine with their firearms, and need to learn to rely on their other nonlethal means of takedown, not just going to cargo and purchasing stunbatons.

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by Gandalf2k15** [comment]
Fine.

**Pull request merged**
