### PR TITLE
Void Raptor fore maintenance remaps

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Remaps and expands a substantial portion of Void Raptor's maintenance on the upper half of the station and adds a tram leading to/from the prison.

## How This Contributes To The Skyrat Roleplay Experience

The biggest issues I've heard echoed related to Void Raptor that this PR seeks to address are both a lack of maintenance on the north side of the station and a number of long maintenance corridors that ultimately lead to dead ends. 

I've pushed both solar arrays on the north side of the station a bit further out in order to expand maintenance up there. There were a lot of dead ends in maintenance around security; so I stole Birdshot's "prison satellite" idea and pushed the prison further out as well. There's now a tram that runs between the prison and security. Maintenance cuts through security's new tram-line instead of coming to a bunch of dead ends around the prison/labor shuttle dock. 

### Images

<summary>
Updated security maintenance & prison tram line.
</summary>
<details>

image
</details>

<summary>
Updated/expanded maintenance on the opposite side; above xenobio.
</summary>
<details>

image

I couldn't really figure out how to address the dead end here so I just added an airlock.
image

</details>

<summary>
Engineering Hard Storage has been moved near the break room in order to do away with another long maintenance hallway leading to a dead end.
</summary>
<details>

image

This long corridor in maintenance where engi hard storage used to be now loops back to the station's aft hallway. 
image

</details>

Also fixed access on the CO's locker in the prison? It was set to armory access for some reason; the CO couldn't open it.

## Proof of Testing
Messed around in a private test server for quite a while fixing issues and making sure the tram (and everything else) worked properly.

https://github.com/Skyrat-SS13/Skyrat-tg/assets/62350255/e4a858d6-03f9-47cb-82c0-cf53547db3ef
  
</details>

## Changelog

:cl:
add: Void Raptor's fore maintenance areas have been expanded significantly.
add: Void Raptor's brig now has a tram leading to/from the prison satellite.
tweak: Void Raptor's engineering hard storage has been moved towards Engineering's break room.
fix: The corrections officer can now actually open their office locker on Void Raptor.
/:cl:

### CODE REVIEW

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
I haven't looked at this indepth yet, but I did notice the lizard plushies are getting thanos snapped. Intentional or not, please make sure your branch is 1:1 with master as there was a refactor for these plushies recently.

image
image

**Comment by YakumoChen** [comment]
The tram feels fairly unnecessary. It puts the Prison extremely far away from the brig and the map removes a lot of the intrigue and escapability of the Prison. It's a bit of a joke on birdshot and I wouldn't take ideas from a map that is _intentionally_ designed to be bad

The armoury airspace still feels cramped and overly protected which is one of the main complaints maintainers have made about it

Firing range still being by the Prison (along with the only ammo printer) excaberates the big problem it already had being very far away from security storage

Gulag shuttle being moved is good although moot since gulag is basically never used.

**Comment by YakumoChen** [comment]
Unrelated to the security stuff above, you have many windows in maint with electrified grilles that do not need then or aren't even connected to the grid, please reduce the security on them.

**Comment by YakumoChen** [comment]
image
I see a lot of extraneous loot here without looking at the actual changes.
- Wood logs and axe (could just be wood planks)
- armoured syndicate clothing in space
- Powerful dagger in the cult room
- Rooms just filled with tons of maint loot spawns

**Comment by ghost** [comment]
> The tram feels fairly unnecessary. It puts the Prison extremely far away from the brig and the map removes a lot of the intrigue and escapability of the Prison.

The tram ride takes roughly 5 seconds and is an interesting means of getting back and forth between the prison. The prison's not really made much less accessible by it; nor is it really any harder to escape from than it was before. It's still primarily surrounded by open space with the labor shuttle attached and a passageway leading directly to the prison block through maintenance; along with an airlock just above the CO's office; mostly the same as it was before in terms of layout/escape opportunities. You can still pretty easily break in/out through maintenance by destroying a reinforced wall beside the prison library, or by emagging your way in/out through the CO office maint door, or through space if you prepare a little or get some help from outside.

> Firing range still being by the Prison (along with the only ammo printer) excaberates the big problem it already had being very far away from security storage.

I've moved the ammo bench over to the office (like on most other maps) for the sake of convenience, but I don't feel like the firing range is used enough that putting it in the prison block is going to be a major inconvenience for security. On Ice Box it's literally _inside_ the prison; and if that's fine then this really shouldn't be a problem.

>Unrelated to the security stuff above, you have many windows in maint with electrified grilles that do not need then or aren't even connected to the grid, please reduce the security on them.

Void Raptor has a lot of electrified windows in maintenance around security, so I mimicked that throughout the rest of sec maints; though looking at it now it is definitely a bit much and I've gone ahead and reduced the amount of electrified grilles.

> The armoury airspace still feels cramped and overly protected which is one of the main complaints maintainers have made about it.

This one's a bit tougher to address. I went ahead and gave the extra space bridge I added a more 'under construction' look and did away with the shutters in order to expose it to space and give space-bound antagonists an easier route to the armory and the vault; which was the best I could come up with. Like before, the armory is now a set of shutters away. Or, if you were instead to break in through the new tram line, a few reinforced directional windows. The addition of the tram line does sort of open up a potential new route for antagonists to try to access the armory with the way the windows are set up, especially given they're directional windows and therefore aren't electrified.

image

As for the 'extraneous loot' you mention:

> Wood logs and axe (could just be wood planks)

This is a hatchet. It is an item available at the public garden on every station; or printable at any autolathe.

> Armoured syndicate clothing in space

The armor values on said _armored syndicate clothing:_

image

> Powerful dagger in the cult room

Swapped the bloodletter out with a ritual dagger, which can only be used by cultists - and is relatively easy for cultists to make anyways.

> Rooms just filled with tons of maint loot spawns.

Yeah. Maintenance loot spawns are pretty great. Void Raptor has a lot of them in aft maintenance, and I wanted fore maintenance to match.

image

**Comment by YakumoChen** [comment]
> The tram ride takes roughly 5 seconds and is an interesting means of getting back and forth between the prison. The prison's not really made much less accessible by it; nor is it really any harder to escape from than it was before. It's still primarily surrounded by open space with the labor shuttle attached and a passageway leading directly to the prison block through maintenance; along with an airlock just above the CO's office; mostly the same as it was before in terms of layout/escape opportunities. You can still pretty easily break in/out through maintenance by destroying a reinforced wall beside the prison library, or by emagging your way in/out through the CO office maint door, or through space if you prepare a little or get some help from outside.

The problem is that you don't _need_ a tram to the prison. It just makes a big old waste of space for the whole dock set and the path in between. The tram existing forces the round to consider tram-exclusive events, and I think in general riffing a map feature for something in rotation isn't very good, especially for, as again stated, Birdboat is _intentionally poorly designed_ and cribbing features from it isn't ever a good idea.

**Comment by ghost** [comment]
In hindsight this was far too ambitious of a project for me. I've spent the past couple days stressing out fixing issue after issue after issue and I'd rather just close this and be done with it.

Maybe I'll re-visit this idea in the future when I have a bit more experience with mapping.

**Comment by SpaceLoveSs13** [comment]
Besides the tram part, this pr should be brought back

**Pull request closed without merging**
