### PR TITLE
OPFOR Items Reloaded

### PR DESCRIPTION
**Pull request by desertmote**
## About The Pull Request

In this PR I improved the items you can choose in the OPFOR loadout list.

A bunch of unmaintained weapons are culled, now the gun selection include only maintained weaponry.
The weapons are now given in a gun case, supplied with its basic ammunition.

For the sake of the approval process, the item bundles have been removed. Bundles are now only clothing, and renamed to outfits instead. This way a staffie working on the OPFOR request knows exactly what they are approving.

Progression traitor items are a noteworthy addition, the scalpel and nuke screwdriver specifically. This allows an OPFOR traitor to interact and roleplay with these items and goals without the gamification.

Another noteworthy addition is the organ selection, currently exclusively existing of Xenomorph organs (-eggsac and vore stomach). A player with these organs can create engaging combat scenarios involving resin structures and acid.

The OPFOR menu in general has slightly improved navigation, including a sorted list, better categorization and a scroll wheel.

<details>
<summary>Loadout demos</summary>
  
demo3

demo4

demo5

demo1

demo6

</details>

ZaKndrO7V4

## Changelog

:cl:
balance: The OPFOR loadout item-selection is rewritten
add: The OPFOR loadout has a new category for gaining organs

add: Adds a syndicate version of the detective holster
imageadd: A new 'strange' autosurgeon for alien organs
fix: Fixes the robohand bundle, and improves remaining bundles like ocelot and heister
balance: NRI lightweight MRE is small sized instead of normal sized
code: Ds2 balaclava no longer hides hair
code: Removes a bugged message from the handheld mirror
/:cl:

### CODE REVIEW

**Comment by desertmote** [comment]
(Outdated)

Demo of some outfit loadouts. From the top:

1. Syndicate Operative
2. Syndicate Engineer
3. Syndicate Spy
4. Cybersun Operative
5. Cybersun Hacker
6. NRI Soldier
7. Azulean Boarder
8. Professional (Heister)

some loadouts

Check out the file here `modular_skyrat/modules/opposing_force/code/equipment/clothing.dm`

**Comment by frontline03** [comment]
For the loadouts i'd probably stick to the red and black the syndicate are known for.

**Comment by burgerenergy** [comment]
Two things, both related;

If you want to add the supermatter scalpel and the nuclear screwdriver you should instead add the box kit. The scapel has tongs to actually pick up the shard, otherwise that shit is just on the floor which while it still fucks with the SM, isn't exactly productive. I am pretty sure you can't even do anything with the nuke without the tongs once you open it, nor to memory is there a sprite for it being opened.

Removing the core of the nuke does nothing, gameplay wise, although the core is radioactive until it's in the holder. The supermatter shard will dust people when carried in tongs, although the person holding the shard will also get dusted if they touch anything with it. Both are rendered permanently inert and harmless once put into the holder box the kit comes with. You need to add an admin note both of these saying these details, as well as the SM kit makes it dramatically more likely to delam. (Also probably a general description, as it's a niche TG objective.)

**Comment by desertmote** [comment]
Thanks a lot for pointing that out!

**Review by lessthnthree — APPROVED** [review]

**Pull request merged**
