### PR TITLE
Makes ashwalker/icecat seed production not reliant on technology any further

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

Adds a new doohickey, you put plants in it and it'll turn them into seeds.
In reality, it functions extremely similarly to how a seed extractor bag does, but without the whole technology bit.
Also it has a funny animation.

## How This Contributes To The Skyrat Roleplay Experience

extractor

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

After grinding:

image

image
image

</details>

## Changelog

:cl:
qol: Ashwalkers and icecats are no longer reliant upon technology for the extraction of seeds from their produce. Now? They have a big stone wheel they crush the plants in.
/:cl:

### CODE REVIEW

**Comment by Elli-Skala** [comment]
Are natives able to build more in the case of it being destroyed? (Say in the case of a Rouge death bolt)

**Comment by Paxilmaniac** [comment]
> Are natives able to build more in the case of it being destroyed? (Say in the case of a Rouge death bolt)

Coming 2023

**Comment by ghost** [comment]
Think TG would accept this? They're starting to lean into adding makeshift versions of machines, having this up there'd be nice for their own roles too (Hermit and Ashwalkers for example)

**Review by Jolly-66 — APPROVED** [review]
Map edits are fine.

**Comment by Paxilmaniac** [comment]
> Think TG would accept this? They're starting to lean into adding makeshift versions of machines, having this up there'd be nice for their own roles too (Hermit and Ashwalkers for example)

Maybe. You are welcome to do so yourself if you think so.

**Review by desertmote — APPROVED** [review]

**Pull request merged**
