### PR TITLE
[NON-MODULAR] fixes things so that classic (including peacekeeper) batons can stamcrit again

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

Not sure if it was a bug or intentional but here's your fix, batons can stamcrit again.

## Why It's Good For The Game

BECAUSE I SHOULDN'T HAVE TO FUCKIN BASH SOMEONE TO STAMCRIT THEM, SINCE THREE PEOPLE GOING AT SOMEONE WITH BATONS FOR FIVE MINUTES DOES ABSOLUTELY NOTHING

## Changelog
:cl:
fix: batons stamcrit again
/:cl:

### CODE REVIEW

**Comment by FlamingLily** [comment]
HELL YEAH

**Comment by CloverIsLucky** [comment]
Please speedmerge this! @Gandalf2k15

**Comment by CloverIsLucky** [comment]
Or someone with merge permit!

**Comment by Gandalf2k15** [comment]
Huh, this is a strange one. Also add a skyrat comment. Not sure why it's like this, but I know we used to be able able stamcrit

**Comment by Funce** [comment]
Try fixing on /tg/?

**Comment by lyricalpaws** [comment]
> 
> 
> Try fixing on /tg/?

Isn't this an us issue because we edited health and stamina values, not tg?

**Comment by Seris02** [comment]
Yes, and they merged the fix on tg and now they're having issues, so they're going to revert it.

lmao

**Pull request merged**
