### PR TITLE
[MIRROR] The CentCom-ening part 5: I might have a problem [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/70226
--------------------

## About The Pull Request
HELLO HELLO LADIES AND GENTLEMEN, ITS THAT TIME OF THE DAY AGAIN!

Did you know this is what our CentCom commanders looked like?
image

They never even wore the correct green all throughout the uniform! It was out of place and very garish, a prevailing issue that haunted the job for nearly a decade, until I broke into the scene and made PR #57023, which would slowly improve the visuals to something more adequate for the role.
image

But for gods sakes, the uniforms at the time despite the improvements, *still* had problems! So I kept working on it. I would then follow up with PRs #60414, #63029 and #64377, which would add more clothes and continue to pretty up this job I oh-so love!
image

Which brings me here. I went through more improvements in my spriting journey, going from a fledgling artist who did a few clothes people really enjoyed, to now becoming a /tg/station spritetainer. Which made me want to try something new for CentCom! Don't you miss that old, bright green? Don't you wish it looked better and had a fully realized concept? Boy howdy do I have some good news!
image

This PR (again), revamps the clothing choices of our favorite green-clad commanders and administrators into something even *more* refined than before!

## So What Has Changed?

Glad you asked! A few things really, primarily:
- The CentCom Commander's Suit
- The CentCom Commander's Suitskirt
- The CentCom Officer's Turtleneck
- The CentCom Officer's Skirtleneck
- The CentCom Commander's Formal Coat (And Alternate)
- The CentCom Officer's Fur Coat
- The CentCom Commander's Cap
- The CentCom Commander's Hat
- The Intern's Shorts
- The Head Intern's Beancap
- The CentCom Winter Coat

Have all been successfully resprited with utmost care to shading and coloring! Particularly, the uniforms now boast a new light green, as seen in the first iteration, done at its maximum potential, as well as a really nice gold palette to pair itself with!

A few additions have been made as well, as perceptive ones may have noticed in the screenshot:
- The CentCom Official's Suit returns!

Since a turtleneck didn't make much sense for such a formal job. The turtlenecks are now instead the base clothing for Emergency Response Teams!

Finally, a new addition has been made which some admins may appreciate, due to the absolute massive scale of clothes available for one to access:
- The CentVend!

image

This one-of-a-kind bad boy is currently hidden inside the CentCom Commander's bedroom. It includes all CentCom uniforms, as well as a few extra pieces of apparel such as combat gloves, jackboots, laceups and sunglasses! Hopefully, this encourages admins to appreciate the full wardrobe of Central Command, as there is admittedly a lot to find which is obfuscated by spawn commands.

image

## Why It's Good For The Game
Other than it adding a few extra quality of life things that were missing from the game, this is all just yet another exercise in my never-ending journey to make Central Command as pretty as it is, and continue to show the world that I still got it as a spriter and artist! And to believe this *alone* reached 2 years of continuous updates. I hope you all enjoy it as much as I do!

## Changelog

:cl: PositiveEntropy
add: Adds the CentVend inside Central Command! You're now able to vend Central Command clothing items for all your commanding needs!
add: Re-adds the CentCom Official's suit, making it the default clothing option for CentCom Officials! The turtlenecks have instead been made to be the standard ERT uniform.
imageadd: Nanotrasen returns once again to update CentCom's wardrobe, changing its green to a newer, fresher one!
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
These are... bright.
Is it worth making all CC stuff go to the modularskyrat cc.dmi and having the darker green? Whoever merges it just @ me on discord with the answer and I'll make a PR if needed

**Comment by GoldenAlpharex** [comment]
> These are... bright. Is it worth making all CC stuff go to the modularskyrat cc.dmi and having the darker green? Whoever merges it just @ me on discord with the answer and I'll make a PR if needed

I think we should start by seeing how it's like in-game, and we can see about making them darker afterwards if we feel like it's needed.

**Comment by GoldenAlpharex** [comment]
Actually, @Paxilmaniac do we need to adjust CentCom for this, ourselves? I don't think so, but just to be sure.

**Review by GoldenAlpharex — APPROVED** [review]
Code checks out for me!

**Comment by Paxilmaniac** [comment]
> Actually, @Paxilmaniac do we need to adjust CentCom for this, ourselves? I don't think so, but just to be sure.

None of our AM templates should touch the edited areas of CC, it should be fine

**Pull request merged**
