### PR TITLE
updates the icebox ashwalker den

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
Fairly big redo of a lot of the icebox ashwalker den, castle? Den.

THE full resolution screenshot, go look at mapdiff bot if you want to see it with the walls smoothed

As for changes, the full (I think) list of changes are here:
- All instances of lavaproof lattices have been replaced because wolves are hilarious?
- The ash ritual thing has been moved to a brand new building in the center
- Basalt tiles have been added to the garden area in a way that actually looks decent
- The xenoarch tools were removed because I haven't seen a single soul use them, not once
- The full toolbelts have been replaced with the ashwalker variants of tools
- A few bundles of natural paper have been placed around, because paper has a few uses aside from writing on
- Several hatchets have been placed around as there are a few things that need hatchets specifically to work
- Some grass and small bushes have been strewn about so its not just barren snow around the camp

## How This Contributes To The Skyrat Roleplay Experience
Having the ritual out in the open annoyed me a bit, and there were a few nitpicks I had with how things looked, certain things like advanced tools not fitting the theme well enough, and the fact that people would (and probably still will to my annoyance) replace all the dirt over in the farm with basalt and make it look ugly.

## Changelog

:cl:
qol: several facets of the ashwalker's home on icebox have been changed, including a new building for the ash ritual, basalt in the farming area, the ability to bring wolves from one side of the plasma river to the other, and a few others
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
where mapping tag

**Comment by Jolly-66** [comment]
> where mapping tag

N/A because the bot doesn't apply it properly. I cry too, don't worry.

**Comment by Paxilmaniac** [comment]
ignore the red folder in that screenshot its a bundle of natural paper they just dont render right ever until theyre actually in a game

**Review by Jolly-66 — DISMISSED** [review]
Mapping looks good. Just double check with Jake since hes responsible for the ashie rites, if you haven't already.

**Comment by Elli-Skala** [comment]
Unlisted in the pr is replacing the xenoarch tools and tool belts with the ash walker version of the tools (though I think that's fine)


Though why add natural paper? Ash walkers can't read or write the only things they could use them for is making paper frame walls or paper bags, and even then they can't make any more (but that's just because they don't have exactly a botany metal hatchet the only tool that allows you to make paper)

**Comment by Paxilmaniac** [comment]
making this a draft for now because i've got some ideas to try out, and a few things to do tomorrow

**Review by jjpark-kb — CHANGES_REQUESTED** [review]
put back the xenoarch tools-- just because they aren't often used doesn't mean they aren't; additionally, its required to have the tools to just do one of the rituals as well.

**Comment by Paxilmaniac** [comment]
guh, fine, but PLEASE add some variant of the xenoarch tools that don't just look like modern stuff in the future

**Comment by Paxilmaniac** [comment]
the CI failure on icebox isn't caused by me

**Pull request merged**
