### PR TITLE
Delta station atmos door ID requirement undo

### PR DESCRIPTION
**Pull request by GuiltyNeko**
## About The Pull Request
Delta station atmos is either atmos or engineering access, which allows heads of staff and the paramedic access to atmospherics, which is of course not necessary in the slightest. Engineers still have atmos access on skeleton crew and can get the HoP or captain to give them atmos access if they need it.

## Changelog

:cl:
fix: removed generic engineering access from delta station atmos doors
/:cl:

### CODE REVIEW

**Review by GoldenAlpharex — COMMENTED** [review]
Was that a thing upstream too? If so, could be a good idea to fix that there too?

Is this this way on any other map, or is Delta just an outlier in this regard?

**Comment by GuiltyNeko** [comment]
I think this is a silly thing some mapper decided to do for some reason, it's only delta.

**Comment by GoldenAlpharex** [comment]
If we don't want this to be reset every map reset, we might want to make that change upstream too, then.

**Comment by KathrinBailey** [comment]
do this upstream as well if you want it to stay

**Pull request merged**
