### PR TITLE
fixes some of the issues of the createanddestroy unit test

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
title

## Why It's Good For The Game
send help

## Changelog
no

### CODE REVIEW

**Comment by jjpark-kb** [comment]
66 reasons typically

**Comment by jjpark-kb** [comment]
down to 16

**Comment by GoldenAlpharex** [comment]
> down to 16

You're insane, good job! I'll probably see if I can't fix one or two as well, if you'd like, or keep on doing my review of it.

**Comment by jjpark-kb** [comment]
its a fix

**Pull request merged**
