### PR TITLE
[SEMI-MODULAR] Hooch heals assistants

### PR DESCRIPTION
**Pull request by Superlagg**
## About The Pull Request

Hooch heals assistants as it should.

## How This Contributes To The Skyrat Roleplay Experience

Nerfing assistants isn't a good thing, actually.

## Changelog

:cl:
add: The assistant's favorite drink, hooch, heals them once more.
/:cl:

### CODE REVIEW

**Comment by axietheaxolotl** [comment]
Wrong changelog entry, and generally just dumb. I'm fully in agreement with /tg/ that assistants shouldn't get any benefits over any other job.

**Comment by GoldenAlpharex** [comment]
Ided PR

In all seriousness, I didn't know that was a thing, I bet you most people didn't and are none the wiser, it's not a clear mechanic and it just feels like it'd be useful for people to avoid interacting with other departments even more as assistants.

**Comment by ghost** [comment]
Upstream balance and decisions aside, this is not only a brand new change, but one thats STILL being debated upstream. I really recommend against a PR to re-add something that they may re-add or re-work this soon anyways

**Comment by SpaceVampire** [comment]
Nerfing assistants is a good thing, actually.
Get a real job, hippie.

**Comment by Iamgoofball** [comment]
:-1:
greytide be gone

**Comment by tf-4** [comment]
Wait for it to settle upstream at least. Though even then, I'm not sure how attached to this feature I am.

**Comment by Gandalf2k15** [comment]
Given this was changed with good reason, I do not want to readd it.

**Pull request closed without merging**
