### PR TITLE
[Modular] Ports the bluespace locker from oldskyrat

### PR DESCRIPTION
**Pull request by NotRanged**
## About The Pull Request

Ports the BS locker from old skyrat, latest yog fixes included.

image
image

## Why It's Good For The Game

It was always pretty neat to have people turn it into their little hideout, a small bar area, an antag shelter, you name it.

## Changelog
:cl:
add: Ported the Bluespace Locker from old codebase/Yogs. A random locker gets turned into this every round, the interior of which is considerably larger than the outside!
/:cl:

### CODE REVIEW

**Comment by NotRanged** [comment]
idk what's wrong here ;( I didn't varedit any area paths

**Comment by YakumoChen** [comment]
imo it should really have some better protections on it to not make it such a perfect hideout. iirc it basically removes you from any method of tracking, and it's obviously inconspicuous, not even an examine text or other hint that it's not what it seems.

**Comment by unit0016** [comment]
~~the easiest way is to turn it into a dorm before an antag gets to it~~

**Comment by Gandalf2k15** [comment]
Reslove conflicts and we can TM this,.

**Comment by NotRanged** [comment]
*scream

**Comment by Gandalf2k15** [comment]
Conflicts a!!

**Comment by NotRanged** [comment]
just fullmerge it already aaaaa ill fix in a moment

**Pull request merged**
