### PR TITLE
Shady Market - Tiny Fixes and QOL

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

This just corrects a couple oversights and adds a little QOL to the BMD. Primarily the mask missing for the modsuit and the fab board being a station board and not the away one.

## How This Contributes To The Skyrat Roleplay Experience

While I personally am not a fan of the added modsuit over the softsuit, it was missing its mask and without any others on the base it was forcing them to rob the station roundstart so they could spesstide. 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
  SOAP (random spawner)
  
image

 Contraband Contraband Contraband (random spawner)
image

Proper away board
image

Suit Storage now includes mask
image
  

</details>

## Changelog

:cl:
qol: Shady Market - Added soap to the shower and returned the crap starting spawner for a weapon
fix: Shady Market - You can now breathe in space with your mask and print things from your proper lathe/imprinter
/:cl:

### CODE REVIEW

**Comment by Zenitheevee** [comment]
One thing worth keeping in mind, The "TechFab" machine could also print out circuit boards. The Protolathe its replaced with cannot.

**Comment by Zergspower** [comment]
Ah, i'll add the printer then

**Comment by Zergspower** [comment]
> Error: FAIL /datum/unit_test/nuke_cinematic 4.1s 

Okay

**Review by Paxilmaniac — APPROVED** [review]
ok i guess

**Pull request merged**
