### PR TITLE
[Modular] Tactical Skirtleneck Digi Fix

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Makes the tactical skirtleneck work for digitigrade legs. That's it. That's the PR.
image

## Why It's Good For The Game
Oversight bad mmkay.

## Changelog
:cl:
fix: Wearing a tactical skirtleneck no longer morphs your legs to plantigrade automatically.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Skirts don't normally need a digi version, what was broken with them?

**Comment by Azarak** [comment]
The issue is that the skirt is covering the legs AND not having a digi variant, triggering the squashing mechanism.

The proper fix to this would be change its coverage to `body_parts_covered = CHEST|GROIN|ARMS` and leave the `mutant_variants = NONE`, and discard the icon changes

**Comment by Gandalf2k15** [comment]
> The issue is that the skirt is covering the legs AND not having a digi variant, triggering the squashing mechanism.
> 
> The proper fix to this would be change its coverage to `body_parts_covered = CHEST|GROIN|ARMS` and leave the `mutant_variants = NONE`, and discard the icon changes

This

**Comment by unit0016** [comment]
Done.

**Review by Azarak — APPROVED** [review]

**Pull request merged**
