### PR TITLE
Added Prison Gates, and ID lockable lockers to Perma

### PR DESCRIPTION
**Pull request by Mundang**
## About The Pull Request
Replaced some of the airlocks in Perma to Prison gates, and changed the lockers to ID lockable lockers

## How This Contributes To The Skyrat Roleplay Experience
Allows for the function to the ID timer, and removes the need to have a separate timer.

## Changelog

:cl: Mundang
add: replaced airlock in Perma with prison gates
add: replaced lockers with genpop lockers
/:cl:

### CODE REVIEW

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
This PR is incompatible with how we do map edits (with the exception of BlueShift).

Delta already has a modular prison segment, and should have these items already (if they don't then I'm wrong)
As for the other maps, I won't permit a single tile auto mapper segment just to add these, as this could possibly get pushed upstream.

I would close this PR with just this comment, but I'm on hiatus right now, so Pax will be in charge here.

**Comment by Iamgoofball** [comment]
they can't take it upstream though the turnstile gates are a down here thing

you could however use the permabrig doors from tramstation instead

**Comment by Mundang** [comment]
That is what I have done. 

> they can't take it upstream though the turnstile gates are a down here thing
> 
> you could however use the permabrig doors from tramstation instead
That is what I have done.

**Comment by Zonespace27** [comment]
Feel free to re-PR this with the changes made.

**Pull request closed without merging**
