### PR TITLE
[MODULAR][TM-ONLY] Disables rot infecting people. Why.

### PR DESCRIPTION
**Pull request by Vizoplez**
## About The Pull Request
/tg/ moment

## Why It's Good For The Game
this ignores armor and can give you lethal diseases despite having full internals. Also fucks over miners.

## Changelog
:cl:
tweak: DISABLED ROT INFECTIONS.
/:cl:

### CODE REVIEW

**Comment by SpaceVampire** [comment]
Could you balance it upstream as well?
Its part of the funny gas not making you sick changes.

**Comment by Vizoplez** [comment]
> Could you balance it upstream as well?
> Its part of the funny gas not making you sick changes.

this is a stopgap until upstream fix it.

**Comment by SpaceVampire** [comment]
> 
> 
> > Could you balance it upstream as well?
> > Its part of the funny gas not making you sick changes.
> 
> this is a stopgap until upstream fix it.

Test-merge or something then maybe? I do agree its really annoying in the current state.

**Comment by DuffCreeper** [comment]
Local moth sits in cargo and suddenly starts dying cause his window was open and someone coughed

**Comment by Cheshify** [comment]
+1 do this

**Comment by Gandalf2k15** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/4525

**Comment by Gandalf2k15** [comment]
#4525

**Pull request closed without merging**
