### PR TITLE
[NO GBP] Fixes Icebox

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Title

- ~~Readds gas miners~~ Apparently these were meant to be removed long ago and just... somehow came back. They've been re-removed
- Unbreaches Security
- Fixes the HoS console
- Fixes detective/lawyer door access
- Fixes genturfs/areas
- Fixes missing sec vendor
- Updates labour shuttle to skyrat version

As for why security ALSO had no power... _that_ round? I've no clue, map-wise it should have power. I blame the IPC warden.

Marked as no gbp because these issues were from one of my own recent PRs

## How This Contributes To The Skyrat Roleplay Experience
Fun fact: I made the last PR at like, 5 to 6 AM.
It was merged without review.

Now we suffered the consequences. 

I'll be labelling the time/how much sleep I got from now on in all my PRs.

## Changelog

:cl:
fix: Icebox Gas Miners Do Not Exist; as a bonus, Icebox prison isnt breached any more
/:cl:

### CODE REVIEW

**Comment by zeratino** [comment]
yo have you fixed the hos requests console as well?

**Comment by ghost** [comment]
> yo have you fixed the hos requests console as well?

Oh, yea, I did. That wasnt even caused by me but I saw the HoS in THAT round mention it, so its fixed now. I'll update the description.

**Comment by SpaceVampire** [comment]
>Readds gas miners

Wait, I thought we wanted those removed on our maps.
Did something change?

**Comment by tf-4** [comment]
Yeah adding gas miners is not a fix, they shouldn't be added AFAIK

**Comment by gonenoculer5** [comment]
> Yeah adding gas miners is not a fix, they shouldn't be added AFAIK

W h y. Making Atmos more fun by allowing us to actually recover from disasters such as tank piercing from rods now that their back, aswell as allowing us to easily run multiple things at once without needing to order 8 billion plasma canisters to run the turbine and a BZ reaction at the same time should be a GOOD thing. I see no reason not to add gas miners other than the potential cargo cheese with the crystalizer or some shit. Canned standard gases (plasma, CO2, N2, O2, N20, the scrubber net ones) are neigh worthless to cargo so the only cheese I see is going through the labor to setup a elaborate gas contraption or setting up a crystalizer farm for diamonds/plasma.

**Comment by tf-4** [comment]
> > Yeah adding gas miners is not a fix, they shouldn't be added AFAIK
> 
> W h y. Making Atmos more fun by allowing us to actually recover from disasters such as tank piercing from rods now that their back, aswell as allowing us to easily run multiple things at once without needing to order 8 billion plasma canisters to run the turbine and a BZ reaction at the same time should be a GOOD thing. I see no reason not to add gas miners other than the potential cargo cheese with the crystalizer or some shit. Canned standard gases (plasma, CO2, N2, O2, N20, the scrubber net ones) are neigh worthless to cargo so the only cheese I see is going through the labor to setup a elaborate gas contraption or setting up a crystalizer farm for diamonds/plasma.

this is not the PR to have this discussion on.

Don't bundle fixes with balance changes

**Comment by ghost** [comment]
> Don't bundle fixes with balance changes

The gas miners were on the map before my update, I assumed them intentional. Something went tragically wrong and they somehow reappeared at some point though; this wasnt a balance change, as its how Ice was before my incorrectly-updated map was pushed

~~I'm torn between removing them here (which WOULD technically be balance, as they, again, were there before my remap) or leaving it up to a second PR per this quote alone~~ Decided on discord, gas miners are removed. PR updated accordingly.

**Pull request merged**
