### PR TITLE
[Modular] Icebox Syndies get Syndicate winter coats + Interdyne specific Syndie headsets

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request

Sprites and adds in a Syndicate winter coat with the stats of a Security winter coat, giving them specifically to Icebox syndies on spawn. Along with adding 5 to the Syndicate vendor for any other time you wanna wear it.

image

Tactical turtleneck + coat
image

The headsets were more a flavor choice since it's a Syndicate facility, why wouldn't they have their own specific headsets.

## How This Contributes To The Skyrat Roleplay Experience

Syndicate players (and the multitude of Syndicate lizard players) won't freeze to death on Icebox cause a watcher went "heehoo noticed you from 20 tiles away" 
Headset flavor for the Syndicate agents!

## Changelog

:cl: Syndicate Supply runners
expansion: Interdyne has sent in a new shipment of winter coats for operatives located in frozen sectors of space, along with stocking their vendors with spares.
expansion: Deep Space 2 and Interdyne research facilities have been sent a shipment of Syndicate headsets with their specific radio channel.
/:cl:

### CODE REVIEW

**Comment by axietheaxolotl** [comment]
tfw I don't get credited for my idea
IMG_20211206_204352

**Comment by tf-4** [comment]
I'm not really sure why they need this. Don't the hardsuits have heating?

**Comment by Xymec** [comment]
> I'm not really sure why they need this. Don't the hardsuits have heating?

There's only one hardsuit on interdyne, so it's either this or just giving them an extra hardsuit or two.

**Comment by Xymec** [comment]
> I'm not really sure why they need this. Don't the hardsuits have heating?

or alternatively...just removing watchers in general or making them less cancerous to play against (Such as getting pratically stunlocked because you keep getting spammed with ice beams and the slowdowns stack making the legion cores and lux pens almost an actually needed item if you want to go up against more than two of them.) Personally i'd rather just go the lazy way and do this though.

**Comment by tf-4** [comment]
I don't really think watchers are that much of an issue tbh

**Comment by GoldenAlpharex** [comment]
Or, y'know, you could actually give them a Syndicate winter coat, surviving in the snow with just your jumpsuit and boots is very strong and counter-intuitive. Could have some Syndicate winter boots to match, too.

**Comment by Ebin-Halcyon** [comment]
I'll mark it as a draft and make Syndicate winter coat sprites in the meantime then.

**Review by tf-4 — APPROVED** [review]
Looks good

**Pull request merged**
