### PR TITLE
De-snowflakes latejoin on-station code, latejoin borgs now sync properly, see #6472

### PR DESCRIPTION
**Pull request by FlamingLily**
## About The Pull Request
see #6472

## Why It's Good For The Game
Fixes good

## Changelog
:cl:
fix: Latejoin borgs are synced to the AI again
/:cl:

### CODE REVIEW

**Comment by FlamingLily** [comment]
Before anyone asks: The previous linked PR (my one) was a revert for a PR that removed latejoin cyborg slots. Said slots were never mirrored to the config, so I'm assuming that PR is being ignored and am therefore fixing the reasons for the issues.

**Comment by FlamingLily** [comment]
I'm not sure what build.js is doing in there..

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
I think that the suggestions I made would probably be better, but you'd have to test to make sure that it both compiles and actually works.

Also, for `build.js`, try to find a way to remove the file from the PR, if you struggle to do so, hit me up and we'll find a solution.

**Comment by FlamingLily** [comment]
Neither golden's suggestion or my current code works, will re-open later

**Review by FlamingLily — COMMENTED** [review]
forgot to delete some debug lines

**Pull request merged**
