### PR TITLE
[modular][map](hopefully) restores stuff we lost in the map reset

### PR DESCRIPTION
**Pull request by thestubborn**
## About The Pull Request

title

## How This Contributes To The Skyrat Roleplay Experience

having badges and office good

## Changelog

:cl:
fix: restores stuff we lost in the map reset
/:cl:

### CODE REVIEW

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
image
not that I care either way if this gets back in or if you replace the entire prison with a 1x1 room with a cryopod in it but...

**Comment by thestubborn** [comment]
> 
> 
> image
> not that I care either way if this gets back in or if you replace the entire prison with a 1x1 room with a cryopod in it but...

the woe of copy and pasting

**Comment by thestubborn** [comment]
yeah i tried to revert ice as much as I could
I done all the maps in one commit so...joys

**Review by KathrinBailey — APPROVED** [review]
sure I guess
not sure what's so hard about copying this stuff in the first place and why there's so many catch-up PRs for it.

**Pull request merged**
