### PR TITLE
Revert "Fix thermomachine temperature abuse (#60841) (#7650)"

### PR DESCRIPTION
**Pull request by CandleJaxx**
This reverts commit a7239ffc606f2c7f2f43d99069c773cb1eddc209.

## About The Pull Request

Reverts a PR wherein thermomachines were made functionally unable to use the station-inbuilt waste system as a waste system.

## Why It's Good For The Game

Needlessly complicates toxins by rehashing an already hard-to-learn system.

## Changelog
:cl:
revert: thermomachine changes
/:cl:

### CODE REVIEW

**Comment by jjpark-kb** [comment]
make changes modular.

**Comment by ZephyrTFA** [comment]
This revert brings back a bug; a pretty bad bug aswell. 
Just add a space loop to the waste network

**Comment by Gandalf2k15** [comment]
Do this upstream as well, they've got the same problem

**Comment by nevimer** [comment]
> This revert brings back a bug; a pretty bad bug aswell.
> Just add a space loop to the waste network

It's not that simple in practice at all. Even with waste cold, all the stations thermal machines will report 0.1% efficiency and simply not cool gasses whatsoever. Medical is simply unable to use the cryo tubes until you make them a custom solution. On top of that, if you set a target temperature, you will use 100's of kilowatts immediately killing the area's APC in a single tick 100 to 0 on its power cell right away. You need to babysit the thermal machines (incrementally lower its target temp) and put a lot of effort in each and every one. Regarding enjoyability as a an atmos main? It's fun, sure. I like playing "atmos to the rescue" but it sucks for the station in general when they cease to function unless atmos is going above and beyond for each department. 

It's seriously not as simple at "just adding a space loop" - You can have thousands of moles in the waste network, and the highest efficiency I've seen with waste at around 40 kelvins is... 0.7%. Reverting this is a serious QOL improvement and is backed up by the pinned message on discord of "stop trying to make the game too real".

**Comment by ZephyrTFA** [comment]
> > This revert brings back a bug; a pretty bad bug aswell.
> > Just add a space loop to the waste network
> 
> It's not that simple in practice at all. Even with waste cold, all the stations thermal machines will report 0.1% efficiency and simply not cool gasses whatsoever. Medical is simply unable to use the cryo tubes until you make them a custom solution. On top of that, if you set a target temperature, you will use 100's of kilowatts immediately killing the area's APC in a single tick 100 to 0 on its power cell right away. You need to babysit the thermal machines (incrementally lower its target temp) and put a lot of effort in each and every one. Regarding enjoyability as a an atmos main? It's fun, sure. I like playing "atmos to the rescue" but it sucks for the station in general when they cease to function unless atmos is going above and beyond for each department.
> 
> It's seriously not as simple at "just adding a space loop" - You can have thousands of moles in the waste network, and the highest efficiency I've seen with waste at around 40 kelvins is... 0.7%. Reverting this is a serious QOL improvement and is backed up by the pinned message on discord of "stop trying to make the game too real".

Fixing a bug is not making the game "too real"
Just because something is an inconvenience to you does not mean that you should remove it entirely. 
If you truly think this is an issue you should fix it instead of reverting something that was done in the past to fix an even larger bug. 
The entire reasoning behind the fix you are trying to revert was that you could literally use thermo machines to get upwards of 5MK. You reverting this brings back that game breaking bug and will pose very serious consequences. 
Fix the cause of the issue, do not bandaid it.

**Comment by jjpark-kb** [comment]
with all of the discussion, this PR will be closed.

To summarize:
We should try not to revert MIRROR PRs, but instead modularize our changes that could "revert" the changes.
This MIRROR in specific was meant to fix game-breaking bugs, of which we do not want.
If you truly desire for it to be changed, creating a PR on /tg/ would solve this issue.

Thank you!

**Pull request closed without merging**
