### PR TITLE
[PORT] [READY] Ports over Paradises' trenchcoats and fedoras.

### PR DESCRIPTION
**Pull request by CandleJaxx**
## About The Pull Request

This PR is part of a small series of ports I'm doing, from Paradise to Skyrat. This one includes their Fedora and Trenchcoat sprites, fit for human, digi, and vox.

## How This Contributes To The Skyrat Roleplay Experience

Ever wanted to act like a sleek, fancy-looking Noir Detective? Maybe a rough-and-tumble mafioso? Boy, do we (I) have the drip for you!

## Images

image
image
image
image
image
image
image
image

## Changelog

:cl:
add: A fresh batch of swanky-looking trenchcoats and fedoras have found their way to the Frontier!
/:cl:

### CODE REVIEW

**Comment by CandleJaxx** [comment]
@thestubborn hey drip-person look at my drip

**Comment by thestubborn** [comment]
...acceptable drip

(no but seriously these are great, you didn't show digi legs, but no one cares about that)

🔫now port the coat stand from /vg/

**Comment by thestubborn** [comment]
wait why did you delete the icon for the blueshield armour?

**Comment by CandleJaxx** [comment]
oh Fuck did i? one sec lmao

**Comment by CandleJaxx** [comment]
fixed cheers

**Comment by thestubborn** [comment]
@CandleJaxx 
image
no i meant the obj icon

**Pull request merged**
