### PR TITLE
Roleplay Friendly Fireplaces

### PR DESCRIPTION
**Pull request by Deek-Za**
My friends, today we're going to have a quick fireside chat about fireplaces.
image

## About The Pull Request
Increases the Burn timer for wood from 15 seconds to 1.5 minutes
Increases the max fuel capacity for the fireplace from 5 minutes to 30 minutes.
Adjusted animation/lighting phase timers.

## How This Contributes To The Skyrat Roleplay Experience
Fireplaces are pretty cool. But with our server having a higher RP focus and a much more likelihood to stop and sit at certain scenes longer, I think it's a better adjustment for Skyrat.
This is a gripe I see pretty regularly with fireplaces and them burning through fuel super quickly. One wood burns up in 15 seconds. And if you store enough fuel(20 Wood) to cap it out you get a grand total of.. five minutes.
Honestly some of our lengthy based RP'rs would burn through a full capacity before it's their turn to RP post again!
You basically have to keep feeding in logs as you go and I see/hear semi-regular complaints about this. Plus someone getting up every couple of minutes to throw wood in the fire is a real mood killer.

## Changelog

:cl: Deek-Za
qol: Fireplaces now burn longer and have better fuel efficiency.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
#8216 fix this too please

**Comment by Deek-Za** [comment]
> #8216 fix this too please

Where did this happen to you? I've twice now sat in a room with a fire rolling for 30 minutes and didn't come close to a CO2 death. Matter of fact it seems like the only CO2 being generated was mostly just from my breathing and not the fireplace itself.

**Comment by ZephyrTFA** [comment]
Fireplaces do not create CO2

**Comment by YakumoChen** [comment]
> 
> 
> > #8216 fix this too please
> 
> Where did this happen to you? I've twice now sat in a room with a fire rolling for 30 minutes and didn't come close to a CO2 death. Matter of fact it seems like the only CO2 being generated was mostly just from my breathing and not the fireplace itself.

It's happened to me multiple times in the icebox maint cabin. It was definitely CO2 because the second time I brought an air filter before I started the fire and it spiked the CO2 heavily

**Pull request merged**
