### PR TITLE
[modular] adds the ability for six character hex colours (draft so maintainers know what to do when this gets merged on TG, if it does)

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

title

yes this code might not be the best

## How This Contributes To The Skyrat Roleplay Experience

it doesn't

## Changelog

:cl:
qol: adds the ability for six character hex colours 
/:cl:

### CODE REVIEW

**Comment by Seris02** [comment]
oh
I forgot to commit changes to tgstation.dm
I normally just ignore it
woops

**Comment by Seris02** [comment]
just ignore the fact that it's failing integration tests, it won't when all of this gets put onto that other PR

**Review by GoldenAlpharex — APPROVED** [review]
Code seems to check out.

**Comment by Funce** [comment]
Done-zo mate

**Pull request merged**
