### PR TITLE
[MODULAR] Gives robo medihuds/NV medihuds

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

Title. 2 normal huds in the vendor, infinite huds via the exofab.

## How This Contributes To The Skyrat Roleplay Experience

Since robo is the synth medical subdepartment now, and we've given them so many medical tools, why not medihuds? This way they can more effectively perform triage, identify wounded synths, see how quickly someone is dying from electrical damage, etc.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

</details>

## Changelog

:cl:
balance: Robotics now has 2 medihuds in the vendor, and infinite medihuds from the exofab
/:cl:

### CODE REVIEW

**Comment by lessthnthree** [comment]
"we've given them so many medical tools,"
Is exactly why I was wary to let you start doing it. Give an inch, you PR a mile.

Can you make the science goggles view synth health or something. Or do we not stop until you've put everything from medical and engineering into your exofab.

**Comment by nikothedude** [comment]
jeez dude lose the attitude, theres no reason to be so abrasive

**Comment by nikothedude** [comment]
but, i suppose, it would actually make more sense for diag huds to see synth health - but then i'd also have to go and consider making medhuds _not_ show synth health

not sure, ill leave this pr open in the meantime

**Comment by lessthnthree** [comment]
I think with the introduction of all the new mechanics in your synth wounds there should be a line of related tools to keep some delineation, instead of just giving robos medical's equipment, engineering's advanced tools, etc.

**Comment by nikothedude** [comment]
actually nah its just a better idea to separate it, fuck it, ill do that at some point

**Pull request closed without merging**
