### PR TITLE
Makes the Snout Clown Mask Consistent.

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request

Every default Clown mask has the same colour scheme.
White facepaint, yellow eyeliner/cross thing, red lips and blue eyes.
All of them except this fucking thing.

image
Which is green for some reason.
This fixes that.
## How This Contributes To The Skyrat Roleplay Experience

I like consistency.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image
image
image

</details>

## Changelog

:cl:
image: The Snouted Clown mask is now the same colour scheme as the rest of the species clown masks. A shared symbol of unity in Clown Brotherhood.
/:cl:

### CODE REVIEW

**Comment by theselfish** [comment]
While I wait for this to build, take the new, in dm sprite. 
image

**Comment by theselfish** [comment]
image
Might make it a bit darker.

**Comment by burgerenergy** [comment]
are you implying clowns need to follow rules and structure?

**Comment by theselfish** [comment]
Actually no, it's consistent.
image

**Comment by theselfish** [comment]
> are you implying clowns need to follow rules and structure?

No. I just think that having one mask stick out like a sore finger isn't good.

**Review by vinylspiders — APPROVED** [review]
Looks good to me, @GoldenAlpharex ?

**Comment by theselfish** [comment]
@GoldenAlpharex Waiting for the worms, here.

**Review by GoldenAlpharex — APPROVED** [review]
Looks good to me!

**Pull request merged**
