### PR TITLE
[NON-MODULAR] Removes the banhammer drop from abandoned crates

### PR DESCRIPTION
**Pull request by NullDagaf**
## About The Pull Request

Title.

## Why It's Good For The Game

Dumb OOC jokes in-game are bad, m'kay?

## Changelog
:cl:
balance: changed the abandoned crate's 96th drop from a banhammer to an RCD
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Why would you want to remove more stuff from something that already contains stuff that's less useful than maintenance's crates?

**Comment by Vizoplez** [comment]
Improper title conventions, lack of SKYRAT EDIT comments. Please rectify or close PR
-Intern dev

**Comment by NullDagaf** [comment]
> Improper title conventions, lack of SKYRAT EDIT comments. Please rectify or close PR
> -Intern dev

where exactly do you want me to put more SKYRAT EDIT comments

**Comment by NullDagaf** [comment]
Noice, gandalf didn't close this one yet

**Pull request closed without merging**
