### PR TITLE
[SEMI-MODULAR] Ports Paradise photocopier ass sprites

### PR DESCRIPTION
**Pull request by dawsonkeyes**
## About The Pull Request

Hey you! Have you ever played a skyrat-exclusive race and been sad that your photocopied ass is a human one? I haven’t, but this PR is for you!

Scrounging existing asses into a .dmi, this pull request add’s paradise’s icons for the likes of vulpkanin, podpeople, unathi, and more!

## How This Contributes To The Skyrat Roleplay Experience

IMMERSIVE
ASS
DESIGN

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
Nothing to add here yet - this PR still needs more testing on my end!

</details>

## Changelog

:cl:
add: Photocopiers now have more species-specific ass sprites from Paradise
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Dawson for Asstainer 2023

**Comment by BubbleTrroubles** [comment]
Way to go Dawson!!

**Comment by ghost** [comment]
I expect a ping on discord for sprite review when this has been tested, Dawson. Do not disappoint me.

**Comment by Iamgoofball** [comment]
finally, immersion is returned to the lands

**Comment by dawsonkeyes** [comment]
ok ok

**Comment by tf-4** [comment]
Very stale, feel free to get a spritetainer to reopen this one though.

**Pull request closed without merging**
