### PR TITLE
return to tradition - brings .50 back in line with tg balance

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
brings p50 (the sniper) back into tg baseline
also kills off sopo ammo because it was essentially supplanted by disruptor but NOBODY realized this

## How This Contributes To The Skyrat Roleplay Experience
i think one-shot or adjacent guns is fundamentally an awful decision in general
my crusade against whatever the hell gunwank caused gubman 3 or whatever it was continues

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>

image
  
</details>

## Changelog

:cl:
balance: .50 (used in the snipers and renamed to .416 or whatever) is now back to TG balance standards. Knockdown on hit, 60 instead of 110 damage, etc. etc.
fix: .50 Soporific was removed because disruptor ammo was right there and nobody realized it existed.
/:cl:

### CODE REVIEW

**Comment by chemistrymain2** [comment]
if this gets closed re open the thing but for the .50 sopfor

**Comment by Paxilmaniac** [comment]
this will not be good for the carp season

**Review by GoldenAlpharex — DISMISSED** [review]
Saying that they were never intended for 135 health when our entire balance was designed around it is rather disingenuous.

There's absolutely no substance to justifying why this would be a good change, but since I'm nice, I'm giving you one day to try and make the most convincing reasoning ever. That being said, it's still likely going to be a no, so don't get your hopes too high.

**Comment by Draganfrukts** [comment]
My big evil 50 cal that fires a bullet that do less damage than a revolver despite having a shot delay of a full second

**Comment by chemistrymain2** [comment]
> My big evil 50 cal that fires a bullet that do less damage than a revolver despite having a shot delay of a full second

it stuns you and blows limbs off

**Comment by vinylspiders** [comment]
This looks good to me now that the health changes are removed but I will leave it to @GoldenAlpharex to take a final look as they were reviewing this before.

**Review by vinylspiders — APPROVED** [review]

**Pull request merged**
