### PR TITLE
Redoes bluesec clothing sprites to have a nicer, more consistent color palette, along with correcting alot of glaring mistakes.

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request
Tin. Updated the old sprites which had mediocre colors, and a lot of ugly things attached to them along with a few sprinklings of sprite distortion.
Image of the items in game, from security officer, to warden, to HoS
PR stuff-export

## How This Contributes To The Skyrat Roleplay Experience
Color palettes matter alot.

## Changelog

:cl:
imageadd: Security clothing have been resprited to have a nicer looking and more consistent color palette.
imagedel: Bluesec bulletproof helms have been returned to the stock TG look, rejoice.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
~You should axe the white jumpsuit because its just spraypainted in the end anyways and that goes against the whole point of giving them unique uniforms. I give u permission, I regret adding it~

**Review by tf-4 — APPROVED** [review]

**Comment by MacaroniCritter** [comment]
The new security cap deviates from the previous ones design and it makes me sad.

**Comment by Ebin-Halcyon** [comment]
Stuff I still gotta do on this, no motivation to do it at the moment.

**Comment by Ebin-Halcyon** [comment]
Right, pushed through the last of the sec stuff. This is basically finished, ping me on the discord if there's something missed.

**Comment by Zonespace27** [comment]
lgtm from the previous TM

**Pull request merged**
