### PR TITLE
(Probably) Temporarily removes the ninja kit because #10550 breaks it anyway

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
## About The Pull Request
Title says it all. #10550 breaks it, it'd look all broken and I don't think working with the new high-frequency blade would be a wise move, until we know just *how good* it is now (probably very good.)

To be merged right after #10550.

## How This Contributes To The Skyrat Roleplay Experience
Someone attacking you with an item that has no valid icon states wouldn't be fun, trust me on that one.

## Changelog

:cl: GoldenAlpharex
del: Striking News: The Syndicate has temporarily put on hold their contract with the Spider clan, resulting in shortage in Cyborg Ninja kits in the uplinks. No further information was given, but rumor has it that there was many changes to one of its main items and that the Syndicate will take a moment to adapt it to their needs.
/:cl:

### CODE REVIEW

**Comment by dawsonkeyes** [comment]
I made a PR faster so mine is cooler

**Comment by GoldenAlpharex** [comment]
Wait actually I'm stupid, this isn't needed, we didn't actually touch the vibro weapon.

**Comment by GoldenAlpharex** [comment]
No I'm stupid, we did, lol.

**Comment by GoldenAlpharex** [comment]
1984.

**Pull request merged**
