### PR TITLE
[Modular] Icebox Dorms Overhaul

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
This started off as me fleshing out the pool some more, then quickly spiraled. These dorms aren't as nice as the ones on DS-1, but the cozy vibe is there. Replaces the original dorms. Those are now booths, because you can never have enough booths. Also inadvertently re-adds the removed secret first dorm.
Showers are hooked up to some water synths. They can't all be ran simultaneously due to how plumbing works, but running just a few should work fine(?)
image
image

## Why It's Good For The Game
If the prison dorms are better than the real dorm, just make the real dorms better again. Dingus.

## Changelog
:cl:
add: Icebox has new dormitories.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Feels like there's a lot of open space hmm

**Comment by H0gberg** [comment]
Wonderful work!

**Comment by NullDagaf** [comment]
> Open space to an ice cave

Yeah, I'm sure this won't cause any issues, for sure.

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Alright, I legitimately fell asleep before posting this so I'm doing it again. I'm going off your images in the PR.

**Issues with top level.**
1. Too many seating areas. Replacing dorms as shown in your pic is kinda lazy. It looks simply like you're trying to fill up space, and it doesn't look good. Try and integrate the old sleep area and new space created by removing dorms into something that looks like it's always been that way.
2. Turn yourself into an AI and test if you can see the entirety of the room. Got a feeling a few tiles might be lacking coverage.

**Issues with bottom level.**
1. It's completely unpiped. I can't really let that go at all. There's no reason for each room to not have functional atmos.
2. You've just copy and pasted the dorm rooms. This works for prisons because it's supposed to look uniform, but less so here. Old Icebox had two different styles of room.
3. Far far far far far too much empty wasted space. A six-tile-wide corridor? Why?
4. Lights aren't sufficiently covering the hallway.
5. Dorm rooms themselves look super ugly. They're also waaaay too big. Go solely for maximizing function. What do people want out of these rooms? An area for a group to sit and talk. A bed for, _urhm..._ naptime? You could delete the entire shower area and shove it into the bedroom, separating it instead with a shower curtain and making it a wetroom. You could turn the L-shaped wooden tapes into an I shaped row of tables and move the microwave, then move the seating area into that room. You've now cut nearly half of the room out with no loss of function.
6. Boxing ring is dead space. Axe it completely, it never gets used at all. Ever. If anyone ever wants to do that sort of thing, they can make one in 90s somewhere where they'll actually get people watching.
7. Use airlock cyclelink helpers for the bottom left external airlocks.

**Comment by unit0016** [comment]
> Alright, I legitimately fell asleep before posting this so I'm doing it again. I'm going off your images in the PR.
> 
> **Issues with top level.**
> 
> 1. Too many seating areas. Replacing dorms as shown in your pic is kinda lazy. It looks simply like you're trying to fill up space, and it doesn't look good. Try and integrate the old sleep area and new space created by removing dorms into something that looks like it's always been that way.
> 2. Turn yourself into an AI and test if you can see the entirety of the room. Got a feeling a few tiles might be lacking coverage.
> 
> **Issues with bottom level.**
> 
> 1. It's completely unpiped. I can't really let that go at all. There's no reason for each room to not have functional atmos.
> 2. You've just copy and pasted the dorm rooms. This works for prisons because it's supposed to look uniform, but less so here. Old Icebox had two different styles of room.
> 3. Far far far far far too much empty wasted space. A six-tile-wide corridor? Why?
> 4. Lights aren't sufficiently covering the hallway.
> 5. Dorm rooms themselves look super ugly. They're also waaaay too big. Go solely for maximizing function. What do people want out of these rooms? An area for a group to sit and talk. A bed for, _urhm..._ naptime? You could delete the entire shower area and shove it into the bedroom, separating it instead with a shower curtain and making it a wetroom. You could turn the L-shaped wooden tapes into an I shaped row of tables and move the microwave, then move the seating area into that room. You've now cut nearly half of the room out with no loss of function.
> 6. Boxing ring is dead space. Axe it completely, it never gets used at all. Ever. If anyone ever wants to do that sort of thing, they can make one in 90s somewhere where they'll actually get people watching.
> 7. Use airlock cyclelink helpers for the bottom left external airlocks.

Screenshots aren't up to date. I did pipe it, though thanks for reminding me that I forgot about cameras. I'll see what I can do.

**Comment by unit0016** [comment]
I've filled up the central hall - I like it as it is, but it needed decor. Technically it could be narrowed down to a three wide hall, but I feel it'd lose it's charm and look generic.
All of the rooms but dorms one and two are now using the design Kath suggested, killing two birds with one stone - Variety and redesign.
Cameras.
Boxing ring from the pool PR is removed.
Airlocks cyclelinked - only those with appropriate access can use it anyways.

**Comment by hugmeorelse** [comment]
> > Alright, I legitimately fell asleep before posting this so I'm doing it again. I'm going off your images in the PR.
> > **Issues with top level.**
> > 
> > 1. Too many seating areas. Replacing dorms as shown in your pic is kinda lazy. It looks simply like you're trying to fill up space, and it doesn't look good. Try and integrate the old sleep area and new space created by removing dorms into something that looks like it's always been that way.
> > 2. Turn yourself into an AI and test if you can see the entirety of the room. Got a feeling a few tiles might be lacking coverage.
> > 
> > **Issues with bottom level.**
> > 
> > 1. It's completely unpiped. I can't really let that go at all. There's no reason for each room to not have functional atmos.
> > 2. You've just copy and pasted the dorm rooms. This works for prisons because it's supposed to look uniform, but less so here. Old Icebox had two different styles of room.
> > 3. Far far far far far too much empty wasted space. A six-tile-wide corridor? Why?
> > 4. Lights aren't sufficiently covering the hallway.
> > 5. Dorm rooms themselves look super ugly. They're also waaaay too big. Go solely for maximizing function. What do people want out of these rooms? An area for a group to sit and talk. A bed for, _urhm..._ naptime? You could delete the entire shower area and shove it into the bedroom, separating it instead with a shower curtain and making it a wetroom. You could turn the L-shaped wooden tapes into an I shaped row of tables and move the microwave, then move the seating area into that room. You've now cut nearly half of the room out with no loss of function.
> > 6. Boxing ring is dead space. Axe it completely, it never gets used at all. Ever. If anyone ever wants to do that sort of thing, they can make one in 90s somewhere where they'll actually get people watching.
> > 7. Use airlock cyclelink helpers for the bottom left external airlocks.
> 
> Screenshots aren't up to date. I did pipe it, though thanks for reminding me that I forgot about cameras. I'll see what I can do.

Thanks for taking critique in stride. :)

**Comment by unit0016** [comment]
Mmhmhm..
Map conflicts.
I'll fix it inn a bit, I won't have access to my main PC for a day or two.

**Comment by YakumoChen** [comment]
Unironically it doesn't feel like there's enough rooms. All that space down there and all the dorms are like, apartment buildings now. Can't you convert a few of them into more compact bedroom types and fit a couple more rooms in?

**Comment by unit0016** [comment]
> Unironically it doesn't feel like there's enough rooms. All that space down there and all the dorms are like, apartment buildings now. Can't you convert a few of them into more compact bedroom types and fit a couple more rooms in?

That's because they take up more room. There's actually one more room from what there is on the server right now.
Technically, I could fit a dorm room in a three tile room, and get a good 50 or so dorms in the space here if I was efficient. But that's stupid. People don't want _more_ dorms - there's five already, not counting DS-1, the ghost cafe, etcetera. They want _better_ dorms. Icebox is one of the few maps this is easy to do in, seeing as it's multiz with a lot of free space.
The only serious flaw I see with the pitch I've made here is gibtonite.

**Comment by tf-4** [comment]
> The only serious flaw I see with the pitch I've made here is gibtonite.

just map out a little around it so gibtonite won't spawn next to dorms

**Comment by YakumoChen** [comment]
What does that big hole actually look down into? If it's bare ice cave I'm pretty sure that's going to cause atmos issues?

Why not just replace it with a maint den or something

**Comment by tf-4** [comment]
> 
> 
> What does that big hole actually look down into? If it's bare ice cave I'm pretty sure that's going to cause atmos issues?
> 
> Why not just replace it with a maint den or something

looking at it, it seems to look down about... here 
image

**Pull request closed without merging**
