### PR TITLE
[MODULAR] Fixes yet another avenue of prisoner escape via the fucking sex toy vendor.

### PR DESCRIPTION
**Pull request by Iamgoofball**
lmao free multitools

### CODE REVIEW

**Comment by Zonespace27** [comment]
Considering we have #10661 up, I don't see the need in axing it entirely from all vendors

**Comment by Iamgoofball** [comment]
The ERP vendor shouldn't have any gameplay objects in it period.

**Comment by Xymec** [comment]
> The ERP vendor shouldn't have any gameplay objects in it period.

such a bad PR, you're supposed to put a syndicate minibomb in it.

**Comment by Gandalf2k15** [comment]
The cake cannot be had and eaten, you should have to work to get the things needed

**Pull request merged**
