### PR TITLE
[SEMIMODULAR] Station Names for each map!

### PR DESCRIPTION
**Pull request by FlamingLily**
## About The Pull Request
This PR changes the code for station names. Depending on config settings, station names can be preset (a la "Space Station 13) as they could before, they can be randomly generated, with split configs for standard random generation and holiday random generation, and the main feature of this PR, using the current map's name (in the map's .json) as the station's name.

For instance, if the map is "NSS Journey," this would make the station name, ICly, the "NSS Journey."
To be extra clear, there's two more config flags

HOLIDAYSTATIONNAMES which allows for randomly generating a holiday station name (note that holiday station names will override set names, both with the STATIONNAME flag, and the next flag. Standard name generation will also not generate holiday names if this flag is disabled)
and
MAP_STATIONNAME which takes the station_name value in the map's .json file and sets it to the station name. If this is enabled, it will override the STATIONNAME config. If there is no station_name, name generation will fall back on STATIONNAME or random generation

Note that this does not hinder the captain's ability to rename the station, if they so desire.

Obviously, "Delta station" isn't a very good name for our setting, so, each map's name has been updated accordingly (subject to change, with suggestions)
(Note: NSS = NanoTrasen Science Station, NSB = NanoTrasen Science Base)
Delta - NSS Pollux - courtesy of @Snakebittenn 
Meta - NSS Castor - courtesy of @Snakebittenn
Icebox - NSB Boreas - courtesy of @thestubborn 
Tram - NSS Gallivant
Kilo - NSS Unity (get it... cause it's... small... and cramped... so everyone's forced into unity 🤣 )

I have also edited the station name of each file to read NTS Pollux - (Delta Station). This preserves the original map name, for voting and status display, while providing the new name, too add flavour. NSS Journey has also gotten this treatment, being called "NSS Journey - (Skyrat Box Station)" in map_name, and remaining NSS Journey in the station_name

## Why It's Good For The Game
RP, flavour that doesn't break immersion and is more than random words (but also doesn't restrict that ability, via configs)

## Changelog
:cl:
add: Each map now has a unique name!
add: Delta station is now the NSS Pollux
add: Meta station is now the NSS Castor
add: Icebox is now the NSB Boreas
add: Tram is now the NsS Gallivant
add: Kilo is now the NSS Unity
config: Added new config flag - HOLIDAYSTATIONNAMES - allows/disallows generating random holiday station names
config: Added new config flag - MAP_AS_STATIONNAME - takes the aforementioned map names and makes the station name it, if enabled
/:cl:

### CODE REVIEW

**Comment by DuffCreeper** [comment]
Certainly a hundred times better than getting a station name of 'Muslim Tomb Juliet' via random gen

**Comment by Arctaisia** [comment]
Thanks a whole heap for working on this! :heart:

I absolutely love these names, too, all of them sound powerful, unique, and somewhat make sense.

**Comment by YakumoChen** [comment]
:-1:
Would I believe that Nanotrasen is launching deathtraps into space with suitably lazy / ironic names as a testament to how little they actually care?

Yeah.

**Comment by YakumoChen** [comment]
In a more serious note, I think "NTSS" (NanoTrasen Space Station) would be a more suitable designator for... well, space stations. 

Or some kind of randomized acronym. Hell, that was the whole reason for the names to begin with. They don't even have to be funny / ironic, it's just as believable we're calling a place the "Orbital Complex" or "Space Research Vessel" or what have you without having it be literally called "DeathTrap 5" [Designator] [Ship Type] Journey still sounds cool without being needlessly "Low RP"

**Comment by YakumoChen** [comment]
I mostly don't like "NSB" because "Science Base" is the least Planetary Colony sounding designation I've heard of. 

(NTPB) "Planetary Outpost"
(NTRE) "Research Establishment" (we already have one server regularly using this one for it's planetary station, heh heh)
(NTRC) "Research Colony"
the list goes on

**Comment by YakumoChen** [comment]
Finally I think this will make the map vote / etc confusing because having all these "NSS" names won't tell anyone what map it is, unless that's accounted for already. "Tram" and "Box" at least have the gimmick in the name or have universally recognizable layout by the name. Boreas is the only one that vaguely hints at the map type now.

It's also disrespectful to the namesakes of the people who created these maps, some of which have their maps named after them.

**Comment by KathrinBailey** [comment]
I'd much rather this be, if it isn't already, solely restricted to the randomly generated station names if none are chosen, and not part of map votes.
No one will know which station is which. Everyone will forget, people will vote for the wrong wrongs. No one know what NSS Starbumble-Heck or NSS FantaOrange is. Everyone knows what Box and Meta is. Plus, maps like Kilo and Tram are incredibly recent, a ton of effort was put into them, it'd really suck if you made a station just for it to get used and renamed into something completely random.

**Comment by Arctaisia** [comment]
> In a more serious note, I think "NTSS" (NanoTrasen Space Station) would be a more suitable designator for... well, space stations.
> 
> Or some kind of randomized acronym. Hell, that was the whole reason for the names to begin with. They don't even have to be funny / ironic, it's just as believable we're calling a place the "Orbital Complex" or "Space Research Vessel" or what have you without having it be literally called "DeathTrap 5" [Designator] [Ship Type] Journey still sounds cool without being needlessly "Low RP"

We already have one with the N(Role)(Type) designation prefix system, better to keep things consistent and it's certainly not a system that isn't used in our own world. China, for example, uses the WZ(Vehicle)(Type/Role)(Itteration) system for military vehicles it makes, using numbers, but the same kind of system. Secondly, the others in the lore team (the ones that listened to me at least (mostly just xyel listened to me)) seem to enjoy the use of the N(R)(T) system, Xyel even proposed O at the end for outpost, first he proposed it as a replacement for B, but we got it to be a smaller version of Base, so both can be used. Multiple other servers also use it, and these are ones with extensive lore/higher RP standards, such as Paradise (More lore), Virgo/Chomp (Similar RP standards to us and more lore), so we're not the first to use it at all.

And for what Kat said, I think just the start-of-shift names works, ye! Not the biggest need to have them for the vote names, but we can easily add a format like `NSS Journey - (Box), NSS Boreas - (Icebox)`, etc. etc. for the voting screen, if possible. But I do really think this is a good direction for the general immersiveness of the server when it comes to a HRP-friendly environment.

**Comment by FlamingLily** [comment]
Currently, this DOES affect the vote screen, BUT, I can whip up a fix if it's that much of an issue.

**Comment by unit0016** [comment]
I agree with Kath wholeheartedly. We should change up the random name generator's strings and code a bit instead of renaming all the /tg/ maps.
While nothing's wrong with this designations, (They're great, mwah, love em) in my personal opinion we should save them for own own, dramatically overhauled takes on the maps. Like NSS Journey!

...And also we're gonna have to edit the commemorative plaques. Honk.

**Comment by Arctaisia** [comment]
> I agree with Kath wholeheartedly. We should change up the random name generator's strings and code a bit instead of renaming all the /tg/ maps.
> While nothing's wrong with this designations, (They're great, mwah, love em) in my personal opinion we should save them for own own, dramatically overhauled takes on the maps. Like NSS Journey!
> 
> ...And also we're gonna have to edit the commemorative plaques. Honk.

That's a good point, giving our own maps some individuality over the other servers, in both design and name, I like that idea, kept with it on my own map since I first put my plans down for it, so I agree that new maps we make should be given this identity of N(Role)(Type), but at least with this little name generator thing, it'll make things feel a little more immersive, though I do still agree that it's not 100% necessary to change their vote menu names, just the generated name! 

Also commemorative plaques.. Gotta love them, but yeah..

**Comment by FlamingLily** [comment]
Vote menu names HAVE been updated, BUT, they preserve the original map name (icebox is now "NSB Boreas - (IceBox Station)")

**Comment by Mothblocks** [comment]
> Obviously, "Delta station" isn't a very good name for RP 

hey im from tg land and ive been thinking about this for the past day, what on earth does this mean?

**Comment by YakumoChen** [comment]
I still hold that it's an insult to the creators to rename the maps. Kilo and Meta specifically are named after their respective map makers.

Have you considered just naming them "NSS Delta" or similar?

**Comment by FlamingLily** [comment]
> 
> 
> > Obviously, "Delta station" isn't a very good name for RP
> 
> hey im from tg land and ive been thinking about this for the past day, what on earth does this mean?

Well, it's kinda poorly phrased, but I mean within the setting of SS13 through a HRP lens, having stations named things like "Delta Station" (or, like, Tram Station), it's less, I guess suited, than things like NSS [something]

**Comment by FlamingLily** [comment]
> 
> 
> I still hold that it's an insult to the creators to rename the maps. Kilo and Meta specifically are named after their respective map makers.
> 
> Have you considered just naming them "NSS Delta" or similar?

I'm not renaming the maps, though, I'm giving them an IC name while still preserving the map names. The only map which is having it's original name edited could be the Journey, if you want to take it that way, but even then, I asked Blu about it and they said it was fine to make the map's name, code-wise, "NSS Journey - (Skyrat Box Station)"

**Comment by GoldenAlpharex** [comment]
I do agree with what others are saying, I think NTSS would sound better and would be more in line with the rest of the NanoTrasen-related acronyms in the game (NTOS, NTNet, etc.)

Other than that, I'm not really a fan of Castor for Meta, Castor is the French word for Beaver and it just doesn't really make much sense for a space station to be called like that when it has absolutely no correlation whatsoever with the map itself.

**Comment by Gandalf2k15** [comment]
Reminder: It's Nanotrasen, not NanoTrasen

**Comment by YakumoChen** [comment]
> Reminder: It's Nanotrasen, not NanoTrasen

NT is the consistent acronym for everything produced by Nanotrasen regardless.

**Comment by YakumoChen** [comment]
> > I still hold that it's an insult to the creators to rename the maps. Kilo and Meta specifically are named after their respective map makers.
> > Have you considered just naming them "NSS Delta" or similar?
> 
> I'm not renaming the maps, though, I'm giving them an IC name while still preserving the map names. The only map which is having it's original name edited could be the Journey, if you want to take it that way, but even then, I asked Blu about it and they said it was fine to make the map's name, code-wise, "NSS Journey - (Skyrat Box Station)"

Then why not just keep the names as is but with NSS or whatever appended? "NSB IceBox" isnt the most creative name, but you'd be hard pressed to argue its "Low RP" just because it isnt a romanticized name.

**Comment by FlamingLily** [comment]
> 
> 
> > > I still hold that it's an insult to the creators to rename the maps. Kilo and Meta specifically are named after their respective map makers.
> > > Have you considered just naming them "NSS Delta" or similar?
> > 
> > 
> > I'm not renaming the maps, though, I'm giving them an IC name while still preserving the map names. The only map which is having it's original name edited could be the Journey, if you want to take it that way, but even then, I asked Blu about it and they said it was fine to make the map's name, code-wise, "NSS Journey - (Skyrat Box Station)"
> 
> Then why not just keep the names as is but with NSS or whatever appended? "NSB IceBox" isnt the most creative name, but you'd be hard pressed to argue its "Low RP" just because it isnt a romanticized name.

Cause naming them like they'd be named Icly, with verbs like Gallivant and Journey or nouns like Unity sounds better, imho

**Comment by FlamingLily** [comment]
> 
> 
> I do agree with what others are saying, I think NTSS would sound better and would be more in line with the rest of the NanoTrasen-related acronyms in the game (NTOS, NTNet, etc.)
> 
> Other than that, I'm not really a fan of Castor for Meta, Castor is the French word for Beaver and it just doesn't really make much sense for a space station to be called like that when it has absolutely no correlation whatsoever with the map itself.

tbh agreed on the NTSS side gonna change those

Any suggestions for a name for meta and delta, then? Cause castor and pollux are a duo deal if one changes so will the other

**Comment by YakumoChen** [comment]
> 
> 
> > > > I still hold that it's an insult to the creators to rename the maps. Kilo and Meta specifically are named after their respective map makers.
> > > > Have you considered just naming them "NSS Delta" or similar?
> > > 
> > > 
> > > I'm not renaming the maps, though, I'm giving them an IC name while still preserving the map names. The only map which is having it's original name edited could be the Journey, if you want to take it that way, but even then, I asked Blu about it and they said it was fine to make the map's name, code-wise, "NSS Journey - (Skyrat Box Station)"
> > 
> > 
> > Then why not just keep the names as is but with NSS or whatever appended? "NSB IceBox" isnt the most creative name, but you'd be hard pressed to argue its "Low RP" just because it isnt a romanticized name.
> 
> Cause naming them like they'd be named Icly, with verbs like Gallivant and Journey or nouns like Unity sounds better, imho

Those are just romanticized names, there's not a problem with a ship named "NTSS Delta", is there? Is this a "High RP" argument or just an opinion, because I'm against the map names being changed needlessly.

**Comment by FlamingLily** [comment]
> 
> Those are just romanticized names, there's not a problem with a ship named "NTSS Delta", is there? Is this a "High RP" argument or just an opinion, because I'm against the map names being changed needlessly.

Not _necessarily_ no.

**Comment by Arctaisia** [comment]
I feel the NT in NTSS is adding another unnecessary consonant to the prefix, Xyel themselves had a problem with three consonants in the prefix and is why he proposed NSO in the first place. Also, N is the more commonly used prefix when it comes to their objects from what I've seen. Plus, I agree with Gandalf here that it's not NanoTrasen, it's Nanotrasen, the reason NT is used more is because in those cases, it works with fewer syllables, or 'NOS' doesn't sound as good. NSS, NMB, NHS, etc. to me roll off the tongue better than 4 syllables.

TG already uses NTSS anyways, but for ships, not stations, like the NTSS Raven, it'd just get confusing.

The reason I proposed N(Role)(Type) in the first place was due to lore reasons, and is more commonly used on higher RP servers.

You don't want too many syllables in a prefix, afterall, they should clearly define what something is without being too long, shortened to as short as possible, hence why most other servers use N(R)(T) rather than NT(R)(T) or NTSS, TG is the only one to have used them from what I've seen, and as said before, it's for ships.

Do keep in mind, too, these are corporate acronyms. They're not designed to specifically sound good, they're designed to relay information at a glance. If you gave someone a sheet of what the letters meant, and then showed them the names of a structure, they could define it's type, ownership, and purpose. If you simply told them everything that has NTSS is owned by NT, they wouldn't be able to define it's purpose or type simply by looking at the name.

The uses of N(R)(T) are:
- Defines structure's ownership, Nanotrasen
- Defines the role of the craft, science, medical/hospital, mining/industrial, civilian/commerce, etc. 
- Defines the structure type, and with C, O, and P, it's relative size.
- Has 3 letters.

The uses of NT(R)(T)
- Defines all that N(R)(T) does above
- Longer, 4 letters.

The uses of NTSS (Standalone)
- Defines ownership of the structure, Nanotrasen
- Longer, 4 letters.

**Comment by FlamingLily** [comment]
hhhhhhhh okay I agree again man i'm a flip flopper eh?

**Comment by Gandalf2k15** [comment]
We dont need a change to the random gen names. I don't see the need.

**Pull request closed without merging**
