### PR TITLE
makes binary and trinary atmos machines use no power

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
removes the power use from trinary and binary atmos devices

## How This Contributes To The Skyrat Roleplay Experience
removing the power use from these machines can allow the engine to stay afloat longer-- the APC won't be drained so fast and cause massive issues (and massive explosions)

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
balance: trinary and binary atmos devices use no power now
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
hmm maybe add this to the lowpop measures thing so when we get to highpop it can be turned off?

**Comment by jjpark-kb** [comment]
> hmm maybe add this to the lowpop measures thing so when we get to highpop it can be turned off?

perhaps, yea... would you be able to put that in your PR?

**Comment by Gandalf2k15** [comment]
yeah sure

**Comment by Gandalf2k15** [comment]
incorporated into https://github.com/Skyrat-SS13/Skyrat-tg/pull/25837

**Pull request closed without merging**
