### PR TITLE
[SEMI-MODULAR] Multilinguist Quirk!

### PR DESCRIPTION
**Pull request by RimiNosha**
## About The Pull Request
Allows you to have five languages total!

Trade off? Ten whole points! That's a hefty price to pay for a positive quirk that only gives you extra fluff with fellow crewmembers, I think!

Disclaimer: I have no idea what the language balance is, but with the ashtongue PR being merged, I think this hopefully should be 100%  crewmember-oriented fluff!

Of course, any tips and suggestions are more than welcomed, along with just telling me my 10-minute PR isn't good for SR!

## How This Contributes To The Skyrat Roleplay Experience
It's feasible for folk to have a comprehension of several languages, I think, so this would be fun for those who like flexing their language skills!

And with this quirk's cost, it's guaranteed to produce some quirky characters for those who pick it, which'd be fun to see and RP with!

## Changelog

:cl:
add: Multilinguist, which gives you two language points for the cost of 10 balance.
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
This seems like way too much for the way our languages are right now. Half of them are meaningless, and we already have people filling their third slot with nonsense just because they feel the need to fill it. Not to mention, this takes away from the usefulness of curators/pAIs/circuit translators.

**Comment by RimiNosha** [comment]
Yea, figures that'd be an issue...

I'll leave this open for a bit, but now that you brought up that point, I'm likely gonna close this- depends on what the overall consensus is though!

**Comment by ghost** [comment]
We already have a trait for this, trait points for 2 language points .-. This pr is redundant

**Comment by Zonespace27** [comment]
Resoundingly "eh" about this PR, even with the high cost i question why one person needs to know so many languages

**Comment by RimiNosha** [comment]
Yup, closing then- It was an interesting idea in my head, but this does indeed seem pretty useless and unwanted!

**Pull request closed without merging**
