### PR TITLE
[Ready] [Fully Modular] Xenomorph Balancing - Buffs & Speeding Tickets

### PR DESCRIPTION
**Pull request by KathrinBailey**
## About The Pull Request
**Take One:**
**Health**
• Hunter & Drone: 125 => 150
• Sentinel: 150 => 200 
• Praetorian 250 => 350
• Queen 400 => 500
**Damage**
• Drone: 20 => 20, attack delay 1 => 0.75
• Hunter & Sentinel: 20 => 25, attack delay 1 => 0.75
• Praetorian: 20 => 40, attack delay 1 => 0.75
• Queen: 20 => 50, attack delay 1 => 0.75
**Speed Slowdown Modifier:** _0 is human speed, higher numbers are slower._
• Hunter: -1 => -0.5
• Drone: 0 => -0.2
• Sentinel: 0 => 0
• Praetorian: 1 => 1
• Queen: 3 => 1.5

Also adds flavour text saying xenos are somewhat intelligent, they know what virology is, they know what the brig, armoury and security is. They also are warned not to attack the AI unless they want to build a nest there, the xeno perceives the AI has spotted them or the station crew's threat level is overwhelming (IE security has combat mechs).

## Why It's Good For The Game
Xenomorphs are, as of now, laughably weak. Hunters are so fast you're fighting the game more than the hunter themselves. This should make hunters less frustrating and playing xenomorphs in general more fun. Keep in mind, a laser does 40 damage instead of 20 to a xenomorph. Prior to this, you could send two assistants, holding two eguns or laserguns in each hand, and they'll annihilate a xenomorph nest. This changes it so you maybe have to send three assistants.

We shouldn't have antags that are so weak their threat level is just laughable. So, here we are. Xenomorphs won't be so laughably easy to ignore.

## Changelog
:cl:
balance: Xenomorphs are now no longer laughably weak and easily to wipe out. Queens are faster, hunters are slower. Xenomorphs do more damage in general, the bigger they are, the harder they hit!
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Suggesting 3 xeno trial rounds + 1 week test merge.

**Comment by Oscari-pog** [comment]
Putting the "stationwide" into the "stationwide threat" that xenos are. Good PR.

**Comment by chefferz** [comment]
Things needed to semi balance this.

Make knockout time far less than it currently is when hugged, and resisting out of nests easier and not two solid minutes. If it's going to be made easier to knock people down/do more limb damage, then it should be easier to escape when caught.

The ice box station is an absolute pain in the ass to deal, because with this speed buff now all they got to do is make some satellite nest, hug, and drag you through the cold snow where you die to freezing because you're knocked out the entire time. This is changing the dynamic too much.

**Comment by chefferz** [comment]
Things needed to semi balance this.

Make knockout time far less than it currently is when hugged, and resisting out of nests easier and not two solid minutes. If it's going to be made easier to knock people down/do more limb damage, then it should be easier to escape when caught.

As an example, ice box station is an absolute pain in the ass to deal with xenos as-is, and even with their current speed now all they got to do is make some satellite nest, hug, and drag you through the cold snow where you die to freezing because you're knocked out the entire time. This is changing the dynamic too much with how long major wounds take to heal.

This PR in general was made because Kathrin observed a round where a bunch of mechs were made in response to a xenomorph infestation, I really do not believe they need this strong of a movement buff, or damage buff, particularly with how long it takes to get revived if you actually do die. If mechs are the main issue, make their damage penetrate armor/code to do damage to mechs.

**Comment by Hemlock32** [comment]
Higher mobility, damage and health...? Erm... I might be crazy, but, if you give them literally everything from what I consider a triangle of power... That's generally something considered overpowered... Glass canons, immobile tanks. Both those are considered balanced. Titanium canons with extreme mobility? Not so much considered balanced.

**Comment by KathrinBailey** [comment]
> Higher mobility, damage and health...? Erm... I might be crazy, but, if you give them literally everything from what I consider a triangle of power... That's generally something considered overpowered... Glass canons, immobile tanks. Both those are considered balanced. Titanium canons with extreme mobility? Not so much considered balanced.

It's very evident that you haven't played as or against xenomorphs in a long time outside of maybe CM. You definitely haven't played them whilst they have been testmerged.
1. Hunter speed is **nerfed.**
2. Queen is still **incredibly** slow, they've just gone from completely defenceless, to completely defenceless unless all of security are wearing EVA suits, are starving, are carrying dufflebags, and have one leg destroyed. Maybe they be able to catch up to them.
3. Xenomorphs still take 2x damage from all burn damage. Welders hit for 30, a single laser hits for 40. Having two lasers is 80 damage. They're all laughably squishy, Queen included.
4. You're nearly always massively outnumbered, and if the crew constructs a single combat mech, the only way you can destroy it is to force the player of the mech to crash their game and have to rejoin and wait the BYOND 30 seconds, and even then, you'll need multiple xenomorphs attacking the mech to destroy it before the player rejoins.

So far all of these changes aren't considered far enough, even with Azarak's combat changes no longer testmerged. It's likely a few other buffs will happen to make Xenomorphs viable, like spawning with two larva and making larvae hatch faster from hosts.

**Comment by Gandalf2k15** [comment]
You'll need to buff them some more.

**Comment by SpookyTheFox** [comment]
Due to the higher damage and the combat rework, xenos are a 1 hit knock down right now, which is pretty much automatic death in space game. After playing a few rounds of this monstrosity, all the damage and attack delay changes need to go. Remember that this is a role play server, you can't expect crew to fight this with the correct procedures and weapons.

**Comment by Jeweledbug** [comment]
Why are buffs never incremental. Why do we give huge amounts of health, speed, etc to Xenos like this rather than add a little and keep boosting it if it's not enough. I really... really don't get this. Whether it's blobs, combat, xenos, etc. It's never just small changes to see if it fits. Why such massive improvements for a mid round.

**Comment by KathrinBailey** [comment]
> Why are buffs never incremental. Why do we give huge amounts of health, speed, etc to Xenos like this rather than add a little and keep boosting it if it's not enough. I really... really don't get this. Whether it's blobs, combat, xenos, etc. It's never just small changes to see if it fits. Why such massive improvements for a mid round.

I have absolutely no idea what you're talking about.
This is an incremental buff. This PR has been testmerged for two or so weeks, and has been changed in literal increments.
If you want to know the purpose of this PR, read the description given to it.

**Comment by chefferz** [comment]
Xenomorphs are "laughably weak" because their entire purpose is to snowball and dominate the station.

They are literally like Zerg in Starcraft. Weak by themselves, but as an army built up can wreck.

These changes are genuinely not needed, because even normally they are, when played by a person that is semi knowledgeable about locations and mechanics, able to destroy.

**Comment by Jeweledbug** [comment]
> > Why are buffs never incremental. Why do we give huge amounts of health, speed, etc to Xenos like this rather than add a little and keep boosting it if it's not enough. I really... really don't get this. Whether it's blobs, combat, xenos, etc. It's never just small changes to see if it fits. Why such massive improvements for a mid round.
> 
> I have absolutely no idea what you're talking about.
> This is an incremental buff. This PR has been testmerged for two or so weeks, and has been changed in literal increments.
> If you want to know the purpose of this PR, read the description given to it.

I'm really not sure If I am on the same page if I see virtually double the effectiveness of Queens and praetors as well as stronger over all xenos. It's a huge boost overall and really _really_ shows with xenos now. Especially with no real limits on their meta knowledge.

I see this as part of a larger whole in progression on skyrat. The continuous push to make mid rounds deadlier and deadlier to the point where even TG main would give us weird looks. Even though they understand that they're not really supposed to lead to a round end. They're an addition to chaos. The sauce on the ribs. They are what makes you go "We already have X and Y, and now we have Z? Could this day get any worse!" They are never ever intended to be the focus of the round.

**Comment by Gandalf2k15** [comment]
Overdue in merging, full merging now.

**Pull request merged**
