### PR TITLE
Adds Cargo/QM Gorkas and Turtlenecks

### PR DESCRIPTION
**Pull request by ghost**
image
image

## About The Pull Request
Adds Cargo Gorkas/Gorka Jackets and Cargo Turtlenecks, as well as Quartermaster versions with silver badges/trims!
The Cargo outfits can be found in loadout/vendors, and the QM versions only in the loadout.
_Also just a note, they're coded in with the earlier Utility Port I did that ported oldbase outfits, seeing as they were late-oldbase additions anyways that I was recently asked to re-add by their creator, Dragonfruits. The jacket is a re-texture of another gorka jacket to be added later, too, so thanks to the creator for that!_

## Why It's Good For The Game
New outfits are fun. Oldbase outfits are fun. Sexy Gorkas are sexy.

## Changelog
:cl:
add: Added Cargo/Quartermaster Gorkas (and Gorka Jackets) and Turtlenecks, available in the loadout and in the cargo vendor - Thank you to Dragonfruits for the sprites!
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Love it, cheers for porting this back over from oldbase

**Comment by ghost** [comment]
> 
> 
> You currently have a negative Fix/Feature pull request delta of -25. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

Begone bot, I'm re-adding old stuff ;-;

**Comment by thestubborn** [comment]
uh oh, stinky conflict


but anyway, good to see someone's (hopefully) using those gorkas i threw into the sprites
you gonna do more for other departments? like a sec camo gorka (I was thinking to use the smock i took from ww13, think its erbsenmuster)

**Comment by ghost** [comment]
> 
> 
> uh oh, stinky conflict
> 
> but anyway, good to see someone's (hopefully) using those gorkas i threw into the sprites
> you gonna do more for other departments? like a sec camo gorka (I was thinking to use the smock i took from ww13, think its erbsenmuster)

conflict is sprites, which is kinda making sense with the fact I added new ones, so I'll hope a maintainer can help me sort it out if not do it themselves x-x

and yea, if someone tosses me more sprites and some motivation, I'll probably add just about any clothing item as long as its not plain bad >w>

**Comment by thestubborn** [comment]
> 
> 
> > uh oh, stinky conflict
> > but anyway, good to see someone's (hopefully) using those gorkas i threw into the sprites
> > you gonna do more for other departments? like a sec camo gorka (I was thinking to use the smock i took from ww13, think its erbsenmuster)
> 
> conflict is sprites, which is kinda making sense with the fact I added new ones, so I'll hope a maintainer can help me sort it out if not do it themselves x-x
> 
> and yea, if someone tosses me more sprites and some motivation, I'll probably add just about any clothing item as long as its not plain bad >w>

orion i have a giant shame pile of sprites

**Comment by ghost** [comment]
ok now that i've seen this shame pile i'm gonna add some other cargo-related stuff so hopefully this isnt merged before tomorrow night

**Comment by KathrinBailey** [comment]
image
Why is it jaggy?

**Comment by ghost** [comment]
> 
> 
> image
> Why is it jaggy?

Thats just ss13 being ss13, if you look to the left of the secod picture the background tile is doing it too

**Comment by Draganfrukts** [comment]
I sprited them so I have to urge this to be merged

**Comment by ghost** [comment]
> 
> 
> I sprited them so I have to urge this to be merged

working on fixing the conflict RN then I'll ping someone to look at it, dont worry <3

**Comment by ghost** [comment]
motherFUCKER IT ADDED A NEW CONFLICT WHILE I WAITED FOR SOMEONE TO MERGE IT WTFFFF MAN

**Comment by ghost** [comment]
motherFUCKER

**Comment by Draganfrukts** [comment]
Death

**Pull request merged**
