### PR TITLE
Improves the color contrasting on colorable jackboots and colorable laceups

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
I had a complaint that it was hard to get good colors because there's not enough good contrasting, thus I aim to fix this problem:
image
image
image
image

## How This Contributes To The Skyrat Roleplay Experience
They do look a bit better this way

## Changelog

:cl:
imageadd: The color contrasting on recolorable jackboots and recolorable laceups has been improved
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
`modular_skyrat/modules/GAGS/icons/shoes/shoes.dmi`:
`boots` has two frames, and stray pixels in the bottom-left of left-face frame 1 
`laceups` has a stray pixel in the bottom-left of the back-face

Only two issues, fix 'em and icons'll be sound

**Review by GoldenAlpharex — COMMENTED** [review]
Looks good, although I feel like it's maybe the "front" texture that needs a little bit more contrast, perhaps? I dunno, it's hard to say.

**Comment by Paxilmaniac** [comment]
i could maybe do something about that

**Review by GoldenAlpharex — APPROVED** [review]
It looks nice, yes, yes.

**Pull request merged**
