### PR TITLE
revokes stealth blob removal

### PR DESCRIPTION
**Pull request by NotRanged**
## About The Pull Request

max_occurences was stealthily set to 0 in some PR without mention or discussion. Setting it back to 1 allows the random even spawner to actually roll it rarely once more. Additionally sets min players to 60.

## How This Contributes To The Skyrat Roleplay Experience

Stealth removal bad, blob good. Lowpop blob bad though.

Also brings back swarmers and xenos, since they were all disabled. Of course admins can still cancel events when they roll, if they are deemed unfit for the current round!

## Changelog

:cl:
add: Blob, swarmer, and xeno events should roll naturally again.
/:cl:

### CODE REVIEW

**Comment by sandshark808** [comment]
You can view the PR history of a specific file to see when it was changed. The PR that made this change was #5277.

**Comment by NotRanged** [comment]
Yeah, and it mentions nothing about removing blob.

**Comment by SpookyTheFox** [comment]
We have certainly had blobs since April. It was almost certainly changed to allow finer control elsewhere. You should talk to @hugmeorelse about this one, as he keeps very tight control over mid rounds, events, and dynamic.

**Comment by NotRanged** [comment]
Except that there is no 'finer control' with them right now. I can get a figure once foxbus stops being dead, but they occur easily less than once a week, perhaps once every two weeks since this change.

**Comment by SpookyTheFox** [comment]
That frequency is quite intentional, even that many is pushing it. Again, you need to talk to Xyel, it's set like that on purpose.

**Comment by lyricalpaws** [comment]
It also stealth disables xenos

**Comment by NotRanged** [comment]
explains why we haven't seen those in forever too

**Comment by ArdentSpark** [comment]
~~I distinctly remember seeing a PR that was "Resets xenos to TG baseline and disables them", I don't believe xenos were stealth disabled~~

Although saying this I literally cannot see this anywhere

I should really fact check my shit before spouting "uhhhhhhh ackshually I think x"

**Comment by SpookyTheFox** [comment]
> 
> 
> ~I distinctly remember seeing a PR that was "Resets xenos to TG baseline and disables them", I don't believe xenos were stealth disabled~
> 
> Although saying this I literally cannot see this anywhere
> 
> I should really fact check my shit before spouting "uhhhhhhh ackshually I think x"

You did not imagine it, it was done here: https://github.com/Skyrat-SS13/Skyrat-tg/pull/8139

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
