### PR TITLE
[SEMI-MODULAR][BOUNTY]Mindshield Damaging + Cult Mindshield Prevention

### PR DESCRIPTION
**Pull request by Vizoplez**
## About The Pull Request
Title, prevents cult from being mindshielded until deconverted, and also adds mindshield damaging

## How This Contributes To The Skyrat Roleplay Experience
One, cult currently has no reason to convert security the slow way (removing their mindshield, then trying to get consent), This however, adds the same maths used for calculating if it should deconvert a revolutionary, to decide if it should 'damage' a mindshield or not.

This has a visual icon, visible to all officers when a mindshield is broken.

Broken mindshields don't prevent against conversion, and give cult more incentive to try and 'break the will' of officers.

Also gives a huge message to nearby cultists so they know when to stop beating the shit out of an officer.

## Changelog
:cl:
add: Mindshield damaging
balance: Cult are no longer able to be mindshielded while still a cultist.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Why do cultists need consent to indoctrinate people into their cult? It's brainwashing.

**Comment by Vizoplez** [comment]
> Why do cultists need consent to indoctrinate people into their cult? It's brainwashing.

Ask someone else about that, this PR only addresses cultists being able to mindshield themselves with little consequence


And allows for mindshields to break, requiring removal of the mindshield, then reimplanting it

**Comment by ForrestWick** [comment]
> Why do cultists need consent to indoctrinate people into their cult? It's brainwashing.

We'll cross that bridge when we get to it tbh, the main issue with cult right now is a lotta people dont like it because it's just stupidly gamer and hard to learn, so they dont wanna even touch it and would rather run away from it entirely, which is kinda why they dont wanna be converted

**Comment by ForrestWick** [comment]
> > Why do cultists need consent to indoctrinate people into their cult? It's brainwashing.
> 
> We'll cross that bridge when we get to it tbh, the main issue with cult right now is a lotta people dont like it because it's just stupidly gamer and hard to learn, so they dont wanna even touch it and would rather run away from it entirely, which is kinda why they dont wanna be converted

And before someone says anything about this, if people wanna play the game a certain way even if it's outside what you view to be the proper way to play, they have ever right to have their fun if it isnt actually hurting others. You can argue that cultists get hurt cause red eyes and halos are tied to station pop, but we can easily fix that

**Comment by Gandalf2k15** [comment]
Given the indepth discussions on discord this won't be getting merged

**Pull request closed without merging**
