### PR TITLE
Disables the electrical welder and brings back OG e-welder, pending fixes.

### PR DESCRIPTION
**Pull request by FlamingLily**
## About The Pull Request
Title

## Why It's Good For The Game
It's incredibly broken, to the point where people (or at least, myself) would rather forgo it for a standard welder. Making it the only option at this stage is... a bad idea.

## Changelog
:cl:
fix: brings back the classic experiemental welder, pending fixes to the electrical welder
/:cl:

### CODE REVIEW

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
please change the welding tool to the original in:
code/game/objects/items/storage/belt.dm

I'm not sure why the research unlockable welding tool is getting such a heavy nerf.
This also fucks over Ashwalkers a ton, so yeah.
An electrical welding tool should be something else.

**Comment by Gandalf2k15** [comment]
> please change the welding tool to the original in:
> code/game/objects/items/storage/belt.dm
> 
> I'm not sure why the research unlockable welding tool is getting such a heavy nerf.
> This also fucks over Ashwalkers a ton, so yeah.
> An electrical welding tool should be something else.

It's about the same level of power, it's just as good as the old one, and faster. It should work.

**Comment by FlamingLily** [comment]
> 
> It's about the same level of power, it's just as good as the old one, and faster. It should work.

It SHOULD work, but it doesn't.

It doesn't fix cyber limbs, it doesn't weld things like cameras onto walls, there's too many bugs with it for it to be a viable replacement to the experimental welder at this point in time.

**Comment by FlamingLily** [comment]
FUCK

**Comment by FlamingLily** [comment]
> FUCK

trying to code on my phone was a mistake

**Comment by softcerv** [comment]
> 
> 
> > It's about the same level of power, it's just as good as the old one, and faster. It should work.
> 
> It SHOULD work, but it doesn't.
> 
> It doesn't fix cyber limbs, it doesn't weld things like cameras onto walls, there's too many bugs with it for it to be a viable replacement to the experimental welder at this point in time.

The cybernetic limb thing is probably the biggest issue that I've ran into with the electric welder so far.

**Pull request merged**
