### PR TITLE
Prison Wars Episode 6: Return of the Genpop

### PR DESCRIPTION
**Pull request by KathrinBailey**
## About The Pull Request
• Ports genpop from Oracle https://github.com/OracleStation/OracleStation/pull/419 and Citadel https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9072.
• Shifts genpop IDs to 80 and 81 for enter and leave.
• Gives blueshield and all of sec the access.

## Why It's Good For The Game
Genpop is less boring than brig cells. With sentences of up to 30m for murder, prisoners should be able to spend time in prison instead of the brig.
This is a very good system for giving roundstart prisoners some friends.

## Changelog
:cl:
add: Oracle's Genpop infrastructure ready to be placed on maps for Genpop prisons.
add: Access for genpop for all of secutiy.
add: Secret questline for Butterlords that want to mount this opportunity and use their blade.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Can you make the turnstiles doors? It sucks how uncheeseable they are. Make them standard airlock doors.

**Comment by CameronWoof** [comment]
Genpop is fine for longer sentences, but for shorter stays or violent criminals (martial arts are a VERY common buy here) it makes much more sense to keep the person in a short-term cell or isolation, if there are other prisoners already. Better prisoner management tools are nice but please do not remove the short-term cells like you did last time.

**Comment by KathrinBailey** [comment]
> onger s

Nah I only removed them under the assumption people would actually use genpop instead of sticking people in the brig cells for 15m, I'm leaving the brigs as they are.
All that changes is you'll be able to use the turnstile to get from the prison, to your locker full of stuff, then you can get changed and call someone to let you out.

**Comment by KathrinBailey** [comment]
image
image
It's all working.

**Pull request merged**
