### PR TITLE
[MODULAR] Makes showers clickable with mobs on them by adjusting their layer.

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request

This PR raises the showers layer to that above mobs so that it can be interacted with easier and look correct.  
## Before
dreamseeker_JCspm4IjxF
## After
dreamseeker_wD0puc0syG

## How This Contributes To The Skyrat Roleplay Experience

It's great to be able to interact with a shower when someone is on the tile as one. Notably on blueshift. 

## Changelog

:cl:

fix: Showers now layer properly above mobs. 

/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/10318
you were told to bring this upstream

**Comment by Gandalf2k15** [comment]
Take it upstream.

**Comment by nevimer** [comment]
nah, no gbp

**Comment by nevimer** [comment]
someone else will have to do it since i don't want to be associated with any of the tgstation dramas.

**Pull request closed without merging**
