### PR TITLE
[MODULAR] Removes pillows from Grimoire Purpura

### PR DESCRIPTION
**Pull request by softcerv**
## About The Pull Request
Does as the title says.

## How This Contributes To The Skyrat Roleplay Experience
The pillow structures generated by the pillows can be used to farm cloth. Until pillows are refactored, it's best that we have them removed from Grimoire Purpura to prevent abuse.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
 
image

</details>

## Changelog

:cl:
fix: removes pillows from Grimoire Purpura, preventing infinite free cloth.
/:cl:

### CODE REVIEW

**Review by Zonespace27 — APPROVED** [review]

**Comment by YakumoChen** [comment]
Is it possible to just make a child of the pillow with the deconstructing action (wirecutters?) just doing an early return?

**Comment by softcerv** [comment]
> Is it possible to just make a child of the pillow with the deconstructing action (wirecutters?) just doing an early return?

Even if I did that, I would need to update the code for the prop summoner to account for structures, which is something that I'd rather not deal with. Especially since with the pillow structures, you can put multiple pillows on a pile.

**Comment by YakumoChen** [comment]
Make the pillow structure unable to use the grimoire pillows then

**Comment by softcerv** [comment]
> Make the pillow structure unable to use the grimoire pillows then

More than that would need to be done. I don't feel like adding more onto the organic interface code for something like this to work. If you wish to handle it in a future PR, you are more than welcome to.

**Review by tf-4 — APPROVED** [review]

**Pull request merged**
