### PR TITLE
Revert "Revert "[MIRROR] Refactor area and turf lighting""

### PR DESCRIPTION
**Pull request by Gandalf2k15**
Reverts Skyrat-SS13/Skyrat-tg#7902

Keeping this open to track the issue.

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
image

**Comment by Seris02** [comment]
can you fix the issue that is when an admin places a map everything in that radius goes completely pitch black before you merge this?

**Comment by GoldenAlpharex** [comment]
> can you fix the issue that is when an admin places a map everything in that radius goes completely pitch black before you merge this?

Probably, yeah.

**Comment by GoldenAlpharex** [comment]
> can you fix the issue that is when an admin places a map everything in that radius goes completely pitch black before you merge this?

I checked with upstream and they already have a fix for this coming up :)

**Pull request merged**
