### PR TITLE
[MODULAR] Updates Arachne borg sprite

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Replaces Arachne borg skin with new version, as per request.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image
image
image
image
image
image

</details>

## Changelog

:cl: Baron
imageadd: Replaced Arachne borg sprite
/:cl:

### CODE REVIEW

**Comment by rosextango** [comment]
the sprite quality really doesn't hold up to the previous arachne models, nor do i see a need to replace them? i dunno, that's just my take on things

i would be fine if these were separate sprites, but... they aren't

**Comment by CandleJaxx** [comment]
yeah, i don't think this should be a replacement? adding another borg skin seems fine, but replacing a solidly made sprite with a-- relatively off-model, i guess? it doesn't contrast as well as most of the other borg sprites

**Comment by lessthnthree** [comment]
It was a request from the Arachne creator to remove the sprite.

**Comment by RimiNosha** [comment]
~~https://github.com/Skyrat-SS13/Skyrat-tg/pull/17449~~

~~The outcome for removing arachne was already decided.~~ (informed that this was given the go ahead by the decides of that PR, nevermind)

Also kinda shitty to not mention this in the title and changelog.

**Review by Zonespace27 — APPROVED** [review]
I think these look a lot worse, but the powers that be want it changed

**Comment by rosextango** [comment]
I thought the removal was denied?

**Comment by Zonespace27** [comment]
> I thought the removal was denied?

Outright removal, yes
Resprite, no

**Comment by rosextango** [comment]
I'm sorry, but this resprite looks awful compared to the sprites we had before.

**Comment by dawsonkeyes** [comment]
they could, at the very least, resemble the current sprites in overall layout or design language

**Comment by lessthnthree** [comment]
so make some :)

**Comment by rosextango** [comment]
Pretty sure Viro is already working on additional/new sprites for the Arachne borg. You should probably ask him/them. Not sure why you didn't ask them about changing their sprites?

**Comment by Zergspower** [comment]
I know it's beyond what we can do but yeah these are kinda... I guess i'm more confused by why we're keeping the name if they dont even look like arachnids anymore?

**Pull request merged**
