### PR TITLE
[Modular] Adds a bunch of new cargo packs for medical and engineering

### PR DESCRIPTION
**Pull request by NotRanged**
## About The Pull Request

Contains the following packs (contents, (cost total)):
**Engineering**
2x Industrial RCD (8k)
1x Advanced RCD (10k)
3x Material Pouches (3k)
4x double-cap emergency O2 tanks (3k)
3x advanced fire extinguishers (3.6k)
1x engineering hardsuit (2.6k)
1x atmospherics hardsuit (3.2k)
3x engineering inducers (1.2k)

**Medical**
1x medical hardsuit (2.6k)
1x NanoTrasen Defib (5k)
1x Medical Beam Gun (15k)

**Security**
1x security hardsuit (3.2k)

this PR also bugfixes the *hiss emote by turning it into *hiss1 so it doesn't conflict with xenos, because I accidentally pushed the fix to this branch so this is where it goes now

## Why It's Good For The Game

This adds a bunch of missing, limited supply, and a few normally unobtainable items to cargo crates for (what I believe; feel free to discuss) are balanced prices, incentivizing more use of the cargo bounties by the medical and engineering departments in order to get these new items.

## Changelog
:cl:
add: Added a bunch new cargo crates for engineering and medical.
fix: *hiss is now *hiss1 so it actually works again and doesn't conflict with xeno hiss.
/:cl:

### CODE REVIEW

**Comment by NotRanged** [comment]
If you know of any more items, devices, or machines of any department that could use being in a cargo crate feel free to let me know and/or suggest it here.

**Comment by SpookyTheFox** [comment]
HARD SUIT HARD SUIT HARD SUIT
THANK YOU

Sorry, I am very excited right now. It's been painful having six engineers and two hardsuits.

**Comment by RatFromTheJungle** [comment]
> 
> 
> If you know of any more items, devices, or machines of any department that could use being in a cargo crate feel free to let me know and/or suggest it here.

security hardsuits,
atmos gasminer kit maybe,
and most importantly
the hydroponics tray crate that TG stole from us

**Comment by GoldenAlpharex** [comment]
> If you know of any more items, devices, or machines of any department that could use being in a cargo crate feel free to let me know and/or suggest it here.

We need to be able to buy the Stellar, Donk and Executive carpets :)

**Comment by GoldenAlpharex** [comment]
> > If you know of any more items, devices, or machines of any department that could use being in a cargo crate feel free to let me know and/or suggest it here.
> 
> security hardsuits,
> atmos gasminer kit maybe,
> and most importantly
> the hydroponics tray crate that TG stole from us

Gasminer sounds super OP, and we can easily make hydroponics trays, just ask an engineer and they'll make one for you in no time.

**Comment by KathrinBailey** [comment]
I like it although I'm not sure about the medical beamgun, 10k seems rather cheap given what it can do.
Poke me if I forget to return to this in a few days.

**Comment by SpookyTheFox** [comment]
> 
> 
> I like it although I'm not sure about the medical beamgun, 10k seems rather cheap given what it can do.
> Poke me if I forget to return to this in a few days.

Medical beam gun would be fun to have more often, but I don't think it should be in cargo. The station has the Oddy for that functionality. On the topic of the beam gun, it could really use a buff to improve it's healing speed and maybe some wound care capability. It's a relic of many years past, and was intended for a very different and simple medical system. The hand held one should stay as ERT or space loot. Medical ERT in general needs some love, but that's another topic entirely.

I'm glad someone brought up security hard suits, that's also been a painful experience with a 12 man department sharing two suits.

**Comment by NotRanged** [comment]
Sec hardsuit - 3.2k (added)
Medical beamgun - 15k (was 10k)

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by Gandalf2k15** [comment]
All is good yes!

**Comment by SpookyTheFox** [comment]
I tried buying the medical hardsuit last night, in round # 604. It billed the station, and the crate with the hardsuit didn't show up on the shuttle. It was attempted twice. I'll have another look at this and try local testing it, but something might be not quite right.

**Pull request merged**
