### PR TITLE
[WIP] [Needs lore review] Cultural information - Cultures, Locations, Factions, language menu, cultural pay

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
ALL READY EXCEPT FOR ACTUAL LORE STUFF

Adds bay-like cultural information, each species has a set of possible backgrounds they can choose from. The backgrounds economic power affects your starting pay, because presumably you come from a wealthier background. Depending on the backgrounds you will also be able to learn some languages, or be forced to have them (i.e. lizards from lavaland must know draconic).

Lowered starting paychecks from 7 to 4 and added a bonus that depends on your backgrounds (3x(150 x econ power))
^^^This is regarding the STARTING cash
You get up to 6 linguistic points, which you spend on languages, 1 to understand it, 2 to speak it. Common and forced languages are inclusive for that cost.
Screenshots with some testing stuff still in, just to show the capabilities of the systems

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Review by Gandalf2k15 — APPROVED** [review]
Code is fine.

**Comment by Azarak** [comment]
Needs a lore pass n stuff too

**Comment by Azarak** [comment]
thank you git actions very cool

**Comment by Azarak** [comment]
a

**Comment by ShadeAware** [comment]
Jesus christ just merge this already, we're obviously not getting any lore any time soon at this rate.

**Comment by KasparoVy** [comment]
pls god

**Comment by ghost** [comment]
Do we have anyone currently, or even actively working on lore? I dug through the lore channel in the discord and found a few things, but it seems like it's been stale for a _while_, without any real progress being made, and what lore we do have only serves to **outline the basic factions and corporations.** Personally I'd love to see this test merged, as well as the lore get more worked on and updated in the future.

**Comment by Aphast** [comment]
give

**Comment by hugmeorelse** [comment]
weh

**Comment by KasparoVy** [comment]
Just gotta believe.

**Comment by lolman65** [comment]
how long is it till its merged?

**Comment by gonenoculer5** [comment]
Does this add Sagaru as a language out of curiousity?

**Comment by Stalkeros2** [comment]
When.

**Comment by NullDagaf** [comment]
> how long is it till its merged?

When we'll have lore. 🤡

**Comment by KasparoVy** [comment]
:(

**Comment by NullDagaf** [comment]
> > how long is it till its merged?
> 
> When we'll have lore. 🤡

Told ya.

**Pull request closed without merging**
