### PR TITLE
[MIRROR] adds alternate medborg sprites

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/54627
--------------------

## About The Pull Request

adds alternate medborg sprites

## Why It's Good For The Game

https://www.youtube.com/watch?v=bJMeQQBbd8Y

## Changelog
:cl:
imageadd: adds alternate medborg sprites
/:cl:

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Trust me on this one, just don't

**Comment by Kylerace** [comment]
Trust me on this one, just do

**Comment by Azarak** [comment]
hmm

**Comment by Azarak** [comment]
oh we already had those ha

**Comment by Azarak** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/1484

**Pull request closed without merging**
