### PR TITLE
Complete Freighter Remap

### PR DESCRIPTION
**Pull request by Lunar248**
## About The Pull Request
Completely remakes the Freighter, taking visual inspiration from DS-2, and from the original on the gameplay side of things. It's now a bit more ship-like in shape, and has been trimmed down in width, while trying to compact and modernize some aspects of the design.

Some of the entirely new things include a scrubbing network, more available vendors, a small armory to contain a couple surplus guns for the crew to use, and more deliveries intended for the station.

While I was at it, I also fixed some of the area subtypes, since they weren't showing correctly in SDMM, and I added missing ones.

## How This Contributes To The Skyrat Roleplay Experience
In short, the Freighter ghostrole has long been my favourite on Skyrat, and I feel like it has a lot of potential to be an interesting RP force in most rounds. I feel like this has been held back by the somewhat dated, clunky design of the old freighter, not to mention only a few crates meant to be delivered. Now, there's a better variety of crates, and the freighter itself should be more suited to RP.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

image
image
image

</details>

## Changelog

:cl:
add: Completely revamps Freighter ghostrole, adding a new map, while trying to keep the spirit of the original.
del: Removes the old Freighter map.
fix: Fixed the old area subtypes for the Freighter, and added new ones where they were missing before.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Actually really love the design, the armory actually BEING an armory or vault in that case. I adore the design, looks like an actual ship instead of just a rushed piece of development.

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
Few things.

<details>
<summary> Active Turfs </summary>
You have active turfs here.

image

</details>

<details>
<summary> Nitpicks </summary>
Subtype this locker.

image

Please find another way to run these pipes. Running them through walls isn't good practice.

image

Add closed blast doors here.

image

Two things here:
1. Add shutters to the kitchen counter.
2. Add some fluff objects to the tables so they're no so bare.

image

Consider spreading out the tables contents (add another table).

image

This button shares the same var `lockdown` with the doors in the bridge. Please add a new button for the bridge doors.

image

image

Remove this vendor. The other one is a subtype with more products. There's no need to have two of the same thing with a direct upgrade right next to it.

image

Move this iv-drip out from the crate please. It just looks goofy.

image

This is incredibly iffy for me. Either find a new MODsuit to put here, or consider using modules instead. This MODsuit can't stay.

image

Two more things:
1. Spread out the guns on the racks. It'll just look nicer.
2. Subtype the ammo crate.

image

Please name your airlocks.

I would also consider giving the freighter a little more uranium for the generator. Five or ten sheets (I don't know whats in code) should suffice.

</details>

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
You forgot a button for these blast doors.
image

Also please move this fire alarm, this is bad practice stacking wall mounts.
image

**Comment by Lunar248** [comment]
To clarify, there is a button for those doors, but it's secured in the vault, in a different area. Fixed the second issue, is there any other details you need to go over?
image
image

**Review by Jolly-66 — APPROVED** [review]

**Pull request merged**
