### PR TITLE
[Modular] Secmed sprite changes

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request

Updates the ugly jumpsuit and slightly touches up the labcoat, adds a custom belt for secmeds, only holds security gear.
image

## How This Contributes To The Skyrat Roleplay Experience

Peacekeeper stuff was *really* ugly. Nicer looking sprites are always nice.

## Changelog

:cl:
imageadd: Security medics have gotten a new shipment of clothing
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Eh, I much prefer the old ones. Make them both available.

**Comment by YakumoChen** [comment]
REDSEC? POG????

**Comment by Ebin-Halcyon** [comment]
> Eh, I much prefer the old ones. Make them both available.

gimme a sec, gonna readd it then.

**Comment by axietheaxolotl** [comment]
I'd much rather you don't just take things I made without crediting me.

also the red turtleneck just makes him look like a syndicate operative, and the white on the labcoat and vest looks like cumstains more then anything.

**Comment by Ebin-Halcyon** [comment]
> I'd much rather you don't just take things I made without crediting me.
> 
> also the red turtleneck just makes him look like a syndicate operative, and the white on the labcoat and vest looks like cumstains more then anything.

It's just a white secbelt with red accents, the original draft of the sec reskin had it before you. Quit making a problem out of nothing.
image
image

**Comment by YakumoChen** [comment]
> I'd much rather you don't just take things I made without crediting me.

Reminder this is an open source code base, credit is not required with this license, assuming it was merged somewhere else.

**Pull request merged**
