### PR TITLE
Disables hulk + A way to disable mutations

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request
Removes from the DNA console hulk. This mutation has not really seen much use outside of valid hunting, which is against server rules.

Also adds a way to disable mutations from the DNA console without outright removing them.

## Changelog

:cl:
balance: Hulk has been removed from the possible mutations.
/:cl:

### CODE REVIEW

**Comment by dawsonkeyes** [comment]
I don’t see why Hulk ought to be removed if validhunting is already against the rules

**Comment by Zonespace27** [comment]
I disagree, not with the change itself[^1], but with the concept of "throwing the baby out with the bathwater", simply removing something because it *can* be used to validhunt is poor justification, in my eyes.

[^1]: I don't care enough about hulk to argue for keeping it that much

**Comment by softcerv** [comment]
Even if I think the reasoning is questionable, considering that most of the server's population wasn't able to use this because this was human only, I don't consider this to be a great loss by any means.

**Review by GoldenAlpharex — APPROVED** [review]
Hulk was always hot garbage, it's never fun to deal with, and only had to be severely baby-proofed so people couldn't just easily grief with it. Honestly? Good freaking riddance.

**Comment by Iamgoofball** [comment]
hulk is in it's weakest form it's ever been, and you guys still removed it?

**Pull request merged**
