### PR TITLE
PDH Rebalance/Spellcheck

### PR DESCRIPTION
**Pull request by Draganfrukts**
## About The Pull Request

In this PR I address a couple balance concerns and fix some stuff. Also cool description.

## Why It's Good For The Game

-Currently the SOCOM is a 3 round burst, low firing delay and accurate gun that fires ///12mm///. It kills you in 5 hits and you have almost no time to react. This PR gives it some charm and still keeps it a very, very decent gun.
-john odst's gun is actually john odst's gun now!!!!

## Changelog
:cl:
balance: SOCOM is no longer a machine pistol. It is instead an integrally suppressed semi-automatic. It is now EMP resistant as a trade-off.
balance: Osprey has lost its EMP proofing. Sorry HoP!
tweak: All PDH handguns now have model names.
spellcheck: Fixed some typos in PDH descriptions, mainly the use of "pristegious"
spellcheck: Gave the SOCOM a reference to the game it came from. All PDH pistols now have an assigned "commonly issued" part of their descriptions, like Special Ops, Military, Law Enforcement and Corporate.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Nawww, too much of a nerf to the captains gun, leave it be 3rnd burst!

**Comment by Gandalf2k15** [comment]
Also it needs to keep its yellow stripe!

**Comment by Draganfrukts** [comment]
> Nawww, too much of a nerf to the captains gun, leave it be 3rnd burst!

Captain should never be an offensive role and the SOCOM is literally the exact opposite of defense. I can solo war ops with it.

**Comment by LocalizedDownpour** [comment]
Might be an upopular opinion here, but the Captain shouldn't be a combat role AT ALL. THe Sabre is already a robust melee weapon and fits the captain motif. They should get a 'antique' type weapon to fit that, not ostensibly the most powerful handgun in the entire game with only maybe the .50 BMG sniper rifle outclassing it.

**Comment by Draganfrukts** [comment]
> Might be an upopular opinion here, but the Captain shouldn't be a combat role AT ALL. THe Sabre is already a robust melee weapon and fits the captain motif. They should get a 'antique' type weapon to fit that, not ostensibly the most powerful handgun in the entire game with only maybe the .50 BMG sniper rifle outclassing it.

See this is the thing, it actually outclasses the sniper. Sniper has a firing delay of 40 (around 4 seconds per shot if TIDI is behacing) and a single-fire 5 round config. You need 2 shots to hardcrit, the TTK of the Socom is rivaling a Call of Duty game rn

**Comment by Gandalf2k15** [comment]
Undo the sprite changes and I'll allow it

**Comment by LocalizedDownpour** [comment]
Replace the Socom with like...a 1700's hand cannon with a comically high damage output but a comical reload cycle that takes a minute. One shot, deals 70 damage, has to be hand loaded.

**Comment by Draganfrukts** [comment]
> Replace the Socom with like...a 1700's hand cannon with a comically high damage output but a comical reload cycle that takes a minute. One shot, deals 70 damage, has to be hand loaded.

You are the CO of a research vessel in 2560, not Captain Charles O'Hemmington piloting a British Navy Ship on its way to India

**Comment by LocalizedDownpour** [comment]
> > Replace the Socom with like...a 1700's hand cannon with a comically high damage output but a comical reload cycle that takes a minute. One shot, deals 70 damage, has to be hand loaded.
> 
> You are the CO of a research vessel in 2560, not Captain Charles O'Hemmington piloting a British Navy Ship on its way to India

I mean you have a sabre...my point is that the Captain and HoP shouldn't have the most power weapons in the game bar none.

**Comment by Draganfrukts** [comment]
There's your bright color stripe on a gun made for stealth operations

**Comment by Gandalf2k15** [comment]
Seems fine.

**Pull request merged**
