### PR TITLE
[Modular] Ghost Cafe Tweaks.

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Fixes decals. Removes the jukebox. Stops implying death. Makes admin-tools IC appropriate. Gives missing chameleon gear (no headset or PDA though, honk.) Integrates with the ID card module properly. Adds a bolt to the new dorm.
Also resprites the stack spawners - which originally was just the ARCD anyways - to the new ARCD sprite, but r a i n b o w. And in a nice fade, too!

## Why It's Good For The Game
Feexes good.

## Changelog
:cl:
fix: The Cafe now is.. better equipped. With another bolt. Honk.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
While you're at it, could you add a bluespace RPED or two, since we can't print them but we're still getting some box of deluxe parts to upgrade the machines?

**Comment by unit0016** [comment]
> While you're at it, could you add a bluespace RPED or two, since we can't print them but we're still getting some box of deluxe parts to upgrade the machines?

Camera consoles can be used with the BSRPEDS for free upgrades on-station, sorry. The security lathe may not be there, but the cargo one sure as fuck still is, which can print outpost camera consoles. DS-1 at least has IC reasons to not do it, Ghost Cafe does **not.**

**Comment by GoldenAlpharex** [comment]
> > While you're at it, could you add a bluespace RPED or two, since we can't print them but we're still getting some box of deluxe parts to upgrade the machines?
> 
> Camera consoles can be used with the BSRPEDS for free upgrades on-station, sorry. The security lathe may not be there, but the cargo one sure as fuck still is, which can print outpost camera consoles. DS-1 at least has IC reasons to not do it, Ghost Cafe does **not.**

Then, can it be a normal RPED?

**Comment by unit0016** [comment]
> > > While you're at it, could you add a bluespace RPED or two, since we can't print them but we're still getting some box of deluxe parts to upgrade the machines?
> > 
> > 
> > Camera consoles can be used with the BSRPEDS for free upgrades on-station, sorry. The security lathe may not be there, but the cargo one sure as fuck still is, which can print outpost camera consoles. DS-1 at least has IC reasons to not do it, Ghost Cafe does **not.**
> 
> Then, can it be a normal RPED?

Yeah, that'd work.

**Comment by SpookyTheFox** [comment]
> 
> 
> > While you're at it, could you add a bluespace RPED or two, since we can't print them but we're still getting some box of deluxe parts to upgrade the machines?
> 
> Camera consoles can be used with the BSRPEDS for free upgrades on-station, sorry. The security lathe may not be there, but the cargo one sure as fuck still is, which can print outpost camera consoles. DS-1 at least has IC reasons to not do it, Ghost Cafe does **not.**

Good catch for DS-1, that needs to be fixed so the mechanics are impossible.

**Comment by unit0016** [comment]
> > > While you're at it, could you add a bluespace RPED or two, since we can't print them but we're still getting some box of deluxe parts to upgrade the machines?
> > 
> > 
> > Camera consoles can be used with the BSRPEDS for free upgrades on-station, sorry. The security lathe may not be there, but the cargo one sure as fuck still is, which can print outpost camera consoles. DS-1 at least has IC reasons to not do it, Ghost Cafe does **not.**
> 
> Good catch for DS-1, that needs to be fixed so the mechanics are impossible.

Question is, how? The best I've got is giving them a custom protolathe/circuit imprinter variant that has it's own departmental flag. That would be high maintenance as **fuck** though.

**Comment by unit0016** [comment]
Closing because merge conflicts.

**Pull request closed without merging**
