### PR TITLE
Reverts newsec

### PR DESCRIPTION
**Pull request by Gandalf2k15**
It is time.

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
wait

**Comment by GoldenAlpharex** [comment]
"missed a few files"
>removes 1500+ files

Nice

**Comment by Swiftfeather** [comment]
why

**Comment by Gandalf2k15** [comment]
this is not what i asked for but ok

**Comment by FlamingLily** [comment]
Local maintainer reverts Skyrat code to TG. 🥴

**Comment by GoldenAlpharex** [comment]
Over 2.2 thousand files now, whew

**Comment by FlamingLily** [comment]
I can't tell if this is a meme-PR poking fun of newsec haters and trying to be like "well I'll just remove ALL the modules then 😠" or a legitimate fuck-up but either way

whew

**Comment by Gandalf2k15** [comment]
Let's try this on a different branch

**Pull request closed without merging**
