### PR TITLE
Space ruins that annoyed me part 1: Blackmarket trader, abandoned satellite, alien tool lab

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
Does up the blackmarket trader and tool lab ruins, deletes the abandoned satellite because it never spawned to begin with and holds no purpose.

## How This Contributes To The Skyrat Roleplay Experience
Both of these ruins suffered from being one of the two hallmarks of a skyrat space ruin. In the case of the blackmarket trader, it was just a big rectangle with nothing interesting going on with it. In the case of the tool lab, it was an uninteresting "come get your free loot here!" type ruin.

I've changed both of these to hopefully remedy the issues I found with them both, check em out below in the proof of testing section.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

The new alien tool lab:

image

The new blackmarket trader:

image

</details>

## Changelog

:cl:
add: The blackmarket trader ruin itself has been given a significant improvement, hopefully really nailing that shady little outpost tucked inside of an asteroid theme I think it's been going for.
add: The alien tool lab ruin has been changed to be a bit more interesting than a box full of a full set of alien level tools.
/:cl:

### CODE REVIEW

**Comment by Lukaster42** [comment]
The blackmarket... how am i supposed to build a drug factory and techfab now?

**Comment by ghost** [comment]
RIP my satellite baby, god knows what was wrong with you but putting you down is probably  for the best

**Comment by Zergspower** [comment]
rip the seedy drug lab

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
Hi. Kept you waiting, huh?

<details>
<summary> Black Market</summary>

This is a complete circuit. 
image

Stylistic critique, use different airlocks here? And name them too!
image

Another small one here too.
We have the fluff shelves, could probably use them in the bay + add a little bit more decal fluff. I don't know, a blood splatter or something. Some idiot probably got gibbed once.
image

Either electrify all or none, and find an alternative for the electrified grills,
image

image

</details>

<details>
<summary> Alien Lab </summary>

Could probably make the lab itself a bit dingy. Aliens are not human after all :)
Plus environmental story telling is guuci.
image

Designate an actual area for this ruin. No, you do not need to make an icon for it (although would be appreciated no less).
image

I don't think there's anyway to put a body in a morgue slab or body bag, but if there is, more environmental story telling.
image


</details>

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
<details>
<summary> Black Market </summary>

Proper-itize the airlock name.
image

This is still a complete circuit loop.
image

</details>

Alien lab I'm satisfied with.

**Comment by Paxilmaniac** [comment]
monkeybusiness

**Review by Jolly-66 — APPROVED** [review]
I self owned myself.

image

**Pull request merged**
