### PR TITLE
Makes custom material walls use a lighter version of our walls as the base, instead of tg walls

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
What does this look like in game you might ask? I couldn't really think of anything besides glass that uses this but here you go:
image

## How This Contributes To The Skyrat Roleplay Experience
Funny moment when all of the custom material stuff uses tg walls

## Changelog

:cl:
imageadd: custom material walls (glass walls, pizza, meat, etc) will now use a lightened version of skyrat's wall sprites, rather than tg wall sprites
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Can you do a screenshot that isnt glass? Glass sucks for material walls and screenshots bc you can see the girder.

**Comment by Paxilmaniac** [comment]
> Can you do a screenshot that isnt glass? Glass sucks for material walls and screenshots bc you can see the girder.

The only other ones I can think of are meat and pizza walls but those are disabled through some means

**Review by GoldenAlpharex — APPROVED** [review]
Seems good to me! I wish we could update more of the walls that are coming from /tg/ to match ours (thinking about you, shuttle and titanium walls) some more, but I just don't know how worth it it would be considering how fast the wallening is coming along lately.

**Review by tf-4 — APPROVED** [review]
OK

**Pull request merged**
