### PR TITLE
Moves the void raptor pizza place from a weird asteroid in space to maintenance where the portal used to be

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

image

image

## How This Contributes To The Skyrat Roleplay Experience

Void raptor supposedly being a ship, its strange to have just an asteroid floating off to the side of it with a pizza place buried in it.

The second annoying part about it existing is that it's just the pizzeria ruin from icebox copied and pasted into space.

## Proof of Testing

Its in the about the pull request section.

Day 100 no map edit tag

## Changelog

:cl:
add: Void raptor now has an abandoned pizzeria attached to the station where the portal to moffuccis used to be.
del: the abandoned pizza place stuffed in some sand floating alongside void raptor has been removed.
/:cl:

### CODE REVIEW

**Comment by theselfish** [comment]
It being removed fully was the better option.

Ruins shouldn't be baked into the map, it devalues them.

**Review by Jolly-66 — DISMISSED** [review]
Linters.

**Comment by OrionTheFox** [comment]
> It being removed fully was the better option.
> 
> Ruins shouldn't be baked into the map, it devalues them.

This is moving it **from being** a baked-in ruin to being a maintenance room.
Saying that 'ruins shouldnt be baked in' might as well mean that maintbars and abandoned robotic bays shouldn't pre-exist and it should be empty rooms.
The METEOR was a baked-in ruin, since it wasn't part of the station. This is an abandoned maintenance kitchen, same as other maps have, with a theme.

**Comment by Paxilmaniac** [comment]
> Linters.

nuh uh

**Comment by Jolly-66** [comment]
I'll review it this week.

**Review by Jolly-66 — DISMISSED** [review]
Make it more like a proper maint room.

Destroy the lights, make it look more banged up and dirty.
Really my only nitpick.

**Review by GoldenAlpharex — APPROVED** [review]
Jolly said it was okay, he's just not at his computer right now.

Merging this so we can fix another issue related to VR without having to deal with conflicts.

**Pull request merged**
