### PR TITLE
Billions must trauma team | Adds "STAND BACK MEDICAL TREATMENT IS HAPPENING" holoprojectors to cargo | Vending machine with thousands of balm

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

If you didn't gather it all from the title, this does three big things.

One, and the star of the show, the treatment zone holoprojector.

image

Does nothing mechanically outside of tell people to stay tf back while you're working on someone. Handy!

Second, the DeForest Med-Vend, a vendor you can now find randomly across the station, or make yourself if you wanted to.

image

This vendor holds almost the whole selection of DeForest medical items from cargo, at a markup compared to their cargo-ordered counterparts. And before anyone gets any ideas, it will ALWAYS be considered on station, even if it spawns at the interlink, so no freebies for you!

Third, and finally, the cost of the non-combat medpens has been slashed in half. While using them as a paramedic I found myself not wanting to use them despite how expensive they are. This is a concern I've had voiced by a few others as well, so I'm reducing the cost of the ones for healing. Stuff like the combat stims, twitch, demoneye, the like, are still their original price, however.

Except that wasn't finally! There's one more little thing:
The loadout now has both the yellow civil defense medkit, and the red roll-up frontier medkit in it, for people that want to take medical stuff but don't want the standard medkit. This one was requested by more than a few people.

## How This Contributes To The Skyrat Roleplay Experience

1. I'm trying to larp as trauma team but I don't have a giant "STAND BACK" hologram, this is lrp and must be fixed immediately.

2. Cargo is cool and all, but having the medical stuff for everyone be accessible at a markup through a vending machine means that people aren't entirely reliant on cargo for the medical items if they want them. It also allows medical staff to quickly restock at the vendor without having to wait for cargo, if they don't have that kind of time.

3. I think I said it pretty well in the about the pr section. People would get the pens then barely ever use them because of how expensive they are. Making them a little more accessible should make these fears a little less prominent.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image
image
image

</details>

## Changelog

:cl:
add: A new vending machine can be found around the station in some areas, selling DeForest medical supplies for an upcharge compared to cargo.
qol: To the relief of paramedics everywhere, a holoprojector can now be found in cargo for cheap that projects a big red "STAND BACK" 3x3 hologram to let people know you're working and need some space.
balance: Most non-combat medpens in cargo have been halved in cost.
image: Sprites for new vendor and hologram by yours truly.
/:cl:

### CODE REVIEW

**Comment by desertmote** [comment]
Now we just need policy so the paramedic is allowed to deck whoever doesn't abide to the hologram.

**Comment by Plum-but-gayer** [comment]
> Now we just need policy so the paramedic is allowed to deck whoever doesn't abide to the hologram.

decking someone is a 101 or at most a 201 so it's a perfectly acceptable IC escalation with our current policy :)

anyway this rules shout out paxil. Love getting the other medkits in the loadout, also.

**Comment by burgerenergy** [comment]
While I like the projector, I feel like the vendor is pretty niche and takes up already oversaturated vendor space. As a suggestion, though, maybe replace/add to the medical kiosk that's in the lobby? If memory serves a couple of maps have them situated here and there, not just medical, and it wouldn't be taking up _more_ space

**Comment by HoodMilk** [comment]
This PR is a violation of the Geneva Convention but yeah the projector looks useful.

**Comment by Paxilmaniac** [comment]
> This PR is a violation of the Geneva Convention but yeah the projector looks useful.

What's the UN going to do, stop me?

**Comment by ghost** [comment]
Could try upstreaming the holoprojector bit. The med projector on TG is kind of unloved, having a Triage marker would be cool

**Comment by Ephemeralis** [comment]
DeForest paid me to sponsor this message in exchange for paying my medical bills for my chronic liver failure that resulted from using their pens.

**Comment by projectkepler-ru** [comment]
> > This PR is a violation of the Geneva Convention but yeah the projector looks useful.
> 
> What's the UN going to do, stop me?

As someone who will soon be working with the UN
Yes, I will stop you

**Pull request closed without merging**
