### PR TITLE
[MODULAR][DNM] Disables borg shrink module

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Re-opens https://github.com/Skyrat-SS13/Skyrat-tg/pull/5186 which was closed in favour of #5211, but #5211 got closed.

Happy to close if something like https://github.com/Skyrat-SS13/Skyrat-tg/pull/5211 gets opened and merged.

## Why It's Good For The Game

This shit is still possible 
image

## Changelog
:cl:
del: The cyborg shrink module has been disabled
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Working on an alternative to #5211 which will leverage flags/a list of traits and defines so we don't have to keep standing up variables like 'has_snowflake_dead_sprite' and 'is_small' or w/e.

Would rather not've been driven by ultimatum PRs but c'est la vie, hopefully it'll be a more palatable solution.
Want to be smol, but that tennisball sized borg is just ridiculous lol. So totally agree with the rationale.

Will be pushing changes [here](https://github.com/KasparoVy/Skyrat-tg/tree/honey_i_shrunk_the_borgs) before PRing.

**Comment by tf-4** [comment]
More than happy for someone to do that. I would _prefer_ it was done that way in fact, but I don't have the time nor inclination to do it myself. So I'll close this when yours is merged.

**Comment by thestubborn** [comment]
based

**Comment by KasparoVy** [comment]
@tf-4 Thanks for keeping the ball rolling on this at any rate

EDIT: First pass completed, applied flags to cyborgs. Next up is to adjust logic that checked for the old variables

EDIT2: Testing now.

**Comment by NullDagaf** [comment]
I'm really not sure why people insist on having this in the first place, when it's very concept is abusable. No, it doesn't matter if you only have "big borgs" be able to use it, a smaller hitbox is a smaller hitbox.

**Comment by SpaceVampire** [comment]
I honestly agree with that.
I also think it makes most of the modules look worse in general.
Because it doesn't downscale well.
Even on the ones that it doesn't make super tiny.
Its still a pretty significant advantage.
To a unit that already doesn't have to deal with damage slowdown.

**Comment by Funce** [comment]
Looking to merge #6211

**Pull request closed without merging**
