### PR TITLE
[NON-MODULAR] Removes the Stealth Implant

### PR DESCRIPTION
**Pull request by FlamingLily**
## About The Pull Request
Removes the stealth implant from the uplink

## Why It's Good For The Game
Stealth implants are the epitomie of an anti-RP, anti engagement, anti *fun* antag tool. They're not at all conducive to an RP environment, providing an unlimited use, zero risk, get out of jail free card from any RP interaction. Just pop the funny box, and you're out of there.

They're also not at all engaging from a mechanics point of view. About to get into a fight with sec? lmao no, pop the funny box.

They are a zero accountability, zero engagement, free pass to be a shitter, and have no place on this server in their current state.

A rework of their abilities would be desired, however, I have not spent enough time understanding the code of the implant, and have no desire to do so. If such a PR is opened, I will happily close this one.

## Changelog
:cl:
del: Stealth Implant
/:cl:

### CODE REVIEW

**Comment by EvilCrimsonWitch** [comment]
Instead of a full removal, I'd love to see some changes done to the item. Can't say I've used it enough to have any amazing ideas, but anything from increasing its TC cost, increasing it's cooldown, making the time it takes to go fully invisible a bit longer, etc. I'd say it certainly deserves some sort of nerf though, it's just too good at escaping situations immediately.

**Comment by FlamingLily** [comment]
> 
> 
> Instead of a full removal, I'd love to see some changes done to the item. Can't say I've used it enough to have any amazing ideas, but anything from increasing its TC cost, increasing it's cooldown, making the time it takes to go fully invisible a bit longer, etc. I'd say it certainly deserves some sort of nerf though, it's just too good at escaping situations immediately.

Maybe. I'm not going to do that.

**Comment by Draganfrukts** [comment]
Very heated PR, and also you should make your changelog say something in the lines of "deletes stealth implant" instead of being emotional about it.

Several ways to balance it, price can be tweaked, and there's a number of mechanical counters to said item.

Any other contributor or developer who wants to put in the effort can tweak it to behave like it did on oldbase, where moving increased the alpha value of the box and it took a second to fade away upon activation.

From a personal standpoint, I don't care
From a development standpoint, removing something just because someone did something bad with it in one round is really bad practice and should be avoided.

I understand your frustration.

**Comment by FlamingLily** [comment]
> Very heated PR, and also you should make your changelog say something in the lines of "deletes stealth implant" instead of being emotional about it.

Changelog's broken, unless it gets fixed overnight it doesn't matter
> Several ways to balance it, price can be tweaked, and there's a number of mechanical counters to said item.

The only mechanical counter would be thermals, an antag item, I believe
> Any other contributor or developer who wants to put in the effort can tweak it to behave like it did on oldbase, where moving increased the alpha value of the box and it took a second to fade away upon activation.

Sure. But I don't have the desire to do so.

> From a development standpoint, removing something just because someone did something bad with it in one round is really bad practice and should be avoided.

I've outlined in my PR as to why it's not conductive to an RP environment. It's not about the round, though that round is certainly the driving force.

**Comment by FlamingLily** [comment]
If someone wants to rework it as an alternative solution to this PR
go for it.

But until then, I'll be PRing to remove it.

**Comment by Gandalf2k15** [comment]
Salt PR, try again with a more constructive standpoint.

**Pull request closed without merging**
