### PR TITLE
Ports OutpostStation From Unitystation... In Full.

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Ports the 'finished' version of outpoststation from unit0016/FrontierProgram , and by extension, Unitystation. Modified to be compliant with the skyrat version of the blueshield module. It is a fully functioning station with dorms, two mining shuttles, ferry dock, and whiteship dock. - The only missing features being toxins., disposals mailing, and functional navbeacons for simplebots. **!!** (I'm not sure why I'm avoiding adding it, honestly, there's areas pre-set for it and everything.)
Overview:
https://cdn.discordapp.com/attachments/640760727489085450/780446549682552883/unknown.png

## Why It's Good For The Game
Map variety is the spice of life. While my own project, MinStation, probably wouldn't fit here, Outpost plays like a goddamn dream despite it's vulnerability to meteors, and is a map, in my eyes, more recognizable than Box. While it's not 100% faithful, being based on an older version and needing to take liberties because of the labour shuttle and prison, it's more than well to do.

## Changelog
:cl:
add: Added Outpost model stations to rotation.
add: Added The Outpost Station Emergency Shuttle.
config: Added outpost to the map config.
server: Outpost's shuttle is a hulking monster and will probably ram into Delta station's maintenance.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
We can give this a test run.

**Comment by Gandalf2k15** [comment]
After looking over the map, it's good, but, it does lack the finishing touches. My suggestion is that we full merge this so people can add onto it.

**Comment by unit0016** [comment]
Aye. I'm gonna try to make a functioning whiteship for the beast and then fix up the three problems I noted in the PR... well, except the navbeacons, I have no gosh darn clue how those work, hah!

**Comment by unit0016** [comment]
It's occurred to me I should probably move those changes to a new branch so it doesn't muck things up. Doing that now.

**Comment by unit0016** [comment]
Closing after Round ID 41. Restarted in 15 minutes with the only fucking feedback I got being "smartfridge in botany please", "the teleporter needs cables", and "this is so bare" with a bunch of other people, including the fucking staff, just shitposting about how bad it was without actually being constructive or even letting it, you know, **be tested.**

**Pull request closed without merging**
