### PR TITLE
Genetics can no longer unlock Thermal Vision mutation

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
long overdue

## Why It's Good For The Game
Thermal Vision for stationcrew and security is unhealthy for the game, serving mostly as a tool to validhunt antagonists, and is a big kick in the balls for any antagonists trying to play stealthily, or hide away.

## Changelog
:cl:
del: Genetics can no longer unlock thermal vision
/:cl:

### CODE REVIEW

**Comment by CloverIsLucky** [comment]
Why not better make the Thermals unprintable in green/blueshift OR only make it be available for red alert instead of removing it?

**Comment by Azarak** [comment]
> 
> 
> Why not better make the Thermals unprintable in green/blueshift OR only make it be available for red alert instead of removing it?

How do you explain that ICly?

**Comment by ShadeAware** [comment]
Good riddance, Thermals cuck literally any attempts at stealth or hiding. Being able to see through walls isn't something anyone should have easy access to.

**Review by atakiya — APPROVED** [review]

**Comment by SpookyTheFox** [comment]
In light of new modes like assault ops, I think it would be prudent to keep these higher end abilities available.

**Pull request merged**
