### PR TITLE
disabler

### PR DESCRIPTION
**Pull request by FlamingLily**
## Changelog
:cl:
fix: sartge disabler
/:cl:

### CODE REVIEW

**Comment by lyricalpaws** [comment]
disabler

**Comment by unit0016** [comment]
disabler

**Comment by Ebin-Halcyon** [comment]
disabler

**Comment by ZephyrTFA** [comment]
Shadow nerf disguised as a buff, unbelievable

**Comment by KathrinBailey** [comment]
I haven't been keeping up, is it _supposed_ to be a disabler?

**Pull request merged**
