### PR TITLE
Ensuring all of our maps will get compiled by the Compile Maps action

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
## About The Pull Request
**FAIR WARNING**: CI will likely fail from this, simply because of the sheer amount of maps that now will be loaded and that were never loaded by the action before. That's expected, and that's what I want.

I'll see what needs to be fixed, and depending on the amount of broken stuff I'll either make another PR or commit that directly to this PR.

## How This Contributes To The Skyrat Roleplay Experience
Ever wanted to have functional maps that are properly compiled before being on the main server to ensure that there's no easy-to-fix runtimes? I have.

## Changelog

:cl: GoldenAlpharex
fix: All maps will now properly be covered by the GitHub Compile Maps Action, meaning that we'll finally know of all the bugs on our maps before merging PRs that break stuff.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Hmmm, this does less than I expected it to. I'll see about changing things around, perhaps having more Integration tests runs at the same time, one on each map, without the create_and_destroy thing... Or maybe no unit tests at all. Just some food for thought.

**Comment by ORCACommander** [comment]
there are 47 maps that are in the modular_skyrat directories.

**Comment by GoldenAlpharex** [comment]
> there are 47 maps that are in the modular_skyrat directories.

Is there? Which ones?

**Comment by ORCACommander** [comment]
image

**Comment by ORCACommander** [comment]
looks like space ruins and the like are already excluded from all maps on tg anyway...

**Comment by GoldenAlpharex** [comment]
That's such a mess, we'll have to re-order that, we even already have a `skyrat` folder in the `_maps` folder.

If anyone's down to do some minor moving around, I'd be a very happy Golden.

**Comment by ORCACommander** [comment]
indeed it should be one or the other.

**Comment by GoldenAlpharex** [comment]
It should be good to merge, honestly.

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
