### PR TITLE
Members of Centcomm and Command can no longer be thieves

### PR DESCRIPTION
**Pull request by Zonespace27**
## About The Pull Request
All heads + Blueshield and NT Rep can no longer be thieves

## How This Contributes To The Skyrat Roleplay Experience

Heads shouldn't be antags, per golden:
image

## Changelog

:cl:
fix: Heads of Staff and Centcomm employees can no longer be thieves.
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
tried upstream?

**Comment by Zonespace27** [comment]
> tried upstream?

Hasn't been tried, but seems pretty clearly intended
image

**Comment by thestubborn** [comment]
then i'll defer to goof or someone knowledgable about tg related balance

**Comment by RatFromTheJungle** [comment]
> then i'll defer to goof or someone knowledgable about tg related balance

tg allows head antags, we don't, this is a skyrat thing

**Comment by thestubborn** [comment]
> > then i'll defer to goof or someone knowledgable about tg related balance
> 
> tg allows head antags, we don't, this is a skyrat thing

oh
image

**Review by tf-4 — APPROVED** [review]

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
I like it, it's just missing the Security roles.


Yes, I could change this in Dynamic, but I'd rather change it in the code to make it clearer, and so it's less of a pain for downstreams.

**Review by GoldenAlpharex — APPROVED** [review]

**Pull request merged**
