### PR TITLE
Soft revert of HoP's winter coat resprite.

### PR DESCRIPTION
**Pull request by SpaceVampire**
## About The Pull Request

Removes the changes done in https://github.com/Skyrat-SS13/Skyrat-tg/pull/8978, while keeping the actual sprites in the code for the moment. This also changes the stuff done to allow them to hold the energy guns, along with the armor on the parade jacket.

## How This Contributes To The Skyrat Roleplay Experience

This was done on Maintainer request.

## Changelog

:cl:
fix: The HoP coat has returned to it's old glory.
fix: The parade jacket no longer has random armor, along with gun-sized pockets. Sacrifice for your drip.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
To clarify, this was requested due to the sprite change being made to a singular Winter Coat, which means it doesn't look like any of the ones we have in-game currently, making it stick out, which isn't something I want to promote. If you'd like to have different wintercoats, it'd be nice to resprite more than just one. Especially if it's to make them look like a parade jacket with a hood (doesn't mean it's looking bad at all, it just looks too close to the parade jacket)

**Comment by GoldenAlpharex** [comment]
However, I'd be more inclined to have it if it was something that could be chosen, rather than just an imposed look for it.

**Comment by axietheaxolotl** [comment]
idc about reverting the icon, I was gonna add a reskin anyway. I care though about you removing the armour.

HoP's jacket has armour for three main reasons: 1) all parade jackets have armour already, Captain's and HoS'. 2) the HoP is a threat for many a reason, for access and giving AA, and there's a high chance he might have the spare ID or code on him, which is also incredibly valuable, hence why they have a gun and an armour vest in the first place. 3) It doesn't even have equal value to the HoP's main armour, and is worse in every stat.

There's no reason to take it away, not for balance, because the HoP could just wear the vest and get better armour. Not for aesthetics, and not for realism. There's no *good* reason to take away the parade jacket's armour. Besides maybe a hate boner for HoP's.

**Comment by axietheaxolotl** [comment]
If you're going to remove the armour from the HoP's jacket, remove it from all. Or don't, because that'll just make it so that no one will wear it, because it's an objective downgrade.

**Comment by axietheaxolotl** [comment]
Also, this isn't a "fix" this is a balance change. Fix implies it was unintentional, which it wasn't.

**Pull request merged**
