### PR TITLE
Gun Modernisation PR

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

This finally brings forth the new looking WW2 weapons I made back in the day, the spritework is by ironnhawk.

It gives them a few buffs here and there since they're modernised.

image

## Changelog
:cl:
add: Modern versions of the ww2 weapons!
/:cl:

### CODE REVIEW

**Comment by BrotherHangyul** [comment]
They look really cool but who's gonna use them? Syndicate or NT?

**Comment by Gandalf2k15** [comment]
> They look really cool but who's gonna use them? Syndicate or NT?

We're not sure yet. Perhaps an independent faction.

**Comment by BrotherHangyul** [comment]
> > They look really cool but who's gonna use them? Syndicate or NT?
> 
> We're not sure yet. Perhaps an independent faction.

russians 😳

**Comment by MLGTASTICa** [comment]
> > > They look really cool but who's gonna use them? Syndicate or NT?
> > 
> > 
> > We're not sure yet. Perhaps an independent faction.
> 
> russians 😳

serbians

**Pull request merged**
