### PR TITLE
De-crapifies the sec taser - by replacing it with a disabler

### PR DESCRIPTION
**Pull request by capsaicinz**
_"Don't tase me bro!"_

## About The Pull Request

Made in conjunction with #6925, offering a different take on working this taser out. Replaces the Armadyne taser given both to the security officer and sergeant with the classic disabler, without removing the Armadyne taser from the code. Gives the warden his disabler back, the poor thing!

## Why It's Good For The Game

Tasers suck. Tasers really, _really_ suck. Even during testing, I found that tasers were wildly RNG when it came to how fast it would work, how many shots it would take, and so on. Giving disablers back gives security a perfectly non-lethal form of cracking down on criminals, and a little bit more.. _motivation_, to yoink that ablative trenchcoat from the armory.

We always need more motivation for that, right?

## Changelog
:cl:
balance: replaces security officer and sergeant's taser with a disabler. gives the warden a disabler, too.
/:cl:

### CODE REVIEW

**Comment by lyricalpaws** [comment]
+1

**Comment by FlamingLily** [comment]
CDOs should get the shit taser (pepperballs are dumb but that's just opinion)

**Comment by CloverIsLucky** [comment]
Can the Correctional Officer get the disabler too?

**Comment by lyricalpaws** [comment]
> 
> 
> Can the Correctional Officer get the disabler too?

Give CO the shittified taser, actually. They dont need to stop heavily geared antags, and sometimes just need to give prisoners a little jolt. They have riot gear already and a batong, which is more than enough to deal with prisoner threats usually.

**Comment by lyricalpaws** [comment]
> 
> 
> CDOs should get the shit taser (pepperballs are dumb but that's just opinion)

See what I said above, keep peppers on cdos, and give co a taser

**Comment by capsaicinz** [comment]
i don't see why COs shouldn't get tasers, yeah. they're pretty cucked out of most sec gear roundstart, regardless. i declare "good."

**Comment by capsaicinz** [comment]
whoops forgot shitty co jacket doesn't have suit storage.

**Comment by Gandalf2k15** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/6921 - Incorporated into this, I've replaced the taser with a disabler.

**Pull request closed without merging**
