### PR TITLE
Assistants are no longer counted in Dynamic Threat Generation.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Assistants are no longer counted in Dynamic Threat Generation.

## Why It's Good For The Game
Ever wonder why some games result in there being 6 antags, 1 blob, 1 revenant, 2 xeno queens, 2 teams of abductors, and a partridge in a pair tree? It's because threat generation considers "crew" by the following standards
- Alive
- Has a client

Which means everyone typefucking on the Interlink is counted. Every syndicate agent on lavaland is counted. Every ashwalker, plant person, and golem is counted. Everyone in Interdyne is counted. Everyone typefucking in the ghost cafe is counted.

In this PR, it changes the standards to be
- Alive
- Crew
- Non-assistant

This should result in much fairer threat calculations. The reason why assistant checking is in there is because, and lets be real, 75% of assistants are here to erp or rp, 25% are here to fuck around. Maybe like out of 20 assistants in a round, 3 are considered useful to the station. It's a hard truth.

## Changelog
:cl: BurgerBB
balance: Assistants are no longer counted in Dynamic Threat Generation.
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
Also don't merge this because I haven't tested it yet.

**Comment by thestubborn** [comment]
Maybe have it be "assistants are only counted on station z level"?

**Comment by Gandalf2k15** [comment]
> Maybe have it be "assistants are only counted on station z level"?

Yes. Do this instead.

**Comment by GoldenAlpharex** [comment]
Also, you should probably make it so ghost roles aren't counted either.

**Comment by hugmeorelse** [comment]
> > Maybe have it be "assistants are only counted on station z level"?
> 
> Yes. Do this instead.

Agreed. I strongly recommend this.


> Also, you should probably make it so ghost roles aren't counted either.

Agreed.

**Comment by hugmeorelse** [comment]
> Also, you should probably make it so ghost roles aren't counted either.

This.

Also, this will give us more control. Whenever we don't have a lot of assistants but a higher player count, dynamic mode can be more intensive. If we have a lot of assistants but not many departmental players, it can be more relaxed. Dynamic mode configurations can be changed, so that there's not as many dead shifts either.

**Comment by BurgerLUA** [comment]
> Also, you should probably make it so ghost roles aren't counted either.

This is already done. Ghost roles aren't considered crew.

**Comment by BurgerLUA** [comment]
> Maybe have it be "assistants are only counted on station z level"?

No, the issue is that the vast majority of assistants usually don't do anything productive to the crew's interests by hanging around in the bar or other places. See how many people choose the "Off-Duty" role compared to people who stick with assistant. It's clear that the assistant role is used for people who don't want any responsibilities.

**Comment by BurgerLUA** [comment]
> > Also, you should probably make it so ghost roles aren't counted either.
> 
> This.
> 
> Also, this will give us more control. Whenever we don't have a lot of assistants but a higher player count, dynamic mode can be more intensive. If we have a lot of assistants but not many departmental players, it can be more relaxed. Dynamic mode configurations can be changed, so that there's not as many dead shifts either.

This is out of the scope of the PR.

**Comment by GoldenAlpharex** [comment]
> > > Also, you should probably make it so ghost roles aren't counted either.
> > 
> > 
> > This.
> > Also, this will give us more control. Whenever we don't have a lot of assistants but a higher player count, dynamic mode can be more intensive. If we have a lot of assistants but not many departmental players, it can be more relaxed. Dynamic mode configurations can be changed, so that there's not as many dead shifts either.
> 
> This is out of the scope of the PR.

I mean, no, you just answered my question. I was blind and didn't see the word "crew" in the PR description lol.

**Comment by BurgerLUA** [comment]
Also the reason why "z-level" isn't checked is because this would be too expensive. It would have to loop through all the players and check their z-level. I think the solution of checking just one variable once is acceptable.

**Comment by linnpap** [comment]
you could just count all assistants and half the number by ~50%

**Comment by thestubborn** [comment]
> 
> 
> > Maybe have it be "assistants are only counted on station z level"?
> 
> No, the issue is that the vast majority of assistants usually don't do anything productive to the crew's interests by hanging around in the bar or other places. See how many people choose the "Off-Duty" role compared to people who stick with assistant. It's clear that the assistant role is used for people who don't want any responsibilities.

Then maybe have assistants in the dorm/bar area excluded, or like linn said, have...dunno, five assistants count as one player?

**Comment by BurgerLUA** [comment]
I will not be adding any exceptions or taking suggestions on adding exceptions to things that are highly variable, such as location. What is currently implemented is fine codewise and sanity wise.

**Comment by ZephyrTFA** [comment]
> 
> 
> I will not be adding any exceptions or taking suggestions on adding exceptions to things that are highly variable, such as location. What is currently implemented is fine codewise and sanity wise.

A check for the station z level is literally a single proc call.

**Comment by FlamingLily** [comment]
> Also the reason why "z-level" isn't checked is because this would be too expensive. It would have to loop through all the players and check their z-level. I think the solution of checking just one variable once is acceptable.

I am almost 100% certain with a codebase as robust as TG that there's definitely a "get all mobs on z level" proc somewhere

**Comment by BurgerLUA** [comment]
Okay let me explain this once before people insist that people suggest things that just cannot be done without a massive complete overhaul of dynamic.

For nearly every length check of that global list, I would need to replace it for a for loop checking the following on a per player basis:
- if their z-level matches the station z-level (involves a get_turf check)
- if their job is assistant
- if their area is not in the bar or dorms or whatever (involves an istype check)

For looping through 100 players this is expensive. This would probably cause an overtime of 0.1 seconds per check. The solution I implemented is fine.

**Comment by BurgerLUA** [comment]
This PR is not stale.

**Comment by BurgerLUA** [comment]
This PR is not stale.

**Comment by BurgerLUA** [comment]
I just wanted to also touch on some things.

The dynamic configuration was shared with me and the problem with it is that it basically guarantees that every round will have I think 3-4 antags as the denominator for every antag type (except wizard) in rotation was set to 40, which means that for every 40 players one antag is to be allocated. If you look at any round, you'll see that it will always have 3 or 4 antags regardless of the ratio of assistants to actual jobs.

This is not a good solution as there are vastly different ratios of useful roles to assistant on different times in Skyrat. Usually later in the night people ERP more compared to the early hours for US residents. This PR should adjust for when people get their horny on late at night.

**Comment by Lauwma** [comment]
My issue with this is that some assistants are antags

**Comment by BurgerLUA** [comment]
> My issue with this is that some assistants are antags

They can still be antags with this. When generating threat, they're not counted as crew.

**Comment by Lauwma** [comment]
> > My issue with this is that some assistants are antags
> 
> They can still be antags with this. When generating threat, they're not counted as crew.

Yes but that means you are removing threats from people that can possibly get antag

**Comment by BurgerLUA** [comment]
> > > My issue with this is that some assistants are antags
> > 
> > 
> > They can still be antags with this. When generating threat, they're not counted as crew.
> 
> Yes but that means you are removing threats from people that can possibly get antag

No no, you don't understand. Assistants can still get antag from this.

**Comment by Lauwma** [comment]
I understand that they can get antag, just that it seems odd to not comptabilise in the threat individuals that can be antags.

**Comment by GoldenAlpharex** [comment]
@BurgerLUA there's a merge conflict.

**Comment by BurgerLUA** [comment]
> @BurgerLUA there's a merge conflict.

Fixed.

```
<<<<<<< Dynamic-Fix
=======
#include "modular_skyrat\modules\vox_sprites\code\datums\greyscale\config_types\greyscale_configs.dm"
#include "modular_skyrat\modules\vox_sprites\code\modules\clothing\head\head.dm"
#include "modular_skyrat\modules\vox_sprites\code\modules\clothing\shoes\sneakers.dm"
#include "modular_skyrat\modules\vox_sprites\code\modules\clothing\under\color.dm"
#include "modular_skyrat\modules\vox_sprites\code\modules\clothing\under\jobs\security.dm"
>>>>>>> master
```

**Comment by BurgerLUA** [comment]
Oh just remember when merging this, be sure to pay attention to how many traitors spawn each round and adjust accordingly to how much you think are needed.

**Comment by KasparoVy** [comment]
This is great and makes sense, very much looking forward to it

Many of the suggestions are confusing

**Comment by GoldenAlpharex** [comment]
@hugmeorelse I'm leaving it up to you to merge it whenever you have time to tweak with the Dynamic config the round right after.

**Comment by Gandalf2k15** [comment]
This was actually already achieved upstream.

**Comment by BurgerLUA** [comment]
makes u think

**Comment by BurgerLUA** [comment]
Wait where? I don't see the PR for it.

**Comment by Gandalf2k15** [comment]
image

**Comment by BurgerLUA** [comment]
You misunderstand this PR. This PR removes assistants from being counted completely.

**Comment by GoldenAlpharex** [comment]
@hugmeorelse Dynamic is your territory, make a decision about it when you see fit.

**Comment by tf-4** [comment]
This is currently not needed, as confirmed by the host.

**Pull request closed without merging**
