### PR TITLE
[Non-Modular] Ghostroles Now Apply Their Loadout Correctly

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Implements the loadout for ghostroles, as I originally intended wayy back with the quirk PR (but was too smallbrained to do)
I don't see this as problematic for the feature freeze considering it's simply bringing parity with the character event spawner and is expanding the use of a feature we already use. Tested with the syndicate prisoner role and worked just fine!

## Why It's Good For The Game
Being able to stylize is.. nice... 😳 

## Changelog
:cl:
expansion: Ghostroles now have their loadouts applied to them, bringing complete feature parity with character event spawners.
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
this doesnt work with ashwalkers right?

**Comment by unit0016** [comment]
> this doesnt work with ashwalkers right?

It does. But so do augmentations, so. So long as ashies have some modicum of roleplaying integrity..

**Comment by Elli-Skala** [comment]
finally, i can start with a maid dress as a ash walker

**Comment by unit0016** [comment]
> finally, i can start with a maid dress as a ash walker

Imagine being a gamer miner, full ashdrake armor, memento mori, nanites, virus, immortality talisman and a crystal that lets you turn into a cockroach.

And then just stumbling upon a tribe of lizardpeople, all in maid dresses.
Horrifying.

**Pull request merged**
