### PR TITLE
[MODULAR] Double-DonutStation.

### PR DESCRIPTION
**Pull request by SpaceVampire**
## About The Pull Request

This is an attempt at reworking Multi-Z DonutStation (Created by MMMiracles), for modern Skyrat.
Currently I am working to update everything to the new Smartpipe system.
Along with fixing other out of date paths, and adding all of our own changes.
Like the Blueshield, NT-Rep Office, and other stuff.
Hopefully I can be asked to actually finish this.
Current PR is a still a WIP, map now actually loads in DMM.

## How This Contributes To The Skyrat Roleplay Experience

More maps, and more Multi-Z maps are good. Just anything other then BoxStation.

## Changelog

:cl:
add: DountStation, a new tasty workplace environment!
/:cl:

### CODE REVIEW

**Comment by ForrestWick** [comment]
Donuts station was CBT before and genuinely unfun to play, so I'm gonna need some convincing that this version is going to work

**Comment by FlamingLily** [comment]
> 
> 
> Donuts station was CBT before and genuinely unfun to play, so I'm gonna need some convincing that this version is going to work

It's not box/meta/delta but again.

**Comment by KathrinBailey** [comment]
don't forget that supply pipes need to be layer 4 and scrubbers layer 2, if you ported this from bee then you're going to have to change it all.

**Comment by SpaceVampire** [comment]
> don't forget that supply pipes need to be layer 4 and scrubbers layer 2, if you ported this from bee then you're going to have to change it all.

It was taken from TG station, but you know. It's been a while.
This was just me making it so that all the current paths at least seemed valid in strongdmm.
So yeah. I changed a bunch of pipe related shit, trying to figure out if I broke stuff.
While the thing refuses to show up, even with what I assume at the correct config changes.

**Comment by IsaacTheSharkWolf** [comment]
best of luck with the project

**Comment by ForrestWick** [comment]
> > don't forget that supply pipes need to be layer 4 and scrubbers layer 2, if you ported this from bee then you're going to have to change it all.
> 
> It was taken from TG station, but you know. It's been a while.
> This was just me making it so that all the current paths at least seemed valid in strongdmm.
> So yeah. I changed a bunch of pipe related shit, trying to figure out if I broke stuff.
> While the thing refuses to show up, even with what I assume at the correct config changes.

What thing?

**Comment by SpaceVampire** [comment]
I just can't be asked to finish this at the moment.
Plus we already have other cooler maps in dev.

**Comment by ForrestWick** [comment]
> I just can't be asked to finish this at the moment.
> Plus we already have other cooler maps in dev.

Even despite my hatred of donut, it is sad to see you stop development for it. Hopefully you can pick it up later, cause it is something I feel we could give some attention to

**Pull request closed without merging**
