### PR TITLE
[DNM][Host] Revert [MIRROR] Dynamic 2022, Part 1 - Redesigning midround rolls 

### PR DESCRIPTION
**Pull request by nevimer**
This reverts commit ea6f252e810bea0d52be32a5b8a3fa6daf0d5b90.

## About The Pull Request

Temporarily disables new dynamic. Do not merge. 
## How This Contributes To The Skyrat Roleplay Experience

Round flow

### CODE REVIEW

**Comment by Iamgoofball** [comment]
You'll want to start coding more midrounds, I think.

**Comment by Zonespace27** [comment]
> You'll want to start coding more midrounds, I think.

This is in fact a part of the issue, we only have: (for heavy midround rolls)

- Ninja
- Ayys
- Benos
- Malf AI
- Blob
- Blob Infection
- (not) Space Dragon (random event only, the ruleset is disabled for ???)
- Pirates

**Comment by Iamgoofball** [comment]
It's probably time I break out Xyel's design doc and start coding a bunch of low-impact rulesets.

**Comment by Gandalf2k15** [comment]
this was fixed

**Pull request closed without merging**
