### PR TITLE
[Manual Mirror] Fixes headsets not using their proper worn sprites

### PR DESCRIPTION
**Pull request by ghost**
### Original PR: https://github.com/tgstation/tgstation/pull/72953

---

## About The Pull Request
You're probably wondering "They had worn icons?"
Yes, yes they do. No one fucking noticed.

image

## Why It's Good For The Game
Missing sprites fixed.

## Changelog

:cl: Ebin-Halcyon
fix: Headsets now have their old worn sprites back, did you ever notice it?
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
WHOOPS that was the wrong name hahaha oops

**Review by Ebin-Halcyon — APPROVED** [review]

**Comment by ghost** [comment]
💀  idk how 2 make new screenshots

**Comment by Zonespace27** [comment]
> 💀 idk how 2 make new screenshots

delete the old ones and run CI locally (or the screenshot tests, specifically, both work)

**Comment by ghost** [comment]
> > 💀 idk how 2 make new screenshots
> 
> delete the old ones and run CI locally (or the screenshot tests, specifically, both work)

Trying this had no result 😭

**Comment by ghost** [comment]
This is out of my hands. I've not gotten the actual requested assistance.

**Pull request closed without merging**
