### PR TITLE
[MODULAR]Re-nerfs batons to be acceptable again

### PR DESCRIPTION
**Pull request by Vizoplez**
## About The Pull Request
Why the fuck do we do this to ourselves

## Why It's Good For The Game
Batons shouldn't win a fight in 3 hits, nor should they strike fast enough to stunlock someone on your own

## Changelog
:cl:
fix: We now have the correct values from upstream /tg/ after they fixed batons being buggy
/:cl:

### CODE REVIEW

**Comment by capsaicinz** [comment]
this feels like a stupidly high cooldown for a baton. i'm not sure what pushed you to make this, but batons are already pretty shit on when it comes to cooldown as it is.

**Comment by Mavromino** [comment]
Security has been being nerfed into the ground recently. Already our default ammo makes our guns peashooters, 9mm literally does negative damage, and you want to nerf them more?

**Comment by Vizoplez** [comment]
This is the exact same value as /tg/ please fact-check what you have just said.

To let me explain. Very carefully.

Peacekeeper batons are not stunbatons. They are CLASSIC batons. This means they have no timer when knocking someone down, unlike stunbatons. They may do less stamina, this does not however affect the fact they are in reality, far, far better and less counterable by traitor adrenals than /tg/ batons.

Refer to #dev-discussion.

**Comment by Alanii** [comment]
I understand antag play is based around fragging security and preventing them from doing their jobs, but you may want to try different values than the previous "haha good luck getting 5 hits on someone in a fight while they run away."

When balancing items you should actually take into account of gameplay rather than numbers, because this nerf made the security baton one of those items some people would just ignore to use when its easier shoving people to the ground like every other person is able too than using the actual tools given.

But don't ask me, I play security. And those who do not play security know security's tools better as noted by every 'security-nerf PR' made by contributors who like to play antagonist. 

/shrug

**Comment by Vizoplez** [comment]
> Security has been being nerfed into the ground recently. Already our default ammo makes our guns peashooters, 9mm literally does negative damage, and you want to nerf them more?

You may be playing the wrong server, we just un-nerfed them and 9mm does 32 damage per shot, and 10mm magnum (peacekeeper btw) does 48 per shot.

**Comment by Vizoplez** [comment]
> > Security has been being nerfed into the ground recently. Already our default ammo makes our guns peashooters, 9mm literally does negative damage, and you want to nerf them more?
> 
> You may be playing the wrong server, we just un-nerfed them and 9mm does 32 damage per shot, and 10mm magnum (peacekeeper btw) does 48 per shot.

image

**Comment by Vizoplez** [comment]
> I understand antag play is based around fragging security and preventing them from doing their jobs, but you may want to try different values than the previous "haha good luck getting 5 hits on someone in a fight while they run away."
> 
> When balancing items you should actually take into account of gameplay rather than numbers, because this nerf made the security baton one of those items some people would just ignore to use when its easier shoving people to the ground like every other person is able too than using the actual tools given.
> 
> But don't ask me, I play security. And those who do not play security know security's tools better as noted by every 'security-nerf PR' made by contributors who like to play antagonist.
> 
> /shrug

batons are still far superior to shoving since they instantly do 40 stamina damage and instantly knock someone down, allowing you to press X and shove them again, hardstunning them for ~8 seconds.

**Comment by ForrestWick** [comment]
Some people brought up a good point on discord.

Why are people getting mad about sec doing herd and group tactics against antags while also nerfing their gear to enforce said tactics, which then nullify rp in most cases cause one accidental punch or shot means the whole scene is dropped

**Comment by Vizoplez** [comment]
> Some people brought up a good point on discord.
> 
> Why are people getting mad about sec doing herd and group tactics against antags while also nerfing their gear to enforce said tactics, which then nullify rp in most cases cause one accidental punch or shot means the whole scene is dropped

[](https://media.tenor.co/videos/b5fe53653709401a99df3d047ffb7508/mp4)


for real though, the reason security resort to group tactics is most of them are horribly unrobust, never use pepper spray or any other tools they are given, and instantly resort to a gun or baton which if any good antagonist knows how to counter, means they're dead.

As it stands, a single officer should not be able to take out a well-armed syndicate agent who has most likely had superior training, and is juiced on implants and nanomachines that help reduce pain/etc.

**Comment by Alanii** [comment]
> batons are still far superior to shoving since they instantly do 40 stamina damage and instantly knock someone down, allowing you to press X and shove them again, hardstunning them for ~8 seconds.

The cool down mechanic is far too long than you think it is. I would encourage you to actually play security for a few weeks, and attempt any form of nonlethal arrest attempts. The fact you have to resort to shoving rather than using the tools given shows the PR is nothing more than a "nerf" with no reason behind it other than "its not fair baton is useful for security."

I understand the antagonists who are unrobust get arrested, but there are current rules in place to prevent security from gimping their entire round. There is a reason why antagonists always tend to have the upper hand due to the constant reaction nerfs to security equipment and the fact security will get in trouble for not going 'easy' on an antagonist in most scenarios. 

> > Some people brought up a good point on discord.
> > Why are people getting mad about sec doing herd and group tactics against antags while also nerfing their gear to enforce said tactics, which then nullify rp in most cases cause one accidental punch or shot means the whole scene is dropped
> 
> 
> for real though, the reason security resort to group tactics is most of them are horribly unrobust, never use pepper spray or any other tools they are given, and instantly resort to a gun or baton which if any good antagonist knows how to counter, means they're dead.
> 
> As it stands, a single officer should not be able to take out a well-armed syndicate agent who has most likely had superior training, and is juiced on implants and nanomachines that help reduce pain/etc.

Security resorts to group tactics due to their nonlethal tools being useless. If their nonlethal tools were not completely useless (i.e. pepperball, rubbers, the weird rubber, etc.) security would be less inclined to group up to take down antagonists. 

I shall also mention that the security glasses don't even prevent you from being pepperballed or peppersprayed. So some security see pepperspray as a complete useless tool to use when their gear doesn't protect them from it.

Again, the reaction nerfs tend to not help the gameplay, and instead just make security more useful at killing antagonists than bringing them in through nonlethal means.

The current nonlethal ammunition is not as useful as you may claim it is when you take into account gameplay.

**Comment by ForrestWick** [comment]
> 
> > batons are still far superior to shoving since they instantly do 40 stamina damage and instantly knock someone down, allowing you to press X and shove them again, hardstunning them for ~8 seconds.
> 
> The cool down mechanic is far too long than you think it is. I would encourage you to actually play security for a few weeks, and attempt any form of nonlethal arrest attempts. The fact you have to resort to shoving rather than using the tools given shows the PR is nothing more than a "nerf" with no reason behind it other than "its not fair baton is useful for security."
> 
> I understand the antagonists who are unrobust get arrested, but there are current rules in place to prevent security from gimping their entire round. There is a reason why antagonists always tend to have the upper hand due to the constant reaction nerfs to security equipment and the fact security will get in trouble for not going 'easy' on an antagonist in most scenarios. 
> 
> > > Some people brought up a good point on discord.
> > > Why are people getting mad about sec doing herd and group tactics against antags while also nerfing their gear to enforce said tactics, which then nullify rp in most cases cause one accidental punch or shot means the whole scene is dropped
> > 
> > 
> > for real though, the reason security resort to group tactics is most of them are horribly unrobust, never use pepper spray or any other tools they are given, and instantly resort to a gun or baton which if any good antagonist knows how to counter, means they're dead.
> > 
> > As it stands, a single officer should not be able to take out a well-armed syndicate agent who has most likely had superior training, and is juiced on implants and nanomachines that help reduce pain/etc.
> 
> Security resorts to group tactics due to their nonlethal tools being useless. If their nonlethal tools were not completely useless (i.e. pepperball, rubbers, the weird rubber, etc.) security would be less inclined to group up to take down antagonists. 
> 
> I shall also mention that the security glasses don't even prevent you from being pepperballed or peppersprayed. So some security see pepperspray as a complete useless tool to use when their gear doesn't protect them from it.
> 
> Again, the reaction nerfs tend to not help the gameplay, and instead just make security more useful at killing antagonists than bringing them in through nonlethal means.
> 
> The current nonlethal ammunition is not as useful as you may claim it is when you take into account gameplay.

Not every traitor is a syndi, this is why ambitions exist. The uplink is something we cant control

**Comment by Alanii** [comment]
> 
> Not every traitor is a syndi, this is why ambitions exist. The uplink is something we cant control

Then buff specific antagonist items and the link rather than making security neigh useless.

Not every person security fights is a traitor with an uplink. They also fight assistants and other groups who create problems themselves.

Security doesn't exist to solely fight the nerd with an uplink.

**Comment by Lauwma** [comment]
Alright I've made my point on discord already but I'd like maintainers to see my arguments too since the Yawet doesn't seems very convinced. 

As a reference I'll first give some /TG numbers.
On /TG, to stunlock someone it takes around 3 seconds with the stunbaton. You hit a first time (put your baton back in your belt if you are robust), wait them to fall down, then baton again.
That's because the stunbaton applies 60 stamina damages and an effect that knockdowns the opponent after a few seconds. 2 batons is effectively a critical stamina state since the stamina pool is at 100.

Currently on Skyrat, without this nerf. Apparently I've been told carbons has a stamina pool of 135 and batons do 40 stamina damage every 1.5 seconds. 

135/40 =~ 4
It means you are effectively downing someone after 6 seconds, nearly double the time and with some trouble since you don't have what makes stunbatons very good, the timed knockdown AND the weapon drop (you need to actually shove in order to disarm).
If we nerfed the baton to have a 2.5 cooldown, we would end in a theorical 10 seconds, which is around a 66% increase. Which is a fairly big deal considering someone can shoot a gun 8 times during that 4 additional seconds.
Keep in mind all of this is in a 1v1 scenario.

Effectively, antags are never faced by one lone security member, and when they are the sec officer is already very likely to die if the antagonist is as skilled or more skilled than the officer in clicking on a sprite. Though antagonists have the advantage of the surprise effect/ect... but that's not really my point here.
My point is that most antagonists are dealt with than three or more security officers, effectively, if three sec officers are coordinated it takes 2 seconds to subdue someone if they are shoving them after the baton hit. This scenario is not affected by this nerf. 

That means that we are nerfing security officers that already have poor odds when alone for an issue that happens mainly when security officers are more than one, which makes little sense to me. 

There's also an other issue with this, petty crimes and organic crimes in general. In thoses cases Security are often alone to deal with multiple low threats, take a bar fight for exemple, I don't know if you already tried to break a barfight and subdue everybody by yourself and bring them in the brig but it's already VERY VERY hard and often you need as much officers there's non antag criminals (making effectively multiple 1v1 so nerfing again, what doesn't need to be nerfed). 

I think what you should do instead if bust certain antagonists items that are currently useless like the stimpack (only gives you speed, the stun resistance is barely noticeable) and the CNS rebooters (I never seen this implant do a difference).

**Comment by Sethnov** [comment]
were not tg

**Comment by CloverIsLucky** [comment]
Hello, as secmain, I'm here to downvote the PR too.

**Comment by KathrinBailey** [comment]
> > Security has been being nerfed into the ground recently. Already our default ammo makes our guns peashooters, 9mm literally does negative damage, and you want to nerf them more?
> 
> You may be playing the wrong server, we just un-nerfed them and 9mm does 32 damage per shot, and 10mm magnum (peacekeeper btw) does 48 per shot.

the heck, did someone change all of this again?
I renamed TG 9mm and TG 10mm into 9mm Something and 10mm Magnum to separate them from the peacekeeper 9mm & 10mm of the exact same name, so it's less confusing for the players.
10mm magnum shouldn't be used in peacekeeper stuff? I'm so confused...

**Comment by Gandalf2k15** [comment]
No need to do this. Please.

**Pull request closed without merging**
