### PR TITLE
Cyber P.I. Costume

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Adds Cyberpunk P.I. Costume, using sprites from Eris, sourced from https://github.com/VOREStation/VOREStation/commit/a23605c9fd39b7123218d56250f7aaaeaefd929c

## Why It's Good For The Game
New costumes and outfits are fun

## Changelog
:cl:
add: Added a sleek modern coat + longcoat, available in the loadout and Detective's vendor
add: Added a matching hat to complete the costume, the type-34C semi-enclosed headwear - available in the loadout for Detectives as well as in their vendor
/:cl:

### CODE REVIEW

**Comment by Draganfrukts** [comment]
You know Seymour, these cyberpunk sprites are quite similar to the ones they have at CEV Eris. 
YouKnowSeymour

**Comment by SarmentiCampbell** [comment]
Because they are, I just had the flemme of doing the same thing when i knew that virgo ported them over aswell

**Comment by ghost** [comment]
Making a snarky comment doesnt contribute anything. I was _asked_ to port this outfit and given a PR with working sprites to use.
I'm changing it all a tad anyways, so I'm closing this for now. I'll be sure to mention its from Eris too, just for you @Investigator77

**Comment by ghost** [comment]
Alright, changes done. Fixed credits and modified the outfit to be more of a detective uniform than a costume (specifically the headwear. The coat itself is still in the loadout for any crew)

**Comment by Draganfrukts** [comment]
Bro I was just making a joke

**Comment by Gandalf2k15** [comment]
Seems good. I'll accept.

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
