### PR TITLE
[Modular] Add Bio Bag of Holding

### PR DESCRIPTION
**Pull request by tt-relay-104**
## About The Pull Request
Adds neat biobag of holding, stats were taken from bio bag of holding on Skyrat13 build

## Why It's Good For The Game
Some QoL for xenobiology

## Changelog
:cl:
add: added Bio Bag of Holding
/:cl:

### CODE REVIEW

**Comment by NullDagaf** [comment]
An entire new tech node for that? I dunno man...

**Comment by tt-relay-104** [comment]
i can add it to existing node but it will be less modular

**Comment by NullDagaf** [comment]
> i can add it to existing node but it will be less modular

Pretty sure you could still keep all the changes in /modularskyrat ? Appending an entry to a list doesn't sound too hard.
Don't quote me on that, though.

**Comment by YakumoChen** [comment]
👎 
This is severe powercreep for xenobio, traitoring as one has a heavy limitation based on how many cores you can carry at once. There isn't really even a need for this except to traitor since most xenobio players put the smartfridge in an adjacent tile. The most "qol" you're saving is a few left clicks in exchange for huge unneeded buffs to antagonists.

**Comment by tt-relay-104** [comment]
> This is severe powercreep for xenobio, traitoring as one has a heavy limitation based on how many cores you can carry at once. There isn't really even a need for this except to traitor since most xenobio players put the smartfridge in an adjacent tile. The most "qol" you're saving is a few left clicks in exchange for huge unneeded buffs to antagonists.

That sounds fair at first point. But when you think about it, why the hell someone whould take 100 cores with yourself? When there is better option for that like crossbreeds, if you really want to powercreep you should use that, not those basic cores. Give me a fair situation were you can use all those cores and don't get banned? (That would be of fair for the TG but not in the rules of skyrat, you can't do really much with basic cores in this rule frame)
UPD: That was on the skyrat13 build and it was good, does it changed much in term of powercreeping antags?

**Comment by YakumoChen** [comment]
Oldbase did not have good balance in the slightest and I wouldnt recommend basing any balance change from "but oldbase had it"

Base cores are still pretty good, and being able to carry 100 of them at once is a terrible prospect. 100 IEDs, 100 gold cores. 100 small plasma fires. Having an absolute shit ton of cores isnt ban worthy so long as you're using them smartly.

**Comment by Gandalf2k15** [comment]
Unfortunately my friend I feel the balance concerns raised here may outweigh the benefits of having this bag, if you can address them, feel free to reopen the PR with some changes 👍

**Comment by Folkess** [comment]
> Unfortunately my friend I feel the balance concerns raised here may outweigh the benefits of having this bag, if you can address them, feel free to reopen the PR with some changes 👍

Nerfing it to 50 slots and locking behind tier 5 slime core would sustain your feeling of balance? (still be valuable as qol for xenobiology)

**Comment by tt-relay-104** [comment]
I will approach this question when i'll be more experienced at xenobio balance

**Pull request closed without merging**
