### PR TITLE
Granite's Love/hate of Ruins pass 6 of X - Interdyne ship Edition

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

Interdyne slowly crept into a bloated block of weh, shrinking it back down and migrating facilities to DS-2 as well as prepping it to have it's own Shuttle system for both navigating to DS-2 and future-proofing for Overmap (maybe?).

Interdyne now has a custom-made shuttle just for it! 

Say hello to the Burst
--
image
image

Small n Spunky, the Burst is designed to withstand extremes in temperatures both Hot and Cold. 

Newly laid out Interdyne
--
image

## How This Contributes To The Skyrat Roleplay Experience

Refocus' s Interdyne into what it is meant to be, a research medical facility. Expanded xenobio, a bigger chem area and due to their defacto-role of lavaland's medbay a secure Operating Theater for all those angry locals.. The removal of the exterior turrets was something I should've done instead of just adding the neutral faction bypass, all they've done is call over megafauna to eat into the base and cause way more problems than they were meant to solve.

No more vault, along with the self-destruct bomb that has no real purpose here anymore. It was a tossup between keeping it and making it a maxcap or removing it. Everything within the vault was spread throughout the rest of the small station, the suit is now in the DO's office where it should have been in the first place. The Kitchen/Bontany/ Dorm areas are a lot more fleshed out and less cramped, each dorm room having their own lock now even.

DS-2's foreverdockedship is now gone and replaced with a docking computer for the Burst as well as the landing zone for said Burst.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
  
image

  
</details>

## Changelog

:cl:
add: New Interdyne shuttle - the Burst!
balance: Interdyne has 2 doors in the front with all exterior turrets removed
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
I don't like how interdyne gets more bloated and space inefficient with each new iteration. It's damning that the actual research parts get smaller and smaller while the bloat and irrelevant sections get bigger and bigger.

**Comment by YakumoChen** [comment]
:-1: Removed the actual research portions of Interdyne, the entire purpose of the ruin in the first place
:-1: Removed virology for no reason
:-1: Made Interdyne totally dependent on DS2 (which doesn't spawn on all maps)
:-1: Ruined the point of the lava lake by making parts of the base land connected
:-1: The vault should be the ore silo if nothing else
:-1: Ore silo now useless with no research / lathe area to print from
:-1: Space overly focused on recreation / domiciles instead of research
:-1: Service turned into a full scale restaurant for a crew of 9, this is what DS2 should be preferred for
:-1: Giant, empty parts of the map that can't even be reasonably expanded into and take up more lavaland space.

**Comment by YakumoChen** [comment]
needs MDB ignore tag

**Comment by Zergspower** [comment]
Not entirely sure why it'd need MDB ignore, but a few things are getting redone before i take it out of the draft (the button was not there last night oddly).  This is just the Lavaland Interdyne mind you not Icebox.

The Proto and auto are boards to build now and are more than likely slated to be completely removed in favor of them being for the new DS-2 ship remake.

oversight on the left and has been fixed, Virology/Xeno was a deal of one or the other and Xeno won out. I'm going to play with re-adding it below science area but it made no fucking sense to have a 3x3 space in an open room to do _bioweapons_.

**Comment by unit0016** [comment]
Hi @Zergspower - If you'd have me despite no longer being relevant to Skyrat, I'd like to make my thoughts entirely clear as the original bastard who worked on both this and DS-2 post-rebase - Based. I'm glad someone got the cargo shuttle working, and gladder that they're both being retooled because sweet mother of mercy where I originally intended to go wasn't going to happen, cool as it would've been.

This is the 5th time this map's been redesigned, just to put a sticky note on it. If only we'd known it'd be so much trouble. 😅

**Comment by Zergspower** [comment]
> Hi @Zergspower - If you'd have me despite no longer being relevant to Skyrat, I'd like to make my thoughts entirely clear as the original bastard who worked on both this and DS-2 post-rebase - Based. I'm glad someone got the cargo shuttle working, and gladder that they're both being retooled because sweet mother of mercy where I originally intended to go wasn't going to happen, cool as it would've been.
> 
> This is the 5th time this map's been redesigned, just to put a sticky note on it. If only we'd known it'd be so much trouble. 😅

always welcome to comment! And yeah i'm kind of happy with the Burst, and has a few lines of code away from being overmap capable if/when we do get that in too!

**Comment by YakumoChen** [comment]
needs MDB ignore tag because you're making the bot upset because the map is basically being redone.

**Comment by Paxilmaniac** [comment]
You do not need MDB ignore unless you are changing a large number of maps (like +5 or so). If you are referring to MDB2, MDB2 hasn't successfully ran on a single map pr on this codebase.

**Review by Paxilmaniac — CHANGES_REQUESTED** [review]
_maps/RandomRuins/LavaRuins/skyrat/lavaland_surface_syndicate_base1_skyrat.dmm:2885:error: bad type or variable: s

Classic sdmm 2 goof, somewhere you have a stray 's' in a varedit i think

**Comment by YakumoChen** [comment]
huh, how did I never notice that?

**Comment by YakumoChen** [comment]
I think the service and quarters area needs compressed by like, a lot. One of the best parts of the current interdyne is that you could walk into the commissary, and everyone there was there. 
image
_Everything's here._

It doesn't feel like a compact research base if I have to walk through two screens of kitchen and bar to potentially find anyone.

It's a small base for 9 crew, it doesn't need seating for 18.

**Comment by Zergspower** [comment]
> _maps/RandomRuins/LavaRuins/skyrat/lavaland_surface_syndicate_base1_skyrat.dmm:2885:error: bad type or variable: s
> 
> Classic sdmm 2 goof, somewhere you have a stray 's' in a varedit i think

pffffffft nice - i'll be working on it this weekend and see where i probably tried pressing S to pan down and typed in like a dumbass

**Comment by Zergspower** [comment]
this isnt abandoned btw - i'm waiting for the DS-2 ship redux wat i'm helping Zy with so this can be put  in behind it with the ship

**Comment by unit0016** [comment]
Hey @Zergspower, if you don't feel like finishing this, I've been toying with the idea of coming back to SR for real since one of the gremlins from my time suggested I should, ~~+ revisiting this map'd be a solid bit of justification for it~~ and can either finish the job here or do a remap of my own to do the 'ol freak of a ruin justice.
...For *real* this time, because I damn well didn't last time.

**Comment by Jolly-66** [comment]
There's conflicts and the last commit for this PR was from almost 2 months ago, plus this PR has also been on/off stale between then and now. 

If you would like to continue this PR, I suggest opening a new one. In the mean time I'm closing it mostly due to inactivity.

**Pull request closed without merging**
