### PR TITLE
[SEMI-MODULAR] Engineering Cyborg Advanced Materials Upgrade

### PR DESCRIPTION
**Pull request by ZephyrTFA**
## About The Pull Request

Adds a new upgrade for engineering borgs that allows them to manipulate plasteel and titaniumglass

## Why It's Good For The Game

We had it old base and it was nice; we dont have it here and I want it here

## Changelog
:cl:
add: Engineering cyborgs can now install an advanced materials upgrade
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Currently on the fence with this one. 

Not sure why but I just get the feeling certain borgs will find a way to abuse this. It's why I'm also hesitant on giving borgs the crusher. Discuss further in discord.

**Comment by Oscari-pog** [comment]
Love this one, at last, repairing reinforced walls.

**Comment by ZephyrTFA** [comment]
@Funce 🥺

**Comment by Funce** [comment]
Wup you go!

**Comment by YakumoChen** [comment]
I don't like this at all... engi borgs are already the most powerful module, and being able to lay down un-RCDable, very difficult to remove walls means they can just make super-forts anywhere they want (which is especially big for malf AIs)

The ways to get through r-walls is either very limited or expensive or time consuming, giving borgs an infinite supply of them isn't a great idea.

**Comment by lyricalpaws** [comment]
> 
> 
> I don't like this at all... engi borgs are already the most powerful module, and being able to lay down un-RCDable, very difficult to remove walls means they can just make super-forts anywhere they want (which is especially big for malf AIs)
> 
> The ways to get through r-walls is either very limited or expensive or time consuming, giving borgs an infinite supply of them isn't a great idea.

The joke is malf rolls once in a blue moon

+1 for the pr

**Review by KathrinBailey — APPROVED** [review]
You can already make forts that cannot be RCD deconstructed as a borg, so the argument against this PR that this let's you do that doesn't really worry me.
Gonna ask others if there's no other objections, I'm honestly fine with this. It enables engiborgs to do more construction projects and the rwall spam protential for malfs can be countered with jackhammer. A certain other walling method I shall not discuss is harder to defeat with a jackhammer.

**Pull request merged**
