### PR TITLE
[NO-GBP] Last loadout fixes to make it on par with the old system

### PR DESCRIPTION
**Pull request by Majkl-J**
## About The Pull Request

Brings back the 3 plushies 3 misc. Fixes loadouts not showing correctly when set to "Spawn with case"

## How This Contributes To The Skyrat Roleplay Experience

Fixes a bug and brings back old loadouts, hooray.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  Spawning with case untouched:

image

 Spawning with case in menu:

image

 Category limits:

image

image

</details>

## Changelog

:cl:
fix: Brings loadouts back on par with the old system mechanically
/:cl:

### CODE REVIEW

**Comment by IgiariValkyr** [comment]
My donator item is still missing from the system. The Black and Red Turtleneck for Head of Security

**Comment by SpaceLoveSs13** [comment]
> My donator item is still missing from the system. The Black and Red Turtleneck for Head of Security

I couldnt find any removal of any head of security red or black turtlenecks. Could you link your donator pr, that would be very helpful! I will make a seperate pr to add them then.

**Comment by IgiariValkyr** [comment]
> > My donator item is still missing from the system. The Black and Red Turtleneck for Head of Security
> 
> I couldnt find any removal of any head of security red or black turtlenecks. Could you link your donator pr, that would be very helpful! I will make a seperate pr to add them then.

It’s still in game from what I know, it’s just not in the new loadout system but was in the old one

**Comment by SpaceLoveSs13** [comment]
> > > My donator item is still missing from the system. The Black and Red Turtleneck for Head of Security
> > 
> > 
> > I couldnt find any removal of any head of security red or black turtlenecks. Could you link your donator pr, that would be very helpful! I will make a seperate pr to add them then.
> 
> It’s still in game from what I know, it’s just not in the new loadout system but was in the old one

Got it I will take a look

**Pull request merged**
