### PR TITLE
[NON-MODULAR]Improving the AI and PAI HUD

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request

So I noticed the AI and PAI huds feel like they were made for an era long ago, conforming to hard 15x15 screen sizes and hard coded positions. Also buttons were placed with no organization... So I repositioned all the buttons to make better use of space on both 15x15 and 21x15 screen sizes! Also, this makes the UI elements scale to partial positions with TOP/BOTTOM/LEFT/RIGHT coordinates, replacing absolute NSWE positions. 

No more Mac OS 9 feel!

## Screenshots
dreamseeker_WLNDdPJFCh
dreamseeker_q9RYIFedMA
dreamseeker_zUq5alG6c9
dreamseeker_9zaxwpBk0a

## How This Contributes To The Skyrat Roleplay Experience

The AI and PAI interfaces are now making better use of screen space.

## Remarks
I'd like some feedback as so to the button positioning and layout, as I put them in a way that makes sense to _me_, but I am not a PAI or AI frequent. Constructive criticism and feedback please!

## Changelog

:cl:

qol: Improves the AI and PAI HUD elements

/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
You should PR this upstream when the freeze ends.

**Comment by tf-4** [comment]
^ do it upstream

**Comment by nevimer** [comment]
> ^ do it upstream

There are already skyrat edits in the file

**Comment by tf-4** [comment]
I'm not sure what that changes? Should still be taken upstream

**Comment by nevimer** [comment]
> I'm not sure what that changes? Should still be taken upstream

Once it goes upstream, and comes back down here, you're gonna have to re add the skyrat additions anyways, probably?  I dunno. Feature freeze. They won't take it, so why must it be attempted in vain?

**Comment by tf-4** [comment]
The freeze lasts like 3 more days. Just take it upstream.

**Comment by nevimer** [comment]
re-opening for review or something, PAI's are popular now and its probably a good time to relook

**Comment by tf-4** [comment]
There's no need for this many non-modular changes. Ask upstream, if they reject it then let me know and I'll happily re-open this. Though I imagine they'll be happy to take it.

**Comment by GoldenAlpharex** [comment]
That being said, for the pAI one, the placement of some stuff feels arbitrary, the important stuff should probably be in the center, like how it is with hands for carbons.

**Pull request closed without merging**
