### PR TITLE
Department Specific Central Command Fax's

### PR DESCRIPTION
**Pull request by SomeRandomOwl**
## About The Pull Request

This adds AREA specific variables to the heads of staff rooms (plus lawyer) for fax machines. This enables them to have specially named faxes for Central command that makes a bit more sense for the department they are located in.

## How This Contributes To The Skyrat Roleplay Experience

Allows for a bit more variety for RP when it comes to paperwork and Fax machines, for example why would the CE need to fax the legal department for engineering issues? They are now connected to the engineers in central. Why would the NT Rep fax the complaints department? They would have a direct line to central command themselves. Etc.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
63qImDxkV4

Vq0hSiIKT8

up29zAbHpT

3v8wO7eiFH

q4BuSoMQZU

iBQB5NFo06

jda3UXekVb

zbNgMoMdpL

goAj7Vsw1U

image

</details>

## Changelog

:cl:
add: Added Departmental Specific Fax lines to the heads of staff office fax machines, they now can complain to the part of central that fits their department.
add: Added Random fluff Fax lines to every fax machine, there is also now a random 1/300 rare chance to get a unique rare fax line, You can finally get a chance to send a letter to Santa.
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
-1
everything being divvied up between 

NT HR Department
NT Legal Department
NT Complaint Department
NT Customer Relations
Nanotrasen Tech Support
NT Internal Affairs Dept

makes sense for the unlimited bureaucracy of a space megacorporation, and requires you to have some level of creativity unless you're the Captain
having to phrase an engineering issue as 'hey we need to contact tech support' is more rich and flavorful than 'we just directly contact Engineering But Stronger'
it's a bit too convenient to just be able to directly fax 'Medical Emergencies' instead of having to plead your case to whatever intern is working at, idk, Customer Relations or the Complaint Department, and takes away, a bit, from the Captain and NT Rep's somewhat-unique ability to have the full authorization and swagger to just directly talk to CC Itself™️ over the comms console. i would imagine that a head of staff is not supposed to have one single source that they can reliably describe any general issue to, as you're supposed to pick which kind-of-fitting subdepartment of the NanoTrasen bureaucracy that you feel is closest to whatever you're complaining about. 

especially considering even if it is kind of a loose fit to contact tech support about 'telecomms physically exploded, actually' it's up to staff if they feel like Tech Support would be helpful or not, it's as helpful or unhelpful as they want it to be.

**Comment by SomeRandomOwl** [comment]
As I stated on the discord, I do not see an issue with having Departmental specific faxes for the heads of staff, it is an attempt to promote more paperwork RP as not every head of staff even participates with paperwork RP. I want to promote it more and give the heads specific department related lines to central as it makes sense that they would be able to and need to talk to someone in charge of their specific and related department. They shouldn't have to jump through hoops to talk about a engineering related issue to central, or medical, or science or supply. They should have the ability to talk to the people they need who would understand them and their needs the most rather than some offshoot. The heads are meant to be professionals why would they not have a line to talk to their department, to handle department related issues professionally?

**Comment by SomeRandomOwl** [comment]
I may look into this more and adding more onto this in the morning, someone mentioned being able to fax third party companies and quite like that idea

**Comment by SomeRandomOwl** [comment]
To keep it here too, I am changing a few of the fax names to have external companies as a possibility, as well as maybe some other few special faxes

**Comment by Zonespace27** [comment]
Overall, not a fan. I'd rather keep the faxes to "generic NT" for two reasons:

- For dept-NT, as the guy who replies to the vast majority of faxes, I'd like to not be pigeonholed into a subsection of NT when writing the replies
- For the generic not-NT places, I'd rather have them be actual, fleshed-out lore companies. We however lack those.

Closing in 24h unless another maintainer disagrees.

**Pull request closed without merging**
