### PR TITLE
[MODULAR] More Horns

### PR DESCRIPTION
**Pull request by Nerev4r**
## About The Pull Request

<details>
<summary>The Horn Section</summary>

image
image
image
_Dragon_ horns from _Virgo._ More like dragon these nu-

image
image
image
_Lifted_ horns from _Sojourn._ Hey, I've seen this one before!

image
image
image
_Curly_ horns from _Sojourn._ You could almost hang her on a rack.

image
image
image
_Upward_ horns from _Sojourn._ Does not improve football scores.
</details>

## How This Contributes To The Skyrat Roleplay Experience
Adds new customization options borrowed from https://github.com/quotefox/Hyper-Station-13, https://github.com/VOREStation/VOREStation/pulls, https://github.com/Citadel-Station-13/Citadel-Station-13-RP, and https://github.com/sojourn-13/sojourn-station.

## Changelog
:cl:
imageadd: Adds more horns. Upward, curly, lifted, horns from Sojourn, and a Dragon option from Virgo.
/:cl:

### CODE REVIEW

**Review by tf-4 — APPROVED** [review]
Sprites are nice. Code is fine.

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
I'm not so sure about homestuck reference horns, and the stabber horns' perspective looks waaaay off, they'd be better off if they aimed slightly to the left and to the right on the front and back perspective, a-la Hellboy, if you get what I mean. Horns poke out of the skull, so them bending *inward* doesn't make much sense anatomically, and doesn't look particularly good on a 32x32 scale, sadly.

**Comment by Nerev4r** [comment]
Cut the stabber horns for now.

**Comment by rosextango** [comment]
> I'm not so sure about homestuck reference horns, and the stabber horns' perspective looks waaaay off, they'd be better off if they aimed slightly to the left and to the right on the front and back perspective, a-la Hellboy, if you get what I mean. Horns poke out of the skull, so them bending _inward_ doesn't make much sense anatomically, and doesn't look particularly good on a 32x32 scale, sadly.

What do you mean? The stabbers look perfectly fine perspective wise, and I know I'm not the only one of this opinion (see TF4 above). This really sucks as I was looking forward to utilizing them.

Also, if you are truly bothered by the addition of candy corn horns, then I would suggest removing the hairstyles Rosa, Jade, Dave, etc from customization, alongside the white suit and cueball helmet, as those are also references to Homestuck. Space Station 13 is a game full of hundreds of references, even to obscure things, such as the Chaos Donut being a reference to the Chaos Dunk from Barkley's Shut Up And Jam Gaiden, accompanied by a slowed down midi that has a chance to play upon entering the AI chamber, that midi being from the same game referenced. I have even seen Troll-like characters on the station, as in, "candy corn" horns and grey skin. To be bothered by pop culture references in the game would be to be bothered by most of what makes Space Station 13 the game it is today, e.g. ED-209, the Ripley mech, xenomorphs, so on so forth.

I don't know. I feel as if personal opinion and aesthetic is getting in the way of these PRs actually coming to fruition, and that your opinion is unfortunately the minority. I could be wrong.

**Comment by GoldenAlpharex** [comment]
> 

I just don't want to deal with the possibility that people will see them and go "oh so it's okay to make a homestuck character, cool". It's not subtle, it's like the *one* thing that you see and instantly go "oh yeah that's from homestuck", which is always something I'm not really fond of.

**Review by GoldenAlpharex — APPROVED** [review]
I'm fine with this.

**Comment by rosextango** [comment]
> > 
> 
> I just don't want to deal with the possibility that people will see them and go "oh so it's okay to make a homestuck character, cool". It's not subtle, it's like the _one_ thing that you see and instantly go "oh yeah that's from homestuck", which is always something I'm not really fond of.

I was under the impression that Homestuck characters would be fine, as we see plenty of people with characters based around My Little Pony, League of Legends (yordles), general fantasy (Drow, Elves, Dwarves), Touhou, Warhammer 40,000 (orcs), so on so forth. Are you saying that these characters are not okay to make, either? It wouldn't be fair to exclude Homestuck if these kinds of characters get a pass.

**Comment by GoldenAlpharex** [comment]
At this point it's a rules argument, not a development argument, and I'm not looking to keep on arguing on here.

**Pull request merged**
