### PR TITLE
[SEMI-MODULAR] [READY] Space Hotel Rework

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Reworks Space Hotel into something more modern.

hotel

## Why It's Good For The Game

The hotel is fucking shit rn

## Changelog
:cl:
add: Modernises the Space Hotel
add: Hotel Manager role - fire employees!
fix: Moves hotel guard shotgun to the spawner to stop people stealing it before anyone spawns there
/:cl:

### CODE REVIEW

**Comment by Grunnyyy** [comment]
Good PR

**Comment by misterreporter** [comment]
Thanks for taking my suggestion and doing something with it! I just wanted the appropriate tiles added but youve went and added all sortsa new things and re-designed it.  Good PR imo!

**Comment by Grunnyyy** [comment]
> Thanks for taking my suggestion and doing something with it! I just wanted the appropriate tiles added but youve went and added all sortsa new things and re-designed it. Good PR imo!

DON'T STEAL MY GLORY

I ASKED FOR THIS LIKE, YEARS AGO

;((

**Comment by tf-4** [comment]
lol i've been sitting on this for like a month. I'll get it finished up in a couple days

**Comment by tf-4** [comment]
ok this is about done as long as it passes checks

**Comment by NullDagaf** [comment]
Are the kitchen and hydroponics area ID restricted?

**Comment by tf-4** [comment]
> 
> 
> Are the kitchen and hydroponics area ID restricted?

~~No. I could easily make them restricted, though.~~
Done.

**Comment by misterreporter** [comment]
One last follow up question. Can tcomms be established or put on the hotel from the editor end? Its pretty annoying when you go there and you cant get a message out or hear the radio unless you can get the people with the knowledge (if they are around) to assist.

**Comment by tf-4** [comment]
> 
> 
> One last follow up question. Can tcomms be established or put on the hotel from the editor end? Its pretty annoying when you go there and you cant get a message out or hear the radio unless you can get the people with the knowledge (if they are around) to assist.

it could, though it could lead to hotel staff spamming advertisments on comms which would be A: annoying, and B: make staff have to tell them to stop, when generally they have enough going on as it is

I'll think a bit more about this

**Comment by misterreporter** [comment]
> > One last follow up question. Can tcomms be established or put on the hotel from the editor end? Its pretty annoying when you go there and you cant get a message out or hear the radio unless you can get the people with the knowledge (if they are around) to assist.
> 
> it could, though it could lead to hotel staff spamming advertisments on comms which would be A: annoying, and B: make staff have to tell them to stop, when generally they have enough going on as it is
> 
> I'll think a bit more about this

Maybe for the ghost who join the staff roles put a little piece of text about NOT spamming over gen comms besides like, an ad or so per shift so people atleast know that they are there? And if we're gonna be realistic, the people on station do a good enough job by themselves spamming and spouting non-sense. I'm sure a few extra messages wouldn't be world ending.

**Comment by Gandalf2k15** [comment]
Just to check; the original map is unedited correct?

**Comment by tf-4** [comment]
> 
> 
> Just to check; the original map is unedited correct?

~~yup~~ Ok apparently it somehow wasn't. But it is now.

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
1. Don't use freezer and showroom floor literally everywhere. It doesn't look modern, it just looks weird.
2. Especially don't surround the pool in those tiles then surround that in wood, it's incredibly jarring.
3. Always put plating under windows.

Ideally the space hotel rework I'd have wanted would've involved doing one thing first:
_Delete everything._
Space Hotel is so cursed that I'd rather someone attempt making something new instead of just doing minor changes.

**Comment by tf-4** [comment]
> 
> 
>     1. Don't use freezer and showroom floor literally everywhere. It doesn't look modern, it just looks weird.
> 
>     2. Especially don't surround the pool in those tiles then surround that in wood, it's incredibly jarring.
> 
>     3. Always put plating under windows.
> 
> 
> Ideally the space hotel rework I'd have wanted would've involved doing one thing first:
> _Delete everything._
> Space Hotel is so cursed that I'd rather someone attempt making something new instead of just doing minor changes.

Where is there not plating under windows? Other than that, I can change the flooring up easily.
That said, I can scrap the whole thing and start from nothing if you think it's that far beyond saving.

**Review by KathrinBailey — APPROVED** [review]
Whilst I would prefer the entire hotel deleting and being remade from the ground up, this now at least has lots of QoL improvements like actually having griddles.

**Pull request merged**
