### PR TITLE
[MODULAR] Adds minimum players to several high-severity items and kits for traitors #2

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Title

Remake of #6638 

This time, not on master branch!

## Why It's Good For The Game

No super high severity items on lowpop!

## Changelog
:cl:
balance: Puts high severity traitor items behind player minimum requirements.
/:cl:

### CODE REVIEW

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Are we ever even under 50 players?
Seems like this just enables them for all but the absolute rarest of circumstances.
Please try and get some sample sizes of our population (specifically what this variable `player_minimum` is looking for. Connected? Alive? Observer or alive?) during highpop and lowpop hours. Just ahelp and ask.

**Comment by Oscari-pog** [comment]
Does this refer to players playing or players connected? There are usually a lot of people "connected", but not really playing.

**Comment by KathyRyals** [comment]
Please write a more describing changelog and/or PR body.

**Comment by lyricalpaws** [comment]
Github actions hurts my soul

**Pull request closed without merging**
