### PR TITLE
[Modular] Xeno-resin *turf emote gets its own quirk

### PR DESCRIPTION
**Pull request by desertmote**
## About The Pull Request

Hi, I'm back. 👋😊
Another one of the race-exclusive *turf emotes gets a quirk to add it onto other species.

## How This Contributes To The Skyrat Roleplay Experience

It was requested, and I understand since the amazing new character editor allows more freedom.

## Changelog

:cl:
add: Xeno-resin quirk
/:cl:

### CODE REVIEW

**Comment by desertmote** [comment]
Unfortunately I don't know how to add/edit quirk icons, I would fix the sparkle quirk icon and give this one an icon too if I could.

**Comment by tf-4** [comment]
Not sure I like this tbh, xeno-hybrids getting it at all was questionable and this is worse.

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
Code checks out, but I don't think I personally agree with this at all. I don't want to see more xeno resin around the station, especially from non-Xeno-hybrid.

**Comment by desertmote** [comment]
Ok, however I don't really see the difference between this and the spiderweb *turf. Remember these expire in 10 seconds if not stood upon.

**Comment by tf-4** [comment]
Xenos are vastly more common than spiders, and that's saying something

**Comment by desertmote** [comment]
Ok, I understand. Just one more thing to consider is that the sprite *turf uses is distinguishable from real xeno-turf. That's all.

**Comment by tf-4** [comment]
> Ok, I understand. Just one more thing to consider is that the sprite *turf uses is distinguishable from real xeno-turf. That's all.

Ah, distinguishable how? It's been a while since I looked at the *turf xeno turf

**Comment by desertmote** [comment]
> > Ok, I understand. Just one more thing to consider is that the sprite *turf uses is distinguishable from real xeno-turf. That's all.
> 
> Ah, distinguishable how? It's been a while since I looked at the *turf xeno turf

It's smaller than a full tile, the edges don't come near the 32x32 image pixel edge. original xeno resin is larger than a 32x32 full-tile.

**Comment by desertmote** [comment]
seems like there is no interest in ending this pr.

**Pull request closed without merging**
