### PR TITLE
Dwarves are no longer affected by the body size preference

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
## About The Pull Request
As shrimple as that.

Ideally the dwarfism and gigantism mutations should not work with body size modifications, but I didn't want to take too long to roll out this fix.

## How This Contributes To The Skyrat Roleplay Experience
Hee hoo tiny dwarf go brr.

Good riddance.

## Changelog

:cl: GoldenAlpharex
fix: Dwarves are no longer affected by the body size preference.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
>Ideally the dwarfism and gigantism mutations should not work with body size modifications, but I didn't want to take too long to roll out this fix.

 I put code in to fix this, did someone revert it?

**Comment by GoldenAlpharex** [comment]
> > Ideally the dwarfism and gigantism mutations should not work with body size modifications, but I didn't want to take too long to roll out this fix.
> 
> I put code in to fix this, did someone revert it?

I saw your code for it, but from what I remembered I could still see people with it, maybe it's just that I didn't notice it was all because of dwarves (in which case, fair enough, I fully fixed the issue then).

**Comment by Iamgoofball** [comment]
>it was all because of dwarves

chrome_DiOxOwYW0D

**Comment by softcerv** [comment]
No more funny dwarf men :( 
this is truly a horrible day for Skyrat.
we have died as a codebase.

**Comment by Nerev4r** [comment]
You're probably gonna want to address the free tablewalking they suddenly got.

**Review by tf-4 — APPROVED** [review]

**Pull request merged**
