### PR TITLE
fix-synthliz-tail

### PR DESCRIPTION
**Pull request by VastKilleroOm**
## About The Pull Request

Grants the ability to make "*wag" for "Synthetic Lizard Tail". 

The sprite was already in the game, I just added a "variable" to the tail that wasn't there

## How This Contributes To The Skyrat Roleplay Experience

Now everyone can select "Synthetic Lizard Tail" and do "*wag".....
Like many other tails...

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
https://github.com/Skyrat-SS13/Skyrat-tg/assets/74047915/39bc0bec-20ea-4614-9d22-101f5d4f7ad4

</details>

## Changelog

:cl: Vlada Frolova
fix: fixed a few things
/:cl:

### CODE REVIEW

**Comment by VastKilleroOm** [comment]
where is my "fix" label 
"ъуъ"

**Comment by lessthnthree** [comment]
> where is my "fix" label "ъуъ"

it looks for 'fix' or 'fixes' specifically iirc

**Comment by lessthnthree** [comment]
Please post the Proof of Testing section, thanks.

**Comment by VastKilleroOm** [comment]
@lessthnthree 
Your proofs are ready

**Review by lessthnthree — APPROVED** [review]

**Comment by lessthnthree** [comment]
> @lessthnthree Your proofs are ready

Thanks. You can delete the branch on remote, I meant to merge not revert. :)

**Pull request merged**
