### PR TITLE
FIRE ALL PHASERS at MONKE [CONFIRMED KILL]

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

We took the shot Captain, will it work?

## Why It's Good For The Game

NO MONKE

## Changelog
:cl:
fix: We've fired upon the monkey that was in the Jefferies tubes with all phasers.
/:cl:

### CODE REVIEW

**Comment by Vizoplez** [comment]
MONKEY TAX OOH OOH ACK!
image

**Comment by Gandalf2k15** [comment]
> MONKEY TAX OOH OOH ACK!
> image

We're still waiting on the confirmed hit, will it continue it's monkey business?

**Comment by DuffCreeper** [comment]
funne monke

**Comment by Gandalf2k15** [comment]
AHAHAHAH FUCK YOU MONKE
image

**Comment by KathrinBailey** [comment]
**NOOOOOOOOOO**

**Pull request merged**
