### PR TITLE
[MIRROR] [MDB Ignore] DELTASTATION: Remaps science, medbay, the chapel, and the library, and a whole lot more. Featuring mass driver. The Alpha and the Omega.  [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/68431
--------------------
###  Feedback on the layout is very much appreciated!

This PR entirely remaps the lower half of Deltastation. 

I'd go into detailed closeups of everything that's changed like I do normally, but so much was tweaked that's not very feasible. Here's a high resolution image instead. 

delta_p_wild

Fixes #38611

## Why It's Good For The Game

Deltastation's medbay is currently, very ... meh. 

Big hallways, very small treatment center. Lots of wasted space. 

So, I wanted to enact my long time plan to create a theme for Deltastation - A non-centralized departures hallway, to match the now non-centralized arrivals hallway. 

One thing led to another and here we are. 

The Departures hallway now branches off the starboard primary hallway, going down to the departures lounge, which has been redesigned. It now faces south. *Meta-clone!!*

The library is now between the central primary hallway and dormitories, featuring a lot more open design. 
The chapel has a grand window looking out onto the shuttle dock.
The maintenance between the dorms, the library, and the chapel has been reworked as well. Aux electric was shrunk a bit and slapped here. 

Medical and Science are now adjacent, both below the corporate lounge area, which was changed to serve as a more "command event area". 

Medical lies along the departures hallway.
Psychology now has an access door to a main hallway.

Science now wraps around the corner of the hallway. Genetics gets a hallway desk, by the pharmacy, and robotics is now across from the HoP line, slightly disconnected from the main science connection. 
The experimentor gets its own room again, Xenobiology touches space. Science maintenance recieved some major adjustments to accommodate.

Some other very minor changes were done around the map in general for consistency purposes. 

## Changelog

:cl:  Melbert
add: Almost the entire bottom half of Deltastation has been remapped. 
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
orderly and sci guard players in shambles now that they have to share a room

make sure you update automapper for delta for the new changes

**Comment by Jolly-66** [comment]
Please stop reminding me

**Comment by Zenitheevee** [comment]
P A I N
Though that new library and church do be lookin pretty 👌🏼 
Shame that it got rid of the maint det room.

**Comment by Jolly-66** [comment]
Time to bite the bullet and let the pAI refactor keep burning in eternal mapping hell.

**Pull request merged**
