### PR TITLE
[Modular] Removes DS-1.

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Well, after another shift of DS-1 self-antagging. It's time to say goodbye.
This removes DS-1. Also plays tetris with the second centcom z-level so we can fit more onto it.

## Why It's Good For The Game
fuck off, self-antag bad. We removed comms agents from interdyne for a reason

## Changelog
:cl:
del: DS-1 is gone. 🦀 
/:cl:

### CODE REVIEW

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Github handles archiving, so remove the DS1 map if that's your purpose.
If you're removing the map though, you should remove all the ghost role spawners from code too.

**Comment by unit0016** [comment]
done

**Comment by FlamingLily** [comment]
I still think #5364 is the better solution 😔 i just want my syndie prisoner rp man 😔 

but I mean I guess this works as a stopgap

**Comment by Cheshify** [comment]
o7 DS-1, another feature fallen, but one that had to go

**Comment by KathrinBailey** [comment]
> I still think #5364 is the better solution 😔 i just want my syndie prisoner rp man 😔
> 
> but I mean I guess this works as a stopgap

In the near-ish future you'll get your bad guy takes you prisoner RP. May or may not be syndie, though.

**Comment by coffeecoffeecoffee** [comment]
I set up a github just to write this, and I have no idea how this works, but this feels like an extreme salt PR. DS-1 players have always been good faith actors as far as I've seen - some of the best antagging I've ever seen yet was the -one- time they felt it was justified to go to the station to recover their abducted captain, and they performed the single cleanest fucking Payday style breakout I've ever seen right under security's nose - and I haven't ever observed this being a role that encourages people to self-antag wildly any more than ghost roles, especially like Ash Walkers. Have you considered removing them first, considering the numbers of times I've seen miners start shit with them/they start shit with miners?

For the record, I've never actually spawned on the DS-1 myself, so maybe there's something I'm missing that I wouldn't if I had played a prisoner there or something? But I've literally never encountered them on the station. This feels like taking something way out of proportion.

**Comment by unit0016** [comment]
> I set up a github just to write this, and I have no idea how this works, but this feels like an extreme salt PR. DS-1 players have always been good faith actors as far as I've seen - some of the best antagging I've ever seen yet was the -one- time they felt it was justified to go to the station to recover their abducted captain, and they performed the single cleanest fucking Payday style breakout I've ever seen right under security's nose - and I haven't ever observed this being a role that encourages people to self-antag wildly any more than ghost roles, especially like Ash Walkers. Have you considered removing them first, considering the numbers of times I've seen miners start shit with them/they start shit with miners?
> 
> For the record, I've never actually spawned on the DS-1 myself, so maybe there's something I'm missing that I wouldn't if I had played a prisoner there or something? But I've literally never encountered them on the station. This feels like taking something way out of proportion.

That was Cybersun, not DS-1.

**Comment by coffeecoffeecoffee** [comment]
Shows how much I know. Maybe it would help to elaborate on what the DS-1 does to be worth removing as opposed to the Cybersun?

**Comment by unit0016** [comment]
> Shows how much I know. Maybe it would help to elaborate on what the DS-1 does to be worth removing as opposed to the Cybersun?

DS-1 no longer has a purpose. It's an entirely empty ghostrole that nobody plays, stuck on a Centcom z-level with nothing to do. With a juicy, juicy shuttle, that's arguably better than the nuclear fucking cruiser.
Now, this is locked off typically. But about.. say, four, five times now? We've had people break into the armory meant for when we had assault ops, steal the rocket launcher, and bust out into the cruiser. Then they fly it to the station to self-antag.

We've had people outright kidnapping station people with this, and. You know. Obviously. That's not good. DS-1 was never meant to even leave their z-level, let alone have station comms and interact with them.

DS-1 needs to go. For the self-antagonizing observers, like why we removed comms agent - And for the pure lack of content.

**Comment by thestubborn** [comment]
> 
> 
> > Shows how much I know. Maybe it would help to elaborate on what the DS-1 does to be worth removing as opposed to the Cybersun?
> 
> DS-1 no longer has a purpose. It's an entirely empty ghostrole that nobody plays, stuck on a Centcom z-level with nothing to do. With a juicy, juicy shuttle, that's arguably better than the nuclear fucking cruiser.
> Now, this is locked off typically. But about.. say, four, five times now? We've had people break into the armory meant for when we had assault ops, steal the rocket launcher, and bust out into the cruiser. Then they fly it to the station to self-antag.
> 
> We've had people outright kidnapping station people with this, and. You know. Obviously. That's not good. DS-1 was never meant to even leave their z-level, let alone have station comms and interact with them.
> 
> DS-1 needs to go. For the self-antagonizing observers, like why we removed comms agent - And for the pure lack of content.

would you consider moving the syndi prisoner role somewhere? maybe expand lavaland or the spaceship to accommodate them?

**Comment by unit0016** [comment]
> would you consider moving the syndi prisoner role somewhere? maybe expand lavaland or the spaceship to accommodate them?

Depends hard. They're going to have to be completely rewritten if they do come back.

**Comment by Gandalf2k15** [comment]
Nah, no reason to delete this honestly. Leave it in, expand/remove anything that is being abused.

**Pull request closed without merging**
