### PR TITLE
Colours in command HUD icons with a goldish colour + QM HUD change

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
Gives command staff more distinct job Icons by making their HUD gold instead of white
Also gives the QM a more command-style HUD icon that still has some cargo colours to not look too much like the HoP (who has a similar icon)

image
image
image
Closes #13644

### Which one of these is a Head of Security?
image
image

### Which one of these is a Chief Medical Officer?

image
image

This meme is brought to you by Redsec Gang.

## Changelog

:cl:
imageadd: command staff have updated security icons after local screaming cat went on a rampage being unable to tell the difference between the head of security and their officers.
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
The gold, in my opinion, isn't contrasty enough. It's not a really pleasant gold either, in my opinion with an accurate monitor. Why not edit the blue portion instead? For me, it had a deep punch difference before, but it could be deeper. Command is typically white - Why not white border with Department colour icon in center? The defines can be found somewhere for an exact value

**Comment by theselfish** [comment]
Good PR. Though I think the yellow is a bit piss coloured.

No idea where "Command is white" came from.
Command is dark blue and gold. Well, the Captain is.

**Comment by theselfish** [comment]
Oh and on the QM thing; Wouldn't it make sense to have his icon be a blue/gold version of the Cargo Tech icon?

**Comment by theselfish** [comment]
Also also; In Game sprite pictures. Please.

**Comment by YakumoChen** [comment]
Not editing the command blue colour. Editing the white is the only logical choice, it makes the icon differ from every other job icon in the game (white on department). The only reason there's difficulty in the icons is because of the (aggrieved) change to Bluesec for job icons.

The gold colour is up for debate, but it's difficult to find a colour that is not too dark but not too yellow to make it hard to see anyway. Being coloured like piss is probably inevitable.

**Comment by YakumoChen** [comment]
> Also also; In Game sprite pictures. Please.

I don't really feel like booting up a compile to show the sprites that are already pictured

**Comment by YakumoChen** [comment]
since I favour #13644 over this PR I'm making this a draft and I guess maintainers can just force merge this if they don't like the other one.

**Comment by MassacreDemigirl** [comment]
piss command

**Pull request closed without merging**
