### PR TITLE
Modular, obviously, Starts modularizing our mining gear sprites in preparation for #8911

### PR DESCRIPTION
**Pull request by RatFromTheJungle**
## About The Pull Request

Keeps our old mining armor icons (after many mishaps, because coding isn't my passion.) because they fit better here.

## How This Contributes To The Skyrat Roleplay Experience

Keeping my beloved,
image

## Changelong

No.

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
image
do not talk about the old name it did not appear in chat

**Comment by gonenoculer5** [comment]
image

**Comment by gonenoculer5** [comment]
Your sins do not go unwritten, wanderer.

**Comment by RatFromTheJungle** [comment]
> 
> 
> The new mining stuff has more drip, but yeah, good idea to keep the old icons around too as an alternate option

once goof's reskinning is in, the new stuff will be the reskin for this

**Comment by RatFromTheJungle** [comment]
> 
> 
> Your sins do not go unwritten, wanderer.

that wasn't me

**Comment by gonenoculer5** [comment]
> > Your sins do not go unwritten, wanderer.
> 
> that wasn't me

Must've been the wind. Carry on.

**Comment by axietheaxolotl** [comment]
cringe pr
the new sprites are league betters

**Comment by thestubborn** [comment]
wouldnt it be simpler to use the aesthetics folder for this?

**Comment by GoldenAlpharex** [comment]
@RatFromTheJungle Please fix the Integration Tests part of CI with your PR and we'll be good to go with this.

**Review by GoldenAlpharex — APPROVED** [review]
Let's gooooo

**Pull request merged**
