### PR TITLE
[Modular] <In theory, Returning guns to the people, episode III, is this even about guns anymore? 

### PR DESCRIPTION
**Pull request by RatFromTheJungle**
## About The Pull Request

adding more crates to cargo 😈 

## Why It's Good For The Game
More cargonian content, after out dear TG-ian overlords shot them down in cold blood, besides the same two gun crates.

## Changelog
:cl:
add: Medieval crate, to the service department, expensive because its questionably balanced, price will probably go up much higher.
add: purchasable weapon maint kits, now. 😈 
add: the long lost hydroponics tray crate, that's just been sleeping in the code.
add: unique claymore for the medieval crate.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Please make a new claymore subtype or use the existing ones (like item/claymore/weak)

Cargo buyable null rods is NOT a good idea.

**Comment by hugmeorelse** [comment]
> Please make a new claymore subtype or use the existing ones (like item/claymore/weak)
> 
> Cargo buyable null rods is NOT a good idea.

Please elaborate on why it is not a good idea. Also, please try to temper whatever frustrations or emotions you have. You're coming off way too strong here. 

Thank you.

**Comment by YakumoChen** [comment]
Honestly, I think you're exaggerating how emotional that comment came off as, but sure.

Null rods are anathema to many antagonist types (namely wizards and all cult-related antagonists) and the weak claymore already exists to fill the niche I believe you want (it happens to be the one used in the holodeck, which has all the other items the crate contains, coincidentally)

**Comment by RatFromTheJungle** [comment]
> 
> 
> Honestly, I think you're exaggerating how emotional that comment came off as, but sure.
> 
> Null rods are anathema to many antagonist types (namely wizards and all cult-related antagonists) and the weak claymore already exists to fill the niche I believe you want (it happens to be the one used in the holodeck, which has all the other items the crate contains, coincidentally)

the PR is marked as a draft for a good reason, I'm just using the nullrod claymore as a stand-in, as the 'weak' one is.. a fair bit stronger then the name gives on, and personally, far stronger then i'd feel alright with putting in a crate, think of it as a "To be replaced" note,

**Comment by RatFromTheJungle** [comment]
claymores in the crate have been replaced by a unique one, that makes it clear just how underwhelming they are

**Review by Gandalf2k15 — APPROVED** [review]
lgtm

**Pull request merged**
