### PR TITLE
[MIRROR] New Station Trait: Cybernetic Revolution + Body Purist Quirk [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/71229
--------------------
## About The Pull Request
Adds a new station trait, the Cybernetic Revolution
It causes every crewmember to spawn with a cybernetic implant/organ (it depends on their job).
For example. the bartender has an upgraded cybernetic liver, security officers have extendable flashes, prisoners have flash shielded eyes. For AIs, they get the surveillance upgrade.
The trait also lowers research costs for the cybernetic designs, triples the price of EMP kits and EMP flashlights, doubles price of EMP bombs, and allows traitors to buy autosurgeons, so they can implant themselves with whatever they ripped out of the crew.
If you do not wish to partake, you can also take the Body Purist quirk, which prevents you from getting a cybernetic, but everytime you have a mechanical limb/organ from some other source, you will take a severe mood penalty.

## Why It's Good For The Game
This could be a cool modifier to rounds once in a while, slightly modifying the gameplay of all the crew.
Also our implant system is very barely used, so why not?
image

## Changelog
:cl:
add: New Station Trait: Cybernetic Revolution
add: Body Purist Quirk
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
We'll have to account for cat ears, hemophage hearts, and that sort of thing.

**Comment by SarmentiCampbell** [comment]
and the numerous jobs we have.

**Comment by hugmeorelse** [comment]
We probably won't be running it on the station.

**Comment by Fikou** [comment]
> We probably won't be running it on the station.

pussy

**Comment by Stonetear** [comment]
I don't know if they actually fixed it, but Plasmamen shouldn't get their stomachs changed.  Plasmamen stomachs are already immune to hunger so it's a direct downgrade.

**Review by Tastyfish — APPROVED** [review]
Technically those `job_to_cybernetic` placeholders are invalid but it doesn't matter.

**Pull request merged**
