### PR TITLE
[Testmerge Ready] Ancient Station - Remake

### PR DESCRIPTION
**Pull request by ForrestWick**
## About The Pull Request
_In the first years of Nanotrasen's rise to economic power, the advent of Plasma was being first discovered. Initially regarded as a fuel source, Nanotrasen began to amass science teams to experiment with the strange element on secretive research stations hidden outside the borders of SolGov controlled space. There were initially a handful of these stations, each one housing a small group of individuals kept silent with NDA contracts and significantly large paychecks. For unknown reasons however, all three were decommissioned and the crews pulled from their respective stations. Except for one._

_200 years later, what remains of the crew of the NTSS002, Designation DCB0201, wakes up from cryo stasis after the station AI warned and ushered them to the cryo pods, assuring them they would awaken in 8 hours once a radiation storm had passed. These men and women awake to find their station a rusted derelict, most of it in tatters, and an unknown enemy stalking the halls of the once tightly-locked science wing. They must work together to survive, and find out just what happened aboard their station. Or die trying..._

Preview Images:
https://i.imgur.com/mUprEDM.png
https://i.imgur.com/fCR936Z.png
https://i.imgur.com/FVooMLT.png
https://i.imgur.com/7LaeeTo.png
https://i.imgur.com/TNc53aY.png
https://i.imgur.com/ZHr3ro0.png
https://i.imgur.com/nultkln.png

## Why It's Good For The Game
Old Station/Charlie Station originally got a small rework from me some months ago, adding new areas and fixing a few of the old ones. This, however, is a new, complete overhaul of the ruin, with new content, a new weapon, a revamped layout, new areas, and even a special gift meant for the Old Station Miner in particular.

This PR bumps the spawns up to 8, adding an old station Atmos Tech on top of the previous additions. The ruin/ghost role offers new and returning players a new experience with a much better layout than before. This ruin will allow you to practice combat, construction, engineering, atmos, medical, space mining, botany/cooking with limited resources, and ports over the Staff Assistant jumpsuit from Citadel, initially ported from Goon. Players who spawn into the role must work together (yes that means roleplay) to reclaim the station from hostile occupants, repair the station's power grid and atmospherics, and find out just what happened 200 years ago.

## Changelog
:cl:
add: Completely new oldstation ruin/ghost role map
add: staff assistant jumpsuit ported and added to old station assistant loadout
tweak: old station chaplain no longer has their holy status, due to my own coding knowledge limitations. If someone else is willing to help fix this, let me know or open a PR on your own later.
config: the new ruin map will need to be added to the config, and I'm pretty sure maintainers/headmins are in charge of that so I won't do it this time
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Much better.

**Comment by RAND0MPR0** [comment]
I regularly play "Oldstation" - Honestly I would really like it if KS13 was merged with Oldstation (so rare that people actually play the KS13 drone spawner, and they can't even interact/rp with non-drones if a space explorer or somebody turns up), but that's just my opinion, and a little off-topic.

The majority of the time there is only 2-4 people playing Oldstation, and there is a massive increase in the amount of xenos, maybe decrease their overall health? Hardcore sounds fun though

I think it would be better if you want to mess with the whole xeno organ thing then make the Queen's corpse the same as the lavaland spawner (and remove the organs on the table, although I'm not too sure on that one), as it also gives you cool stuff for killing it, which is quite hard, instead of having it lying on a table before the "boss fight" which doesn't give you any cool stuff.

Seems very similar to this; https://github.com/Skyrat-SS13/Skyrat13/pull/3014

**Comment by Gandalf2k15** [comment]
We'll go ahead and test merge this.

**Comment by hugmeorelse** [comment]
Update.

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request closed without merging**
