### PR TITLE
Teshari are now able to eat "Gore"

### PR DESCRIPTION
**Pull request by RikuuTheRiolu**
## About The Pull Request

This change is to Remove "Gore" from a disliked food

## How This Contributes To The Skyrat Roleplay Experience

This PR will allow more food freedom and roleplay options for the Teshari, from taste test's to funeral rights, among many other thing's.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

  Capture

</details>

## Changelog

:cl:
balance: Removed "Gore" from disliked food's for Teshari
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Is there some kind of lore reason for this PR or is this just "I want to eat the raw liver" reasoning? I don't see anything in your "why it's good" that isn't a fairly generic statement you can apply to any PR of this nature.

Also: use the balance tag, not add/del

**Comment by softcerv** [comment]
> Is there some kind of lore reason for this PR or is this just "I want to eat the raw liver" reasoning? I don't see anything in your "why it's good" that isn't a fairly generic statement you can apply to any PR of this nature.

I feel like this makes sense because Teshari are a raptor-like species.

**Comment by RikuuTheRiolu** [comment]
> Is there some kind of lore reason for this PR or is this just "I want to eat the raw liver" reasoning? I don't see anything in your "why it's good" that isn't a fairly generic statement you can apply to any PR of this nature.
> 
> Also: use the balance tag, not add/del

ah sorry! im a bit new to the GitHub scene as ive never done something like this before so i dont expect it to be a perfect first time! 

However as for the lore reasoning i ripped a bit from Polaris because i saw a quote from the funeral rights. where it says

"When a Teshari dies, they are given the funeral rites appropriate to their pack's culture. Most commonly this involves eating their dead ritually in order to return their spirit to that of the pack, or conducting sky burials which allow a Teshari's spirit to join with the world."

But I also want this to be added because. This was an intentional change once but never got added into the game for one reason or another, Alongside the fact they are raptor like creatures that primarily love meat it wouldn't be a far cry to see them eating lesser quality meats as well.

**Comment by nikothedude** [comment]
this has lore implications so it needs the teshari lore dude or gal or entity to approve it first 

most likely. thats how i assume it works in this place

**Comment by SpaceVampire** [comment]
I don't really care that much, but it might be better to just remove it from disliked foods.
Because getting a buff from eating the lowest value uncooked food feels kind of cheap.

**Comment by CliffracerX** [comment]
Tesh are raptors - fluffy cutesy genemods from the Akula or not, they're *still raptors* - and survivors of an enslaving colonizing force, at that.  Might as well let them lean into the more uncomfortable side of what Tesh are without being gamer'd by the disgust mechanic - not to mention, give them an avenue other than overdosing on caramel when the chef refuses to make meaty foods.

**Comment by hugmeorelse** [comment]
> this has lore implications so it needs the teshari lore dude or gal or entity to approve it first
> 
> most likely. thats how i assume it works in this place

Thanks! I appreciate you bringing that up.

We don't have a specific lore person for Teshari, so I'll answer this. I think this is fine. They are, indeed, a raptor-like alien species. So, from an official lore standpoint, this should be fine. However, what @SpaceVampire says does hold validity. I think at the very least, removing it from "Disliked" makes sense. Anything else is a question of balance.

**Comment by RikuuTheRiolu** [comment]
> > this has lore implications so it needs the teshari lore dude or gal or entity to approve it first
> > most likely. thats how i assume it works in this place
> 
> Thanks! I appreciate you bringing that up.
> 
> We don't have a specific lore person for Teshari, so I'll answer this. I think this is fine. They are, indeed, a raptor-like alien species. So, from an official lore standpoint, this should be fine. However, what @SpaceVampire says does hold validity. I think at the very least, removing it from "Disliked" makes sense. Anything else is a question of balance.

I see your reasoning though from a gameplay standpoint we are in a sense inferior to Lizard folk in almost every conceivable way with the exception of us being able to eat dairy products while they cannot. That being the Damage weakness to brute and burn and the temperature as well. Would it truly break the balance of Teshari if I were to ask for 2 liked foods and 1 disliked while they enjoy 5 liked foods and 2 disliked foods?

**Review by tf-4 — CHANGES_REQUESTED** [review]
> I don't really care that much, but it might be better to just remove it from disliked foods.
> Because getting a buff from eating the lowest value uncooked food feels kind of cheap.

Do this and it's fine

**Comment by CliffracerX** [comment]
> > I don't really care that much, but it might be better to just remove it from disliked foods.
> > Because getting a buff from eating the lowest value uncooked food feels kind of cheap.
> 
> Do this and it's fine

Mood buffs are horrifyingly inconsequential- and for a no-RP mechanics system to boot- are people really going to drag their feet about this when Tesh are already so severely debuffed in so many other ways?  Letting them survive off spare parts when the kitchen isn't making what they need in order to avoid the -10% walk speed is NOT going to dramatically reshape balance or make them overpowered.

**Comment by YakumoChen** [comment]
> Mood buffs are horrifyingly inconsequential

If it doesn't matter to you than why are you continuing to be so resistant to the requested change?

**Comment by CliffracerX** [comment]
> > Mood buffs are horrifyingly inconsequential
> 
> If it doesn't matter to you than why are you continuing to be so resistant to the requested change?

I'll word it better, then: mood buffs are horrifyingly inconsequential from a *game balance perspective*; a Teshari who got the buff from eating a liked food isn't automatically going to win over a mood-debuffed foe, doubly so when taking into account the fact they're Frail by default.  Sources of mood buffs are literally just QOL on Skyrat since we still use the system & being 10% slower is annoying.

**Comment by YakumoChen** [comment]
I think my point still stands 

You should consider this is still a buff, a fairly large one in terms of mood, whether this is a +0 or a +1 instead of a negative is not a hill worth dying on.

**Comment by CliffracerX** [comment]
> I think my point still stands
> 
> You should consider this is still a buff, a fairly large one in terms of mood, whether this is a +0 or a +1 instead of a negative is not a hill worth dying on.

It is a buff- and a fairly large one in terms of mood, which is a *quality of life* system on Skyrat that typically punishes Teshari & other races with abnormal diets.  They have only one liked food by default, TWO dislikes as-is, builtin Frail, a cold resilience buff that is insufficient to save you from damage, and a heat weakness that can make fires significantly more lethal.  The kitchen rarely puts out food that is actually edible to Tesh due to almost everything containing grain, take more damage just by existing, and don't have any meaningful mechanical buffs to their name.

Compared to other species on Rattus:
- Humans are flat-out good, with no debuffs & easy access to Liked foods from any vendor or any chef
- Felinids have self-heal, fall immunity, and two of the cheapest food types (Bugs, Gore) are Liked, with low-impact debuffs
- Lizards get almost every food type Liked, albiet with the harsh penalties of unique blood and inability to change temp
- Moths can eat almost ANY clothing subtype for a Liked buff at that & get almost immediately maxed out by just one item.
- MOST species have 2-4 Liked, with few or no Disliked or Toxics.

All of this is to say- this is a *lot* of fuss over what ultimately amounts to a minor QOL buff for Teshari players, one that *even afterwards* still puts them barely in line with the generics like Anthromorph in terms of liked to disliked food numbers - and still leaves them strictly worse than other species in almost all other areas, not to mention *still unable to eat* most food served at the kitchen - which is what gives the best, longest-lasting food on the station.

I am resistant to the requested nerf because I *play* a Teshari a majority of the time on the main station & have become intimately familiar with their weaknesses as such.  While I won't personally be using the ability to eat gore due to how Naaka is as a character, I also know a fair helping of Tesh who *do* lean into them being raptors & who'd actually benefit from it as such.  If Vox can eat your Borer-destroyed liver for an additional mood buff after saving your life, why shouldn't a *literal raptor?*

**Comment by YakumoChen** [comment]
> and don't have any meaningful mechanical buffs to their name.

They have a small sprite, which makes all the difference in melee

Anyway as I said this isn't a hill worth dying on, it's the difference between +0 and +1, and there are a lot of ways to get mood up.

**Comment by Stalkeros2** [comment]
add it; who cares about balance that'd be a cool nice little feature and i'd be able to feed teshari livers

**Comment by xHazelNuts** [comment]
> They have a small sprite, which makes all the difference in melee
> 
> Anyway as I said this isn't a hill worth dying on, it's the difference between +0 and +1, and there are a lot of ways to get mood up.

Teshari are still one tile large, and they're not that tiny. The same melee advantage could be stated for aquatics and anyone else with good species buffs by using the simple Body Size mechanic.

Listed here is my Teshari
image_2023-04-29_114303253
Compared to my Minimum height Aquatic-Based Slugcat
image_2023-04-29_114413051

Without the ears, they would be the exact same size as a normal height Teshari (Give or take a pixel or two). I don't really see how the size comes into play all that much.

**Comment by SomeRandomOwl** [comment]
> > and don't have any meaningful mechanical buffs to their name.
> 
> They have a small sprite, which makes all the difference in melee
> 
> Anyway as I said this isn't a hill worth dying on, it's the difference between +0 and +1, and there are a lot of ways to get mood up.

The small sprite is also technically a nonissue as quite literally ANY species can have a sprite as small as a tesh, hell i know some tesh who wish they can by default be bigger rather than how small all tesh are

**Comment by CliffracerX** [comment]
> > and don't have any meaningful mechanical buffs to their name.
> 
> They have a small sprite, which makes all the difference in melee

Sprite size is only a buff in *PvP melee.*  Skyrat is not a PvP server.  If you're clicking spaceman until horizontal, it's likely as a Contractor or similar antag, and you're clicking on secoffs while using a contractor baton- a one-hit down regardless of species or sprite size, secoffs who have fancy gear that increases the size of their sprite, possibly customizations like the cloak, and who are generally *not Teshari* because playing a combat role when you take significantly increased damage is pain.  Nine times out of ten, if you're taking damage from another mob, it's a simplemob and they simply get to bump into you, sprite size doesn't matter- meaning for them, Teshari are flat out an easier kill.

**Comment by SylvetteSylph** [comment]
~vore pr~

While I'm not a super big fan of removing the major difference between lizard and teshari diets, it does make sense from a lore standpoint. However, if we _are_ changing it, then going half-baked is kind of more lame. It doesn't really make a whole lot of sense roleplay-wise for a species to be able to eat gore but not like it?? Like, if you had no major opinion on eating directly from a corpse, then the inherent fact that you're eating from a corpse would be directly disgusting, no? That's sort of exactly why lizards have it set to liked, it just makes more sense that way.

Also this is like in no way a balance issue. High speed teshari exist whether you like it or not, and gore is not actively readily available for any jobs barring medical. Not to mention as stated earlier, you can make any species as small as teshari. IMO, it _only_ makes it weird for roleplay to have it like that.

Overall: if you make the changelog say "CentCom has allowed Teshari to eat your flesh if you look at them wrong" then this will be a good PR

**Comment by SomeRandomOwl** [comment]
I do have to add that this entire point becomes moot if someone decides to pick back up #18432 which would change food likes and dislikes to a character by character preference system, because let's face it, people are weird, some people are vegans, some are strictly meat eaters (and some clinically insane are cannibals) someone adopting #18432 and just continuing with that may just be the better option than just statically setting food prefs as this PR intends to continue with.

I don't know about the rest of you all, but I think that leaving food preferences up to character by character basis rather than statically set would be a significantly better option

**Comment by SylvetteSylph** [comment]
> I don't know about the rest of you all, but I think that leaving food preferences up to character by character basis rather than statically set would be a significantly better option

Also 100% agree, but this is entirely based on that PR being picked up again. It probably makes more sense to develop the game that exists to be as good as possible without worrying about what might potentially become moot if a PR that isn't actively being worked on goes through.

If someone _does_ bring it back though, by all means is player choice better on this front.

**Comment by tf-4** [comment]
Let me know if you plan to make the requested changes

**Comment by CliffracerX** [comment]
> Let me know if you plan to make the requested changes

Do you plan to address the concerns that those changes are *unnecessary*?  There's been a significant amount of discussion since you posted your alteration request, and coming down from on high after ignoring the thread for a week to say "make my changes or get closed" just feels icky.

**Comment by tf-4** [comment]
> Do you plan to address the concerns that those changes are unnecessary?

no

**Comment by CliffracerX** [comment]
> no

Do you have anything more to say for why those changes *are* necessary- anything to say at all, than a single "no?"

**Comment by MidoriWroth** [comment]
Dunno why this is such a big issue, it’s just making them able to eat gore which makes sense being raptors who cannot process grain and such like lizards. Some here are acting like the PR is gonna double their health or something, it ain’t that serious 😒

**Review by tf-4 — APPROVED** [review]

**Pull request merged**
