### PR TITLE
[Non-Modular]The Buff nobody wanted. Wallet

### PR DESCRIPTION
**Pull request by Guidesu**
## About The Pull Request
Just increased the wallet storage for one and you can put epi-pen on it...
Why..?
Why not it's just good to have things which can save your life without messing with your cluster inside of your backpack.

## Why It's Good For The Game
Honestly, it is more QOL thing.
Being able to put normal syringes but no epi-pen?
Probably an oversight

## Changelog
:cl:
balance: Wallet have one extra space and can store epi-pens or any kinda of medical pens

/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
balance ruined.

**Comment by heretomakecomments** [comment]
I'm no coder and can barely read the code for this small change, but I like it! Can you also put photos in the wallet? I've yet to try.

**Comment by DiscountDirtyDan** [comment]
This is an awesome idea. Could you make allergy warning necklaces fit in there too?

**Comment by Guidesu** [comment]
> This is an awesome idea. Could you make allergy warning necklaces fit in there too?

Sure.
I was thinking to add a passport and such but that is for another time.

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
