### PR TITLE
[NONMODULAR] Ghosts don't turn visible round-end

### PR DESCRIPTION
**Pull request by NullDagaf**
## About The Pull Request

title
only added comments in seperate lines so it shouldn't cause merge issues ever :tm:

## Why It's Good For The Game

shuttle arriving at central command shouldn't bring ghosts into the corporeal plane
also lrp or sthing

## Changelog
:cl:
del: Ghosts don't appear on EORG anymore
/:cl:

### CODE REVIEW

**Comment by NullDagaf** [comment]
okay the commit only changed what i wanted it to good

**Comment by FlamingLily** [comment]
finally, dorms ghosts can stay without fear of being spotted

**Comment by Oscari-pog** [comment]
We still have EORG and unless you think that EORG is roleplay-friendly this PR is pointless

**Comment by NullDagaf** [comment]
> We still have EORG and unless you think that EORG is roleplay-friendly this PR is pointless

okay great
i quite don't care

**Comment by Gandalf2k15** [comment]
Until we get actual EORG rules this isn't needed, it can be reopened when we actually have a use 👍

**Comment by NullDagaf** [comment]
> Until we get actual EORG rules this isn't needed, it can be reopened when we actually have a use 👍

Got it, deleting the branch.

**Pull request closed without merging**
