### PR TITLE
CRITICAL FIX adds dorms vendor to ghost cafe

### PR DESCRIPTION
**Pull request by FlamingLily**
## About The Pull Request
yeah

## Why It's Good For The Game
how has this not already been the norm wtf

## Changelog
:cl:
fix: Ghost cafe now has a dorms vendor
/:cl:

### CODE REVIEW

**Comment by FlamingLily** [comment]
yesssssss label it as a fix skyrat bot let me rake in that gbp 😈

**Comment by RatFromTheJungle** [comment]
sex machetn in ghost cafe?!@!?!??!!?

**Comment by unit0016** [comment]
speedmerge so I can add it to DS-1 too 
because that abomination is my unholy charge

**Comment by KathrinBailey** [comment]
I hate these dumb artifacts that keep failing integration tests.

**Pull request merged**
