### PR TITLE
Allow using certain toys on cyborgs

### PR DESCRIPTION
**Pull request by thegrb93**
## About The Pull Request
Allows using kink toys on cyborgs
## How This Contributes To The Skyrat Roleplay Experience
Better borg erp
## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
[2024-05-25 21-05-17.webm](https://github.com/Skyrat-SS13/Skyrat-tg/assets/6713261/ce27124d-235b-4bc2-9cfb-19b9cfbfcf10)

[2024-05-25 21-22-42.webm](https://github.com/Skyrat-SS13/Skyrat-tg/assets/6713261/6d6cd5ad-1c99-4aa9-805a-325e241f608b)

</details>

## Changelog
:cl:
code: Can now use kink toys on cyborgs
/:cl:

### CODE REVIEW

**Comment by thegrb93** [comment]
Admittedly, I have not tested it yet on carbon targets. Will try to get another video of that in a bit

**Comment by thegrb93** [comment]
Seems to all be working fine still with carbons. Can do a vid if really needed.

**Comment by SpaceLoveSs13** [comment]
Idk how I feel about this. Will this respect and allow borgs to control their prefs related to sex toys? As well as since the code is up for all mobs, what about non-sentient mobs and everything else in the game?

**Comment by thegrb93** [comment]
> Idk how I feel about this. Will this respect and allow borgs to control their prefs related to sex toys? As well as since the code is up for all mobs, what about non-sentient mobs and everything else in the game?

The prefs are stored in the client which borgs have, and each toy checks that the user and target are either a human or robot.

**Pull request merged**
