### PR TITLE
[MIRROR] Yet ANOTHER areas splicing PR [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/77359
--------------------
## About The Pull Request
Title.

## Why It's Good For The Game
Hi! Some time last year I was responsible for breaking up the original `space_station_13_areas.dm` ~~and responsible for breaking a few things in the process~~. Anyway- I was looking at one of Ghommies PRs and was snooping around the area files again.

This PR does two things:
1. Nukes `space_station_13_areas.dm` since it was an empty file, just containing a comment that was outdated.
2. Rips apart `areas/station.dm` into `areas/station/*`.

First and foremost, `station.dm` was a whopping `1,771` lines long, and that's just for areas used among our many maps of now and then.

I also deleted `/area/misc/asteroid` because it seemed unused after doing a search.

The old `station.dm` was converted into `areas/station/misc.dm` since not every single area is going to be created with organization in mind.

I also updated comments here and there to be a little more.. obvious? Also and lists I saw were expanded out. They look so much better now!!

## Changelog

N/A this shouldn't really affect anything. Muh organization.

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Have Fun Jolly.

**Review by Jolly-66 — APPROVED** [review]

**Comment by Jolly-66** [comment]
>File was not included 

Why

**Comment by vinylspiders** [comment]
> > File was not included
> 
> Why

Because there was a single diff in the file in our version of station.dm due to a missed mirror so it didn't get deleted.

**Comment by vinylspiders** [comment]
See: https://github.com/Skyrat-SS13/Skyrat-tg/pull/23039 and merge that first

**Pull request merged**
