### PR TITLE
further lowers bluespace miner price

### PR DESCRIPTION
**Pull request by RatFromTheJungle**
## About The Pull Request

further lowers the price of the bluespace miner crate to 30k, which is more then a fair price for something that takes a decent bit of setup compared to the 800 credit miner conscript crate, or a single plasmacutter that can provide 3x the reward a bluespace miner ever could, in like 15m.

## How This Contributes To The Skyrat Roleplay Experience
Resource scarcity is a lie drummed up by the absolutely insane, shit was never scarce to begin with.

## Changelog

:cl:
balance: made the bluespace miner worth 150 crates, or 30k, which is still alot.
/:cl:

### CODE REVIEW

**Comment by chizzyyyy** [comment]
at this point just remove bluespace miner and add a "miner lootbox" which is just an ore crate randomly filled with 5 to 250 random ores

**Comment by RatFromTheJungle** [comment]
> at this point just remove bluespace miner and add a "miner lootbox" which is just an ore crate randomly filled with 5 to 250 random ores

that doesn't require any set up, or even space to open however ☹️ , but it's easier to make up extreme 'equivalents' then accept that ores were never once rare, I guess.

**Comment by chizzyyyy** [comment]
> > at this point just remove bluespace miner and add a "miner lootbox" which is just an ore crate randomly filled with 5 to 250 random ores
> 
> that doesn't require any set up, or even space to open however ☹️ , but it's easier to make up extreme 'equivalents' then accept that ores were never once rare, I guess.

It was a half joke, but with the trade offs that the BS miner has, there's no real way of properly balancing it without making miners feel obsolete.

**Comment by RatFromTheJungle** [comment]
> > > at this point just remove bluespace miner and add a "miner lootbox" which is just an ore crate randomly filled with 5 to 250 random ores
> > 
> > 
> > that doesn't require any set up, or even space to open however ☹️ , but it's easier to make up extreme 'equivalents' then accept that ores were never once rare, I guess.
> 
> It was a half joke, but with the trade offs that the BS miner has, there's no real way of properly balancing it without making miners feel obsolete.

it's like, painfully slow for alot of set up.

**Comment by Zonespace27** [comment]
Okay, I've gotten to play with the miner for a bit now. As it stands, I feel like 75k is a bit much for what it provides. At maximum tier parts, after running for 30 minutes with near 100% uptime, here's what I got:
2 Diamond
4 Uranium
8 Gold
27 Plasma
16 Silver
13 Titanium
26 Glass
44 Iron
Which, considering how it took me, a lone QM, nearly 2 hours to get the money and setup, feels a little low considering how that's 5-10 minutes at most of miner work at mid game.

**Pull request merged**
