### PR TITLE
You can no longer shove people off of tables from range

### PR DESCRIPTION
**Pull request by Zonespace27**
## About The Pull Request

You're able to shove people off tables as a borg from any range, this fixes that.
Note that according to the reporter, this is only a skyrat, not /tg/ issue.

## How This Contributes To The Skyrat Roleplay Experience

Bugs are bad.

## Changelog

:cl:
fix: Borgs can no longer shove people off tables at range.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Did you test it on /tg/ too, to be sure that it's not an issue for them as well?

**Comment by tf-4** [comment]
I feel like if it's a Skyrat-exclusive issue, there's probably a modular fix.

Possibly an issue with https://github.com/Skyrat-SS13/Skyrat-tg/pull/4561.

**Comment by Seris02** [comment]
not a fix
this is just duct tape
unless it actually is a fix, in which case, tg has it too, and you should send it off to them instead

**Comment by Zonespace27** [comment]
> I feel like if it's a Skyrat-exclusive issue, there's probably a modular fix.
> 
> Possibly an issue with #4561.

it's an issue with #4561, will push changes in a minute

**Review by GoldenAlpharex — APPROVED** [review]
Much better.

**Pull request merged**
