### PR TITLE
Icebox underground Consultant/blueshield offices

### PR DESCRIPTION
**Pull request by GuiltyNeko**
## About The Pull Request
Title, I took a lot of inspiration from the blueshift offices when making this. Entrance is in the left bridge area, yes it makes less room to get in, no you weren't using that much space anyways.
~~As the office is directly underneath the windowed area to the left of the bridge, the snow there has been removed so as to allow you to watch the consultant chew out officers for breaking regs, or whatever they do in their offices.~~ Ganymede asked for a cafe, so there we are, a cafe.
Consultant's office has two desks, a fishtank, and the famous employment records, while their bedroom has the pile of smokes and booze/shotglasses from blueshift rep's office. Blueshield gets drinks, and some consoles.
There's a one by one maintenance room with a space heater, god knows they'll need it with the included exterior airlock.
Blueshield and rep offices have privacy shutters/curtains, lobby does not. You cannot have your cake and eat it too.
Beds of both rooms have been strategically positioned so that, as long as they stay entirely on their beds themselves, nobody will be able to peep on either one without removing a window or a wall, in both cases getting command on their asses for breaking into the bridge. So, ya know. Enjoy your "privacy".

My main reason for this PR, and the way I did it, was the lack of a rep's office on blueshift, and wanting to make more use of the extensive space provided by icebox, and for further clarification, I explicitly wanted to put it close to the bridge. Also something something fuck box layouts.

~~Oh yeah, and I stealth removed that FUCKING double plasma window around the SM. It's annoyed me for absolutely forever and I'm truly so tired of it.~~ I got told to not do this, so... eh. Whatever.

## How This Contributes To The Skyrat Roleplay Experience
Consultant and bluey offices on icebox. What's not to love?

## Pictures
image
image
image

As a parting note, this will allow players to create whatever they want in that area above the rep's office without needing a holofan, as the area won't have any special air to deal with. Also yes, I tested all this.

## Changelog

:cl:
add: Blueshield and Nanotrasen Consultant's offices have made their way to icebox
/:cl:

### CODE REVIEW

**Comment by GuiltyNeko** [comment]
By the way I spent literally an hour chasing down an issue with the map conflict thing trying to figure out why it was erroring only to find out I missed a damn quotation. Literally an hour.

**Comment by YakumoChen** [comment]
The plasma window thing is an upstream issue, I recommend you revert that and fix it up there instead.

**Comment by YakumoChen** [comment]
also that window with the curtain on the very far right has a view of a shutter and that annoys me a lot. Please make it just a normal wall.

**Comment by MassacreDemigirl** [comment]
image
Inner shutterwindows look a bit odd, might want to square up or just replace the inner ones with walls
___
image
image
These should be R-Walls as bluey and ntr office are command areas

**Comment by MassacreDemigirl** [comment]
image
might want to just tile this off to give NTR privacy with their clientele and add usable area to the hallway. kinda like a secondary commisary or a quebecs coffee shop

**Comment by GuiltyNeko** [comment]
> Inner shutterwindows look a bit odd, might want to square up or just replace the inner ones with walls

Honestly inner shutter windows look LESS odd. I REALLY don't like diagonal wall connections and I wanted to avoid this being a big ugly box.

> might want to just tile this off to give NTR privacy with their clientele and add usable area to the hallway. kinda like a secondary commisary or a quebecs coffee shop

Sure, I can do that.

> The plasma window thing is an upstream issue, I recommend you revert that and fix it up there instead.

I know it's an upstream issue, I don't map to improve TG, I map to improve skyrat. I'm not going to bother doing it upstream, that's simply outside the realm of shit I care about.

Edit: Linters say I have multiple identical pipes on the same tile, too. I caught a few of these kinds of things already when doing it but gawd I did a lot more of this than I normally would.



> also that window with the curtain on the very far right has a view of a shutter and that annoys me a lot. Please make it just a normal wall.

I put it there anyways because angle bullshit and if you imagine that you're sitting in the chair on the right side desk, if I remove that window, you get less of a view, because again, angle bullshit. The window isn't for looking straight out of, it's for dealing with the angle bullshit.

Edit edit: Icebox does not have a vacant commissary, or more specifically, does not use that area type anywhere on the map.

**Comment by GuiltyNeko** [comment]
For further clarification on the inner corner shutter windows, these two are EXTREMELY ugly.
image
image
This is why I did it the way I did, is because really, it's the least ugly option.

**Comment by GuiltyNeko** [comment]
This is what a commissary looks like in the timeline that has a commissary above the consultant's office instead of empty space.
image

**Comment by GuiltyNeko** [comment]
Linters haunt me somebody say it's not my fault.
Edit: Yeah no not my fault, blueshift is throwing errors, not me.

**Comment by MassacreDemigirl** [comment]
Hey I think icebox does not have the coffee shop so wink wink add a coffee shop in there mayhaps?

**Comment by GuiltyNeko** [comment]
Okay so there's a coffee shop now. Honestly? Better use of the space than that ugly "oh look it's snowing" block of windows.
image

**Comment by GuiltyNeko** [comment]
Now in darker colors I guess. If I do one more commit on this fucking coffee shop I'm adding it to the PR title.
image

**Comment by MassacreDemigirl** [comment]
what a zased pr

**Comment by YakumoChen** [comment]
> I know it's an upstream issue, I don't map to improve TG, I map to improve skyrat. I'm not going to bother doing it upstream, that's simply outside the realm of shit I care about.

This goes against our development process. Either fix it upstream or leave it alone so there's no conflict when someone does fix it.

**Comment by Gandalf2k15** [comment]
ok

**Pull request merged**
