### PR TITLE
[modular] [ready] (probably) added brig medic and sarg to locked item lists in loadout 

### PR DESCRIPTION
**Pull request by thestubborn**
you cant be a sergeant cowboy

or wear scrubs as a brig medic

this fixes that, enhancing cowboy roleplay by about 15%, and the ability to look cool by 90%

pew4zorsl5j21

meaning the black paws ride again

### CODE REVIEW

**Comment by tf-4** [comment]
follow da format

**Comment by RatFromTheJungle** [comment]
> 
> 
> follow da format

no 😈

**Comment by thestubborn** [comment]
> 
> 
> follow da format

what format, if you mean the title it actually escaped my mind bc I had to remake this

**Comment by FlamingLily** [comment]
> what format, if you mean the title it actually escaped my mind bc I had to remake this

this format probably




## About The Pull Request
you cant be a sergeant cowboy

or wear scrubs as a brig medic

this fixes that, enhancing cowboy roleplay by about 15%, and the ability to look cool by 90%


## Why It's Good For The Game
image


## Changelog
:cl:
fix: Security Medics and Sergeants can now get cowboy gear and other security loadout items
fix: Security Medics can now get scrubs and other medical loadout items
/:cl:

**Comment by thestubborn** [comment]
i hate this

**Comment by thestubborn** [comment]
I MOVE AGAIN
https://github.com/Skyrat-SS13/Skyrat-tg/pull/4637

**Pull request closed without merging**
