### PR TITLE
Cyborg shapeshifter

### PR DESCRIPTION
**Pull request by SarmentiCampbell**
## About The Pull Request
Ey, Cyborg Shapeshifter is back. Only as a upgrade now and not exclusive to the syndie borg

## Why It's Good For The Game
Hey, It could be used for stuffs and it would be also nice when the ghost cafe is getting ported over

## Changelog
:cl:
add: Added the borg shapeshifter upgrade, Unlockable after the illegal technology node has been unlocked
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Resolve conflicts and we can see about merging

**Comment by Gandalf2k15** [comment]
Runtimes, check checks.

**Comment by Gandalf2k15** [comment]
Update this to master, runtimes are occuring, go ahead and test this out, and then look at runtimes in game.

**Comment by Funce** [comment]
What a fun bug to hunt for!

**Comment by SarmentiCampbell** [comment]
Ey!

**Pull request merged**
