### PR TITLE
A few modifications to icebox's brig

### PR DESCRIPTION
**Pull request by cheapcents**
## About The Pull Request

A few modifications for Icebox's brig, made by the original mapper.

Added reinforced windows and windoors below the interrogation cells.
Changed the snowmobile storage to include a dedicated airlock.
Added a few vending machines at the bottom right of the brig, normally there on other stations but not previously on this one, which made that little corner seem a little too empty.
Added reinforced windows inbetween each cell on the brig. Prisoners now have more stuff to look at while waiting to be released. Breaking in is a little harder.
Added flashers inside prisoner cells.
Added toolboxes next to warden's office. Modifying the brig is a little easier.
Removed grayscale chairs on the courtroom, gave titles to a few of them.
Added a carpet to lawyer's office. It looks a little neater now.
Replaced chasm tiles next to execution with openspace tiles.
Replaced iced plates on outer brig airlocks to smoothed ones. They look nicer.

## Changelog

:cl:
qol: Made several small modifications to Icebox's brig.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
@cheapcents Your PR name literally says nothing about the content. Your changelog is also not formatted properly and will not work out.

**Comment by cheapcents** [comment]
> 
> 
> @cheapcents Your PR name literally says nothing about the content. Your changelog is also not formatted properly and will not work out.

I changed the name shortly after posting it.

Also, I'll edit the changelog. I was not aware that it would appear in the ingame changelog.

**Comment by YakumoChen** [comment]
What's different

Did you fix making transporting prisoners not a pain in the ass?

**Comment by cheapcents** [comment]
> 
> 
> What's different
> 
> Did you fix making transporting prisoners not a pain in the ass?

Check the map diff renders. Also, updated the description.

The issue with transporting prisoners is because of stairs making it so you let go of someone you're pulling when you change zlevels through them... I remember this not being an issue at all. While this isn't fixed, you can use the normal ladder in the CO's office or push / throw them down the stairs.

**Comment by YakumoChen** [comment]
> 
> 
> > What's different
> > Did you fix making transporting prisoners not a pain in the ass?
> 
> Check the map diff renders. Also, updated the description.
> 
> The issue with transporting prisoners is because of stairs making it so you let go of someone you're pulling when you change zlevels through them... I remember this not being an issue at all. While this isn't fixed, you can use the normal ladder in the CO's office or push / throw them down the stairs.

can you just replace the stairwell with a lift then?

**Review by KathrinBailey — APPROVED** [review]

**Pull request merged**
