### PR TITLE
Random assortment of clothes

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Just adds a bunch of new clothing items to the loadout that were unused in the dmi.

image

## Changelog
:cl:
add: Added an asortment of clothing items to the loadout, tactical hawaiian anyone?
/:cl:

### CODE REVIEW

**Comment by Sethnov** [comment]
do they have digi legs versions ?

**Comment by Gandalf2k15** [comment]
absofuckinlutelynot

**Comment by Sethnov** [comment]
> absofuckinlutelynot

can you add them ?

**Comment by Gandalf2k15** [comment]
> > absofuckinlutelynot
> 
> can you add them ?

I could but I'm not a spriter and that would be out of scope

**Comment by thestubborn** [comment]
if you keep doing this gandalf i'm gonna run out of clothing in the shame pile

**Pull request merged**
