### PR TITLE
Fixed "Safeguard" run time error in game options config

### PR DESCRIPTION
**Pull request by ORCACommander**
Game Options config file was pointing to a "safeguard" law which does not exist. changed it to armadyne_safeguard to clear run time error.

## About The Pull Request

Was debugging my own down stream when i found a run time error saying an AI law did not exist.
AI law referred to was "safeguard". this does not exist in the tg upstream version of the file. Eventually found the proper AI law in modular_skyrat/modules/sec_haul/code/misc/ai_module.dm. Further, ss13 loads the random AI list and weighted random AI law list even when this ai selection type is disabled by the config options

## Why It's Good For The Game

run time errors slow things down. killing them speeds things up.

## Changelog
:cl:
fix: Run time error from Invalid AI law in game_options.txt
config: config/game_options.txt
server: Config File Modified
/:cl:

### CODE REVIEW

**Comment by FlamingLily** [comment]
Safeguard.... you mean skyrat's current default lawset?

**Comment by ORCACommander** [comment]
> 
> 
> Safeguard.... you mean skyrat's current default lawset?

`[2021-03-18 01:42:28.467] ## WARNING: Bad lawid in game_options.txt: safeguard in code/datums/ai_laws.dm at line 265 src: Unknown Laws usr: .`

Like i said, the game is not finding it because it is looking for a law ID.
I can find the items related to safe guard and there is config/silicon_laws.txt , however config/silicon_laws.txt does not generate a law ID

**Comment by ORCACommander** [comment]
actually, found a better fix, instead of safeguard it needs to be armadyne_safeguard i think, setting to draft and gonna test

**Comment by ORCACommander** [comment]
yep that cleared it instead of safeguard just missing, it was just mislabeled.

in regard to my first commit
modular_skyrat/modules/sec_haul/code/misc/ai_module.dm

Is not where i would think to look for an AI law

**Pull request merged**
