### PR TITLE
Major Zombie Overhaul - HNZ1 & Zombie Random Event

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Okay, so it's become apparent that currently zombies are boring, shitty and really not even that fun to play. Let's change that.

TL;DR: This makes zombies a more interdepartmental venture, requiring scientific interaction to synthesize the cure to this horrific virus. Medical still needs to actually perform the cures via surgery. Virology for the vaccine

Note: It is not a virus in the traditional sense, it is a custom component I just put together.

Let's break this down into sections: New zombies, HNZ1 virus, RNA extractor, RNA vials, RNA recombinator, HNZ1 cure, science nodes

## New zombies
So the basic zombie has been changed and upgraded slightly. They have some basic stat changes. They are slightly faster, and they are less "zombie" like. We want to go for a more 28 days later feel here. You'll want to fortify your departments for this threat, should it occur.

The way the virus is actually spread has changed, instead of being a gauranteed infection, it now checks if the poor sod can be injected. If they cant - no infection! This part is a major debuff.

There is no stupid black ooze organ now, all datum, only datum, datum all the time.

## HNZ1 Virus
image
"Human Neurovirus Z-1"

The "romerol" thing is from bygone times. Instead we now have the HNZ1 virus, a more technologically advanced and lore-friendly virus. It's manufactured by Nanotrasen's Bioweapons division. Realistically once this thing gets out, it's very hard to stop the spread of it. However, Nanotrasen do have ways to recombinate the RNA of the virus, thus making it less of a problem to deal with. More on this to come later.

## RNA extractor
image
RNA vial and extractor

The RNA extractor is very important in the fight against zombies, this is used to extract RNA from LIVING zombies, you need to attack them with it and they need to be alive. It fills the inserted vial(assuming there is one) with RNA, this can then be uploaded into the RNA recombinator. A zombie can only have it's RNA extracted every so often, so you can't spam extract the same live zombie! What we at NBD suggest is to capture a few and harvest their RNA over time. Remember, stuns work on these guys!(They don't even need to have a ckey attached).

## RNA Recombinator
image
image

Nanotrasen RNA Recombinator

The RNA recombiator can do one of two things:

Create a cure:
The RNA Recombinator is the pinnacle of NBD, it's made to recombinate virus RNA so efficiently that you only need a slither of RNA from the original virus. Use this machine(and protect it, or make loads of them) to manufacture the HNZ1 cure! It takes a while to recombinate the RNA you put inside it, and can only do one at a time, but it works very well! Make sure you keep it powered too! It increments in percentage every so often, depending on internal components(upgrade them to make it MUCH faster). The basic Nanotrasen Bioweapons guide to defeating this virus is harvesting the RNA from live (braindead)specimens, and using these machines to go go gadget. 

Create more virus:
It can also create more virus with the RNA sample, this is useful if you want to make some test monkes!

## HNZ1 cure
image
"Experimental HNZ1 Cure sample"

This is the final stage in the war against the virus, you can completely cure someone with one of these. Simply slap it into them via surgery and they'll be cured in no time! (hopefully). An added benefit to this is that it provides several minutes of immunity, meaning you cannot pick the virus up again if you're bitten! Brilliant. It halts the virus in it's tracks even if said person has not... bit the dirt yet. Tie the zombie up, insert this in them, then in a few minutes... bam, new human!

## SCIENCE!
image

Here's the techweb system for the varus research tech, you can print as many as you want out! R&D is **integral** to this fight against the zombuls.

## Admin only event
Adds an admin event so admins can do this ICl'y.

I understand there will be some balance concerns with this, this needs TM'd first, I'll deal with all that.

## Changelog
:cl:
add: Zombies have been overhauled! See: https://github.com/Skyrat-SS13/Skyrat-tg/pull/4659
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
It's all datums, holy shit.

**Comment by Gandalf2k15** [comment]
HMM YES TODAY I WILL LINTER

**Comment by SpookyTheFox** [comment]
>zombies are boring, shitty and really not even that fun to play

Said no one ever. I don't know where this is coming from. One of the best things about zombies is that you, yes YOU the individual spaceman, can have a material impact on the outcome of the round, by working to deconvert zombies using your knowledge of the game.

Everything I see about these proposed changes makes the majority of the station non-participants, and puts this round monopolizer in the hands of a small number of players that probably don't know or care enough to build the RNA machine, if they are even participating in the round at all.

**Comment by Gandalf2k15** [comment]
> > zombies are boring, shitty and really not even that fun to play
> 
> Said no one ever. I don't know where this is coming from. One of the best things about zombies is that you, yes YOU the individual spaceman, can have a material impact on the outcome of the round, by working to deconvert zombies using your knowledge of the game.
> 
> Everything I see about these proposed changes makes the majority of the station non-participants, and puts this round monopolizer in the hands of a small number of players that probably don't know or care enough to build the RNA machine, if they are even participating in the round at all.

What makes you say that? You know, just aim for the head, like you said

**Comment by Gandalf2k15** [comment]
Clearly, you are assuming based on nothing that conventional means don't work on em. This changes how you CURE a person, it's far more RP friendly.

**Comment by SpookyTheFox** [comment]
> 
> 
> Clearly, you are assuming based on nothing that conventional means don't work on em. This changes how you CURE a person, it's far more RP friendly.

Forcing one side to follow a convoluted mechanical path and pretend to role play it doesn't sound like fun to me. The far more likely outcome is, since the cure will not be immediately available, the zombies are just going to get shuttle gibbed upon discovery. This PR makes curing them so difficult, and unable to be done by all the people that sit around all day waiting for something to do, IE medbay.

**Comment by Gandalf2k15** [comment]
> > Clearly, you are assuming based on nothing that conventional means don't work on em. This changes how you CURE a person, it's far more RP friendly.
> 
> Forcing one side to follow a convoluted mechanical path and pretend to role play it doesn't sound like fun to me. The far more likely outcome is, since the cure will not be immediately available, the zombies are just going to get shuttle gibbed upon discovery, since this PR makes curing them so difficult, and unable to be done by all the people that sit around all day waiting for something to do, IE medbay.

It moves it from medbay to science, dude, read the damn PR. It's EASIER in many ways to MASS produce a cure that can be stockpiled and used in the event of you getting bitten, it also provides IMMUNITY. Holy shit, read the PR.

**Comment by Gandalf2k15** [comment]
> > Clearly, you are assuming based on nothing that conventional means don't work on em. This changes how you CURE a person, it's far more RP friendly.
> 
> Forcing one side to follow a convoluted mechanical path and pretend to role play it doesn't sound like fun to me. The far more likely outcome is, since the cure will not be immediately available, the zombies are just going to get shuttle gibbed upon discovery. This PR makes curing them so difficult, and unable to be done by all the people that sit around all day waiting for something to do, IE medbay.

image

**Comment by YakumoChen** [comment]
Moving the cure from medbay to science is the problem, as surgically curing zombies is much more fun and engaging, and taking content away from medbay, a department that in most rounds has very little to do a majority of the time, is not that cool.

Science has a _lot_ of content available that can last them a majority of the round, medbay has a lot of content frontloaded and only has a little progression for them that isn't round-specfic, and the vast majority of that is just "medical doctors being engineers to make medbay look nice"

**Comment by Gandalf2k15** [comment]
> Moving the cure from medbay to science is the problem, as surgically curing zombies is much more fun and engaging, and taking content away from medbay, a department that in most rounds has very little to do a majority of the time, is not that cool.
> 
> Science has a _lot_ of content available that can last them a majority of the round, medbay has a lot of content frontloaded and only has a little progression for them that isn't round-specfic, and the vast majority of that is just "medical doctors being engineers to make medbay look nice"

It's not fun when people instantly metagame it. Zombies are hella boring when you're instantly metagamed and dezombified. This at leasts means you have to TRY and manufacture a cure, not just "hurr durr operate here and remove this hehehe". Science and medical need to work together. The actual virus can be postoponed by constant medical support. Honestly this is a debuff for zombies, it will need to be tested and balanced, with changes made.

**Comment by YakumoChen** [comment]
Honestly I see zombies causing one of two outcomes in a round

-The research never gets done for whatever reason, zombies either overrun or get slaughtered by security. All zombies killed are round removed for a significant chunk of time minimum (whereas before they would just be cured and revived)
-Zombies begin after the research is done, so the cure is speedran and the plague contained before the zombies get to do anything

Slapping a zombie with a Thingy and waiting a whole minute to slap them with another Thingy isn't really that interesting or cool or engaging either compared to surgical cures. Being captured alive and put in a GBJ to be used as a cure guinea pig for the Thingy Waiting Machine also sounds like a snorefest.

**Comment by Gandalf2k15** [comment]
> Honestly I see zombies causing one of two outcomes in a round
> 
> -The research never gets done for whatever reason, zombies either overrun or get slaughtered by security. All zombies killed are round removed for a significant chunk of time minimum (whereas before they would just be cured and revived)
> -Zombies begin after the research is done, so the cure is speedran and the plague contained before the zombies get to do anything
> 
> Slapping a zombie with a Thingy and waiting a whole minute to slap them with another Thingy isn't really that interesting or cool or engaging either compared to surgical cures. Being captured alive and put in a GBJ to be used as a cure guinea pig for the Thingy Waiting Machine also sounds like a snorefest.

Zombies can easily break through things as they've also recieved a decent buff. I hate that you think surgery is fun for medical, when you get overwhelmed and overrun things go downhill very quickly. And why the fuck would some medical doctor know how to cure this virus? No, science needs to research it first. That's RP friendly. Not gamering it.

**Comment by YakumoChen** [comment]
Surgery is fun for medical doctors because that is literally 99% of the content they have, regardless of how overran they are.

**Comment by Gandalf2k15** [comment]
> Surgery is fun for medical doctors because that is literally 99% of the content they have, regardless of how overran they are.

It's not very fun for the zombies.

**Comment by YakumoChen** [comment]
More fun for zombies then being put in an iron cubicle and only let out to be slapped with the Thingy Collector until everyone is cured.

**Comment by Gandalf2k15** [comment]
> More fun for zombies then being put in an iron cubicle and only let out to be slapped with the Thingy Collector until everyone is cured.

Takes a long time for the cure to be made.

**Comment by YakumoChen** [comment]
That's a long time to wait in Gay Baby Jail

**Comment by Gandalf2k15** [comment]
> More fun for zombies then being put in an iron cubicle and only let out to be slapped with the Thingy Collector until everyone is cured.

Cure lasts 3 minutes.

**Comment by Gandalf2k15** [comment]
> That's a long time to wait in Gay Baby Jail

I understand you're just fishing for a bite.

**Comment by YakumoChen** [comment]
Your PR recommends herding live zombies into a cage to be slapped with the Cure Making Device. How is that fun?

**Comment by Gandalf2k15** [comment]
> Your PR recommends herding live zombies into a cage to be slapped with the Cure Making Device. How is that fun?

They don't need to be sentient, get a monkey, expose it, done, got yourself a test subject, just like real life. If you have a sentient one, it WILL break out.

**Comment by YakumoChen** [comment]
That sounds like you're prying all the content of curing zombies away from medical and giving it to the exactly one player in virology who just presses buttons on a machine and slaps a monkey human every so often.

**Comment by Gandalf2k15** [comment]
> That sounds like you're prying all the content of curing zombies away from medical and giving it to the exactly one player in virology who just presses buttons on a machine and slaps a monkey human every so often.

I could easily do this: Make it a surgery step to implant the cure.

**Comment by Gandalf2k15** [comment]
Bam, now it's a medical and science thing, I guess you're gonna nitpick something else though.

**Comment by YakumoChen** [comment]
If you're baiting me for some kind of toxic reply I'm not going to bite either.

> > Surgery is fun for medical doctors because that is literally 99% of the content they have, regardless of how overran they are.
> 
> It's not very fun for the zombies.

I can go back to this though. If the zombies aren't getting deimplant surgery now, what are they doing until that point after someone kills one? Being cuffed and killed over and over until the cure is done?

**Comment by Gandalf2k15** [comment]
> If you're baiting me for some kind of toxic reply I'm not going to bite either.
> 
> > > Surgery is fun for medical doctors because that is literally 99% of the content they have, regardless of how overran they are.
> > 
> > 
> > It's not very fun for the zombies.
> 
> I can go back to this though. If the zombies aren't getting deimplant surgery now, what are they doing until that point after someone kills one? Being cuffed and killed over and over until the cure is done?

They can't be cuffed.

**Comment by YakumoChen** [comment]
How are you supposed to contain them then

**Comment by SpookyTheFox** [comment]
> 
> 
> > If you're baiting me for some kind of toxic reply I'm not going to bite either.
> > > > Surgery is fun for medical doctors because that is literally 99% of the content they have, regardless of how overran they are.
> > > 
> > > 
> > > It's not very fun for the zombies.
> > 
> > 
> > I can go back to this though. If the zombies aren't getting deimplant surgery now, what are they doing until that point after someone kills one? Being cuffed and killed over and over until the cure is done?
> 
> They can't be cuffed.

That is going to be an issue. I do not expect players to role play favorably with zombies that insist on not patiently waiting to be cured. They are almost certainly going to be gibbed or cremated while everyone waits for a cure that likely never materializes.

**Comment by Gandalf2k15** [comment]
> How are you supposed to contain them then

Stun them, delimb them(they'll regenerate eventually), or, just manufacture the cure, put yourself in a bit of danger, and cure them.

**Comment by Gandalf2k15** [comment]
> > > If you're baiting me for some kind of toxic reply I'm not going to bite either.
> > > > > Surgery is fun for medical doctors because that is literally 99% of the content they have, regardless of how overran they are.
> > > > 
> > > > 
> > > > It's not very fun for the zombies.
> > > 
> > > 
> > > I can go back to this though. If the zombies aren't getting deimplant surgery now, what are they doing until that point after someone kills one? Being cuffed and killed over and over until the cure is done?
> > 
> > 
> > They can't be cuffed.
> 
> That is going to be an issue. I do not expect players to role play favorably with zombies that insist on not patiently waiting to be cured. They are almost certainly going to be gibbed or cremated while everyone waits for a cure that likely never materializes.

This PR is to add support mechanics for RP, the thing about it is that game mechanics SUPPORT RP, not create it. This adds a layer for a scientific explanation(it goes a long way in an RP server) for it's existence. Science can all gather round the test subject NPC, try getting samples of RNA, maybe get bitten, you know, have to quarantine that person. If you don't look at it from a purely gamer perspecitve, it's easy to see how this is more RP friendly. Remember the zombies on a shuttle event?

**Comment by YakumoChen** [comment]
Do you think being a nugget / repeatedly killed zombie is preferable to a zombie strapped to a surgery bed getting organ removal?

The element of danger goes out the window when you can just slap yourself with a cure and be good for 3 minutes.

A lot of this PR really seems to hinge on putting zombie players in an equally shitty spot waiting to get cured while taking most of the fun away from the hands of bored medical doctors.

**Comment by Gandalf2k15** [comment]
> Do you think being a nugget / repeatedly killed zombie is preferable to a zombie strapped to a surgery bed getting organ removal?
> 
> The element of danger goes out the window when you can just slap yourself with a cure and be good for 3 minutes.
> 
> A lot of this PR really seems to hinge on putting zombie players in an equally shitty spot waiting to get cured while taking most of the fun away from the hands of bored medical doctors.

We can't have the cake and eat it unfortunately here. This only adds RP support. If our players, on an RP server, favour that over manufacturing a cure, well... I'm sorry but we're fucked. 

I refuse to allow current zombies to exist. This is how we can finally get some more random events.

**Comment by Gandalf2k15** [comment]
What I could also do is make it so after a zombie is infected for so long, it can't be cured, just like the Tvirus.

**Comment by FlamingLily** [comment]
I like the PR as is, tbh.

I think my main gripe is that most people don't realise this is an RP server, but that's no issue made from the PR

**Comment by YakumoChen** [comment]
Then they'll just be gibbed and put out of the round, like a hostile changeling would.

I have to ask where the RP is here, actually. Like, this just seems like a lot of mechanics replacing a lot of different mechanics. Zombies spreading infection is functionally the same, right?

Also I should bring up a problem where this is a lot like that other changeling nerf where silicon species players get to just completely be separated and wholly immune from this brand of content.

**Comment by Gandalf2k15** [comment]
> I like the PR as is, tbh.
> 
> I think my main gripe is that most people don't realise this is an RP server, but that's no issue made from the PR

Thank you so much.

**Comment by Gandalf2k15** [comment]
> Then they'll just be gibbed and put out of the round, like a hostile changeling would.
> 
> I have to ask where the RP is here, actually. Like, this just seems like a lot of mechanics replacing a lot of different mechanics. Zombies spreading infection is functionally the same, right?
> 
> Also I should bring up a problem where this is a lot like that other changeling nerf where silicon species players get to just completely be separated and wholly immune from this brand of content.

See the above comment. We have had SO much fun roleplaying this shit. Please, stop looking at it from a "how can I cheese this" perspective.

**Comment by Gandalf2k15** [comment]
> Then they'll just be gibbed and put out of the round, like a hostile changeling would.
> 
> I have to ask where the RP is here, actually. Like, this just seems like a lot of mechanics replacing a lot of different mechanics. Zombies spreading infection is functionally the same, right?
> 
> Also I should bring up a problem where this is a lot like that other changeling nerf where silicon species players get to just completely be separated and wholly immune from this brand of content.

Infection is not the same anymore no

**Comment by YakumoChen** [comment]
> 
> See the above comment. We have had SO much fun roleplaying this shit. Please, stop looking at it from a "how can I cheese this" perspective.

No, explain it to me like I'm an idiot. Where is the RP here? Tell me how this encourages roleplay.

 The mechanical means to cure zombies is on the research console now so it's no longer a mystery of "what is causing this / how do I stop it". It appears to me like this doesn't encourage roleplay.
Zombies and infection spreading is mostly mechanics and zombies are in part rule bound to _be mechanical_ and not roleplay. 
Doing the research / curing zombies this way doesn't appear to introduce any roleplay from my POV
Making large sects of players largely excluded from the infection just seems like it's taking away fun / content, not roleplay.

**Comment by Gandalf2k15** [comment]
Gonna be adding a science experiment, standard techweb point cost is 18k as per discussions in discord.

**Comment by SpookyTheFox** [comment]
Another aspect of zombies this PR is not addressing, is that it's really not that much fun to play as one for most players. They *want* to be cured. Only the most moronic greytiders run around avoiding medbay until they die so that they can then dunk on everyone else with zombie claws. This PR takes that away, and the only solution offered is cremate/gib. It's a lot more fun to get cured before the infection takes hold and go back to fighting the zombies, rather than joining them. These proposed changes are pushing counter to what players actually want to do.

**Comment by Gandalf2k15** [comment]
> Another aspect of zombies this PR is not addressing, is that it's really not that much fun to play as one for most players. They _want_ to be cured. Only the most moronic greytiders run around avoiding medbay until they die so that they can then dunk on everyone else with zombie claws. This PR takes that away, and the only solution offered is cremate/gib. It's a lot more fun to get cured before the infection takes hold and go back to fighting the zombies, rather than joining them. These proposed changes are pushing counter to what players actually want to do.

There's a massive notice saying NOT TO DO THIS. DO NOT DO THIS. IT IS AGAINST POILCY.

**Comment by SpookyTheFox** [comment]
> 
> 
> > Another aspect of zombies this PR is not addressing, is that it's really not that much fun to play as one for most players. They _want_ to be cured. Only the most moronic greytiders run around avoiding medbay until they die so that they can then dunk on everyone else with zombie claws. This PR takes that away, and the only solution offered is cremate/gib. It's a lot more fun to get cured before the infection takes hold and go back to fighting the zombies, rather than joining them. These proposed changes are pushing counter to what players actually want to do.
> 
> There's a massive notice saying NOT TO DO THIS. DO NOT DO THIS. IT IS AGAINST POILCY.

What are you going to do then, ban them for not liking your game mode?

**Comment by Gandalf2k15** [comment]
> > > Another aspect of zombies this PR is not addressing, is that it's really not that much fun to play as one for most players. They _want_ to be cured. Only the most moronic greytiders run around avoiding medbay until they die so that they can then dunk on everyone else with zombie claws. This PR takes that away, and the only solution offered is cremate/gib. It's a lot more fun to get cured before the infection takes hold and go back to fighting the zombies, rather than joining them. These proposed changes are pushing counter to what players actually want to do.
> > 
> > 
> > There's a massive notice saying NOT TO DO THIS. DO NOT DO THIS. IT IS AGAINST POILCY.
> 
> What are you going to do then, ban them for not liking your game mode?

Whew, thank you for this golden comment.

**Comment by Trubbl3** [comment]
so what medbay gonna do now while all of this is happening since they aren't part of the event anymore?

**Comment by Gandalf2k15** [comment]
> so what medbay gonna do now while all of this is happening since they aren't part of the event anymore?

We've changed it, PR is out of date. It's now a medical thing, they need to operate/use the machines. To get the TECH though you need to perform an experiment on a zombie. More details to come soon.

**Comment by Gandalf2k15** [comment]
> so what medbay gonna do now while all of this is happening since they aren't part of the event anymore?

Check the PR again

**Comment by Trubbl3** [comment]
Can you find a way to get the virologist involved or have operation or surgeries to slowdown the transformation rate or pacify the zombies as a stopgap solution while the real cure is on the making?

Maybe the need of some antibodies in the form of a viro vaccine to not get infected again. Like you can get cured off the zombie virus but can be infected again without a vaccine with the antibodies

**Comment by Gandalf2k15** [comment]
> Can you find a way to get the virologist involved or have operation or surgeries to slowdown the transformation rate or pacify the zombies as a stopgap solution while the real cure is on the making?
> 
> Maybe the need of some antibodies in the form of a viro vaccine to not get infected again. Like you can get cured off the zombie virus but can be infected again without a vaccine with the antibodies

This could be a good idea, yeah, we can probably make the VACCINE part of virology.

**Comment by hugmeorelse** [comment]
As always, this is a work in progress. Getting upset over this is insipid. 

I have asked for the random event and the possible traitor item to be removed. Besides that, everything seems okay. Though, I am asking for more of an "I Am Legend" sort of approach instead of pure zombies. It fits the sci-fi setting better in my opinion.

**Comment by Gandalf2k15** [comment]
Updates:
Admin only, fine by me.
It's actually more an interdepartmental effort. Requiring Science and Medical, leaning towards medical. Medical is needed to perform surgery to delay the conversion until they can create the antivirus.

**Comment by Gandalf2k15** [comment]
You can now synthesize the virus as well as the cure. If you really want to do that...

**Pull request closed without merging**
