### PR TITLE
Coronal Mass Ejection no longer starts fires

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
see title. Plasma has been removed from CMEs. It just makes hot oxygen now.
CMEs no longer shock you and set you on fire when you neutralize them
removes the announce every time someone neutralizes a CME since it's obnoxious

## Why It's Good For The Game
Fuck this event.
Everything about this event is designed to punish you. 
CME spawns? Have a fire.
Ignore CME? Have a big old EMP
Remove CME? _Have another fire._ Enjoy being on fire, idiot, because **FUCK YOU**

## Changelog
:cl:
qol: CME no longer creates fires, especially when you're trying to neutralize them.
qol: less CME earmurder
/:cl:

### CODE REVIEW

**Comment by Trubbl3** [comment]
based and salt pr pilled

**Comment by Elli-Skala** [comment]
also a minoriy of people can take part of this event as using a nurlizer ALSO on top of the second fire shocks you

**Comment by SpaceVampire** [comment]
It is possible that you could make it... less loud? Its just such an annoying pain every time that it triggers, and the fact that they still zap up if you neutralize them seems spiteful. Its weird when that isn't how any of the other random event anomalies work.

**Comment by YakumoChen** [comment]
No, this PR only removes the fire, because I am salty and this event sucks

**Comment by YakumoChen** [comment]
I don't even know where the code is to shock you from it.

**Comment by SpaceVampire** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/blob/c0b99ccfefb8caa009572621e82ecae6443f99b8/code/game/objects/items/devices/anomaly_neutralizer.dm

Right here, where they set you on fire. I suppose it won't be as bad if they aren't spawning plasma all the time, but it always came of as kinda weird.

**Comment by YakumoChen** [comment]
already found it but thank you

**Comment by SpaceVampire** [comment]
(Only thing left is the Ear-Rape announcement spam, I'm really not sure if it needs to play the sound every single time with big bold text, but this is really more in pet-peeve level.)

**Comment by YakumoChen** [comment]
I removed some of the earrape

**Comment by Gandalf2k15** [comment]
I'll modify this myself later as there are a few other tweaks I'd like to make.

**Comment by YakumoChen** [comment]
> Modify


> But he's actually just refusing to merge the actual PR without a given reason

**Pull request closed without merging**
