### PR TITLE
[MODULAR] Purring felinids will slowly heal everyone nearby 

### PR DESCRIPTION
**Pull request by alexv-ds**
## About The Pull Request

Purring felinids will slowly heal everyone nearby, 1 burn and 1 brute every purr.

## Why It's Good For The Game

Purring catgirls its cool ^_^

## Changelog

:cl:
add: added a small heal to those on the same tile as felinid while purring. 
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
Based???????????????????????

**Comment by alexv-ds** [comment]
> 
> 
> Based???????????????????????

Based on stereotypes that cats lie on sore body parts.

**Comment by ZephyrTFA** [comment]
This doesn't make any sense at all; but I still love it.
Maybe have other species do special things like this too?

**Comment by Low3** [comment]
But actually cats lie of injured body parts simply because they are warmer and purr since they enjoy your suffering.
In conclusion: not realistic, catgirl propaganda and absolutely not based.

**Comment by alexv-ds** [comment]
> But actually cats lie of injured body parts simply because they are warmer and purr since they enjoy your suffering.
> In conclusion: not realistic, catgirl propaganda and absolutely not based.

But it's still cute

**Comment by FlamingLily** [comment]
I don't really like this, it's a species buff that doesn't really make sense. Sure, it's cute. But cute for the sake of cute and disregarding everything else...

**Comment by WhateverDimeIs** [comment]
Like it isn't a serious buff that felinids can lick bleeding wounds to stop the bleeding

**Comment by unit0016** [comment]
I can't wait for the memes in devchannels regarding this one. Not even a bad change because of the emote timer, I'm just amused by the possibility of a paramedic deciding "Aiuri sucks" and healing some poor soul by spamming *purr

**Comment by tf-4** [comment]
I think 2 might be a bit much. 1 would be more reasonable

**Comment by Vizoplez** [comment]
felinids can also fix bleeding wounds by licking them already
no

**Comment by GoldenAlpharex** [comment]
It could even be .5 damage. Just enough to say that it's there, without really making much of a difference.

**Comment by alexv-ds** [comment]
> 
> 
> It could even be .5 damage. Just enough to say that it's there, without really making much of a difference.

I think 0.5 is too small

**Comment by Stalkeros2** [comment]
> felinids can also fix bleeding wounds by licking them already
> no

Okay, and?

**Comment by lyricalpaws** [comment]
I love this pr dearly

**Comment by GoldenAlpharex** [comment]
After chatting with other devs, I think that adding an additional cooldown on this would be better.
What I'd suggest is making it so there's a 1-minute cooldown between the times it can heal, so that it doesn't feel LRP as fuck because all the funny felinid doctors circle you and purr every two seconds to get you back on your feet.
It would thus be a situational thing that could lead to interesting scenarios, without breaking balance much. If need be, I can add suggestions to show you how I'd implement that in your code.

**Comment by Cheshify** [comment]
Yeah... let's not. Why not add a positive quirk that gives people a mood buff? I'm ok with Golden's suggestion above, but this feels a lot more situational and could be a good positive quirk wherein hearing someone purr gives you a big mood bonus.

**Comment by Cheshify** [comment]
So, to go further on my previous comment. This PR sets a precedent that I think a few devs are very wary about. That being: well if X race can have a special healing mechanic tied to emotes, why can't mine? I believe something like this happened on another codebase, another dev told me something similar happened on codebases such as :(Cit-RP, Paradise, V.O.R.E, Aurora)

**Comment by alexv-ds** [comment]
> 
> 
> After chatting with other devs, I think that adding an additional cooldown on this would be better.
> What I'd suggest is making it so there's a 1-minute cooldown between the times it can heal, so that it doesn't feel LRP as fuck because all the funny felinid doctors circle you and purr every two seconds to get you back on your feet.
> It would thus be a situational thing that could lead to interesting scenarios, without breaking balance much. If need be, I can add suggestions to show you how I'd implement that in your code.

Okay. I'll add a cooldown. But what about numbers?
With recharge per minute, how much damage to heal?

**Comment by GoldenAlpharex** [comment]
> > After chatting with other devs, I think that adding an additional cooldown on this would be better.
> > What I'd suggest is making it so there's a 1-minute cooldown between the times it can heal, so that it doesn't feel LRP as fuck because all the funny felinid doctors circle you and purr every two seconds to get you back on your feet.
> > It would thus be a situational thing that could lead to interesting scenarios, without breaking balance much. If need be, I can add suggestions to show you how I'd implement that in your code.
> 
> Okay. I'll add a cooldown. But what about numbers?
> With recharge per minute, how much damage to heal?

If this still happens, I would still keep it at 1 brute 1 burn, hell, I'd even make it either brute-only or burn-only, as otherwise it'll massively affect the gameplay without a really solid reason behind it, and would just result in people abusing it to avoid having to go to medical.

**Comment by SpaceVampire** [comment]
I support this because I play Catgirls, and they are a core TG race.
But if anything like this comes up in the future for a race that I don't play, then it is awful power-creep.

**Comment by FlamingLily** [comment]
> 
> 
> Yeah... let's not. Why not add a positive quirk that gives people a mood buff? I'm ok with Golden's suggestion above, but this feels a lot more situational and could be a good positive quirk wherein hearing someone purr gives you a big mood bonus.

I love this actually.

Cat Lover/Dog Lover, give you a mood buff when hearing *meow/*nya/*purr or *bark/*bork/*woof respectively.

**Comment by SergeiKoralev** [comment]
Joke: Next: Lizard tail wag in proximity of the supermatter decreases the rate of delamination.

Real response: This is kinda funny and probably going to wind up in appearance bans due to spam macros.

**Comment by alexv-ds** [comment]
> Joke: Next: Lizard tail wag in proximity of the supermatter decreases the rate of delamination.

Ok, in next pr

**Comment by ZephyrTFA** [comment]
> Joke: Next: Lizard tail wag in proximity of the supermatter decreases the rate of delamination.
> 
> Real response: This is kinda funny and probably going to wind up in appearance bans due to spam macros.

Doing this now

**Pull request merged**
