### PR TITLE
[MODULAR] Nerfs pepperball guns into the fucking floor

### PR DESCRIPTION
**Pull request by Vizoplez**
## About The Pull Request
Title

## Why It's Good For The Game
Pepper balls shouldn't be better than primaries unless you're wearing a security gas mask + glasses

## Changelog
:cl:
tweak: pepperballs no longer inject 50u of reagents (What the fuck?)
/:cl:

### CODE REVIEW

**Comment by Draganfrukts** [comment]
Wouldn't this be a balance change instead of a tweak? :trollface:

**Comment by Vizoplez** [comment]
no :)

**Comment by Deek-Za** [comment]
Alright so. I'll be honest this seems mostly to be a salt PR. 
I don't think it's a good idea to be making balance changes based off of a round where things went poorly for someone who wasn't prepared and got caught off-guard by a CDO. There's multiple options for protective coverings for this gun after all.
The fact is that this "Nerf" doesn't actually nerf the gun at all by addressing the wrong issue. If you do 5 over 50, it's still gonna trigger the same knockdown effect because that's just how it(The reagent) works. You can see this by using a peppersprayer which only doses 5u at a time, for an example.
I think a discussion about changing the effects of the pepper sprayer is fine, but this PR isn't anything more then a _placebo_.

**Comment by Vizoplez** [comment]
> Alright so. I'll be honest this seems mostly to be a salt PR.
> I don't think it's a good idea to be making balance changes based off of a round where things went poorly for someone who wasn't prepared and got caught off-guard by a CDO. There's multiple options for protective coverings for this gun after all.
> The fact is that this "Nerf" doesn't actually nerf the gun at all by addressing the wrong issue. If you do 5 over 50, it's still gonna trigger the same knockdown effect because that's just how it(The reagent) works. You can see this by using a peppersprayer which only doses 5u at a time, for an example.
> I think a discussion about changing the effects of the pepper sprayer is fine, but this PR isn't anything more then a _placebo_.

This is incorrect. Condensed Capsaicin, while in your system, causes blurred vision, causes you to drop items, causes multiple separate effect. This applies 5u to put it in line with pepperspray, henceforth a /nerf into the ground/. It should not be a nuclear bomb of chems that cause funny effects.

image


it also slows you until its out of your system

**Comment by Vizoplez** [comment]
AKA: 

The knockdown is fine.

The massive lingering effects the gun has is not.

**Comment by Deek-Za** [comment]
> AKA:
> 
> The knockdown is fine.
> 
> The massive lingering effects the gun has is not.

Honestly, Yeah. This is a much better explanation of what this is trying to achieve. 
And that's fair.

**Comment by FlamingLily** [comment]
As I said on the vintorez PR, this is a balance change, you'll get yelled at for mislabelling, but probably get it merged if it's labelled correctly.

**Comment by Vizoplez** [comment]
> As I said on the vintorez PR, this is a balance change, you'll get yelled at for mislabelling, but probably get it merged if it's labelled correctly.

This is less of a balance PR and more of a tweak PR for the above reasons, the pepperballs function identically, its just they have a more reasonable after-effect duration now.

**Comment by KathrinBailey** [comment]
> Wouldn't this be a balance change instead of a tweak? :trollface:

I mean 50u of chems per ball doesn't sound like intended behaviour, maybe a fix? 👀

**Comment by Gandalf2k15** [comment]
50 was too much.

**Pull request merged**
