### PR TITLE
Revert "[NonModular] Sepia/lightpink rebalance"

### PR DESCRIPTION
**Pull request by SpaceVampire**
With this new upstream PR: https://github.com/Skyrat-SS13/Skyrat-tg/pull/5117 We have a better balance for them.
Thus this one isn't gonna be needed anymore if we merge it.
Fun fact, clicking Revert doesn't given you the usual format.
So I am doing this one free-form baby.
So you can pick pink and be a pacifist, or pick Sepia and have it randomly not work.
Boom, balance.

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
I think the 'reduced' speed should stay, because pacifist or not, people being ludicrously fast 4ever is never an ideal situation, especially here with our higher tidi and slower bullets.

**Comment by SpaceVampire** [comment]
> 
> 
> I think the 'reduced' speed should stay, because pacifist or not, people being ludicrously fast 4ever is never an ideal situation, especially here with our higher tidi and slower bullets.

I feel like it could be at least somewhat buffed, given that now its going to see more use as an actual tool for like, medical staff, because you can't really fight with it, and dragging bodies slows you down already. This is kinda a double-nerf to it now, when it was already fine after that last balance. I mean, if we didn't want it, then we could have not merged the other thing, but that is already done.

**Comment by Vizoplez** [comment]
batons and nonlethal things still work, like grenades

**Comment by RatFromTheJungle** [comment]
> I feel like it could be at least somewhat buffed, given that now its going to see more use as an actual tool for like, medical staff, because you can't really fight with it, and dragging bodies slows you down already. This is kinda a double-nerf to it now, when it was already fine after that last balance. I mean, if we didn't want it, then we could have not merged the other thing, but that is already done.

above from yawet, as well as all non-direct fighting still works, pacifism is an illusion, in reality it does very little, especially when people who want to use this, will be preparing pre-emptively.

**Comment by Gandalf2k15** [comment]
Agreed.

**Pull request merged**
