### PR TITLE
NRI M42 and M40 Sprites

### PR DESCRIPTION
**Pull request by Erol509**
## About The Pull Request

Im adding two sprites, that I forgot. Its the M-42 helmet and M40 mask that can be bought from cargo. Now, teshari can wear every NRI clothes that can be bought by company. 

## How This Contributes To The Skyrat Roleplay Experience

More sprites = more fun

## Proof of Testing

Every change here is the same as in my previous NRI PR, and Im too lazy to show the results in game. They work, trust me 
image
image

## Changelog

:cl:

imageadd: Teshari M-42 helmet, and M40 Gas Mask sprites 

/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
Gas mask front/south-facing sprite is pretty goofy.

**Comment by Erol509** [comment]
@Ebin-Halcyon @tf-4

**Review by tf-4 — APPROVED** [review]
code is fine

**Review by Ebin-Halcyon — APPROVED** [review]
Apologies for being late, fine over here.

**Pull request merged**
