### PR TITLE
Minor Hotel Additions.

### PR DESCRIPTION
**Pull request by theselfish**
## How This Contributes To The Skyrat Roleplay Experience

The Hotel is in an odd space. It's essentially a sometimes spawning Interlink, it, to myself at least, has a very haunted aura about it. So I've added a few things, some desk bells, a set of clothing to the Caretaker's room, an autodrobe, etc etc.

I also added a fire axe to it's engine room. For when the Caretaker needs to...Correct...Patrons. I know it's not meant as a combat arena, it isn't meant to encourage that. It's ...Well, flavour might be the wrong word. If requested I'll change it to an empty frame.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  

image
"I said I'm not gonna hurt ya. I'm just gonna bash your brains in. I'm gonna bash 'em right the fuck in!"

image
You know the line.

image
"l like you, Lloyd. l always liked you."

(I am pretty on the fence about the glass wall. I even reverted it to iron. We don't have any reflective walls, so the mirrors were what I went with.)

image
"My girls, sir, they didn't care for the Overlook at first. One of them actually stole a pack of matches, and tried to burn it down. But I "corrected" them sir. And when my wife tried to prevent me from doing my duty, I "corrected" her."

image

</details>

## Changelog

:cl: Cursor, Delbert Grady
add: The Overlook- Err 'Twin'- Whatever the Space Hotel is called has had some minor additions.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
The-Shining-008

**Review by Zergspower — CHANGES_REQUESTED** [review]
I'd lose the axe, i wont be able to look over everything else until Sunday but hotel security exists for a reason and i was extremely careful with what items i gave this place

**Comment by theselfish** [comment]
> I'd lose the axe, i wont be able to look over everything else until Sunday but hotel security exists for a reason and i was extremely careful with what items i gave this place

...Empty cab it is, then.

**Comment by Zergspower** [comment]
I can only peek via mapdiff currently and can load the map up properly tomorrow

<Details>
<Summary>Few things</Summary>

I'm a little confused by the added golashes and mop bucket when the janitors closet exists already
image
image

The bathroom's going to need to shrink back down to what the size was, however i have a suggestion for a different layout.

First keep the water tank move, then remove the pink wall and toilet and move the urinals there instead and have it just be a singular stall toilet.
image

I think you ate the lightswitch here in the bar
image

I'm indifferent on the orange carpet but you missed a tile under the door
image


</Details>

**Comment by theselfish** [comment]
Noted.

Right.

-Orange Carpet.
This is because there's nothing close to the Overlook carpets in game.
image
Nor am I willing to try and sprite it.
-Lightswitch.
Yep, I'll move the cabs into the...Wall? Other wall? Hard to find a spot for them that isn't used.
I'll keep one out front in the wall, other in the back room. I doubt one will get emptied anyway. I also tossed a beer keg in since the bar backroom's rather empty.
-Bathroom. 
On it.
-Galoshes.
I missed the Janitor room during editing, found it during testing, forgot to remove the stuff in the staff room.

**Comment by Zergspower** [comment]
What i meant by indifferent is i didnt really care either way what carpet was used there - looks good from here

**Review by Zergspower — APPROVED** [review]

**Review by vinylspiders — APPROVED** [review]

**Pull request merged**
