### PR TITLE
[NON-MODULAR]X-01 nerf revert

### PR DESCRIPTION
**Pull request by projectkepler-ru**
## About The Pull Request
This PR change the cell of the X-01 back to its original 1200 charges vs the skyrat 1000 charges, see below for information
I couldn't find the specific pull request that changed  this sadly

## How This Contributes To The Skyrat Roleplay Experience
In all honesty, gun cargo is a wee bit too strong and a slight nudge to make energy weapon get used more, even if its just the one role I play, would be nice. I find it kinda absurd that the HoS starts with 3 gun and hes pretty much never gonna use the X-01 outside of emergency because of how few shots it hold

## Proof of Testing
image
image
image

<details>
<summary>Screenshots/Videos</summary>
  Disabler : 20 shot  vs 16
Laser : 10 shot vs 8
Ion : 4 shot vs 3 
</details>

## Changelog

:cl:
balance: reverted the nerf on the X-01 
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
I'm not sure why we lowered the cell anyways but good change. 👍

**Comment by projectkepler-ru** [comment]
> I'm not sure why we lowered the cell anyways but good change. 👍

It was part of the original ballistic sec! which also nerfed some energy weapon as far as I'm aware?
I'm currently hunting those down but it'll take time and HoS is the only sec role I really play

**Comment by projectkepler-ru** [comment]
@Paxilmaniac  IT WAS ALL FUCKING GANDALF FAULT I KNEW IT
#1346

**Review by vinylspiders — APPROVED** [review]

**Comment by vinylspiders** [comment]
Good find

**Pull request merged**
