### PR TITLE
NRI Teshari Sprites

### PR DESCRIPTION
**Pull request by Erol509**
## About The Pull Request

Im making this early, so I can slowly work on it. And post my progress here. 

**TO DO**
- [x] advanced imperial fatigues uniform + wariants (captain, medic, engineer) 
- [x] NRI soldier hev_suit+ wariants (captain, medic, engineer) 
- [x] Helmet and wariants
- [x] B42M combined armor vest +  B42M Medic wariant
- [x] Cordun-M armor system
- [x] Lower belt height (only green for now)

## How This Contributes To The Skyrat Roleplay Experience

More Sprites

## Proof of Testing
<details>
SOON

Advanced imperial fatigues uniform
image
Captain
image
Medic
image
Engineer
image

Helmets 

image
image
image
image

Hev Suit Soldier 
image
image
image
image

## Changelog

:cl:

imageadd: New NRI Sprites for Teshari species

/:cl:

### CODE REVIEW

**Review by Erol509 — COMMENTED** [review]
Przypadkowo zrobiłem komentarz

**Comment by Erol509** [comment]
only green belt for now, maybe in the future I will do for the rest

**Review by Tastyfish — APPROVED** [review]
Approving code

**Review by tf-4 — APPROVED** [review]

**Comment by tf-4** [comment]
@Ebin-Halcyon

**Review by Ebin-Halcyon — APPROVED** [review]

**Review by tf-4 — APPROVED** [review]

**Pull request merged**
