### PR TITLE
Teshari Refurbishing

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request

Tin, cleans up Teshari mob sprites giving a coherent color palette, splitting some things and generally prettifying the birds.

Some specifics this does:
-Removes the mediocre tree ear type and instead replaces them with a ponytail option you can select.

-Removes the mane ear style and the mane from the thin mane ear style, instead adding a selectable mane under the fluff dropdown menu, make sure to set your mismatched parts on

-Removes a few empty markings and fixes a few others

## How This Contributes To The Skyrat Roleplay Experience

neat

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
teshari spinaround

</details>

## Changelog

:cl:
image: Teshari have been resprited in their entirety, set your colors if they look off.
image: One new Teshari ear style, a ponytail.
image: Upright mane, and thin mane Teshari ear styles have been edited/removed, add a mane through the fluff dropdown menu. Set your mismatched parts on.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
One thing that I can't quite wrap my head around: Why do their ears/whatever the hell is on their head, have a relatively different color when viewed from the side compared to being viewed from the front or the back?
image
image


I feel like it's just a bit inconsistent between the angles, the top/front (in green) part of the ears (or whatever it's called) should probably be the same color as what you can see in the front view, otherwise it kind of feels like the source of light used to make the shading is different and a bit inconsistent between the orientations.

**Comment by hugmeorelse** [comment]
Looking good.

**Review by GoldenAlpharex — APPROVED** [review]
The new touch-ups improved them significantly, good work Halcyon!

**Comment by Ebin-Halcyon** [comment]
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 7 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself.

Blow me.

**Pull request merged**
