### PR TITLE
[RSC] Audible Reductions

### LINKED ISSUE #21465: modular_skyrat/modules/hev_suit/sound/pcv/planet.ogg is too large
`modular_skyrat/modules/hev_suit/sound/pcv/planet.ogg`

- 1:28 long
- 3.5MB size
- Reason: This sound is far too long and large for a sound that's only played in one location, that being on-activation of the PCV armor.

### LINKED ISSUE #21466: modular_skyrat/modules/alerts/sound/security_levels/gamma_alert.ogg is too large
`modular_skyrat/modules/alerts/sound/security_levels/gamma_alert.ogg`

- 2:06 long
- 4.7MB large
- Reason: Too long, too large for a sound that's only able to be played in one situation. Should be very easy to shorten it into a better looping sound.

### LINKED ISSUE #21467: modular_skyrat/master_files/sound/ambience/starlight.ogg is too large
`modular_skyrat/master_files/sound/ambience/starlight.ogg` 

- 4:07 long
- 2.5MB
- Reason: Nice song, not compressed enough, a cut-down in length would be ideal as well.

### LINKED ISSUE #21468: modular_skyrat/modules/encounters/sounds/alarm_small_09.ogg is insanely large
`modular_skyrat/modules/encounters/sounds/alarm_small_09.ogg`

- 0:06 long
- __3.5MB__ large
- Reason: Oh my god it's a 6 second looping soundbyte why is it larger than a 4 minute song

### LINKED ISSUE #21470: modular_skyrat/modules/encounters/sounds/intercom_loop.ogg is too large
`modular_skyrat/modules/encounters/sounds/intercom_loop.ogg`

- 0:15 long
- 2.6MB large
- Reason: The length is fine, it's just far too large for 15s

### LINKED ISSUE #21473: modular_skyrat/modules/encounters/sounds/engine_ignit_int.ogg is too large
`modular_skyrat/modules/encounters/sounds/engine_ignit_int`

- 0:08 long
- 1.4MB large
- Reason: Length is fine, it just needs compression

### PR DESCRIPTION
**Pull request by SomeRandomOwl**
## About The Pull Request

Ok ok ok, more audio size reductions, i probally should have just bundled my other pr with this but I got bored and decided to reduce files sizes for the project so here goes:

`modular_skyrat/modules/alerts/sound/security_levels/gamma_alert.ogg` Fixes: #21466
Length Reduced: `3m > ~13s` Now Loops Indefinitely until alert change, new size: `4.7MB > 81.3KB`

`modular_skyrat/modules/hev_suit/sound/pcv/planet.ogg` Fixes: #21465
Removed, See [Here](https://discord.com/channels/596783386295795713/640760727489085450/1112422195608682496)
Size Reduction, 3.5MB

`modular_skyrat/modules/hev_suit/sound/nri`
Removed, See [Here](https://discord.com/channels/596783386295795713/640760727489085450/1112422195608682496)
Size Reduction, ~2.4MB

`modular_skyrat/master_files/sound/ambience/starlight.ogg` Fixes: #21467
Length Kept, new size: `2.5MB > 1.23MB`

`modular_skyrat/modules/encounters/sounds/alarm_small_09.ogg` Fixes: #21468
Length reduced: `6s > 2s`, new size: `3.5MB > 21.2KB`

`modular_skyrat/modules/encounters/sounds/intercom_loop.ogg` Fixes: #21470
Length Kept, new size: `2.6MB > 104KB`

`modular_skyrat/modules/encounters/sounds/engine_ignit_int.ogg` Fixes: #21473
Length Kept, new size: `1.4MB > 56.4KB`

## How This Contributes To The Skyrat Roleplay Experience

Reduces RSC cache significantly 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

Gamma Alert:

https://github.com/Skyrat-SS13/Skyrat-tg/assets/2568378/ca34b929-8834-45c9-b2a9-13ce80740294

Starlight: 

https://github.com/Skyrat-SS13/Skyrat-tg/assets/2568378/4b2087e4-0578-4c82-b92a-e64ca371506b

Engine Ignite:

https://github.com/Skyrat-SS13/Skyrat-tg/assets/2568378/de7a59d2-3205-4c3f-80e0-7ef02084d21d

Intercom Loop: 

https://github.com/Skyrat-SS13/Skyrat-tg/assets/2568378/9c0df9a7-f35b-4849-9e3e-42dedffeff1d

Small Alarm:

https://github.com/Skyrat-SS13/Skyrat-tg/assets/2568378/fe8b35eb-f2cb-47af-8b8c-238fb357ce58

</details>

## Changelog

:cl:
sound: reduced the size and length of a few large audio files
sound: Gamma Alert level now indefinitely loops until alert level is changed, so you really know that the universe is ending
sound: NRI HEV Suit no longer has Unique sounds
sound: All HEV suits no longer have intro songs
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
My only question is, do we have a looping part for the Gamma sound effect? One of the main cool factor about it was how intense and long it was (it always made me shiver a little), and I feel like we could achieve the same effect by using a sound loop, which would still cut down drastically on the file size since the looping sound would be just there once.

**Comment by SomeRandomOwl** [comment]
> My only question is, do we have a looping part for the Gamma sound effect? One of the main cool factor about it was how intense and long it was (it always made me shiver a little), and I feel like we could achieve the same effect by using a sound loop, which would still cut down drastically on the file size since the looping sound would be just there once.

I could maybe, though i could revert that file and simple just compress it too and see what reductions i get there, i could theoretically reduce it to >1MB i think rather than 4.7MB

**Comment by SomeRandomOwl** [comment]
explorer_KFd3CnYggY


Even better than that

**Comment by SomeRandomOwl** [comment]
Updated Gamma alert 

https://github.com/Skyrat-SS13/Skyrat-tg/assets/2568378/317cb637-a3d1-406c-8071-b8323c42dade

**Comment by SomeRandomOwl** [comment]
i just noticed i titled it osc instead of RSC woops

**Comment by SomeRandomOwl** [comment]
Video of the recent push

https://github.com/Skyrat-SS13/Skyrat-tg/assets/2568378/07b076d1-2c0b-45d5-9dd6-7c69fe663ed9

**Review by Gandalf2k15 — DISMISSED** [review]
Keep the original function and don't remove anything for the sake of RSC reduction please, keep the full functionality of the suits. Sound compression is fine.

**Comment by SomeRandomOwl** [comment]
> Keep the original function and don't remove anything for the sake of RSC reduction please, keep the full functionality of the suits. Sound compression is fine.

i asked @Zonespace27  this the other day, and he told me it would have been fine as the person who requested this of me was the one who originally made the suits. Unless i misunderstood?

**Comment by Zonespace27** [comment]
image

Stalkeros advised they should be removed and I don't really have an opinion one way or another beyond the fact that decreasing the RSC size is good.

**Comment by Gandalf2k15** [comment]
> image
> 
> Stalkeros advised they should be removed and I don't really have an opinion one way or another beyond the fact that decreasing the RSC size is good.

The core HEV suit is mine so I don't want the original functionality removed, removal from subsequent subtypes is fine though.

**Review by Zonespace27 — APPROVED** [review]
sgtm

**Pull request merged**
