### PR TITLE
Adding a fighting pit to Ghost Cafe. For containment following a ruling.

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request

I added a fighting pit to follow 
image
This ruling. You get a fence and knives. OpFor/ahelp/pray for other stuff.
I fixed the alien tools not having a retractor.
Added a Chameleon ID. For whatever reason people want it.
I also spun every single stool around. They were annoying me.

## How This Contributes To The Skyrat Roleplay Experience

People enjoy fighting in the Ghost Cafe. A ruling has been made that you must make an area for it.
 This gives them an area, with a note for explanation of why it is there.

## Changelog

:cl:
add: Ghost Cafe has a fighting pit. You can also use a Chameleon ID.
qol: Ghost Cafe stools now properly face the correct direction. 
fix: There is now an Alien Retractor to match the rest of the kit.
/:cl:

### CODE REVIEW

**Comment by softcerv** [comment]
This is something most likely out of the scope of this PR, but being able to watch this via cameras like you can with the Thunderdome arena (I think you can do this, but I'm not 100% sure) would be pretty neat

**Comment by theselfish** [comment]
> This is something most likely out of the scope of this PR, but being able to watch this via cameras like you can with the Thunderdome arena (I think you can do this, but I'm not 100% sure) would be pretty neat

Most likely. Yes. I have thought of adding an advanced camera console for whatever reason.
But I think that for watching the Arena I'd need to install cameras.
Add in the fact the current thunderdome monitors don't even work and...

**Comment by tf-4** [comment]
We used to have this and it was explicitly and intentionally removed. see https://github.com/Skyrat-SS13/Skyrat-tg/pull/3820 for similar

**Comment by theselfish** [comment]
> We used to have this and it was explicitly and intentionally removed. see #3820 for similar

Yet people still want to fight in the Cafe. To the point a ruling has been made that says *If you want to have a fighting pit with your friends make yourself an area in one of the free parts and keep it there.*

This is cutting out the making part.

**Comment by theselfish** [comment]
I should also mention that in the time since that PR a Medical Wing has been re-added.

**Comment by hugmeorelse** [comment]
I appreciate the enthusiasm, but I think we're fine without it.

**Comment by hugmeorelse** [comment]
There are two reasons for this. This is another element we have to maintain for maps which is something we're already struggling to do, and the value being added here does not supersede what has to be done to maintain this. Lastly, I fail to understand why we want to take up more real estate for something that can be easy built or just done without in one of the free parts. It's not like you need an actual fighting pit to fight in. You can practice mechanics there easily.

**Pull request closed without merging**
