### PR TITLE
Song name is no longer displayed.

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Removes the song name from the widget, the reason is some songs have retarded names and there is already an option to display the song title. 

## Why It's Good For The Game

No more shitty song names being displayed.

## Changelog
:cl:
del: Song names from de widgets 
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
CUNT TGUI

**Comment by Owai-Seek** [comment]
From the chat widget or somewhere else? I honestly like the chat one because it makes it more apparent that songs are being played.

**Comment by Gandalf2k15** [comment]
It still says when a song is play, just, for admin QOL(event related) it's easier for us to have the option to tell you what is playing and what is not. Otherwise it will just display: A song

**Comment by Owai-Seek** [comment]
So it will allow you to play it with (or without) title in case you want ambiance?

**Comment by Gandalf2k15** [comment]
Yessir

**Comment by Azarak** [comment]
Shouldnt it not be displaying anything then? instead of just "A song"

**Comment by Gandalf2k15** [comment]
That would look strange. We still want to give people the option to turn the sound down and up. And stop it if need be.

**Comment by Azarak** [comment]
well if admin mans want this, and you can still lookup the song name, I think it's alright to merge

**Review by Azarak — APPROVED** [review]

**Pull request merged**
