### PR TITLE
Adds Screams & Emotes for Raptors, Rodents & Felines

### PR DESCRIPTION
**Pull request by KasparoVy**
## About The Pull Request
Sets up an emote to use the raptor purr soundfile that was already in the codebase and ports the raptor scream from https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/2340 which is a cockatoo shriek edited by BlackMajor
Credit to BlackMajor & CitRP for the sound and idea.

**EDIT:** Also adds a rodent/mouse/rat scream and squeak emote accordingly. Scream ported from Polaris/Virgo.

**EDIT2:** Also adds a feline purr emote ported from https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/2298 - credit for sound goes to @buffyuwu

## Why It's Good For The Game
Further customization of character voice, catering to saurian, raptor/avian or Teshari/Avali characters and folks who just dig these cool sounds.
**EDIT:** Also caters to rodent/mouse/rat & feline players.
One of them already existed and was just waiting for a couple lines of code to see action.

## Changelog
:cl:
soundadd: You can now select a raptor/Avali/Teshari scream in the character creator.
soundadd: Using *rpurr, you can now purr like a raptor or whatever your imagination decides.
soundadd: You can now select a rodent scream in the character creator.
soundadd: Using *squeak, you can now squeak like a mouse.
soundadd: Using *purr, you can now purr like a feline. Soft and rumbly.
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
if only we had neigh or a mouse squeak

but seriously, emote sound man good

--add a rat scream--

**Comment by KasparoVy** [comment]
@thestubborn There's Moth Squeak here - `*msqueak` but proper rat squeak would be easy, just a sec'

**Comment by thestubborn** [comment]
> 
> 
> @thestubborn There's Moth Squeak here - `*msqueak` but proper rat squeak would be easy, just a sec'

its not the same aaaaaaaaaaaaaaaaaaaa
but seriously yeah, its...alright, lol

**Comment by KasparoVy** [comment]
@thestubborn IK it ain't the same I wasn't going to leave you hanging, you're not the only one I know who'd ask and there's a reason squeak was added over on Virgo!

**Comment by Gandalf2k15** [comment]
I'll merge this soon, can you also add a *purr emote :)

**Comment by KasparoVy** [comment]
> I'll merge this soon, can you also add a *purr emote :)

Do you have a specific sound file you'd like, or one from a specific server? Otherwise I'll hunt thru other code bases and try to snipe an open use sound file otherwise

**Comment by KasparoVy** [comment]
@Gandalf2k15 Done thanks for the suggestion, forgot what a treasure trove CitRP is for emotes

We got cat, mouse & birb in here, the full package.

**Comment by Sigmar-alkahest** [comment]
sweeet, screams for the birbs.

**Comment by buffyuwu** [comment]
:)

**Pull request merged**
