### PR TITLE
[MODULAR] Adds new legless taur variant: "Goop"

### PR DESCRIPTION
**Pull request by Syrox25**
## About The Pull Request

As tited this PR adds a taur varient designed for slimes or organic blob-like entities.

## How This Contributes To The Skyrat Roleplay Experience

This variant fills a gap for those who want to have legless slime/blob characters but find Tentacle/Naga too large or not in line with their ideas.

Allows a more subtle amorphous/blob like appearance, see below:

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  While designed primarily for slimes the sprite sheet has been left full opaque as slime morphing applies its own.

image

image

It just fits within normal skirt dimensions, meaning no clipping issues or vanishing pixels. Pencil skirts however are incompatible but using this taur, its unlikely to be an issue..

image

image

Modsuits are handled automatically. Ran into issues with slime morphed taur parts but seems unrelated to this PR.

image

</details>

## Changelog

:cl:
add: Adds new Taur variant: "Goop"
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
Perhaps a smoother variant?

**Comment by Syrox25** [comment]
Outline or detailing?

**Comment by Nerev4r** [comment]
> Outline or detailing?

Oh, like, detailing; just smoother n without the lines down the middle. That'd slap, I think.

**Comment by Syrox25** [comment]
Alright. Didnt want it to look barren and undetailed so added that melting look, can tone it back.

I'll work on some edits and throw it up probably tomorrow.

**Comment by Nerev4r** [comment]
> Alright. Didnt want it to look barren and undetailed so added that melting look, can tone it back.
> 
> I'll work on some edits and throw it up probably tomorrow.

This one's totally fine for one purpose, it'd just be cool to have an alternate version. Either way, thank you for this! <3

**Comment by Blockzzy** [comment]
Perfect base for mushroom men! Great addition!

**Comment by Syrox25** [comment]
Went for a design that was more of a T shape and with the challenge of fitting it into a pencil skirt without clipping. Came out alright I think.
Close to human foot dimensions with the top raised up.

image

image

Temp name of slime for now but kinda reluctant to use it for either due to name overuse in the code (5460 results) Open for name ideas :>

(Oh.. Not added yet but the spritesheet is on standby)

**Comment by hugmeorelse** [comment]
goopy goober

**Review by Ebin-Halcyon — APPROVED** [review]

**Comment by Syrox25** [comment]
Gah, I never pushed the thin one, was gonna see if it was fine first.
No worries, ill open a new PR, thanks <3

**Pull request merged**
