### PR TITLE
[semi-modular] updated cloak sprites from Bee Station

### PR DESCRIPTION
**Pull request by werewolfboyfriend**
## About The Pull Request
Updates the head of staff cloaks to improved sprites yoinked from Bee Station and adds the two chaplain cloaks they've got, as well. Those are in the ChapDrobe as contraband.
I also deleted the duplicates of tg items from the neck dmis? Correct me if I'm wrong, but there doesn't seem to be a purpose to the duplicates and scarves and the like are fine without it.
Screenshot 2021-04-22 183204
Screenshot 2021-04-22 194853
credits:
https://github.com/BeeStation/BeeStation-Hornet/pull/3420
https://github.com/BeeStation/BeeStation-Hornet/pull/2964
https://github.com/BeeStation/BeeStation-Hornet/pull/2898
https://github.com/BeeStation/BeeStation-Hornet/pull/2769
https://github.com/BeeStation/BeeStation-Hornet/pull/2765
https://github.com/BeeStation/BeeStation-Hornet/pull/2470

## Why It's Good For The Game
The old ones are a little potato, honestly. They're only partially shaded and the shading is... weird. These ones are better designs and have shading that makes sense... and colors that make sense, in the CE's case.
cloaks are my fave aspect of head of staff customization

## Changelog
:cl:
add: Two chaplain cloaks.
imageadd: New sprites for head of staff cloaks.
/:cl:

### CODE REVIEW

**Comment by KathrinBailey** [comment]
Ngl, they cover the head way too much.

**Comment by werewolfboyfriend** [comment]
> Ngl, they cover the head way too much.

These have the exact same footprint as existing cloaks.

**Comment by KathrinBailey** [comment]
> > Ngl, they cover the head way too much.
> 
> These have the exact same footprint as existing cloaks.

that doesn't make it better, knock a few pixels off and it'll look way better.

**Comment by werewolfboyfriend** [comment]
> > > Ngl, they cover the head way too much.
> > 
> > 
> > These have the exact same footprint as existing cloaks.
> 
> that doesn't make it better, knock a few pixels off and it'll look way better.

looked terrible with anything cropped off, so I shifted the position down one instead:
Untitled
how's that? the chaplain ones had to stay the same, though, as they clip with the matching clothes otherwise

**Pull request merged**
