### PR TITLE
Fixes of a bunch of sprite issues with Synth lizards

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request
Tin. Annoying visual problems, fixed.

Current, see hand sticking out of glove and minor poking out of the chest region.
image

Fixed versions:
image

## How This Contributes To The Skyrat Roleplay Experience

Fixed sprites.

## Changelog

:cl:
imageadd: Synth lizards have had a few sprite issues addressed.
/:cl:

### CODE REVIEW

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
You're going to fail the Screenshots tests until you delete `code/module/unit_tests/screenshots/screenshots_humanoids__datum_species_robotic_synthliz.png` and then run unit-tests locally.

Furthermore, if you're up to the task, just try and fill in the `prepare_human_for_preview()` proc for synthlizards so they actually look like real synthlizards in the screenshot (and at the same time, in the prefs menu! Win-Win!)

If you need any help with that second part, you can take a look at [how I did it for Skrells.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14763).

**Comment by Ebin-Halcyon** [comment]
> You're going to fail the Screenshots tests until you delete `code/module/unit_tests/screenshots/screenshots_humanoids__datum_species_robotic_synthliz.png` and then run unit-tests locally.
> 
> Furthermore, if you're up to the task, just try and fill in the `prepare_human_for_preview()` proc for synthlizards so they actually look like real synthlizards in the screenshot (and at the same time, in the prefs menu! Win-Win!)
> 
> If you need any help with that second part, you can take a look at [how I did it for Skrells.](https://github.com/Skyrat-SS13/Skyrat-tg/pull/14763).

Gotchu

**Comment by Ebin-Halcyon** [comment]
woe.

**Comment by Ebin-Halcyon** [comment]
I'm going to fucking cry, oh my god. Nearly 3 weeks. I'll fix the screenshots tomorrow or something.

**Review by GoldenAlpharex — APPROVED** [review]
Sad that you didn't get to update the screenshot too much, oh well.

**Comment by Ebin-Halcyon** [comment]
> Sad that you didn't get to update the screenshot too much, oh well.

I am far too dumb in coding to do it, sadly.

**Pull request merged**
