### PR TITLE
Unique Operational Status Readout Module Death Sound

### PR DESCRIPTION
**Pull request by Stalkeros2**
## About The Pull Request
Replaces /tg/'s status readout death sound with a new unique one for the NRI roles and the assault ops that seem to also be using it.

## How This Contributes To The Skyrat Roleplay Experience
Honestly? It's cool; Really though, helps the crew with finding out whether an NRI cop/assault operative or a normal crewmember has died.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
Trust me; I -really- wouldn't wanna upload another super shitty video from this PC.
</details>

## Changelog

:cl: Stalkeros, Motho for the sound
sound: New unique sound for the operational status readout module.
/:cl:

### CODE REVIEW

**Comment by SpaceLoveSs13** [comment]
Don't you think the sound is bit too high pitched? it's very painful to the ear in my opinion.

**Comment by Stalkeros2** [comment]
In a way, that's the point - a pretty noticeable sound would attract more attention to someone dying.

**Comment by W4rd3nn** [comment]
The sound is a tri-tone. It's intentionally harsh and attention-grabbing. Pitching it down probably wont help much because the high part of the tri-tone is always gonna be ouchies. Its like the cyborg death sound. You won't hear it very often, but when you do hear it, you should pay attention.

See reference: https://www.youtube.com/watch?v=zwzHtuyTZ_c

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
I don't want to have to manually download the file to figure out what the sound is, can you please add it in the PR body? Thank you.

**Review by GoldenAlpharex — APPROVED** [review]
I have since been able to hear what it sounds like, and I'm fine with it.

**Pull request merged**
