### PR TITLE
NuInterlink, or as I like to call it, the Evac Shuttle now docks at the Interlink

### LINKED ISSUE #15907: Centcom Kitchen and Bar Buttons for Shutters are in the wrong locations.
## Testmerges:
[#15675: 'Reverts #11270 (Event Voter)' by Zonespace27 at commit f83ec84088](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15675)
[#15802: '[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs' by RimiNosha at commit 71d1ca4de8](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
[#15842: '[Tram] New tram, new consequences. Tram collisions actually hurt.' by lessthnthree at commit 555409a216](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15842)

## Reproduction:
Go to centcom and head for the kitchen shutters and press the button
Observe the bar shutters opening

Go to centcom and head for the bar shutters and press the button
Observe the kitchen shutters opening

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request
This PR overhauls the Interlink, as well as removing the evac shuttle from docking at CC. It now docks at the Interlink.
And yes, this is my last PR for awhile. I've been on hiatus since earlier in the day.

closes: #15907

Still a work in progress because I wanna do spiffing up (and I didn't delete the old Interlink yet, lol).
Also need to test with some of the wacky shuttles because shuttle docks are wacky as fuck (may request a TM since this isn't something I can just do rapid fire).

Small checklist of shit to do:

- [ ] Make new "CC" area defines 
- [x] Add four smaller dorm rooms
- [x] Decalening 

## How This Contributes To The Skyrat Roleplay Experience
Its been an idea from what I've been told, to have the evac shuttle dock at the Interlink. Now thats a reality.

The Interlink is split up into two portions, the Interlink North (where we latejoin spawn into), and the Interlink South (where the Evac shuttle docks).

### Interlink North:

<details>
<summary>Interlink "Arrivals!"</summary>
It never hurts to reuse old assets when they fit.

image

</details>

<details>
<summary> Longue areas!</summary>
Ignore the broken paintings. Who uses dirs for directions instead of subtypes :skull:

image

Little cafe!

image

Locker room!

image

Primary garden!

image

Aux garden with a cave (spooky!)

image

</details>

### Interlink South:

<details>
<summary> Administration?!</summary>

Customary check point.

image

Blueshield Office.

image

NT Consultant Office.

image

Executive meeting room!

image

</details>

<details>
<summary> Evac dock </summary>

Main area.

image

Medbay.

image

Library longue! Featuring an adult section.

image

Bar! (Bartenders can bartend here!)

image

Kitchen! (Chefs can cook here!)

image

Evac garden!

image

</details>

## Changelog

:cl: Jolly
add: The Interlink has been overhauled.
add: The Evac shuttle now docks at the Interlink at the conclusion of a round.
del: The Evac shuttle no longer docks at CC.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
We also have to check for the greentext objectives for leaving via the escape shuttle to take the Interlink's area into account, but potentially not the North portion.

**Comment by Jolly-66** [comment]
Should be in a "good" state. Just need to make the area define.

**Comment by Paxilmaniac** [comment]
What's the point of ever having mapdiff bot if we use mdb ignore on every pr that touches maps

**Comment by Paxilmaniac** [comment]
Otherwise, I feel there's some good here but you might get a pr to your branch from me since suggesting map changes here is uh, you know

**Comment by Jolly-66** [comment]
> What's the point of ever having mapdiff bot if we use mdb ignore on every pr that touches maps

Sometimes I don't feel like waking AA ire. I posted screenshots no less so shush.

**Comment by RimiNosha** [comment]
> > What's the point of ever having mapdiff bot if we use mdb ignore on every pr that touches maps
> 
> Sometimes I don't feel like waking AA ire. I posted screenshots no less so shush.

You put a bunch of loose snips with 0 context, this is next to useless for getting an idea of the new layout.

Also, they are out of date, and are missing important details like the departmental arrows.

<details><summary>Actual Image</summary></details>

**Comment by RimiNosha** [comment]
Onto my actual feedback, though. 

The dorms have those awful invincible wall sprites, which also makes them feel clinical. Maybe return the wooden walls the rooms had before?

Nice touch with the window going all the way through to the shuttle from the spawn point, though, that should *hopefully* reduce the chances of people being unable to find the new shuttle location on the new map!

**Review by Paxilmaniac — CHANGES_REQUESTED** [review]
This seems overall pretty good, but there are some issues with the shuttle dock itself. One, that whole area with the diamond pattern just feels... off, wrong even, you can't really make a pattern like that look good.

Second, do not have anything in front of where the shuttle lands.
image

This whole 'cave' section seems a bit unnecessary, and is just asking to get crushed by someone who bought one of the larger shuttles.

**Comment by GoldenAlpharex** [comment]
Looks like the decals are overlapping the wrong way around, I assume that was when some of said decals got changed around.
image

I'd assume this was an handicapped spot, but I think the decal for the handicapped spot is missing, in this case.
image

It appears to be missing a telecommunications relay, too. Either that, or I'm blind and couldn't find it, but it's not working.

For the dorms rooms, first of all, I think the walls should be made of the invincible wood again, instead of being the ugly invisible CentCom walls.

Then, here's a picture of how I'd change stuff:
image

Green in this case would be a table with two seats (facing one-another), so that people can still use the room for other purposes than just the bed. The rest is just moving stuff about.

**Review by Paxilmaniac — CHANGES_REQUESTED** [review]
Another two things, at round end it appeared to not have breathable air, I suspect either the grass or dirt types used 'outdoors' so check their roundstart atmos.

Second, 
image
This door has an indestructible wall under it.

**Comment by Jolly-66** [comment]
I'll come back when I get the time. I'll try to keep the feedback in mind when I get back (and more importantly, reopen the PR)

**Comment by Jolly-66** [comment]
I'm so fresh you can suck my nads.

**Comment by Paxilmaniac** [comment]
epic fight between github actions and jolly livestreamed on liveleak

**Comment by Jolly-66** [comment]
I am INCREDIBLY TIRED and FULL OF ANATOMY AND PHYSIOLOGY (and molecular biology but we don't talk about him)

**Review by Paxilmaniac — COMMENTED** [review]
Not fully set on how some of these areas are, why some of these areas are, so on. I want to ask you to look at the current automapper template for the CC dock to get a sense of how I'd do some of it, but I also don't think I should be holding everyone to my highest mapping standards because my standards are unreasonable.

**Review by Paxilmaniac — APPROVED** [review]
Surely this won't cause any problems

**Comment by Paxilmaniac** [comment]
cutely gives you merge conflicts

**Comment by Tastyfish** [comment]
`/atom/proc/onCentCom()` should be adjusted as it's currently hardwired to check if you're either on a transitting shuttle, or specifically a subtype of `/area/centcom` and I wouldn't want greentext to get busted from this.

Edit: Nevermind, I just noticed the interlink area *is* a subtype of /area/centcom so I think it would work. Might have problems with people using the interlink early to avoid the gameloop but that might be more of an administration problem.

**Comment by YakumoChen** [comment]
The exit lines don't match up with the current default shuttle

The addition of caves is kind of weird and doesn't make the most sense to me, but I guess it's harmless

The telecomms machine probably shouldn't be near/adjacent to any of the dorms, or else you're going to drive people crazy with the buzzing noise.

People in theory could cut through the fences without issue, and get to the exit dock from the arrivals area.

**Comment by SomeRandomOwl** [comment]
The fax machines on the interlink are unnamed, as well as the shutter button for the bar controls the wrong shutters, and the actual shutter button for the bar is [underneath one of the shutters on the bar](https://files.ratchtnet.com/i/3a1726)

**Comment by Tastyfish** [comment]
The fax machine should probably just be removed to not be confused with the upcoming ability to fax to CC (admins) via this PR https://github.com/tgstation/tgstation/pull/71129

**Review by Paxilmaniac — APPROVED** [review]
Should be good to go

**Review by GoldenAlpharex — APPROVED** [review]
Let's goooooooo

**Pull request merged**
