### PR TITLE
[SEMI-MODULAR] Gubman 3.1: A bureaucrat? With a hand cannon!?

### PR DESCRIPTION
**Pull request by Draganfrukts**
## About The Pull Request

The second iteration of Gubman 3 is upon us, Gubman 3.1. Balance, fixes, and kickass sprites.

## Why It's Good For The Game

Now, let me start off with the removal of the Head of Personnel's firearm from his locker.
This isn't a "what I think" scenario, multiple times HoPs have gotten themselves and others injured over negligency of the gun they have, which is chambered in 12mm for some reason. That goes without mentioning that it's rarely used as something defensive, but rather a powerful firearm that lets you get your way because "le big pistole :)" and a tool for getting those gucci valids.

The energy gun is a much more logical choice for someone who essentially amounts to a bureaucrat, you sit in an office nearly all day and in edge cases take over the captain while he's gone. You don't have to mess with round types, you can switch between disablers and lasers on the go, and there's rechargers everywhere. You need 5 or 6 disabler shots to knock someone down, and you need around 8 lethal shots to bring someone to critical if they have no armor - it's close to what it was before except this time it's not nearly as powerful of an offensive tool but rather something to save your ass.

--

The QM is getting his own Mosin Nagant variant. This sounds great to a lot of us! But, there's a major concern for people in Security and others. "Why's he getting a rifle?"
The Mosin is cargo's staple gun, it's been for a long time now. Despite everything, there's one issue everyone overlooks. It's slow firing, it gets dirty easily, jams, it can even explode. The QM's Mosin cannot be sawn off, which makes it !!!UNCONCEALABLE!!! (with the exception of a bag of holding), it inherits stats from the Central Command mosin with the exception that this one can actually catch dirt and jam just like a normal mosin, the only true advantage is that it has 3 extra bullets in its internal magazine, to a total of 8. It spawns loaded, but has no stripper clips so if you run out and have to reload you have to load bullets in manually.

Security should instruct the Quartermaster to keep their right to bear arms within their own department, as it's a self defense gun. That also means defending your cargo techs if they're being slaughtered in front of your very eyes. Unless it's a high alert, and stuff is going to shit fast, keep that gun sealed or within cargo!

## Media
imagen

## Changelog
:cl:
balance: HoP now starts with an energy gun instead of a 12mm pistol with spare ammo.
balance: QM has a custom Mosin Nagant in his locker. No fancy stripper clips, though. And it gets dirty.
imageadd: Resprited Mosin Nagant and Obrez
imageadd: Added "Archangel" Mosin, a plastic abomination from a conversion kit.
fix: Fixed toy C20r overlay, it now shows properly on top of the gun instead of being offset.
tweak: Tweaked the size of the combat shotgun to reflect its size.
tweak: Tweaked the riot shotgun sprite
tweak: Tweaked the C20r magazine sprite to reflect the object icon.
tweak: Tweaked the size of the M90gl to be closer to that of a carbine rather than a compressed pdw
/:cl:

## Credits!
CEV Eris - Initial mosin sprite that was like a crushed baby sks with a bayonet that I had to change

### CODE REVIEW

**Comment by Draganfrukts** [comment]
Added a job disclaimer when you spawn that basically tells you it's a self defense gun and sec can take it if you do stupid shit

**Review by Gandalf2k15 — APPROVED** [review]
ok

**Comment by Draganfrukts** [comment]
Good to go :)

**Review by Funce — APPROVED** [review]
Looks good to me!

**Review by Gandalf2k15 — APPROVED** [review]
Funce said yes too, fine by me.

**Pull request merged**
