### PR TITLE
Water No-Tram Station

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request

Tramstation is a popular map upstream. Many people like Tramstation here, but hate the tram. I agree, so I did my own spin on it. This is Tramstation, but it doesn't have the tram (AND UNDERWATER!!). It's also a top secret underwater facility. Water?
https://sb.atlantaned.space/info/mapularity

https://user-images.githubusercontent.com/77420409/145999786-ab45711d-08a6-4013-86b5-0f96d53d1ab8.mp4

https://user-images.githubusercontent.com/77420409/145999898-ff918633-1a1b-4370-8363-4bb75199d397.mp4

## How This Contributes To The Skyrat Roleplay Experience

More map variety. Could be fun! 

TODO: Show me how to make the interlink shuttle work. 

## Changelog

:cl:
add: Water No Tram Station is added.
config: Adds Water No Tram to Map Vote and Config.

/:cl:

### CODE REVIEW

**Comment by Elli-Skala** [comment]
Oh God. Oh fuck.

**Comment by ghost** [comment]
Amazing

Make sure it has some waterproofing changes done to it, i.e. drains in airlocks, maybe break up the underpass of where the tram was a bit so its not a big floodable hall, etc etc

**Comment by nevimer** [comment]
> 

Ah, forgot those exist! Will add!

**Comment by Arctaisia** [comment]
Mfers stole the tram, can't have shit in Nanotrasen space...

Though this is nice! Would love to see it!

**Comment by Gandalf2k15** [comment]
You can't just leave the tram line like that. Turn it intona hallway

**Comment by Tastyfish** [comment]
> You can't just leave the tram line like that. Turn it intona hallway

Either that or give everyone skateboards on spawn. (sorta /s)

**Comment by Tastyfish** [comment]
Oh yeah also, since this is the exact sort of thing that usually murders the server, does flooding the entire main hallway noticeably cause lag (time dilation) and if so by how much? Since it's so huge, just the main hall is probably a reasonably benchmark.

**Comment by YakumoChen** [comment]
Removing the tram just makes it a map with an oversized, ugly hallway with terrible transit times between departments....

**Comment by SpaceVampire** [comment]
I'm down to try out some underwater stuff, but you really should just leave the tram around.
At the very least do something else fun with the space. The tram is cool tho.

**Comment by thestubborn** [comment]
many people like getting their balls stomped on

tram bad

**Comment by Gandalf2k15** [comment]
We don't even have a slot for another map, and this one will quickly fall out of sync and no one will maintain it much like NSS journey

**Comment by Gandalf2k15** [comment]
We don't have the capabilities to support another map.

**Pull request closed without merging**
