### PR TITLE
Removes armadyne oldarms as a company you can buy weapons from

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
If for some reason you can't tell from the title, it removes armadyne oldarms, that's it.

## How This Contributes To The Skyrat Roleplay Experience
My brother in christ the year is 2562 there ain't NO goddamn way we're gonna be seeing like, nazi and soviet guns from world war two on sale en masse.

## Changelog

:cl:
del: The armadyne oldarms division, facing impending shutdown from the parent company, has ceased selling firearms to stations
/:cl:

### CODE REVIEW

**Review by Zonespace27 — APPROVED** [review]
Adding oldarms in the first place was a mistake on my part

**Review by tf-4 — APPROVED** [review]

**Comment by Zonespace27** [comment]
DNM while i finish something related

**Comment by PCPort** [comment]
WAHOO

**Comment by PCPort** [comment]
https://youtu.be/ca7PkiauzbI?t=8

**Pull request merged**
