### PR TITLE
Fixes CI again

### PR DESCRIPTION
**Pull request by Zonespace27**
## About The Pull Request

Woo varedits are great I love them

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
alright who ran updatepaths and didn’t read ci failing afterward

**Comment by Zonespace27** [comment]
waiting on word from AA wrt MDB

**Comment by Zonespace27** [comment]
Nevermind, I can't merge anything so yolo

**Review by GoldenAlpharex — APPROVED** [review]
:)

**Comment by Cyprex** [comment]
Originally broken by https://github.com/Skyrat-SS13/Skyrat-tg/pull/19122

**Pull request merged**
