### PR TITLE
[Modular] #2770 but Modularised

### PR DESCRIPTION
**Pull request by BrotherHangyul**
## About The Pull Request

Copy of #2770 but it's also been modularised.

## Why It's Good For The Game

"Let's be honest here. /TG/'s done nothing but nerf security. First it was buckshot and slugs, now it's our printed guns. These budget weapons should help tip the odds a little, and also means security has to interact with cargo more, which is an upside for the maintainers."

Changelog
🆑
add: Surplus armoury crate.
/🆑

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
This still isn't modular, you'll need to add in modular comments to the bits of code you've added, and check the linters for errors.

**Comment by BrotherHangyul** [comment]
> This still isn't modular, you'll need to add in modular comments to the bits of code you've added, and check the linters for errors.

pain.

**Comment by BrotherHangyul** [comment]
Okay, modular comments added and checks passed.

**Comment by YakumoChen** [comment]
> > murderboning spiders
murderboning traitors with desword
murderboning lings
murderboning space dragons
murderboning spiders but ling flavoured

What does this have to do with adding mosins as opposed to them using lasers?

**Comment by BrotherHangyul** [comment]
> > > murderboning spiders
> > > murderboning traitors with desword
> > > murderboning lings
> > > murderboning space dragons
> > > murderboning spiders but ling flavoured
> 
> What does this have to do with adding mosins as opposed to them using lasers?

Lasers are either completely ineffective against or not as good as against these threats (especially DE-sword traitors, they're growing in size)

**Comment by YakumoChen** [comment]
That's kind of the point.

Lings are more vulnerable to burns however so that's not true.

**Comment by BrotherHangyul** [comment]
> That's kind of the point.
> 
> Lings are more vulnerable to burns however so that's not true.

Chitnous armour.

If there's absolutely 0 counter to an antagonist, it's unbalanced. This PR balances it out a little.

also I know that you're a vocal anti-ballistic person, please don't comment further unless it's actually to contribute.

**Comment by MLGTASTICa** [comment]
Sec has plenty of guns in the armoury , 4 of them can bypass shields and theres  countless other ways to do it already , very unnecesarry.

**Comment by BrotherHangyul** [comment]
> Sec has plenty of guns in the armoury , 4 of them can bypass shields and theres countless other ways to do it already , very unnecesarry.

Name the four guns then.

**Comment by MLGTASTICa** [comment]
> > Sec has plenty of guns in the armoury , 4 of them can bypass shields and theres countless other ways to do it already , very unnecesarry.
> 
> Name the four guns then.

ion , temp , the 2 shotguns , dragnet.

**Comment by BrotherHangyul** [comment]
> > > Sec has plenty of guns in the armoury , 4 of them can bypass shields and theres countless other ways to do it already , very unnecesarry.
> > 
> > 
> > Name the four guns then.
> 
> ion , temp , the 2 shotguns , dragnet.

Ion doesn't effect the de-sword last time I checked

Temp gun is a valid strategy yeah but it's woefully underused

Shotguns don't spawn on icebox now and also no lethal rounds makes it very hard to take them down

Dragnet slows down but it won't do the stamdamage for you, you can use it as a follow-up to stunbaton but the DE-sword has a 75% block chance

Temp-gun is the only solid cure

**Comment by YakumoChen** [comment]
It's almost like a weapon that has requires an investment of half* of your TC should be suitably powerful and difficult to fully overcome and not just spending a few cargo credits on a mosin.


*16 would be almost a full TC budget on non-Skyrat servers

**Comment by YakumoChen** [comment]
`armor = list(MELEE = 40, BULLET = 40, LASER = 40, ENERGY = 50, BOMB = 10, BIO = 4, RAD = 0, FIRE = 90, ACID = 90)`

``linked_alert.icon_state = "fleshmend"
owner.adjustBruteLoss(-10, FALSE)
owner.adjustFireLoss(-5, FALSE)
owner.adjustOxyLoss(-10)``

Chitinous armor has no special defense against lasers. Fleshmend heals brute damage twice as fast and it can't heal while on fire, so no, lasers are the optimal weapon of choice against changelings.

**Comment by YakumoChen** [comment]
Spiders die to temperature guns and pretty much anything actually. If you aren't using temperature guns against spiders though, you're doing it incorrectly.

The only antagonist that _needs_ 'countered' here is the space dragon, which is a singular, lone antagonist that is vulnerable to getting ganged up on by the entire crew regardless, much the same a Blob would be.

**Comment by BrotherHangyul** [comment]
> It's almost like a weapon that has requires an investment of half* of your TC should be suitably powerful and difficult to fully overcome and not just spending a few cargo credits on a mosin.
> 
> *16 would be almost a full TC budget on non-Skyrat servers

Yeah well this is skyrat. Different servers need different amounts of balancing; you can pair the De-sword with implants due to 30 TC, making you even harder to kill. This isn't a hard-hard counter, this is just a counter.

Also it's literally just a new gun crate, why are you complaining? We can order WT-550's.

Also also from a lore perspective (see pr #2809 ) this fits in, as NT is now using budget weapons. Nagants are the definition of budget.

**Comment by YakumoChen** [comment]
Traitors have more TC to create a more interesting story, not to aid balancing around antag items getting needless nerfs. That doesn't stop the fact that it's still a 16 TC item with the main advertised benefit being "it counters most of the shit security is likely to throw at you at range". I can't say I agree with security's current changes either and would probably push for a reduced cost for the dsword or just removing it due to it lacking relevancy in that sort of balance state.

The WT is kind of a shitty weapon overall (almost intentionally) and adding more shitty ballistics isn't solving any issues, especially stupidly cheap ones only there to counter the guy who bought the reflecting sword.

**Comment by YakumoChen** [comment]
On top of that the crate is sort of completely nonsensical in general. There's _already_ a mosin crate in the cargo packs list and it costs literally half as much and comes with 2 anyway. This crate also isn't even contraband, which it should be considering how non-standard these guns are (and because the russian crate IS contraband)

All these debates and this whole PR falls apart when you realize that this isn't actually adding anything, doesn't it?

**Comment by BrotherHangyul** [comment]
Incorrect, due to coding, the "mosin crate" has a chance of having no mosin in the first place, and the chance of a second is low. Most of the time it's literally just clothes, ammo and no gun. This is a guaranteed 3 mosin-nagants.

Woodstock double-barrel shotguns can be purchased by the armoury, I see no reason a bolt-action doesn't fit in.

Value of 15 isn't stupidly cheap.

I'm going to ask you to no longer post in this PR's discussing section since you clearly haven't bothered to even play security nor look at the code behind both this crate and the normal "mosin crate", which isn't even a god-damn guncrate.

Traitors should not be untouchable. This fixes that. Stop being so anti-ballistic, stop wanting to nerf security into the ground for no reason and stop trying to make antagonists stronger than they are.

**Comment by YakumoChen** [comment]
You know I'm an HoS main and have been playing since 2014, right?

Traitors aren't untouchable. They should be difficult to fight 1 on 1 like every other antagonist in the game. Security is a team role and are supposed to coordinate to take down dangerous antags. If a desword guy is killing everyone because officers run at him one at a time, that's intended balance.

Secondly, the current revamp security is a severe nerf to the entire department, so I don't know why you're complaining to me.

The 1 in 10 chance for the russian crate I didn't know (I play security, not cargo) but that doesn't change the fact you can still get mosins from those crates anyway.

**Comment by BrotherHangyul** [comment]
> You know I'm an HoS main and have been playing since 2014, right?
> 
> Traitors aren't untouchable. They should be difficult to fight 1 on 1 like every other antagonist in the game. Security is a team role and are supposed to coordinate to take down dangerous antags. If a desword guy is killing everyone because officers run at him one at a time, that's intended balance.
> 
> Secondly, the current revamp security is a severe nerf to the entire department, so I don't know why you're complaining to me.

Revamp is a revamp, not a nerf. Some things were changed.

I've seen groups of officers attempt to take on DE-sword users with a solid plan, they were all killed despite this. I was there, in-game, assisting the antagonist since we were both traitors. They shredded through security officers with zero trouble and killed nearly everybody in the department with little problem. 

That's unbalanced. An item should not be able to take on an entire department and win.

**Comment by YakumoChen** [comment]
Then remove the item, don't add shitty guns to cargo in a misguided attempt to 'balance' security.

**Comment by BrotherHangyul** [comment]
> Then remove the item, don't add shitty guns to cargo in a misguided attempt to 'balance' security.

When you code it.

**Comment by YakumoChen** [comment]
I think it's perfectly balanced and this is a dumb PR, but we'll see if it's closed or not. Maintainer has already said this is a dumb PR.

**Comment by BrotherHangyul** [comment]
> I think it's perfectly balanced and this is a dumb PR, but we'll see if it's closed or not. Maintainer has already said this is a dumb PR.

For the last time.

A weapon that can kill the entire security department is *not* balanced.

**Comment by YakumoChen** [comment]
We should remove the revolver too while we're at it. And the regular esword. And the ebow. Hell, let's just remove the arms off every traitor before they get the chance to kill someone, much less all of security if they're robust enough.

**Comment by BrotherHangyul** [comment]
> We should remove the revolver too while we're at it. And the regular esword. And the ebow. Hell, let's just remove the arms off every traitor before they get the chance to kill someone, much less all of security if they're robust enough.

When you code it.

**Comment by YakumoChen** [comment]
When you code it, since it seems to be an issue only you seem to care about.

**Comment by BrotherHangyul** [comment]
> When you code it, since it seems to be an issue only you seem to care about.

When you code it.

**Comment by Zenitheevee** [comment]
look, I'm gon' be quite honest here chief.

I dont think sec needs a gun that can 2 shot knock down a person, Atleast not in its current state.

**Comment by AlinaStarkova** [comment]
i would just like to mention, tg hasnt nerfed security beyond removal of shotguns (since they want to keep ballistics as syndicate and lasers for NT). the other "nerf" your referring to, the removal of your printed guns is NOT from tg, your mixing things up, those guns came from oldbase, aka citidel downstream. tg never ever had those guns before, you lost them on the rebase, tg didnt remove them from you

as someone who codes and maps upstream and actively plays skyrat as well, it would be nice to not have upstream blamed for every little thing :(

**Comment by BrotherHangyul** [comment]
> i would just like to mention, tg hasnt nerfed security beyond removal of shotguns (since they want to keep ballistics as syndicate and lasers for NT). the other "nerf" your referring to, the removal of your printed guns is NOT from tg, your mixing things up, those guns came from oldbase, aka citidel downstream. tg never ever had those guns before, you lost them on the rebase, tg didnt remove them from you
> 
> as someone who codes and maps upstream and actively plays skyrat as well, it would be nice to not have upstream blamed for every little thing :(

My apologies.

**Comment by Gandalf2k15** [comment]
With the security rework this won't be needed.

**Comment by BrotherHangyul** [comment]
> With the security rework this won't be needed.

but muh mosins...

**Comment by Gandalf2k15** [comment]
Yeah we're moving away from people spamming guns and shit, we want to control how many sec gets. I don't think we need mosins when you've got modern guns.

**Pull request closed without merging**
