### PR TITLE
[MODULAR] Require a little more effort to lie about yourself

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

Title. Girth -> 5, Length -> 6. A bit higher than the real life values, which makes sense to me given how I'm betting natural selection would work on a place as horny as the station.

## How This Contributes To The Skyrat Roleplay Experience

10 inch default is just TOO MUCH. Plain and simple.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

</details>

## Changelog

:cl:
spellcheck: Nanotrasen replaced the faulty measuring devices for certain bodyparts. Sorry to all the crew who thought they were actually 10 inches
/:cl:

### CODE REVIEW

**Comment by nikothedude** [comment]
no fucking clue of what changelog tags to use

**Comment by nikothedude** [comment]
balance???? maybe??? erp balance????

**Comment by lessthnthree** [comment]
Maybe someone typo'd default dick size. :ev_smug: 

Or "modified default value to lie about your dick size"

Something something gonna have to inspect the proof of testing. I actually have a lot of good changelog suggestions, I just don't know if you want your name attached to them.

**Review by lessthnthree — APPROVED** [review]

**Comment by Stalkeros2** [comment]
penis update

**Comment by nikothedude** [comment]
penis update

**Comment by YakumoChen** [comment]
Maybe the pr should have a more github friendly title?

**Pull request merged**
