### PR TITLE
[MIRROR] Foodening [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/77887
--------------------
Reopen of #76205

## Changelog

:cl:
add: Mood buff power and duration depends on the ingredient quality and recipe complexity of the food.
add: Hand-crafted food also gives a non-mood buff. The buff type depends on recipe complexity and duration - on ingredient quality.
code: Added infrastructure to assign custom buff to certain dishes for unique effects
add: Consumable reagents now care about purity, being more nutritious with higher purity. Dispensers give synthetic food, natural sources are organic and better and give longer buffs.
add: Grown food reagent purity now depends on lifespan, endurance and instability stats of the seed. 
add: Natural booze now uses the same purity formula and 100% purity can increase booze power by up to 200%.
add: Added Fat reagent that is now a base type for lard, vegetable oil, olive oil. Corn oil and cooking oil merged into vegetable oil.
balance: Reagents and their purities are preserved during food chemical reactions, processing, cooking and crafting.
balance: Sugar nutrition rebalanced due to it being 100% pure in chem dispenser, overdose happens at 100u now.
fix: `grind_results` of grown food give full amount equal to all removed nutrients instead of just `/datum/reagent/consumable/nutriment`
qol: Seed Extractor now shows additional seed data: possible mutations, juicing result, grinding result, fermentation result
fix: Reverts the unintended change of monkey cube biomass cost back to 50
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
This will require tweaks to our modular biogenerator products (like the weird synthmeat) and also our modular alcohol distilling options; probably.

**Comment by vinylspiders** [comment]
> This will require tweaks to our modular biogenerator products (like the weird synthmeat) and also our modular alcohol distilling options; probably.

Alcohol should be fine I think? As for the biogenerator produced meat product I just made a PR for that upstream. That item should have the synthetic purity to begin with.

**Review by vinylspiders — APPROVED** [review]

**Review by lessthnthree — APPROVED** [review]

**Comment by OrionTheFox** [comment]
### __**This PR is currently breaking all (tested) food made in the crafting menu. Players cannot examine, pick up, or eat anything made through it.**__

**Comment by GoldenAlpharex** [comment]
Seems to have been fine so far. Let's roll with it.

**Pull request merged**
