### PR TITLE
[Nonmodular][Smoothbrain] /tg/ never made syndicate masks fireproof

### PR DESCRIPTION
**Pull request by Vizoplez**
## About The Pull Request
wow

## Why It's Good For The Game
please find and send a youtube link of moistcritikal clapping the shit out of /tg/code

for real, this is a bug and unintended behaviour

## Changelog
:cl:
fix: Syndicate man no longer has his mask melt off beneath his hardsuit.
/:cl:

### CODE REVIEW

**Comment by Vizoplez** [comment]
For why this is relevant
-be interdyne
-fight drake


-fight drake
image

-die because your gas mask melted off

**Comment by Gandalf2k15** [comment]
Go upstream with this 4eeee

**Comment by capsaicinz** [comment]
upscree

**Comment by SpaceVampire** [comment]
Yeah wait.
If this is an bug and unintended behaviour.
Shouldn't it just be done upstream instead?

**Comment by Gandalf2k15** [comment]
upsrream this fix pls

**Pull request closed without merging**
