### PR TITLE
[MODULAR] Forge Weapon Resprite : ROCK AND STONE(tm)

### PR DESCRIPTION
**Pull request by dawsonkeyes**
## About The Pull Request

This PR resprites forge melee weaponry (and the hammer tool) to be more up-to-date in regards to modern skyrat sprites.
It does **not** change sprites for ranged weaponry and armor, or the structures themselves (like the anvil). Just the weapons and tools, and their respective inhands.

image

Also includes miscellaneous description changes to better define the function of the weapons!

## How This Contributes To The Skyrat Roleplay Experience

Roleplay experience? Doesn't do jack squat. But maaan do they look cool!

## Changelog

:cl:
add: Added newer sprites for forge weaponry and their constituent parts.
/:cl:

### CODE REVIEW

**Comment by dawsonkeyes** [comment]
also do note that the weapons themselves are greyscaled on the metal-y bits!!!! all is well with materials B))

**Comment by dawsonkeyes** [comment]
this is *also* still a wip so we draftin

**Comment by ghost** [comment]
Sprite review will be done on discord bc github and images is a bad combo

**Comment by Paxilmaniac** [comment]
cutely gives you merge conflicts

**Pull request closed without merging**
