### PR TITLE
[Meow!] K4TBorgs, by Zydras!

### PR DESCRIPTION
**Pull request by Nerev4r**
## About The Pull Request
Adds cat-themed anthropomorphic borgs to the game, sprites by @zydras! More commentary will probably come in a director's comment later, but without further adieu, let's get right into the funny internet cats. WOO!

p.s. Those aren't paws, actually. Those are wheels. These mfs SKATE.

## How This Contributes To The Skyrat Roleplay Experience
New customization is always great for silicon players. [1]

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
  
image
image
image
image

  
</details>

## Changelog
:cl: Zydras
image: Kugelblitz 4utomation Technologies has unveiled its competing lineup of cyborg chassis, the K4Ts.
/:cl:

## Works Cited
[1] Motho. “[MODULAR] NiKA and NiKO Borg Models.” GitHub, 5 July 2023, github.com/Skyrat-SS13/Skyrat-tg/pull/22269.

### CODE REVIEW

**Comment by W4rd3nn** [comment]
no maid borg panties.
0/10

**Comment by CliffracerX** [comment]
The designs on these are wildly charming and different, and *any* new content for borg mains is great.

**Comment by hugmeorelse** [comment]
I approve. More two-legged borgs are great.

**Comment by coffeecoffeecoffee** [comment]
they make me viscerally, deeply uncomfortable but the spritework is undeniably good. one concern i think is worth mentioning is that the visual clarity of many of the alt poses - tipped, wrecked, etc. - is less than great, i'm really really squinting and leaning in to tell what's going on with their body and limbs when they're not standing, myself

**Comment by Draganfrukts** [comment]
Let me tell you something–
### I'm from Buenos Aires, and I say merge them all!

**Comment by Stalkeros2** [comment]
no maid borg panties.
0/10

**Comment by Draggeru** [comment]
Edit: Wrong thing lmao

**Comment by TYWOHKA** [comment]
?
image

**Review by Ebin-Halcyon — APPROVED** [review]
I still personally don't like the design but i'm tired, and atleast it isn't a dogborg.

**Review by GoldenAlpharex — APPROVED** [review]
Looking good! Maybe a bit bulky for my taste, but not inherently bad, and it's just up to my personal taste, the sprites look great!

**Review by GoldenAlpharex — APPROVED** [review]
Nice, let's go!

**Pull request merged**
