### PR TITLE
[WIP] [non-modular] Showers dont run out of water

### LINKED ISSUE #1389: Showers have finite water aAAAAAAAaaaaAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
AAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaaaaAAAAAaAAaaaAAaaaAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaaaa this ruins the shower rp, give us unlimited water back.

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/1389

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by Owai-Seek** [comment]
The hero we need. As a sidenote, it's the same for sinks, but I (guess) that's not as big an issue. Seems silly TG would do it at all.

**Comment by Azarak** [comment]
> 
> 
> The hero we need. As a sidenote, it's the same for sinks, but I (guess) that's not as big an issue. Seems silly TG would do it at all.

realism, you wouldnt want someone to turn on all the showers and just leave them be with no care for water, now they'd run out and you'd have someone to blame, IC conflict. The more real a game feels the better the roleplaying experience is

**Comment by Gandalf2k15** [comment]
Eh I don't agree with this one. It takes us away from roleplay.

**Comment by Azarak** [comment]
> 
> 
> Eh I don't agree with this one. It takes us away from roleplay.

not worth it to go with realism on here, people like shower scenes, let them enjoy them

**Comment by Gandalf2k15** [comment]
This was a TG change, they weren't much about realism and these showers last long enough for a scene. Fuck me we don't need to be bending over backwards to cater towards ERP.

**Comment by Azarak** [comment]
> 
> 
> This was a TG change, they weren't much about realism and these showers last long enough for a scene. Fuck me we don't need to be bending over backwards to cater towards ERP.

How is this bending backwards for ERP? It's a very small change, really only noticable for those who do want to enjoy it

**Comment by Gandalf2k15** [comment]
Please also remember this will cause showers to produce infinite chemicals, the reason for tg doing this was to prevent abuse as you can change the contents.

**Comment by Hemlock32** [comment]
Don't showers use plumbing with the new system? Doesn't that mean you could fuck with the plumbing and make infinite chemical showers?

**Comment by Owai-Seek** [comment]
Are showers pre-piped to get more water? How long does 200 units last?

Worst case scenario, we could make a subclass of shower specifically for the shower rooms/dorms that -only- produce water.

**Comment by Azarak** [comment]
Oh it does use plumbing?

**Comment by Azarak** [comment]
Okay this changes the things

**Comment by MLGTASTICa** [comment]
Maybe do a creative fix and add a reagent synthethizer + chemister tank hooked up to showers ? instead of just deleting another way of creating RP by shower saboutage?

**Comment by Azarak** [comment]
> 
> 
> Maybe do a creative fix and add a reagent synthethizer + chemister tank hooked up to showers ? instead of just deleting another way of creating RP by shower saboutage?

Good idea, but requires map maintenance which we currently dont do.
Inb4 sometime in the future we'll have disposal pipes, atmos pipes and hydraulic pipes all over the map

**Comment by YakumoChen** [comment]
Surely there's a subtype of shower that has the old functionality? 
If not then just do a partial revert of the code.

**Comment by Azarak** [comment]
i'll mess with this later

**Pull request closed without merging**
