### PR TITLE
[MODULAR] Sneks don't make footsteps

### PR DESCRIPTION
**Pull request by JGlitch**
## About The Pull Request

having a snake taur body makes you not make footsteps

## Why is this good for the game

Snake tail dont have steppies!

## Changelog

:cl:
refactor: snake characters don't make footsteps
/:cl:

NullFag helped me out on this one uwu

### CODE REVIEW

**Comment by SpaceVampire** [comment]
I really don't like the idea of linking a mechanical advantage to a certain cosmetic body part.

EDIT: It isn't like having wings lets you fly around in zero gravity.

**Comment by YakumoChen** [comment]
You should make a new race if you want bodypart templates to have effects.

Snakes should make the dragging sound instead of steps anyway, instead of straight buffing them

**Comment by Gandalf2k15** [comment]
> I really don't like the idea of linking a mechanical advantage to a certain cosmetic body part.
> 
> EDIT: It isn't like having wings lets you fly around in zero gravity.

actually wings allow you to fly in zero g

**Comment by SpaceVampire** [comment]
> actually wings allow you to fly in zero g

I could have sworn that only worked if you were actually a moth.
Not if you just added wings to some random race.

**Comment by JGlitch** [comment]
> You should make a new race if you want bodypart templates to have effects.
> 
> Snakes should make the dragging sound instead of steps anyway, instead of straight buffing them



> I really don't like the idea of linking a mechanical advantage to a certain cosmetic body part.
> 
> EDIT: It isn't like having wings lets you fly around in zero gravity.

Closing PR and adding that change.

**Pull request closed without merging**
