### PR TITLE
Void Raptor - Medbay additions, QoL tweaks

### LINKED ISSUE #19250: Void Raptor lacks free plating tiles in maintenance, causing roundstart mice to spawn in the emitter room
I feel like this is already summed up in the title.

image

(There were 8 mice in this room, mind you)

Void Raptor needs more "free" plating tiles around in maintenance so mice.. stop doing this.

### LINKED ISSUE #22557: Void Raptor has no doctor-accessible medical records console
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Bizarrely, there are no medical record consoles available to doctors in the Void Raptor medbay (however, the orderly office has one, as well as the morgue office.)

### PR DESCRIPTION
**Pull request by LovliestPlant**
## About The Pull Request
This PR adds two small rooms to Void Raptor's medbay, additionally a number of QoL adjustments have been made in other areas.

Medbay
- Adds an Exam Room and Charting Office to the skybridge opposite of the escape pod.
- Removes the potted plants from mebday storage, and the exta anesthetic closets from the treatment center.
- Adds a light to the hall outside of the CMO's office, on the wall opposite of the row of chairs.
- Fixes an access oversight on the treatment center back (hangar) entrance.
- Overhauls the cold storage room. Adds a coldroom freezer system; adds a handful of emergency oxygen tanks, emergency nitrogen tanks, and masks to the internals crate; replaces the empty medical crate with a spare robotics limbs crate; and replaces the Oxygen canisters with anesthetic mix canisters.
- Adds blankets to roundstart beds in the treatment center.

Security
- Changes the access requirement to the southern set of doors in the brig office from "general" to "entrance". Bringing them in parity with the Northern entrance to the space.
- In the CO's office, fixes a clipping issue with the security records laptop by replacing it with a normal console. (Donut box moved out into the hallway)
- In the CO's office, fixes CO's not being able to open the "Brig Officer's Locker" in that room.
- Adds a towel bin near the showers in perma.

Public Pool
- Replaces the linen bin with a towel bin.

Maints
- Replaces patches of flooring with bare plating throughout maintenance.
- Removes a handful of lights from maintenance to ease midround spawning

fix: #22557
fix: #19250
Partially addresses  #20835

## How This Contributes To The Skyrat Roleplay Experience

The lack of accessible records consoles and private spaces in Void Raptor's medbay makes medical RP tough to have. As it stands, the best doctors can really manage is sitting their patient in the row of chairs in front of the CMO's office. This PR adds two small spaces to support medical RP, and give doctors some roundstart records access.

Additionally, Void Raptor's brig has long been a pain to navigate for detectives and lawyers. This aims to reduce those headaches by allowing them through the security office's Southern entrance, which would save those roles a tiresome detour around to the North entrance.

The tweaks to maints are arguably more of a bugfix. Replacing grate floors with bare plating will allow mice to spawn in places other than the SM's emitter room. Additionally there have previously been instances of midrounds (nightmare specifically iirc) being unable to spawn due to the number of lights in maintenance areas. This PR removes lights from several tunnels and smaller rooms in maints, which should give them an easier time spawning.

The lack of towels was brought up back in april. Adding a bin to perma's showers and retrofitting the old linen bin in the public pool will go some small way to alleviating that.

The CO's office is now a bit more functional for players that use it.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

exam room, charting office, and cold storage
VR_med_coldCans

Medbay storage and treatment center
VR_med_treatment

Changes to maintenance are distributed, but do seem to have solved engineering's mouse problem
VR_med_sm

CO's office (before)
VR_Perma_Before

CO's office (after)
VR_Perma_Afer

Perma towels
VR_Perma_Towel

Pool towels (pulled one out as an example)
VR_Pool_Towel

</details>

## Changelog

:cl:
add: [Void Raptor] Adds an exam room and charting office to medbay, just opposite of the escape pod.
add: [Void Raptor] Adds a refrigeration system to medbay's cold storage room.
qol: [Void Raptor] Removes some clutter from medbay (storage plants, extra anesthetic closets), adds blankets to TC beds.
qol: [Void Raptor] Access to the Southern entrance to the Security office now matches that of the North entrance.
qol: [Void Raptor] Overhauls medbay's cold storage room. Adds a coldroom freezer system; adds a handful of emergency oxygen tanks, emergency nitrogen tanks, and masks to the internals crate; replaces the empty medical crate with a spare robotics limbs crate; and replaces the Oxygen canisters with anesthetic mix canisters.
qol: [Void Raptor] Adds towel bin to perma, replaces the linen bin in the public pool with a towel bin.
fix: [Void Raptor] Replaces flooring with bare plating in sections of maints, should fix mouse spawning.
fix: [Void Raptor] Fixes the back entrance to the medbay's treatment center requiring morgue access.
fix: [Void Raptor] CO's can now open the brig officer locker in their office.
fix: [Void Raptor] Fixes a minor clipping issue with the records console in the CO office.
/:cl:

### CODE REVIEW

**Comment by W4rd3nn** [comment]
this is pog. we need more stuff conducive 2 rp

**Comment by sqnztb** [comment]
Since you're doing this, can you also fix an access helper that I've been meaning to do for a while? The back door in the TC at 101,122 has the morgue access helper for some unholy reason, so chemists on minimal access can't get in (though we can go right through the maints entrance at 107,122 and 106,121 because reasons). Can you swap that to just the general medical one?

edit: 👏

**Comment by LovliestPlant** [comment]
Literally never noticed that, lmao. Fix is in!

**Comment by SpaceVampire** [comment]
I already attempted to fix the issue with detectives having messed up access on this map compared to all of the other stations. Thought that I went ahead and got it working correctly, but it is possible that I missed something. I had also planned to update the engi to make it so that people who could access the lobby could access the lathe as that is the way it is handled on ever other map, but I got busy and never ended up getting around to it. The room just really needs to be connected to the lobby directly, instead of linked to the engine room.

**Comment by LovliestPlant** [comment]
okay that's the last change I swear

**Comment by LovliestPlant** [comment]
okay, NOW we're done.

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
While we're here, change these to be anesthetic canisters. O2 canisters are no longer used for cryo.

image

**Comment by LovliestPlant** [comment]
> While we're here, change these to be anesthetic canisters. O2 canisters are no longer used for cryo.
> 
> image

Swapped!
VR_med_coldCans

**Review by Jolly-66 — APPROVED** [review]
I don't like the freezer for the cold room being in maint, but if it creates issues for admins I'll fix it later.

**Pull request merged**
