### PR TITLE
Updates modular cargo sprites to fit the upstream resprite, adds digi support for new upstream sprites

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

**Removes the Gorka Jacket:** Only the modular Cargo one was used and now TG has a Cargo Gorka Jacket

**Updates all our modular ones to fit the new palette:**
image

**Wow! TG's now have proper Digi support!**
image

**Onmobs of our new ones (All digi, I'm not respawning that many time as human to get a full roster for a FOURTH screenshot)**
image

## How This Contributes To The Skyrat Roleplay Experience
Sprite maintinence ☠️ 

## Proof of Testing
It's all in the About section.

## Changelog

:cl:
del: Removed the now-obsolete Skyrat Cargo Gorka-Jacket; TG now has one!
image: updated all of the cargo sprites to match TG's, including digitigrade sprites!
fix: the QM's Formal Skirt now actually uses the Skirt icon rather than the Suit
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
looks good 👍

**Comment by HoodMilk** [comment]
I liked the old palate, oh well.

**Review by lessthnthree — APPROVED** [review]

**Comment by vinylspiders** [comment]
Is this still a work in progress?

**Comment by ghost** [comment]
> Is this still a work in progress?

Was on vacation :skull:

**Comment by ghost** [comment]
damn you screenshotdiffs

**Comment by ghost** [comment]
Well, no matter what I do, screenshots won't update on my side
So have fun maintainers cuz I can't fix this

**Comment by vinylspiders** [comment]
> Well, no matter what I do, screenshots won't update on my side So have fun maintainers cuz I can't fix this

no worries

**Pull request merged**
