### PR TITLE
[PR to overmaps-and-traders branch] Redesigns most of the buyable shuttles so that they aren't vastly different in quality to the ones I've made

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
@Gandalf2k15 You'll want to have a look at this
These are all changes for OVERMAP, and will not effect master until overmap is merged.

Redesigns ALL of the non-platform shuttles that can be purchased.

<details>
<summary>Deckard</summary>
<br>
</img>
</details>

<details>
<summary>Vulture</summary>
<br>
</img>
</details>

<details>
<summary>Crow</summary>
<br>
That single wall to the right of the outside airlock should be diagonal. I've fixed it but mapdiff didn't catch it so you get this
</img>
</details>

<details>
<summary>Nexus</summary>
<br>
</img>
</details>

<details>
<summary>Nexus Retrofit</summary>
<br>
</img>
</details>

Also updates the descriptions to all of the ships in the purchase menu to match their new looks and roles

## How This Contributes To The Skyrat Roleplay Experience
Incidentally, stops all of the ships from breaking parts of the station when they are spawned.
I thought it was kind of sad having shuttles that people simply didn't buy at all, because the ones I made were just so much more preferable, so now ALL of the shuttles are on an equal playing ground for looking and working well, and all of them are viable choices for overmap activities.

## Changelog

:cl:
expansion: every overmap ship that can be bought has been given a new design!
fix: none of the overmap ships will crash into the station when bought
balance: prices of several of the shuttles have been changed to match their new form
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
Marking this for draft because I want to take a look at the rest of the shuttles too, doesn't seem right to have a vast difference in map quality between all the different types

**Comment by Paxilmaniac** [comment]
Alright NOW it should be ready, I can finally rest forever now that I've spent six hours doing this

**Comment by thestubborn** [comment]
add the among us ship bitch

**Pull request merged**
