### PR TITLE
[DNM] Gunsec? Nah son gunstation; Gives everyone and their mother a firearm, as the founding fathers intended.

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

(Will eventually) Give every role and every department a firearm of some type at roundstart.

To have some fun with it, this adds some unique weapons specific to certain departments.

https://user-images.githubusercontent.com/82386923/229257852-1aaac588-9a94-4de9-8e94-ed47f9edbbfc.mp4

https://user-images.githubusercontent.com/82386923/229257856-fbdce5a2-0f50-4052-9cad-4f5e5a65f954.mp4

https://user-images.githubusercontent.com/82386923/229257865-81108fd9-cb4d-4bb9-9cc9-58367bbf015b.mp4

https://user-images.githubusercontent.com/82386923/229257860-a5bd036a-d2fb-4c66-977f-fd8945bedb4c.mp4

## How This Contributes To The Skyrat Roleplay Experience

So many modern problems now are caused by the regular crewman not having access to a blasta to blow up their problems with.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

Just look in those videos up top
  
</details>

## Changelog

:cl:
add: Starting today, every crewmember will be able to partake in their founding father given right to have a firearm and to shoot that firearm for no reason.
/:cl:

### CODE REVIEW

**Comment by syntax1112** [comment]
YAY

**Comment by PCPort** [comment]
FREEEEEEEEEEEEEEEEEEEE BIIIIRD YEEAA-AA-AAHH

**Review by Gandalf2k15 — APPROVED** [review]
After careful consideration and deliberation with the balance team, we have decided that this is a net positive for overall game balance. Approved for fast-track merge.

**Comment by Zonespace27** [comment]
image

**Pull request merged**
