### PR TITLE
[MIRROR] Refactors crew records (#72725) + Medical/Security records now use the max/min age. [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/73084
--------------------

## About The Pull Request

Both record types were using different minimum and maximum ages to the normal ones, resulting in 17 year old crewmembers having their records state 18 and records could be increased beyond normal crew ages (technically this isn't an issue I guess if any maintainers want this reverted)
## Why It's Good For The Game

Fixes a bug with 17 year old crewmember and consistency.
## Changelog
:cl:
fix: 17 year old crew member medical/security records will no longer show them as 18
code: Medical and security records now use the minimum and maximum age defines rather than hardcoded minimums and maximums
refactor: Crew records have been refactored.
refactor: Medical records -> TGUI
refactor: Security records -> TGUI
refactor: Warrants console -> TGUI
qol: Players are now alerted when their fines are paid off.
qol: Cleaned up sec hud examination text.
qol: Adding and deleting crimes is easier.
qol: Writing crimes in the console sets players to arrest.
qol: You can now mark someone as a suspect through sec hud.
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
relies on missed mirror of https://github.com/tgstation/tgstation/pull/72725

**Comment by KathrinBailey** [comment]
> relies on missed mirror of [tgstation/tgstation#72725](https://github.com/tgstation/tgstation/pull/72725)

went and cherry picked this and fixed the bazillion conflicts
god help my soul

**Review by GoldenAlpharex — APPROVED** [review]
Should be good to go now.

**Review by GoldenAlpharex — APPROVED** [review]
Haven't got any other issues reported to me since the last fixes I made, so I guess we'll figure out in the future if anything else is broken.

**Pull request merged**
