### PR TITLE
Less obnoxious firedoor alarm

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request
For how often the firedoors trigger their alarms (and stay on constantly for an entire round fairly often) it's too loud and obnoxious. This changes it to a softer, lower volume fire alarm chime that's easier to blend in the background if the entire station's spaced and you're gonna be there a while.

## How This Contributes To The Skyrat Roleplay Experience
The firedoors alarming constantly gets on your nerves after a while.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

Both recorded at same volume.

Old:

https://user-images.githubusercontent.com/83487515/213531747-1478ad69-8c01-4b1b-bb5d-9b622397e24d.mp4

New:

https://user-images.githubusercontent.com/83487515/213531774-aadc3b70-2221-42c3-a502-44ee9e1802dd.mp4

</details>

## Changelog

:cl: LT3
soundadd: New firedoor alarm sound
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
This new sound really feels like it doesn’t convey the reason a firelock is closed, because of danger.  It’s already an issue that people will open firelocks willy nilly and cause even more problems. Imagine that you as a player approach a firelock and just hear it quietly pinging, you’d probably think nothing of crowbarring it open only to discover the unmatched power of the void of space behind it.

**Comment by lessthnthree** [comment]
3 tones and then a pause is the standard modern fire alarm pattern. Also the doors have red lights for fire, blue lights if it's cold (space)

I held a poll and it was overwhelmingly in favour that the current alarm is too obnoxious.

**Comment by Zergspower** [comment]
being completely frank the current alarm is brain drillingly annoying to the point our wild poll was like 90% in favor of flat removing it. I dont really see the argument here as it's 1 sound regardless  of why the door is closed - besides if the monkey brain part ignores the blaring flashing lights and goes 'safe' then that's kinda on them

> This new sound really feels like it doesn’t convey the reason a firelock is closed, because of danger. It’s already an issue that people will open firelocks willy nilly and cause even more problems. Imagine that you as a player approach a firelock and just hear it quietly pinging, you’d probably think nothing of crowbarring it open only to discover the unmatched power of the void of space behind it.

**Comment by ghost** [comment]
Honestly, the only thing that I feel needs done to the current alarms is lowering the volume, which I think even TG upstream would agree with. This feels like a holopad notification, more than an alarm.

**Comment by burgerenergy** [comment]
I think a louder pitched beep (IE, this one) is more obnoxious tbh.

**Comment by Jolly-66** [comment]
Yeah I'm not a fan of this.
I'd rather listen to the brain drilling alarm over this water drop tone.

**Comment by Zergspower** [comment]
> Honestly, the only thing that I feel needs done to the current alarms is lowering the volume, which I think even TG upstream would agree with. This feels like a holopad notification, more than an alarm.

halving it or more at minimum - then again im on the team of 'why do we even need this anyway'

**Comment by lessthnthree** [comment]
I put recordings of both up side by side. I don't see how the old one is less obnoxious. It's loud and annoying when it runs constantly.


https://user-images.githubusercontent.com/83487515/213532336-477b5465-cc16-4a3d-84c8-445a7efd2c5a.mp4

https://user-images.githubusercontent.com/83487515/213532350-13c82a75-cde8-480e-9043-7128f7f99d1d.mp4

**Comment by theselfish** [comment]
If something is loud, you lower the volume.

You don't buy a new chipset.

**Comment by YakumoChen** [comment]
Our firedoors are worsened by the fact they're door based and not alarm based, making the whole room obnoxious to be in if even one goes off (not to mention it tends to be very buggy)

**Pull request closed without merging**
