### PR TITLE
Refits upstream paramedic uniforms to fit digi, removes the Bee version of the dark paramedic uniform

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request
Tin.
image

## How This Contributes To The Skyrat Roleplay Experience

Refit

## Changelog

:cl:
imageadd: Paramedic clothing has been refitted for digitigrade legs
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
thats not tin that's blue :) 
image
image

**Review by GoldenAlpharex — COMMENTED** [review]
Honestly, I kind of liked the old white and blue paramed sprites, perhaps we could have them be the alternative, rather than "dark" which was the one we had up until now?

**Comment by Ebin-Halcyon** [comment]
> Honestly, I kind of liked the old white and blue paramed sprites, perhaps we could have them be the alternative, rather than "dark" which was the one we had up until now?

Give me a mo' i'll make it the alternative.

**Comment by ghost** [comment]
God bless you for maintaining your own work :pray: I would have forgotten to do this

**Comment by Ebin-Halcyon** [comment]
> God bless you for maintaining your own work 🙏 I would have forgotten to do this

I give 200% until I burn out and disappear from the internet entirely. I don't know when i'll reach the end, but it'll happen.

**Pull request merged**
