### PR TITLE
[MODULAR] ODST ERT

### PR DESCRIPTION
**Pull request by pinkblossom6**
## About The Pull Request

Adds a new security ERT for use with the pod system for immediate responses.

https://i.imgur.com/hoLkkIT.png

## Why It's Good For The Game

Allows for a very quick response of a security ERT using the ERT bay pod system.

## Changelog
:cl:
add: Adds the ODST ERT
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Not big on even more ERT types. We already have like a dozen different ERT styles now and the pod system is already in place and very usable by admins for regular ERT

**Comment by Draganfrukts** [comment]
Sprites approved by official spriter (merge this)

**Comment by Gandalf2k15** [comment]
Why did you remove the truama team files?

**Comment by Gandalf2k15** [comment]
whoops

**Comment by pinkblossom6** [comment]
> whoops

Oh I just put them into a new folder, with both ODST and Trauma Team being in the same folder (additionalert)

**Pull request merged**
