### PR TITLE
Replaces icebox maint bar with the better one from Citadel

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Slaps in old-old maint bar, with dorm rooms
image

And replaces the regular icebox maint bar with some loot and dirt
image

## Why It's Good For The Game

This bar is way better than the tiny one. The tiny one literally never gets used by more than two or three people.

## Changelog
:cl:
add: Replaces Icebox maint bar with the one from Citadel
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
haha i forgot to map merge

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Could you slap in the **old** old maint bar from Citadel? You can work extra rooms into it, but this maint bar always was heavily annoying due to being an obnoxious blockage you have to walk around for EVA.
Plus, I think there was a preference for the old old bar over the old bar. x_x

**Comment by tf-4** [comment]
> Could you slap in the **old** old maint bar from Citadel? You can work extra rooms into it, but this maint bar always was heavily annoying due to being an obnoxious blockage you have to walk around for EVA.
> Plus, I think there was a preference for the old old bar over the old bar. x_x

Idek what that looks like off the top of my head but sure

**Comment by KathrinBailey** [comment]
**YOUR INTEGRATION TESTS HAVE BEEN RUMMAGED BY MONKEY BUSINESS**
image
**PAY THE BANANA TAX OR NO COMPILE FOR YOU, OOH OOH OOH!!**

**Comment by KathrinBailey** [comment]
https://affectedarc07.github.io/SS13WebMap/Citadel/BoxStation/

**Comment by SpookyTheFox** [comment]
Nice, I remember this place. It actually had a feeling of being a dusty abandoned location.

**Pull request merged**
