### PR TITLE
[Modular] New Space Ruin

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request

Adds a new space ruin, the Nanotrasen Research Outpost. They've been doing some sketchy shit, and it was recently abandoned. Ruin includes
-Enemies to unga-bunga
-Loot to be grabbed
-Traps (the deadly kind)
-Environmental Storytelling
-Eggplant
-Oh also you can disable it in config if you want 

Now Featuring: TGM formatting
gremblo

## Why It's Good For The Game

We need more ruins, I think. If it's not well received I can easily port it to be a planet-side one.

## Changelog
:cl:
add: A new Distant Signal is being registered by GPS devices...
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
heretic ruin. +1

**Comment by Cheshify** [comment]
> heretic ruin. +1

We didn't have any ruins with that theme, and we're still lacking any working simplemobs that fit the theme, though that's a PR for another time. I believe zombies are a fitting replacement, however.

**Comment by gonenoculer5** [comment]
> > heretic ruin. +1
> 
> We didn't have any ruins with that theme, and we're still lacking any working simplemobs that fit the theme, though that's a PR for another time. I believe zombies are a fitting replacement, however.

Honestly if you want to throw some simplemobs in wearing heretic clothes that'd be cool long as it doesnt drop any antag items (such as the armorers robes since this is clearly a path of rust heretic)

**Comment by Cheshify** [comment]
> > > heretic ruin. +1
> > 
> > 
> > We didn't have any ruins with that theme, and we're still lacking any working simplemobs that fit the theme, though that's a PR for another time. I believe zombies are a fitting replacement, however.
> 
> Honestly if you want to throw some simplemobs in wearing heretic clothes that'd be cool long as it doesnt drop any antag items (such as the armorers robes since this is clearly a path of rust heretic)

Potentially? I want to work on some new projects, so that's a PR for another time. When I eventually return to ruins, I'll add simplemobs then (I hate spritework)

Alternatively if you want to be unbelievably based you could add the mobs, but I won't make you drop ongoing projects for that.

**Comment by Cheshify** [comment]
> implying i have something better to do other than making reality ending teslas and engineering shitposts

If you want to collab on something, name on the ratcord is the same as my Git name

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
image
image
Some inconsistencies with walls.
image
This sink looks janky, try moving it to the window or something.
image
Move the wallmount or the light to another spot so it doesn't look like the wallmount is on top of the light.

Other than that, all good. Well done. 👍

**Review by KathrinBailey — APPROVED** [review]

**Comment by KathrinBailey** [comment]
(I approve generally it still needs the changes done, I clicked approve and thought they were already done.)

**Comment by Cheshify** [comment]
> (I approve generally it still needs the changes done, I clicked approve and thought they were already done.)

Er not yet, doing em now

**Pull request merged**
