### PR TITLE
Undoes every skyrat change to the plasma cutter projectiles file

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
colbubdedged (thats spelled right i think) keeps reposting this image of mech plasma cutters doing 45 damage and i thought surely this can't be real, surely we did no make the plasma cutter one of the best mech weapons, surely not!

## How This Contributes To The Skyrat Roleplay Experience
image

https://user-images.githubusercontent.com/82386923/201255855-7f371c4a-533c-44e7-bd71-aeb6382987e1.mp4

To actually explain why this is good, plasma cutters do very little damage by default for a reason, and that is that plasma cutters are mass printable. You can argue that there was the whole pressure damage reduction bit, but really all this served to do was make what's supposed to be a relatively harmless ranged mining tool into a really deadly weapon against blobs or really anythign in space. And, well, the mech plasma cutter, where do I even start. 45 damage on an energy weapon is basically the same as the actual lasers that come from research later on, no good man!

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

</details>

## Changelog

:cl:
balance: Recent job safety regulations have required that power limiters be placed on plasma cutter equipment, as a result plasma cutters, hand held and mech mounted, will cause significantly less harm when fired at anything that isn't rocks.
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
*seethes and copes*
good tho

**Comment by press-mark** [comment]
big if true

**Comment by Ebin-Halcyon** [comment]
Skyrat.

**Comment by Acer202** [comment]
Cutters on SR were always a saving grace against ashwalkers being respawn trolls. Probably for the best, though.

**Review by Zonespace27 — APPROVED** [review]

**Comment by HoodMilk** [comment]
I saw a durand with a plasma cutter on it, it made me sad.
This is a good PR.

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
