### PR TITLE
[MIRROR] Disabler SMG: We got laser carbine, so why not have automatic disabler? [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/79158
--------------------
## About The Pull Request
Basically, it's #78685, but instead of an automatic deadly laser gun, it's an automatic disabler gun.

https://github.com/tgstation/tgstation/assets/42353186/6ce1c401-30a6-45f7-a55c-4d95f742c35a

_For comprasion, normal disabler takes 4 shoots and too uses 80% of charge_

disabler SMG

smg inahnd

It's a side-grade as well, the damage is halved (15 instead of 30) while the ammo count (40 instead of 20) is higher. So damage potential stays the same.
The sound which it uses is more weak sounding to signify that.

You **can't** dual wield them.

You can order a crate of 3 at Cargo.
## Why It's Good For The Game
Automatic guns are fun, and as laser carbine showed - REAL FUN.
This introduces another automatic gun available to the crew through Cargo because variety is always good, and this way we cover the both most prominent projectiles (Lasers and Disablers). 
Now Security can have fun without only killing people, this also lets Pacificists have some as well.

<details>
  <summary>GET DISABLED</summary>

  HoS does ratatata

</details>

## Changelog
:cl:
add: New automatic weapon for the crew - Disabler SMG. Capable of rapidly firing weak disabler beams.
/:cl:

### CODE REVIEW

**Review by vinylspiders — APPROVED** [review]

**Comment by ApplePlastic** [comment]
what the fuck!!

**Comment by vinylspiders** [comment]
Yeah this is probably being nerfed shortly lol

**Comment by Iamgoofball** [comment]
why?

**Comment by Plum-but-gayer** [comment]
this looks sick as hell I literally was just thinking we should have something like this today

**Pull request merged**
