### PR TITLE
Peacekeeper Security Redux [STAGE-5.7]

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## Peacekeeper Security Redux

image

**This is now in phase 5.**

**This PR will also readd the Brig Phys.**

Welcome to the security redux. In this we're going to be changing up a lot of the current security items to have a more corporate feeling, the new colour pallet will be base black and secondary white. We have also fundamentally changed the way security will be interacting with the crew.

With the removal of the energy gun now decided, this has created a void which we aim to fill using many of our new weapons.

This includes changing what weapons the HoP and Captain get. They will both get UNIQUE sidearms, there will only be 1 of each on the station.

We have swapped out the stun-baton for the peacekeeper baton, you can still buy the baton from cargo.

Security itself has had a large uniform and loadout change, and we will be adding more. With this comes a choice of sidearms and main guns that security can choose from using tokens.

# Armament Tokens

image
We have added a new system for security to get unique guns and ammo for themselves, much like the mining token. This can be redeemed at the armaments vending machine. All security officers come with 1 sidearm token by default.

**Sidearm token:**
Can be used to redeem 1 pistol or revolver from the vending machine, there will be a decent selection.
Available gunsets:

- Glock-17

**Primary token:**
These are stored in the armory and can only be given out by the warden. There are 5 of them. They can be used to redeem SMG's from the armament vendor.
Available gunsets:

- LG-2 Norwind
- A-3 PCR

# Gunsets
image
Gunsets are the basic storage case for any gun and ammo. They all come with an ammo pouch and contain whatever contents are set by the gunset.
The captain and HoP both get their personalised gunset in the locker.
For instance, a gunset will contain 1 ammo pouch, the gun(no mag) and 3-4 mags for that gun, all in a neat little box!

*Current Gunsets*
- Glock 17
1x Glock 17
3x Glock 17 rubber mags

- HoS's gunset:
1x Glock 18
2x Glock lethal mags
2x Glock rubber mags

- Captain's Gunset
1x PDH 'Socom'
2x PDH lethal mags
2x PDH IHDF mags

- HoP's Gunset
1x PDH 'Osprey'
3x PDH rubber mags

## New Uniform Set:
image

The standard security belt can now hold pistols, and has an alt+click quickdraw function.

**Officer:**
Standard(What you would wear on green alert):
image

Alert(What you would wear on red alert etc):
image
image

Warden:
image

HoS:
image

Officers come with black beret variants too. **All old clothes are of course still available as well.** 

## New Armaments:
All of em use realism. Jamming and cleaning is required.

## Pistols

**G-17**
image
This is standard issue for all officers in place of the disabler.

```
Stats:
Calibre: Peacekeeper 9mm
Mag cap: 17 rounds
Selective fire: SEMI
```

**G-18**
image
This is the HoS's baby, it's the automatic version of the above.

```
Stats:
Calibre: Peacekeeper 9mm
Mag cap: 33 rounds
Selective fire: SEMI & AUTO
Burst: 3 RNDS
```

**PDH 'Osprey'**
image
The Personal Defence Handgun.
This is NT's standard issue sidearm for commanding officers.

```
Stats:
Calibre: Peacekeeper 10mm
Mag cap: 8 rounds
Selective fire: SEMI 
```

**PDH 'Socom'**
image
The Personal Defence Handgun.
This is NT's prestigious command sidearm, given to captains only.

```
Stats:
Calibre: Peacekeeper 10mm
Mag cap: 8 rounds
Selective fire: SEMI & AUTO
Burst: 3 RNDS
```

## Rifles

**LG-2 'Norwind' Rifle**
image
The LG-2 'Norwind' Rifle
This is a zoomable rifle that has a low mag capacity and slow rate of fire. It's securities long-range defence weapon.

```
Stats:
Calibre: Peacekeeper 12mm
Mag cap: 8
Selective fire: SEMI & AUTO
Burst: 2 RNDS
```

**A-3 PCR**
image
The Automatik-3 Peacekeeper Cyclic Rifle
This is NT's standard issue larger-than-handgun SMG. It's not great, it's not terrible, but if you treat it well, it'll treat you well.

```
Stats:
Calibre: Peacekeeper 9mm
Mag cap: 25
Selective fire: SEMI & AUTO
Burst: 3 RNDS
```

**DMR 'Ripper' Gen-2 (unsure of what to do with it yet)**
image
[REDACTED]

```
Stats:
Calibre: [REDACTED]
Mag cap: [REDACTED]
Selective fire: [REDACTED]
Ammo types: [REDACTED]
```

**Peacekeeper Baton**
image
This is the replacement for the stun baton, all officers get one. It is worse than the classic baton, but should help with the issues we currently have with this being the go to. We want firefights, damn it!

These can still be ordered from supply, and the HoS gets one by default.

# The SMARTGUN
image
ArmaTek is delighted to present the S-M-A-R-T gun. It's a launcher style weapon with a chain-fed cartridge magazine. 

The "smartgun round" is a state of the art dispersal round, it is designed to embed itself into the target after delivering an initial shock of around 3kV, trying to pull this round out causes a secondary shock, likely to down said target. The gun itself is very bulky and slow to fire, but this is due to charge-up time. 

As a replacement for the lack of any kind of taser/grenade launcher, we bring you the ArmaTek S-M-A-R-T gun.

This thing is generally used for large space life, however NT have opted to use it in their security forces.

```
Stats:
Calibre: SMARTGUN 30mm
Round capacity: 5
Round type: SMARTGUN
Fire rate: SLOW
```

## New Ammo Types
image
These ammo types have different cartridges that are easily distinguishable from others. This should help with bullet fests for the detective.

1. **Standard:** Normal lethal round. (Red). These are your bog standard normal damage copper slugs. Cheap, and in abundance. Found in autolathe.
image
image

2. **Hollowpoint:** Higher chance of wound and more damage. (Gold).  These are locked behind research, low grade weapons.
image
image

3. **Rubber rounds:** Low damage but high stamina damage. (Blue). These are cheap, and will down someone quickly. But beware, they still do a bit of damage. They're in the security section of any autolathe.
image
image

4. **IHFD (Intelligent high-impact displacement foam) rounds.** (Green). These are the pride and joy of this. They are essentially no damage disabling rounds. They hit a target and disintegrate on impact, transferring only the force into the body dealing a great amount of stamina damage leaving no bruises! They are locked behind advanced weaponry in the protolathe.
image
image

**All of the mags will be colour-coded(see above) and you can retype them by at clicking and selecting what bullets you plan on putting in.**

# Round Types:

- Peacekeeper 9mm
```
Calibre: 9mm
Compatible types: STANDARD | HOLLOWPOINT | RUBBER | IHDF
```
- Peacekeeper 10mm
```
Calibre: 10mm
Compatible types: STANDARD | HOLLOWPOINT | RUBBER | IHDF
```
- Peacekeeper 12mm
```
Calibre: 12mm
Compatible types: STANDARD | HOLLOWPOINT | RUBBER
```
- SLDN 577
```
Calibre: 9mm
Compatible types: STANDARD
```

## New loadout items
As you know, loadout items have changed, here are the affected jobs and what has been changed.

- Captain
Energy carbine replaced with the captain's gunset.

- HoP
Energy Carbine replaced the hops's gunset.

- Head of Security > Security Commander
The HoS has been renamed, and has the standard peacekeeper boots, gloves, and a brand new uniform. Their energy carbine has been replaced by the Glock 18. They are the only security member with a stunbaton by default.

- Warden
Given a new look and some new clothes. Standard peacekeeper replacement.

- Security Officer
Security officers have been given an all new look, from the ground up.  They've been given a Glock 17 in place of their disabler, it will come with rubbers as standard.

## Special weapon skin requests
You can request special reskins from me for weapons that can be given to you and you only via loadout options.
- TBA

## CREDITS:
Code: Me
Some sprites: Me
Uniforms and equipment: JungleRat
Guns: Sojourn and Eris

## Why It's Good For The Game

We all enjoy SS13 for different reasons, and security has always been lacking somewhat in the department, we'll try to address this. It will evolve over time however I'd like to see how security copes with this.

Security is of course a touchy subject for people that never play it, for whatever reason, so we're going to change things up a little. 

## Changelog
:cl:
add: We've given our security department a new look. Hopefully this stuff won't attract bulls.
add: A new system for getting your sidearm as security. Please check your bag for a "token", and redeem it at the nearest armament vending machine.
add: The standard security belt can now hold pistols, and has an alt+click quickdraw function.
add: The Captain and HoP have now had their energy guns replaced with gunsets, please, check your lockers!
tweak: Most magazines you get can be reskinned by alt+clicking!
tweak: The entire fucking security department.
tweak: As a security officer, you are now equipped with an older style baton, we don't have the cash to keep sending you new state-of-the-art ones.
tweak: We've opted to use our surplus armory to stock up frontier stations. Expect varaing quality.
/:cl:

### CODE REVIEW

**Comment by Zenitheevee** [comment]
>All heads "That are high enough" starting with osprey

Both Poggers and Pogn't.
On one hand, I agree that all heads should have a means of self-defense thats better than a stick. 
On the other hand, Some heads are headasses, And will use any and all excuse to use it. 

Also, "That are high enough" Is a bit vague. High in what regard? Does this mean all heads or only ones like Cap, Hop and Hos? 

Edit: Oh post answers that question above... But at that point, Why not just state its a HoP Only item?

**Comment by Gandalf2k15** [comment]
> > All heads "That are high enough" starting with osprey
> 
> Both Poggers and Pogn't.
> On one hand, I agree that all heads should have a means of self-defense thats better than a stick.
> On the other hand, Some heads are headasses, And will use any and all excuse to use it.
> 
> Also, "That are high enough" Is a bit vague. High in what regard? Does this mean all heads or only ones like Cap, Hop and Hos?
> 
> Edit: Oh post answers that question above... But at that point, Why not just state its a HoP Only item?

Ah, it was too vague, it is replacing the HoP's egun.

**Comment by BrotherHangyul** [comment]
This is.

Beautiful.

Holy fuck.

**Comment by Mithrun** [comment]
Still think a glock doesn't exactly fit into ss13's aesthetic, especially as like a staple weapon, but.. otherwise this is looking great!

**Comment by Vynellin** [comment]
I still stand by the nerf to stun batons should be the old TG version more. 
The new suits look alot better than the old one tho id say you could add variants to the white bits? If possible.
Maybe allow the tokens to redeem for the basic hybrid taser/Big boi laser guns (Unless they are still in the armory if so.) *Shrug*
I do think the doors look silly but thats more cause the doors in general and not a color problem.
So much better improvements over the first pr.
Also come ooon give detective some love they need it.

**Comment by Gandalf2k15** [comment]
> I still stand by the nerf to stun batons should be the old TG version more.
> The new suits look alot better than the old one tho id say you could add variants to the white bits? If possible.
> Maybe allow the tokens to redeem for the basic hybrid taser/Big boi laser guns (Unless they are still in the armory if so.) _Shrug_
> I do think the doors look silly but thats more cause the doors in general and not a color problem.
> So much better improvements over the first pr.
> Also come ooon give detective some love they need it.

I'll change up the batons soon, gotta get it working properly. And we're really trying to move away from energy guns here, that's the point. So tokens should be unique firearms.  Otherwise there is still a bit to come with this.

**Comment by Gandalf2k15** [comment]
> Still think a glock doesn't exactly fit into ss13's aesthetic, especially as like a staple weapon, but.. otherwise this is looking great!

It's only one of the options security will get! Don't worry!

**Comment by Vynellin** [comment]
> > I still stand by the nerf to stun batons should be the old TG version more.
> > The new suits look alot better than the old one tho id say you could add variants to the white bits? If possible.
> > Maybe allow the tokens to redeem for the basic hybrid taser/Big boi laser guns (Unless they are still in the armory if so.) _Shrug_
> > I do think the doors look silly but thats more cause the doors in general and not a color problem.
> > So much better improvements over the first pr.
> > Also come ooon give detective some love they need it.
> 
> I'll change up the batons soon, gotta get it working properly. And we're really trying to move away from energy guns here, that's the point. So tokens should be unique firearms. Otherwise there is still a bit to come with this.

Ehh fair enough. (Tho purely cause how stuff like some random always unga antags work I do stand by lasers should be kept in the armory or at least craftable)

**Comment by Vynellin** [comment]
oh also side tangent giving sec ammo will make them more unpredictable in gun fights against antags cause. "Are they out of ammo or reloading?" Vs. "Okay they expended their battieres nows a good chance to flee."

**Comment by Gandalf2k15** [comment]
> oh also side tangent giving sec ammo will make them more unpredictable in gun fights against antags cause. "Are they out of ammo or reloading?" Vs. "Okay they expended their battieres nows a good chance to flee."

This does seem fairly neutral, it's not a bad thing as far as I can see. But ammo boxes will be bulky and not really carryable, so they'll have a predictable amount of ammo over time, they need to return to base and restock once they've expended their ammo. This is a buff/nerf it seems.

**Comment by MLGTASTICa** [comment]
Great PR , many improvements over stage 4 and 3.

**Comment by Vynellin** [comment]
> > oh also side tangent giving sec ammo will make them more unpredictable in gun fights against antags cause. "Are they out of ammo or reloading?" Vs. "Okay they expended their battieres nows a good chance to flee."
> 
> This does seem fairly neutral, it's not a bad thing as far as I can see. But ammo boxes will be bulky and not really carryable, so they'll have a predictable amount of ammo over time, they need to return to base and restock once they've expended their ammo. This is a buff/nerf it seems.

INB4 we get officers running around with bags of holding.

**Comment by Gandalf2k15** [comment]
> > > oh also side tangent giving sec ammo will make them more unpredictable in gun fights against antags cause. "Are they out of ammo or reloading?" Vs. "Okay they expended their battieres nows a good chance to flee."
> > 
> > 
> > This does seem fairly neutral, it's not a bad thing as far as I can see. But ammo boxes will be bulky and not really carryable, so they'll have a predictable amount of ammo over time, they need to return to base and restock once they've expended their ammo. This is a buff/nerf it seems.
> 
> INB4 we get officers running around with bags of holding.

Remember bags were nerfed!

**Comment by Vynellin** [comment]
> > > > oh also side tangent giving sec ammo will make them more unpredictable in gun fights against antags cause. "Are they out of ammo or reloading?" Vs. "Okay they expended their battieres nows a good chance to flee."
> > > 
> > > 
> > > This does seem fairly neutral, it's not a bad thing as far as I can see. But ammo boxes will be bulky and not really carryable, so they'll have a predictable amount of ammo over time, they need to return to base and restock once they've expended their ammo. This is a buff/nerf it seems.
> > 
> > 
> > INB4 we get officers running around with bags of holding.
> 
> Remember bags were nerfed!

Wtf when?

**Comment by Gandalf2k15** [comment]
> > > > > oh also side tangent giving sec ammo will make them more unpredictable in gun fights against antags cause. "Are they out of ammo or reloading?" Vs. "Okay they expended their battieres nows a good chance to flee."
> > > > 
> > > > 
> > > > This does seem fairly neutral, it's not a bad thing as far as I can see. But ammo boxes will be bulky and not really carryable, so they'll have a predictable amount of ammo over time, they need to return to base and restock once they've expended their ammo. This is a buff/nerf it seems.
> > > 
> > > 
> > > INB4 we get officers running around with bags of holding.
> > 
> > 
> > Remember bags were nerfed!
> 
> Wtf when?

They require anomaly cores to work now!

**Comment by Vynellin** [comment]
> > > > > > oh also side tangent giving sec ammo will make them more unpredictable in gun fights against antags cause. "Are they out of ammo or reloading?" Vs. "Okay they expended their battieres nows a good chance to flee."
> > > > > 
> > > > > 
> > > > > This does seem fairly neutral, it's not a bad thing as far as I can see. But ammo boxes will be bulky and not really carryable, so they'll have a predictable amount of ammo over time, they need to return to base and restock once they've expended their ammo. This is a buff/nerf it seems.
> > > > 
> > > > 
> > > > INB4 we get officers running around with bags of holding.
> > > 
> > > 
> > > Remember bags were nerfed!
> > 
> > 
> > Wtf when?
> 
> They require anomaly cores to work now!

With how often they happen thats not much of a nerf

**Comment by CameronWoof** [comment]
The guns look neat (though everything from Eris looks fantastic, so that's not surprising) but I'm pretty sure I hate the black and white security look.

Just steal Eris' Ironhammer uniforms, they look much better than anything here.

**Comment by Gandalf2k15** [comment]
> The guns look neat (though everything from Eris looks fantastic, so that's not surprising) but I'm pretty sure I hate the black and white security look.
> 
> Just steal Eris' Ironhammer uniforms, they look much better than anything here.

We may consider it, but we do want our own look.

**Comment by Gandalf2k15** [comment]
**Update 5.5**
Gunsets are in.
The captain now gets their gunset.
The HoP now gets their gunset.
The armament vending machines have been added, plus their functionality.
Security now get their tokens.
Most instances of the egun have been replaced in some capacity.

**Comment by Gandalf2k15** [comment]
Remember, you can alt+click mags to reskin them.

**Comment by Gandalf2k15** [comment]
You can now quickdraw your pistol from the belt.

**Comment by Gandalf2k15** [comment]
In phase 6 I will be adding:
Attachable pouches for your armor which can hold any small items.
A whole array of new guns
More gunsets 
The brig phys

**Comment by Vizoplez** [comment]
> > > > > > > oh also side tangent giving sec ammo will make them more unpredictable in gun fights against antags cause. "Are they out of ammo or reloading?" Vs. "Okay they expended their battieres nows a good chance to flee."
> > > > > > 
> > > > > > 
> > > > > > This does seem fairly neutral, it's not a bad thing as far as I can see. But ammo boxes will be bulky and not really carryable, so they'll have a predictable amount of ammo over time, they need to return to base and restock once they've expended their ammo. This is a buff/nerf it seems.
> > > > > 
> > > > > 
> > > > > INB4 we get officers running around with bags of holding.
> > > > 
> > > > 
> > > > Remember bags were nerfed!
> > > 
> > > 
> > > Wtf when?
> > 
> > 
> > They require anomaly cores to work now!
> 
> With how often they happen thats not much of a nerf

Very much still an issue, we nerfed the SM at some point, and other anomaly cores only come from maxcaps.

**Comment by H0gberg** [comment]
looking tons better! But one good QOL would maybe to make the tokens purchasable at cargo, and maybe hacking the arming vendors could give a cool/silly gun which could be funny like I dunno a fuckin' bow and some arrows

**Comment by Gandalf2k15** [comment]
Phase 5.7 is now here. We've added this:
PCR unique ammo
The LG-2 norwind
More gunsets

**Comment by Gandalf2k15** [comment]
Updoot:@
# The SMARTGUN.
image
ArmaTek is delighted to present the S-M-A-R-T gun. It's a launcher style weapon with a chain-fed cartridge magazine. 

The "smartgun round" is a state of the art dispersal round, it is designed to embed itself into the target after delivering an initial shock of around 3kV, trying to pull this round out causes a secondary shock, likely to down said target. The gun itself is very bulky and slow to fire, but this is due to charge-up time. 

As a replacement for the lack of any kind of taser/grenade launcher, we bring you the ArmaTek S-M-A-R-T gun.

This thing is generally used for large space life, however NT have opted to use it in their security forces.

Instead of having a locker full of riot bullets, you have a locker with this, that has 1 smartgun and 2 mags. You can't recreate the mags or bullets.

```
Stats:
Calibre: SMARTGUN 30mm
Round capacity: 5
Round type: SMARTGUN
Fire rate: SLOW
```

**Comment by Vynellin** [comment]
Where is the qms gun

**Comment by Mithrun** [comment]
> > Still think a glock doesn't exactly fit into ss13's aesthetic, especially as like a staple weapon, but.. otherwise this is looking great!
> 
> It's only one of the options security will get! Don't worry!

I hope the loadout system ends up being very compact with as little options as possible, otherwise it would 1. be too daunting for anyone getting 2. hard to balance in such a way where it won't be like "oh there's 7 guns but everyone just uses this one." 
good luck!

**Pull request closed without merging**
