### PR TITLE
[Modular] Interdyne 2.0, + Syndie Wardrobe

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Completely redos the Interdyne base from the ground up for all the features we've got for it. Trades out the turbine for a Nanite and Circuitry lab. Ancient Lathes are now roundstart.
image

This PR also updates Cybersun, Interdyne, and DS-1 to have a new Syndicate wardrobe vendor! And maybe something else, if you look hard enough.

## Why It's Good For The Game
Old base was beginning to look like a tumor, and the turbine? The turbine was always a meme and a half. I genuinely don't think sacrificing the server's tickspeed via megafauna ramming into engineering's air tanks was worth it.

## Changelog
:cl:
add: Interdyne's planetary outposts have been completely rebuilt from the ground up.
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
Looks very soulless

**Comment by unit0016** [comment]
> Looks very soulless

image

**Comment by Sethnov** [comment]
bring back my atmos plasma oxygen nitrogen chambers

**Comment by unit0016** [comment]
> bring back my atmos plasma oxygen nitrogen chambers

>I genuinely don't think sacrificing the server's tickspeed via megafauna ramming into engineering's air tanks was worth it.

**Comment by YakumoChen** [comment]
#4123

I don't really see a need for lathes, or mining in general. Lavaland Syndicate is supposed to mostly be a learning role for science, mining just adds an unneeded cold war between the station and syndicate on lavaland, especially now that you've taken away traitor interaction with it.

All I see miners doing is just speedrunning the megafauna anyway because they didn't roll miner at roundstart.

**Comment by unit0016** [comment]
> #4123
> 
> I don't really see a need for lathes, or mining in general. Lavaland Syndicate is supposed to mostly be a learning role for science, mining just adds an unneeded cold war between the station and syndicate on lavaland, especially now that you've taken away traitor interaction with it.

#2948 
Quote from the PR: "Comms Agents get both Interdyne and Syndiecomms, except Space Comms agents, who keep their cool bowman headset." Not to mention how many resources truly are packed into lavaland. Let me emphasize this point and emphasize it greatly: **Not even rounds that lasted multiple days on /tg/station campbell mined out all of lavaland.** Multiple. Days.

https://github.com/Skyrat-SS13/Skyrat-tg/pull/3808


> All I see miners doing is just speedrunning the megafauna anyway because they didn't roll miner at roundstart.

Interdyne Miners haven't rushed megafauna for a _month_ now. Do you know why, Chen? **They can't print GPS units.** In fact, contrary to popular knowledge, I genuinely consider Interdyne to be **too** friendly with the station, outright appearing onstation to hand over corpses and outright using the station medbay on occasion, talking with them over comms and forming friendships.

**Comment by YakumoChen** [comment]
I see interdyne miners killing megafauna all the time. I've gone on observe to listen to them bragging about how fast they do it. It's not uncommon, and GPS units are easy to get. You can _print them from the protolathe_

**Comment by unit0016** [comment]
> I see interdyne miners killing megafauna all the time. I've gone on observe to listen to them bragging about how fast they do it. It's not uncommon, and GPS units are easy to get. You can _print them from the protolathe_

**You cannot print them from the ancient protolathe.** You'd know this if you didn't just open the issue and come up to complain about someone else by proxy. I'm gonna save the maintainers and myself the hassle and just block you, honestly.

**Comment by Kush1Push1** [comment]
> Looks very soulless

**Comment by unit0016** [comment]
> > Looks very soulless

> 
image

**Comment by Vizoplez** [comment]
> I see interdyne miners killing megafauna all the time. I've gone on observe to listen to them bragging about how fast they do it. It's not uncommon, and GPS units are easy to get. You can _print them from the protolathe_

I dont think you've played in the past three weeks.

**Comment by werewolfboyfriend** [comment]
Love this, this looks really nice, except for the whole botany/lockers/dorms area is laid out kind of awkwardly. I feel like the kitchen/bar would make more sense there, with botany where the kitchen/bar is now. Maybe that would leave room for actual tables. Xenobio could use an equipment locker back, too.

**Comment by unit0016** [comment]
> Love this, this looks really nice, except for the whole botany/lockers/dorms area is laid out kind of awkwardly. I feel like the kitchen/bar would make more sense there, with botany where the kitchen/bar is now. Maybe that would leave room for actual tables. Xenobio could use an equipment locker back, too.

I'll brainstorm to see if I can set up a better system, honk.

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
