### PR TITLE
restoring some items in a vendor

### PR DESCRIPTION
**Pull request by thestubborn**
## About The Pull Request

title, a bunch of collars, keys for them, ring gag, and uhh-
here
stuff from here https://github.com/Skyrat-SS13/Skyrat-tg/pull/8457/files

## How This Contributes To The Skyrat Roleplay Experience

most of these items weren't anywhere else barring the loadout
## Changelog

:cl:
fix: restored items to the lustvendor
/:cl:

### CODE REVIEW

**Comment by ForrestWick** [comment]
Hey while you're at it, engi wardrobe vendors are missing items, as are the normal engivends. 
image
Hazard suits are missing roundstart. Just... 0 available every round.

image

Same with scanner goggles

**Comment by thestubborn** [comment]
image
seems fine

**Comment by GoldenAlpharex** [comment]
Can you update this PR with master, so we can re-run CI and ensure that it passes?

**Comment by thestubborn** [comment]
> 
> 
> Can you update this PR with master, so we can re-run CI and ensure that it passes?

k

**Review by GoldenAlpharex — APPROVED** [review]
Honestly, sure, we can always have them taken out when they get replaced.

**Pull request merged**
