### PR TITLE
[DNM] [MDB IGNORE] code for an event: the air is no longer flammable edition

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
you know you know

## How This Contributes To The Skyrat Roleplay Experience
it likely won't

### CODE REVIEW

**Comment by azrael-x86** [comment]
changing runtime station to fit an event: cursed as hell

**Comment by Paxilmaniac** [comment]
this is going to fail checks

**Comment by Paxilmaniac** [comment]
i should've given this mdb ignore :trollface:

**Comment by Zonespace27** [comment]
> i should've given this mdb ignore :trollface:

AA will come for our collective souls in a day or two

**Comment by Paxilmaniac** [comment]
i think you can still testmerge closed prs and im not actively fucking with this so

**Pull request closed without merging**
