### PR TITLE
Mirror #72127

### PR DESCRIPTION
**Pull request by Zonespace27**
https://github.com/tgstation/tgstation/pull/72127
Closes https://github.com/Skyrat-SS13/Skyrat-tg/pull/18415

🆑 SkyratBot
add: chocolate boxes now contain bonbons (formerly tiny chocolates), truffles, and peanut butter cups
balance: changed the sugar in clown cakes' food_reagents to banana juice
balance: increased the amount of vitamin in pound cakes
fix: slices of bread now taste like their respective breads instead of tasting "indescribable"
fix: fiesta skewers are now MEAT and VEGETABLES
/🆑

### CODE REVIEW

**Comment by ghost** [comment]
```
modular_skyrat/modules/customization/modules/food_and_drinks/food/teshari_food.dm:31:error: MakeProcessable: undefined proc
modular_skyrat/modules/imported_vendors/code/vendor_snacks.dm:48:error: MakeLeaveTrash: undefined proc
modular_skyrat/modules/imported_vendors/code/vendor_snacks.dm:137:error: MakeLeaveTrash: undefined proc
modular_skyrat/modules/imported_vendors/code/vendor_snacks.dm:247:error: MakeLeaveTrash: undefined proc
code/game/objects/items/food/bread.dm:534:error: MakeBakeable: undefined proc
modular_skyrat/modules/customization/modules/hydroponics/grown/kiri.dm:29:error: MakeBakeable: undefined proc
modular_skyrat/modules/customization/modules/hydroponics/grown/muli.dm:29:error: MakeBakeable: undefined proc
modular_skyrat/modules/customization/modules/food_and_drinks/food/scottish.dm:9:error: MakeProcessable: undefined proc
modular_skyrat/modules/customization/modules/food_and_drinks/food/teshari_food.dm:11:error: MakeProcessable: undefined proc
modular_skyrat/modules/customization/modules/food_and_drinks/food/teshari_food.dm:14:error: MakeGrillable: undefined proc
modular_skyrat/modules/customization/modules/food_and_drinks/food/teshari_food.dm:17:error: MakeBakeable: undefined proc
modular_skyrat/modules/customization/modules/food_and_drinks/food/teshari_food.dm:52:error: MakeProcessable: undefined proc
modular_skyrat/modules/customization/modules/food_and_drinks/food/teshari_food.dm:55:error: MakeGrillable: undefined proc
modular_skyrat/modules/customization/modules/food_and_drinks/food/teshari_food.dm:58:error: MakeBakeable: undefined proc
modular_skyrat/modules/customization/modules/food_and_drinks/food/teshari_food.dm:155:error: MakeProcessable: undefined proc
```
These all simply need conversion to snake_case; specifically to these procs:
```
make_edible()
make_processable()
make_leave_trash()
make_grillable()
make_bakeable()
make_decompose(mapload)
make_microwaveable()
```

Though, the error in code/game/objects/items/food/bread.dm is concerning. Did a file not get caught in the mirror?

**Comment by Tastyfish** [comment]
@OrionTheFox The bread error was a skew on master tg that was fixed by https://github.com/tgstation/tgstation/pull/72414. Cherry picking it in.

**Comment by Jolly-66** [comment]
That irritated me

**Review by Tastyfish — APPROVED** [review]
breb

**Pull request merged**
