### PR TITLE
[Semi-Modular] Resurrects #1304's Catwalk Changes

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Does what it says on the tin.
New catwalk items, mechanics, prefabs, and changes. Part of a WIP update to the NSS Journey 👀 
Craftable by players! You can construct catwalks the standard way by using two rods on a space tile, but you can also craft catwalks in the crafting menu now.
Example in action:
image
image
image
image

## Why It's Good For The Game
Honestly Eris-style catwalks is great, Lets maintenance be more varied than just "plating with wire". Deltastation's style is good, but we can DO BETTER.

## Changelog
:cl:
add: Catwalks have been changed up! New catwalk varieties are available, now showing wires underneath.
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
I've discovered the edits to the solars was unnessecary
fuck

**Comment by unit0016** [comment]
Map changes removed. I'll do it to Journey on it's own time.

**Comment by Arctaisia** [comment]
Literally in love with this right now.

**Comment by ghost** [comment]
You've made a good PR! You've been rewarded 1(one) cat! https://youtu.be/pRtxaJdZPAo

**Review by KathrinBailey — APPROVED** [review]

**Comment by GoldenAlpharex** [comment]
Is your branch updated to the current state of the repo? If not, it might be why you're failing CI because of `connected_loc`

**Comment by unit0016** [comment]
Cockroach CI Suite moment

**Review by Gandalf2k15 — APPROVED** [review]
LGTM

**Comment by Azarak** [comment]
a little credit wouldnt hurt

**Comment by unit0016** [comment]
> a little credit wouldnt hurt

Wasn't sure how to go about it other than directly posting the PR number, tbh.

**Pull request merged**
