### PR TITLE
Disable spiders from rolling in events

### PR DESCRIPTION
**Pull request by Funce**
## About The Pull Request
Good bye spiders! You will no longer appear here.

## How This Contributes To The Skyrat Roleplay Experience
Spiders are boring, we're dealing with it today.

## Changelog

:cl: Foxtrot / Funce
balance: Spider infestation no longer appears randomly
/:cl:

### CODE REVIEW

**Comment by PCPort** [comment]
Don't mind me, just downvoting the salt PR.

Spiders are:

-Fun to play
-A genuine threat to the entire crew if played well, not just security (rare)
-Not at all impossible to defeat, especially with the advent of gun cargo
-Variety to the antag roster

If you don't like the current state of spiders, then think up some actual CHANGES as opposed to just removing them. Improve, not remove, remember?

**Comment by Funce** [comment]
They're still there, they just don't appear randomly anymore. So only when the admins feel particularly..... vindictive.

**Comment by PCPort** [comment]
They roll rarely enough that it's a non-issue as is. At most you'll see like... One spider infestation a week, if that.

**Comment by Higgin** [comment]
spiders should not only roll randomly but be more frequent, they're a good midround and this is a bad PR

edit: also gating things to admin-spawn-only tends to mean they show up even less than before, which sucks when a lot of those things stand to add more cool variety to the rounds a person might catch

**Comment by hugmeorelse** [comment]
Spider shouldn't be rolling right now. We were planning on bringing it back with a combat rework, but that didn't happen. So, it shouldn't be rolling right now. That may change after discussion. However, it's being turned off until discussions are had.

This should be running in dynamic instead anyhow.

**Pull request merged**
