### PR TITLE
Void Raptor - Exposes open plating in maintenance

### LINKED ISSUE #19250: Void Raptor lacks free plating tiles in maintenance, causing roundstart mice to spawn in the emitter room
I feel like this is already summed up in the title.

image

(There were 8 mice in this room, mind you)

Void Raptor needs more "free" plating tiles around in maintenance so mice.. stop doing this.

### PR DESCRIPTION
**Pull request by SomeRandomOwl**
## About The Pull Request

This adds more exposed plating tiles in void raptors maintenance tunnels PR is intended to fixes: #19250

## How This Contributes To The Skyrat Roleplay Experience

This changes up and adds more places for mice to spawn rather than all in the emitter room

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

https://github.com/Skyrat-SS13/Skyrat-tg/assets/2568378/6aa9c6a5-e321-4690-be97-d0852fed527c

</details>

## Changelog

:cl:
fix: Maintenance bills haven't been paid on void raptor, some plating in the maintenance tunnels are more exposed, expect more mice.
/:cl:

### CODE REVIEW

**Comment by SomeRandomOwl** [comment]
merge conflict?

**Comment by Jolly-66** [comment]
1. You should really be starting from your master branch*, which you should always make sure is 1:1 with upstream/master
2. The correct format to link issues (and have them closed when a PR is merged) is `fixes: #0000`

*Basing it off it, NEVER push from your master branch unless you desire to create a nightmare for yourself.

**Comment by SomeRandomOwl** [comment]
> 1. You should really be starting from your master branch*, which you should always make sure is 1:1 with upstream/master
> 2. The correct format to link issues (and have them closed when a PR is merged) is `fixes: #0000`
> 
> *Basing it off it, NEVER push from your master branch unless you desire to create a nightmare for yourself.

it should be from a new branch from master, im not sure why it wasnt already updated

**Comment by SomeRandomOwl** [comment]
really fucking odd, it just like ignored 300 commits that where on the master branch already when i made this branch thats so dumb

**Comment by SomeRandomOwl** [comment]
dumb bot it is a map edit

**Comment by SomeRandomOwl** [comment]
ok that didnt fix it, not sure whats broken

**Comment by SomeRandomOwl** [comment]
Ok clearly this branch is cursed, im just going to retry and remake this again but this time ensuring im going from master so i dont start with any merge conflicts

**Pull request closed without merging**
