### PR TITLE
[Modular] Body size 0.8 is pickable again

### PR DESCRIPTION
**Pull request by Superlagg**
## About The Pull Request

'Fixes' a rounding error(?) that made sanitize_float round 0.8 down to 0.79999995, and therefore think 0.8 is less than 0.8 when step was set to 0.01.

Literally just set step in /datum/preference/numeric/body_size from 0.01 to 0.0000001. Seems to work just fine.

## How This Contributes To The Skyrat Roleplay Experience

Short characters can be that teensy bit shorter like they should be.

## Changelog

:cl:
fix: Body size now accepts 0.8 as it should.
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
Ngl I don't like this as a fix. I don't have an alternative, but this feels hacky.

**Comment by YakumoChen** [comment]
isn't this going to bloat out the field with a bunch of decimals?
What you should do is just change MIN_BODYSIZE to 8.01 or something so it doesnt' bug out.

**Comment by Superlagg** [comment]
> isn't this going to bloat out the field with a bunch of decimals? What you should do is just change MIN_BODYSIZE to 8.01 or something so it doesnt' bug out.

The field already accepts enormous decimals just that they're rounded down when saved and loaded. And, the field scales to the number in there. If you put in 0.8, it'll show 0.8 and scale the box to fit.

I tried changing the body size defs, setting it to 0.79 made it so 0.79 was accepted as well. Setting it to 0.801 wouldnt help either, since players would need to type in 0.801 to get 0.8.

**Comment by YakumoChen** [comment]
My concern is that the typical way to change the number is to drag the "slider" and that's going to make a mess with a field that has a ton of decimals in each step

**Comment by GoldenAlpharex** [comment]
I feel like there's a better way to do it than this.

**Pull request closed without merging**
