### PR TITLE
[modular][ready]the scottish metaclub infests cooking

### PR DESCRIPTION
**Pull request by thestubborn**
https://www.youtube.com/watch?v=eypZnajNdmQ

## About The Pull Request

adds haggis and battered sausage to cooking

## Why It's Good For The Game
image

if lizards can get a bunch of food, then another alien race should get their food

## Changelog
:cl:
expansion: haggis and battered sausage added to cooking
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
I didn't know that the Scottish were aliens 😎

**Comment by YakumoChen** [comment]
PR it upstream

**Comment by thestubborn** [comment]
> 
> 
> PR it upstream

fuck tg
and I'm too lazy

**Comment by thestubborn** [comment]
> 
> 
> I didn't know that the Scottish were aliens 😎

we are, yes

**Comment by linnpap** [comment]
Based.

**Pull request merged**
