### PR TITLE
"Reverts" TG Lizard Scream

### PR DESCRIPTION
**Pull request by Owai-Seek**
## About The Pull Request

"Reverts" the weird goat sounds to the much better Citadel Scream.

## Why It's Good For The Game

The old scream was better, and these sound weird. One is literally just a tone shift of another.

For anyone wanting to listen to them:

OLD
https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/modular_skyrat/modules/emotes/sound/voice/scream_lizard.ogg

NEW
https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/sound/voice/lizard/lizard_scream_1.ogg
https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/sound/voice/lizard/lizard_scream_2.ogg
https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/sound/voice/lizard/lizard_scream_3.ogg

## Changelog
:cl:
qol: Citadel/Oldbase Lizard Scream returns.
/:cl:

### CODE REVIEW

**Comment by sneksnek** [comment]
big agree

**Comment by Vizoplez** [comment]
I'd say the new ones are better IMO, if a little weird sounding.

**Comment by RatFromTheJungle** [comment]
image

**Comment by KasparoVy** [comment]
> 
> 
> I'd say the new ones are better IMO, if a little weird sounding.

It's totally a matter of taste, I ain't gonna fault anyone for liking either or, but I really really enjoy the new ones. *Shrug*

Wish we could choose our 'voice', so to say.

**Comment by Gandalf2k15** [comment]
Nawwwh I actually like the new one more.

**Comment by NullDagaf** [comment]
Personally, I have no strong feelings one way or the other.

**Comment by NullDagaf** [comment]
....mostly because I didn't even hear them in the first place 🤡

**Comment by Owai-Seek** [comment]
I'd rather it be put to a vote if we're going to use one or the other, but preferably there would be an ability to change to what scream you want, and I don't have the coding capabilities to do that. Gandalf. I'm pretty sure you don't even play a lizard.

**Comment by Gandalf2k15** [comment]
> I'd rather it be put to a vote if we're going to use one or the other, but preferably there would be an ability to change to what scream you want, and I don't have the coding capabilities to do that. Gandalf. I'm pretty sure you don't even play a lizard.

Yes I do actually. I much prefer the new screams compared to the comical old ones we had. A lot of people feel the same way as I do. And being the Head coder here I do have the power to veto something. But in this case I'll leave it be for now and see if a majority of people agree.

**Comment by NullDagaf** [comment]
Okay, after actually listening to the sounds.

...yeah, please revert. Idea's good but the execution's absolute dogshit.

**Review by KathrinBailey — APPROVED** [review]
Am fine with this being merged because the new ones sound like a goat that has survived a botched execution attempt in a slaughterhouse. It's awful.

If you want to put this to a poll, fair warning. People don't give a shit and won't even listen to the sounds. They'll just click the funny buttons. So I'd upload the sounds directly to the page so they don't have to download them.

If you don't have access to post polls poke me and I'll do it for you.

**Comment by Owai-Seek** [comment]
I'd have to convert the sounds to .mp3 I think, .ogg aren't a supported file type for github previews.

**Pull request closed without merging**
