### PR TITLE
[MODULAR] Let us know what limbs we have. 

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request

Undoes the the user-facing effects of https://github.com/Skyrat-SS13/Skyrat-tg/pull/13302

While TGstation may not care what limbs we have, it's a good idea for us given we have TONS of limb types all with different behavior, commonly found. Especially common with synths. 
dreamseeker_xFWWZOtgMh

## How This Contributes To The Skyrat Roleplay Experience

Flavourful + Helps medical / robotics / players. 

## Changelog

:cl:
code: Overrides the limb-name var from generic to origin-species on initialize. 
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
image

**Comment by YakumoChen** [comment]
the PR you're reverting doesn't actually affect self-examine part names, just combat logs and wounds.

**Comment by GoldenAlpharex** [comment]
I really don't think reverting this is a good thing. At all. It's just more clutter in combat logs, for no actual gain, since that information is already available.

**Comment by nevimer** [comment]
> I really don't think reverting this is a good thing. At all. It's just more clutter in combat logs, for no actual gain, since that information is already available.

Then we should add a way to inspect other peoples limbs, as medical scanners do not show what limbs a person has, nor do visual inspections.

**Pull request closed without merging**
