### PR TITLE
|

### PR DESCRIPTION
**Pull request by ValuedEmployee**

### CODE REVIEW

**Comment by nevimer** [comment]
They're currently disallowed from the Goofsec PR to have medical supplies - their access was removed. Additionally,  they don't start with tools to do more than maybe one person's worth of first aid, extremely inefficiently. Mayhapsbe add back their medical access in exchange. Most officers are carrying guns anywho, and the firefly required one magazine or more to kill someone.

**Comment by YakumoChen** [comment]
They could also just ask medical for supplies???

**Comment by softcerv** [comment]
> They're currently disallowed from the Goofsec PR to have medical supplies - their access was removed. Additionally, they don't start with tools to do more than maybe one person's worth of first aid, extremely inefficiently. Mayhapsbe add back their medical access in exchange. Most officers are carrying guns anywho, and the firefly required one magazine or more to kill someone.

https://github.com/Skyrat-SS13/Skyrat-tg/pull/13778, this is going to be added in the firefly's place for this PR. This way sec-medics will still be able to do basic paramedic level healing but they won't start off with a lethal ballistic pistol. If they need any additional firepower, they can either buy it or get it from the armory like the other officers.

**Comment by nevimer** [comment]
> They could also just ask medical for supplies???

Security Medic 
Medic
Security

Medical?
Security... Hmm... 
They have it in their job title.. But yet... no medical access.. less access than a paramedic.. But the HOS? Yeah  it's fair game they bust down medicals doors and pilfer the goods and go arrest doctors mid surgery, no problem there. Yeah, help yourself to all the department lathes too, why not? Tool belt? HOS belt. Only the essentials. 

But the medic having access to the department that will frequent...
Too far. Nope, can't do it. Gotta suffer.

**Comment by theselfish** [comment]
It's almost like Sec Medical is a stupid job anyway.
Though I do agree (shockingly) that HoS shouldn't be able to barge into departments.
It's why Goof added Orderlies. You tell them to get the fuck out of a surgery room.

**Comment by softcerv** [comment]
> > They could also just ask medical for supplies???
> 
> Security Medic Medic Security
> 
> Medical? Security... Hmm... They have it in their job title.. But yet... no medical access.. less access than a paramedic.. But the HOS? Yeah it's fair game they bust down medicals doors and pilfer the goods and go arrest doctors mid surgery, no problem there. Yeah, help yourself to all the department lathes too, why not? Tool belt? HOS belt. Only the essentials.
> 
> But the medic having access to the department that will frequent... Too far. Nope, can't do it. Gotta suffer.

They are pretty much supposed to be security officers that handle light paramedic stuff, they don't need access to a wide variety of medical tools, just the stuff that you'd probably get from medikits.

The HoS should probably get their medical access knocked down a peg or two, but that is something that is outside of the scope of this PR.

**Comment by Gandalf2k15** [comment]
This was a recent change and isn't going to be changed again for some time.

**Pull request closed without merging**
