### PR TITLE
[MODULAR] Removes the most useless ruin in code

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request
Title.

## How This Contributes To The Skyrat Roleplay Experience
~~Less crap I have to maptain.~~
Its a gag that could be spent on spawning other ruins. Its also invisible.
I don't find this funny.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

image
  

</details>

## Changelog

:cl: Jolly
del: A mysterious single tile invisible space fan has been removed from the game. Yes, this was a map.
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
YIPPIE

**Comment by RatFromTheJungle** [comment]
sorry this is important in the lore, infact, could you make 13 more? Thanks!

**Comment by Jolly-66** [comment]
> sorry this is important in the lore, infact, could you make 13 more? Thanks!

I'll make 13 more once you force it from my cold dead hands.

**Comment by Paxilmaniac** [comment]
how did you make it fail compiling every map

**Comment by Jolly-66** [comment]
> how did you make it fail compiling every map

NUINTERLINK.

**Comment by tf-4** [comment]
bad justification for removal this is a key map. It doesn't need maintaining, as it is a single tile

**Comment by Jolly-66** [comment]
> bad justification for removal this is a key map. It doesn't need maintaining, as it is a single tile

I'll justify your death (updated it).

**Review by Zonespace27 — APPROVED** [review]

**Comment by SpaceVampire** [comment]
More and more SOUL leaves the codebase by the day...
Never forget what they took from us.

**Review by Paxilmaniac — APPROVED** [review]
I forgot that I'm a maptainer and can merge this

**Review by Paxilmaniac — CHANGES_REQUESTED** [review]
I remember why now,
modular_skyrat/modules/mapping/code/space.dm

Remember to remove this part
image

**Review by Paxilmaniac — APPROVED** [review]

**Comment by Zenitheevee** [comment]
Finally

**Pull request merged**
