### PR TITLE
removes australicus slime extract injector from the uplink

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

removes australicus slime extract injector from the uplink

## Why It's Good For The Game

Because basically nobody has fun when it happens and people end up extremely salty, makes for unfun rounds.

## Changelog
:cl:
del: removes australicus slime injector from the uplink
/:cl:

### CODE REVIEW

**Comment by BurgerLUA** [comment]
This gets abused way too much and it leads to round ending scenarios that are worse than any maxcap or supervirus you can buy in the uplink. It's genuinely extremely powerful and it's absolutely silly that this costs 10TC.

**Comment by KathrinBailey** [comment]
Will bring this up with staff unless another maintainer overrules it.

**Comment by MLGTASTICa** [comment]
Why not make it 40 TC so that antags have to cooperate to cripple the station?

**Comment by SpaceVampire** [comment]
"cripple the station"
It spawns two broodmother spiders, the same as the old spawn spiders event.
In order to do this you need to be fairly deep into xenobio, to make sure it can't be done right at the start of the shift.
They aren't that powerful, this sounds like it more of an issue with people not dealing with them at all, and letting it get out of hand, because spiders have some pretty major weaknesses. 
EDIT: You also don't get to play as them or anything, so you have to count on their being a decent number of willing ghosts if you want to see any real effect from it.

**Comment by BurgerLUA** [comment]
> "cripple the station"
> It spawns two broodmother spiders, the same as the old spawn spiders event.
> In order to do this you need to be fairly deep into xenobio, to make sure it can't be done right at the start of the shift.
> They aren't that powerful, this sounds like it more of an issue with people not dealing with them at all, and letting it get out of hand, because spiders have some pretty major weaknesses.
> EDIT: You also don't get to play as them or anything, so you have to count on their being a decent number of willing ghosts if you want to see any real effect from it.

Skyrat currently has 92 players playing. Only 54 are actually on the crew manifest. That leaves 38 either in the lobby or observing. That's 41% of players. Out of those 38 players observing, how many do you think are willing to play a yolo ghost role with basically no rules on escalation and can always respawn as a new spider?


You will have enough spiders. And the thing is that security doesn't usually sweep maint when the spiders are finally spawned in, so they're going to have a lot of time to lay eggs. You'll have an army of spiders in about 5 minutes ready to target the shuttle because that's meta.

**Comment by YakumoChen** [comment]
Spiders die extremely fast to atmos or cold of any kind (temperature guns are massively deadly to spiders). It's really as easy as just exposing their nest to space or arming the crew with temp guns. Spiders can't heal.

**Comment by BrotherHangyul** [comment]
Was an incredibly shitty round today.

Spiders plasmaflooded and N2O flooded the station, killing most of the round's pop.

Remove this shit.

**Comment by YakumoChen** [comment]
How did they manage that lol
Sounds more reasonable to ban the player since that's griefy

**Comment by BrotherHangyul** [comment]
> How did they manage that lol
> Sounds more reasonable to ban the player since that's griefy

By biting canisters kek

also nobody got banned for it

**Comment by YakumoChen** [comment]
Should have been, opening shit air hurts the spiders more than the crew since they dont get gad masks 

Also its pretty explicitly grief.

**Comment by Gandalf2k15** [comment]
Hello, this has been in limbo for a while. I will hold a vote momentarily.

**Comment by Gandalf2k15** [comment]
Vote outcome was stalemate, this will be closed until further notice. This hasn't been an issue as of late, so please understand my want for github to be tidy.

**Comment by hugmeorelse** [comment]
> Vote outcome was stalemate, this will be closed until further notice. This hasn't been an issue as of late, so please understand my want for github to be tidy.

We aren't a democracy. Why didn't you contact me?

**Comment by hugmeorelse** [comment]
@Gandalf2k15 commented and tagged the wrong PR.

This is an easy call to make here. It seems like I was not alerted in a timely manner.

Merged.

**Comment by hugmeorelse** [comment]
> > "cripple the station"
> > It spawns two broodmother spiders, the same as the old spawn spiders event.
> > In order to do this you need to be fairly deep into xenobio, to make sure it can't be done right at the start of the shift.
> > They aren't that powerful, this sounds like it more of an issue with people not dealing with them at all, and letting it get out of hand, because spiders have some pretty major weaknesses.
> > EDIT: You also don't get to play as them or anything, so you have to count on their being a decent number of willing ghosts if you want to see any real effect from it.
> 
> Skyrat currently has 92 players playing. Only 54 are actually on the crew manifest. That leaves 38 either in the lobby or observing. That's 41% of players. Out of those 38 players observing, how many do you think are willing to play a yolo ghost role with basically no rules on escalation and can always respawn as a new spider?
> 
> You will have enough spiders. And the thing is that security doesn't usually sweep maint when the spiders are finally spawned in, so they're going to have a lot of time to lay eggs. You'll have an army of spiders in about 5 minutes ready to target the shuttle because that's meta.

That's bad math, since you're forgetting ghost roles play a big role in the server. We almost never have only 59% of the players playing. It is usually 70% to 80%. It never gets below that once the round gets going, because inactive players get disconnected at round end and are usually not reconnected. I get your point on you just counting crew, but let's be correct too while making the point on top of that.

**Pull request merged**
