### PR TITLE
[Semi-Modular] Advanced Shuttles Revamp, and new Advanced Shuttles!

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
The advanced shuttles we have are nice, but, uh... their code is bad, their underlay is bad, and they're only half-implemented.

This should fix that.
<details>
<summary>Nanotrasen has commissioned the use of the NMC Phoenix (Mining), NMC Chimera (Public) and NMC Manticore (Large Mining) aboard their frontier stations!</summary>

image
image

</details>
<details>
<summary>The NLV Consign (Cargo) has seen some overhauls and been sent back to the station for use!</summary>
Its docked backwards in this picture, that is fixed I assure you.

image
</details>
<details>
<summary>The NMC Drudge (Labour) has also been newly commissioned for use as prisoner transport.</summary>

image
</details>

Thanks to @Arctaisia (Wehliz Supreme#8988 on discord) for all the sprites, they're custom-made or largely modified from Eris sprites. Technically they were meant to wait until #7982, but I'd rather see 'em here before then, for consistency.
<hr>
<details><summary>**Code and smaller changes are in this dropdown!**</summary>

- Most map's .json has the cargo shuttle changed. This needed to be done individually because Delta has a unique one.
- Most _skyrat maps' docking ports are changed to spawn the new shuttles at roundstart instead. The .readme has been updated to account for this.
- Moved the _skyrat CC's ERT docking marker down one so it actually lines up.
- **Non-modular:** `/obj/docking_port/mobile/supply/proc/sell()` has been modified to not sell anything in the cargo shuttle's "cockpit" area. The door remains unlocked in case stuff spawns in there, but nothing inside will be sold.
- Code/icon cleanup for ship lockers; now there's base types and color variants, rather than unique ones per-shuttle. Also makes it easier to tweak/add new ones in the future.
- Slightly re-organizes the shuttle area file along with the new area additions
- Downgrades the internals tanks in the arrivals shuttle's O2 lockers; they were higher quality than even engineers get without paying, and thus were stolen roundstart without fail. Also removes the seclite from the trash, because again, its just loot to rush for.
- Engine vent counts as wall-mounted now, so it can actually see more use
- Wall closets cant fit humans, but still fit smaller animals
- Condensed all the shuttle turf code into a single file, as most of it was just changing filepaths and iconstates anyways
- Also fixes the rockplanet dock not being correct because no one cares about rockplanet enough to do it in a seperate PR. Plus all random mining is disabled anyways, so its more just to let people test without that error.
 
</details>
<hr>

**TO-DO:** FIX UNDERLAYS
**TO-DO:** LOOK INTO REPAIRS (RCD method?)(WILL NOT BE IN THIS PR)

## How This Contributes To The Skyrat Roleplay Experience
Half-done things are never fun and stick out like a sore thumb. Only having pods, the Relay, and an evac shuttle made them seem out of place. Not to mention, they were buggy, and code-wise they werent fun to read.
Rather than remove them all, which I'm fairly sure would be denied, why not make it a consistent thing?

## Changelog

:cl: Orion_the_Fox, Arctaisia (Sprites)
add: Added the NMC Phoenix, NMC Chimera, NMC Drudge, and NMC Manticore 'advanced shuttles' as new mining/labor shuttles
add: The NLV Consign (Cargo shuttle) has been retrofitted to match up to this standard, and returned to use aboard the station. Though, their manual piloting was, ah, damaged, and will not return.
balance: You can no longer hide in wall lockers. Sorry, but, uh, 'what? how?'. Small animals still fit, however.
balance: The NTV Relay (Arrivals shuttle) no longer starts with higher quality internals tanks than engineering, nor a seclite.
fix: The NAV Monarch (CC Ferry), NTV Relay, and evac shuttle now have floortiles that all match up with eachother. No more random uneven floors!
fix: The NAV Monarch now aligns with the CC dock, so both doors are usable.
fix: Wall closets can no longer fit humans. How it was possible, not even science can answer, but the demons that allowed it have been dispelled.
fix: Rockplanet now uses the correct landing dock ID for the public shuttle
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
CI fail is due to it not wanting to dock the ERT ship. Why? IDK, the dock code is a bunch of haha funny numbers to me, I didnt touch it I just moved the dock down one.

**Comment by Arctaisia** [comment]
Hh do make sure to also put down the eris spriters who sprited the basis of these shuttles,, I just resized, added, and readjusted (Except the labor shuttle/drudge and the largemining/manticore, that's all my doing)

Still, glad to have helped! <3

**Comment by thestubborn** [comment]
image
he touched shuttle code

**Comment by ghost** [comment]
> he touched shuttle code

but you see, I've come out on top, and a better coder for it >:)

**Comment by ghost** [comment]
I'm taking this off draft so the rest of it can be reviewed. God only knows how to fix the underlay though; hopefully someone who knows wtf is going on there comments as much

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by Gandalf2k15** [comment]
We'll fix the underlay bug in another PR, atmoisation and all.

**Comment by ghost** [comment]
> We'll fix the underlay bug in another PR, atmoisation and all.

thank god i hate that thing

**Pull request merged**
