### PR TITLE
Space hotel Tender loving Care (and more)

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

The depressing box in space is far less depressing now, each room having a unique layout and theme with one being aimed at the 'group' activities as well. I also nuked the solars that were oddly placed at the top right and moved them to the southeast, no more weird catwalk hugging the entire left and top side of the Hotel.

Room 1

<details>
<summary> Yellow - General use room with fancier carpet</summary>

image

</details>

Room 2

<details>
<summary> Pink - 'The observatory' with highlighted pink carpets and the best view in the hotel!.</summary>

image

</details>

Room 3

<details>
<summary> Teal - Broad with lots of room (For friends and more) for cuddles of course</summary>

image

</details>

Room 4

<details>
<summary> Green - CC 'Work' themed, Why should you stress out when you can work in peace?</summary>

image

</details>

Room 5

<details>
<summary> Orange - fairly generic lower 'tier' (RP price structure after all)</summary>

image

</details>

Room 6

<details>
<summary> Purple - Generally bland as well but with nicer carpet</summary>

image

</details>

Room 7!

<details>
<summary> Blue - New room completely! This is the Penthouse, with its own sauna and pool with individually functioning curtains to boot.</summary>

image

</details>

Managing office

<details>
<summary>Moved to where room (4?) was next to the main entry-space. The manager now has quite a bit more to deal with including making sure Fronk the Hotel's bat stays healthy.</summary>

image

</details>

Dock

<details>
<summary>A better dock! Moved to the south and better utilizes space provided to fit 2 Large ships</summary>

image

</details>

Lobby

<details>
<summary>An entirely new Lobby! Bolted doors to prevent early runners into the Hotel, </summary>

image

</details>

Engineering - Brig

<details>
<summary>The brig was removed as it was just a waste of space, all needed items were moved to the new staff room. Engineering now has a magical SMES after a few attempts at trying other variants didnt provide enough power, we dont want power to be the focus for the staff here. Finally, Comms! A comms relay has been placed here and defaults to off and can be turned on with a multi-tool.</summary>

image

</details>

Pool/Sauna

<details>
<summary>The large and completely open sauna is gone and instead replaced by 6 smaller private ones, the pool lost about half its size and is still rather large. You can see the Janitors closet here as well.</summary>

image

</details>

Staff room and Gift shop with medical storage

<details>
<summary>I arranged these in a way that makes sense from a business perspective, the break room for staff holds most of the spawners and gear for  all members including faction headsets. The row of vending machines were modernized for the new ones added for species flavor, the medical room was re-arranged into a walk-in. Cryo has it's own off-shot room.</summary>

image

</details>

## How This Contributes To The Skyrat Roleplay Experience

Originally my goal was to simply add curtains and this spiraled into an entirely new area of enhancements:

a 7th room
complete redesign of over half of all areas
A brand new door subtype modeled off the puzzle door, they can only be opened with the master key the manager has or the key assigned to that specific door. Borgs or AI cannot interact, they cannot be destroyed nor broken down or hacked in.
Key cards for each door plus a master
A new Permanent portal placer, useful here but also in other niche areas especially events
Magical SMES in engineering after giving up the power fight
Themed and colored room sploshes
My sanity
Front Desk now has a bolting function
A newly added gift shop with some random-spawn costumes (some rare ones may show up!)
Coffee pots! everyone gets coffee!
**FRONK!** The cutest bat in space

## Changelog
:cl:
qol: Space Hotel - remade all rooms, moved Solars and dock to the south and managers office next to the entry for the hotel rooms
qol: Space Hotel  - Many many many many changes to the overall look and feel, from carpets/walls/colors/rooms
qol: Space Hotel - Staff now have a bit more control over the 
fix: Space Hotel - fixed couch direction bug in lobby
fix: Space Hotel  - broken clothing/spawners and decals
add: Space Hotel - New keyed doors specially made for the hotel! No key? No Room!
add: Space Hotel - New Door Sprites/coloring and function
add: Space Hotel  - New Permanent Portal creator for the manager to place a static portal for easier transition from station to Hotel
qol: Space Hotel  - Many many many many changes to the overall look and feel, from carpets/walls/colors/rooms
add: 
/:cl:

### CODE REVIEW

**Review by Jolly-66 — COMMENTED** [review]
I looked at MDB and theres a dupe cob web up here.

image

**Comment by YakumoChen** [comment]
imo the penthouse should be larger? It's not even the largest room of the bunch, it's shaped oddly, and is only larger than the standard sized rooms by a few tiles.

Maybe give it a jacuzi or something

**Comment by Zergspower** [comment]
> imo the penthouse should be larger? It's not even the largest room of the bunch, it's shaped oddly, and is only larger than the standard sized rooms by a few tiles.
> 
> Maybe give it a jacuzi or something

I played around with a few things, and Room 1 is actually scaled down after Golden and I looked through it, all  the lewd stuff is closeted instead of just 'out' and it has a bathroom like the other rooms. Wasnt enough filler I felt but a hottub in the bathroom isnt a bad idea vs a shower

**Comment by YakumoChen** [comment]
The three-wide room actually feels a lot smaller than the four-wide standard rooms, even if the cubic area is technically larger, which is the main problem.

**Comment by YakumoChen** [comment]
Looking at it in game

New "kink" room
image

Observatory
image

"Penthouse"
image

The penthouse feels oddly like the least luxurious of the three. The room looks cramped, the space is used poorly, nothing about it makes it feel like the "best" room in the hotel. It has, I believe, the least actual space of the three non-standard rooms.

**Comment by Zergspower** [comment]
When I do the second pass i'll see about the penthouse - i did play around with adding a mini pool or jettub- I plan on shriinking down the pool/sauna areas into micro-private ones and can maybe even add that to the Penthouse

**Comment by savoryrex** [comment]
Might need a cryo pod or two, and perhaps a little costume vendor for some dress-up! Can't forget that. Otherwise this is really neat. :)

**Comment by Zergspower** [comment]
> Might need a cryo pod or two, and perhaps a little costume vendor for some dress-up! Can't forget that. Otherwise this is really neat. :)

Aye i podded in the costume vendor at the start so that'll get added - did overlook cryo !

**Comment by YakumoChen** [comment]
I recommended this in round but the SMES should be replace with the magic / bluespace SMES to prevent the hotel from becoming derelict. 

The manager spawning in their office would be a nice touch.

**Comment by Acer202** [comment]
Need some playing cards! Fun vendor? Carpet and wood in the engineering room might be a good idea for re-designs, too!

**Comment by Zergspower** [comment]
> 

actually thinking RTG's since Hotel gets raided often even with our policy

**Comment by YakumoChen** [comment]
magic SMES units can't be looted, they just revert to regular SMES boards. RTGs are pretty lootable themselves however, I don't recommend it.
(also it will break the immersion the solars are the main power source if you add RTGs)

**Comment by Zergspower** [comment]
> 

image
was more looking at an electrical closet that's just 'left alone'

**Comment by Zergspower** [comment]
> 

image

**Comment by Zergspower** [comment]
> Looking at it in game
> 
> 
> The penthouse feels oddly like the least luxurious of the three. The room looks cramped, the space is used poorly, nothing about it makes it feel like the "best" room in the hotel. It has, I believe, the least actual space of the three non-standard rooms.

image

**Comment by Zergspower** [comment]
Gave the pool personal lockers, 
Penthouse has a hot-tub and sauna, 
Engineering has a set-25Kw power-gain via RTG's, 
Front Desk shrunk 1 tile to give more space to walk, 
moved manager to their office, 
Front desk has windoors now,
Cryo Pods added with Console (Silent),
Fun! Vendor Added,
Clothesmate  Added,
Bar has 3 sets of each card game in their backroom,
Botany has the Floragun with their tool spawn,
N2 and O2 tanks now have their relevant Canisters spawn,
Actually HOOKED up the air tanks/Exhaust as they were just piped and never connected for some reason,
Added wrenches to each room to allow for 'toys' and small redesign,
Added crowbar to managers office incase of somehow it being out of power
Added Tiny Fans to Sauna(s) and all outward facing doorways - should be panicking to solf atmos issues


<details>
<summary></summary>


image

image

image

</details>

**Comment by LuckynDucky** [comment]
The restrooms next to the lobby do not have lights in them, made them a bit spooking going into. Also, the north door of the staff spawn room has the fire alarm in it.  Would be a good idea to move it.
You might want to replace the single sheets in the laundry room with doubles, would make swapping sheets easier.

**Comment by Zergspower** [comment]
> e

ooooh good catch on the sheets - also going to add a ghost-bardrone spawner

**Comment by Zergspower** [comment]
> 

We actually dont have a double sheet bin! Going to look into getting that added in - but going to merge this version as i'm happy where it's at right now and when I go to retouch the main area we'll hopefully have the sheets in by then

**Comment by Zergspower** [comment]
I'm happy with this first pass of the Hotel, later on i'll do the main areas but want to avoid waiting too long to where we'll start having integration issues

**Comment by Zergspower** [comment]
poke

**Comment by Zergspower** [comment]
image

**Comment by Zergspower** [comment]
I'd be good to test merge this for a few days to get community feedback

**Comment by FlamesWillLive** [comment]
it'd be nice if the hotel manager could select a spot, on the station and just... plop a portal there. Ideally, it'd work the exact same way the pizza portal from void raptor functions. walk into, or interact with it, to warp to the portal on the other side. no need to fiddle with recalibrating and people losing their legs. I'd like it to be easier for the crew to interact with it, without giving command an headache or extra work, and this seems like the easiest way.

If the hotel is also given a way to make announcements, say on a cooldown or a limited amount of them, it'd be pretty easy to both get people aware of their existence in-round and give them the realistic ability to visit, no matter the chaos level on the station.

**Comment by Zergspower** [comment]
image
7th room added at Lukasers idea

**Comment by Zergspower** [comment]
image
RTG's just weren't super viable without upgrades, removed the new room and replaced them with a magical SMES - shrunk the map size further and is now 59x68

**Comment by YakumoChen** [comment]
> image RTG's just weren't super viable without upgrades, removed the new room and replaced them with a magical SMES - shrunk the map size further and is now 59x68

I WARNED YOU ABOUT RTGS BRO
I TOLD YOU DAWG

**Comment by Zergspower** [comment]
> > image RTG's just weren't super viable without upgrades, removed the new room and replaced them with a magical SMES - shrunk the map size further and is now 59x68
> 
> I WARNED YOU ABOUT RTGS BRO I TOLD YOU DAWG

I liked the idea of power management - but it just wasnt working as they needed upgrades

**Review by Paxilmaniac — CHANGES_REQUESTED** [review]
You've got undefined types on the hotel somewhere
image

**Comment by Zergspower** [comment]
> You've got undefined types on the hotel somewhere image

Fucking headgear change... hnnng

**Review by Paxilmaniac — APPROVED** [review]
Mapping side seems fine, wait for those keycard doors to be done before anyone merges this though.

**Comment by YakumoChen** [comment]
update your PR body if you can

**Comment by Zergspower** [comment]
> update your PR body if you can

yeah good point since the rooms are basically done

**Comment by Zergspower** [comment]
> update your PR body if you can

Done finally - whew that list grew

**Comment by YakumoChen** [comment]
I almost want to nitpick that the relay isn't squared away in its own room but otherwise it looks very nice now.

**Comment by Zergspower** [comment]
> I almost want to nitpick that the relay isn't squared away in its own room but otherwise it looks very nice now.

I have an idea - but yeah i couldnt really fit that model there but i think i have a solution

**Comment by GoldenAlpharex** [comment]
I think it's been up for long enough, let's get it merged and we'll just fix anything that's left in another PR.

**Comment by Sigmar-alkahest** [comment]
minor thing, but the pamphlets for the hotel should really get some updated text to account for the changes.

**Pull request merged**
