### PR TITLE
Runs an organic preference through prettier because CI reasons

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request

~~code standards~~ (this is insanity on the who gives a shit level)

## How This Contributes To The Skyrat Roleplay Experience

we love CI working and not dying all the time

## Changelog

:cl:
code: run organic interface through prettier
:/cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
#14643?

**Comment by nevimer** [comment]
jumping out a window brb

**Comment by GoldenAlpharex** [comment]
"Close this because you merged mine"
- Jolly 2022

**Comment by Jolly-66** [comment]
`>:(`

I meant that in the way this accomplished the same thing

**Pull request closed without merging**
