### PR TITLE
[HOST][TM-ONLY AT FIRST] Disables Progression Traitors

### PR DESCRIPTION
**Pull request by Zonespace27**
## About The Pull Request
This PR disables prog traitors, reverting them to the regular 2 objectives + escape/die

In addition, makes traitors have 15 TC by default, earning an extra 25 on OPFOR approval.

## How This Contributes To The Skyrat Roleplay Experience
Host supported it, and it'll be interesting to see if this fixes any of the supposed issues that have been caused by progression traitors.

On the subject of the extra 5 TC: I think it won't be a massive amount of harm to give them an extra 5 TC *if* they fill out an OPFOR for an actual gimmick to do. Seeing as how you won't be able to earn large amounts of TC (as with prog traitors, without even needing to fill out an OPFOR), might as well see how this goes.

## Changelog

:cl:
del: Progression Traitors are now gone
balance: Traitors get 15 TC by default and earn 25 more on filling and getting an OPFOR application approved.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
I feel like we had a time back when traitors had more than 35 TC. Was a bit too ham.

**Comment by GoldenAlpharex** [comment]
I'd probably say make it 10 by default, to really drive home how discouraged it is.

**Comment by Gandalf2k15** [comment]
Make it 20 as default. Traitors can request more TC in OPFOR.

**Comment by hugmeorelse** [comment]
Let's keep it at the values I've put out. 

We'll adjust accordingly.

**Comment by MassacreDemigirl** [comment]
Cant they just ask for TC via opfor

**Comment by Iamgoofball** [comment]
terrible change, leave progression traitors in but disable the telecrystals for doing objectives, that's literally all you needed to do to fix prog traitors for skyrat

this is what i said to do before but nobody listened to me apparently

the opfor TC split is good tho

**Comment by TetrakoHateThis** [comment]
Hoping this one is still gonna be going through.

**Pull request closed without merging**
