### PR TITLE
[MOSTLY-MODULAR] Tarkon Overhaul: Defcon Levels [TM Ready]

### PR DESCRIPTION
**Pull request by Zenitheevee**
## About The Pull Request

This PR does a few things, The first and most important thing
It converts Tarkon into a ***MODULAR*** space ruin.
No- Not as in "Modular Skyrat", As in that it can change between rounds. Infact actually pretty much ALL of it is modular.
So, lets get INTO said modular tarkon, Measured in Defcon Alerts from 5 to 2.

<details>
  <summary>Tarkon Defcon 5: Celebration Overdose</summary>

```
Oh dear, Someone overdid it on the Miami Punch... Well, Clean up, Tarkonites, And maybe after another bottoms up... Preferably of Redeyes this time.
```
defcon5

Defcon 5 is, To put bluntly, A flavoured look of what the current Port Tarkon would look if it wasn't in a shitstorm of disaster. No broken windows, No spaced areas, No risk or threat. Survival guaranteed, But calm down on the drinks this time aye?

</details>

<details>
  <summary>Tarkon Defcon 4: Rude Awakening</summary>

  ```
 Y'there, Ensign? Get the miner and engineer to work, A rogue space rock crashed into the side of the port. We expect working conditions by the end of the day.
  ```
defcon4

Not Entirely safe, This Defcon is testing how fast the crew can get it back up to working condition. With the mild threat of carp being infesting the now spaced areas, The biggest threat might just be the lack of air. Survival likely, But there's always a chance of it going sour. Now get back to work, Those walls wont build themselves.
</details>

<details>
  <summary>Tarkon Defcon 3: Xenos Infestation</summary>

  ```
 Hey, Survivor, Wake the FUCK UP Survivor. You got Company, And chances are they might not be friendly. I dont know how the FUCK it happened, but FIX IT.
  ```

defcon3

This is the Port Tarkon that everyone knows. Just like Charlie, It has aliens, guns, and fun. Survival Possible, Just dont miss.

</details>

<details>
  <summary>Tarkon Defcon 2: Dead Signal</summary>

  ```
 . . . c a n   y o u   h e a r   t h e   m u s i c ?  T h e   s c r e a m s . . . T h e   c r i e s . . . I t ' s   s o   c a l m i n g . . .
  ```

defcon2

Right. This one requires some... Explaining.
This is the testing point of Tarkon. What can and cant be done. A test to use _EVERYTHING_ at one's disposal, This one relies on planning, and potentially hired help. Survival Probable for the heartiest of players, With the reward being said survival. Chances are, You wont clean up the station, and thats OK. Suggestion? Haul ass to the shuttle. 

</details>

"ok whats with that "Mostly Modular" thing though?"
Well
Modular ruins like this need a TOML file. and well, not knowing quite where to put it i just kinda put it with the rest of them. Shouldn't be a big problem right? 

oh, Also finally relocates the Tarkon Driver shuttle to where it should be. No one told me to fix it yet so i just kinda did it there.

## How This Contributes To The Skyrat Roleplay Experience

Puts inconsistencies in Tarkon, Just enough in hopes to break the monotony of playing original tarkon every round. Also creates a few scenarios to open up more interaction with the main station at large.

## Changelog

:cl:
add: Adds 3 new variations to Tarkon, Now randomly spawning over it
add: Adds a few more papers to Tarkon, mostly for ingame defcon alerts
balance: Gives the cultist mobs "Cult" faction instead of "Cultist".
/:cl:

### CODE REVIEW

**Review by tf-4 — CHANGES_REQUESTED** [review]
~put the `.toml` in `modular_skyrat/modules/mapping` somewhere. Probably something like `modular_skyrat/modules/mapping/code/modular_maps/PortTarkon.toml` would be good.~

**Comment by Zenitheevee** [comment]
> put the `.toml` in `modular_skyrat/modules/mapping` somewhere. Probably something like `modular_skyrat/modules/mapping/code/modular_maps/PortTarkon.toml` would be good.

Moved and tested to make sure stuff works.
Stuff works, Full send.

**Comment by Zenitheevee** [comment]
wh-
Ok i swear it worked on local test one second

**Comment by Zenitheevee** [comment]
Ok
Its gonna have to be how it is unless yall wanna deal with CI Failing because of some unit test that... Probably is designed to check if the config file is put *in the config file folder*

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
