### PR TITLE
[Semi-Modular] Stops female lizard's chests poking out of female fitted uniforms

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request
Self explanatory, an absolutely tiny thing but i've noticed this for a long time now and it fucking bothers me to no end.

Fixed:
image

Current:
image

## How This Contributes To The Skyrat Roleplay Experience

An absolutely tiny thing that doesn't affect any other species other than lizards. I'd rather get this fixed than have it linger forever.

## Changelog

:cl:
fix: Lizard's chests no longer poke through the front of their jumpskirts
/:cl:

### CODE REVIEW

**Review by Gandalf2k15 — CHANGES_REQUESTED** [review]
We do not support non-modular icon changes.

**Comment by Ebin-Halcyon** [comment]
ghgughuh doesn't work without the changes.

**Comment by nikothedude** [comment]
You could just like, make a check for if the species is lizard, and if yes, use an alternate dmi for the sprites. That's what taurs do for suits and jumpsuits, although that checks DNA.

**Comment by Ebin-Halcyon** [comment]
I am sadly not smart enough for that.

**Pull request closed without merging**
