### PR TITLE
[NONMODULAR][A DIRECT BORG BUFF]Mining cyborgs now have crushie back

### PR DESCRIPTION
**Pull request by Vizoplez**
## About The Pull Request
Because I missed you, crumshie

## Why It's Good For The Game
PKA sucks

## Changelog
:cl:
add: mining cyborg crusher makes me go :)
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
-1 I don't see why we need to be buffing bogs even more.

**Comment by Vizoplez** [comment]
> -1 I don't see why we need to be buffing bogs even more.

Borgs have been directly hard-nerfed when it comes to mining even more

**Comment by tf-4** [comment]
+1 mining borgs suck dick

**Comment by SpaceVampire** [comment]
-1
I'm pretty sure the main point of mining cyborgs.
Is to go mining, in the case that the station is really lacking resources.
_Or killing the blob, they are pretty good at that as well._
Just don't think they need to be hunting down megafauna.
I'm also not sure if all the crusher trophies would even work correctly with them?

**Comment by tf-4** [comment]
> -1
> I'm pretty sure the main point of mining cyborgs.
> Is to go mining, in the case that the station is really lacking resources.
> _Or killing the blob, they are pretty good at that as well._
> Just don't think they need to be hunting down megafauna.
> I'm also not sure if all the crusher trophies would even work correctly with them?

You could say all that about regular miners, apart from the trophies bit

**Comment by Vizoplez** [comment]
> -1
> I'm pretty sure the main point of mining cyborgs.
> Is to go mining, in the case that the station is really lacking resources.
> _Or killing the blob, they are pretty good at that as well._
> Just don't think they need to be hunting down megafauna.
> I'm also not sure if all the crusher trophies would even work correctly with them?

You aren't a head admin

**Comment by Vizoplez** [comment]
> -1
> I'm pretty sure the main point of mining cyborgs.
> Is to go mining, in the case that the station is really lacking resources.
> _Or killing the blob, they are pretty good at that as well._
> Just don't think they need to be hunting down megafauna.
> I'm also not sure if all the crusher trophies would even work correctly with them?

Also, certain trophies not working for them is intentional, but a majority do.

**Comment by SpaceVampire** [comment]
> You aren't a head admin

I channel the will of the people in my votes.
> Also, certain trophies not working for them is intentional, but a majority do.

I mean, given that on TG you can't use the Crusher at all. I am not sure if intentional is the correct choice of words.
If you just have some that work at random and some that don't, that just feels pretty fucky.
>You could say all that about regular miners, apart from the trophies bit

I mean, I view hunting fauna to be a major part of regular mining.
It would be like saying the job of science is only to stand around and click the unlock tech button.
There is only so much boss killing content in any given shift, I don't think cyborgs really should be competing for it.
The crusher is also a pretty strong melee weapon, just in terms of general use.

**Comment by Vizoplez** [comment]
> > You aren't a head admin
> 
> I channel the will of the people in my votes.
> 
> > Also, certain trophies not working for them is intentional, but a majority do.
> 
> I mean, given that on TG you can't use the Crusher at all. I am not sure if intentional is the correct choice of words.
> If you just have some that work at random and some that don't, that just feels pretty fucky.
> 
> > You could say all that about regular miners, apart from the trophies bit
> 
> I mean, I view hunting fauna to be a major part of regular mining.
> It would be like saying the job of science is only to stand around and click the unlock tech button.
> There is only so much boss killing content in any given shift, I don't think cyborgs really should be competing for it.
> The crusher is also a pretty strong melee weapon, just in terms of general use.

a majority of the useful crusher trophies aren't even from megafauna, borgs suck against megafauna and basically instantly die against them.

**Comment by Trubbl3** [comment]
>a majority of the useful crusher trophies aren't even from megafauna, borgs suck against megafauna and basically instantly die against them.

Why would you use a borg to go for megafauna?

**Comment by CloverIsLucky** [comment]
+1
I was waiting for this... Finally! Fuck the accelerator! Wait, have you tested if the borg can attach trophies themselves?

**Comment by CloverIsLucky** [comment]
> 
> 
> > a majority of the useful crusher trophies aren't even from megafauna, borgs suck against megafauna and basically instantly die against them.
> 
> Why would you use a borg to go for megafauna?

You don't need to fight megafaunas as a minerborg unless if you're needed to fight them if they are a hazard for the mining station or for the entire crew.

As for the addition of the crusher, I have a great expectation at this PR: 

The kinetic crusher isn't limited just for fight megafaunas, aside of that, if this PR gets merged, the minerborgs will finally have a better tool for self-defense in the Asteroid Map, where the mining map is pressurized and the KA is nauseatingly bad. They also will finally butcher watchers for get diamonds. I hate Asteroid and a crusher for the cyborg's arsenal in such a horrendous place to mine would be great <3

**Comment by SpaceVampire** [comment]
> The kinetic crusher isn't limited just for fight megafaunas, aside of that, if this PR gets merged, the minerborgs will finally have a better tool for self-defense in the Asteroid Map, where the mining map is pressurized and the KA is nauseatingly bad. They also will finally butcher watchers for get diamonds. I hate Asteroid and a crusher for the cyborg's arsenal in such a horrendous place to mine would be great <3

Rockplanet has awful design and shouldn't have been pushed as "main" map in the current state, but the issue created by it should hopefully be fixed with this https://github.com/Skyrat-SS13/Skyrat-tg/pull/6256 (This one is big, just wait for it.... Rocks no longer suck away all your air. Amazing, right?
The reason the last one is important is that, all the air here is fixed (hopefully). Low-pressure means mining tools do full damage, and that mobs aren't so terribly strong any more! ) As for your second point, you can ALREADY butcher watcher as a mining cyborg, just use the shovel that you come with. It has the component for it.

**Comment by Reco201** [comment]
> > The kinetic crusher isn't limited just for fight megafaunas, aside of that, if this PR gets merged, the minerborgs will finally have a better tool for self-defense in the Asteroid Map, where the mining map is pressurized and the KA is nauseatingly bad. They also will finally butcher watchers for get diamonds. I hate Asteroid and a crusher for the cyborg's arsenal in such a horrendous place to mine would be great <3
> 
> Rockplanet has awful design and shouldn't have been pushed as "main" map in the current state, but the issue created by it should hopefully be fixed with this #6256 (This one is big, just wait for it.... Rocks no longer suck away all your air. Amazing, right?
> The reason the last one is important is that, all the air here is fixed (hopefully). Low-pressure means mining tools do full damage, and that mobs aren't so terribly strong any more! ) As for your second point, you can ALREADY butcher watcher as a mining cyborg, just use the shovel that you come with. It has the component for it.

You lose the shovel on upgrade to the diamond mining drill.

**Comment by CloverIsLucky** [comment]
> 
> 
> > The kinetic crusher isn't limited just for fight megafaunas, aside of that, if this PR gets merged, the minerborgs will finally have a better tool for self-defense in the Asteroid Map, where the mining map is pressurized and the KA is nauseatingly bad. They also will finally butcher watchers for get diamonds. I hate Asteroid and a crusher for the cyborg's arsenal in such a horrendous place to mine would be great <3
> 
> Rockplanet has awful design and shouldn't have been pushed as "main" map in the current state, but the issue created by it should hopefully be fixed with this #6256 (This one is big, just wait for it.... Rocks no longer suck away all your air. Amazing, right?
> The reason the last one is important is that, all the air here is fixed (hopefully). Low-pressure means mining tools do full damage, and that mobs aren't so terribly strong any more! ) As for your second point, you can ALREADY butcher watcher as a mining cyborg, just use the shovel that you come with. It has the component for it.

Haha, no dude, stop finding an excuse to complaint and whin about why borgs shouldn't have their crusher back. 

The shovel can butcher, yes, but you get very little loot for it for doing it than using the survival knife or the crusher to butcher creatures and doesn't worth doing it. And as @Reco201 said, you lose the shovel on upgrade to diamond drill.

Also I hope the rockplanet revamp unfucks the problems with the current one.

**Comment by hugmeorelse** [comment]
@SpaceVampire Irrelevant comment. As staff, we should avoid that.

**Comment by Swiftfeather** [comment]
-1 I hate borgs

**Pull request closed without merging**
