### PR TITLE
Blueshift barbershop update (this time for reals edition) (hopefully)

### PR DESCRIPTION
**Pull request by IsaacTheSharkWolf**
## About The Pull Request

Adds the barbershop location to blueshift, as well as reducing the ammount of maints objects for performance and fixing the whole airlock ordeal (hopefully)

## How This Contributes To The Skyrat Roleplay Experience

Most importantly it gives the barber role a proper location to do their job, secondly it should improve map performance ever so slightly.

## Changelog

:cl:
add: Barbershop with spa and tattoo/piercing workshop.
del: A bunch of maint objects to save on performance
fix: Fixed the whole airlock space_dir vars issue thingymajig (hopefully)
/:cl:

### CODE REVIEW

**Comment by IsaacTheSharkWolf** [comment]
here's hoping it actually works this time

**Comment by ORCACommander** [comment]
@GoldenAlpharex & @Gandalf2k15 Full CI Pass

**Comment by GoldenAlpharex** [comment]
Drafting pending a little rework of the upstairs portion of the barber shop.

**Comment by IsaacTheSharkWolf** [comment]
> Drafting pending a little rework of the upstairs portion of the barber shop.

I'll fix up the pool thing sometime later, right now i just need this merged so barbers can actually play on my station

**Comment by IsaacTheSharkWolf** [comment]
NSS blueshift366
Since the tag says i need images, here's the images related to visible content i added, this being floor 1 of the barbershop, having the barber part and a piercing/tattoo workshop (as these features are likely to be added later by gandalf)
It is currently located in the mall area to the left on level 2.
NSS blueshift367
This is the spa section of the blueshift barbershop, likely to be changed a bit in the future but it'll do for now.
This is located on level 3 right to the bottom left of dorms.

**Pull request merged**
