### PR TITLE
Catwalk Tiles REVAMPED!

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Resprites, Re-paths, and adds new catwalk tiles, made specially to blend with a few other tiles!
image
Left to right: Base TG, Plating(base), iron, white iron, dark, flat white, titanium

All these catwalks are now available by radial-reskinning the TG one (made from rods); originally the two we had were only able to be placed in mapping. For some reason.

<details><summary>**Technical Note**</summary>

Due to the usual TG 'hardcoding moment', `/turf/open/floor/catwalk_floor/update_overlays()` has been commented out and is overwritten in our catwalk file.
</details>

~~**To-Do**: Clear the shadow/occlusion from the overlay. Somehow.~~ Involves layer stuff; upstream also has the shadows anyways, so any changes they make I'll make to these.
Speaking of, upstream ALSO has a bug in which these are basically glorified floortiles, and you cant actually see the pipes below them. So thats fun. Not for this PR though; fix PR'd upstream.

## How This Contributes To The Skyrat Roleplay Experience
Better blending catwalks than what we previously had, plus a few more. Also, now they're actually player-accessible.

## Changelog

:cl: SolGov Engineering Safety Association (SESA)
expansion: SolGov and NT both acknowledge the dangers of typical station maintenance shafts, including exposed wiring and piping. While they can't manually improve every single station, they've supplied Engineering staff with a solution: improvements to the Catwalk Tiles they created previously. Now, you can reskin it into an assortment of ones more fitting to your projects! (Craft with rods, then use in-hand to get the reskin radial menu)
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Also, none of the original filepaths were changed! So no map conflicts, but blueshift miiiight have a few weird looking things. Dark ones will look fine but the previously half-iron-half-white plates will be the Maint variant now

I'm sure if/when this is merged, the map author will have a field day tho anyways

**Comment by ghost** [comment]
actually gonna hold on this until I get an upstream fix merged

**Comment by OrionTheFox** [comment]
time to re-open it already, and just pre-emptively do the changes from my upstream fix >:)

**Comment by ghost** [comment]
hghnbgh I'll just leave it as a comment here bc i'm sure upstream will merge my simple fix fairly fast

**DNM UNTIL the eventual mirror of <https://github.com/tgstation/tgstation/pull/62988> "Fixes Catwalk Tiles"**

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by tralezab** [comment]
@OrionTheFox hellooooooo you should bring this upstream! we'd love it ;))))

**Comment by ghost** [comment]
> @OrionTheFox hellooooooo you should bring this upstream! we'd love it ;))))

i was scared of this
uh
so
upstream has the overlay as static

**Comment by ghost** [comment]
and frankly
i'm scared of upstream maintainers because i'm a shitty coder lmao
so if i changed the code up there then they'd critique it to a level that i'm not used to YET
@tralezab

**Comment by GoldenAlpharex** [comment]
> and frankly i'm scared of upstream maintainers because i'm a shitty coder lmao so if i changed the code up there then they'd critique it to a level that i'm not used to YET @tralezab

He's a maintainer upstream, Orion. ;)

**Comment by GoldenAlpharex** [comment]
And they're not *that* scary.

**Comment by ghost** [comment]
wh a

**Comment by ghost** [comment]
either way it has to wait for the overlay fix to go thru, so

**Comment by ghost** [comment]
also leaving a note to myself here, a based CE and I had the idea that maybe floorbots could automatically place catwalks in maintinence areas 😳

**Comment by ghost** [comment]
gonna leave this as a draft until I decide on doing it upstream or not

**Comment by ghost** [comment]
https://github.com/tgstation/tgstation/pull/63016 taken upstream

**Pull request closed without merging**
