### PR TITLE
feat: Respawn delay!

### PR DESCRIPTION
**Pull request by larentoun**
## About The Pull Request

Adds respawn delay. Disabled by default in the config.

## How This Contributes To The Skyrat Roleplay Experience

Sometimes, rules are not enough to stop meta-gaming and respawning immediately to harass their killer, or just starting the round as observer to look for antags and joining in.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image
image

</details>

## Changelog

:cl:
add: Respawn Delay (to lobby). Disabled by default.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Take it upstream

**Comment by TheGandalf85** [comment]
This might be a good contender for upstream, yeah. There shouldn't be any reason it can't merge with upstream. If for some reason it does have a reason, then bringing it here is good.

**Comment by Higgin** [comment]
good for upstream but also good for here, can it also be applied to midround spawns

**Comment by larentoun** [comment]
> good for upstream but also good for here, can it also be applied to midround spawns

It could be applied for them by checking death timer

**Pull request closed without merging**
