### PR TITLE
[READY] Resprites shark/fish tail and adds smoother wagging animations for them

### PR DESCRIPTION
**Pull request by Draganfrukts**
## About The Pull Request

Does what it says on the tin.

## Why It's Good For The Game

Current shark tail sprites look !!yucky!!

## Changelog
:cl:
imageadd: Resprited Shark, Shark no fin and Fish tails.
imageadd: Resprited marine tail hardsuit overlay.
/:cl:

## Credit

I grabbed the initial sprites from https://github.com/sojourn-13/sojourn-station and tweaked them.
I'm unsure where the original sprites come from, or if they're from there.
If you know who the original spriter is, let me know and I'll change it ASAP.

## Media

https://i.gyazo.com/691af64693320f52595e3a98c174eabd.mp4
https://i.gyazo.com/179a986af80357b1abc8502d501aecf7.mp4

(Gyazo is low quality and jank, but you get the point)

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
convince me these are real, then maybe

**Comment by Draganfrukts** [comment]
> 
> 
> convince me these are real, then maybe

sorry @RatFromTheJungle but you need to put on the nightmare vision goggles

**Comment by KasparoVy** [comment]
@Investigator77 Can we please get a side-by-side comparison & in-game pics?

New sharp sprites look great but I'm a huge fan of the existing Fish tail sprites, looking at the icon diff bot I'm concerned and would **love if the original fish tail sprites as an alternate version**

Looking at the wagging animation from IconDiffBot and in .dmm I'm concerned because it seems designed to rely on ping-ponging (reaches end of anim then reverses, and so on and so forth) so it's quite choppy

The Fish tail is just the shark minus the fin, and loses nearly all characteristics that made it appealing

This is what the fish tail looked like before. Looking at the new version, not only is it a copy-paste of the shark no-fin sprites, but it loses all characteristics that made it different and appealing. See further below.
image

Shark no-fin sprites are the exact same
image

**Please leave the original fish tail sprites as an alternate version**

**Comment by KasparoVy** [comment]
The new shark tail sprite is badass and the wagging is sick, but would love to hold onto the OG fish tail sprite and have the issues addressed/tested

Hopefully it's just me being dumb about the wagging and it in fact works fine ingame, if so -- sorry for the nag

**Comment by Draganfrukts** [comment]
> 
> 
> The new shark tail sprite is badass and the wagging is sick, but would love to hold onto the OG fish tail sprite and have the issues addressed/tested
> 
> Hopefully it's just me being dumb about the wagging and it in fact works fine ingame, if so -- sorry for the nag

I'll make sure to add unique fish tail sprites. Consider it like, right by tomorrow if not earlier. Also, animated states are almost entirely dependant on the client and not the server so it will play out fine, think of how the new felinid wagging tail is.

**Comment by Draganfrukts** [comment]
I also specifically remember giving fish a unique variant but I probably overrid it in my spree of being fucking stupid

**Pull request merged**
