### PR TITLE
[MIRROR] Moves the new HoS winter trenchcoat from the wintercoat file into the proper armor file [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/70014
--------------------

## About The Pull Request
The last security resprite reworked the HoS wintercoat into a subtype of their armored trenchcoat, basically removing the original HoS wintercoat from the game but still left the icon and code of the new trenchcoat inside the old files.

Since I had done multiple clean ups around the wintercoat files I was not going to let it sit there and be confusing, so I moved them into the default armor file together with the base trenchcoat.

Also, ABC'd some lists while I was touching the winter coat file.

## Why It's Good For The Game
Cleaner code with less confusion and maybe avoid some future issues with the winter trenchcoat unsycing from it's base armored trenchcoat because it is on a different file.

## Changelog
Not player facing

### CODE REVIEW

**Comment by ghost** [comment]
TG 'keep everything to one PR' challenge

DNM until the sec resprite mirror is in

**Review by GoldenAlpharex — APPROVED** [review]
Should be good to go now!

**Comment by ghost** [comment]
~~Lemme doublecheck this tonight before merging it, wanna make sure digi compatiablity is there if possible and that we dont somehow override the icon somewhere~~

**Comment by ghost** [comment]
Looks good, but to prevent issues with digi, before merge can someone with perms please add the following to `modular_skyrat\master_files\code\modules\clothing\clothing_variation_overrides\suit.dm`
```nix
/obj/item/clothing/suit/armor/hos/trenchcoat/winter
	supports_variations_flags = CLOTHING_DIGITIGRADE_VARIATION_NO_NEW_ICON
```

**Comment by Tastyfish** [comment]
> Looks good, but to prevent issues with digi, before merge can someone with perms please add the following to `modular_skyrat\master_files\code\modules\clothing\clothing_variation_overrides\suit.dm`
> 
> ```nix
> /obj/item/clothing/suit/armor/hos/trenchcoat/winter
> 	supports_variations_flags = CLOTHING_DIGITIGRADE_VARIATION_NO_NEW_ICON
> ```

Done.

**Pull request merged**
