### PR TITLE
[MIRROR] Updates Lizard Sprites & New Digitigrade Sprites [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/74549
--------------------
## About The Pull Request
Hi.
This pr contains work that is a  collaborative effort between myself, Halcyon, Mqiib and `2cents#8442` for the original leg-work (Ha Ha, Get it?), ultimately finished by myself.

Here's a preview!

image

And here's some side previews!

image

## Why It's Good For The Game

Lizard sprites have not been updated since their inception in 2016. They will now be updated and be much more consistent with everything else.

Signed off by @ optimumtact

## Changelog
:cl:
imageadd: Lizards have been resprited, as well as Digitigrade sprites. Please remember to update your colors to account for this. (Note: This does not affect Skyrat digitigrade options, since all of our sprites are modular. This change should therefore be inconsequential here.)
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
THE LIZARD THIGHS ARE REAAAAAL

**Comment by Zonespace27** [comment]
(aside from the change we need to do in the commented out code) I don't trust that this won't break anything, so I'd like a TM first, juuuust in case.

**Comment by Jolly-66** [comment]
Finally
Lizard players eating good

**Comment by thgvr** [comment]
The `mutants.dm` edit is because tg's color clamping or whatever that stops you from going below a certain value for your colors, and the bases are brighter so I had to adjust it a bit. Not sure that's an issue here.

**Comment by Ebin-Halcyon** [comment]
For the love of fucking god, don't speed merge this gandalf, I will fucking kill you. Genuinely.

**Comment by Ebin-Halcyon** [comment]
Hopium FLOWS through me.

**Comment by Ebin-Halcyon** [comment]
God.

**Comment by thgvr** [comment]
Keep on keepin' on.

**Comment by Ebin-Halcyon** [comment]
> Keep on keepin' on.

It's hard.

**Comment by Ebin-Halcyon** [comment]
It's so over.

**Comment by Z0w0plankton** [comment]
I've  noticed that the leg sprites for synthetics are different vs organics. The seperation between the legs for synthetics seems jarring. Here's some images from the same character being organic vs synthetic. 
afbeelding
afbeelding

**Comment by gummardgumphrey** [comment]
Gradient markings for digi aren't yet adjusted for the new sprites, which'll probably affect a lot of people's characters.

image

In addition, certain socks aren't sprited for digi either. (i.e., the "greyscale" line of socks, as well as other striped knee-high socks).

image

image

image

**Comment by sergeirocks100** [comment]
The sandals don't have updated sprites.

Also, the sprite for the shorts has strange chunks missing out of the waistband.

Screenshot_79

**Comment by CliffracerX** [comment]
Synth scutes are missing.
image
Synth pecs are missing.
image

Default lizardfolk have no marking patterns available at all, ditto for Unathi and Ashwalkers.
image

**Comment by Ebin-Halcyon** [comment]
>123Neok

Arcane synthetic code doesn't let me do anything, a leg marking to remedy it will be added.

> Gumphrey

Anything with markings on the legs are to be converted at a later date. Same with socks.

> Sergei

To be converted at a later date for the shoes.
Shorts apparently slipped out from under my radar when redoing them. I'll fix it in another commit.

>Cliffracer

Scutes were removed with the new way to make a Synth with the base underbody being the main and the synth plating markings being what you color seperately on each limb. It'll probably be readded in another commit later down the line.

Unrelated issue, it's been like this for awhile.

**Comment by Ebin-Halcyon** [comment]
And leaving this here for posterity cause no one looks in the spriting channel to get the tutorial and will come here to report the same thing over and over.

The 'Synth Scutes' marking was removed in favor of the 'synth plating' markings set.

Synthetic lizards work like this now:
your chassis color is the 'under plating' layer, your base color that is shown under all the overplating.

image

The Synth plating markings you select from the augments menu is what you use to 'color' the over plating of your synth.

image

For example with this Synth I selected a deep burgundy red for the chassis color and a bright blood red for the synth platings marking, which ends up like this.

image

This is what a 'base synth' would look like with nothing but the synth plating markings.

Beyond that, it's up to your imagination to change it.

**Comment by gummardgumphrey** [comment]
Posting this, though this may just be a personal opinion, I think some people may agree that..

The leporid snout from the front-view before the respritening was a lot more clean, the mouth pixel was a lot more subtle and less pronounced.

image

But now it looks kinda dodgy and weirdly shaded; the mouth pixel looks more like a mustache now if anything.

image

**Comment by Zergspower** [comment]
> Synth marking tutorial, snip.

issue here is the most commonly used chest marking is missing, and no chest mark seems to be able to override the base chassis now - so it's hardlocking synths to be this default rather than letting us do anything

image

**Comment by Jolly-66** [comment]
Guys if you're gonna quote someone who has a long message pleases condense it.

**Comment by Ebin-Halcyon** [comment]
>Zergspower

Addressed in another comment.

>Scutes were removed with the new way to make a Synth with the base underbody being the main and the synth plating markings being what you color seperately on each limb. It'll probably be readded in another commit later down the line.

**Comment by Fairdan** [comment]
The Otie body markings are mostly busted, outside of the arms.
Side note: the body sprites are bit odd, the shading seems to be a bit overboard compared to the newer human sprites.
image

**Comment by Ebin-Halcyon** [comment]
>Fairdan

Not sure why that's happening, I haven't touched that. Most likely caused by the species refactor stuff going on besides this PR.
image

image

image

**Comment by Ebin-Halcyon** [comment]
Alright show's over, 3 months of my life down the drain for nothing.

**Comment by desertmote** [comment]
> Alright show's over, 3 months of my life down the drain for nothing.

?

**Review by GoldenAlpharex — APPROVED** [review]
Should be good to go as a pure mirror PR.

**Pull request merged**
