### PR TITLE
[MIRROR] Overlays for notifying when radios are on broadcast [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/71006
--------------------

## About The Pull Request
Adds overlays for when the radios are on broadcast snd speaker

Theres 4 overlay settings, an "idle" (broadcasting or speaker enabled) and "active" (flicked when recieving or sending a radio msg)

### SBR
The base icon is the screen being off, and the bars are seperated into ovelays with the top one being broadcasting. The idle overlay displays the bar short, while the active will make the bars animate like the current animation)

having both off will make the antenna go down since its "not being used"

### Intercoms
Intercoms are simpler, just having lights on the speaker flash green if the corresponding mode is active

### Headsets
Headsets are unaffected because of the small sprites.

except miner and explo headsets where the antenna will go down if both are disabled bc its "not being used"

## Why It's Good For The Game
Helps you tell whether somone (like ai) is spying, makes it easier to notice whether youee in broadcasting range of an intercom, and its a cool immersion thing to ""see"" the mic readings on a sbr
## Changelog
:cl:
add: radios have overlays for showing broadcasting settings
/:cl:

### CODE REVIEW

**Comment by Tastyfish** [comment]
Requires our custom radio sprites to get new overlays.

**Review by Tastyfish — APPROVED** [review]
Approving code. I made overlays for the intercom states as such

image

**Comment by Tastyfish** [comment]
Oh and I removed 2 cruft icon states in the blueshield headset dmi that are unused.

**Review by GoldenAlpharex — APPROVED** [review]
Nice!

**Pull request merged**
