### PR TITLE
Void Raptor - AI Sat Power isolation and fixes to the mini-powernet - removes the alien blob of a building above chapel

### LINKED ISSUE #18251: Voidraptor AI Sat Power Issues
## Testmerges:

None

## Reproduction:

The AI can be killed on voidraptor by smashing a single glass window. 
dreamseeker_4PhuHfsJr2
This glass window here will put you into a tube to the AI sat, where you will see an SMES.
StrongDMM_kNnqUdX2i6

StrongDMM_r4gn2slxxL
This SMES here, powers everything by default on the AI sat, including the AI itself. One only had to discretely turn off the output and wait two minutes for the AI to die, due to a wiring issue further south. The placement itself is bad, but, it's further compounded by this issue.
StrongDMM_8EycKUxOIX

The AI's own SMES is connected it ITSELF, acting as a power sink if you have no idea how wirenets or powernets work (and believe me, nobody fucking knows unless you are coder brain, it is very obtuse.)

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

fixes: https://github.com/Skyrat-SS13/Skyrat-tg/issues/18251

Looking at the map after seeing the issue listed above it kind of clicked that the VR Sat has both a direct powerline on top of their own power generation. Falling in line with maps that have the AI with solars i've isolated it from the station grid and removed the entryway SMES, i also fixed the wiring so all the AI has to do is turn solars on similar to how they do in Tramstation.

Old
image

New
image

a side request to give the pacman a wire under it so i just swapped it with the cell charger as well
image

Addon:
Somehow a WIP slipped through and appeared in todays version, so i added it as a removal
image

## How This Contributes To The Skyrat Roleplay Experience

less wire fuss for really just a simple oversight

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
Solars are actually wired roundstart now and show once you scan
image

SMES charges and outputs properly
image

a side request to give the pacman a wire under it so i just swapped it with the cell charger
image

well a screenshot of space? But also the mapping editor showing it gone as well
image
image

</details>

## Changelog

:cl:
fix: Void Raptor - Fixes the AI's Powernet and isolates it from the station grid
qol: Void Raptor - Moves the Generator to be on top of a wire for easier quick-attach
fix: Void Raptor - Gets rid of the accidental addition above the chapel
/:cl:

### CODE REVIEW

**Comment by Zergspower** [comment]
god fucking damnit

**Review by Jolly-66 — DISMISSED** [review]
You need to update your PR title, as well as CL to reflect changes made in this PR.

**Comment by Zergspower** [comment]
done

**Review by Paxilmaniac — APPROVED** [review]
The mystery structure gone too soon

**Pull request merged**
