### PR TITLE
[Non-modular] Raises maximum character age from 85 to 300

### PR DESCRIPTION
**Pull request by desertmote**
## About The Pull Request

What it says on the tin.

## How This Contributes To The Skyrat Roleplay Experience

The number is a little arbitrary. Sometimes a character happens to be older than 85. 

## Proof of Testing

dreamseeker_iv5sNml9u5

## Changelog
:cl:
qol:  Raises maximum character age from 85 to 300
/:cl:

### CODE REVIEW

**Comment by Elli-Skala** [comment]
How does this effect old timer aging death?

**Comment by lessthnthree** [comment]
Why 300? That's equally as arbitrary.

**Comment by desertmote** [comment]
> Why 300? That's equally as arbitrary.

it is arbitrary but _not_ equally so.
ppl older than 85 exist in real life, first of all. and then furthermore we have races that can be even older like mechanicals or hemos.
the real answer is because the person who requested this PR gave me this number.

**Comment by bowlofsoup4ik** [comment]
duh. what about:
a) raise limit even more;
b) maybe split biological and chronological age, so players can choose, how old character looks like and how old they actually is. or just let ppl choose examine text about age or smth (which like "she's seems young adult", "she's seems middle aged", etc etc)
upd1: yes, i stole it from rimworld
upd2: zolmachi gamers (like me) would be happy btw (⁠｡⁠•̀⁠ᴗ⁠-⁠)⁠✧

**Comment by theselfish** [comment]
300 is a very arbitrary number.
Why not 999, which is the highest three-digit number. Or 9999.

Also, I swear that having age over 90 has a special examine text.

**Comment by tf-4** [comment]
QOL changes come under the freeze

**Pull request closed without merging**
