### PR TITLE
Body part wreching(dislocation) [SEMI-MODULAR]

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Allows people to dislocate other people's arms, legs, etc. This causes a moderate wound to occur, simple dislocation. Synthliz needs to have synth wounds enabled. 

Also fixes the issue with two screams being played when someone screams.

## Why It's Good For The Game

Good for torture RP and other such things.

## Changelog
:cl:
add: The ability to dislocate people's things.
fix: Double screams.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Groins need to be added at some point.

**Comment by ShadeAware** [comment]
Don't forget the ability to far-cry your dislocations (and other people's dislocations) back into place, at the cost of brute damage

**Comment by Gandalf2k15** [comment]
TG already has that.

**Comment by Azarak** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285 Already has dislocation as one of the introduced grab manevours

**Comment by Gandalf2k15** [comment]
I'm leaving this open as this version seems to have more versatility and effect, we should incorporate this into the new system @Azarak

**Comment by Azarak** [comment]
> 
> 
> I'm leaving this open as this version seems to have more versatility and effect, we should incorporate this into the new system @Azarak

The controls for grab manevours do different effects than dislocate on chest/head, so it'd be hard to. Tho I do like the flavors of those.

**Pull request closed without merging**
