### PR TITLE
Void Raptor morgue renovations

### LINKED ISSUE #21352: Dead end maintenance disposals pipe behind CMO office on Void Raptor
## Round ID: 
local

## Testmerges: 
N/A

## Reproduction:

Pictures say more than a thousand words.

image

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Exactly what it says on the tin; renovates Void Raptor's morgue. Also inadvertently fixes some broken disposal pipes in maintenance around the morgue.

Closes https://github.com/Skyrat-SS13/Skyrat-tg/issues/21352

And closes https://github.com/Skyrat-SS13/Skyrat-tg/pull/21377

## How This Contributes To The Skyrat Roleplay Experience

With medical recently getting an entire dedicated Coroner job Void Raptor's morgue felt pretty cramped and overall sorta lacking. This PR shifts the CMO's office ever-so-slightly to the left in order to expand on the morgue a bit.

The Coroner now gets their own private office/autopsy area locked behind a windoor along with some secure morgue trays; bringing Void Raptor's morgue more in line and up to par with some of our other maps.

## Proof of Testing
Screenshots of changes and proof the disposals were fixed:
image

https://github.com/Skyrat-SS13/Skyrat-tg/assets/62350255/171ab82d-6688-482d-9da3-d10b72ce73f2

</details>

## Changelog
:cl:
qol: Void Raptor's morgue has received some renovations.
fix: Fixed Void Raptor's broken morgue/CMO disposals.
/:cl:

### CODE REVIEW

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
MDB is reporting unexpected changes made here, please fix them.

image

Also please find another wall for the fire extinguisher. 

image

**Review by Jolly-66 — COMMENTED** [review]
Can you provide testing proof that the disposal pipes work?

**Comment by ghost** [comment]
> Can you provide testing proof that the disposal pipes work?

Yeah. Here's a video. The rest of the bins in medical work as well; but github video files have a 10MB upload limit so this'll have to suffice.

https://github.com/Skyrat-SS13/Skyrat-tg/assets/62350255/9349dfa4-2b99-4725-a2a5-f16dc926886d

This is my first time ever doing mapping stuff in SS13 so when I launched a private server to test my changes and realized disposals were broken I assumed that while I was remapping the morgue I had somehow accidentally broken the disposals pipes and subsequently fixed them.

Evidently that wasn't the case; Void Raptor's disposals were just broken to begin with - had I realized that I probably would've mentioned the fix in the original PR body, sorry!

**Comment by NotDhu** [comment]
> Can you provide testing proof that the disposal pipes work?

Yeah. Here's a video. The bins in the CMO's office and the surgery room work as well; but github video files have a 10MB upload limit so this'll have to suffice.

https://github.com/Skyrat-SS13/Skyrat-tg/assets/62350255/9349dfa4-2b99-4725-a2a5-f16dc926886d

This is my first time ever doing mapping stuff in SS13 so to be safe I launched a private server and tested disposals around the morgue after finishing my changes. Upon realizing disposals were broken I assumed that while I was remapping the morgue I had somehow accidentally broken the disposals line and subsequently fixed it.

Evidently that wasn't the case; Void Raptor's disposals line was just broken - had I realized that I probably would've mentioned the fix in the original PR body, sorry!

**Review by Jolly-66 — APPROVED** [review]
It's always good to test disposals if you mess with it to ensure its properly fixed.

Its a pain in the ass to work and mess with, I'll be honest.

I'll merge this once a mob refactor gets merged to ensure I don't accidentally cause a merge skew.

**Pull request merged**
