### PR TITLE
old status indicators pr v2

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request
It is basically the old one, but as a component! I will be filling out the details later. Just making this a draft for review. 
https://github.com/Skyrat-SS13/Skyrat-tg/pull/12529

## How This Contributes To The Skyrat Roleplay Experience

Same reasons as before

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
still going to work on this, but, when I have time

**Comment by nevimer** [comment]
still working on this, this is test ready

**Comment by nikothedude** [comment]
so cool dude..,,,

**Comment by nevimer** [comment]
> so cool dude..,,,

didn't you explosively leave before

**Pull request closed without merging**
