### PR TITLE
Stops overriding the sprite of every single chair for one rather mid sprite change

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

We overwrote the sprite of every single chair in the codebase just so normal iron chairs could look different.

They look like this now (tg default)

image

## How This Contributes To The Skyrat Roleplay Experience

Surely we would not encounter problems in the future when literally every chair was overwritten in the aesthetics folder

## Proof of Testing

Look at the screenshot above

## Changelog

:cl:
imagedel: The entire chairs aesthetics folder has been removed, this has resulting in a massive one chair sprite changing
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Changes check out to me, no unintended lost sprites
Which makes me wonder as well, why we had a whole file for a single icon override...

**Comment by Paxilmaniac** [comment]
> Changes check out to me, no unintended lost sprites Which makes me wonder as well, why we had a whole file for a single icon override...

We have so many of these

**Review by Ebin-Halcyon — APPROVED** [review]
Aesthetic folder my fucking hated.

**Comment by ghost** [comment]
CI fail unrelated

**Review by tf-4 — APPROVED** [review]

**Pull request merged**
