### PR TITLE
[MIRROR] Sign Language Refactor & Bugfixes [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/71265
--------------------
## About The Pull Request
This PR contains an intermediate refactor and a bug-fix for sign language, which was originally from the Tongue Tied quirk/tongue. With helpful advice from @ MrMelbert and @ LemonInTheDark, I have successfully decoupled sign language from the tongue and ported it into a highly modular DCS component, and then added an Action for toggling it. Big thanks to @ Wallemations, the original creator of Tongue Tied, for creating the new Action sprite and helping me to complete this project!

The new sign language component is added to all new Carbon mobs, and incrementally overrides several critical functions, variables, and argument lists relevant to a mob's speech; the component primarily listens for the addition/removal of trait `TRAIT_SIGN_LANG` in order to function.

Additionally, fixed a bug in the original implementation of sign language that caused its say verbs such as "emphatically signs" to stop working. The bug was caused by an unsafe early removal of exclamation points from the input string, causing a conflict with the `say_mod` proc which requires such punctuation points to be present.

Here's a granular list of changes:
- Added a ubiquitous signal to extend the behavior of `/atom/movable/proc/say_quote`.
- Added a ubiquitous signal to extend the behavior of  `/atom/movable/proc/lang_treat`.
- Fixed a bug in the original implementation of sign language that caused its `verb_yell` to stop working.
- Refactored sign language into a Carbon-only DCS component.
- Refactored the Tongue Tied tongue to use `TRAIT_SIGN_LANG` and `TRAIT_MUTE`.
- Removed the Tongue Tied quirk, in favor of two separate quirks.
- Added the Signer quirk for sign language, good, costs 4 points.
- Added the Mute quirk, negative, gives 4 points.
- Added a rare sign language Action granter book to maint and space loot, "Galactic Standard Sign Language".

## Why It's Good For The Game
This PR tactfully re-implements Tongue Tied, re-introducing it as two new quirks: For sign language itself, I added the Signer quirk, which is a good quirk which allows you to use sign language for 4 quirk points. I also added the Mute quirk, which grants 4 quirk points in exchange for your audible voice. There is also a marked improvement in the code health as a result of my changes.

Here's a preview of the sign language Action. If you're also mute, it becomes invisible to reduce clutter:
image

In regard to how useful sign language is, it can be used as:
1. A way to communicate across a vacuum without a radio.
2. An easy way to communicate with deaf people.
3. An easy way to communicate as a Mute person.

## Changelog

:cl: A.C.M.O.
del: Removed the Tongue Tied quirk. The tongue can still be found and used in-game.
refactor: Refactored Tongue Tied's tongue to use the Sign Language and Mute traits.
add: Added Sign Language innate action. Granted by book or quirk.
add: Added the Galactic Common Sign Language book as rare maint and space loot.
add: Added the Signer quirk, which teaches you sign language in exchange for 4 quirk points.
add: Added the Mute quirk, which grants you 4 quirk points in exchange for your voice.
fix: Fixed sign language say_yell verb, which allows you to emphatically sign.
/:cl:

### CODE REVIEW

**Comment by Floofies** [comment]
I am now working on the hotfix PR for this PR!

**Comment by Floofies** [comment]
Ok, I have completed PR #17594 to make this PR merge-able!

**Comment by Floofies** [comment]
Looks like something got overlooked in the changelog/notes. The Tongue Tied tongue itself was totally removed by TG maintainers, but the changelog does not reflect this. Sorry about that, it was a last-minute change

**Review by GoldenAlpharex — APPROVED** [review]
I forgot to actually merge this.

**Pull request merged**
