### PR TITLE
[MODULAR] Admins can now delete NIFs and NIFs now remove after being broken for two shifts.

### PR DESCRIPTION
**Pull request by softcerv**
## About The Pull Request
Adds a parameter to the `save_nif_data` proc, allowing for NIFs to be manually removed from the user's modular persistence save. Additionally, when at 0 durability and after not being repaired for a shift, NIFs are now removed.

## How This Contributes To The Skyrat Roleplay Experience
This is a useful command for admins to have, and this also makes NIF deletion function as intended.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
 
image

image

</details>

## Changelog

:cl:
qol: NIFs can now be manually removed from a player file.
fix: NIFs now delete when broken for two shifts
/:cl:

### CODE REVIEW

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by YakumoChen** [comment]
that's not how proof of testing works

**Comment by softcerv** [comment]
> that's not how proof of testing works

Elaborate. I demonstrated that the PR did what It set out to do.

**Comment by YakumoChen** [comment]
> > that's not how proof of testing works
> 
> Elaborate. I demonstrated that the PR did what It set out to do.

Proof of testing is proof you compiled the PR and ran it in the game, to ensure it works. You should be posting a screenshot of deleting an NIF, not just posting the code we can already read.

**Comment by softcerv** [comment]
> > > that's not how proof of testing works
> > 
> > 
> > Elaborate. I demonstrated that the PR did what It set out to do.
> 
> Proof of testing is proof you compiled the PR and ran it in the game, to ensure it works. You should be posting a screenshot of deleting an NIF, not just posting the code we can already read.

If you look at the screenshots provided, you'll notice that they are of the JSON of the file used for NIF save data from both before and after the removal. In the second one, the path and examine text are missing, meaning that the NIF wouldn't spawn in for future rounds.

**Comment by YakumoChen** [comment]
I'm telling you that's against the point of having a proof of testing section, it needs to be proven to work on a running instance.

**Pull request merged**
