### PR TITLE
Anomaly neutralizers don't murder you with CMEs

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request

title

## Why It's Good For The Game
see #4243

## Changelog
:cl:
qol: Anomaly neutralizers don't kill you anymore
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
No. We literally just nerfed them, deal with the consequences of touching a literal ball of fire. Stop making PR's right after the previous one was closed.

**Comment by Vizoplez** [comment]
based

**Comment by hugmeorelse** [comment]
> No. We literally just nerfed them, deal with the consequences of touching a literal ball of fire. Stop making PR's right after the previous one was closed.

I think this should be reconsidered. Please don't close PRs like that without allowing others to place their input like my own.

**Comment by YakumoChen** [comment]
Neutralizing a CME gives you 5 fire stacks AND stuns you, which is enough to give you extremely significant damage by the time you can get up or outright crit you if you don't have a fire extinguisher on hand.

As I said before, we should not have dangerous events completely punish you for daring to interfere with them, or else nobody will want to prevent high amounts of station damage from being dealt

There is also NO WARNING for neutralizers punishing you, and precedent for neutralizers on actual anomalies is that doing so is safe outside of the direct damage anomalies can deal to you normally.

It's extremely poor design and doesn't contribute positively to the round to make every CME neutralization be lethally deadly.

**Pull request closed without merging**
