### PR TITLE
[semi-modular] reagent forging

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request

adds reagent forging:
reagent forging is where one creates gear (sword, staff, gloves, or armor) and then once completed, is able to imbue a reagent into them.

The process is as follows:
10 iron to make a forge
10 iron to make an anvil
5 wood to make a water basin
order the forging starter kit from cargo, under service tab
use wood on the forge to fuel it
use the billow a few times to increase the temperature
take your tongs and pick up iron rods
use the tongs on the forge to choose a sword, a staff, or a chain
click on the tongs to drop whats in it currently, and then pick up the sword, staff, or chain
use the tongs on the anvil to place the item on the anvil
use the hammer and slowly hit the item (get used to the good hit feeling)
once it is ready, tong the anvil and then tong the water basin.
swords and staffs require 2 additional wood in the crafting, under weapon tab
gloves require 3 chains, armor requires 6 chains, under clothing tab
use 3 regenerative cores that haven't dulled yet on the forge to upgrade it
(additionally, you can use 10 watcher sinew to lower the chance for the temp to lower, and coal is a better fuel source)
get 200u of any chem and pour it onto the weapon/clothing (capable of holding 500u, so that means 2 chemicals can be 200)
use the weapon/clothing on the upgraded forge to imbue.
weapons and clothing will essentially inject the chemical, NOT by touch or gas, etc.
## Why It's Good For The Game

more means of crafting weapons/clothing.
this is the base, which means other stuff can be definitely added and I most de
## Changelog
:cl:
add: Added reagent forging (check PR)
soundadd: added hammer hit and water hiss
imageadd: added icons for all new items/structures
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
I politely request for the swords to be able to fit in the crusader belt.

**Comment by CameronWoof** [comment]
Potassium sword in one hand, water sword in the other...

What do reagents in clothing do?

**Comment by Cheshify** [comment]
So, I do have an issue with this on a technical level. It's important that there exists documentation for this since it's new and skyrat exclusive. If this got a page on a wiki I have little issue (before I read the code that is)

**Comment by jjpark-kb** [comment]
> Potassium sword in one hand, water sword in the other...
> 
> What do reagents in clothing do?

slowly inject the imbued reagents over time.

**Comment by jjpark-kb** [comment]
> So, I do have an issue with this on a technical level. It's important that there exists documentation for this since it's new and skyrat exclusive. If this got a page on a wiki I have little issue (before I read the code that is)

Im not sure if I can edit the wiki page. If I can, I will.

**Comment by Gandalf2k15** [comment]
just gonna send it

**Comment by Trubbl3** [comment]
this will only be used by powergamers tbh

**Comment by Cheshify** [comment]
> this will only be used by powergamers tbh

It's... already merged.

**Pull request merged**
