### PR TITLE
[MODULAR] What Cloner?

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
Removes the "Do Not Clone" trait

## How This Contributes To The Skyrat Roleplay Experience
Improves immersion due to the actual lack of cloning technology in the sector.

## Changelog

:cl:
fix: Nanotrasen has updated medical records upon finding out that it was still tracking those incompatible with illegal cloning technology, which is banned sector-wide. Such records have been expunged.
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
> You currently have a negative Fix/Feature pull request delta of -30. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

Jesus christ.

**Comment by YakumoChen** [comment]
GBP is a flawed system when the majority of bugs come from upstream and are fixed upstream

**Comment by tf-4** [comment]
We have plenty of bugs that you're welcome to look at

**Review by GoldenAlpharex — APPROVED** [review]
I was wondering for the longest time why we still had it, and yet I never really thought about removing it. However, are you sure there's no other code related to it in the TGUI quirk stuff?

**Comment by GoldenAlpharex** [comment]
They didn't answer my question yet :waa:

**Comment by Gandalf2k15** [comment]
> They didn't answer my question yet :waa:

quirks don't require anything in TGUI

**Comment by YakumoChen** [comment]
@Gandalf2k15 there was but you merged it 2 minutes too early lmao

**Comment by GoldenAlpharex** [comment]
> @Gandalf2k15 there was but you merged it 2 minutes too early lmao

Just make another PR then.

**Comment by Gandalf2k15** [comment]
I'll check and if there is I'll push It to master.

**Comment by Gandalf2k15** [comment]
No further action is required, quirks do not have dependencies.

**Pull request merged**
