### PR TITLE
Fixes Skyrat Camera Icons [TM FIRST]

### LINKED ISSUE #16512: camera sprites are WHACK
## Round ID:

N/A
## Testmerges:
N/A

## Reproduction:
image
This camera here on icebox is "floating" above the engine door frame.
image
Upstream, it's not a problem as it's just pixel shifted to the right BUT:
image
Our camera sprites are on the right hand side for some reason...

---
Pretty sure this falls under an overwritten sprite issue.

Could probably be solved by moving the camera sprite to the left, but I dunno if that'd mess up SR specific maps like Blueshift & Void Raptor.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Hey, you! Yes, you!
Have YOU ever seen a camera looking like it was in the WRONG place?<details><summary>Something like thiiiiiiiis???</summary>

image
</details>

Well FUCK YOU buddy! That wasn't in the wrong place! You simply perceived it backwards!
In fact, you're not alone! EVERYONE on the Skyrat SS13 Roleplay Server (For Mature, Rugged Souls) has been experiencing that since time immemorial!

Want to know why?
**SOME KNUCKLEHEAD PUT ALL OUR ICONS IN BACKWARDS!** ~~(Love u whoever did it u give my life purpose)~~

Fixes  #16512

---

Jokes aside, **this needs testmerging first** to make sure it doesn't fuck over any skyrat maps or mapping-templates too hard. I'd love to test them myself but my SDMM has literally been flagged as a virus on my PC (it probably is tbh it hasnt worked in months) and I cannot do anything to maps any more. TM would be so that our mappers have an advance warning and can either push to this PR or can make PRs for right after this is merged.

---

Also someone yell at Jolly when this is merged he needs 2 know

## How This Contributes To The Skyrat Roleplay Experience
Maybe NOW when we're playing TG maps our camera's will look correct for once? Maybe?

## Changelog

:cl:
fix: after about a year of agony, the Station Technicians have finally realized they've been putting your cameras on backwards! Give 'em a shout if any are still out of place, but you should see lots of improvement when it comes to where they're mounted.
/:cl:

### CODE REVIEW

**Comment by press-mark** [comment]
THANK YOU

edit; only issues i can see popping up is that the placement on our maps like void raptor & blueshift might have some funky placements

**Review by GoldenAlpharex — APPROVED** [review]
Looks good to me!

**Comment by ghost** [comment]
> THANK YOU
> 
> edit; only issues i can see popping up is that the placement on our maps like void raptor & blueshift might have some funky placements

Figured as much, TM is more to give them time to adapt than anything at this point. Merging it with them totally caught off-guard or ootl would be, as some might call it, "a dick move."

**Comment by Gandalf2k15** [comment]
ok this is working

**Pull request merged**
