### PR TITLE
Cere Station [DO NOT MERGE] [MDB IGNORE]

### PR DESCRIPTION
**Pull request by Ignari-contrib**
## About The Pull Request
Cere Station is coming back.

## How This Contributes To The Skyrat Roleplay Experience
Large map for our large population

## Changelog
Heavy WIP

:cl:
add: New large map
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Since it's WIP, I'm marking it as a draft.

**Comment by Jolly-66** [comment]
You should consider putting [MDB IGNORE] in the PR title to stop the bot from generating diffs (as its probably gonna be huge), lest the repo gets blacklisted from crashing the bot every time a commit is pushed.

**Comment by Tastyfish** [comment]
Good lord, this is big. The main corridor box is 100-150 turfs long on each side. It might need transit tubes or something, I'm not sure.

**Comment by Tbowes-dev** [comment]
> Good lord, this is big. The main corridor box is 100-150 turfs long on each side. It might need transit tubes or something, I'm not sure.

Transportation wouldnt be an issue, if this is copying the original rooms each of the long hallways as teleport linkpads already built
Iam glad there is another attempt at making Cerestation work, wish the best to you

**Comment by Tastyfish** [comment]
> > Good lord, this is big. The main corridor box is 100-150 turfs long on each side. It might need transit tubes or something, I'm not sure.
> 
> Transportation wouldnt be an issue, if this is copying the original rooms each of the long hallways as teleport linkpads already built Iam glad there is another attempt at making Cerestation work, wish the best to you

Ah OK, I didn't look closely at the objs when popping open the map.

**Pull request closed without merging**
