### PR TITLE
Cutting ties; DS-2/Interdyne

### PR DESCRIPTION
**Pull request by xXPawnStarrXx**
## About The Pull Request
Too long didn't want to read? Seperates Interdyne and DS-2

Apparently due to recent policy changes, Interdyne is not an affiliate of the Syndicate. I have also experienced that a contingent of Interdyne characters apparently hold a bizzare disdain for anyone on DS-2, so clearly buisness relations have gone sour. I don't see why the Syndicate would want a pad connected to a group that frequently insists on trading and interacting positively with NT. So this seeks to remove DS-2's connection to Interdyne and their communications.

To counteract the lack of access to Lavaland; DS-2 now gets 2 bluespace miners for them to set up to supplement the loss of minerals.

## How This Contributes To The Skyrat Roleplay Experience
It allows for DS-2 to be it's own independant party without having to deal with Interdyne players and their negative attitude towards the other faction. No more walled off teleporter or threats of violence because you want to mine some ores.
This also means that in the inverse; Interdyne doesn't have to concern themselves with DS-2.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image
image
image

</details>

## Changelog

:cl:
add: Added two bluespace miners to DS-2, gave cybersun frequency (UPLINK) headsets to DS-2
del: Removed telepads between DS-2 and Interdyne, removed interdyne headsets from lockers and spawns.
/:cl:

### CODE REVIEW

**Comment by xXPawnStarrXx** [comment]
For some reason it's failing on something I've not even edited. Apparently doesn't like the syndicate weapons...

**Comment by ghost** [comment]
I like some of the changes, such as separating the Interdyne and DS-2 more by giving them their own respective comms channels and such. 

I dislike the idea of completely separating them. I've experienced both sides and I can say that while yes there is hostility between the DS-2 and the Interdyne, it's generally due to how the folks on the DS-2 have behaved towards the Interdyne. Personally I see this as an IC conflict that's dragged on for too long and repeated too often. 

The DS-2 and Interdyne (hereby referred to as ID) are trade partners. They are meant to work together to fulfill each others goals and make rounds more interesting by putting two factions within arms length of the other. I've often seen the DS-2 and the ID work together. ID provides materials for the DS-2 and the DS-2 can help by giving ID things that the ID could sell to the NT station. However there are some bad apples in the DS-2 who use their access to ID to walk around and throw their weight around without actually having any down there. This leads to the characters getting annoyed with the DS-2 which eventually led to them blocking off or disconnecting the pad.

You can imagine that situation like a neighbor (DS-2) comes over to your house (Interdyne) and instead of ringing the door bell (Asking for permission), barges down the front door and walks around your house like they own it. Of course the homeowner gets angry and puts measures down to stop it from happening.

Proposed Solution:
Both characters and players of their respective factions show respect to the other. Request and receive permission to enter the other faction's base before entering, show respect to those who work at said bases, and generally both try to show some level of professionalism when it comes to how you treat your trade partners.

**Comment by xXPawnStarrXx** [comment]
> Proposed Solution: Both characters and players of their respective factions show respect to the other. Request and receive permission to enter the other faction's base before entering, show respect to those who work at said bases, and generally both try to show some level of professionalism when it comes to how you treat your trade partners.

While I 100% agree with this, a lot of frequent players are at the point where they just entirely wall off the teleporter so they don't get bwoinked for deconstructing it. I even considered moving it to an outside location but that doesn't stop DS-2 taking the pad and just walking into the base.

**Comment by burgerenergy** [comment]
Ignoring the extreme passive aggressive nature of the PR, this is more or less Policy's outspoken goal, if lacking some means for Interdyne to travel there. (But shuttle stuff requires a lot more effort and mapping besides, which is a can we can kick further down the road.)

I would prefer if we renamed the Cybersun "Uplink" to DS2 or something, but I couldn't find where that was in in the code before I got burnt out on SS13, for the time being, for the drafted Interdyne PR.

Beyond that, you will also have to make a new cryo computer for DS-2, which transmits to the Cybersun channel. The drafted Interdyne Project has that done already if you just want to copy and paste, no biggie.

**Comment by burgerenergy** [comment]
> > Proposed Solution: Both characters and players of their respective factions show respect to the other. Request and receive permission to enter the other faction's base before entering, show respect to those who work at said bases, and generally both try to show some level of professionalism when it comes to how you treat your trade partners.
> 
> While I 100% agree with this, a lot of frequent players are at the point where they just entirely wall off the teleporter so they don't get bwoinked for deconstructing it. I even considered moving it to an outside location but that doesn't stop DS-2 taking the pad and just walking into the base.

also ds-2 **cannot** go onto lava land **except** for visiting interdyne _with their permission_, so

**Comment by xXPawnStarrXx** [comment]
> Beyond that, you will also have to make a new cryo computer for DS-2, which transmits to the Cybersun channel. The drafted Interdyne Project has that done already if you just want to copy and paste, no biggie.

I've already done that, I can change the channel, but since the DS-2 FOB is meant to be all of the syndicate, it just being the "UPLINK" network works.

**Comment by ghost** [comment]
> While I 100% agree with this, a lot of frequent players are at the point where they just entirely wall off the teleporter so they don't get bwoinked for deconstructing it. I even considered moving it to an outside location but that doesn't stop DS-2 taking the pad and just walking into the base.

Well, to look at it this way, people are walling it off for a reason. I believe the best solution would be for unprofessionalism leading to LRP notations and bwoinks. Eventually ghost role bans if it continues. That way people can ahelp if someone from the DS-2 or the Interdyne are being unreasonable within roleplay. I don't think this PR is a good solution personally.

**Comment by xXPawnStarrXx** [comment]
> Well, to look at it this way, people are walling it off for a reason. I believe the best solution would be for unprofessionalism leading to LRP notations and bwoinks. Eventually ghost role bans if it continues. That way people can ahelp if someone from the DS-2 or the Interdyne are being unreasonable within roleplay. I don't think this PR is a good solution personally.

The best way to outright end this without wasting more staff time is to just seperate them, they could be reconnected in the future in some way, like a shuttle or tram. For now however, I think until tempers cool, just seperating both parties is best.

**Comment by RatFromTheJungle** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/24645

 does everything thing this should have, with this being (a lot) a little off mark for what the policy says. 
 
 I else-wise don't really see a reason, or justification in this PR that would justify going against the intended design both short and longterm

**Comment by GoldenAlpharex** [comment]
I appreciate the efforts that went through this PR, I think we're better off going with that other PR Jungle's linked, for now.

**Pull request closed without merging**
