### PR TITLE
Adds a new type of horn and tail sprite

### PR DESCRIPTION
**Pull request by Z0w0plankton**
## About The Pull Request
Adds a new horns and tail style, ~~Au Ra~~ Side swept back, and reptile slime respectively

## How This Contributes To The Skyrat Roleplay Experience
More character customization for nerds

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
dreamseeker_Q9MDSkyYhv

afbeelding
afbeelding
afbeelding

</details>

## Changelog

:cl:
add: Side swept back horns tyle, reptile slim tail.
/:cl:

### CODE REVIEW

**Comment by HoodMilk** [comment]
Let's fucking go

**Review by tf-4 — CHANGES_REQUESTED** [review]
I'd rather they were called something other than "Au Ra" as, even though they're obviously inspired by that, we don't want to encourage people to make literal Au Ra characters as it's not the same universe.

**Comment by Z0w0plankton** [comment]
>



> I'd rather they were called something other than "Au Ra" as, even though they're obviously inspired by that, we don't want to encourage people to make literal Au Ra characters as it's not the same universe.

Renamed them to side swept back, and reptile slim!

**Review by tf-4 — APPROVED** [review]
code is good

**Review by Ebin-Halcyon — APPROVED** [review]
I hate demihumans.

**Pull request merged**
