### PR TITLE
The intern got fired.

### PR DESCRIPTION
**Pull request by Useroth**
Due to multiple complaints, the announcement intern has been fired.

### CODE REVIEW

**Comment by Oscari-pog** [comment]
Seems unnesessary, I actually found it quite fun. Not to mention that
Station traits have a 35 percent chance of occuring
And they get chosen out of a pool of 15+

It seems dumb to remove it just because some people dislike it

**Comment by Gandalf2k15** [comment]
This is absolutely outrageous! How dare you fire my son!

I'd like to speak to your manager.

**Comment by Swiftfeather** [comment]
Bad pr

**Comment by YakumoChen** [comment]
Seems kind of kneejerk

**Comment by BrotherHangyul** [comment]
I actually quite like the intern, seems unnecessary.

**Comment by tf-4** [comment]
intern is loud and annoying, first time I heard it I wanted to turn it off instantly. This is a good change as far as I'm concerned.

**Comment by MLGTASTICa** [comment]
Intern is great

**Comment by Sethnov** [comment]
please keep the intern

**Comment by actioninja** [comment]
> 
> 
> This is absolutely outrageous! How dare you fire my son!
> 
> I'd like to speak to your manager.

you're not my real dad

**Comment by ghost** [comment]
Literally 1984

**Comment by press-mark** [comment]
just turn the volume of the voice down / lower the chances if its really that much of an issue

**Comment by NullDagaf** [comment]
About time.

**Comment by Gandalf2k15** [comment]
The people have spoken. We'll keep him for now.

**Comment by actioninja** [comment]
ok now let me in

**Pull request closed without merging**
