### PR TITLE
MAP FUCKING RESET 25/05/2022

### PR DESCRIPTION
**Pull request by Gandalf2k15**
You know why I kill people? Because of map resets.

### CODE REVIEW

**Comment by Jolly-66** [comment]
Thank you for the reset daddy Cobalt 🥺

**Comment by Gandalf2k15** [comment]
ah fuck it
i cant be assed, someone else can do the rest, you need to do tram, kilo and meta

**Comment by Gandalf2k15** [comment]
nah fuck it dont worry i got it all hahahahha fuck you

**Comment by tf-4** [comment]
Here we witness Cobalt's descent into madness.

**Pull request merged**
