### PR TITLE
Ports AI/Cyborg QoL updates, Allows AI to examine and adds more QoL features.

### PR DESCRIPTION
**Pull request by MLGTASTICa**
## About The Pull Request

Ports the AI/Cyborg QoL updates from original Skyrat. Adds turf checks for firelocks
 closing and electrifying doors.
Allows AI to examine mobs and objects. They are unable to read paper at all and can't examine door descriptions to prevent spam.
## Why It's Good For The Game
Makes easier to play AI. Allows AI to examine which is very usefull with items that have the same inhand sprite as a flash , for example a AI card.
Non-modular , modified core files.If its possible to modularize please tell me how and i will do it as soon as i can.
Edit : Was fully modulerized
## Changelog
:cl:
add: Ports Skyrat AI/Cyborg QoL
add: AI can now examine objects and mobs.
code: Added a AI examine proc.
/:cl:

### CODE REVIEW

**Review by Gandalf2k15 — CHANGES_REQUESTED** [review]
Please review the modularisation handbook. 
This can be made into it's own module and have the procs overridden in said module. Your module ID could be SILLICON_QOL. Override the procs by never calling the parent. (no ..())
Put these changes in the module folder.

**Comment by MLGTASTICa** [comment]
Modularized all of it , i used ..() at Aiclickon . If that's an issue i can change it.

**Comment by Gandalf2k15** [comment]
This is better now; you can delete the changes to the main files as those edits are irrelevant.

**Comment by MLGTASTICa** [comment]
Its just random  line change , i can't really seem to get rid of them for some reason

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
