### PR TITLE
[MODULAR] Adds cryo to permabrig 2: Electric Grillaboo

### PR DESCRIPTION
**Pull request by Tastyfish**
## About The Pull Request

(Note that I've only tested it on Icebox, hence the draft.)

The perma brig ultimately has limited space, so I tried to think of a novel solution:
Making the prison's cryo be a tray that comes out of the wall.
image

Note that it's pure chance in the following demo that the console and the actual cryo chamber spawned across from each other, but that's real nice.

Note that in doing so, I realized that the cryo console doesn't have directional versions and is normally just placed manually; as well, its sprite and direction was backwards from the standard for wall mounted objects. So, I added directional helpers and replaced all the instances of the base cryo console with the directional versions, and fixed the directions for the custom (ie Tarkon and Interdyne) ones.

## How This Contributes To The Skyrat Roleplay Experience

Cryopod in prison.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

https://user-images.githubusercontent.com/1185434/211117553-e858a385-fc2e-41ea-adda-e2f90db49208.mp4

</details>

## Changelog

:cl:
add: The perma brig now has a wall mounted cryo pod, for all your prisoner storage needs.
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
While your at it, obviously in a different PR, do you think we could nuke the curtains template in favor of a logic system like this?

**Comment by Tastyfish** [comment]
> While your at it, obviously in a different PR, do you think we could nuke the curtains template in favor of a logic system like this?

Yeah, I was thinking of doing that, but have been busy. It would have to be a new system/thing.

**Comment by Tastyfish** [comment]
Works reasonably well in all maps, obviously it's pseudo-random due to being autospawn.

**Review by Paxilmaniac — APPROVED** [review]
impressive, very nice

**Pull request merged**
