### PR TITLE
Makes the Arrivals Docks feel more open-ended

### PR DESCRIPTION
**Pull request by ghost**
arrival

## About The Pull Request
Does a tad bit of remodeling to the Arrivals Docks so that A. the tram itself has a bit of a better-defined path, B. not everyone spawns on the tram, and instead spawn in a hallway beside the tracks as if they arrived a separate way, C. the dock has a bit more space to expand from instead of being boxed in.
While I was there I also made it feel a bit more truckstop-y and airport-y, specifically with the bathroom, new Info Kiosk, and a Coffee Stand.
I _also_ fixed up dorms, making them a tad bigger, more comfortably layed out, and actually boltable for privacy.

## Why It's Good For The Game
"Ride the tram to take a tram" are you daft, you rode a tram through a spaceport to your station-ferry, which isn't even a tram it's literally a space-ferry that travels through bluespace to your station, shut up already

## Changelog
:cl:
fix: The Arrivals Midpoint is now a bit more vague on the method of your arrival! Did you teleport from far away? Dock your own ship maybe? I dunno, but the hallway beside the tram opens up RP options! It also has other fixes such as Dorms Bolts, and light improvements, like a proper truckstop bathroom and a small cafe sponsored by Jim Norton's Quebecois Coffee!
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
> 
> 
> You currently have a negative Fix/Feature pull request delta of -35. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

kill

**Comment by Gandalf2k15** [comment]
Small request, can you add a cafe sitting area?

**Comment by Gandalf2k15** [comment]
Aaah and replace the space floor bit with flora!

**Comment by Gandalf2k15** [comment]
Since its supposed to be on a planet

**Comment by ghost** [comment]
easy fixes yea
tho, i do question why a midpoint for "refuelling/repairing" of ships would be planetside and not spacebound..

**Comment by ghost** [comment]
i uh, dunno if you meant full-on cafe seating or just the chairs/tables i added, if its the former then i'd rather do that in a full revamp rather than this one. the main point of this PR was for the 'truckstop' feel and the new non-tram spawns

**Comment by ghost** [comment]
actually-
lemme try somethin

**Comment by ghost** [comment]
there. THATs a cafe.

**Comment by Gandalf2k15** [comment]
question it not, young padawan

**Pull request merged**
