### PR TITLE
re-removes frog sound

### PR DESCRIPTION
**Pull request by tf-4**
https://github.com/Skyrat-SS13/Skyrat-tg/pull/2193
got re-enabled in https://github.com/Skyrat-SS13/Skyrat-tg/pull/12541

## Changelog
:cl:
del: The frog no longer makes a noise walking over it again
/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
_reeeeeeeeeeee noises_

**Comment by Stalkeros2** [comment]
nooooooooooooooooo not the frog.(((((((((((((((((((((((((((

**Comment by jjpark-kb** [comment]
improve, not remove! 😢

**Comment by Aether217** [comment]
I think George Orwell wrote a book about this, it's called 1984

**Review by Gandalf2k15 — CHANGES_REQUESTED** [review]
this is super ugly and non modular, make modular

**Comment by Iamgoofball** [comment]
but this is a realistic frog sound, my immersion :(

**Comment by tf-4** [comment]
Mostly modularised, a few non-modular bits but a lot better. If anyone has any suggestions for those that's great.

The noisy type *is* still available, technically, but very uncommon and I didn't want to dive into map edits.

**Comment by Ironnhawk** [comment]
I will cry the day this is merged :<

**Comment by softcerv** [comment]
image

**Comment by Gandalf2k15** [comment]
re-open once you have completed this

**Pull request closed without merging**
