### PR TITLE
[NON-MODULAR] I had to unfuck the Dutch coat hands.

### PR DESCRIPTION
**Pull request by thestubborn**
i may have a tiny brain
but at least I know to add hands to a sprite

### CODE REVIEW

**Comment by ghost** [comment]
yo, dont forget to post pictures of your changes
viewing .dmi files on github is hell x-x

**Comment by thestubborn** [comment]
oh

right

image
this is the fixed coat

image
this is why we need to fix the fucking coat

**Comment by ghost** [comment]
wew thats my bad, probably should have checked that when i added it
's what i get for my usual 3am coding.,

**Comment by Gandalf2k15** [comment]
You'll need to move the dutch jacket to modular, that icon file will be overriten

**Comment by thestubborn** [comment]
> 
> 
> You'll need to move the dutch jacket to modular, that icon file will be overwritten

what just put the icon in the customization folder instead? or will I have to edit the code to make it point there?

**Comment by Gandalf2k15** [comment]
Edit the code to make it point there yes

**Comment by thestubborn** [comment]
> 
> 
> Edit the code to make it point there yes

like...the tg code or make a "dutch jacket" in our code?

**Comment by thestubborn** [comment]
if it's the latter where the hell did we hide it?

> 
> 
> Edit the code to make it point there yes

**Comment by thestubborn** [comment]
wait found it
posted in dev help, may have got it wrong

**Comment by thestubborn** [comment]
> 
> 
> Edit the code to make it point there yes

right, sorted, wasn't sure how to revert the old icon but
if it'll get overwritten anyway, ehhhh

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
