### PR TITLE
[SEMI-MODULAR] Wizards Changes and new spells

### PR DESCRIPTION
**Pull request by SarmentiCampbell**
## About The Pull Request
Wizards now need to set their ambitions before receiving their spellbooks,  Some new spells were added and one spells and several events were removed by the request of Liuvik, For any complaints or feedbacks, Send them to Liuvik, okay thanks.

## Changelog
:cl:
add: The Wizard Federation started teaching some new spells..
del: Several Wizard events were deemed bad and got removed, sadly.
/:cl:

### CODE REVIEW

**Comment by SpaceVampire** [comment]
Why did you remove so many of those events? You might as well just make it so that you can't pick it at all.
I understand why people here would get upset about race swap, or mind swap.
But a lot of the other changes seem super arbitrary.  Like magicarp, cursed items, the floor is lava, petsplosion, and both summon events are fine as far as I can tell. Could you maybe list the actual reasons for em?

**Comment by SarmentiCampbell** [comment]
> Why did you remove so many of those events? You might as well just make it so that you can't pick it at all.
> I understand why people here would get upset about race swap, or mind swap.
> But a lot of the other changes seem super arbitrary. Like magicarp, cursed items, the floor is lava, petsplosion, and both summon events are fine as far as I can tell. Could you maybe list the actual reasons for em?

For any complaints or feedbacks, You should go to Liuvik

**Comment by SpaceVampire** [comment]
> 
> 
> > Why did you remove so many of those events? You might as well just make it so that you can't pick it at all.
> > I understand why people here would get upset about race swap, or mind swap.
> > But a lot of the other changes seem super arbitrary. Like magicarp, cursed items, the floor is lava, petsplosion, and both summon events are fine as far as I can tell. Could you maybe list the actual reasons for em?
> 
> For any complaints or feedbacks, You should go to Liuvik

Sure, but it would be nice if they were on the actual PR about it.
I feel like you could have split the changes up more, because some stuff like the new AMB system is good and should probably be merged quickly. But adding new spells, and changing old ones could be debated separately.

**Comment by SarmentiCampbell** [comment]
> > > Why did you remove so many of those events? You might as well just make it so that you can't pick it at all.
> > > I understand why people here would get upset about race swap, or mind swap.
> > > But a lot of the other changes seem super arbitrary. Like magicarp, cursed items, the floor is lava, petsplosion, and both summon events are fine as far as I can tell. Could you maybe list the actual reasons for em?
> > 
> > 
> > For any complaints or feedbacks, You should go to Liuvik
> 
> Sure, but it would be nice if they were on the actual PR about it.
> I feel like you could have split the changes up more, because some stuff like the new AMB system is good and should probably be merged quickly. But adding new spells, and changing old ones could be debated separately.

Yeah, Just message them to discords, And I can understand that second part.

**Comment by YakumoChen** [comment]
How many spell points are these new spells? All of them seem extremely weak compared to typical wizard spells to the point they might as well be cantrips.

**Pull request merged**
