### PR TITLE
[Modular] Adds 6 new tails!

### PR DESCRIPTION
**Pull request by NotRanged**
## About The Pull Request

Adds: 
Leopard tail (with wagging)
2 new fox tail variations (no wagging :( )
2 new avian tails
'cable' tail (thin stripe with plume at the end)

https://gyazo.com/3f554e3a84dc99ce61629beec0596cb1 Snow leopard

Birb 1
image

Birb 2
image

Fox 1
image

Fox 2
image

## Why It's Good For The Game

More customization yey

Tail baseline sprites taken from Virgo/Vesta, heavily modified to fit our style and custom colouring.

## Changelog
:cl:
add: Added a leopard tail that can wag, and leopard chest markings (just spots really).
add: Added 2 new fox tail variations, 2 new avian tails, and a cable tail. They can't wag.
/:cl:

### CODE REVIEW

**Comment by KasparoVy** [comment]
Amazing, cheers! Very happy to see more avian tails.

**Comment by NotRanged** [comment]
dont merge yet am still working on some stuff a

**Comment by NotRanged** [comment]
no more cheetah it'll come later in a separate PR along with markings and snout
feel free to merge this
image

might still edit the leopard tail a bit later, to make it more friendly to non-snow leopard colors

**Review by KathrinBailey — APPROVED** [review]
image

**Comment by Seris02** [comment]
Just gonna leave something here, the ~~leopard~~ fox (I'm blind) sprites look fluffy or fat at the base with the side sprites, but that idea goes completely out the window when you look at the front and back sprites, it doesn't line up with the side sprites.

**Comment by NotRanged** [comment]
> Just gonna leave something here, the ~leopard~ fox (I'm blind) sprites look fluffy or fat at the base with the side sprites, but that idea goes completely out the window when you look at the front and back sprites, it doesn't line up with the side sprites.

Yeah I see, I'll give that a quick pass

Anyway! Better snow leopard sprite and markings
image

https://gyazo.com/3f554e3a84dc99ce61629beec0596cb1

**Comment by NotRanged** [comment]
Okay, ready to merge now

**Pull request merged**
