### PR TITLE
Adds holofan to engineering

### PR DESCRIPTION
**Pull request by scrubs2009**
## About The Pull Request

Adds 2 holofan projectors to each supermatter chamber

## Why It's Good For The Game
Many supermatter setups require piping inside the core itself. This requires a holofan to do safely. This means that every round if you plan on doing an internal radiator setup you need to go bother atmos or the CE. I feel like just adding one in the SM chamber would help with this. 

## Changelog
:cl:
add: Added atmos projector to supermatter chambers. 
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
As much as I like the sound of this, it does sort of give engineers the ability to go brainlet and cheese the setup with absolutely no risk at roundstart. It's all about risk and reward.

**Comment by scrubs2009** [comment]
> As much as I like the sound of this, it does sort of give engineers the ability to go brainlet and cheese the setup with absolutely no risk at roundstart. It's all about risk and reward.

I mean there's never any risk. You just go and bother atmos or the CE for one. Or walk to the HOP to go get the access for it. No one ever weighs the pros and cons of doing the stupidly risky idea of doing SM core work without one. All adding a holofan would do would cut down on roundstart hassle.

**Comment by KathrinBailey** [comment]
This is just powercreep, albeit very minor powercreep, but powercreep.
You don't actually need this to pipe your SM safely roundstart at all. Check the floor under the SM. Do you know what gas the crystal chamber starts with? The same gas as everywhere else on the station. Just open the door, walk in and pipe away.
If you fear someone turning on the scrubbers whilst you're there, that's what magboots are for.
This is just giving research unlocks to engineering roundstart. The only reason atmos has them roundstart is so they have an actual job.

Consider alternative approaches to this. Perhaps a subtype of the holofan that's unlocked earlier, but can only project one tile at a time? Or if you really want, delete atmos and merge engineering and atmos into one big job.

**Comment by Oscari-pog** [comment]
Or add the tiny fans (such as the mining shuttle gets) in the spots

**Pull request closed without merging**
