### PR TITLE
[Modular] Puts a 30 hour time-gate on department guard jobs

### PR DESCRIPTION
**Pull request by desertmote**
## About The Pull Request

What it says on the tin, you must be familiar with security and their gameplay loop to play departmental guard.
(Disclaimer: I can't actually test this, so I do not know if its truly 30 hours)

## How This Contributes To The Skyrat Roleplay Experience

No, departmental guards are not security, **but**:
As proven by the game's state, they do interact with the sec/antag gameplay loop. Because of this, they must be knowledgeable on how to prevent overstepping into security officer territory, and how to handle antags and the like without over-escalating further than the guard role is supposed to.

Department guards currently can play without ever having been an officer, it lures in inexperienced players who then gain a false sense of authority and abuse it. By having to play as officer they will be forced to interact with security policy and corp regs.
That way when they are familiar with their boundaries, they know better how not to cross it.

## Changelog

:cl:
balance: You must have playtime as security officer to play as departmental guard
/:cl:

### CODE REVIEW

**Comment by dawsonkeyes** [comment]
based and not-a-security-officer pilled

**Comment by Zonespace27** [comment]
Not a fan. Dept guards are explicitly "not sec", requiring sec hours takes it in the opposite direction

**Comment by desertmote** [comment]
> Not a fan. Dept guards are explicitly "not sec", requiring sec hours takes it in the opposite direction

They can be 'not sec' even better once they actually know what it means to be sec.
I know the intention of department guards, but they have not been living up to the concept.

**Comment by Stonetear** [comment]
I don't play security for ideological reasons.

I just like to defend my department and rescue scientists from their creations when their experiments backfire on them.  This seems like some kind of reactive PR based on someone's experience in a single round, and not reflective of the departmental guard experience as a job: defending your department against wierdos, letting roboticists into toxins so they can make BZ, letting engineers into atmos to grab a tank, or letting medical staff into chemistry for tools.

**Comment by softcerv** [comment]
>By having to play as officer they will be forced to interact with security policy and corp regs.
That way when they are familiar with their boundaries, they know better how not to cross it.

Nothing in the Security Policy mentions Departmental Guards needing to follow corp regs or other security policy. They are not security nor are they expected to answer to security. Here is what they are expected to do:
>
     Your duties as a guard are as follows:
    Remove or detain trespassers and disruptive individuals from the department.
    Report those mentioned above to security or hand them in if you detained them.
    Ensure that the members of the department are safe and in good health.
    Respond to calls from your respective head or department members.
    Use your limited knowledge to aid the department in case of emergency.

If you wanted to add a playtime requirement, it would most likely be better to add a departmental requirement rather than security.

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
I'd be fine with a crew time or dept time requirement, but not security

**Comment by desertmote** [comment]
> This seems like some kind of reactive PR based on someone's experience in a single round

You should mention what makes you think this because it is absolutely not the case. I don't make PRs 'based on a single round', ever; and frankly I find the accusation insulting.



> I'd be fine with a crew time or dept time requirement, but not security

Completely changes the PR's intention. Dep guard is sec+ in its current state, so I made them have to know how to sec. Making them play more of the department they already know how to play (i.e orderly who knows all of medical) will solve nothing and actually make them even more inclined to jack-of-all-trades their department while having a lethal gargo gun on green.

**Comment by Iamgoofball** [comment]
dep guard is not, in fact, "sec+"

security policy and corp regs are not a part of their job, they don't enforce space law nor do they enforce security policy, they have a carveout for good faith cooperation with security but that's the same as every other job on the station

**Comment by Iamgoofball** [comment]
>As proven by the game's state, they do interact with the sec/antag gameplay loop. Because of this, they must be knowledgeable on how to prevent overstepping into security officer territory, and how to handle antags and the like without over-escalating further than the guard role is supposed to.

they interact with the """"sec/antag""""(security are not the only people allowed to interact with antagonists, by the way) gameplay loop in the same way that the rest of the crew does

>Department guards currently can play without ever having been an officer, it lures in inexperienced players who then gain a false sense of authority and abuse it. By having to play as officer they will be forced to interact with security policy and corp regs. That way when they are familiar with their boundaries, they know better how not to cross it.

department guards don't enforce corporate regulations or abide by security policy because they aren't security

they enforce kicking troublemakers out of the department, keeping their coworkers safe, and doing what their head of staff and the captain says to do

**Comment by desertmote** [comment]
You can keep telling me 'they are not sec' in every way imaginable, but they still act like it in the game. They make arrests, they carry equal or higher caliber weaponry, they take down antagonists. Not just in one round, I'm seeing it happen, and I'm talking to people who see it happen, and have been for weeks.

**Comment by Iamgoofball** [comment]
>They make arrests

they can detain people in their department and kick them out the front door, if they're roaming the hallways busting people then sure that's a problem but their toolkit inherently punishes that kind of playstyle

>they carry equal or higher caliber weaponry

everyone does, welcome to guncargo

>they take down antagonists

anyone is allowed to take down an antagonist, antagonists don't have special protections that means nobody but sec can kick their ass if they get into a fight

**Comment by desertmote** [comment]
> > They make arrests
> 
> they can detain people in their department and kick them out the front door, if they're roaming the hallways busting people then sure that's a problem but their toolkit inherently punishes this
> 
> > they carry equal or higher caliber weaponry
> 
> everyone does, welcome to guncargo
> 
> > they take down antagonists
> 
> anyone is allowed to take down an antagonist, antagonists don't have special protections that means nobody but sec can kick their ass if they get into a fight

I don't understand why you are pretending like validhunters don't exist, and especially so on a role where players are encouraged to enforce authority without any of the usual policy. You do know that dep guards are patrolling maintenance like officers do, right?

**Comment by Iamgoofball** [comment]
validhunters are a universal constant of ss13 and it's why we have admins, i'm not pretending they don't exist, i'm just not mentioning them because it's a known issue with every job in ss13 and why we have admins

a department's maintenance is part of it's department, it's why we call them department maintenance tunnels, it's entirely reasonable for them to be in there and be working in there, it's space department staffers can inhabit and need to work in occasionally so there's no reason for them to not have authority over it when it's part of the department

i feel like there's some underlying fundamental misunderstanding of the nature of what a department is going on here

**Comment by desertmote** [comment]
I'm going to quote a piece of what I just posted which you didn't mention a response to, and will leave the PR with that.

> especially so on a role where players are encouraged to enforce authority without any of the usual policy.

**Comment by Iamgoofball** [comment]
>especially so on a role where players are encouraged to enforce authority without any of the usual policy.

the authority they have is the same authority any department staffer has to exert the wills of their department and their department head, they just have the tools to do so effectively

**Pull request closed without merging**
