### PR TITLE
[Semi-Modular] Adds Shipstation, an entire station... on a shuttle.

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Based on Paxilmaniac's Original PR for /tg/: https://github.com/tgstation/tgstation/pull/53185
A 19 player (If all modes are taken into account, skyrat only has one problematic gamemode for this map at the moment, which is families. In other words, 39 players!), ultra-lowpop map where the entire station is situated on a shuttle - with some minor exceptions. Captains here need to be trained to make sure the whole crew is onboard, and crew, likewise, need to **get on when it's time to leave.** Has been heavily playtested in the state I'm PRing it, a notable round even having a traitor steal the real whiteship to engage the station in kidnapping / combat. A quirk of this specific map is that roundstart a head of staff will have to link the lathes and ORM to the ore silo, but it's not detrimental.

This map also includes a MAP SPECIFIC JOB - The Shuttle Pilot. Their job is to the captain away from the captain - maintaining the ship and flying it when all crew is on-board.
Screenshots:
The Ship Itself
image
Space Dock 32, Where the ship starts
image

Shuttle Pilot In-Game
image

**Important for admins: What to do if the shuttle gets destroyed?** - Typically this'd result in a roundend scenario where the captain calls the emergency shuttle, but sometimes, shit just happens. Landing on a colossus or a bombing or chemistry 'accident' or what have you is a fact of life, and it shouldn't stop the round or roundend anyone onboard. Here's how to recover quickly and efficiently.

1).Move any and all corpses or survivors back to the dock via droppods. People who were dusted or similar can be respawned via a control click.
2).After checking to confirm **no bodies remain,** open the shuttle manipulator (admin, events), click on templates, and scroll down to 'station'. Select the NTSS 'Companionship'. Click Modification, then replace.

## Why It's Good For The Game
Map variety is good! We also need a dedicated lowpop map, methinks, and ShipStation is perfect for even 8 player sessions.

## Changelog
:cl:
add: ShipStation. An entire station for you, and 38 other spacemen!
/:cl:

### CODE REVIEW

**Comment by NotRanged** [comment]
This looks really cool but... Our lowpop is like, 40 people.

**Comment by unit0016** [comment]
I based the map pop requirements on /tg/'s mode minimums. I know most are disabled, but Families, the one mode on skyrat this map wouldn't work with, could trigger if I set it higher than 39. Making the adjustment up to that number, though!

**Comment by dawsonkeyes** [comment]
it's not the omegaultrasuperdupermaximum lowpop map that is 10x10station but it's awesome all the same

**Comment by unit0016** [comment]
Also, due to how.. experimental this is. I'd recommend a testmerge.

**Review by Gandalf2k15 — APPROVED** [review]
Approved for Test Merge. I will update the server config accordingly.

**Comment by KathrinBailey** [comment]
I don't think we're ready for this until we have a much bigger wealth of high-quality space ruins. It's not too great for highpop, which we perpetually are.
Some issues that I'd call hard requirements to be fixed before this becomes something that isn't a test/event.
1.
image
Reinforced walls are being used almost everywhere, there's no need for them over normal walls.
2. Shuttle needs cryo pods on it if the crew are intended to stay there, ideally.
3. Security holding cells on the ship need to use timers.
4. Asteroid docking station thingy needs a whole bunch of dorms.
5. Airlocks **MUST** be on the outside of the ship so it can actually dock properly to other things.
image
Airlock needs to be one tile to the left here.

Things that I'd love to see that would be improvements to make this much more desirable and give it the potential to be an in-rotation map.
• Station could have some of the more passive stay-in-department jobs brought there, or have larger versions there. Service should probably have a full comfortable presence on the station, and a minor more utilitarian presence on the shuttle.
• Xenobio and other parts on the station Z level should be connected.

**Comment by KathrinBailey** [comment]
Oh, the station actually needs functional atmos.

**Comment by unit0016** [comment]
It'd probably be best to rebuild the map from the ground up for those changes, honestly, I had enough trouble slapping all the shuttles onto the station.

**Comment by unit0016** [comment]
Rebuilt!

**Comment by unit0016** [comment]
I forgot to add the landmark for the pilot, adding it quickly. Map should be good again, only thing it's lacking is Atmospherics (while I won't be able to cram a full atmos system with N2o and Plasma tanks in, I will hook up the N2 and O2 tanks!)

**Comment by unit0016** [comment]
Donezo.

**Comment by unit0016** [comment]
Should mention, yes, small issue with the digitigrade sprites for the pilot's jumpsuit. I'm not sure how to fix it.

**Comment by unit0016** [comment]
Took a look at the blueshield module for a fix, it's done. Should be ready for another test now?

**Comment by unit0016** [comment]
The merge conflict is fixed (just won't be considered so automatically), I added the missing icons from the base repo. Safe to overwrite.

**Comment by Gandalf2k15** [comment]
Please check the conflicting files

**Comment by unit0016** [comment]
I did. I added the comms officer icon back in while keeping the shipstation ship pilot one. Is there something I'm missing?

**Comment by unit0016** [comment]
I rechecked to confirm. Yes, the merge conflict is bull. I'm doing some mumbo jumbo to fix it.

EDIT ; Nope, using the card.dmi skyrat's currently using and adding the changes on doesn't change the file at all from it's current state. Merge conflict will have to be manually resolved, something I am incapable of doing.

**Comment by unit0016** [comment]
I found the problem and the conflict is gone.

**Comment by Gandalf2k15** [comment]
update from master and clear conflicts, then we can full merg this.

**Comment by unit0016** [comment]
Done - did some reorganizing of card.dmi while I was in there, everything should be in the correct section now, weh.

**Comment by unit0016** [comment]
Updated to fit with the sec overhaul too, henk.

**Comment by Gandalf2k15** [comment]
Update with the recent type path thingies

**Comment by unit0016** [comment]
Got it, doing that

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by ghost** [comment]
what did you do to my baby

**Comment by Fikou** [comment]
no its my baby

**Comment by unit0016** [comment]
> what did you do to my baby

It's on life support after the crash, it probably isn't going to make it. It may be best to say your goodbyes.

**Pull request merged**
