### PR TITLE
Removes Clowns and ERP

### PR DESCRIPTION
**Pull request by NullDagaf**
hahaha you got bamboozled it actually removes the clown ERT and the ERP ERT

i don't need to say why it's good

### CODE REVIEW

**Comment by SpookyTheFox** [comment]
I rather like those, and they are adminbuse only to begin with. They should stay.

**Comment by Draganfrukts** [comment]
Cringe PR, I should not explain why!

**Comment by NullDagaf** [comment]
> I rather like those, and they are adminbuse only to begin with. They should stay.

Yes, they're exclusive to adminbussing. No, I don't trust admins not to abuse them.

**Comment by Gandalf2k15** [comment]
Eh, no, we're not removing admin bus tools, no reason to, if staff can't be trusted with the tools, then we deal with them. Never blame your tools.

**Comment by NullDagaf** [comment]
> if staff can't be trusted with the tools, then we deal with them

I'll hang that quote on a wall.

**Pull request closed without merging**
