### PR TITLE
[MODULAR] [FANTASTIC] Blueshift has a paddy mech now

### PR DESCRIPTION
**Pull request by W4rd3nn**
## About The Pull Request
I put da paddy in da brig call it patty cake

also can we get a tag for like... PRs that make stuff from upstream appear downstream but arent mirrors ;3

## How This Contributes To The Skyrat Roleplay Experience
it doesnt it actually makes it 100000x worse

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
https://github.com/Skyrat-SS13/Skyrat-tg/assets/12723348/fbc9b6b7-0710-427d-b2de-eb46b06aa7a1

</details>

## Changelog

:cl:Motho
fix: NanoTrasen remembered to equip the NSV Blueshift with an APLU Paddy.
/:cl:

### CODE REVIEW

**Comment by W4rd3nn** [comment]
haha commit history

**Comment by W4rd3nn** [comment]
wait hold on i left a silly lil floating fire alarm

**Comment by W4rd3nn** [comment]
okay NOW you can speedmerge :3

**Comment by vinylspiders** [comment]
Was this yellow stripe intentional? 

image

Otherwise, looks good to me! @Jolly-66 ?

**Comment by W4rd3nn** [comment]
> Was this yellow stripe intentional?
> 
> image
> 
> Otherwise, looks good to me! @Jolly-66 ?

Noooo….

Frick. Gimme a bit

**Comment by Iajret** [comment]
you also misrotated mechcharger in cargo. At least according to mapdiff bot

**Comment by W4rd3nn** [comment]
> you also misrotated mechcharger in cargo. At least according to mapdiff bot

i hate SDMM

**Comment by W4rd3nn** [comment]
Okay now its sexy and fixed. Yippee

**Review by vinylspiders — APPROVED** [review]

**Comment by vinylspiders** [comment]
image

Just remember to make a new branch next time. Less chance of things like the random yellow stripe getting picked up from before that way.

**Comment by W4rd3nn** [comment]
> image
> 
> Just remember to make a new branch next time. Less chance of things like the random yellow stripe getting picked up from before that way.

dis was cuz i edited a prefab, not cuz i used da same branch :3

**Pull request merged**
