### PR TITLE
Ports Outpoststation from Unitystation

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
After several months of work, an abandoned project, and my own laziness leading to the total lack of care in certain spots (cough cough, atmos), Outpost has been FULLY FUNCTIONALLY ported to byond. I would've PR'd this upstream, but the guy who was porting Omega to modern /tg/ has proven they don't like new maps and, apparently, want only four in the pool at a time. It also adds an emergency shuttle, given it's own shuttles.dm file (hopefully) in compliance with the modularization protocols? The one missing feature of the map is toxins, which will be added Soon:tm:. Atmospherics is messy, as well, seeing as it's where I crammed the gravity generator and telecomms, but it shouldn't pose a gameplay problem.

## Why It's Good For The Game
In my opinion, map variety is great! Outpoststation is a regular favorite on Unitystation and quite polished, and while we don't have the shuttle systems they do, the map is bound to be just as good regardless.

## Changelog
:cl:
add: Outpost model stations have been retrofitted to be launchable in your sector.
add: The Outpost Station Emergency Shuttle has been, likewise, retrofitted to comply with modern Docking Standards.
config: Added Outpost to the configuration and maps.txt
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
👀

**Comment by ShadeAware** [comment]
Yo
This shit kinda good doe :eyes:

**Comment by Gandalf2k15** [comment]
This requires a map merge and convert. ensure the areas are correctly formatted too. Please see the travis error for more information.

**Comment by unit0016** [comment]
Noted. Something was wrong with the python script for me, so I'll just do it manually. Going to whip out a few of the stated adjustments along with that, then it'll probably be ready for some live-fire testing.
oh, and adding bolts to the dorm rooms. That's marginally more important, hah.

**Comment by unit0016** [comment]
Ah shit, Travis CI check failed again, that's not good. Not sure what I fucked up, though.

**Comment by unit0016** [comment]
Honestly I'd like someone else with a bit of experience to look in at where the hell this has broken. Regardless, going to work on polishing maintenance up to the standards delta station set a bit while this happens.

**Comment by unit0016** [comment]
Moving the project elsewhere due to 'external factors'.

**Pull request closed without merging**
