### PR TITLE
[NONMODULAR] Nerfs stealth implant

### PR DESCRIPTION
**Pull request by FlamingLily**
## About The Pull Request
5 seconds to cloak

## Why It's Good For The Game
Stealth implant is an infinite, un-counterable in it's current state get out of jail free card

## Changelog
:cl:
balance: Stealth implants are slower
/:cl:

### CODE REVIEW

**Comment by Seris02** [comment]
5 seconds is a bit too much, how about something like 
2 seconds to cloak
and make it take like 2 seconds to actually activate it

**Comment by FlamingLily** [comment]
> 
> 
> 5 seconds is a bit too much, how about something like
> 2 seconds to cloak
> and make it take like 2 seconds to actually activate it

That's 4 seconds total. 1 second difference.

**Comment by Seris02** [comment]
It's the fact that it splits it that makes a difference. The cloaking can happen even if you accidentally touch a wall or something, then it would take 5 seconds again, which is too much. But if you make it take time to activate instead, then it'll be more fair, and it won't be an instant 'haha now I'm invisible', as well as not having to wait 5 seconds for it to recloak every time you touch a wall.

**Comment by FlamingLily** [comment]
> 
> 
> It's the fact that it splits it that makes a difference. The cloaking can happen even if you accidentally touch a wall or something, then it would take 5 seconds again, which is too much. But if you make it take time to activate instead, then it'll be more fair, and it won't be an instant 'haha now I'm invisible', as well as not having to wait 5 seconds for it to recloak every time you touch a wall.

It only reveals you if you bump into a living atom

**Comment by SpaceVampire** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/6429
Balance change during a feature freeze again? 🤔 
But really. I feel like it would it be better to increase the activation time instead.
So that it is still as useful for sneaking around once you are inside of it. But less of an escape tool.
Five seconds really is a bit too much for this kind of change. More than double what it was before.

**Comment by ForrestWick** [comment]
The stealth box is also easy to counter since all you need to do is close a few doors

**Pull request closed without merging**
