### PR TITLE
Guns Galore: SCAR-L

### PR DESCRIPTION
**Pull request by LeonY24**
## About The Pull Request

One more new gun for gunsgalore base. Fed by M16 magazines, which are now renamed to "5.56 magazine"'s, since it's not exclusively for M16's anymore.
image
image
image
image
image
image

Sprites are done by myself, based of M16 sprites, recolored and reshaped.

## How This Contributes To The Skyrat Roleplay Experience

Getting prepared to renovate and make away missions better.

## Changelog
:cl:
add: SCAR-L assault rifle.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
556 is getting changed to .277 Aestus in #13138

**Comment by Stalkeros2** [comment]
We surely don't need another M16 for any of the away missions I am planning to work on, at least for now.
A 7.62 rifle (*wink wink* SCAR-H *wink wink*) would be better tho.

**Comment by LeonY24** [comment]
> We surely don't need another M16 for any of the away missions I am planning to work on, at least for now. A 7.62 rifle (_wink wink_ SCAR-H _wink wink_) would be better tho.

speaking of another m16 it's more like another modern m16 with faster firerate, and speaking of scar-h it'd be a gun which would fuck harder and more rough than AK, are you sure you want another _ou-pee weapon that is imbalanced_

**Comment by LeonY24** [comment]
> 556 is getting changed to .277 Aestus in #13138

5.56 is no more

**Pull request merged**
