### PR TITLE
interlink and escape shuttle change

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
instead of escape shuttle at CC, it is at interlink.
changes interlink a little...
image

## How This Contributes To The Skyrat Roleplay Experience
Continuity between interlink and the station. You arrive from interlink, you leave to interlink.

## Changelog

:cl:
add: Set the escape shuttle to interlink, rather than CC
add: Changed the layout of interlink
/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
How will this work with EORG?

**Comment by YakumoChen** [comment]
That doesn't make sense. Why have an escape shuttle in the first place if you can just use arrivals?

**Comment by SpaceVampire** [comment]
So in order to get on the escape shuttle, you would first have to ride all the way back to the interlink?
I also worry this could break a couple of the escape shuttles from being able to be used.
Along with making the whole escape area feel weird and out of the place on all of the maps.
It is also weird if you want to pull anything escape related as an antag. Due to that not being allowed on the interlink.

**Comment by YakumoChen** [comment]
> So in order to get on the escape shuttle, you would first have to ride all the way back to the interlink?

No it lands at the interlink after it leaves the station

**Comment by SpaceVampire** [comment]
> No it lands at the interlink after it leaves the station

Oh, does it? Yeah. That makes sense, after re-reading the PR.
This is what happens when you post too late into the night.

In that case, I'm just going to point out that having two shuttles going to the same location still feels pretty weird.
Along with the fact that it seems this will have to come with some change in policy.
Due to interlink being the calm location, and CC being the funny fighting location.
Especially with how some staff would set up end round stuff there.

**Comment by jjpark-kb** [comment]
> How will this work with EORG?

EORG will be removed and not allowed.

> That doesn't make sense. Why have an escape shuttle in the first place if you can just use arrivals?

Because alternatives are fine, we don't all have to use the escape shuttle.

> In that case, I'm just going to point out that having two shuttles going to the same location still feels pretty weird.

Sure, it might feel weird at first, but I am sure we will all get used to it.

> Along with the fact that it seems this will have to come with some change in policy.

Yep, we are still discussion policy. That is why this is not merged yet. Though the end result will be no more EORG.

> Due to interlink being the calm location, and CC being the funny fighting location.

It will remain somewhat calm, chill. I personally don't see Skyrat needing EORG.

> Especially with how some staff would set up end round stuff there.

Now they can set up harmless, good stuff at interlink.

**Comment by YakumoChen** [comment]
This removes all immersion of the importance of the escape shuttle and the entire point of it being an emergency shuttle if it's literally nothing but a glorified, oversized, longer-wait arrivals shuttle.

How does this contribute to the Skyrat Roleplaying Experience?

Other feedback:
-This severely reduces the quality of the dorms area
-Interlink now has a public-access medbay with tons of medical stuff and _literal wands of healing_ and this is going to be extremely difficult to police people who loot it on spawn

**Comment by jjpark-kb** [comment]
> This removes all immersion of the importance of the escape shuttle and the entire point of it being an emergency shuttle if it's literally nothing but a glorified, oversized, longer-wait arrivals shuttle.

Valid concern.

> -This severely reduces the quality of the dorms area

Subjective. Explain how it reduces the quality of the dorms.

> -Interlink now has a public-access medbay with tons of medical stuff and literal wands of healing and this is going to be extremely difficult to police people who loot it on spawn

Nope. Has a shift-ending pad door. That medical (as well as bar) is only accessible once the round ends.

**Comment by Suspect-One** [comment]
I still don't understand why I'll have to wait for the emergency shuttle if I can just leave the station through arrivals and get to the Interlink any way. 

And what about the escape pods?

**Comment by YakumoChen** [comment]
>Subjective. Explain how it reduces the quality of the dorms.

You removed all the premium cabins with food and bathrooms, and left only the tiny bedrooms

They also just look bad. You put a chair in a corner next to a bed and table. That's just terrible interior design.

**Comment by YakumoChen** [comment]
>Nope. Has a shift-ending pad door. That medical (as well as bar) is only accessible once the round ends.

That just wraps back around to the issue of the base design being nonsensical just to cater to rounded being there

**Comment by YakumoChen** [comment]
>Nope. Has a shift-ending pad door. That medical (as well as bar) is only accessible once the round ends.

That just wraps back around to the issue of the base design being nonsensical just to cater to rounded being there

**Comment by Tastyfish** [comment]
This fundamentally shatters all of the gameplay mechanics that center around delaying or denying the escape shuttle, including several game modes. If I'm a traitor, can I speedrun all of my objectives and then leave on the arrivals shuttle back to the interlink 30 minutes into the round? If not, how is that different than leaving on the escape shuttle to the same destination?

**Comment by PCPort** [comment]
Way to... Trivialize the escape shuttle and remove the sense of urgency from round-ending catastrophies, since you can just take the Interlink shuttle and have it arrive at the same place anyway.

This all feels very... Hugbox-y. Skyrat's an MRP-HRP server, not a consequence-free adult sandbox.

**Comment by PCPort** [comment]
Also, EORG's an SS13 staple. Why ban it? Is there actually a demand for the removal of EORG, and is it an actual sizable majority of people that want it removed? I somewhat doubt that this change isn't based solely on your personal preferences.

**Comment by jjpark-kb** [comment]
> This all feels very... Hugbox-y.

I don't see how this is hugbox. This is just making escape shuttle go to interlink rather than CC.

> Also, EORG's an SS13 staple.

Calling EORG a staple is a bit stretched; and really, we don't need to follow the status quo on it.

> Why ban it?

Because EORG is awful and should not be on Skyrat. If you need to take out your OOC frustrations on someone, take a break and then come back on. 

> I somewhat doubt that this change isn't based solely on your personal preferences.

Uh, sorry, no. There are plenty of people who want EORG removed.

**Comment by PCPort** [comment]
> Uh, sorry, no. There are plenty of people who want EORG removed.

I'd love to meet them! Maybe we should do a community vote, being able to see what everyone's opinions on the matter are would be very interesting

**Comment by hugmeorelse** [comment]
> > Uh, sorry, no. There are plenty of people who want EORG removed.
> 
> I'd love to meet them! Maybe we should do a community vote, being able to see what everyone's opinions on the matter are would be very interesting

How about this isn't the place for it? This is not for debating whether you like it or not. 

We're not doing a community vote. We do not do that, and we do not plan on starting that either.

**Comment by hugmeorelse** [comment]
> > Uh, sorry, no. There are plenty of people who want EORG removed.
> 
> I'd love to meet them! Maybe we should do a community vote, being able to see what everyone's opinions on the matter are would be very interesting

How about this isn't the place for it? This is not for debating whether you like it or not. 

We're not doing a community vote. We do not do that, and we do not plan on starting that either.

Let me explain a few things here for people.

We are getting rid of EORG. This was a near unanimous vote by staff beforehand. This isn't the first time we've tried to address the EORG question. I have rubber stamped that vote and have given it the go-ahead. For starts, it does not thematically fit what we ultimately want to do with the server.

We are a roleplay server first. We may use TG as our upstream , but we are not "furry TG" as some may believe. If you are here for that reason, you are here for the wrong reasons. I am not here to cater to you if so. I apologize for any wasted times, but you are not my target audience to be brutally frank. You do not make up the majority of the server. We have tried this experiment, and it failed.

As for the Interlink, we decided to use it for two reasons. Firstly, this is to allow people to roleplay after the round ends, especially if a staff member needs to handle tickets. EORG is fun for a moment, but you're dead for a while afterwards. Here, you can continue to do what you want. We also want to clamp down on people doing LRP memes on the shuttle, just because they think the round is over.

For this purpose, we need an area people can interact with after the round. Instead of using Central Command, which would need a major overhaul and is only ever used at the end of the round, we decided to augment Interlink further instead. This reduces the amount of maintenance the maintainers have to do on the map, and it ensures changes are maintained with every map resets. We get to re-use assets, and it makes sense. People come to the station through the Interlink, and they go back home through the Interlink. 

This isn't a move to "hugbox" the server, **especially since we literally have a streamlined way to approve antagging without actually being a traditional antagonist role.** Like, we are looking to create more conflict. If this happens to magically dampen the antagging that happens near the shuttle, just know that most people complain that the action happens too much near the end, especially near the shuttle. They would much prefer the antagging and the action to be done all throughout the round, as that would be way more exciting than someone's last ditch attempt to antag near the end of the round. So, again, I fail to see how this hugboxes the server.

**Comment by jjpark-kb** [comment]
Someone said they will make a better version.

**Pull request closed without merging**
