### PR TITLE
Adds two new public plushies to the loadout 

### PR DESCRIPTION
**Pull request by DuffCreeper**
## About The Pull Request

Adds two new plushies of certain crew that are publicly available to everyone at the backpack toy loadout menu

## Why It's Good For The Game

Because marketable plushies
https://i.imgur.com/Pm3zIbD.png

## Changelog
:cl:
add: New tab in backpack loadout for plushies to prevent clutter of random plushies
add: Two new plushies of a certain moth and deer
add: Sound file of baby deer to said deer plush interact
fix: deerplush.ogg was found to be corrupted and now fixed, plushies meant to use the sound file have been uncommented due to the fix
add: Plushies found in the modular plush file have been added to the plushie loadout tab
add: new musical moff that is extremely sus
add: two modular files for instruments in `modular_skyrat\modules\customization` 
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
I kind of feel like we shouldn't flood loadout with non-generic items for specific people...

The loadout doesn't even have the generic ones, at that.

**Comment by DuffCreeper** [comment]
> I kind of feel like we shouldn't flood loadout with non-generic items for specific people...
> 
> The loadout doesn't even have the generic ones, at that.

Can always make a new loadout tabs for plushies specifically actually, saves cluttering normal stuff with plushies like these

**Comment by YakumoChen** [comment]
Just port the Plush Choice Box from Citadel and you can avoid all of these problems.

**Comment by YakumoChen** [comment]
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12750

**Comment by DuffCreeper** [comment]
> [Citadel-Station-13/Citadel-Station-13#12750](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12750)

Actually wouldn't be a bad idea. But I'm too smooth brain to port features *dab

**Comment by H0gberg** [comment]
> > [Citadel-Station-13/Citadel-Station-13#12750](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/12750)
> 
> Actually wouldn't be a bad idea. But I'm too smooth brain to port features *dab

Too bad porting eet is a better idea

**Comment by WTFIsmyname** [comment]
> I kind of feel like we shouldn't flood loadout with non-generic items for specific people...
> 
> The loadout doesn't even have the generic ones, at that.

We have fuckloads of plushies for specific people. TF are you talking about.

**Comment by YakumoChen** [comment]
> 
> We have fuckloads of plushies for specific people. TF are you talking about.

They're putting these plushies in the loadout.

**Comment by WTFIsmyname** [comment]
> > We have fuckloads of plushies for specific people. TF are you talking about.
> 
> They're putting these plushies in the loadout.

We have multiple solutions for this.

**Comment by DuffCreeper** [comment]
> > We have fuckloads of plushies for specific people. TF are you talking about.
> 
> They're putting these plushies in the loadout.

And now they're in their own subcategory

**Comment by YakumoChen** [comment]
I'm saying that donator plushies have no real sense being in the loadout (they're only really going to be enjoyed by one or two specific people), and that you should be putting generic plushies only in the loadout (the deer and moth plushies are not in the loadout, but these very specific character plushies are?)

Or better yet, just atomize this PR and just add the plushies only.

I'm not sure if these plushies are of OP's characters in which case this PR is entirely self serving because "I want to be able to have my own, unique toys at roundstart"

**Comment by DuffCreeper** [comment]
> I'm saying that donator plushies have no real sense being in the loadout (they're only really going to be enjoyed by one or two specific people), and that you should be putting generic plushies only in the loadout (the deer and moth plushies are not in the loadout, but these very specific character plushies are?)
> 
> Or better yet, just atomize this PR and just add the plushies only.
> 
> I'm not sure if these plushies are of OP's characters in which case this PR is entirely self serving because "I want to be able to have my own, unique toys at roundstart"

One is of mine, the other is of a friend. I plan on porting some oldbase plushies over once this is committed since I need to find out who actually plays and so forth. I seriously do not see a problem with just throwing these plushies in the loadout for the few people who might know the person and have it as an option. With the recent commit it is now out of the way in its own tab.

Either way the generic plushies are in the game and able to be used, but I can push another commit to add them to the loadout menu

Plus in old base you forget we had this exact same thing, people with their OCs in the game as plushies, who is going to select those? I don't know but they were in the game to begin with since it hurts nobody. Stop trying to make an issue where there is none, this is a harmless PR that adds plushies

**Comment by YakumoChen** [comment]
I've never said once I've had a problem with player plushies in the game. My only beef is that they're bloat to the loadout menu when they're entirely self-serving to the less than three people who will ever decide to loadout with each one. 

The generic variants have at least the benefit of being, as I said, generic, and joe schmoe having the option to loadout with Specific Player Deer Plushie but without the option of loading with Generic Deer Plushie doesn't make sense.

Loadout items are supposed to be common items people will pick to customize, player/ckey specific items shouldn't be in that list unless they're behind some convienence like a choice box where everyone can choose their own snowflake toy without filling up loadout with bloat, or a donator / ckey specific list where people won't have to see it if it's not their special item.

**Comment by YakumoChen** [comment]
Not to mention the reasons behind the PR are just plain disingenuous. "I made the plushies available to everyone" is just hiding the real reason, "I want to have it round start for myself"

**Comment by WTFIsmyname** [comment]
> Not to mention the reasons behind the PR are just plain disingenuous. "I made the plushies available to everyone" is just hiding the real reason, "I want to have it round start for myself"

And?

**Comment by YakumoChen** [comment]
> 
> 
> > Not to mention the reasons behind the PR are just plain disingenuous. "I made the plushies available to everyone" is just hiding the real reason, "I want to have it round start for myself"
> 
> And?

>worsens the quality of the code
>refuses offered solution because 'lol lazy'
>needless bloat in loadout literally nobody but 2 people want
>"and?"

**Comment by DuffCreeper** [comment]
> > > Not to mention the reasons behind the PR are just plain disingenuous. "I made the plushies available to everyone" is just hiding the real reason, "I want to have it round start for myself"
> > 
> > 
> > And?
> 
> > worsens the quality of the code
> > refuses offered solution because 'lol lazy'
> > needless bloat in loadout literally nobody but 2 people want
> > "and?"

1. Code is literally the same as everything else
2. You're expecting someone who can't code to somehow port said solution
3. Bloat is contained in it's own category which now includes other plushies
4. And?

**Comment by WTFIsmyname** [comment]
> > > Not to mention the reasons behind the PR are just plain disingenuous. "I made the plushies available to everyone" is just hiding the real reason, "I want to have it round start for myself"
> > 
> > 
> > And?
> 
> > worsens the quality of the code
> > refuses offered solution because 'lol lazy'
> > needless bloat in loadout literally nobody but 2 people want
> > "and?"

It's plushie code. Its not gunna ram the tidi by even a single percent. The solution is fine. We had like 20 personalised plushies on old code with no issue. I realise you hate fun Chen, but can you just stop? There is literally nothing wrong with this pr beyond your hate or someone having a personalised thing in game. Shit.

**Comment by YakumoChen** [comment]
Arguing about this further is dumb. Do what you want, I guess. Just be consistent about it at least though.

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by Gandalf2k15** [comment]
Good that you put them in their own subcategory!

**Pull request merged**
