### PR TITLE
[MIRROR] Removes lean [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/65464
--------------------

## About The Pull Request

Removes lean, its sprite, and all appearances of it in code.

## Why It's Good For The Game

Lean is an annoying, overused flavour of the month meme, totally devoid of character or originality. The only reason for it to exist here is because somebody saw it once, giggled for a few milliseconds, and made a maintainer giggle for a similar length of time.

It serves no useful gameplay purpose, and which I have never personally seen even being used, yet its mere existence empowers and legitimises people to reach sometimes borderline OOC in IC levels of talking about lean, safely protected by the shield of lean existing as an ingame thing regardless of how rarely seen.

Due to this ability to cover for annoying behaviour, its rarity and its lack of functional purpose in gameplay when actually made, I do not see any way in which lean existing is not a net negative.

tl;dr lean sucks

## Changelog

:cl:
del: Lean has been removed entirely from the game
/:cl:

### CODE REVIEW

**Review by GoldenAlpharex — APPROVED** [review]
I agree, man this was stupid.

**Comment by Zonespace27** [comment]
damn, golden beat me to the auto-merge 😔

**Comment by Blockzzy** [comment]
worst update to ever grace skyrat

**Comment by DriftingSkies** [comment]
MY FUCKING LEAN NOOOOOOOII

**Comment by Blockzzy** [comment]
what next, removing the swag outfit because adminges get bored of it?

**Pull request merged**
