### PR TITLE
[FIX][CI][MDB IGNORE] Updating Stations to NT Safety Standard 35489-A1

### PR DESCRIPTION
**Pull request by ORCACommander**
## About The Pull Request
Updates Skyrat maps to be compliant with external access upstream update

## How This Contributes To The Skyrat Roleplay Experience

Fix CI Failures

## Changelog

:cl:
fix: The Following Stations are now in compliance with NT EVA Safety Protocols Submerged Kilo Station, NSS Journey and Blueshift
/:cl:

### CODE REVIEW

**Comment by ORCACommander** [comment]
@GoldenAlpharex

**Comment by IsaacTheSharkWolf** [comment]
This fix will need to be applied to a newer unreleased version of blueshift, the one you probably have is the old version.

**Review by GoldenAlpharex — APPROVED** [review]
Looks good to me.

**Comment by GoldenAlpharex** [comment]
I'll merge this and help Isaac getting his branch updated instead.

**Pull request merged**
