### PR TITLE
Removes more ERP related items and verbs if ERP is disabled in config

### PR DESCRIPTION
**Pull request by larentoun**
## About The Pull Request

This PR does multiple things, whose objectives are to improve/add more functionality to DISABLE_ERP_PREFERENCES in config.
This PR:
- Removes ERP IC Verbs, such as "Climax", "Toggle Arousal" and "Toggle Genitals";
- Removes ERP items in Initializing stage, making maps ERP-clean;
- Removes ERP organs insertion, even if they somehow were modified in Character Setup before;
- Removes ERP strippable inventory.

Since I'm not the most experienced coder, I would like to know about better practices which could've been used, so I will change things accordingly and more clearly.

## How This Contributes To The Skyrat Roleplay Experience

Servers which disable ERP preferences will see less ERP things in their worlds.

## Changelog

:cl:
expansion: DISABLE_ERP_PREFERENCES in config now removes ERP IC verbs, items, organs and strippable inventory
/:cl:

### CODE REVIEW

**Comment by NX115** [comment]
Interesting. I eagerly await the sequel: removing the station from the map.

**Comment by twilightwanderer** [comment]
ss220 wants to build a magical world without ERP.

**Comment by zipliks** [comment]
> ss220 wants to build a magical world without ERP.

we call it "Russia"

**Comment by twilightwanderer** [comment]
> we call it "Russia"

Ha. The funny thing about "Russia" is that it has Fluffy Frontier. So there's a Shrek swamp in the magical world?

**Comment by zipliks** [comment]
> > we call it "Russia"
> 
> Ha. The funny thing about "Russia" is that it has Fluffy Frontier. So there's a Shrek swamp in the magical world? 
> 

Fluffy Frontier does not exist. It's all gossip and conspiracy theories.

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by ORCACommander** [comment]
I run one of the No ERP downstreams. I appreciate this effort. but I did like having the erp items and rooms for map flavor. Would be better if that was a new sub toggle. oh well Guess i'll write a code overrides in 3-4 weeks

**Comment by larentoun** [comment]
> I run one of the No ERP downstreams. I appreciate this effort. but I did like having the erp items and rooms for map flavor. Would be better if that was a new sub toggle. oh well Guess i'll write a code overrides in 3-4 weeks

I see. I will look into it, shouldn't be much of a problem

**Comment by larentoun** [comment]
> I run one of the No ERP downstreams. I appreciate this effort. but I did like having the erp items and rooms for map flavor. Would be better if that was a new sub toggle. oh well Guess i'll write a code overrides in 3-4 weeks

https://github.com/Skyrat-SS13/Skyrat-tg/pull/13142

**Pull request merged**
