### PR TITLE
Space dragons are now dynamic spawned only

### PR DESCRIPTION
**Pull request by Funce**
## About The Pull Request
Dynamic already has a spawn for space dragons. This just takes it out of event rolling.

## How This Contributes To The Skyrat Roleplay Experience
Dynamic is great

## Changelog

:cl: Foxtrot (Funce)
admin: Space Dragon is now dynamic only
/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
Config has space dragon disabled for dynamic

**Comment by hugmeorelse** [comment]
> Config has space dragon disabled for dynamic

That's the point.

**Comment by GoldenAlpharex** [comment]
> Config has space dragon disabled for dynamic

The goal here would be to enable it through there instead, if we want it.

**Review by GoldenAlpharex — APPROVED** [review]
Looks good!

**Pull request merged**
