### PR TITLE
[MODULAR] Remove this at the right time or the tram will kill us all

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request
Merge this when https://github.com/tgstation/tgstation/pull/71754 is merged.

Our modular changes to the tram mean when https://github.com/tgstation/tgstation/pull/71754 is merged, our tram is gonna be super bloodthirsty unless we remove it. Makes it no longer a modular change, we'll be same as upstream.

## How This Contributes To The Skyrat Roleplay Experience
Medbay will hate us if the tram is doing like 700 brute damage.

## Changelog

:cl: LT3
code: Removed modular code from the tram, reflecting upstream changes to tram collision damage.
/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
unless the lift master multiplies its collision lethality with the tram master's lethality, the upstream PR will change nothing

**Comment by lessthnthree** [comment]
> unless the lift master multiplies its collision lethality with the tram master's lethality, the upstream PR will change nothing

Line 392.

https://github.com/tgstation/tgstation/pull/71754/files#diff-74b820e1e722e132d6b589ab1d9165c4d97e100b55274ece89f3d3fe0464c003

**Comment by RimiNosha** [comment]
You forgot to remove the file from the dme, by the by.

**Comment by lessthnthree** [comment]
> You forgot to remove the file from the dme, by the by.

Yeah, just caught that lol.

**Comment by Funce** [comment]
I swear no bulli, I merged in this PR with the mirror.

**Comment by lessthnthree** [comment]
Nah great if you can combine them into one.

**Pull request closed without merging**
