### PR TITLE
[NON-MODULAR] No OOC Channel Tab-Switching!

### PR DESCRIPTION
**Pull request by RimiNosha**
## About The Pull Request
Ew, why is OOC a cycle-able tab option?

## How This Contributes To The Skyrat Roleplay Experience
Not seeing admin ERP in OOC is nice!

## Changelog

:cl:
del: Removed OOC from the TGUI-Say channel switch function.
/:cl:

### CODE REVIEW

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
👎 If the concern is OOC, remove that from channel incrementation, the feature itself is fine honestly

**Comment by RimiNosha** [comment]
> 👎 If the concern is OOC, remove that from channel incrementation, the feature itself is fine honestly

Done, though I think that code is the best we're getting without risking big edits!

**Comment by Gandalf2k15** [comment]
This type of non modular edit is not acceptable, take this upstream or suggest a preference based system.

**Comment by RimiNosha** [comment]
That's going to take *even more* non-modular edits. Just gonna close on here, and potentially take it upstream if I find the inspiration to.

**Pull request closed without merging**
