### PR TITLE
Randomized exotic seeds crate

### PR DESCRIPTION
**Pull request by yorii**
## About The Pull Request

Randomizes all the seeds in the exotic seeds crate.

## How This Contributes To The Skyrat Roleplay Experience

Makes the crate at least 99% less boring.

## Proof of Testing

<details>
<summary>Screenshot</summary>

image

</details>

## Changelog

:cl:
add: Added random seed contents to the exotic seeds crate.
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
Just one tiny problem with it. The exotic seeds crate is necessary as a reliable source to get Seedlings, which aren't available anywhere else.

**Comment by yorii** [comment]
> Just one tiny problem with it. The exotic seeds crate is necessary as a reliable source to get Seedlings, which aren't available anywhere else.

Ah I see, that's an oversight from my part, I actually pulled this PR out of a different fork of the codebase.
I will try and get a better sense of what loot table works best for Skyrat proper and adjust the items and weight values accordingly.

If anyone is familiar with any more requirements that otherwise would break the game please do inform me :)

**Comment by HoodMilk** [comment]
Also exotic seed crates are the only way to get shrubs and (maybe?) rainbow flowers.

**Comment by vinylspiders** [comment]
You should probably take this upstream, or create a modular version of this that coexists alongside the current one in light of the comments (like maybe a randomized version that is discounted because you don't know what you are getting?).

You could also just alternatively modularly overwrite the list (making it weighted) and override the `fill()` proc in `master_files` like you did here, but without the Skyrat edits. I just am not a big fan of the whole Skyrat edit commenting out entire blocks thing when it can be avoided is all.

**Comment by yorii** [comment]
Closing this in favor of upstream PR: https://github.com/tgstation/tgstation/pull/78565

**Pull request closed without merging**
