### PR TITLE
Fixes being unable to re-select "Quartermaster" as a title after picking any alt-title

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Annoying that you can't go back to the title you want after misclicking an alt title. Especially when Quartermaster is the title you're given by default.

## How This Contributes To The Skyrat Roleplay Experience
This qualifies as a bug fix. Being unable to return to the default is not intended.

## Proof of Testing
image

## Changelog

:cl:
fix: fixed being unable to re-select the "Quartermaster" title in job prefs after selecting an alt-title
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
A whole story in a single image:
image

**Comment by rosextango** [comment]
The change was made to reflect the lore and that you're not supposed to be able to select Quartermaster.

https://github.com/Skyrat-SS13/Skyrat-tg/pull/18670 Here's the pull in question.

**Comment by ghost** [comment]
> The change was made to reflect the lore and that you're not supposed to be able to select Quartermaster.
> 
> #18670 Here's the pull in question.

I am more than aware, I was there during that.
However, **as already stated,** you have **always** been able to select Quartermaster, even after that PR. You could not RE-select it. This is a fix to allow players to re-select a choice that they already had.
Moreover, that PR **was meant to include a Quartermaster title**, per several reviews and the closing approving statement.

**Comment by vinylspiders** [comment]
Yeah, it looks like while the intent was there it was not quite executed completely. It feels like a bug that it still shows up by default until you change it.

**Review by vinylspiders — APPROVED** [review]

**Pull request merged**
