### PR TITLE
wound refactor compatability

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request
Makes https://github.com/Skyrat-SS13/Skyrat-tg/pull/23407 work

## How This Contributes To The Skyrat Roleplay Experience
Refer to the other PR

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
 wow all the wound types work
image

</details>

## Changelog

:cl:
No player facing changes
/:cl:

### CODE REVIEW

**Comment by nikothedude** [comment]
it will be done eventually

**Comment by PawnAtWork** [comment]
Is this for the stuff you're doing on TG? Expanding it onto Skyrat additions?

**Comment by vinylspiders** [comment]
This is for https://github.com/Skyrat-SS13/Skyrat-tg/pull/23407 most likely

**Comment by PawnAtWork** [comment]
Yeah, it's their PR on TG. I guess they're planning to add synth and new species compat.

**Comment by nikothedude** [comment]
back at it

**Comment by nikothedude** [comment]
this should be ready to go, but i suggest test merging the parent PR once this is merged, just because i dont have as much time to comprehensively test this as id like

**Comment by nikothedude** [comment]
changes include: updating our wounds, muscle wounds being a bit rarer (not by much), removing unused splint code, refactoring bodypart aid to be a bit more sane

**Comment by nikothedude** [comment]
ah fuck i gotta complete the pr 1 sec

**Comment by vinylspiders** [comment]
Is this good to fuse with the mirror now? edit: nevermind, I just saw the comment saying it was.

**Review by vinylspiders — APPROVED** [review]

**Pull request merged**
