### PR TITLE
Removes Dogborg Movement sprites with zero shame.

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request

image

## How This Contributes To The Skyrat Roleplay Experience

See above.
## Proof of Testing

They no longer move.
<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog
:cl:
del: Dogborg movement sprites are gone.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
wrong server?

**Comment by theselfish** [comment]
Nope. Upstream from Bubber.

**Comment by Gandalf2k15** [comment]
I didn't think they were a downstream anymore hm

**Comment by thegrb93** [comment]
The movement sprites for some of them are good like drakeborg. If there's a specific bad one, do that instead.

**Comment by SpaceLoveSs13** [comment]
So the reasoning of this pr is solely because Goofball said so? What is your input on this?
Also why not have this fixed instead of removing it completely?

**Comment by theselfish** [comment]
> So the reasoning of this pr is solely because Goofball said so? What is your input on this? Also why not have this fixed instead of removing it completely?

I'm not a spriter, I don't have the money to fork out for this, nor do I want to.
I agree with what Goof said and have nothing to add that he didn't perfectly say.

**Comment by thegrb93** [comment]
I think a lot of people would disagree

**Review by projectkepler-ru — CHANGES_REQUESTED** [review]
This is still missing on why it's a good change. Details please

**Comment by theselfish** [comment]
> This is still missing on why it's a good change. Details please

Barely anything else in this game has movement sprites. And when they do it's something tiny and barely noticeable like the wheels on a medibot.

**Comment by Gandalf2k15** [comment]
not something we're gonna go with

**Pull request closed without merging**
