### PR TITLE
Makes self-surgery a skillchip (TBA)

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

# This is TBA until I get host confirmation

This makes almost all self-surgeries require the TRAIT_BASIC_SURGEON to start, if you don't have this trait then it falls back onto backup checks.

Synthetics can perform self-surgeries on their own chests for self repair.

All antagonists are able to perform basic self-surgeries.

This was made on host request.

## Changelog
:cl:
balance: Self-surgeries is now a skillchip and is given to certain jobs such as the medical doctor, CMO and security medic.
balance: Antagonists can perform basic self-surgeries.
balance: Synthetics can only perform self-surgery on their chest.
/:cl:

### CODE REVIEW

**Comment by Nerev4r** [comment]
What about offstation roles like Ashlanders and whatnot?

**Comment by Gandalf2k15** [comment]
> What about offstation roles like Ashlanders and whatnot?

They count as antagonists afaik.

**Comment by Eclipse-Presence** [comment]
This could pose an issue for roboticists, who could no longer implant or do synthetic revival surgery.

**Comment by Eclipse-Presence** [comment]
> This could pose an issue for roboticists, who could no longer implant or do synthetic revival surgery.

Oh, it was changed to self-surgeries. Still, goodbye synthetic self-augmentation, it was fun while it lasted.

**Comment by Sigmar-alkahest** [comment]
edited to self surgery? ok, good. bypasses alot of RP-conflict bullshit.

**Comment by RatFromTheJungle** [comment]
with it being self surgeries, there is really no reason anyone could complain, besides people wanting to blatantly powergame.

**Comment by unit0016** [comment]
Can we get ghostroles (Specifically the syndicate trio and charlie station) to have this skillchip as well? Would be nice QOL for them.

**Comment by Oscari-pog** [comment]
I mean this seems only reasonable

**Comment by Cheshify** [comment]
Gandalf, this is... such a bad idea. With this, you're preventing:
- Ash Lizard Surgery
- Ghetto Surgery
- Paramedics, Chemists, and Virologists helping with surgery
- Antags implanting bombs into people
- Roboticists doing surgery
- Syndicate base surgeries
Skills like this shouldn't be locked behind skillchips.
Let's use engineering for example, anyone with the tools can hack a door, it's easier for engies because they have a skillchip to help them see the wires. It doesn't prevent anyone from doing the basic skill, it just makes it harder for people not engies to do it. Don't merge this, don't follow this train of logic with skillchips, and please I beg you don't merge this.

**Comment by SpookyTheFox** [comment]
Giving it to antags sounds reasonable. I'm still waiting to see a toolset implant prison escape. Reducing self surgery to chest only for non-antag synths is good too. For the chest, the only usable implants they can self install are the reviver (it works on synths apparently), the thruster set, and the internal health analyzer.

**Comment by hugmeorelse** [comment]
There was a miscommunication. I asked for skill-chips for self-surgery.

**Comment by hugmeorelse** [comment]
There was a miscommunication. I asked for skill-chips for self-surgery. It's been fixed.

**Comment by hugmeorelse** [comment]
> Can we get ghostroles (Specifically the syndicate trio and charlie station) to have this skillchip as well? Would be nice QOL for them.

Interesting proposition. I'll fly it by staff.

**Comment by SpookyTheFox** [comment]
I would do this as an antag trait like antag metabolism, not a skillchip. There are other uses for skill chips that antags might want the slot for, and it's subject to skill chip mechanic sillyness, like removing it, implanting it in someone else, looking for it, etc.

Ghost roles- absolutely not.

Another one I forgot about non-antag synths- they can currently do several high impact self surgical procedures that should be restricted, such as remove tracking implants. This should not be available to non-antags. The more I think about it, the more I think non-antag robotic part self surgery needs to go.

**Comment by Gandalf2k15** [comment]
CBA to do this right now.

**Pull request closed without merging**
