### PR TITLE
[MODULAR] Problem computers

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

This PR ports Problem Computers from previous codebase

## Why It's Good For The Game

RnD and cargo can now get points by solving math tasks. Non-passive point income is good.

## Changelog
:cl:
add: Added problem computers
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
IMO they're bad game design and it was a mistake to have them in the first place. Encouraging players to open wolfram sucks

**Comment by MLGTASTICa** [comment]
Modular computers shouldn't be ported , anyone capable of doing basic math can speedrun T4 parts in 10 minutes.

**Comment by Owai-Seek** [comment]
I personally don't know how research works on TG, and don't play science at all, but this affects the way cargo works as well. It shouldn't be exceptionally easy to just print additional money, especially when there's PRs upstream that are trying to change the economy in some major ways.

**Comment by Azarak** [comment]
I'll be coming up with more interactive ways for science to gain points in the near future

**Pull request closed without merging**
