### PR TITLE
lets icewalkers be digitigrade

### PR DESCRIPTION
**Pull request by zeroisthebiggay**
## About The Pull Request

~~i actually have no idea if this'll work but it should work idk trust the webedit~~ tested and actually works without any tangible issues besides sprite color inconsistency but that's universally present

## How This Contributes To The Skyrat Roleplay Experience

love me socked demis

## Proof of Testing

there's an outdated screenshot in the comments that shows it working but with two mysterious UI elements on the left bar; in current versions it's been fixed so imagine there being a little UI dropdown in the character creator when you select icewalkers that lets you choose between plantigrade and digitigrade legs and when you do it it does exactly what it says there

## Changelog

:cl:
add: icewalkers can be digitigrade
/:cl:

### CODE REVIEW

**Comment by theselfish** [comment]
@Nerev4r  I disagree with this. But they're one of your pet projects.

Thoughts?

**Comment by zeroisthebiggay** [comment]
> @Nerev4r I disagree with this. But they're one of your pet projects.

okay but genuinely curious why
it's not mandatory it's just more customization

**Comment by HoodMilk** [comment]
Demis having big dumb animal legs knee down or thigh down has always been a thing, so this makes sense

**Comment by ghost** [comment]
image

This **needs** testing. It's a required field. **Especially** when you're touching character customization or spawning in any way.

**Comment by Paxilmaniac** [comment]
I thought you could already do this, guess that explains the lack of digigrade catpeople. +1 to the list of "stuff I thought I already let you do but turns out no".

**Comment by zeroisthebiggay** [comment]
> image
> 
> This **needs** testing. It's a required field. **Especially** when you're touching character customization or spawning in any way.

i'll test it in a bit

**Comment by zeroisthebiggay** [comment]
> > image
> > This **needs** testing. It's a required field. **Especially** when you're touching character customization or spawning in any way.
> 
> i'll test it in a bit

image

**Comment by GoldenAlpharex** [comment]
> > > image
> > > This **needs** testing. It's a required field. **Especially** when you're touching character customization or spawning in any way.
> > 
> > 
> > i'll test it in a bit
> 
> image

The point of that category is to provide a screenshot that proves that you did test your stuff, and that it didn't break other stuff in the process.

**Comment by zeroisthebiggay** [comment]
> The point of that category is to provide a screenshot that proves that you did test your stuff, and that it didn't break other stuff in the process.

image

look the five line change i copy pasted from another species file does the intended thing

**Comment by ghost** [comment]
The attitude and borderline refusal to test the change does not inspire any confidence that this PR was done with the best intentions.

**Comment by zeroisthebiggay** [comment]
> The attitude and borderline refusal to test the change does not inspire any confidence that this PR was done with the best intentions.

what bad intentions can a five line change that allows icewalkers to have funny backwards knee legs do
the 'refusal to test the change' is me being lazy and not wanting to test a webedit

**Review by Gandalf2k15 — APPROVED** [review]
okay yaya

**Pull request merged**
