### PR TITLE
finally: bluesec MODsuits

### PR DESCRIPTION
**Pull request by zeroisthebiggay**
## About The Pull Request

does what it says on the tin

image

image (1)

~~also if you want you can paint kit them to be red again~~ nope
~~it'll adjust the colors of modules like the pepper shoulders and mirage grenade launcher too~~ see latter statement

as a final note: the pepper shoulders module will be black on any MODsuit that isn't the normal security one because i thought it looked nice

## How This Contributes To The Skyrat Roleplay Experience

consistency

## Proof of Testing

it's modular

## Changelog

:cl:
image: bluesec MODsuits. finally goddamn
/:cl:

### CODE REVIEW

**Comment by zeroisthebiggay** [comment]
`Error: Error: found unexpected type for label 'Map Modification' (should be array of config options)
Error: found unexpected type for label 'Map Modification' (should be array of config options)`
what does it mean

**Comment by Plum-but-gayer** [comment]
YEAHHHHHHHHHHHHHHHHHHHHHHHHHH thank you :3

**Comment by projectkepler-ru** [comment]
Unironically ultrabased

**Comment by burgerenergy** [comment]
imo it could use even more blue so they're less little edgelords

**Comment by zeroisthebiggay** [comment]
> imo it could use even more blue so they're less little edgelords

it's the same amount of red on the original modsuits because it's just a palette swap
plus i like edgy

**Comment by W4rd3nn** [comment]
only thing the visor and lights should be blue but the rest is gucci

**Comment by zeroisthebiggay** [comment]
> only thing the visor and lights should be blue but the rest is gucci

that's too much blue
yellow allows it to be easily identified as being a security MOD

**Comment by IgiariValkyr** [comment]
Looks too similar to Deathsquad now.

**Comment by zeroisthebiggay** [comment]
> Looks too similar to Deathsquad now.

image

what game u playing

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
I feel like we don't really _need_ the option to have them be red again, it was only red because nobody had bothered to do what you've just done. I feel like it'll simplify the logic a lot if you don't have that in there. If anyone wants redsec again, as a downstream or whatever, they can still get the icons from the commits in this PR if need be. Or, y'know, just revert this PR and it'll be there too.

That being said, thank you on making this change, it looks quite nice. 😃

**Comment by zeroisthebiggay** [comment]
> I feel like we don't really _need_ the option to have them be red again, it was only red because nobody had bothered to do what you've just done. I feel like it'll simplify the logic a lot if you don't have that in there. If anyone wants redsec again, as a downstream or whatever, they can still get the icons from the commits in this PR if need be. Or, y'know, just revert this PR and it'll be there too.
> 
> That being said, thank you on making this change, it looks quite nice. 😃

i like to have options for people who may want to make a secmod without actually being associated with security or if they just want a red color palette
also i just don't want to have to open git again :s

**Comment by GoldenAlpharex** [comment]
> > I feel like we don't really _need_ the option to have them be red again, it was only red because nobody had bothered to do what you've just done. I feel like it'll simplify the logic a lot if you don't have that in there. If anyone wants redsec again, as a downstream or whatever, they can still get the icons from the commits in this PR if need be. Or, y'know, just revert this PR and it'll be there too.
> > That being said, thank you on making this change, it looks quite nice. 😃
> 
> i like to have options for people who may want to make a secmod without actually being associated with security or if they just want a red color palette also i just don't want to have to open git again :s

The problem with that is that we all know there's going to be a decent amount of players that are just going to go for the red reskin every round out of spite, which tends to be annoying to deal with for staff.

**Comment by zeroisthebiggay** [comment]
> > > I feel like we don't really _need_ the option to have them be red again, it was only red because nobody had bothered to do what you've just done. I feel like it'll simplify the logic a lot if you don't have that in there. If anyone wants redsec again, as a downstream or whatever, they can still get the icons from the commits in this PR if need be. Or, y'know, just revert this PR and it'll be there too.
> > > That being said, thank you on making this change, it looks quite nice. 😃
> > 
> > 
> > i like to have options for people who may want to make a secmod without actually being associated with security or if they just want a red color palette also i just don't want to have to open git again :s
> 
> The problem with that is that we all know there's going to be a decent amount of players that are just going to go for the red reskin every round out of spite, which tends to be annoying to deal with for staff.

i'll get around to it then

**Comment by zeroisthebiggay** [comment]
> Reference in

anyways hi yeah ready

**Review by Gandalf2k15 — APPROVED** [review]
Fancy! LGTM.

**Pull request merged**
