### PR TITLE
sneedu plushie donator item!!

### PR DESCRIPTION
**Pull request by capsaicinz**
## About The Pull Request

this for me dawg!! and everybody else who wants to hold the very man who once picked up a live ttv bomb himself!! 

## Why It's Good For The Game

qol for all users. bliss levels reported to skyrocket when this is in the code. we don't know why. 

snad

## Changelog
:cl:
add: adds the sneed plushie.
/:cl:

### CODE REVIEW

**Comment by H0gberg** [comment]
I'm gonna squish da sneed! squish squish!

**Comment by Arctaisia** [comment]
Time to FORCEFULLY GRAB

**Comment by thestubborn** [comment]
Well well, look at the station slicker with his fancy donator plush!

**Comment by capsaicinz** [comment]
Please do not bully him please

**Comment by capsaicinz** [comment]
maintainers PLEASE

**Pull request merged**
