### PR TITLE
The massive Meka resprite

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request

Tin, massively overhauls the Meka sprites to have a consistent, cleaner color palette, general face lifts and a total makeover to bring it into the current day in age with the rest of the sprites.

This has been a multiple month slog and it'll be finished soon. Just opening this early to have it there.

To Do:

- [x] Finish the dead sprites.

## How This Contributes To The Skyrat Roleplay Experience

Sprites.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

Engineering, Medical, Cargo, Mining, Syndicate
PK, Service and alt, Jannie, Ninja.

Meka stand spin

Meka sit spin

</details>

## Changelog

:cl:
imageadd: Almost all Mekas have been resprited in their entirety.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Speedmerge.

**Comment by Stalkeros2** [comment]
Borg, law 2, sit on face.

**Comment by theselfish** [comment]
I will ping the original Meka creator for their thoughts. On principle.

@theOOZ

**Comment by Ebin-Halcyon** [comment]
They've already given their thoughts on the discord before, but sure w/e.

**Comment by desertmote** [comment]
all of my yes

**Comment by Ebin-Halcyon** [comment]
You should shut the fuck up... now!

**Review by GoldenAlpharex — APPROVED** [review]
Looks good, nice work!

**Pull request merged**
