### PR TITLE
[MODULAR] Adds *vomit and *forcevomit

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request
Title.

Neither of the emotes purge any reagents. They exclusively disadvantage you.

*vomit can be used in any state that isn't death, including hard crit. You immediately vomit with the normal effects.

*forcevomit has you sticking your fingers down your throat. It cannot be done if you are unconcious, or if your mouth is covered. This induces vomiting 2 seconds later, even if you are unconcious, but not if you die. This does NOT stun you, to incentivize people to use the correct emotes for certain situations.

If your stomach is failing, you will instead vomit up blood and suffer no nutrition penalty but instead take brute damage. This is to just add a bit more flavor to organs and organ failure.

## How This Contributes To The Skyrat Roleplay Experience

Many situations may warrant autonomous vomiting (a corpse for example) but mechanics don't support this. With *vomit, you can autonomously vomit as much as you want.

*forcevomit is another logical thing - there are ALSO situations in which someone may want to _induce_ vomiting. Sadly, allowing chem purging at will is kind of broken as hell, so it doesn't purge your chems. 

## Proof of Testing

<details>

https://user-images.githubusercontent.com/59709059/233865995-0183c564-e073-442e-9802-95d5df87e6f6.mp4

<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
add: *vomit, which lets you instantly vomit with no chem purging effects and a stun. It can even be done when in hard crit!
add: *forcevomit, which has you stick your fingers down your throat and induce vomiting two seconds later. Can only be done while conscious and if your mouth is uncovered, but doesn't stun.
/:cl:

### CODE REVIEW

**Comment by nikothedude** [comment]
at maintainer concern the emotes now have a large cooldown to prevent spamming

**Comment by tf-4** [comment]
You asked in discord if anyone would have a problem with it and I said I do, it's going to just be spammed in hallways and generally unfavourably LRP ways. I do not see the RP benefit outweighing that.

**Comment by nikothedude** [comment]
It has a 15 second cooldown. It drains nutrition and stops working below 100. It stuns the user. It's so hard to spam with. This is just paranoia especially since you aren't even willing to try it

**Comment by nikothedude** [comment]
Sorry that a bit hostile, I'm a bit aggravated right now

**Comment by nikothedude** [comment]
Also, what about flypeople? I frnakly don't see those guys going around vomitting "jsut because" despite the fact that they can do it easily, have a "reason" to do it that would shield them from some consequence, the fact they can spam it, and the fact they vomit EXTRA.

**Comment by Zonespace27** [comment]
I'm willing to go to bat for this
It can be tried out with a TM for a period of time, and if people aren't shitters with it to a large degree, then I do believe this could be a good PR for RP.

**Comment by desertmote** [comment]
it begs to be said that you can vomit already by spamming *spin. it has a good delay and mechanically nerfs you to be woozy, too.

**Comment by nikothedude** [comment]
> it begs to be said that you can vomit already by spamming *spin. it has a good delay and mechanically nerfs you to be woozy, too.

Yeah but who wants to spin to vomit in a isutation you would logically vomit in? If I see a corpse I'm not gonna do a 2048 degree spin to vomit.

If it turns out vomit neeeds to be nerfed even further, I may add nausea.

**Comment by desertmote** [comment]
> Yeah but who wants to spin to vomit in a isutation you would logically vomit in? If I see a corpse I'm not gonna do a 2048 degree spin to vomit.
> 
> If it turns out vomit neeeds to be nerfed even further, I may add nausea.

fall to the floor and emote like youre barfing while spamming *spin hotkey. its not hard, ive done it plenty of times for stupid joke moments, and horrible chef's.

**Comment by nikothedude** [comment]
> > Yeah but who wants to spin to vomit in a isutation you would logically vomit in? If I see a corpse I'm not gonna do a 2048 degree spin to vomit.
> > If it turns out vomit neeeds to be nerfed even further, I may add nausea.
> 
> fall to the floor and emote like youre barfing while spamming *spin hotkey. its not hard, ive done it plenty of times for stupid joke moments, and horrible chef's.

Okay, but my argumkent is taht A. It takes too long in some contexts B. You _don't spin around like a lunatic_ in real life if you see something gross. You just vomit

This PR adds a way to vomit that works in most RP scenarios without being unneccessarily goofy.

**Comment by nikothedude** [comment]
anyway im gonna close github for now ive got to focus on an assignemtn oh god

**Comment by Gandalf2k15** [comment]
Please resolve the concerns brought up by other maintainers before overriding and opening.

**Pull request closed without merging**
