### PR TITLE
Remove/replace cat scream with new cat scream [NO GBP]

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

This PR is to present to remove the cat scream sound if a suitable replacement is not found. 

The sound is found to be grating among a number of players to the point of being excruciatingly painful. It is poorly mixed and the sound quality notably poor compared to others.

This may or may not be the start of a comprehensive overhaul of the sounds present on Skyrat.

Other possible solutions include having a sound preference that lets people choose what sound gets played client side (looking at you, climax.) which would be in the scope of another PR.

**Requirements for New Cat Scream:**
- Should not be a literal clip of a cat screaming.
- Should not be made to be 'funny'. This is a roleplay server after all.
- Must be well recorded and mixed.

## Changelog

:cl: Skyrat
:del: Cat scream removed until a replacement is found
/:cl:

### CODE REVIEW

**Comment by OzzyMcPseudonym** [comment]
Please for the love of god merge this, I unironically wish cat scream made people valid salad, it's that grating on the ears.

**Comment by Zergspower** [comment]
we're getting rid of this and not gorilla? wtf?

**Comment by desertmote** [comment]
april fools was two months ago

**Comment by hugmeorelse** [comment]
> we're getting rid of this and not gorilla? wtf?

We can get rid of that too and just have it only for gorillas.

**Review by tf-4 — DISMISSED** [review]
Justify your PR.

**Comment by lessthnthree** [comment]
> Justify your PR.

As it's labelled, host request.

**Comment by Nerev4r** [comment]
i gotta say re; the cat scream if we're doing an audit on 'bad/overly loud/super high pitched/poorly mixed' emotes/screams we might as well go all the way w/ it
this feels like we're only using 50% of our ass here, like.

skeleton scream
dragon scream
zombie scream god forbid it's still in there
raptor scream
awoo
peep2
weh


edit: i don't necessarily mean removal just an adjustment of the sfx files themselves should be sufficient.

**Comment by tf-4** [comment]
> > Justify your PR.
> 
> As it's labelled, host request.

That's not a justification. Please follow the PR template including a proper justification. This is required for all even mildly subjective changes (i.e. not flat-out fixes), and goes doubly so for what is obviously a controversial change.
This can be re-opened afterwards.

**Comment by tf-4** [comment]
Still needs justification in the PR body

**Comment by SpaceVampire** [comment]
I would agree that you shouldn't just remove something that a lot of people use and enjoy, without at least offering your justification for it. Especially because that would allow people to offer up suggestions and modifications to address whatever the perceived issue is.

**Comment by hugmeorelse** [comment]
If you guys want "cat scream", fine one that isn't a literal cat screaming. 

> i gotta say re; the cat scream if we're doing an audit on 'bad/overly loud/super high pitched/poorly mixed' emotes/screams we might as well go all the way w/ it this feels like we're only using 50% of our ass here, like.
> 
> skeleton scream dragon scream zombie scream god forbid it's still in there raptor scream awoo peep2 weh
> 
> edit: i don't necessarily mean removal just an adjustment of the sfx files themselves should be sufficient.

You're really reaching here. None of them is literally as grating as the cat scream. It causes me physical pain every time I hear people spam it, and I know a lot of other people here find it equally as grating. It's the equivalent of nails scratching on chalkboard.

**Comment by Nidvex250** [comment]
This is just a Salt PR and everyone knows it.
Removing it without any good justification or anything is not what a Mature and Rugged Soul would do, It's not even a bad sound, trying to call it nails on chalkboard is good publicity to nails on chalkboard.

**Comment by Nerev4r** [comment]
> This is just a Salt PR and everyone knows it. Removing it without any good justification or anything is not what a Mature and Rugged Soul would do, It's not even a bad sound, trying to call it nails on chalkboard is good publicity to nails on chalkboard.

nah it does need to have it's volume reduced and the 'highs' if I can call them that severely lowered
because at some point in the middle of the sfx it does legit peak speakers

**Comment by YakumoChen** [comment]
IDR

**Comment by hugmeorelse** [comment]
@nidvex250 It's fine if you disagree, but there's no need for that sort of inflammatory behavior. You can leave a normal critical post like everyone else.

**Comment by Nidvex250** [comment]
> nah it does need to have it's volume reduced and the 'highs' if I can call them that severely lowered because at some point in the middle of the sfx it does legit peak speakers

That would be a good PR then. I'm mainly just against the outright removal of a standard scream noise. I wouldn't be against the sound being remastered, adjusted, or replaced with a better quality version.

...and yeah @hugmeorelse is right, I'm sorry. Just been annoyed at some of the PRs I've seen and kinda lost my cool here. I'll step away and take a breath.

**Comment by dawsonkeyes** [comment]
let's remove all of the other problematic sounds while we're at it, then -- no half measures?

**Comment by QuacksQ** [comment]
Omw to make a PR that removes sounds that annoy me

**Comment by hugmeorelse** [comment]
Since people would rather popcorn post, I'm locking the discussion. I hear some interesting ideas, but it's too bad it has to be shut down because of people here.

**Comment by hugmeorelse** [comment]
> > nah it does need to have it's volume reduced and the 'highs' if I can call them that severely lowered because at some point in the middle of the sfx it does legit peak speakers
> 
> That would be a good PR then. I'm mainly just against the outright removal of a standard scream noise. I wouldn't be against the sound being remastered, adjusted, or replaced with a better quality version.
> 
> ...and yeah @hugmeorelse is right, I'm sorry. Just been annoyed at some of the PRs I've seen and kinda lost my cool here. I'll step away and take a breath.

I appreciate your apology. Also, normally, I would agree, but I've been waiting for almost two years now on that. Nothing has come to fruition despite my requests to people. So, I'm removing it, until a suitable replacement comes along.

**Comment by hugmeorelse** [comment]
Discussion moved to the Discord. Much more productive there. :)

**Comment by theOOZ** [comment]
Let us hear the new sound in the PR description.

**Review by Funce — APPROVED** [review]

**Comment by Funce** [comment]
Justification is good. We can get a new cat screech WYCI. As it stands, leaving it in is more detrimental than taking it out.

**Pull request merged**
