### PR TITLE
The Skyrat underwear resprite

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request
Tin.
Updates a bunch of Skyrat specific underwear and tops and a few more socks. Adding digitigrade variants and making them split versions have parity with the TG versions.
Also removes a bunch of unused underwear that was really fucking ugly.

## How This Contributes To The Skyrat Roleplay Experience

Sprites

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
Underwear

</details>

## Changelog

:cl:
imageadd: A bunch of underwear has been resprited, take a look.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Can you give an actual list of changes instead of a nebulous "a bunch"?

**Comment by Ebin-Halcyon** [comment]
> Can you give an actual list of changes instead of a nebulous "a bunch"?

IDB2 exists for a reason.

**Comment by YakumoChen** [comment]
It benefits non-coders and the search function if the changes are listed in the PR body

PR also lacking Removal tag and the title is not clear on removals

**Comment by Ebin-Halcyon** [comment]
> It benefits non-coders and the search function if the changes are listed in the PR body
> 
> PR also lacking Removal tag and the title is not clear on removals

If I add every single item I changed the CL would take up half of the changelog space, it isn't hard to look at underwears, people don't even notice them half the time.
I don't need a removal tag for removing unused sprites either.

**Comment by Iamgoofball** [comment]
IDB2 is for us to make sure you didn't replace the sprites with the words "fuck you" in pixel art on every dmi file without downloading them locally, it's not a replacement for a changelog

**Review by Zonespace27 — APPROVED** [review]

**Review by GoldenAlpharex — APPROVED** [review]
Seems good to me!

**Pull request merged**
