### PR TITLE
IceBox Fixes: Removes accesses; adds lattices

### PR DESCRIPTION
**Pull request by Stalkeros2**
## About The Pull Request
Removed access from Icebox mining's those two airlocks so both the public mining and xenoarch are *actually* public use.
image
Added a short bridge here so people can also actually access it too, as well as marker beacons to light the way there because why not?
image

## How This Contributes To The Skyrat Roleplay Experience
~~I dunno, you tell me.~~
Map fixes good.

## Changelog

:cl: Stalkeros
fix: Made Icebox's public mining actually public and accessible.
/:cl:

### CODE REVIEW

**Comment by Zenitheevee** [comment]
>Reads "adds lattices" 
>Immediate PTSD from Lattice-based runtimes in DM waiting for server boot

**Review by GoldenAlpharex — APPROVED** [review]
Looks good!

**Comment by MassacreDemigirl** [comment]
Maybe add a pathway with markers from public mining exit to it?

**Comment by Stalkeros2** [comment]
> Maybe add a pathway with markers from public mining exit to it?

Basically done.

**Pull request merged**
