### PR TITLE
[Modular] Quick report system for security officers

### PR DESCRIPTION
**Pull request by twilightwanderer**
## About The Pull Request

**_Note: This is a transposition of this [PR](https://github.com/tgstation/tgstation/pull/66578), which was rejected by one of the main developers of tgstation. Initially I didn't want to try porting it to Skyrat, but after talking to its players I decided to try to convert it into a module._**

Adds a special skill for station security officers, as well as a system of quick radio reports for security headphones. The security officer will be able to call up a special earpiece menu with the choice of a short report and say it to the security channel with his location. This is formalized through a special chip as a skill similar to engineers' knowledge of the wires. 

The following reports are currently available:
1. Combat Actions
- Pursuing the perpetrator.
- I'm fighting.
- I'm hurt.
- Taking combat losses.
- Retreat

2. Detecting
- Station damage.
- Fire.
- Depressurization.
- Criminal trail.
- Corpse.
- Perpetrator.
- Dangerous perpetrator.

3. Status
- Positive
- Negative
- My location
- Busy
- Available

4. Support Request
- Requesting a detective
- Requesting combat support
- Requesting Engineering assistance
- Requesting Medical assistance

## How This Contributes To The Skyrat Roleplay Experience

Sometimes the game as an officer is so dynamic that there is simply not enough time to write in a chat call for help before you get killed. With this system, I want to give officers at least some chance to cooperate in dynamic battles by giving them the ability to send basic messages to the security channel at the push of a button. I have framed this as a combat skill learned in special training before arriving at the station, sort of like knowing special radio codes for real policemen. I also tried to strike a balance by making the reports minimal, without describing the nature of the criminals and crimes. 

## Changelog

:cl:
add: quick report system for security officers
/:cl:

### CODE REVIEW

**Comment by twilightwanderer** [comment]
Hmm, this is the first time I've encountered that Git stubbornly refuses to index the icon file.

**Comment by tf-4** [comment]
> The idea is interesting tho, it's just giving too much information.
A button on the top that is given by the sec headset and just pings the security channel would be interesting, as you are given no extra information about anything, just that an officer is possibly on danger, it pushes officers to ask the AI for their location, to use clues from the round to guess what is the issue at hand, ask paramedics to help them track their corpse, etc.

This comment on the original PR pretty much sums this up for me.
I also think it's far less of an issue here than it may be on tg due to our much tighter escalation rules.

**Comment by hugmeorelse** [comment]
This seems promising. My only concern really is that this may give an advantage to antagonists, especially since our players here feel that security has too much of an advantage in coordinating and swarming an antagonist. Besides that, this seems like a nice addition to the server.

**Comment by YakumoChen** [comment]
Most of these seem extremely unlikely to be used, especially in combat where this would be of the most benefit. 
I'd almost rather this be just the combat actions as a radial and nothing else. Although that brings with it what xyel says, its going to make security swarming worse than it is.

Skyrat does not have a big issue with communication in security really.

**Comment by nevimer** [comment]
> Most of these seem extremely unlikely to be used, especially in combat where this would be of the most benefit. 
> I'd almost rather this be just the combat actions as a radial and nothing else. Although that brings with it what xyel says, its going to make security swarming worse than it is.
> 
> Skyrat does not have a big issue with communication in security really.

Security kinda does not communicate, it's a real issue where security is clueless despite calls for help, or things already explained. If chat wasn't a disaster, loud mode wouldn't have been made, megaphones, etc.

**Comment by Kush1Push1** [comment]
"Why are you reporting like a robot?"

**Pull request closed without merging**
