### PR TITLE
Adds a cool dorsal frill to markings for lizards

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

Title. Sprite provided by thgvr. 

## How This Contributes To The Skyrat Roleplay Experience

its cool

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

image

image

</details>

## Changelog

:cl:
add: Adds a cool dorsal frill in head markings
/:cl:

### CODE REVIEW

**Review by vinylspiders — CHANGES_REQUESTED** [review]
Shouldn't this be a frill, not a body_marking? There's a other icon file and sprite accessory category for that.

The sprites themselves look good to me, though.

It would also be really cool if you could divide it into primary, secondary, and tertiary to allow for multi colored frills. Looks like it'd be perfect for that.

pinging @GoldenAlpharex

**Comment by nikothedude** [comment]
> Shouldn't this be a frill, not a body_marking? There's a other icon file and sprite accessory category for that.
> 
> The sprites themselves look good to me, though.
> 
> It would also be really cool if you could divide it into primary, secondary, and tertiary to allow for multi colored frills. Looks like it'd be perfect for that.
> 
> pinging @GoldenAlpharex

it COULD be a frill, but most frills are on the SIDES of the head, and are mutually exclusive

and god fuckin damn i have no idea how to divide them up

**Comment by vinylspiders** [comment]
> > Shouldn't this be a frill, not a body_marking? There's a other icon file and sprite accessory category for that.
> > The sprites themselves look good to me, though.
> > It would also be really cool if you could divide it into primary, secondary, and tertiary to allow for multi colored frills. Looks like it'd be perfect for that.
> > pinging @GoldenAlpharex
> 
> it COULD be a frill, but most frills are on the SIDES of the head, and are mutually exclusive
> 
> and god fuckin damn i have no idea how to divide them up

It's not that complicated, you just have to duplicate the sprite and rename the icon_states to `_primary`, `_secondary`, `_tertiary` and then go in with the eraser to break the sprite into individually colored parts

**Comment by vinylspiders** [comment]
> it COULD be a frill, but most frills are on the SIDES of the head, and are mutually exclusive

I getcha, but having there just be one special frill that's hidden away in body markings is not ideal either.

If you really want them to be stackable with the side frills I suppose what you could do is make it both a frill option and a head marking and call it "Dorsal Frill - Marking version". You won't be able to make use of the matrixed colors with that, though.

**Comment by nikothedude** [comment]
i am moving to galaxia and am focusing my efforts there

**Pull request closed without merging**
