### PR TITLE
[MODULAR] Contractor Nerfs II: I Still Know What You Did Last Summer 

### PR DESCRIPTION
**Pull request by Nerev4r**
## About The Pull Request
This is a reopening of #22309.
What this does is lower the contractor MODsuit's armor from 

 melee = 30 --> 15
 bullet = 40 --> 20
 laser = 20 --> 15
 energy = 30 --> 15
 bomb = 30 --> 35
 bio = 30 --> 100
 fire = 80 --> 80
 acid = 85 --> 90
 wound = 30 --> 25
 
 What this does in practice is, 
 Currently a Contractor's armor stats are, if they're on-station where they can use their armor booster, actually enhanced by
 
 /datum/armor/mod_module_armor_boost
    melee = 25
    bullet = 30
    laser = 15
    energy = 15

So right now, their 'functional armor' as I'll call it is actually somewhere in the neighborhood of 
melee = 55
bullet = 70 (!)
laser = 35
energy = 45

Now, their functional armor will be 
melee = 40
bullet = 50
laser = 30
energy = 30

## How This Contributes To The Skyrat Roleplay Experience
To quote a legendary warrior-poet, solo antags such as contractor (the most known of the pack right now) have essentially become the new Wizard. It's One Guy With All The Stuff running in circles shitting and pissing on everyone. Every single solo antagonist like this, midround or not, that doesn't just get rocked in 60s or less is built around essentially creating an experience that demands the attention and 'all hands on deck searching and hunting' of a blob, but without the same widespread enjoyment of a blob. Contractors right now are the worst offender as nigh-unhuntable jauntmonsters that duck and weave around every single fight while boasting almost 70 functional armor against our most common Security damage type.

Additionally, policy is seeking to work with code on this one in order to dial Contractors back from the new state of Station Threat. Scaling uncontrollably _while_ having insane starting gear is just not okay, man. 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog
:cl:
balance: The armor of contractors has been lowered, and their baton holster costs another point to get.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
why reduce the bio? 100 bio armour is near-universal for modsuits, and the contractor one is spaceproof.

**Comment by Hatterhat** [comment]
contractor should actually have a different armor booster, `/obj/item/mod/module/armor_booster/contractor`, which is

```
/datum/armor/contract_booster
	melee = 20
	bullet = 20
	laser = 20
	energy = 20
```

so really with their current armor stats shouldn't it be more like
```
	melee = 50
	bullet = 60
	laser = 40
	energy = 50
```

this armor is still pretty bad and i do support "making it easier to shoot the bad guy in the face"

**Comment by Nerev4r** [comment]
unnerfed fire because uh
bottling and zippoing a contractor would be goofy

**Review by GoldenAlpharex — APPROVED** [review]
Sure.

**Comment by GoldenAlpharex** [comment]
(Putting on No GBP because this was something that was requested and it's a cooperation between code and policy)

**Pull request merged**
