### PR TITLE
[DEV ONLY] [TM-ONLY-FN] Minor changes to combat

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

DEV-ONLY.

## Changelog
:cl:
add: Combat has once again been modified slightly.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Ah yes, now every time you get knocked down, you drop everything. Does that affect resting on your own?
Edit: I don't mean to start an argument, I just want to know exactly what this does, provided that there's no info being given.

**Comment by Gandalf2k15** [comment]
Currently unsure of where this is going. It'll change rapidly, so, yeah. No information for now.

**Comment by gamermomentum** [comment]
What's the goal of this PR?

**Comment by Gandalf2k15** [comment]
> What's the goal of this PR?

To combat rest combat

**Comment by gamermomentum** [comment]
Rest combat might be a little wacky but this has positively cranked the power of shove and batons. 
this isn't meant to start a big dialogue or argument but I'm not sure this is the best way to achieve that.

**Comment by Gandalf2k15** [comment]
> Rest combat might be a little wacky but this has positively cranked the power of shove and batons.
> this isn't meant to start a big dialogue or argument but I'm not sure this is the best way to achieve that.

That's why the PR has no desc or anyhting, i wanna trial run lots of different methods to see which one tackles it best

**Comment by GoldenAlpharex** [comment]
> > Rest combat might be a little wacky but this has positively cranked the power of shove and batons.
> > this isn't meant to start a big dialogue or argument but I'm not sure this is the best way to achieve that.
> 
> That's why the PR has no desc or anyhting, i wanna trial run lots of different methods to see which one tackles it best

I'm curious, how about making it so you can't hold items in your hands when you lay down with combat mode on, or when you turn on combat mode whilst resting it drops your items?

**Comment by NullDagaf** [comment]
How descriptive.
Also the LOCKED tag should probably.. you know. **Actually lock the chat.**

**Comment by Gandalf2k15** [comment]
This has reached it's ultimatum, I'll do more later.

**Pull request merged**
