### PR TITLE
[MIRROR] Evidence Storage Is Now An Area [MDB IGNORE]

### LINKED ISSUE #70959: Evidence Storage area is inconsistent across maps
The 'Evidence Storage' room 'area' in security is inconsistent between maps, so procs that call based on area can't work consistently.

Evidence Storage should be its own area and not tacked on to whatever it's next to based on whichever map.

image
image
image

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/70983
--------------------

## About The Pull Request
Fixes https://github.com/tgstation/tgstation/issues/70959
Gives each map Evidence Storage, which each has an APC
Icebox
image
Deltastation
image
Metastation
image
Tramstation
image
Kilostation
image
## Why It's Good For The Game
Probably good for stations to have a consistent evidence room. Breaks up the big block that is security.
## Changelog
:cl:
fix: All maps have a consistent Evidence room.
imageadd: Ddds an icon for the Evidence Storage area
/:cl:

### CODE REVIEW

**Comment by Tastyfish** [comment]
ah fun security being remapped on every station, have fun map maintainers lol

**Comment by Zonespace27** [comment]
The fact that this is 10x the size of the TG pr indicates a maptainer (or myself if nobody else does) should probably just do a map reset

**Comment by Paxilmaniac** [comment]
a maptainer (me) (im the only one active)

**Comment by Paxilmaniac** [comment]
actually to be honest with you im surprised there's not more lines changed considering it touches every tg map

**Comment by Jolly-66** [comment]
You're all weak.

**Review by Jolly-66 — APPROVED** [review]

**Pull request merged**
