### PR TITLE
[SEMI-MODULAR] CUSTOMIZATION - Modular Augmentation system

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
Adds a modular and clean system to modify your character with augmentations ranging from limbs, implants to organs. You can also stylize your augmented limbs. The system uses quirk points to balance for character power

The system is quite small, lightweight and modular, and will make extra categories, slots etc. etc. just by defining them and adding a datum definition that should be instantiated

The limb styles are hardcoded, but easily adjustable

Usage of markings + augments to make a pretty OC

This removes the prosthetic limb quirk

## Why It's Good For The Game
Character customization.

## Changelog
:cl:
add: Added a cool augmentation system
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Attacking a robotic limb with a screwdriver, mostly sharp damage, doesn't cause any injury to that limb.

**Comment by Azarak** [comment]
> 
> 
> Attacking a robotic limb with a screwdriver, mostly sharp damage, doesn't cause any injury to that limb.

was due to cyborg limbs having a flat damage reduction. Added a subtype without armor to be used instead

**Comment by ShadeAware** [comment]
> 
> 
> > Attacking a robotic limb with a screwdriver, mostly sharp damage, doesn't cause any injury to that limb.
> 
> was due to cyborg limbs having a flat damage reduction. Added a subtype without armor to be used instead

I dunno, I think they should have atleast a small bit of armor. You die instantly to even the weakest of EMPs, so it seems like you should get atleast something in return. Taking away the armor just leaves you with something thats all malice with no benefit, which sucks absolute shit.

**Comment by Azarak** [comment]
> 
> 
> > > Attacking a robotic limb with a screwdriver, mostly sharp damage, doesn't cause any injury to that limb.
> > 
> > 
> > was due to cyborg limbs having a flat damage reduction. Added a subtype without armor to be used instead
> 
> I dunno, I think they should have atleast a small bit of armor. You die instantly to even the weakest of EMPs, so it seems like you should get atleast something in return. Taking away the armor just leaves you with something thats all malice with no benefit, which sucks absolute shit.

The limbs have solid ups and downs, being immunity to bone break, bleeding, easy repair, and the downs being vulnerability to EMP (one robo arm will paralyze you for 1 second, make you drop held item, and deal ~6 damage, it's not that big of a deal), and the inability to heal from chemicals. 

This system is meant for customization, and not min/maxing.

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
