### PR TITLE
Make Tesla zaps generate energy again

### PR DESCRIPTION
**Pull request by Microvolnovka19**
## About The Pull Request

The Title says it's all. 

_P.S. I've tested this and managed to successfully set up a tesla engine._

## How This Contributes To The Skyrat Roleplay Experience

With this PR Tesla can now actually generate energy. What does this mean? The admins can create a custom station goal a.k.a. "set up a tesla" or engineers can try to delam SM into tesla and then generate energy with it(Tesla generates MUCH MORE energy than SM, since I haven't changed the parameters). 

## Changelog

:cl: SuperDrish
fix: Tesla zaps now can generate energy with coils as intended.
/:cl:

### CODE REVIEW

**Review by tf-4 — CHANGES_REQUESTED** [review]
Take it upstream first

**Comment by nikita-chekistov** [comment]
> Take it upstream first

Yeah, I've tried already 
https://github.com/tgstation/tgstation/pull/70505

**Comment by tf-4** [comment]
Not really convinced that this is something we want. We don't especially want to _encourage_ tesla delams. Or intentional delams in general.

**Comment by nikita-chekistov** [comment]
> Not really convinced that this is something we want. We don't especially want to _encourage_ tesla delams. Or intentional delams in general.

Its just an example, that surely will require something like OPFOR. I think that Tesla will be used mostly for custom station goal.

**Comment by nevimer** [comment]
even when it didnt work people were setting them up to sound grief the entire map....

**Comment by tf-4** [comment]
Yeah, I'm gonna say that this is something we're not interested in for the time being. Sorry.

**Pull request closed without merging**
