### PR TITLE
[MODULAR] Delta Med Changes

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request

Moves cloning to the recovery room and makes it the new cloning.
Removes the operating theatre.
Moves the break room to where the operating theatre used to be.
fixed1

Expands the treatment center & Storage Room
Gives treatment a little back room
Gives Delta medical some amenities that other medical departments have (Linen bins, medical laptop)
fixed

## Why It's Good For The Game

Delta's medical wing is cramped, to say the least. An operating theatre that wastes far too much space, cloning being multiple rooms away from cryogenics, an inaccessible medical storage, and a painfully tight treatment center with very little room to set up the number of beds and computers that an efficient medbay needs.

This PR aims to remedy some of the issues that I believe Delta's medical wing has, remove redundant workspaces, and give doctors the ability to set up a more efficient treatment center (all while adding a few amenities that other station like Meta already have).

## Changelog
:cl:
add: Gave Delta Medical a fresh redesign
del: Removed Delta operating theatre
/:cl:

### CODE REVIEW

**Comment by CameronWoof** [comment]
These changes remove two rooms that were previously single-purpose, flavorful rooms that added to the verisimilitude of the department (the formal operating theatre and the recovery ward) and creates a very large new area that honestly doesn't have a lot going for it and doesn't provide a clear direction or idea, to me.

I would be fine with moving the cloning bay to where you've put it here, placing hallway-facing windows on its left edge and partitioning it away from the recovery ward, and I like the small informal storage area at the back of the treatment center, which would fit nicely where cloning was previously. This would keep the formal operating theatre intact (which I posit is an important, flavorful space and provides a decent place for antagonists to operate without there being any obvious impropriety), and give the recovery ward its identity back as a sovereign space to rest and heal in.

**Comment by Swiftfeather** [comment]
Good change, bumps delta medbay to better fit the other two station medbays, while not over optimizing it to high heaven

**Comment by SpaceVampire** [comment]
> 
> 
> These changes remove two rooms that were previously single-purpose, flavorful rooms that added to the verisimilitude of the department (the formal operating theatre and the recovery ward) and creates a very large new area that honestly doesn't have a lot going for it and doesn't provide a clear direction or idea, to me.
> 
> I would be fine with moving the cloning bay to where you've put it here, placing hallway-facing windows on its left edge and partitioning it away from the recovery ward, and I like the small informal storage area at the back of the treatment center, which would fit nicely where cloning was previously. This would keep the formal operating theatre intact (which I posit is an important, flavorful space and provides a decent place for antagonists to operate without there being any obvious impropriety), and give the recovery ward its identity back as a sovereign space to rest and heal in.

I agree with this. The second image there really just comes up as empty, soulless, and kind of unnecessary in a way that the original one didn't. I can see where you are coming from the stuff about cloning, because it was something that we just forced into there in the first place.

**Review by KathrinBailey — APPROVED** [review]
Lack of pre-built surgery computer isn't great but we'll see if it actually causes any issues.

**Pull request merged**
