### PR TITLE
[SEMI-MODULAR] Engineering Borg Powertools

### PR DESCRIPTION
**Pull request by DuffCreeper**
## About The Pull Request

Combines the Screwdriver, Wrench and the Crowbar, wirecutters into their own respective tools for engineering borgs

## Why It's Good For The Game

The idea of this was to basically clean up the inventory of the borgs by combining their tools into... _very familiar_ powertools
woo

I have not changed force, speed or anything else relating to the tools that might make them too different from the old ones. Aside from the fact you can swap them like their powertool counterpart

(also yes the sprites are stupid *dab)

## Changelog
:cl:
add: Engineering Cyborgs now have had some of their tools repurposed into their powertool counterpart!
/:cl:

### CODE REVIEW

**Comment by Swiftfeather** [comment]
Smh borg power creep\s

**Comment by MLGTASTICa** [comment]
Good change , cyborg inventory bloat is becoming a issue.

**Review by KathrinBailey — APPROVED** [review]
yes
you can make toolspeed _slightly_ faster if you want, 0.4 is fine, up to you. After all, these are robots using the power tools.

**Comment by DuffCreeper** [comment]
> yes
> you can make toolspeed _slightly_ faster if you want, 0.4 is fine, up to you. After all, these are robots using the power tools.

Maybe but for now this is fine imo

**Pull request merged**
