### PR TITLE
[MODULAR] Ashwalker Village (Fixed this time)

### PR DESCRIPTION
**Pull request by ForrestWick**
## About The Pull Request

As Citadel did a long while ago, and as we had when Skyrat was still Citcode, Ashwalkers have been given an updated version of their nest in modular_skyrat. The actual nest ruin that was previously there is untouched, and if this winds up getting merged, I'll leave it up to whoever controls map stuff as to whether or not the small nest ruin gets left alone. If it does, I'll come back to it to add some of the QOL upgrades the village has. This PR also adds some new clothing options for Ashwalkers, supplied in the temple roundstart.

The village layout is seen here: https://cdn.discordapp.com/attachments/640744619302453316/866897079225155584/unknown.png

Added new clothes, revamped the layout, added some new appliances (the mortar on the table is a reskinned grinder), an ORM so you don't have to rely on bonfire smelting RNG, a mining vendor (might get removed, we'll see), a larger farming area, an expanded temple, a proper storage hut, and a cooking hut. The rest of the space is ripe for building.

## Why It's Good For The Game

General QOL for Ashwalkers, a lot of it presents more options for how to do things. The map is modular and the normal tg ruin is untouched.. Also new clothes for the lizard dudes.

## Changelog
:cl:
add: Added more ashwalker clothes.
expansion: Made an Ashwalker village that is a permanent fixture of lavaland, expanded the previous ashwalker nest ruin as a base for this.
qol: Gives Ashwalkers more tools, barter options, and general gameplay options for their rounds.
config: put the new map in the config file
/:cl:

### CODE REVIEW

**Comment by Guidesu** [comment]
I have to wait two days due to pure randomization of custom mining just to play today and see no ask walker village. Strange before this TM ashwalker den would be a guaranted spawn

**Comment by Guidesu** [comment]
@ForrestWick  This is a kinda urgent issue you need to see

**Comment by ForrestWick** [comment]
> @ForrestWick  This is a kinda urgent issue you need to see

Which commit is currently TM'd

**Comment by ForrestWick** [comment]
> > @ForrestWick  This is a kinda urgent issue you need to see
> 
> Which commit is currently TM'd

Ok so apparently this might have something to do with the size of the ruin. According to Zephyr, if the game cant find space for a ruin it wont spawn it even if it's set to always spawn, so I'll try condensing the size of the ruin tonight and see if that helps. Gimmie two hours here cause that's when I get off work

**Comment by Guidesu** [comment]
Aye thanks

**Comment by ForrestWick** [comment]
Going to make a new PR due to the conflicts and how many there are. Easier that way for me.

**Pull request closed without merging**
