### PR TITLE
[Mostly-Modular] Expansive Shipping Part 1: Mostly Armaments

### PR DESCRIPTION
**Pull request by Zenitheevee**
## About The Pull Request

Hello Peddlers, Merchants and Cargonians alike, For I am about to make your job slightly more difficult by giving you more crates you have to manage.

This PR adds A WHOLE WHOPPIN 9 additions, Including 1 Emag specific crate and 2 Experimental Contraband goody packs ((WHICH WORK!))

The following crates include:

Hydrohelper has been removed, Atleast for now. I'll probably bundle it later with some more stuff at a higher price, with some more... Thematicly appropriate things. 

2 Techshell packs. The Value pack is a Science crate and comes with 3 Techshell boxes for 2150, And a Goody pack that only comes with one box at 850 (Half the oldrat crate price (Oldrat crate came with 2 boxes)). QUITE A STEAL!
2 Goody packs for WT-550 ammo types. Because man, Hand emptying and reloading mags are a pain. These require hacking the console and are a _bit_ more, But Ey, Forgetabouteet
Mini E-gun was already added.....

3 New Armory crates: 
Woodstock Originals, Containing 3 Woodstock shotguns. Perfect when the Bartender needs a spare.
Peacekeeper Shotgun crate, Containing 3 Peacekeeper shotguns and a few boxes of non-lethal shells. 
WT-550 Ammo Variety pack, Containing 2 of each WT-550 Mag at a STEAL of a price

And lastly, A very Gimmicky Emag-only crate, The Totally-not-mafia Secretkeeper crate. 
Snitches needing stitches? Trenchcoat and Fedora just your style? Just want the Tommygun? Well this pack will SURELY Allow you to rack up the Protection money people will be shelling out to you, Especially with how much this thing costs. 

## Why It's Good For The Game

Debatably good for the game, But adds back some supply crates from oldrat, Adds a few new ones, And gives Antag Cargo's a new gimmick to try out. Its a shame i couldn't make the mafia crate available for Family rounds for PEAK Family fun.

## Changelog
:cl:
add: 5 new packs to cargo
add: 2 new contraband packs to cargo
add: 1 new emag crate to cargo
/:cl:

### CODE REVIEW

**Comment by Zenitheevee** [comment]
Also, Just to make 1 thing clear.

The edits to the base Pack + Goodies section are _**PURELY**_ For organization purposes. They are Otherwise entirely optional, And if removed will only revert all the packs from going to the bottom of their respective categories

**Comment by Owai-Seek** [comment]
It's probably be better if all the modular crates were in the same file. In the oldbase, cargo packs were all in different files based on what tab they showed up in, TG condensed it to a single file so it's easier to deal with. 

I can't really speak about the balance of any of the armory packs, guns, and goodie bags, because I don't do combat, so I won't mention too much about them.

Not really a fan of the hydroponics one though. Getting boards from service is pretty easy, the bartender, botanist, chef, janitor, and (maybe?) the lawyer all have access to the protolathe. There's also a public garden available on all maps. It also gives cargo a way to easily print money by building hydro trays, draining power, and selling plants in-house.

**Comment by Zenitheevee** [comment]
> 
> 
> It's probably be better if all the modular crates were in the same file. In the oldbase, cargo packs were all in different files based on what tab they showed up in, TG condensed it to a single file so it's easier to deal with.
> 
> I can't really speak about the balance of any of the armory packs, guns, and goodie bags, because I don't do combat, so I won't mention too much about them.
> 
> Not really a fan of the hydroponics one though. Getting boards from service is pretty easy, the bartender, botanist, chef, janitor, and (maybe?) the lawyer all have access to the protolathe. There's also a public garden available on all maps. It also gives cargo a way to easily print money by building hydro trays, draining power, and selling plants in-house.

To inform the idea of most of the Armory crates, It is a mix of "Solving In game issues" And "Retrieving oldrat packs". The Peacekeeper shotgun crate helps heavily for the fact that there is no other way to get them, And sadly there _Are_ bounties for them. The woodstock ones are almost entirely just oldrat pack referencing, along with pretty much everything else in armory except for the Emag crate.

The Hydro pack is definitely an addition that _Can_ make cargo more self-serving when it comes to plants, Which can be a problem, But it was not made with cargo, specifically, in mind. While hydroponics boards can be ordered, i often find that when science isn't rushing research it tends to heavily get neglected. The public gardens do often have biogens and seed extractors, Though in most cases they oft lack hydro-trays in favour for dirt piles. This pack heavily favors those maps, _Especially Pubby with its lack of easily reachable public gardens as its hidden in maints_. 

 As for making it into its own seperate file instead of merging it with the pack.dm file, It was a small oversight from when i was coding, as i started coding and pulling from the oldrat bloat.dm file (Hence the shared name), Ontop of forgetting to branch off of my master branch before starting to code it. While I dont _Personally_ see a problem with it, I can merge if it becomes a problem of organization.

**Comment by Zenitheevee** [comment]
Changelog 1: 
+Commenting out Hydrohelper pack for redoing and re-packaging with another PR. 
+Adjusting contents of Mafia crate to look more genuine for mafia member, Switching out the black jumpsuit for a bartender uniform and giving a waistcoat for that _Authentic_ look

**Comment by Zenitheevee** [comment]
er... If i could get some information, Be it even things to remove, or pricing ideas, As.. this has kinda been in what seems like a stalemate for a while... That would be appreciated if it means getting this done through faster.

**Comment by Zenitheevee** [comment]
Seeing as several things have decided to happen while this was sitting in purgatory, I'm going to merge master in and do some rebalancing. This should also help prevent the PR from being marked as stale as its been unattended to for almost 2 weeks now.

**Comment by Gandalf2k15** [comment]
Hey, can you change the skyrat edit comments to be like those on the document?

**Comment by Zenitheevee** [comment]
> 
> 
> Hey, can you change the skyrat edit comments to be like those on the document?

Give me a short minute, i also need to kershuffle some stuff around regarding a recent merge

**Comment by Gandalf2k15** [comment]
Ah, no, do it like this: //SKYRAT EDIT ADDITION - MISC

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
