### PR TITLE
[NON-MODULAR] Admin Marks

### PR DESCRIPTION
**Pull request by ZephyrTFA**
Adds the ability for admins to assign special little icons to players to denote them.
image

Host Approved.

:cl:
admin: Player Marks, accepts any emoji, find them in the Player Panel and the Who verb
:/cl:

### CODE REVIEW

**Comment by FlamingLily** [comment]
How long do the marks last for?

**Comment by ZephyrTFA** [comment]
> 
> 
> How long do the marks last for?

Until cleared

**Comment by FlamingLily** [comment]
Nice

**Comment by KathyRyals** [comment]
You would have a decent chance of getting this merged upstream, I think. I certainly would appreciate a feature like that as a tg admin. Too bad about the freeze.

**Pull request closed without merging**
