### PR TITLE
Removes nymphomania entirely.

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request
This PR either removes or comments out all mentions of nymphomania in the game's code. 

## How This Contributes To The Skyrat Roleplay Experience
Nymphomania is a quirk that is entirely useless, and only serves to make the game a lot worse. You can roleplay horny characters, instead of using a needless mechanical restriction that cannot be controlled, and is not loose enough to be able to be applied to most characters. It's like a ethical pacifist taking the pacifist quirk. 

Plus-its code sanctioned prefbreak. Why should we have to suffer people literally MASTURBATING in public, blushing in public, all that? Why should we have to hear people literally jacking off in the bathrooms from across the map? Without this quirk, we can actually take goddamn action both IC and OOC. All this quirk does is serve as a justification for people to act like horny assholes in public, with no fear of retribution, **because they literally die if they DON'T masturbate.**

People that use this quirk currently don't need it, and can simply roleplay it instead. I predict this PR will get backlash from those that use the quirk, but I firmly believe this is a net positive.

## Changelog

:cl:
del: Removed nymphomania.
/:cl:

### CODE REVIEW

**Comment by IsaacTheSharkWolf** [comment]
Agreed, perhaps add it as a flavor quirk that doesn't really do much of anything so that it can be roleplayed as a condition.
Shouldn't have any mechanical purpose though.

**Comment by nikothedude** [comment]
> Agreed, perhaps add it as a flavor quirk that doesn't really do much of anything so that it can be roleplayed as a condition. Shouldn't have any mechanical purpose though.

Fair, but you don't need it as a quirk to play as if you have that as a condition. People would view you as ridiculous if you didn't have it officialized, though.

**Comment by IsaacTheSharkWolf** [comment]
> > Agreed, perhaps add it as a flavor quirk that doesn't really do much of anything so that it can be roleplayed as a condition. Shouldn't have any mechanical purpose though.
> 
> Fair, but you don't need it as a quirk to play as if you have that as a condition. People would view you as ridiculous if you didn't have it officialized, though.

Well it is supposed to be sort of like a medical/psychological condition.
By removing the mechanical bits and making it flavor only you can legitimize the roleplay somewhat, in return allow psychologists and medical doctors to take action if they roleplay themselves getting out of controll, like perhaps some drug that calms them down.

**Comment by IsaacTheSharkWolf** [comment]
But it may just be easyer to remove it all outright, which is also a good option.
Some people will get butthurt but nothing really changes aside from the fact they will have to grow a pair and owe up to the fact they are roleplaying as a nymphomaniac instead of being "forced"  to roleplay as one due to how they made their character

**Comment by Lamella-0587** [comment]
Hi! I'm the author of this quirk. We're planning on maintaining nymphomania and improving the user experience with this quirk. May I ask you to not remove this, please? It's an optional feature with mechanics that was working nicely, but with some balance and mechanics improvement required, still, we're working on it. Please, stop erasing our content. Thank you!

**Comment by Gandalf2k15** [comment]
Delete the code, don't comment it out

**Comment by nikothedude** [comment]
> Hi! I'm the author of this quirk. We're planning on maintaining nymphomania and improving the user experience with this quirk. May I ask you to not remove this, please? It's an optional feature with mechanics that was working nicely, but with some balance and mechanics improvement required, still, we're working on it. Please, stop erasing our content. Thank you!

I'd rather this quirk be disabled until it's improved. I haven't **seen** any active improvement done to this quirk to make it less creepy to be around, and thus, I'm proposing it be disabled until you make it less creepy. 

Your quirk's mechanics also _dont_ work nicely, if you read what I said, your quirk makes people masturbate in public with no fear of retribution, ic or ooc. To me, and many others, this is really, really, really creepy, and we really don't want to see it.
 
And please don't say I'm "erasing your work", I'm not, it still exists, it's just not in the game anymore. Removing features that don't work well and/or disabling them is a normal aspect of game design.

**Comment by nikothedude** [comment]
> Delete the code, don't comment it out

suuuure

**Comment by nikothedude** [comment]
I suppose I could just, disable the emotes, but that doesn't solve the issue of people using fleshlights in the restroom and people having to suffer from hearing _plap plap plap_ every so often. Not nympho's fault though.

**Comment by dawsonkeyes** [comment]
good removal

**Comment by OctusGit** [comment]
Incredibly based

**Comment by Lamella-0587** [comment]
that hurts

**Comment by nikothedude** [comment]
> that hurts

Sorry, but it's not like I'm holding you at gunpoint. If this is merged, all you have to do to re-add this is confirm with maintainers what's acceptable and change it to be that way. Or even now, honestly. Nothing's stopping you.

**Comment by restlessObserver** [comment]
Hi, im from your fellow server, with same code, but russian community, annnnnnd... Honestly im agreed with previous statements. Our horny player picking this quirk  only for justifying of their job-leaving (especially serious jobs like medics, command and engineers) and thats all.

**Comment by Stalkeros2** [comment]
Nothing better than the sense of cooperation.

**Comment by GoldenAlpharex** [comment]
> that hurts

If you manage to add it back in a non-intrusive way, go ahead. But as it stands, it's simply not polished enough.

**Comment by Stonetear** [comment]
[If only there was a convent and easy to make drug for dealing with this...](https://skyrat13.tk/wiki/index.php/Guide_to_chemistry#Camphor)

**Review by GoldenAlpharex — APPROVED** [review]
Arousal code is so ugly, grrrr... But thankfully for you, this is just a removal so I won't ask for anything else regarding it.

**Pull request merged**
