### PR TITLE
Fixes the ghost role spawner spawning a naked human while waiting on you to decide whether you want to use the character from your preferences or not

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
## About The Pull Request
That was a very silly bug that was annoying me a little. Now it doesn't do that anymore.

However, now, when you spawn, you drop the box, which I'm not entirely sure of the reason why it does that. If anyone would know, I'd love to hear it, because that's also going to be annoying in the long run.

## How This Contributes To The Skyrat Roleplay Experience
Less bugs = more better experience.

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  It doesn't spawn you as a naked human ahead of time anymore. I don't remember if I took screenshots of it or not, but either way they're gone now, as I tested this yesterday evening.
</details>

## Changelog
:cl: GoldenAlpharex
fix: Ghost role spawners no longer spawn a naked human while waiting for you to click "Yes" to the fact that you want it to use a character from your preferences.
/:cl:

### CODE REVIEW

**Comment by RimiNosha** [comment]
Can you double check to see if this fixes backpack contents being doubled? If so, I can scratch that off of my pile of crap to fix before backgroundsv2.

**Comment by Zergspower** [comment]
could we also bring back the alias function with this?

**Comment by RimiNosha** [comment]
Agreed, it'll hopefully reduce the amount of accidental station-side names on syndie roles and vice versa.

**Comment by GoldenAlpharex** [comment]
> Can you double check to see if this fixes backpack contents being doubled? If so, I can scratch that off of my pile of crap to fix before backgroundsv2.

Which backpack contents? Like, in which situation does this happen?

**Comment by GoldenAlpharex** [comment]
> could we also bring back the alias function with this?

What alias function?

**Comment by YakumoChen** [comment]
> > Can you double check to see if this fixes backpack contents being doubled? If so, I can scratch that off of my pile of crap to fix before backgroundsv2.
> 
> Which backpack contents? Like, in which situation does this happen?

happens for certain interdyne roles for sure

**Review by Zonespace27 — DISMISSED** [review]

**Comment by Tastyfish** [comment]
> > Can you double check to see if this fixes backpack contents being doubled? If so, I can scratch that off of my pile of crap to fix before backgroundsv2.
> 
> Which backpack contents? Like, in which situation does this happen?

I pulled this PR, spawned as an Interdyne bio scientist, and spawned with 2 rifles and 2 marakovs so the loadout is still being partially being given twice for them. As well, I didn't spawn with codespeak, so the special() call might be busted I don't know.

**Review by tf-4 — APPROVED** [review]
Seems fine to me. Alias feature was dumb and encourage laziness, not really interested in seeing it again

**Pull request merged**
