### PR TITLE
[NON-MODULAR] changes map voting to exclude both box maps if one would be excluded

### PR DESCRIPTION
**Pull request by dankmemerino147**
## About The Pull Request

see title. If either icebox or journey is put on the blocked_maps list, the other one will be as well. (the blocked_maps list handles excluding maps from voting and rotation)

## Why It's Good For The Game

icebox and journey are fundamentally the same map; not having this change can, and has, lead to streaks of only box being played, which is part of what the blocked_maps list is designed to prevent.

"well actually icebox is multi-Z and journey isn't" fuck off immensely. the fact that the phrase "box maps" is understood to refer to both of them illustrates that they are the same map for >90% of intents and purposes.

## Changelog
:cl:
fix: box maps are treated as one map for map voting/rotation purposes
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
I for one would just like Icebox gone while keeping Journey but I'm ~~absolutely~~ probably biased seeing as it's my work 🤡

**Comment by dankmemerino147** [comment]
i have no clue why that runtime is happening, it's not affected by anything i changed

**Comment by FlamingLily** [comment]
Nonmodular, actually, but commented correctly so it's fine.

**Comment by dankmemerino147** [comment]
> 
> 
> Nonmodular, actually, but commented correctly so it's fine.

oh i'll change it then

**Comment by SpaceVampire** [comment]
Playing on those maps doesn't feel like the same thing at all.
The location and design totally matters.
Why is people voting for what they want to play an issue?

**Comment by ZephyrTFA** [comment]
These maps play and feel completely different. I don't see the need for this

**Comment by Gandalf2k15** [comment]
Yeah the maps are completely different. This is an indirect way to kill icebox. People vote for what they want. This is also an indirect way to restrict their vote.

**Pull request closed without merging**
