### PR TITLE
Revert "[MODULARISATION AUDIT] Role preferences defines"

### PR DESCRIPTION
**Pull request by Zonespace27**
Reverts Skyrat-SS13/Skyrat-tg#15014
Prefs don't work with this PR

### CODE REVIEW

**Comment by Zonespace27** [comment]
image
the skyrat antags (drifting contractor, lone infil) auto-disable

**Comment by Zonespace27** [comment]
also this
image

**Comment by Gandalf2k15** [comment]
explain to me why not

**Comment by Zonespace27** [comment]
> explain to me why not

Best I can figure it's something to do with the init order of them and the global list of antags on 107/114

**Comment by Gandalf2k15** [comment]
OK

**Pull request merged**
