### PR TITLE
[SEMI-MODULAR] Makes firelocks manually openable

### PR DESCRIPTION
**Pull request by FlamingLily**
## About The Pull Request
Title says it all.

## Why It's Good For The Game
Icebox.

But seriously, being trapped behind a firelock because of depressurization sucks, and as scummy as NT is lore-wise, they probably wouldn't skimp on a really cheap way to prevent deaths. 

## Changelog
:cl:
add: After repeated incidents on their "Icebox" line of standardized research stations, NanoTrasen has added a manual override lever to their emergency shutter designs!
add: Added flavour text when attempting to crowbar (or manual override) a welded firelock.
/:cl:

### CODE REVIEW

**Comment by FlamingLily** [comment]
I said I'd do it, 'inn'I?

**Comment by FlamingLily** [comment]
MONKEEEEEEEEEEEEEEEEEEE

**Comment by Gandalf2k15** [comment]
I like this, the manual override is a good idea.

**Comment by KathrinBailey** [comment]
I like this but I honestly feel this is something TG would go for.

**Comment by FlamingLily** [comment]
> I like this but I honestly feel this is something TG would go for.

Check the first iteration of this, I did check with TG and they said they didn't want it

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
