### PR TITLE
[modular][ready] formal wear for medical and engineering in loadout, gas masks unadded, but coded

### PR DESCRIPTION
**Pull request by thestubborn**
## About The Pull Request
image
start of the project

## Why It's Good For The Game

formal wear is good, unadded to venders, will do down the line later
not the viro one
that's too cursed for our world, adding that to the vendor will cause some ark of the covenant shit

## Changelog
:cl: Howo Boss
add: Added formal wear for Medical, Engineering and the Quartermaster
add: some more gas masks to the code
add: will to live 2.0
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
rule 5 of improv always say bones

**Comment by Gandalf2k15** [comment]
Add the new captain uniforms to the loadout?

**Comment by thestubborn** [comment]
> 
> 
> Add the new captain uniforms to the loadout?

will do hold on

**Comment by thestubborn** [comment]
done

**Comment by pinkblossom6** [comment]
I just checked these out in the thunderdome. The icon paths are incorrect and are resulting in a checkered item instead. (For

(They're pretty cool though, none the less!)

edit: only for the gas masks

**Pull request merged**
