### PR TITLE
FlotillaStation DNM [MDB ignore]

### PR DESCRIPTION
**Pull request by LovliestPlant**
## About The Pull Request
Adds a new 2 Z-level map intended for low to mid pop (it can support a full crew so actual ideal pop is tbd). Gameplay areas of focus will be EVA activities and player construction. RP flavor is largely centered on showcasing lore related assets from the various factions in our lorebase.

<details>
<summary>Map Upper/Lower Screenshots</summary>
 
[EDIT: Maps up to date as of QA pass 3]

2023-06-08 TOP

</details>

Department POI's:
- Command (NT): Integrated AI sat, combination evac / arrival terminal, shard SM
- Sec (Vox Shoal): Pure Nitrogen atmosphere on upper level (apart from spawn room / quarters), modular shooting range, plasma/oxy turbine.
- Engineering (Moffic Fleet): integrated "gas scoop" atmos miners, external life support hookups for all gasses, shard SM.
- Service (Teshari League for Self-Determination): Integrated Dorms, Courtroom, public garden. Solar arrays.
- Medical (SolFed): Large open hangar area (chem factory space), integrated quarantine room, plasma/oxy turbine.
- Science (Akulan New Principalities): BIG solar arrays, in-house pool for aquatic comfort, observation deck, extra lockers to store shoredresses once #20131 is merged.

All departments possess nominally independent power and atmospheric systems. Map-wide power is pre wired, and hookups for air/waste/fuel as needed are pre placed for each department.

<details>
<summary>Modular Shooting Ranges</summary>
  
rng_1

rng_2

rng_3

rng_4

rng_5

</details>

Modular additions include:
- A host of new areas
- floor turfs, *air alarms, and scrubbers which support a pure nitrogen atmosphere.
- subtype of the camera console for use in modular shooting ranges
- subtype air sensor and incinerator control console for use in Medbay turbine

TO DO:
- Fix Isolation cell timers not broadcasting on the radio
- Build and implement air alarm helpers for Nitrogen atmosphere

## How This Contributes To The Skyrat Roleplay Experience
In-house maps are much easier to maintain with respect to local changes and tweaks to suit community and gameplay developments. FlotillaStation is intended to provide a space for showcasing and/or testing out lore related assets as they are developed. Spaces like this and other in-house maps will be foundational to efforts to implement our lore in-game when the time comes.
In the mean time, FlotillaStation was designed with open and easily accessible RP space in mind, no longer will we be shackled to the Bar for RP opportunities!

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

COMMAND 

cmd_up

cmd_lib

ai_sat_aft_05-28

cmd_evac

cmd_sm

ENGINEERING

eng_up

eng_sm

eng_low

SECURITY

sec_office

sec_shoot

sec_perma

SERVICE

serv_rear

serv_low

MEDICAL

medbay_aft_upper_05 28

med_low

CARGO

cargo_up

cargo_fore_lower_05-28

cargo_aft_lower_05-28

SCIENCE

sci_up

sci_low

</details>

## Changelog

:cl:
add: Adds a new map, FlotillaStation!
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
https://user-images.githubusercontent.com/82386923/236033833-3ef7433a-b462-4374-9ba7-cf56147a4e05.mp4

**Comment by KathrinBailey** [comment]
Two things from a quick glance on my phone.
1. Make sure you test mail sorting and have it fully working. Make packages, tag them, change their and send them down. Use the follow/jump commands in the VV panel to go to the packages and make sure they pop out in the right bins. This is a hard requirement, mail sorting isn't hard and we can help with it if need be. TG made it much easier with mapping helpers anyway.
2. Prison kitchen has regular walls connecting to security. These need to be really. Additionally, the prison really should have an oven and a reagent grinder if you're feeling generous enough to let them have fun baking. They also need a bar/botany chem master OR the tribal ash walker centrifuge.

**Comment by press-mark** [comment]
cool map. make sure you run the debug mapping verb tests on it!

**Comment by QuacksQ** [comment]
Do we really need a supermatter right next to arrivals?

**Comment by W4rd3nn** [comment]
Looks neat my only concern is why is cargo and science parked nose to butt?

**Comment by LovliestPlant** [comment]
@KathrinBailey 
1. Mail system added and tested! Had to run a new piping network for it, IIRC the sorting helpers didn't exist when I start work so the map didn't have that functionality at first.
2. Thankq for catching that wall in perma. Additionally inmates can now enjoy the wonders of soup.

@W4rd3nn 
I was going to say there would've been some crazy amount of re-engineering needed to move sci back any further, as I'd tried earlier. Apparently I fixed whatever the issue was and could make the move without much fuss :D. The Akulan New Principalities no longer drive like they're from Philly.

Map SSDM screenshots are updated!

**Comment by HushTD** [comment]
As a mapper, only one question...
image

Still, love the science tegu...

**Comment by LovliestPlant** [comment]
special attention given to pets (McGriff is on vacation at the bridge due to sec being N2 😄)
Maints insofar as "slipping around the map discreetly" is p much just the space between departments. I made sure to include at least a couple of MODs in each dept, ditto for external airlocks on each Z-level in each dept.
"hiding and renovating" maints are gonna be the thruster rooms, them little shuttles dotted about, and player made areas using some easily accessible tools and life support hookups innervating the map.

**Comment by LovliestPlant** [comment]
QA Pass #3 "Learned What Updatepaths Are"
New Isolation Cells
Flot_WindoorIsolations

Re-Arranged Shooting Range 2
Flot_ShootingRange_classroom

**Comment by Jolly-66** [comment]
I would like to just make this clear to all contributors who wish to take on ambitious projects (not just mapping) in the future: Please reach out to one of us, the maintainers, before doing so so we can help iron out any potential issues or tell you if your project would be applicable for Skyrat.

Secondly, I would like to extend my thanks to you for spending time on this map for how long you've been working on it. It was no doubt an ambitious project you undertook.

However, the general consensus among the other maintainers and myself is that we don't really want this map.

There's a lot going on. The general disconnection of departments, narrow hallways in some places and some designs not making sense.

As a result, I'll be closing this PR. Thank you for your time and the ideas you've brought.

**Pull request closed without merging**
