### PR TITLE
Introducing a new space ruin, "Shuttle 8532."

### PR DESCRIPTION
**Pull request by capsaicinz**
## About The Pull Request

_The strangely named "Shuttle 8532."  Once an NT multi-purpose vessel capable of travelling far distances and long durations while remaining completely self-sustaining, now utterly obliterated by an undetected asteroid cutting straight through the middle of the shuttle itself. The Syndicate took the golden opportunity to raid the newly vulnerable and rapidly decaying shuttle, and though the crew fought tooth and nail to defend what was theirs, it seems that neither side quite got what they wanted. Now, Shuttle 8532 is fated to drift across local space for eternity, tempting newly signed space explorers with its weaponry, materials, and loot._

**haha, does this count as a feature? map PR? we'll find out!**

This PR, as said, introduces a new space ruin. Equipped with rather mild loot, it's still certainly sure to sway the course of action for anybody who happens to stumble across it first- whether or not for ill-intentions. The most valuable loot aboard the shuttle is certainly the three armory contraband loot spawners, kept safe in the more secure parts of the shuttle. In order to access them, a player is expected to connect the bottom, engine portion of the shuttle to the upper half, restoring power and lifting the lockdown on the crew quarters area. Along with the armory loot and various maintenance loot, a set of alien mechanical tools can be found in the engine room, and a Syndicate hardsuit within the medbay portion.

## Why It's Good For The Game

Who doesn't enjoy a little bit of story and adventure out on the rims of space? Also, landmines. I just really enjoy cool looking ruins.

Shuttle 8532

## Changelog
:cl:
add: Added a new space ruin, "Shuttle 8532"
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
I feel that alien tools are far too much loot, given away for free. Keep in mind we already have alien tools available from a ruin exclusively designed around them (the greytide research ruin)

I am interested to know what is in the energy turrets as well: Turrets give out their guns when destroyed, so that counts as "loot" as well. Armoury contraband is, I believe, a choice of several _very_ powerful guns, including a combat shotgun, Desert Eagle, or straight up syndicate revolver, and I don't believe even one of those is very appropriate without being fairly well guarded.

**Comment by capsaicinz** [comment]
> I feel that alien tools are far too much loot, given away for free. Keep in mind we already have alien tools available from a ruin exclusively designed around them (the greytide research ruin)
> 
> I am interested to know what is in the energy turrets as well: Turrets give out their guns when destroyed, so that counts as "loot" as well. Armoury contraband is, I believe, a choice of several _very_ powerful guns, including a combat shotgun, Desert Eagle, or straight up syndicate revolver, and I don't believe even one of those is very appropriate without being fairly well guarded.

i’m plenty expecting some issues when it comes to loot- it’s not something i’m all too experienced in in any regard, really. (and i, for one, didn’t even know turrets will give out their guns! hence my general usage of them.)

the front turrets are all laser- though, i completely intend on turning them into simple covers instead, considering the bridge as an entry point is entirely discouraged enough as it is. the main focus of the turrets are the two ballistics on either side of the ship, primarily guarding the maintenance compartments where the armory loot is in the first place. i've thought about removing the armory spawner on the bridge, and instead placing something of far less lethal value (yet still equally valuable— will have to think about that,) and probably will end up doing it.

the alien tools are entirely replaceable as well, considering there’s already a full toolbox of mechanical and electric tools. no real issue would come from removing them, and i’m more than happy to in the name of balance.

one day, i will learn loot and get good.

**Comment by YakumoChen** [comment]
The alien tools should probably go (perhaps leave one alien tool spawner in its place in a more secure spot on the ship). Given the exclusivity of them to a particular ruin, they should not be replicated anywhere else static in space (though I believe certain ruin loot spawners can randomly produce them)

The guns, the biggest reason I'd ask why they're laying around and fully loaded is, "why didn't any of the crew use them to fight the boarders?" 

You could be creative. Leave a few empty magazines near the bodies, or makeshift weapons, whatever feels more appropriate. Remove the spawners. Leave, at best, one weapon of value on the bridge, guarded by the syndicate mob, but don't make it more than of moderate strength. Weapon options you can already find around space are basic laser guns or pistols (including .50s which is exotic ammo), not counting the heavily guarded loot of the Space Battle ruin, if that's still run in TG code.

**Comment by capsaicinz** [comment]
> The alien tools should probably go (perhaps leave one alien tool spawner in its place in a more secure spot on the ship). Given the exclusivity of them to a particular ruin, they should not be replicated anywhere else static in space (though I believe certain ruin loot spawners can randomly produce them)
> 
> The guns, the biggest reason I'd ask why they're laying around and fully loaded is, "why didn't any of the crew use them to fight the boarders?"
> 
> You could be creative. Leave a few empty magazines near the bodies, or makeshift weapons, whatever feels more appropriate. Remove the spawners. Leave, at best, one weapon of value on the bridge, guarded by the syndicate mob, but don't make it more than of moderate strength. Weapon options you can already find around space are basic laser guns or pistols (including .50s which is exotic ammo), not counting the heavily guarded loot of the Space Battle ruin, if that's still run in TG code.

back to work! i've definitely made some changes, as follows-

- the hidden maintenance compartments both spawn a syndicate cosmetic. one also spawns prison contraband (the most powerful of which would likely be the knife or shiv, which is already pretty easily accessible on station) and money. the other spawns a random donk pocket box (tasty), and a random engie only fancy tool.
- the science area spawns two fancy techs (anomaly core, tech disk, or a camera bug), and has a crate of refined plasma.
- medbay has two boxes in a closet- a box of bluespace beakers, and a box of variety syringes. (which DOES include the possibility of a lethal injection, i believe.)
- instead of alien tools in the engine room, it now holds two stacks of iron and glass.
- the bridge is now guarded by two melee commandos, and holds a retro laser gun.

  whew! the turrets remain, but the front four laser turrets have been broken into only covers. the remaining four turrets are /porta_turret/syndicate, so they shouldn't drop any guns. i think. maybe.

**Comment by ghost** [comment]
https://gyazo.com/798000fc334f47cd8e7490b2a3a359a0
they really do be sittin in space doe

**Comment by capsaicinz** [comment]
> https://gyazo.com/798000fc334f47cd8e7490b2a3a359a0
> they really do be sittin in space doe

ever wanted to take a break from maintaining the externals of the ship, but don't wanna go through the process of pressurizing and taking off your EVA gear?

**Comment by NullDagaf** [comment]
> ­> Code Improvement label
>­> No actual code changes

Yeah no. Your GDP shall stay fucked.

**Comment by capsaicinz** [comment]
> > ­> Code Improvement label
> 
> >­> No actual code changes
> 
> 
> 
> Yeah no. Your GDP shall stay fucked.

c'mon now!! blame the bot, not me!

**Comment by capsaicinz** [comment]
also, i think i shoooould be fixing the areas and any problems relating the spawning today. hopefully we can finally push this out or die trying. hotel visits have got me lazy.

**Pull request merged**
