### PR TITLE
[Modular] Adds the asset protection ert

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Adds the asset protection ERT, a Nanotrasen made and staffed ERT team using state of the art technology to protect their bottom line. They are less geared towards killing than their counterparts, the deathsquad, and don't need to be paid as much as the deathsquad teams, therefore making them a more viable solution for taking care of expensive events that DON'T require the crew's complete annihilation.

The files are entirely localized in modular_skyrat/master

~~Posting to get a sense of how people feel, I've got a couple more things to polish up tonight.~~
- ~~Add crowbars~~
- ~~Test multiple players~~
- ~~Populate security belt contents~~
- ~~Give centcomm access~~

All I need is to sprite in a new icon for the ID, but for now I think it's fine.

## Why It's Good For The Game

I don't like admins calling "asset protection" and then a full blown deathsquad shows up, names and all. There's currently nothing in between our "red alert" and "Delta alert (deathsquad)" ERTs. 

## Changelog
:cl:
add: Adds asset protection ERT.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
👎 
Dislike this heavily. This is just Deathsquad but "nice", hardsuit and all.

This only serves to confuse players and is heavy ban bait for anyone who gets the role.

Deathsquad and its loadout are for "complete annihilation". The mere presence of a Deathsquad hardsuit inspires fear. 

The point of the Deathsquad *is asset protection*. "Protect important assets by destroying one beyond hope of recovery so it cant threaten other assets" kind of protect. 

Red alert ERT still gets the best gear in the entire game short of what... a death squad gets. There doesn't need to be an in between because Delta Alert *is the alert level for station destruction*

**Comment by YakumoChen** [comment]
(Also they don't need a crowbar, the pulse carbine is an all access pass)

**Comment by tf-4** [comment]
https://github.com/tgstation/tgstation/pull/56872 pls :(

**Comment by Swiftfeather** [comment]
> [tgstation/tgstation#56872](https://github.com/tgstation/tgstation/pull/56872) pls :(

I don't know what you're referencing? The code I have here is just a modified copy of the deathsquad code

**Comment by tf-4** [comment]
> 
> 
> > [tgstation/tgstation#56872](https://github.com/tgstation/tgstation/pull/56872) pls :(
> 
> I don't know what you're referencing? The code I have here is just a modified copy of the deathsquad code

30 `mob/living/carbon/human/H`
34 `var/obj/item/radio/R`
37 `var/obj/item/card/id/W`

These are all super vague names. I appreciate it's modified dsquad code, but it should still follow that guideline

**Comment by Swiftfeather** [comment]
> 30 `mob/living/carbon/human/H`
> 34 `var/obj/item/radio/R`
> 37 `var/obj/item/card/id/W`
> 
> These are all super vague names. I appreciate it's modified dsquad code, but it should still follow that guideline

Done

**Comment by Gandalf2k15** [comment]
This is admin only content and I'm happy with the changes.

**Pull request merged**
