### PR TITLE
[MODULAR] Contractor nerf

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

This salt PR: 

1) Nerfs the armor values of the Contractor MOD, which in some cases were **higher** than the Elite Syndicate one, to be the same as the classic blood-red Syndicate suit we all know.

        melee = 30 --> 15
        bullet = 40 --> 20
        laser = 20 --> 15
        energy = 30 --> 15
        bomb = 30 --> 35
        bio = 30 --> 100
        fire = 80 --> 50
        acid = 85 --> 90
        wound = 30 --> 25

2) ~~Removes the baton holster module from the Drifting Contractor on-spawn loadout, effectively removing their anti-drop (until they _earn it_ by completing contracts).~~

3) Increases the reputation price of the baton holster module from 1 to 2 ~~3, to be the same as the scorpion hook.~~

All of these changes were suggested by who I believe is the most proficient contractor player right now and, in this regard, truly knows what should be toned down.

## How This Contributes To The Skyrat Roleplay Experience

- Drifting contractors are objectively way too strong right now. 

- A mechanically proficient person who rolls contractor can effectively keep security occupied for an entire round (we're talking at least two full hours of kiting and chasing which is just not fun) and doesn't really contribute to roleplay.

- Such an oppressive and time consuming antag can result in a lot of player opfors being denied because security wouldn't be able to deal with both.

- Hopefully, I mean hopefully, this can incentivize contractor players to be a little less gamey and a bit more roleplayish, though I'm aware this is only possible if security doesn't immediately jump them.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

image

  
</details>

## Changelog

:cl: Gyran
balance: halved the armor values of Contractor armor, to be on par with a standard Syndicate mod.
balance: Increased to 2 the reputation price of the baton holster module for contractors.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
> PR that enables security to steal and use the overpowered baton

I don't see how this encourages roleplay, since it will make security more aggressive

**Comment by Gyrandola** [comment]
> PR that enables security to steal and use the overpowered baton
> I don't see how this encourages roleplay, since it will make security more aggressive

Do you prefer the contractor holding all the cards and kiting security for two hours straight? You're implying security will only roleplay with antags they cannot win against. It's a bad faith assumption and it doesnt change the fact that contractors do need a nerf.

Also
> Such an oppressive and time consuming antag can result in a lot of player opfors being denied because security wouldn't be able to deal with both.

This is perhaps the most important point

**Comment by YakumoChen** [comment]
> Do you prefer the contractor holding all the cards and kiting security for two hours straight? You're implying security will only roleplay with antags they cannot win against. It's a bad faith assumption and it doesnt change the fact that contractors do need a nerf.

How does this make a difference other than, again, encouraging security to be more aggressive and steal the overpowered baton? I don't support a PR that allows security to disarm the one tool they shouldn't be obtaining from contractors

**Comment by YakumoChen** [comment]
Oh and yes, security will, in fact, only roleplay with antags they can't win against. Its a legitimate tactic to stop overbearing antags.

**Comment by Hatterhat** [comment]
maybe contractor just shouldnt be able to get the teleporter that lets them evade a perfectly good fight

**Comment by FarsightedNightlight** [comment]
I'm pretty much in support of this PR because:
A. Contractor armor is _ridiculously_ over tuned; I cannot tell you how many times I've literally been peppered with armor piercing rounds, or MCR shots and just shrugged it off with moderate bruises and burns without even using medicine OR healing viruses. The Syndicate redsuit offers superb protection as well, sure, not as best as an elite suit or even better, but it does offer superior armor over a standard Security team.

B. It removes the anti-drop capability that Drifting Contractors begin with; meaning you have to earn it. It forces you to be resourceful if Security per say, takes your baton and destroys it. People say Security might try to use it, but that is inherently against policy to do so. 

C. Baton holsters becoming 3rep to purchase means that they have to go out of their way to save up reputation to get it. Just like the scorpion hook, the benefits far outweigh the downside of the cost. 

Just because Security might 'abuse xyz', doesn't mean they will. And if they do, then there's always a punishment for it that will encourage otherwise; plus there is always the whole point of your equipment being a double-edged sword. Even as Hatter suggested though, there are inherent ways to disengage a firefight. Example: Black Fulton Kits! Plus, the removal of the experimental hand teleporter uplink would _damage_ things rather than fix them, because Drifting Contractors use a stand traitor uplink. It would just make it inaccessible to anyone who OPFOR'd persay, and wanted to get one. Same case without something such as Sleepy Carp. I'd really only suggest the removal of items if their uplink was somehow classified as non-traitor and thusly could be edited safely without damaging other players with uplinks!

**Comment by YakumoChen** [comment]
I never was against reducing the armour but there's no reason to give security the means or temptation to be able to strip and use the contractor baton. On top of it being the primary tool they need to actually function as the antagonist.

As it stands, contractor players being clever and evading security is not a reason to nerf them, and doesn't have anything to do with the "roleplay experience".

**Comment by YakumoChen** [comment]
Also the armour values don't actually match the blood red hardsuit ones, because you haven't taken to account the armour module they come with.

Contractor suits are actually worse than syndicate modsuits?

https://github.com/Skyrat-SS13/Skyrat-tg/blob/2ae299876d34428fbb8bcedc402d5c4cdd6e0f24/modular_skyrat/modules/modsuit_armour/modsuit_armour.dm#L184

**Comment by Gyrandola** [comment]
> Also the armour values don't actually match the blood red hardsuit ones, because you haven't taken to account the armour module they come with.
> 
> Contractor suits are actually worse than syndicate modsuits?
> 
> https://github.com/Skyrat-SS13/Skyrat-tg/blob/2ae299876d34428fbb8bcedc402d5c4cdd6e0f24/modular_skyrat/modules/modsuit_armour/modsuit_armour.dm#L184



Contractor mods also come with an armor booster module.

**Comment by FarsightedNightlight** [comment]
> On top of it being the primary tool they need to actually function as the antagonist.

I really wouldn't quite say that is the case! Now, if it was something like the abductor baton, I would! But contractors get an uplink, which can allow you to buy a replacement telescopic baton with similar function for just _two_ TC! As for the concerns of Security using it, I believe there was recommendation to somehow lock it to the contractors biometrics akin to an Abductor would. Unfortunately the matter is that players are complaining that they can't disarm the contractors of their baton, which makes it hard to nonlethal them when they can just break cuffs and knock you into stamina crit in two hits. It's a very unfortunate double edged sword. And I would rather see something change, then the antagonist get disabled because nobody wanted to make a change.

**Comment by YakumoChen** [comment]
> > On top of it being the primary tool they need to actually function as the antagonist.
> 
> I really wouldn't quite say that is the case! Now, if it was something like the abductor baton, I would! But contractors get an uplink, which can allow you to buy a replacement telescopic baton with similar function for just _two_ TC! As for the concerns of Security using it, I believe there was recommendation to somehow lock it to the contractors biometrics akin to an Abductor would. Unfortunately the matter is that players are complaining that they can't disarm the contractors of their baton, which makes it hard to nonlethal them when they can just break cuffs and knock you into stamina crit in two hits. It's a very unfortunate double edged sword. And I would rather see something change, then the antagonist get disabled because nobody wanted to make a change.

You can't seriously be comparing a teleporting antag that can buy an identical backup tool to being able to buy a dogshit baton that barely works as a replacement

**Comment by YakumoChen** [comment]
I could also say here something about replacing contractor with the name of any other "round start" antagonist when you argue that contractors can be clever and avoid security

But then I remember that contractors are the only threat security actually gets to fight most rounds any more, because nobody is making OPFORs.

**Comment by FarsightedNightlight** [comment]
> You can't seriously be comparing a teleporting antag that can buy an identical backup tool to being able to buy a dogshit baton that barely works as a replacement

I actually am. Why? Because the Abductor baton is essential for their job, unlike Contractor. It applies a stun, sleep, and cuff. A telescopic baton, or god forbid, a sleepy pen can on a good placement can allow you to loot a security officer; or even get your baton back _if_ it was taken. The contractors baton isn't as job intensive as the abductors is. Maybe with upgrades, sure.

You don't need your baton as a contractor, but it's sure as hell convenient to have. Which, is why you should have a reason to not be so careless in an engagement and lose it. As a non-abductor you benefit from being able to utilize security weapons as well, if they are not mindshielded.

The point is, you have an uplink at your disposal that you can replace your weapon with; even if it's not better. The biggest complaint with contractor has been it's armor, as well as it's no-drop module. If this was such a problem, then OPFOR contractors would be spawning with baton holsters as well.

**Comment by YakumoChen** [comment]
> If this was such a problem, then OPFOR contractors would be spawning with baton holsters as well.

Almost never see people OPFOR contractor, drifters get the bonus because they're midround and get stuff to compensate they've got less time to do objectives

**Comment by FarsightedNightlight** [comment]
> Almost never see people OPFOR contractor, drifters get the bonus because they're midround and get stuff to compensate they've got less time to do objectives

This is true. But it's still not so much a problem if we manage to lock the batons usage to an antag datum I'd say.

**Comment by FarsightedNightlight** [comment]
> > Almost never see people OPFOR contractor, drifters get the bonus because they're midround and get stuff to compensate they've got less time to do objectives
> 
> This is true. But it's still not so much a problem if we manage to lock the batons usage to an antag datum I'd say.

Upon second thought this might not work. Unless the datum works through the registered tablet. Then OPFOR Contractors couldn't use the baton. Unless there was two variants.

**Comment by Gyrandola** [comment]
> > Almost never see people OPFOR contractor, drifters get the bonus because they're midround and get stuff to compensate they've got less time to do objectives
> 
> This is true. But it's still not so much a problem if we manage to lock the batons usage to an antag datum I'd say.

That can be done but it's probably something for another PR

**Comment by burgerenergy** [comment]
I do not think removing the role's saving grace in the form of no-dropping their primary weapon is a good idea. Yes, there are robust souls who take contractor and show off they are, in fact, ss13 solid snake. Most do not, and our community has a habit of dying off in blob events to walls that do not move or friendly fire. The majority are not robust, it's a saving grace to keep a fairly high event, to memory, from just abruptly ending on a wet fart and having bad feels all around. I put it to you that the amount of contractors that actually secure a single snatch is probably in the sub-20% range.

Skill issue, yes, but it's a simple crutch to allow the antag to remain at least nominally effective instead of being neutered due to a single wet sign or stunbaton.

armor sure go nuts whatever

**Comment by YakumoChen** [comment]
For every Caligra (we all know who this salt nerf is targeting) there's 5 bumbling contractors who get caught immediately or try to actually roleplay cleverly and this PR only punishes those 5, when it probably won't affect the Caligra in the slightest.

Keep that in mind when trying to make a balance PR.

Its nerfs like this and the general sentiment of the community that only the highest quality players should write OPFORS or play antag that is the reason nobody wants to play antag currently

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Requires @Zonespace27 's input since they're codeowner for contractor I think.

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
- DCs very fundamentally rely on their baton as their primary weapon and kidnapping tool. I do not want them losing it easily, so the baton holster module can stay
- I'm okay with the module costing 2, but I see no reason for it to take 2 contracts (on par with the instant-fight-ending SCORPION) to obtain
- Justify your armor change specifically please

**Comment by Gyrandola** [comment]
> - Justify your armor change specifically please

I don't know how else to justify the change other than saying that the current values are simply too strong. 40 bullet protection (let's not forget the armor booster module stacked ontop of that) coupled with a stim makes a contractor the equivalent of a changeling running around like crazy while also being functionally impervious to damage. Add to that a darkhealy virus on icemoon and youve got something that, in the right hands, is nearly invincible.

From an in-universe point of view, it also makes you wonder why a kidnapping mercenary is somehow given an armor that is straight up superior to an Elite Syndicate one.

In any case though, I dont believe an armor nerf alone is going to be enough to fix the problem that contractors are right now, but we'll see.

**Comment by ghost** [comment]
>  there's no reason to give security the means or temptation to be able to strip and use the contractor baton.

yeah, security can strip and use most antag gear; but they don't because they'd be bwoinked for doing so, it's against in-game regulations and against ooc policy. this is a goofy argument; by the same logic literally every piece of antag gear should have anti-drop because "security COULD use it if they get their hands on it."

> Oh and yes, security will, in fact, only roleplay with antags they can't win against.

doomposting like this is silly and i could just as easily say something like "contractors will only roleplay if they know they can't win mechanically" and it holds just about as much weight as your comment

**Comment by NotDhu** [comment]
> DCs very fundamentally rely on their baton as their primary weapon and kidnapping tool. I do not want them losing it easily, so the baton holster module can stay

they spawn with 13 TC and can buy plenty of other gear; what's the point of having access to an entire uplink worth of equipment if you straight up spawn with one of the best melee weapons in normal gameplay (only really surpassed by the abductor baton) and can't ever lose it?

the baton being as strong and as reliable as it is has led to most contractors only ever buying like the same 3-4 items that all pair incredibly well with the baton (s-carp, stims, and freedom implants are all incredibly common)

it's disappointing because their baton being as reliable as it is discourages build variety and encourages every contractor to solely play around their baton; there are already ways to get anti-drops from the uplink at the cost of a few TC if they're that worried about losing their baton; and it should be something you have to actively spec into/purchase rather than being a given that every single drifting contractor spawns with.

if you're worried about them losing the baton and being totally unable to ever get another then i think a better approach would be to add spare batons to the contractor uplink for like 1-3 TC; that way if they lose it they can just buy a replacement for a few TC rather than being literally unable to lose it at all. abductors have a similar thing going.

**Comment by EliteRiceFarmer** [comment]
Security main here. HoS main, rather.

I find the armour a bit excessive. Seeing how they can handle a CMG, with 24 shots. Loaded full AP and they just shrug it off.

Then again, not really a problem. Disabler works fine if the contractor doesn't know what they're doing.

The ones with the e-sword and shield are problem. They can tank ballistic rounds to the point that if you don't buy a AMR. You're probably screwed.

I enjoy spending 2-3 hours chasing some robust contractor player. I also enjoy them being overpowered. So my honest opinion is: Nerf or do not nerf, it is your choice.

Nerf would probably let the contractor negotiate. But right now? It's fight or flight mode for both sides: The contractor and security.

As HoS, my first thing to do when there's a contractor is buying a AMR and giving everyone CMGs loaded with AP rounds. Set them to go in pair. Fortunately, with SR rules. I always tell the officers to tell them to surrender first before shooting. Except the contractor ALWAYS shoot us first. Seemingly all the bloody times. That and they blows up when we catches them with our disabler.


PS: If security use contraband (antag stuff) and station is not on red. That's a bwoinkable offence. Bwoink them, broski.

**Comment by softcerv** [comment]
I am unable to approve this, but this looks fine from a code perspective.

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Alright sorry for the delay, IRL work has kept me away from a single shift of space station for almost a week.

I'd much rather we tread lightly.
If you revert the current changes and instead just remove the armor booster module, I'll pester Golden to testmerge it.

Contractors can't do anything but murder-kill their targets without their baton, I really want to see much stronger justification for making the holster harder to get.

The armor booster however does seem to stack to some insane stats.
image
I think this makes contractors the most disabler-resistant antagonist (50% damage reduction) in the game.

**Comment by Gyrandola** [comment]
You dont seem to know whats the problem with contractors.

**Comment by KathrinBailey** [comment]
It's kinda on you to explain the problem if we're not seeing it, it's a pull **request**. Not a pull demand or a pull edict.

**Comment by Gyrandola** [comment]
> It's kinda on you to explain the problem if we're not seeing it, it's a pull **request**. Not a pull demand or a pull edict.

It's all explained in the PR request already. I've already gutted half of the changes at an ex mantainer's request and I dont intend to compromise any further. These changes arent asspulled, they come from the perspective of someone who has dealt with more than enough contractors, has played as contractor AND has consulted with the best contractor player on the scene. Other changes such as the armor booster removal can be done in another PR and not under my name, thus this is closed.

**Pull request closed without merging**
