### PR TITLE
improves some of the ceramic and glassblowing sprites

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
image

## How This Contributes To The Skyrat Roleplay Experience
These were one of the codersprites of all time before, I can only hope these are better than what they were.

## Changelog

:cl:
imageadd: New icons for glassblowing cups, bowls, globes, and plates!
imageadd: New icons for ceramic plates, cups, and bowls!
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
why did create and destroy fail

**Comment by Tastyfish** [comment]
> why did create and destroy fail

`/obj/item/reagent_containers` breaks if `MATERIAL_EFFECTS` is set. Just remove that flag from the glass cup and bowl.

Edit: actually just beakers, so this only applies to the glass cup.

**Comment by Paxilmaniac** [comment]
I thought material effects did transparency for glass and whatever, I was wrong and it was actually also on material color

**Comment by Tastyfish** [comment]
> I thought material effects did transparency for glass and whatever, I was wrong and it was actually also on material color

Yep!

**Review by jjpark-kb — APPROVED** [review]

**Pull request merged**
