### PR TITLE
[NON-MODULAR][TM-FIRST] Cryopods can now store items.

### PR DESCRIPTION
**Pull request by ZephyrTFA**
## About The Pull Request

Cryopods no longer drop all of your items on the ground when you go into cryosleep.

## Why It's Good For The Game

See above.

## Changelog
:cl:
add: Cryopods can store items; and their control computer can dispense them.
/:cl:

### CODE REVIEW

**Comment by capsaicinz** [comment]
i absolutely agree with this. i don't understand at all why they thought it'd be a good idea to merge that drop item thing.

**Comment by GoldenAlpharex** [comment]
Just to be clear, can just about anyone pick up those items from the computer...?

**Comment by ZephyrTFA** [comment]
> 
> 
> Just to be clear, can just about anyone pick up those items from the computer...?

Huh, good point.

**Comment by GoldenAlpharex** [comment]
> > Just to be clear, can just about anyone pick up those items from the computer...?
> 
> Huh, good point.

I have no clue how it was originally implemented, but I feel like making it so it's only people of at least the same access level as the one that was on your card would have access to your stored items.

**Comment by ZephyrTFA** [comment]
> 
> 
> Just to be clear, can just about anyone pick up those items from the computer...?

Problem solved.

**Comment by YakumoChen** [comment]
> 
> 
> i absolutely agree with this. i don't understand at all why they thought it'd be a good idea to merge that drop item thing.

Because TG is more action oriented, with short rounds. Most of the people cyroing are likely to be assistants anyway, and it prevents any important items (like theft objectives) from being lost somehow.

It works better on TG because TG plays much different than Skyrat, and it's better for that style of gameplay.

**Comment by NullDagaf** [comment]
> i absolutely agree with this. i don't understand at all why they thought it'd be a good idea to merge that drop item thing.

Round removal of objective items, hard-to-get gear (see - mining), etc.
Although we don't have objectives so it shouldn't be that big of an issue.

**Comment by Gandalf2k15** [comment]
Seems good, tested in game. Well done lad.

**Pull request merged**
