### PR TITLE
[Modular] New IDs, New Syndicate Icon Trims

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Does what it says on the tin. Tested and working. We can literally make new ID card types, it's super duper easy!
Also implements the unsued syndicate icon trims and removes the rest. They weren't really needed anyways.

## Why It's Good For The Game
Why does my Deck Officer have a Nanotrasen Silver ID, that's dummy.

## Changelog
:cl:
imageadd: Two new generic ID cards are available, silver and gold - Along with a few new syndicate trims to mess with.
imagedel: A bunch of formerly used (now unimplemented) ID trims have been nuked.
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
Going to implement more ID cards.

**Comment by Gandalf2k15** [comment]
No non-modular icon changes

**Comment by unit0016** [comment]
> No non-modular icon changes

oh fuck that was a mistake

**Comment by unit0016** [comment]
Closing this PR because I am unironically too lazy to fix that huge ass mistake
ICON
CHANGE
MOMENT

**Pull request closed without merging**
