### PR TITLE
CI FIX & MAP RESET [MDB IGNORE]

### PR DESCRIPTION
**Pull request by tf-4**
I like it when CI passes

### CODE REVIEW

**Comment by Jolly-66** [comment]
Lmao TG maps making compile maps cry
Prolly be best to reset those

**Comment by tf-4** [comment]
I was yeah just forgot to p u s h

**Comment by tf-4** [comment]
i want gbp

**Comment by tf-4** [comment]
oops

**Comment by Jolly-66** [comment]
> i want gbp

What the fuck I want it too gimme

**Pull request merged**
