### PR TITLE
Massive shuttle refactor and arrivals system change

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

So this is a big one, let's start with general shuttles.

## Shuttle changes
So I've replaced the central command shuttle with a new layout as well as all the escape pods. The credits go to TauCeti for these cool sprites. I did most of the code.

I've also changed up the dock for the ferry too.

Ferry:
image

Escape pods:
image

## Arrivals changes
Welcome... welcome to city 17.

So! Arrivals has changed drastically. Instead of a permanent shuttle, there's a "tram dock" where latejoins arrive. You are then supposed to head into the shuttle interlink and catch it to the station. It moves back and forth and can be called an infinite amount of times.

This adds a new layer of feel to the RP of the game, as though someone is actually arriving from somewhere else. And not some magic shuttle. 

New arrivals shuttle:
image

Tram dock:
image
(I expect people to improve on this! But we gotta start somewhere!)

New emergency shuttle!:
image

Note for custom map makers:
In order to make your map compatable with the new systems, you must set your arrivals docker to look like this, and reposition it. You will also need to move the far away airlock over by 1 square.
image

The centcom ferry has also been updated, you will need to change that dock too. See: DELTA station for an example.

## Changelog
:cl:
add: A new ferry shuttle.
add: New escape pods.
add; New arrivals shuttle.
add: A brand new arrivals system! Head for the shuttle interlink after you arrive on the tram. 
add: Admins can now FORCE a shuttle to dock somewhere. Please, be careful with this.
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
Dear god please give us the shuttle builder/byos aswell, its super cool to be able to build our own spaceships. Weh.

**Comment by hecksadecimal** [comment]
Hope this gets testmerged soon, I really want to see it in action.

**Comment by Gandalf2k15** [comment]
ALSO IGNORE THE FUCKING MULTI COLORED DECALS FUNNY TG IS FUNNY

**Comment by FlamingLily** [comment]
ssexy shuttle

**Comment by Arctaisia** [comment]
Heck yes, 11/10 on this one, I love the tram dock, and the fact that the shuttles have two way facing thrusters is something that alot of space game designs lack, but makes more sense than just one way ones, this is real good

**Comment by unit0016** [comment]
Worried with this one, specifically for Outpost and the ever problematic shipstation.
I've got a big update for Outpost in the works already, that I'm having trouble with detailing out. A new arrivals shuttle being awkwardly hamfisted in isn't... _great._ Along with the new design for the Ferry, which totally screws over the original placement on both maps.

**Comment by Gandalf2k15** [comment]
> Worried with this one, specifically for Outpost and the ever problematic shipstation.
> I've got a big update for Outpost in the works already, that I'm having trouble with detailing out. A new arrivals shuttle being awkwardly hamfisted in isn't... _great._ Along with the new design for the Ferry, which totally screws over the original placement on both maps.

Just redesign arrivals and the Dock. It took me 5 minutes lol.

**Comment by LemonInTheDark** [comment]
Fair warning, tram code isn't very performant by its very nature, since you can't move half of a tram. Warranty void if sticker is removed, etc etc

**Comment by Gandalf2k15** [comment]
> Fair warning, tram code isn't very performant by its very nature, since you can't move half of a tram. Warranty void if sticker is removed, etc etc

Gotcha, no tram funny business here, just good ol'l gordon freeman arriving in city 17 goodness.

**Comment by YakumoChen** [comment]
I really don't like the idea of the arrivals shuttle being pilotable. 

-Being able to travel _from the station_ to the spawn area is a big no bueno.
-Having to arbitrarily wait 2+ minutes to get to the actual station is kind of meh and everything feels like a lot of wait times just to get on station.
-Rare items on tram dock for no real reason. Clear PDA? Double emergency oxygens? I would like to see them not be there.
-Dorms on arrivals just kind of encourages this sort of bad behavior of returning to / staying in Spawn all game. It shouldn't be a place you can return to or should stay in.

The "It's LRP" argument seems kind of weak here. You already spawn on the shuttle traveling to the station most of the time, giving justification to how you're getting there and it doesn't take several minutes to actually _arrive_ to play the game. A game mechanic like spawning in shouldn't need a lot of justification, the important part is getting into the round.

Another big thing this will affect is if the shuttle gets damaged, people will be forced to wait at Spawn where they can't get into the round because riding the long shuttle without air kills them.
The spawn area with all its atmos and jazz will also be a lag issue, most likely and might even create its own problems like spawn area becoming uninhabitable somehow. These are a lot of problems that the arrivals shuttle normally manages to largely avoid.

Overall I feel this rectifies a "problem" that doesn't really need to be created, and instead raises a very large amount of potential weak points and problems itself that hinders the most basic concept of inserting a character into an ongoing round.

**Comment by Gandalf2k15** [comment]
> I really don't like the idea of the arrivals shuttle being pilotable.
> 
> -Being able to travel _from the station_ to the spawn area is a big no bueno.
> -Having to arbitrarily wait 2+ minutes to get to the actual station is kind of meh and everything feels like a lot of wait times just to get on station.
> -Rare items on tram dock for no real reason. Clear PDA? Double emergency oxygens? I would like to see them not be there.
> -Dorms on arrivals just kind of encourages this sort of bad behavior of returning to / staying in Spawn all game. It shouldn't be a place you can return to or should stay in.
> 
> The "It's LRP" argument seems kind of weak here. You already spawn on the shuttle traveling to the station most of the time, giving justification to how you're getting there and it doesn't take several minutes to actually _arrive_ to play the game. A game mechanic like spawning in shouldn't need a lot of justification, the important part is getting into the round.
> 
> Another big thing this will affect is if the shuttle gets damaged, people will be forced to wait at Spawn where they can't get into the round because riding the long shuttle without air kills them.
> The spawn area with all its atmos and jazz will also be a lag issue, most likely and might even create its own problems like spawn area becoming uninhabitable somehow. These are a lot of problems that the arrivals shuttle normally manages to largely avoid.
> 
> Overall I feel this rectifies a "problem" that doesn't really need to be created, and instead raises a very large amount of potential weak points and problems itself that hinders the most basic concept of inserting a character into an ongoing round.

Shuttles have new safety features. They bolt the doors long before it leaves. Also gonna be adding a few more features.

**Comment by GoldenAlpharex** [comment]
I have to say, having tried it a few times, there definitely needs to be a shorter travel time from station to the tram dock, because waiting 30 seconds for that feels entirely unnecessary. It's just something boring that brings absolutely no value to the fact of joining late, it's just delaying people's gameplay for usually no real gain, especially when it's long after round start and that you're absolutely alone up there.

**Comment by YakumoChen** [comment]
> Shuttles have new safety features. They bolt the doors long before it leaves. Also gonna be adding a few more features.

Locking doors is kind of least concern (and last second escape shuttle hops which I've always found to be cool action would be ruined by the escape shuttle doing this). I'm more concerned about a window breaking on the arrival ferry making a 30 second long death ride to the station kill you.

These shuttles also look hard to fix or even deconstruct. Are they normal walls?

I'm also concerned since alternate shuttles seemed to be disabled and that takes a lot of fun out of escape.

These also look notoriously hard for others to custom map new shuttles

**Comment by Gandalf2k15** [comment]
> > Shuttles have new safety features. They bolt the doors long before it leaves. Also gonna be adding a few more features.
> 
> Locking doors is kind of least concern (and last second escape shuttle hops which I've always found to be cool action would be ruined by the escape shuttle doing this). I'm more concerned about a window breaking on the arrival ferry making a 30 second long death ride to the station kill you.
> 
> These shuttles also look hard to fix or even deconstruct. Are they normal walls?
> 
> I'm also concerned since alternate shuttles seemed to be disabled and that takes a lot of fun out of escape.
> 
> These also look notoriously hard for others to custom map new shuttles

They're prefab shuttles, other shuttles can be bought.

**Comment by Gandalf2k15** [comment]
merging before map conflicts make me wanna kill myself

**Comment by FatFatFat1** [comment]
изображение

You mean TauCeti

**Comment by BesumniiChebureck** [comment]
Yes, they took everything from us and could not even write the server name correctly

**Comment by Gandalf2k15** [comment]
> изображение
> 
> You mean TauCeti

Whoops, that's fixed. It's actually in the credits of the code too, dotted around. I think we changed one of the master changelogs.

**Pull request merged**
