### PR TITLE
[SEMI-MODULAR] Expansion to the Barber, aswell as Barbershop fixes/mapping.

### LINKED ISSUE #9174: Barber sign has no inhand sprite when removed from the wall.
## Round ID:
3474

## Testmerges:
The following pull requests are currently test merged:
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit a0622a98fc
#8960: '[SEMI-MODULAR?][TESTMERGE FIRST] Glow in the dark markings/bodyparts/eyes' by Seris02 at commit b769e1dbbc

## Reproduction:

Step 1: Remove barber shop sign from wall.
Step 2: Scream as reality itself rends and you beholden a floating red error sign of death, ensuing the final end of this world.

### PR DESCRIPTION
**Pull request by gonenoculer5**
Heftily expands on Barbershop code in general and gives it an actual reason to exist beyond RP.

## About The Pull Request

Personally speaking, I've always thought barber was an interesting idea, but executed kind of poorly. Some of the code is kind of messy so this PR aims to clean up and even slightly refactor the barbershop code if possible, whilst also expanding on its content to give the station more of a reason to care about this semi-neglected part of the greater whole. This will likely come in a few steps as I work on it and check with @GoldenAlpharex for code review, as detailed below:

First stage of this PR will be adding in the following items:

New Implants:
- [ ] Fab-U-Soft Skillchip: Gives the user an innate understanding in the detailed workings of how to cut, style, and change looks of other players. Required to correctly make use of tools such as the polisher/buffing wheel/nail file.
- [ ] Fabworks Toolset: Gives the implantee a set of built in barber tools, like the botany/janitor toolset. Requires T2 implant tech.

New tools and toys:
- [ ] Scale Polisher/Buffer: Allows the barber to tend to lizard-folk crew, by polishing their scales/talons and the like.
- [ ] Buffing Wheel/Angle Grinder: Allows the barber to tend to IPC and synthetic crew alike, by buffing away rust and other ailments to synthetic crew. 
- [ ] Nail File: Allows the barber to file down nails and talons alike.
- [ ] Associated misc moodlets and such for getting a polishing/grinding/pedicure, along with associated negative moodlets for having this done to you whilst being the wrong species. (Grinding on a human, for example. Ouch.)

All of these items will check for a new skill chip dedicated to the Barber, so that the crew cant just carry around these new tools and self-use them for free mood points. (The exception to this is the Comb and the Brush, because that would just be absurd.)

Stage 2 of this PR is as follows:

Fixes:
- [ ] Make the Comb and Brush compatible with furred anthromorphs, regardless of hairstyle, whilst targeting chest.
- [ ] Make the Scissors multi-step in 8 second increments to allow the target to understand that a haircut is actually occuring, instead of just playing a 3 second sound for a 60 second task, leaving the player confused.
- [ ] Fix Icebox's salon so that it actually have privacy instead of just being straight up open to the public, and adding salon door bolts to the other salons, similar to how Blueshift does it. (Thanks @IsaacTheSharkWolf for that!) and potentially give any non-public door into the salon the barber access requirement.
- [ ] Fix the barberpole's inhand sprite so that it actually has one instead of being a god-defying red error sign. Fixes #9174 

New Content for Traitors and normal Barbers:
- [ ] Massaging/Chiropractice tools such as Actuators, for aligning bones. Bootleg bonesetting surgery for low tier wounds. 
- [ ] "Sweeny Style" loadout kit, barber exclusive. Includes a bloodied straight razor, a new martial art based around accupuncture (maybe), and a book teaching the user on how to make a type of meatpie. Maybe more, TBA at a later date.

## How This Contributes To The Skyrat Roleplay Experience

Basically, this is an overall big expansion to the Barber and how they interact with the station, because frankly just existing to cut hair and stand around with a thumb up your ass is pretty boring. Also gives the crew a reason to interact with the barber beyond RP, in the form of positive moodlets.

## Changelog

:cl: Gonenoculer5
expansion: Three new items for interactability in the barbershop, the Scale Polisher, Buffing and Grinding wheel, and a nail file. New chiropractor tools for massages/chiropractice. New skillchip for the Barber to make them an expert at what they do, at roundstart. New barber shop toolset implant for T2 implants that gives the user a variety of daily use tools.
fix: Fixes the barber pole inhand sprite because it didnt exist in the first place.
fix: Scissors actually do what they are supposed to do now and alert the player using them and the target.
fix: Anthromorphs with fur can actually be combed/brushed now. Rejoice.
spites: Added a new sprite for the barberpole's inhand, Scale Polisher, Angle Grinder, and Nail File. Adds a new sprite for the chiropractic Actuator and Acupuncture needles.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Hello, is this still being worked on? @gonenoculer5

**Comment by gonenoculer5** [comment]
> Hello, is this still being worked on? @gonenoculer5

Yes, still being worked on. It's gonna be up for a while, thats why its a draft.

**Comment by gonenoculer5** [comment]
I have to do some code investigation to find out where the fuck the on_attack() code for the comb and brush are so I can make it check for hair OR species, so that furred anthromorphs can be brushed/combed regardless of hairstyle

**Comment by gonenoculer5** [comment]
> I have to do some code investigation to find out where the fuck the on_attack() code for the comb and brush are so I can make it check for hair OR species, so that furred anthromorphs can be brushed/combed regardless of hairstyle

(because saying that they have no hair when they are in fact, covered in it, is infact, retarded.)

**Comment by gonenoculer5** [comment]
ope gotta update the changelog with the stuff this will be adding.

**Comment by gonenoculer5** [comment]
Before you all scream at me yes I know this has exactly 1 whitespace line commit. Pls.

**Pull request closed without merging**
