### PR TITLE
Better Pay for Blueshield

### PR DESCRIPTION
**Pull request by NItch212**
## About The Pull Request
Changes the blueshield's pay to be on par with command, because a skilled bodyguard deserves better. (literally my first time "coding" for this game)

## Why It's Good For The Game
Makes the blueshield have the pay they actually deserve, the low wages of the past are no longer! (Seriously, they are a professional...ideally)

## Changelog
:cl:
add: Blueshield now has the same pay as command, and an actual defined paycheck in its code
/:cl:

### CODE REVIEW

**Comment by SpaceVampire** [comment]
How much were they payed before? Trying to figure out just how much power creep they have been getting lately.

**Review by MLGTASTICa — COMMENTED** [review]
Put your pay change in Skyrat-tg/modular_skyrat/modules/blueshield/code/modules/jobs/job_types/blueshield.dm , don't create a new file for this when there is already one

**Comment by NItch212** [comment]
> How much were they payed before? Trying to figure out just how much power creep they have been getting lately.

I'm pretty sure they got like minimum pay or something stupid, thing is they didn't even have a existing code line for their pay, so whatever the default is

**Comment by NItch212** [comment]
> Put your pay change in Skyrat-tg/modular_skyrat/modules/blueshield/code/modules/jobs/job_types/blueshield.dm , don't create a new file for this when there is already one

That was a mistake, still new to this

**Comment by Oscari-pog** [comment]
Should be onpar with security tbh

**Comment by YakumoChen** [comment]
isn't Blueshield like a centcomm official or something? They should easily have command level pay.

**Comment by H0gberg** [comment]
they started with like 300 bucks lol

**Comment by Gandalf2k15** [comment]
Hey, please do this modularly as this file already exists

**Pull request closed without merging**
