### PR TITLE
[NON MODULAR] Changes toxins experiments from requirement to discounts.

### PR DESCRIPTION
**Pull request by KathyRyals**
## About The Pull Request

Changes the three current toxins-related experiments from reqs to heavy discounts. Makes the base price way higher to compensate.

image

## How This Contributes To The Skyrat Roleplay Experience

Science has a shit ton of experiments and things to do, and not a lot of people have the knowledge on how to produce good toxins bomb with the new atmos systems and such. This ensures that the weapon techs and all associated techs are still doable in such cases (remember that MCRs are extremely reliant on those and that sec is currently decently reliant on MCRs since we removed other lasers), while still heavily rewarding scientists who do the toxins experiments.

## Changelog

:cl:
balance: Toxins experiments are now discounts and not requirements.
/:cl:

### CODE REVIEW

**Comment by SpaceVampire** [comment]
This really removes the whole point of doing toxins, and you don't need /any/ toxin skill at all to pull of that first level experiment. You can literally just chuck a basic water/potatum grenade into chem from there. You can also already order the many of the important MCR parts from Cargo (using your free cargo orders) anyway, so all this does it stop you from getting the VERY BEST stuff unless someone did their job. Which are already overkill in pretty much every situation.

**Comment by KathyRyals** [comment]
If it's so easy why doesn't it get done so often? Literally, even on the highest of high pop, it's a gamble.

**Comment by Zenitheevee** [comment]
So, I'm in support of this but i would _personally_ suggest bumping it up a bit more. 

IIRC the _base_ cost of weapon research currently is 10k and doesn't go down. 
While this would make it more _rewarding_ for people to actually do the tests... _currently_ its not all that much more expensive than the original price and i have a firm understanding it's experiment _might_ get skipped over 

I _Would_ also, however, Suggest leaving MoG as a _required_ experiment, If only because the stuff locked behind it is _really_ good, and otherwise some of the stuff _might_ be desired to be re-shifted in where its placed.

**Comment by SpaceVampire** [comment]
> If it's so easy why doesn't it get done so often? Literally, even on the highest of high pop, it's a gamble.

People being lazy, and not wanting to put even a minimal level of effort into stuff? Security not pushing them hard enough to unlock it? When I play shaft miner, I always use my power of screaming over the radio at full force every five minutes in order to secure my plasma cutter just like god intended. I'm so glad that ORM upgrades don't matter anymore on that same front.

**Comment by AtoriBirb** [comment]
Think this is a good idea. It really sucks when no one does toxins and you're just like.. welp half my armory is crap now. At least this way you could EVENTUALLY get it, even if you have to beg the RD to waste so much research on it, or wait for late game buildup and excess. At least it would just be possible.

**Comment by thestubborn** [comment]
today in skyrat

soft removing toxins

**Comment by zeratino** [comment]
this
this is good :)

**Comment by Iamgoofball** [comment]
:-1:
These are behind toxins explicitly so that you can't do them every round. Sometimes you don't get things every round. Simply make do with what you have. Nothing in R&D behind the toxins experiments is required to do your job.

**Comment by Aether217** [comment]
> > If it's so easy why doesn't it get done so often? Literally, even on the highest of high pop, it's a gamble.
> 
> People being lazy, and not wanting to put even a minimal level of effort into stuff? Security not pushing them hard enough to unlock it? When I play shaft miner, I always use my power of screaming over the radio at full force every five minutes in order to secure my plasma cutter just like god intended. I'm so glad that ORM upgrades don't matter anymore on that same front.

The difference is that to get your plasma cutter all science needs to do is hit 3 buttons, to get toxins done they need to spend 5-20 minutes depending on how much they set up, run 2 tests if they want to do MoG as well and then research. The comparison is not equivalent because one is just hitting a few nodes under the threat of miners throwing a hissy fit and not bringing resources in while the other is a time investment and some effort over the threat off...?

**Comment by Zenitheevee** [comment]
> > If it's so easy why doesn't it get done so often? Literally, even on the highest of high pop, it's a gamble.
> 
> People being lazy, and not wanting to put even a minimal level of effort into stuff? Security not pushing them hard enough to unlock it? When I play shaft miner, I always use my power of screaming over the radio at full force every five minutes in order to secure my plasma cutter just like god intended. I'm so glad that ORM upgrades don't matter anymore on that same front.

So, Here is part of the issue, As someone who used to play science:
There's no benefit to researching advanced weapons most of the time. 
The biggest reason, From a science central thought process, Are the _mechs_.
Weapon research and everything beyond it only helps _Security_ do their jobs, To the point that sabotaging toxins could genuinely be the one and only thing stopping security from getting their fun toy gun mods and other things. 
And, Going further onto that, Toxins has only been artificially made important. Anomaly cores are niche in use and research generates at a pace that is comfortable to go do experiments between using the console. The experiments themselves are the only thing keeping toxins from being absolutely optional to get all of research done. And quite honestly, I think thats good. Toxins should be a bigger bonus to do than being inflated to a state of requiredness.

**Comment by thestubborn** [comment]
> > > If it's so easy why doesn't it get done so often? Literally, even on the highest of high pop, it's a gamble.
> > 
> > 
> > People being lazy, and not wanting to put even a minimal level of effort into stuff? Security not pushing them hard enough to unlock it? When I play shaft miner, I always use my power of screaming over the radio at full force every five minutes in order to secure my plasma cutter just like god intended. I'm so glad that ORM upgrades don't matter anymore on that same front.
> 
> So, Here is part of the issue, As someone who used to play science: There's no benefit to researching advanced weapons most of the time. The biggest reason, From a science central thought process, Are the _mechs_. Weapon research and everything beyond it only helps _Security_ do their jobs, To the point that sabotaging toxins could genuinely be the one and only thing stopping security from getting their fun toy gun mods and other things. And, Going further onto that, Toxins has only been artificially made important. Anomaly cores are niche in use and research generates at a pace that is comfortable to go do experiments between using the console. The experiments themselves are the only thing keeping toxins from being absolutely optional to get all of research done. And quite honestly, I think thats good. Toxins should be a bigger bonus to do than being inflated to a state of requiredness.

if you believe all this
why not take it upstream? see what they think of soft removing toxins

**Comment by Zenitheevee** [comment]
> > > > If it's so easy why doesn't it get done so often? Literally, even on the highest of high pop, it's a gamble.
> > > 
> > > 
> > > People being lazy, and not wanting to put even a minimal level of effort into stuff? Security not pushing them hard enough to unlock it? When I play shaft miner, I always use my power of screaming over the radio at full force every five minutes in order to secure my plasma cutter just like god intended. I'm so glad that ORM upgrades don't matter anymore on that same front.
> > 
> > 
> > So, Here is part of the issue, As someone who used to play science: There's no benefit to researching advanced weapons most of the time. The biggest reason, From a science central thought process, Are the _mechs_. Weapon research and everything beyond it only helps _Security_ do their jobs, To the point that sabotaging toxins could genuinely be the one and only thing stopping security from getting their fun toy gun mods and other things. And, Going further onto that, Toxins has only been artificially made important. Anomaly cores are niche in use and research generates at a pace that is comfortable to go do experiments between using the console. The experiments themselves are the only thing keeping toxins from being absolutely optional to get all of research done. And quite honestly, I think thats good. Toxins should be a bigger bonus to do than being inflated to a state of requiredness.
> 
> if you believe all this why not take it upstream? see what they think of soft removing toxins

Because:
- i believe to a high extent that TG would put an outright no on it
- i'm not the one making the PR
- The day i take a PR up to TG is the day i resign my sanity, pride and dignity

**Comment by nikita-chekistov** [comment]
Truly idiotic. Simplifying the game for what reason? "Eh... Toxins are hard... bluh-bluh-bluh... I dont know how to bluh-bluh-bluh... I dont want to ask experienced players how that works, so I will simply delete it". 

My opinion is:
If you want to make the game simplier - go play 2d platformers, they are surely would be your level of difficulty.

**Comment by FeenieRU** [comment]
Toxins are not a thing, that should be simplified. I'm not professional in toxins, but I can prepare bomb 5-10-21 without upgrading by RPED and waiting for resources in ten minutes almost at the beginning of the shift.

**Comment by FeenieRU** [comment]
And I tell you a secret for explosion experiment. You can request chem-grenade in chemistry, or... 
Take Firefighter/Plasma Cutter and explode a fuel tank in bomb-testing site.

**Comment by Stalkeros2** [comment]
Learn how to play the game instead of simplifying it.
There's a lot of ways of avoiding the bomb making part, many of them being easier than other, and even then, making a bomb isn't that hard - it's literally chemistry with gases.

**Pull request closed without merging**
