### PR TITLE
[MODULAR] Departmental Baton Sprites Update

### PR DESCRIPTION
**Pull request by MassacreDemigirl**
## About The Pull Request
Makes the departmental batons look fancier and no longer use the contractor baton as their sprite

## How This Contributes To The Skyrat Roleplay Experience
The contractor baton should not be used for other things due to fogging its actual recognizability.

## Media
image
___
engNB
engOFF
engON

## Changelog

:cl:
add: Added new sprites for Departmental Batons
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
[distant ree about lack of photos in PR body]

Here they come...

**Comment by tf-4** [comment]
As predicted: Please use photos of the item _in game_ in the PR body :)

**Comment by MassacreDemigirl** [comment]
image
Done @tf-4

**Comment by thestubborn** [comment]
@Iamgoofball

**Comment by Iamgoofball** [comment]
:+1:

**Review by GoldenAlpharex — APPROVED** [review]
Haha funny advanced roasting stick.

**Pull request merged**
