### PR TITLE
[NON-MODULAR] Remove poggers from the game

### PR DESCRIPTION
**Pull request by linnpap**
## About The Pull Request
"Poggers" is soooo 2000-late! All the cool kids are saying "shewby" now. Of course, saying these words now also come with the realistic internal pain of how fucking stupid you sound, too!

## Why It's Good For The Game
So that mongrels can no longer spout (some) real life memes in game. Possibly also helps develop world building with the creation of in-game fictional memes.

## Changelog
:cl:
add: No one says "poggers" anymore. The new meme is "shewby"
add: Adds a feeling of self loathing whenever you say a meme in-game
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
cringe

**Comment by Cheshify** [comment]
def not poggers, amogus!

**Comment by Gandalf2k15** [comment]
Make this use a JSON to parse the data. Check out the accent code

**Comment by SpaceVampire** [comment]
We already have a word-filter, its done via config.

**Comment by linnpap** [comment]
would it be better if it only gave you a negative mood debuff instead of just outright removing the word?

**Comment by NullDagaf** [comment]
> would it be better if it only gave you a negative mood debuff instead of just outright removing the word?

IMO, do both
but.. ye we already have a word filter. Shittily set up but yeah.

**Pull request closed without merging**
