### PR TITLE
[Non-Modular] Directional meteor waves

### PR DESCRIPTION
**Pull request by NotRanged**
## About The Pull Request

Just like how it was on the old codebase, meteor waves now have a specified direction they spawn the asteroids in.

Additionally, meteor shield sat crates are always available at cargo.

## Why It's Good For The Game

This allows engineers to know where the threat is coming from to prepare, and allows them to actually buy shield sats again when the station goal isn't there.

## Changelog
:cl:
balance: The cost of meteor shield sat crates has been increased to 10k
tweak: Meteor shield sat crates are available to purchase from cargo at all times now.
tweak: The meteor wave event only barrages the station from a certain cardinal direction.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
I don't like the availability of shield sats, they sort of remove the threat of meteors.

**Comment by NotRanged** [comment]
> I don't like the availability of shield sats, they sort of remove the threat of meteors.

Well the current counterplay to meteors is 'guess I'll die lol' which isn't very great either?

I could make the meteor sat crates like 10k each, which would also limit their availability since cargo is always dirt poor nowadays.

**Comment by Gandalf2k15** [comment]
> > I don't like the availability of shield sats, they sort of remove the threat of meteors.
> 
> Well the current counterplay to meteors is 'guess I'll die lol' which isn't very great either?
> 
> I could make the meteor sat crates like 10k each, which would also limit their availability since cargo is always dirt poor nowadays.

I would be fine with that, yes.

**Comment by NotRanged** [comment]
Done.

**Comment by Azarak** [comment]
Make sure to modularize properly. When you change a line make sure to leave the original commented out
//[line] //ORIGINAL
[new_line] //SKYRAT EDIT CHANGE

Also document properly whether something is an addition, change, removal in the comment suffix, make sure its all caps too.

**Comment by Azarak** [comment]
> 
> 
> > > I don't like the availability of shield sats, they sort of remove the threat of meteors.
> > 
> > 
> > Well the current counterplay to meteors is 'guess I'll die lol' which isn't very great either?
> > I could make the meteor sat crates like 10k each, which would also limit their availability since cargo is always dirt poor nowadays.
> 
> I would be fine with that, yes.

I think 10K is a bit much. Cash isnt so easy to get as on the old base

**Comment by NotRanged** [comment]
I'll lower it to 6k

**Comment by atakiya** [comment]
Maybe we add a small probability so they still spawn non-directional? Something like maybe 5% or so.

**Comment by NotRanged** [comment]
Could do yeah, gimme a bit

**Comment by Gandalf2k15** [comment]
Please make the above changes and reopen this once they are complete, thank you!

**Pull request closed without merging**
