### PR TITLE
[modular] Reverts to red sec job icons on secHUD

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
Alternative to #13620
Closes #13620

Security, Warden, Detective, Brig Officer, and Sec Medic have red icons on the secHUD again
QM's icon is command blue with a cargo colour outline to keep it a little distinct from the visually-similar HoP icon like in the other PR

## How This Contributes To The Skyrat Roleplay Experience

Frankly, the clarity of being able to tell security jobs apart from other jobs (namely, command jobs with matching icons) is too important. Like the chat colour for security communications, having it be red and distinct is far more valuable than another shade of blue mixing in with the three other job types that also use blue. (This is in reference to secHUD icons, not the jobs in general)

it's better clarity than dark blue and gold command next to dark blue and white icons anyway.

## Changelog

:cl:
imageadd: Security staff's secHUD icons are once again red, to make them distinct from command and medical's icons.
imageadd: the Quartermaster has a more command-coloured secHUD icon.
/:cl:

### CODE REVIEW

**Comment by MassacreDemigirl** [comment]
good for readability

**Comment by theselfish** [comment]
Maybe we could also change the *uniforms* to match this colour, for readability alone I mean. No other reason...

**Comment by Zergspower** [comment]
Yeah i have zero clue why the change was made, it made telling who the HOS was against regular secoffs a nightmare for example.

**Comment by theselfish** [comment]
@YakumoChen Are you sure the Brig Officer wasn't changed?

**Comment by YakumoChen** [comment]
I forgot brig officer I think, hold on

**Comment by YakumoChen** [comment]
I'm not even sure what that icon is supposed to be tbh

**Review by GoldenAlpharex — APPROVED** [review]
I'm in support of this, it's probably sadly the best solution we have with the resolution we're using.

**Comment by theselfish** [comment]
I still think the QM icon should be a gold and blue version of the Cargo Tech icon, to keep in the theme of other heads.

The RD is a b/g version of the scientist icon.
The HoS is a b/g version the sec officer.
The CE the Engi.
CMO, Medi.

The only outliers are Cap and HoP.

**Comment by YakumoChen** [comment]
On the fence about it. Tbh if you want to do that to the QM icon you're free to PR it after this

**Comment by GoldenAlpharex** [comment]
Yeet.

**Pull request merged**
