### PR TITLE
[modular] fishin'

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
adds fishing...
you can get some ores, strange rock, and fish if you fish from water
image
image

## How This Contributes To The Skyrat Roleplay Experience
fishing. its a vibe... not combat!

## Changelog

:cl:
add: added fishing
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
based citrp port

can we get a comfy indoor lake next?

**Comment by Arctaisia** [comment]
You need to add the cap. I will not fish unless I have a cap that reads just how much those fish fear me.

Still, nice~

**Comment by jjpark-kb** [comment]
> based citrp port
> 
> can we get a comfy indoor lake next?

??? Im sorry but this isnt at all a citrp port...

**Comment by thestubborn** [comment]
> 
> 
> You need to add the cap. I will not fish unless I have a cap that reads just how much those fish fear me.
> 
> Still, nice~

hold on I know this one
https://github.com/tgstation/tgstation/pull/60512

**Comment by thestubborn** [comment]
> 
> 
> > based citrp port
> > can we get a comfy indoor lake next?
> 
> ??? Im sorry but this isnt at all a citrp port...

damn, citrp has bait and other fishing stuff, its cool

**Comment by GoldenAlpharex** [comment]
https://www.youtube.com/watch?v=jYE-1HfReQo

**Comment by Arctaisia** [comment]
> > > based citrp port
> > > can we get a comfy indoor lake next?
> > 
> > 
> > ??? Im sorry but this isnt at all a citrp port...
> 
> damn, citrp has bait and other fishing stuff, its cool

It has way too many differences to what their system is to be a port, plus, Jake made this from the ground up, from what I assume.

Plus, it's originally a Polaris/Bay thing, not CitRP, CitRP is a Downstream of VOREstation, which is a downstream of Polaris, and so on.

**Comment by thestubborn** [comment]
> 
> 
> > > > based citrp port
> > > > can we get a comfy indoor lake next?
> > > 
> > > 
> > > ??? Im sorry but this isnt at all a citrp port...
> > 
> > 
> > damn, citrp has bait and other fishing stuff, its cool
> 
> It has way too many differences to what their system is to be a port, plus, Jake made this from the ground up, from what I assume.
> 
> Plus, it's originally a Polaris/Bay thing, not CitRP, CitRP is a Downstream of VOREstation, which is a downstream of Polaris, and so on.

again, my monkey brain sees two of the same thing...

**Pull request merged**
