### PR TITLE
[Semi-Modular] The Charlie Station Overhaul

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Finally. It's here.
Did it pull you out of the game that every time you played Charlie, you woke up over a hundred years later. Repeatedly?
Did it bother you that almost nobody bothered with the SM? Botany?
What about the cryopods being inconsistent?
Well. This, everyone. Is the solution. A new, streamlined Charlie station experience. No more flamethrowers to burn out the alien resin. No more weird IC inconsistencies.

## Overview
Players take control over 5 stranded Nanotrasen Employees in a 'modern' (Repurposed from the cheapest parts possible) Nanotrasen Supplemental Outpost Facility, ransacked by Syndicate Forces and internal strife. There is no 100 year timejump. You are current day employees. What little of the station remains - a mere part of Beta, along with Charlie and Delta - Are occupied, and near ready to be rigged to blow. Just evac, right? Small problem. You can't get a distress signal to Central Command, ~~and you have built in implants that force you to stay here~~. (Removed on request.) Even if you could get the word out, this is a confidential site. You're going to be stuck here. A full RND kit is already on-deck (Surprisingly the servers are separated (though the actual research isn't.)) Along with three boltable dorms, and two extra unboltable ones in the prison. Also a pool.
image

## Requested Policy
I would _greatly_ prefer if stationchars could be used here. It's not a requirement for the role to work - not at all - but gosh darnit, they aren't getting a use from me as is.

## Why It's Good For The Game
Charlie, as-is, is a weird holdover role that doesn't make sense IC and is almost ever only used for cybersun's benefeit via raiding. This fixes that, also makes it more fun for sandboxy folk in the process -basically brings it up to par with new cybersun.

## Changelog
:cl:
add: From the internal dossier: Central Command has recommissioned Charlie-Class stations as supplementary sites.
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
Bluespace locker is throwing errors here for some reason?

**Comment by unit0016** [comment]
I love a smooth update.

**Comment by Gandalf2k15** [comment]
I'd be happy with this if you could remove the implant making you stay there

**Comment by unit0016** [comment]
Done

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by GoldenAlpharex** [comment]
Ah, yes, a pool on Charlie station.

**Comment by unit0016** [comment]
> Ah, yes, a pool on Charlie station.

I should take an oath to always include pools with my work after the Icebox lag being blamed on the pool tbh

**Pull request merged**
