### PR TITLE
Removes the upgrade requirement on Soda Machines for the juices

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

I never really understood why it needed a beaker upgrade to unlock more juices, and given how hard it is to get upgrades without yelling 50 times this just resolves that. The upgrades also jumble the entire juice list making it just annoying to even find what you need half the time.

image

## How This Contributes To The Skyrat Roleplay Experience

You still very very very much want an upgrade for the machine itself as the base machine is still ass and drains fast, this however lets us use roundstart juices that a lot of our custom SR recipes use.  

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  New machine, nice and sorted as well
  
  
image

</details>

## Changelog

:cl:
qol: Soda Machine recipe - removes upgrade requirement for the locked juices (not emagged)
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
If you want these juices without upgrades I still believe you should go to the people right next door who's job it is to grow the fruits these juices come from.

**Comment by Zergspower** [comment]
> If you want these juices without upgrades I still believe you should go to the people right next door who's job it is to grow the fruits these juices come from.

Still need the machine to get upgraded that isnt going away, and i dont think anyone has gone to botany from the bar outside of getting the more exotic items to mix such as peppers and chocolate

**Comment by Paxilmaniac** [comment]
> > If you want these juices without upgrades I still believe you should go to the people right next door who's job it is to grow the fruits these juices come from.
> 
> Still need the machine to get upgraded that isnt going away, and i dont think anyone has gone to botany from the bar outside of getting the more exotic items to mix such as peppers and chocolate

People do this all the time what? I saw it happen multiple rounds of a bartender asking for berries and such because they didn't have the juice.

**Review by tf-4 — COMMENTED** [review]
Just wait for upgrades or ask botany.

**Comment by Zergspower** [comment]
I asked for prior approval to even doing this and got it from Zone, there's no reason for this timelock to be in place - i can understand a chem machine but even the booze machine doesnt have it. You still need to get your ugprade anyway because the base machine is complete ass and recharges 1u /10sec

**Comment by theselfish** [comment]
Is it really that much of a hassle to...

Talk to people?
PDA someone who can upgrade? Go to the desk of a department that can do that?
You know, roleplay?

**Comment by YakumoChen** [comment]
Hydroponics is only a :v away

**Comment by tf-4** [comment]
@Zonespace27

**Comment by Zergspower** [comment]
Again this doesnt remove the _need_ to do upgrades as the stock booze and soda machine is complete shit, you still need to go to botany and chemistry for the special ingredients as well.  The only 'gain' here is being able to make our(SR exclusive) drinks without losing a 3rd to half the round for no other reason than we put an arbitrary ingredient lock behind them when not even TG has those.

copying Jungle as he said it well
upgrades at the least engaging part of the game 

literally no one has ever asked botany for juices like, period, because they just wait for parts because why not?

and waiting for the parts adds nothing but time-gates to something, for the sake of timegates, which is more of an upstream thing then a consideration here

**Comment by theselfish** [comment]
> literally no one has ever asked botany for juices like, period, because they just wait for parts because why not?

Didn't @Paxilmaniac attest to the contrary?

Also, I think modifying an upstream file for something as trivial as "I do not wish to interact with the rest of my department" is not good.

**Comment by Zergspower** [comment]
> > literally no one has ever asked botany for juices like, period, because they just wait for parts because why not?
> 
> Didn't @Paxilmaniac attest to the contrary?
> 
> Also, I think modifying an upstream file for something as trivial as "I do not wish to interact with the rest of my department" is not good.

It's... already modified? this code isnt upstream we added it

**Comment by theselfish** [comment]
> > > literally no one has ever asked botany for juices like, period, because they just wait for parts because why not?
> > 
> > 
> > Didn't @Paxilmaniac attest to the contrary?
> > Also, I think modifying an upstream file for something as trivial as "I do not wish to interact with the rest of my department" is not good.
> 
> It's... already modified? this code isnt upstream we added it

I stand corrected, then. Apologies.

**Comment by Zonespace27** [comment]
> @Zonespace27

My reasoning for saying "yeah sure" when asked was that, when it comes to it, (most) drinks that you can make are just varying options of flavor and I don't see much of a reason to keep them locked. Unless someone's aiming for a drink with some other upside (e.g. doctor's delight (in which case, a lot of them need something from chem, too)), they just... won't make that drink if it requires talking to botany

**Comment by tf-4** [comment]
The full range of drinks should be available to people who the extra bit of effort in. The people that can't be bothered SHOULD get it late, if at all.
It encourages interaction without having a tangible effect on the round (i.e doesn't prevent round progression in any way).

**Comment by Zergspower** [comment]
They are - this doesn't get you anything you needed to get from other departments even when it was unlocked prior (all the chemistry stuff, all the niche botany stuff) , and it again still very much needs upgrades regardless for speed because making 1 drink on a base machine tanks your energy takes takes 10 seconds to recharge 1 unit of energy

**Comment by tf-4** [comment]
I'm very much against giving people everything for free roundstart with no effort, doubly so for things that encourage you to interact with others to get.

**Comment by YakumoChen** [comment]
> and it again still very much needs upgrades regardless for speed because making 1 drink on a base machine tanks your energy takes takes 10 seconds to recharge 1 unit of energy

Damn, you might have to open your wallet and buy the drinks from the vendor 2 tiles away if you run out then.

**Pull request closed without merging**
