### PR TITLE
[MODULAR] Adds two new weird animal sounds!

### PR DESCRIPTION
**Pull request by gummardgumphrey**
## About The Pull Request

This adds two new emotes: Weird Cat Noise (*wcat) and Weird Dog Noise (*wdog), feline-esque and canine-esque crew rejoice!

https://user-images.githubusercontent.com/77675526/188328538-0ff6b6ed-ef0d-4c99-900c-aa65a8a8fa1a.mp4

https://user-images.githubusercontent.com/77675526/188328540-6ff91e72-578f-4419-a776-6e2d5ab8f027.mp4

(since runechat is buggy)
unknfdgdfgdfown

## How This Contributes To The Skyrat Roleplay Experience

Hearing anomalous animal noises echoing down a dark, damp maintenance hall adds an extraordinary amount of immersion.

## Changelog

:cl:
add: Weird Cat Noise (*wcat)
add: Weird Dog Noise (*wdog)
/:cl:

### CODE REVIEW

**Comment by linnpap** [comment]
I NEED IT... SOMETHING

**Review by RimiNosha — COMMENTED** [review]
Good names for these emotes are "meow2" and "whine", I think. They describe these sounds much better than just "Weird x sound"!

**Comment by gummardgumphrey** [comment]
> Good names for these emotes are "meow2" and "whine", I think. They describe these sounds much better than just "Weird x sound"!

correct me if i'm wrong but i think there may already be a *whine emote. but yeah, valid points -- it's just that the "gimmick" of these emotes is to have _somewhat_ indiscernable noises that could be described with something as vague and outlandish as "weird X noise"

**Review by tf-4 — COMMENTED** [review]
I'm not really sure if I'm sold on these SFX. They're not the best quality sound clips, especially the cat one, and we already have a number of low-quality SFX that I'd much rather get rid of than accept as a standard.

**Comment by Zonespace27** [comment]
Seconding tf4 on this one, plus you didn't include sound attribution anywhere so I can't be sure these are agpl3 compliant

**Pull request closed without merging**
