### PR TITLE
[MODULAR][FIX/QoL] Mediguns eject Medicells into hands before the floor.

### PR DESCRIPTION
**Pull request by softcerv**
## About The Pull Request
Changes the proc used to remove the medicells so that they dispense into the users hands first. It was originally intended to work like this, I just didn't know this proc existed. 

## Why It's Good For The Game
Makes Mediguns less cumbersome to use.

## Changelog
:cl:
fix: Mediguns now eject Medicells into the user's hands instead of always on the floor.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Do both of these things

**Comment by Gandalf2k15** [comment]
Move it to drop location then attempt to put in hanes

**Comment by Gandalf2k15** [comment]
Else it will null it

**Comment by softcerv** [comment]
> 
> 
> Else it will null it

OH, lemme do that real quick then!

**Pull request merged**
