### PR TITLE
make cme shorter in time

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
less frequent bubbles
bubbles last less time
the event lasts less time
cme is softer

## Changelog
:cl:
balance: the CME event lasts for less time
balance: the CME will not have the armageddon level
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Armageddon is admin only, leave it

**Comment by jjpark-kb** [comment]
> Armageddon is admin only, leave it

done.

**Comment by Gandalf2k15** [comment]
Just revert the armageddon values

**Comment by jjpark-kb** [comment]
> Just revert the armageddon values

done.

**Comment by jjpark-kb** [comment]
closing for now.

**Pull request closed without merging**
