### PR TITLE
Unfucks set_security_level.dm

### PR DESCRIPTION
**Pull request by NullDagaf**
## About The Pull Request

Anyone who messed with set_security_level.dm knows how autistic it's coded. This PR attempts to un-fuck it, at least a bit. Do @ me if I goofed somewhere though.

## Why It's Good For The Game

Bad code is bad, Good code is less bad.

## Changelog
:cl:
refactor: Unfucked ``set_security_level.dm``
/:cl:

### CODE REVIEW

**Comment by NullDagaf** [comment]
is that how you do a pr

**Comment by atakiya** [comment]
Uhhhh, you may not wanna commit your stuff onto master, even if its on your fork.
If you do, make sure that[ github actions are disabled on your fork](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/disabling-and-enabling-a-workflow).
The current merge conflict is due to an automated workflow on your fork.

**Comment by NullDagaf** [comment]
> Uhhhh, you may not wanna commit your stuff onto master, even if its on your fork.
> If you do, make sure that[ github actions are disabled on your fork](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/disabling-and-enabling-a-workflow).
> The current merge conflict is due to an automated workflow on your fork.

english

**Comment by NullDagaf** [comment]
aaa

**Pull request closed without merging**
