### PR TITLE
[PORT] Serenity Station from Nova Station

### PR DESCRIPTION
**Pull request by Erol509**
## About The Pull Request

# Copy pasted from Nova, Im not the author, I take no credits.  Link to the original PR bellow
https://github.com/NovaSector/NovaSector/pull/3040

Big thanks to GoldenAlpharex for all his help on the code & biome generation.

A nova-specific map featuring a station located on a forest planet. The forest planet has caves filled with mushrooms, and underground cold liquid plasma springs bubbling to the surface.

This includes 3 z-levels: the underground mushroom level; the surface forest level; and a space level that has a small orbital station and linkage to other space z levels.

This station features a custom shuttle to go between the orbital and planetary shuttle, though the public mining shuttle can also go between them (with 3 docking options now: planetary dock, orbital dock and lavaland).

There are custom mushroom tree, mushroom floor, mushroom flora, stillcap and megadeer sprites for this map. The megadeer is more or less a reskinned wolf and drops a reskinned wolf crusher trophy. The stillcap is a basic mob that hides as a mushroom when a target is not nearby.

There are two main cave generation types: the surface, which functions as normal cave generation such as icebox, and the lower mushroom level which uses biome generation to mix in three different biomes (red, blue and green)

The name comes from the ship Serenity from Firefly, the show that got me into science fiction.

## Proof of Testing
</details>

## Changelog
:cl: Thlumyn for the map and sprites, GoldenAlpharex for most of the code
add: Added SerenityStation map.
add: Added lightshroom, mushroom bush, mushroom tree, and colored ash flora mushroom plants.
add: Added Stillcap and Mega Deer mobs.
add: Add forest cave generation and mushroom cave biome generation.
config: Add SerenityStation to the map config.
/:cl:

### CODE REVIEW

**Comment by Erol509** [comment]
Okay, so linters are failing for some stupid reason. 
They are bitching about this freezer...
image

**Comment by SpaceLoveSs13** [comment]
Well another thing to maintain guughhghgh

**Comment by SpaceLoveSs13** [comment]
Also fix the unit tests fail. It's gonna plague every pr if I merge it. Look at how the previous create_and_destroy unit test was fixed.

**Comment by Erol509** [comment]
Ci failed because I still have cargo_nova. Gonna change that soon, at least its my guess

**Review by SpaceLoveSs13 — APPROVED** [review]

**Comment by Erol509** [comment]
I will port fixes from Nova if any are merged, dont worry.

**Comment by Thlumyn** [comment]
Hey there, I'm the original author of this map. I was not asked or consulted before this map was ported; I would rather this map not be on Skyrat for the time being. Thanks

**Comment by SpaceLoveSs13** [comment]
> Hey there, I'm the original author of this map. I was not asked or consulted before this map was ported; I would rather this map not be on Skyrat for the time being. Thanks

Thanks for informing me, it also helps me to not maintain another modular pr. I will close it. Apologies for the inconveniences.

**Pull request closed without merging**
