### PR TITLE
You know what? Fuck you. *Removes your glock*

### PR DESCRIPTION
**Pull request by Draganfrukts**
## About The Pull Request

This PR removes both Glock pistols from the game and replaces them with something else.

## Why It's Good For The Game

Why is a gun company making reproductions of some shitty 20th century plastic pistol in the early 2560s?

## Changelog
:cl:
del: The great, great grandson of Gaston Glock Jr. has sued Armadyne over their blatant unlicensed reproduction of Glock handguns. As a result, they have all been pulled from the market and any stations they were being dispensed in.
add: Armadyne, in cooperation with AEROMECH, has replaced their Glock-17 models with the brand new APS-F1; a bullpup design.
add: After signing a contract with the government of New Russia, Armadyne has obtained the proper licensing to produce the PP-25 submachine gun, and they are now working on replacing all Glock-18 models with it. Lopland requested that their orders be outfitted with modern optics, a golden command stripe and a special ZenitCo stock.
tweak: Changed Glock-17 gunset to properly display APS-F1
fix: PCR, VKC and Pitbull now display proper gunsets instead of the old sprites
/:cl:

### CODE REVIEW

**Comment by FlamingLily** [comment]
based

**Comment by zeratino** [comment]
based

**Comment by Arctaisia** [comment]
based

**Comment by thestubborn** [comment]
i havent checked but unless you're replacing them with some cowboy revolvers or a ww2 handgun I'm gonna say a cringe for this one

**Comment by Draganfrukts** [comment]
> 
> 
> i havent checked but unless you're replacing them with some cowboy revolvers or a ww2 handgun I'm gonna say a cringe for this one

>Complaining about why late 20th century gun in space
>"If it's not an even older gun I'm gonna say a cringe for this one"

**Comment by thestubborn** [comment]
yeah, because most post ww2 guns are ugly as fuck
or post vietnam if you wanna stretch it

**Comment by BrotherHangyul** [comment]
If you'rr arguing that the glock shouldn't be in rotation, neither should any of the shitty halo references? Why is an arms company copyimg designs from a fucking videogame?

**Comment by Gandalf2k15** [comment]
Ladies it's just preference calm down, tho I'd prefer this was made into a completely new gun, leaving the g18 as it is, ands replacing the hos gun with this.

**Comment by Draganfrukts** [comment]
I accidentally closed it I just woke up

**Comment by thestubborn** [comment]
> 
> 
> > If you'rr arguing that the glock shouldn't be in rotation, neither should any of the shitty halo references? Why is an arms company copyimg designs from a fucking videogame?
> 
> Because Halo doesn't exist IC and SS13 is a game built on videogame references lmao

references in general, if we're going off that logic then the glock (which by the way, is still being made, Glock 44 came out in 2019), which has been in countless games should be fine

**Comment by thestubborn** [comment]
also i hate a lot of guns with a curve, they look fucking stupid, that's all

**Comment by Draganfrukts** [comment]
Ready for merge now

**Comment by BrotherHangyul** [comment]
> > If you'rr arguing that the glock shouldn't be in rotation, neither should any of the shitty halo references? Why is an arms company copyimg designs from a fucking videogame?
> 
> Because Halo doesn't exist IC and SS13 is a game built on videogame references lmao

Then an IRL and first person shooter genre reference is fine. Fuck your Russian, return to true and trested.

**Comment by Draggeru** [comment]
Improve don't remove. Just change the skin and name ¯\_(ツ)_/¯

**Comment by Draganfrukts** [comment]
> 
> 
> Improve don't remove. Just change the skin and name ¯_(ツ)_/¯

funny because that's literally what it does lol

**Comment by BrotherHangyul** [comment]
This isn't an improvement though?

**Comment by Gandalf2k15** [comment]
My G I told you, make these a completely separate gun instead of keeping them as the same stats as the glock REEEEE

**Comment by Draganfrukts** [comment]
> 
> 
> My G I told you, make these a completely separate gun instead of keeping them as the same stats as the glock REEEEE

WE ALREADY DISCUSSED IN THE DEV CHANNEL HEADASS

**Comment by Gandalf2k15** [comment]
MAKE IT A NEW GUN REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by thestubborn** [comment]
my bro

i will literally give you sprites i found

add silly lights or whatever you think makes it look 'modern'

just not fuckin halo

**Comment by thestubborn** [comment]
or better idea for both worlds

cit rp had a system where you could reskin weapons (and i think we have the framework), add this new weapon as a reskin to it, best of both worlds

**Comment by LeonY24** [comment]
fuk u

**Comment by Gandalf2k15** [comment]
Do this in gubman 3.

**Pull request closed without merging**
