### PR TITLE
Marks the flatpacked Fabricator and RTG imports as 'restricted'

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
It really makes no sense for the crowbar to be restricted, but not the thing that can print infinite crowbars (plus a lot more)...
And the improperly shielded RTG just doesn't make sense to be all-access either. Giving untrained and unauthorized crew access to radiation spewers?

If the code was in place, I would prefer to make them restricted to only Engineering so that other command staff don't just buy them to kit their department with budget-JoL and tools, but import code runs off guncargo code which only had guns in mind rather than the broad spectrum of departmental accesses...

## How This Contributes To The Skyrat Roleplay Experience
Really it just doesn't make sense that the prybar is restricted but not the thing that prints them. Seems like an oversight.
And the RTG just doesn't make sense to not be restricted because, again, it's not shielded. Radioactive contaminants shouldn't be all-access.

## Proof of Testing
It's really that shrimple

image

## Changelog

:cl:
balance: the flatpacked Fabricator and RTG are now restricted-access imports
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
image

**Comment by HoodMilk** [comment]
To be fair anyone with lathe access can print out uranium and start flooring the station with it. But the fabricator board makes sense.

**Comment by SpaceLoveSs13** [comment]
The entire point of the PR was to allow anyone to start a functional system from scratch anywhere when needed in dire situations. Unnecessarily restricting the access of the fundamental item in the block is not required.

**Comment by SomeRandomOwl** [comment]
> The entire point of the PR was to allow anyone to start a functional system from scratch anywhere when needed in dire situations. Unnecessarily restricting the access of the fundamental item in the block is not required.

If something the lathe can make is restricted from normal purchase, then the lathe itself should also be restricted so people cant work around the restriction

**Comment by ghost** [comment]
> If something the lathe can make is restricted from normal purchase, then the lathe itself should also be restricted so people cant work around the restriction

This pretty much summed up the reasoning behind the PR yeah thanks 4 being better with words

**Review by lessthnthree — APPROVED** [review]

**Pull request merged**
