### PR TITLE
Removes TRAIT_NUMBED, using TRAIT_ANALGESIA instead

### PR DESCRIPTION
**Pull request by Majkl-J**
## About The Pull Request

See name, fixes people screaming during surgeries when they shouldn't. Also adds back the mood events removed on accident.

Only change from original functionality is that robotic parts no longer cause any pain or mood debuffs. There is absolutely no reason for these to hurt or affect you negatively, it's a literal piece of metal.

## How This Contributes To The Skyrat Roleplay Experience

Less screaming, more healing

### Testing

Yet again I forgot screenshots but the chemicals worked, so did the surgery bed in runtimestation

## Changelog

:cl:
balance: Robotic part surgeries no longer cause you to scream out in pain or affect you negatively.
fix: People no longer scream in pain on stasis beds
refactor: Removes TRAIT_NUMBED, using TRAIT_ANALGESIA instead
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
this isn't a fix, this is intended behavior

**Comment by Majkl-J** [comment]
> this isn't a fix, this is intended behavior

See https://github.com/Skyrat-SS13/Skyrat-tg/pull/26504

image

Doubt this entire functionality was just wiped intentionally. I can work in a more in-depth fix if needed

+TG added numbing functionality so there's no reason to run 2 different traits

**Comment by Iamgoofball** [comment]
ah, i think i misread your PR

**Comment by Majkl-J** [comment]
> ah, i think i misread your PR

To be completely honest the writing in the body was a bit iffy, fixed it

**Review by softcerv — APPROVED** [review]
This looks good

**Pull request merged**
