### PR TITLE
Tweaks the Ants PR to make food decay longer, and no longer decay on lockers/fridges/crates. I was paid $20 to make this PR.

### PR DESCRIPTION
**Pull request by BurgerLUA**
## About The Pull Request

Decay times were increased significantly to make up for the fact that Skyrat rounds are 2 hours long instead of tg's 1 hour rounds.

Food no longer decays on fridges, lockers, and crates.

Tweaks a notice to a warning.

## Why It's Good For The Game

Someone offered me $20 to make this PR so this change is super needed given that someone is willing to pay me to fix it. Basically the PR is fine but the values were way to unforgiving for Skyrat and there was an issue with food decaying while on elevated surfaces like lockers, crates. and fridges.

## Changelog
:cl:
balance: Nerfs ant decomposition times.
/:cl:

### CODE REVIEW

**Comment by SpaceVampire** [comment]
I feel like you might be able to PR the fridges, lockers, and crates upstream as that seems like more of a possible oversight. But I think the actual decay value is fine, if you want to be able to interact with the mechanic within a reasonable timeframe.

**Comment by BurgerLUA** [comment]
> I feel like you might be able to PR the fridges, lockers, and crates upstream as that seems like more of a possible oversight. But I think the actual decay value is fine, if you want to be able to interact with the mechanic within a reasonable timeframe.

If they want to port it to upstream, then they can if they want to because it is not definitely an oversight.

**Comment by SpaceVampire** [comment]
> If they want to port it to upstream, then they can if they want to because it is not definitely an oversight.

I don't know enough about authorial intent to be sure, but fridges not working to protect food from ants at the very least seems off. Still hold what I sad about the time values not needing to be increased, especially if you just kept the rest of it.

**Comment by Gandalf2k15** [comment]
Do this upstream for the fridge stuff, since that will be accepted up there. As for the values, make it 20, 15 and 10.

**Comment by BurgerLUA** [comment]
> Do this upstream for the fridge stuff, since that will be accepted up there. As for the values, make it 20, 15 and 10.

Leave this PR up in case it gets rejected.

> > If they want to port it to upstream, then they can if they want to because it is not definitely an oversight.
> 
> I don't know enough about authorial intent to be sure, but fridges not working to protect food from ants at the very least seems off. Still hold what I sad about the time values not needing to be increased, especially if you just kept the rest of it.

It's open fridges. Not closed ones.

**Comment by SpaceVampire** [comment]
> It's open fridges. Not closed ones.

Oh. Well in that case, why should they work?
If you have stuff in an open locker/crate I don't see an issue with it getting ants.
I had assumed you were talking about closed ones in both cases.

**Comment by BurgerLUA** [comment]
> > It's open fridges. Not closed ones.
> 
> Oh. Well in that case, why should they work?
> If you have stuff in an open locker/crate I don't see an issue with it getting ants.
> I had assumed you were talking about closed ones in both cases.

Ok so this is the reason why I don't want to go to /tg/ and do it. Personally I find it dumb because some things spawn on elevated surfaces. This entire ant PR is dumb because it calls locate() multiple times to find certain items instead of using a var if the object is an elevated surface.

**Comment by ForrestWick** [comment]
> I feel like you might be able to PR the fridges, lockers, and crates upstream as that seems like more of a possible oversight. But I think the actual decay value is fine, if you want to be able to interact with the mechanic within a reasonable timeframe.

The decay rate is insanely fast, and ruins the workflow for chefs like me. If it stays like it is now and this PR isn't merged, I will unironically stop playing chef completely.

**Comment by SpaceVampire** [comment]
> Ok so this is the reason why I don't want to go to /tg/ and do it. Personally I find it dumb because some things spawn on elevated surfaces. This entire ant PR is dumb because it calls locate() multiple times to find certain items instead of using a var if the object is an elevated surface.

I mean, if you can make it more efficient you should actually do that upstream.
Along with those other proposed changes.
Like, it is a new feature stuff usually gets tweaked.

**Comment by hugmeorelse** [comment]
I support this PR. In the meanwhile, TM it. However, I do think efficiency changes should be done upstream. I am sure tg will appreciate it. However, we should TM this if this is problematic. We can full-merge if they deny the efficiency change.

Also, we have a proper bounty system setup. Please follow that in the future if you can. It would be highly appreciated. For more details on that, ask Cobalt on Discord.

**Comment by hugmeorelse** [comment]
@SpaceVampire @Gandalf2k15 I agree that some changes like the efficiency change should be brought upstream, but we should TM this in the meanwhile since it seems to be a major problem for chefs/cooks.

**Review by Funce — APPROVED** [review]

**Pull request merged**
