### PR TITLE
[Modular] Tradership Remake

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Rebuilds the admin-only tradership to more resemble.. a trader ship, rather than a recolored whiteship like it was originally.
image

## Why It's Good For The Game
The faction module may be as disused as the chrono legionaries, but. Hey. Why let that stop us?

## Changelog
:cl:
add: The faction module has received an overhauled trader ship.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Almost looks bigger than shipstation.

**Comment by Azarak** [comment]
Are the access requirements on airlocks set proper?

**Comment by Azarak** [comment]
Also, can you put a warehouse in it? Or a general storage area? Much like the one in the previous iteration. The engineering section perhaps shouldnt have floor tiles and should be on dimmer lights, the APC should be there too.

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
1. For a trading ship there's less cargo space than my bedroom and I can assure you I'm not living a grand life here.
2. Kitchen is colossal, you don't need two fryer units and a giant keg of oil. That's more oil than a McDonald's has both in use and in drystock combined. You don't need a dedicated walk-in freezer, just a fridge (change the `name` variable to fridge-freezer if you want); you definitely don't need a butchering rack there. I've got a more functional kitchen into a 3x4 room that has two entrances, so I know it can be done smaller. Throw a sink in there, too.
3. Consolidate engineering/EVA into one room. You honestly don't need that much.
4. This needs atmos piping. You need a pressure tank for air, and an outlet in space to get scrubbed CO2 and other harmful gases out.
5. Remove the six sofa seating area. No need for it.
6. Optionally change one of the spare bedrooms into a meeting room and/or recreation room if you want that.

**Comment by KathrinBailey** [comment]
image
image
This is my heavily unfinished shuttle for something else if you want inspiration.
Three crew rooms, one Captain room, three prisoner cells. Fully functional (and excessive) atmos. This was before smartpipes.

**Comment by Gandalf2k15** [comment]
I'll allow it

**Pull request merged**
