### PR TITLE
[NON-MODULAR] Only roboticists can repair prosthetics

### PR DESCRIPTION
**Pull request by NullDagaf**
## About The Pull Request

Title. If you don't have ~~roboticist as your assigned job~~ roboticists' skillchip, you physically can't repair prosthetics. Also you can't repair prosthetics on your own.

## Why It's Good For The Game

­> Gives roboticists something to do, past just "make borgs"
­> Few if any jobs besides roboticist should even have the knowledge of how to fix prosthetics, maybe engineer but even that is stretching it
­> Encourages cross-department interactions (and interactions in general), as medical can't fix the prosthetics on their own

## Changelog
:cl:
balance: you can no longer self-repair prosthetic limbs, you need to have the roboticist fix them for you
/:cl:

### CODE REVIEW

**Comment by xXPawnStarrXx** [comment]
Instead, Make broken bone style injuries and such but only for robotics.

**Comment by NullDagaf** [comment]
> Instead, Make broken bone style injuries and such but only for robotics.

Not something I know (yet) how to do.
~~Also, "bobmed"~~

**Comment by FlamingLily** [comment]
Do what paradise does, once the damage gets past a certain threshold, trying to repair it gets a "The damage is too severe to patch over externally!" message and you require robotics treatment.

**Comment by NullDagaf** [comment]
> Do what paradise does, once the damage gets past a certain threshold, trying to repair it gets a "The damage is too severe to patch over externally!" message and you require robotics treatment.

"[Common] MedDoc143 meows: Yo engineers, pass a toolbelt"

**Comment by RatFromTheJungle** [comment]
This affects synths without being clear about it, as they are entirely bodypart_robotic, without even mentioning the severe upset to balance this does.

**Comment by FlamingLily** [comment]
> "[Common] MedDoc143 meows: Yo engineers, pass a toolbelt"

"[Common] SmartPlayer says, smartly: "What? No.""

The idea that X will do a certain job doesn't work because X *can already do any job on the station.* Other than access to tools and areas, nothing mechanical stops anyone from setting the engine, from cooking or manning the bar, for working botany, from doing robotic's job, or, get this, hunting antags

**Comment by NullDagaf** [comment]
> This affects synths without being clear about it, as they are entirely bodypart_robotic

yes

>without even mentioning the severe upset to balance this does.

Bah, balance. This isn't TG nor CM, you don't ***need*** strict balancing. Also does it matter THAT MUCH if you need to visit robotics for a tiny bit? If your prosthetics are damaged, chances are rest of your body is too. And if that's the case, you'd probably need to visit medical anyway, robotics is like right next to them.

**Comment by NullDagaf** [comment]
> > "[Common] MedDoc143 meows: Yo engineers, pass a toolbelt"
> 
> "[Common] SmartPlayer says, smartly: "What? No.""

"[Common] MedDoc143 meows: okay then i'll just grab one from the tool storage"

**Comment by FlamingLily** [comment]
> "[Common] MedDoc143 meows: okay then i'll just grab one from the tool storage"

#development-main SmartCoder writes: "Fuck tool storage"

**Comment by FlamingLily** [comment]
> Bah, balance. This isn't TG nor CM, you don't _**need**_ strict balancing. Also does it matter THAT MUCH if you need to visit robotics for a tiny bit? If your prosthetics are damaged, chances are rest of your body is too. And if that's the case, you'd probably need to visit medical anyway, robotics is like right next to them.

Except we have an action only server on this codebase

We *have* action on the main server, too. Removing 50% of health from a heretic wouldn't pass on the basis that "bah who needs balance when we're an RP server".

**Comment by RatFromTheJungle** [comment]
> Bah, balance. This isn't TG nor CM, you don't _**need**_ strict balancing. Also does it matter THAT MUCH if you need to visit robotics for a tiny bit? If your prosthetics are damaged, chances are rest of your body is too. And if that's the case, you'd probably need to visit medical anyway, robotics is like right next to them.

Correct, this isn't TG nor CM, this is a server where departments and jobs are both unreliable and understaffed at changing times throughout the day, and locking the ability to heal(at all) six(?) player species entirely to one job, especially one of the least reliable jobs, is about as poorly thought through as an individual change can be.

Which to add onto, this is a server where 'small' injuries are a constant, this change singlehandedly buffs every single antag, weapon, security themselves, midrounds(because now even less people show up to them), for no conceivable reason past, "..I can't find anything to do as robotics but make borgs"

**Comment by NullDagaf** [comment]
> Except we have an action only server on this codebase

image

I refuse to acknowledge the existence of a dead server.

**Comment by thestubborn** [comment]
i just stubbed my robotoe, better wait in the giant robotics line so I can get a single bit of wire

**Comment by NullDagaf** [comment]
> Removing 50% of health from a heretic wouldn't pass on the basis that "bah who needs balance when we're an RP server".

Pretty sure heretics should be somewhat stealthy.
If you're not actively murdering everyone, robotics shouldn't have that much of a problem with fixing your arm.

> Correct, this isn't TG nor CM, this is a server where departments and jobs are both unreliable

­> "this is a bad change because people are dumb"

> and understaffed at changing times throughout the day, and locking the ability to heal(at all) six(?) player species entirely to one job, especially one of the least reliable jobs, is about as poorly thought through as an individual change can be.

..fffiiine, I'll make it a skill-chip so you can :tm: fix shit even without roboticists at hand.

> Which to add onto, this is a server where 'small' injuries are a constant, this change singlehandedly buffs every single antag, weapon, security themselves, midrounds(because now even less people show up to them), for no conceivable reason past, "..I can't find anything to do as robotics but make borgs"

Do you seriously expect people to aim specifically at your prosthetics.
As for IPC's and synths, tough fucking luck. Get some repairing nanites and stop complaining. Borgs don't seem to have an issue with wires not being self-repairable/needing a human for repairs.

**Comment by unit0016** [comment]
Ghostroles be like *dies*

...on a more serious note, this shafts them pretty hard.

**Comment by NullDagaf** [comment]
> Ghostroles be like _dies_
> 
> ...on a more serious note, this shafts them pretty hard.

The only one I can think of it'd affect in any way if at all, are **maybe** the syndicate roles. Ashwalkers are too tribal for them, golems are golems, lifebringers don't have access to them.

Cybersun/Interdyne (?) shouldn't get into combat regardless, former being a transporter crew, while the latter occupy a listening post, not a remote operation base.

**Comment by thestubborn** [comment]
> 
> 
> > Ghostroles be like _dies_
> > ...on a more serious note, this shafts them pretty hard.
> 
> The only one I can think of it'd affect in any way if at all, are **maybe** the syndicate roles. Ashwalkers are too tribal for them, golems are golems, lifebringers don't have access to them.
> 
> Cybersun/Interdyne (?) shouldn't get into combat regardless, former being a transporter crew, while the latter occupy a listening post, not a remote operation base.

the former quite literally starts with hostile armed simple mobs

**Comment by NullDagaf** [comment]
> the former quite literally starts with hostile armed simple mobs

wait fuck you're right

**Comment by unit0016** [comment]
Not to mention all ghostroles can mechanically have cybernetic limbs thanks to our uses prefchars thing, even ashies.

And Interdyne mining. And cybersun's simplemobs/assistants tiding space, etc.

And also Oldstation! Don't forget them.

**Comment by Nerev4r** [comment]
We already nerfed the shit out of synths, and it doesn't really make sense that someone with a whole prosthetic limb can't fix even the slightest damage themselves.

**Comment by NullDagaf** [comment]
> even ashies

pain.gif

**Comment by Gandalf2k15** [comment]
Quite a good change actually.

**Comment by Arctaisia** [comment]
I honestly don't think this is the best way to do it, perhaps making prosthetics harder to repair than just a welder, or using a tool/item that only roboticists have would wirk a little better, with only one of those tools/items existing, so it can't be nabbed until it's researched, but that's just my idea.

I don't dislike this change, though just has some problems, still not bad, in my lizard brain at least, *weh

And if we do this, we should make synths a little hardier at least, and perhaps make some 'robot first aid kits' for synths, to heal up some minor damage.

**Comment by FlamingLily** [comment]
> 
> 
> Do what paradise does, once the damage gets past a certain threshold, trying to repair it gets a "The damage is too severe to patch over externally!" message and you require robotics treatment.

This is still the best solution in my eyes. It solves the issue without insanely nerfing synthetics into the ground because one person got bored playing robotics once.

**Comment by NullDagaf** [comment]
> I honestly don't think this is the best way to do it, perhaps making prosthetics harder to repair than just a welder, or using a tool/item that only roboticists have would wirk a little better, with only one of those tools/items existing, so it can't be nabbed until it's researched, but that's just my idea.

I don't think it's the best way to approach this either. I'd love to either tie it to a skill, whereas if you aren't experienced you're likely to fail more often/take more time, or even just implement robotic wounds only robotics has the tools to fix.
However, this is a solution that "works" right now. If we ever, dare I say, port Bobmed (please don't censor me for this) I'd be fine with this being reverted.

**Comment by PCPort** [comment]
So, wait, uh. From an **RP** perspective (Shock horror! Pull requests' consequences on roleplay being discussed in a roleplay server!)

All the characters who have had prosthetic limbs for a long period of time, and have been self-repairing them round to round? For like, months? Suddenly lose the ability to do that because roboticist players got bored??

Like how would you justify that ICly?

**Comment by NullDagaf** [comment]
> So, wait, uh. From an **RP** perspective (Shock horror! Pull requests' consequences on roleplay being discussed in a roleplay server!)
> 
> All the characters who have had prosthetic limbs for a long period of time, and have been self-repairing them round to round? For like, months? Suddenly lose the ability to do that because roboticist players got bored??
> 
> Like how would you justify that ICly?

Good point. I suppose I could make self-repair a quirk..
Actually, now that I think about it, what if you COULD self-repair (assuming you either are robotics or have that quirk), but it both takes a longer while, and has a fairly big (33%?) chance to fail? (Burn damage when repairing brute, wasting coil when repairing burn) That should accomplish the same goals, while being a bit more forgiving.
If you wouldn't have that quirk, you still couldn't be able to repair yourself/others.

Yeah, I think I'll implement that when I'll get back home. Give or take 3 days.

**Comment by SpaceVampire** [comment]
> Good point. I suppose I could make self-repair a quirk..
> Actually, now that I think about it, what if you COULD self-repair (assuming you either are robotics or have that quirk), but it both takes a longer while, and has a fairly big (33%?) chance to fail? (Burn damage when repairing brute, wasting coil when repairing burn) That should accomplish the same goals, while being a bit more forgiving.
> If you wouldn't have that quirk, you still couldn't be able to repair yourself/others.
> 
> Yeah, I think I'll implement that when I'll get back home. Give or take 3 days.

I would recommend not making it quirk based.
We already have an issue with free quirk points, especially when it comes to synths.
I t would be best if they were only used for stuff that was mostly just flavor.
Instead of actual important balance stuff.
Feel like the best way is to just make self-repair an option for everyone, and just have it be real slow.
Which is the same way it (works? used to work?) when you used brute packs on yourself vs others.

**Comment by tf-4** [comment]
This solves an issue that doesn't exist, and it doesn't even do a good job of solving it.

**Comment by softcerv** [comment]
> 
> 
> This solves an issue that doesn't exist, and it doesn't even do a good job of solving it.

agreed, why is this an issue that needs to be solved with a quick solution?

**Comment by Vizoplez** [comment]
### This is not balance. This is a feature; we are currently feature frozen. Furthermore, this entirely upsets the balance of the game for a multitude of races that use TRAIT_ROBOTIC.

Strong no from me.

**Comment by YakumoChen** [comment]
Absolutely not. We don't entirely limit features of the game to certain jobs that aren't even guaranteed to exist in any given round.

This would be exactly the same as limiting organic healing to only those in the medical department. It's not only nonsensical, but utterly destroys the flow of the game as a whole.

**Comment by FlamingLily** [comment]
> Actually, now that I think about it, what if you COULD self-repair but it both takes a longer while

It _already _does__

**Comment by NullDagaf** [comment]
> This is not balance. This is a feature

uhhuh

**Comment by NullDagaf** [comment]
> > Actually, now that I think about it, what if you COULD self-repair but it both takes a longer while
> 
> It _already _does__

A
### LONGER
while.

**Comment by YakumoChen** [comment]
Tedium doesnt add positively to the game

If you want to make robotics more incentivized for fixing synths:
-make help-applied synth healing non instant and give robotics a speed bonus via their skill chip
-1:1 tend wounds identical synth surgery
-Synth wounds
-Robotics area exclusive speed bonus to synth surgery like we have in surgery rooms 
-upgraded synth and borg healing items that need to be researched under a borg tech mode, other servers have nano paste for this purpose. Printable from sci lathe only.

**Comment by lyricalpaws** [comment]
Like tf-4 said, it fixes an issue that doesn't exist, and synths are already bad enough to play. I'm gonna say no.

**Comment by ZephyrTFA** [comment]
This PR is not needed in any capacity. The problem you claim to 'fix' is infact not a problem to begin with but it instead your opinion on the current method of repairing synths. 
Do not purposefully mislabel your PR.

**Comment by SpookyTheFox** [comment]
I support what this is trying to do. Easy self repair absolutely needs to go. How it's done here seems a little harsh. But, it does get the job done. Robotics being out of commission should rightfully leave robotic species in just as much trouble as if there was no medbay.  Also, I see nothing preventing simple replacement of the limbs via surgical methods, so it's not like there isn't still a work around.

**Comment by Nerev4r** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/6359

**Comment by Vizoplez** [comment]
sorry this PR is no longer needed :)

**Comment by KathrinBailey** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/6369
if above doesn't address this
then this needs to be done instead
image

**Pull request closed without merging**
