### PR TITLE
Makes all underwear/socks digitigrade compatiable

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Title
Now I can wear whatever I want and u cant stop me..

also tweaks some names and re-organizes a tad. Just a tad though.

Also removes Long John Bottoms because those already exist as male_longjohns upstream

### NEW: properly implements #18597, adding it to our modular file and giving it digi variants
Also renames lots of the old fishnet stuff to include (Greyscale), and removed the 'gloved' versions that didn't even work because of how underwear layering works.
Proof of testing added.

## How This Contributes To The Skyrat Roleplay Experience
Icons just being invisible for people kinda sucks
There was another reason when I started but ngl I entirely forgot it lmao

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

  image
Oooh... ahh...

jnc7CPpNyV
Now I can be gay all I please

I'm not showing pictures of all of them. All of them work. I tested every. Single. Underwear. Type. Even ones I didn't change.

And, for the new fishnet changes, yes, surprise surprise, it works! Wow!
m6ZUOKBcXF
VS1pRqBQp9

</details>

## Changelog

:cl:
fix: fixed Lizared underwear hiding chests
imageadd: added digitigrade sprites for most underwear that was missing it
/:cl:

### CODE REVIEW

**Review by Ebin-Halcyon — CHANGES_REQUESTED** [review]
Reviewing on mobile as I'm out for a Christmas family thing. I'll do a more in depth review later.
Main things I noticed at a glance over is the addition of the lower quality version of the sports bras with the old color palette.

Screenshot_20221218-154515_Chrome


Screenshot_20221218-154453_Chrome

**Comment by ghost** [comment]
My bad, copied a more up to date tg file and it overwrote ours

Regardless though, not gonna finish this, so 🤷

**Comment by ghost** [comment]
On second thought... underwear :drool:

**Review by Ebin-Halcyon — APPROVED** [review]
Nothing I can see out of place right now, i'll probably notice it in game a month later.

**Pull request merged**
