### PR TITLE
Removes Antag Hud post Round End

### PR DESCRIPTION
**Pull request by SpaceLoveSs13**
## About The Pull Request

Removes antag hud post round end. The ability to see who is antag who is not. (Round end report still shows this, just no glowy red T, H, ghost symbols)

## How This Contributes To The Skyrat Roleplay Experience

Noticing lot of EORG after post round end that has been targetted towards Traitors or people who have later been proven to be evil. While EORG is still bannable, I believe things that can stop one from going "Oh you are the bad guy", "Oh you stole/killed [antag item]/him" despite round end RP still going, is beneficial to the community and overall encouraging people not to enact in round end deathmatch in CC.

## Proof of Testing

https://user-images.githubusercontent.com/68121607/198348759-a069cd67-ad7f-4b5f-b2c4-7f6e40d8c3f7.mp4

Traitor IPC. Round end happens(might not see it because OBS did not capture it but the round end report button shows up on top left). Antag Hud doesn't show up for any mob.

## Changelog
:cl:
del: Antag hud for mobs after round end has been removed. Round End report still shows antags.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
correlation != causation, this is a bad PR

**Comment by Zonespace27** [comment]
> Noticing lot of EORG after post round end that has been targetted towards Traitors or people who have later been proven to be evil.

I have literally never seen this (and neither have other staff I've talked to) unless you count conflict that carries on after round end, which _is not EORG_

**Comment by SpaceLoveSs13** [comment]
> > Noticing lot of EORG after post round end that has been targetted towards Traitors or people who have later been proven to be evil.
> 
> I have literally never seen this (and neither have other staff I've talked to) unless you count conflict that carries on after round end, which _is not EORG_

I have seen it myself in the two rounds i just played last time. Obviously I am not a valid source of statistics. However it definitely wasn't due to on going rp, rather a spontaneous "You are bad, I knew it". Proceeds to magdump.

**Review by tf-4 — APPROVED** [review]
It cuts down on OOC info being pushed in your face at round end which I think is what Xyel and staff want (?)
Either way I don't really see a reason to keep this as a feature

**Pull request merged**
