### PR TITLE
Toxins area fixes

### PR DESCRIPTION
**Pull request by GuiltyNeko**
## About The Pull Request
Toxins was broken, wrong areas, no cables. Tada, now it's not.

## How This Contributes To The Skyrat Roleplay Experience
Power.

## Changelog

:cl:
fix: Toxins now has power on all three main maps, as well as correct area mapping.
/:cl:

### CODE REVIEW

**Comment by GuiltyNeko** [comment]
Oh yeah and I removed some silly stuff from the middle of space next to atmos on meta.

**Comment by Zonespace27** [comment]
Take it upstream unless this is somehow an SR issue

**Comment by GuiltyNeko** [comment]
There's conflicts now and I don't know how to fix conflicts still so I guess I'll be closing anyways. Of note, golden said something about copy pasting something and hoping it would go well, which caused this? I don't know, that's what was said in the discord, so maybe upstream, maybe not? Dunno.

**Comment by GuiltyNeko** [comment]
Yeah after looking at the non-skyrat versions of these maps in strongdmm, it's 100% not a TG issue, it's an us issue.

**Comment by GuiltyNeko** [comment]
Reopening because I magically figured out how to resolve conflicts and I officially hate the simplicity.

**Pull request merged**
