### PR TITLE
[MODULARISATION AUDIT] Modularise some liquids code

### PR DESCRIPTION
**Pull request by tf-4**

### CODE REVIEW

**Comment by ghost** [comment]
While we're here, I beg of you, add some opacity to fluids on the ground and make extinguishing the fire ACTUALLY extinguish the fire 🥺 those two issues ALONE make the fluids horribly unfun 🙏

**Comment by tf-4** [comment]
While that's a good idea, that's not really in the scope of the pr

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by SpaceVampire** [comment]
Merged with three downvotes?
Democracy is dead. Real 1984 hours.

**Comment by dwasint** [comment]
> While we're here, I beg of you, add some opacity to fluids on the ground and make extinguishing the fire ACTUALLY extinguish the fire 🥺 those two issues ALONE make the fluids horribly unfun 🙏

if you wish to port that feature from my version of it i have a system similar to that that adds dynamic opacity to fluids.

**Pull request merged**
