### PR TITLE
[MIRROR] Adds dedicated sprites for metal hydrogen armor

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/57591
--------------------
## About The Pull Request

Adds two new (nicely made) sprite sets for the metal hydrogen armor and helmet, which previously reused bad-looking sprites and thus blended terribly.

## Why It's Good For The Game

No more butt-fugly sprite reuses!
image

## Changelog
:cl:
add: New metal hydrogen armor sprites
/:cl:

### CODE REVIEW

**Comment by dawsonkeyes** [comment]
YEAH BAYBEE

**Comment by gonenoculer5** [comment]
This shit looks awful ngl. I prefer the look of the original shit. -1 for me dawg.

**Comment by dawsonkeyes** [comment]
> This shit looks awful ngl. I prefer the look of the original shit. -1 for me dawg.

your opinion is noted and subsequently forgotten

**Comment by KasparoVy** [comment]
RIP, downgrade

**Pull request merged**
