### PR TITLE
Small L.Wish Vendor resprite, removes unused Cyan sprite

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Title
Did YOU know that the sprite can be changed to Cyan? No? Of course you didn't, nobody used it!
So now it's gone.

Also removed the hard black lines, extremely colorful shading (why was it so colorful but only in splotches) and some of the unnecessarily prominent **imagery.**
dreamseeker_3ydr1DlZMx

The untrained eye won't even know what's changed.

## How This Contributes To The Skyrat Roleplay Experience
Makes it stick out less. Subtlety can be a good thing; having this stuff not only present, but violently loud and out of place makes it feel more videogamey and weird. If we're gonna have this stuff, can't it at least fit in?

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  I already posted this but here
  
dreamseeker_3ydr1DlZMx

</details>

## Changelog

:cl:
imageadd: tweaked the lustwish sprite to blend better with other vendors
imagedel: deleted the practically unused cyan lustwish sprite
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
Does this fix the map editor issue too?

**Comment by ghost** [comment]
> Does this fix the map editor issue too?

~~*Theoretically*, since it removes the randomized sprite state, it should. Maybe.~~
I forgot to change the actual icon state actually. NOW it should. Theoretically.

**Review by tf-4 — APPROVED** [review]

**Comment by Zergspower** [comment]
Sooo what's the before?

**Comment by ghost** [comment]
Old was posted in discord:
image
The changes are minor and mostly color tweaks, shading, and shape to make it more consistent with other vendors. Cyan is, ofc, gone. And yes, it's still wider, just not full tile wide

**Review by Ebin-Halcyon — APPROVED** [review]
Yeah, ig.

**Pull request merged**
