### PR TITLE
Kills the outdated aesthetics sub-module for Catwalks

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
TG has accepted the retextured catwalks as their own, and so now I can kill this;
Sadly this means re-pathing all the mentions of the old catwalks, so this has mapping changes too. Please lord forgive me.

## How This Contributes To The Skyrat Roleplay Experience
No more duplicates, no more 'why my catwalk borken?!?!'

## Changelog

:cl:
del: Outdated catwalks have been removed and fully replaced with TG catwalks
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
how tf can it have merge conflicts, I just did this from a fresh branch off master >:(

**Review by GoldenAlpharex — APPROVED** [review]
Code checks out.

**Comment by GoldenAlpharex** [comment]
MDB checks out too, yeet!

**Comment by ghost** [comment]
good riddance

**Pull request merged**
