### PR TITLE
[Modular] Ghost Cafe (No EORG Opt-Out, Though.)

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
What it says on the tin. I looked into porting EORG-Opt Out, but the only part of it that I got working was the preferences before it runtimed to hell and back. Figured I might as well throw up the work I did do, though, even if it's not in the most complete state. Heavily based on the ninja GBJ without actually touching the original, 8 big ass condos, a pool, two bars, and cryo. Also a ballroom to customize.
image
This PR also changes the assault ops prisoners to no longer be roundstart randomly generated humans and instead ghostroles, as originally intended.

UPDATE: Cafe Cyborgs are back. Took some bullshit but they don't runtime anymore, and can't unlock their cover!

## Why It's Good For The Game
Syndies have DS-1 to relax and dick around in, but station chars have, at best, the space hotel. That didn't sit right with me, so I made this!

## Changelog
:cl:
add: The ghost cafe has half-returned!
/:cl:

### CODE REVIEW

**Comment by NonoodWhatever** [comment]
Looks pretty interesting.

**Comment by H0gberg** [comment]
wonderful work!

**Comment by SpaceVampire** [comment]
You could always just go to the low-pop server that still exists as well. I thought that we didn't actually want the ghost-cafe to return.

**Comment by unit0016** [comment]
ninety nine percent sure "anti-EORG bad" is a meme, not something people are serious about.
Not to mention character backporting would be scuffed considering they don't share every part, AND not to mention that the lowpop server won't be around forever.

**Comment by unit0016** [comment]
need to move the map quickly, weh

**Comment by unit0016** [comment]
Merge conflict and cyborg code problems, damn.

**Comment by unit0016** [comment]
shelving this for now. Cyborg code is a problem, along with map conflicts. I want to focus on overhauling ruins right now anyways.

**Pull request closed without merging**
