### PR TITLE
New SMES sprites by Irra

### PR DESCRIPTION
**Pull request by Erol509**
## About The Pull Request

New SMES sprites by Irra or @martinlyra from https://github.com/Haven-13/Haven-Urist/pull/67
128158604-1cb17b84-996d-41bb-a5b5-c121a1171777
image

SMES's have a EMP interaction now.

## How This Contributes To The Skyrat Roleplay Experience

More modern sprites for SMES, they have similar soul as previous one, but have more modern display. 

## Proof of Testing
image
image

## Changelog

:cl: Irra
add: New SMES sprites made by Irra and retlaw34 for panel icon. Credits for them.
/:cl:

### CODE REVIEW

**Comment by Erol509** [comment]
Oh, my god. This PR might be a failure, because runtimes from colony fabricator missing  sprites

**Comment by Gandalf2k15** [comment]
Nice sprites, will merge once fixed ;)

**Comment by jjpark-kb** [comment]
> Nice sprites, will merge once fixed ;)

I will only say we shouldn't because it currently is PR'd on /tg/. If it fails to get merged up there, then yea, lets merge it.

**Comment by Erol509** [comment]
> Nice sprites, will merge once fixed ;)

It has runetimes, I mean everything works in game. But CI is failing due to paxil using smes as a base path for his batteries. And I cant quite figure out how to split them.

**Comment by Erol509** [comment]
Yeah, Im not going to rewrite whole colony's module code to fix CI

**Pull request closed without merging**
