### PR TITLE
makes the xeno scream an actual (series of) xeno scream(s)

### PR DESCRIPTION
**Pull request by thestubborn**
## About The Pull Request

this replaces the terrible...or very bad hiss 6 which drives me and quite a few people up the wall with its annoyingness  with actual xenomorph sounds, from TGMC

## How This Contributes To The Skyrat Roleplay Experience

its more immersive compared to hiss6, it also doesn't sound like a spiked cock being dragged across an ultrafine chalkboard

https://files.catbox.moe/clwdhq.ogg
https://files.catbox.moe/q5bplm.ogg
https://files.catbox.moe/8d3j8t.ogg
https://files.catbox.moe/456rx4.ogg

I couldn't decide which sounded best, so I done all em 😈 

## Changelog

:cl: Plateau (who done nothing) sound people from TGMC (they done everything)
expansion: made the xeno scream actual xeno screams
soundadd: four new sounds for the xeno scream, from TGMC
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
These are ear piercingly loud and grating

**Comment by thestubborn** [comment]
just like the current xeno scream then,,,

**Comment by GoldenAlpharex** [comment]
> just like the current xeno scream then,,,

No, I'd say this is arguably even worse in terms of ear-shattering, and letting players make this kind of noise would just result in me coding out xenomorph screams entirely.

**Comment by thestubborn** [comment]
> 
> 
> > just like the current xeno scream then,,,
> 
> No, I'd say this is arguably even worse in terms of ear-shattering, and letting players make this kind of noise would just result in me coding out xenomorph screams entirely.

good

**Comment by GoldenAlpharex** [comment]
They still don't sound much better, sorry. Feel free to open another one if you get better sounds for them.

**Pull request closed without merging**
