### PR TITLE
Tram-STAIR-tion

### PR DESCRIPTION
**Pull request by Aurelien3189**
Get it?

Replaces most of the ladders on tramstation with stairs, to provide walkways beneath the tram to reduce tram-trauma

image

image

I'm not too confident in this one, but I thought it might have some utility. Suggestions or feedback welcome!

### CODE REVIEW

**Comment by FlamingLily** [comment]
just catch the tram silly

**Comment by tf-4** [comment]
I actually like this. Not sure if it has any balance issues off the top of my head but stairs look better than ladders and are more enjoyable to use

**Comment by Gandalf2k15** [comment]
TG may like this. Given we just got smart pipes were going to have to map reset. Again.

**Comment by Gandalf2k15** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/4695

**Pull request closed without merging**
