### PR TITLE
[WIP] THE BRAZILIAN FOOD REVOLUTION! Gives and creates several Brazilian/Spanish recipies to the game.

### PR DESCRIPTION
**Pull request by Guidesu**
## About The Pull Request
**PLEASE BE CIVIL ABOUT THIS PULL REQUEST, IF YOU ARE LATIN SPANISH (AKA: South American Spanish guy) FEEL FREE TO HELP ME ON THIS PR SINCE I DON'T KNOW JACK SHIT ABOUT YOUR CULTURAL FOOD.**

This PR is to give several Brazilian and Spanish types of food but adapted to space culture due to several years and changes.
Plus adding more Brazilian drinks like Caipirinha (Caipirinha is a Brazilian alcoholic drink, or a cocktail of São Paulo origin, made with cachaça, lemon, sugar, and ice. Variations include a caipiroska - with vodka when freed from cachaça - and a caipiríssima - with rum), and Cachaça (Cachaça is a distilled spirit made from fermented sugarcane juice.).

Meaning this PR will be a hell of fun to make and I am opened to ideas!

## Why It's Good For The Game
More content to bartenders/cook.
Cultural exchanges.
Plus more fun to do in the game.

## Changelog
:cl:
WIP
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
add something to the drink file


anyway, add churros, that's like the one Spanish food I know/remember

**Comment by Guidesu** [comment]
> add something to the drink file
> 
> anyway, add churros, that's like the one Spanish food I know/remember

I will

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=Fw90Bk_a6aY

**Comment by thestubborn** [comment]
ADD....Sopa de Macaco, Uma Delicia
and https://www.youtube.com/watch?v=-e5gTx1fVU4

**Pull request closed without merging**
