### PR TITLE
De-Cockpits the Cargo Shuttles

### PR DESCRIPTION
**Pull request by sqnztb**
## About The Pull Request

Removes the cockpit from the cargo shuttle. The table and computer have been left for nostalgia reasons.

## How This Contributes To The Skyrat Roleplay Experience

Titan's been gone forever. This should've been handled long ago. One less excuse for cargo to lose a crate.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

</details>

## Changelog

:cl:
qol: Cargo shuttles have had the cockpits removed.
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
No cock huh.

**Comment by Jolly-66** [comment]
The cock pit is soul.

Yes, the **cock** pit.

**Comment by sqnztb** [comment]
I left the table for you, specifically, Jolly. You're welcome.

**Review by GoldenAlpharex — COMMENTED** [review]
I'll leave this up to Paxil and Jolly, but personally I don't think that the table/console should stay.

**Comment by Iamgoofball** [comment]
You should just revert it back to the stock /tg/ cargo shuttle.

**Comment by sqnztb** [comment]
> I'll leave this up to Paxil and Jolly, but personally I don't think that the table/console should stay.

I honestly did consider this, but leaving them in place with just taking the wall/airlock down gives a nice, even 8x5 space instead of 8x5+2

**Comment by Paxilmaniac** [comment]
I should've just removed the cockpit when I redid these

**Comment by Jolly-66** [comment]
The cockpit is GOOD ITS SOULFUL

**Comment by Paxilmaniac** [comment]
There's nothing wrong with this pr for the record I just figured it'd be better if I redid the shuttles proper to not have a cockpit.

**Comment by Iamgoofball** [comment]
The cockpit is literally useless due to the fact the cargo shuttle isn't driven anymore, it's fully automated again, all it does is block crates and require techs to welder down the cockpit walls to get at their crates/mail.

**Comment by MitztheKat** [comment]
The cockpit is a pain in the ass.
I'd just name the table Cock-pit and some silly flavour text saying
"there's a big dent in the table, pointing downwards. so that's where those crates went..."
then I'm 110% sold

**Pull request closed without merging**
