### PR TITLE
No more crunchy socks

### PR DESCRIPTION
**Pull request by Funce**
## About The Pull Request
The Secboots are no longer crunchy. We've put them all through the laundry! Along with the socks! No more will that cursed crunch haunt you.

## Why It's Good For The Game
I kind of like living, though I do swear that my life is not in danger as I write this

## Changelog
:cl: Foxtrot (Funce)
del: Security Boots no longer crunch when you walk!
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Also, nah, I don't think it's needed, just lower the volume slightly.

**Comment by YakumoChen** [comment]
wtf I love the crunchy boots, I love that antags know I'm coming 3 lightyears away.

**Comment by FlamingLily** [comment]
I also like the crunchy boots, but honestly, my main issue with this PR is that there's a way to get rid of them in game, it's really optional.

I would suggest adding a roll of tape to the locker room over outright removing the crunch.

**Comment by Cheshify** [comment]
Make em click instead please, crunch bad

**Comment by LeonY24** [comment]
crunchy sound is shit and doesn't make any sense. sec doesn't have so much things on them to crunch like that, even more, only boots make your footsteps sound like shit.

**Comment by YakumoChen** [comment]
The boots sound like marching. It's a trope, and it adds depth to security's interactions with antagonists (given as security is much more audible now)

**Comment by Gandalf2k15** [comment]
I think we can keep it, don't remove the sound, if you must, change it to something you think is better.

**Comment by NullDagaf** [comment]
LEAVE THE CRUNCH IN OR WE RIOT

**Comment by Funce** [comment]
I guess I'll save this for later then.

**Pull request closed without merging**
