### PR TITLE
Disables savannah ivanov until further notice.

### PR DESCRIPTION
**Pull request by Gandalf2k15**
Title. Host suggest.

Too OP and also has a bug where MMIs go to Brazil if they die in mech.

### CODE REVIEW

**Comment by Vizoplez** [comment]
I got ahold of the savannah ivanov mech that killed 90% of the nukies. Player skill made it far too good.

**Comment by NetraKyram** [comment]
I'll be real with you, it requires coordination and skill, that shouldn't be disabled, or removed. That's just my two cents on it, don't disable one of few _really good things_ that relies on **coordination and teamwork** to be so good. Fixing the bugs? Certainly, disabling it completely? I don't think so.

**Comment by hugmeorelse** [comment]
> I'll be real with you, it requires coordination and skill, that shouldn't be disabled, or removed. That's just my two cents on it, don't disable one of few _really good things_ that relies on **coordination and teamwork** to be so good. Fixing the bugs? Certainly, disabling it completely? I don't think so.

It single-handedly destroyed a 10-men nuclear operatives team.

**Comment by Iamgoofball** [comment]
Skill issue.

**Pull request merged**
