### PR TITLE
Mini Suit File Cleanup: Removes some completely unused, sus (tm), 1944 'german military' larp sprites from the modular suits file

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
Just look at icondiff if you want to see what I'm talking about.

## How This Contributes To The Skyrat Roleplay Experience
These are both unused and I don't know why we have them to begin with.

## Changelog

:cl:
imagedel: Removed a few entirely unused sprites from the modular suits icon file
/:cl:

### CODE REVIEW

**Review by Zonespace27 — APPROVED** [review]
I blame hubert and/or cobalt for the nazi clothing

**Review by tf-4 — APPROVED** [review]

**Comment by Paxilmaniac** [comment]
merge conflict oh you bastard

**Comment by tf-4** [comment]
whats the rd labcoat stuff

**Comment by Paxilmaniac** [comment]
world's worst merge conflict resolve, that's what

**Review by GoldenAlpharex — APPROVED** [review]

**Pull request merged**
