### PR TITLE
[READY] [MODULAR] Closable stasis beds and stasis body bags.

### PR DESCRIPTION
**Pull request by FlamingLily**
## About The Pull Request
Introduces stasis body bags. When closed, has the same effect as an active stasis bed, however, does not allow you to operate or treat the person, cause y'know it's a closed bodybag. It also does not activate on a living person, for balance reasons.

Stasis beds have been reworked! They now close when in use, but unlike bodybags, are still able to be used on living beings. From here on, they'll be called "stasis units" to avoid confusion

*Technically* has not changed stasis beds. The new stasis units are a different object from the old ones, and the old ones are no-longer researchable, and they have been removed from the 'core' maps (those being Meta, Delta, both boxes, Tram and Kilo).

Added 2 stasis units to each map's medbay, as per above. The security medbay gets a stasis body bag. More can be printed from the medical (and science, for the bodybag) lathe when cryogenic technology (where the original stasis bed used to be) is researched.

Stasis beds have been replaced with medical beds.

Icons! With the previous 2 bodybag types for reference. (The green is the stasis one, naturally.)

bags

More icons!
bedicon

## Why It's Good For The Game
Stasis beds have long been used as *the medbay tool*, which is unhealthy for gameplay in the same sense that a sleeper is. Stopping them from being linked to operating computers was a good change, but all it did was mean "let's build an operating table next to the stasis bed." This allows doctors to actually make use of the surgery rooms, helps to stop the treatment center from being cluttered with operating tables **everywhere**, encourages more diverse RP and mechanics from the medbay, and overall, should work to improve medbay as a whole.

## Changelog
:cl:
add: NanoTrasen's RnD department has managed to condense the stasis technology commonly seen in stasis beds into a fold-able body bag!
balance: A critical flaw has been found in the old stasis bed design. The new design, however, closes when in use, so you are unable to perform surgery on them or treat those inside them.
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
[Here They Come]

Overall, pretty good sounding. I still like the idea of having Stasis beds be a late shift tech, that is really costly and takes a fair bit of points to get to, letting medbay still use them but making it so they cant just outright rely on them at shiftstart.

**Comment by FlamingLily** [comment]
> 
> 
> [Here They Come]
> 
> Overall, pretty good sounding. I still like the idea of having Stasis beds be a late shift tech, that is really costly and takes a fair bit of points to get to, letting medbay still use them but making it so they cant just outright rely on them at shiftstart.

While I see where you're comin' from, I also think that all that would do is be:

New research priority from all med's whinging
Adv. Mining > T4s > Adv. Biotech > Stasis beds

**Comment by Gandalf2k15** [comment]
Better change: instead of removing the beds, make them have a cover that closes when you put the patient in it.

**Comment by Gandalf2k15** [comment]
> Better change: instead of removing the beds, make them have a cover that closes when you put the patient in it.

This is arguably the less intrusive and more modular option

**Comment by FlamingLily** [comment]
> 
> 
> > Better change: instead of removing the beds, make them have a cover that closes when you put the patient in it.
> 
> This is arguably the less intrusive and more modular option

I mean, that was suggested, but thing is that's far outta my league

Also this is entirely modular, the beds are still in the code, just the research has been changed. and the maps changed so you can't access or make them

**Comment by gonenoculer5** [comment]
> > Better change: instead of removing the beds, make them have a cover that closes when you put the patient in it.
> 
> This is arguably the less intrusive and more modular option

@FlamingLily steal old sleeper code basically. make it so you put them in the stasis bed and cant do anything to them, literally putting them on ice until you can fix them basically.

**Comment by FlamingLily** [comment]
> 
> 
> > > Better change: instead of removing the beds, make them have a cover that closes when you put the patient in it.
> > 
> > 
> > This is arguably the less intrusive and more modular option
> 
> @FlamingLily steal old sleeper code basically. make it so you put them in the stasis bed and cant do anything to them, literally putting them on ice until you can fix them basically.

See, my issue here is what would be the point? Just use the stasis bags like that.

**Comment by Cheshify** [comment]
Medical's had MORE than enough major hits to their effectiveness.

**Comment by Arctaisia** [comment]
I like this, primarily because they're a paramedic tool that baycode has, and it really lets them work much better. Maybe a redo to stasis beds would be in order rather than outright removing them, but I certainly am 100% down for stasis bags, they'd make a paramedic's job much easier, and I see them used plenty of times on Chompstation.

**Comment by FlamingLily** [comment]
> 
> 
> Medical's had MORE than enough major hits to their effectiveness.

I still fail to see how this would make them any less effective.

YES, you can no longer do surgery on them, okay. So do what medical does today anyway, drag the stasis bag into a surgery room and use the table.

Organ rot mid-surgery? Formaldehyde.

Plus, the lack of clutter in the treatment center will INcrease effectiveness of medbay overall.

**Comment by Gandalf2k15** [comment]
I just don't like the fact they're stasis bags. Bags containing super high tech components. Eeh.

**Comment by FlamingLily** [comment]
Leaving these here for discussions and a bit of insight as to why I think the change is a good idea
med1
med2

**Comment by FlamingLily** [comment]
what the fuck why is everything broken?

**Comment by FlamingLily** [comment]
aaaaaaaaaaaaaaaaaaa
https://github.com/Skyrat-SS13/Skyrat-tg/pull/4695
pain okay closing this until it fuckin' works

**Comment by FlamingLily** [comment]
guess who's back back again hopefully working now

**Comment by FlamingLily** [comment]
well no map errors yet so uh looking good

**Comment by FlamingLily** [comment]
aaaaaaaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

ok as an aside todo: make stasis bags suffocate y/n? y

**Comment by YakumoChen** [comment]
Why would they suffocate? Isn't the point of stasis _stopping_ life ticks?

**Comment by FlamingLily** [comment]
> Why would they suffocate? Isn't the point of stasis _stopping_ life ticks?

They suffocate for balance reasons, because having magic "you stop dying now" bag available at round start completely nullifies pretty much any kind of need for paramedics to have epi

ICly, there's no reasonable explanation cause there's no reasonable explanation for how stasis works on conscious living patients anyway

It's too stop bodies from rotting, not to keep people alive

**Comment by softcerv** [comment]
These stasis body bags are cool as hell, but I don't think that the regular stasis beds should be removed from medbay. Having surgery removed from stasis beds would probably be more than enough of a nerf for them. 

The stasis bags doing oxygen damage doesn't sound horrible, but like it should be at a reduced rate or something. Like enough that it encourages doctors to be fast with treatment, but not enough that it feels like a hindrance to use.

**Comment by FlamingLily** [comment]
> 
> 
> These stasis body bags are cool as hell, but I don't think that the regular stasis beds should be removed from medbay. Having surgery removed from stasis beds would probably be more than enough of a nerf for them.

See, my issue with this idea is that it won't inherently change anything with the current medbay status of "stasis bed is for every kind of injury because it literally stops any negative things." A magic box that stops people dying with no further effort needed feels too powerful and is bad for gameplay, the same way old sleepers were.

> The stasis bags doing oxygen damage doesn't sound horrible, but like it should be at a reduced rate or something. Like enough that it encourages doctors to be fast with treatment, but not enough that it feels like a hindrance to use.

I'm afraid I'm a little confused here, the bag would only do suffocation damage to someone who is alive, naturally, so it would be used as a tool to preserve dead bodies, and only dead bodies

**Comment by softcerv** [comment]
> See, my issue with this idea is that it won't inherently change anything with the current medbay status of "stasis bed is for every kind of injury because it literally stops any negative things." A magic box that stops people dying with no further effort needed feels too powerful and is bad for gameplay, the same way old sleepers were.

((Yes, I know that this has been touched on earlier, but still.))
Having interactions with the patient unavailable during stasis, sort of like sleepers, shifts the beds into being more a tool that gives doctors some extra time to breathe and prepare before they preform surgery on their patient rather then just having it be a better surgery table. 

If stasis only works on dead people just feels like it would make the stress of one of the most stressful jobs on station that much more stressful, especially during times where medbay is crowded.

**Comment by FlamingLily** [comment]
> Having interactions with the patient unavailable during stasis, sort of like sleepers, shifts the beds into being more a tool that gives doctors some extra time to breathe and prepare before they preform surgery on their patient rather then just having it be a better surgery table.
> 
> If stasis only works on dead people just feels like it would make the stress of one of the most stressful jobs on station that much more stressful, especially during times where medbay is crowded.

My question then becomes: How often does, realistically, surgery get performed on a living person, while they're under threat of dying?

You'll pretty much always stabilise a patient before moving ahead in surgery, and if they can't be stabilised, you should pump 'em full of enough chems that they don't die mid-surgery

**Comment by softcerv** [comment]
> 
> 
> > Having interactions with the patient unavailable during stasis, sort of like sleepers, shifts the beds into being more a tool that gives doctors some extra time to breathe and prepare before they preform surgery on their patient rather then just having it be a better surgery table.
> > If stasis only works on dead people just feels like it would make the stress of one of the most stressful jobs on station that much more stressful, especially during times where medbay is crowded.
> 
> My question then becomes: How often does, realistically, surgery get performed on a living person, while they're under threat of dying?
> 
> You'll pretty much always stabilise a patient before moving ahead in surgery, and if they can't be stabilised, you should pump 'em full of enough chems that they don't die mid-surgery

I'm not saying that surgery would immediately be preformed on crit patients, but rather that stasis would give doctors the time that they need, to be prepared to stabilize a patient then preform surgery. During that time doctors would be able to diagnose the patient, figure out how they want to go about treating the patient, and gather the chems/surgery tools that are needed.

**Comment by FlamingLily** [comment]
> > My question then becomes: How often does, realistically, surgery get performed on a living person, while they're under threat of dying?
> > You'll pretty much always stabilise a patient before moving ahead in surgery, and if they can't be stabilised, you should pump 'em full of enough chems that they don't die mid-surgery
> 
> I'm not saying that surgery would immediately be preformed on crit patients, but rather that stasis would give doctors the time that they need, to be prepared to stabilize a patient then preform surgery. During that time doctors would be able to diagnose the patient, figure out how they want to go about treating the patient, and gather the chems/surgery tools that are needed.

I don't think there's all that many scenes where a patient would HAVE to have surgery before being stabilised, so surgery prep wouldn't need to happen before then, and as for stabilising a patient, I don't believe that takes *too* much prep or effort, as long as you've got epi on standby and some first aid gear, you should be fine, right?

**Comment by softcerv** [comment]
> 
> 
> > > My question then becomes: How often does, realistically, surgery get performed on a living person, while they're under threat of dying?
> > > You'll pretty much always stabilise a patient before moving ahead in surgery, and if they can't be stabilised, you should pump 'em full of enough chems that they don't die mid-surgery
> > 
> > 
> > I'm not saying that surgery would immediately be preformed on crit patients, but rather that stasis would give doctors the time that they need, to be prepared to stabilize a patient then preform surgery. During that time doctors would be able to diagnose the patient, figure out how they want to go about treating the patient, and gather the chems/surgery tools that are needed.
> 
> I don't think there's all that many scenes where a patient would HAVE to have surgery before being stabilised, so surgery prep wouldn't need to happen before then, and as for stabilising a patient, I don't believe that takes _too_ much prep or effort, as long as you've got epi on standby and some first aid gear, you should be fine, right?

If we are considering situations where there are only like one or two patients at once, working without stasis isn't horrible.
However, if something comes that ends up filling medbay with servery injured patients, the lack of stasis will make an already difficult and stressful situation that much more agonizing to deal with for medical players.

**Comment by FlamingLily** [comment]
> If we are considering situations where there are only like one or two patients at once, working without stasis isn't horrible.
> However, if something comes that ends up filling medbay with servery injured patients, the lack of stasis will make an already difficult and stressful situation that much more agonizing to deal with for medical players.

Mmmm, that is true, but how often is there swathes of *injured* but not ***dead*** patients.

The last instance I can remember was when a looping rod hit 16 people, the vast majority of them were dead, not dying, by the time they got to the medbay.

**Comment by softcerv** [comment]
> 
> 
> > If we are considering situations where there are only like one or two patients at once, working without stasis isn't horrible.
> > However, if something comes that ends up filling medbay with servery injured patients, the lack of stasis will make an already difficult and stressful situation that much more agonizing to deal with for medical players.
> 
> Mmmm, that is true, but how often is there swathes of _injured_ but not _**dead**_ patients.
> 
> The last instance I can remember was when a looping rod hit 16 people, the vast majority of them were dead, not dying, by the time they got to the medbay.

I'd say that I usually get more patients with some kind of severe injury or in crit rather than dead most of the time that I've had to deal with a flooded medbay. 

Stasis also makes the whole zombie event a lot more bearable too, as a medical player.

**Comment by FlamingLily** [comment]
Hmmm, I'll definitely consider this stuff.

**Comment by softcerv** [comment]
> 
> 
> Hmmm, I'll definitely consider this stuff.

Thank you for taking my opinion into consideration, there are a lot of ideas in this PR that I like, even if I'm not the most keen on having stasis changed to be focused around use on corpses.

**Comment by SpaceVampire** [comment]
I would also point out that Cryostylane already exists, to allow a cryostasis in dead people created via chems.
So this feels like its kinda poking into the same general area.

**Comment by YakumoChen** [comment]
I don't really ever see chems like cyrostylane ever made or used, chemists are a very rare breed of medical and often contribute extremely little to medbay when they do exist.

I do see large crowds of injured dumped into medbay from time to time, especially from large sec vs antag fights, usually antags only bother to crit security and not full kill and the survivors often bring in the in-crit and dead and need treatment themselves.

 Epis and chems dont do a whole lot on severe crit, and those bleeding out, often without a team of doctors and a few stasis beds or at least several medibots you'd be likely to see more people dying on the table.

**Comment by FlamingLily** [comment]
> ... you'd be likely to see more people dying on the table.

I get that, but consider for a second.

That's not a bad thing, necessarily.

The alternative is being dumped on a status table, usually while in hard crit (i.e. unconscious and unable to see or interact with anything) and being stuck like that while doctors prepare and organise the other patients.

Whereas, a large swathe of critical patients come in? First, find the most injured, or most important to keep alive, triage style. Try and get them stable, while watching over the other patients. If one dies, stasis bag them, move on to the next patient. Now, the player who died *has the ability to leave their body, to chat with dead chat, and to watch as the medbay works to revive them.* They get a brief respite with *more substance* than just being unconscious for the entire time.

**Comment by FlamingLily** [comment]
Also as an aside no one uses chems other than straight healing chems because stasis beds are better

**Comment by softcerv** [comment]
> 
> 
> Also as an aside no one uses chems because stasis beds are better

It's not only stasis beds, most options feel like they outclass using chemicals to be honest. I usually only find chems useful for oxy/tox along with organ damage that I can't fix with surgery.

**Comment by FlamingLily** [comment]
> 
> 
> > Also as an aside no one uses chems because stasis beds are better
> 
> It's not only stasis beds, most options feel like they outclass using chemicals to be honest. I usually only find chems useful for oxy/tox along with organ damage that I can't fix with surgery.

True, but replacing beds w/ bags should help to give chemists and chems a little more of a role, without making them entirely depended on.

**Comment by YakumoChen** [comment]
> 
> 
> > ... you'd be likely to see more people dying on the table.
> 
> I get that, but consider for a second.
> 
> That's not a bad thing, necessarily.
> 
> The alternative is being dumped on a status table, usually while in hard crit (i.e. unconscious and unable to see or interact with anything) and being stuck like that while doctors prepare and organise the other patients.
> 
> Whereas, a large swathe of critical patients come in? First, find the most injured, or most important to keep alive, triage style. Try and get them stable, while watching over the other patients. If one dies, stasis bag them, move on to the next patient. Now, the player who died _has the ability to leave their body, to chat with dead chat, and to watch as the medbay works to revive them._ They get a brief respite with _more substance_ than just being unconscious for the entire time.

Hard disagree. A death in medbay is considered a loss for medbay staff. This also impacts players who are Do Not Revive. I would consider any feature for medbay that purports essentially "let them die, it makes it easier/better" to be an extreme step back in terms of medbay goals.

I largely don't consider stasis beds to be a problem. You only get 2 at roundstart, and the research to build more is generally late-game / hour in tech at minimum and still requires someone to spend the time to actually build them. Beds are usually reserved for top priority patients who have life-threatening injuries as well when medbay is overrun. Beds are something medbay gets to improve treatment and make more availability to deal with high volume problems, which I feel is natural progression


Considering you expressed desire to make living people in bags suffocate, I have to ask, "what is the point of this feature?" 
-Epi pens do the same function stasis bags do to corpse, ie preserve them. 
-Having someone in a stasis bed in crit, suffocating, is no better than the actual crit status does regardless, making it largely pointless to carry injured in them unless they're bleeding out or something that would be worse than suffocating. 
-You can't be sure on someone's status in a bag since you have no way to examine them, making triage much harder.

It seems like it would be better to remove stasis completely if that is your goal.

**Comment by YakumoChen** [comment]
> 
> 
> Also as an aside no one uses chems other than straight healing chems because stasis beds are better

Chems generally aren't interesting to use in triage. Having a magic liquid do your job for you is as fun as it sounds, surgery is the bulk content of Medical Doctor as a job because surgery and triage is engaging. TG has largely moved away from straight healing chems I would assume generally for this reason, they're supposed to be used for non-critical injuries and unconventional ailments (like toxin or organ damage or radiation)

**Comment by FlamingLily** [comment]
> > Also as an aside no one uses chems other than straight healing chems because stasis beds are better
> 
> Chems generally aren't interesting to use in triage. Having a magic liquid do your job for you is as fun as it sounds, surgery is the bulk content of Medical Doctor as a job because surgery and triage is engaging. TG has largely moved away from straight healing chems I would assume generally for this reason, they're supposed to be used for non-critical injuries and unconventional ailments (like toxin or organ damage or radiation)

I'm sure they're more fun than a magic Box that's available with no extra effort

**Comment by Owai-Seek** [comment]
Just re-add the need for anesthetics and leave stasis beds alone.

Why would you want people to be dead longer, or die faster.

**Comment by YakumoChen** [comment]
> Better change: instead of removing the beds, make them have a cover that closes when you put the patient in it.

Honestly I still think this is the best idea, since you made stasis not actually work on living people and there is still a need for stasis

**Comment by FlamingLily** [comment]
> Why would you want people to be dead longer, or die faster.

Just saying it again, I, at least personally, though I'm sure plenty would agree, would much prefer to be dead and waiting than alive and waiting to be treated.

If you're alive but near death and stuck on a stasis bed, and doctors are busy, your options are. Wait, usually with no one to talk to or anything, or get off the bed and die. Or worse, you're in hardcrit and unconscious. Then you're stuck unconscious while you wait for treatment.

Whereas without stasis beds, okay sure, deaths on the treatment table may be far more common. Dying isn't a bad thing, especially when you can be revived. You get deadchat, you get to observe, you're not stuck idly waiting for treatment with nothing else to do.

Doctors should be prioritizing saving the living over trying to revive the dead, which is not to say *don't* revive the dead, of course. Just wait until there's not someone dying.

**Comment by GoldenAlpharex** [comment]
> > Why would you want people to be dead longer, or die faster.
> 
> Just saying it again, I, at least personally, though I'm sure plenty would agree, would much prefer to be dead and waiting than alive and waiting to be treated.

I don't know man, dying ain't really that much fun, especially since you usually have to forget what killed you, whereas it's not as required for when you're just gravely injured.
> If you're alive but near death and stuck on a stasis bed, and doctors are busy, your options are. Wait, usually with no one to talk to or anything, or get off the bed and die. Or worse, you're in hardcrit and unconscious. Then you're stuck unconscious while you wait for treatment.

Unless the person treating you doesn't know what they're doing, you're going to stay in hardcrit for at maximum twenty to thirty seconds.
> Whereas without stasis beds, okay sure, deaths on the treatment table may be far more common. Dying isn't a bad thing, especially when you can be revived. You get deadchat, you get to observe, you're not stuck idly waiting for treatment with nothing else to do.

I'd say that's only true if you're stuck in hardcrit for an extended period of time, otherwise it's a lot less annoying to stay alive and just be healed up than to have to die and wait as you see your organs decaying.

> Doctors should be prioritizing saving the living over trying to revive the dead, which is not to say _don't_ revive the dead, of course. Just wait until there's not someone dying.

You said it right here. They should be prioritizing the living, which means, you do whatever you can to avoid them dying. If they die, you failed your job, and putting someone in a fancy bodybag instead of using an epipen just makes little sense to me.

Stasis beds are fine because there's no more advanced surgeries on them, hell, as others have pointed out, they could have covers when the person's on it, so you can't interact with them, but the entire point of stasis is to give medbay some time to breathe when things get hectic. It's usually for when someone's bleeding out, highly intoxicated or on the brink of death, and gives you more time to focus on the roleplay part of things instead of having to go fully mechanical of "if I don't act now they're actually dead"

**Comment by Gandalf2k15** [comment]
Aaaa make stasis beds simply close when in use

**Comment by FlamingLily** [comment]
Alright, I've decided I'll be giving stasis beds a sleeper-like lid.

**Comment by Trubbl3** [comment]
man, you guys sure to make medbays work harder for no reason, huh

**Comment by SpaceVampire** [comment]
> 
> 
> I don't really ever see chems like cyrostylane ever made or used, chemists are a very rare breed of medical and often contribute extremely little to medbay when they do exist.
> 
> I do see large crowds of injured dumped into medbay from time to time, especially from large sec vs antag fights, usually antags only bother to crit security and not full kill and the survivors often bring in the in-crit and dead and need treatment themselves.
> 
> Epis and chems dont do a whole lot on severe crit, and those bleeding out, often without a team of doctors and a few stasis beds or at least several medibots you'd be likely to see more people dying on the table.

For the record, I have seen a lot of people using Cryostylane lately. You can just make a bunch of 1u patches of it, from what I understand? Medical always seems to have em, and you can make a factory as well.

**Comment by Glue-m** [comment]
Is there a difference in sprite for when the stasis unit/bodybag contain a body?

**Comment by FlamingLily** [comment]
> Is there a difference in sprite for when the stasis unit/bodybag contain a body?

No, afraid not ~~yet~~, but I will add some examine text.

**Comment by FlamingLily** [comment]
oh god its been tmed i didnt even see that

**Comment by ChungusGamer666** [comment]
ah yes, gay baby jail sleepers

**Comment by FlamingLily** [comment]
Oh hey this might literally fix the only issue I'm having, in that you hit the stasis unit with your tools when using them
https://github.com/Skyrat-SS13/Skyrat-tg/pull/5041

**Comment by NullDagaf** [comment]
> man, you guys sure to make medbays work harder for no reason, huh

Cope. Not everything should be this easy.

**Comment by HoodMilk** [comment]
This does not solve the problem of "doctors are just building operating tables in the treatment room". Also this is incredibly problematic for plasmamen who basically cannot have surgery done without dying now.

**Comment by NullDagaf** [comment]
> This does not solve the problem of "doctors are just building operating tables in the treatment room".

This PR is not trying to solve that problem. It's trying to solve the "using stasis beds for surgery" problem.

> Also this is incredibly problematic for plasmamen who basically cannot have surgery done without dying now.

First off, plasmamen are quite rare, ~~as you cannot do the horny if you're burning~~ so this isn't as big of an issue you're making it seem to be. And second, both dedicated plasma rooms and even just the good ol' "roller bed under the shower" trick work too.

Also here's a thing to wonder about - isn't the POINT of this PR to reduce the, dare I say, "abusability" of stasis beds? They're used for basically everything, short of minor bruises. Your arms are necrotic? On the stasis bed you go. Appendix bursts? Slap them on that bed. Heck, even what you just said - plasmamen, with their vastly different biology SHOULD have a separate section of sorts, so they don't randomly combust or something - but people just fucking put them on stasis!

It's just. Stasis beds. For nigh everything.
Let them be changed, m'kay?

**Comment by Trubbl3** [comment]
instead of gutting TG med, better just rework it all into oldcod med

**Comment by FlamingLily** [comment]
> 
> 
> instead of gutting TG med, better just rework it all into oldcod med

Would if I could 😔

**Comment by FlamingLily** [comment]
Note: I may have broken tramstation

**hard**

it's not even opening in SDMM, so, uh

uh oh

**Comment by FlamingLily** [comment]
ok

fixed hopefully

**Comment by Kush1Push1** [comment]
Stasis beds were overpowered, nice

**Comment by FlamingLily** [comment]
i changed non-skyrat delta.... sigh

**Review by KathrinBailey — APPROVED** [review]
Since I don't really touch medical nor play it that much I'm going to give others a last chance to weigh in.
Unless there are any objections, I'll merge tomorrow. Please poke me in like 16-24 hours because I'll probably be very tired and forget.

**Comment by sqnztb** [comment]
Late to the party since I didn't see the PR before, but uh, how are you supposed to treat someone who is undergoing an allergic reaction now?

**Comment by Trubbl3** [comment]
> Late to the party since I didn't see the PR before, but uh, how are you supposed to treat someone who is undergoing an allergic reaction now?

Pent acid and suck it up if you don't have it or blood filtering but yeah the patient might die in the process

**Comment by tf-4** [comment]
> Late to the party since I didn't see the PR before, but uh, how are you supposed to treat someone who is undergoing an allergic reaction now?

Diphenhydramine, pentetic, syriniver, blood filtering. There are many options

**Comment by sqnztb** [comment]
Yeah none of those are actual options to keep someone alive.

Blood filtering does not work fast enough to save someone by itself. Period. Full stop. It is too slow of a surgery.

Pentetic purges the histamine and heals toxin at the roughly the same rate as the allergy reaction. It doesn't do anything for brute or oxyloss. Though if it's administered **IMMEDIATELY** after the allergen, it can save the patient just on the basis of it purging out the allergen before the histamine overdose kicks in.
Epinephrine _pauses_ the allergy proc but any histamine in system already continues to tick away.
Syriniver/musiver does not do enough healing to counteract the toxin buildup. It doesn't do anything for the brute or oxyloss.
Diphenhydramine purges histamine at the same rate as it's produced by the allergy reaction. It doesn't do anything for the toxin, brute, or oxyloss.
Multiver (by itself) purges the histamine and heals toxin at the same rate as the allergy reaction. It doesn't do anything for brute or oxyloss.
An advanced medibot with upgrades sitting right next to you can amusingly keep your damage numbers down enough for you to survive. Until you die of multiple organ failures.

The only thing that I've found that'll keep someone from keeling over due to an allergic response is a cocktail of 100% pure 1000K seiver, salicylic/libital, multiver, atropine, and diphenhydramine. Epinephrine can also be added in, for what it's worth, but it's not required, it just makes the purging faster. And this all assumes that the patient isn't allergic to any of the aforementioned. Granted it's been a long time since I've experimented, but if someone else has an easier cocktail that:
- Purges only histamine at a rate equal to or greater than 3u/tick.
- Heals 5+ toxin/tick (3 from allergen processing, 2 from histamine OD)
- Heals 2+ brute damage/tick
- Heals 2+ oxyloss/tick

I feel like allergen response, as it is with this PR, is now 100% death because it'll be easier to just let the person die and blood filter them out. This isn't exactly good gameplay.

**Comment by Trubbl3** [comment]
stasis beds are used to stabilize people who are almost dead and get them ready for surgery on an operating bed if changed it will make doctor just suck up, letting patients die to just defib later.

Using them for anything else is plain wrong and inefficient, those new stasis pods are plain useless, theres no point of shoving people inside them if you cannot treat them, they will die the second you get them out of the stasis pod making them just a glorified forma patch to preserve bodies

**Pull request merged**
