### PR TITLE
[MODULAR] Hairfre Hairstyle

### PR DESCRIPTION
**Pull request by softcerv**
## About The Pull Request
This PR ports over the hairfre hair from Hyperstation

## How This Contributes To The Skyrat Roleplay Experience
Having more hairstyles doesn't hurt, especially if they are ones that people will use. This PR was a request from one of my friends

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

image

image

image

image

</details>

## Changelog

:cl:
image: adds the hairfre hairstyle from hyperstation
/:cl:

### CODE REVIEW

**Comment by lukevale** [comment]
one of the goats styles tbh

**Comment by tf-4** [comment]
Only tangentially related but god I fucking hate the hair selection menu so much 
It should really be reworked to make hairstyles actually findable before adding more (not that I'm saying you should do that for this pr)

**Comment by softcerv** [comment]
> Only tangentially related but god I fucking hate the hair selection menu so much It should really be reworked to make hairstyles actually findable before adding more (not that I'm saying you should do that for this pr)

Yeah, I agree that it would be better to have a search function for hair. (Or something to make the hair system more usable)

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
Could you just add a screenshot with like, red hair or something like that? It's hard to tell what the shading is for the NORTH orientation of the sprite, as opposed to the other ones, and I just want to see if it's a white thing or if it's going to be like that for every color.

**Comment by softcerv** [comment]
> Could you just add a screenshot with like, red hair or something like that? It's hard to tell what the shading is for the NORTH orientation of the sprite, as opposed to the other ones, and I just want to see if it's a white thing or if it's going to be like that for every color.

image

**Comment by Paxilmaniac** [comment]
Holy flat color batman

**Comment by lukevale** [comment]
> Holy flat color batman

it's not flat. It's that such a bright color makes it really hard to see the frankly EXTREMELY subtle shading. It can look nice. It's one of those, "if you don't notice it, it's doing it's job."

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
Yeah, I think the shading on the back is just too light, it's just as if it wasn't there at all. I had to squint really hard to notice anything, and it just feels very flat compared to the other directions of the sprite.

If you change the shading of the back part of the hair to be a bit more contrasted, then I'd be willing to go through with this.

**Review by GoldenAlpharex — APPROVED** [review]
Seems good now.

**Pull request merged**
