### PR TITLE
[MIRROR] replaces chaos holoparasite with gaseous holoparasite [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/72049
--------------------
## About The Pull Request
replaces chaos holopara with the gaseous holopara (if someone has a better name suggest it)
instead of the fire and hallucinations, it can now expel gas from itself, flooding an area with one of the following:
o2, n2, n2o, co2, h2o, bz or plasma
its punches cause sparks and it regulates the user's temperature and extinguishes them
https://streamable.com/leukv5

## Why It's Good For The Game
chaos holopara is very underwhelming, the hallucinations arent really that good and ss13 fires arent either, also there was no real theme tied around it, what do hallucinations and fire have in common?
this may be more fun and it plays more with the sandbox, lets see!

## Changelog
:cl: fikou
del: chaos holoparasite
add: gaseous holoparasite, it can expel various gases from its body and stabilizes the users temperature
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
I'm open to arguments in favour of it, but I am pretty sure we do not want plasmafires from this.

**Comment by Stonetear** [comment]
> I'm open to arguments in favour of it, but I am pretty sure we do not want plasmafires from this.

It's not exactly hard to create plasma fires already.

`var/static/list/possible_gases = list(`
`		/datum/gas/oxygen = 5,`
`		/datum/gas/nitrogen = 75, //yes 75 times. overpressurizing is hard!.`
`		/datum/gas/water_vapor = 0.1, //you need incredibly little water vapor for the effects to kick in`
`		/datum/gas/nitrous_oxide = 1.5,`
`		/datum/gas/carbon_dioxide = 5,`
`		/datum/gas/plasma = 0.25,`
`		/datum/gas/bz = 1,`
Here's the multipliers for the different gasses.  Not a lot of plasma is released at all, really.

If we're looking to replace plasma, I suggest either Halon, which extinguishes fires, or Freon, which burns those who breathe it as well as chilling the room it's in.

**Comment by despong** [comment]
alright guys today we're gonna make a tritium fire with a holopara

**Comment by W4rd3nn** [comment]
I wouldn't be opposed to the (relatively small) plasma fires this could create. Fighting fires really isn't an issue, especially so if atmos is relatively competent. It's also just fun, both for whoever started the fire and whoever is fighting it and putting it out. 

As for the dangers of it, it can be properly handled through the regular escalation rules.

I do not see the amount of plasma it puts out as being an issue considering it's really easy to just crank open a canister anywhere and get a better result. If anything, the plasma would be more of a hazard to the parasite's user than anything.

**Comment by Zonespace27** [comment]
We'll see how this goes, merge skew

**Review by Zonespace27 — APPROVED** [review]

**Pull request merged**
