### PR TITLE
[MODULAR] Adds a tiny icon for people with temporary flavor text.

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

Title. Adds a new global overlay, a check on living update_overlays, and updates overlays when the temporary flavor text verb is used.

## How This Contributes To The Skyrat Roleplay Experience

I rarely ever notice anyone's temporary flavor text despite it usually holding some importance to like, how they look. This will hopefully get people to examine people with temporary flavor text more and read it, since I myself pretty much never examine someone unless I feel I might gain something extra out of it.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

https://user-images.githubusercontent.com/59709059/212491439-b41d4c07-6869-45c6-8cb6-4c9020174083.mp4

I'd also show it being removed, but holy shit OBS makes MASSIVE files and I'm limited to 10 MB on github.
I tested adding it, removing it, deleting myself with it, hurting myself to trigger update icons, stripping, putting on clothes. All of them proved it worked decently.
</details>

## Changelog

:cl:
add: Temporary flavor text now adds a small overlay to your character.
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
I assume you've tested this with other hud icons e.g. weapons permits?

**Comment by nikothedude** [comment]
> I assume you've tested this with other hud icons e.g. weapons permits?

Honestly forgot weapon permits were there, I'll re-adjust the position if it gets weird

**Comment by nikothedude** [comment]
image

It works

**Review by tf-4 — APPROVED** [review]
Solid idea to promote an underused feature

**Pull request merged**
