### PR TITLE
Liquids system

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
This introduces a proper atmos-like system for liquids, including immutable liquids such as the ones you'd use for an ocean map.
The subsystem is very efficient, it's a hybrid of cell and group processing and uses various caching methods to be more efficient.

Spill a beaker over a tile, or rupture a tank to get some liquids on the ground, they'll even out across the surface as a puddle, and slip people. Or use a grenade without foam or smoke, just raw reagents to spill them down
If you get enough liquids in one tile (will require closing a room, or making a pool with metal sheets), depending on the volume they'll behave as you'd expect an ankle-high, or shoulder-high or cant-breath-high water would. High enough water will make falls harmless, and will constantly expose the people inside to the reagents by touch, any slips or falls will cause you to ingest some too. The higher the level, the slower it'll make you too
You can even do reactions in the puddles, throw some potassium into a pool and cause an explosion.
The puddles can be set on fire aswell, provided they're a good accelerant, such as welding fuel, alcohol, clf3 or napalm

Reinforced Tables and Sandbags provide a partial blockage against liquids. If a room is set on fire by a liquid puddle, get on an r table!

Engineers get a plumbing device that can be used to create input and output pumps that interact with on-tile liquids

How do you get rid of them?
Water evaporates by itself, aslong as its in a puddle.
Use a mop, then right click a bucket to squeeze the liquids out.
If a water is not the most shallow puddle possible, you can also scoop it out by a beaker, or other containers
There's also a portable liquid pump you can find, functions similarly to the porta scrubber

## Changelog
:cl:
add: Added a liquids system, which includes a lot of changes. See https://github.com/Skyrat-SS13/Skyrat-tg/pull/4584
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
OH SHIT, YO? THIS LOOKS SICK.

**Comment by GoldenAlpharex** [comment]
This would be really freaking sweet, if it's actually a serious PR and that it is what I think it is.

**Comment by Oscari-pog** [comment]
Oh my god you didnt

**Comment by NullDagaf** [comment]
PLEASE MAKE THE CHANGELOG PROPER OR DON'T AT ALL
THE PR CAN STAY RETARDED BUT I DON'T WANT A WALL OF CHANGES NOT DESCRIBING ANYTHING
AND YOU DON'T WANT YOUR GBP TANKED

**Comment by GoldenAlpharex** [comment]
A definition of what's going on and the core mechanics of this new liquids feature would be nice.

**Comment by Owai-Seek** [comment]
I don't know if this is gonna stick around or not, but if it does, and it's the one that adds floor liquids...

Scooping liquids into a beaker is infinitely easier than mopping them up, which seems a bit silly.

Once scooped, you can't really dump them anywhere unless you take it directly to the recycler. (Dropping a beaker down disposals just sends the mess to cargo.)

People can't seem to figure out how to squeeze reagents out mops, so they just, mop up the fluids, and then wipe them off on the same floor they just mopped dry. Which seems to just, delete the reagents.

**Comment by Azarak** [comment]
> 
> 
> PLEASE MAKE THE CHANGELOG PROPER OR DON'T AT ALL
> THE PR CAN STAY RETARDED BUT I DON'T WANT A WALL OF CHANGES NOT DESCRIBING ANYTHING
> AND YOU DON'T WANT YOUR GBP TANKED

imagine caring about imaginary points

**Comment by Azarak** [comment]
> 
> 
> I don't know if this is gonna stick around or not, but if it does, and it's the one that adds floor liquids...
> 
> Scooping liquids into a beaker is infinitely easier than mopping them up, which seems a bit silly.
> 
> Once scooped, you can't really dump them anywhere unless you take it directly to the recycler. (Dropping a beaker down disposals just sends the mess to cargo.)
> 
> People can't seem to figure out how to squeeze reagents out mops, so they just, mop up the fluids, and then wipe them off on the same floor they just mopped dry. Which seems to just, delete the reagents.

Changed so mops can hold more and you can squeeze them into buckets, and beakers require somewhat of a height to the liquid in order to be able to use them well.

**Comment by gonenoculer5** [comment]
So, one thing I wanna note on this is that the water maps, (such as water Kilo) do not work right with the supermatter. The spaceloop (waterloop now I guess) isnt stable enough to run the SM on for longer than about five or six minutes when me and some other engineers tested it on the first public test. not sure if this is that PR or not. I assume the intended way to do this is to watercool the SM like a fucking gaming PC rig with the plumbing constructor? If you intend us to do this, why include a spaceloop at all, out of curiousity.

Thanks.

**Comment by Azarak** [comment]
> 
> 
> So, one thing I wanna note on this is that the water maps, (such as water Kilo) do not work right with the supermatter. The spaceloop (waterloop now I guess) isnt stable enough to run the SM on for longer than about five or six minutes when me and some other engineers tested it on the first public test. not sure if this is that PR or not. I assume the intended way to do this is to watercool the SM like a fucking gaming PC rig with the plumbing constructor? If you intend us to do this, why include a spaceloop at all, out of curiousity.
> 
> Thanks.

HE pipes exchange heat with the liquids, it should work

**Comment by Gandalf2k15** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/4695

**Comment by FlamingLily** [comment]
Ok, so, currently the flammable liquids system is literally unfightable. The way liquids igniting works is "all at once", so pushing back a fire with extinguishers is physically impossible.

Now, I know what you're thinking. "Liquid fires shouldn't be extinguished with standard extinguishers" and to that I say "I wholly agree, **but** there is no other way *to* fight them at the current time"

**Comment by GoldenAlpharex** [comment]
image
There, an image of liquid overlays being quite visibly broken. It's under the tram, and yet appears on top of it.

**Comment by Azarak** [comment]
> 
> 
> image
> There, an image of liquid overlays being quite visibly broken. It's under the tram, and yet appears on top of it.

that's an issue with all vis overlays

**Comment by Azarak** [comment]
> 
> 
> Ok, so, currently the flammable liquids system is literally unfightable. The way liquids igniting works is "all at once", so pushing back a fire with extinguishers is physically impossible.
> 
> Now, I know what you're thinking. "Liquid fires shouldn't be extinguished with standard extinguishers" and to that I say "I wholly agree, **but** there is no other way _to_ fight them at the current time"

No that was just a bug, it should be fixed now

**Comment by Low3** [comment]
cum lake

**Comment by hugmeorelse** [comment]
Bump

**Comment by unit0016** [comment]
Please keep up the work Azarak, this was honestly one of ~~the best optimized liquid systems~~ the funnest additions we've had tbh.

**Comment by Gandalf2k15** [comment]
Let's see something here.

**Comment by Gandalf2k15** [comment]
Executive decision; Merge it.

**Pull request merged**
