### PR TITLE
Guaranteed ashwalker nest spawn

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Make ashwalkers great again. They'll spawn in every round from now on! No more *Observe>GhostSpawnersList>Respawn* checks right after roundstart!

## Why It's Good For The Game

More ghostroles. Also, people really do love them c: 
Possibility of their spawn was too low (cost 20 omg)

## Changelog
:cl:
balance: Ashwalker nest will spawn always now
/:cl:

### CODE REVIEW

**Comment by SpaceVampire** [comment]
I really don't think every single shift needs to have Ash-walkers.
It should be the same as all the other ghost-roles, which are already too bloated.

**Comment by Draganfrukts** [comment]
hehe libards

**Comment by NullDagaf** [comment]
Or.. you could instead map in a proper ashwalker base?

**Comment by NullDagaf** [comment]
Also, uh.
### **_ADD YOUR SKYRAT EDIT COMMENTS_**

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
follow modularisation guidelines
this will be closed in 24h if no updates, you can always request it re-opened if you miss this.

**Comment by KathrinBailey** [comment]
Not complaint with modularisation guidelines and failed to respond in a timely manner.

**Pull request closed without merging**
