### PR TITLE
[MODULAR] Security headwear armor rebalance and consistency fix

### PR DESCRIPTION
**Pull request by Gyrandola**
## About The Pull Request

This PR rebalances and standardizes the armor values of all security fabric headwear, while also fixing the fact that some caps had no armor values at all, so that they are:
1) Consistent
2) Not as strong/stronger than helmets

<details>
<summary>Click here for details</summary>
== Old values ==

**garrison cap / security cap**
melee III
bullet II.5
laser II.5
energy II.5
bomb II.5
fire II
acid V

**sec beret**
melee III.5
bullet III
laser III
energy IV
bomb II.5
fire II
acid V
wound IV

**sol police cap / sol traffic cop cap / sec ushanka**
No armor values

== New values - Standardized for every mentioned head piece ==

melee III
bullet II
laser II
energy II
bomb I
fire II
acid II
wound I
</details>

As of 06/06, I've also standardized every Warden and HoS headwear piece, without rebalancing their armor values.

## How This Contributes To The Skyrat Roleplay Experience

The standardization of the armor values allows security officers to pick their favorite cap without worrying that one may be stronger than the other, thus favoring roleplay over meta.

The overall rebalance (or nerf, I guess) of the armor values themselves serves as a way to encourage the use of helmets DURING ALERTS. What I mean is that obviously a beret shouldnt be in any way comparable to a proper helmet, but at the same time, nobody wants secoffs to exclusively use helmets when there's no need to simply because they're stronger. 

So, if that becomes an issue I'm sure the sec policy/corpregs could be changed to disallow the use of helmets during green/blue alert. Policy committee be praised.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

Screenshot 2023-06-04 163912

Screenshot 2023-06-06 132901

</details>

## Changelog

:cl: Gyran
balance: rebalanced and standardized the armor values of all security caps to be the same, even those that previously had no armor at all.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Name the datum something else because its too easy to confuse with "head of security"

**Comment by RatFromTheJungle** [comment]
Giving them all the same armor is a nice-change, but,
Making the rest of the headgear flatly worse then the helmet armor wise is an extremely-odd choice, considering the helmets were already flatly better beforehand, and seems to do nothing but just flatly punish you for not rocking the helmet 24/7

**Comment by Gyrandola** [comment]
> Giving them all the same armor is a nice-change, but, Making the rest of the headgear flatly worse then the helmet armor wise is an extremely-odd choice, considering the helmets were already flatly better beforehand, and seems to do nothing but just flatly punish you for not rocking the helmet 24/7

I believe it just isn't normal that the beret and the helmet have the same Melee protection level. (for example)

**Comment by nikothedude** [comment]
Im gonna say it again, as was stated on the discord, that berets and stuff were, and still are, treated as alternate drip for security officers. "It not being normal" or "It not feeling right" are really weak arguments on their own.

**Comment by Gyrandola** [comment]
> Im gonna say it again, as was stated on the discord, that berets and stuff were, and still are, treated as alternate drip for security officers. "It not being normal" or "It not feeling right" are really weak arguments on their own. 

I believe you telling me with a straight face that a beret and a helmet should have the same protection class is a weak argument.

There's a reasonable limit to the rule of cool.

**Comment by YakumoChen** [comment]
can see where you're coming from but it's absolutely consistent with the Captain, Warden, and Head of Security which do not have helmet options and are not considered out of place (most of which have better armour than secoffs can get in general)

**Comment by Gyrandola** [comment]
> can see where you're coming from but it's absolutely consistent with the Captain, Warden, and Head of Security which do not have helmet options and are not considered out of place (most of which have better armour than secoffs can get in general)

Speaking of which, I'm standardizing the head of security caps aswell but without really altering their armor values, which brings me to the point of this answer: I think Command having high armor values on clothing is fine, because they dont really have the option to put on real armor or helmets (and they shouldn't), and the importance of their role warrants this "exception".

**Comment by YakumoChen** [comment]
Should modularly do the same with detective hats, oranges seems particularly keen on preventing it upstream

**Comment by Gyrandola** [comment]
> Should modularly do the same with detective hats, oranges seems particularly keen on preventing it upstream

Seems the unique detective hats have the same stats, it's just that the Det vendor lets you buy a bunch of normal fedoras. I would have to make them a subtype.

**Review by tf-4 — APPROVED** [review]

**Pull request merged**
