### PR TITLE
Mirrors #72354

### PR DESCRIPTION
**Pull request by Zonespace27**
https://github.com/tgstation/tgstation/pull/72354
Closes https://github.com/Skyrat-SS13/Skyrat-tg/pull/18418

### CODE REVIEW

**Comment by Tastyfish** [comment]
@Zonespace27 Just quickly looking at a basic `^/datum/armor/` find in files grep, modular_skyrat has several duplicated armor paths as well, many of which have different values. Couple of examples where the definitions are different include `/datum/armor/centcom_formal_nt_consultant` and `/datum/armor/plasmaman_blueshield`. There are several that are just identical though. I'm not gonna bother trying to make that C# code work since I imagine it doesn't check if they're actually different.

**Comment by Tastyfish** [comment]
I reproduced the C# code with a one-line bash command:
`grep -nr "^/datum/armor/" modular_skyrat | sed "s/:/ /g" | sort -k3 | uniq --all-repeated=separate -f2`

The result is as follows:
```log
--- File - Line - type
modular_skyrat/modules/gladiator/code/game/objects/items/gladiator_items.dm 55 /datum/armor/berserker_gatsu
modular_skyrat/modules/gladiator/code/game/objects/items/gladiator_items.dm 80 /datum/armor/berserker_gatsu

modular_skyrat/modules/nanotrasen_rep/code/clothing.dm 54 /datum/armor/centcom_formal_nt_consultant
modular_skyrat/modules/nanotrasen_rep/code/clothing.dm 67 /datum/armor/centcom_formal_nt_consultant

modular_skyrat/modules/novaya_ert/code/head.dm 122 /datum/armor/hev_suit_nri
modular_skyrat/modules/novaya_ert/code/suit.dm 161 /datum/armor/hev_suit_nri

modular_skyrat/modules/hev_suit/code/hev_suit.dm 818 /datum/armor/hev_suit_pcv
modular_skyrat/modules/hev_suit/code/hev_suit.dm 910 /datum/armor/hev_suit_pcv

modular_skyrat/modules/SEVA_suit/code/seva_obj.dm 22 /datum/armor/hooded_seva
modular_skyrat/modules/SEVA_suit/code/seva_obj.dm 50 /datum/armor/hooded_seva

modular_skyrat/modules/blueshield/code/blueshield_clothing.dm 44 /datum/armor/plasmaman_blueshield
modular_skyrat/modules/blueshield/code/blueshield_clothing.dm 64 /datum/armor/plasmaman_blueshield

modular_skyrat/modules/medievalcrate_skyrat/code/vintageitems.dm 25 /datum/armor/plate_larp
modular_skyrat/modules/medievalcrate_skyrat/code/vintageitems.dm 6 /datum/armor/plate_larp

modular_skyrat/modules/emergency_spacesuit/code/emergency_spacesuit.dm 24 /datum/armor/space_emergency
modular_skyrat/modules/emergency_spacesuit/code/emergency_spacesuit.dm 77 /datum/armor/space_emergency

modular_skyrat/modules/hev_suit/code/hev_suit.dm 179 /datum/armor/space_hev_suit
modular_skyrat/modules/hev_suit/code/hev_suit.dm 54 /datum/armor/space_hev_suit

modular_skyrat/master_files/code/modules/clothing/under/jobs/cargo.dm 28 /datum/armor/utility_syndicate
modular_skyrat/master_files/code/modules/clothing/under/jobs/command.dm 120 /datum/armor/utility_syndicate
modular_skyrat/master_files/code/modules/clothing/under/jobs/engineering.dm 28 /datum/armor/utility_syndicate
modular_skyrat/master_files/code/modules/clothing/under/jobs/medical.dm 46 /datum/armor/utility_syndicate
modular_skyrat/master_files/code/modules/clothing/under/jobs/rnd.dm 33 /datum/armor/utility_syndicate
modular_skyrat/master_files/code/modules/clothing/under/misc.dm 59 /datum/armor/utility_syndicate
```

**Comment by Zonespace27** [comment]
> \<snip\>

Thanks for running that

**Review by GoldenAlpharex — APPROVED** [review]
Looks good!

**Pull request merged**
