### PR TITLE
[NONMODULAR] [CI FIX (FUCK)] Update lighting.dm

### PR DESCRIPTION
**Pull request by lyricalpaws**
## About The Pull Request
Fixes ci failing because of a lighting change that we didn't get

## How This Contributes To The Skyrat Roleplay Experience
Code actually works now

## Changelog

:cl:
fix: `attack_obj -> attack_atom` ci fix
/:cl:

### CODE REVIEW

**Comment by lyricalpaws** [comment]
Bandaid fix til I can make lighting.dm in to a folder ala tgcode (hopefully later today)

**Comment by GoldenAlpharex** [comment]
> Bandaid fix til I can make lighting.dm in to a folder ala tgcode (hopefully later today)

I'll fix it in my lighting fix already. ;)

**Comment by lyricalpaws** [comment]
> 
> 
> > Bandaid fix til I can make lighting.dm in to a folder ala tgcode (hopefully later today)
> 
> I'll fix it in my lighting fix already. ;)

How long til it arrives

**Comment by GoldenAlpharex** [comment]
> > > Bandaid fix til I can make lighting.dm in to a folder ala tgcode (hopefully later today)
> > 
> > 
> > I'll fix it in my lighting fix already. ;)
> 
> How long til it arrives

I'll finish it when I'm home today. It's already up #8063

**Comment by lyricalpaws** [comment]
> > > > Bandaid fix til I can make lighting.dm in to a folder ala tgcode (hopefully later today)
> > > 
> > > 
> > > I'll fix it in my lighting fix already. ;)
> > 
> > 
> > How long til it arrives
> 
> I'll finish it when I'm home today. It's already up #8063

Sweet

**Pull request closed without merging**
