### PR TITLE
[MIRROR] SPECIES NUKING 2023: Makes tongues handle liked/disliked food instead of species datum [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/76204
--------------------
## About The Pull Request

Alright, let's get real, handling food tastes with the species datum is hacky at best - This is a continuation of my nuking of the species datum, which currently handles way too much of human mobs' behaviors. 

While moving that to the tongue isn't exactly a perfect solution, it allows for more interesting behavior than the species datum, especially now that I added getter procs to get foodtypes liked/disliked by the mob and such.

Closes https://github.com/Skyrat-SS13/Skyrat-tg/pull/22137, https://github.com/Skyrat-SS13/Skyrat-tg/pull/22251 (as I added them to this PR)

## Why It's Good For The Game

Makes tongue transplants more appealing and emergent, since they fully control tastes and not just taste sensitivity which is pretty much cosmetic.

## Changelog

:cl:
refactor: Liking/disliking food is now handled by the tongue organ, not the species. Also, having a failing tongue means you can't taste food properly!
add: You can read peoples' tongues now, if you have the entrail reading skillchip.
fix: fixed food preferences displaying incorrectly when examining tongues
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
This is going to need a workaround if we're going to continue to use tongues more for roleplay purposes like we do

**Comment by Namwty** [comment]
I wonder if I can replace my tongue in real life so I can suddenly like mushrooms 👍

**Comment by vinylspiders** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/22137 hotfix to go with this

**Review by GoldenAlpharex — APPROVED** [review]
Should be good to go now!

**Pull request merged**
