### PR TITLE
[MODULAR] magic wand refactor: the mystery of the disappearing wand.

### PR DESCRIPTION
**Pull request by softcerv**
## About The Pull Request
Refactors a majority of the magic wand code. Additionally, this PR fixes several bugs with magic wands, the most prevelant being the wands disappearing when set to high.

## How This Contributes To The Skyrat Roleplay Experience
Less technical debt and bugfixes are a positive thing for roleplay.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

image

</details>

## Changelog

:cl:
refactor: refactors magical wand code, fixing several bugs.
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
You should take this upstream, wands are tg code.

**Comment by softcerv** [comment]
> You should take this upstream, wands are tg code.

These are special skyrat wands. (Too powerful for TG)

**Comment by nikothedude** [comment]
> You should take this upstream, wands are tg code.

i was about  to say the same thing until i viewed files changed

**Comment by Gandalf2k15** [comment]
expelliarmus

**Pull request merged**
