### PR TITLE
Removes flag that had Hemophages use skin tone dropdown and give them mutant colors instead

### PR DESCRIPTION
**Pull request by FearfulFurnishing**
## About The Pull Request

Remove the use_skintones flag from Hemophage species.

Give Hemophage species the TRAIT_MUTANT_COLORS inherited trait for skin color customization available to other species. Also alphabetized their inherited traits list for cleanliness.

## How This Contributes To The Skyrat Roleplay Experience

Saw this in development-suggest discord channel and separately had a player of the species bring it up to me. Mutant coloring allows greater character customization than using a preset skin color and augments to try to get a preferred appearance.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

https://github.com/Skyrat-SS13/Skyrat-tg/assets/139661819/31f1d73b-f833-407a-bf30-37276471882b

</details>

Verified skin tone drop down menu no longer present when in character customizer for a Hemophage. 

Changed Hemophage first mutant color and confirmed it altered skin tone. 

Spawned into private server as a Hemophage and verified mutant color was used for skin color.

## Changelog

:cl:
tweak : Hemophages now set skin color based on mutant color instead of preset skin tone drop down menu.
/:cl:

### CODE REVIEW

**Comment by EpicCharger** [comment]
As the hemophage player that talked to them about this, I would love mutant color options.

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
I'm going to put a Do Not Merge on this because, one, it's about to conflict with a mirror (not your fault), and two, I'd rather we implement something like this in a smarter way, where we give people the option to use skin tones or not.

This would be the exact opposite of a QoL for everyone that _does_ use skintones as Hemophages, so I'd rather avoid that if I can, and have an actual pref option that allows you to swap between the two.

**Comment by GoldenAlpharex** [comment]
If you need some pointers as to how to do this, just poke me in the dev channels, it shouldn't be too difficult. It'd just be messing around with traits some more, alongside preferences.

**Comment by FearfulFurnishing** [comment]
I'm going to close this request for now, appreciate the feedback and assistance received here and in the discord. For now I'm lacking on time and experience to devote to getting a trait adjusting preference properly working without introducing potential bugs. May make a second attempt at this sometime in the future after tackling more basic things first. 

Some points on outstanding issues (take these with a grain of salt please, DM language is a new beast to me still) in case someone attempts something similiar:

- the target apply_to_human directive of a preference seemed to be called with has a reference to the previously selected species, not the species selected to which makes it inaccurate to know whether a species needs new traits added to it on the fly or not
- the skin_tone preference itself relies on a character having an inherent_trait, not just having a trait in general. Making skin_tone rely on the HAS_TRAIT directive would fix that but would require an upstream change request.
- whether a saved slot was or was not using preset skin tones when available as an optional feature wasn't being respected properly when loading a saved character. This is probably connected to the first point.

**Pull request closed without merging**
