### PR TITLE
[MIRROR] You can now tip borgs over [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/64097

### CODE REVIEW

**Comment by axietheaxolotl** [comment]
finally, a good PR

**Comment by softcerv** [comment]
Thank god, a way to deal with shitty borg players without having to worry about being ahelped.

**Comment by desertmote** [comment]
Need to revert some [stuff](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10667) first, bear with me...

**Comment by AsaiasWolffe** [comment]
yikes

**Comment by AsaiasWolffe** [comment]
> I hate Silicon

>Teaches Silicon that they should still live within the Crew rather than above them, otherwise people will tip you over and no one would want to help tip you back up.

if this is the direction SR is going then im happy i got out when i did

**Comment by GoldenAlpharex** [comment]
> > I hate Silicon
> 
> > Teaches Silicon that they should still live within the Crew rather than above them, otherwise people will tip you over and no one would want to help tip you back up.
> 
> if this is the direction SR is going then im happy i got out when i did

Brother, this is a mirror PR.

**Review by GoldenAlpharex — APPROVED** [review]
Looks like it'll work.

**Comment by CypressBz** [comment]
Hah, yeah. Nah, I've been looking for a reason to leave, this is it. This is a joke. 😂

**Pull request merged**
