### PR TITLE
[fix][modular][ready](hopefully) Fixes dogborg deathsprites not showing

### LINKED ISSUE #5739: Cyborg defeat state not triggering
## Reproduction: Destory a cyborg and you will see it go into a static stand and do not show its destroyed state.

The cyborgs and robots have defeat sprite animations. and should be restored.

wreck

### PR DESCRIPTION
**Pull request by thestubborn**
## About The Pull Request

title

fixes Fixes #5739

## Why It's Good For The Game

someone asked for it, and while i don't like dogborgs, I'm also not a massive dick, so i thought i'd fix it

## Changelog
i cannot do a proper changelog because I'm at a perfect -69

### CODE REVIEW

**Comment by Sonic121x** [comment]
modular_skyrat/modules/altborgs/code/modules/mob/living/silicon/robot/update_icons.dm

I think this is what causeing the snowflake death sprite not showing correctly
```
if(robot_resting)
		if(stat != DEAD && model.dogborg)
			switch(robot_resting)
				if(ROBOT_REST_NORMAL)
					icon_state = "[model.cyborg_base_icon]-rest"
				if(ROBOT_REST_SITTING)
					icon_state = "[model.cyborg_base_icon]-sit"
				if(ROBOT_REST_BELLY_UP)
					icon_state = "[model.cyborg_base_icon]-bellyup"
				else
					icon_state = "[model.cyborg_base_icon]"
			cut_overlays()
	else
		icon_state = "[model.cyborg_base_icon]"
```
the icon_state keep getting reset

**Comment by thestubborn** [comment]
> 
> 
> modular_skyrat/modules/altborgs/code/modules/mob/living/silicon/robot/update_icons.dm
> 
> I think this is what causeing the snowflake death sprite not showing correctly
> 
> ```
> if(robot_resting)
> 		if(stat != DEAD && model.dogborg)
> 			switch(robot_resting)
> 				if(ROBOT_REST_NORMAL)
> 					icon_state = "[model.cyborg_base_icon]-rest"
> 				if(ROBOT_REST_SITTING)
> 					icon_state = "[model.cyborg_base_icon]-sit"
> 				if(ROBOT_REST_BELLY_UP)
> 					icon_state = "[model.cyborg_base_icon]-bellyup"
> 				else
> 					icon_state = "[model.cyborg_base_icon]"
> 			cut_overlays()
> 	else
> 		icon_state = "[model.cyborg_base_icon]"
> ```
> 
> the icon_state keep getting reset

so just delete that shit or?

**Comment by Sonic121x** [comment]
move the dead sprite check after that part should be able to fix it.
```
	if(stat == DEAD && model.has_snowflake_deadsprite)
		icon_state = "[model.cyborg_base_icon]-wreck"
```

**Comment by thestubborn** [comment]
> 
> 
> move the dead sprite check after that part should be able to fix it.
> 
> ```
> 	if(stat == DEAD && model.has_snowflake_deadsprite)
> 		icon_state = "[model.cyborg_base_icon]-wreck"
> ```

will do

**Comment by Sonic121x** [comment]
wait... i mean it like this
```
	if(robot_resting)
		if(stat != DEAD && model.dogborg)
			switch(robot_resting)
				if(ROBOT_REST_NORMAL)
					icon_state = "[model.cyborg_base_icon]-rest"
				if(ROBOT_REST_SITTING)
					icon_state = "[model.cyborg_base_icon]-sit"
				if(ROBOT_REST_BELLY_UP)
					icon_state = "[model.cyborg_base_icon]-bellyup"
				else
					icon_state = "[model.cyborg_base_icon]"
			cut_overlays()
	else
		icon_state = "[model.cyborg_base_icon]"

	if(stat == DEAD && model.has_snowflake_deadsprite)
		icon_state = "[model.cyborg_base_icon]-wreck"

	update_fire()
```

**Comment by Strazyplus** [comment]
Fixes #5739

**Comment by Funce** [comment]
Add above comment to your PR description to link the issue, and I'll merge

**Comment by Funce** [comment]
And also, funny numbers don't mean anything. One day I'll have the changelog working, this isn't for posterity :angery:

**Review by Funce — CHANGES_REQUESTED** [review]
Above

**Comment by thestubborn** [comment]
> 
> 
> Above

on it

**Review by Funce — APPROVED** [review]

**Comment by Strazyplus** [comment]
Sorry this did not fix it!

https://i.imgur.com/sG31vjl.png (assuming its merged and we had two hard restarts today alone.)

**Pull request merged**
