### PR TITLE
doubles the wizard starting spell points 

### PR DESCRIPTION
**Pull request by Elli-Skala**
## About The Pull Request

Gives the wizards 20 starting spell points to be in line with other antag's double power

## Why It's Good For The Game

helps wizards some what fight against our buffed security using the same changes as other antags

## Changelog
balance:  wizard starts with 20 spell points 
/:cl:

### CODE REVIEW

**Comment by Swiftfeather** [comment]
Amazing, I totally felt that our wizards were very underpowered due to sec buffs, this will even the playing field more and all the future wizard rounds after this comes out will be much more interesting

**Comment by SpaceVampire** [comment]
I unironically support this PR.

**Comment by SarmentiCampbell** [comment]
this will be very helpful, yes

**Comment by Cheshify** [comment]
We have Wizards?

**Comment by Oscari-pog** [comment]
We dont have wizards, but in case they are enabled, or a admin runs a event, they wont get memed on by rubbers anymore.

**Comment by Gandalf2k15** [comment]
We don't have wizards right now, if we ever get them, we can look into buffing them if we need to.

**Pull request closed without merging**
