### PR TITLE
Engines: Return of the Singularity(and tesla)

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

This simply readds the routes for singularity engine generation as well as the tesla. 

PA is back ofc.
image

image

image

Sprites from TauCeti! God I love those guys.

## Changelog
:cl:
add: Readded the singularity engine generator, tesla generator and particle accelerator. All available from your cargo department.
/:cl:

### CODE REVIEW

**Comment by DuffCreeper** [comment]
WOOOOOOOOOOO

**Comment by GoldenAlpharex** [comment]
Uhm.

**Comment by Gandalf2k15** [comment]
> Uhm.

Uhm what

**Comment by GoldenAlpharex** [comment]
> > Uhm.
> 
> Uhm what

As much as I like those engines, I don't really miss the round ending because yet another person accidentally let them go loose.

**Comment by Gandalf2k15** [comment]
> > > Uhm.
> > 
> > 
> > Uhm what
> 
> As much as I like those engines, I don't really miss the round ending because yet another person accidentally let them go loose.

We're back to SS13 baby!

**Comment by GoldenAlpharex** [comment]
> > > > Uhm.
> > > 
> > > 
> > > Uhm what
> > 
> > 
> > As much as I like those engines, I don't really miss the round ending because yet another person accidentally let them go loose.
> 
> We're back to SS13 baby!

I mean, for the action server, sure, but... I don't know, I've never been a fan of the round ending for everyone because one person decided to do a funny engine and not take care of it.

**Comment by FlamingLily** [comment]
> 
> 
> > > Uhm.
> > 
> > 
> > Uhm what
> 
> As much as I like those engines, I don't really miss the round ending because yet another person accidentally let them go loose.

~~as if the SM doesn't do that~~

Admins can, if it's a 5 minute loose, just do something like what paradise does and *delete* if they wanna

**Comment by Gandalf2k15** [comment]
Also you have to be a literal ape to cause a singuloose

**Comment by GoldenAlpharex** [comment]
> Also you have to be a literal ape to cause a singuloose

Oh, I know, but... Yet it seems to happen every single time, from my experience. I've only seen... Very few singularities/teslas that didn't cause the shuttle call for one reason or the other.

**Comment by FlamingLily** [comment]
@gonenoculer5 says to ~~port~~ recreate the singulo-buster rocket from goonstation and fuck yeah please do

**Comment by Gandalf2k15** [comment]
> > Also you have to be a literal ape to cause a singuloose
> 
> Oh, I know, but... Yet it seems to happen every single time, from my experience. I've only seen... Very few singularities/teslas that didn't cause the shuttle call for one reason or the other.

You realise we haven't actually had a singularity engine on the current base? Meaning we haven't had one for over 6 months.

**Comment by Arctaisia** [comment]
Love the singulo sprites, though not sure if I really like the particle accelerator's one, the black outline makes it feel old, and the lack of detail makes it seem out of place.

**Comment by werewolfboyfriend** [comment]
those PA sprites look like a toothbrush

**Comment by ORCACommander** [comment]
Hail lord singuloth

**Comment by FlamingLily** [comment]
Ye PA sprite is a bit dumb looking from the images

**Comment by Gandalf2k15** [comment]
> Ye PA sprite is a bit dumb looking from the images

been updated, dw

**Comment by gonenoculer5** [comment]
singulo buster rocket when

**Comment by Gandalf2k15** [comment]
Fucking merge conflicts. Can someone add the basic setup equipment to the maps after this is FM'd?

**Comment by softcerv** [comment]
Would it also be possible to get the TEG too?

**Pull request merged**
