### PR TITLE
[READY] Fixes blood and damage overlays for taur suits

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
inventory.dm had to be moved because of compile order

## Changelog
:cl:
fix: Fixes blood and damage overlays for taur suits
/:cl:

### CODE REVIEW

**Comment by Low3** [comment]
epic

**Comment by KasparoVy** [comment]
Wait what there were taur suits? HELL YEAH BROTHER

**Comment by Low3** [comment]
> Wait what there were taur suits? HELL YEAH BROTHER

Nah, it's just if you wear outer stuff as taur and get covered in blood, blood overlay was a tile away from you.

**Comment by KasparoVy** [comment]
Aha, I see-- I remember something like that a couple days ago and wasn't sure what was going down there. Thanks for explaining

Them offsets

**Comment by Azarak** [comment]
I should probably do the same for the damaged overlay, I forgot about it

**Comment by atakiya** [comment]
AAAAAAAAAA use drafts for WIPs 🗞️

**Review by atakiya — APPROVED** [review]

**Pull request merged**
