### PR TITLE
[MODULAR] Adds bosco and lloyd borgs

### PR DESCRIPTION
**Pull request by linnpap**
## About The Pull Request
Adds a new miner borg skin and a service borg skin, Bosco and Lloyd.
image
image

## How This Contributes To The Skyrat Roleplay Experience
More borg skins are always nice.

## Changelog

:cl:
add: Added Bosco and Lloyd borg skins
/:cl:

### CODE REVIEW

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
Way too tiny. I already dislike the PK ball borg

**Review by tf-4 — CHANGES_REQUESTED** [review]
That is WAY too small

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
Cute idea, but those sprites are simply waaaay too small for a cyborg. If it was a drone, at the limit, that could possibly pass, but even then, it's very small.

Yes, I know it's from Deep Rock Galactic, and I know that making them bigger wouldn't really look nice. That doesn't change how it is.

**Comment by Tbowes-dev** [comment]
Try your best to make the sprites more bigger, Know a number of people would love to see the work and it be a shame if they got refused because its too small for combat.

Or you could make them a skin for the maintenance drones some regularly play and make a bigger version down the line for cyborgs.

**Comment by tf-4** [comment]
A maintenance drone skin would work here.

**Comment by mel-byond** [comment]
I like the idea of having a APD-B317 as drone, I mean, APD stands for All-purpose Drone anyway

**Pull request closed without merging**
