### PR TITLE
Adds tail wagging animation for servelyn tails

### PR DESCRIPTION
**Pull request by Z0w0plankton**
## About The Pull Request

Adds a missing tail wag animation for the servelyn tails

## How This Contributes To The Skyrat Roleplay Experience

More tail wagging is good!

## Proof of Testing

<details>

dreamseeker_PaVEP4P2mo

<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
imageadd: Wagging animation for Servelyn tails
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
You need to make sure that you post your proof of testing content `<after this>` with a space, else the embed won't work properly. I fixed this for you.

**Comment by GoldenAlpharex** [comment]
The wagging feels like it could use being slowed down a bit.

**Comment by Z0w0plankton** [comment]
> The wagging feels like it could use being slowed down a bit
Slowed down the wagging from front and back  here:

dreamseeker_IvEff3yL4k

**Review by tf-4 — APPROVED** [review]
Code is fine

**Review by Ebin-Halcyon — APPROVED** [review]
They're fine enough.

**Pull request merged**
