### PR TITLE
[SEMI-MODULAR] Nanotrasen Radio and TV

### PR DESCRIPTION
**Pull request by twilightwanderer**
## About The Pull Request

Have you ever wanted to be a screen star? Or better yet, the showrunner who makes those stars? I'm afraid I can't help you with that. But at the very least, I can make sure you get a taste of this wonderful world. Meet the radio and television system at our lovely station!

изображение

Would you like to interview syndicate operatives? You're welcome! Do you want to do a cooking show with the cooking of Pun-Pun's tail? Tell us about it! Tell you how to survive in prison? I'll write it down! Plunge into the wonderful world of crazy TV shows with Dmitry Nagiev with the new Radio and Television system. 

P.S. I originally developed this system exclusively for [Alliance Station](https://github.com/twilightwanderer/Alliance-Station). But since I mostly play the Skyrat build, I decided to adapt it for you as well.

## How This Contributes To The Skyrat Roleplay Experience

How does it work?

Have you probably noticed the weird monitors in the bar and elsewhere that broadcast rarely and on very big holidays how some rude guys beat each other up? Well, they're working again, and they're even broadcasting something! 

dreamseeker_9Jc169TNCD

dreamseeker_OypR46cI9c

These screens, allow you to watch and listen to live broadcasts. For a more classic way to get information, there is a separate radio and radio receivers.

n73UcTROxu

You can broadcast and broadcast from the studio, or you can use a special assistant drone and broadcast from any corner of the station or the whole galaxy! 

dreamseeker_6uXDN6hA0L

k6jm7oumkN

Studio on icebox:

изображение

Studio on tram:

изображение

Studio on delta:

изображение

Studio on meta:

изображение

## Changelog

:cl:
add: Nanotrasen Radio and TV system
/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
Drafting since this doesn't seem to be done yet, good work though 👍

**Comment by Gandalf2k15** [comment]
Oh this is cool as fuck

**Comment by twilightwanderer** [comment]
Made studios for the main maps with the exception of Kilo and Blueshift. In the case of Kilo I don't even know where to fit the studio, and for Blueshift its developer is sure to make a studio much better than me.

**Comment by SpaceVampire** [comment]
This seems like the kind of thing that could be done upstream instead of here.
Would make having to maintain the maps less of a hassle for starters.
Know we have some new tools for it, but still.

**Comment by twilightwanderer** [comment]
> This seems like the kind of thing that could be done upstream instead of here. Would make having to maintain the maps less of a hassle for starters. Know we have some new tools for it, but still.

I understand, but I don't really want to work with TG after a couple of unpleasant incidents. And I very much doubt, based on the specifics of gameplay, that such an innovation will be included in TG.

**Review by tf-4 — CHANGES_REQUESTED** [review]
Make the 'PDAs' use GAGS rather than 30 icon states pls

**Comment by twilightwanderer** [comment]
> Make the 'PDAs' use GAGS rather than 30 icon states pls

These PDAs were not originally prepared for this system. To make it work, you have to prepare ~15 templates instead of 30 normal sprites. I don't want to do that monkey's work, so I'll limit myself to one standard one.

**Comment by tf-4** [comment]
Alright, up to you.

**Comment by twilightwanderer** [comment]
I'm reopening the PR because a group of people find it useful. I don't think so.

**Comment by TetrakoHateThis** [comment]
Just to provide the player/RP insight, this is actually a super cool idea that I pray doesn't fall ill. It has the potential to encourage more spanning or gradiose players to act on their character archetypes and provides perhaps one of the more perfect ways to build up initial interactions among the playerbase.

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
Sorry it took me so long to get to reviewing this.
Heres a few things,

<details>
<summary>Delta</summary>

Since this is only on area, we don't need 3 air alarms all over the place. However, I can see the in flavor in at least keeping two. I suggest removing the bottom most one.
Taking a second look over I missed the forth one. I would like to try and keep air alarms to a minimal as, again, this is one area and we don't need four.

image

Also, please find another spot to put the TV studio. Plunking it down right in the middle of the arrivals hall seems like a nightmare. Also, not to mention, the navigation beacon is still there, and the bots will simply help themselves into the room.

image

I know this makes sense OOC, but please don't put cameras on windows. We want to try to avoid putting things on windows as much as possible.

image

</details>

</details>

<details>
<summary>Ice Box</Summary>

Pasting the template causes a bit of extra gen_turf to be added. Just remove it.

image

Ditto as from previous.

image

Also, unlike the other TV stations, they're in accessible areas the crew can get into rather easily. This is plunked in the service hall, which is a "restricted" area. Only service crew can readily access it. I would recommend trying to find a new spot.

</details>

<details>
<summary>Meta</summary>

We don't run cables/pipes through walls. Please have them connect from the hall.

image

Same with Delta. Remove one of the air alarms.

image
</details>

<details>
<summary>Tram</summary>

Ditto. Trim down the air alarms.

image

Ditto. We don't run pipes through walls. 

image

</details>

Few minor, general things.

1. Make icons for the area defines. These are super easy. Each `area_whatever.dmi` has a font template in it. You don't need to be a spriter to make these. If you need help, follow a preexisting area already.
2. Make subtype versions of the TV Record Screen, rather than var editing them.
3. I understand these are TV studios, but please include a generic camera in the waiting room. This way, if something happens, and AI or security can look in and see whats happening.
4. This is a minor nitpick, but altogether, if you can swap out the autodrobes for just two/three crates of costumes that'll be fine. Again, just a minor nitpick. It would be cooler to see each station have a different set of "themed" costumes, just to give each one a different breath of life.

**Comment by ghost** [comment]
> stuff from jolly

to second the 4th point, the vendors cost money, and it can really add up too even if its like, 10cr per item. Crates of costumes would be good for this and would mean you can spice up the rooms themselves to match the costumes too, if you chose

**Comment by twilightwanderer** [comment]
Sorry, but with the current implementation of the automaper, I have no idea how to fully implement the studio as I conceived it. It is claimed that it is intended to make it easier to update maps with TGs. But so far I see only constant agony with the choice of location for the new area and bringing electricity and air with a copy of half of the original map. The solution I presented is what I was able to find within this system.

**Comment by Jolly-66** [comment]
If you need help, you should reach out to us (maintainers) or other contributors in the mapping channel.

**Pull request closed without merging**
