### PR TITLE
[NON-MODULAR] Porting audible emotes from oldbase.

### PR DESCRIPTION
**Pull request by desertmote**
## About The Pull Request

It allows you to use audible emotes for speech with a ! prefix. Like ';! cheers "Hello crew!"'.
Works without radio and with whisper command, too.

## Why It's Good For The Game

This code is ported from our very own oldbase. One of my own most awaited features to return.

## Changelog
:cl:
add: Audible emotes! Prefix your messages like ;! scoffs "I did ++not++ forget the nuke disk."
/:cl:

### CODE REVIEW

**Comment by Vizoplez** [comment]
Code looks functional, will ping memetainer

**Comment by H0gberg** [comment]
*spin *clap *flip

**Comment by Gandalf2k15** [comment]
Hi, please check the modularisation comments in this, you'll need to make them conform to standards,

**Comment by desertmote** [comment]
> Hi, please check the modularisation comments in this, you'll need to make them conform to standards,

sorry! i fiex

**Comment by Gandalf2k15** [comment]
We can test merge this.

**Comment by Gandalf2k15** [comment]
Seems fine, TM'd this a bit ago.

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by StarHorder** [comment]
sowa thia include the felinind nyahaha?

**Comment by StarHorder** [comment]
oh my god i am stupid and read everything wrong

**Comment by Arctaisia** [comment]
People have wanted these for so long, thank you so much for adding both custom say audible emotes, and bay-style audible emotes again, very much appreciated <3

**Pull request merged**
