### PR TITLE
Removes all-in-one grinder icon override

### PR DESCRIPTION
**Pull request by desertmote**
## About The Pull Request

It's been improved by upstream, so we should use that one.

## How This Contributes To The Skyrat Roleplay Experience

Its prettier, IMO!

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
dreamseeker_kvhBvwObJy

</details>

## Changelog

:cl:
image: Resets the all-in-one grinder icon
/:cl:

### CODE REVIEW

**Comment by QuacksQ** [comment]
Soul removal

**Comment by out-of-phaze** [comment]
> Soul removal

exorcism

**Review by Zonespace27 — DISMISSED** [review]
Remove the sprite as well

**Review by Ebin-Halcyon — APPROVED** [review]
Sure.

**Review by tf-4 — APPROVED** [review]

**Pull request merged**
