### PR TITLE
Gives forging armor some new sprites, removes a single bit of forging armor as a consequence

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
I was working on some stuff when it was suggested to me that I pr the sprites I made as replacement for the current forging sprites, some of them in game as follows:
(Oh yeah and there's variations of these for newvox, oldvox, teshari, and shoes for digis)

An example set made out of iron plates:
image

Someone wearing said example set:
image
image

Sure why not, if we hate it then oh well.

## How This Contributes To The Skyrat Roleplay Experience
The current armor sprites for forging are... less than ideal to say the least, on suggestion of someone else I'm pring these I made for an event.

## Changelog

:cl:
del: One of the pairs of boots had to go, there's now only one shoes option (excluding horseshoes ig) for forging
imageadd: Forging armors now have sprites (Including variants for all the species!), and have been reflavored a little to match their new look
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
oh yeah here's how the base uncolored version looks on all the species
image

**Comment by ghost** [comment]
- icon-less state `horseshoe` in `modular_skyrat/modules/reagent_forging/icons/mob/clothing/forge_clothing.dmi`

Assume it's intentional, a'la gear harnesses? IDK how to feel about sprite-less armor though...

---

Other than that, sprites check out! Just make sure the left/right facing are on correctly, I can't tell but know that sometimes people get them 1px offset

**Comment by Paxilmaniac** [comment]
> * icon-less state `horseshoe` in `modular_skyrat/modules/reagent_forging/icons/mob/clothing/forge_clothing.dmi`
> 
> Assume it's intentional, a'la gear harnesses? IDK how to feel about sprite-less armor though...
> 
> Other than that, sprites check out! Just make sure the left/right facing are on correctly, I can't tell but know that sometimes people get them 1px offset

That's how they were before and I ain't changing it here, maybe later, as for the left/right I definitely made sure, as you can see by me having model refs for every species in that image ready. In fact, a few actually were shifted one pixel the wrong direction before I fixed them on that.

**Review by jjpark-kb — DISMISSED** [review]

**Comment by jjpark-kb** [comment]
Do not merge until https://github.com/Skyrat-SS13/Skyrat-tg/pull/16732

**Review by jjpark-kb — APPROVED** [review]

**Pull request merged**
