### PR TITLE
Kills every single instance of baked in color decal floors on the maps (Today on making prs that conflict with other prs I have open)

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
Orion had a todo to remove these, I realized how disgusting it is, mapper please just use decals.

## How This Contributes To The Skyrat Roleplay Experience
We have tile decals for a reason, don't bake in decals onto the tiles themselves.

## Changelog

:cl:
fix: tiles with the decals sprited in (terrible) have been replaced with just normal tiles with decals on top (good)
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Blessed be! Blessed be!

**Comment by ghost** [comment]
Icons and Code (all removals of now obsolete tiles) LGTM
I can't do anything for map review bc I'm dumb! :b

**Comment by Zergspower** [comment]
wait we're losing the nice preset tiles? the decals are too opaque in comparison and fuck now all the maps are going to look jank - how is this a better route than stacking 4-6 decals on 1 tile?

**Comment by Paxilmaniac** [comment]
These 'preset' tiles are anything but nice, they will become out of sync with tile sprite changes, decal changes, literally any change, and if the extensive collection of tile decals can't help you, nothing will.

**Comment by Zergspower** [comment]
> These 'preset' tiles are anything but nice, they will become out of sync with tile sprite changes, decal changes, literally any change, and if the extensive collection of tile decals can't help you, nothing will.

I just dont want to have to stack decals is all, and i disagree the presets looked nice - can we at least fix the decals? e.g. 
image
image
image

**Comment by Zergspower** [comment]
image
and this is what im talking about - decals hide details and to me just looks off

**Comment by Paxilmaniac** [comment]
I don't know what you mean by having to stack decals, but if you have multiple of an identical decal on the same tile I will gut you

**Comment by Jolly-66** [comment]
The colors don't match the decals we have on hand. Updating them to match would be incredibly redundant to do so, and a waste of time.

Good riddance.

**Comment by Zergspower** [comment]
> I don't know what you mean by having to stack decals, but if you have multiple of an identical decal on the same tile I will gut you

i highly suggest not looking at the ruins then - it's something i noticed as im fixing them all (i'm not leaving them stacked mind you)

**Comment by Paxilmaniac** [comment]
Almost every single one of skyrat's space ruins is a sin in some way, and they are not safe from me

**Comment by Zergspower** [comment]
But yeah - we need to fix the decals too - and i am sad we're doing this as the floors will looked even more washed out :/

**Comment by Paxilmaniac** [comment]
there's my free conflict

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
There's definitely a regression in appearance tied to this change, there's a lot less depth to the floor tiles when the decals are applied, because it's a simple flat color thing, whereas our floor tiles with specific colors on them had some proper shading to them. Personally, it's my main gripe with it, the resulting tiles just look significantly uglier than the "baked in" ones. Now, if the decals could be changed to lessen that effect, I'd be very much down for it.

Barring that, you also removed a lot of colors from many of our modular maps, by removing the colored tiles without applying decals back, resulting in a much less polished appearance overall. Here's the files where that has happened:
`interdynefob.dmm`
`piratefort.dmm`
`scrapheap.dmm`
`BlueShift_middle.dmm`
`VoidRaptor.dmm`
`pirate_enclave.dmm`
`prison_transport.dmm`
`slaver_syndie.dmm`

I'm also not entirely sure what the removal of a template in `Skyrat_Map_Reset.dmm` had to do with this PR, are we no longer using it?

**Comment by Paxilmaniac** [comment]
I’ll go fix those in a bit, the prison template on skyrat map reset is completely unused and only came up because it was one of the things using the removed tiles.

**Review by GoldenAlpharex — APPROVED** [review]
Yes, yes, much better.

**Pull request merged**
