### PR TITLE
A skillchip for RCD

### PR DESCRIPTION
**Pull request by Kush1Push1**
## About The Pull Request

A skillchip for RCD. So you cannot use one without the skillchip.

It's a rough draft without commentry or modularization. More about seeing reaction to such changes. If deemed fit, I'll continue to work with it.

## How This Contributes To The Skyrat Roleplay Experience

No discussions about "is it meta" about using RCD. If you have the chip, you can. If you don't, it is too complicated for the character.

## Proof of Testing

<details>

dreamseeker_L9rCHa2k57
 
</details>

## Changelog

:cl: SishTis
add: A skillchip for RCD usage.
balance: You cannot use RCD without the skillchip.
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
hard limiting tools via skillchip is the exact opposite of what skillchips should be used for, especially something as commonplace as the RCD

I also can't speak for the downstreams, but RCDs are just builder-guns, not really super-skill-requiring tools

**Comment by Kush1Push1** [comment]
It's all about balance (to myself). There is also an option to lock all station-produced RCDs to engineering access.

**Comment by HoodMilk** [comment]
There's literally books in the library on how to use engineering tools, and the RCD itself has a menu where you choose what to build.

Who asked for this.

**Comment by Stalkeros2** [comment]
> Who asked for this.

Neither Skyrat nor the downstream; it's the man's own volition. The latter's developers are chuckling at the OP from their secret channel.

**Comment by Ebin-Halcyon** [comment]
Coder makes worst balance PR ever, asked to leave coderbus.

Aside from that, genuine problems arise when you sit down and realize "Oh wait, there's no way to build over lava or plasma tiles" that isn't lategame stuff (Lavaproof rods.)

Skillchips are also hot garbage and shouldn't be used to gate stuff like this off.

**Comment by Iamgoofball** [comment]
```No discussions about "is it meta" about using RCD. If you have the chip, you can. If you don't, it is too complicated for the character.```

this does not answer the question "How This Contributes To The Skyrat Roleplay Experience"

**Comment by Zonespace27** [comment]
We've (the maintainer team) discussed having a system a la baystation skills in the past (a system that this emulates), the current agreement is "no".

**Pull request closed without merging**
