### PR TITLE
[MODULAR] Balances the new CMG-1 from .45 to 10mm Auto

### PR DESCRIPTION
**Pull request by MassacreDemigirl**
## About The Pull Request
.45 is a caliber mostly used for traitor weaponry (C20r). Moves CMG-1 to 10mm Auto which is a bit less powerful cartridge. Makes the CMG magazines multi-sprite and cleans up mags.dmi a bit.

## How This Contributes To The Skyrat Roleplay Experience
A balanced gun is good.

## Changelog

:cl: ErdinyoBarboza
balance: CMG-1 is now chambered in 10mm Auto. 
imagedel: Removed some duplicate icons from sechaul mags.dmi
/:cl:

### CODE REVIEW

**Comment by Lukaster42** [comment]
The 10mm is a pretty slow cartridge, maybe you can convert it to 9mm.

**Comment by Draganfrukts** [comment]
CMG-1 is supposed to be a direct counterpart of the C20r. It's why it's a subtype.

**Comment by Draganfrukts** [comment]
> CMG-1 is supposed to be a direct counterpart of the C20r. It's why it's a subtype.

NVM I'M RETARDED. GANDALF CHANGING SHIT...

**Comment by Gandalf2k15** [comment]
Given the availability of higher grade arms, as well as the fact this gun primarily uses rubbers, there is no need to change it.

**Pull request closed without merging**
