### PR TITLE
[Modular] Buffs Blob

### PR DESCRIPTION
**Pull request by SpaceVampire**
## About The Pull Request

This changes the blob victory limit from 700 back to 400, while removing the code that sends out the extra rapidly approaching critical mass warning signal. I was having weird issues with my earlier PR, but please read it here for more details.
https://github.com/Skyrat-SS13/Skyrat-tg/pull/4661

## Why It's Good For The Game

Following request of KathrinBailey, I have only lowered victory condition as it was the only thing they liked about my PR that I did to nerf blob slightly. Once again, I would recommend reading it for more context.

## Changelog
:cl:
fix: The hour long blob-based stalemates that just keep happening.
/:cl:

### CODE REVIEW

**Comment by DiscountDirtyDan** [comment]
Holy fucking shit thank you for this change, blob rounds drag and I want blobs to be able to win instead of either A) getting ERTs on them just from blob fatigue or B) nuked

**Comment by SpaceVampire** [comment]
@Gandalf2k15 
I did as you requested.
Its the exact same changes as before, but with the merge issues fixed.

**Comment by Gandalf2k15** [comment]
Aight, since the last PR has been open for ages, I'll merge this.

**Review by Gandalf2k15 — APPROVED** [review]
Old New PR.

**Pull request merged**
