### PR TITLE
Replaced openspace vacuums with basic space on blueshift

### PR DESCRIPTION
**Pull request by IsaacTheSharkWolf**
## About The Pull Request

Should help with performance by reducing the amount of tiles that have to do multiZ rendering.

## How This Contributes To The Skyrat Roleplay Experience

Hopefully this reduces the strain on the server enough to make blueshift playable once more.

## Changelog

:cl:

fix: Replaced unnecesary openspace tiles with simple space tiles to save on performance.

/:cl:

### CODE REVIEW

**Comment by nevimer** [comment]
Replacing the intended tiles with /basic is a not a solution for the much bigger issue that is awful performance from TG's multi-z rendering code. The maps game play should not be compromised because multi-z is primitive on TGstation. Basic is used to prevent processing during initialization, and is quite frankly intended for nothing more. 
VSCodium_XARfllrb2U
VSCodium_4m1vCTTrgQ
VSCodium_PtSPLjvqOu

Players have NO possible way to interact with /basic. Basic in unclickable, admins cannot even right click on it. It's effectively null space with a sprite. This is bad. Last I checked, there were a LOT of issues with atmos on deck 1 and breaches due to /basic being the base turf (since changed to not basic). Be very careful.

**Comment by IsaacTheSharkWolf** [comment]
> Replacing the intended tiles with /basic is a not a solution for the much bigger issue that is awful performance from TG's multi-z rendering code. The maps game play should not be compromised because multi-z is primitive on TGstation. Basic is used to prevent processing during initialization, and is quite frankly intended for nothing more. VSCodium_XARfllrb2U VSCodium_4m1vCTTrgQ VSCodium_PtSPLjvqOu
> 
> Players have NO possible way to interact with /basic. Basic in unclickable, admins cannot even right click on it. It's effectively null space with a sprite. This is bad. Last I checked, there were a LOT of issues with atmos on deck 1 and breaches due to /basic being the base turf (since changed to not basic). Be very careful.

Would it make more sense to just make the openspace tiles opaque in turn to ensure it doesn't render what is below it (from what i've been told this is the major cause for performance issues.)

**Comment by Jolly-66** [comment]
I had done this with a test merge I wanted to do, but BlueShift was taken out of rotation.

It may be time for an official re-do of BlueShift, all things considered. The map has proven to be a headache and a performance nightmare. 
I have ideas and plans I want to do, but I don't think this'll be the way to do it. Replacing open space just makes it impossible to use the IC verbs to move up/down.

EDIT: Also, please for the future, a map change as trivial as this, please use [MDB IGNORE] in your PR title, otherwise AA is going to be rather angry with us burning his servers.

**Comment by Gandalf2k15** [comment]
This has been tried several times now, as Jolly said, it is time to redo it

**Comment by IsaacTheSharkWolf** [comment]
> I had done this with a test merge I wanted to do, but BlueShift was taken out of rotation.
> 
> It may be time for an official re-do of BlueShift, all things considered. The map has proven to be a headache and a performance nightmare. I have ideas and plans I want to do, but I don't think this'll be the way to do it. Replacing open space just makes it impossible to use the IC verbs to move up/down.
> 
> EDIT: Also, please for the future, a map change as trivial as this, please use [MDB IGNORE] in your PR title, otherwise AA is going to be rather angry with us burning his servers.

i'm not looking forward to redoing blueshift, i've done plenty of refactors of the map and i'm honestly tired of it all.
remaking it will just make it a new map and probably ruin the vibe blueshift has, and knowing byond it'll probably run like shit anyways.

i've got a few other map projects which might be adequate replacements but i'm honestly kind of demotivated because all that work went down the drain, not exactly the best thing to push you forward especially knowing it'll probably be shat anyways whether it be players or performance.

i don't even know what causes the performance issues, it can't be the multi-z alone since there are maps used (primarily on other servers) that have plenty more but run just fine.
I wish i knew what it was so i could work on it but shit just turns up with nada.

**Comment by nevimer** [comment]
> > I had done this with a test merge I wanted to do, but BlueShift was taken out of rotation.
> > 
> > It may be time for an official re-do of BlueShift, all things considered. The map has proven to be a headache and a performance nightmare. I have ideas and plans I want to do, but I don't think this'll be the way to do it. Replacing open space just makes it impossible to use the IC verbs to move up/down.
> > 
> > EDIT: Also, please for the future, a map change as trivial as this, please use [MDB IGNORE] in your PR title, otherwise AA is going to be rather angry with us burning his servers.
> 
> i'm not looking forward to redoing blueshift, i've done plenty of refactors of the map and i'm honestly tired of it all.
> remaking it will just make it a new map and probably ruin the vibe blueshift has, and knowing byond it'll probably run like shit anyways.
> 
> i've got a few other map projects which might be adequate replacements but i'm honestly kind of demotivated because all that work went down the drain, not exactly the best thing to push you forward especially knowing it'll probably be shat anyways whether it be players or performance.
> 
> i don't even know what causes the performance issues, it can't be the multi-z alone since there are maps used (primarily on other servers) that have plenty more but run just fine.
> I wish i knew what it was so i could work on it but shit just turns up with nada.

Just wait for someone to improve multi-z. Baystation had a good implementation, might be worth porting.

**Pull request closed without merging**
