### PR TITLE
[NONMODULAR] General borg nerfs, and changes. (More then one, and I don't wanna clot the title)

### PR DESCRIPTION
**Pull request by RatFromTheJungle**
## About The Pull Request
Currently, it's just an announcement of intent with the opening of the PR, and so people can view the changes as I make them and provide feedback, but in general, this is toning back alot of the untouched things borgs have.

## Why It's Good For The Game
Borgs have alot of items, and functions(chemicals) that have gone generally untouched despite general nerfs to crew, and with the lack of nanites, I feel I can now thoroughly justify opening this to start.

## Changelog
:cl:
balance: Replaced sodium thiopental with lesser sodium thiopental, functionally the same chem half as effective.
balance: In preparation of another PR, changed the nanites syndicate borgs have from standard to lesser.
balance: Changed the hardstun on the borgs stunarm to a knockdown, while my ape brain tries to remember how to add stamina damage.
/:cl:

### CODE REVIEW

**Comment by SpookyTheFox** [comment]
These proposed changes really don't seem like they have anything to do with the loss of nanites.
On the contrary, I think you should boost the sodium thiopental to something a little stronger, perhaps Sulfonal. Sodium thiopental It's very slow acting, and difficult to keep people down long enough to do much to them. It fits with the theme though, as it's a chemical in the syndicate kit.
And the stun arm needs to be buffed to a full knock out with a much longer duration as well. I find it incredibly satisfying to do to others how borgs are normally treated, with an incredibly un-fun 1 hit game ending stun.
Remember that these items need to reliably perform and win in 1 vs 3 combat.

As always, I'm up for discussing balance in detail, we should do so in the discord.

**Comment by RatFromTheJungle** [comment]
> These proposed changes really don't seem like they have anything to do with the loss of nanites.

> And the stun arm needs to be buffed to a full knock out with a much longer duration as well. I find it incredibly satisfying to do 

1, It currents takes about 15s to hard KO someone with it, which ignores most forms of waking them up, and by 25s they'll be stamcrit aswell, well within the time it takes you to do this indefinitely, to up to six people, with little to nothing they can do in return, far to strong.

2, No, it's very overpowered, and with the crew being noticeably easier to kill, and prevented from meta-preparing against cyborgs until it's typically functionally to late, it's far to good an item that can't be easily knocked out of their hand. (It's immensely stronger then even the contractors baton, which is supposed to be an instant fight winner)

I'll bring it up in the discussion channel to go more in depth, but with the lack of nanites, borgs need their non lethal options toned back as they are no longer (almost) required to use them.

**Comment by hugmeorelse** [comment]
@RatFromTheJungle Can we delay this, especially since we haven't seen the full extent of the PR's effect? We're also dealing with new silicon policy changes that's coming up. I highly recommend you talk to members of this group. I can set that up whenever you're ready. DM me.

**Comment by Vizoplez** [comment]
Massive nukie nerf :)

**Pull request closed without merging**
