### PR TITLE
[MIRROR] Fixes pod person hair restyling [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/73196
--------------------

## About The Pull Request

Pod person hair restyling had a few issues. The mob signed up to restyling in try_attach_limb. This was not called on mob creation, so you could only restyle a pod person if you cut off their head, and put it back on. I have moved this to set_owner, and I have also made it unregister when needed.

- You couldn't restyle heads sitting on the ground either, as external_organs were deprecated. I tried to use the bodypart_overlay, but sadly that has no reference to the original organ. However, the organ was still present in the contents of the bodypart, so i could loop through them at least.

## Why It's Good For The Game

Fixes #73089

Once again you can snip snap at the small petals on someone's head to turn them into a giant flower, or vica versa.

## Changelog 

:cl:
fix: pod person hair can be once again styled by secateaurs
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
https://github.com/tgstation/tgstation/pull/72734

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/19635

**Review by GoldenAlpharex — APPROVED** [review]
Should be good to go now!

**Comment by tf-4** [comment]
missing edit to `restyling.dm` ln 34 unless that's not needed @GoldenAlpharex 

https://github.com/tgstation/tgstation/blob/6196896abc3b8b85d83124d0bf3b8136b234f7d3/code/modules/surgery/organs/external/restyling.dm#L34

I assume it _is_ needed, but you also did all the mutant parts stuff so.

**Comment by GoldenAlpharex** [comment]
> missing edit to `restyling.dm` ln 34 unless that's not needed @GoldenAlpharex
> 
> https://github.com/tgstation/tgstation/blob/6196896abc3b8b85d83124d0bf3b8136b234f7d3/code/modules/surgery/organs/external/restyling.dm#L34
> 
> I assume it _is_ needed, but you also did all the mutant parts stuff so.

Technically it isn't needed because of some changes that I made upstream that I'll be merging down here soon:tm:. It doesn't work to begin with right now, and honestly with our current system I'm not even certain this will be working properly either. I just also couldn't care enough to spend even more time on the damn podpeople hair.

**Pull request merged**
