### PR TITLE
Engineering Tallborg

### PR DESCRIPTION
**Pull request by Jureiia**
## About The Pull Request
Adds a tallborg/MEKA engineering module. Previews below:
dreamseeker_msHdq8VpGA

https://user-images.githubusercontent.com/53306684/180661157-42a9a408-ad68-4e3e-b4d7-e95346a2cb57.mp4

Credit for original MEKA sprites goes to theOOZ, edits done by me.

## How This Contributes To The Skyrat Roleplay Experience
A lot of cyborg players who like to play tallborgs are remiss to find that when they want to help with engineering issues as a borg that there isn't an option if they like to be somewhat consistent with how their borg looks, this gives those people the option.

## Changelog

:cl:
add: A new cyborg module: Engineering MEKA.
/:cl:

### CODE REVIEW

**Comment by EerieDream** [comment]
Finally I can play borg.

**Comment by desertmote** [comment]
this gets the zeng-hu seal of approvement ☑

**Comment by GuiltyNeko** [comment]
Since the medical tallborg gets a duffelbag, could this one get maybe a toolbox? It's thematic.
Edit: the sprite, I mean, in case that was somehow not clear.

**Comment by Oxotnak** [comment]
Finally i can make flavor for borgy and be not scared that i was asked to change module on engi

**Pull request merged**
