### PR TITLE
[NONMODULAR] get this ugly ass ID shit off our chests

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

SHIT IN THE ID SLOT NO LONGER SHOWS UP ON YOUR BODY!

~~removes all this awful new ID things off of chests, EXCEPT for prisoners. Prisoners get to keep their ID pinned on their chest because it certainly makes more sense.~~

~~NOTE TO MAINTAINERS: I did my best to be as absolutely unobtrusive in the code as possible to minimize merge conflicts. 
Making a new DMI with one blank icon state in it was the easiest wayto get rid of the purple and black squares of shame from the beltslot PDA and Tablet.~~

## Why It's Good For The Game

I got several complaints from several people about this new stuff, and I, too, don't like it. So let's just undo that bit and go back to having good fashion sense, yeah?

## Changelog
:cl:
fix: Ugly ID and shit not on chests anymore reeee
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
Having it show a blank overlay is a terrible implementation, any overlay contributes to maptick, so having empty ones is a terrible waste. Just comment out the code that compiles the ID worn icon, somewhere in human_update_icon or something like that

**Comment by sergeirocks100** [comment]
You could probably try and revert PDAs to the old sprites, while you're at it, i think the new ones look ugly too.

**Comment by Swiftfeather** [comment]
> Having it show a blank overlay is a terrible implementation, any overlay contributes to maptick, so having empty ones is a terrible waste. Just comment out the code that compiles the ID worn icon, somewhere in human_update_icon or something like that

@Azarak I've complied with this, but there' a funny new integration error hehehe

**Comment by tf-4** [comment]
Downvote. It serves a purpose as outlined in the doc and doesn't look that bad, though the latter is obviously subjective

**Comment by GoldenAlpharex** [comment]
It's not so bad, just don't keep your ID out, leave it in your PDA and it won't show, it's that simple.

**Comment by Jureiia** [comment]
> 
> 
> It's not so bad, just don't keep your ID out, leave it in your PDA and it won't show, it's that simple.

PDAs in the ID slot show up on the sprite now ☹️

**Comment by Swiftfeather** [comment]
> It's not so bad, just don't keep your ID out, leave it in your PDA and it won't show, it's that simple.

The pda and tablet sprites have no place on the chest and instead of bashing my skull against the steel wall that is overlay adjustment, the most efficient way was to simply stop putti g sprites on your chest. This also reduces one tiny little thing the server needs to process.

**Comment by tf-4** [comment]
Ok what about the purpose it serves other than aesthetic

**Comment by 9723** [comment]
IMO It hardly serves a purpose other than aesthetics, the ID is covered up by any outer clothing layer sprite which renders their practical purpose of being identifiable without examining nearly pointless considering how often people wear outer layer clothing while for the people who choose not to wear an outer layer it serves as nothing but a heinous eyesore on your character sprite.

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
