### PR TITLE
[MODULAR] Ghost Cafe Renovations - Beach Resort

### PR DESCRIPTION
**Pull request by kannthus**
## About The Pull Request

Welcome one and all to the brand new SolFed's Beach Resort which includes: 

2 cabins, with privacy curtains and en-suite bathroom:
CleanShot 2022-02-17 at 10 13 21

A stocked bar resting aside a full kitchen w/ freezer, a dance floor, everything you really need for those lovely valentine dates:
CleanShot 2022-02-18 at 09 58 57

Once you've gained your food, feel free to rest at either the outdoor picnic area or lounge at the waterside mats (to truly soak in those rays) while also knowing you and your compatriots are safe with a lifeguard:
CleanShot 2022-02-18 at 09 58 05

A newly installed Bridge with safety railings to avoid any unfortunate accidents, leading down to a bathroom/changing area with appropriate uniforms in a locker: 
CleanShot 2022-02-18 at 09 56 49

The Full Resort (big image, open in new tab to see)
CleanShot 2022-02-18 at 09 57 38

And of course it wouldn't be a beach experience without them, our lovely beach guest of honor has been seen within the establishment, let me know if you find them.

## How This Contributes To The Skyrat Roleplay Experience

Anyway, roleplaying bit aside: I feel this would spruce up the cafe quite a lot, not only giving people more places to reside and do their deeds, but also expanding the Cafes boundary (only by a few tiles out). Genuinely I believe a lot of people would enjoy this as a different atmosphere from the rest of the ghost cafe and allow for people to "stage their scenes" in a wider variety of biomes.  

## Changelog

:cl:
add: Ghost Cafe - Beach Resort
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
I'm all for it but tbh I'm not sure why we need an entire second full bar and kitchen? I'd scrap most of that and just leave the rooms really.

**Comment by kannthus** [comment]
> I'm all for it but tbh I'm not sure why we need an entire second full bar and kitchen? I'd scrap most of that and just leave the rooms really.

I understand where you are coming from, but at the same time the cafe has become more and more congested as of late due to a variety of reasons and having 1 kitchen/bar for the amount of people whom can be there at once is a little overbearing (too many cooks..), especially if someone wanted some alone time or preform any unique scenes or scenarios, the reason I called it a "Resort" is its supposed to be a little more then just a few cabins and be independant from the original cafe without being too over-the-top. 

I also plan to add:
- [x] Crabs (on request)
- [x] Beach-ey outfits/uniform lockers (on request)
- [x] Lifeguard stand (on request)
- [x] Windoors (on request)
- [x] Restrooms/changing area
(Put on draft while I add these)

**Comment by YakumoChen** [comment]
also uh build a windoor if you're connecting a door to a table

**Comment by kannthus** [comment]
> also uh build a windoor if you're connecting a door to a table

Ah whoops of course, will do!

**Comment by YakumoChen** [comment]
other suggestions: 
-Add a goldschlager and the silver booze (I can't remember the name) to the bar crate or something if you didn't already, those are good thematically for a yippie beach
-bee plushie doesn't belong in the trash :( What did bee plushie ever do to you?

**Comment by YakumoChen** [comment]
-you don't need tiny fans in the ghost cafe either

**Comment by kannthus** [comment]
> other suggestions: -Add a goldschager and the silver booze (I can't remember the name) to the bar crate or something if you didn't already, those are good thematically for a yippie beach -bee plushie doesn't belong in the trash :( What did bee plushie ever do to you?

Also will add that too yeah.

Hey! its his home, he loves it there:
CleanShot 2022-02-18 at 04 57 56

**Comment by kannthus** [comment]
> -you don't need tiny fans in the maid cafe either

You do, otherwise the room depressurises every time you enter a door, it's the reason why every other door has it on the cafe.

**Comment by YakumoChen** [comment]
thats weird and probably a bug somewhere, I have no idea why it would be like that

**Pull request merged**
