### PR TITLE
Removes the fishing minigame

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
title

## How This Contributes To The Skyrat Roleplay Experience
the server sometimes experiences some REALLY bad stuff that makes playing the fishing minigame nigh impossible.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image
image

</details>

## Changelog

:cl:
del: removed the fishing minigame
del: removed the trash from the water basin fishing source
/:cl:

### CODE REVIEW

**Comment by nikothedude** [comment]
never heard of this problem before, can someone confirm

also, wHy remove the trash

**Comment by jjpark-kb** [comment]
> never heard of this problem before, can someone confirm

The server chugs at times, I don't see why you need confirmation of this.

> also, wHy remove the trash

It is broken and has been broken for sometime, it was going to be removed eventually.

**Comment by nikothedude** [comment]
> > never heard of this problem before, can someone confirm
> 
> The server chugs at times, I don't see why you need confirmation of this.

no i mean confirmation taht server lag obliterates the miningame

**Comment by nikothedude** [comment]
actually why am i asking for someone else to confirm their word is as fine as yours w/e

**Comment by Nerev4r** [comment]
It's mostly been insulated from lag as far as I'm aware. @Ghommie Can you weigh in on this?

**Comment by Paxilmaniac** [comment]
the trash removal change is fine but

I play on that dollar store college dorm internet connection and the only times the fishing minigame is so effected by lag that I couldnt use it, I'm also lagging hard enough that _nothing else in the game would have been playable in the first place_. I think using the server as an excuse for removing it is falsified and hiding why you actually want it gone.

**Comment by Nerev4r** [comment]
Conjecture of intent isn't really necessary here. I'd remark myself, though, that fishing was pretty doable the other day (when I tried it for the first time in months) even with a really shitty rod setup. I'll check w/ the author in devcode.

**Comment by jjpark-kb** [comment]
discussion in dev-code; something else will be done instead

**Comment by Ghommie** [comment]
> It's mostly been insulated from lag as far as I'm aware. @Ghommie Can you weigh in on this?

The fishing minigame doesn't run on a TGUI window anymore. It has its own subsystem, and severe server lag will impact it just like any other subsystem, if not worse: it's supposed to fire every decisecond, and the delays to the subsystem firing can easily be much larger than that. 

In the end, you can do what you want, I don't mind really. Even if the minigame were removed in favor of a do-after, the problem of latency spikes won't make the experience much more pleasant anyway.

**Pull request closed without merging**
