### PR TITLE
LORECASTERS: Making newscasters maybe somewhat relevant again

### PR DESCRIPTION
**Pull request by Zonespace27**
## About The Pull Request
This PR adds new functionality to newscasters in their ability to broadcast lore-based announcements, read from a config file, every X minutes (default is 30m, set by config).

For news stories that go out of rotation for simply being too old, download the new News Archive NTOS app, which lets you read all articles that went out of circulation (again read from a config)

image

image

## How This Contributes To The Skyrat Roleplay Experience
Adds just a bit of a way for people to care about lore, and get an IC explanation for some development changes and additions, such as reporting on the FTU adding more contractors to the station after cargo got a job slot increase, for example.

## How to add new articles
To add a story to rotation, add it to config/skyrat/news_stories.json, ideally at the top of the file for maximum organization
Once a story's been out too long, or there's too many in circulation, move older ones to config/skyrat/archived_stories.json, again ideally add it to the top

Both JSON files take the same format, allowing for:
Title: What the article will be called (Default: Nanotrasen News Broadcast)
Text: What the article contains (Default: Someone forgot to fill out the article!)
Year: Publication Year (Default: Current year + 540)
Month: Publication Month (Default: Current month)
Day: Publication Day (Default: Current day)

## Changelog

:cl:
add: Newscasters now intermittently broadcast announcements relating to the lore and recent developments.
add: For out-of-circulation articles, download the News Archive app on any NTOS-compatible device to read all of them!
/:cl:

### CODE REVIEW

**Comment by hugmeorelse** [comment]
My man.

**Comment by Stalkeros2** [comment]
Based as FUCK.

**Comment by GoldenAlpharex** [comment]
I really like the idea.

**Comment by Plum-but-gayer** [comment]
ohhhh this looks sick as hell

**Pull request merged**
