### PR TITLE
Granite's Love pass 3 of X for ruins - DS-2 flavor

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

Due to the size and usage i'm bringing this into its own PR rather than in the batches of five like the others, the goal of all of these PR's is to either redesign/shrink/expand or otherwise bring a ruin up to current date with mapping styles and usage. DS-2 getting its own PR is mostly how I'm doing with the Ghost Hotel - a section at a time after feedback and TM's. More than likely no items will be touched unless i spot something egregious or overlooked, this PR will also allow QOL items to be added if necessary. 

## How This Contributes To The Skyrat Roleplay Experience

DS-2 is just too large of a ruin to exist as its current state, given how few play the role the goal is to shrink the station by at least 25% As of the first pass - I was able to scrape off 23 X and 11 Y bringing it from 100x86 to 77x75. A more condensed version wil add a fair bit of value, being this large it's hard to both engage with others and half the time not even know you have prisoners.

DS-2
--

## Changelog

:cl:
qol: Mass redesign of the Interdynefob ruin aka DS-2 - focusing on shrinking down unused areas and optimizing each rooms size.
fix: interdyne fob - A lot of minor duplications and errors, mostly with cables and piping
/:cl:

### CODE REVIEW

**Comment by Zergspower** [comment]
The dock will not be touched and, yes, a gigabeacon board will be placed in the vault when i move further down.

**Comment by Zergspower** [comment]
Pool shrunk by 2 tiles wide, half dorms removed and chapel integrated in their spot. Solars moved down some to work with the map shrink and the gym scaled down into a smaller workout room. Cryo moved to the never-used sec-checkpoint above the dock, Solars obviously altered - i may rethink them and move them to the available space to the right which would free up another chunk of realestate.

**Review by Paxilmaniac — APPROVED** [review]
I was going to take a look at doing this myself but honestly thank you for beating me to it. I think that even with the current size reduction there's a LOT of just unnecessary or unused areas, but this is a good start.

**Comment by Zergspower** [comment]
> I was going to take a look at doing this myself but honestly thank you for beating me to it. I think that even with the current size reduction there's a LOT of just unnecessary or unused areas, but this is a good start.

Yep - just going to get feedback and visually see it for a couple days then get the next push out which will probably start with the prison area and left maints

**Comment by Zergspower** [comment]
PR updated with new changes and post screenshot updated with this one -

Second pass included Maintenance, Botany and EVA rewiring and repiping most of maints to be a redundant source of power/air/waste. Isolated Virology off from the distro and waste, balanced armory by removing the drums and replaced with actual boxes of ammo for slugs and beans (35 per box wow) at 2x each - didnt make sense the peacekeepers there had no starting ammo outside of emptying the drums.

**Comment by Zergspower** [comment]
Brought back the Syndie Softsuits in EVA

**Comment by Zergspower** [comment]
I'm good with this version and a test merge

**Comment by YakumoChen** [comment]
Could probably stand to remove the prison bedrooms on the left side, potentially just chop out the solars entirely because rtgs and magic smes.

**Comment by Zergspower** [comment]
> Could probably stand to remove the prison bedrooms on the left side, potentially just chop out the solars entirely because rtgs and magic smes.

I'm still trying to figure out how much to shrink the Prison or flat remove it, the TM will give us a fair bit of insight into what it'll look like in practice and generally shows what is needed beyond there. I've actually already made the call to remove either the RTG's or Solars but just havnt decided _which_ yet.

**Comment by gamermomentum** [comment]
The new workout room looks super desolate. Maybe put a bench by the door, and add a window somewhere? It just looks too gloomy.

Also, I don't really play the role but I'm pretty sure those Drums were for the Admiral's bulldog. I don't know if the Admiral still actually has that(As he lost some stuff a while ago), but if he does you might wanna readd some of them to the Admiral locker or something.

**Comment by YakumoChen** [comment]
>remove either the RTG's or Solars but just havnt decided which yet.

I'd stick with rtgs, those and the solars are largely cosmetic and RTGs take up less space(they feed into a magic smes), fits more thematically with other syndie installations too. Less entry points into the sekrit syndie base.

I feel like you could remove the license plate machine room, prisoners aren't there to make a quick buck for the syndicate, unlike those at NT.

**Comment by HoodMilk** [comment]
Honestly it might be worth making ds2 into mostly a prison. They don't really need a lot of the stuff like botany, medical, science, and service since it will be linked to the lavaland base every round. Having it be an extension of the lavaland base rather than trying to make it it's own thing could be nice.

Having ds2 just be security, a prison, bridge, and hangar (all of which are not present on the lavaland base) could trim it down a lot and bring ds2 into it's own identity rather than just being a ministation that's barely ever used.

Bit of an extreme take but it's food for thought.

**Comment by YakumoChen** [comment]
I could almost argue more for chopping the service modules from interdyne where they feel extremely clunky and cramped, the secret research base should be more compact than the more obvious main base.

I could vouch for chopping the medbay out though, and the research lab.

**Comment by CandleJaxx** [comment]
tbh the dock should be made a lil bit bigger- docking the syndicate drop ship inside is fun if it gets spawned in

**Comment by Zergspower** [comment]
DS-2-2

**Comment by YakumoChen** [comment]
I'd additionally remove, at minimum, the research / lathe part of the scilab, and the virology lab, since both of those primarily are done on interdyne. Ore silos can't be cross-level anymore as well so it's unlikely the lathes on ds2 ever see much use.

**Comment by gamermomentum** [comment]
I was just having a lookover the new ruin and it actually looks pretty good now. Just some small stuff. 

Freezers are still access restricted to an access the DS2 crew doesn't have. 
You didn't mention, but the Cgloves+ got changed to regular Cgloves. It's probably nbd but I always thought it made sense for the Syndicate Warden to have krav. Maybe stick some in the MAA's locker, if not the original two pairs.  
You switched the botany thing to a mutagen dispenser which, in the face of them having a somatoray roundstart, is a pretty tremendous downgrade compared to the old T4 botany chem dispenser that's been retained by Interdyne. 
The Admiral also still has a Bulldog but now has no magazines for it, or at least not that I could find anywhere. 
The Chapel is HUGE. Compared to every other room on the station (Outside of the hangar and the pool) it's really outrageously big. 
Also I think you borked the wakeup announcement thing from #14901. Lavaland still does it, but DS-2 doesn't anymore. 

Good change on the gym though. It's not a dreary little closet, and it actually just looks really good being part of the hallway.  I don't think it has any light fixtures in it, though.

**Comment by Zergspower** [comment]
> I was just having a lookover the new ruin and it actually looks pretty good now. Just some small stuff.
> 
> Freezers are still access restricted to an access the DS2 crew doesn't have. You didn't mention, but the Cgloves+ got changed to regular Cgloves. It's probably nbd but I always thought it made sense for the Syndicate Warden to have krav. Maybe stick some in the MAA's locker, if not the original two pairs. You switched the botany thing to a mutagen dispenser which, in the face of them having a somatoray roundstart, is a pretty tremendous downgrade compared to the old T4 botany chem dispenser that's been retained by Interdyne. The Admiral also still has a Bulldog but now has no magazines for it, or at least not that I could find anywhere. The Chapel is HUGE. Compared to every other room on the station (Outside of the hangar and the pool) it's really outrageously big. Also I think you borked the wakeup announcement thing from #14901. Lavaland still does it, but DS-2 doesn't anymore.
> 
> Good change on the gym though. It's not a dreary little closet, and it actually just looks really good being part of the hallway. I don't think it has any light fixtures in it, though.

The MAA is going to get Krav vs C+ in their loadout rather than their locker, that's really the only touch to the 'gamer gear' even though calls for more were made. I really wanted to focus on just the downsizing on DS-2 before migrating over to Interdyne to do a redesign there, after everything's done the items can be addressed.

I kinda like the chapel, the one im most proud of designing :), depending on if another shrink happens it'll get compressed down too, but currently I've surpassed my goal of resizing for the time being.

i'll probably add a bulldog mag to the Admirals loadout, rather have general shotgun ammo there for the other weapons rather than just theirs.

Odd about botany, I basically scooted things into form rather than adding/deleting - i'll look at that closer.

Odd i didnt touch the sleepers but can look at that as well, may have been a conflicting TM

iirc that area is force-lit but i'll recheck the lighting (Gym)

**Comment by Paxilmaniac** [comment]
these animals are so fucking funny they make me want to merge without looking

**Pull request merged**
