### PR TITLE
Removes dabbing

### PR DESCRIPTION
**Pull request by NullDagaf**
nuff said

### CODE REVIEW

**Comment by StarHorder** [comment]
I fully support this.

**Comment by Tumesuo** [comment]
cope, seethe

**Comment by Fikou** [comment]
sneed

**Comment by Vizoplez** [comment]
Improper title conventions, lack of SKYRAT EDIT comments. Please rectify or close PR
-Intern dev

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by Gandalf2k15** [comment]
> Improper title conventions, lack of SKYRAT EDIT comments. Please rectify or close PR
> -Intern dev

dw it's already a skytat file

**Comment by NullDagaf** [comment]
> > Improper title conventions, lack of SKYRAT EDIT comments. Please rectify or close PR
> > -Intern dev
> 
> dw it's already a skytat file

doesn't matter
gotta spam that copypaste

**Pull request merged**
