### PR TITLE
Adds LOOC to the local chat filter

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

Adds LOOC to the local chat filter.

## Why It's Good For The Game

Because it is. Also, if you're on just a local tab, you shouldn't be able to have an excuse of "But I didn't see their LOOC!"

## Changelog
:cl:
tweak: adds LOOC to the local chat filter
/:cl:

### CODE REVIEW

**Comment by Seris02** [comment]
> You currently have a negative Fix/Feature pull request delta of -10. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

WELL OKAY THEN JEEZ

**Comment by Gandalf2k15** [comment]
Also add this tot he OOC filter?

**Comment by Seris02** [comment]
It's a local one, and like I said above, I really don't think you should be allowed to be on a local only chat filtered tab and claim not to have seen any LOOC's expressing nonconsent or anything like that. Plus, Local OOC.

I'll reread this in the morning to see what you have to say and I'll put it in OOC if you want it there. Also, can ya rerun travis?

**Comment by Gandalf2k15** [comment]
ye, just add this to the OOC tab too

**Comment by Gandalf2k15** [comment]
update from master

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
