### PR TITLE
[MODULAR] Pride month

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Expands the pride event to cover the month of June
Tramstation is getting trimlines too!

## How This Contributes To The Skyrat Roleplay Experience

Longer unique station trait

image

## Changelog

:cl: LT3
config: June is pride month
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Isn't the pride event the one that makes all the tiles multi colour?

**Comment by lessthnthree** [comment]
> Isn't the pride event the one that makes all the tiles multi colour?



> Isn't the pride event the one that makes all the tiles multi colour?

Added a picture, trimlines are less garish than random tile colours.

**Comment by Jolly-66** [comment]
> Isn't the pride event the one that makes all the tiles multi colour?

Pride month makes all decalsin a set row a color, so basically a slow gradient/rainbow effect.

April Fools randomizes ALL decals, which I utterly fucking hate.

**Comment by Nerev4r** [comment]
https://user-images.githubusercontent.com/12636964/229316460-05f07065-62a8-4cac-add5-8462d5c5f630.mp4

**Comment by Gandalf2k15** [comment]
Oh those, I'm not a fan of making the entire station look incorrectly mapped for a month. A week is fine, but the whole map has oddly coloured decals. Perhaps have pride month do something that isn't so garish? Could make the status displays show a raindbow flag.

**Comment by Nerev4r** [comment]
I think it's pleasant on the eyes; probably a maptainer decision?

**Comment by dawsonkeyes** [comment]
https://user-images.githubusercontent.com/76002401/229316772-1257c4d8-e90b-481d-8cfa-87c3a70010cf.mp4

**Review by Gandalf2k15 — CHANGES_REQUESTED** [review]
A month of incorrectly mapped decals is a bit much, make this something less garish.

**Comment by lessthnthree** [comment]
> A month of incorrectly mapped decals is a bit much, make this something less garish.

How about an airlock overlay

image

**Comment by Gandalf2k15** [comment]
> > A month of incorrectly mapped decals is a bit much, make this something less garish.
> 
> How about an airlock overlay
> 
> image

that could work, let's see how it looks in game

**Comment by Gandalf2k15** [comment]
> > A month of incorrectly mapped decals is a bit much, make this something less garish.
> 
> How about an airlock overlay
> 
> image

or perhaps change the white N in these to be rainbow 
image

**Comment by lessthnthree** [comment]
Yeah too many airlocks with all the animation frames and types. Think a single lighting overlay for it, and yeah the Nanotrasen sign or something.

**Comment by lessthnthree** [comment]
This is probably gonna be a month's away so closing.

**Comment by softcerv** [comment]
https://user-images.githubusercontent.com/68373373/229325500-b8f66bbb-b5a0-4521-95be-d1a0642b6e96.mp4

**Pull request closed without merging**
