### PR TITLE
[READY]Adds two new space ruins, tiny bit of framework for other future mapping

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Adds two silly ruins based off.. um.. salvaging ships (I've censored the interiors to preserve the surprise <3
tram
salvageyard

On top of those two ruins, it adds a few fluff items for use in mapping, the most important ones being Spaceship Walls/Windows (Re-textured survival pod walls without the stripe, making it possible to recolor them) and Metal Poles (Modified Tram Lines that can be used in more vague situations. Very important for future projects.)

Also does a tiny bit of cleanup with the VG decals, sliding the icons into a decal folder and removing a duplicate link in the code >->

## Why It's Good For The Game
First off, fun space ruins with their own little lorebits are cool and you can't change my mind.
Second, future prep for other maps, my own and others.

## Changelog
:cl:
add: Added 2 new space ruins!
add: Spaceship Walls are now NT-approved, the plating/glass of which can be gotten by crafting Titanium Sheets/Titanium Glass in-hand.
add: Vague Metal Pole decor items for mapping purposes
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Marked as WIP because I'm waiting on a single sprite, plus uh.. forgot I was going to implement spaceship walls being craftable >-> The craftability should be easy and done within the night, idk how long until the sprite is sent to me

**Comment by ghost** [comment]
:( I can't test this because master is broken, so I can't finish making the spaceship stuff craftable

**Comment by ghost** [comment]
> 
> 
> :( I can't test this because master is broken, so I can't finish making the spaceship stuff craftable

nevermind im just stupid and was running an outdated byond
tests done, all works. literally only waiting on that icon now

**Comment by KathrinBailey** [comment]
make sure to test compile in vsc with runtime breakpoint checked to see if you get stack trace warnings for those lattices on plating.

**Comment by ghost** [comment]
> 
> 
> make sure to test compile in vsc with runtime breakpoint checked to see if you get stack trace warnings for those lattices on plating.

I tried that then realized I was lazy, so I just replaced every instance of a lattice on a non-noop turf with the fake decal lmao

**Comment by Quink-Fix** [comment]
These plates don't work on wall girders.

**Pull request merged**
