### PR TITLE
[Host Request] Vendors will no longer have a chance to gib you

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
## About The Pull Request
Does what it says on the tin. Everything else is fine but this one is just kinda stupid.

Requested by the host, but honestly I agree with it.

## How This Contributes To The Skyrat Roleplay Experience
No more funny RR from a machine that you find in about 50 copies throughout the entire station.

## Changelog

:cl: GoldenAlpharex
qol: Vendors' wheels have been oiled and should no longer annihilate your skull upon falling onto you anymore. Safety is still not guaranteed.
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
Hugbox

**Comment by GoldenAlpharex** [comment]
> Hugbox

:pensive:

**Comment by GoldenAlpharex** [comment]
(For clarification, it just makes it so you can't roll the chance for the vendor to delete your head anymore, everything else stays the same)

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by Ziiro** [comment]
Just change to severing the head off. Removing it from the table does have the side effect of making the remaining options more likely, so beware.

**Comment by GoldenAlpharex** [comment]
> Just change to severing the head off. Removing it from the table does have the side effect of making the remaining options more likely, so beware.

I thought about it, but at the end of the day that makes even less sense, I prefer staying true to the other events that make sense for a vendor to do, like embed you with a shitton of glass shards, which is arguably a lot funnier.

**Comment by ChungusGamer666** [comment]
Hugbox moment

**Comment by nikothedude** [comment]
could we kindly set up the github actions bot to ban anyone who uses the word "hugbox", thanks, i think our code quality would increase tenfold

**Comment by tf-4** [comment]
> could we kindly set up the github actions bot to ban anyone who uses the word "hugbox", thanks, i think our code quality would increase tenfold

it's justified here tho

**Comment by Iamgoofball** [comment]
host dead pls nerf

**Comment by Iamgoofball** [comment]
In all seriousness, this is actually one of the least damaging situations from a vending machine because "my body exploded" is easy to fix in Medical(new body + SAD)

**Comment by GoldenAlpharex** [comment]
> In all seriousness, this is actually one of the least damaging situations from a vending machine because "my body exploded" is easy to fix in Medical(new body + SAD)

Well just fix the SAD to not give you weird colors then :)

**Comment by ChungusGamer666** [comment]
in all seriousness players facing stupid consequences for their own stupid actions is fine

**Pull request closed without merging**
