### PR TITLE
[WIP] [DNM] Edits and replaces most new gun sprites + Flavor

### PR DESCRIPTION
**Pull request by Draganfrukts**
## About The Pull Request

Does what it says on the tin, little changes and stuff (or big) to most new armadyne guns.

## Why It's Good For The Game

I hate. And let me say it clear. _**I fucking hate**_ when someone takes sprites from other codebases untouched and disregards things from it. This PR aims to change that. Little edits, big edits, whatever, I just don't think you can have a good looking codebase if everything in it is taken from somewhere else.

(If I see the "b-but it looks better when sprite is from this codebase because it's from this codebase and should not be touched...." comment I'm going to throw rocks at your bedroom window at 4 AM on a monday night)

## Changelog
:cl:
tweak: WIP
balance: WIP
imageadd: WIP
imagedel: WIP
spellcheck: WIP
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
b-but it looks better when sprite is from this codebase because it's from this codebase and should not be touched

**Comment by Gandalf2k15** [comment]
Keep the blue yellow and red lines reeee

**Comment by Draganfrukts** [comment]
God fucking DAMN you PR

**Comment by Draganfrukts** [comment]
Fuck it I'll finish this someday and upload everything in one pack

**Pull request closed without merging**
