### PR TITLE
[MODULAR] Items stored in pockets will now be sent flying when gibbed

### LINKED ISSUE #22299: Pocket items don't drop when gibbed.
## Testmerges:
https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110
https://github.com/Skyrat-SS13/Skyrat-tg/pull/21360
https://github.com/Skyrat-SS13/Skyrat-tg/pull/21708
https://github.com/Skyrat-SS13/Skyrat-tg/pull/22045
https://github.com/Skyrat-SS13/Skyrat-tg/pull/21991

## Reproduction:
When gibbed, items in pockets are destroyed instead of dropping onto the ground. This mostly defeats the purpose of even picking up a GPS as **everything else** that's worn is destroyed. Clothes, belt, shoes, backpack, suit item, EVERYTHING.

### PR DESCRIPTION
**Pull request by vinylspiders**
## About The Pull Request

Closes https://github.com/Skyrat-SS13/Skyrat-tg/issues/22299

What it says on the tin--I'm not sure if this has ever been the case that they dropped, but it makes sense and someone requested it. So here it is.

## How This Contributes To The Skyrat Roleplay Experience

Having two safe item slots when fighting mobs that can gib is nice.

## Proof of Testing

<details>
<summary>ID in pocket slot gets yeeted</summary>
  
dreamseeker_55iYz5f28i

</details>

## Changelog

:cl:
qol: items stored in pockets now fall out and get sent flying when gibbed (instead of just being deleted)
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Cool idea but I'm not sure what this really adds.  Roles likely to be gibbed aren't likely to store super useful things in pockets (miners) or have a vested interest in not retaining items when they gib (ninja, etc)

**Comment by vinylspiders** [comment]
> Cool idea but I'm not sure what this really adds. Roles likely to be gibbed aren't likely to store super useful things in pockets (miners) or have a vested interest in not retaining items when they gib (ninja, etc)

It adds a way to recover some items from gibbed players which the linked issue was raising concerns about. 

A fair point about antag roles but I don't know. It seems logical that some pocket items could remain intact. Besides I don't think that reason is as important here as upstream, though perhaps I'm mistaken in that regard.

**Comment by YakumoChen** [comment]
> A fair point about antag roles but I don't know. It seems logical that some pocket items could remain intact.

I mean, I'm not quite sure what's logical about items in a loose pocket being unharmed when your body is being rend into a fine paste myself. I could maybe see value in the ID slot in particular being safe just to save some headache, but this seems like a really niche feature.

Not everyone puts their GPS in their pocket so it wouldn't be very reliable in saving others (most people won't realise this feature exists either)

**Comment by vinylspiders** [comment]
> I mean, I'm not quite sure what's logical about items in a loose pocket being unharmed when your body is being rend into a fine paste myself. 

It's not always though--perhaps what I can do is make this only happen when `no_bodyparts` is `FALSE`. Because the default version of gibbing sorta throws your limbs and organs everywhere (but doesn't delete them). Which suggests items could very easily fall from pockets yknow?

**Comment by YakumoChen** [comment]
I think the organs and limbs are more to make gibbing look visually distinct than to necessarily save them (other than the head)

Gibbing is usually a punishment (in the case of being careless on mining) or an intentional denial (in the case of antagonism) so I'm a bit skeptical of making the effort to lessen its effects.

**Comment by vinylspiders** [comment]
> Gibbing is usually a punishment (in the case of being careless on mining) or an intentional denial (in the case of antagonism) so I'm a bit skeptical of making the effort to lessen its effects.

I hear you. I don't personally think a couple stray pocket-sized items will really do much to mitigate the 'punishment' of being gibbed but I do think the whole ninja thing is a legitimate concern.

At any rate I am not opposed to ditching this and closing the linked issue as not planned if this is going to be a problem for people.

Just my thoughts on it anyway.

**Review by lessthnthree — APPROVED** [review]

**Pull request merged**
