### PR TITLE
[s] Code for an event

### PR DESCRIPTION
**Pull request by Zonespace27**
a

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
image
 I am sure nothing will go wrong

**Comment by YakumoChen** [comment]
hmmmm I wonder what the event is from all these commits

**Comment by Zonespace27** [comment]
> hmmmm I wonder what the event is from all these commits

truly a mystery

**Comment by Zonespace27** [comment]
I can TM closed PRs

**Comment by Jamarkus127** [comment]
is almost as if the gamemode suffered the same fate...

**Comment by Zonespace27** [comment]
went well

**Pull request closed without merging**
