### PR TITLE
[Not Modular] Defibrillates bonus ore from the ORM. 

### PR DESCRIPTION
**Pull request by ShadeAware**
## About The Pull Request
Better upgrades now equates to more resources, as it was on the oldbase.

## Why It's Good For The Game
Doing literally anything right now is hell and we constantly run out of all materials. It wasn't fun in the old base when we tried it, its not going to be fun now.

## Changelog
:cl:
balance: Upgrades in the ORM actually make the output of the ORM better again.
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
counterargument: more mining slots

**Comment by ShadeAware** [comment]
> 
> 
> counterargument: more mining slots

Counter counter argument:

1. A lot of people don't play mining, so it wouldn't do anything

2. Even so, **why not both?**

**Comment by Gandalf2k15** [comment]
Yes good

**Comment by Gandalf2k15** [comment]
I suggest a test merge of this to see if it breaks game balance.

**Comment by Azarak** [comment]
> 
> 
> I suggest a test merge of this to see if it breaks game balance.

Sounds good

**Comment by ShadeAware** [comment]
> 
> 
> I suggest a test merge of this to see if it breaks game balance.

Let me know if any glaring issues pop up, and I can adjust numbers accordingly.

**Comment by Gandalf2k15** [comment]
This is being voted on. Merging will depend on vote outcome.

**Comment by Gandalf2k15** [comment]
I think we'll be denying this one. With the reason: 

"It creates an unbalanced economy due to the fact it makes a lot of other things obsolete. Having infinite resources to this extent is bad. Having finite resources is good, and will hopefully address some issues we are having just now."

You may appeal this denial in 30 days or present a change that would make this PR address the above issues. Vote outcome was 4 no and 0 yes.

**Pull request closed without merging**
