### PR TITLE
Space Hotel Updates/fixes/etc

### PR DESCRIPTION
**Pull request by GuiltyNeko**
## About The Pull Request
Big list of stuff, here we go
Changed all doors to access helpers
Added a few firelocks
Trimmed down the decal count
Added a missing disposal pipe
Added a laundry cart
Added curtains to the dorm rooms facing space
Changed the ID of the dorm locks to not conflict with the station dorms, as I'm fairly certain station dorms could lock hotel dorms, and vice versa.
Removed plating from underneath catwalk
Added more solar panels, as I was told current power was insufficient
Added Desk bells
Added a few trash cans
Removed cables that were going to APCs that probably used to exist but definitely didn't anymore
Did a pass on scubber/distro lines, replacing them with un-dirred pipes and added missing pipes, and missing scrubbers in some places
Added a disconnected comms relay to the "engineering" room, so they only have to get a link instead of build the entire machine
Added a modular engineering console for the purpose of tracking power usage
Added a gun recharger in the front office
Added a proper waste output 
Added cameras and two camera consoles, from TG's version of the hotel
Removed a strange "shortcut" in the disposals line that didn't accomplish anything
Made all lights directional variants

## How This Contributes To The Skyrat Roleplay Experience
Better hotel is better

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

There is genuinely nothing I can provide screenshots on, because it's all so damn small. Everything I've said is 100% as described.

Also suggest changelog tags, because the system is beyond me for something so large as this. (large as in so many things like how do I CL this it's so much different stuff)

### CODE REVIEW

**Comment by GuiltyNeko** [comment]
Important couple things that don't really suit being in the main PR description, I was thinking about maintenance trash piles in a couple of the areas that are two tiles wide and want feedback on that idea as long as I'm working on the space hotel.

Additionally, I was thinking it might be fitting to have buttons for the dorm locks in the Hotel Manager's office, as you might be required to remove a patron from the hotel, or whatever other reason you might have, and it would be good to have a way to do that without, you know, hacking the door, since real hotels have spare keys, and that's not something you can do with these doors buttons so easily.

**Comment by tf-4** [comment]
Just use the fix tag.
Also it may be better just to add RTGs instead of more solars, even if RTGs are cringe

**Comment by GuiltyNeko** [comment]
> even if RTGs are cringe

I did think about RTGs but avoided it for more-or-less this exact reason, plus the fact that that would take away from the available interior space, and it would have to go in the engineering area. And outside RTGs would be kinda weird.

**Comment by GuiltyNeko** [comment]
This is going to sit and rot as a draft until someone provides some kind of feedback/suggestion on the trash piles and staff manager room bolt buttons things, by the way, because I'm here doing stuff already so it's really easy to just through a couple more things in such as that. Point being, Feedback please.

**Comment by GuiltyNeko** [comment]
I do not have the energy to unconflict this, at least not right now. May revisit it at some point, sure as shit isn't gonna be any time soonish. If someone else wants to do it, blah blah blah PR to my branch and whatever, you know the deal if you're gonna put in that effort. Or just completely do it yourself on your own branch from what I've done. Either way is whatever.

**Comment by RimiNosha** [comment]
I might have a poke at this then, when I get a moment to do so!

**Pull request closed without merging**
