### PR TITLE
Akhter Company Expansion 3 | Return of CO2 cracker my wife | Steals some of the biogenerator stuff from the other pr and makes it cooler isntead

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

This pr slightly expands the collection of stuff in both the Akhter company, and in the rapid construction fabricator. So, lets take a look.

A returning classic:

image

The **CO2 Cracker**

Functions much like an electrolyzer, except its only use is turning carbon dioxide into oxygen. Handy!

image

The **Recycler**

A machine that has a simple use. Put items in, it'll crush them into materials. If the materials in it are enough to make a full sheet, then that sheet will be spat out.

(Note that the glowing bits on the next two were broken at the time of this screenshot being taken, but I've fixed them since then)

image

The **Organic Rations Printer**

An offshoot of the biogenerator system, and the ultimate kitchen buddy (if you have no other access to ingredients, that is).

image

The **Wall Med-Station**

Another offshoot of the biogenerator system, this one mounts to walls and prints basic medical supplies, doctors love it!

## How This Contributes To The Skyrat Roleplay Experience

With the same reasoning of the other PR open at the same time as this one: There's a lot of gaps and not enough niches filled by rapid construction fabricator and Akhter company stuff.

While the biogenerator in the other one is a good first step, its also REALLY bloated with items. So, instead, I've split them among two others in this PR.

The CO2 cracker and recycler allow you to do two of the most important things with limited-resources gameplay, recycle your waste. Oxygen from CO2 (which a lot of the machines from the fabricator produce), and a recycler for materials from stuff you aren't using anymore, is quite handy.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image
image

</details>

## Changelog

:cl:
add: There are several new, handy for colonization machines for sale from the Akhter company, or for manufacture in the rapid construction fabricator. These include the return of the CO2 cracker, as well as two biogenerator-like machines for making certain food items and basic medical supplies.
qol: Those of you finding yourselves stuck with the rapid construction fabricator as your only method of making and breaking things, can now rejoice at the addition of a recycler for items with materials! Simply insert enough items to make a sheet or multiple of materials, and it'll spit them out.
image: Sprites for the new machines made by me.
/:cl:

### CODE REVIEW

**Comment by Ephemeralis** [comment]
That medstation is really, *really* good. I'm actually a little bit worried about it. You may want to flat add a certain quantity of chemical isomers/other impurities to generated medpens to reflect their printed status - they'll still be good, but with some kind of tradeoff.

**Comment by Paxilmaniac** [comment]
> That medstation is really, _really_ good. I'm actually a little bit worried about it. You may want to flat add a certain quantity of chemical isomers/other impurities to generated medpens to reflect their printed status - they'll still be good, but with some kind of tradeoff.

**All** medpens already have an impurity and or chemical isomer in them. Nor are any of them particularly strong, which is why I haven't made any changes to it.

**Comment by ghost** [comment]
This printer, and the Akhter company as a whole, is quickly becoming extremely overpowered. It's a way for crew to avoid interacting with the normal suppliers, producers, or performers of basically everything. You've got it printing food and medical gear from biomass, providing engineering-grade tools and power, synthesizing chemicals, providing O2 and also cooling/heating it - the game's balance is being slashed yet in-game and in-policy it's been treated as akin to just an Autolathe, despite being able to fill nearly every niche and solve a large amount of issues that should be inciting roleplay or encouraging cooperation.

It and a majority of this content really, really should not be available outside Build-A-Station events. @GoldenAlpharex

**Comment by Paxilmaniac** [comment]
>  You've got it printing food and medical gear from biomass, providing engineering-grade tools and power, synthesizing chemicals, providing O2 and also cooling/heating

These are all things that cargo has been able to do with zero effort with their gazillions of credits every single round without trouble. The existence of a machine that lets people do things except worse on their own is such an insanely non-issue and I think you are concerning yourself too highly over it.

This, as everything I have made before, will be used extensively for a single week before people realize its easier and better to just do things normally, and it'll sit in its designed niche corner where it'll only be seen maybe one every three rounds.

**Comment by Ephemeralis** [comment]
> > That medstation is really, _really_ good. I'm actually a little bit worried about it. You may want to flat add a certain quantity of chemical isomers/other impurities to generated medpens to reflect their printed status - they'll still be good, but with some kind of tradeoff.
> 
> **All** medpens already have an impurity and or chemical isomer in them. Nor are any of them particularly strong, which is why I haven't made any changes to it.

What I was meaning to get at is that the *printed* medpens should have *more* impurities/isomers in them to reflect the fact that they're gurgleblasted chemical concoctions of dubious ilk even for DeForest's stuff. Otherwise the wall station is like, a flat 'buy this and never order pens from cargo' again kinda deal.

Also, they're pretty alright mixes! They're not like super optimal or meta or anything but they do what they say on the label for the most part and I've personally used them to considerable effect in a number of circumstances.

**Comment by Paxilmaniac** [comment]
> What I was meaning to get at is that the _printed_ medpens should have _more_ impurities/isomers in them to reflect the fact that they're gurgleblasted chemical concoctions of dubious ilk even for DeForest's stuff. Otherwise the wall station is like, a flat 'buy this and never order pens from cargo' again kinda deal.
> 
> Also, they're pretty alright mixes! They're not like super optimal or meta or anything but they do what they say on the label for the most part and I've personally used them to considerable effect in a number of circumstances.

What I'll do actually, is instead of the pens, it just dispenses from low purity healing chems directly. That'd be a bit better I think?

**Comment by Ephemeralis** [comment]
> > What I was meaning to get at is that the _printed_ medpens should have _more_ impurities/isomers in them to reflect the fact that they're gurgleblasted chemical concoctions of dubious ilk even for DeForest's stuff. Otherwise the wall station is like, a flat 'buy this and never order pens from cargo' again kinda deal.
> > Also, they're pretty alright mixes! They're not like super optimal or meta or anything but they do what they say on the label for the most part and I've personally used them to considerable effect in a number of circumstances.
> 
> What I'll do actually, is instead of the pens, it just dispenses from low purity healing chems directly. That'd be a bit better I think?

That could work - possibly dispense them as something similar to hypospray cartridges only compatible with a medstation-specific thing that it also prints? That way, when someone whips out the ratchety medstation autoinjector and shuffles out a cartridge, they can experience a moment of Akhter Company Fear for the hammering their organs are about to get.

**Pull request closed without merging**
