### PR TITLE
[15.ai] Fixes the awful ear piercing peaking volume un-normalized default announcement voice.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Replaces the announcement sounds with a fresh, good, actually properly normalized voice that uses the audio effect from the original AI voice!
Examples:
blue.ogg | https://file.house/kodc.ogg
downtoGREEN.ogg | https://file.house/MIDB.ogg
announce.ogg | https://file.house/9-Re.ogg
crew_s_called.ogg | https://file.house/1R_W.ogg
meteors.ogg | https://file.house/36HU.ogg

## "What was wrong with the old voice?"
Here's a comparison of the Red Alert announcement with my version and the Skyrat version. Mine is on top, theirs is on the bottom.

audacity_9tnnyi5A0k

Look at how much the audio is peaking, and how **loud** it is. It's insane how loud it is. It's ear piercing, and just does not sound good because of the awful echo effect applied.

Also, my audio files get the point across in 3 seconds what took 17 seconds to get across. Come on. This is basic. People can read the text. They don't need it loudly read to them by someone talking through a megaphone directly into their ears. It's immersion breaking as shit, and just infuriates everyone.

My audio files were processed with an audio pipeline designed to mimic the original SS13 announcement audio.
## How This Contributes To The Skyrat Roleplay Experience

The current default announcer is universally regarded as awful and a vast downgrade from the stock SS13 announcer. It spends SEVENTEEN SECONDS to tell us the alert level is blue. It restates things already stated by the text. It's not peaked properly. Every audio engineer I have placed these files in front of told me they are awful, terrible, and downright abysmal.

These were bad announcement files. So, I have replaced them with higher quality versions with a better voice and less fucking peaking. God, the peaking was so bad. I had to turn my fuckin volume down every single time an announcement hit because of how bad it was. Was the person who added these deaf?

## Changelog

:cl:
qol: Fixes the awful ear piercing peaking volume un-normalized default announcement voice with the help of 15.ai. Check it out at 15.ai!
/:cl:

### CODE REVIEW

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Could you put a line somewhere linking to 15.ai?
Their TOS states they require a link anywhere "within the project" (so a code comment would suffice) and to only use 15.ai for announcer voices, but yeah nah that's a bit needy. _Our old TG AI isn't an announcer though, they're our dearest friend and urh... a character! It's the playable AI!_

If you want an alternative to 15.ai you could try Uberduck.ai; they have the same terms minus the bit about only using 15.ai for announcer voices. Plus, they have Omni-Man.

I think the GLADoS line are a bit sucky, but that's just my personal opinion, I'm not going to roadblock this PR with it. Especially since what we have at the moment is so much worse. What I will say though is maybe try and regenerate the lowered to green one, because it sounds like "Lowered to... Breen." Optional but highly recommended since people are gonna meme about `Breen Alert` and I can't blame them because it's hilarious.

**Comment by Iamgoofball** [comment]
Oh, yeah, that's why I stuck 15.ai in the changelog entry. I re-genned the Breen Alert line, it sounds way better. I'm not using Uberduck for audio quality reasons, it's, uh, rough. They let folks train models for 5 seconds then slap them up. It's not great.

**Review by KathrinBailey — APPROVED** [review]
(apparently github itself counts as the project and not the contents of the project so...)

**Comment by Gandalf2k15** [comment]
Lgtm fix it later this isn't worth a test merge.

**Comment by YakumoChen** [comment]
Finally, it only took three tries to remove the 20 second text readouts

**Pull request merged**
