### PR TITLE
[modular][ready]From the River to the-

### PR DESCRIPTION
**Pull request by thestubborn**
*BZZT*

## About The Pull Request

My team of lawyers, one of whom is a blue haired cat girl has asked me to retract one of my previous code statements.
I am a great friend to the community, and I apologise to those I have hurt with my comments.

## Why It's Good For The Game

My lawyers has advised me to do this.

## Changelog
:cl:
fix: I legally cannot say.
/:cl:

### CODE REVIEW

**Comment by NotRanged** [comment]
> You currently have a negative Fix/Feature pull request delta of -69. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

Nice

**Comment by Guidesu** [comment]
> > You currently have a negative Fix/Feature pull request delta of -69. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.
> 
> Nice

image
weak

**Comment by ghost** [comment]
> 
> 
> You currently have a negative Fix/Feature pull request delta of -69. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

quick remove the CL before you lose your -69

**Comment by Guidesu** [comment]
> > You currently have a negative Fix/Feature pull request delta of -69. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.
> > quick remove the CL before you lose your -69

image
WEAK?

**Comment by thestubborn** [comment]
> 
> 
> > You currently have a negative Fix/Feature pull request delta of -69. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.
> > quick remove the CL before you lose your -69

i wanted to, but the last few prs i made, @Funce forced me to add em

**Review by Funce — APPROVED** [review]

**Comment by thestubborn** [comment]
https://www.islamic-relief.org.uk/about-us/where-we-work/palestine/
https://docs.google.com/forms/d/e/1FAIpQLSdweZIiYIHj_ejHbNcQSq47C6HW2-dyNJJr6UBt2I_5IBo0Vg/viewform

**Pull request merged**
