### PR TITLE
[MODULAR] Sets Deltastation's SM to baseline loop you'd see on Meta/Icebox

### PR DESCRIPTION
**Pull request by DuffCreeper**
## About The Pull Request
Was previously merged
https://github.com/Skyrat-SS13/Skyrat-tg/pull/3313

There are some differences but it's in the same vein

## Why It's Good For The Game
Changes marked in red
aaa

Basically the biggest change in this one compared to the last one was the freezer loop being...  weird since it had a T intersection where to the left you have space loop and the right the freezer loop like wtf?

## Changelog
:cl:
qol: Deltastation's SM has been cleaned up to have a baseline loop like Meta/Icebox
/:cl:

### CODE REVIEW

**Comment by ORCACommander** [comment]
image

top left, you added and extra scrubber and an extra pump

Apart from that no, you have pipes going through walls

**Comment by DuffCreeper** [comment]
> image
> 
> top left, you added and extra scrubber and an extra pump
> 
> Apart from that no, you have pipes going through walls

Ah heck i hate that

Anyway I don't wanna be that guy but alot of SMs do the same https://imgur.com/a/2phdTyN

Wrenches and RPDs can remove and add pipes to walls without a problem and I've got no problem with it along with other players who've used the SM

**Comment by Ghilker** [comment]
lmao why is this good for the game? you haven't said that

**Comment by Ghilker** [comment]
also yes, pipes in walls and UNDER windows. This is an very bad PR that tryes to dumb down the SM because they can't handle having layers

**Review by KathrinBailey — APPROVED** [review]
Much better for new players

**Pull request merged**
