### PR TITLE
[Semi-Modular] Icemoon hostile mobs rebalance

### PR DESCRIPTION
**Pull request by atakiya**
## About The Pull Request
Rebalanced hostile icemoon simplemobs to be less of a pain for mining.

## Why It's Good For The Game
Being ganged up on from outside your vision cone, then put on fire and smashed to dust, then waiting 20 minutes for medical to fix your body while breaking it more is not very fun.

This tries to fix that and give most people a chance against those mobs again while still keeping it difficult as the loot is quite something.

## Changelog
:cl:Avunia Takiya
balance: made ice whelps less brutal
balance: made ice demons less annoying
/:cl:

### CODE REVIEW

**Comment by atakiya** [comment]
Unsure if this is semi-modular or modular.
Core files have been commented out according to spec.

**Comment by Azarak** [comment]
May wanna wait with mob rebalances till https://github.com/Skyrat-SS13/Skyrat-tg/pull/1285 is ready

**Comment by atakiya** [comment]
> 
> 
> May wanna wait with mob rebalances till #1285 is ready

Already aware, keeping as draft for now if that is fine - if not, do close.

**Comment by Gandalf2k15** [comment]
I don't think we should really be touching these mobs as TG are doing stuff downstream as we speak. And, we want mining to be a challenge again. Let's not go back to miners having gamer gear 24/7 every shift thanks.

**Pull request closed without merging**
