### PR TITLE
[Modular] Aesthetic Additions

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Adds additional aesthetics module content for a buncha stuff that needed it. Tools, dressers, holopads, the supermatter, even PDAs!
All content was sourced from BeeStation / CEVEris / YogStation 13 / Unitystation / Tau Ceti. Absolutely love the spritework in all of these repos and the people who made them <3 - regardless, where not applicable, sprite was edited by myself. Also, yes, the seclockers are blue.
Demonstration screenshots:
image
image
image
image

## Why It's Good For The Game
Me like pretty sprite. Also, consistency.

## Changelog
:cl:
add: Aesthetics Module Additions - More stuff for your eyes to look at!
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
LEGEND

**Comment by RatFromTheJungle** [comment]
cabinet sprites, good most of the kitchen sprites- alright.
locker/freezer sprites are just a straight downgrade from TG, (lockers are the biggest offender here)
and canister sprites will probably cause some issues with TGs tiered-canisters, and if they make any changes to those

**Comment by unit0016** [comment]
They don't, uses the same overlay system. Can tweak or remove certain parts, just throwing together the ones I got working into one package.

**Comment by Gandalf2k15** [comment]
Have you made sure to cross reference each icon file with the original?

**Comment by unit0016** [comment]
yep. Did some testing, too. Every icon that I noticed was an error and didn't show up properly now points back correctly to it's original icon file.

**Review by Gandalf2k15 — APPROVED** [review]
All good!

**Comment by Vynellin** [comment]
WTF IS THE PDA!
Also the sm looks like a didlo now that you read this you cant unread this

**Comment by Vynellin** [comment]
Okay further more wtf is the cans
and WHY DOES THE HOLOPAD LOOK SO WEIRD

**Pull request merged**
