### PR TITLE
[NON-MODULAR] Restore nonmodular changes to VotePanel.tsx

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Restores the changes to VotePanel.tsx to hide vote counts. PR https://github.com/Skyrat-SS13/Skyrat-tg/pull/19666 changed where the edit needs to be.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

</details>

## Changelog

:cl: LT3
fix: Non-admins can't view the active vote counts
/:cl:

### CODE REVIEW

**Comment by Elli-Skala** [comment]
Is this still needed with the new voting system?

**Comment by lessthnthree** [comment]
Yes, ballots should still be secret.

**Comment by tf-4** [comment]
Despite having implemented this in the first place I'm not _entirely_ sure this is needed with the new vote system, but at the same time I don't feel strongly enough to block it or anything.

**Comment by lessthnthree** [comment]
That's also how little opinion I have on it. One way to solve this!

**Comment by lessthnthree** [comment]
Vote was overwhelming to keep as-is with the new system, but we can't have nice things. Players are voting for maps and changing last minute, just as they did before.

**Review by Gandalf2k15 — APPROVED** [review]
OK

**Pull request merged**
