### PR TITLE
[MODULAR] Removes the undercharger MCR attachment.

### PR DESCRIPTION
**Pull request by RatFromTheJungle**
## About The Pull Request

What it says on the tin, removes the under-charger attachment.

## How This Contributes To The Skyrat Roleplay Experience

A weapon shouldn't be quasi-non-lethal, especially considering how the charger with essentially any other laser modifying attachment leaves it, still, functionally lethal, while pretending it's not.

something something 'clarity that a laser-gun is a laser-gun'

## Changelog

:cl:
del: Removes the MCR's undercharger attachment.
/:cl:

### CODE REVIEW

**Comment by AtoriBirb** [comment]
Didn't i try to do this like three months ago

Edit: yap, #11490

**Comment by theselfish** [comment]
I want this to be merged purely for another Sec walkout.

**Comment by RatFromTheJungle** [comment]
> Didn't i try to do this like three months ago
> 
> Edit: yap, #11490

yea, i waited for the rebalance and let it sit for a month and some change, didn't fix the issues with it

**Review by Zonespace27 — APPROVED** [review]

**Review by Gandalf2k15 — APPROVED** [review]
honestly with guncargo, this isn't needed anymore

**Comment by MassacreDemigirl** [comment]
I was meaning to do this but was too lazy +1

**Pull request merged**
