### PR TITLE
Even more halloween costumes in loadout

### PR DESCRIPTION
**Pull request by ihavenoideahowtonamemyaccount**
## How This Contributes To The Skyrat Roleplay Experience

even more roundstart costumes = fun²

## Changelog

:cl:
add: even more halloween costumes options in the loadout
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
That's one hell of a long name.

**Comment by GoldenAlpharex** [comment]
Also, we're not near Halloween enough for me to merge this, we can wait until we get the roundstart Halloween species for this.

**Comment by ihavenoideahowtonamemyaccount** [comment]
> Also, we're not near Halloween enough for me to merge this, we can wait until we get the roundstart Halloween species for this.

 it's a continuation of my previous pull request, should have added that in the post :|
 #8586

**Comment by GoldenAlpharex** [comment]
> > Also, we're not near Halloween enough for me to merge this, we can wait until we get the roundstart Halloween species for this.
> 
> it's a continuation of my previous pull request, should have added that in the post :| #8586

Ah. Eh. Hmmm. I guess I'll check with Gandalf then.

I didn't want for us to have to remember to remove those later on.

**Comment by GoldenAlpharex** [comment]
I have discussed with myself for long enough and I think we're ready.

**Pull request merged**
