### PR TITLE
[Vanity] Mouse sprite accessory pack

### PR DESCRIPTION
**Pull request by desertmote**
## About The Pull Request

new ooz sprite pack just dropped, its for mice. it also features a bonus hairstyle! woahhhh!

## How This Contributes To The Skyrat Roleplay Experience

new mouse ears
mouse_new
updated coloring on old ears (tri color)
mouse_old

new mouse tail
mouse_wag

the hairstyle featured is new too

## Changelog

:cl:
imageadd: added a new long over-eye hairstyle
imageadd: added new mouse ears and updated the old
imageadd: added a new mouse tail
/:cl:

### CODE REVIEW

**Comment by HoodMilk** [comment]
More customization is always good, and multicolor mouse ears are nice

**Review by GoldenAlpharex — APPROVED** [review]
Cute!

**Comment by Nerev4r** [comment]
post this rat

**Comment by GoldenAlpharex** [comment]
I forgot to merge it last time I looked.

**Pull request merged**
