### PR TITLE
Modular languages translation keys

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Extension of https://github.com/Skyrat-SS13/Skyrat-tg/pull/14410 to include modular language translation keys

Does NOT include monkey or pirate. As I thought that was dumb. I'd rather remove those two from available languages anyways.

## How This Contributes To The Skyrat Roleplay Experience

Consistency uhhhh good

## Changelog
:cl:
add: Added translation keys for modular languages.
/:cl:

### CODE REVIEW

**Comment by desertmote** [comment]
please dont remove monkey language oh my goooOoOoOoOd

**Review by Zonespace27 — COMMENTED** [review]
Might be worth adding an ashtongue key even if it's not gonna be used

**Comment by tf-4** [comment]
> Might be worth adding an ashtongue key even if it's not gonna be used

This feature is only intended for roundstart race languages, I don't really want to make it into a balance PR around ashwalkers

**Comment by Jezzared** [comment]
> please dont remove monkey language oh my goooOoOoOoOd

I want Pirate to stay. It can be cool flavor to a character. I think we should just have less language slots by default. Just two, with linguist still granting four. Then languages will be more special.

**Comment by tf-4** [comment]
This PR isn't for talking about removing languages or lack thereof

**Pull request merged**
