### PR TITLE
Blueshift 3.0 DNM [MDB ignore]

### PR DESCRIPTION
**Pull request by IsaacTheSharkWolf**
Adds a revised version of blueshift with 2 z levels and a new whiteship.

## About The Pull Request

After a lot of work and being lazy i finally finished up the revamp of blueshift, it's got it's ass chopped off and is now only 2zs tall!
With most of the original ship preserved to the best of my ability you will still see a few overhauled sections, namely cargo and engineering which have been made from the ground up to fit the new formfactor.
Some other departments have had some improvements implemented to better suit players with roleplay opportunities specifically in mind.
Most notably is the size down of maintenance areas which are now far more streamlined and logical, with a pair of large chunks of maints jungle still up yet harder to reach up north on layer 2, this should give security far less of a painful time searching around the more shady parts of the ship.
Less interestingly i have taken some special consideration to atmospherics performance by dividing up large areas a little more, which will ensure things are far less performance intensive once there are a few breaches.

On top of that a long lost project i once had for blueshift has been revitalized and implemented, a whiteship custom made for blueshift which will now hopefully spawn alongside it's parent map.
This sizable frigate appears to have been lost after making a SOS call including some data of alien lifeforms on board.. who knows what it might be but be careful when exploring the derelict vessel.
It's cargo bays were laden with goodies when it was in transit so whatever the risk may be it'll be worth it.

I'm sorry to those who had to wait so long for this map to return, i was kinda demotivated for a while but i'm glad i got around to publishing it again, i love my little spaceship map and i hope you guys do too, i'll be happy to hear feedback when you have it.

## How This Contributes To The Skyrat Roleplay Experience

Adds a beloved map back into rotation, streamlined and updated to run better then ever (hopefully).

## Screenshots!

<details>
  Level 1 of blueshift:
  
Blueshift 3 0 lower nonets

 Level 2 of blueshift:
 
Blueshift 3 0 upper nonets

Whiteship:

Blueshift whiteship

</details>

## Proof of Testing

Screenshots below!

<details>

As for actual proof, here are some ingame screenshots.
Schermopname (1407)
Schermopname (1405)
Schermopname (1402)
Schermopname (1400)
Schermopname (1398)
Schermopname (1396)
Schermopname (1391)
Schermopname (1385)

</details>

## Changelog

:cl:
add: New map, blueshift.
add: Whiteship for blueshift.
/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
We are SO back, woo

**Review by Jolly-66 — COMMENTED** [review]
I'm going to thoroughly look over some of the code facing stuff first (config stuff and any linters) because that's more important first. 
I'll review the map in chunks coming up.

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
You need to add Blueshift to `config/maps.txt`
Please don't copy what I'm about to put here since the formatting may not be correct.

```
map blueshift
	minplayers (if applicable)
	maxplayers (if applicable)
	votable
endmap
```

PLEASE keep in mind, you don't need to set a min/max if you want. These are changed on the box depending on how things pan out. Votable is required to make the map, well, votable by players.

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
For some of these runtimes, it would be better to **read the file** in VSC as opposed to searching it in SDMM. Look at each runtime individually and determine if it would be better to do this with.

<details>
<summary> Runtime 1 </summary>
Most likely a case of stuff getting updated and old vars not being changed. It happens, and sometimes not everyone makes an Updatepaths script. Open up another map filer (or look at some already premade fluff paper) to see what the new var is.

```
[04:24:16] Runtime in preloader.dm,30: Undefined variable /obj/item/paper/var/info

  proc name: preloader load (/world/proc/preloader_load)
  src: world
  call stack:
  world: preloader load(the paper (/obj/item/paper))
  the paper (/obj/item/paper): New(the plating (90,96,3) (/turf/open/floor/plating))
  /datum/parsed_map (/datum/parsed_map): create atom(/obj/item/paper (/obj/item/paper), the plating (90,96,3) (/turf/open/floor/plating))
  /datum/parsed_map (/datum/parsed_map): build coordinate(/list (/list), the plating (90,96,3) (/turf/open/floor/plating), 1, 0, 1)
  /datum/parsed_map (/datum/parsed_map):  tgm load(1, 1, 3, 0, 1, -1e+31, 1e+31, -1e+31, 1e+31, 0, 1)
  /datum/parsed_map (/datum/parsed_map):  load impl(1, 1, 3, 0, 1, -1e+31, 1e+31, -1e+31, 1e+31, 0, 1)
  /datum/parsed_map (/datum/parsed_map): load(1, 1, 3, null, 1, null, null, null, null, null, 0, 1)
  Mapping (/datum/controller/subsystem/mapping): LoadGroup(/list (/list), "Station", "map_files/NSVBlueshift", /list (/list), /list (/list), /list (/list), 0)
  Mapping (/datum/controller/subsystem/mapping): loadWorld()
  Mapping (/datum/controller/subsystem/mapping): Initialize()
  Master (/datum/controller/master): init subsystem(Mapping (/datum/controller/subsystem/mapping))
  Master (/datum/controller/master): Initialize(10, 0, 1)
  ```
</details>

<details>
<summary> Runtime 2 </summary>
I believe this has to do with atmos sensors/atoms associated stuff. I remember running into this issue on TaleStation a few months ago and that was the problem, double check your gas monitors, injectors and vents in the gas tanks, as well as their associated monitoring consoles.

I'm not including a 3rd runtime since it seems related to this (null.return air()).

I'm by no means an exemplarily coder and merely trying to provide some guidance in digesting issues while teaching how to read and understand map lints/CI.

```
[04:26:18] Runtime in stack_trace.dm,4: addMachineryMember: Nonexistent (empty list) or null machinery gasmix added to pipeline datum from N2 to Pure which is of type /obj/machinery/atmospherics/components/binary/pump. Nearby: (145, 78, 3) (code/modules/atmospherics/machinery/datum_pipeline.dm:134)
  proc name:  stack trace (/proc/_stack_trace)
  src: null
  call stack:
   stack trace("addMachineryMember: Nonexisten...", "code/modules/atmospherics/mach...", 134)
  /datum/pipeline (/datum/pipeline): add machinery member(N2 to Pure (/obj/machinery/atmospherics/components/binary/pump))
  /datum/pipeline (/datum/pipeline): build pipeline blocking(Pure to Mix (/obj/machinery/atmospherics/components/binary/pump))
  Atmospherics (/datum/controller/subsystem/air): setup pipenets()
  Atmospherics (/datum/controller/subsystem/air): Initialize()
  Master (/datum/controller/master): init subsystem(Atmospherics (/datum/controller/subsystem/air))
  Master (/datum/controller/master): Initialize(10, 0, 1)
  ```

</details>

<details>
<summary> Log Mapping </summary>

This requires me to look at the map to fully grasp whats going on (mostly atmos issues), but they're pretty self explanatory for the most part.

You have duped APCs in areas XYZ. You also have pipe fighting, which is, you should be using smart pipes/bridge pipes (I forget what they're called) to neatly organize pipes that may be running over other pipes.

image

</details>

<details>
<summary> Cable Powernets </summary>

This is another unique mapping lint for us, which would again, require me to look at the map to grasp whats going on.

I would assume the issue here is with isolated power nets, probably being tthe power station rooms I made way back when, but they should be an A into B into C circuit (producer to storage to consumer). Investigate the area cords given.

image

</details>

**Comment by IsaacTheSharkWolf** [comment]
> 

Fixed all of these i think!

**Review by tf-4 — CHANGES_REQUESTED** [review]
Here's a brief look-over

<details>
<summary>Supermatter</summary>

This should be two pumps
image

Again here
image

This should not be here, honestly. They have the pipe from atmos, or they can drag cans across when needed.
image

</details>

<details>
<summary>Engineering</summary>

You need two RPDs at most, really. Maybe three at a push.
image

Are _six_ SMESs still necessary?
image

This is too many MODs. Two or three is fine.
image

</details>

<details>
<summary>Atmos</summary>

This is a lot of unused space.
image


I do not think it's a good idea to have the air mix tanks...
image

... directly below ordnance.
image

</details>

<details>
<summary>AI Sat</summary>

No. You cannot have the SM chamber here in the AI sat lobby. It's an enormous buff to malf AIs and allows for extremely easy RR. It needs to be moved away somehow, and I don't just mean making the glass flooring into regular tiles. The AI sat cannot be above the SM.
image

This seems a lot more secure than other AI sats with triple-layered r-walls into a turret.
image
On Meta, for example, it's two r-walls into a SMES.
image

Not really the AI sat, but a lot of this needs to go.
image

No to:
- All powertools including advanced multitool and long-range analyser
- Bluespace RPD
- ARCD
- Skillchip

</details>

<details>
<summary>Security</summary>

This is a LOT of space for a removed role
image

We run 5 sec slots currently, should be 5 lockers.
image

2-3 MODs max
image

Not entirely keen on a free funny baton
image

</details>

**Comment by biobootX** [comment]
Please don't _completely_ remove the medical ward from the brig, it's a cool flavor room.

**Comment by IsaacTheSharkWolf** [comment]
> Here's a brief look-over
> 
> Supermatter
> This should be two pumps  
> Again here 
> > This should not be here, honestly. They have the pipe from atmos, or they can drag cans across when needed. 
> 
> Engineering
> You need two RPDs at most, really. Maybe three at a push.
> Are _six_ SMESs still necessary?
> 
> This is too many MODs. Two or three is fine. 
> 
> Atmos
> This is a lot of unused space. 
> 
> I do not think it's a good idea to have the air mix tanks...
> 
> ... directly below ordnance.
> 
> AI Sat
> No. You cannot have the SM chamber here in the AI sat lobby. It's an enormous buff to malf AIs and allows for extremely easy RR. It needs to be moved away somehow, and I don't just mean making the glass flooring into regular tiles. The AI sat cannot be above the SM. 
> 
> This seems a lot more secure than other AI sats with triple-layered r-walls into a turret. On Meta, for example, it's two r-walls into a SMES.
> 
> Not really the AI sat, but a lot of this needs to go. 
> 
> No to:
> 
> * All powertools including advanced multitool and long-range analyser
> * Bluespace RPD
> * ARCD
> * Skillchip
> 
> Security
> This is a LOT of space for a removed role 
> 
> We run 5 sec slots currently, should be 5 lockers. 
> 
> 2-3 MODs max
> 
> Not entirely keen on a free funny baton 

1. pumps and n2 room
Can do, i'll fix that up real quick.

2. RPDs, six SMES units, Engineering suits.
Can do, though i'd keep the six smes units for now considering the considerable powerdraw blueshift still has.
This can always be changed later if it turns out to be wholly unnecesary.

3. Atmos.
The empty space is meant for cooling loops first and foremost, giving wiggle room for both the project room as well as the turbine and fusion engine.
As for the mix tanks.. it's certainly a little risky, but i think i might just turn the tops of those tanks into invincible variants if it turns out to be a real issue.

4. AI sat.
I don't exactly understand what's wrong with it, considering most players don't go for dusting anyways.. not to mention it'd probably delaminate the crystal on top of it.
If absolutely necessary i can *probably* scoot it down a little further, but i can't tear up the entirety of engineering and AI sat just for that.
The additional Rwall layer i can certainly thin out without too much effort however.
The tool storage can go as well, or at least be filled in with basic tools instead.

5. Security.
Sure, i'll reduce the amount of lockers and suit storage units.
It's a lot of room for an inactive role but i kinda like how it looks, i'll keep it in because it just adds more thematic fluff to security.
I don't have anything *better* to put in it's place, though if need be i can "abandon-ify" it a little.
Sure i'll remove the funny baton as well, didn't know it was *that* funny.

**Comment by Iamgoofball** [comment]
@tf-4 you guys don't have malf-AIs though, traitor rolls are disabled

also re:

```We run 5 sec slots currently, should be 5 lockers.```

this is incorrect, set it to default locker count and then add the extra locker spawn mapper helpers that we use on /tg/ maps to dynamically add new lockers based on sec pop

**Comment by Zonespace27** [comment]
> @tf-4 you guys don't have malf-AIs though, traitor rolls are disabled
> 
> 

Midround ruleset

**Comment by Iamgoofball** [comment]
@Zonespace27 did the scope on the antag disable PR change to roundstart only?

**Comment by IsaacTheSharkWolf** [comment]
Is this pertinent to the map?
There was a flaw and it's been fixed for now, i'll redo the AI sat some other time and will keep this in mind, but until then the 9 invincible tiles will stop the worst of the cheesing.
(also to clarify to those who read my response to TF-4's question regarding the atmos tanks, no i did not make the tops of them invincible, i just used R-floors for them instead, some of which have been varedited to look like normal floors for aesthetic purposes)

**Comment by Zonespace27** [comment]
> @Zonespace27 did the scope on the antag disable PR change to roundstart only?

No, malf ai's just stayed in since the PR was made

**Review by GoldenAlpharex — APPROVED** [review]
This looks good to me on a purely code perspective, it'll be good to test-merge once the Maptainer says it's good to go.

**Comment by GoldenAlpharex** [comment]
> > AI Sat
> > No. You cannot have the SM chamber here in the AI sat lobby. It's an enormous buff to malf AIs and allows for extremely easy RR. It needs to be moved away somehow, and I don't just mean making the glass flooring into regular tiles. The AI sat cannot be above the SM. image
> 4. AI sat.
>    I don't exactly understand what's wrong with it, considering most players don't go for dusting anyways.. not to mention it'd probably delaminate the crystal on top of it.
>    If absolutely necessary i can _probably_ scoot it down a little further, but i can't tear up the entirety of engineering and AI sat just for that.

It's not because most players don't do it _right now_ that they won't do it eventually. This makes it simply trivially easy, and as "cool" as it might look, I can't help but agree with tf-4 there.

**Comment by IsaacTheSharkWolf** [comment]
> It's not because most players don't do it _right now_ that they won't do it eventually. This makes it simply trivially easy, and as "cool" as it might look, I can't help but agree with tf-4 there.

Yeah, TF-4 explained it to me in greater detail and i've since made a small edit to "fix" it, right now the glass panes are invincible so you can't just deconstruct one with a RCD and call it a day.
It's not a great solution but it'll work as a stopgap until i do a rework of the sat proper, which will probably be sometime later this year if we actually start running it again.

**Comment by YakumoChen** [comment]
Since this is two Zs like tram now and the load is more bearable, will Blueshift have  proper deep space levels again?

**Comment by IsaacTheSharkWolf** [comment]
> Since this is two Zs like tram now and the load is more bearable, will Blueshift have proper deep space levels again?

Yeah, it's got space Zs enabled afaik.

**Review by Jolly-66 — COMMENTED** [review]
I'm not done with my notes, but please ensure your PR is 1:1 with master due to the Coroner being added.
(If its not merged yet, check back later)

You'll need to:
1. Remove ALL morgue trays from robotics AND any that may be in sec
2. Add coroner spawns to the medbay morgue, and organize a room for them.
3. The room should consist of: (1) beep active tray, (1) surgery table, (1) coroner vendor.
If you need a visual check the other maps.

**Comment by IsaacTheSharkWolf** [comment]
> I'm not done with my notes, but please ensure your PR is 1:1 with master due to the Coroner being added. (If its not merged yet, check back later)
> 
> You'll need to:
> 
> 1. Remove ALL morgue trays from robotics AND any that may be in sec
> 2. Add coroner spawns to the medbay morgue, and organize a room for them.
> 3. The room should consist of: (1) beep active tray, (1) surgery table, (1) coroner vendor.
>    If you need a visual check the other maps.

I'll be sure to get it set up.

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
These jobs are missing landmarks.

image

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
I'm going to structure this review by reviewing each department separately, starting with the ones I know the most about due to having a sizeable amount playtime in them between here and /tg/.

Also because I don't feel like losing about five pages worth of reviews because I closed my browser.

<details>
<summary>Medical Review</summary>

Please remove the organ harvester.
We don't need to give "round start upgrades" to departments to "make their job easier". If medical wants to become more efficient at harvesting organs, they can research the tech required and get one built.
image

Swap two of the cots in triage for statis beds. Basically, move the two stasis beds already here. This is a busy room during high stress, so doctors and patients alike shouldn't be walking all over each other creating more of an issue.
image

Please cull the pharmacy area here.
image

Remove one of these newscasters.
image

Remove the machine frame. If its there for a future autolathe, they can build it then.
image

Remove these doors. If the issue is "people getting deeper into medbay when they shouldn't", push the doors themselves back or have it be an IC issue. The doors being here is clunky, and its in a high traffic area.
image

Cryo needs to be remapped. It's a big room for what is essentially a small purpose. The sleepers also need to go. It also feels clunky with it being adjacent to the recovery ward as well.
image

The jetpack and extra MODsuit module need to go here.
image

All this excess food in the recovery ward needs to go as well. If you want to just leave a box or two of donk pockets (spawner preferably) that's fine.
image

Virology needs to be remapped. It feels clunky and mostly 1x1 halls. I know its a one man job, but it doesn't have to feel this tight.
image

The CMO office is inconsistantly secured, please fix that.
image

Also move the Laz injector to the RD office.

The aquarium is also inaccessible here.
image

All the CMOs clothes spawns in their locker, in their garment bag. Please remove this locker.
image

Stylistic nitpick but convert these material walls back to regular walls.
image

Chemistry also needs to be reinforced with its walls.

## GENERAL NOTES

The usage of reinforced directional windows needs to be reconsidered. Consider changing some to regular directional windows in the pharmacy, medbay storage and so on. This also applies to the big tile windows, but their usage cases are a little more strict (i.e don't replace the ones in pharmacy/chemistry, but medbay storage is fine).

The wall items need to be culled.
Items that share the same wall from either the same or different direction should be avoided. It's generally good practice, but some cases its inescapable (like with buttons, which are fine). See the following image for an example of what I mean (located in chemistry).
image

Final general note that'll append each of my reviews:
Despite us having mapping tools to "check what each room needs", we realistically do not need newscasters, light switches and so on in every room. Where people may be (lounging, relaxing, waiting) would be an ideal place to put them, or where groups of people would congregate. It is a news stream after all.

</details>

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
<details>
<summary> Service Review </summary>

The entire bar-kitchen duo needs to be remapped and incorporated together.
Blueshift is a big map, and people will be collecting in these areas for indeterminant amounts of time. By having these areas be open to one another, it enables more roleplay, and altogether look a lot nicer. Whether the RP is a bar brawl or someone holding a small party is up to the individuals.
image

Hydro needs excessive culling. They don't need the lab, and the garden doesn't need to be that big nor does it need the animals. Keeping the garden as the bee apiary is fine, however. Also, remove the garden define from the area. Keep it all hydro.
image

Vendor resupplies, and resupplies in general, is cargos job, not services.
image

Please reincorporate this area into the library. Having separate areas without a definable area (in game) makes it hard to track what areas which.
image

Chappy doesn't need bees, even more so when they can open the flood gates to the hall.
image

Remove the elite card, this just creates an issue of people making a mad dash for it.
image

Arcade could use a minor size reduction.
I know its cool and fun, but we don't have a lot of arcade games as it stands.
image

The wrestling arena is super out-of-the-way, and as a result, has low foot traffic for a "service" area.
Service areas are being defined as non-generic public spaces, which may include non-job specific areas, such as the wrestling arena.
image

Dorms needs a SERIOUS area culling.
It's by far, one of the top 3 areas in terms of size on Blueshift. Please subtype out areas for this.
image
image

The commissary kitchen needs its own area.
image

Same with the sauna room.
image

Please split up the barber areas, and make a barber sauna room too.
image


</details>

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
Active turfs, by the way.

```
There are 12 active turfs at roundstart caused by a difference of the air between the adjacent turfs. To locate these active turfs, go into the "Debug" tab of your stat-panel. Then hit the verb that says "Mapping Verbs - Enable". Now, you can see all of the associated coordinates using "Mapping -> Show roundstart AT list" verb.
```

**Comment by Iamgoofball** [comment]
@Jolly-66 I feel like it's killing the soul of the map to merge the bar/kitchen when we have a separate bar/kitchen on IceBox already. that does the exact same thing, but there's ways to mitigate this

Part of the big appeal of Blueshift is it's got this "luxury cruise liner retrofitted into a station" vibe to it, and the separate areas as individual "businesses" feel is great. Skyrat runs a massive pop size anyhow, these areas end up filled up no matter what with the 160-200 player rounds. Spreading things out a bit actually helps because it reduces people stepping all over eachother.

Also, the silver walls should stay in the sanitorium because the padded cell aesthetic is great. Wallrening would save this but wallening is not soon.

**Comment by AnywayFarus** [comment]
давай бро, поднажми, хочу эту карту обратно в ротацию!

**Comment by Jolly-66** [comment]
After talking with Isaac, I've decided to close this PR due to their life taking up time.

However, Isaac has said that if anyone else wants to pick this up they're more than welcomed to. 

BEFORE DOING SO HOWEVER, please reach out to me so that we may further iron out reviews that I still have, but waited for Isaac to respond to each wave to make things easier.

Please do not take this closure as me saying "I don't want Blueshift". I very much want it to return, but unfortunately, Isaac hit a snag and is too busy to complete this PR.

**Pull request closed without merging**
