### PR TITLE
Reverts the ugly monkey plant

### LINKED ISSUE #9671: Invisible potted plant in Interlink
## Round ID:
3673

## Reproduction:
The potted plant just south of the shuttle terminal in the Interlink appears to be invisible. You can shift+right-click on it to open the context menu and pick it up. Doing so will make your sprite completely invisible save for HUD elements such as MedHUD and SecHUD. This also makes it incredibly difficult for other players to click on you for combat or other functions. I spoke with an admin during the round and they confirmed that the potted plant should not be doing this according to its variables.

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
Reverts flora.dm to base TG, thereby removing the ugly awful monkey plant
The monkey plant was an undocumented change added by #6368

it's also currently broken for whatever reason so I'm doing a service by fixing the code.
closes #9671

## How This Contributes To The Skyrat Roleplay Experience

Plants are supposed to look nice. Having an aesthetic plant that looks like a horrifying crossbreed of a living animal and a bush does not serve the appealing function potted plants are supposed to have.

Furthermore it didn't make much sense anyway. It survives just fine in atmosphere that would normally kill monkies, the tanks on the sprite aren't removable, etc immersion broken please get it out of here.

## Changelog

:cl:
fix: Removed an invisible and extremely ugly plant
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
You linked the wrong bug, that's for roundstart silicon not connecting to the AI

**Comment by YakumoChen** [comment]
fixed

**Comment by Iamgoofball** [comment]
I'm positive the monkey plant is a stock tg thing

**Comment by YakumoChen** [comment]
nope, check blame

**Comment by softcerv** [comment]
I know that this technically fixes a bug, but at the same time I feel like labeling what is a removal PR as a fix in the CL feels a bit disingenuous?

**Comment by Gandalf2k15** [comment]
We're keeping the monkey

**Comment by Gandalf2k15** [comment]
And ackshually it was part of the aesthetics module

**Comment by SpaceVampire** [comment]
> And ackshually it was part of the aesthetics module

image

Are you sure about that?

**Review by Gandalf2k15 — CHANGES_REQUESTED** [review]
Leave the aesthetics flora as is and fix the code instead

**Pull request closed without merging**
