### PR TITLE
Wedding Stuff

### PR DESCRIPTION
**Pull request by Thlumyn**
## About The Pull Request

After helping with a few weddings on Skyrat, there were a couple things which were sorely missing. Namely, **wedding cakes** and a **good location.** The maps I've seen used for it had a renamed interlink area, however that also renamed the actual interlink as well, so this PR creates wedding cake items (including wedding cake slices, hemophage wedding cakes, and hemophage wedding cake slices) and with an interlink area subtype, "Event Venue" that can be renamed (eg, through specific maps on StrongDMM) without renaming the entirety of interlink. 

I've not done a pull request here before, any advice is appreciated. I don't think upstream would be too interested in the wedding cake because it's mechanically just a worse pound cake, so its only purpose is for wedding RP, which I've not seen done outside of Skyrat.

<br>

## How This Contributes To The Skyrat Roleplay Experience

Skyrat players love weddings, and having their own wedding maps, and are tired of eating plain cakes at weddings.

## Proof of Testing

<details>
<summary>Screenshots/Videos 
</summary>

 https://user-images.githubusercontent.com/102194057/235377217-b8bb7a7e-802b-4bbe-9b76-0869a1b93238.png

</details>

## Changelog

:cl:
add: Added wedding cakes
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
Maybe push this upstream?*

I know on Manuel players do roleplay weddings every once in a while. Also more food (CAKES) is always fun.

*Talking about the wedding cakes at least

**Comment by Thlumyn** [comment]
Oh, heck, I wasn't aware they did weddings on Manuel, 
Ill try to push the cake itself upstream at least.

**Comment by Jolly-66** [comment]
It's not an often occurrence, but they do happen!

**Comment by Jolly-66** [comment]
Also, for the markdown comment:

```markdown

<details>
<summary> Testing evidence </summary>

Put your stuff here!!

</details>

```

Don't put links DIRECTLY under `<summary> </summary>`, it'll bug the syntax out.

**Comment by Thlumyn** [comment]
Thanks Jolly! That was doin me a confuse

**Comment by Thlumyn** [comment]
For reference; https://github.com/tgstation/tgstation/pull/75076 
If it gets merged on tg I will modify this PR to just to be the area edit and hemophage cakes

**Comment by Jolly-66** [comment]
I fixed your proof of testing for you.

You NEED to leave a space AFTER `<summary> Proof of Testing </summary>`. That being, a NEW LINE (space UNDER)

**Comment by Gandalf2k15** [comment]
gg

**Pull request closed without merging**
