### PR TITLE
[Modular] Fixes durathread helmet disappear on muzzled people

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Makes it so muzzled can wear it. 
image

## Why It's Good For The Game

no invisible hat man.

## Changelog
:cl:
fix: Durathread hats are no longer invisible on muzzled characters.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Just set it's mutant_variants to none?

**Comment by Swiftfeather** [comment]
> Just set it's mutant_variants to none?

buuut thenn it's less modular reeeeee okay

**Comment by Gandalf2k15** [comment]
We have a file in master_files for that!

**Comment by Swiftfeather** [comment]
> We have a file in master_files for that!

oh nice

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
