### PR TITLE
TESHARI NEW SOUNDS

### PR DESCRIPTION
**Pull request by TeshariEnjoer**
## About The Pull Request

Ported resomi and teshari sounds from bay and Vore builds.

- Added new cough, scream, laugh and sneeze.

https://github.com/Skyrat-SS13/Skyrat-tg/assets/126053988/b95f376c-17f3-4b90-a6c2-e692f78869f6

https://github.com/Skyrat-SS13/Skyrat-tg/assets/126053988/712af443-2efb-4196-b760-d34bd17edf87

https://github.com/Skyrat-SS13/Skyrat-tg/assets/126053988/cba3dd5c-e57b-4844-9919-a5f3a51c58d1

https://github.com/Skyrat-SS13/Skyrat-tg/assets/126053988/68050602-9efa-4037-9dcd-753cacc22e09

## How This Contributes To The Skyrat Roleplay Experience

This PR make tehsasri much cute and adorable.

## Changelog

:cl:
add: New teshari sounds. 
sound: added four new sounds. tesharilaugh, tehsariscream, tesharicoung, tesharisneeze.
refactor: Changed teshari DNA scream.
/:cl:

### CODE REVIEW

**Comment by Low3** [comment]
squeaky toy rp squeaky toy rp

**Comment by desertmote** [comment]
Let us hear the sounds in the PR description.

**Comment by TeshariEnjoer** [comment]
> Let us hear the sounds in the PR description.

Done.

**Comment by EerieDream** [comment]
Yes.

**Comment by HoodMilk** [comment]
Somehow this makes Teshari even more annoying than they already are. Incredible.

**Comment by TeshariEnjoer** [comment]
> Somehow this makes Teshari even more annoying than they already are. Incredible.

Yes.

**Review by tf-4 — DISMISSED** [review]
That scream sound is incredibly grating, gonna need you to find an alternative of some description. The rest are fine, if a little similar.

**Comment by Namwty** [comment]
I'll be real, while sneeze/cough/laugh I guess could make sense, but dang that scream... surely there has to be something else.

**Comment by TeshariEnjoer** [comment]
> That scream sound is incredibly grating, gonna need you to find an alternative of some description. The rest are fine, if a little similar.

Check it now.

**Comment by desertmote** [comment]
Is it just me or does the laugh cut out before ending?

**Comment by TeshariEnjoer** [comment]
> Is it just me or does the laugh cut out before ending?

 It doesn't.

**Comment by Zonespace27** [comment]
Needs TM before merging

**Comment by tf-4** [comment]
> Is it just me or does the laugh cut out before ending?

it does have a very abrupt ending

**Comment by Erol509** [comment]
For me sneezing and coughing sounds the same 😞

**Pull request closed without merging**
