### PR TITLE
[Semi-Modular] Adds Omegastation to the game.

### PR DESCRIPTION
**Pull request by sergeirocks100**
## About The Pull Request

Before we begin, let me give you some background information.

Around August of 2020, on /tg/station, i began work on updating OmegaStation, bringing in 2 years worth of changes, and adding in most areas and all non-head roles.

The map went through 2 different PRs in September, and Inept ended up deciding against putting it in because he didn't want a dedicated lowpop map taking up one of the 4 in-repo map slots.

I updated it sporadically since then, until i came up with the idea of trying to get it onto Skyrat, because of how close it is to /tg/.

I spent a couple of days making needed adjustments to the map to fit the new codebase, and i think it's ready for a pull request.

I am a complete and utter outsider to Skyrat, and i can't even play there without going onto a Discord server i can't use, but i would like to see all of my hard work benefit people, and i think Omega could possibly have a warmer reception to the maintainers here than the ones on /tg/.

Now, lets get into the meaty details.

Changes:

Most of the design flaws of the original map have been fixed.

Most areas and all non-head jobs have been added in.

To-Do:

- [ ] Try to add in a gulag and courtroom, if i can find room.

- [ ] Convert the job changes ([here](https://github.com/sergeirocks100/tgstation/blob/c4d2b0cd38385107fdb8bcc905499cfd9e25aaa0/_maps/map_files/OmegaStation/job_changes.dm)) to the new JSON format (I have no clue about how to use the new format, and i will probably need someone to do it for me).

- [ ] Violate euclidean geometry and add in a holodeck.

- [ ] Move the piping out of the walls.

- [ ] Find somewhere to stuff the blueshield (or exclude it in the job changes)

Screenshot:

s22

I think it's a big improvement over the original /tg/ and Citadel versions of the map, and i think it will be far more enjoyable as a result.

I have no clue if this complies with the modularity guidelines, but i will fix what i need to if it turns out it doesn't.

Credits:

Okand: Creating Omegastation.

Me: Dragging it out of its tomb and fixing it up.

Uomo91: Helping me with the map.

Kylerace: Helping me with the map.

Citadel Station 13: A couple of rooms (Toxins, the theater in the maint bar) copied and modified from their version of the map.

## Why It's Good For The Game

While i do know that Skyrat gets incredibly high populations at all hours of the day, i think that it would be good for anybody who may want to host their own server with their friends or something of that sort, and needs a map smaller than the ones available.

## Changelog
:cl:
add: NT's decommissioned "Omega" line of stations have been put back into use.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Isn't Omega that real tiny map? I can't see this getting use except for pure meme rounds, we almost never go under 60pop on here.

**Comment by sergeirocks100** [comment]
I don't necessarily think this is for the server itself, because i know it's far too big to have the map in regular rotation.

Rather, i think it would be a good map for small, self-hosted rounds with some friends, or other situations where you have small amounts of people and you don't need a large map.

**Comment by sergeirocks100** [comment]
Considiering that it's passing CI, and i don't think i'm interfering with anything on /tg/, i think it's safe to declare this modular.

**Comment by tf-4** [comment]
After a cursory look across the map, I came up with a few things.
- Add gas miners to atmos.
- Move the Security techfab to the armoury.
- The law office seems needlessly large, as well as having rwalls at the front that seem unnecessary. You could shift the bottom wall up by one to expand the armoury a little.
- Unless I'm blind, there are no Security weapon vendors.
- Not necessarily an _issue_ as much as a design choice I don't really agree with, but the AI upload is particularly unsecure.
- What's up with these windows? image
- Tinyfans in arrivals, while I see what you're going for and I do like it, it's generally a poor design choice to have tinyfans.
- Remove cloning - replace with CMO office?
- RND servers are inconsistently walled

**Comment by sergeirocks100** [comment]
I'll go ahead and add gas miners to the atmospherics tanks.

I'll look into expanding the armory out into the law office space, and seeing if i can place in a weapons vendor and the protolathe.

I'll replace those windows with spawners.

I don't see any tiny fans in arrivals, unless you're referring to the air blockers at the escape pod bay.

I already removed the cloning bay, but i don't really see the point in cramming in a CMO's office on a map which isn't supposed to have that role.

I'll go ahead and reinforce the western wall of the server room.

**Comment by YakumoChen** [comment]
The alien role spawns are kinda iffy. They all ought to be in rooms with a vent to crawl in.

**Comment by Gandalf2k15** [comment]
We can test merge this!

**Comment by Gandalf2k15** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/4695

**Comment by AsaiasWolffe** [comment]
The SM waste pipe isnt connected so by default the sm is set to delam every round.

**Comment by Gandalf2k15** [comment]
Please update this to use smartpipes and fix the SM,  make arrivals wrok witht he new tram and centcom ferry too(see meta station)

**Pull request closed without merging**
