### PR TITLE
[READY FOR TESTING] [SEMI-MODULAR] New catwalks and maintenance goodies! And a mockup 2-z level station to display those features

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
The map is metastation with several things moved to the 2nd level and other things adjusted. Also added our exclusive rooms, such as cryogenics and blueshield's office

Currently I've commented out the plating's change to appearance as due to inheritance and smoothing, it's really tricky to make this not do issues

StrongDMM_2020-10-14_11-23-26
dreamseeker_2020-10-14_11-22-20
dreamseeker_2020-10-14_11-21-51
dreamseeker_2020-10-14_11-21-17

## Changelog
:cl:
add: Added maintenance tiles and new catwalks

add: Added METAL STATION to the rotation
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
looks real nice , good employment of  eris sprites for maint so far.

**Comment by Gandalf2k15** [comment]
very poggers

**Comment by Azarak** [comment]
a

**Comment by Azarak** [comment]
I'll revive the catwalks and such later

**Pull request closed without merging**
