### PR TITLE
[fix]fixes kilo

### PR DESCRIPTION
**Pull request by thestubborn**
## About The Pull Request

kilo has finally been fixed

## Why It's Good For The Game

kilo needed fixed

## Changelog
:cl:
fix: fixes kilo in the only way I know how
/:cl:

### CODE REVIEW

**Comment by Vizoplez** [comment]
good PR speedmerge

**Comment by FlamingLily** [comment]
Based PR

**Comment by ZephyrTFA** [comment]
While I agree wholeheartedly, document it correctly. This is a removal

**Comment by thestubborn** [comment]
> 
> 
> While I agree wholeheartedly, document it correctly. This is a removal

thats not as funny

**Comment by KathrinBailey** [comment]
errgghh
I'd close this for wasting time with misleading labeling
but I agree with it, so... :|

**Comment by thestubborn** [comment]
> 
> 
> errgghh
> I'd close this for wasting time with misleading labeling
> but I agree with it, so... :|

i mean, it DOES fix kilo

**Comment by KathrinBailey** [comment]
> > errgghh
> > I'd close this for wasting time with misleading labeling
> > but I agree with it, so... :|
> 
> i mean, it DOES fix kilo

yeah but in the same way as me banning everyone fixes LRP
or removing all code and doing hello world probably fixes integration tests failing

**Pull request closed without merging**
