### PR TITLE
[MODULAR] Re-Skyratifies TramStation

### PR DESCRIPTION
**Pull request by MassacreDemigirl**
## About The Pull Request
As per title, Adds Skyrat spesific map requirements to TramStation

## Changelog

:cl: ErdinyoBarboza
fix: TramStation is now Skyrat Compatible!
/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
Did you get rid of the var-edited lustwish in the brig of tram?

**Comment by MassacreDemigirl** [comment]
> Did you get rid of the var-edited lustwish in the brig of tram?

Yes

**Comment by MassacreDemigirl** [comment]
removed the delta edits from this

**Comment by theselfish** [comment]
Not agaaaaaaain.

Tram is a population killer on Skyrat.

**Pull request merged**
