### PR TITLE
Vox Sprites Fix One [READY FOR MERGE]

### PR DESCRIPTION
**Pull request by OctusGit**
## About The Pull Request

Fixes and gives some sprites to a few vox items that were lacking. This is the first patch to the giant project of overhauling and fixing the species.

- [x] Tophat
- [x] Dragon armor
- [x] Cowboy hat
- [x] Cowboy hat black
- [x] Cowboy hat pink
- [x] Cowboy hat white
- [x] Cowboy hat wide
- [x] Cowboy hat wide black
- [x] Cowboy hat wide security
- [ ] Green Sombrero
- [x] Vox contractor softsuit and helmet
- [x] Cowboy hat security
- [x] Blueshift armor
- [x] Blueshift helmet
- [x] Atmos gas mask
- [x] Security jumpsuit
- [x] Utility security jumpsuit
- [x] White and blue security uniform
- [x] Beekeeper hood
- [x] Grey security uniform

(I wish I could spoiler it, but I have no idea how lol.)

<Pictures>

dreamseeker_HYah1a83dl

dreamseeker_fBcsynlmuo

dreamseeker_WOOHgasKAk

dreamseeker_ZnyLRhkT8K

</details>

## How This Contributes To The Skyrat Roleplay Experience

More sprites = More clothing options.
## Changelog

:cl:
imageadd: New vox sprites ranging from security, drake armor, and cowboy hats!
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Pretty sure the sombreros are using GAGS so not sure if that'll work, hence why we ask for in-game pictures.

**Comment by OctusGit** [comment]
I'll get em in a bit.

**Comment by GoldenAlpharex** [comment]
Also [here](https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287)'s how to make spoilers, you're welcome :)

**Comment by OctusGit** [comment]
Ive added all of the hats except the sombrero, GAGS is new to me so ill work on that later. For now, ill keep the PR up and I'm actually gonna fix some of the armors.

**Comment by GoldenAlpharex** [comment]
> Ive added all of the hats except the sombrero, GAGS is new to me so ill work on that later. For now, ill keep the PR up and I'm actually gonna fix some of the armors.

Awesome, this is why we ask for in-game pictures, if you need help, feel free to ask on the Discord.

**Comment by OctusGit** [comment]
This should be good to go, I can add more stuff in a different PR but school is on my ass, so this is the first step.

**Review by GoldenAlpharex — APPROVED** [review]

**Pull request merged**
