### PR TITLE
Probably saves init time by not loading an edited centcom shuttle dock that we don't use anymore

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

Its as shrimple as that, I remade the dock when we still used centcom as the destination for the evac shuttle, but we don't anymore and jolly never fixed it.

All it does now is eliminate the shuttle docking port because I love the interlink :)) I love my corn syrup :)))

## How This Contributes To The Skyrat Roleplay Experience

The server might load like a picosecond faster because we're not doing automapper loading on this single template.

## Proof of Testing

I can't connect to my own local for some reason so proof of testing might be a while :(

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
del: The fancy CC dock won't load anymore because the shuttle doesn't actually dock there anymore
/:cl:

### CODE REVIEW

**Review by Jolly-66 — COMMENTED** [review]
I'm on mobile so take this with a grain of salt.

Make sure the shuttle dock marker isn't there.

**Comment by Paxilmaniac** [comment]
Please don't tell me that the entirety of the interlink working relied on the automapper template deleting it.

**Comment by Jolly-66** [comment]
I don't know I never tested the otherwise.

**Comment by Paxilmaniac** [comment]
Bruhhhh It fuckin is

**Review by Jolly-66 — APPROVED** [review]
image

**Pull request merged**
