### PR TITLE
removal of two "organic" traits

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
removes bimbo and sexual obsession

## How This Contributes To The Skyrat Roleplay Experience
these traits just make playing feel awkward... and they are not really too good code-wise either.

## Changelog

:cl:
del: removed bimbo and sexual obsession traits
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
No sex.

**Comment by Zonespace27** [comment]
Damn, I got PR sniped

On a serious note, also remove the bimbofication preference as well

**Comment by hugmeorelse** [comment]
What do these two traits do?

**Comment by Zonespace27** [comment]
> What do these two traits do?

Sexual obsession is an admin-only trait that makes you want to non-con a random person. It is basically regular obsessed but even weirder.

Bimbo is given on a hexacrocin OD and stops you from talking, along with skyrocketing your arousal immediately.

**Comment by YakumoChen** [comment]
> Bimbo is given on a hexacrocin OD and stops you from talking, along with skyrocketing your arousal immediately.

This is just a little disingenuous. It basically works like a lewd version of the Social Anxiety trait

I strongly disagree with the removal. I feel it could be, at worst improved. Plenty of people play with Social Anxiety and we haven't removed it yet.

Not to mention it's entirely optional to recieve in the first place (you need to OD on hexa which by itself you're only taking if you intend to scene)

**Comment by thestubborn** [comment]
> > Bimbo is given on a hexacrocin OD and stops you from talking, along with skyrocketing your arousal immediately.
> 
> This is just a little disingenuous. It basically works like a lewd version of the Social Anxiety trait
> 
> I strongly disagree with the removal. I feel it could be, at worst improved. Plenty of people play with Social Anxiety and we haven't removed it yet.
> 
> Not to mention it's entirely optional to recieve in the first place (you need to OD on hexa which by itself you're only taking if you intend to scene)

bimbo is a bit guff honestly
feel free to remake it etc etc

**Pull request merged**
