### PR TITLE
[MODULAR] Removes the NT Consultant and Barber offices from the map, converts their locker and jobspawn locations to automapper spawns in the bridge and locker room respectively.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Removes the NT Consultant and Barber offices from the map, converts their locker and jobspawn locations to automapper spawns in the bridge and locker room respectively.

Cuts down on automapper templates by 11.

## How This Contributes To The Skyrat Roleplay Experience

1. The bridge and locker room work perfectly fine for the jobs in question, and this changes very little about the jobs outside of visuals.

2. The offices added a LOT of extra automapper templates to maintain that we don't really need at all due to point 1.

Reduces the maintenance burden for the maintainers on the NT Consultant and Barber jobs by tenfold by removing the bespoke map edits to every map for them(NT Consultant didn't even have one on Kilo lmao) and replacing them with simple, easy to maintain automapper entries for their spawn points and lockers with equipment since that's all a job needs to be real and fit in with the station thematically apparently. 

If squatting in another job's shared common rooms is good enough for Orderlies, Bouncers, Engineering Guards, Science Guards, and Customs Agents, it's good enough for the NT Consultant who already has an office on CC and the Barber who can use the locker room that's already unused most rounds and has high traffic and people looking to customize their outfits already.

## Proof of Testing

dreamseeker_I5Ji4FQfNL
dreamseeker_sd0fSoeNEk

## Changelog

:cl:
qol: Removes the NT Consultant and Barber offices from the map, converts their locker and jobspawn locations to automapper spawns in the bridge and locker room respectively.
qol: The bridge and locker room work perfectly fine for the jobs in question, and this changes very little about the jobs outside of visuals.
qol: The offices added a LOT of extra automapper templates to maintain that we don't really need at all as a result.
qol: The Barber is located in the fitness room on Tram due to no locker room on Tram.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
Hell, we could reduce the locker issue by simply moving the equipment onto them by spawning, preventing people from being job changed into either job as a result since now they cannot get replacement equipment(for the barber, at least, since the NT consultant already HAS an office)

**Comment by Zergspower** [comment]
My dude we just made a whole new set of roles for that location for the NTC - and the barbershop is definitely used

**Comment by Iamgoofball** [comment]
I don't see what that has to do with anything stated in the OP of this PR. The NTC has their own office on the Interlink/CC they can use and the Barber cleanly fits into the locker room with no issues. Everything they need to do their job is present, so why do they need an automapper template?

**Comment by Zergspower** [comment]
Because the NTC is a shared job between 3 factions now, and they _do_ need an office on station, it's called RP

**Comment by Iamgoofball** [comment]
And I could easily say the same about Orderlies, Customs Agents, Engineering Guards, Science Guards, and Bouncers but maintainers made it crystal clear right here https://github.com/Skyrat-SS13/Skyrat-tg/pull/17171#issuecomment-1320968264, RP, visuals, and fitting into the space isn't a consideration when it comes to automapper templates

automapper templates that aren't 100% mandatory don't need to exist because they add overhead and maintainability, and these two templates for each map don't NEED to exist, the NT rep has their own office on the Interlink and the Barber easily fits in the locker room with automapper entries.

This PR cuts back on 11 automapper templates our mapping team no longer needs to maintain while having zero impact on the gameplay involved. The rooms work fine enough, so we don't need to replace them with bespoke rooms via automapper templates.

**Comment by Zergspower** [comment]
Asking a role to stay off station to handle duties doesnt work well with rp, and flat removing job locations that have been there makes no sense either - i'm trying to figure out what even prompted this? Stating it has zero impact to gameplay is just flat false

**Comment by Iamgoofball** [comment]
They don't need to stay off station to handle duties, they can do everything they NEED to do from the bridge as an NT consultant, all the tools they need are there. It'd be nicer for them to have an office, sure, but that's optional and maintainers made it clear that if it's optional, we don't want to roll an automapper template just because it'd be nice to have.

> i'm trying to figure out what even prompted this?

Why don't you check out the source I cited in the last post?

**Comment by Iamgoofball** [comment]
Oh, you know, I did forget a fax machine on the bridge, here let me fix that.

**Comment by Iamgoofball** [comment]
There, fax machine on the bridge, NTC is fully feature complete on the bridge and no longer needs to go back to the Interlink office.

**Comment by lessthnthree** [comment]
Why are you removing the NTC office? One example of many, if an employee wants to meet to discuss a complaint about command, there's the office. You don't say 'Come to the Interlink' or 'Come on to the bridge'

**Comment by Iamgoofball** [comment]
Did you read the prior discussion or the OP? I've answered that question already.

**Comment by lessthnthree** [comment]
> Did you read the prior discussion or the OP? I've answered that question already.

I did, and am asking why you're removing their on station presence in the form of their office.

**Comment by Zergspower** [comment]
Actually hard no from an administrative perspective, the interlink is a hard-set location of  neutrality - antags leaving the station to go talk to the NTC is off the table

**Comment by Iamgoofball** [comment]
People can talk to the NTC on station on the bridge or in any of the locations on the station. Administration has no bearing here, sort that amongst yourselves, this is entirely about maintainability.

**Comment by lessthnthree** [comment]
> People can talk to the NTC on station on the bridge or in any of the locations on the station. Administration has no bearing here, sort that amongst yourselves, this is entirely about maintainability.

"in any locations on the station" ie: the office they have that you're trying to remove?

**Comment by Iamgoofball** [comment]
>"in any locations on the station" ie: the office they have that you're trying to remove?

There is an endless supply of private locations on the station where people can discuss things confidentially, such as the Lawyer's Office which has blast shutters for a quiet discussion, or any room in maintenance, or any of the unused areas on the station that aren't frequently inhabited by the crew.

There's also PDA messages, the PDA chatrooms, passing pieces of paper along, a whispered conversation in the bar, etc. Simply get creative.

If "having a private conversation" is a mechanic of the NT rep, we've got about eighty billion ways to do that in code alone already, a physical space on the map on station to do so already exists and it's called the station itself. Shaving 11 automapper templates off the list drastically reduces the amount of work our maintainer team has to do to keep up to date with /tg/ maps.

**Comment by Iamgoofball** [comment]
Hell, we might be able to shave another 5 templates off if I switch us back to the /tg/ arrivals shuttle and make the /tg/ arrivals shuttle dock at Interlink properly

**Comment by Iamgoofball** [comment]
>"in any locations on the station" ie: the office they have that you're trying to remove?

Also, if it's really important they be in an office, then we can move them from the Bridge to the Lawyer's Office, it does everything they want.

**Comment by Iamgoofball** [comment]
Did you guys know Tram doesn't have the locker room? Wild stuff

**Comment by coffeecoffeecoffee** [comment]
I don't know about the rest of this or the conversation surrounding it, but -

"If squatting in another job's shared common rooms is good enough for Orderlies, Bouncers, Engineering Guards, Science Guards, and Customs Agents, it's good enough for the NT Consultant who already has an office on CC and the Barber who can use the locker room that's already unused most rounds and has high traffic and people looking to customize their outfits already."

...Aren't literally all of those the roles you've cited ones you designed and PR'd yourself? You're using this as context and precedent for why, now, other roles should be like this too, as though you didn't create this 'precedent' yourself, or like it exists outside of the roles you made?

**Comment by Iamgoofball** [comment]
The maintainers decided guards get to squat in someone else's office, not me. I tried to fix it and was told no. That exact misconception about the situation that you have is the problem here, but the maintainers made their decision.

**Comment by coffeecoffeecoffee** [comment]
Ah, I see.

**Comment by Iamgoofball** [comment]
Am I high or does Github not say who closed this?

**Comment by Iamgoofball** [comment]
yeah lmao I didn't even get a github email about the PR being closed, wack

**Comment by Iamgoofball** [comment]
well, I'll just reopen this PR, must be a tragic github bug

**Pull request closed without merging**
