### PR TITLE
removes reagent requirements from medicells, makes the oppressive force cell a slime extract thing

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
- removes reagent requirements from medicells
- oppressive force relocator cell thing is now made with a bluespace slime extract like the body teleporter

## How This Contributes To The Skyrat Roleplay Experience

i just did this because i saw that there was a pr that was failing unit tests b/c of this

## Changelog

:cl:
balance: Medicells no longer require reagents to print because reagent costs for lathe designs got depreciated. Rejoice.
balance: Oppressive force relocation cell is made like the body teleporter cell (with a bluespace slime extract or something).
/:cl:

### CODE REVIEW

**Review by lessthnthree — APPROVED** [review]

**Comment by lessthnthree** [comment]
Straight up removing the requirement with no balance has to be looked at.

**Comment by vinylspiders** [comment]
I feel like these should either be moved into the pill press/chem factory options or put into the crafting menu with the reagent requirements intact.

The whole point of these is the reagents within, and it doesn't make any sense to remove them. Kinda cheapens the point of chemistry.

**Comment by chemistrymain2** [comment]
> I feel like these should either be moved into the pill press/chem factory options or put into the crafting menu with the reagent requirements intact.
> 
> The whole point of these is the reagents within, and it doesn't make any sense to remove them. Kinda cheapens the point of chemistry.

TG has a PR merged  that removes the code for reagent support in protolathes.

**Comment by vinylspiders** [comment]
>TG has a PR merged that removes the code for reagent support in protolathes.

I'm aware. Not a fan of it.

Or as a compromise I guess we could just give them a little extra -something- to build. Just feels too easy now.

**Comment by HoodMilk** [comment]
Just make the lathes print an empty medicell that you craft into the other cells with chemicals (would also have the benefit of actually showing you what chems you need too)

**Comment by lessthnthree** [comment]
That could work, an empty cell and you put libital in it to make the brute cell, etc.

**Comment by lessthnthree** [comment]
> Just make the lathes print an empty medicell that you craft into the other cells with chemicals (would also have the benefit of actually showing you what chems you need too)

Let's make the medicell a subtype of hypovial, then it can be printed in the chemmaster with the chemicals inside.

**Comment by lessthnthree** [comment]
Making a cell using reagents can be done in a different PR. To keep things moving I'm okay with removing the reagents, however will be raising the material cost of the cell a bit.

**Pull request merged**
