### PR TITLE
[Semi-Modular] DS-2: Because It's Not A Feature, It's a "Map Change".

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Adds a new hybridization (bastardization?) of the syndicate ghostroles into one, to give way for other factions and stories therein. This is a full fucking station - minus some things, like xenobio and toxins. Omegastation's creaming it's jeans.
It's also connected to Interdyne. God help us.
**This PR does not include the framework in order for either of these two to be properly, quote 'valided' yet. Also, the cargo shuttle broke while making this, so no Interdyne cargo. Fuck shuttlecode. It also, by itself, does not disable Cybersun - _though the intent was very much for it to be so._**

There's also some stealth changes: Interdyne updates, pod floors are no longer.. blue. For. Whatever reason they were to begin with.
image

Full Map!:
image

## Why It's Good For The Game
Literally ever reason we tried to remove DS-1. Also Host was interested in merging everything down and letting one occasionally be valid. There isn't the framework for that last part yet but hey this is a baller start

## Changelog
:cl:
add: DS-2.
del: DS-1.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
What;'s with the unrelated map changes?

**Comment by unit0016** [comment]
> What;'s with the unrelated map changes?

Wildwest's assaultops spawners had to go byebye since I removed DS-1. Interdyne is connected so I did some brief touchups.

**Comment by Gandalf2k15** [comment]
Fix conflicts.

**Comment by Gandalf2k15** [comment]
REEE conficts

**Pull request merged**
