### PR TITLE
Updates a lot of security clothing, unifies a lot of the security blue colors that were all over the place, some other things

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

I randomly passed through the security clothing file earlier and noticed that man some of those jumpsuits had some crust to them. Since I'm between big projects right now and its friday night baby, I decided I'd give everything a good touching up and cleaning up.

The important takeaways are basically that all of the blues are more or less the same, no more hos and warden using the old peacekeeper palette, so on.

Some of the really crusty or plainly not fitting stuff I ended up removing, a rough list below:

- The big one, sol cop stuff is gone from sec because we **HAVE NOT ARE STILL ARE NOT SOLFED POLICE** we are a random private security company.
- The godawful white noise tactical uniforms for sec that weren't used anywhere
- The corrections officer's silly little hat (why does bro get a cap to rival the HOS when he is below the average secoff, hello?)

## How This Contributes To The Skyrat Roleplay Experience

Some of our stuff is starting to show its age and to be honest there's still more I need to cover, the face shield helmets are a notable example.

Everything using the same color of blue rather than some things using old peacekeeper and some things using the new sec blue was weirdly inconsistent and I assume just a holdover from someone forgetting to update everything.

## Proof of Testing

<details>
<summary>SEE HERE FOR SOME OF WHAT IT LOOKS LIKE</summary>

Some char creator previews:

Security Officer:
image

Warden:
image

Correction's Officer:
image

Head of Security:
image

Some random combinations of stuff:
image

Digitgrade support look at that:
image

</details>

## Changelog

:cl:
image: A large number of security's clothing has been unified in color palette and updated in style.
del: Some really old or unfitting security outfits, like the correction's officer's weird hat and the unusued tactical peacekeeper jumpsuit have been removed.
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
Its already conflicting how bruh

**Comment by burgerenergy** [comment]
The Solfed stuff has been re-proposed a few times as fancy looking dress uniforms, so if you just wanted to rename them...

**Comment by ghost** [comment]
image
image

Is this black palette one taken from another icon somewhere? It's very... soft. Makes it all blend together pretty badly, including with the background.
If it's taken from a TG palette then nothing to be done down here, but if not it might be worth considering trying another one

**Comment by Paxilmaniac** [comment]
> 

this is the "black sec anything cloth" palette used by anything on tg

**Comment by ghost** [comment]
> > 
> 
> this is the "black sec anything cloth" palette used by anything on tg

michael-j-fox-crying

**Comment by W4rd3nn** [comment]
Would prefer the solfed stuff to be renamed/re-flavored rather than fully removed. It's good drip.

**Review by Jolly-66 — APPROVED** [review]
Peacekeeper losing stocks

**Pull request merged**
