### PR TITLE
Aesthetic Overhaul V3.0[SEMI-MODULAR][READY]

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Due to the fact we're getting isometric walls from TG eventually I wanted to make a placeholder to get rid of the ancient OPENSS13 walls and door sprites, with some minor touch ups here and there. There have been quite a few sounds changed too.

Doors now have an ambient light and also a vis overlay light so they look far more in place. They come with all new sounds too.

The status display has been updated as well, with some animated status displays.

The walls and Rwalls have been very slightly touched up to match the door sprites.

A few of these sprites are from TauCeti station. Credit goes to them. I only refactored them.

A few come from Eris, changed by me.

### v1.0
I have added new window sprites and Rwindow sprites made by me.
### v1.5
Updated air alarm, intercom, apc and firealarm
### v1.6
Updated firedoor, mining vendor, washing machine and blast_doors.
### v2.0
newscaster DONE
bookshelf DONE
disposals chute DONE
chairs DONE
stools DONE
requests console DONE
light switch DONE
roller bed DONE
nanomed DONE
extinguisher cabnets DONE
extinguishers DONE
buttons DONE
shield generators DONE
space heater DONE
emitter DONE
field generator DONE
rad collector DONE
cameras DONE
morgue units DONE
plastic flaps Done

### V2.5
Updated lights, and given a few guns a new look.
Computer typing sounds added.

### V3.0 FINAL
Updated floors
Guns, icons and sound.
Added benches, craftable via plates.
added a special fantastic variant to the nuclear gun

## Images
OLD:
image
NEW:
image

image
image
image
image
image
image
image
image
image
image

New guns:
image

New benches:
image
image

## Changelog
:cl:
add: Added new walls, airlocks and status displayed, credit to tau ceti.
add: New windows that fit with the aesthetic. Made by me.
add: Hundreds of new sprites.
add: Lots of new sounds.
add: Craftable benches, make them using metal sheets.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Updated to include windows, will post screenshots soon.

**Comment by Gandalf2k15** [comment]
Added new rust walls and tinted windows.

**Comment by Owai-Seek** [comment]
Just some notes from what I observed with this on the live server.

- Regular Walls and most windows look fine IMO, haven't noticed any odd clipping yet.
- Reinforced Walls have some sort of weird die on top of them. Seems odd?
- I don't like the doors at all, and a few people seem to agree. The previous ones were symmetrical, and these ones are not. It just feels really -off-. They also have always-on blue lights, which clash with the yellow lights that everything else gives off, and make maintenance a lot more bright.
- I like the door opening sounds, but the beeping from a non-accessible door might get annoying, especially when people have a tendency to relentlessly spam click the doors.
- (Update 1.5) I actually like the TG Air Alarms/Intercoms, dunno why we need to swap them out.

**Comment by Gandalf2k15** [comment]
Updated to include air alarms, APC's, and intercoms. Will do fire alarm next.

**Comment by Gandalf2k15** [comment]
> Just some notes from what I observed with this on the live server.
> 
> * Regular Walls and most windows look fine IMO, haven't noticed any odd clipping yet.
> * Reinforced Walls have some sort of weird die on top of them. Seems odd?
> * I don't like the doors at all, and a few people seem to agree. The previous ones were symmetrical, and these ones are not. It just feels really -off-. They also have always-on blue lights, which clash with the yellow lights that everything else gives off, and make maintenance a lot more bright.
> * I like the door opening sounds, but the beeping from a non-accessible door might get annoying, especially when people have a tendency to relentlessly spam click the doors.
> * (Update 1.5) I actually like the TG Air Alarms/Intercoms, dunno why we need to swap them out.

It's all about continuity. We don't just change walls and leave the doors and other stuff. We're doing this properly.

**Comment by Gandalf2k15** [comment]
v1.6 new sounds all around, blastdoors, shutters, firealarms, machines, firelock QOL.

**Comment by Gandalf2k15** [comment]
Crates added.

**Comment by Gandalf2k15** [comment]
Ver 2.0 now complete.
newscaster DONE
bookshelf DONE
disposals chute DONE
chairs DONE
stools DONE
beds - Will upgrade later.
requests console DONE
light switch DONE
roller bed DONE
nanomed DONE
extinguisher cabnets DONE
extinguishers DONE
buttons DONE
shield generators DONE
space heater DONE
emitter DONE
field generator DONE
rad collector DONE
cameras DONE
morgue units DONE
watercooler later
bench Will upgrade later
E-N (corgi) port? Will do later.
plastic flaps Done
Guns - later

**Comment by Gandalf2k15** [comment]
### V2.5 pushed.
Due to TG's changes in energy guns, I have changed the name of the energy gun to energy rifle, and increased its cell to 2500 as this is your main firearm. The lasergun also gets a similar boost. As well as some sprite changes.

Updated lights.

Updated (some) guns.

**Comment by Gandalf2k15** [comment]
Computer typing sounds added.

**Comment by Gandalf2k15** [comment]
Gun updates.

**Comment by ShadeAware** [comment]
### Absolutely based.

**Comment by Owai-Seek** [comment]
I don't think something involving guns statistics should be included in a PR about changing aesthetics. That change should be atomized if it's still in the PR.

On the aspects of the aesthetics, and sound changes though.

- Fire alarm noise goes on for too long, when one goes off it's not an issue, when five or six go off, it's fucking -terrible-.
- You can't really effectively hide behind plastic flaps anymore, which might not seem important, but it is in a chase.
- I feel things are wall-mounted devices are blending into the walls way too much, especially Fire Cabinets and Intercoms.
- Concrete floors don't really feel like they match TG flooring at all.
- Still not a fan of the doors. They're just too inconsistent.

Here are some examples of what I mean. Keep in mind, I have ghost vision with these, so things that are overlapping are probably on different sides of the wall. AIR Alarms, APC's, and Console Request Boards, and hell, even intercoms, all look incredibly samey.

dreamseeker_64cs0ALP0O
image
dreamseeker_6Y5wag8FYB

**Comment by Gandalf2k15** [comment]
> I don't think something involving guns statistics should be included in a PR about changing aesthetics. That change should be atomized if it's still in the PR.
> 
> On the aspects of the aesthetics, and sound changes though.
> 
> * Fire alarm noise goes on for too long, when one goes off it's not an issue, when five or six go off, it's fucking -terrible-.
> * You can't really effectively hide behind plastic flaps anymore, which might not seem important, but it is in a chase.
> * I feel things are wall-mounted devices are blending into the walls way too much, especially Fire Cabinets and Intercoms.
> * Concrete floors don't really feel like they match TG flooring at all.
> * Still not a fan of the doors. They're just too inconsistent.
> 
> Here are some examples of what I mean. Keep in mind, I have ghost vision with these, so things that are overlapping are probably on different sides of the wall. AIR Alarms, APC's, and Console Request Boards, and hell, even intercoms, all look incredibly samey.
> 
> dreamseeker_64cs0ALP0O
> image
> dreamseeker_6Y5wag8FYB

I will sort a couple of things here, those concrete floors are not a change made by my PR. Overlapping devices is because you have ghost vision, otherwise, they look good. The point in everything being changed is to ensure continuity as much as possible. The wall-mounted objects are supposed to blend in more than having black outlines on a grey wall. Bad art design, mostly the fault of TG not updating OpenSS13 sprites and leaving them for the very reason people dislike change. We have such an inconsistent art design flow and it's irritating to the point I can't stand it anymore. Think of it like this, these objects are mass-produced by the same company so it's logical they'd use similar design choices.

**Comment by Owai-Seek** [comment]
It might make sense logistically that it all looks the same but from a gameplay standpoint, everything looking the same means you don't know what the hell you're clicking on until you commit the tiniest details to memory or examine every single thing.

The wall mounted objects on TG may not look similar, but IMO, that makes them easily distinguishable from each other. I wouldn't want my thermostat to look like my light switch. Hell, I wouldn't even mind these if they were easily distinguishable, but not standing out, and "fitting in" makes them harder to use.

**Comment by Gandalf2k15** [comment]
Removed gun balance, added new gun sounds, benches, floors, V3.0 now complete.

**Comment by BobJoga** [comment]
Looks like the old sprites which i absolutely despise, and i don't like it - but it's a net improvement over the dogshit r4407 sprites.

**Review by Azarak — APPROVED** [review]
Good bit of duplicate code on the machines UI interact, but could lead into future issues if you do call parent, so I guess that's alright

Good bit of things clashing styles with other stuff, but not like that was already the case with a lot of stuff, generally I think this is an improvement. Also the sounds and fire doors are amazing

**Comment by SmArtKar** [comment]
That stuff looks like utter bullshit and doesn't fit the style at all. People really hate it

**Comment by Gandalf2k15** [comment]
Don't post toxic comments. Thank you.

**Pull request merged**
