### PR TITLE
[SEMI-MODULAR] You can no longer attack without CI + more 

### PR DESCRIPTION
**Pull request by NullDagaf**
### Okay, the gist of it because not everyone understands code:
**If you try to attack someone without having the combat indicator on for at least two seconds, you'll get a message saying you "refrain from attacking unprepared" and end up not attacking at all.** Made sure it works for guns and spells too - no security memery.
Additionally, getting hit, be it by a projectile or in melee forces your CI up.

Also most damaging abilities have a pacifist check now.
...not sure why they didn't.

---

### Now for the code-geeks (because no one wants to check the changes, smh):
New config setting: COMBAT_INDICATOR_TIME - determines in deciseconds how long do you need to have CI on to be able to attack - 2 seconds by default. (**USE IT.**)
The requirement for CI to be on for attacking is handled by the `COMBAT_INDICATOR` config flag. If the CI is disabled, so is the check.
Modified the `set_combat_indicator()` proc to support forced CI changes. Mostly used for bypassing the CI cooldown.
New variable in `/obj/effect/proc_holder/spell` - `harmful`. Used in checks for pacifist and CI.

### This just enforces the policy.
Mechanical implementation of rules are "always" good, and it's less work for the admins about people "attacking without CI", more time for them to focus on other, possibly more important issues.

## Changelog
:cl:
balance: spells/abilities now have a pacifist/CI check
code: getting hit enables your CI
code: added a check for combat indicator being enabled - can't attack if you don't have it on for a set amount of time
config: new config flag for CI, determines how long you need to wait in CI until you can attack
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
Hardblocking people from attacking for 2 seconds for not having the indicator is a super dumb idea , especially when we allow ambushing and permanent mechanical states.

**Comment by NullDagaf** [comment]
> Hardblocking people from attacking for 2 seconds for not having the indicator is a super dumb idea , especially when we allow ambushing and permanent mechanical states.

Pretty sure ambushing still requires CI.
Quote: "Do not "jump" someone by turning on the combat indicator to immediately attack someone."
Ambushes count for that too, and I did get bwoinked once for not having CI on during an ambush. Unless you can point to somewhere in the policy that says otherwise, I'm assuming bullshit.

As for permament mechanical states, isn't that just keeping CI on all the time?

**Comment by SpaceVampire** [comment]
Having combat mode linked with the combat indicator is still stupid, given that you need to use it for a wide number of reasons that aren't at all combat related. Its not just not getting pushed, its also used used for engineering. "Ahh yes, time to make a super loud noise and flash the icon every time I want to unweld a table."

**Comment by NullDagaf** [comment]
> Having combat mode linked with the combat indicator is still stupid, given that you need to use it for a wide number of reasons that aren't at all combat related. Its not just not getting pushed, its also used used for engineering. "Ahh yes, time to make a super loud noise and flash the icon every time I want to unweld a table."

You.. can use right click to deconstruct tables.
Always could in fact, ever since the intent removal.

**Comment by RatFromTheJungle** [comment]
image
(from new antag policy)
This would mean you get an entire two seconds where even if they react, they can't fight back.

**Comment by YakumoChen** [comment]
> image
> (from new antag policy)
> This would mean you get an entire two seconds where even if they react, they can't fight back.

Running away is something they can do however, and something that is extremely effective a majority of the time.

Being cuffed in particular is something that turning combat mode on would severely punish you for, since it allows your cuffer to react appropriately.

**Comment by FlamingLily** [comment]
Ah yes, I get ambushed. Now for two seconds I must just let myself get beat to shit, okay cool my CI is ready properly, and I'm dead.

There are times when instant attacking is needed.

**Comment by FlamingLily** [comment]
> You.. can use right click to deconstruct tables.
> Always could in fact, ever since the intent removal.

Some things explicitly require combat mode, not just right clicks.

Niche example, but, using a hand labler on a rack.

**Comment by NullDagaf** [comment]
> image
> (from new antag policy)

You mean the antag policy 2.0? You know, that thing that's unfinished and not even linked in rules/any official channel?

Also jeez, if you guys have **so** much gripe with CI being triggered with combat mode I can change that back. Seems kinda redundant to me, and it will probably cause confusion for new players but alright.

**Comment by NullDagaf** [comment]
BTW, that commit also makes it so if you get hit by a sentient mob/bullet, your CI turns on automatically.

..yes, it bypasses the cooldown. No, you can't just hit yourself to skip it - that's already handled.

**Comment by FlamingLily** [comment]
> 
> 
> BTW, that commit also makes it so if you get hit by a sentient mob/bullet, your CI turns on automatically.
> 
> ..yes, it bypasses the cooldown. No, you can't just hit yourself to skip it - that's already handled.

Okay, okay, you know what, I'm liking it, actually. I think that change has pretty much solved most of my gripes with this idea.

**Comment by Owai-Seek** [comment]
I kinda feel mixed on this because it feels a bit convoluted.

Automatic toggle when being shot/hit is a + because then you know who's been attacked and who's probably shooting back, so when they run down the hall with guns drawn, people are more likely to know whats up.

Personally, I usually forget to turn both of them on. (Combat mode, AND Combat Indicator), but that kinda makes sense because I'm not in combat a lot.

Even in combat, sometimes you want to be in combat mode, and sometimes you don't, I feel.

**Comment by NullDagaf** [comment]
> I kinda feel mixed on this because it feels a bit convoluted.
> 
> Automatic toggle when being shot/hit is a + because then you know who's been attacked and who's probably shooting back, so when they run down the hall with guns drawn, people are more likely to know whats up.
> 
> Personally, I usually forget to turn both of them on. (Combat mode, AND Combat Indicator), but that kinda makes sense because I'm not in combat a lot.
> 
> Even in combat, sometimes you want to be in combat mode, and sometimes you don't, I feel.

The PR only affects combat indicator. It won't force you into combat mode or anything.
Also as a sidenote, because the check for combat mode got replaced with a CI one, no need to scramble to switch intents:tm: when you're getting attacked. And for the attackers - just turn CI on.

**Comment by RatFromTheJungle** [comment]
I would also like to know how this affects,
Nightmares, Wizards (who don't use actual in hand projectiles for the most part- or active items for most spells), abductors, and thrown objects,
there is a lot of fringe and edge cases just skipping the CD after getting hit doesn't particularly help, with the main culprit being the CD itself, 
prime ex's: that if a nightmare has his CI up while jaunting, after the first hit you're fucked anyway, or abductors having to stand around for 2s waiting for the magic timer. Not even going to mention Wizard, because that would be an entire paragraph of "this won't work, because it doesnt affect the wizards spells at all, and he can still kill willy-nilly without it."

(And this is all without mentioning the times where CI will randomly turn it off- which would reset your timer unless they happen to hit you to reproc it.)

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
This needs to not block anyone from attacking at all.
All it should do is do a to_chat to the user and then make an admin notice saying how early they attacked in deciseconds (attacking in 29 deciseconds is acceptable, even though the rules say 30).
Also, modularisation guidelines...

**Comment by NullDagaf** [comment]
> This needs to not block anyone from attacking at all.
> All it should do is do a to_chat to the user and then make an admin notice saying how early they attacked in deciseconds (attacking in 29 deciseconds is acceptable, even though the rules say 30).

Why.. not? Correct me if I'm wrong, but aren't people not allowed to attack without CI on? Why involve the admins if you can resolve things with mechanics? Besides, this is already generous, as the default wait time is two seconds, one second shorter than even ambushes.

> Also, modularisation guidelines...

GIIIIVE ME A SECOND
THOUGHT IT'D BE FINE

**Comment by NullDagaf** [comment]
> I would also like to know how this affects,
> Nightmares, Wizards (who don't use actual in hand projectiles for the most part- or active items for most spells), abductors, and thrown objects,
> there is a lot of fringe and edge cases just skipping the CD after getting hit doesn't particularly help, with the main culprit being the CD itself,
> prime ex's: that if a nightmare has his CI up while jaunting, after the first hit you're fucked anyway, or abductors having to stand around for 2s waiting for the magic timer. Not even going to mention Wizard, because that would be an entire paragraph of "this won't work, because it doesnt affect the wizards spells at all, and he can still kill willy-nilly without it."
> 
> (And this is all without mentioning the times where CI will randomly turn it off- which would reset your timer unless they happen to hit you to reproc it.)

Okay, so.

Nightmares use an armblade. Armblades are an item. This is already handled.

Wizards ~~wait we HAVE wizards?!!~~ only melee spells I can think of are Ei Nath (Which you can't react to), Flesh to Stone (Again, one tap and you drop..n't), and Mind Swap which.. Well come on, no combat here, and it puts both users to sleep regardless. Every other spell is either non-damaging in nature (jaunt, blink, teleport, spacial thingy), or makes projectiles (every wand/staff, fireball, arcane barrage, etc). Only exception I can think of are traps, and those are.. well, traps.

Abductors, well..
_flashback to that one time I got bwoinked for not waiting 3 seconds as an ayy_
I dunno man, let them have CI on.

Thrown objects, well.. thought they weren't that big of an issue. If they are, I can easily make them trigger CI too, but that would also make sorium/dark matter/explosions/whatever-else-propels-items trigger CI too.

---
As for the CI turning itself off randomly, 
### **that really sounds like a bug and not a feature.**

**Comment by RatFromTheJungle** [comment]
> Nightmares use an armblade. Armblades are an item. This is already handled.

this is not handled- the issue is them having it on first, pre-emptively, and the first hit making them 100% immune to anyone hitting back (as it destroys all that persons lights), while the other person would either have to dodge them for 2s, or get hit (which makes the nightmare immune to getting hit back)

> Wizards ~wait we HAVE wizards?!!~ only melee spells I can think of are Ei Nath (Which you can't react to), Flesh to Stone (Again, one tap and you drop..n't), and Mind Swap which.. Well come on, no combat here, and it puts both users to sleep regardless. Every other spell is either non-damaging in nature (jaunt, blink, teleport, spacial thingy), or makes projectiles (every wand/staff, fireball, arcane barrage, etc). Only exception I can think of are traps, and those are.. well, traps.

rod form, magic missile, all things that would require people to pre-emptively have CI on, or they get insta-fucked

> _flashback to that one time I got bwoinked for not waiting 3 seconds as an ayy_
> ## Thrown objects, well.. thought they weren't that big of an issue. If they are, I can easily make them trigger CI too, but that would also make sorium/dark matter/explosions/whatever-else-propels-items trigger CI too.

thrown weapons are like, leagues stronger then other ones, see throwing stars, or spears.

**Comment by NullDagaf** [comment]
> this is not handled- the issue is them having it on first, pre-emptively, and the first hit making them 100% immune to anyone hitting back (as it destroys all that persons lights), while the other person would either have to dodge them for 2s, or get hit (which makes the nightmare immune to getting hit back)

If you don't know about the nightmare, it's fair game. They hit you, and you figure out they exist - and at the same time, CI turns on.
If you do know that they're somewhere in maintenance, you have two results:
One: You want to talk/RP/whatever else. In this case, you keep the CI off, yeah?
Two: You want to "test your aim". In this case, you would probably be on guard for them. Ergo, you'd probably be ready to shoot, and likely not interested in talking. Ergo, you'd have your CI on while patrolling maints.

> rod form, magic missile, all things that would require people to pre-emptively have CI on, or they get insta-fucked

Okay, genuinely forgot about rod form. And I don't really have a solution for that, either - making the penetration (no lewds) trigger CI would also trigger it for the immovable rod, which is... undesirable.
And magic missile is a projectile, so that's handled.

> thrown weapons are like, leagues stronger then other ones, see throwing stars, or spears.

Fair enough. Coding that right now.

**Comment by RatFromTheJungle** [comment]
If you don't know about the nightmare, it's fair game. They hit you, and//
 
  you die horribly because on the first hit they become immune to return attacks from you, (unless they just so happen to be directly inside of a well lit room) - and at the same time CI turns on and you're practically in crit.

> > rod form, magic missile, all things that would require people to pre-emptively have CI on, or they get insta-fucked
> 
> Okay, genuinely forgot about rod form. And I don't really have a solution for that, either - making the penetration (no lewds) trigger CI<

 wouldn't help, rod form is an instant crit, you have to hit it pre-emptively, like a lot of other antag abilities.
> And magic missile is a projectile, so that's handled.< 

it's a hardstun, if you don't react preemptively (again), before it hits you (you get about a second to react), you're hardstunned for 3(?) seconds.

>Fair enough. Coding that right now.

if you make throwmode prevent you from throwing "damaging" items, we'll be back to when gandalf tried it with combat indicator, and every other item being unthrowable without popping CI and having six assistants jump into a random fight because red circle.

Or, if you make it proc it **after** they're hit, you might as well close the PR, because then sec could throw their batons at each other to skip the combat mode proc.

and all of this would be solved by just, removing the superficial cooldown that only serves to benefit those who find ways around it, or even better for them, to cheese it to instantly win a fight before the other can start.

**Comment by NullDagaf** [comment]
> If you don't know about the nightmare, it's fair game. They hit you, and//
> 
> you die horribly because on the first hit they become immune to return attacks from you, (unless they just so happen to be directly inside of a well lit room) - and at the same time CI turns on and you're practically in crit.
> 
> > > rod form, magic missile, all things that would require people to pre-emptively have CI on, or they get insta-fucked
> > 
> > 
> > Okay, genuinely forgot about rod form. And I don't really have a solution for that, either - making the penetration (no lewds) trigger CI<
> 
> wouldn't help, rod form is an instant crit, you have to hit it pre-emptively, like a lot of other antag abilities.
> 
> > And magic missile is a projectile, so that's handled.<
> 
> it's a hardstun, if you don't react preemptively (again), before it hits you (you get about a second to react), you're hardstunned for 3(?) seconds.
> 
> > Fair enough. Coding that right now.
> 
> if you make throwmode prevent you from throwing "damaging" items, we'll be back to when gandalf tried it with combat indicator, and every other item being unthrowable without popping CI and having six assistants jump into a random fight because red circle.
> 
> Or, if you make it proc it **after** they're hit, you might as well close the PR, because then sec could throw their batons at each other to skip the combat mode proc.
> 
> and all of this would be solved by just, removing the superficial cooldown that only serves to benefit those who find ways around it, or even better for them, to cheese it to instantly win a fight before the other can start.

Okay I am
WAY too tired to solve your complaints right now.

just as a last comment for today, if the item you get hit by deals less than 5 damage your CI doesn't toggle. Can raise that up a bit later but
NOT RIGHT NOW

**Comment by NullDagaf** [comment]
Okay, back.

> > If you don't know about the nightmare, it's fair game. They hit you, and-
> 
> you die horribly because on the first hit they become immune to return attacks from you, (unless they just so happen to be directly inside of a well lit room) and at the same time CI turns on and you're practically in crit.

...so what you're saying is, people should be able to instantly react to a threat they don't even know is there. Also it **really** sounds like you're complaining about nightmares instead of the PR itself.
 
> wouldn't help, rod form is an instant crit, you have to hit it pre-emptively, like a lot of other antag abilities.

> it's a hardstun, if you don't react preemptively (again), before it hits you (you get about a second to react), you're hardstunned for 3(?) seconds.

### ...you're complaining about **_WIZARDS_** here.

Also if it REALLY bothers you that much, I can make **combat** spells require CI. Combat to be specific, so you don't go "waah, i shouldn't need ci for item summoooon".

> if you make throwmode prevent you from throwing "damaging" items...

I considered this, but since almost every item deals damage on throw, it wouldn't really work out. I could probably add a check for if the thrown item has **some** amount of damage, but that just seems convoluted.

> Or, if you make it proc it **after** they're hit, you might as well close the PR, because then sec could throw their batons at each other to skip the combat mode proc.

Already adressed that part. If the item you're hit by deals less than 6 damage (Which I'mma raise to 11 just to cuck abusers even more), you don't have CI turned on.
Besides, this is assuming security is coordinated enough to do that, which.. You know. Is kinda ridiculous.
> and all of this would be solved by just, removing the superficial cooldown that only serves to benefit those who find ways around it, or even better for them, to cheese it to instantly win a fight before the other can start.

This is just how the policy works. You're supposed to turn on your CI and wait 5 seconds, am I not correct? 3 for ambushes.

**Comment by NullDagaf** [comment]
Okay, now damaging spells need to have CI on. As a bonus, spells (that includes mutations and abilities) have a pacifist check now.

...no really, that IS a bonus. If I'm putting a new variable in 16+ files, might as well add a 3 line change that utilizes said variable.

**Comment by GreenTea98** [comment]
remove null from your name and you're set because this is retarded

**Pull request closed without merging**
