### PR TITLE
Adds Polychromic Sweater

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Adds a polychromic commando sweater to go along with the colored ones already in-game

## Why It's Good For The Game
Choice in color variety is always nice, especially for items that had multiple colored variants anyways

## Changelog
:cl:
add: Added Polychromic Commando Sweater
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
3 colors? This looks only to be one

**Comment by ghost** [comment]
I can fix that, my bad! I had lots of trouble wrapping my head around the polychromatic code and didn't see how to make it one-color but think I might have found a solution

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by Gandalf2k15** [comment]
Check dem .dmi conflicts and then we can merge :P

**Comment by ghost** [comment]
oh fuck its worse now

**Pull request merged**
