### PR TITLE
[Modular] Cybersun Remap 😳 

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Remaps Cybersun. Yes. From the ground up this time.
Complaints Addressed:
Setup time has been reduced dramatically. No more roundstart firefight - but consequentially, not as many guns.
You know how you're supposed to set up that jail you're supposed to house people in? Yeah, nobody does. This dedicates an entire empty wing to just that.
Place is as big as Interdyne, now. Plenty of room to fuck about with without expanding the ship directly.
image

## Why It's Good For The Game
fuck u *desouls ur forgottenship.dmm*

## Changelog
:cl:
add: Cybersun has been completely remapped from the ground up.
/:cl:

### CODE REVIEW

**Comment by NullDagaf** [comment]
Jesus, that's.. **big.**

**Comment by NullDagaf** [comment]
On a more serious note.
A) Big-ass empty room. I doubt even a crackhead engineer would be able to fill it in entirety.
B) The overall shape is somewhat.. cube-y, particularly the sides. Even a one-block indent at the top would probably be enough.
C) ...why do we have engines on the top? I get you're trying to imitate energy cannons, but their description will still show up as "engines". Also, they're still looking like engines.
D)'Not enough guns. No, I mean seriously, assuming the walls aren't indestructible (I will hurt someone if they are), I could weld in: Through the sides, through the main window, through the entire backside (No. Stop the horny thoughts.)
E) Oh god I just noticed the back engine asymmetry it's killing me aaaaaaaa

**Comment by unit0016** [comment]
> A) Big-ass empty room. I doubt even a crackhead engineer would be able to fill it in entirety.

That's the point. You wouldn't slap something of long-term, irreparable importance next to a prime target to be shot, the engines. You're also supposed to construct the area to house prisoners to avoid just being able to self-antag with no effort.
> C) ...why do we have engines on the top? I get you're trying to imitate energy cannons, but their description will still show up as "engines". Also, they're still looking like engines.

If they were meant to be cannons they'd be varedits to say cannons. They're engines. It's a battlecruiser, not a transport craft, it's designed for quick adirectional movement in any possible direction at any possible angle.
> D)'Not enough guns. No, I mean seriously, assuming the walls aren't indestructible (I will hurt someone if they are), I could weld in: Through the sides, through the main window, through the entire backside (No. Stop the horny thoughts.)

They're reinforced walls, plus it's designed that way so the rear of the ship's a weakpoint in case they are actually building a prison and capturing people.
> E) Oh god I just noticed the back engine asymmetry it's killing me aaaaaaaa

HOW THE FUCK DID IT END UP THIS WAY AAAAAAA

**Comment by unit0016** [comment]
Closing this in favor of another WIP alternative.

**Pull request closed without merging**
