### PR TITLE
[NON-MODULAR] Removes Genetics

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Removes genetics from the game.

## Why It's Good For The Game

It's a job without any meaningful content, space adapt being removed was the final nail in the coffin. We need to make space for its upcoming replacement.
Some powers *may* be moved to implants, but that will be atomised.

The old labs have been abandoned! Oh no!
image

## Changelog
:cl:
del: Genetics is no longer in the game.
fix: My GBP balance was too low. This PR fixes that.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Thank you, thank you. We'll be sure to speed merge this and allow absolutely no feedback.

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by tf-4** [comment]
wait let me put fix in the changelog i want more gbp

**Comment by YakumoChen** [comment]
Is this a serious PR?

I'm strongly against this. Weren't people just posting in other PRs that genetics had multitudes of content? Where did that sentiment suddenly go?

Is there any actual planned replacement or is the department just going to be an empty room for eternity?

This PR feels antagonistic just due to the "let me make this a fix PR for points" thing.

**Comment by tf-4** [comment]
> Is this a serious PR?
> 
> I'm strongly against this. Weren't people just posting in other PRs that genetics had multitudes of content? Where did that sentiment suddenly go?
> 
> Is there any actual planned replacement or is the department just going to be an empty room for eternity?
> 
> This PR feels antagonistic just due to the "let me make this a fix PR for points" thing.

This was a joke PR done for April fools, even if the idea might be explored down the line.

**Comment by tf-4** [comment]
Closing this now until we have a clearer sense of how we want to go about doing something like this, primarily having something to fill the void because zombies ain't gonna cut it 🧟‍♂️

**Comment by YakumoChen** [comment]
oh alright. It's still test merged so there was some confusion of if it was actually being taken seriously

**Pull request closed without merging**
