### PR TITLE
[Tram] Tram better syncs to new crossing signal timing

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request
So it turns out, the horizontal_speed var is actually a delay, so the lower the number, the faster the tram goes. Higher number, slower tram! So presently we have a max speed tram that can crit or kill you, this is an oversight.

## How This Contributes To The Skyrat Roleplay Experience
We don't want a blindingly fast tram that can crit or kill you.

## Changelog

:cl: LT3
balance: Tramstation's tram speed is now better synced with the crossing lights.
/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
Disagree with this. If it's an issue with lethality, lower the change you made instead of kneecapping the tram itself.

**Comment by lessthnthree** [comment]
The tram _should_ hurt if it hits you, but needs to be a bit slower so that players can reasonably cross. We could do 0.7 to keep that risk of danger.

**Comment by Paxilmaniac** [comment]
Beware of the pipeline:
Increase lethality of the tram to basically instakill you --> We suddenly have to slow the tram because its instakilling people

What zonespace said, revert the change we made on the tram's damage if its a problem, don't slow it down.

**Comment by lessthnthree** [comment]
After a round of testing, it's only a slight speed reduction to 0.6.

**Comment by lessthnthree** [comment]
> Beware of the pipeline: Increase lethality of the tram to basically instakill you --> We suddenly have to slow the tram because its instakilling people
> 
> What zonespace said, revert the change we made on the tram's damage if its a problem, don't slow it down.

The concept is that the tram should be damaging, but the lights should give you a proper indication if it's okay to cross. The proc is only every 2 seconds, so slowing the tram a bit, not a lot, solves it.

**Comment by Zonespace27** [comment]
> > Beware of the pipeline: Increase lethality of the tram to basically instakill you --> We suddenly have to slow the tram because its instakilling people
> > What zonespace said, revert the change we made on the tram's damage if its a problem, don't slow it down.
> 
> The concept is that the tram should be damaging, but the lights should give you a proper indication if it's okay to cross. The proc is only every 2 seconds, so slowing the tram a bit, not a lot, solves it.

fix that issue instead of taking a half-measure then

**Comment by lessthnthree** [comment]
Okay.

**Comment by lessthnthree** [comment]
Increasing the subsystem processing cost on CPU by checking the crossing signals more often instead of just slowing the tram a bit that you probably wouldn't notice unless we told you.

**Comment by Iamgoofball** [comment]
you should just fix the crossing signal being inaccurate if the tram speed is adjusted, yeah

**Comment by Gandalf2k15** [comment]
Fix the crossing stuff instead, also wtf is tha file and why is it there

**Comment by lessthnthree** [comment]
I don't want to put additional load on the server by decreasing the time between when the crossing signals update, and a slight slowdown of the tram seems like a better course. 0.5 to 0.6 you're not going to notice unless you knew it happened.

**Comment by lessthnthree** [comment]
A slight change in tram speed is not worth this.

**Comment by Iamgoofball** [comment]
It's not gonna be that expensive and it's a bugfix but alright

**Pull request closed without merging**
