### PR TITLE
[MODULAR] Fixes plenty of issues on Waterkilo

### LINKED ISSUE #5907: Waterkilo mapping
## Testmerges:
Irrelevant, most likely

image

### PR DESCRIPTION
**Pull request by DuffCreeper**
## About The Pull Request

Basically the map was missing paths so solars never spawned in lmao aaaaaand waste was connected to distro
Also fixes arrivals
Fixes #5907

## Why It's Good For The Game

Okay so many fucking edits have been made on this description so i'm just going to list them.

Fixed Solars not spawning
Fixed Waste being connected to Distro
Fixed Arrivals not working
Fixed Sec not spawning with their Armadyne(TM) vendors
Fixed departments not having their dang Cargo consoles
Fixed rocks generating where the escape pods are
Failed to fix my saddness

## Changelog
:cl:
fix: Fixes #5907
fix: Fixes plenty more that I just cant list off aaa
/:cl:

### CODE REVIEW

**Comment by DuffCreeper** [comment]
Gonna actually try and get arrivals working as well

**Comment by FlamingLily** [comment]
Stick "Fixes #5907" in there so it gets done properly

**Comment by DuffCreeper** [comment]
> Stick "Fixes #5907" in there so it gets done properly

Shall do

**Comment by DuffCreeper** [comment]
YOOO BACK TO DRAFT BOIS WHY IS THERE SO MANY BROKEN THINGS HOLY FUCK

**Comment by Gandalf2k15** [comment]
Aaaaaa waterkilo wasn't really supposed to be used at all. Its more of an example of how to make a water map.

**Comment by DuffCreeper** [comment]
> Aaaaaa waterkilo wasn't really supposed to be used at all. Its more of an example of how to make a water map.

image

**Comment by Gandalf2k15** [comment]
Well, I guess this works too xD

**Comment by tobjv** [comment]
Did you fix the lack of dorm cryo?

**Comment by DuffCreeper** [comment]
> Did you fix the lack of dorm cryo?

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Pull request merged**
