### PR TITLE
Nerfs security into the ground

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

I put security on their high horse, and I'll rip them right back down.

After playing a few rounds as antagonist it's become very clear to me that I have overbuffed security by a mile. I was putting this off for a bit, but I have to.

All security rounds, aside from 12mm, have had a siginficant debuff.

I've also done away with that nasty hitscan gun.

## Changelog
:cl:
balance: Security weapons are no longer instant fight winners. Also yeeted the hitscan lasergun.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
While we're at it, can we get rid of the "holding at gunpoint" mechanic? It's just something dumb that somehow makes it so your accuracy is increased and it doesn't actually do much for roleplay. There's already some "holding at gunpoint" mechanics on /tg/, you just need to be at point-blank.

**Comment by DiscountDirtyDan** [comment]
> While we're at it, can we get rid of the "holding at gunpoint" mechanic? It's just something dumb that somehow makes it so your accuracy is increased and it doesn't actually do much for roleplay. There's already some "holding at gunpoint" mechanics on /tg/, you just need to be at point-blank.

While I'm not the most educated to comment on a gameplay perspective I would like to say from a strictly _**roleplay perspective**_ its removal would encourage people to use emotes more rather than relying on mechanics for things, which I think is cool. Plus, it lets me point at people in the halls without locking a gun onto them, which is a good benefit imo.

**Comment by Arctaisia** [comment]
> > While we're at it, can we get rid of the "holding at gunpoint" mechanic? It's just something dumb that somehow makes it so your accuracy is increased and it doesn't actually do much for roleplay. There's already some "holding at gunpoint" mechanics on /tg/, you just need to be at point-blank.
> 
> While I'm not the most educated to comment on a gameplay perspective I would like to say from a strictly _**roleplay perspective**_ its removal would encourage people to use emotes more rather than relying on mechanics for things, which I think is cool. Plus, it lets me point at people in the halls without locking a gun onto them, which is a good benefit imo.

Yep, it's a mechanic that came from Bay/Polaris, for the sole intemt of, well, holding people at gunpoint for RP. We really need to keep it.

**Comment by GoldenAlpharex** [comment]
> Yep, it's a mechanic that came from Bay/Polaris, for the sole intemt of, well, holding people at gunpoint for RP. We really need to keep it.

My problem with it is if it gives a mechanical advantage to the players, which it shouldn't.

**Comment by MLGTASTICa** [comment]
I believe the issue here is not the weapon damage themselves , but the bonus that comes from the combat update , it makes bullets deal 80% more damage , if your bullet had 15 now it gets 12 stamina damage ontop.

**Comment by KathrinBailey** [comment]
Keep in mind security are still rocking up to the fights with either 65% melee or 65% bullet damage reduction.
Having such low damage just makes each seccie tankier than a blood-red hardsuit, but now they do similar damage to some chucklefuck assistant.

**Comment by LocalizedDownpour** [comment]
If there is a way to separate like...Sec 9mm/10mm from Traitor 9mm/10mm that would be ideal.

**Comment by RatFromTheJungle** [comment]
> 
> 
> Keep in mind security are still rocking up to the fights with either 65% melee or 65% bullet damage reduction.
> Having such low damage just makes each seccie tankier than a blood-red hardsuit, but now they do similar damage to some chucklefuck assistant.

elaborate? i skimmed their stats and their gear appears to be mostly around 35-40 focused on primarily chest/head (assuming the full loadout)

**Comment by CameronWoof** [comment]
Security can no longer contest horror lings. Either pull back on these nerfs or nerf/disable horror form.

**Comment by BrotherHangyul** [comment]
Agree with Cameron, horror form is very OP. I understand it's a last resort and meant to be powerful, but being able to re-transform in the span of ~15 seconds is incredibly overpowered.

**Comment by Gandalf2k15** [comment]
> Agree with Cameron, horror form is very OP. I understand it's a last resort and meant to be powerful, but being able to re-transform in the span of ~15 seconds is incredibly overpowered.

It's 3 minutes from horror form death

**Comment by CameronWoof** [comment]
The problem is that horror lings don't die. They just stay horror form, vent crawl, and fleshmend with their new infinite chem regen.

**Comment by Gandalf2k15** [comment]
I think debuffing security isn't really something I wanna do, we'll continue powercreep instead.

**Comment by KathrinBailey** [comment]
> I think debuffing security isn't really something I wanna do, we'll continue powercreep instead.

**Time to add the new Xenomorph caste, 40mm Xeno that has an underslung grenade launcher on each arm.**
**Blob Factories will also now spawn goliaths that are three times faster than usual!**

**Pull request closed without merging**
