### PR TITLE
"Frozen Moonlight" Interdyne

### PR DESCRIPTION
**Pull request by AstraFarera**
## About The Pull Request
Replaces Interdyne bases with a dome-like, Wavefield Science designed Interdyne laboratories. 

## How This Contributes To The Skyrat Roleplay Experience
 "Developed by Wavefield Science dome-like Interdyne laboratory that was dropped like a meteorite from space and deployed at crater created by landing impact.
 An advanced laboratory itself fitted with a modular shield generator, defence perimeter turrets and external bridge."

 It is actually the same interdyne we have now, but cozy and a much handier. 
 I saw pr and some attempts to connect DS-2 with Interdyne via little ship, so i also built a landing zone for it at lavaland, if it will be needed someday, but.. im not pleased of DS-2 existance. Tired watching ds2 fullgeared admirals doing science here.
 
 
 
I playing mostly Interdyne so it's nice to improve thingys i like.. 
  For example i tired of turret placement when going to mine: removing first rocky block, watching some monster behind it and getting shot from behind is just a thing that happens over and over with every person, so i built that "external access distance" with a bridge away of turrets.. 
  Tired of current RnD department which is a place i hang the most, tired to move fabricators around every time i join cause there's no handy table for docs and experimentation tracking notepad; tired of tiny chemistry room so now its way handier.. Tired bumping lots of doors so i replaced em with futuristic energy fields that prevents air passage, but not stopping your movement 5 times when you move from Rnd to Chemistry. Also Interdyne at wiki sites comes with genetics, but there's no genetic lab we have now, as well as "new" cytology that seems suits nice to "bioweaponary" tag Interdyne wear. 
  I tried to keep most of items at place to keep it "the same interdyne that do tings people got used it to".. At least somehow.
 
  Trying to build a modular forcefield became vi last thing for me.  Current Interdyne we have requires twice as big forcefield to cover whole station and literally have no place for it.. Even if it is not really powerful, having it feels so sweet, so i built whole laboratory with shield in a middle so it perfectly covers this dome. 
 
  About lighting..  I'm really tired of those white bright unlit rooms like from "portal" game. I know that most of things i create is about tiny lights in darkness, but isn't it cozy.. For example cargo now literaly looks like a bunker enterence with that red lights and weather radar mounted onto wall.. Maybe some places way to colorful, but just look how liquid plasma glows at night at an Icebox map.. it's so wonderful.. so sweet comparing to bloody lavaland.. 
 Im really sorry if it is too dark at some places, i can not figure exact enough brightnes by myself due my eyes nature, but i have some great people that helped me out with every single department.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

</details>

## Changelog

:cl:
tweak: An Interdyne base replaced with a Wavefield Science designed dome-like Interdyne laboratory.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
How does this compare with the footprint of current interdyne?

**Comment by AstraFarera** [comment]
> How does this compare with the footprint of current interdyne?

  Oh.. Ello.. If you mean the location size, its literally the same grid bounds, except the lab itself is twice smaller, but if you mean why to change something.. Well.. 
Lots of reasons actually.. Added em into pr description.

**Comment by burgerenergy** [comment]
ORB

Nix the trees in the hallway that do not have a wall immediately behind them, imo. So the ones on the south end, mostly.

**Comment by AstralWavefieldAi** [comment]
> ORB
> 
> Nix the trees in the hallway that do not have a wall immediately behind them, imo. So the ones on the south end, mostly.

Trees becomes transparent when you pass through.. but.. sure, can do. 
image

**Comment by ghost** [comment]
Aesthetically it is a lot more pleasing to the eyes. Background wise it being a sphere like pre-built base deployed on planet like a meteorite hitting the surface sounds sick. 

The layout is a little bit awkward in certain places. mostly due to the spherical nature of the base... 
Like the really weird looking kitchen botany combo... The machines are placed awkwardly far apart from each other which probably makes cooking somewhat annoying.
The research area has a similar issue where things just seem a bit out of place having to conform to the curved wall 
And medical area suffer from the same issues as the previous two areas.

- Dorm rooms should probably get a wardrobe.
- I dont see a photocopier machine.. 
- And there isn't really a proper space to sit down and eat at the same table as someone else.
- Also no deck officer office. 

Probably more Im just not spotting right away here.. 
The forcefield is a cool addition, I like it.
The admins will probably reject this because it doesnt reduce the lavaland footprint. Personally I think a lot of the ruins that exist are a waste of space (looking at you beach bums and other visual candy ruins)

**Comment by AstraFarera** [comment]
> Aesthetically

Elooo.. Let's see..
. About simple parts.. Photocopier sounds nice and i can fit some closets at dorms.. About tables.. do it like everyone do irl - take the food to your workplace and feel nice about breaking regulations ha. About office.. i do not like having rooms that used once per year. It feels nice to work lika family with everyone at one place, just as cryo chambers at spaceships where all people like.. equal and useful ha. Mind ussp posters :D
. About merging.. well.. i guess we all can see some really weird updates and strange decisions some people made.. really weird sol weapons for example or gamedesign solutions that brings nothing but.. well.. I just suggesting thingy i made by way many people likes after lots of discussions and if it will be rejected, i can go downstream to exact server i playin. It's just nice to share.
. About machine placement.. well.. I definitely can work with a kitchen a bit, but it is really difficult to get what do you mean exactly, cause by playing this game i feel really nice with most of it, especially rnd and medical since i like.. live in here hah.. One day you should see my "experimentation tracking docs and notes" hah X) Surely i can place all of them at one tile with pixelshifting and call it a day, or.. pile em together living to way to reach em if you are playing this ghost role not alone, but.. you know.. It feels handy exactly by this way. I can move somethin if you can explain where and why exactly.. it's nice to.

**Comment by Zergspower** [comment]
I can give this a lookthrough proper on Sunday - but from the screenshots you'll need to redo the windows as floating 1 panel ones just don't look good 
image

**Comment by AstraFarera** [comment]
>  floating 1 panel ones just don't look good 

Making round things is difficult, but it's not a thing that requires map changes here, mostly because it will ruin the whole idea and cozy feelings. I think tile nature of game made by squares looks fine with squares as is, even for "round" objects, like forcefield tiles or plasma river to snow turf connections...

**Comment by gamermomentum** [comment]
A way I saw someone deal with 1 tile windows looking goofy is by giving them a liner with directionals, either internal or external. 

I dunno if that'd look good with plastitanium but it could be worth a shot.

**Comment by AstraFarera** [comment]
>worth a shot.

But.. windows can not go diagonal within one cell, like some plastitanium walls..

Lab has been built in exact shape of working modular forcefield ring which is always made of same 1 tile thickness when powered..

Making those windows like 2 tiles thick externally overlaps forcefield, expanding em internally significantly cuts the workspace and both of those solutions makin windows look really awful.. Tey all quite durable, tey have storm shutters and i literally see nothing wrong with em.

 I do not understand worldview when such little thing bothers someone, if its just tile/voxel basic game mechanic..
  If you have an exact suggestion, i can try it.

**Comment by whataboutism-alos** [comment]
Big fan of the aesthetic, particuarly the attention to detail in floor textures. I also appreciate the accessible piping, those are two issues with current Interdyne that have beeen around forever. I think a solution to the windows would just be to add a stepped window much like Tarkon's quarter-circular Lounge room. I will always be a true fan of the "rooms connected by catwalks" feel of the original Interdyne (prior to its current state where the lava got all filled in)... **But I'm a fan of this!**

**Comment by GizkaFreechman** [comment]
Remove the genetics lab, because when a mutation is discovered, all dna consoles on every Z level will register it as such, this can lead to interdyne potentially job stealing from genetics players

**Comment by whataboutism-alos** [comment]
> Remove the genetics lab, because when a mutation is discovered, all dna consoles on every Z level will register it as such, this can lead to interdyne potentially job stealing from genetics players

Could add a Z-level override for it pretty easily, just like the one for ORM linking. Worth it, considering there’s a poster literally called “Interdyne Gene Clinics”.

**Comment by SomeRandomOwl** [comment]
#24645 is likely probally going to be the preferred one here as that pr is being specifically designed to fit current policy for interdyne / ds2

**Comment by AstraFarera** [comment]
> Big fan of the aesthetic, particuarly the attention to detail in floor textures. I also appreciate the accessible piping, those are two issues with current Interdyne that have beeen around forever. I think a solution to the windows would just be to add a stepped window much like Tarkon's quarter-circular Lounge room. I will always be a true fan of the "rooms connected by catwalks" feel of the original Interdyne (prior to its current state where the lava got all filled in)... **But I'm a fan of this!**

My thanks...
..And about windows.. I really feel fine with 1 tile windows placed like that, but if it ruins someones day, changes of all windows will require forcefiled reconfiguration for more than maxed 19 radius or probably whole station rebuild.. I tried to make this lab compact and comfy with an idea of perfect shield covefage.. I feel that i can not fix windows by easy way to make it look good for everyone, i'm really sorry. 

> Could add a Z-level override for it pretty easily, just like the one for ORM linking. Worth it, considering there’s a poster literally called “Interdyne Gene Clinics”.

If it is something about coding, i've no idea how this environment works, i work with.. different stuff about gpu. 
I just made a sequence mutation here and saved it to vi console and to disc, then checked genetics console ona main station and saw nothing. But if you mean gene discovery.. well.. it used quite rarely and not trackable anyways. So.. 
Seems fine.

> #24645 is likely probally going to be the preferred one here as that pr is being specifically designed to fit current policy for interdyne / ds2

Yea, i saw it just before even trying to learn SDMM and buildin this lab, but i made no changes to code, i just offerin a pleasant station design and that's it. It is fine if it will be rejected, cause it was fun to even construct it. Also i can simply go downstream to exact server i playing and let people compare the feelings. 

And.. one more thing. It is sweet that someone finaly tried to make an interdyne-ds2 shuttle to bloody work, cause having quantum pad deels just.. wrong.

**Comment by whataboutism-alos** [comment]
> My thanks... ..And about windows.. I really feel fine with 1 tile windows placed like that, but if it ruins someones day, changes of all windows will require forcefiled reconfiguration for more than maxed 19 radius or probably whole station rebuild.. I tried to make this lab compact and comfy with an idea of perfect shield covefage.. I feel that i can not fix windows by easy way to make it look good for everyone, i'm really sorry.

Ah okay, if the forcefield prevents it then it is what it is. As long as the windows don't fail to retain air pressure. I've seen that in a few cases of diagonal windows built mid-round. Imagine roundstart would be a bit more robust though.

**Comment by burgerenergy** [comment]
> #24645 is likely probally going to be the preferred one here as that pr is being specifically designed to fit current policy for interdyne / ds2

This has a place for the Icemoon, where DS-2 is not relevant and Interdyne can be wholly independent. So that's fine.

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by fabelsascha** [comment]
And then Skyrat up died, rendering all of this work pretty moot

**Pull request merged**
