### PR TITLE
[Modular] Interdyne Remap

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Remaps Interdyne to be more Metroid Zero Mission and Less Metroid Fusion. I'm testing out my style for NSS Maelstrom, my hobbyist project original map.
image

## Why It's Good For The Game
Current design is just kinda meh honestly. But this.. this is good.

## Changelog
:cl:
add: Interdyne has been remapped from the ground up.
/:cl:

### CODE REVIEW

**Comment by capsaicinz** [comment]
i actually enjoy this pretty thoroughly. the whole central vault area is neato, but a few plants or benches (or heck, even a vending machine or two) would definitely spruce it up in my opinion. based and syndiepilled.

**Comment by Elli-Skala** [comment]
doubt this was intentional but seems xenobio along with getting smaller also doesnt have a monkey recycler, along side any bio hazard lockers

**Comment by NullDagaf** [comment]
Metroid Fusion was the better one and you know it

**Comment by dekunutkid** [comment]
Can we get a welder and water tank in there? there's no way of filling welding tools or fire extinguishers outside of those, unless I'm completely mistaken.

**Comment by unit0016** [comment]
> Metroid Fusion was the better one and you know it

the aesthetic was kinda killer doe...
image

**Pull request merged**
