### PR TITLE
Ports monophobia and light sensitivity from Citadel.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

Ports monophobia and light sensitivity from Citadel.

## Why It's Good For The Game

More snowflake traits, also both of these were in the original Skyrat.

## Changelog
:cl:
add: quirks from Citadel
/:cl:

### CODE REVIEW

**Comment by ShadeAware** [comment]
image

**Comment by ShadeAware** [comment]
Remember to compile and run your builds, and check for runtime errors ingame using the Dream Daemon console.

**Comment by Gandalf2k15** [comment]
aaaaaaaaaaaaaaaaaa please do this modularly

**Comment by ghost** [comment]
> aaaaaaaaaaaaaaaaaa please do this modularly

...what does that mean?

**Comment by Useroth** [comment]
@TheSpaghetti https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/modular_skyrat/readme.md

If you encounter any trouble with it or got any questions, ping us on the discord, we're always happy to help.

**Comment by Gandalf2k15** [comment]
As we've said, please do this modularly, and remake the PR.

**Pull request closed without merging**
