### PR TITLE
[MODULAR] You know what? Bonk you *removes your baton*

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request
~~tired of seeing security officers with stun batons, I've already said it. Now if they want it they have to work for it, and contribute to the station with bounties in the process.. It now costs 4,000 credits. Obtainable after a few bounties, but nobody should be able to get it early or midround without effort.~~

Removes nightstick conversion kit from sec vendor.

## Why It's Good For The Game
Secoffs could basically buy these almost right away. No bueno. Make them wait until science researches it mid-late round.

## Changelog
🆑
balance: Nightstick conversion kits can no longer be purchased from vendors
/🆑

### CODE REVIEW

**Comment by YakumoChen** [comment]
4000 is a little excessive and unrealistic compared to prices of pretty much every other premium item on the station. That's more than most entire cargo crates.

Reducing the stock also doesn't make a lot of sense when it's paired with the price nerf.

**Comment by Swiftfeather** [comment]
> 4000 is a little excessive and unrealistic compared to prices of pretty much every other premium item on the station. That's more than most entire cargo crates.
> 
> Reducing the stock also doesn't make a lot of sense when it's paired with the price nerf.

Sorry I'll fix it

**Comment by Swiftfeather** [comment]
@YakumoChen fixed.

**Comment by Vizoplez** [comment]
This literally just does nothing and provokes sec into using stuff like stunprods. No bueno. Balance the item itself instead of pressing backspace.

**Comment by FlamingLily** [comment]
> 
> 
> This literally just does nothing and provokes sec into using stuff like stunprods. No bueno. Balance the item itself instead of pressing backspace.

Agreed.

Improve, don't remove, as they say.

The fact that any stun currently wins a battle in one hit also doesn't help.

**Comment by Gandalf2k15** [comment]
list format reeee

**Comment by hugmeorelse** [comment]
@Yawet330 @FlamingLily  While I agree, keep it to an objective discussion and keep any extraneous opinions and sass to yourself.


**Ex:**
The following comment you made isn't that bad, but it's a slippery slope and I want to set the boundaries firmly.
> This literally just does nothing and provokes sec into using stuff like stunprods. No bueno. Balance the item itself instead of pressing backspace.

to

"Increasing the price may cause security to look for alternatives like stun-prod which will not solve the problem. Please balance the item instead to prevent that."

**Alternative Ex:**

> 4000 is a little excessive and unrealistic compared to prices of pretty much every other premium item on the station. That's more than most entire cargo crates.
> 
> Reducing the stock also doesn't make a lot of sense when it's paired with the price nerf.

This critique by @YakumoChen minimizes all of which I talk about, and it gets its message across strongly and just fine.

**Comment by YakumoChen** [comment]
Considering my terrible reputation for github comments its nice to know comments like that tell me im improving in my attempts to be less monumentally shitty, thanks

**Comment by YakumoChen** [comment]
Related to the PR I changed to a 👍 because the item is researchable regardless.

Having them available in the clothing vendor never made any sense anyway.

**Comment by Gandalf2k15** [comment]
Ok

**Pull request merged**
