### PR TITLE
Removes the plushie of a Minecraft Youtuber from the code.

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request

Title.

## How This Contributes To The Skyrat Roleplay Experience

We really shouldn't have stuff celebrating these kinds of people in the code. Or anywhere, really!

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog
:cl:
del: Minecraft Youtuber plush is gone.
/:cl:

### CODE REVIEW

**Comment by SpaceLoveSs13** [comment]
Who even is this?

**Comment by theselfish** [comment]
> Who even is this?

 Seldaris something.

**Review by SpaceLoveSs13 — CHANGES_REQUESTED** [review]
Fix all the dme edits please.

**Comment by theselfish** [comment]
> Fix all the dme edits please.

Whoops!

**Review by SpaceLoveSs13 — APPROVED** [review]

**Pull request merged**
