### PR TITLE
[MODULAR] Pride Flag Capes and Pins

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

Does what it says on the tin.

### Capes
Bi:
image

Rainbow:
image

Trans:
image

Ace:
image

Enby:
image

Pan:
image

### Pins

Rainbow:
image

Bi:
image

Pan:
image

Trans:
image

Ace;
image

Enby:

image

## How This Contributes To The Skyrat Roleplay Experience

“I believe that telling our stories, first to ourselves and then to one another and the world, is a revolutionary act.” – Janet Mock

## Changelog

:cl:
add: Pride Pins and Capes
imageadd: Corresponding Sprites
/:cl:

### CODE REVIEW

**Comment by axietheaxolotl** [comment]
image

here's proof of it working in game

**Comment by softcerv** [comment]
yooooooo based af

**Comment by dawsonkeyes** [comment]
I’d love the capes if they weren’t fucking chess boards please god make them solid stripes, I’m all for gay chess but yknow

**Comment by dawsonkeyes** [comment]
also consider an upstream pr, oranges would totally add this

**Comment by ghost** [comment]
> 
> 
> I’d love the capes if they weren’t fucking chess boards please god make them solid stripes, I’m all for gay chess but yknow

yea, the capes' checkers were throwing me off. those pins are amazing though.

Also, dont forget that the pins can have a 'Fandom' or whatever its called HuD icon, let you see others wearing pins. Mime/Clown pins use it.

**Comment by AveonaRoot** [comment]
Still didn't getting how this will improve RP and why it missed straight pin but yeah,  let's add another useless junk.

**Comment by tf-4** [comment]
^ weird

OK uhhh just two things

1. The checkerboard effect is weird imo. Pins look good.

2. Put pictures of the sprites _in game_ in the PR body, not in the spriting software

**Comment by Pascal125** [comment]
Add a Hetero pin and Cape. Where is Transgender. Where is Pansexual? Where is Nonbinary? Where is Lesbian? Where is Asexual? What about Demisexual? What about Agender? Where is Genderfluid? And what about Genderqueer? Aromantic? Polyamorous?

If we're gonna add useless bloat, it might as well be inclusive.

**Comment by Arctaisia** [comment]
I love these, though perhaps tone down the checkered pattern a bit! Otherwise, pins are amazing, time to replace my NTRep badge with a trans pride pin,,

Edit: Also yes, as Dawson said, upstream would love these <3

**Comment by tf-4** [comment]
> Add a Hetero pin and Cape. Where is Transgender. Where is Pansexual? Where is Nonbinary? Where is Lesbian? Where is Asexual? What about Demisexual? What about Agender? Where is Genderfluid? And what about Genderqueer? Aromantic? Polyamorous?
> 
> If we're gonna add useless bloat, it might as well be inclusive.

Wyci

**Comment by ghost** [comment]
> 
> 
> Add a Hetero pin and Cape. Where is Transgender. Where is Pansexual? Where is Nonbinary? Where is Lesbian? Where is Asexual? What about Demisexual? What about Agender? Where is Genderfluid? And what about Genderqueer? Aromantic? Polyamorous?
> 
> If we're gonna add useless bloat, it might as well be inclusive.

trans is LITERALLY in there but ok

**Comment by Pascal125** [comment]
> > Add a Hetero pin and Cape. Where is Transgender. Where is Pansexual? Where is Nonbinary? Where is Lesbian? Where is Asexual? What about Demisexual? What about Agender? Where is Genderfluid? And what about Genderqueer? Aromantic? Polyamorous?
> > If we're gonna add useless bloat, it might as well be inclusive.
> 
> Wyci

Can you maybe not be insensitive, or i'll report you to Github. Thanks.

**Comment by Stalkeros2** [comment]
https://github.com/Baystation12/Baystation12/pull/29900

**Comment by axietheaxolotl** [comment]
I'm not gonna add Straight Pins, you cannot stop bringing it up, because it's not gonna happen, at all. You're not funny.

**Comment by axietheaxolotl** [comment]
> Add a Hetero pin and Cape. Where is Transgender. Where is Pansexual? Where is Nonbinary? Where is Lesbian? Where is Asexual? What about Demisexual? What about Agender? Where is Genderfluid? And what about Genderqueer? Aromantic? Polyamorous?

You said this is hyperbole, and as a strawman, I assume, but I'd be more then willing to actually do it. For this PR, I just wanted the "base" sexualities down, if that makes any sense. But later down the line? Sure, I'd be more then willing to add more specific pride pins (or just add them yourself.)

Also, Trans, Pan, Enby, Ace pins exist, so I am not sure what you're talking about?

**Comment by Seris02** [comment]
> > > Add a Hetero pin and Cape. Where is Transgender. Where is Pansexual? Where is Nonbinary? Where is Lesbian? Where is Asexual? What about Demisexual? What about Agender? Where is Genderfluid? And what about Genderqueer? Aromantic? Polyamorous?
> > > If we're gonna add useless bloat, it might as well be inclusive.
> > 
> > 
> > Wyci
> 
> Can you maybe not be insensitive, or i'll report you to Github. Thanks.

How was that insensitive? WYCI means “when you code it”, ie, code it in yourself if you want it in the game

**Comment by ghost** [comment]
> How was that insensitive? WYCI means “when you code it”, ie, code it in yourself if you want it in the game

They're victimizing themselves, dont give them the attention they're egging for.
They arent even from our server ffs.

**Comment by Pascal125** [comment]
> > How was that insensitive? WYCI means “when you code it”, ie, code it in yourself if you want it in the game
> 
> They're victimizing themselves, dont give them the attention they're egging for

Oh yes, because wanting representation and respect for all people is victimization. Reported. Go troll somewhere else.

**Comment by Arctaisia** [comment]
> > > How was that insensitive? WYCI means “when you code it”, ie, code it in yourself if you want it in the game
> > 
> > They're victimizing themselves, dont give them the attention they're egging for
> 
> Oh yes, because wanting representation and respect for all people is victimization. Reported. Go troll somewhere else.

The reason that straight pride is not included, is mostly due to the past. These groups are represented, as they were, and in some places still are, persecuted for their identity, which is morally wrong. We know that being trans comes down to genetics and upbringing, thinhs they cannot change, so does pretty much everything in the LGBTQ+ community. The movement is to encourage people to support these minorities, and so far, has fortunately worked.

The reason straight pride is not included,is because straights were not persecuted the same way other groups were in the past. They're a majority, and most don't feel the need to represent themselves behind a flag due to this, that, and including them in the LGBTQ+ movement would make the movement sort of irrelevant. 

This is in no way saying that you shouldn't be proud of yourself. Everyone should be. But due to the past of straight pride as a term, it has been used in anti-LGBTQ+ rallies, and other similar events, to provoke the community. 

But perhaps, instead, an LGBTQ+ Ally pin would be more fitting? It represents those who are not in the LGBTQ+ community, but instead support it. It is a much less controversial pin overall.
Sorry for the big sentence, just need to explain a lot. And please, don't just try provoke people here, it's quite rude.

**Comment by Deimosegg** [comment]
> > > > How was that insensitive? WYCI means “when you code it”, ie, code it in yourself if you want it in the game
> > > 
> > > 
> > > They're victimizing themselves, dont give them the attention they're egging for
> > 
> > 
> > Oh yes, because wanting representation and respect for all people is victimization. Reported. Go troll somewhere else.
> 
> The reason that straight pride is not included, is mostly due to the past. These groups are represented, as they were, and in some places still are, persecuted for their identity, which is morally wrong. We know that being trans comes down to genetics and upbringing, thinhs they cannot change, so does pretty much everything in the LGBTQ+ community. The movement is to encourage people to support these minorities, and so far, has fortunately worked.
> 
> The reason straight pride is not included,is because straights were not persecuted the same way other groups were in the past. They're a majority, and most don't feel the need to represent themselves behind a flag due to this, that, and including them in the LGBTQ+ movement would make the movement sort of irrelevant.
> 
> This is in no way saying that you shouldn't be proud of yourself. Everyone should be. But due to the past of straight pride as a term, it has been used in anti-LGBTQ+ rallies, and other similar events, to provoke the community.
> 
> But perhaps, instead, an LGBTQ+ Ally pin would be more fitting? It represents those who are not in the LGBTQ+ community, but instead support it. It is a much less controversial pin overall. Sorry for the big sentence, just need to explain a lot. And please, don't just try provoke people here, it's quite rude.

Isn't that the whole reason we want to get straight pride pins?
Might as well just make them an antag uplink item at this point.

**Comment by Iamgoofball** [comment]
can we repoban the bad faith gamers demanding straight pride stuff

**Comment by GoldenAlpharex** [comment]
Okay, let's chill out a little bit.

From a purely objective point of view, these pins are cute, the capes have a really odd pattern that really doesn't scream "flag" to me. I think this is an instance where making it into GAGS would very, very appropriate, for consistency and ease to add more.

That being said, as we all know, this can be a sensitive subject, and because I don't want want to make this kind of decision alone at all, I'll bring it up with the other maintainers, we'll get back to you about it shortly, to see if there's anything else we'd like to see changed, added or reworked.

**Comment by hugmeorelse** [comment]
I'm going to give a warning to everyone involved that's trying to stir shit over this, because it's absolutely retarded to be arguing about pins of all things. They're fucking pins. Go do something better with your lives than obsess over the fact that there are pins in various colorful pattern.

Anyways, we should have these be an available option in the vendors during June. There should only one set of options for the sake of efficiency, namely being the pride option. I actually want to rein in the outfits and try to maintain a fitting aesthetic for the server.

**Comment by Gandalf2k15** [comment]
> I'm going to give a warning to everyone involved that's trying to stir shit over this, because it's absolutely retarded to be arguing about pins of all things. They're fucking pins. Go do something better with your lives than obsess over the fact that there are pins in various colorful pattern.
> 
> Anyways, we should have these be an available option in the vendors during June. There should only one set of options for the sake of efficiency, namely being the pride option. I actually want to rein in the outfits and try to maintain a fitting aesthetic for the server.

As Xyel said, there should only be one "pride" pin, this can be signified by the rainbow. Please make the requested changes and the DNM tag will be removed for review.

**Comment by Gandalf2k15** [comment]
GIven this is being done upstream, this PR is no longer required.

**Pull request closed without merging**
