### PR TITLE
Fixes the HoP locker door

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

the stripe wasn't even with every other Head's locker, I have fixed that.

hoplocker

## Why It's Good For The Game

OCD

## Changelog
:cl:
fix: fixes the inconsistency in the HoP's locker icon
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
An icon change is not a modular change.

**Comment by GoldenAlpharex** [comment]
Also, I'd probably say "Fixes the HoP's locker's door" or something like that, because I thought you meant the airlock at first.

**Comment by tf-4** [comment]
Can you put a before / after in the PR body?

**Comment by axietheaxolotl** [comment]
> 
> 
> Can you put a before / after in the PR body?

done

**Comment by Gandalf2k15** [comment]
No non modular icon changes!

**Pull request closed without merging**
