### PR TITLE
[MODULAR] MRE Vendors : Soft Rework of Chef, Part 1

### PR DESCRIPTION
**Pull request by Sylphet**
## About The Pull Request

This PR is a sort of soft rework for the chef job, moving its design philosophy closer to that of the bartender, where visiting is optional, and the lack of a chef is not a terrible station ending threat. - it adds a vendor with MREs containing full meals, available to all crew in or near the bar of each map. There's lots of variety, and meals for each major race, as well as common dietary restrictions, and a contraband meal available by hacking. One exists roundstart, and a replacement board will be printable from the autolathe, under electronics. Additional refill canisters are adminspawn only for balance reasons, but it should never need to be refilled.

I'll be following this up with another PR, adding in a restaurant, and new highly customisable meals, to further move the chef into its new role and make sure that it isn't starved for content.

Unhappy Meal sprite done by Meatstuff ❤️
Stupid cat brain coding problem fixed with help from Golden ❤️  

## How This Contributes To The Skyrat Roleplay Experience

_**TL;DR -- We have over 120 people most days, on rounds lasting two to three hours. Reality is a chef isn't going to work that long or be able to feed that many people without resorting to fried egg spam. This takes pressure off the chefs, makes the kitchen the place to go for luxury food and RP rather than an obligation to fill your stomach, adds depth to the economy, and stops the station as a whole from starving if the chef sucks, is overworked or does not exist.**_

This PR will add to the bar a vending machine filled with affordable, filling meals, similar to Bay's MRE vendor. I'm doing this because in my experience, people just walk up and take food before leaving without a word, unlike the bar, where people sit down and order drinks, waiting around to chat with the bartender or other customers. I think this is because people are forced to eat, while they choose to go to the bar, and this is why chefs don't see as much RP as the bartender does. The PR should help fix it because now people will choose to go to the kitchen, and ask for special meals when they want them, rather than silently taking a few of the fried eggs that you're desperately throwing together to keep up with demand. People who just want to lose the slowdown debuff will be fed, leaving chef players with a lighter workload and free to make fun meals while chatting with customers, just like the bartender can. The chef can use this lighter workload to feed the bots in quiet moments, and they will no longer struggle to feed 170 hungry furries alone. The vendor will also pay into the service budget, creating a desirable product and a credit sink for the economy, that also allows for the HoP to help the chef to order rare ingredients so they can cook what they want, or what other people want cooked for them. Yes - this will absolutely reduce the number of people visiting the kitchen, and I'm sure that the chef job will be very dead for the first few shifts that this is in. However, I'm certain that this will improve in the long term the quality of RP available to chefs, based on my own observations, discussions with skyrat chef players, and my experience as a chef in Skyrat and other HRP servers which already have this kind of thing. And if after being given a good try, it's shit - I'll remove it.

## Changelog

:cl:
add: Adds a vendor with MREs containing full meals, available to all crew in the bar of each map.
/:cl:

## Examples, sprites, and full menu
MRE2

### CODE REVIEW

**Comment by ghost** [comment]
We have an MRE in-game (god knows where) that might have a more fitting icon than a box

**Comment by Stalkeros2** [comment]
M myes tasty crayon jalapeno spread cheese with some charms on top.

**Comment by SpaceVampire** [comment]
This is cute, but I don't think it is a good PR for a number of reasons.
The vender is /yet another/ map edit we are going to have to worry about keeping around every time we update to TG.
It also breaks the design philosophy about vending food not being a complete replacement for the job.
I get why that is the point, but I still don't agree that making the job less important is a good thing.
The bartender is able to make special drinks that come with cool effects and buffs.
Something that the cook really isn't able to do at the moment, so there isn't as much point to the job otherwise.
As far as "lack of a chef being a terrible station ending threat", I really haven't seen that come up as an issue.
Normally people enjoy working the job, and if it gets that bad you can always call on Cargo to order pizza.
Or get science to go ahead and make some silver cores, you already have options.
Which I think is a lot more enjoyable then just walking to the vender. Hell, if you still wanted to keep the MREs.
You could work them into being some kind of pack you can order for them, along with maybe maint loot.
This is just the least interesting way to interact with the whole food system.

**Comment by Sylphet** [comment]
@SpaceVampire 

> The vender is /yet another/ map edit we are going to have to worry about keeping around every time we update to TG.

Totally valid, though map edits are part of adding things. With new Skyrat maps coming up like Blueshift, hopefully this issue goes away in time. Until then I'll just have to deal with readding this after resets.

> The bartender is able to make special drinks that come with cool effects and buffs. Something that the cook really isn't able to do at the moment, so there isn't as much point to the job otherwise. 

So - this is more of a fault of the foods that the chef can make. We should have more foods like this. Adding some foods with buffs and effects would give more reasons than just RP to go visit the chef, and it's something I'd be interested in working on. At the same time - most drinks that people order from the bar do not have special effects. It's a lot of B52s, manly dorfs... To see someone actually order a bastion bourbon or something is rare. Because of that, I'm not convinced that people _need_ their food or drinks to do anything fancy in order to go and get them.

> As far as "lack of a chef being a terrible station ending threat", I really haven't seen that come up as an issue. 

I'm just exaggerating here.

> Normally people enjoy working the job, and if it gets that bad you can always call on Cargo to order pizza. Or get science to go ahead and make some silver cores, you already have options. Which I think is a lot more enjoyable then just walking to the vender. 

Have to disagree here. In the end, we're a roleplaying server, and roleplay should be our priority. It isn't fun, or encouraging RP, for people to have to track down cargo and get them to order a pizza, agree to the order, wait for the turn around time on that for the pizza to actually get into their hands... The alternative is to get science to stop what they're doing long enough to make for you some silver cores, yeah. Science are _notoriously_ hard to contact, and harder to get anything from. If you want to begin a scene with someone, and need a quick bite to eat first - it's harmful to the RP that you _want_ to engage in to spend your time on this stuff. This wouldn't be a problem if there was food on the table, but that brings us to the challenge of feeding so many people. One or two chefs cannot cook the food that they want to cook, **and** feed the entire station. The problem for chefs is throughput. Either you make uninteresting food like fried eggs and burritos, and keep everyone fed, but it's unsatisfying for you as a player - or you make interesting food, crazy hamburgers, goliath steaks, and people get angry with you because you don't have food out. This is meant as a _support_ for the chef, not a replacement - to remove the pressure on them to cook food that all 150 or so people on station, with all of their own dietary restrictions, are able to eat. It's a total change in balancing for the job where the chef will cook luxury food, and *this* is what will bring people in, rather than the mechanical need to eat.


I'm also going to expand on the role of the chef in a future PR, this is only the first part.

**Comment by sandshark808** [comment]
> Have to disagree here. In the end, we're a roleplaying server, and roleplay should be our priority. It isn't fun, or encouraging RP, for people to have to track down cargo and get them to order a pizza, agree to the order, wait for the turn around time on that for the pizza to actually get into their hands... The alternative is to get science to stop what they're doing long enough to make for you some silver cores, yeah. Science are _notoriously_ hard to contact, and harder to get anything from. If you want to begin a scene with someone, and need a quick bite to eat first - it's harmful to the RP that you _want_ to engage in to spend your time on this stuff. This wouldn't be a problem if there was food on the table, but that brings us to the challenge of feeding so many people. One or two chefs cannot cook the food that they want to cook, **and** feed the entire station. The problem for chefs is throughput. Either you make uninteresting food like fried eggs and burritos, and keep everyone fed, but it's unsatisfying for you as a player - or you make interesting food, crazy hamburgers, goliath steaks, and people get angry with you because you don't have food out. This is meant as a _support_ for the chef, not a replacement - to remove the pressure on them to cook food that all 150 or so people on station, with all of their own dietary restrictions, are able to eat. It's a total change in balancing for the job where the chef will cook luxury food, and _this_ is what will bring people in, rather than the mechanical need to eat.

I very much disagree with this. Cargo is always looking to order cool stuff and as a science player I make a recurring silver every shift and usually just keep it for myself to eat from. It's a lot of fun to have inter-department cooperation and to "rescue the station" when the chef is gone.

That being said, my main complaint about these food items is that they're all good. If you look at the way vendor food is designed right now, it's junk food which is very filling (there's a cap on how many you can stuff into your gob at once), very tasty, but not nutritious at all.

By contrast the food you picked is nutritious, enjoyed by many species, and in some cases fairly high-end in terms of chef cooking. I know that changing the chef role is what you intend for this, but I don't think the changes will be very positive if these are too prevalent. This is because the cafeteria and bar serve a secondary purpose beyond just getting food: they funnel traffic around the station.

Think of it this way. Everyone wants to eat. When there's food at the counter, they know they can get better meals outside their department and so they leave to grab it. They go there, they eat, and they might get involved in a social situation. They'll be packed in one location and thus open to facing news and threats. The turnaround time is also going to be, on average, longer than it would be from a vendor. Aside from helping them mingle and meet new characters (a roleplay function) that turnaround time gives people opportunities to break into their workplace while they're gone.

I also know that short-order cooking on /tg/ code has been less fun for a highpop server with the cooking changes, and even though I enjoy it a lot of people don't, but I don't think this is the way to solve the problem either. Smaller changes to the time it takes to cook certain foods or the availability of certain products, like maint mobs did for meat, are things that I feel would increase the amount and variety of food cooked in a round while also keeping the chef role as a valuable central pillar of the station. Plus maintaining them would be less hard than remapping the entire kitchen.

**Comment by Sylphet** [comment]
I no longer have interest in maintaining this for Skyrat, anyone interested is free to take my code for themselves. ❤️

**Pull request closed without merging**
