### PR TITLE
Undoes the override for holopad sprites

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

Holopad sprites were redone by tg in https://github.com/tgstation/tgstation/pull/69126

image
image
image
image

## How This Contributes To The Skyrat Roleplay Experience

I'll be honest I just do not like how our holopad override looks, and the tg one was redone so there's no justification left to keep the override.

## Proof of Testing

Soon

## Changelog

:cl:
imagedel: The sprite override for holopads has been undone, reverting us to to what tg has
/:cl:

### CODE REVIEW

**Review by Ebin-Halcyon — APPROVED** [review]
Knew I missed something. Fuck the aesthetics folder.

**Comment by Paxilmaniac** [comment]
Fastest pr approval known to mankind

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
The fact that they were re-done upstream doesn't mean that they're necessarily better.

I can understand not liking the current ones, but I don't really think upstream's are much better. I'd much rather have our own version of it.

Overrides aren't a bad thing, being visually different is also part of the appeal of playing here.

**Comment by Paxilmaniac** [comment]
I do not think we should override things when we do not have to. This is definitely a "we do not have to".

**Review by GoldenAlpharex — APPROVED** [review]
Fuck it I guess.

**Comment by Gandalf2k15** [comment]
Those are objectively worse. Ney.

**Pull request merged**
