### PR TITLE
Removes the AMR from being able to be purchased in Cargo

### PR DESCRIPTION
**Pull request by Zergspower**
## About The Pull Request

Doesnt remove the rifle but removes it from being purchasable from cargo

## How This Contributes To The Skyrat Roleplay Experience

2000 credits for a rifle that can outdo basically anything and go through everything it's shot towards, not really something crew would be needing to purchase as this even outperforms syndicate weapons.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  It's just a del
</details>

## Changelog

:cl:
del: Cargo - AMR rifle is no longer purchasable via cargo
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
it does less damage in total then functionally any of the traitor handguns, does less in total time, has less ammo, and only barely competes with half the guns in cargo: all that's wrong with it is the wound-chance because it's over-rolling

**Comment by Zergspower** [comment]
> it does less damage in total then functionally any of the traitor handguns, does less in total time, has less ammo, and only barely competes with half the guns in cargo: all that's wrong with it is the wound-chance because it's over-rolling

Did you miss the part about infinite penetration?

**Comment by Nerev4r** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/20773

**Comment by RatFromTheJungle** [comment]
> > it does less damage in total then functionally any of the traitor handguns, does less in total time, has less ammo, and only barely competes with half the guns in cargo: all that's wrong with it is the wound-chance because it's over-rolling
> 
> Did you miss the part about infinite penetration?

and to reply regardless; people don't really stand in straight lines

**Comment by burgerenergy** [comment]
they do tho? Maintenance fights are often enough and hallways are either two or three wide

**Comment by tf-4** [comment]
gone with https://github.com/Skyrat-SS13/Skyrat-tg/pull/20773 for now but may revisit this as an option in the future

**Pull request closed without merging**
