### PR TITLE
Expands the Ghost Cafe's Library Room to include a Art Gallery

### PR DESCRIPTION
**Pull request by SomeRandomOwl**
## About The Pull Request

This expands the Library room on the ghost cafe to include a small art gallery, with 4 large painting slots, and 4 small painting slots.

## How This Contributes To The Skyrat Roleplay Experience

This adds in a way for people who are more artistically inclined a way to save their paintings they may or may not paint at the ghost café. The previous Library room didn't have slots for large paintings, this addition adds in large slots thus allowing more art to be set down and archived.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

image

</details>

## Changelog

:cl:
add: The Ghost Cafe's Library room has been expanded, it now includes a Art Gallery, for all of you aspiring Vincent van Gogh artists out there. You now have a space to archive more art! 
/:cl:

### CODE REVIEW

**Review by Gandalf2k15 — CHANGES_REQUESTED** [review]
don't allow them to create paintings that will show up on station, a gallery alone is fine however.

**Comment by SomeRandomOwl** [comment]
> don't allow them to create paintings that will show up on station, a gallery alone is fine however.

How do i prevent that? is there a specific var i need to set on them?

**Comment by Gandalf2k15** [comment]
> > don't allow them to create paintings that will show up on station, a gallery alone is fine however.
> 
> How do i prevent that? is there a specific var i need to set on them?

You'll just need to remove the machines that enable it and just have the pictures.

**Review by Jolly-66 — APPROVED** [review]
Map changes are whatever. Make sure to include either more art supplies or the art vender. Either or, preferably.

**Comment by SomeRandomOwl** [comment]
> Map changes are whatever. Make sure to include either more art supplies or the art vender. Either or, preferably.

alright, i can do that

**Comment by SomeRandomOwl** [comment]
image
image

Updated visuals

**Comment by SomeRandomOwl** [comment]
huh theres checks failing but i dont think its on my end?

`_maps/map_files/Deltastation/DeltaStation2.dmm:80393:error: undefined type: /obj/item/stamp/head/hop
_maps/map_files/Deltastation/DeltaStation2.dmm:80402:error: unknown type
loading map_files/IceBoxStation/IceBoxStation.dmm
loading map_files/MetaStation/MetaStation.dmm
loading map_files/Mining/Lavaland.dmm
loading map_files/NorthStar/north_star.dmm
loading map_files/tramstation/tramstation.dmm
_maps/map_files/tramstation/tramstation.dmm:46041:error: undefined type: /obj/item/stamp/head/hop
_maps/map_files/tramstation/tramstation.dmm:46054:error: unknown type
loading map_files/VoidRaptor/VoidRaptor.dmm`

I didnt touch those and thats the only error i can see in the github checks, the build works on my local machine so im not sure why those checks are failing?

**Comment by SomeRandomOwl** [comment]
looks like the type path of the stamps got changed?

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
