### PR TITLE
[MODULAR] deeeeer taaaail

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

adds a cute deer tail

credits to arctaisia who made the sprites <3

## How This Contributes To The Skyrat Roleplay Experience

cute deer tails are needed for my experiences to improve

## Changelog

:cl:
add: adds a deer tail
/:cl:

### CODE REVIEW

**Comment by Arctaisia** [comment]
❤️

**Review by GoldenAlpharex — APPROVED** [review]
Looks good. Also that's a lotta commits my man

**Comment by Gandalf2k15** [comment]
Now we just need bunny ears

**Comment by Gandalf2k15** [comment]
and snout

**Comment by Seris02** [comment]
> Now we just need bunny ears

we have bunny ears

**Pull request merged**
