### PR TITLE
[MIRROR] New crates [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/79665
--------------------
crates_flat

## About The Pull Request

Updates the sprites of existing crates and adds some new ones.

TODO:

- [x] Make syndicrate sprite work with its dual lock
- [x] Map for bitrunning, robo, etc.
- [x] Specify the new crates in cargo orders

## Why It's Good For The Game

More crates variety.

## Changelog

:cl:
image: Crates got new sprites
image: Added more crate styles
/:cl:

### CODE REVIEW

**Comment by nikothedude** [comment]
guys can we use these theyre actually good this time

**Comment by Plum-but-gayer** [comment]
old crates are soulful and i'll miss them but these look soooo good

**Comment by W4rd3nn** [comment]
Immediately making a PR to disable our current crate overrides

**Comment by GoldenAlpharex** [comment]
These do already look much better than their previous iteration, I'm not actually really against giving these a go. They're pretty close to what we have in terms of general aesthetic/style, so I'm not against trying them out.

**Review by vinylspiders — APPROVED** [review]

**Pull request merged**
