### PR TITLE
Removes Medical Doctor alt-titles and most of the Scientist alt-titles because even after adding the angry red text saying you still have to do your job, people are still getting wishy washy about doing their job.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request
Removes Medical Doctor alt-titles and most of the Scientist alt-titles because even after adding the angry red text saying you still have to do your job, people are still getting wishy washy about doing their job.

## How This Contributes To The Skyrat Roleplay Experience

Really sucks when a medical doctor refuses to medical doctor you because their ID says nurse, and it really sucks when nobody in R&D but the science guard will hit the buttons because everyone says their ID cards are individual jobs.

## Changelog

:cl:
del: Removes Medical Doctor alt-titles and most of the Scientist alt-titles because even after adding the angry red text saying you still have to do your job, people are still getting wishy washy about doing their job.
/:cl:

### CODE REVIEW

**Comment by Elli-Skala** [comment]
Thank god

**Comment by ArdentSpark** [comment]
I really dislike this but I can't personally verify if people are being shitters and not doing their job, so I can't really thumbs down it but.

Flavour roles are nice, man.

**Comment by Iamgoofball** [comment]
flavor roles are nice
flavor roles being used as an excuse to not do work is not nice

**Comment by Stalkeros2** [comment]
I really think this should be resolved and punished ICly/with a slight assistance of an admin instead of gutting out an incredibly nice way of expressing your character's personality/skills/whatever because "heehee hoohoo shitters being shitters".

**Comment by hugmeorelse** [comment]
Should we add nurse jobs as a separate thing?

**Comment by Zenitheevee** [comment]
I'm gonna be honest here.
I _Genuinely_ dont think this is going to fix jack.
If people are going to take jobslots then fuck off, They're going to do it regardless.

**Especially** on the medical side, Because... Surgeons and Nurses are still very important to the medical process. If they're fucking off, Then they should be strictly warned through an Ahelp, If not flat jobbanned.

Scientist... Some of them are a bit more wishywashy, But i think its odd you're keeping "Theoretical Physicist" when thats... Probably the least actual useful title. The hell are they theorizing? Whether or not they'd get yeeted for sitting down and trying to cosplay as the thinker?

**Comment by Tastyfish** [comment]
It's funny because in real life, nurses do almost all of the actual work and doctors just stare at the charts and nod most of the time.

**Comment by thestubborn** [comment]
cc'ing in my comment from the discord, because contrary to what most people believe, I am not a blind cheerleader for goof

i
mean i get it, but
and i hate being that guy but
"staff issue"

**Comment by gonenoculer5** [comment]
Honestly. Staffing issue. Report people who do this to staff and let them sort it. Guarentee it'll stop after enough evidence for this specific problem is gathered and the responsible parties are bwoinked about it. Folks shouldn't stop doing their tasks just because of purely flavor alt titles, at the worst make it so that using alt titles as an excuse not to work is bwoinkable.

**Comment by ChungusGamer666** [comment]
Players being terrible won't stop happening. Coders already did what they could.

**Comment by ChungusGamer666** [comment]
> Should we add nurse jobs as a separate thing?

More job bloat is 👎

**Comment by Gandalf2k15** [comment]
re open this if the strobe don't work

**Pull request closed without merging**
