### PR TITLE
[MODULAR] Dehardcodes head/armory access from Cryo-console requirements

### PR DESCRIPTION
**Pull request by Zenitheevee**
## About The Pull Request

No longer shall ghost roles be forsaken to forgo items lost via cryo

## How This Contributes To The Skyrat Roleplay Experience

Its odd that, Despite _Having access changes_, that ghost roles cant access cryo-consoles linked to their access

## Changelog

:cl:
fix: Cryo Consoles can now use alternative accesses
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
More of a fix (which is worth more GBP)

**Comment by Zenitheevee** [comment]
Test seems to be failing from-... Backpack item or something?

**Comment by tf-4** [comment]
> Test seems to be failing from-... Backpack item or something?

not your fault

**Review by jjpark-kb — APPROVED** [review]
looks good

**Pull request merged**
