### PR TITLE
DS-2/Interdyne modsuits no longer have access requirements

### PR DESCRIPTION
**Pull request by Zonespace27**
## About The Pull Request
Pretty sure you can't turn these on since interdyne doesn't have ACCESS_SYNDICATE, this fixes that.

## How This Contributes To The Skyrat Roleplay Experience
Not having to hack modsuits to use them is probably good

## Changelog

:cl:
fix: DS-2 and Interdyne base modsuits no longer need to be hacked to be used by syndicate personnel
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
Is there a reason not to give them syndicate access?

**Comment by YakumoChen** [comment]
????
They do have that access, they wouldn't be able to walk around the base without it

**Comment by Zergspower** [comment]
Freighter is the one that had this issue, i didnt think Interdyne did

**Comment by Tastyfish** [comment]
Yeah, Interdyne and DS-2 use SYNDICATE access for all airlocks.

**Comment by dekunutkid** [comment]
However for some reason locking the modsuit, it's unable to be unlocked by any syndicate member, I have experienced this myself and as such I approve of this change.

**Comment by YakumoChen** [comment]
That seems to be an issue for modsuits in general honestly.

Or just don't lock them

Or just find the root cause of the bug

**Pull request merged**
