### PR TITLE
Expedition Corps Supply

### PR DESCRIPTION
**Pull request by masline147**
## About the Pull Request
Сhanging the balance of the Expedition Corps' equipment statistics and the contents of the delivery box. I think it will be a worthwhile proposal to update this equipment for Gate explorel.
Change:
- Improving protection statistics to the level of Security Service protection.
- Now there will be a full set of equipment in one order. 

## How This Contributes To The Skyrat Roleplay Experience
Now assistants can easily and simply prepare for the journey with just one box. Now Expedition Corps' equipment will not be inferior to CIN equipment. Now the expedition will have a choice between cheap CIN equipment with low protection indicators, and expensive Corps' equipment with good protection. In addition, the forwarders will have melee weapons.
## Proof of testings
image

## Change Log
Balance: Expedition Corps' supplies have a constant filling from the past list. Improve Expedition Corps' equipment stats to the level of security service equipment.

### CODE REVIEW

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
Follow the PR format, I won't review this until then

**Comment by masline147** [comment]
> Follow the PR format, I won't review this until then

Well done. What else?

**Review by Zonespace27 — CHANGES_REQUESTED** [review]
Revert every change in this PR, make the price of the crate on-par with the CIN crate (CARGO_CRATE_VALUE * 15, or 3k)

This crate is fundamentally *not* supposed to be "for gateway explorers", it's a way of obtaining the vanguard drip without begging an admin. At the moment, I see no reason to change this.

**Comment by masline147** [comment]
> Revert every change in this PR, make the price of the crate on-par with the CIN crate (CARGO_CRATE_VALUE * 15, or 3k)
> 
> This crate is fundamentally _not_ supposed to be "for gateway explorers", it's a way of obtaining the vanguard drip without begging an admin. At the moment, I see no reason to change this.

"Explorer armor not for exploring" ... I'm not interested in your logic.

**Pull request closed without merging**
