### PR TITLE
[MODULAR] - Nerfs the LRPness of bananas

### PR DESCRIPTION
**Pull request by SpaceVampire**
## About The Pull Request

Following the advise of @tf-4 in https://github.com/Skyrat-SS13/Skyrat-tg/pull/3938
This PR changes the color to bring them more in line with our role-playing standards
BannanaLRP
Seen above is the normal LRP Banana.
BannanaHRP
Now check our the HRP Banana, with the new color changes.

## Why It's Good For The Game

I switched it to #f9e998, a color that is far less "clowny" in nature.
I hope help improve the roleplay levels in our community, by taking a deigns based off ERIS and other HRP servers.
I have also added racing stripes, so it's optimized for server performance, which is important with our high player counts.

## Changelog
:cl:
balance: Bananas now have a more sensible color.
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
very hrp aurora bay eris and epic

**Comment by Guidesu** [comment]
This new sprites are awful

**Comment by SpaceVampire** [comment]
@Yawet330 
Do I need to do a //SKYRAT EDIT for this?
I wasn't sure how that worked, when I was dealing with ICON files.

**Review by tf-4 — APPROVED** [review]
Looks good. Looking forward to experiencing some HRP banana gameplay.

**Comment by Guidesu** [comment]
Really? Are you going to accept the super satured banana colors?

**Comment by NullDagaf** [comment]
> @Yawet330
> Do I need to do a //SKYRAT EDIT for this?
> I wasn't sure how that worked, when I was dealing with ICON files.

Yes. Also make sure to changelog every pixel you're changing.

**Comment by SpaceVampire** [comment]
> 
> 
> > @Yawet330
> > Do I need to do a //SKYRAT EDIT for this?
> > I wasn't sure how that worked, when I was dealing with ICON files.
> 
> Yes. Also make sure to changelog every pixel you're changing.

BannanEdit

Just to confirm before I push, is this how it should be handled?
I'm working on the changelog improvements, but I am not sure how to format the coordinates for each pixel.
Could you maybe give me an example changelog?
Sorry for all the questions, I am new to this.

**Comment by hugmeorelse** [comment]
Very HRP. I recommend putting on racing stripes, so it's optimized for server performance.

**Comment by tf-4** [comment]
> 
> 
> Really? Are you going to accept the super satured banana colors?

They committed on their master, this is clearly a very important PR. I don't see the issue

**Comment by KathrinBailey** [comment]
Needs to follow modularisation guidelines.
Basically just make a new .dmi that's modular, and change the icon of the banana, so you aren't changing an existing core .dmi file, since you can't really do that in a modular way.

Also, I'm aware that ```"I hope that it can help us distance ourselves from our shameful TG roots."``` was probably a joke, but I'd prefer if you didn't. Don't wanna encourage that kind of talk.

**Comment by SpaceVampire** [comment]
> Very HRP. I recommend putting on racing stripes, so it's optimized for server performance.

Good point. I have done as you recommended.
FastHRPBanaana

**Comment by SpaceVampire** [comment]
> 
> 
> > Really? Are you going to accept the super satured banana colors?
> 
> They committed on their master, this is clearly a very important PR. I don't see the issue

I always commit 100% to my projects. If I didn't think it was fully important, I wouldn't do it.

**Comment by RatFromTheJungle** [comment]
@SpaceVampire it has to be RGB compatible so they know we're serious about the fact it's still a game

**Comment by SpaceVampire** [comment]
> 
> 
> Needs to follow modularisation guidelines.
> Basically just make a new .dmi that's modular, and change the icon of the banana, so you aren't changing an existing core .dmi file, since you can't really do that in a modular way.
> 
> Also, I'm aware that `"I hope that it can help us distance ourselves from our shameful TG roots."` was probably a joke, but I'd prefer if you didn't. Don't wanna encourage that kind of talk.

Can you please review it now? I returned the file I touched the first time to its own state.
Then I moved all of my .dmi stuff to a new file in a modular format.
Well, I used the one that was already there, for the catnip.
I also removed all my comments about TG station, to encourage civility in the general discourse.

**Comment by SpaceVampire** [comment]
> 
> 
> @SpaceVampire it has to be RGB compatible so they know we're serious about the fact it's still a game

How could I best make it RGB compatible?
I'm not fully sure how to address this.

**Comment by RatFromTheJungle** [comment]
> 
> 
> > @SpaceVampire it has to be RGB compatible so they know we're serious about the fact it's still a game
> 
> How could I best make it RGB compatible?
> I'm not fully sure how to address this.

sync it to razer synapse or something idk

**Comment by Arctaisia** [comment]
Amazing, this will be sure to better the server for years to come.

**Comment by Gandalf2k15** [comment]
hahahaahahahahahahashahaha no we can't have non-modular icon changes

**Comment by hugmeorelse** [comment]
> > Very HRP. I recommend putting on racing stripes, so it's optimized for server performance.
> 
> Good point. I have done as you recommended.
> FastHRPBanaana

My hands are tied here. :( I was looking forward to optimized racing bananas on the server. Very HRP.

**Pull request closed without merging**
