### PR TITLE
[Modular] Captain Gasmask For Muzzles and Vox

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Makes a muzzled and vox variant for the captain gasmask. I'm not entirely satisfied with how it fits on vox from the side - but the original gasmask has the same problem, so.. eh.
image

## Why It's Good For The Game
Missing sprite bad

## Changelog
:cl:
imageadd: The captain's gasmask now has a muzzled and Vox variant.
imagedel: The duplicate icons in mask_vox.dmi have been removed.
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
DIRTY PIXEL SIGHTED

**Comment by Gandalf2k15** [comment]
Hey. Check the icons, you've deleted some.

**Comment by KasparoVy** [comment]
Hey @unit0016, I made a Vox gasmask sprite over at Para some years ago, the codebase where most the Vox masks seem to've been ported from. See PR here https://github.com/ParadiseSS13/Paradise/pull/4867

Feel free to get the gasmask from the mask/face .dmi & just replace the colours with the ones from the Captain version.

I'm not sure if my sprite's in here for Vox regular gas mask or not already.

**Comment by unit0016** [comment]
> Hey. Check the icons, you've deleted some.

Yeah, duplicates.

**Comment by Oscari-pog** [comment]
...where does Captain even have the gas mask? I have never seen it.

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
