### PR TITLE
[NON-MODULAR] Minorly nerfs the stealth implant, now 5 seconds instead of 2 to cloak

### PR DESCRIPTION
**Pull request by FlamingLily**
## About The Pull Request
Maaaaaybe outright removing is a LITTLE too much. And no, this isn't a salt PR, please don't give me that.

## Why It's Good For The Game
But I do feel like this needs a nerf.

## Changelog
:cl:
balance: Stealth implant now takes 5 seconds to cloak, instead of 2.
/:cl:

### CODE REVIEW

**Comment by SpaceVampire** [comment]
I feel like that makes it pretty useless when it comes to trying to pull off any kind of escape.
I mean, the box already has an max_integrity of one. You can pop it with just a single bullet.
If you felt like you had to do something about it, like, if it is too common, I think that making it cost more might be better.
Instead of just making it way worse, for anyone who wanted to use it.

**Comment by FlamingLily** [comment]
> 
> 
> I feel like that makes it pretty useless when it comes to trying to pull off any kind of escape.
> I mean, the box already has an max_integrity of one. You can pop it with just a single bullet.
> If you felt like you had to do something about it, like, if it is too common, I think that making it cost more might be better.
> Instead of just making it way worse, for anyone who wanted to use it.

It's still infinite use, 100% moveable, nearly undetectable, and incredibly hard to attack, it's just marginally harder to go ""haha you wanted to RP? n o" and pop it and be gone

**Comment by Gandalf2k15** [comment]
> > I feel like that makes it pretty useless when it comes to trying to pull off any kind of escape.
> > I mean, the box already has an max_integrity of one. You can pop it with just a single bullet.
> > If you felt like you had to do something about it, like, if it is too common, I think that making it cost more might be better.
> > Instead of just making it way worse, for anyone who wanted to use it.
> 
> It's still infinite use, 100% moveable, nearly undetectable, and incredibly hard to attack, it's just marginally harder to go ""haha you wanted to RP? n o" and pop it and be gone

Implying security would want to RP. It's either "surrender" or instantly be killed.

**Comment by FlamingLily** [comment]
> 
> Implying security would want to RP. It's either "surrender" or instantly be killed.

This is not technical or balance analysis, please keep these discussions to the discord

**Comment by Gandalf2k15** [comment]
Balance change during feature freeze.

**Comment by FlamingLily** [comment]
> 
> 
> Balance change during feature freeze.

You have literally added features during the feature freeze, let alone merged and approved balance changes. Please act in good faith.

**Comment by FlamingLily** [comment]
Balance isn't even a feature, and nowhere does the FF mention disallowing balance.

**Comment by hugmeorelse** [comment]
Five seconds seem too many.

**Comment by hugmeorelse** [comment]
Five seconds seem too many.

**Comment by FlamingLily** [comment]
No longer contributing to this server.

**Pull request closed without merging**
