### PR TITLE
[MODULAR] Fixes Interlink doors throwing several warnings on server start

### LINKED ISSUE #19019: Interlink doors throw several warnings on server start
## Errors:
```The general at The Interlink (42,184,2) tried to set req_one_access, but req_access was already set!
The general at The Interlink (44,191,2) tried to set req_one_access, but req_access was already set!
The general at The Interlink (56,191,2) tried to set req_one_access, but req_access was already set!
The captain at The Interlink (42,202,2) tried to set req_one_access, but req_access was already set!
The general at The Interlink (82,223,2) tried to set req_one_access, but req_access was already set!
```

### PR DESCRIPTION
**Pull request by vinylspiders**
## About The Pull Request

Fixes #19019

The warning is caused by the access being hard-edited into the door when there is simultaneously an access helper placed at that loc.
Removed the hard-coded access and made a new mapping helper for when you want access from either captain or centcom.

## How This Contributes To The Skyrat Roleplay Experience

Fixes a bug.

## Proof of Testing

</details>

<details>
<summary>it was hardcoded</summary>
  
image

</details>

<details>
<summary>proof that the doors get their access from the new helper</summary>
  
image

image

image

image

image

</details>

<details>
<summary>no more warnings</summary>
  
image

</details>

## Changelog

:cl:
fix: gets rid of some warnings on server start
qol: new mapping helper for when you want a door that requires centcom or captain access
/:cl:

### CODE REVIEW

**Comment by RimiNosha** [comment]
Heads up, I think that map file is broken. -80k lines for 2k additions is... not right.

**Comment by RimiNosha** [comment]
Oh, you haven't ran mapmerge inside the tools folder. I highly recommend using strongdmm in the future, as it automatically saves it in the right format.

**Comment by vinylspiders** [comment]
> Oh, you haven't ran mapmerge inside the tools folder. I highly recommend using strongdmm in the future, as it automatically saves it in the right format.

ah. my bad.

**Comment by RimiNosha** [comment]
Looking good!

**Review by Paxilmaniac — APPROVED** [review]

**Pull request merged**
