### PR TITLE
Makes the lathe tax a server config, fixes off-station roles, fixes cyborgs and drones interactions. 

### PR DESCRIPTION
**Pull request by nevimer**
## About The Pull Request

Alright. I know the admins are drown in problems with the lathe tax, all midrounds are shut down from using the lathe right now, and the thing doesn't even get the right bank account for your ID right now - only the one paired to your mob - never a stolen ID or anything.

This PR makes it a config variable - how much is charged, and fixes all thats listed in the title. 

## How This Contributes To The Skyrat Roleplay Experience

Step one in un-janking the lathe tax. Moves it to a modular proc. 

## Changelog

:cl:
fix: Allows non-carbons to interact and print once again. Call your local AI, maybe. 
config: Lathe tax is now a config option
/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
https://github.com/tgstation/tgstation/pull/66566

**Comment by YakumoChen** [comment]
#13180 in case that doesn't work too

**Comment by Zonespace27** [comment]
also https://github.com/tgstation/tgstation/pull/66587

**Comment by Iamgoofball** [comment]
Don't shut the lathe tax off, c'mon. Assistants can simply get real jobs or do bounties if they want to freely print shit from departmental protolathes. It'll bust up the economy balance otherwise.

**Comment by nevimer** [comment]
> 



> Don't shut the lathe tax off, c'mon. Assistants can simply get real jobs or do bounties if they want to freely print shit from departmental protolathes. It'll bust up the economy balance otherwise.

Let's not pretend we had a balanced economy in the first place, just an exacerbated problem. It's absolutely essential to game it to partake now. 
dreamseeker_7KNnXiaRb8

**Comment by YakumoChen** [comment]
is that screenshot supposed to prove anything? The only reason you need a ton of credits is for guncargo right now.

The lathe tax isn't even that big, it's like, 10 credits per print? And only applies to dept lathes?

This PR isn't even needed because Zonespace already has PRs up.

**Comment by Gandalf2k15** [comment]
As stated, if you want to make it a config, do it upstream 👍 otherwise we'll wait to see how TG takes this system, it's new, and constantly changing, I'd rather not make non-modular changes yet 💯

**Pull request closed without merging**
