### PR TITLE
Rockplanet LZ-669 [READY]

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

This adds a new mining z-level, the rock planet. This has old ateroid fauna spawning in it and has a perfectly breathable atmosphere. Unless it rains acid. 

Currently this gives DS1 a purpose, they can use their frigate to land on the planet.

## Changelog
:cl:
add: Adds the Rockplanet LZ-669, a new type of mining area. Those that have played asteroid mining will know what this is. This planet has very high yield ore deposits. Mine here!
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
It would be cool to get this as its own mining z-level for the station too, alot of folks miss asteroid mining!

Cool PR.

**Comment by KasparoVy** [comment]
Oh my god that's amazing, bless the return of some traces from asteroid/spessmining

The view is to die for, but even on the rocky planet - cooooool.

**Comment by FlamingLily** [comment]
Does this mean station mining will be able to go here instead of lavaland?

If not, why not?

**Comment by FlamingLily** [comment]
> 
> 
> Does this mean station mining will be able to go here instead of lavaland?
> 
> If not, why not?

`// lavaland.dmm`

Wait is this removing lavaland entirely, or is that just while it's a WIP?

**Comment by DiscountDirtyDan** [comment]
Do it. Please. Holy fucking shit do it. I beg you.

**Comment by Gandalf2k15** [comment]
> > Does this mean station mining will be able to go here instead of lavaland?
> > If not, why not?
> 
> `// lavaland.dmm`
> 
> Wait is this removing lavaland entirely, or is that just while it's a WIP?

Don't look too much into the code just now, it's a WIP, see label and title.

**Comment by FlamingLily** [comment]
> 
> 
> > > Does this mean station mining will be able to go here instead of lavaland?
> > > If not, why not?
> > 
> > 
> > `// lavaland.dmm`
> > Wait is this removing lavaland entirely, or is that just while it's a WIP?
> 
> Don't look too much into the code just now, it's a WIP, see label and title.

Aight fair enough. So is the plan to replace lavaland entirely? Or to have it as selectable on the mining shuttle console? Like you can fly out to the rock or to lavaland, depending on if you wanna take a risk or not?

**Comment by DiscountDirtyDan** [comment]
> > > > Does this mean station mining will be able to go here instead of lavaland?
> > > > If not, why not?
> > > 
> > > 
> > > `// lavaland.dmm`
> > > Wait is this removing lavaland entirely, or is that just while it's a WIP?
> > 
> > 
> > Don't look too much into the code just now, it's a WIP, see label and title.
> 
> Aight fair enough. So is the plan to replace lavaland entirely? Or to have it as selectable on the mining shuttle console? Like you can fly out to the rock or to lavaland, depending on if you wanna take a risk or not?

Please be the plan by the way, holy fucking shit if you name a crypto i will seriously mine it and pay you in it if that's the plan

**Comment by Gandalf2k15** [comment]
I will likely give them an option. I will probably allow DS1 to land on the lower level of LZ669.

**Comment by unit0016** [comment]
> I will likely give them an option. I will probably allow DS1 to land on the lower level of LZ669.

Letting it be an option for maps would be neat. Or random mining z-level would be neat too! Have it pick from an icemoon, lavaland, or the asteroid. Who knows! Fun is endless.

**Comment by FlamingLily** [comment]
> 
> 
> > I will likely give them an option. I will probably allow DS1 to land on the lower level of LZ669.
> 
> Letting it be an option for maps would be neat. Or random mining z-level would be neat too! Have it pick from an icemoon, lavaland, or the asteroid. Who knows! Fun is endless.

I dislike the idea of it being random, while cool in concept, imagine rolling LZ669 when you wanted to hunt some megafauna, well fuck you you're shit outta luck now. Same goes for vice versa. Or god forbid, you roll icemoon and **hate** icemoon

ALTHOUGH. What could be fun, randomly picking between icemoon/lavaland and also having LZ669 as a 100% chance.

Where icemoon/lavaland is for the fat loot with much higher risk, while LZ669 is for miners who would rather do their dang jobs and not powergame- I mean take less of a risk and not have as much of a _personal_ reward.

Of course, this doesn't work on icebox, so, _shrug_

**Comment by Stalkeros2** [comment]
A s t e r o i d fuck yeah.
Great PR, merge asap.

**Comment by KasparoVy** [comment]
> 
> 
> > > I will likely give them an option. I will probably allow DS1 to land on the lower level of LZ669.
> > 
> > 
> > Letting it be an option for maps would be neat. Or random mining z-level would be neat too! Have it pick from an icemoon, lavaland, or the asteroid. Who knows! Fun is endless.
> 
> I dislike the idea of it being random, while cool in concept, imagine rolling LZ669 when you wanted to hunt some megafauna, well fuck you you're shit outta luck now. Same goes for vice versa. Or god forbid, you roll icemoon and **hate** icemoon
> 
> ALTHOUGH. What could be fun, randomly picking between icemoon/lavaland and also having LZ669 as a 100% chance.
> 
> Where icemoon/lavaland is for the fat loot with much higher risk, while LZ669 is for miners who would rather do their dang jobs and not powergame- I mean take less of a risk and not have as much of a _personal_ reward.
> 
> Of course, this doesn't work on icebox, so, _shrug_

I really really like this strategy! Could also just be different shuttle desinations for the mining shuttle

**Comment by SpookyTheFox** [comment]
To clarify-
Is the station able to access LZ-669 at all? And can the DS-1 shuttle go to lavaland? We need to prevent even the possibility of contact between DS-1 ghost roles and non DS-1 players.

**Comment by BrotherHangyul** [comment]
A few issues I'll report as a mining player:

- Megafauna can spawn here. That's great and all but we can't use survival/lux pens due to the atmosphere, meaning we have to either go down to lavaland to stock up on legion cores - which defeats the point of the asteroid - or fight with zero healing, which is pretty hard.

- It's spaced in some areas, which means we still have to go down to lavaland to get the points for a mining hardsuit. Adding the mining hardsuit to the suit options might fix this; if SEVA is space-worthy, forget what I said, that's me being a dumb fuck.

**Comment by Gandalf2k15** [comment]
> A few issues I'll report as a mining player:
> 
> * Megafauna can spawn here. That's great and all but we can't use survival/lux pens due to the atmosphere, meaning we have to either go down to lavaland to stock up on legion cores - which defeats the point of the asteroid - or fight with zero healing, which is pretty hard.
> * It's spaced in some areas, which means we still have to go down to lavaland to get the points for a mining hardsuit. Adding the mining hardsuit to the suit options might fix this; if SEVA is space-worthy, forget what I said, that's me being a dumb fuck.

will fix, oversight in mapgen. Also the atmos leakage has been fixed too

**Comment by SpookyTheFox** [comment]
A serious issue cropped up in actual play, the station can get to rockplanet and mix with DS-1 players. In  code/modules/mining/mine_items.dm , line 76, I see the following:
`possible_destinations = "mining_home;mining_away;landing_zone_dock;mining_away_rockplanet" //SKYRAT EDIT CHANGE`

That needs to get fixed ASAP.

**Pull request merged**
