### PR TITLE
[Non-modular] Updates borg language, adds expanded language module

### PR DESCRIPTION
**Pull request by desertmote**
## About The Pull Request

What borgs used to be able to speak and understand:
Common, uncommon, encoded audio, draconic, moffic, nekomimetic, calcic and coltaic.

What borgs are able to speak and understand now:
Common, uncommon, encoded audio, draconic, moffic, nekomimetic, **spacer, japanese, gutter, russian, selenian, zolmach.**

Borgs can have their language module upgraded by installing a Expanded Translation Module, they can then **also** speak and understand:
Calcic, voltaic, nekomimetic, buzzwords, sylvan, monkey, slime, shadowtongue, piratespeak, terrum, vox, xenoknockoff, xenocommon.

The language module is locked behind Advanced Robotics and Big Data, (In space).
LnZvGl2q4h

## Why It's Good For The Game

Updating old content to include our new content and make it on-par.

## Changelog
:cl:
add: Borgs can speak and understand Spacer, Japanese, Gutter, Russian, Selenian and Zolmach
add: An expanded language module to allow Borgs to speak and understand Calcic, Voltaic, Buzzwords, Sylvan, Monkey, Slime, Shadowtongue, Piratespeak, Terrum, Vox, Xenoknockoff and Xenocommon.
del: Borgs can no longer speak or understand Calcic and Voltaic.
/:cl:

### CODE REVIEW

**Comment by 3D-Bat** [comment]
Two things for this one:

- Let me know if this should be locked behind research.
- Also let me know if the shadowspeak, piratespeak and terrum, for example, should be separate and locked behind more research.

**Comment by GoldenAlpharex** [comment]
I'm not sure why you're locking away Nekomimetic, Calcic and Voltaic behind research, feels a little odd considering they already can understand them right now.

Another thing to consider is how this would affect AIs, if this doesn't affect them, it probably should, and if it does, well, then the three languages that I mentioned above should be added back.

**Comment by SpaceVampire** [comment]
I really dislike the idea of any kind of language module. I would be fine with updating the set that they can understand, but it should be fixed in nature.

**Comment by desertmote** [comment]
> I'm not sure why you're locking away Nekomimetic, Calcic and Voltaic behind research, feels a little odd considering they already can understand them right now.
> 
> Another thing to consider is how this would affect AIs, if this doesn't affect them, it probably should, and if it does, well, then the three languages that I mentioned above should be added back.

I removed those because I find it fitting for our frontier station to have exotic personnel hired due to scarcity or budgeting, who sub sequentially are not accounted for in the original language programming of the AIs. However I do agree that nekomimetic should not be part of that.

**Comment by GoldenAlpharex** [comment]
> I really dislike the idea of any kind of language module. I would be fine with updating the set that they can understand, but it should be fixed in nature.

Yeah, I support this. Plus, updating the set would go through the feature freeze, the module, maybe not.

**Comment by GoldenAlpharex** [comment]
I'm still honestly not a fan of this, I'm not sure I see the point behind this upgrade, aside from making the Curator feel even less necessary.

**Comment by desertmote** [comment]
> I'm still honestly not a fan of this, I'm not sure I see the point behind this upgrade, aside from making the Curator feel even less necessary.

so because curator is the worst thought out job with a shitty omnitongue band-aid the only role that would make sense having the ability is disqualified

**Pull request closed without merging**
