### PR TITLE
Fix for teshari human hats.

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Additional code for https://github.com/Skyrat-SS13/Skyrat-tg/pull/21001 to end the human's hats trouble for teshari. 

It fixes only this:

dreamseeker_yyFtzwKAls

How? Just hold the CTRL and try to move diagonaly.
## Changelog

:cl:
fix: fix for teshari and their human's hats
/:cl:

### CODE REVIEW

**Comment by RaShCat** [comment]
Screenshot Test failure... Well. It's was not an offset!
изображение

**Comment by ghost** [comment]
So. The check of mutant_override is not enough to solve the trouble with modsuits on teshari. 
x_x

**Comment by ghost** [comment]
Due to my lack of knowledge of code base... The offsets will be fixed by someone else. :С

**Comment by ghost** [comment]
@Gandalf2k15 , maybe someone alredy fixing this?
 <details><summary>Teshari trouble</summary>

изображение
</details>

**Review by tf-4 — APPROVED** [review]

**Pull request merged**
