### PR TITLE
[NONMODULAR]Shocks & Zaps, Episode 2

### PR DESCRIPTION
**Pull request by Vizoplez**
## About The Pull Request
Somewhat WIP and may change. Changes shocks to be much more, or less lethal depending on your siemens coefficient, and what gear you are wearing.

## Why It's Good For The Game
Shocks wont even crit you at this current point in time, even with a cranked up SM and playing IPC (The race w/ the highest siemens coefficient, last I checked).

This actively discourages people from making cranked-up SM builds, and generally bypassing it to the grid, since they themselves might fall victim to the various effects this, and other future PRs will attempt to integrate, such as heart attacks (now in code); and potential 'flashing' of limbs (disintegration) 

## Changelog
:cl:
tweak: Oh god oh fuck. Electrical shocks are now much more lethal. Wear proper protection before tampering with equipment.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Uh... Yes, shocks can crit you, I'm not sure where you're taking that from. Sometimes you get shocked many, many times in a row and it ends up killing you, I've seen it happen.

**Comment by Vizoplez** [comment]
> Uh... Yes, shocks can crit you, I'm not sure where you're taking that from. Sometimes you get shocked many, many times in a row and it ends up killing you, I've seen it happen.

Thats only w/ two or more shocks, I'm talking about a single, instantaneous shock.

**Comment by GoldenAlpharex** [comment]
> > Uh... Yes, shocks can crit you, I'm not sure where you're taking that from. Sometimes you get shocked many, many times in a row and it ends up killing you, I've seen it happen.
> 
> Thats only w/ two or more shocks, I'm talking about a single, instantaneous shock.

And how is it a bad thing that you don't die from getting shocked by your first grille? It just makes griefing using shocking grilles even more powerful, and just makes it so you can die in maints by accident by lagging and running into a grille. Very nice gameplay :)

**Comment by Vizoplez** [comment]
> > > Uh... Yes, shocks can crit you, I'm not sure where you're taking that from. Sometimes you get shocked many, many times in a row and it ends up killing you, I've seen it happen.
> > 
> > 
> > Thats only w/ two or more shocks, I'm talking about a single, instantaneous shock.
> 
> And how is it a bad thing that you don't die from getting shocked by your first grille? It just makes griefing using shocking grilles even more powerful, and just makes it so you can die in maints by accident by lagging and running into a grille. Very nice gameplay :)

One; you seem to be misinterpreting both the code, and statement of the PR. Hilariously, lower-tier shocks; such as the ones you usually find in maints (if engineering didnt bypass the SM) can actually be less lethal with my changes :/

They have a higher divisor and generally more forgiving variation to them for low-tier shocks, so.

**Comment by Gandalf2k15** [comment]
Ooooof

**Pull request merged**
