### PR TITLE
Void Raptor - Departure Extention Polishing

### PR DESCRIPTION
**Pull request by LovliestPlant**
## About The Pull Request
Resolves issues with #16941. Specifically:
- Replaces the maints maze near departures with a cafe
- Moved the Russian bar over there too
- Redesigns the mining dock
- Moves the Drone bay to accommodate
- Nudges the chapel a few tiles closer to the main station

## How This Contributes To The Skyrat Roleplay Experience
Makes better use of the prime real estate near departures, and resolves some complaints made by players.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
Overview

VR_v2_All2

New Cafe / Old Bar

VR1940-maint

New Mining Dock / Office

VR_v2_SmallShuttle

</details>

## Changelog

:cl:
del: Void Raptor -Overhauled Departures maints area
qol: Void Raptor -made something easier to use
balance: Void Raptor -Re-arranged mining office and dock, moved drone bay and russian bar.
fix: Void Raptor - Fixed broken disposal pipes
/:cl:

### CODE REVIEW

**Comment by DevinShafer** [comment]
Hi, just making sure this fixes the current issue with disposals chutes, specifically the security delivery chute not being connected up?

**Review by Paxilmaniac — CHANGES_REQUESTED** [review]
While you're at it, please change the mining shuttle to be just a normal mining shuttle, rather than the large one.

**Comment by LovliestPlant** [comment]
Second Pass
VR1940-all
VR194-dock
VR1940-maint

**Comment by LovliestPlant** [comment]
Alt with the default mining shuttle as opposed to the current large shuttle.
VR-smallShuttleAlt
(I'll make it fit a bit better if we go this route)

**Comment by Paxilmaniac** [comment]
> Alt with the default mining shuttle as opposed to the current large shuttle. VR-smallShuttleAlt (I'll make it fit a bit better if we go this route)

That is not how the default shuttle docks ill let you know now, its 5x7 and docks on the side, so itd crush that window below it

**Comment by LovliestPlant** [comment]
It sure is, huh. (I hadn't tested that quick mockup)
Here's a proper arrangement with the smaller shuttle:
VR_v2_SmallShuttle

Also, I'm a tad worried about the nature of that merge conflict. Have I GitHub'd incorrectly? (If I did, I have a sneaking suspicion of what it might be and can make a new PR real quick)

**Pull request closed without merging**
