### PR TITLE
[50% MODULAR, 100% AWESOME] A Modest & Reasonable Janitorial Access Buff or: How I Learned to Stop Worrying and Love The Mop

### PR DESCRIPTION
**Pull request by Nerev4r**
## About the COOL Request
Hello.
In this PR, I have decided to do three things; all in the name of expanding the access that the station's custodians have. 

Firstly, I have given Janitors equivalent access to a Paramedic; short of surgery. This covers all their regular areas, plus basic departmental access-- as a side effect, this includes the Morgue, but it's often filthy and revenant-stricken anyway.  

image
Secondly, I have given them a silver ID, as well as changed the color on it. I changed the color because, unsurprisingly, Service lime looked awful on a silver background. The silver ID is, one, so I could ensure their access would actually fit. Two, silver IDs are a marking of honor and dedication, and frankly Paramedics should get one too; but janitors are the unsung heroes of the station. Three, befitting the whole..
image
...y'know, a Silver ID will allow consenting HoPs and heads of staff to be able to grant them a little more access if, say, the Bridge is regularly being filthied by LT3's beloved ectoplasm anomalies.

## How This Contributes To The Skyrat Roleplay Experience
Janitorial work is one of the most important things on the station that, unfortunately, is primarily impeded by access. It has long been a custom throughout Earth history to grant custodians further access to most of a building for cleaning, and perhaps if we adopt this, Janitors will be seen as more reliable -- and less people will have to take damp rags because they can't count on them to show up. I believe Janitors to be generally one of the most docile phenotypes of Homo Skyrattus, and this shouldn't lead to anything crazier than what paramedics are capable of; plus antags are now opt-in, so. 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

 image

</details>

## Changelog
:cl:
add: Janitors now have Paramedic-level access. Be sure to call for them!
/:cl:

### CODE REVIEW

**Comment by CandleJaxx** [comment]
░░░░░░░░░░░░▄▄                     
░░░░░░░░░░░█░░█                  
░░░░░░░░░░░█░░█                  
░░░░░░░░░░█░░░█                  
░░░░░░░░░█░░░░█                  
███████▄▄█░░░░░██████▄ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█░░░░ Valve, ░░░░░█ 
 ▓▓▓▓▓▓█░░░░Add This░░░░█  
▓▓▓▓▓▓█░░░░Please!░░░░░█ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█████░░░░░░░░░█   
██████▀░░░░▀▀██████▀

**Review by tf-4 — COMMENTED** [review]
I don't really like this conceptually, it discourages people talking to each other. Also, that list of accesses is... it doesn't really make sense and it seems like it's literally just copy-pasted paramedic access - like, why would the janitor need mining? Medical mechs? Construction? Mineral storeroom?

Overall 👎 from me.

**Comment by Nerev4r** [comment]
> I don't really like this conceptually, it discourages people talking to each other. Also, that list of accesses is... it doesn't really make sense and it seems like it's literally just copy-pasted paramedic access - like, why would the janitor need mining? Medical mechs? Construction? Mineral storeroom?
> 
> Overall 👎 from me.

I can cut several of these, but basic department access still remains important to me.

**Comment by rosextango** [comment]
> I don't really like this conceptually, it discourages people talking to each other. Also, that list of accesses is... it doesn't really make sense and it seems like it's literally just copy-pasted paramedic access - like, why would the janitor need mining? Medical mechs? Construction? Mineral storeroom?
> 
> Overall 👎 from me.

Hey, as someone who has played janitor, I can tell you that more than half the time when we ask to get into places, we get ignored, or we get treated like a nuisance because we don't have access and therefore need to be babysat, which isn't a fun interaction for either party. Yes, it discourages people from talking to each other in theory, but as it is right now in practice, a lot of talking just doesn't happen between people. You can't force people to interact if they don't want to.

**Comment by Iamgoofball** [comment]
@tf-4 tbh i'd be willing to try expanded access janitor upstream for the chaos aspect of "janitor with the keyring for every door" making him an interesting target, lemme pitch it to the maintainers

**Comment by lessthnthree** [comment]
> @tf-4 tbh i'd be willing to try expanded access janitor upstream for the chaos aspect of "janitor with the keyring for every door" making him an interesting target, lemme pitch it to the maintainers

That could be interesting.

**Comment by Nerev4r** [comment]
Cut mining and Medical Mech Access; sorry!

**Comment by YakumoChen** [comment]
I heartily disagree with giving the janitor an ID explicitly meant for heads of staff (no, Head of Cleaning is not a real command role)

**Comment by YakumoChen** [comment]
I don't think for the purposes of this PR they need more than cargo, sci, and basic med access. There really isn't a reason for them to go into construction, or morgue, or... botany? 

(I disagree with the PR as a whole but these are the points I'm most against)

**Comment by HoodMilk** [comment]
What if they had a literal keyring that worked liked a jaws of life on powered doors (without causing any damage and without the sound)

**Comment by CandleJaxx** [comment]
> I heartily disagree with giving the janitor an ID explicitly meant for heads of staff (no, Head of Cleaning is not a real command role)

paramedics use silvers too

**Comment by YakumoChen** [comment]
> > I heartily disagree with giving the janitor an ID explicitly meant for heads of staff (no, Head of Cleaning is not a real command role)
> 
> paramedics use silvers too

They do not
Paramedics spawn with grey IDs like all non-command staff.

**Comment by RatFromTheJungle** [comment]
i don't think we need another role given basic-departmental access (which, for some departments is access to their lathe aswell), for the sake of doing something purely mechanical

**Comment by tf-4** [comment]
Yeah I'm very confident in not wanting this for reasons stated.

**Comment by Iamgoofball** [comment]
we'll be doing this upstream anyhow as a form of keychain deal where heads of staff can approve a janitor's access remotely

**Pull request closed without merging**
