### PR TITLE
[MIRROR] Adds Character Loadout Tab to preferences (with just a small handful of items to start)

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/83521
--------------------
## About The Pull Request

Adds a Character Loadout Tab to the preference menu

This tab lets you pick items to start the round with

![image]image

image

## Why It's Good For The Game

This has been headcoder sanctioned for some time, just no one did it. So here we are.

Allows players to add some additional customization to their characters. Keeps us from cluttering the quirks list with quirks that do nothing but grants items. 

## Changelog

:cl: Melbert
add: Character Loadouts
del: Pride Pin quirk (it's in the Loadout menu now)
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
needs the rest of the loadout categories ported

**Comment by Gandalf2k15** [comment]
final bug: doesnt actually write the prefs

**Comment by Wolfy-Sage** [comment]
its me or its not letting people rename some items?

**Comment by Gandalf2k15** [comment]
> its me or its not letting people rename some items?

Fixed

**Comment by Gandalf2k15** [comment]
we can fix rename upstream

**Comment by thegrb93** [comment]
Vox breath mask broken, probably other species too :<

**Pull request merged**
