### PR TITLE
[sprite change] sec plasmaman sprite update

### PR DESCRIPTION
**Pull request by CandleJaxx**
resprites red plasmamen sec uniforms to match the current peacekeeper aesthetic

### CODE REVIEW

**Comment by ghost** [comment]
would this not be better as a new item rather than removing the oldsec variant? I know the oldsec stuff sees some use in events and whatnot..

Also I really need to change which account im on jfc.  This is orion hi hello

**Comment by Gandalf2k15** [comment]
Non modular changes to icons aren't acceptable, best thing to do is make a peacekeeper variant and make the changes in the modular folder

**Comment by SpaceVampire** [comment]
Yeah, if you make a non-modular chance to an core icon file, you have to worry about it ever being touched in the future.
It should be handled the way that was suggested above.

**Comment by Gandalf2k15** [comment]
Hi please enact the above changes and reopen this later.

**Pull request closed without merging**
