### PR TITLE
Repaths a few outdated instances of the HoS's cap, removes a straggling redsec item

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
While ago, TG updated the HoS cap to have a new type path, hats/hos/cap. This let berets go under hats/hos without technically falling under the same thing as the cap.
We never fully updated those paths; hence, our HoS's cap looked like TG's before it was reskinned. This fixes that, along with cleaning a few outdated but related bits of code.

Also removed the HoS skirt from their garment bag again because it's redsec AND its against the skirt restrictions of bluesec

## How This Contributes To The Skyrat Roleplay Experience
Updates an out-of-date thing, fixes bugs the out-of-dateness caused, and returns consistency to security.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
  icons still working for repathed itemss
dreamseeker_Gu8cCXrWTN

  reskins still work waow
image
  
  no more skrirt
dreamseeker_jWHBThlCX2

</details>

## Changelog

:cl:
fix: fixed the HOS's cap being a bit outdated initially. Now it should match the Lopland standard!
del: fixed the HOS's old redsec skirt being available in the garment bag.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
wait wtf why does TG not have this stuff the same

**Comment by ghost** [comment]
wait does TG have this issue or did we miss something

**Comment by ghost** [comment]
This is a TG file causing issues wtf

**Comment by ghost** [comment]
This can be sorted out later

**Comment by ghost** [comment]
Found the bastard

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
