### PR TITLE
[WIP] [modular] Gives a few selectable genetic traits to traits menu. And creates accent.

### PR DESCRIPTION
**Pull request by Guidesu**
## About The Pull Request

I want to give the possibility of more customizations to make each character unique.
So I am kinda lightly editing the genes I wish to add to be more balanced since it will be round-start genetical traits that you can't really remove it.

The mutations in mind i will need to work is:

Positive traits:
Animal Olfaction: You can smell objects and your snout/nose is very sensitive.

Neutral:
Glowy: Natural Glowy light, Really small. 
I mean it's not good since it can be annoying sometimes to have an eternal light on you.
And it's not game-breaking or abusable.
Coughing
Sneezing

Accent traits:
Swedish
Chav
Cowboy
Pirate
German
French

Negatives traits:
Spastic: Will suffer muscle spasms 
Two Left Feet: Well.. you will have some problems moving

## Why It's Good For The Game
More customization is always welcome!
This still W.I.P but it's very simple

## Progress

- [ ] Makes accent's

- [ ] just adds small modified genetic traits.

## Changelog

Don't mind the changelog for now

:cl:
add: Added new things
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
I'm not sure that it's a good idea, it seems like most of it will likely result in powergaming more than anything. If you really want to have a specific gene for your character, just go bug Genetics for it like everyone else.

**Comment by SpaceVampire** [comment]
This feels like a pretty awful idea.
As it kinda ruins the whole point of genetics.
By having people able to just start with whatever free powers they might want.

**Comment by Guidesu** [comment]
Nah. I will limited the ammount of genes you can pick
You can only pick like one gene round start that it

**Comment by Guidesu** [comment]
So since this is an idea and a project to improve my coding.
i need get people opinions

**Comment by Guidesu** [comment]
> telepathy: is a concern because it lets people speak in public, about even the most blatantly illegal things, with 0 chance of getting overheard, and will lead to a lot of people just standing around, saying nothing even people standing right next to them can't hear.
> 
> Animal Olfaction: is just a free pinpointer if you use it right, and one that can't be taken away as easily.
> 
> Spider Webs: this would have to be an alternate version, with a lot bigger of a cooldown to discourage it being spammed everywhere.
> 
> ## Glowy: There is nothing wrong with this one, it's as safe as they come.
> with a mind to preventing these from being easily abused, this could be a very good addition.

Yup I have in mind to make it not abusable

**Comment by desertmote** [comment]
Most mutators are LRP, too harmful for yourself, or too strong to start out with. There are already plans to implement the few worthy genetic mutators to species traits in a refactored way that keeps it from becoming an issue to the station. 
i.e. 
>    ◦ Abilities bound to 1 turf (the player is in). Think of webbing that deletes when the player leaves that turf. 

The only remaining mutators are glow and anti-glow (which is broken afaik), and maybe it would be wise to keep those so genetics has a purpose besides giving SA to sec.

**Comment by Guidesu** [comment]
Why do you even give 
👎  if this is just an idea and i  need opinions?

**Comment by SpaceVampire** [comment]
> 
> 
> Why do you even give
> -1 if this is just an idea and i need opinions?

Because its a fundamentally bad idea that diminishes the job of a department?

**Comment by chefferz** [comment]
Glowy would allow bodies to be found easier.
Animal Olfaction would allow sec to easily powergame finding someone w/o sensors or hiding.

The ONLY thing that makes sense here would be the accents, anything else could be easily abused.

**Comment by Gandalf2k15** [comment]
Hi,if you want to redo this and bring it upto the standards stated, feel free to remake this PR 👍

**Comment by ghost** [comment]
i actually like the idea of accents and the few listed negative ones, the fact they werent traits in the start was kinda weird.
maybe keep the accents to the somewhat rp-able ones (language accents) because pirate/cowboy crew is just a tad lrp to START the round with. they're still funny to get later tho.

**Pull request closed without merging**
