### PR TITLE
[MODULAR] Resprites the HoP's winter coat

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

see title. Based on /veegee/'s on but modified heavily.

HOPCoat

Oh, also made it so that it can hold the HoP's gun.

## How This Contributes To The Skyrat Roleplay Experience

stupid captain, im fuckin ballin (it looks better)

## Changelog

:cl:
imageadd: resprited the HoP's wintercoat
balance: HoP's coat can now hold their egun
/:cl:

### CODE REVIEW

**Comment by Seris02** [comment]
Make it a reskin, not a resprite

**Comment by axietheaxolotl** [comment]
> Make it a reskin, not a resprite

ok but why

**Comment by softcerv** [comment]
> 
> 
> > Make it a reskin, not a resprite
> 
> ok but why

Choices are good. It doesn't hurt to have both options in the game.

**Comment by RatFromTheJungle** [comment]
lookin' like a broke-ass santa claus...

**Pull request merged**
