### PR TITLE
LOOC, Whisper hotkeys. LOOC stylings

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
also moved up the lookup hotkey from L to P so it doesn't conflict with LOOC

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
ugh. we need something for tgui

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by Gandalf2k15** [comment]
Requires TGUI rebuild.

**Comment by Azarak** [comment]
> 
> 
> Requires TGUI rebuild.

yeah but then every upstream PR with UI changes will require that too. Something automated would help

**Comment by Gandalf2k15** [comment]
I recommend leaving the styles out until then

**Comment by Azarak** [comment]
> 
> 
> I recommend leaving the styles out until then

done

**Pull request merged**
