### PR TITLE
fixes another obj thing

### PR DESCRIPTION
**Pull request by theselfish**
## About The Pull Request
how did anyone miss this
how did someone donate for this and not realise

## How This Contributes To The Skyrat Roleplay Experience

above

## Proof of Testing

it works

## Changelog
:cl:
fix: another clothing file fixed
/:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
checks are failing

**Comment by SpaceLoveSs13** [comment]
you dont have to keep merging master wait a bit because I am fixing bunch of missed prs.

**Comment by theselfish** [comment]
> you dont have to keep merging master wait a bit because I am fixing bunch of missed prs.

Habit.

**Comment by SpaceLoveSs13** [comment]
this one will do it

**Pull request merged**
