### PR TITLE
Redoes the blackmarket chevvy shuttle once again, now it might just actually look like a blackmarket cargo shuttle

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
ZAMN
image

## How This Contributes To The Skyrat Roleplay Experience
I wasn't happy with how the current one worked out, now I can stop hating it every time I see it

## Changelog

:cl:
add: The blackmarket chevvy, supposedly a blackmarket cargo shuttle, now finally looks the part
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
When do we get a mapping tag

**Comment by Zonespace27** [comment]
When we fix the bot to apply it

**Comment by Jolly-66** [comment]
> When we fix the bot to apply it

Fix it

Signed, an angry mapper

**Comment by ghost** [comment]
looks like the bot refuses

**Comment by Zonespace27** [comment]
> looks like the bot refuses

the bot holds no power

**Pull request merged**
