### PR TITLE
[MODULAR] infinite showers for the interlink

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

Infinite showers for the interlink.

## Why It's Good For The Game

Because it's fun to RP in the showers and not have the shower suddenly run out of water.

## Changelog
:cl:
add: infinite showers for the interlink
/:cl:

### CODE REVIEW

**Comment by Seris02** [comment]
hhhh

**Comment by NullDagaf** [comment]
"RP in the showers"

**Comment by hugmeorelse** [comment]
Good, clean RP.

**Comment by hugmeorelse** [comment]
I don't see an issue with this if there's no issue with the actual code.

**Comment by Gandalf2k15** [comment]
Have you made sure this can't be cheesed by unwrenching and moving the inifinte chem generator elsewhere?

**Comment by NullDagaf** [comment]
> Have you made sure this can't be cheesed by unwrenching and moving the inifinte chem generator elsewhere?

Can't unwrench a shower.

**Comment by Seris02** [comment]
What they said, wrenching it just changes the temp

**Pull request merged**
