### PR TITLE
[MIRROR] [MDB IGNORE] Grayscale sofas [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/71539
--------------------
## About The Pull Request
Ports some sofa sprites from over at https://github.com/BeeStation/BeeStation-Hornet/pull/7547 and makes them grayscale. Also random tool colours now use defines.

image

image

## Why It's Good For The Game
Gives us the opportunity to make different coloured couches more easily. 
## Changelog

:cl: Tattle, PestoVerde322
imageadd: couches are now grayscale
code: random tool colours now use defines
/:cl:

### CODE REVIEW

**Review by GoldenAlpharex — APPROVED** [review]
Code seems good, needs input from the maptainers for now though.

**Comment by Paxilmaniac** [comment]
cutely has to repath every single sofa on modular maps

**Comment by Tastyfish** [comment]
> cutely has to repath every single sofa on modular maps

Run the UpdatePaths script.

**Review by Jolly-66 — APPROVED** [review]
Yeah sure its couches.

I ran the updatepaths because Paxil is afraid.

**Review by Paxilmaniac — APPROVED** [review]
Incredible

**Pull request merged**
