### PR TITLE
[MIRROR] GAGSify colored/job labcoats [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/79096
--------------------
## About The Pull Request
Title.

## Why It's Good For The Game
Cuts down on sprites, converts colored labcoats into GAGS labcoats.

GAGS labcoats are primarily built by 3 components on top of the, well, actual labcoat.

- The shoulder parts
- Back pattern
- Belt/sash thing

<details>
<summary> Before Image </summary>

image

</details>

<details>
<summary> After Image </summary>

image

</details>

## Changelog

:cl: Jolly
image: Colored labcoats have been GAGSed! Please report any weird oddities on Github.
fix: The coroners lab coat is no longer offset by one pixel.
/:cl:

### CODE REVIEW

**Comment by vinylspiders** [comment]
@Jolly-66

**Comment by Jolly-66** [comment]
> @Jolly-66

You need to update the digi stuff. Doing it is simple enough, you can copy 3/4 of the parts from the main file but you'll need to make the labcoat bases, which requires 0 spiritng background to do.

**Comment by ghost** [comment]
Robotics Labcoat will also need to be changed for this, as we have one with a Black base.

**Comment by Jolly-66** [comment]
Someone else is more than welcomed to help with this, both me and Mal are too busy to get to this.

**Comment by jjpark-kb** [comment]
It will still need digitigrade versions... I can try to figure it out later ofc.

**Pull request merged**
