### PR TITLE
[NON-MODULAR] Removes "ACCESS_QM" from shaft miner and cargo-tech

### PR DESCRIPTION
**Pull request by RatFromTheJungle**
# * Also from the dep-guard
## About The Pull Request
When QM was made a head, removing his access being given out by skeleton-crew was assuredly overlooked, giving both cargo-techs and shaft-miners access to his locker (and his gun), No other department does this.

## How This Contributes To The Skyrat Roleplay Experience
Skeleton crew proc'ing probably shouldn't give everyone a head's access.

## Changelog

:cl:
fix: Fixes the QM's access being given out by skeleton crew, as he is a Head now.
/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
title could afford with being more consise

**Comment by RatFromTheJungle** [comment]
> title could afford with being more consise

ok

**Comment by KathrinBailey** [comment]
@RatFromTheJungle what player count is considered "skeleton crew"?

**Comment by Zenitheevee** [comment]
> @RatFromTheJungle what player count is considered "skeleton crew"?

not _quite_ sure, I remember it being something closer to the 30-pop area, Though I _think_ it also varies between maps?

They're, _realistically_, Numbers we wont reach that often and so accounting for them is kinda off.

After further research, The base _Default_ setting is 20. This could be something that can be and potentially has been changed.

**Comment by RatFromTheJungle** [comment]
> @RatFromTheJungle what player count is considered "skeleton crew"?

usually around 50, from how it happens during lowpop

**Comment by Iamgoofball** [comment]
they have ACCESS_QM so that if there's just a cargo tech they can run the department on their own and, if i recall correctly, operate some equipment that's QM access only

**Comment by RatFromTheJungle** [comment]
> they have ACCESS_QM so that if there's just a cargo tech they can run the department on their own and, if i recall correctly, operate some equipment that's QM access only

the only thing that is, is the express console, which if a real-issue could just be moved to tech access or something,

when they have QM access they get access to the QM's gun, door remote, etc, meanwhile no other department does the equivalent (scientists don't get RD access, etc)

**Comment by Iamgoofball** [comment]
to be fair, the QM isn't a proper head nor do they have a gun(roundstart) at /tg/code

**Pull request closed without merging**
