### PR TITLE
More integrated circuit fixes

### PR DESCRIPTION
**Pull request by hecksadecimal**
## About The Pull Request
This pull request addresses some other problems with integrated circuits that others have brought up. Namely, the inability to recycle circuits and the parsing problems with special characters when it comes to importing a circuit. 

I've made some key changes to the integrated circuits module to make it use materials more like other machines do, while also setting the framework for the possibility of certain chips requiring more exotic materials than just iron. For the moment though, the printer only accepts iron and all the circuits still only need it. With these changes part and assembly recycling also works.

In addition, removing the redundant sanitization of the circuit program allows for people to use special characters. This was already possible to do by setting the pin in-game, and the import was causing discrepancies.

Update: While this was still up I went ahead and fixed the problem with assemblies sending a message to everyone when they're repaired. 

## Why It's Good For The Game
Total waste of metal to print circuits you can't recycle. Not being able to use an exclamation point in an imported circuit was very annoying, especially in the case of constant chips where you would have to remove it and set it manually, then rewire it.

## Changelog
:cl: 0xEFF
fix: Fixed a strange behavior with integrated circuit importing which caused it to ignore things like punctuation.
fix: Fixed integrated circuit recycling.
fix: Fixed repairing assemblies broadcasting to the entire universe.
refactor: The integrated circuit printer has been changed internally to allow for circuits with special material requirements. Currently unused.
/:cl:

### CODE REVIEW

**Comment by hecksadecimal** [comment]
Uh oh linter failure. Where'd it go wrong?
Give me a moment while I solve this.

**Comment by hecksadecimal** [comment]
Yep alright, that fixed it. Ready to go now.

**Comment by Arctaisia** [comment]
There's a few extra problems, sorry for the additional to stack on- But circuitry headwear removes the hair/horns sprites, while the digi circuit jumpsuit doesn't appear with it's own sprite. Just two simple problems, otherwise, thanks a bunch for the fixes, nerd.

**Comment by hecksadecimal** [comment]
> 
> 
> There's a few extra problems, sorry for the additional to stack on- But circuitry headwear removes the hair/horns sprites, while the digi circuit jumpsuit doesn't appear with it's own sprite. Just two simple problems, otherwise, thanks a bunch for the fixes, nerd.

@Arctaisia I dunno if I'll get to those tonight, but I'll put it on my radar.

**Comment by hecksadecimal** [comment]
I threw in the fix for repairing an assembly. 
They should no longer be broadcasting to everyone.

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by GoldenAlpharex** [comment]
Just thought I'd tell you, constant chips can be edited while in the assembly. I thought that was an intended feature, but from what I'm reading here, it might not.

**Comment by hecksadecimal** [comment]
I don't think that's an intended feature, no.

**Pull request merged**
