### PR TITLE
[MIRROR] Allow splitting admin tabs

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/58310
--------------------

## About The Pull Request

This PR adds a configuration option for splitting the admin tab sub groups into separate tabs. This allows for greater convenience, as if the tabs are split you do not have to scroll.

But of course, this is something that needs to be toggled first, and current behavior stays as default.

This can be toggled in preferences, and here is how it looks in action:
image

And if you prefer, you can disable splitting as well.
image

An option for wiping and fetching verbs has also been added to the stat panel debug menu, as previously you could only wipe verbs.

## Why It's Good For The Game

Allows for greater convenience in administration and less scrolling.

## Changelog
:cl: Celotajs
admin: Added a configuration option for splitting the admin tab into multiple tabs
admin: Interviews have been moved to the Tickets tab
qol: It is now possible for administrators to split the admin tab into multiple tabs
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
https://github.com/tgstation/tgstation/pull/58396

**Comment by celotajstg** [comment]
fix is up https://github.com/tgstation/tgstation/pull/58397

**Comment by celotajstg** [comment]
oh and don't forget https://github.com/tgstation/tgstation/pull/58395

**Comment by Gandalf2k15** [comment]
> oh and don't forget [tgstation/tgstation#58395](https://github.com/tgstation/tgstation/pull/58395)

Awesome ,thanks

**Pull request merged**
