### PR TITLE
[NON-MODULAR] OH MY GOD OFF-STATION GRAVGEN, SHUT UP SHUT UP SHUT UP

### PR DESCRIPTION
**Pull request by RimiNosha**
## About The Pull Request

Tin. Fuck you.

## How This Contributes To The Skyrat Roleplay Experience

No deafening alert about black holes every FUCKING TIME THE SERVER STARTS

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

image
image

And station gravgens are still loud and obnoxious. I still fucking hate the audio message.
image

</details>

## Changelog

:cl: RimiNosha
qol: Made off-station gravity generators shut the fuck up.
/:cl:

### CODE REVIEW

**Comment by theselfish** [comment]
Unless you've made some sort of subtype for it, the generator makes noise.

A lot of noise.

**Comment by RimiNosha** [comment]
It silences the stupid-ass loud announcement which is heard across the entire server aside from people on the title screen.

**Comment by Jolly-66** [comment]
Did you know I'm responsible for this?

**Comment by ghost** [comment]
While we're at it you should remove the modular voiceline too since its pointlessly long, pointlessly loud, and pointless

**Comment by theselfish** [comment]
> It silences the stupid-ass loud announcement which is heard across the entire server aside from people on the title screen.

You could put the generator in a box on the same z-level so-

Now I'm confused...
Map change in the images. Code change.

**Review by tf-4 — APPROVED** [review]

**Pull request merged**
