### PR TITLE
Orderly alt titles

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Adds some alt titles for Orderly

## How This Contributes To The Skyrat Roleplay Experience

Roleplay flavour

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
 
image

</details>

## Changelog

:cl: LT3
spellcheck: Orderly alt titles
/:cl:

### CODE REVIEW

**Comment by theselfish** [comment]
"Other dept guards' alt-titles should be kept to [department] guard to avoid confusion, unless the department gets a re-do." Per @Iamgoofball

**Comment by lessthnthree** [comment]
I wasn't sure if that meant that they should all start with Medical, in that case I can remove Porter.

**Comment by Iamgoofball** [comment]
Porter's a bit of a weird one for Medical specifically, yeah.

**Comment by lessthnthree** [comment]
> Porter's a bit of a weird one for Medical specifically, yeah.

It's a UK/Canada thing. But yeah, removed.

**Pull request closed without merging**
