### PR TITLE
[MODULAR] Adds spiked collar to dorms vendor

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
Yeah
## How This Contributes To The Skyrat Roleplay Experience
It does

## Changelog

Eh

### CODE REVIEW

**Comment by YakumoChen** [comment]
> You currently have a negative Fix/Feature pull request delta of -22. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

ok

**Comment by gonenoculer5** [comment]
This is still an addition and should be documented with an add: CL.

**Comment by ErdinyoBarboza** [comment]
Also arent collars lovevend items usually? for obvious reasons

**Comment by thestubborn** [comment]
yakumo, expect the russians to pester and whine at you for this

they really don't like people touching that vendor

**Comment by YakumoChen** [comment]
> This is still an addition and should be documented with an add: CL.

meh

**Pull request merged**
