### PR TITLE
[UPDATE] [VOX SPRITES] Updates missed features, fixes bugged sprites to heads.

### PR DESCRIPTION
**Pull request by CandleJaxx**
candle's dumb

IM SEETHING IM SEETHING

vox shouldn't be grey and sprite names are dumb

## Changelog
:cl:
fix: Adds missing Vox icons for their mining gear.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
@CandleJaxx Did you test it to make sure it worked as you wanted it to?

**Comment by CandleJaxx** [comment]
> @CandleJaxx Did you test it to make sure it worked as you wanted it to?

yep! it works locally, just a sprite issue, had to add the paths n such

**Comment by GoldenAlpharex** [comment]
Hi there, there's been a lot more icons added in this PR, it would be nice if you could take some screenshots of how those look in-game now. Thanks!

**Comment by CandleJaxx** [comment]
> Hi there, there's been a lot more icons added in this PR, it would be nice if you could take some screenshots of how those look in-game now. Thanks!

i didn't actually add many sprites, i just moved over / shifted pixels to the left and right on glasses to fit the face- it'll all look the exact same, just on the different sprites

**Comment by CandleJaxx** [comment]
> Hi there, there's been a lot more icons added in this PR, it would be nice if you could take some screenshots of how those look in-game now. Thanks!

for your benefit tho, since i can't show the chanegs in game very well (very minor) here

from
image
to
image

**Comment by CandleJaxx** [comment]
image
image
image
image
as said, all working as intended

**Comment by KasparoVy** [comment]
> 
> 
> image
> image
> image
> image
> as said, all working as intended

Woah, the tail markings actually work for you! Was that fixed in this PR as well?

**Review by Funce — APPROVED** [review]

**Pull request merged**
