### PR TITLE
Hydra sprites with possible quirk [WIP]

### PR DESCRIPTION
**Pull request by C0rva1r**
## About The Pull Request
Adding Hydra heads to the game. It is purely cosmetic and does not add any direct mechanical changes. I am open to add more to it like a quirk to speak as one of the heads on the character. Another is duping hat and mask sprites for each head if that is interested. This is considered a WIP but very close to being finished. It includes head markings for each head and eyes.

## Why It's Good For The Game

Adds more creativity for players to RP as a hydra character or character's. Something to note however is a bug that markings appear to overlap helmets but may be due to slow icon updates. Also, it's fun seeing hydra heads stuff themselves into one head space on helmets.

## Changelog
:cl:
add: Added Hydra snout
add: Added Hydra Markings for eyes and horns.
imageadd: Hydra snout and Markings
/:cl:

### CODE REVIEW

**Comment by Funce** [comment]
Use your changelog as a way to introduce the changes that the Pull Request brings as a whole. You're not explicitly removing anything that's currently in the server, so you won't need to mark anything as such. Just include it as a note in the PR.

**Comment by C0rva1r** [comment]
Oh sorry, I'll fix that

**Comment by KasparoVy** [comment]
Those wing sprites you added look dope.

**Comment by Guidesu** [comment]
can i finish this PR mate?

**Comment by Guidesu** [comment]
i really want to see this on the game but its seems you forgot about it

**Comment by C0rva1r** [comment]
> i really want to see this on the game but its seems you forgot about it
Personal life has put a number on me for a good while and been heavily ill motivated. Sorry for putting this thing dead for so long but steadily getting back onto to things and I honestly won't mind if you wish to take over. If you like, I can even help out with it. Up to you.

**Comment by C0rva1r** [comment]
> i really want to see this on the game but its seems you forgot about it

Personal life has put a number on me for a good while and been heavily ill motivated. Sorry for putting this thing dead for so long but steadily getting back onto to things and I honestly won't mind if you wish to take over. If you like, I can even help out with it. Up to you.

**Comment by C0rva1r** [comment]
If you want, you can message me on discord. The name is Trin

**Pull request closed without merging**
