### PR TITLE
[NON-MODULAR] Allows AI to send messages to CC

### PR DESCRIPTION
**Pull request by DuffCreeper**
## About The Pull Request

Simply adds a new proc that just, kinda lets AI see the button to send a message and so the captain and ai can send a message etc
image

## Why It's Good For The Game

Allows the AI to handle more duties if command is being either dead on the floor, non existing or doing their thing in a locked room with someone *cough

## Changelog
:cl:
qol: The AI can now communicate with CC, the interaction opportunities are now limitless
/:cl:

### CODE REVIEW

**Comment by FlamingLily** [comment]
Does this mean the AI can request nuke codes/buy shuttles, or is it restricted to solely CC messages?

**Comment by DuffCreeper** [comment]
> Does this mean the AI can request nuke codes/buy shuttles, or is it restricted to solely CC messages?

Just messages. Didn't see the point for nuke codes since AIs cant really arm the nuke without the disk

**Comment by FlamingLily** [comment]
~~Followup, does this allow borgs to do the same? Either by intention or possibly oversight?~~

Lily check the code challenge

**Comment by tf-4** [comment]
Silicon power creep

**Comment by DuffCreeper** [comment]
> Silicon power creep

slowly the ai will replace the captain...

**Comment by SpaceVampire** [comment]
BeepBoop

I really don't think the AI needs to be able to message CentCom. It is far easier for them to do that then the Captain, and I feel like that is just going to lead to the message system being overused. There is a reason it is only Captain access already, and not just the rest of the command staff in general. But I guess this is more... policy or something? Given that the effects of messaging CentCom are already only something that effects anything if admins choose to act on it.

**Pull request merged**
