### PR TITLE
[NON-MODULAR] Air Alarms now start on Contaminated mode and use less power on Contaminated mode, to reduce the negative impact that inattentive atmospherics techs have on a round.

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request

Air Alarms now start on Contaminated mode by default.
WEMIsKVUPe

## How This Contributes To The Skyrat Roleplay Experience

So, the bottom line is that atmos is terribly documented(the official /tg/ wiki is a disgrace with info from literally 2014) and the consequences of this change(bad gas flooding being 10x harder) doesn't matter at Skyrat because flooding gets you banned anyways.

This resolves any issues with floods never getting fixed by atmos techs who are asleep at the wheel or simply uneducated because they haven't been told the atmos secrets by an ancient atmosian elder.

## Changelog
:cl:
balance: Air Alarms now start on Contaminated mode, to reduce the negative impact that inattentive atmospherics techs have on a round.
balance: Scrubbers set to Contaminated mode no longer drain an extremely large amount of power.
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
Me when I drain all the station's power instantly

**Comment by Iamgoofball** [comment]
set the engine up

**Comment by tf-4** [comment]
you underestimate how much power air alarms set to contaminated use

**Comment by Iamgoofball** [comment]
yeha i just checked the numbers you're right, i'll adjust that down too given this change

**Comment by GuiltyNeko** [comment]
Central primary on contaminated draws either 60 or 100 kilowatts.

**Comment by tf-4** [comment]
I don't think this is even an issue that needs resolving anyway tbh.

**Comment by Iamgoofball** [comment]
@tf-4 it's more reliable than trying to get atmos techs to do their job given the shoddy documentation on said job

the only reason not to do these changes is because it makes plasmaflooding non-viable, but also, like, plasmaflooding is nonviable on skyrat by virtue of "you will be banned" so there's no issue there

**Comment by YakumoChen** [comment]
I feel like this isn't really a needed change. The AI can change these as well.
Plasma flooding also isn't banned, it requires an opfor and localised flooding is still within reason for it.

**Comment by GoldenAlpharex** [comment]
Yeah, no, this isn't the way to fix that kind of issue. If Atmos is too complicated to get into, then there should be more in-game ways to teach people the various intricacies of Atmos.

The solution isn't to just baby-proof the station.

**Pull request closed without merging**
