### PR TITLE
[TESTMERGE] Makes icon2html not work

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
it is #1 overtime and it doesn't quite get you an asset every time anyway. I'd like to see how performance goes without it

## Changelog
:cl:
tweak: ICON2HTML is no longer active.
/:cl:

### CODE REVIEW

**Comment by Arturlang** [comment]
Maybe add a way for admins to toggle it on/off

**Comment by Gandalf2k15** [comment]
Untm'ing for this next test.

**Comment by hugmeorelse** [comment]
weh

**Comment by hugmeorelse** [comment]
bump

**Comment by Azarak** [comment]
b

**Comment by Azarak** [comment]
DONT

**Pull request merged**
