### PR TITLE
P90

### PR DESCRIPTION
**Pull request by LeonY24**
## About The Pull Request

P-90 submachinegun at Guns Galore code, made as a preparation for a new away mission we will hopefully make and will not abandon. 
Chambered in .32 ACP, just as CFA's Wildcat. 
Shouldn't be jamming at least for 2 mags, which are 100 boolets to fire.
Has all the sprites - on your back, in your hands and in the world. There are also sprites for the magazine. 
image
image
image
image
image

## How This Contributes To The Skyrat Roleplay Experience

We (some people who murdered Scalamov and massacred Black Mesa) are planning to create one more away mission for gateway. To be forward - there is a downstream server using this repository, so we have to create stuff here.

:cl:
add: P-90 submachinegun, chambered in .32 ACP.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Wasn't there already a PR that added the P90 recently? Or did it get closed?

**Comment by Stalkeros2** [comment]
> Wasn't there already a PR that added the P90 recently? Or did it get closed?

Some stuff happened to it (the gun), and it can't be spawned in because of that.
image

**Comment by LeonY24** [comment]
> Wasn't there already a PR that added the P90 recently? Or did it get closed?

i've found out what the problem is and why P90 wasn't accessible, too ashamed to tell what is the problem, on my way to fix it rn

**Comment by LeonY24** [comment]
i think i've fixed it

**Review by Gandalf2k15 — APPROVED** [review]
LGTM

**Pull request merged**
