### PR TITLE
[MDB IGNORE] Revert "[Void Raptor] Removes the floating Moffucinis Pizzeria"

### PR DESCRIPTION
**Pull request by RimiNosha**
Reverts Skyrat-SS13/Skyrat-tg#19231

Speedmerge moment. Please for the love of integrity do not make this kinda behavior normal. Do the right thing and reopen the removal PR and give people time to provide feedback.

### CODE REVIEW

**Comment by Kepteyn** [comment]
Reverting it is probably not best - it was rude, it was sudden, it hurt someone who has done nothing but show love and care to this community because they care about this community, but the change happened, and probably would have happened in some way or another anyway. What's important is to learn from this and handle things better in the future.

**Comment by Paxilmaniac** [comment]
Jolly and myself are both in agreeance that we do not want the floating pizza place as it was implemented, and I'm not reverting on this.

**Comment by RimiNosha** [comment]
So be it. Not like I'm staying here much longer anyways.

**Review by Jolly-66 — APPROVED** [review]
The speed merge wasn't warranted.
Discussion can go forward with this, however, my feelings and opinions in my PR are still true, and would personally see this not being baked into the map. 

This is discussion for another time, however.

**Comment by RimiNosha** [comment]
It won't automerge cause MDB errored out.

**Pull request merged**
