### PR TITLE
[NONMODULAR]Swarmer rework to manage them somewhat

### PR DESCRIPTION
**Pull request by Vizoplez**
## About The Pull Request
Title

## Why It's Good For The Game
People complained aaa

## Changelog
:cl:
fix; Swarmers can no longer teleport Megafauna or other fauna
tweak: Swarmers will no longer aggro megafauna/fauna by default
tweak: Swarmers will now do 10 brute to any target it cannot teleport (if its a simplemob)
tweak: Swarmers can no longer teleport fauna into safezones
/:cl:

### CODE REVIEW

**Comment by Echopsychotic** [comment]
I feel they should need something to combat the miners when they come for them cause they will. Since you cant do damage to the miners.

**Comment by Vizoplez** [comment]
> I feel they should need something to combat the miners when they come for them cause they will. Since you cant do damage to the miners.

They already get disablers/shock beams and attacks that can stamcrit them, dont worry!

**Comment by SpookyTheFox** [comment]
> tweak: Swarmers will now do 10 brute to any target it cannot teleport (if its a simplemob)

Which mobs are effected by this, do you have examples? Are there any specific mobs that swarmers can stun and then do 10 brute to, on top of this? That scenario would be a problem, and undermine how swarmers are supposed to work.
Also, I was under the impression that player controlled swarmers on lavaland were rightfully getting reverted. They are just shootable fluff, there's no reason to have yet more griefy ghost roles and always antag slots.

**Comment by Vizoplez** [comment]
> > tweak: Swarmers will now do 10 brute to any target it cannot teleport (if its a simplemob)
> 
> Which mobs are effected by this, do you have examples? Are there any specific mobs that swarmers can stun and then do 10 brute to, on top of this? That scenario would be a problem, and undermine how swarmers are supposed to work.
> Also, I was under the impression that player controlled swarmers on lavaland were rightfully getting reverted. They are just shootable fluff, there's no reason to have yet more griefy ghost roles and always antag slots.

No mob that can be stunned can also take ten brute, this is because the beams themselves are simply disablers that used to teleport any simplemobs away.

**Comment by SpookyTheFox** [comment]
> 
> 
> > > tweak: Swarmers will now do 10 brute to any target it cannot teleport (if its a simplemob)
> > 
> > 
> > Which mobs are effected by this, do you have examples? Are there any specific mobs that swarmers can stun and then do 10 brute to, on top of this? That scenario would be a problem, and undermine how swarmers are supposed to work.
> > Also, I was under the impression that player controlled swarmers on lavaland were rightfully getting reverted. They are just shootable fluff, there's no reason to have yet more griefy ghost roles and always antag slots.
> 
> No mob that can be stunned can also take ten brute, this is because the beams themselves are simply disablers that used to teleport any simplemobs away.

In most cases. Note that swarmer disablers are lethal against borgs, so I wonder what other edge cases are out there.

**Comment by SpaceVampire** [comment]
So uh. Given that the PR which triggered this was reverted.
I am going to assume this can just be closed.

**Pull request closed without merging**
