### PR TITLE
[semi-modular][ready] COATS and another, more serious detective costume

### PR DESCRIPTION
**Pull request by thestubborn**
## About The Pull Request

dorks fill this shit out, but I'm a dork

## Why It's Good For The Game

the body is still in the tree, we should get it down, it's been a week detective.
also I wanna get balls deep in ash walker snatch and this coat lets me do it

## Changelog
:cl: Det. Raphael Ambrosius Costeau
add: a costume for the serious side of the ying-yang of investigating bodies in trees
add: two coats, one for pimps and the other for jackals
add: a few more sprites because why give myself LESS work
removed: the will to live
/:cl:

RIGHT SHIT BEFORE I FORGET
Sprites are from...fulp, desert rose, WW13, Desert Rose, Civ 13 (maybe, I cant remember) Yog(maybe) Tau...whatever, the Russian server.

obligitory dm me and ask for them to get removed, or I can buy em or whatever I dunno

### CODE REVIEW

**Comment by thestubborn** [comment]
ALSO THE DETECTIVE SHIT IS IN THE VENDER NOW ARE YOU HAPPY GODS?

**Comment by KasparoVy** [comment]
These look dope @thestubborn 

How many will just appear as `jsuit` when selected by digitigrade users, though?

So many awesome clothing PRs lately, but everything's `jsuit` lmao.

**Comment by thestubborn** [comment]
i dont know digi, i dont touch digi

**Comment by KasparoVy** [comment]
Guess we're getting some more jsuit x_x

**Comment by thestubborn** [comment]
could always sprite it yerself

most i can do is colour edits

**Comment by Jureiia** [comment]
@thestubborn to fix the jsuit issue you just need to add
mutant_variants = NONE
to all the suit items atleast, for stuff that covers the legs, goodluck

**Comment by thestubborn** [comment]
oh, right
cool

**Comment by thestubborn** [comment]
shit i dunno how many i'd even do that on
cant you do the recommend changes thing on...them?

**Comment by Jureiia** [comment]
uhhh, maybe, I'm pretty new to github
hold on

**Pull request merged**
