### PR TITLE
Adds a janitorial closet to DS2, places soap in the syndicate bases

### PR DESCRIPTION
**Pull request by faaaay**
## About The Pull Request

Did you know that there is _no_ cleaning equipment anywhere on the DS2 or the lavaland Syndicate base, except in the brig? This PR aims to changes that by adding a small custodial closet to DS2 (tucked away in what was previously maint below the firing range) and placing a bar of syndicate soap in the Deck Officer/Station Admiral's bathrooms..

## Why It's Good For The Game

The bases are otherwise very well-equipped, which leads me to think this is somewhat of an oversight. As it stands, if a microwave breaks, your only options are to A) make your own from liquid gibs (which might be out-of-character for many characters) or B) nab it from the DS2's brig (which you may not have access to).  
There is an argument to be made that this is a light form of powercreep, as syndie soap is fairly powerful (as far as a cleaning implement can be, at least); however, I think this is in-line with the current gear given to syndicate ghostroles.

## Changelog
:cl:
add: Custodial closet in DS2
add: Soap in the Deck Officer/Station Admiral's bathrooms
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
@unit0016 edit to DS2. Review at your leisure

**Comment by unit0016** [comment]
Janitor wardrobe is a bad idea, but that's about the closest I can get to a problem with this tbh. Brigtiding was too easy anyways.

Also these duplicates(?) spread around the map. Laptop trackpad moment? Who knows.
image
image

**Comment by faaaay** [comment]
> 
> 
> Janitor wardrobe is a bad idea, but that's about the closest I can get to a problem with this tbh. Brigtiding was too easy anyways.
> 
> Also these duplicates(?) spread around the map. Laptop trackpad moment? Who knows.

That's... odd, I don't know how I didn't see that. I'll fix that. 
If I could ask, what's wrong with the janitor vendor?

**Comment by faaaay** [comment]
Update: I am a fool, there's a little custodial closet with a mop and bucket tucked away in DS2 maint. While I think it would be ideal to have soap for cleaning microwaves, this PR isn't really necessary.

**Pull request closed without merging**
