### PR TITLE
[SEMI-MODULAR] [READY] Blueshift

### PR DESCRIPTION
**Pull request by axietheaxolotl**
-----

fsafsafasfsa

-----

> _Jesus... How much is the maintaining cost for this Vessel, again? And all this for a tax loophole?_
> - Unnamed Central Command Official

**NSV Blueshift is a brand new multi z-level high-pop map created by IsaacTheSharkWolf!**

This map's been in-progress for a while now, so we're happy to finally show it off in a good state!

### Top Level - Command/Bridge, AI Sattelite, Science, Medical, and Civilian

BSSC3

### Mid Level - Security, Service, Engineering, Floor 2 of Cargo, and Departures

BSSC2

### Bottom Level - Atmospherics, Bottom Floor of Cargo w/ Mining, GENPOP, and Arrivals

BSSC1

## Credits

Plenty of people helped with this map, so here are some credits:
```
IsaacTheSharkWolf: Main Mapper
AxieTheAxolotl/Viro: Ran private testing, and did code for the map. Helped with the general design.
Gonenoclear5: Helped with Engineering
Floofball: Made parts of Perma
Delta Station: Borrowed some of the maints off of.
```

## How This Contributes To The Skyrat Roleplay Experience

It's a good map, yes? Variety is the spice of life, as they say. And this is pretty spicy if I do say so myself.

## Changelog

:cl: IsaacTheSharkWolf, AxieTheAxolotl, Floofball
add: Nanotrasen Science Vessel Codename: Blueshift has been put into service! 
/:cl:

### CODE REVIEW

**Comment by ForrestWick** [comment]
Pog

**Comment by IsaacTheSharkWolf** [comment]
Hope people like my work!

**Comment by axietheaxolotl** [comment]
> 
> 
> Hope people like my work!

^ Too lazy to do code himself. :trollface: 
jk love u isaac

**Comment by IsaacTheSharkWolf** [comment]
FYI if anyone wonders what the emptied out maints sections are, those were left empty on purpose because i couldn't be bothered to fill in every crevice from the getgo (and to preserve my sanity)

**Comment by Arctaisia** [comment]
Based beyond belief.

Very nice to see it finished, though! <3

Although if it is a large ship, remember that the name should be NSV, not NSS, as the last S is for Station, V is for Vessel, just a heads up ^^

**Comment by axietheaxolotl** [comment]
> 
> 
> Based beyond belief.
> 
> Very nice to see it finished, though! <3
> 
> Although if it is a large ship, remember that the name should be NSV, not NSS, as the last S is for Station, V is for Vessel, just a heads up ^^

me when I try and correct something that I thought was a mistake only to find out that it was correct in the first place and I made it wrong with my "fix"

**Comment by Arctaisia** [comment]
> > Based beyond belief.
> > Very nice to see it finished, though! <3
> > Although if it is a large ship, remember that the name should be NSV, not NSS, as the last S is for Station, V is for Vessel, just a heads up ^^
> 
> me when I try and correct something that I thought was a mistake only to find out that it was correct in the first place and I made it wrong with my "fix"

Big heck, still, nice work coding it in for them! Always lovely to see it finished and usable! Hopefully we can see it at the same time we see the overmap TM'd or fullmerged again, that'd be one of the best shifts ever on TGRat :eyes:

**Comment by ghost** [comment]
Just a note, if SSDecay is ever fixed, the pre-rusted walls wont be necessary

**Comment by sqnztb** [comment]
As one of the few people insane enough to main a paraplegic, here's my one (1) probably fruitless plea to ask for at least another elevator connecting the middle and lower levels. And to fix your existing one. The `industrial_lift` structures don't have the `publicElevator` id set so the button to call it down does nothing.

Also, you have a bunch of roundstart active turfs:
image

... not all of this is the fault of the Blueshift. Some of this is loaded from space ruins and such, but a super quick search shows you have ~255 roundstart AT. Should probably fix them at some point (mapping tab -> Show roundstart AT list)

Edit:

Also uhhh the emitters for the supermatter aren't connected to the grid. They receive no power at roundstart. There's only one wire network inside the engine room and it's all on the input side of the SMES. You need some sort of network from the output side of the SMES going to the emitters unless you want to jump start the supermatter by throwing a crowbar into it like I did.

image

... and a few other issues. I'll stop editing and make a separate comment once I finish my first pass of testing.

**Comment by IsaacTheSharkWolf** [comment]
> As one of the few people insane enough to main a paraplegic, here's my one (1) probably fruitless plea to ask for at least another elevator connecting the middle and lower levels. And to fix your existing one. The `industrial_lift` structures don't have the `publicElevator` id set so the button to call it down does nothing.
> 
> Also, you have a bunch of roundstart active turfs:
> image
> 
> ... not all of this is the fault of the Blueshift. Some of this is loaded from space ruins and such, but a super quick search shows you have ~255 roundstart AT. Should probably fix them at some point (mapping tab -> Show roundstart AT list)
> 
> Edit:
> 
> Also uhhh the emitters for the supermatter aren't connected to the grid. They receive no power at roundstart. There's only one wire network inside the engine room and it's all on the input side of the SMES. You need some sort of network from the output side of the SMES going to the emitters unless you want to jump start the supermatter by throwing a crowbar into it like I did.
> 
> image
> 
> ... and a few other issues. I'll stop editing and make a separate comment once I finish my first pass of testing.

Thank you, i'll try my best fixing these issues, i'm not sure how to fix the active turf thing though, i'm fairly sure all turfs connected to space are either closed or vacuum, but i could have missed a few

**Comment by IsaacTheSharkWolf** [comment]
I'll also consider adding an elevator to arrivals

**Comment by IsaacTheSharkWolf** [comment]
Small 1 tile elevator added to arrivals, specifically for wheelchair users, it's close to the public mining dock

**Comment by sqnztb** [comment]
Hooooookay just from my initial pass....

Atmospherics is an utter mess. You have omni pumps/mixers that are connecting to nearest pipes and ignoring the pipe bridges.
image
image
This is particularly heinous. Distro is connected to the output of the mix tank, and not the actual airmix.
image

Multiple unconnected pressure tanks. If you want these to connect at roundstart, you need to varedit the `initialize_directions` of the tank.
image

Turbine's airlock will never cycle because the dual pump is also improperly piped:
image

Here's the output from check plumbing verb, note the tanks, the pipe bridges, and all of the thermos:
image

Unwired telecomms SMES. Does nothing except dump its roundstart charge into the powernet until it's drained:
image

Likewise the gravity gen's SMES isn't doing anything except taking charge from the powernet until it's full. It doesn't feed to anything:
image

Unwired APC on the fore starboard solars:
image

Unwired APCs for fitness/locker room:
image

Unwired APC for medbay storage:
image

No area for the maints on the far right of this screen. ALSO I REALLY, REALLY NEED TO THROW IN MY TWO CENTS and say that putting a second armory that is just one r-wall away from regular maints is a **REALLY BAD IDEA**.
image

There are a ton of gaps in intercom coverage Some of this is pretty minor. Some not so much.
image
image
image

No dead body placer in the morgue:
image

Consider adding a button to toggle all of the curtains at once for the psych:
image


And regarding your active turfs, they can absolutely be fixed. Roundstart ATs happen whenever you have turfs near each other that have different `initial_gas_mix`. Example - your xenobio kill chamber has `/turf/open/floor/iron/freezer` (which has a regular gas mix) and `/turf/open/floor/circuit/telecomms` which has a `TCOMMS_ATMOS` gas mix. And right below you've got stairs turfs (which have a gas mix) in space. This is mostly a mapper gripe. If you want to keep the aesthetics that you've got, you'd probably want to code in some `/airless` turf subtypes that have `initial_gas_mix = AIRLESS_ATMOS`. The same goes for these dorms. They have a `/turf/open/floor/iron/kitchen_coldroom` which have a `KITCHEN_COLDROOM_ATMOS`. If you want that style of tile, consider the `/turf/open/floor/iron/showroomfloor`. etc etc etc.
image
image

And that's all from me. For now.

**Comment by Gandalf2k15** [comment]
Oh shit, we can use this on the overmap as mutliZ ship station

**Comment by IsaacTheSharkWolf** [comment]
Thank you for pointing out bugs, i'll work trough them now!

**Comment by IsaacTheSharkWolf** [comment]
also regarding atmos, for some reason the pipes autoconnect despite them being directional pipes on the map maker, i'll need to find a workaround for that

**Comment by GoldenAlpharex** [comment]
> Oh shit, we can use this on the overmap as mutliZ ship station

So long as we don't allow it to land anywhere lmao

But imagine a moving station... :^)

**Comment by IsaacTheSharkWolf** [comment]
fixed most of the issues sqn noted, currently working together with them to squash more potential bugs, one of which possibly regarding the SM's cooling loop.

**Comment by IsaacTheSharkWolf** [comment]
additional bugs fixed, SM cooling loop has been fixed too

**Comment by Sonic121x** [comment]
this map look amazing , all the decoration and greening make it feel like a place that can comfortably live in , and if this combine with that overmap ship system
but there is some problem...

1. There are no Nanodrug vendor(/obj/machinery/vending/drugs) in medbay.
2. The Auxilliary Surgical Theatres are rather dark,there is a light switch,but no light to be found.image

**Comment by WitherVictor** [comment]
1.Medbay storage can't get electricity supply
4G$EB$3`@O0UUEPIZGZBH6J

2.Elevator conncets 2f and 3f cannot use, in fact most of elevators can only use once or twice then never worked again
XY7F%H_32GTNG V($IW}P_U

3.Mass driver cannot use
1G2$ P$M3OX4(IO`5Q11YNQ

I can't understand why put bottles of fentanyl here, that's totally poison for murder
R7R1{MMT8 S QX`2BWH$XE

_3VRA8G~6O RR(9C~FBB8`G

**Comment by IsaacTheSharkWolf** [comment]
i actually don't know why the mass driver won't work, it's not any differently configured then on other maps.

**Comment by IsaacTheSharkWolf** [comment]
other then that, fixed all other issues

**Comment by IsaacTheSharkWolf** [comment]
nvm i may have fixed the massdriver issue, it was just outside the controll range var so i put the longrange variant in it's stead.

**Comment by Sonic121x** [comment]
image
image
[2nd floor top right]This area in general just have way too much powerful loot for maintenance(bluespace beaker,combat implant pack with reuseable autosurgen,etc...),and the locked room up there have useable spell book like knock and forcewall.

[2nd floor Engineering Front desk]light switch goes under the window,and the maintenance door don't belong to a area,which cause it to stay unpowered
image

**Comment by IsaacTheSharkWolf** [comment]
nerfing loot a bit, keep in mind that the abandoned library area cannot be reached by conventional means so generally speaking the loot is a little better.

**Comment by Sonic121x** [comment]
> nerfing loot a bit, keep in mind that the abandoned library area cannot be reached by conventional means so generally speaking the loot is a little better.

the key has a consitent placement,so anyone that already know where it is can simply rush for it with just some tool.maybe consider only leave a lesser smoke for spell book(/obj/item/book/granter/spell/smoke/lesser) and remove other...

**Comment by thestubborn** [comment]
image
why has the nt rep got a marx bust?

**Comment by axietheaxolotl** [comment]
> 
> 
> image
> why has the nt rep got a marx bust?

I brought this up myself when the NTRep's office was first done. Quote Isaac, "Know your enemy" or something like that. At this point, I just kinda find it funny. It's more so a practical gag than anything meant to be taken seriously. "The most capitalistic man on the station has a marx bust" is just, funny. Gives me SNL vibes or something.

**Comment by GoldenAlpharex** [comment]
According to the linter: `ValueError: dmm failed to parse, check for a syntax error near or after key 'hAP'`

**Comment by Gandalf2k15** [comment]
Test merge I guess.

**Comment by Arctaisia** [comment]
Less of a gameplay thing, more of a lore thing;
Remember that it should still be NSV, not NSS, I don't know if y'all changed it yet or not, but S is for Stations, defined as artificial orbitting structures exceeding 150x150m in area, or attached to asteroids and 150x150m. Bases (as in NSB) are the same, but rather than orbitting, are on a large celestial body such as a moon or planet. Vessels (as in NSV) are shuttles capable of FTL travel (Which is hard to do mechanically, but given it's size, I'd assume it capable) (Shuttles being structures with the capability to traverse over large distances independently, usually because of engines, doesn't have to be possible ICly, just in it's little lore).

 There's also Platforms, stations under 150m^2, Outposts, same deal but for bases, and Craft, as sublight shuttles.

Just thought I'd clear this up as I've noticed it hasn't changed, and a vessel labelled as a station is confusing, *weh

Unless it is an actual station rather than a shuttle, if so, ignore what I said, *weh

**Comment by GoldenAlpharex** [comment]
I heavily do not recommend a round-start jukebox on station, as it creates a lot of lag for people with high ping, and because they can be heard from everywhere on station, pretty much, which can be annoying for those that don't want to hear it.
image

**Comment by Gandalf2k15** [comment]
This looks like a big ole vessel to me

**Comment by GoldenAlpharex** [comment]
> Less of a gameplay thing, more of a lore thing;
> Remember that it should still be NSV, not NSS, I don't know if y'all changed it yet or not, but S is for Stations, defined as artificial orbitting structures exceeding 150x150m in area, or attached to asteroids and 150x150m. Bases (as in NSB) are the same, but rather than orbitting, are on a large celestial body such as a moon or planet. Vessels (as in NSV) are shuttles capable of FTL travel (Which is hard to do mechanically, but given it's size, I'd assume it capable) (Shuttles being structures with the capability to traverse over large distances independently, usually because of engines, doesn't have to be possible ICly, just in it's little lore).
> 
> There's also Platforms, stations under 150m^2, Outposts, same deal but for bases, and Craft, as sublight shuttles.
> 
> Just thought I'd clear this up as I've noticed it hasn't changed, and a vessel labelled as a station is confusing, *weh
> 
> Unless it is an actual station rather than a shuttle, if so, ignore what I said, *weh

This is definitely bigger than that. It's straight up bigger than Delta and Meta put together.

**Comment by GoldenAlpharex** [comment]
The Tesla and Singularity engines need to not be made available at round start, both for performance and for game balance reasons.

**Comment by Azarak** [comment]
Air in space on the openspace tiles is simulated and non planetary, which caused the server to chug. Change their type to `/turf/open/openspace/airless/planetary`

**Comment by thestubborn** [comment]
because this annoys me and i just saw it on journey (boutta be a bad bitch and make a pr)
you got a station for cyto? one that isn't just squeezed into xenobio?

**Comment by GoldenAlpharex** [comment]
> Air in space on the openspace tiles is simulated and non planetary, which caused the server to chug. Change their type to `/turf/open/openspace/airless/planetary`

That would explain a lot. I'll remember that for future reference.

**Comment by IsaacTheSharkWolf** [comment]
replaced all spaceborne openspace tiles with the planetary variant, attending some other issues people have noted, i should have an updated version out soon!

hopefully the second test will be better performance wise

**Comment by IsaacTheSharkWolf** [comment]
> Less of a gameplay thing, more of a lore thing;
> Remember that it should still be NSV, not NSS, I don't know if y'all changed it yet or not, but S is for Stations, defined as artificial orbitting structures exceeding 150x150m in area, or attached to asteroids and 150x150m. Bases (as in NSB) are the same, but rather than orbitting, are on a large celestial body such as a moon or planet. Vessels (as in NSV) are shuttles capable of FTL travel (Which is hard to do mechanically, but given it's size, I'd assume it capable) (Shuttles being structures with the capability to traverse over large distances independently, usually because of engines, doesn't have to be possible ICly, just in it's little lore).
> 
> There's also Platforms, stations under 150m^2, Outposts, same deal but for bases, and Craft, as sublight shuttles.
> 
> Just thought I'd clear this up as I've noticed it hasn't changed, and a vessel labelled as a station is confusing, *weh
> 
> Unless it is an actual station rather than a shuttle, if so, ignore what I said, *weh

it's in fact a spaceship, just some naming errors cought up in communication that's all.

**Comment by axietheaxolotl** [comment]
> 
> 
> Less of a gameplay thing, more of a lore thing;
> Remember that it should still be NSV, not NSS, I don't know if y'all changed it yet or not, but S is for Stations, defined as artificial orbitting structures exceeding 150x150m in area, or attached to asteroids and 150x150m. Bases (as in NSB) are the same, but rather than orbitting, are on a large celestial body such as a moon or planet. Vessels (as in NSV) are shuttles capable of FTL travel (Which is hard to do mechanically, but given it's size, I'd assume it capable) (Shuttles being structures with the capability to traverse over large distances independently, usually because of engines, doesn't have to be possible ICly, just in it's little lore).
> 
> There's also Platforms, stations under 150m^2, Outposts, same deal but for bases, and Craft, as sublight shuttles.
> 
> Just thought I'd clear this up as I've noticed it hasn't changed, and a vessel labelled as a station is confusing, *weh
> 
> Unless it is an actual station rather than a shuttle, if so, ignore what I said, *weh


https://user-images.githubusercontent.com/86872535/133200112-e603f69f-96c1-498a-9dcf-24c5bc636c44.mp4

**Comment by IsaacTheSharkWolf** [comment]
The new update should improve on performance by a lot, simply due to the fact it uses the correct openspace tiles.
This hopefully massively reduces maptick, there are a few other tricks up my sleeve however if it needs to be reduced further.

**Comment by Sonic121x** [comment]
these lift can go though the floor into a unintented level

1.(cargobay at the left of the cargoshuttle docking location) imageimage
2.(near arrival,inside the Common Mining Dock)imageimage

**Comment by IsaacTheSharkWolf** [comment]
i'm not sure how to fix that

**Comment by Sonic121x** [comment]
after #7962  dice bag now have a new type path(/obj/item/storage/dice) instead of (/obj/item/storage/pill_bottle/dice)
image

this is a neat idea but the shield wall generator only have 8 tile range,so this won't work
image

**Comment by WitherVictor** [comment]
Those atomspheric gas tubes have design problem, they always cause some area cannot get enough oxygen and slowly kill them when they offline, and temperature unit cannot get any gas to cool down/heat up from red tube because of that, which make it unable to use cryo cell

**Comment by Sonic121x** [comment]
its cool to have a roundstart tesla/singularity engine,but the design here have a lot of problem.
image
1:the generator are connect directly into the power net.and with the amount of power both engine capable to generate.this can cause APC to start arking #5767 
2:it seemes there has a place to put down a field generator,but the railing actually block field from being generated
image
image
3:generaly people want the tesla to be limit on a single tile,but the design here are not allow them to do soimage
image
it should be like this
4:also if someone decide to setup a singularity engine,not it will strip away all the windows,also it will emp the smes due to the close range(i would said just don't even think about singularity engine)
image

even though a competent engineer can deal with this with no problem,but you cannon expect every engineer in SS13 to be competent at all time

**Comment by Sonic121x** [comment]
in the AI Satellite Hallway 
image
these two turret are taser/laser turret,which in stun mode,those taser won't be able to do anything though the window
other AI Satellite like the one on NSS Journey have a disabler turret,maybe take a look into that.
image
in the supermatter room,this meter fail to connect to a pipe.
image
in Atmospherics,the omni pump link to the green pipe instead of the intented one,maybe consider change those to green bridge pipe.
image
Science Division there a scrubber didn't connect to the pipe

**Comment by IsaacTheSharkWolf** [comment]
Fixed issues listed except for the SMES placements at the tesla engine location.

**Comment by sergeirocks100** [comment]
You might want to change the header image.

It's white with no outline, and it's pretty much invisible against Github's white background.

**Comment by axietheaxolotl** [comment]
> 
> 
> You might want to change the header image.
> 
> It's white with no outline, and it's pretty much invisible against Github's white background.

github's default background is purple-grey
why are you using light theme github what is wrong with you

**Comment by sergeirocks100** [comment]
> 
> 
> > You might want to change the header image.
> > It's white with no outline, and it's pretty much invisible against Github's white background.
> 
> github's default background is purple-grey
> why are you using light theme github what is wrong with you

I have no clue when the defaults changed, but Github has always been white for me.

**Comment by Lauwma** [comment]
Atmo needs proper bluespace batteries roundstart like every atmo. I would even argue that considering the size it should have its own set of SMES

**Comment by Lauwma** [comment]
There's clearly a very big power issue, maybe you should add more power SMES overall and I would even argue they should be upgraded considering the station almost eats up 1MW roundstart

**Comment by NanoCats** [comment]
Can somebody please explain this map's solars to me? 

Do they work at all? From what I remember of TGcode they need a LOS to space to function properly.

Unless of course, they are in fact ornamental or panels work differently on Skyrat, in which case hush my mouth.

image

Like, I guess, _technically_ they have one tile?

**Comment by Lauwma** [comment]
So the station drains more than 2.5MW and the apc starts arcing at 2.5MW. I think every floor will need their own set of SMES with heavy voltage lines in maintenance going from the SM/Tesla to thoses set of SMES at each floors

**Comment by sqnztb** [comment]
> So the station drains more than 2.5MW and the apc starts arcing at 2.5MW. I think every floor will need their own set of SMES with heavy voltage lines in maintenance going from the SM/Tesla to thoses set of SMES at each floors

This is partially incorrect. The station isn't drawing that much under full load. The station will only draw around 830kW under maximum theoretical load. The additional load seen is from the multiple SMES units around the station having their inputs also hooked into the grid, causing false draw as they pull from and push to the grid at the same time. (Use the secrets panel -> all areas unpowered -> recharge SMESs to see for yourself)

Once the roundstart drain is done, it settles around ~350kW draw.

**Comment by IsaacTheSharkWolf** [comment]
hopefully i've fixed the issue of roundstart power draw, every department except for engineering has a powernet substation that should help aleviate some stress on the powernet as well as serve as a buffer.
Atmos now has 2 bluespace powercells for your atmos needs.
I don't know if the solars work now or not but they should?
Also other powernet issues have been resolved, the tesla engine shouldn't be hotwired to the net anymore.

**Comment by sergeirocks100** [comment]
I went ahead and made a quick edit to the logo using a public domain space background.

blueshiftnewlogo

It should be perfectly visible on both light and dark themes.

**Comment by Sonic121x** [comment]
no slime in xenobio
Q20210918132413
[Cryogenics in medbay]the Temperature control unit isn't linked to the waste loop
Q20210918132811
this is one way to fix it
image
[Atmospherics] the omni pump and Temperature control unit linked to the cyan pipe instead the intented one,change the cyan pipe to bridge pipe should be able to fix this
image
[AI Satellite]this should be a transit tube dispenser(/obj/structure/transit_tube/station/dispenser/flipped)
image
maybe should add a ChemMaster here so if someone doing cyto don't need to run across the room just to filter something
image
[3rd floor Starboard Quarter Solar]the Solar Control computer didn't  have a cable connect to the solar panel,also the door said its Starboard Bow Solar which it isn't
image
[External Airlock on top of viro]i'm not really sure whats going on here,maybe it just on my end,but can someone check this?
image
[Telecommunications Room] this Temperature control unit didn't connect to the waste loop
image
[Xeno Bio]these two Temperature control unit also didn't connect to the waste loop,and the top one aren't even connect to anything
image
I still think the loot in this room are too powerful,especially the guardian card which allow you choose the type,and the force wall book inside the bookcase.
image

**Comment by thestubborn** [comment]
> 
> 
> no slime in xenobio
> [snip]

I like that, it gives people a reason to do cyto

**Comment by NanoCats** [comment]
> I like that, it gives people a reason to do cyto

Not 100% sure about that myself. Every time I need something and it's locked behind a job that I have no business, meta knowledge, or training doing I hunger for death.

**Comment by IsaacTheSharkWolf** [comment]
multiple fixes made!

**Comment by axietheaxolotl** [comment]
fixes/changes:
Tesla no longer hotwired to the grid
Most departments now have SMES substations
Nonessential SMES units don't have any power draw at roundstart
Decorated the shop on layer 2 and 3, layer 2 has a clothing store while layer 3 has a vox/plasmaman store
Extended the colored decal lines in public hallways to hopefully make finding certain departments a bit easyer
Put number tag on most public staircases so you know what floor you are on.
Added grey slimes to xenobio
Various smaller fixes

**Comment by axietheaxolotl** [comment]
We should have made it so Space Ruins don't spawn, in order for performance to be better.

Also a bunch of map changes that I am not going to list out because I am lazy.

**Comment by Sonic121x** [comment]
image[Engineering SMES]
This design here doesn't work,the red cable aren't getting any power form smes,and the hub didn't connect to the red cable on round start,also it drop a cable piece in the hub's place

**Comment by IsaacTheSharkWolf** [comment]
> image[Engineering SMES]
> This design here doesn't work,the red cable aren't getting any power form smes,and the hub didn't connect to the red cable on round start,also it drop a cable piece in the hub's place

Fixing rn

**Comment by Sonic121x** [comment]
image[2nd Floor right side of the Kitchen]
these two APC left unpower due to the wiring
image[Chemistry]
Would be nice if this closet start anchored
image[AI Satellite Hallway]
Since taser bolt cannon pass though glass,these two turret should be useing disabler for stun mode instead,like the one in snowbox.

**Comment by IsaacTheSharkWolf** [comment]
making some additional fixes

**Comment by Sonic121x** [comment]
image
[Engineering SMES Room]the supermatter cable hot wired to the power grid though SMES on the right

**Pull request merged**
