### PR TITLE
[MODULAR] Adds minimum players to several high-severity items and kits for traitors.

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Title

Yes I'm aware it's a master commit, I made an oopsie and said fuck it

## Why It's Good For The Game

Reduce chaos on lower population rounds

## Changelog
:cl:
balance: Several traitor items and kits now have player minimums.
/:cl:

### CODE REVIEW

**Comment by lyricalpaws** [comment]
This is a very good change

**Comment by hugmeorelse** [comment]
Try to keep things at 50 or under. A lot of players don't ready up at roundstart.

**Comment by ZephyrTFA** [comment]
You committed to Master. This is an injustice

**Comment by lyricalpaws** [comment]
> 
> 
> Try to keep things at 50 or under. A lot of players don't ready up at roundstart.

Well they'll just have to ready up if they want their gamer gear /shrug
Seen way too many cqc and johny roboshit players recently and its honestly about time that they were locked to higher pops

**Comment by Swiftfeather** [comment]
> Try to keep things at 50 or under. A lot of players don't ready up at roundstart.

@hugmeorelse done

**Comment by Swiftfeather** [comment]
I guess I better put this on a branch lol

**Comment by SpaceVampire** [comment]
I do think this might just be a symptom of a larger problem, that being that the contents of the kits are inherently unbalanced, and it might be worth reexamining a couple of the editions.

**Comment by hugmeorelse** [comment]
> I do think this might just be a symptom of a larger problem, that being that the contents of the kits are inherently unbalanced, and it might be worth reexamining a couple of the editions.

You're welcome to investigate!

**Comment by Swiftfeather** [comment]
Okay I'm going to put this off of master now, lol

**Pull request closed without merging**
