### PR TITLE
[MODULAR] Horror Form Nerf :tm:

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request
The Changeling Horror Form can no longer ventcrawl.
The Changeling Horror Form is now a one way trip, there's no going back to normal human after it's done.
The Changeling Horror Form has a normal click delay, and now no longer attacks faster than normal.

## How This Contributes To The Skyrat Roleplay Experience

The Changeling Horror Form, when used by a person who understands what a chokepoint is and the value of ventcrawling, is one of the most powerful things in the game, and often requires multiple corpse rushes by Security to actually deal with provided the pilot of the Horror Form is marginally competent and doesn't just stand around in the open actively eating projectiles to the face until it dies.

These changes should tune down the effectiveness of the Horror Form while preventing it from being completely unusable, while hammering in that it is the final stage of a changeling.

## Changelog

:cl:
balance: The Changeling Horror Form can no longer ventcrawl.
balance: The Changeling Horror Form is now a one way trip, there's no going back to normal human after it's done.
balance: The Changeling Horror Form has a normal click delay, and now no longer attacks faster than normal.
/:cl:

### CODE REVIEW

**Comment by MassacreDemigirl** [comment]
Wont it become extremely weak losing its mobility and attack output?

**Comment by Iamgoofball** [comment]
You've still got 750 HP and 40 damage punches and passive health regen, if you can't make that work then I'm not sure what to tell you

**Comment by SpaceVampire** [comment]
Removing vent crawling is based, as I have agreed with the handful of PRs that tried to do it in the past before being closed for some reason. But I am not sure if I agree with removing the ability to shift back out of the form, along with making the direct combat part of it weaker. You should also change the description of the ability to make it very clear that it how it works, so people don't pick/transform without knowing it is a way one street. If you /really/ want to go with that.

**Comment by Iamgoofball** [comment]
Really? I'm just gonna reopen this.

**Pull request closed without merging**
