### PR TITLE
Stories: A storytelling system to bring more life, drama, and soap opera plots into the station: TAKE TWO

### PR DESCRIPTION
**Pull request by Iamgoofball**
dreamseeker_HGwaJjNrm5
dreamseeker_YhEiMngdFw
dreamseeker_8qWad8ewUC

:cl: Zonespace and Iamgoofball, passport sprites by Flavrius, stories written by Oscar Gilmour
add: Adds Stories to the game, a new system designed to enhance the roleplaying experience and breathe life, drama, and soap opera plots into the station!
/:cl:

# Stories to implement:
## Season 1
- [X] Ominous Past 
- [X] Zoldorf's Apprentice
- [X] Auteurs In Space
- [x] Sample Smuggler
- [x] The Quest for The Perfect Brew
- [x] Alternative Medicine
- [x] Regulation Station
- [x] Visions
- [x] Guardian Angel
- [ ] The Buttler Did It (Skyrat is not ready for Buttbots, skipping this one for now)
- [x] Guardnapped
- [x] Worldjumper
- [ ] The Show Must Go On
- [ ] No More Strings
- [ ] Peace Talks
- [ ] Galactica News
- [ ] Memory Purged
- [ ] Goodbye, Space Station 13
- [ ] The Schemes of The Necromancer
- [ ] Lux Leather versus The Justices

## Season 2
- [ ] Head Assistant
- [ ] Triangular Profits
- [ ] Special Delivery
- [ ] Codewords
- [ ] Tell me lies, tell me Syndicate lies
- [ ] Senate Business
- [ ] Peaceful Protest
- [ ] Technophobe
- [ ] Gambler's Gambling Gambit
- [ ] Loose Cannon
- [ ] Organ Dealer
- [ ] BOMBS!
- [ ] Poker Night
- [ ] People Against Oxygen
- [ ] Golden Chef
- [ ] Boardline Impossible
- [ ] Salvation
- [ ] Error 99 (need to find some adjustments to this, maybe cryogenics? we don't got cloners on /tg/code)
- [ ] Of Many Faces
- [ ] Good Workers Follow Orders

### CODE REVIEW

**Comment by Iamgoofball** [comment]
@Stalkeros2 can you resubmit your NRI stories PR and rebase it to the current branch?

**Comment by Stalkeros2** [comment]
> @Stalkeros2 can you resubmit your NRI stories PR and rebase it to the current branch?

Sure.

**Comment by Iamgoofball** [comment]
fuck stalebot

**Comment by Iamgoofball** [comment]
still working with the writer on the 2nd batch of stories

**Comment by Iamgoofball** [comment]
2nd batch of stories done, going to continue integration

if any volunteers are willing to help me get these into code that'd be super helpful, i am 1 person and there's like 40 stories that need transferred from docs into the game

**Comment by Zonespace27** [comment]
Being done upstream for now

**Pull request closed without merging**
