### PR TITLE
[Semi-Modular] The return of SpaceBox.

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Part one of my mapping madness to try and untether map rotation from what /tg/ does, and ultimately help slow down upstream PRs so less breaks live in-game.
For those who are sad about this concept because they want Icemoon mechanics still - fret not. Towerstation is working towards that, And I hope to make a suitable, skyrat-only icemoon map if that falls apart.
Adds a new station - let me reiterate, **NEW** map to rotation. This doesn't replace default /tg/ Icebox, though that is very much the eventual goal. One z-level, heavily based on the beestation incarnation in areas that previously were multi-z. Out of laziness, mostly.
image

## Why It's Good For The Game
We're kinda reliant on updating so mirror PRs don't cascade into infinity. Having our own maps helps alleviate the workload so we can have our cake and eat it too - /tg/ can update their maps however they want, but we don't have to pull down their changes. We can make our own in comfort.

## Changelog
:cl:
add: Boxstation has been thrown up into space.
/:cl:

### CODE REVIEW

**Comment by heretomakecomments** [comment]
More content is usually better! It'd be nice to have both in rotation.

**Comment by KathrinBailey** [comment]
Just with a quick glance:
image
Missing piping for the prison distro isolation point.
image
Some obvious issues with this bit.
image
The old old citadel maint bar got put back here and should also be back here. Also that stuff is floating in space with no lattices to hold it.
image
Thermomachines not set up.
image
Thermomachines not set up.

**Comment by unit0016** [comment]
> Just with a quick glance:
> image
> Missing piping for the prison distro isolation point.
> image
> Some obvious issues with this bit.
> image
> The old old citadel maint bar got put back here and should also be back here. Also that stuff is floating in space with no lattices to hold it.
> image
> Thermomachines not set up.
> image
> Thermomachines not set up.

This is a direct edit of the current icebox build, so that's on whoever updated for smart pipes and freezers, not me.
Updating to feex.

**Comment by unit0016** [comment]
There. All of those fixed, fuck if I know how I missed the gravity generator being missing. Even the maint bar, something that was removed with the map resets, is back.

**Comment by hugmeorelse** [comment]
@unit0016 Be prepared to maintain this. We already have our hands full maintaining our current rotation of maps. If this is not maintained by you or anyone else, it will be removed from rotation if it deprecates significantly.

Also, for anyone else interested in making a map, please note that we do not have that many maintainers. Before embarking on a sizeable project, please contact our maintainers. 

Thank you.

**Comment by Gandalf2k15** [comment]
TM candidate authorised

**Comment by GoldenAlpharex** [comment]
Tell me, uh... Why's Xenobiology so small? There's even a massive space gap between maintenance and it, and having two extra pens really makes a big diference.

**Comment by unit0016** [comment]
> Tell me, uh... Why's Xenobiology so small? There's even a massive space gap between maintenance and it, and having two extra pens really makes a big diference.

I filled in areas that were previously multi-z based on the beestation version of boxstation until later - or old /tg/ in the case of the gravity generator.
Things'll be changed around, for now this is just the start, yeah?

**Comment by Gandalf2k15** [comment]
I'm happy to full merge this. @unit0016 Please do try to keep it upto date. We can fix stuff down the line if we have to.

**Pull request merged**
