### PR TITLE
Fun vendors + Shockcollar

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Ports back our oldbase vendors and shock collars. They're the fun kind. 

Shock collars work exactly as they did before.

Also reworks how the aphro module was listed.

## Changelog
:cl:
add: Kinkmate vendors are back!
add: Shock collars.
/:cl:

### CODE REVIEW

**Comment by KathrinBailey** [comment]
where's the men at sea keg?

**Comment by Gandalf2k15** [comment]
> where's the men at sea keg?

Check the reproductive PR!

**Comment by Swiftfeather** [comment]
Eyyyyy

**Comment by SpaceVampire** [comment]
While you are touching aphro stuff, can you make the perf for it go in a sane place?
Its in game-settings, instead of OOC stuff, for some unknown reason.

**Pull request merged**
