### PR TITLE
[MIRROR] [ready] unit tests all worn icons [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/72370
--------------------
Fixes #71692

:cl: ShizCalev, GoldenAlpharex for the Skyrat fixes
code: Added a unit test for ALL worn icons.
fix: Fixed a bunch of broken worn icons!
fix: Fixes a whole bunch more broken worn icons on Skyrat's items!
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
~~hahahaha....
fuck~~

Actually, looked into it, well over half of the missing worn icons are from sex2.
This is a cruel fucking joke.
I recommend we simply set their worn states to null.

**Comment by ShizCalev** [comment]
> Actually, looked into it, well over half of the missing worn icons are from sex2. This is a cruel fucking joke. I recommend we simply set their worn states to null.

worn_icon_state being null will try to find the icon_state instead due to the way the human icon system works. 

make a blank sprite in the relevant dmi files called "blank" or "nothing" or w/e you wanna call it, and set the worn_icon_state var for items that are intentionally invisible to that state, that way it's explicit that it shouldn't be visible for folks looking through code later on. :>

**Comment by GoldenAlpharex** [comment]
I'm impressed, actually. This is nowhere nearly as many broken icons as there was for the regular icons unit test, nice!

**Review by GoldenAlpharex — APPROVED** [review]
Ready, at long last.

**Pull request merged**
