### PR TITLE
[MIRROR] Critically fixes missing tram rail [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/71619
--------------------
## About The Pull Request

Adds a missing tram rail under one of the fancy new holobarriers that was missing

## Why It's Good For The Game

I CANT GRIND IT BRO

## Changelog

:cl:
fix: Fixes a missing tram rail along the tram line
/:cl:

### CODE REVIEW

**Review by Jolly-66 — APPROVED** [review]
This is probably going to conflict again but it should be fine.

**Review by tf-4 — APPROVED** [review]
lets merge before it conflicts then

**Comment by tf-4** [comment]
oh wait this needs another pr first

**Comment by Paxilmaniac** [comment]
The consequences of my actions

**Comment by Paxilmaniac** [comment]
What da hell happened read why compile maps failed

**Comment by tf-4** [comment]
Because this needs another pr first

**Comment by tf-4** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/17811

**Review by Paxilmaniac — APPROVED** [review]

**Pull request merged**
