### PR TITLE
Adds polychromic gear to ClothesMates

### PR DESCRIPTION
**Pull request by CameronWoof**
## About The Pull Request

Adds every currently available piece of polychromic clothing to ClothesMates.

## Why It's Good For The Game

This stuff is currently all loadout-specific, meaning there's no way to get them on-station. Now they are available in ample supply.

## Changelog
:cl:
add: ClothesMates now stock polychromic clothes, which were previously only available as loadout items.
/:cl:

### CODE REVIEW

**Comment by Sethnov** [comment]
isnt that a donator thing though?

**Comment by Useroth** [comment]
Some of that polychromic gear is indeed donator stuff.
Also, consider adding new stuff to a list by overriding the vending machine's New() and doing a `|=` or `+=`

**Comment by CameronWoof** [comment]
None of the polychromic gear added to the vendor in this PR is donator-specific. All of it is currently available in the loadout.

**Comment by Gandalf2k15** [comment]
Yeah verified. This is fine by me.

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
