### PR TITLE
[MODULAR] Removes the 13 telecrystals contractors start with

### PR DESCRIPTION
**Pull request by dawsonkeyes**
## About The Pull Request

This PR does exactly what it says on the tin. Technically, it deletes the 13tc subtype and resets contractors back to the 0tc version of the implant, but that's all backend - what **YOU**, dear reader, are reading this pr body for, is plain and clear. It does everything it says it does. One telecrystal? Nah. Three? Hell no. Twelve? Not even close. Zero! They get none. I don't know who thought giving them some was a great idea. Those angels are gone, holmes. Away. Dusted. Why?

## How This Contributes To The Skyrat Roleplay Experience

The contractor OPFOR kit and /tg/ balanced - yes, /tg/ balanced - traitor kit do not offer a 13tc discount. This is a full set of gear that would cost a traitor 20tc to get half of, and yet, you START with thirteen telecrystals. Thirteen! That's enough for a .357 magnum revolver. That's enough for sleeping carp. That's enough for enough plastic explosives to make an immovable rod look like a drunk driver.

Removing the 13tc that random-roll contractors start with evens the playing field and prevents them from getting an immensely powerful head start on their equipment with zero provided effort. Contractors have all they need at the start, from the second most powerful stun weapon in the game (abductors got that thang) to a modsuit with frankly _absurd_ protection and speed values (not counting that you start with armor plating modules!) and yet right now they have 13 extra traitor freebie points to buy even more equipment. They even start with a box of random traitor stuff already! Not included in the OPFOR/tot kits! What's not to adore already?

I'm absolutely rambling because it's 4 in the morning here, but contractors already **HAVE** some of the most powerful telecrystal gains in the game, far outpacing even lategame progtots. What might those be, you ask?

**CONTRACTS**

13tc. You want it? It's yours my friend. Just do what you clicked "yes i want to be a contractor" to do! Get those contracts! No more sleeping carp out the front gate!

## Proof of Testing

<details>

<summary>peep the folda</summary>
  
This is a really simple line change, but if a maintainer demands it or CI wrings me out like a wet towel, I'll get the testing tools on my new laptop

</details>

## Changelog

:cl:
balance: random roll contractors now start with zero telecrystals instead of thirteen
/:cl:

### CODE REVIEW

**Comment by dawsonkeyes** [comment]
made while listening to [the 20th anniversary version of mechanized memories](https://www.youtube.com/watch?v=lBmPvWyQ-HY) because i fucking love armored core

**Comment by burgerenergy** [comment]
yea but them having some points to personalize from their already limited selection is more fun

precious few contractors are ever going to make a hit before running neckdeep into security

**Comment by HoodMilk** [comment]
Hopefully this encourages contractors to actually do contracting instead of going "I'm gonna try to fight all of security with my funny baton"

**Comment by desertmote** [comment]
> Hopefully this encourages contractors to actually do contracting instead of going "I'm gonna try to fight all of security with my funny baton"

This is a really important point. Its too common for contractors to enter the round, murder 10 officers, die a glorious death and redtext the 'capture ONE guy' objective.
But losing the opportunity to buy a chameleon kit for the little 2 TC price also isn't cool. Chameleon contractor is already not getting any play, killing it completely would be sad.

**Comment by TheOneAndOnlyCreeperJoe** [comment]
If anything it'll just make contractors even more boring and annoying to go up against? With customization on the table you'll at least have a chance they'll try something new - as opposed to this just homogenizing them into funny baton kidnap man unga bunga.

**Comment by chemistrymain2** [comment]
> If anything it'll just make contractors even more boring and annoying to go up against? With customization on the table you'll at least have a chance they'll try something new - as opposed to this just homogenizing them into funny baton kidnap man unga bunga.

what this guy said

quite honestly @dawsonkeyes you are better off removing sleeping carp from their purchase menu or making sleeping carp not work if stimulants are in your system vs this option

there's a fine line between' they're a bit too strong' and 'this is unfun and rote' and we don't want to force contractors into the role of nightmare where there's literally only one thing they can do and only one thing no matter what

contractors have a hard enough time being interesting As Is

**Comment by Cyprex** [comment]
This overlooks many, many things, most importantly that contractors are blatantly obvious as syndies- i. e. you have a target painted on you at all times, and 0 ranged weapons or other good defenses to start with. (As an aside sec gets tons of freebies here compared to tg, along with a lot less antags). Yes, the baton is strong but it's also tied to your hardsuit which immediately outs you. By taking away these 13 TC you further pigeonhole them into combat with security, as any semblance of stealth(chameleon kit) vanishes. Therefore I really don't think this is a good idea.

**Comment by HoodMilk** [comment]
For the people saying this prevents stealth, you spawn with a chameleon module on your suit and an agent ID, literally just go to the laundry room and throw on some random clothes and set your ID to an assistant and you are good to go.

**Comment by StrangeWeirdKitten** [comment]
If contractors are too powerful, why do 2-3 spawn when the event rolls? Especially when you can combat sleeping carp with a teleshield and stun baton then disabler combo.

**Comment by RatFromTheJungle** [comment]
> If contractors are too powerful, why do 2-3 spawn when the event rolls? Especially when you can combat sleeping carp with a teleshield and stun baton then disabler combo.

because it was made by someone who was intending to play it, heavily, you can probably fill out the rest

**Comment by Lafrien** [comment]
> spawn with a chameleon module on your suit and an agent ID, literally just go to the laundry room

Now imagine that nukie-looking assistant with "normal backpack", tactical webbing, uniform and syndie headset running half the station from departures or arrivals to the Dorms without anyone noticing that suspicious ass.

I suppose giving Contractor a Chameo kit is more rational option than outright confiscating all of TC with no balancing sense.

**Comment by destrucktoid** [comment]
This could also be achieved by starting contractors off with 12 TC instead of 13. Not that i really think contractors getting sleeping carp off the bat is an actual issue, sleeping carp is easily countered if you know what you are doing after all. Regardless, setting them to 0 because you don't like contractors having sleeping carp is massive overkill.

**Comment by radarseas** [comment]
well, one issue. giving contractors _absolutely nothing to start with_ is going to cause them to only be able to rely on the _funny baton._ and it takes out interesting options like  bribing your first target, buying stuff off cargo, using RP and bribery to get what you'd like to compensate _for probably being 2 hours behind crew when you actually spawn in._ or buying syndeye to track your targets over cameras via your tablet so you can see who's actually worth chasing down and who's in a group of about six people.

if a contractor buys a revolver, they're probably ditching a lot of other useful utility gear like say, modsuit thermals, a stimpack, freedom implants for bolas at the worst timing where resisting out isn't feasable, combat medical supplies, etc. _it also makes gimmicy stuff like wasting some TC on posters, spraypaint or cham kit disguises absolutely unfeasable for midrounds where they most need it. especally **known midround characters like say, duelist** that nearly everyone knows_.

as for scarp, well that's an issue with contractors using the same uplink pool as traitors, its also not always a straight-upgrade since contractors often face high-numbers and need to drop their ranged immunity for a split second to baton. you can also hardstun them if you make them catch a flashbang and it goes off. ebolas can't be caught which pairs perfectly with batons. _as for stimpacks starting off, that's a random startoff loadout pool issue._ (and if they already got a contract and stimpacks from it (5TC per pen ain't cheap), well deserved, don't let em kidnap if _you don't want a bigger threat_.

maybe push it down to 12TC-10TC. if you really want to ditch them getting ebows, revolvers and scarp right off the bat? at the very least contractors need their utility stuff facing a station that's usually _1-2 hours ahead of roundstart progress_ where most security equipment is mindshield pinned and **absolutely useless to pick up** unless you plan on destroying it, where night vision is only a protolathe away and security modsuits already have space-advantage with ion thrusters, much less whatever else security slowly obtained over the round. much less the fact half of the crew can easily just obtain firearms of their own violition _whereas you need to cough up those telecrystals for ammo and the gun itself if you want one while loud or without anyone questioning why an **Unassigned** account crate is filled with various equipment and probably a gun or two plus ammo_, or uhh, actually waiting on it and getting out without being questioned the entire time because someone shift+clicked on you with sechuds/medhuds and realised you were actually a stowaway.

Lets also not forget AIs can just bolt in a contractor which shuts them down instantly. there's not much having an uplink can change with that, but at least they can break out of perma with it, or have a fighting chance to go out with a show, also not every contractor is an experienced player, some genuinely do flop with the amount of telecrystals they already get, I feel the current amount is a nice buffer to fall back on.

If anything, scarp's issue lies with antidrop 2 hit baton, _I'd prefer a recall with a 5-8 minute timer like what ninjas have for their katanas over an inbuilt suit antidrop_ while we already have stimpacks which TG has made already solve the dropping equipment issue but that's out of scope for this PR.


_also, these are once again, **midround implantees**_ with 13TC not roundstart/OPFOR kit balanced contractors that have them.

**Comment by radarseas** [comment]
> For the people saying this prevents stealth, you spawn with a chameleon module on your suit and an agent ID, literally just go to the laundry room and throw on some random clothes and set your ID to an assistant and you are good to go.

issue is, known contractor characters, and also its not always feasable to walk over in your syndicate-grade insulated turtleneck and insulated boots.. much less the fact you're wearing a blatent headset, to just blend in, its quite likely someone might call you out over radio heading over, compromising you to begin with. and if that's already armed security well, good luck deploying your _modsuit mid-fighting them to not get shot to death_ much less if they're already patrolling in pairs.

also shift+click with sechuds instantly blows your cover regardless _(you are not crew, you have no records, you're a nobody)_ so you even get spotted beforehand stealth is practically already out of the window as security will know an infiltrator is amongst the crew's ranks, if security is somehow cool about it and makes you a record, that's still gonna cost you that sweet, sweet contract time for a disposable cover.

oh also remember, you start broke, so unless you somehow quietly rob someone and not get called out, you're not buying clothing from the vendors that fits skyrat's crew look. its just gonna be jumpsuits and generic TG-assistant look-alike that slightly sticks out.

**Comment by dawsonkeyes** [comment]
I remind you all that contractors already start with a randomly rolled box of uplink gear to get them started

**Review by lessthnthree — APPROVED** [review]

**Comment by Virescent** [comment]
Salt PR at its finest.

**Comment by dawsonkeyes** [comment]
> Salt PR at its finest.

brotha i was the purveyor of salt. the salter of the earth. i gamed HARD as a contractor. this isnt a salt pr its a balance pr

**Pull request merged**
