### PR TITLE
Removes the job locks from all armbands except the sec armbands, and reflavors all armbands to not directly state this person is a member of x department

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request

Title.

## How This Contributes To The Skyrat Roleplay Experience

Armbands can be used to declare certain skillsets or associations with a department. Example, an EMT might wear a medbay armband, signifying their character knows how to treat people, while a scientist could wear a purple armband, signifying scientist proficiency.

There's no real reason to lock these things, aside from the sec armbands, which can actually be given out to people to say "hey buddy wanna be sec"? Still, though, if you remove the name of the department from these armbands, you remove the ability for people to point to the armband and say "it says sec, so let me arrest this guy". 

All in all, just more customization. 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

</details>

## Changelog

:cl:
qol: All armbands except for the sec ones can now be picked by anyone
tweak: All armbands except the sec ones have been reflavored to not directly mention their departments
add: A new blue armband, signifying sec proficiency but NOT declaring you as a member of sec
/:cl:

### CODE REVIEW

**Comment by nikothedude** [comment]
drafted pending testing

**Comment by theselfish** [comment]
Wouldn't it be far simpler to have one, maybe two GAGs armbands so people can recolour them to their whims?

**Comment by nikothedude** [comment]
> Wouldn't it be far simpler to have one, maybe two GAGs armbands so people can recolour them to their whims?

yeah but i dont know how to sprite nor greyscale

**Comment by Plum-but-gayer** [comment]
ohhhhh this is such a good fucking idea this is so flavorful. now atta can correctly be depicted as a seccie-technician

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
At this point, I'd rather have this be using GAGS instead, so people can make it whichever color they want, and so we can have presets using the different colors, as well as one more general that people can do whatever with.

If you need help making the sprites grayscaled, just send them to me as a PNG and I'll grayscale them for you in like two minutes, it's very easy.

**Comment by vinylspiders** [comment]
https://hackmd.io/@tgstation/GAGS-Walkthrough Also here is the guide so you can follow through with the code portion of it

**Comment by burgerenergy** [comment]
I disagree, actually. Having armbands be labeled towards certain departments is better then someone trying to infer the meaning of, like, two colored pixels on a character sprite.

Now, whether that sort of... eh... cross departmental implied skill set is a good thing is another matter.

**Comment by vinylspiders** [comment]
> I disagree, actually. Having armbands be labeled towards certain departments is better then someone trying to infer the meaning of, like, two colored pixels on a character sprite.
> 
> Now, whether that sort of... eh... cross departmental implied skill set is a good thing is another matter.

That doesn't mean there can't still be labeled ones. You can have GAGS items that start off a specific color but are still using the recolorable sprite.

**Comment by nikothedude** [comment]
i am moving to galaxia and am focusing my efforts there

**Pull request closed without merging**
