### PR TITLE
Converts polychromic cloaks to GAGS

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Removes polychromism from the cloaks and makes them GAGS.
Removes the runescape cloaks because holy shit they look fucking awful.
Tiny adjustment to mush cap pathing to discourage people from just dumping .jsons in the parent folder, please don't do that

They're slightly more muted than before, but I think that's fine? It can be adjusted.

And yes, I chose just about the most boring colour scheme to show them off. I dunno why I did that.

cloaks

## How This Contributes To The Skyrat Roleplay Experience

Polychromism gone soon:tm:

## Changelog
:cl:
code: Cloaks, boatcloaks, veils, and shrouds are now GAGS instead of polychromatic.
del: The runescape cloaks have been removed.
/:cl:

### CODE REVIEW

**Comment by AtoriBirb** [comment]
Hnhh now I'll actually have to turn the hood I was making for the four cloaks into a gags thing too

**Comment by RatFromTheJungle** [comment]
ok but whats this do in american?

**Comment by AtoriBirb** [comment]
> ok but whats this do in american?

Cleanin' out yalls code of the weeds to make it so yas caddle farm ain't so cluttered, and the start of getting rid of outdated tools like polychromatic, hyuck

**Comment by Gandalf2k15** [comment]
oh you sexy bugger kiss me on my hot lips

**Review by Gandalf2k15 — APPROVED** [review]

**Review by GoldenAlpharex — APPROVED** [review]
Looks good!

**Pull request merged**
