### PR TITLE
[MODULAR] Ports Double beds

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

It adds Queen-Sized beds, because why not. This came from Sojourn, but I don't think it originally came from there, so I think this is a port of a port, however that works.

beds

leadditions

## Why It's Good For The Game

(good for ERP)

Uhh, they're better than normal beds? and we no longer have to do the DS-2 strat, of putting two beds together on the same tile, because that always really bothered me.

## Changelog
:cl:
add: Added double beds
imageadd: added double bedsheets
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
next you're gonna be porting the pillory from civ 13 for public punishment and the jesus crosses from...civ 13 for cruxifixtion


public execution

**Comment by axietheaxolotl** [comment]
> 
> 
> next you're gonna be porting the pillory from civ 13 for public punishment and the jesus crosses from...civ 13 for cruxifixtion
> 
> public execution

🤔

**Comment by tf-4** [comment]
Put in-game screenshots in the PR body

**Comment by axietheaxolotl** [comment]
> 
> 
> Put in-game screenshots in the PR body

making me do things smh

**Comment by axietheaxolotl** [comment]
### le additions
leadditions

**Comment by Arctaisia** [comment]
Wooo, nice, I was about to ask where the fuck my NT and CC bedsheets were,,,, :heart:

Though I personally have no idea where the double beds come from. I know it's definitely some old baycode thing, because Vorecode also has them, but I forgot the specific codebase Eris is based on, if it's Polaris then they may have come from there, as that's also what Vorecode is based on.

I once kissed a friend on the NT double bed,,,

**Comment by FlamingLily** [comment]
Are there syndie bedsheets?

**Comment by axietheaxolotl** [comment]
> 
> 
> Are there syndie bedsheets?

no

station gang stay winning

**Pull request merged**
