### PR TITLE
[MIRROR] FOV is Dead (Long Live FOV) [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/80062
--------------------
## About The Pull Request

FOV as it is currently implemented is incompatible* with wallening.
I'm doin wallening, so we gotta redo things here.

The issue is the masking of mobs. Wallening relies on sidemap (layering based off physical position), which only works on things on the same plane (because planes are basically sheets we render down onto)
So rather then masking mobs, let's reuse the masking idea from old fov, and use it to cut out a bit of the game render plane, and blur/over-saturate the bit that's masked out.

My hope is this makes things visible in light, but not as much in darkness, alongside making more vivid shit more easily seen (just like real life)

Here's some videos, what follows after is the commits I care about (since I had to rip a bunch of planes to nothing, so the files changed tab might be a bit of a mess)

Oh also I had to remove the darkness pref since the darkness is doing a lot of the heavy lifting now. I'm sorry.

Edit:
NEW FOV SPRITES! Thanks dongle your aviator glasses will guide us to a better future.

https://github.com/tgstation/tgstation/assets/58055496/afa9eeb8-8b7b-4364-b0c0-7ac8070b5609

https://github.com/tgstation/tgstation/assets/58055496/0eff040c-8bf1-47e4-a4f3-dac56fb2ccc8

## Commits I Care About

[Implements something like fov, but without the planes as layers hell](https://github.com/tgstation/tgstation/commit/a604c7b1c8d74cd27af4d806d85892c1f7e35ba8)

Rather then masking out mobs standing behind us, we use a combo color matrix and blur filter to make the stuff covered by fov harder to see.

We achive this by splitting the game plane into two, masking both by fov (one normally and one inversely), and then applying effects to one of the two.

I want to make the fov fullscreens more gradient, but as an effect this is a good start

[Removes WALL_PLANE_UPPER by adding a WALL_PLANE overlay to material walls (init cost comes here)](https://github.com/tgstation/tgstation/commit/25489337392f708cb337fbf05a2329eacdfc5346)

@ Mothblocks see this. comment in commit explains further but uh, we need to draw material walls to the light mask plane so things actually can be seen on them, but we can't do that and also have them be big, so they get an overlay. Sorry, slight init time bump, about 0.5 seconds. I can kill it with wallening.

[Moves SEETHROUGH_PLANE above ABOVE_GAME_PLANE](https://github.com/tgstation/tgstation/commit/beec4c00e01d34a04fba7c2bb98a9b70d27ead82)

I don't think it actually wants to draw here
@ Time-Green I think this was you so pinging for opinion

[Resprites FOV masks to be clean (and more consistent)](https://github.com/tgstation/tgstation/pull/80062/commits/f02ad13696b3b17658af612c62848b48609d785d)
[f02ad13](https://github.com/tgstation/tgstation/pull/80062/commits/f02ad13696b3b17658af612c62848b48609d785d)

This is 100% donglesplonge's work, he's spent a week or so going back and forth with me sharpening these to a mirror shine, real chill

## Why It's Good For The Game

Walls are closing in

## Changelog
:cl: LemonInTheDark, Donglesplonge
image: Redoes fov "mask" sprites. They're clean, have a very pleasant dithering effect, and look real fuckin good! 
del: Changed FOV, it no longer hides mobs, instead it blurs the hidden area, and makes it a bit darker/oversaturated
/:cl:

### CODE REVIEW

**Comment by Elli-Skala** [comment]
I feel like TG making mask FOV solid black + skyrat making FOV a 100% thing will not be the most enjoyable experience with your screen forever 25% a black void (one if the things we International avoided doing when we were first adding FOV because it's nauseating)

**Comment by Timberpoes** [comment]
My suggestion is not merging this PR for now. See https://github.com/tgstation/tgstation/pull/80301 the revert testmerge PR that's currently on our live servers. Issues with UI and runechat.

**Comment by Ephemeralis** [comment]
The back cone is hysterically ugly. There has to be a better way than that.

**Comment by Jolly-66** [comment]
DNM per comments by Timber, a /tg/ maintainer

**Comment by vinylspiders** [comment]
Includes the hotfix https://github.com/tgstation/tgstation/pull/80307 .

**Comment by vinylspiders** [comment]
That said I think we may want to adjust the alpha and/or make it a pref. It just feels a bit too dark, the shape shouldn't be that visible.

**Comment by Gandalf2k15** [comment]
TG gave their ultimatum.

**Pull request merged**
