### PR TITLE
Updates the buttondown shirt underwear sprites I added

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

As the title says, makes the buttondown shirts you can chose as an undershirt option be more similar to modern tg buttondown shirts.

## How This Contributes To The Skyrat Roleplay Experience

They look better I think, the colors suck a bit less.

## Proof of Testing

Before and afters:

Taken from the character creator on live and from a local respectively

image

## Changelog

:cl:
image: The buttondown shirts (underwear) have been updated with a better look and more contrasted palette
/:cl:

### CODE REVIEW

**Comment by vinylspiders** [comment]
image

For me at least this one pixel is throwing me off, it makes it look more feminine as compared to the original I think?

Also it's a bit high contrasty compared to the tg sprites. Which you did say you were going for, I just think it accentuates that pixel even more probably (tg original shown below).

image

**Comment by Paxilmaniac** [comment]
> image
> 
> For me at least this one pixel is throwing me off, it makes it look more feminine as compared to the original I think?
> 
> Also it's a bit high contrasty compared to the tg sprites. Which you did say you were going for, I just think it accentuates that pixel even more probably (tg original shown below).
> 
> image

You want much higher contrast because it makes things appear way less washed out, especially when it comes to things that can be recolored.

**Comment by vinylspiders** [comment]
> You want much higher contrast because it makes things appear way less washed out, especially when it comes to things that can be recolored.

I should clarify, the contrast is not the issue I have it's that one pixel that gives the illusion of a feminine figure. I think it should be a bit more neutral

image

Like this perhaps?

**Review by vinylspiders — CHANGES_REQUESTED** [review]
It's ultimately just my opinion though in the end. I don't see anything glaringly wrong with these sprites so as long as you fix that merge conflict it has my approval

**Review by vinylspiders — APPROVED** [review]

**Pull request merged**
