### PR TITLE
removes the anomaly core from Nakamura MOD imports antigrav module

### PR DESCRIPTION
**Pull request by zeroisthebiggay**
## About The Pull Request

This is a balance change. If you know, you can buy the antigrav module from Nakamura MOD imports for an extremely cheap price, and get one of the most powerful MOD modules in the game when combined with a jetpack, and especially when combined with either the advanced jetpack from a Syndicate MOD, or more commonly from the Magnate MOD, essentially becoming free methspeed and better noslips that additionally immunize you from ground base hazards and space lube.

You can still achieve the same thing if you buy an anomaly core and process it properly, but this time you're actually paying the real expense for the anomaly core instead of buying it on supreme discount with the thing you were going to probably be putting it inside of anyways.

## How This Contributes To The Skyrat Roleplay Experience

It removes a route of powergame.

## Proof of Testing

<details>
<summary>It's a webedit man.</summary>
 
</details>

## Changelog

:cl:
balance: Nakamura MOD imports have removed the free anomaly cores from their antigravity MOD modules. Oops! Looks like you're gonna have to supply your own from now on.
/:cl:

### CODE REVIEW

**Comment by kittysmooch** [comment]
why would anyone buy this when the module can be printed for free

**Comment by Nerev4r** [comment]
there is precisely one (1) magnate modsuit in the game
and if you genuinely get cargo to give you an antigrav module for your syndicate modsuit as an antag, good for you

**Comment by zeroisthebiggay** [comment]
> there is precisely one (1) magnate modsuit in the game and if you genuinely get cargo to give you an antigrav module for your syndicate modsuit as an antag, good for you

it's still cheaper to buy an antigrav with the core loaded than to buy the raw anomaly core
this is arguably an oversight and defeats the point of making a difficult to acquire item piss easy to acquire

even without the advanced jetpack it's a better form of slip protection if you use it with either a normal jetpack or simply being a moth

**Comment by zeroisthebiggay** [comment]
> why would anyone buy this when the module can be printed for free

having it super early in the round
circumventing the requirement for you to get anomaly cores

**Comment by Elli-Skala** [comment]
The price should be drastically lowered or the option removed outright as a 3000 credit module that you also need to buy a anomaly core for and get rnd to refine isn't to worth it 

Also doesn't make sense how one of three of the anomaly modules just doesn't work

**Comment by kittysmooch** [comment]
> > why would anyone buy this when the module can be printed for free
> 
> having it super early in the round circumventing the requirement for you to get anomaly cores

getting an anomaly core and getting it processed by science is going to take as long as the research, so again, why would anyone buy the empty module when its freely printed at robotics?

**Comment by zeroisthebiggay** [comment]
> The price should be drastically lowered or the option removed outright as a 3000 credit module that you also need to buy a anomaly core for and get rnd to refine isn't to worth it

fair point. i reduced the price by a lot since it's now just an inert module

> Also doesn't make sense how one of three of the anomaly modules just doesn't work

also a fair point. however the antigrav module also has the most practicality while the other two are usually little more than gimmicks. the teleporter has a long wind up that makes it fairly impractical outside of trespassing and the kinesis module **is** a gimmick

**Comment by Nerev4r** [comment]
> Contributor

you can already get the slip protection (people don't really use slips in combat unless they hate you) from the much cheaper gravity harness, *and* it pairs with moths and the jetpack augment. i haven't been seeing many high-profile cases of people using antigravity in a combat way up here lately.

**Comment by zeroisthebiggay** [comment]
gdi

**Pull request closed without merging**
