### PR TITLE
[MIRROR][NO GBP] missed mirror 66864

### PR DESCRIPTION
**Pull request by Tastyfish**
Missed mirror for https://github.com/tgstation/tgstation/pull/66864

Anticipating 100 weird failures from our questionable modules so marking draft

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
I guess it's probably time to pull the plug on NSS Journey, it's been off-rotation and has gone unmaintained for, what, over half a year at this point?

**Comment by Tastyfish** [comment]
> I guess it's probably time to pull the plug on NSS Journey, it's been off-rotation and has gone unmaintained for, what, over half a year at this point?

I think so.

**Comment by Gandalf2k15** [comment]
TRAM STATION FAILURE FIXED IN https://github.com/tgstation/tgstation/pull/67260

**Comment by Tastyfish** [comment]
Nice

**Comment by Jolly-66** [comment]
When you run a downstream yourself and find a CI failure before anyone else

Its free GBP !

**Comment by Tastyfish** [comment]
> When you run a downstream yourself and find a CI failure before anyone else
> 
> Its free GBP !

I farmed like 6 map fix PR's out of this. heh.

**Comment by Jolly-66** [comment]
> Reply chain

Bless map CI because of this

**Pull request merged**
