### PR TITLE
REMOVE gas miners and fix tesla coils on maps

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Remove gas miners from maps and also corrects tesla coils and grounding rods to correct path on ice and delta station

## How This Contributes To The Skyrat Roleplay Experience
Possibly

## Changelog

:cl:
del: Remove gas miners from maps
fix: Tesla coils and grounding rods not spawning on icebox and delta station
/:cl:

### CODE REVIEW

**Comment by jjpark-kb** [comment]
please remove the gas miners from the maps. We currently do not desire gas miners in their current state.

**Review by jjpark-kb — CHANGES_REQUESTED** [review]
Read my above comment.

**Comment by nevimer** [comment]
Miners are essential on blueshift due it's combined area and volume.

**Comment by ghost** [comment]
irrelevant anyways

**Pull request closed without merging**
