### PR TITLE
Changes plasma thrower to an energy gun and lowers its blob damage

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Title, makes the gun behave like an energy gun rather than like an energy-ballistic hybrid kinda thing.
In practice, this just means you recharge it directly rather than having power packs that you can swap in and out. 

Also drops its damage against blobs by 1/4.

## How This Contributes To The Skyrat Roleplay Experience

This gun is *pretty good*, making a BIG dent in blobs and the likes. Unfortunately, however, the replaceable (and rechargeable) energy-magazines are a bit of a balance problem, meaning with just a couple you can have a nigh-on infinite supply of shots.
This way, it's held to the same balance standards as other energy guns - i.e. you have to back up and recharge it directly every once in a while (20 shots).

## Proof of Testing
<details>
<summary>Screenshots/Videos</summary>
  
image

</details>

## Changelog
:cl:
balance: The plasma thrower is now an energy gun, meaning it has to be recharged in a charger rather than reloaded with magazines.
/:cl:

### CODE REVIEW

**Comment by RatFromTheJungle** [comment]
it already is only 10 damage; you should really pick one-nerf or the other, both at once makes it's notably pointless against blobs with a slow reload, and 1/4th(?) the lasergun damage

**Review by Gandalf2k15 — APPROVED** [review]
HYAAAAAAAAAA BALLISTIC ENERGY GUN 😨

**Review by Gandalf2k15 — CHANGES_REQUESTED** [review]
fix CI tho

**Comment by tf-4** [comment]
CI is no longer my problem

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
