### PR TITLE
[MODULAR] Scalamov overhaul (I am literally deleting it)

### PR DESCRIPTION
**Pull request by Stalkeros2**
## About The Pull Request
Full of three man slavic away mission dev team's salt, be warned.

**Deletes** Scalamov. That's it. That's all it does. All the map, all the items, all the icons. Gone. Reduced to ashes.

Believe me, it's for the best.

But jokes and even more salt aside, it's been done in preparation for an SCP-themed away mission (of a better quality) that's meant to fill its role, so not much will be lost, huh.

## How This Contributes To The Skyrat Roleplay Experience
Reduced file size and one **horrible** map and away mission less.

## Changelog

:cl: Stalkeros, LeonY24
del: Deletes Scalamov in its entirety.
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
Small note to whoever writes "make it better" or something - we've tried.
It's just *that* bad.

**Comment by LeonY24** [comment]
legit

**Comment by Whygil** [comment]
Removing entire location without making something to replace it, amazing plan.

**Comment by Stalkeros2** [comment]
*Not like you're losing much with gateways disabled, huh.*

**Pull request merged**
