### PR TITLE
[SPRITING] Tesheari Mk II, Bird Fluff Improvements

### PR DESCRIPTION
**Pull request by CliffracerX**
## About The Pull Request

This PR restores the lost Teshari ear/feather styles that were killed in #20694, updated to the new palette and polished up to current sprite standards, as well as adding a fluff-free variant of the Harpy Alt wings so that manes are no longer mandatory.

## How This Contributes To The Skyrat Roleplay Experience

More customization is always good, and this will make Tesh players happy since they can be absurdly fluffy critters once more.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

Fixed mane ears:
image

Mane ears, fluffless variant- for flavor or for use with the Teshari Mane flufftype:
image

Tree ears, including more use of tertiary colors:
image

Thin mane ears, also including tertiary colors (why didn't they have these before??):
image

Thin mane, fluffless variant:
image

Wooly Teshari kitbash (Fluffless Mane ears, Top Mane fluff, Horns Double frills, Drake horns, and Synthliz antennae):
image

(your daily reminder that Skyrat customization, while imperfect, is robust as hell for making cool-ass kitbashes)

Top-Layer Fluffless Harpy wings:
image

Standard-Layer Fluffless Harpy wings:
image
</details>

## Changelog

:cl:
fix: Teshari Mane (Top) now changes the layer like other (Top) variants
image: updated Teshari Feathers Mane, Tree, and Thin mane & readded them
image: fluffless variants of Harpy Alt Wings for reduced sprite clippage & jank
/:cl:

### CODE REVIEW

**Comment by zydras** [comment]
Hey, just a comment here but something that's going to annoy me (and many others) is that the Kitbash earstyle is actually not centered to the teshari's center, which, is definitely making it feel wrong. 
Think it's possible to fix that by offsetting a side by one or two pixels? Both the forward-facing and backward-facing sprites have that issue. 
Really good addition otherwise!!

**Comment by TeshariEnjoer** [comment]
I'll place it here.

https://github.com/Fluffy-Frontier/FluffySTG/pull/83

**Comment by CliffracerX** [comment]
The kitbash earstyle is made by combining multiple bodyparts; it’s not actually a bespoke earstyle in and of itself, it’s more a tech demo/reminder that Skyrat customization is hella cool!  It’s just the mane ears underneath all the other parts; and it wouldn’t work with the Upright rework that was supposed to be their replacement, which caused no small amount of consternation for my friends who made that kitbash combo to begin with.

**Review by GoldenAlpharex — APPROVED** [review]
Looks good to me.

**Comment by ghost** [comment]
изображение изображение

@CliffracerX  , can someone fix this? Extra pixels at background ears make them unusable.

**Comment by CliffracerX** [comment]
> изображение изображение
> 
> @CliffracerX , can someone fix this? Extra pixels at background ears make them unusable.

I'll see about fixing this later today in a new PR, alongside filling optional inner-ear colors for the types that don't currently support it.

EDIT: I went and checked on my downstream that's like half a year out of date.

image

This was also the behaviour before I ever touched tesh ears.  Fixing it's going to probably require a complete layer reorganization for all ear types, which is going to be *annoying* but not the end of the world.

image

ADJ displays underneath hats and similar, so updating all tesh ears to have their back ears and similar areas on the ADJ layer would fix it, it's just gonna be annoying.

**Pull request merged**
