### PR TITLE
removes two range bone spears on the right code base

### PR DESCRIPTION
**Pull request by Elli-Skala**
Reverts Skyrat-SS13/Skyrat-tg#3383

## About The Pull Request
removes the bone spears from having two range 

## How This Contributes To The Skyrat Roleplay Experience
ash walkers being over powered and easily killing miners with over powered weapons isnt high role play, it was just power creep

## Changelog

:cl:
balance: nerfs ash walker bone spears to one range
/:cl:

### CODE REVIEW

**Comment by PCPort** [comment]
REPOSTING! As a lavaland main I endorse this message, having such a potent melee weapon with two range effectively renders the other ashwalker melee weapons obsolete, which is pretty lame. Variety is the spice of life!

**Comment by Xymec** [comment]
Honestly, I like this PR, adds balance to the spear so Ashwalkers can't just be all 'I have strong spear with 2 tiles range, now die.'

**Comment by GoldenAlpharex** [comment]
As much as this sounds like an "ided" PR, I think it's also kinda needed.

**Review by GoldenAlpharex — APPROVED** [review]
I'm fine with this.

**Pull request merged**
