### PR TITLE
New minefield ruin for space

### PR DESCRIPTION
**Pull request by Aphast**
## About The Pull Request
Adds the clownplanet ruin equivalent of lavaland to space, but deadlier! 

## How This Contributes To The Skyrat Roleplay Experience
more ruins, and one that is truly dangerous if you dont go about it properly, one wrong move and whoopsie! however since ss13 cant make guaranteed maze calculations it will be the same every time, the ruin itself does contain a solution to it aswell.

[image](https://user-images.githubusercontent.com/75702012/139617035-a08d94bf-f601-4146-a574-5fd3b8a9aed8.png)

## Changelog

:cl:
add: minefield.dmm
tweak: config to spawn minefield
/:cl:

### CODE REVIEW

**Comment by Aphast** [comment]
i have been lied to, draft does not fix the wip label

**Comment by tf-4** [comment]
Put an image in the PR. It's in the mapdiffbot anyway it just stops me being able to look on my phone

**Comment by Aphast** [comment]
kinda ruins its thing but aight, there

**Comment by GoldenAlpharex** [comment]
Are those mines anchored? If one goes off, do they all go off? I'm not sure how super entertaining this is, it just means that you gotta watch your steps and then bam, easy loot.

**Comment by tf-4** [comment]
> 
> 
> Are those mines anchored? If one goes off, do they all go off? I'm not sure how super entertaining this is, it just means that you gotta watch your steps and then bam, easy loot.

Welcome to space ruins I guess? Pretty par for the course

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Needs to look way prettier and needs no invulnerable walls. That just makes the entire ruin a goldmine for anyone looking to make an antag base, since there's one entry point.
If you're worried about people "skipping" the puzzle, well, it's less effort to look up the solution than it is to deconstruct two-layer thick rewalls.

**Comment by Aphast** [comment]
hrm, well im unable to do look prettier soo aint much to do here then

**Pull request closed without merging**
