### PR TITLE
Hyena hair, robo wings, and spooder wings addition - Ports from hyper and chomp

### PR DESCRIPTION
**Pull request by Echopsychotic**
## About The Pull Request
Adds: 
hyena mohawk hair (hyper)
roboto wings (chomp)
spider legs (chomp)

images:
dragon wings
hyenahawk
spiderlegs

## How This Contributes To The Skyrat Roleplay Experience
it adds new things! new wings for synths and machine folk are weird looking but nice all the same! And spider legs for those that wanna be spiders without a drider.

## Changelog
:cl:
add: Hyena hair
add: drago_wings (two colors)
add: Spider legs
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
oh shittttt

yall gonna be porting the...eye stock wing things as well?

**Comment by Echopsychotic** [comment]
> oh shittttt
> 
> yall gonna be porting the...eye stock wing things as well?

They didnt seem like they would fit, but might add eye stalks at a later date.

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
This looks fine, however, from looking at the code, there seems to be more than just those three, could you include pictures of those?

**Comment by Echopsychotic** [comment]
> This looks fine, however, from looking at the code, there seems to be more than just those three, could you include pictures of those?

the extra items were added in this RP I have no idea why they were added in this pr as well.

PR:https://github.com/Skyrat-SS13/Skyrat-tg/pull/9023

**Comment by Echopsychotic** [comment]
@GoldenAlpharex changes have been made took longer than I would have liked but weh

**Comment by GoldenAlpharex** [comment]
@Echopsychotic have you discussed with Seris and made sure that it was working now that we merged emissives?

**Comment by Echopsychotic** [comment]
I will give them a ping.

**Comment by Echopsychotic** [comment]
sprites have been altered to fit the new emissives merge with the help of Seris. @GoldenAlpharex

**Comment by GoldenAlpharex** [comment]
> sprites have been altered to fit the new emissives merge with the help of Seris. @GoldenAlpharex

Awesome, I suppose that you have tested them in-game too, just to be sure?

**Review by GoldenAlpharex — APPROVED** [review]
This appears quite fine to me.

**Pull request merged**
