### PR TITLE
MOVES ALL FUCKING CLOTHING ICONS TO MASTER FILES AND BANS THE USE OF CLOTHING MODULE ICON FILES - [DEVCON 1]

### PR DESCRIPTION
**Pull request by Gandalf2k15**
# FURTHER USE OF CLOTHING MODULE ICON FILES IS NOW PROHIBITED. 

# PUT YOUR ICONS INTO THE MASTER_FILES CLOTHING ICON FOLDER.

# I HAVE SPOKEN.

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
@Gandalf2k15 is it normal that it changes stuff related to Dynamic?

**Comment by Gandalf2k15** [comment]
> @Gandalf2k15 is it normal that it changes stuff related to Dynamic?

Yes, this is planned.

**Comment by Sigmar-alkahest** [comment]
pardon the question but, why?

**Review by Funce — APPROVED** [review]
I'll be doing a follow up on this PR to get what's missed

**Comment by Weblure** [comment]
> > @Gandalf2k15 is it normal that it changes stuff related to Dynamic?
> 
> Yes, this is planned.


Can we not sneak in changes under the guise of something completely unrelated?

**Comment by GoldenAlpharex** [comment]
> > > @Gandalf2k15 is it normal that it changes stuff related to Dynamic?
> > 
> > 
> > Yes, this is planned.
> 
> Can we not sneak in changes under the guise of something completely unrelated?

For reference, this was just updating the repo with what we have on the server.

**Comment by Weblure** [comment]
> > > > @Gandalf2k15 is it normal that it changes stuff related to Dynamic?
> > > 
> > > 
> > > Yes, this is planned.
> > 
> > 
> > Can we not sneak in changes under the guise of something completely unrelated?
> 
> For reference, this was just updating the repo with what we have on the server.

The lack of any explanation led to me jumping to the wrong conclusions, my bad.

**Comment by ORCACommander** [comment]
you broke gags
https://github.com/Skyrat-SS13/Skyrat-tg/issues/6037

working on a patch

**Pull request merged**
