### PR TITLE
[Modular] Player Reactivity Changes, Volume One

### PR DESCRIPTION
**Pull request by unit0016**
### This PR contains, has contained, or will contain content that is best experienced as a surprise from a player level.
This PR, conceptually; is simple. It is to introduce more changes to the world based on player actions, permanent scars not through a subsystem like with the curator's oddities and soapstone, but by careful curation of new additions and crafts, celebrating the interactions we have and, in my opinion - making the world that little bit more believable. What can I say, always been a fan of when the game cares about what players do.

- [x] Posters, specifically 'commemorating' the 'dancer' Honk mech, Shipstation, and the time an HOS fell down into the Interdyne xenobio killchamber. Addendum; Three more posters. A certain chemical, Operative Duffy, and of course. RUN.
image
image
- [x] Implement a ruin of the infamous Ship. No, not functional.
- [x] A nod to the woo spider. I'm thinking.. holodisk on some nutter? 

I am open to expanding content based on suggestions of specific events. I had my eyes on adding a wink to some of the things Liuvik did for server events, but ultimately decided I'd have to make too many assumptions on it to do so.

## Why It's Good For The Game
Sue me, I'm on a CRPG kick and want player reactivity, even if I have to do it manually to do it justice.

## Changelog
:cl:
add: Posters! Several posters referencing more 'historic' events of the frontier. There may also be a holodisk somewhere in the depths of maintenance...
expansion: Two new space ruins are on the prowl. One may look familiar...
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
I don't think a pickaxe is a good idea. I don't want to reward rulebreakers.

**Comment by thestubborn** [comment]
notched pickaxe based
add a memorial of the time we killed god

**Comment by Arctaisia** [comment]
I can't wait for my Hubert Gruber terror spider anal vore holodisk...

**Comment by Kroto-Ker** [comment]
Ideas for other items! Since you're open to suggestions. I think!

-Caitlin's Guide to MKultra (A poster or a book)
-Astrogen explosion ruin or maintenance thing
-Broken Dormitory force field generator
-Fake 'paperwork' crate for Cargo. In the warehouse or contraband orderable.
-Belly Brig poster with a picture of a dogborg. :)
-Xenoarcheology lavaland ruin or reference

I hope this is what you meant by suggestions- Great PR regardless!

**Comment by thestubborn** [comment]
no 
this isnt me being funny
no, do not put in belly brig/dogborg

**Comment by Kroto-Ker** [comment]
😈 Belly Brig 😈 
Most effective piece of Security propaganda.

**Comment by unit0016** [comment]
> I don't think a pickaxe is a good idea. I don't want to reward rulebreakers. 

Fair nuff

**Comment by Arctaisia** [comment]
These nods to oldbase make me really happy, thanks nerd, for all this! Love the belly brig poster,, :eyes:

**Pull request merged**
