### PR TITLE
RedSec is back!  🦀

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
...In a crate
Adds a crate with redsec uniforms

## Why It's Good For The Game
I like the color

## Changelog
:cl:
content: RedSec uniforms crate
/:cl:

### CODE REVIEW

**Comment by Vizoplez** [comment]
this is a very cursed commit list.

**Comment by Vizoplez** [comment]
also, webeditor. 🤮

**Comment by YakumoChen** [comment]
It was an idea I had at work that couldn't wait until I got home

It's just copy and paste anyway /shrug

**Comment by coffeecoffeecoffee** [comment]
I was very ready with my thumbs down until I realized it was optional and in a crate. As an option, that's based.

**Comment by YakumoChen** [comment]
@Gandalf2k15 review please

**Review by Funce — APPROVED** [review]
Yeh, this one's alright.

**Pull request merged**
