### PR TITLE
[NON-MODULAR] Change the description of the bear trap

### PR DESCRIPTION
**Pull request by Guidesu**
## About The Pull Request
Mr. Mondays asked me to do this.
Just changed the desc to something not boring

## Changelog
:cl:
code: Changes the bear trap description to be a little more fun.

/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
PR this to the upstream, I don't see why they'd refuse this, I'm sure everyone will agree it's much better.

**Comment by NullDagaf** [comment]
The current description is good enough, I don't see a reason to change it.

**Comment by tf-4** [comment]
Good change, original is bad

**Comment by Gandalf2k15** [comment]
Do this upstream if you must.

**Pull request closed without merging**
