### PR TITLE
[NON-MODULAR] The 30TC traitor update

### PR DESCRIPTION
**Pull request by Azarak**
## About The Pull Request
Actually, let's try with 30 TC first
https://github.com/Skyrat-SS13/Skyrat-tg/pull/1743 Make sure this is also in effect before you merge this, to make sure that traitors are actually following some sort of a story, instead of just chaos and the usual TG objectives.
This PR changes the telecrystal count on uplink to 30, on the spawned ones aswell
Other changes:
Romerol ~~is unavaiable to get from uplink~~ costs 45 TC
Syndicate Bomb now does a smaller explosion and costs 18 TC and cant be discounted
Fists of the North Stars are unavailable to get from uplink
Detomatix is unavaiable to get from uplink
Sabotage bundle can no longer be rolled (the one filled with explosives to the brim)

If this proves to be too much TC for traitors then obvoiusly I'll lower it

## Why It's Good For The Game
Traitors often dont have enough TC for gadgets to do their gimmicks aswell for a real weapon to defend themselves. This should help a lot, especially for people who dont go out of their way on power scavenge hunt.

## Changelog
:cl:
del: Removed Fists of the North Star and Detomatix from the traitor uplink
balance: Traitors now get 30 TC
balance: Syndicate bomb explodes in a smaller radius, costs 18 TC and cant be discounted. Romerol now costs 45 TC
del: Sabotage syndicate bundle can no longer be rolled
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Suggesting test merge phase, will update server.

**Comment by Zenitheevee** [comment]
This is an.... Interesting idea.

**Comment by Low3** [comment]
Sounds good. Maybe do the same thing with explosives bundle? At least if it still exists and works as before.

**Comment by Azarak** [comment]
> 
> 
> Sounds good. Maybe do the same thing with explosives bundle? At least if it still exists and works as before.

good catch, will get rid of it too

**Comment by ShadeAware** [comment]
image
What is this bullshit? Why can't you just make it fucking 40tc instead of sneaking in a bunch of fucking removals for no good reason?

**Comment by Azarak** [comment]
> 
> 
> image
> What is this bullshit? Why can't you just make it fucking 40tc instead of sneaking in a bunch of fucking removals for no good reason?

>
> sneaking removals

Every change is documented, though I shouldnt probably remove Romerol, it wasn't much of an issue on the previous base afterall. I'mma change that actually

**Comment by ShadeAware** [comment]
Sneaking probably wasn't the best word, you're right. Apologies, I was very heated.

**Comment by RatFromTheJungle** [comment]
now 40

**Comment by Azarak** [comment]
Actually lets first start with 30

**Comment by Gandalf2k15** [comment]
Again, testhing shows no inherent issues, let's get the TM's down, this will be FM'd in 1 day.

**Pull request merged**
