### PR TITLE
[non-modular] Disables broken shuttle catastrophe event

### PR DESCRIPTION
**Pull request by NotRanged**
## About The Pull Request

Doesn't work with our current shuttle, setting occurrences to 0 makes it not roll and fail every now and then.

## Changelog
:cl:
fix: Made shuttle catastrophe unable to roll and fail, wasting an event roll.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Can you see about fixing it?

**Comment by NullDagaf** [comment]
> Can you see about fixing it?

Don't fear removals, for they're the step towards enlightenment.

**Comment by YakumoChen** [comment]
I think I specifically remember commenting that the new shuttle messed with alternate shuttles and it was never fixed

**Comment by NotRanged** [comment]
> Can you see about fixing it?

As in, you want shuttle catastrophe to replace your custom shuttle to a random one again?

**Comment by SpaceVampire** [comment]
I do also dislike that the new current shuttle seems to be the same for each station.
Wouldn't mind just returning to the old system, and only keeping that kind of design for the shuttle that takes people to the station.
Its really hard to tell what is a window, what is a wall, and how the blocks actually come together.
Because every part of it is just called "shuttle wall" for some reason.

**Comment by Gandalf2k15** [comment]
Fix the shuttle event.

**Pull request closed without merging**
