### PR TITLE
[MODULAR] Egun Crafting Fix

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request

Yeah so, the E-guns that you're supposed to craft the super-specialized firearms with can't be acquired basically at all anymore, so I updated and modularized the crafting recipes to use what sec can get from energy tokens, the Armadyne Alistar SC-05 Laser Focus Rifle. 

Gorble

Shoutout to this homie who made the bug report https://github.com/Skyrat-SS13/Skyrat-tg/issues/4365

## Why It's Good For The Game

We've got like 7 guns that can't be crafted due to an oversight. I don't like sec powercreep, but this is something they're supposed to have in the first place,.

## Changelog
:cl:
fix: Armadyne has received word of crafty Security Officers modifying the newer Laser Focus Rifles into specialized homebrew firearms, please be warned that this will void their warranty.
/:cl:

### CODE REVIEW

**Comment by Cheshify** [comment]
> You currently have a negative Fix/Feature pull request delta of -5. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

shut up nerd all I DO IS FIXES

**Comment by Gandalf2k15** [comment]
Looking at this... I forgot that I added the hitscan rifle then lazily edited it. Can you change it so that the e-gun token offers the standard laser gun instead? And just delete the hitscan bullshit one.

**Comment by Cheshify** [comment]
> Looking at this... I forgot that I added the hitscan rifle then lazily edited it. Can you change it so that the e-gun token offers the standard laser gun instead? And just delete the hitscan bullshit one.

Yeah sure, keep both laser guns or just the Egun?

**Comment by Cheshify** [comment]
I'll just make this a new PR

**Pull request closed without merging**
