### PR TITLE
[MODULAR] Fix Blueshift capacitor banks not actually being linked

### PR DESCRIPTION
**Pull request by RimiNosha**
## About The Pull Request
These seem as if they're intended to be the roundstart power buffer... except they aren't linked to the main powernet at all!

## How This Contributes To The Skyrat Roleplay Experience
Having roundstart power last longer than 10 minutes is nice, mm?

## Changelog

:cl:
fix: Blushift's roundstart power capacitors are now actually linked, actually giving engineering time to setup the SM before blackouts.
/:cl:

### CODE REVIEW

**Review by Jolly-66 — COMMENTED** [review]
I'm currently talking with the other maints and Isaac to devise what we want to do here.

We're aware of BlueShifts power issues, and it isn't helping that power was "buffed" sometime within the last month.

I'll come back once I have a more concise answer on what we're doing, as I don't think this is the way to go for now.

**Comment by RimiNosha** [comment]
I mean, all I did was add a few wires, cause it very much seems this was intended to be linked to the powernet, cause there's a note referring to them inside the SMES room next the reactor-

But if you've got other plans, then so be it!

**Comment by Jolly-66** [comment]
> Rimi said something

Sorry, I wanted to respond to you last night but I was dog tired.

Currently, your implementation will create an eternal feedback loop with power. Power storage in game is supposed to be linear (power source -> power storage -> powered machine), so that power storage may be drained. I don't know how this would impact performance (that being, the eternal loop).

As I've been talking with Isaac, the entire room is a band aid solution to give engies time to setup. If the issue right now is "we lack power" or "we don't have enough power by [time]", I can look into increasing the output of the SMES, but do please keep in mind, Atmos (15kW), NT Consultant (14kW) and the captains dining room (13kW) are the three biggest round start draining rooms.

I'm voiding chemistry as I'm more concerned about **round-start** out of the box BlueShift.

**Comment by RimiNosha** [comment]
Red wires are currently completely broken, last time I checked, but yea, I should remove the red wires to prevent feedback loops should this go ahead-

I'll wait to see what you guys decide on though!

**Comment by Jolly-66** [comment]
> Rimi said something

Alright, so, I'm wrong and didn't know SMES only connect to layer 2 wires.

For now, I'd **strongly** recommend unwiring the input terminals (that being, make sure they're NOT connected to the main grid). Change the red wires to yellow, remove the junction (to the north of the north door) and things should be working again.

Don't forget you **still** need a SMES power terminal (the thing that juts out on the floor) for the SMES to function.

EDIT: For comparison, heres Metas power room:

image

The tesla coils are directly connected to the SMES (and the room APCs), while the SMES are connected to the rest of the station.

**Comment by RimiNosha** [comment]
Oh wow, yea, I didn't even realize it was the wrong way around either, cause I'm used to seeing red wires being used for input in other codebases-

Will sort out soon!

**Comment by RimiNosha** [comment]
Sorted, let me know if there's anything you want me to change while I'm at it!

**Review by Jolly-66 — APPROVED** [review]
LGTM. Thanks again, this'll at least help with live for the time being until me and/or Isaac get our plans organized and pushed.

**Pull request merged**
