### PR TITLE
[Semi-modular] Ports race-specific drinks from oldbase

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Brings across race-specific drinks from the old base, as well as "Cog Grog" (a renamed CogChamp) and catnip tea.

This includes:
- Cog Grog coggrog
- Catnip Tea catniptea
- Coldscales (lizards) coldscales
- Oil Drum (synthetics) oildrum
- Nord King (humans & dwarves) nordking
- Velvet Kiss (zombies, vampires, and dullahans) velvetkiss
- Abduction Fruit (Abductors) abductionfruit
- Bug Zapper (insects, flypeople, and moths) bugzapper
- Mush Crush (podpeople) mushcrush
- Hollow Bone (plasmamen and skeletons) hollowbone
- Jell Wyrm (jellypeople, slimepeople, and luminescents) jellwyrm
- Laval Spit (golems) lavalspit

## Why It's Good For The Game

More drinks are more fun.

## Changelog
:cl:
add: Ports most race-specific drinks over from the oldbase, as well as two others
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
why rename cogchamp though?

**Comment by tf-4** [comment]
> why rename cogchamp though?

Because it's a meme name

**Comment by YakumoChen** [comment]
The game has a LOT of meme names. There are almost literally countless references. More are being added on a weekly basis.

**Comment by Arctaisia** [comment]
> The game has a LOT of meme names. There are almost literally countless references. More are being added on a weekly basis.

Then we can do our best to try get rid of the terribly obvious ones, this is meant to be an RP server, not some shitty meme server.

**Review by Gandalf2k15 — APPROVED** [review]
This is very cute!

**Pull request merged**
