### PR TITLE
Roller bed cells now buckles the mob to the bed.

### PR DESCRIPTION
**Pull request by KathyRyals**
## About The Pull Request
Roller bed cells now buckles the mob to the bed.

## How This Contributes To The Skyrat Roleplay Experience

Roller bed cells now buckles the mob to the bed. It's cool like that.
## Changelog

:cl:
qol: Roller bed cells now buckles the mob to the bed.
/:cl:

### CODE REVIEW

**Comment by softcerv** [comment]
While I appreciate the QoL, I worry that this might end up making the medigun too robust in the hands in the hands of a secmed (or any sec officer with a medigun) since you can just buckle anyone that gets downed during a fight.

**Comment by KathyRyals** [comment]
I really, really doubt we'll ever see this happen, especially since there is no reason for a sec officer to carry around a medigun.


I'd rather not prevent the introduction of good QoL features just because someone might use them in a gamey way once every 200 shifts.

**Comment by softcerv** [comment]
> I really, really doubt we'll ever see this happen, especially since there is no reason for a sec officer to carry around a medigun.
> 
It's not unimaginable for a sec-medic to carry a medigun. (especially if it ever ends up becoming a weapon for them)
> I'd rather not prevent the introduction of good QoL features just because someone might use them in a gamey way once every 200 shifts.
>
Being able to basically instantly chairbuckle someone in the middle of combat because they touch the floor for a second is really robust and can quickly end a fight, especially if the person is cuffed. Think about how this would pair with CMO or Sec Medic who both have instant knockdown tools and would be likely to use Mediguns. This really feels like more of a buff than a QoL change.

**Review by GoldenAlpharex — APPROVED** [review]
Looks good to me.

**Comment by tf-4** [comment]
maybe a short do_after?

**Comment by softcerv** [comment]
I think the best way to handle this is have the auto-buckling restricted to unconscious, crit, or dead people. That way, It would still be a QoL, but it wouldn't really be a combat tool anymore.

**Comment by tf-4** [comment]
^ also a good solution

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
Yeah I think making sure it's only done when they're unconscious or dead would be the best way for this to not be used for gamering.

**Comment by KathyRyals** [comment]
Good idea.

**Review by tf-4 — APPROVED** [review]

**Review by GoldenAlpharex — APPROVED** [review]

**Pull request merged**
