### PR TITLE
[MODULAR] Removes beesease from the bee loadout

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

Removes it from the bee loadout.

## Why It's Good For The Game

The creator of the loadout asked for it to be removed.

## Changelog
:cl:
del: Removed beesease from the traitor loadout
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
cringe PR! Why!

**Comment by MLGTASTICa** [comment]
Bad PR , the disease is easily cureable.

**Comment by SpaceVampire** [comment]
Yeah, what is the issue with it?
The cure is Sugar, one of the most common reagents in the game.

**Comment by Gandalf2k15** [comment]
I'm pretty sure this can also be attained from the other standard syndicate bundles TG has.

**Comment by Swiftfeather** [comment]
> I'm pretty sure this can also be attained from the other standard syndicate bundles TG has.

I checked this and saw, if it's in another loadout there's no reason to remove it. Must not be too broken! Was just doing this pr at a request anyway.

**Pull request closed without merging**
