### PR TITLE
[MDB IGNORE] Kills yet more Polychrom uniforms (Gives them fitting GAGS replacements where applicable)

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
God
I hate
Polychrom

Is it dead? Is that all the items gone? IDK IDC its the uniforms at least.

Yet another icon sorting PR. Uniforms.dmi's are almost cleared out. I'm almost done with Uniforms.
Almost.

---
Comprehensive list of changes:
- Items that remain: Suit, Suitskirt, Kilt; all reworked to have nicer/GAGS code/sprites.
- Items removed: Shorts, Tri-Tone Jumpsuit, Bottomless Shirt, Tanktop, Feminine Tanktop.
.
- Shorts were unused and kinda ugly; TG has "Buttondown w/ Shorts".
- Jumpsuit caused map changes; TG has "Greyscale Jumpsuit", and jumpsuits shouldn't really be THAT customizable anyways. It gets to the point of not being a jumpsuit any more.
- Bottomless Shirt is weird; it's a suit-top but no bottom? Removed mostly bc it just made no sense. Crew wear pants.
- Tanktop is an Underwear.
- Feminine tanktop is an Underwear.
.
- Re-paths vicvest from /costume/skyrat to /pants/skyrat. Regardless of if TG chooses to move their buttondown out of /costume, it's just so much easier for us to keep them pathed to where their icons are.
- Kilt has been pathed to /pants/skyrat because TG's yet to make a 'shirt+bottom' itemtype and storing these in costume.dmi is unappealing. It works.
- Removes most moved icons out of the master uniform.dmis. You can see how close we are now, 3 lines. 3 lines...
- (I swear I already did this idk how its also in this PR) Removes digi templates from a few digi files; the template is now stored in color_digi.dmi

## How This Contributes To The Skyrat Roleplay Experience
Icon sorting, removing obsolete stuff, nicer sprites, yada yada look at the shit it looks better than poly ever did
<details><summary>IMAGES HERE CLICK NOW CLICK IT DO IT</summary>

image

image

image

</details>

## Changelog

:cl:
imageadd: Poly suit/suitskirt/kilt have been resprited and GAGSified proper! They are now the Recolorable Formal Suit/Suitskirt, and Recolorable Kilt!
imagedel: Poly Shorts, jumpsuit, panties, tank-tops etc are gone. Please use the Recolorable Buttondown w/ Shorts for the Shorts, the Greyscale Jumpsuit for the jumpsuit, and the others are already underwear types.
/:cl:

### CODE REVIEW

**Review by Paxilmaniac — APPROVED** [review]
rest in pieces polychromatic clothing, you will not be missed, map changes are ok

**Comment by Zergspower** [comment]
well tits - i'll go revisit the polychrom ruin

**Review by Ebin-Halcyon — APPROVED** [review]
Sprites are solid to me.

**Review by GoldenAlpharex — APPROVED** [review]
I actually had viewed all the files already, and it seems I just forgot to click Approve.

**Pull request merged**
