### PR TITLE
[MODULAR] Turning the Boowomp inhibitors off

### PR DESCRIPTION
**Pull request by W4rd3nn**
## About The Pull Request
This adds a boowomp emote. It lets you boowomp when you're really sad or bummed out. Synths can boowomp too so when they're lawed to murder the whole station they can go "boowomp". The sound is sourced from the Hanna-Barbera Sound Effects Library.

## How This Contributes To The Skyrat Roleplay Experience
We have a lot of emotes for different states of emotions. Lots of variation. There's only really two for sadness. Frown and Cry. Now we can be varied in our display of sadness.

Here's an endorsement from former president Donald Trump
<details>
<summary>Former Presidential Endorsement</summary>

> Well folks, let me tell you something about the boowomp emote. It's a very, very sad emote. The saddest, in fact. And let me tell you, it contributes to Skyrat's roleplay environment in a tremendous way. Tremendous.
> 
> You see, when you're playing a game like Skyrat, you want to be able to express your emotions, your feelings, your sadness. And that's where the boowomp emote comes in. It allows you to really show your character's sadness, and that's important in a roleplay environment.
> 
> Now, some people might say, "Oh, it's just an emote. Who cares?" But let me tell you, it's more than that. It's a tool for expression. It's a way to connect with other players. It's a way to show empathy, to show that you understand what someone else is going through.
> 
> And that's what Skyrat is all about, folks. It's about connecting with other players, creating a community, and having fun. And the boowomp emote helps to do just that. It's a symbol of the Skyrat community, a way to show that we're all in this together.
> 
> So let's give a big round of applause to the boowomp emote, folks. It's doing a tremendous job. A tremendous job. And let's keep using it to create a strong, supportive, and fun roleplay environment in Skyrat. Thank you, folks.

</details>
And here's an endorsement from current president Joseph Biden to show bi-partisan support.

<details>
<summary>Presidential Endorsement</summary>

> Listen, Jack. The boowomp emote is the real deal. It's a way for us to show our emotions and connect with one another in Skyrat, cut the malarky.
> 
> Now, I know some folks might say, "Oh, it's just an emote, who cares?" But let me tell you something, Jack. It's more than that. It's a way for us to show empathy, to understand one another, and to build a strong and supportive community in Skyrat.
> 
> When I see players using the boowomp emote, I know that we're on the right track. It's a symbol of the values that we hold dear in Skyrat: kindness, compassion, and understanding.
> 
> So let's keep using the boowomp emote, Jack. Let's show our fellow players that we care, that we're here for them, and that we support them. Let's build a Skyrat that we can all be proud of, where everyone is welcome and everyone has a voice.
> 
> In closing, let me just say this: the boowomp emote is a real winner. It's doing a tremendous job, and it's making Skyrat a better place. So let's keep using it, let's keep building our community, and let's keep having fun. Thanks for listening, Jack.

</details>

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

https://user-images.githubusercontent.com/12723348/223578848-47d2e3ae-3b4a-48d9-bd80-2567142ba7a2.mp4

</details>

## Changelog

:cl:Motho
add: Added a boowomp emote for synths and carbons
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
I can't over the fact that's the sound effect used somewhere else when something was taking a shit, and I'm never going to be able to get that mental image out of my head.

**Comment by W4rd3nn** [comment]
> I can't over the fact that's the sound effect used somewhere else when something was taking a shit, and I'm never going to be able to get that mental image out of my head.

i'll wait until ur online and ghosting and then walk into the bathroom and spam the boowomp emote just to harm u

**Comment by YakumoChen** [comment]
> Hanna-Barbera Sound Effects Library.

Copyright issue

**Comment by YakumoChen** [comment]
To elaborate:
Hanna Barbera's stock sounds are royalty-free, but they are _not_ open source, and thus incompatible with the codebase.
To compare, Kevin MacLeod (the musician who can be heard in innumerable videos on Youtube) is also royalty-free, but is also _creative commons_, meaning it is free to use with credit.

**Comment by W4rd3nn** [comment]
> To elaborate: Hanna Barbera's stock sounds are royalty-free, but they are _not_ open source, and thus incompatible with the codebase. To compare, Kevin MacLeod (the musician who can be heard in innumerable videos on Youtube) is also royalty-free, but is also _creative commons_, meaning it is free to use with credit.

what if i told you i held synchronizations rights to the sound effect

**Comment by YakumoChen** [comment]
what does that even mean? Its an open source codebase. You can't just take a copyrighted sound from someone else and make it freely available to everyone. Not without obvious, explicit permission.

Even if you had a license (ie you bought a hard copy of the sounds) I can't see you having the legal right to just add it to an open source codebase with that alone.

**Comment by Zonespace27** [comment]
They won't link it, so I'm just closing this early

**Pull request closed without merging**
