### PR TITLE
[NONMODULAR] Security Cyborgs are now locked behind the techweb! Requires the Mother of God experiment to research!

### PR DESCRIPTION
**Pull request by Iamgoofball**
## About The Pull Request
ObxRtQvLwL
Requires the Mother of God research experiment.

## How This Contributes To The Skyrat Roleplay Experience

Security Cyborgs are extremely powerful, and a frankly abusable module. This gives the Research team a way to keep the AI and Cyborgs from misusing this module, by allowing them to delete it off the research server if needed, and a way to reward the AI and cyborgs if it plays nice and keeps itself in check.

## "but it's an OOC issue"
in 10 years of ss13, no policy document or administrative work or adjustment to equipment has ever stopped security borg players from going sicko mode, ignoring their AI laws, and prioritizing the valid salad/arresting of people

no matter how many people you ban, no matter how big you make the red text saying "follow your AI laws over space law", people will continue to fuck it up endlessly until the heat death of the universe

at the end of the day, it breaks the biggest logical assumption about cyborg modules:
doing your module's job is not likely to run afoul of your lawset outside of edge scenarios
however, because of the situation security cyborgs are given(be a sec officer) you very frequently end up in situations where your laws(obey the crew, dont hurt people, keep yourself alive) conflict with the job you've been assigned(be a sec officer)

this is lessened due to not being on asimov/crewimov, but this actually makes the situation worse because at least on asimov, you can go "law 2 secborg fuck off" and when it doesn't fuck off it gets blown for being rogue
here, not so much, there's some leeway to disregard orders, however players take that leeway and run with it all the way to valid hunter secborg #4323242 because at the end of the day, secborg is a poorly designed cyborg module

peacekeeper does the job the secborg is supposed to do way better(conflict resolution, stop crew harm) by having actual tools to defuse a situation and stop people hurting eachother so the AI and cyborgs have time to go "why can't we all be friends :(" like it's supposed to do

## Changelog

:cl:
balance: Security Cyborgs are now locked behind the techweb! Requires the Mother of God experiment to research!
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
GBP isn't real, it can't hurt you.

**Comment by softcerv** [comment]
I worry that with this solution it will just lead to those same people rushing R&D to get this unlocked.

**Comment by dawsonkeyes** [comment]
i like this, secborgs are nigh immune to most obtainable anti-sec things (see: shoving the fuckers, punching the fuckers) and it's also made impossible to tell what they're about to swing at you (you can see what's in a secoff's hand, but good luck predicting that no-CI flash from borgie)

**Comment by Armyguy** [comment]
HAHAHAHAHAHHA this is just REALLY funny to me, mostly as 95% of borg players (Myself being one of them) find that sec borgs REALLY suck. Even for malf AI sec borgs suck.

**Comment by SpookyTheFox** [comment]
Probably better than what I was considering doing, which is moving them to ghost role only.
However. You need to go back to discord discussion as there's a lot of balance implications in this, and you are knowingly adding further restrictions to content you yourself broke in the sec rework PR. If you are going to touch sec borg, I'd like it to at least work as intended when someone does go to the trouble of unlocking it. Which means fixing the way charge drain works, or more accurately, does not.
Couple other things to things to cover. From a game design philosophy, we do not restrict the AI via mechanics. If you personally feel a silicon player is not following their laws, you need to ahelp, because that is an OOC problem. Removing this takes away their only reasonable option to proactively detain and control human mobs. We need at least one borg type to be able to cuff people. You should ensure it stays available at the very least for malf or by emagging the exosuit fab, unless you are giving another borg, like peace keeper, a cuffing mechanic. Adding cable cuffs to their emag list would work for this purpose.
Also, single letter variable name in robot.dm

**Comment by Iamgoofball** [comment]
>You need to go back to discord discussion as there's a lot of balance implications in this

The only balance implication here is that security cyborg is no longer available roundstart, provided it isn't disabled entirely since apparently nobody including Xyel knew that secborg was turned back on anyways.

**Comment by Iamgoofball** [comment]
>From a game design philosophy, we do not restrict the AI via mechanics.

Yes we do.

**Comment by Iamgoofball** [comment]
>If you personally feel a silicon player is not following their laws, you need to ahelp, because that is an OOC problem.

For ten years, we've tried to administratively fix Security Cyborg in SS13 as a whole.

Literally nobody has ever done it successfully.

Security Cyborg is just bad. This is an objective fact.

**Comment by Iamgoofball** [comment]
>We need at least one borg type to be able to cuff people. 

Actually, we don't.

**Comment by Iamgoofball** [comment]
>Removing this takes away their only reasonable option to proactively detain and control human mobs.

That is outside of the design scope of Cyborgs.

**Comment by Iamgoofball** [comment]
>You need to go back to discord discussion

Also, no I don't, actually.

**Comment by thestubborn** [comment]
yeeeeeeeeeeah

cuffing people is not the borgs job
they are meant to be sideline utilities, tools, even
not the be all end all do everything machine

**Comment by dawsonkeyes** [comment]
> yeeeeeeeeeeah
> 
> cuffing people is not the borgs job they are meant to be sideline utilities, tools, even not the be all end all do everything machine

Either way we already have the best law abiding robot, the almighty beepsky

**Comment by SpookyTheFox** [comment]
> 
> 
> > yeeeeeeeeeeah
> > cuffing people is not the borgs job they are meant to be sideline utilities, tools, even not the be all end all do everything machine
> 
> Either way we already have the best law abiding robot, the almighty beepsky

Which would almost work to maintain feature parity, but the AI control for beepsky is still partially broken, and no one has reverted the construction changes to securetrons and ED-209's now that the base parts are available again.

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by Gandalf2k15** [comment]
Internal vote passed, authorised for automerge.

**Pull request merged**
