### PR TITLE
[Modular] [WIP] "Drake, Where's the Shuttle Console?"

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Makes Cybersun a functioning shuttle. Yes, really. No more hunting for the whiteship and ~~self antagging~~ stealing it from the station.
For balance reasons, the shuttle still requires power. SMES and Pacmans on shuttles are finnicky at best, but meh.

**WIP, Because shuttlecode is a fucking mess**

## Why It's Good For The Game
"It goes right there, see. I drew it with the magic marker."
image

## Changelog
:cl:
add: Cybersun is now a functioning shuttle. God help us all.
/:cl:

### CODE REVIEW

**Comment by Trubbl3** [comment]
can't wait for a single person to use it on bad faith to get removed permanently!

**Comment by unit0016** [comment]
> can't wait for a single person to use it on bad faith to get removed permanently!

You laugh, but ghostrole policy is literally just "you can act in bad faith if x,y,z. Also only research with 15k+ points I guess."
I somewhat have a license to just. Not care.

**Comment by unit0016** [comment]
Closing this PR. Genuinely fuck /tg/ shuttle code, I can't figure this shit out. If someone wants to take a crack at it, be my guest

**Comment by Arctaisia** [comment]
You might be able to copy over whiteship code, make a new area definition and such.. Not sure how it all works, but I think I know how the mapping goes, at the very least.. *Think* is a very large word there. But I do know that it's already been done with the small freighter ship, on the trade route, it's a whiteship that won't leave the z-level once the departures shuttle takes off.

**Pull request closed without merging**
