### PR TITLE
Energy gun rebalance [Semi-Modular]

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Energy gun > Energy carbine
Cell: 1000 > 2500

Laser gun > Laser carbine
Cell: 1000 > 2500

Laser cannon
Cell: 1000 > 2500
Base damage: 30
Chargeup firetime: 0.6 seconds.

## Why It's Good For The Game

This is to counteract TG's changes to energy guns, due to the fact these are now considered your MAIN firearm, they have had their capacity increased significantly. They are big guns, and this should reflect that.

## Changelog
:cl:
balance: Rebalanced energy guns, laser guns, and the laser cannon.
/:cl:

### CODE REVIEW

**Comment by Azarak** [comment]
How many shots is that?

**Comment by Gandalf2k15** [comment]
> How many shots is that?
about 25

**Comment by SpaceVampire** [comment]
I'm still not really in favor of messing with the balance around this stuff, for the same reason as on the other PR closed above. I would like to have more rounds to see how it feels before we start doing weapon rebalances.

**Comment by ShadeAware** [comment]
I think this is still good

**Pull request merged**
