### PR TITLE
[NONMODULAR] Rebalances Space dragons

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

See: Title

Health increased from 400 to 550
Damage increased from 35 to 35-40
Armor pen increased from 30 to 34

## Why It's Good For The Game

Space dragons get fucking DUNKED on right now, it's hilarious. This gives them a BIT more survivability, and encourages people to melee them less.

## Changelog
:cl:
balance: Tweaks space dragons to be a slightly bigger threat.
/:cl:

### CODE REVIEW

**Comment by H0gberg** [comment]
this is very biased, you are a derg, you just want to make all dergs stronger, donut merge!!!!

**Comment by tf-4** [comment]
550 HP is quite a lot. Otherwise decent changes. Would prefer 450-500 HP personally.

**Comment by NullDagaf** [comment]
> encourages people to melee them less

Meanwhile, the miner putin walks over to the space dragon with a proto-kinetic crusher.

**Comment by Sethnov** [comment]
i believe their is a pr for this on tg https://github.com/tgstation/tgstation/pull/57942 but currently a draft.

**Comment by ATH1909** [comment]
how does this actually fix any of the problems with space dragons?

**Comment by IndieanaJones** [comment]
Shoutouts to SimpleFlips

**Comment by GoldenAlpharex** [comment]
>They get dunked on now

>Dragon proceeds to dunk on the station the shift before this PR is re-opened.

Nice.

**Pull request merged**
