### PR TITLE
[MODULAR] Fixes the roundstart slime species being able to get fracture wounds

### LINKED ISSUE #20677: Slime Bones
## Round ID:

8142, though this bug goes back much farther than that. Over a month, if not more than that.

## Testmerges:

[#18110: 'Antag Revamp*: The Nuclear-ish Option' by Zonespace27 at commit 64f88e3e09](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18110)
[#19820: '[TM-ONLY] Prevents the psyker pirate variant from rolling' by GoldenAlpharex at commit b337b1a9a0](https://github.com/Skyrat-SS13/Skyrat-tg/pull/19820)
[#18448: '[MOSTLY MODULAR] Time Clock' by softcerv at commit 95618085cd](https://github.com/Skyrat-SS13/Skyrat-tg/pull/18448)

## Reproduction:

Xenobiological Slime Hybrids, at least the roundstart version, seems to have bones. Slime characters are suffering wounds they shouldn't, such as broken bones and lacerations. Slimes are not meant to have wounds like this.

Wounds can be caused by any numbers of sources, but taking the cursed quirk is a quick way to bring it up. Or get shot, stabbed, or anything.

image
image

### PR DESCRIPTION
**Pull request by vinylspiders**
## About The Pull Request

Roundstart slime limbs were missing the correct bio flags. I ended up just making them subtypes of /slime so that future changes to slimepeople hopefully break things less. There was really no reason for them to not be as far as I could tell.

If this breaks anything please let me know.

edit: at request made them able to still get flesh wounds

Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/20677

## How This Contributes To The Skyrat Roleplay Experience

Bugfix

## Proof of Testing

<details>
<summary>Their limbs get the inorganic bio state now</summary>
  
image

</details>

## Changelog

:cl:
fix: roundstart slimes now have the same wound immunities as the rest of the slimes.
balance: roundstart slimes can still get flesh wounds
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
"Fractures etc"? Does this include all wounds or just bone.

**Comment by vinylspiders** [comment]
> "Fractures etc"? Does this include all wounds or just bone.

ALL wounds. It works exactly the same as it does for the other jelly races.

**Comment by vinylspiders** [comment]
If we want them to work differently from TG slimes and be able to get flesh wounds or whatever, I can add that easily enough.

**Comment by YakumoChen** [comment]
I feel like they should still get bleeding and puncture wounds at minimum? This is a buff for an already pretty overpowered race and full immunity doesn't make much sense. The other slime races are locked behind a department too.

**Comment by vinylspiders** [comment]
> I feel like they should still get bleeding and puncture wounds at minimum? This is a buff for an already pretty overpowered race and full immunity doesn't make much sense. The other slime races are locked behind a department too.

Fair enough. They can get flesh wounds now.

**Comment by vinylspiders** [comment]
I should note, it's possible to be tranformed into a roundstart slime via imperfect mutation toxin. If that is desired to be only for the tg 'upgraded' slimes that are immune to all wounds, then I can unrevert https://github.com/Skyrat-SS13/Skyrat-tg/pull/20712/commits/047312a4683f9669f7240fc09aaaec66926b6068 to remove them from the pool to choose from.

**Comment by nikothedude** [comment]
You know with the lack of bones, I would argue it should become a lot more likely for them to be dismembered. Or alternatively, since they have no bones to hold the flesh together - the limbs could just be crushed off.

Just a little balancing idea to offset the fact this would just be a straight buff otherwise.

**Comment by Resreep** [comment]
> I feel like they should still get bleeding and puncture wounds at minimum? This is a buff for an already pretty overpowered race and full immunity doesn't make much sense. The other slime races are locked behind a department too.

It isn't a buff, this is how they worked and were meant to work. Even now with slimes taking wounds, it doesn't seem to genuinely do anything other than giving bad moodlets.

**Comment by YakumoChen** [comment]
> > I feel like they should still get bleeding and puncture wounds at minimum? This is a buff for an already pretty overpowered race and full immunity doesn't make much sense. The other slime races are locked behind a department too.
> 
> It isn't a buff, this is how they worked and were meant to work. Even now with slimes taking wounds, it doesn't seem to genuinely do anything other than giving bad moodlets.

wounds make dismemberment easier, and bleeding wounds can and should be very deadly if left untreated. Slimes have blood, so they should properly be able to bleed (in fact bleeding should be even more deadly for them than otherwise because they need it to maintain their limbs)

**Review by tf-4 — APPROVED** [review]

**Pull request merged**
