### PR TITLE
Removes all Modular Singularity Code

### LINKED ISSUE #21475: modular_skyrat/modules/aesthetics/singularity directory is too large
`modular_skyrat/modules/aesthetics/singularity` directory

- 12.0MB
- Reason: Very, very large directory that adds a lot to the RSC cache. Up to the spritetainers if they want to axe the directory entirely or do smth else

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request

Closes https://github.com/Skyrat-SS13/Skyrat-tg/issues/21475

Doing some part to reduce some of the overhead shown in #21358
Reverts Singularity to use base TG sprites.
Removes all code associated with the defunct engine.
The singularity is no longer a possible engine to make regularly in game, thus its likelihood of appearance is close to nil in any given round. The modular sprites are therefore more or less 12mb wasted space on our codebase players are forced to load in every time they connect.
All relevant code has been removed due to being defunct.

## How This Contributes To The Skyrat Roleplay Experience
Allowing players to join the game faster will result in a better roleplay experience overall.

## Changelog

:cl:
image: Singularity sprites reverted to base TG for the benefit of game load times.
remove: Singularity engine code
/:cl:

### CODE REVIEW

**Review by Ebin-Halcyon — APPROVED** [review]

**Review by tf-4 — CHANGES_REQUESTED** [review]
can you just drop the whole `modular_skyrat/modules/singularity_engine` folder?

**Comment by YakumoChen** [comment]
There's code for a "singulo forming" animation it still uses.

**Comment by YakumoChen** [comment]
@tf-4 I decided to just remove the whole modular folder for the singulo since it was commented out code anyway.

**Comment by tf-4** [comment]
yeah thats what I meant lol
just needs the dme fixed

**Review by tf-4 — APPROVED** [review]
rest in piss

**Pull request merged**
