### PR TITLE
Doohickey Sidequest - adds an Archangel rifle parts kit for funsies

### PR DESCRIPTION
**Pull request by Hatterhat**
## About The Pull Request
puts the power of the Archangel into the hands of the common spaceman via black market sidequest
image
(black market uplink lets you buy an Archangel parts kit, which is literally just the stock and whatnot)
(you have to craft the parts kit with a basic ~~Mosin-Nagant~~ Sportiv and a screwdriver to turn it into an empty Archangel)
## How This Contributes To The Skyrat Roleplay Experience
makes a "unique" head item slightly less unique, adds another niche item to the black market uplink that could incite organic conflict e.g. "why did this cargo tech break into my office for a bunch of gun parts"
## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

image
image
  
</details>

## Changelog

:cl:
add: The Free Trade Union has reported losing small stocks of their "Archangel" rifle furniture sets. Coincidentally, in-sector black markets (accessible, as always, via appropriate black market uplinks) now report an uptick in availability of the very same parts. Prospective crazed gunmen are advised to bring a screwdriver.
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
image
but why pruple

**Comment by Hatterhat** [comment]
> image but why pruple

its just like that i dont know why i blame tgui

...maybe its because of how it generates the spritesheets and how sr overrides the guns?

**Comment by tf-4** [comment]
Is it purpel for other things?

**Comment by Hatterhat** [comment]
> Is it purpel for other things?

yeah it's the purple wirebrush for the regal condor too

image

i think it's because the .dmi for ballistics is 40x32 where every other given .dmi is 32x32

**Comment by tf-4** [comment]
gotta love gunwank

**Review by tf-4 — APPROVED** [review]

**Pull request merged**
