### PR TITLE
map reset and updates

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
title.
Updates the non-modular maps to upstream and makes our Icebox and Delta more like upstream.

Side note, we are going to need to figure out the camera thing before I go fucking crazy. I spent quite some time going through Tramstation fixing the damn camera and I REFUSE TO BELIEVE there is nothing that can be done to not have to go in and fix every. single. camera.

### CODE REVIEW

**Comment by thestubborn** [comment]
smart cams :)

**Comment by jjpark-kb** [comment]
> @jjpark-kb

I wish, but it was the directions and stuff.

**Comment by thestubborn** [comment]
> > @jjpark-kb
> 
> I wish, but it was the directions and stuff.

what did he mean by this

but, seriously, I meant like
wouldnt it be possible to put cameras on the smartpipe system? or something like that?

**Comment by hugmeorelse** [comment]
If Trams is going to be a problem, we can take it out of rotation if needed.

**Pull request merged**
