### PR TITLE
[Void Raptor] Minor Additions and Fixes

### PR DESCRIPTION
**Pull request by SomeRandomOwl**
## About The Pull Request

This PR adds in the genetics infuser to genetics, adds missing ordinance data disks to ordinance, and moves the disposals in the detectives office, Also added two doors to security specifically for detectives, so they have access to both evidence storage, and the interrogation room, as both rooms previously where locked behind doors that required BRIG access, which detectives lack. 

## How This Contributes To The Skyrat Roleplay Experience

This adds things that both ordinance technicians and geneticists have on other stations.

It also makes the medical records computer and APC accessible in the detectives office

It also allows detectives access two rooms necessary for their job to store evidence and to interrogate suspects.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image
image
image
image
image
image
image
image
image

</details>

## Changelog

:cl:
add: Added a genetic infuser to genetics on Void Raptor
add: Added three Ordinance Data disks to Ordinance on Void Raptor
fix: Moved the Disposals bin in the detectives office on Void Raptor
add: Added two detective access doors to security on Void Raptor, Detectives now have access to evidence storage and interrogation
/:cl:

### CODE REVIEW

**Comment by Jolly-66** [comment]
For future reference please skim currently open PRs. This is the second time this has happened, but the light is being fixed in #18446

**Comment by SomeRandomOwl** [comment]
> For future reference please skim currently open PRs. This is the second time this has happened, but the light is being fixed in #18446

ah, then i can revert that change then one sec

**Comment by SomeRandomOwl** [comment]
That should do it, should avoid any conflict with that PR

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
Please pull master into this PR. I made changes in #18408 and I would like to avoid any issues that may arise.

Just as a general rule of thumb, and this goes to everyone, non-mappers included, try to start a PR on a 1:1 with master. This way you'll mitigate merge conflicts, should you run into the **initially**.

**Comment by SomeRandomOwl** [comment]
> Please pull master into this PR. I made changes in #18408 and I would like to avoid any issues that may arise.
> 
> Just as a general rule of thumb, and this goes to everyone, non-mappers included, try to start a PR on a 1:1 with master. This way you'll mitigate merge conflicts, should you run into the **initially**.

merged with no conflicts

**Comment by SomeRandomOwl** [comment]
adding onto my PR and moving the disposals bin in the detectives office too so that it doesnt block the medical records computer and APC

**Comment by SomeRandomOwl** [comment]
Another minor addition, two detective access doors so detectives can get into evidence storage and interrogation without asking for a fellow officer to let them in

**Review by Jolly-66 — DISMISSED** [review]
Everything else is fine.

But the Detective's desk is way, WAY too cluttered. Please figure out a way to better disperse the items from "necessary" to "fluff", meaning, delete, move to cabinet, whatever. The tables are too noisy as is and not to mention this does look lazily done just to fix the console issue.

image

**Comment by SomeRandomOwl** [comment]
> Everything else is fine.
> 
> But the Detective's desk is way, WAY too cluttered. Please figure out a way to better disperse the items from "necessary" to "fluff", meaning, delete, move to cabinet, whatever. The tables are too noisy as is and not to mention this does look lazily done just to fix the console issue.


Ill see what i can do to clean it up when I am free next

**Comment by SomeRandomOwl** [comment]
<details>
<summary>De-Cluttered</summary>

image
image

</details>

moved the cameras and flasks to their closet, and reduced the overall clutter

**Review by Paxilmaniac — APPROVED** [review]
looks good to me i think

**Pull request merged**
