### PR TITLE
[MODULAR] Modify evac shuttle meteor event

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

It was headmin requested that meteors and space dust no longer hit the escape shuttle.

## Changelog

:cl: Skyrat
del: Removed the meteors and space dust emergency shuttle events
/:cl:

### CODE REVIEW

**Comment by HoodMilk** [comment]
the meteors shook the screen so much the game was unplayable, this is a good change.

**Comment by YakumoChen** [comment]
isn't this an upstream issue though?

Meteors aren't intended to hit the escape shuttle, any claim otherwise is a bug.

**Comment by softcerv** [comment]
> isn't this an upstream issue though?
> 
> Meteors aren't intended to hit the escape shuttle, any claim otherwise is a bug.

https://github.com/Skyrat-SS13/Skyrat-tg/pull/21917 This is an intentional upstream feature.

**Comment by YakumoChen** [comment]
> > isn't this an upstream issue though?
> > Meteors aren't intended to hit the escape shuttle, any claim otherwise is a bug.
> 
> #21917 This is an intentional upstream feature.

image
This is the only meteor-related event I see?

Almost all the shuttle events are supposed to be minimally damaging at best, with a very low chance for them to be hostile, and _none_ of the hostile events are meteors.

**Comment by burgerenergy** [comment]
There was an instance recently (probably that triggered this) where what I assume a friendly meteor bonked into and through a shuttle wall to gib someone, although that feels like a one in a million error.

**Review by GoldenAlpharex — APPROVED** [review]
If it gets fixed upstream to no longer cause issues, they'll be fine to be re-introduced, but for now, I'm fine with them being gone.

**Pull request merged**
