### PR TITLE
[FEATURE] It's Time To Oink

### PR DESCRIPTION
**Pull request by Blockzzy**
## About The Pull Request

Adds an oink emote, and a sound to boot, show the crew your mighty swineliness!

The sole sound added with this is sourced from Mother 3, with the bit crushing removed.

## How This Contributes To The Skyrat Roleplay Experience
There's emotes for just about every playable kind of race, but I noticed there's nothing for pigs, so I wanted to add some!

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

oinker

</details>

## Changelog

:cl:combine
add: Added an oink emote, let the swine run free!
/:cl:

### CODE REVIEW

**Review by Zonespace27 — COMMENTED** [review]
Where's the sound sourced from?

**Comment by Blockzzy** [comment]
> Where's the sound sourced from?

Mother 3, as stated above. I had some help to make it sound much less bit crushed and more organic. I did some digging, there doesn't seem to be any issues in copyright with using sounds from the Mother series. (Earthbound included.)

**Comment by YakumoChen** [comment]
> 

Except for the fact its a Nintendo IP

Nintendo is the absolute last company we want on our radar for copyright infringement.

**Comment by Blockzzy** [comment]
Non-negotiable denial, I gather?

**Comment by nevimer** [comment]
it's worth mentioning that the sound effect was used in previous fan games without issue - https://youtu.be/dWLBmcU2NLY?t=60 https://youtu.be/68lD_eanVuw?t=97

**Comment by YakumoChen** [comment]
Doesn't make it okay, especially since this is an open source codebase.

We don't want to be the codebase that tried to make a Nintendo-owned thing open source.

> it's worth mentioning that the sound effect was used in previous fan games without issue - https://youtu.be/dWLBmcU2NLY?t=60 https://youtu.be/68lD_eanVuw?t=97

Any game like this is one C&D away from being wiped off the internet, and Nintendo is extremely protective of their stuff.

**Comment by Zonespace27** [comment]
> > Where's the sound sourced from?
> 
> 
> 
> Mother 3, as stated above. 

This PR is being closed due to copyright concerns. Nintendo is worse than Disney about this kind of stuff, so it's a risk I don't want to take.

**Pull request closed without merging**
