### PR TITLE
[MODULAR] Adds No Guns-new quirk that strictly disallows you from using guns. That's it.

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request
Adds a new quirk, No Guns, with -6 cost, and the effect of giving you NO_GUNS, the same trait sleeping carp gives you. 

## How This Contributes To The Skyrat Roleplay Experience
The best part of chunky fingers without the dumb parts. I love that quirk, but not the fact that I can't use computers. So, I decided to lazily slap together a PR with the quirk that actually does the good part exclusively.

Also, opt-in mechanical disadvantages good.

## Changelog

:cl:
add: Added a new quirk: No Guns. Makes it so you can't use guns.
/:cl:

### CODE REVIEW

**Comment by SpaceVampire** [comment]
You need to make it so that you can't take this and clunky fingers at the same time due to the overlap between them. I also think this is a bit too specific of a quirk, but whatever.

**Comment by YakumoChen** [comment]
👎 
Too much overlap with Pacifist and Chunky Fingers. 

Even then it needs a specific trait ban for security and heads.

**Comment by tf-4** [comment]
Heads? What? Sec, naturally, and HoS falls under that. But heads is incorrect.

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
I'm fine with this, but that's probably another thing that Security should reasonably not be allowed to have, considering how I don't think you'd hire mercenaries that don't know how to use a gun.

**Comment by nikothedude** [comment]
As much as I'm opposed to quirk restrictions as a whole, sure.

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by PCPort** [comment]
https://youtu.be/NzwRTXBRS2g

**Pull request merged**
