### PR TITLE
[DNM][WIP] The great Teshari clothing resprite

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
### THIS IS A HARD DRAFT/GALLERY PR CURRENTLY TO KEEP TRACK OF MY PROGRESS THROUGH TESHARI RESPRITES AND REQUESTS FOR SPECIFIC ITEMS UNTIL THE MAIN PR GETS MERGED AND THE ABILITY TO OVERRIDE COLOR MATRIX SPRITES IS ADDED

As the PR title says, i'm slowly respriting the main bulk of clothing and misc items to fit on Teshari. That means yes, custom sprites for clothing, hardsuits, hats and more. This is going to take a long while to sprite the bulk of it all, so i'm not going to be respriting EVERY single item, just the main important items like commonly seen clothing, hardsuits, hats and such.

This is an extremely daunting task so forgive me if this takes a long time. Without further ado, I'll let you look at my current progress in sprites as of now. (This will update as I sprite more things)

## **Should you want to shoot me some criticism, give me some assistance in spriting, or ask for a specific item to be resprited shoot me a message on Discord: Halcyon#7104**
<details>
<summary>Hardsuits</summary>
<br>

<details>
<summary>HOS + Helmet</summary>
<br>

image
image
image
</details>

<details>
<summary>RD+Helmet</summary>
<br>

image
image
image
</details>

<details>
<summary>CE + 2 Variants of the helmet, one based off the original helmet and one similar to Virgo's.</summary>
<br>

image
image
image
image
image
</details>

<details>
<summary>Syndicate Hardsuits</summary>
<br>

Blood-Red + Helmet (Combat + EVA)
image
image
image

Elite Hardsuit + Helmet (Combat + EVA)
image
image
image
</details>

<details>
<summary>Misc Hardsuits</summary>
<br>

Engineering + Helmet.
image
image
image

Medical + Helmet
image
image
image
</details>

</details>

</details>

<details>
<summary>Oversuits</summary>
<br>

<details>
<summary>Unarmored Oversuits</summary>
<br>

Hospital Gown
image

Surgery Gown
image

Ranger Cloak
image

Radsuit
image

Departmental Jackets
image

RD Labcoat
image

Captain's fem parade coat
image

Captain's parade coat
image

Duster
image
</details>

<details>
<summary>Armored oversuits</summary>
<br>

Basic armor vest
image

Syndicate Captain's vest
image

Void cloak

HoS Trenchcoat
image

Explorer suit + Hood
image
image

Drake Suit + Helmet
image
image

Infiltrator Vest
image
</details>

<details>
<summary>Winter Coats</summary>
<br>

Basic Winter coat + Hood
image
image

Paramedic Winter coat + Hood
image
image

Assistant's formal Winter coat
image

Bartender's Winter coat
image

Security Winter coat
image
</details>

</details>

<details>
<summary>Back items (backpacks, oxygen tanks, etc)</summary>
<br>

<details>
<summary>Back worn items</summary>
<br>

Oxygen tank
image

Oxygen Jetpack
image
</details>

<details>
<summary>Backpacks</summary>
<br>

Basic Grey
image

Explorer pack
image

Captain's pack
image

Security pack
image

Engineering pack
image

Chaplain's pack
image

Grey Duffel
image

Leather Satchel
image

Explorer Satchel
image

Scientist Satchel
image

Basic Grey
image

</details>

</details>

<details>
<summary>Belts and belt slot items</summary>
<br>

<details>
<summary>Belts</summary>
<br>

Toolbelt
image

Medical Belt
image

CE's toolbelt
image

Explorer rig
image

Chest rig
image

</details>

<details>
<summary>Belt slot items</summary>
<br>

Emergency oxygen tank
image

Extended capacity emergency oxygen tank
image

Sabre Sheath. Sword + No sword
image
image

Bandolier
image

Trashbag
image
</details>

</details>

<details>
<summary>Uniforms</summary>
<br>

<details>
<summary>Skirts</summary>
<br>

Fashionable Skirt
image

NT Rep
image

RD Skirtleneck
image

Syndie Skirtleneck
image

Paramedic jumpskirt
image

HoP jumpskirt
image

Engineer jumpskirt
image

Atmos tech jumpskirt
image

Virologist jumpskirt
image

Chemist jumpskirt
image

Medical Doctor jumpskirt
image

Scientist jumpskirt
image

Cargo Tech jumpskirt
image

Wedding dress + Veil
image
image

Maid dress + Apron
image
image

Black skirt
image

Cheongsam Red
image

Sundress Black + White
image
image
</details>

<details>
<summary>Jumpsuits</summary>
<br>

NT Rep
image

HoP
image

Gear Harness
image

(Big thanks to Cypress for the spritework! I just edited it a bit to make it consistent with how the other jumpsuits look)
Engineer
image

Atmos tech
image

Virologist
image

Chemist
image

Medical doctor
image

Scientist
image

Cargo Tech
image

Clown
image

Blood-Red sneaksuit / pajamas
image
</details>

<details>
<summary>Families</summary>
<br>

Morning Star
image
</details>

</details>

<details>
<summary>Gloves and hand worn items</summary>
<br>

Black Gloves
image

Bone Bracers
image
</details>

<details>
<summary>Misc accessories (Head, neck)</summary>
<br>

<details>
<summary>Head items</summary>
<br>

Colored caps
image

Witch Hat
image

Infiltrator Helmet
image

Helmet
image

SWAT Helmet
image

SWAT Syndie
image

Welding helmet up + down
image
image

Bucket
image

Traffic cone
image
</details>

<details>
<summary>Berets</summary>
<br>

Basic beret + badge
image
</details>

<details>
<summary>Neck items</summary>
<br>

Neckerchief.
image

Striped Scarf
image

</details>

</details>

<details>
<summary>Glasses + Eye slot items</summary>
<br>

<details>
<summary>Glasses</summary>
<br>

Sunglasses
image

Thin glasses
image

Gar + Giga gar glasses
image
image
</details>

<details>
<summary>Eye slot items</summary>
<br>

Health Hud
image

Eye patch
image

Welding Goggles up + down
image
image

Optical meson scanner
image

Blindfold
image
</details>

</details>

<details>
<summary>Masks</summary>
<br>

Basic Gas mask
image

Alt Gas mask
image

Explorer mask
image

Joy mask
image

Facehugger
image

Breath mask up + down
image
image

Clown Mask
image
</details>

<details>
<summary>Shoes</summary>
<br>

<details>
<summary>Boots</summary>
<br>

Jackboots
image

Sneakboots
image

Winter Boots
image

Blood-Red Magboots
image

Explorer boots
image

</details>

<details>
<summary>Sneakers</summary>
<br>

Black
image

</details>

<details>
<summary>Misc shoes</summary>
<br>

Blue leg wraps
image

Clown shoes
image
</details>

</details>

## How This Contributes To The Skyrat Roleplay Experience

Having custom sprites are pretty nice.

## Changelog

:cl:
imageadd: Custom Teshari clothing and gear sprites.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
Doing GAGS for these now will save lots of work down the line, like the leg wraps just being wrap base + optional pattern, and the wintercoats especially becoming gags..,,.

**Comment by ghost** [comment]
Also a sprite worth looking into is the surgical apron, it looks like the generic labcoat rn which is kinda.. wrong

**Comment by Ebin-Halcyon** [comment]
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 5 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself.

Shut up, github bot.

**Comment by Ebin-Halcyon** [comment]
Gonna be closing the PR itself while I find someone to actually code in the stuff.
No, this doesn't mean i'm giving up on the project, i'll still be spriting. You'll get your bird sprites.

**Comment by ghost** [comment]
😭

**Comment by Ebin-Halcyon** [comment]
Papelinn is now coding these in. Either i'll add his code to this PR or he'll open his own PR. For now, this is open to show that it's still being actively worked on.

**Comment by Ebin-Halcyon** [comment]
it's here.
#10233

**Pull request closed without merging**
