### PR TITLE
service drake

### PR DESCRIPTION
**Pull request by AnywayFarus**
## About The Pull Request
Adds a service cyborg drake sprite

## How This Contributes To The Skyrat Roleplay Experience
More appearance for cyborgs - more variety.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

https://github.com/Skyrat-SS13/Skyrat-tg/assets/78199449/fdd12cca-b6c0-42ef-91ed-84872b6d98de

</details>

## Changelog

:cl:
add: Service drake cyborg sprite
/:cl:

### CODE REVIEW

**Comment by desertmote** [comment]
It looks like a ninja drake more than it looks service.

**Review by desertmote — CHANGES_REQUESTED** [review]
Please fix the PR example embed and give the drake a distinct service look, so it can't be confused for a ninja model.

**Comment by AnywayFarus** [comment]
> Please fix the PR example embed and give the drake a distinct service look, so it can't be confused for a ninja model.

more white color?
just have vale and it looks quite similar
image

**Comment by desertmote** [comment]
Unfortunately Vale's service is bad too, because of the same reason; though I wasn't there to say something about it at the time it was PR'd.

**Comment by AnywayFarus** [comment]
> Unfortunately Vale's service is bad too, because of the same reason; though I wasn't there to say something about it at the time it was PR'd.

but what about edition, more white color or.. more light green?

**Comment by Zergspower** [comment]
I'd shoot for some white highlights maybe. Though i'm not seeing the whole Ninja angle - you're using the same color pattern as the other borgs not just Vale. Im not sure what the real issue there is from the Ninja POV given they're all black completely with green lights.

Given the trend even the Vale's colors are fine so idk

Other service borgs
image
image
image

Ninjas
image
image
image
image

**Pull request closed without merging**
