### PR TITLE
[NonModular]  Better Random Station Names

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
alternative to #5712
This is an attempt to make roundstart station name generation better. Includes holiday name config introduced in #5712

Station names now generate as:
["NS" (Nanotrasen Space/Science)] + [A Ship Type] [A Name] [Number/Numeral]
An example would be "NS Lab Ingenuity 8"
Vetted the naming strings to produce better, more "High RP" names.

## Why It's Good For The Game
Randomly generated names have charm and fighting over permanent map names is kind of silly.
Removes all the "Low RP" name generation. Old ship types had their bad ones cut. New names are mainly based on existing, real space probe / ship names + a few solar bodies and other spaceshipy names and can probably be filled out with even more names.

## Changelog
:cl: FlamingLily, YakumoChen
config: Added new config flag - HOLIDAYSTATIONNAMES - allows/disallows generating random holiday station names
server: Ship name generation changed to be more consistent and better for RP.
/:cl:

### CODE REVIEW

**Comment by Arctaisia** [comment]
Doesn't align with what the lore team has, at least in draft, for space station names.

**Comment by YakumoChen** [comment]
can you clarify

**Comment by YakumoChen** [comment]
@Arctaisia I took the "T" out of the prefix, based on what you wrote in the other PR, but otherwise it seems to hold up to the same standard you outlined before.

I could just add another prefix chain if you want different roles to make it come out like "Nanotrasen Science Lab Voyager III" or "Nanotrasen Mining Orbital Jupiter Alpha" 

This is pretty much what strings lists are for. They're easy to edit text files.

**Comment by tf-4** [comment]
Good change. This can be adjusted again ~~if~~ _when_ lore comes out, but this is a good stopgap. Current name gen is awful.

**Comment by FlamingLily** [comment]
Y'know

We could do both

It just hit me, I've made sure all my edits are bound to configs, so if we really wanted, we could merge both and just have the configs set to _not_ pre-set names while we wait for lore

**Comment by YakumoChen** [comment]
I considered that, which is why I didn't put that it closes your PR (although I don't like the renamed map files, which is most of the reason for making this PR)

**Comment by Gandalf2k15** [comment]
We'll be fine without it. I'd rather keep the current layout

**Pull request closed without merging**
