### PR TITLE
Removes cloning once and for all 

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

So with recent updates, it's become increasingly more obvious that cloning is redundant and is causing me **a lot** of headaches in terms of upstream compatibility. 

Generally speaking, I don't see cloning used, and if it is used, it's normally by miners. This lack of use and the fact it's also causing a lot of map conflicts makes its remaining value diminish quickly; because of this I've spoken with the rest of the maintainers and the host and we've decided the best course of action is removal. 

This doesn't mean we won't be adding a new system for revival in the future, but for now, this has to go. It's driving me crazy and was not worth the effort porting it in the first place. 

We understand some people may be disappointed by this and we're happy to hear your complaints and reasoning, but in the long run, this IS being removed. If someone wants to develop an alternate solution they can, however for now revival surgery seems to be the best bet, and it does increase medical's RP

Not to mention cloning is actually borked in its current state, not sure why people are angry about its removal. Most people have forgotten about it, but now they realise it's actually gone, they're angry.

## Changelog
:cl:
del: Cloning has been removed.
/:cl:

### CODE REVIEW

**Comment by Swiftfeather** [comment]
>Revival surgery

>No body

smh gandalf you know better

**Comment by Sethnov** [comment]
if only if i knew coding i would make alternative solution

**Comment by SpaceVampire** [comment]
I support this.
Cloning creates the whole "Oh, we can just clone them." thing that ruins all hostage situations even more.
Its also really not that commonly used, most people just do surgery anyway.
At the end of the day, we have respawn enabled, you can just repawn as someone else.

**Comment by Sethnov** [comment]
> I support this.
> Cloning creates the whole "Oh, we can just clone them." thing that ruins all hostage situations even more.
> Its also really not that commonly used, most people just do surgery anyway.
> At the end of the day, we have respawn enabled, you can just repawn as someone else.

depending on the round it may not be wise to respawn, and since operating computers no longer work on stasis beds, i fear tons of dead people with a medical team that is not experienced.

**Comment by CameronWoof** [comment]
Cloning is the backup plan when all else fails in medical. It's very, very good to have. But gibbing is definitely round removal now, which is its own problem for Miners.

Ah well.

**Comment by hugmeorelse** [comment]
> > I support this.
> > Cloning creates the whole "Oh, we can just clone them." thing that ruins all hostage situations even more.
> > Its also really not that commonly used, most people just do surgery anyway.
> > At the end of the day, we have respawn enabled, you can just repawn as someone else.
> 
> depending on the round it may not be wise to respawn, and since operating computers no longer work on stasis beds, i fear tons of dead people with a medical team that is not experienced.

We hope to balance things in medical, so that they're able to cope whenever there are tons of dead people around. However, we don't see cloning used that much, even in situations like that. With that said, we'll see what we can do to mitigate the effects.

**Comment by Swiftfeather** [comment]
Miners on suicide watch

**Comment by hugmeorelse** [comment]
> Miners on suicide watch

TG miners have been handling it just fine for a while now. :)

**Comment by sergeirocks100** [comment]
As a /tg/ regular myself, i would like to disagree.

As much as i didn't like cloning, i admired at how it could bring someone back fully intact, with no original body available, from a brain or a severed head.

Without cloning, with no body available, you have to nab unmonkeys from genetics and put the victim's head or brain on the unmonkey, which is exactly what happens on /tg/.

This, of course, messes with the patient considerably, since they have a all new body with a different appearance, different name if they had to have a brain transplant, and other possible differences from their original body, which, at least as far as i know, all of the xenobiology slimes and potions in the world can't fix fully.

Pod cloning changes the patient's appearance too, by making them a pod person, but they have their original genetics, and they could possibly return the normal with a green slime from xenobiology or some mutation toxin.

I would suggest, instead of eliminating cloning completely, making it so that only severely damaged bodies, such as husked bodies, severed heads, and brains can be accepted by the cloner.

**Comment by Vizoplez** [comment]
You can infact fix /everything/ with xenobio stuff; I've done it as a transformed miner - who got made a cloth golem, I got myself back to my original race by doing the following
-Stabilised green extract, morphing into a lumi slime - then switching myself to have all the parts I wished for, including mutant DNA stuff such as wings, then drank the relevant mutation toxin, turning myself into that race.

But... at the same time.

**As it stands, there is no fast way to repair organ damage except fully replacing every single one of their organs.**

Cloning is essential for long-dead due to the fact organ damage almost always neccessitates cloning if they've been dead for more than 10 minutes. I dont want it gone; but we can take certain steps to just /make it better/, I dont mind a temporary removal for readjustment - but... overall? Its a rather needed feature.

**Comment by Gandalf2k15** [comment]
> As a /tg/ regular myself, i would like to disagree.
> 
> As much as i didn't like cloning, i admired at how it could bring someone back fully intact, with no original body available, from a brain or a severed head.
> 
> Without cloning, with no body available, you have to nab unmonkeys from genetics and put the victim's head or brain on the unmonkey, which is exactly what happens on /tg/.
> 
> This, of course, messes with the patient considerably, since they have a all new body with a different appearance, different name if they had to have a brain transplant, and other possible differences from their original body, which, at least as far as i know, all of the xenobiology slimes and potions in the world can't fix fully.
> 
> Pod cloning changes the patient's appearance too, by making them a pod person, but they have their original genetics, and they could possibly return the normal with a green slime from xenobiology or some mutation toxin.
> 
> I would suggest, instead of eliminating cloning completely, making it so that only severely damaged bodies, such as husked bodies, severed heads, and brains can be accepted by the cloner.

It needs to be reworked from the ground up, I'm not dealing with the shitty conflicts or the bugs that keep occurring, in its current state, it does not work. So I'm removing it. Some talked about a DHF system, some talked about just respawning. Either way, this will be going sooner rather than later.

**Comment by Gandalf2k15** [comment]
> You can infact fix /everything/ with xenobio stuff; I've done it as a transformed miner - who got made a cloth golem, I got myself back to my original race by doing the following
> -Stabilised green extract, morphing into a lumi slime - then switching myself to have all the parts I wished for, including mutant DNA stuff such as wings, then drank the relevant mutation toxin, turning myself into that race.
> 
> But... at the same time.
> 
> **As it stands, there is no fast way to repair organ damage except fully replacing every single one of their organs.**
> 
> Cloning is essential for long-dead due to the fact organ damage almost always neccessitates cloning if they've been dead for more than 10 minutes. I dont want it gone; but we can take certain steps to just /make it better/, I dont mind a temporary removal for readjustment - but... overall? Its a rather needed feature.

I can count the number of rounds I've seen cloning used on two hands, people don't use this at all.

**Comment by Vizoplez** [comment]
> > As a /tg/ regular myself, i would like to disagree.
> > As much as i didn't like cloning, i admired at how it could bring someone back fully intact, with no original body available, from a brain or a severed head.
> > Without cloning, with no body available, you have to nab unmonkeys from genetics and put the victim's head or brain on the unmonkey, which is exactly what happens on /tg/.
> > This, of course, messes with the patient considerably, since they have a all new body with a different appearance, different name if they had to have a brain transplant, and other possible differences from their original body, which, at least as far as i know, all of the xenobiology slimes and potions in the world can't fix fully.
> > Pod cloning changes the patient's appearance too, by making them a pod person, but they have their original genetics, and they could possibly return the normal with a green slime from xenobiology or some mutation toxin.
> > I would suggest, instead of eliminating cloning completely, making it so that only severely damaged bodies, such as husked bodies, severed heads, and brains can be accepted by the cloner.
> 
> It needs to be reworked from the ground up, I'm not dealing with the shitty conflicts or the bugs that keep occurring, in its current state, it does not work. So I'm removing it. Some talked about a DHF system, some talked about just respawning. Either way, this will be going sooner rather than later.

DHF and an altered-carbon style of stacks/laces would be preferable; since a majority of other servers take similar stuff; calling peoples cloned forms 'sleeves' ecetera - and calling the 'cortical stack' (which is what holds the mind datum) an actual stack.

**Comment by Gandalf2k15** [comment]
Just so you know, I brought cloning back https://github.com/Skyrat-SS13/Skyrat-tg/pull/151.

**Comment by Gandalf2k15** [comment]
> > > As a /tg/ regular myself, i would like to disagree.
> > > As much as i didn't like cloning, i admired at how it could bring someone back fully intact, with no original body available, from a brain or a severed head.
> > > Without cloning, with no body available, you have to nab unmonkeys from genetics and put the victim's head or brain on the unmonkey, which is exactly what happens on /tg/.
> > > This, of course, messes with the patient considerably, since they have a all new body with a different appearance, different name if they had to have a brain transplant, and other possible differences from their original body, which, at least as far as i know, all of the xenobiology slimes and potions in the world can't fix fully.
> > > Pod cloning changes the patient's appearance too, by making them a pod person, but they have their original genetics, and they could possibly return the normal with a green slime from xenobiology or some mutation toxin.
> > > I would suggest, instead of eliminating cloning completely, making it so that only severely damaged bodies, such as husked bodies, severed heads, and brains can be accepted by the cloner.
> > 
> > 
> > It needs to be reworked from the ground up, I'm not dealing with the shitty conflicts or the bugs that keep occurring, in its current state, it does not work. So I'm removing it. Some talked about a DHF system, some talked about just respawning. Either way, this will be going sooner rather than later.
> 
> DHF and an altered-carbon style of stacks/laces would be preferable; since a majority of other servers take similar stuff; calling peoples cloned forms 'sleeves' ecetera - and calling the 'cortical stack' (which is what holds the mind datum) an actual stack.

Just need someone to code it.

**Comment by Vizoplez** [comment]
> > You can infact fix /everything/ with xenobio stuff; I've done it as a transformed miner - who got made a cloth golem, I got myself back to my original race by doing the following
> > -Stabilised green extract, morphing into a lumi slime - then switching myself to have all the parts I wished for, including mutant DNA stuff such as wings, then drank the relevant mutation toxin, turning myself into that race.
> > But... at the same time.
> > **As it stands, there is no fast way to repair organ damage except fully replacing every single one of their organs.**
> > Cloning is essential for long-dead due to the fact organ damage almost always neccessitates cloning if they've been dead for more than 10 minutes. I dont want it gone; but we can take certain steps to just /make it better/, I dont mind a temporary removal for readjustment - but... overall? Its a rather needed feature.
> 
> I can count the number of rounds I've seen cloning used on two hands, people don't use this at all.



> > > > As a /tg/ regular myself, i would like to disagree.
> > > > As much as i didn't like cloning, i admired at how it could bring someone back fully intact, with no original body available, from a brain or a severed head.
> > > > Without cloning, with no body available, you have to nab unmonkeys from genetics and put the victim's head or brain on the unmonkey, which is exactly what happens on /tg/.
> > > > This, of course, messes with the patient considerably, since they have a all new body with a different appearance, different name if they had to have a brain transplant, and other possible differences from their original body, which, at least as far as i know, all of the xenobiology slimes and potions in the world can't fix fully.
> > > > Pod cloning changes the patient's appearance too, by making them a pod person, but they have their original genetics, and they could possibly return the normal with a green slime from xenobiology or some mutation toxin.
> > > > I would suggest, instead of eliminating cloning completely, making it so that only severely damaged bodies, such as husked bodies, severed heads, and brains can be accepted by the cloner.
> > > 
> > > 
> > > It needs to be reworked from the ground up, I'm not dealing with the shitty conflicts or the bugs that keep occurring, in its current state, it does not work. So I'm removing it. Some talked about a DHF system, some talked about just respawning. Either way, this will be going sooner rather than later.
> > 
> > 
> > DHF and an altered-carbon style of stacks/laces would be preferable; since a majority of other servers take similar stuff; calling peoples cloned forms 'sleeves' ecetera - and calling the 'cortical stack' (which is what holds the mind datum) an actual stack.
> 
> Just need someone to code it.
https://www.youtube.com/watch?v=-flYz3k0RaQ

**Comment by Gandalf2k15** [comment]
image

When people realise cloning is being removed even though it was never really there.

**Comment by AdventKaori** [comment]
Well.  If it's causing headaches for our coders it's causing headaches for our coders.  I'm still salty about the plumbing changes tho.

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
Just to be awkward and pushy, can you remove the DNA scanners from the maps and rename the doors? It should only take like 5m.
It'll make things less confusing. If people see the cloning room with a DNA scanner but no cloning pod and computer, they're gonna ahelp. And they're gonna do it every single darned round until I get around to repurposing the cloning rooms to something new.

**Comment by Gandalf2k15** [comment]
> Just to be awkward and pushy, can you remove the DNA scanners from the maps and rename the doors? It should only take like 5m.
> It'll make things less confusing. If people see the cloning room with a DNA scanner but no cloning pod and computer, they're gonna ahelp. And they're gonna do it every single darned round until I get around to repurposing the cloning rooms to something new.

yessir of course, i have done as you asked mighty one

**Comment by hugmeorelse** [comment]
> Well. If it's causing headaches for our coders it's causing headaches for our coders. I'm still salty about the plumbing changes tho.

I appreciate your understanding. You have all the right to be salty.

Anyhow, this is something that we had to do, so don't take it out on the coders. If we had half the development staff of TG, this wouldn't be an issue. To get to the point where TG is though, we need to make sure coders don't have to deal with bullshit that they're unable to deal with as of now. 

On the flip side, I do hope it encourages people to be more careful and more considerate of their characters!

**Comment by unit0016** [comment]
In light of recent events in-game, I'm going to state simply: **we need a replacement** for cloning **ASAP**, at least for ghostroles. 'Not being careful' doesn't excuse being roundremoved for being in the wrong place at the wrong time.

**Review by KathrinBailey — APPROVED** [review]
With great sadness we must end the era of cool pods.

Contact CC, we still have cloning there and we use it for parties. 👀

**Comment by hugmeorelse** [comment]
> In light of recent events in-game, I'm going to state simply: **we need a replacement** for cloning **ASAP**, at least for ghostroles. 'Not being careful' doesn't excuse being roundremoved for being in the wrong place at the wrong time.

If you're able to code it or know anyone that can code it, that would be great.

**Pull request merged**
