### PR TITLE
adds (fake) syndicate maid items to the clothesmate & loadout

### PR DESCRIPTION
**Pull request by zeroisthebiggay**
## About The Pull Request

it's good drip and it's a shame that it's nigh impossible to get normally
they're fake and have no positive bonuses over anything that isn't already very easily obtainable

## How This Contributes To The Skyrat Roleplay Experience

drip always improves roleplay

## Proof of Testing

<details>
<summary>i promise that i loaded the dream daemon and checked to see that it all worked</summary>
  
</details>

## Changelog

:cl:
add: fake syndicate maid outfit
add: aforementioned items in loadout/clothesmate
/:cl:

### CODE REVIEW

**Comment by desertmote** [comment]
I don't want to see these on station, and especially not in the loadout menu. Its not "impossible" to get normally, you just play the ghostrole its made for.
Its also a lazy addition. The tacticool/tactical turtlenecks have different sprites, descriptions, and a function to turn them into the real deal.

**Comment by YakumoChen** [comment]
Syndicate clothing should not be easily attainable by crew

The syndicate-appearing tacticool clothes are not in vendors either, nor loadout, and this should continue to be consistent

Items specifically made for syndicate roles should stay available for only syndicate roles.

**Comment by Ebin-Halcyon** [comment]
nty. Syndicate specific.

**Comment by zeroisthebiggay** [comment]
> The syndicate-appearing tacticool clothes are not in vendors either, nor loadout, and this should continue to be consistent

They are. (Unless by 'syndicate-appearing tacticool clothes' you mean the 'real' versions, if so then that's just poor wording.)
https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/code/modules/vending/clothesmate.dm#L167
https://github.com/Skyrat-SS13/Skyrat-tg/blob/master/modular_skyrat/modules/loadouts/loadout_items/under/loadout_datum_under.dm#L464
It probably wouldn't be hard to just move the maid outfit to the contraband selection and just take them out of the loadout`(?) - the tacticool gear is already available in the loadout, I don't see why taking another gimmick item that's supposed to mimic/parody the look of antag gear is so shunned`

If it's 'too similar' to the legitimate variation, wouldn't renaming it to something more 'parody-ish' like `tacticute` solve that issue? It's not like you see these items anywhere near the station, and in essence it's just a black and red maid outfit.
210360613-5ca2e4ef-7760-4e37-a28e-e46dd0e87f86
-not even brandished with anything that'd make it 'syndicate'

>The tacticool/tactical turtlenecks have different sprites, descriptions, and a function to turn them into the real deal.

Tactical turtlenecks are also widely used by `every syndicate antagonist ever`, and Skyrat's iteration of them doesn't seem to even have been added to the uplink ala the original /TG/ PR - the maid outfit was, to my knowledge, added only for one-maybe-few ghost roles as an alternative cosmetic option. I'd sincerely doubt there'd be a massive influx of self-antag/validhunt over a differently colored maid outfit.

**Comment by YakumoChen** [comment]
Not really keen on seeing crew casually walking around in syndicate outfits, which many of them definitely will start doing as soon as this PR becomes known.

**Review by Ebin-Halcyon — CHANGES_REQUESTED** [review]
These were originally sprited and coded in specifically for the Syndicate roles and I don't want them available to the general public without an actual sprite difference between the two.

and with the sprite freeze going on, it'll be closed until I'm finished refitting everything. If no other maintainers have qualms about my decision, I'll be closing this in an hour.

**Pull request closed without merging**
