### PR TITLE
[MODULAR] NiKA and NiKO borg models

### PR DESCRIPTION
**Pull request by W4rd3nn**
## About The Pull Request
Adds two new types of borg models to engineer, miner, cargo, sec, peacekeeper, med, jani, service, syndi, and ninja borg types. One is a feminine/light duty borg, the other is a masculine/heavy duty borg. Sprites courtesy of thedragmeme. Additionally, this temporarily changes the tallborg's opencover overlay (with Halcyon's permission). This will be fixed as soon as it's possible to make borgs have unique opencovers.

## How This Contributes To The Skyrat Roleplay Experience
New customization is always great for silicon players. This fills the niche of a tallborg for both feminine and masculine body types.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

image

image

image

image

image

image

image

</details>

## Changelog

:cl:Motho & TheDragMeme
image: MekaNIKA Heavy Industries has unveiled it's new commercial line-up of cyborg chassis, the NiKA and the NiKO.
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
more robot sex

**Comment by W4rd3nn** [comment]
> 

this is my entry for sex 3

**Comment by HoodMilk** [comment]
These look fresh as fuck, masculine looking meka are very cool.

**Review by Ebin-Halcyon — APPROVED** [review]
Sure.

**Comment by TYWOHKA** [comment]
Oh... Now we have... TOMBOY VERSION OF ALL MEKAS???

**Review by GoldenAlpharex — APPROVED** [review]
These look pretty dope!

**Pull request merged**
