### PR TITLE
[WIP] dragon horns and fat taur sprites - chomp port

### PR DESCRIPTION
**Pull request by Echopsychotic**
done for a friend :p

## About The Pull Request
adds the large dragon horns (colorable) and fat lizard taur (tri-color) so enjoy
taur

done for a friend :p

## How This Contributes To The Skyrat Roleplay Experience
adds more sprites to use if people want them

## Changelog

:cl:
add: Fat lizard taur body changed to allow three different colors
add: Large dragon horns
/:cl:

### CODE REVIEW

**Comment by Arctaisia** [comment]
<3 
I should help port all the other taurs and horns from Virgo some day...

**Comment by thestubborn** [comment]
the fat lizard taur laughed
you are wrong
image

**Comment by GoldenAlpharex** [comment]
Those horns are nice, not sure how I feel about that taur sprite though. Feels kinda weird considering we don't really have "fat" sprites, so it just makes it kinda stand out in a less favorable way.

**Comment by Arctaisia** [comment]
> Those horns are nice, not sure how I feel about that taur sprite though. Feels kinda weird considering we don't really have "fat" sprites, so it just makes it kinda stand out in a less favorable way.

There's quite a few other 'fat taur' sprites on vorecode, would adding those all as options make it seem a little less singled out?

**Comment by Echopsychotic** [comment]
> Those horns are nice, not sure how I feel about that taur sprite though. Feels kinda weird considering we don't really have "fat" sprites, so it just makes it kinda stand out in a less favorable way.

I could begin work on adding the other fat taur models and put this as WIP till a majority is added in. Could also add horns and other sprites as well.

**Comment by GoldenAlpharex** [comment]
> > Those horns are nice, not sure how I feel about that taur sprite though. Feels kinda weird considering we don't really have "fat" sprites, so it just makes it kinda stand out in a less favorable way.
> 
> I could begin work on adding the other fat taur models and put this as WIP till a majority is added in. Could also add horns and other sprites as well.

Not exactly what I meant. You're appending fat sprites to a sprite that can't be fat. It will never look like it makes much sense. If you want to add more horns, go ahead, but I don't have much interest for fat taur sprites.

**Comment by Echopsychotic** [comment]
> Not exactly what I meant. You're appending fat sprites to a sprite that can't be fat. It will never look like it makes much sense. If you want to add more horns, go ahead, but I don't have much interest for fat taur sprites.

I could add a fat stomach for chest markings, not like how hyper has it which is a sex mechanic but I could add the fat sprites to the normal sprites

**Comment by GoldenAlpharex** [comment]
I'm not looking for fat sprites, I don't want to have *another* icon_state for all the worn sprites that we'll have to maintain.

**Comment by softcerv** [comment]
> 
> 
> I'm not looking for fat sprites, I don't want to have _another_ icon_state for all the worn sprites that we'll have to maintain.

I mean, if it's hidden under clothing then would it have to be maintained?

**Comment by Echopsychotic** [comment]
> I'm not looking for fat sprites, I don't want to have _another_ icon_state for all the worn sprites that we'll have to maintain.

adding actual fat sprites to the player model is too much of a pain I learned as there are layers that need to be altered to get them to not clip under the legs. though I think the fat taur models themselves would fit anyways as its just a new taur model and allows for more choice even if the regular sprite also cant look fat.

**Comment by GoldenAlpharex** [comment]
It just doesn't look right with the rest of the body, you don't really have a slim upper body and then just twice the bodymass added in the back for a fatter sprite, which puts it in a very awkward position when it comes to consistency with the rest of the game and its spriting style.

I've discussed with the other maintainers and we agreed that it would be too much maintenance to have this, because just having one doesn't make much sense visually, people will end up wanting to add more things to make it fit more and that's not something any of us has time or interest in maintaining. There's already very little work being put in integrating Taur-friendly sprites as-is, having more taur sprites that don't fit the general shape of the others will mean even more work in that regard, so the odds of more taur-friendly sprites being added as a result is very slim. Because of this, and to avoid more issues in the future with compatibility and consistency, I'll be closing this PR.

That being said, I'm still down for the horns to be added, so feel free to add them in another PR and I don't see any issues in getting those in the game!

**Comment by Arctaisia** [comment]
> It just doesn't look right with the rest of the body, you don't really have a slim upper body and then just twice the bodymass added in the back for a fatter sprite, which puts it in a very awkward position when it comes to consistency with the rest of the game and its spriting style.
> 
> I've discussed with the other maintainers and we agreed that it would be too much maintenance to have this, because just having one doesn't make much sense visually, people will end up wanting to add more things to make it fit more and that's not something any of us has time or interest in maintaining. There's already very little work being put in integrating Taur-friendly sprites as-is, having more taur sprites that don't fit the general shape of the others will mean even more work in that regard, so the odds of more taur-friendly sprites being added as a result is very slim. Because of this, and to avoid more issues in the future with compatibility and consistency, I'll be closing this PR.
> 
> That being said, I'm still down for the horns to be added, so feel free to add them in another PR and I don't see any issues in getting those in the game!

It's just some additional aesthetics and customisation, there shouldn't be much of a problem with it. It might look a little off with the body proportions, but all we'd really need is the fat belly sprites from Hyper to negate that, maybe.

Also, it wasn't just the one taur sprite, he added all 'fat' variants from vorecode. It was still Work In Progress.

I can get it looking a little out of place, but the others are mostly fine, and it's additional customisation, I don't really see what's wrong with more player freedom in expressing their characters. We don't need a hundred taur variant clothing sprites, most people just work with what we got in that regard without much complaining, so that shouldn't be much of a problem. It's not much of a problem, and personally, the scolipede taur looks more out of place due to a higher back. *shrug

I can get it looks like vore, or something, but that shouldn't mean one person can stop all these others from making a character that better suits the character's body.

**Pull request closed without merging**
