### PR TITLE
Voidraptor christmas tree addition

### LINKED ISSUE #17869: Void Raptor doesn't have a christmas tree spawner
## Reproduction:

Somebody just needs to slap down a `/obj/effect/spawner/xmastree` somewhere in a public area that has room for the multi-tile big christmas tree.

You can manually spawn it as `/obj/structure/flora/tree/pine/xmas` if you need to see how big it actually is.

### Proof
Screenshot of find in files listing showing every map but Void Raptor having a christmas tree spawner

### PR DESCRIPTION
**Pull request by LovliestPlant**
## About The Pull Request

This PR adds a christmas tree spawner to Voidraptor at the hallway junction in front of Botany.
fix: #17869 

## How This Contributes To The Skyrat Roleplay Experience

Brings the joy of spessmass to Voidraptor, and brings it in line with the other maps in rotation.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
[Location 1] 

VR_Tree

[Location 2]

VR_Tree2

[Location 3]

VR_Tree3

[Location 4]

VR_Tree5

</details>

## Changelog

:cl:
fix: [Voidraptor] Resolves the missing christmas tree. Have a merry Spessmass and a happy new year!
/:cl:

### CODE REVIEW

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
Make it accessible. Rail hopping is not accessible.

**Comment by LovliestPlant** [comment]
How would something like this look?

VR_Tree2

**Comment by Jolly-66** [comment]
That is still not a suitable location.

**Comment by LovliestPlant** [comment]
The last decent spot I can find would be the evac cafe:

VR_Tree3

**Review by Jolly-66 — DISMISSED** [review]
I'm still not pleased with where you keep placing the tree.

Originally, it was fine. All you had to do was make it accessible, instead of gated/locked in.

**Comment by LovliestPlant** [comment]
Oh. Well, back to the start with a bit of railing surgery. How's something like this work?

VR_Tree5

[edit: replaced the photo with the corrected siding decal]

**Review by Tastyfish — APPROVED** [review]
Jolly told me he was fine with that solution. We need a Christmas tree in by tomorrow in my opinion so approving.

**Pull request merged**
