### PR TITLE
[MODULAR] Resprites skyrat's modular cargo

### PR DESCRIPTION
**Pull request by Draganfrukts**
## About The Pull Request

Time to replace these dinky-ass old sprites from 2019 with something a little fresher.

## How This Contributes To The Skyrat Roleplay Experience

It makes the artstyle consistent (Made with [TG PR #66570](https://github.com/tgstation/tgstation/pull/66570) in mind) and they just look good in general.

## Changelog

:cl:
imageadd: Resprited (almost) all of Skyrat's modular cargo clothes!
imageadd: Quartermaster and Cargo skirtlenecks!
qol: Added spriting resources to modular cargo file intended for those looking to add even more
spellcheck: Tidied up some cargo clothing descriptions
fix: Cargo clothes that previously showed up in loadout and don't anymore, DO again.
/:cl:

## Sprites - Credits

Imaginos - 3.0 Jumpsuits (Base)
Halcyon - Funky turtleneck stuff and pockets for the pants

## Sprites - Showcase

image

### CODE REVIEW

**Comment by Draganfrukts** [comment]
opened as draft because i forgot digitigrade existed. whoops.

**Comment by Draganfrukts** [comment]
Remind me tomorrow to add sprite pictures it's almost 4 AM

**Comment by theselfish** [comment]
Here was me hoping the Scarface suit would count as Cargo.

**Comment by Draganfrukts** [comment]
Speedmerge this and #13214 thanks

**Comment by Ebin-Halcyon** [comment]
🙏

**Comment by Draganfrukts** [comment]
pr also lacking fix and spellcheck tags :[

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
Looks good, but aren't you missing, like, a good handful of digi sprites for these?

**Review by GoldenAlpharex — APPROVED** [review]
I'm trusting you on this one, and I'd appreciate if it didn't take 1+ week to get those digi sprites in. Thanks!

**Pull request merged**
