### PR TITLE
[MODULAR][REMOVAL] Removes Stasis Pods

### PR DESCRIPTION
**Pull request by softcerv**
## About The Pull Request
Removes stasis pods from the techweb, replacing them with stasis tables. stasis body bags are still being kept in. All instances of stasis pods in maps have been replaced with standard stasis tables.

## How This Contributes To The Skyrat Roleplay Experience
Stasis pods have become redundant in our current medical system considering that surgery tables now have inbuilt stasis on them. Even without stasis surgery tables, they end up making situations more difficult for medbay in a non-engaging way, especially when medbay has to deal with plasmamen or any other scenario that requires work while on stasis. They also have a negative side affect unintentionally hiding bodies away, leading to them being soft round removed in many cases.

Along with gameplay issues, keeping stasis pods in the game adds another factor that we need to deal with when managing map resets.

## Changelog

:cl: softcerv, GuiltyNeko
del: removes stasis pods from techweb and maps
/:cl:

### CODE REVIEW

**Comment by Lizzzard26** [comment]
Are you serious? You wrote that pods "easily remove" players from the eyes of medics, but that's far from it. Even beginners are able to detect the presence of a patient in the pod. Besides, the point of pods is to hide a dead body from outsiders (those who are not medbay staff), so that no one can see a rotting corpse with its guts out, some limbs missing and eyes gouged out. Do you think it's normal to have a dead body storage area right in the Medbay lobby? I almost forgot to tell you that the doctors will operate on patients right there, without reaching the surgery (it's already passed experience, when there were no pods in the Medbay, only surgical tables in the lobby). Do not forget that this server with the RP component and put the corpses on public display is not consistent with the rules.

POV: *Walk into a medbay for headache pills.
4 corpses right in the lobby: Hi, you ok?

**Comment by hugmeorelse** [comment]
> Are you serious? You wrote that pods "easily remove" players from the eyes of medics, but that's far from it. Even beginners are able to detect the presence of a patient in the pod. Besides, the point of pods is to hide a dead body from outsiders (those who are not medbay staff), so that no one can see a rotting corpse with its guts out, some limbs missing and eyes gouged out. Do you think it's normal to have a dead body storage area right in the Medbay lobby? I almost forgot to tell you that the doctors will operate on patients right there, without reaching the surgery (it's already passed experience, when there were no pods in the Medbay, only surgical tables in the lobby). Do not forget that this server with the RP component and put the corpses on public display is not consistent with the rules.
> 
> POV: *Walk into a medbay for headache pills. 4 corpses right in the lobby: Hi, you ok?

I am going to kindly ask you to tone it down. Please change your post accordingly, otherwise it will be hidden. You can say all of this without the harsh tonality. This is not Discord. This is Github.

**Comment by softcerv** [comment]
> Are you serious? You wrote that pods "easily remove" players from the eyes of medics, but that's far from it. Even beginners are able to detect the presence of a patient in the pod. Besides, the point of pods is to hide a dead body from outsiders (those who are not medbay staff), so that no one can see a rotting corpse with its guts out, some limbs missing and eyes gouged out. Do you think it's normal to have a dead body storage area right in the Medbay lobby? I almost forgot to tell you that the doctors will operate on patients right there, without reaching the surgery (it's already passed experience, when there were no pods in the Medbay, only surgical tables in the lobby). Do not forget that this server with the RP component and put the corpses on public display is not consistent with the rules.
> 
> POV: *Walk into a medbay for headache pills. 4 corpses right in the lobby: Hi, you ok?

I can understand where you are coming from with your concerns, however, in most cases where medical has a backlog of bodies, it is important that those bodies are easily visible to medbay staff so that they can quickly understand what work needs to be done. I don't think I have ever heard of or experienced anyone getting in trouble with admins for leaving bodies out, it's sort of the way that medbay normally works.

There are still a good amount of options if you want to hide bodies, stasis body bags are still being kept in, which function identically to the pods.

**Review by Gandalf2k15 — APPROVED** [review]
ok

**Comment by Gandalf2k15** [comment]
P.s these are never gonna be in maps anyway lol.

**Pull request merged**
