### PR TITLE
Project: Interdyne

### PR DESCRIPTION
**Pull request by burgerenergy**
## About The Pull Request

Just a WIP draft for now, but; this is a project to modernize Interdyne and bring it up to speed with the policy of them being a separate entity away from DS-2, as well as tidying up DS-2 to make that happen as necessary. Any bugs I fix along the way is just aces.

This PR will consist of some backend stuff as I refactor Interdyne off of being lifted from TG's Lavaland people, a few new sprites, and map updates both to DS-2 as well as a full new Interdyne facility with Lava/Ice versions as, unfortunately, required.

A rough checklist so far;

- [X] Refactor Interdyne's spawnrole
- [ ] Interdyne gets their own, non-Syndie/chameleon trim
- [X] Interdyne ID gets some QoL access, namely robotics and ORM access.
- [X] Interdyne loses their backpack stowable fucking antimaterial sniper rifles. (The makarovs stay, though)
- [ ] Interdyne gets a new map for 10~ players, two versions
- [ ] Interdyne-Lavaland gets a shuttle/white-ship that can travel both to DS-2 and to station
- [X] Interdyne gets a motherfucking stamp, courtesy of Dee.
- [x] DS-2 moved off Interdyne net, using the conveniently unused Cybersun net. (Including sleeper call outs.)
- [ ] figure out why cybersun is called uplink in game
- [ ] Remove quantum teleporter from DS-2 map
- [ ] Add a Bluespace Miner to DS-2, so they do not _require_ Interdyne to be staffed to function
- [ ] Remove the Syndie miner spawners, ideally replace them if space permits.
- [ ] Remove skyrat edits if requested
- [ ] maaaaybe adjust DS-2's armory while I'm here

large_stamp-interdyne

## How This Contributes To The Skyrat Roleplay Experience

Interdyne was in a weird place in the past. Attached to DS-2, but stuck largely on a TG ruin's code and not given much in the way of features. Now that they're separate that needs to change, which includes getting them a new map - as much as I love the aesthetic.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
refactor: Interdyne spawners refactored
add: Interdyne receives a whole new map and shuttle
balance: DS-2's quantum pad and miner roles removed, replaced with bluespace miner
image: Sprites for Interdyne; stamp and ID trims.
/:cl:

### CODE REVIEW

**Comment by CandleJaxx** [comment]
a suggestion balance-wise, if you're tapping into ds-2's armory aswell, i suggest either replacing the sol pistols they got recent w/ makarovs, or giving interdyne the sol pistols too, as interdyne getting the funny syndie pistol, and ds-2 not, is a little odd

**Comment by ChickyRooster** [comment]
While I understand the want to change DS-2's frequency away from Interdyne, perhaps having just the Deck officer have access to the DS-2 channels would work better instead of a complete removal?

**Comment by CandleJaxx** [comment]
also do keep in mind the interdyne deck officer has syndie bridge / security access, so that will need to be removed aswell

**Comment by burgerenergy** [comment]
> While I understand the want to change DS-2's frequency away from Interdyne, perhaps having just the Deck officer have access to the DS-2 channels would work better instead of a complete removal?

While I understand trying to keep them in some contact, I don't want the leadership of either to be able to snark on the other sides' comms; The DO/admin/whatever-I-settle-on also being _potentially_ hostile to the Syndicate, or at least not policy-guaranteed to chums, also means that can't fly, and I'm not having the admiral or maybe more appropriately the liaison stew on the reverse, either.

However! I plan on solving this by simply giving Interdyne a fax machine. The tricky issue is evidently a fax machine that can see and contact DS-2's Syndie one while also being visible to the station, but I am kicking the can down the road when I get to it. Keeping them in some form of contact is still the intention, just not direct peanut gallery radio contact.

**Comment by W4rd3nn** [comment]
put shipping containers in >:)

**Comment by KathrinBailey** [comment]
**fair warning**
do not make the new interdyne map any larger than it is currently, it is massively over-inflated with junk and could easily be made half the size.
lavaland has limited space on it and we're already eating a huge amount of it with TG's mining base and the Skyrat supersized ashwalker area.

**Pull request closed without merging**
