### PR TITLE
remove fungal mold from mold event

### PR DESCRIPTION
**Pull request by jjpark-kb**
## About The Pull Request
title.

## How This Contributes To The Skyrat Roleplay Experience
host request.

## Changelog

:cl:
del: removed fungal mold from event spawning
/:cl:

### CODE REVIEW

**Comment by ReynTheLord** [comment]
Fungal mould has been a MASSIVE pain to deal with, alongside some other mould types. this one though is just infuriating as it just essentially gives the station a highly contagious, highly deadly, disease, not even player controlled, by merit of existing.

At least sentient disease is fun and virology diseases require players to make them.

**Comment by restlessObserver** [comment]
So you removing it because its hard to deal with.
No offense but But I see the behavior of a little pussy here. Because something hard to deal with doesn't mean you need to delete it. Its literally skill issue of someone with not enough speed and knowledge.

**Comment by softcerv** [comment]
> So you removing it because its hard to deal with. No offense but But I see the behavior of a little pussy here. Because something hard to deal with doesn't mean you need to delete it. Its literally skill issue of someone with not enough speed and knowledge.

Yes. if something is difficult that it causes issues for 90% of the playerbase, then it is something that should be removed or balanced. Please try and be constructive here instead of hurling insults at people, GitHub really isn't the place for this.

**Comment by hugmeorelse** [comment]
If you're going to be toxic, we will just block and move on. Github is not a place for this as @softcerv said.

**Pull request merged**
