### PR TITLE
Re-adds missing Arrivals ERT Docks

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
(ALL IMAGES ARE SLIGHTLY OUTDATED)
These got removed in the last map reset, so ERT ships now crash spectacularly into arrivals :)

This adds back the ones we had, with several improvements both visually, design-wise, and functionally (such as Tram's one actually fitting the ERT ship now)

<details><summary>
Delta (unchanged from pre-reset)</summary>

image

</details>

<details><summary>
Meta (added separated room for Auxiliary dock, and doors) (I had to remove my favorite personally-added easter egg for this remap curse you)</summary>

image

</details>

<details><summary>
Tram (shuttle actually fits now (as marked), more pretty, separated Auxiliary dock</summary>

image

</details>

<details><summary>
Ice (actual unique LZ instead of just landing in the snow, smoking area)</summary>

image

</details>

I also have a file full of templates for these and the coordinates to copy-paste them that I'll hand off whenever someone needs them - its a bit messy right now though so im not adding it into our map files for everyone to see

## How This Contributes To The Skyrat Roleplay Experience
Why does our ERT think that spacing arrivals is okay

## Changelog

:cl:
fix: Nanotrasen has found the time and money to re-fit their ERT docks onto arrivals. Now their response teams wont have to ram through the glass walkways just to land!
/:cl:

### CODE REVIEW

**Review by Jolly-66 — COMMENTED** [review]
Very nice altogether. Just hit lints for that duped wire.

Just wanna comment a few things I had originally done before the rude awakening.
Do you mind if you can add fluff blast-doors to the bays with force fields? They don't need buttons or anything to be toggled (or add them, its just fluff in the end).

Also Tram is missing airlocks going into the hanger, could you add those please?

**Comment by ghost** [comment]
> 

was actually thinking about the blast doors already, I guess this is just more the reason

**Review by Jolly-66 — COMMENTED** [review]
It seems you accidentally removed some grills on Delta. Use MDBs rendered images to see exactly where, if my images aren't too helpful.
<details>
<summary>Delta</summary>
West of northern solars here:

image

Over here near cryopods:

image

</details>

I also can't tell if it was intentional, or if its just MDB, but you're missing your decal work from the landing zone on Ice Box. Same with Meta.

**Review by Jolly-66 — CHANGES_REQUESTED** [review]
Also, in some of the bays, please separate out the vents/scrubbers more. They shouldn't be on top of each other. I would recommend four vents (2 distro/waste) for the bays each due to them being bigger than average rooms. Also please add air alarms to the bays.
<details>
<summary>Meta</summary>

The bottom dock could be touched too, but its small enough where it doesn't bother me too much. You may want to fluff it up a bit outside the vents, however.

image
</details>

<details>
<summary>Tram</summary>

Please also ensure there is an **accessible** fire alarm in the bay. The one current is in the hall, not the bay.

image
</details>

Nit pick but please add vents here, and round off the warning tapes with corners please.

<details>
<summary>Ice Box</summary>

image
</details>

Sorry for this double whammy. These are just somethings that bothers me.


EDIT: Second do-over of the images. You don't need an APC for the bay, unless you're redefining the area. Unlike air alarms, you only need **one** per area.

**Comment by ghost** [comment]
> 

Delta is a manual mirror of https://github.com/tgstation/tgstation/pull/67408, so disposals actually leaves the station, and the grille by Cryo was to clean up a second map 'flightpath' (Security's old sofa being thrown out their airlock - the way it was remapped with cryo would have either blocked the sofa or let it drift further away, this was solely so something we already added blended a bit nicer)

**Comment by ghost** [comment]
> 

I'll fix the vents, yea
They shouldddd have air alarms but I'll double check - also, I think that that APC _is_ the one APC, or supposed to be; i'll clean it up regardless

Also its super annoying bc TG mapped icebox without the rounded corner decals (if you look at the north arrivals which is unchanged, you see that) so I was doing it for consistency
Trust me, I hate it too, but remapping ALL of arrivals wasnt the goal, its meant to just paste cleanly in

**Comment by ghost** [comment]
And its intentional, ~~Meta~~ and Icebox arent meant to have the decals, only Tram because the tram bay only barely fits it so it makes sense to have it clearly marked where it goes; ice one looks gross being so bright over snow, ~~and meta is able to fit it well enough that the decals feel redundant~~
Looking closer, meta might actually need those decals, or at least a bit of tweaking, whoops

**Comment by Jolly-66** [comment]
If the trims for the snow didn't look good, try opting for other trims (look at what I did for cryo)

It sucks we don't have anything for outside terrain in general, asethetically speaking, since Box has received a lot of updates within the last 6 months. Just gotta work with what we have.

**Comment by ghost** [comment]
<details><summary>META</summary>

image
</details>

<details><summary>TRAM</summary>

image
</details>

<details><summary>DELTA</summary>

image

</details>

<details><summary>ICE</summary>

image

</details>

**Review by Jolly-66 — APPROVED** [review]
Mapping LGTM.

Can't circumvent the Box tile aesthetic because of a lack of mapping fluff.

Orion won't be able to test this until tomorrow so I'll pull this locally to my machine whenever I get the time later today.

**Review by Jolly-66 — COMMENTED** [review]
Curse me not having commit access.
Few minor things I think we can fix later.

<details>
<summary>Box</summary>

Wrong plating type.
image

Big ass intercom dead zone.
image

Also the plushie hidden outside needs a grammar check.

</details>

<details>
<summary>Meta</summary>

The bay needs to be extended/the ferry needs to be dropped. This is inaccessible to move in.
image

Intercom dead zone.
image

Metas bay is still missing: an air alarm.

</details>


<details>
<summary>Tram</summary>

Same issue here with the ferry blocking stuff.
image

Camera blind spots.
image

More intercom dead zones.
image

Trams bay is still missing: accessible fire alarm buttons, and an air alarm.

</details>

Delta is omitted because it was a retrofit, and shouldn't need any attention.

Maps were tested, and the ferrys dock fine.

**Comment by ghost** [comment]
> 

most of these are just scooting stuff about, I'll fix it before this is sound to merge

**Comment by ghost** [comment]
> 

most of these are just scooting stuff about, I'll fix it before this is sound to merge

**Comment by ghost** [comment]
i sure love it autoclosing because i reset it to master to fix conflicts 😎

**Comment by Zonespace27** [comment]
😎 based

**Comment by ghost** [comment]
okay the commit should be in any minute now

**Comment by ghost** [comment]
what
NO

**Comment by ghost** [comment]
NO!!!

**Comment by ghost** [comment]
HOW IS IT CONFLICTING I UPDATED THEM

**Comment by ghost** [comment]
I HATE YOU .DMM!!!

**Comment by Gandalf2k15** [comment]
Ffixc congicts

**Comment by ghost** [comment]
and VOILA

**Pull request merged**
