### PR TITLE
[SEMI-MODULAR][WIP] Adds TowerStation

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Adds TowerStation to the game. 

Still needs lots of optimisation so it doesn't hit 75% TD 10 minutes in

YES I removed mining for performance, might re-add it later if I can get performance good enough

All z-levels, bottom to top. The ground floor is shown in full here, all other levels cropped to the station area as the rest of them is basically just rock.
Z1
z2
z3
z4
z5
z6
z7
z8
z9

## Why It's Good For The Game

New maps are fun

## Changelog
:cl:
add: NT have authorised a new station to be built, and they wanted something with a view. TowerStation is now available. 
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/4695

**Comment by zeratino** [comment]
LETS
FUCKING
GOOOOOOOOOOOOOO

**Comment by tf-4** [comment]
This is still looking for another test round btw.
Mining is currently _disabled_ for performance testing, though probably will be added back as I don't think it will have that much impact.

**Comment by tf-4** [comment]
> 
> 
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 7 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

maybe if I got a bitch ass test merge and feedback then it wouldn't be stale, would it punk

> you may wish to close this PR youself

stupid ass bot can't even spell yourself

**Comment by tf-4** [comment]
Closing until I have more time to work on this and sort it out properly.

**Pull request closed without merging**
