### PR TITLE
[MIRROR] Refactors tile reskinning

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/54233
--------------------

## About The Pull Request

Refactored the tile reskinning and associated code to offer more generic and expansible behavior.

* Variant floors now produce the proper variant item stack when crowbared.
* Removes `icon_regular_floor` and associated old code, replacing it with a more standard use of `base_icon_state`.
* Renames the icon states to something more informative.
* Replaces the `human_maxHealth` var for a define.

## Why It's Good For The Game

@ KathrinBailey wants to expand on this feature, so to avoid repeated code a more generic approach is positive.

dreamseeker_ZVCgi7UxrP

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Do not merge. Manual icon override required.

**Comment by Gandalf2k15** [comment]
Do not merge. Manual icon override required.

**Comment by Azarak** [comment]
> 
> 
> Do not merge. Manual icon override required.

What do you mean? This updates the icons just like the parent PR

**Comment by Gandalf2k15** [comment]
The modular override, I'll deal with it soon

**Pull request merged**
