### PR TITLE
[MIRROR] [TEST-MERGE FIRST] Allows all limbs to be dismembered and significantly refactors wounds [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/77813
--------------------
## About The Pull Request
**_THIS PR UPDATES THE SCAR VERSION - ALL EXISTING SCARS WILL BE WIPED_**

Expands the wound system functionality to support any type of limb at all.

To do this, wounds have been significantly refactored. For starters, wounds now use limb biotype instead of wound type for determining what they can be applied to. They also use singleton instances for most "can we apply this" checks instead if copy pasted initial(). 

Wounds now use a "wound series" instead of wound_type for determining the, well, series. Previously, all WOUND_BLUNT wounds were considered bone wounds, making it impossible to have multiple WOUND_BLUNT wounds at once. Now, its based on wound series - bone wounds are of the blunt bone wound series, and use the typical logic. 
One change that results from this is the ability for everything with a jointed limb to get a dislocation. Yes, this includes things like prosthetics.

On the note of external and internal biotypes: Exterior are bones, Interior is flesh. Interior protects exterior from slash until its mangled, at which point it either exposes exterior to slash or allows dismemberment if theres no exterior.
Basically - it acts the exact same way, except its not hardcoded, and its more modular.

A lot, lot more changes were made - I cant name them all, but if youre interested, you can read up. Wounds have more procs, more modularization, and less hardcoding.

Sadly, scars have been updated in such a way so that the wound version must be updated. Scars will be deleted.

## Why It's Good For The Game

As it stands, half the limbs in the game can't be dismembered. This changes that, allowing every single limb to be dismembered.

The two dismemberment critera are now:

1. If able to get mangled flesh or bone, it can be dismembered once it gets mangled flesh and bone (or JUST flesh if it only has a internal biostate, vice vers afor bone if external only)
2. If it cant be dismembered by the above, it will have a chance to dismember when at or above 80% of its total max damage

Finally, code being better is usually a good thing.

## Changelog
:cl:
balance: Prosthetics and slimepeople can now have limbs dismembered
balance: Slimepeople can now receive slash wounds, but cannot bleed
balance: Most limbs can now be dislocated
refactor: Scar backend reworked, scars will be wiped as they update to the new format
/:cl:

NOTE: https://github.com/Skyrat-SS13/Skyrat-tg/pull/23408 included

### CODE REVIEW

**Comment by nikothedude** [comment]
DO NOT MERGE THIS UNTIL IM DONE WITH IT

**Comment by nikothedude** [comment]
https://github.com/Skyrat-SS13/Skyrat-tg/pull/23408

**Comment by nikothedude** [comment]
#23408 is now ready to be merged but i suggest this is TMed for a round or two

**Comment by vinylspiders** [comment]
> #23408 is now ready to be merged but i suggest this is TMed for a round or two

https://github.com/Skyrat-SS13/Skyrat-tg/pull/23408 is now merged with this. Should be ready for testmerge now.

**Review by GoldenAlpharex — APPROVED** [review]
It works.

**Pull request merged**
