### PR TITLE
[MIRROR] Updates the Syndicate revolver into a new revolver (with the same stats) [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/71704
--------------------
## About The Pull Request
Makes the syndicate revolver a subtype of the normal revolver and gives it its own sprite, name (S-357) and a new uplink description. 
Pics: 
image
image

Before:
image
## Why It's Good For The Game
Currently the revolver is a bland, generic, brown gun that doesn't look like a sci-fi revolver. Now it has a cleaner, more unique design that fits into the setting and into the Syndicate standard of high tech ballistics.

Changing the uplink description gives players a clearer idea of what they are buying.

Moving the Syndicate .357 from the base of all revolvers into its own entry allows for future changes on the Syndicate revolver to not impact every single revolver in the game.

## Changelog
:cl:
add: The Syndicate uplink revolver has been changed from the default .357 to the S-357. It has the same stats and price as the old version but with a new sprite.
qol: Adds a better explanation on the .357 uplink entry so players have an better understanding of what they are buying.
/:cl:

### CODE REVIEW

**Comment by Krypandenej** [comment]
Why not give keep the old version as a skin, for the inevitable space cowboy? Plus, gatfruit may need an updated look assuming the two revolvers are the same.

**Comment by Paxilmaniac** [comment]
> Why not give keep the old version as a skin, for the inevitable space cowboy? Plus, gatfruit may need an updated look assuming the two revolvers are the same.

Gatfruit does not need any changing because it'll be the exact same, literally all this does is separate the syndie revolver out as its own revolver type and changes the uplink one to that.

**Comment by ghost** [comment]
As was said, the main perk of this is properly splitting the revolver to be an explicitly syndie variant

And dont be concerned about the sprite, TG already looked to be wanting to change it 🙏  It'll likely just be a darker version of a generic revolver

**Comment by Zonespace27** [comment]
this got reverted already lol

**Pull request closed without merging**
