### PR TITLE
fixes the arborlink vault floor until we get these catwalks in check.

### PR DESCRIPTION
**Pull request by capsaicinz**
## About The Pull Request

god i hate these new catwalks so much i hate them i hate them. replaces the arborlink vault catwalks with tile.

## Why It's Good For The Game

it'll get promptly reverted as soon as our ACTUAL catwalks come back. god i hate this.

## Changelog
:cl:
fix: replaced arborlink vault broken catwalks with tiles. also removed any trace of air tanks because apparently those are fucked.
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
they are 'back', they're just broken. They're subtypes of the catwalk plating.

**Comment by capsaicinz** [comment]
> they are 'back', they're just broken. They're subtypes of the catwalk plating.

have they fixed it since i sent this out? i know they did all sorts of funky stuff to the catwalks, but the original problem i was fixing was the catwalks not existing at all, since the original ones we used were just yoinked from my ruin because the paths were invalid, i guess?

**Comment by unit0016** [comment]
> > they are 'back', they're just broken. They're subtypes of the catwalk plating.
> 
> have they fixed it since i sent this out? i know they did all sorts of funky stuff to the catwalks, but the original problem i was fixing was the catwalks not existing at all, since the original ones we used were just yoinked from my ruin because the paths were invalid, i guess?

I brought the catwalks back, though they're still uh. Problematic in-game.
Pipes and cables appear above them, the dark ones aren't. Dark, etc

**Comment by capsaicinz** [comment]
> > > they are 'back', they're just broken. They're subtypes of the catwalk plating.
> > 
> > 
> > have they fixed it since i sent this out? i know they did all sorts of funky stuff to the catwalks, but the original problem i was fixing was the catwalks not existing at all, since the original ones we used were just yoinked from my ruin because the paths were invalid, i guess?
> 
> I brought the catwalks back, though they're still uh. Problematic in-game.
> Pipes and cables appear above them, the dark ones aren't. Dark, etc

gahaha, yeah, that's what i was thinking. my original idea was to just quickly get this merged, and just cover up where the catwalks _were_ in my space ruin with fancy tiles, since that works just as well. though, apparently, catwalks just might get fixed by the time this gets merged!

i did not take into account that this would be taking this long

**Pull request merged**
