### PR TITLE
[Semi-Modular] [Not ready] Ports oldbase vore system

### PR DESCRIPTION
**Pull request by Swiftfeather**
## About The Pull Request

The goal of this PR is to get vore added to the server. I have absolutely no idea what I'm doing so I'm putting up a draft PR for interested parties to assist in getting this added.

A lot of this is poojcode, credit to oldbase skyrat, which was a fork of citadel, which was a fork of tgstation

## Why It's Good For The Game

Vore is more hrp than traitors.

## TO DO

- Fix the rest of the errors
- Test
- Fix issues from testing
- Dogborg sleepers 
- Tie being able to see belly bulges and stuff to preferences so the angry normies don't have their poor, innocent souls harmed

## Changelog
:cl:
add: Vore
/:cl:

### CODE REVIEW

**Comment by Swiftfeather** [comment]
I'm currently in need of assistance changing code to fit tg, including the new combat mode indicators, the human.dm errors, screen_objects errors, and proc issues

**Comment by Arctaisia** [comment]
Just needs a bit of time and fixing, and this'll be back, then we can finally have a reason for most of the unironically better RPers to come back :petpet:

**Comment by Swiftfeather** [comment]
I need people more experienced with tg code, more specifically the differences between cit and tg code to help make certain things fit the new codebase

**Comment by Arctaisia** [comment]
I'd probably suggest Azarack or Cobalt, but Azzy probably can't help as they're on their break doing their own projects

**Comment by Echopsychotic** [comment]
While I wish it was the new vore code, I doubt this will bring a lot of them back. Some found other and of course dedicated vore servers that people don't shit on them for their kink. 

That being said if it is added and done well, I hope it does bring some people back as I know the addition of size code will also bring people back.

**Comment by Arctaisia** [comment]
> While I wish it was the new vore code, I doubt this will bring a lot of them back. Some found other and of course dedicated vore servers that people don't shit on them for their kink.
> 
> That being said if it is added and done well, I hope it does bring some people back as I know the addition of size code will also bring people back.

Yee! More people to smuggle to those vore servers- Pff.

**Comment by Draganfrukts** [comment]
I'm strongly against this purely for code and performance reasons, unless you can rectify Pooj's extreme shitcode

**Comment by SpaceVampire** [comment]
> I'm strongly against this purely for code and performance reasons, unless you can rectify Pooj's extreme shitcode

I second this. The server is already having a lot of performance issues, and if this code is going to make that worse I really don't think that fucking over its ability to function over a minority fetish is the correct way forward.

**Comment by Gandalf2k15** [comment]
Hey hey. Can you atmoise this?

**Comment by Swiftfeather** [comment]
Okay, after a lot of fucking around with this I have determined while vore would be a good thing for our server, old citcode vore is not the way to go.

- If vore is going to be ported, the effort is better spent porting vore station code, since it'll probably take the same amount of effort for a better result

**Pull request closed without merging**
