### PR TITLE
[MIRROR] splits space adaptation into two mutations [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/62764
--------------------

## About The Pull Request

splits space adaptation into two different mutations:
pressure adaptation, which is the old effect of low pressure immunity and also **high pressure immunity**
temperature adaptation, which is the old effect of low temperature immunity and also **high temperature immunity**
these 2 mutations have had their instability cost dropped to 25 and are **incompatible with each other**

## Why It's Good For The Game

gives you a choice between protecting yourself against the harder hitting, but easier to deal with pressure, and easier hitting, but harder to deal with temperature
lets crew prepare against hot temperatures, which could make genetics an interesting target point for atmos techs/ais
you can no longer just get a single mutation and not care about anything else for spacewalking, you have to prepare at least a bit to secure yourself against the other type of damage from space, or take damage
more genetics content :D

## Changelog

:cl:
balance: space adaptation has been split into two mutations. pressure adaptation giving you full immunity to pressure and temperature adaptation giving you full immunity to temperature. these are not compatible with each other.
/:cl:

### CODE REVIEW

**Review by GoldenAlpharex — APPROVED** [review]
*Grumbles grumbles spans not using the macros grumbles grumbles*

**Comment by Iamgoofball** [comment]
there's an issue with genetics text and the span macros apparently

**Comment by ORCACommander** [comment]
space adapt was locked by skyrat as a balance change. apart from making this code work, it will probly want a balance review

**Comment by Iamgoofball** [comment]
This solves the big issue with space adapt, which was spacesuit nullification for absolutely no upkeep or maintain cost.

**Comment by softcerv** [comment]
> 
> 
> space adapt was locked by skyrat as a balance change. apart from making this code work, it will probly want a balance review

This solves most of the issues that people brought up with it in the removal PR

**Comment by GoldenAlpharex** [comment]
I'm personally fine with giving this a go, we can always disable them later if they appear to be a problem.

**Pull request merged**
