### PR TITLE
Adds a non-synthliz/IPC robotic mammal and HUMAN species

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

This adds two new species for those that wish to make themselves synthetics, but not be a lizard or IPC. It allows all types of mammal bodyparts, uses the mammal bodypart as a base and has all synthetic internal organs. Basically, it's works like a synthliz does but you're a synthfox.

I might add new wounds to synthetic bodyparts and allow synthetic "Bleeding" e.g. losing hydraulic fluid and squirting it everywhere.

## Changelog
:cl:
add: Adds a new synthetic species, the synthetic mammal, meaning you can now have synthetic species that aren't just mutated synthliz's.
add: Adds a new synthetic human species, acts like an IPC but looks like a human.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
Where are the pictures dave

**Comment by KasparoVy** [comment]
HEEEELL yeah. Bless you

Would it be possible to allow synthliz to choose 'spines' like the regular lizardpeople can, and to allow the selection of facial hair so they can choose the horns/frills, eg. Horn Adorns? Those two are the only things I wager are missing from that base, otherwise this is fantastic

**Comment by Gandalf2k15** [comment]
> HEEEELL yeah. Bless you
> 
> Would it be possible to allow synthliz to choose 'spines' like the regular lizardpeople can, and to allow the selection of facial hair so they can choose the horns/frills, eg. Horn Adorns? Those two are the only things I wager are missing from that base, otherwise this is fantastic

Horns are already there, I can add spines yes

**Comment by NullDagaf** [comment]
*squirt*

**Comment by EerieDream** [comment]
These species can't do the emotes synth lizards have, like *dwoop, *yes, and *no. Will there be a fix for that?

**Comment by Gandalf2k15** [comment]
yeah i'll fix that

**Comment by KasparoVy** [comment]
> 
> 
> > HEEEELL yeah. Bless you
> > Would it be possible to allow synthliz to choose 'spines' like the regular lizardpeople can, and to allow the selection of facial hair so they can choose the horns/frills, eg. Horn Adorns? Those two are the only things I wager are missing from that base, otherwise this is fantastic
> 
> Horns are already there, I can add spines yes

Thanks a ton. This' what I meant by the facial hair bit - sorry for the crap explanation
image

Currently no facial hair styles render on synthliz species, they can choose it in character creator but in preview and in-game it doesn't show

**Comment by Gandalf2k15** [comment]
> > > HEEEELL yeah. Bless you
> > > Would it be possible to allow synthliz to choose 'spines' like the regular lizardpeople can, and to allow the selection of facial hair so they can choose the horns/frills, eg. Horn Adorns? Those two are the only things I wager are missing from that base, otherwise this is fantastic
> > 
> > 
> > Horns are already there, I can add spines yes
> 
> Thanks a ton. This' what I meant by the facial hair bit - sorry for the crap explanation
> image
> 
> Currently no facial hair styles render on synthliz species, they can choose it in character creator but in preview and in-game it doesn't show

Ah that's intended for synthliz's

**Comment by Nerev4r** [comment]
Can you let them beep and select antennae perhaps?

**Pull request merged**
