### PR TITLE
Metastation science fixes

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Whoopsie with manual copying over of new sci.

## Changelog
:cl:
fix: Fixed metastation science
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Well, Medbay also looks different right now on Meta, is it intended? It's got the decommissioned cloner and stuff.

**Comment by Gandalf2k15** [comment]
> Well, Medbay also looks different right now on Meta, is it intended? It's got the decommissioned cloner and stuff.

Intended up

**Comment by RatFromTheJungle** [comment]
ok bro i like it

**Review by KathrinBailey — CHANGES_REQUESTED** [review]
This does the following:
• Reverts Blueshield office and removes it completely.
• Reverts Cloning and removes it completely.
• Reverts cryo and removes it completely.
• Reverts prison cryo and removes it completely.
It also has some additional errors:
• Multiple xenobio cameras on the wrong networks, half of them are incorrect.
• Reinforced floors under windows throughout xenobio.

I'd prefer it Xyel weighs in on removing cloning from the maps, since originally, half of the reason for testmerging map changes was to add cryo and cloning. Seems weird to do a complete 180 turn out of nowhere on cloning.

**Pull request closed without merging**
