### PR TITLE
[AutoMapper] Some map fixes

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request
Fixes some oversights.

## How This Contributes To The Skyrat Roleplay Experience
No more hanging bluespace gas vendor outside of Metas barber shop.
Disposals now properly catapults itself into space on Delta.
Prison doors in Deltas prison are now proper glass airlocks.

## Changelog

:cl: Jolly
qol: On Delta, the prison's cell airlocks had glass reinserted. Prisoners can now no longer get their arms jammed in them when they open.
fix: On Delta, the disposals launcher now no longer vomits right next to the prison. 
fix: On Meta, outside the barber shop there should no longer be a spooky floating bluespace gas vender.
fix: On Meta, the inner side walls of the barber shop bordering EVA/Gateway are now proper R-Walls.
/:cl:

### CODE REVIEW

**Comment by Tastyfish** [comment]
This PR cut out large portions of the delta perma.

**Comment by Jolly-66** [comment]
> This PR cut out large portions of the delta perma.

This was intentional.

**Comment by Tastyfish** [comment]
> > This PR cut out large portions of the delta perma.
> 
> This was intentional.

Wasn't mentioned in the PR at all

**Comment by Tastyfish** [comment]
Also if you're mapping in the lustwish, you should add Delta Station to `/datum/area_spawn/lustwish_prison`'s `blacklisted_stations` since otherwise there are 2 lustwishes now.

**Pull request merged**
