### PR TITLE
Gives the carwo rifles names that suck less to refer to

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

Renames the carwo rifles:

Carwo 'd'Infanteria' Rifle -> Carwo-Cawil Battle Rifle

Carwo 'd'Elite' Marksman Rifle -> Cawil Marksman Rifle

Carwo 'd'Outomaties' Machinegun -> Qarad Light Machinegun

## How This Contributes To The Skyrat Roleplay Experience

The names of the carwo rifles aren't necessarily bad, its just that many people are confused as to what they are actually supposed to be called when referring to them. Rather than make a bunch of sol speakers (latin-hispanic kinda) fuck up french-afrikaans, I'll just give the rifles a better name to refer by.

## Proof of Testing

Just trust me bro

## Changelog

:cl:
qol: The sol rifles have had their names changed so that they suck less to refer to as characters that don't speak french-afrikaans (coming 2023)
/:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
> just trust me bro



real

**Comment by Ephemeralis** [comment]
This is gungirl erasure.

**Comment by theselfish** [comment]
Do everyone a favour and add what ammo type they're chambered in to the descriptions, please.

This is already an issue with Skyrat guns.

**Comment by Paxilmaniac** [comment]
> Do everyone a favour and add what ammo type they're chambered in to the descriptions, please.
> 
> This is already an issue with Skyrat guns.

ill do a sweep of every single weapon later and add their caliber to their descriptions

**Review by vinylspiders — APPROVED** [review]
French is hard I guess

**Pull request merged**
