### PR TITLE
[NONMODULAR] fixes material issues with metal hydrogen armor and buffs it

### PR DESCRIPTION
**Pull request by dawsonkeyes**
## About The Pull Request

Metal hydrogen armor has a few issues with it's material datums. This pr fixes those and gives it a slight buff, as it currently lacks any value as armor.

## Why It's Good For The Game

Not broken! Also, it's actually worth getting as an armor now, rather than making it once and realizing it's shit.

## Changelog
:cl:
fix: elder atmosian armor material datums not wacky
add: new elder atmosian armor stats
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
Hey, while your at it, @dawsonkeyes , think you could fix MH golems? They require shoes despite being golems still, and a couple other issues I think.

**Comment by gonenoculer5** [comment]
Also dear god this used material flags? Still? Really TG?

**Comment by Gandalf2k15** [comment]
Can you do this on TG?

**Comment by dawsonkeyes** [comment]
> Can you do this on TG?

Last I checked they only wanted the sprite changes upstream

**Comment by Gandalf2k15** [comment]
Add skyrat edit comments and we guuci

**Comment by Gandalf2k15** [comment]
Hello, if you wish for this PR to be merged please make the suggested changes and reopen it, thanks! 👍

**Pull request closed without merging**
