### PR TITLE
[MODULAR] Fixes security snowmobiles.

### LINKED ISSUE #9201: Security Snowmobiles don't realize they have a key in them
Reporting client version: 514.1569

## Round ID:
3484

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[SEMI-MODULAR?][TESTMERGE FIRST] Glow in the dark markings/bodyparts/eyes](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8960)

### PR DESCRIPTION
**Pull request by RatFromTheJungle**
## About The Pull Request

Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/9201

## How This Contributes To The Skyrat Roleplay Experience
makes snowmobiles work.

## Changelog

:cl:
fix: fixes security snowmobiles.
/:cl:

### CODE REVIEW

**Comment by Seris02** [comment]
fairly certain this isn't gonna fix it since uh
`/datum/component/riding/vehicle/atv/snowmobile/snowcurity`
isn't a typepath that's actually used anywhere
also, you don't need to make another file, snowmobiles are modular anyway just put the fix with the other snowmobile code

**Comment by RatFromTheJungle** [comment]
mm yes i know what fixed it
image

**Comment by ForrestWick** [comment]
Thanks for this, I've had a lot going on in my life and lotta other projects I wanted to focus on that I kept forgetting or just wasnt able to get around to this. I appreciate that you were able to get it, so thank you

**Review by GoldenAlpharex — APPROVED** [review]

**Comment by out-of-phaze** [comment]
This didn't fix anything because `make_ridable` is never called for ATVs, as shown by how this simply adds the proc. Also, on the base ATV type it's added in `Initialize` anyway.

**Pull request merged**
