### PR TITLE
[SEMI-MODULAR] Lighting Update

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

We started on the right track with the last lighting PR, this makes some improvements to it.

Dimming the lights got us away from the fullbright in every room and corner, but as it is the lighting is too uniform and skews on the yellow side. Instead of dramatic dark corners, rooms lit by their machinery, genuine light and dark places right now everything is the same dim shade of brown.

Instead of having dim lights with a large light spread this opts for more powerful lights with a shorter range. With this the objects in the room contribute more to the lighting ambiance and we can get those dark rooms and more dramatic features. The temperature is moved back towards daylight for the day shift and a dimmed night shift warming the colour to skew towards starlight.

A problem with the high spread lighting is there is no real consequence to destroying lights in an area. By concentrating the light on the sources and have the light falloff more rapidly you have a bigger impact if you smash out a light in a room.

## How This Contributes To The Skyrat Roleplay Experience

Your surroundings more impact the lighting in your area.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
image

image

image

image

image

image

image

image

image

image

image

image

</details>

## Changelog

:cl: LT3
code: Various lighting adjustments
/:cl:

### CODE REVIEW

**Comment by Zergspower** [comment]
oooooh hell yeah - that gives it a fucking spooky abandoned office-building vibe.

**Comment by tf-4** [comment]
This seems a little too cool honestly. The current is too warm, but this is a big step in the opposite direction.

It does seem a little bit brighter overall, though, which is a big +1 from me who can barely see half the time

**Review by Gandalf2k15 — APPROVED** [review]

**Comment by QuacksQ** [comment]
Was this tested on other maps or only on Tram? Asking because I only see screenshots from tram and the impact on the visuals of different maps can be affected greatly by the lighting from this PR.

**Comment by lessthnthree** [comment]
Yes, on Meta, VR and Icebox as well. Some light adjustments are needed for
a few areas but the light range should cover most everything.

**Pull request merged**
