### PR TITLE
[NON-MODULAR] Health-scanner text visual clarity

### PR DESCRIPTION
**Pull request by desertmote**
## Changelog
:cl:
qol: Health-scanner's dark-blue text is purple now to aid visual clarity
/:cl:

## About The Pull Request

Current: 
Current

New:
New-dark
New-light

## Why It's Good For The Game

Visual clarity is important! I got this request and figured it would be easy. Lmk if upstreaming it is better, although I can't really be bothered for now. 🤭

### CODE REVIEW

**Comment by tf-4** [comment]
this doesn't seem any easier to read to me, honestly

**Comment by desertmote** [comment]
> this doesn't seem any easier to read to me, honestly

ill make it even clearer

**Comment by Swiftfeather** [comment]
I would try upstream

**Comment by desertmote** [comment]
the modular commenting is messy and i can make the colors even better upstream. will give it a shot.

**Pull request closed without merging**
