### PR TITLE
Re-centers the title screen

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
## About The Pull Request
I don't know how but our title screens don't need to be re-centered, so they no longer will be.

## How This Contributes To The Skyrat Roleplay Experience
I'm sick of VV'ing the title screens, man.

## Changelog

:cl: GoldenAlpharex
fix: The titlescreens are now centered again.
/:cl:

### CODE REVIEW

**Comment by Iamgoofball** [comment]
You're supposed to just make them widescreen.

**Comment by GoldenAlpharex** [comment]
> You're supposed to just make them widescreen.

They already are.

**Comment by GoldenAlpharex** [comment]
We have a wider widescreen than /tg/ and as such our title screens were updated for that, and it just works.

**Comment by GoldenAlpharex** [comment]
It's a tiny fix, no reason to wait for someone else to merge it.

**Pull request merged**
