### PR TITLE
Increases Cargo Borg's Upgraded Clamp Capacity

### PR DESCRIPTION
**Pull request by Reco201**
## About The Pull Request
Increases the capacity of the upgraded Cargo Borg's Clamp by 1

Edits the examine text to be correct with the change in capacity.

## How This Contributes To The Skyrat Roleplay Experience
The current upgraded clamp allows you to carry exactly one wrapped crate while a cargo tech is able to carry 5 in the Loader Modsuit. 
image

This change from 1 to 2 Wrapped crates allows cargo borgs to make more deliveries while also still allowing cargo techs to carry larger orders if they wish.
image

## Changelog

:cl:

balance: Cargoborgs upgraded clamp can now carry two wrapped crates instead of one.

/:cl:

### CODE REVIEW

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
I would like for you to do something extra for me here:

I'd like for you to update the description with how many crates are currently stored in the clamp. I can show you how, just poke me in the development channels, but I think it's a good learning opportunity for you.

**Comment by Reco201** [comment]
Got it working with the changes, will add screenshots soon

**Comment by Reco201** [comment]
image
image
image
@GoldenAlpharex

**Review by GoldenAlpharex — APPROVED** [review]
Looks good!

**Pull request merged**
