### PR TITLE
Adds a collection of some kinda random greyscaled, recolorable clothes options

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request
Similarly to the forge armor pr, I made these for an event but it was suggested to make these regular access since there were some good ones in there. Thus I present:

image
image

A hood, with the bit around the neck and the hood itself being separately colorable.

image
image

A mantle, based off the amazing head of staff mantle resprite we had.

image
image

An apron, there's nothing much special here.

image
image

Jackboots, but you can color them.

image
image

Something pretty close to laceups, again with the ability to color them now.

image
image

Lastly, sandals, I know you're not gonna wear these with socks right?

What this pr also does:
Moves the bathrobe icon and gives it icons for all the races.
Makes a bunch of folders and standard icon files for moving other GAGS stuff into eventually, I'll get to it.

## How This Contributes To The Skyrat Roleplay Experience
I saw recently there was a poll for greyscale items people might want, and realized I have a few decent ones laying around now that fit every species. Get that ultimate customization with the ability to greyscale more stuff!

## Changelog

:cl:
add: A collection of new greyscaled clothing items have been added to the loadout, clothes vendors, and a few even to the ashwalker clothes supplier. These include a hood, a mantle, an apron, boots, laceups, and sandals!
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
oh no every integration test failed i really done fucked it up now

**Review by Ebin-Halcyon — APPROVED** [review]
All solid work, just remember to add in game screenshots.

**Comment by Paxilmaniac** [comment]
yeah gotcha

**Review by GoldenAlpharex — APPROVED** [review]
Looks good to me!

**Pull request merged**
