### PR TITLE
[Modular] Nyahaha Emotes

### PR DESCRIPTION
**Pull request by SarmentiCampbell**
## About The Pull Request
I was held at gunpoint by hubert, send help

## Why It's Good For The Game
gatto

## Changelog
:cl:
add: Added Four new laughs for felinids
/:cl:

### CODE REVIEW

**Comment by HUBERTGRUBE** [comment]
https://youtu.be/Sg14jNbBb-8?t=3

**Comment by Swiftfeather** [comment]
NO!

**Comment by ghost** [comment]
**What have you done**

**Comment by Gandalf2k15** [comment]
ok

**Comment by desertmote** [comment]
urghf

**Pull request merged**
