### PR TITLE
[MIRROR] Reflavors the Mosin to be a surplus rifle from the past IC 200 years, rather than from 670 years ago in game. Allergy warning: May contain microscopic silverscale buff [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/77169
--------------------
## About The Pull Request

As the beautiful title may imply:

The Mosin-Nagant rifle has been reflavored into something _slightly_ more modern for the setting (The game currently takes place in 2563 you know). Rather than a gun made in 1891 ending up in the hands of cargo techs 670 years in the future, instead aspiring revolutionaries, larpers, and eastern europeans in general will be seen arming themselves with something at least a few hundred years more modern.

<details>
<summary>The Sakhno Precision Rifle, the new Nagant</summary>
<br>

image

"A Sakhno Precision Rifle, a bolt action weapon that was (and certainly still is) popular with frontiersmen, cargo runners, private security forces, explorers, and other unsavoury types. This particular pattern of the rifle dates back all the way to 2440."

</details>

<details>
<summary>The Sakhno M2442 Army, surplus power</summary>
<br>

image

"A modification of the Sakhno Precision Rifle, _Sakhno M2442 Army_ is stamped into the side. It is unknown what army this pattern of rifle was made for or if it was ever even used by an army of any sort. What you can discern, however, is that its previous owner did not treat the weapon well. For some reason, there's moisture all through the internals."

</details>

<details>
<summary>The Sakhno - Zhihao Sporting Rifle, weapons for the rich</summary>
<br>

image

"An upgrade and modernisation of the original Sakhno rifle, made with such wonders as modern materials, a scope, and other impressive technological advancements that, to be honest, were already around when the original weapon was designed. Surprisingly for a rifle of this type, the scope actually has magnification, rather than being decorative."

</details>

<details>
<summary>The Lionhunter and Enchanted Bolt Action</summary>
<br>

image

Because it wouldn't make sense for heretics and wizards to be summoning brand new military green bolt action guns, some wood-like and significantly fancier looking variations of the sprite now exist for both of the guns.

</details>

</details>

<details>
<summary>How these look in game:</summary>
<br>

image

</details>

## Why It's Good For The Game

<details>
<summary>See a before and after:</summary>
<br>

The sprites on the left of the arrow are what they are now, and the sprites on the right are what they will turn into, note that there's one old sprite to several new sprites, this is because guns that were represented by the same sprite before now have their own unique looks.

These are subject to be slightly different than what you see here, but will be more or less like these images.

image

image

image

image

</details>

While I understand the appeal of wanting a shitty, old rifle to have in the game for everyone's surplus needs, the Mosin (and a good few other guns too, looking at you 1911) is just a fair bit too old in my book. About 670 years old. I find it more believable that while there would still be some shitty surplus weapon that cargo techs and larpers would non-stop fawn over, it'd be something that's old by the standards of the year 2563 where the game takes place, vs old by the standards of 2023.

I think it'd greatly help the sense of the fact that we exist many hundreds of years in the future if we stop using guns made before the first world war.

## Changelog
:cl:
image: The Mosin-Nagant has been given new sprites and a reflavor, looking for the old rifle? Look for the Sakhno Precision Rifle.
balance: The tiniest balance thing, but since Silverscales use the Sakhno-Zhihao rifle, which has a scope on it, their main weapon now has a scope.
sound: The cargo rifle now has a new, considerably more rifle sized firing sound. Gotten from tgmc from https://github.com/tgstation/TerraGov-Marine-Corps/pull/12280.
/:cl:

note: includes https://github.com/Skyrat-SS13/Skyrat-tg/pull/23092 as well

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
this will probably break really bad with our mosin overrides I will make a pr to fix everything

**Comment by vinylspiders** [comment]
> this will probably break really bad with our mosin overrides I will make a pr to fix everything

Thank you for that! It'll be included in this now.

**Comment by SpessManCN** [comment]
> this will probably break really bad with our mosin overrides I will make a pr to fix everything

wait, what will happen to the QM mosin? give him a Zhihao rilfe?

**Comment by Paxilmaniac** [comment]
> > this will probably break really bad with our mosin overrides I will make a pr to fix everything
> 
> wait, what will happen to the QM mosin? give him a Zhihao rilfe?

The QM rifle is untouched outside of me renaming its description to mention the correct ammo type

**Comment by vinylspiders** [comment]
Still looks fine to me.

**Review by vinylspiders — APPROVED** [review]

**Pull request merged**
