### PR TITLE
Improved the barber's chair's appearance and improves the barber item code overall

### LINKED ISSUE #9174: Barber sign has no inhand sprite when removed from the wall.
## Round ID:
3474

## Testmerges:
The following pull requests are currently test merged:
#8842: '[TM-Only] First attempt at stopping tgchat from eating messages' by GoldenAlpharex at commit a0622a98fc
#8960: '[SEMI-MODULAR?][TESTMERGE FIRST] Glow in the dark markings/bodyparts/eyes' by Seris02 at commit b769e1dbbc

## Reproduction:

Step 1: Remove barber shop sign from wall.
Step 2: Scream as reality itself rends and you beholden a floating red error sign of death, ensuing the final end of this world.

### PR DESCRIPTION
**Pull request by GoldenAlpharex**
## About The Pull Request
It annoyed me how the barber's chair looked kinda silly because it didn't overlay anything above the mob when they're sitting down. They're now a subtype of comfy chairs and inherit some code that I'm also PR'ing upstream, it should trickle down to us soon™️. 

This looks so much better:
image

As always, every time I touch barber code, I end up improving it because it annoys me. As such, the scissors will now tell you when you're not aiming for the right body parts to change their hairstyle. Scissors and razors can now be VV'd to have the time they take to perform their actions tweaked, because that was annoying. The barber's sign can no longer be unwrenched, so it won't make an item that looks like an error anymore. 

Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/9174.

## How This Contributes To The Skyrat Roleplay Experience
Makes the barber's shop more visually pleasing, and also improves the usage of it within the context of the game.

## Changelog

:cl: GoldenAlpharex
code: Improved the barber code some more.
fix: Fixed the barber sign not looking like anything when picked up.
imageadd: Sitting down on a barber's chair will now allow you to sit properly in it, rather than awkwardly lying on top of everything, armrests included!
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
> The barber's sign can no longer be unwrenched, so it won't make an item that looks like an error anymore.

No, no, no. Thats not how were doing this. Add a proper damn in-hand sprite or wait for me to fix it.

**Comment by GoldenAlpharex** [comment]
> > The barber's sign can no longer be unwrenched, so it won't make an item that looks like an error anymore.
> 
> No, no, no. Thats not how were doing this. Add a proper damn in-hand sprite or wait for me to fix it.

You can fix it later, it's literally one line, but until your thing goes through, I don't see a need for it to be the way it is currently.

**Comment by gonenoculer5** [comment]
> > > The barber's sign can no longer be unwrenched, so it won't make an item that looks like an error anymore.
> > 
> > 
> > No, no, no. Thats not how were doing this. Add a proper damn in-hand sprite or wait for me to fix it.
> 
> You can fix it later, it's literally one line, but until your thing goes through, I don't see a need for it to be the way it is currently.

Why not literally just use the generic sign sprite for it then rather than disable it. Agony.

**Comment by GoldenAlpharex** [comment]
> Why not literally just use the generic sign sprite for it then rather than disable it. Agony.

Because there's more stuff that doesn't work with it, like the fact that, when you put it back, it's entirely not placed correctly. I didn't want to mess with that in this PR, and I don't feel like the ability to move it is integral to the game at this current point in time.

**Comment by tf-4** [comment]
Link issues https://github.com/Skyrat-SS13/Skyrat-tg/issues/9174

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
