### PR TITLE
Revert "[MIRROR] remove y##f in h##l spray, adds furry pride spray [MDB IGNORE]" [ MODULAR ]

### PR DESCRIPTION
**Pull request by Gandalf2k15**
Reverts Skyrat-SS13/Skyrat-tg#14651

we cannot be held back by the shackles of autocracy on this server, it is only right, we are free, we are whole

### CODE REVIEW

**Comment by Zonespace27** [comment]
image

**Comment by GoldenAlpharex** [comment]
:trollface:

**Comment by Gandalf2k15** [comment]
YOU CANNOT SILENCE DEMOCRACY

**Comment by nevimer** [comment]
cobalt link fursona

**Comment by Paxilmaniac** [comment]
what th efuck is a democracy

**Comment by hugmeorelse** [comment]
cobalt link fursona

**Comment by CentralSmith** [comment]
Can you fucking not spam the server with this?

**Comment by SarmentiCampbell** [comment]
cobalt link fursona

**Comment by Gandalf2k15** [comment]
HNNNNNNNNNNNNGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by Gandalf2k15** [comment]
I WILL MODULRAISE IT IJKFJ

**Review by tf-4 — APPROVED** [review]
lgtm

**Comment by Paxilmaniac** [comment]
non modular change
image

**Comment by Gandalf2k15** [comment]
> non modular change image

i added [modualr] to title, ur cringe and wrong

**Comment by Paxilmaniac** [comment]
L + didn't link fursona

**Comment by Jolly-66** [comment]
Link your fursona

**Comment by zeratino** [comment]
Link your fursona

**Pull request merged**
