### PR TITLE
Defaults Mutant Variants to NONE. Going forward, MANUALY tag clothes you add mutant_variants support for.

### PR DESCRIPTION
**Pull request by Iamgoofball**
I'm not doing it in this PR.

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Finally. It was on my bucket list for a long time.

**Review by GoldenAlpharex — APPROVED** [review]
People will have to fix their clothing after this PR. I'll ping them on Discord or something.

**Comment by Gandalf2k15** [comment]
We already have a section for this. Do not invert this. Everything will break and I am not fixing it.

**Comment by Gandalf2k15** [comment]
My recent PR addressed this partially, please, don't do this.

**Pull request closed without merging**
