### PR TITLE
feeshy donator item, adds the odd lizzy plush.

### PR DESCRIPTION
**Pull request by capsaicinz**
## About The Pull Request

i hate the anti-christ. feeshy's donator item. shakes his ass.

## How This Contributes To The Skyrat Roleplay Experience

it doesn't. 

## Changelog

:cl:
add: added the odd lizzy plush.
/:cl:

### CODE REVIEW

**Comment by azrael-x86** [comment]
why

**Comment by capsaicinz** [comment]
this single pr is fucking ruining my repo so hold on

**Comment by axietheaxolotl** [comment]
this is amazing
I love it.

**Comment by axietheaxolotl** [comment]
https://user-images.githubusercontent.com/86872535/135959942-a8872a8f-29df-4530-85d2-c1862027a1bf.mp4

**Comment by capsaicinz** [comment]
I HATE THE ANTICHRIST

**Pull request closed without merging**
