### PR TITLE
Should fix ghosts going splishy splashy

### LINKED ISSUE #5906: Ghosts that are orbiting ghosts create splash noises in fluids
## Testmerges:
Unrelated, likely
#3255: 'Sizeplay v 0.5' by Useroth at commit 63855a05a7
#5884: '[MODULAR][TM-FIRST][READY] Interaction Menu Framework and Basic Interactions' by ZephyrTFA at commit 90d92e24cf

### PR DESCRIPTION
**Pull request by FlamingLily**
## About The Pull Request
Fixes #5906 

Haven't been able to test but this should fix it

## Why It's Good For The Game
Fix good

## Changelog
:cl:
fix: Ghosts have been banned from the splishy splashy. You wanna splash? Exist in our reality, nerd.
/:cl:

### CODE REVIEW

**Comment by FlamingLily** [comment]
_glare_

**Comment by FlamingLily** [comment]
sigh

**Comment by Azarak** [comment]
Feature regressions for items not creating splishy splashes. Check isobserver() instead
Also this would prevent items caching on fire on liquid fire puddles

**Comment by Azarak** [comment]
Camera eyes using abstract move... don't know if that triggers the signals

**Comment by Azarak** [comment]
or I guess just reverse the logic and check for item or mob

**Comment by Gandalf2k15** [comment]
Isobserver is the good option

**Comment by FlamingLily** [comment]
tbh I didn't even realise isobserver existed

**Pull request merged**
