### PR TITLE
[NONMODULAR] Renames Combat Gloves

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
Renamed Combat Gloves to Black Gloves. The description isn't changed.

## How This Contributes To The Skyrat Roleplay Experience
They're black gloves, they shouldn't be obvious at a glance unless you're holding them in your hands.

## Changelog

:cl:
balance: combat gloves appear as black gloves now
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
I am fairly certain that the description is kinda hinting at them looking differently from normal black gloves. Maybe no one had the sprite to replace them or simply didn't wanna - gloves are gloves, anyways.

**Comment by YakumoChen** [comment]
"These tactical gloves are fireproof and electrically insulated."

That doesn't hint at anything at all, really. Insulated fibers don't have to be yellow, mind you, they're just recognizable from the rubber gloves.

**Comment by Gandalf2k15** [comment]
The gloves should have some differentiating features in some way or another, what I suggest is either leaving them as tactical gloves or giving the on-mob sprites a different shade/pattern. There are times that you want to display what you're wearing.

**Comment by GoldenAlpharex** [comment]
They're named combat gloves to force you to examine people to tell that they're combat gloves and not just black gloves. The color was chosen on purpose for this reason. Stealthy, as long as people don't take the time to look carefully.

This isn't the way to go.

**Pull request closed without merging**
