### PR TITLE
[MODULAR] Synth and IPC Construction!

### PR DESCRIPTION
**Pull request by RimiNosha**
## About The Pull Request
Requires #16105

Yup, robotics able to build... *robots*, imagine that!

- Makes the SAD able to be built by science, cause robotics can now create bodies, so...
- Makes synth and IPC torsos buildable!
- Adds in a new research, along with a discount experiment to scan various robots, as well as synths!
- Adds a new item that can convert **cyborg** MMIs, Posibrains and AI Circuits into other types into either cyborg or synth brains, but you can't convert non-MMI brains into MMIs.

Almost completely untested, and is heavily subject to change.

I am likely to make the lathe print entire bodies with limbs attached, but without the organs, otherwise there's gonna be a crapton of snowflake code just for printing arms and legs for each type of synth.

## How This Contributes To The Skyrat Roleplay Experience
Synths are now expendable, and IPCs doubly so!

Seriously though, having to be humonkey'd as a synth before being SAD'd by medical is... ew.

## Changelog

:cl:
add: Added a new experiment and research to unlock the ability for robotics to build synths and IPCs.
add: Robotocists can now finally build Synths and IPCs.
add: A new item to convert Cyborg-based brains to other similar types of brain.
qol: The self actualization device can now be printed by science to accommodate synth and IPC building.
/:cl:

### CODE REVIEW

**Comment by Zergspower** [comment]
I like it, but it also just makes me finally think it's time for me to put synths in one file like other races are.

**Comment by ghost** [comment]
> I like it, but it also just makes me finally think it's time for me to put synths in one file like other races are.

Wonder if we could make all synths into one species at this point, have everything else as customization

**Comment by Iamgoofball** [comment]
that should be done, yes

**Comment by Zergspower** [comment]
> > I like it, but it also just makes me finally think it's time for me to put synths in one file like other races are.
> 
> Wonder if we could make all synths into one species at this point, have everything else as customization

Yeah - when we redid their surgeries and damage taken values it was a fucking nightmare and a half. I'm adding it to my list of things to get done so we can

**Pull request closed without merging**
