### PR TITLE
CME occurrence rebalance

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

I've had a few complaints about CME's happening too often. People probably don't realise it but events that are destructive are what keep the game interesting. 

I've lowered the length of time these last by a bit. 

I've halved the spawn rate and changed how they spawn, it's now one datum that picks what type it's gonna be.

Closes https://github.com/Skyrat-SS13/Skyrat-tg/pull/4386

## Changelog
:cl:
balance: CME occurrence chances have been changed.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
I mean, I still believe that, if they weren't so punishing when people neutralize them, that it would be a much more enjoyable event. The problem with messing with a room's air is that, with atmos as it currently is, it's kind of a pain to fix. Players don't really want to just run around for the rest of the round trying to fix the air alarms because people stopped the anomalies and it just turned the rooms into saunas-- The bad kind of saunas, mind you.

**Comment by Gandalf2k15** [comment]
> I mean, I still believe that, if they weren't so punishing when people neutralize them, that it would be a much more enjoyable event. The problem with messing with a room's air is that, with atmos as it currently is, it's kind of a pain to fix. Players don't really want to just run around for the rest of the round trying to fix the air alarms because people stopped the anomalies and it just turned the rooms into saunas-- The bad kind of saunas, mind you.

You say that people don't like it because it's punishing, but the only fire it starts is 15 moles of plasma when they spawn, the only ones that cause a fire when neutralized are the extreme(red) ones. The rest do not spawn a fire when neutralized.

**Comment by GoldenAlpharex** [comment]
> > I mean, I still believe that, if they weren't so punishing when people neutralize them, that it would be a much more enjoyable event. The problem with messing with a room's air is that, with atmos as it currently is, it's kind of a pain to fix. Players don't really want to just run around for the rest of the round trying to fix the air alarms because people stopped the anomalies and it just turned the rooms into saunas-- The bad kind of saunas, mind you.
> 
> You say that people don't like it because it's punishing, but the only fire it starts is 15 moles of plasma when they spawn, the only ones that cause a fire when neutralized are the extreme(red) ones. The rest do not spawn a fire when neutralized.

Well, my apologies, I haven't really paid attention to them as I was one of those to just flee to lavaland every time they happened, because I either had implants or nanites and didn't feel like being crippled. If it's limited to Extreme, then that's a little better in my books, but it still feels a little weird of a concept nonetheless.

**Comment by YakumoChen** [comment]
Neutralizing a CME also unavoidably sets you on fire and stuns you for good measure, making it difficult to do so without heavy fire protection since it will outright kill you from one neutralization.

The game doesn't warn you that neutralizers do this on CMEs and it frankly doesn't make sense compared to how actual anomalies are dealt with.

**Comment by Mithrun** [comment]
> I've had a few complaints about CME's happening too often. People probably don't realise it but events that are destructive are what keep the game interesting.

As someone who's played a lot of engineering i can tell you that there is a clear difference between actually playing engineering and annoying busywork that makes you curse the day you were born. Fixing air alarms is the latter. I really don't like the CME and don't understand why so many of the events are just there to annoy engineers. Clearly there's a problem with them not really having a lot of work but surely there's a way to make it fun.

**Comment by NullDagaf** [comment]
...i was gonna have a autist spazm about how cme's are fundamentally bad
but then i remembered i didn't even experience them firsthand

**Comment by softcerv** [comment]
One of the biggest issues I have with CMEs is that they personally feel incredibly unrewarding and painful to deal with, I feel like there should be some kind of reward for dealing with them like anomalies have.

**Pull request merged**
