### PR TITLE
[MODULAR] Removes Security Medic

### PR DESCRIPTION
**Pull request by SpookyTheFox**
## About The Pull Request
How many fully qualified surgeons kick down doors with the swat team as their day job? Not many. This Pull Request removes the Security medic. It cleans up all associated datums and sprites. It does not remove the still quite generous medical area in the brig, in case security wants to bring in an outside doctor or attempt basic patch ups themselves.

My apologies to the sprite makers, the uniform actually looked really good.

## Why It's Good For The Game
The Security Medic has always been a dubious role. It has all the access of a paramedic, a doctor, and a security officer. As a member of security, they are able and equipped to make arrests, yet they also have full access to medbay and maintenance, two things not afforded to actual medical staff for obvious balance and role play reasons. The mere existence of this job allows an entire department to bypass reliance on another, a failure to adhere to a critical aspect of the game.

It also unfairly allows very easy access to pacification, implant checks, and outright theft of supplies from medbay, all of which security should go through the proper channels to receive. Further, the job also contributes to sec role slot bloat. The role shortcuts role play opportunities, contributes to medbay having nothing to do, promotes security cliques, and would be considered abuse on any role play focused server. Thus, I propose removing it, in it's entirety.
 

## Changelog
:cl:
del: See commit history
balance: removes an overly strong role that bridges two departments it should not.
/:cl:

### CODE REVIEW

**Comment by Vizoplez** [comment]
Incorrect naming convention, furthermore; you havent actually removed a majority of their items.

Change the title to [MODULAR] Removes Security Medic

**Review by Vizoplez — APPROVED** [review]
Looks good, though doesnt remove the Firefly gunbox, ecetera. Non-issue.

**Comment by CameronWoof** [comment]
The claim that Sec Medic is a problem seems unfounded to me. What actual problem does their existence cause?

**Comment by Vizoplez** [comment]
`[02:20:23] Runtime in monkey_behaviors.dm,93: undefined variable /turf/open/floor/plating/dirt/var/held_items
  proc name: attempt pickpocket (/datum/ai_behavior/monkey_equip/pickpocket/proc/attempt_pickpocket)
  src: /datum/ai_behavior/monkey_equi... (/datum/ai_behavior/monkey_equip/pickpocket)
  call stack:
  /datum/ai_behavior/monkey_equi... (/datum/ai_behavior/monkey_equip/pickpocket): attempt pickpocket(/datum/ai_controller/monkey (/datum/ai_controller/monkey))
  world: ImmediateInvokeAsync(/datum/ai_behavior/monkey_equi... (/datum/ai_behavior/monkey_equip/pickpocket), /datum/ai_behavior/monkey_equi... (/datum/ai_behavior/monkey_equip/pickpocket/proc/attempt_pickpocket), /datum/ai_controller/monkey (/datum/ai_controller/monkey))
FAIL: /datum/unit_test/spawn_humans 5s
	REASON #1: [02:20:23] Runtime in monkey_behaviors.dm,93: undefined variable /turf/open/floor/plating/dirt/var/held_items
  proc name: attempt pickpocket (/datum/ai_behavior/monkey_equip/pickpocket/proc/attempt_pickpocket)
  src: /datum/ai_behavior/monkey_equi... (/datum/ai_behavior/monkey_equip/pickpocket)
  call stack:
  /datum/ai_behavior/monkey_equi... (/datum/ai_behavior/monkey_equip/pickpocket): attempt pickpocket(/datum/ai_controller/monkey (/datum/ai_controller/monkey))
  world: ImmediateInvokeAsync(/datum/ai_behavior/monkey_equi... (/datum/ai_behavior/monkey_equip/pickpocket), /datum/ai_behavior/monkey_equi... (/datum/ai_behavior/monkey_equip/pickpocket/proc/attempt_pickpocket), /datum/ai_controller/monkey (/datum/ai_controller/monkey))`

Monkey AI once more beats CI

**Comment by SpaceVampire** [comment]
Couldn't you keep all the stuff for it in the code, and just set the round-start slots to zero like we did with the clown? I could still see someone wanting to use the outfit in the future, and that makes it more configurable.

**Comment by SpookyTheFox** [comment]
> 
> 
> Couldn't you keep all the stuff for it in the code, and just set the round-start slots to zero like we did with the clown? I could still see someone wanting to use the outfit in the future, and that makes it more configurable.

That is one possible approach, and I did consider it. However, I ultimately went with full removal. A core tenant of what it means to be MRP, is playing plausibly realistic characters who are not experts at everything. A security officer that is also an expert surgeon is not a quality team role play driven character. Further, even placing the equipment locker in the brig invites players to bypass another department, and overly easy access to medical care just encourages security to disregard their own safety and charge into battle. The very premise of this role is to negate critical balance and role play aspects of the game. Keeping the security medic role with the slots turned off flies in the face of this, it really should never have existed to begin with.

**Comment by SpookyTheFox** [comment]
> 
> 
> `[02:20:23] Runtime in monkey_behaviors.dm,93: undefined variable /turf/open/floor/plating/dirt/var/held_items proc name: attempt pickpocket (/datum/ai_behavior/monkey_equip/pickpocket/proc/attempt_pickpocket) src: /datum/ai_behavior/monkey_equi... (/datum/ai_behavior/monkey_equip/pickpocket) call stack: /datum/ai_behavior/monkey_equi... (/datum/ai_behavior/monkey_equip/pickpocket): attempt pickpocket(/datum/ai_controller/monkey (/datum/ai_controller/monkey)) world: ImmediateInvokeAsync(/datum/ai_behavior/monkey_equi... (/datum/ai_behavior/monkey_equip/pickpocket), /datum/ai_behavior/monkey_equi... (/datum/ai_behavior/monkey_equip/pickpocket/proc/attempt_pickpocket), /datum/ai_controller/monkey (/datum/ai_controller/monkey)) FAIL: /datum/unit_test/spawn_humans 5s REASON #1: [02:20:23] Runtime in monkey_behaviors.dm,93: undefined variable /turf/open/floor/plating/dirt/var/held_items proc name: attempt pickpocket (/datum/ai_behavior/monkey_equip/pickpocket/proc/attempt_pickpocket) src: /datum/ai_behavior/monkey_equi... (/datum/ai_behavior/monkey_equip/pickpocket) call stack: /datum/ai_behavior/monkey_equi... (/datum/ai_behavior/monkey_equip/pickpocket): attempt pickpocket(/datum/ai_controller/monkey (/datum/ai_controller/monkey)) world: ImmediateInvokeAsync(/datum/ai_behavior/monkey_equi... (/datum/ai_behavior/monkey_equip/pickpocket), /datum/ai_behavior/monkey_equi... (/datum/ai_behavior/monkey_equip/pickpocket/proc/attempt_pickpocket), /datum/ai_controller/monkey (/datum/ai_controller/monkey))`
> 
> Monkey AI once more beats CI

I've noticed this for the last day or so. I did test my PR on local, from a complete branch download, new TGUI build, and compile, to make sure it's working as intended.

**Comment by CameronWoof** [comment]
Brig Physician is a very attractive fantasy and operates without issue on several other servers. The "problems" you state in your description are literally just the features of the role. They allow the only department that should be doing implant checks or ordering pacification surgery to actually do them, while supplying localized healthcare for prisoners, who are practically their own department entirely on some shifts. 

Most of your criticisms could be correctly leveled against Paramedic, the absolute apex medical role with access to way more places than most roles have (including your lauded maintenance access) who has the ability to roam the halls, dealing with patients before any of the doctors in medbay even see that they're hurt. 

If anything, we could try redefining the role to not include normal officer duties before outright removing something because they're "robbing medbay of something to do", whatever that even means. But I just don't think Security Medic is not a problem.

**Comment by YakumoChen** [comment]
As a sec main I'm initially against this
As a doctor main I see the value in pushing this through.

Forcing sec to generally bring everyone to medbay (officers, prisoners, detainees) allows much more interesting roleplay and opportunities for these roles to interact instead of guaranteeing everyone will be dealt with by a role which cannot be antag and is always security-aligned and will almost always be treated in a Security Safe Space.

**Comment by Gandalf2k15** [comment]
The entire point of the security medic role is to aid officers on the field and deal with emergencies in the brig. Thats the reason the brig first aid area is so bare. The medic should be in the brig during green alert and on the field with officers helping them in deadly situations. Think of CM and their squad medics. And removing the content like this isn't something we should be doing. We can change it if need be to put more emphasis on the role and its duties

**Comment by SpookyTheFox** [comment]
> 
> 
> The entire point of the security medic role is to aid officers on the field and deal with emergencies in the brig. Thats the reason the brig first aid area is so bare. The medic should be in the brig during green alert and on the field with officers helping them in deadly situations. Think of CM and their squad medics. And removing the content like this isn't something we should be doing. We can change it if need be to put more emphasis on the role and its duties

If they were doing away missions, there would be something to be said for a dedicated combat medic. But the truth of the matter is, the are never more than a hundred and fifty meters from a futuristic hospital when they are on the station. Giving security their own medic is neither realistic nor in the interest of game balance or role play.

In addition, the brig medical area isn't even close to being bare basics, it has everything needed for invasive surgery, and is frequently upgraded beyond that. The security medic has round start access to a mix of equipment that normal doctors and paramedics are mutually excluded from having access to, or even the means of obtaining without outside help.

The security medic slot solely exists to prevent the largest department on station from having to interact with and receive assistance from other departments, and to shortcut critical roleplay and balance mechanics.

**Comment by Gandalf2k15** [comment]
> > The entire point of the security medic role is to aid officers on the field and deal with emergencies in the brig. Thats the reason the brig first aid area is so bare. The medic should be in the brig during green alert and on the field with officers helping them in deadly situations. Think of CM and their squad medics. And removing the content like this isn't something we should be doing. We can change it if need be to put more emphasis on the role and its duties
> 
> If they were doing away missions, there would be something to be said for a dedicated combat medic. But the truth of the matter is, the are never more than a hundred and fifty meters from a futuristic hospital when they are on the station. Giving security their own medic is neither realistic nor in the interest of game balance or role play.
> 
> In addition, the brig medical area isn't even close to being bare basics, it has everything needed for invasive surgery, and is frequently upgraded beyond that. The security medic has round start access to a mix of equipment that normal doctors and paramedics are mutually excluded from having access to, or even the means of obtaining without outside help.
> 
> The security medic slot solely exists to prevent the largest department on station from having to interact with and receive assistance from other departments, and to shortcut critical roleplay and balance mechanics.

When I made the security medic I made it more security than medic for a reason, they're not SUPPOSED to be doing all of that. Removing a role that allows security players to feel less involved in the action is bad, especially considering how many people enjoy the role. This works well on most servers and there isn't much reason for it not to work here. 

The work others have put into it also warrants a change and not a remove. Until I actually witness them becoming a problem I don't think they need to be removed. We may, as I've said, look into removing some of their equipment to deal with this.

**Comment by SpookyTheFox** [comment]
> The work others have put into it also warrants a change and not a remove. Until I actually witness them becoming a problem I don't think they need to be removed. We may, as I've said, look into removing some of their equipment to deal with this.

I've looked long and hard at the role, and even played it. I am aware others put a lot of effort into it, but no one did the critical work of balancing such an over provisioned role against other, existing roles on the station. The equipment they are given is pretty egregious. Their locker is filled with tools and consumables that do not belong to that class and are intended to be time locked for the proper users to mid round at a minimum. But it goes beyond that. Their access within medbay is more than either a doctor or a paramedic has. This is especially baffling when there is already a medical department guard role.

The very point of this role, is to do the work of another department, and to create a high power job that is not only an armed security guard, but also better than a doctor or a paramedic. In practical application, the security medic also allows the security department to bypass balance otherwise built into the division of departments and individual jobs, and detracts heavily from role play by wrongfully giving security extended, priority access to medbay mechanics that were never intended.

Outright removal has additional benefits, such as diminishing role play failures from the security department stemming from reduced penalties for injury or death, and rewarding the actual medical department for their skill and knowledge. It will also do wonders for reducing security department isolation and wrongful self service.

 The security medic role never should have been created in the first place, and after extended consideration, removal is a much more desirable option than reworking the role to bring it in line with access and power of other jobs on the station. Security is not mechanically prevented from buying their own first aid kits, crew monitor, and requesting additional access, but there are plenty of reasons they should not be given these under the guise of an official position. The security medic role itself is bad for the game, and needs to go.

**Comment by Gandalf2k15** [comment]
> > The work others have put into it also warrants a change and not a remove. Until I actually witness them becoming a problem I don't think they need to be removed. We may, as I've said, look into removing some of their equipment to deal with this.
> 
> I've looked long and hard at the role, and even played it. I am aware others put a lot of effort into it, but no one did the critical work of balancing such an over-provisioned role against other, existing roles on the station. The equipment they are given is pretty egregious. Their locker is filled with tools and consumables that do not belong to that class and are intended to be time locked for the proper users to mid round at a minimum. But it goes beyond that. Their access within medbay is more than either a doctor or a paramedic has. This is especially baffling when there is already a medical department guard role.
> 
> The very point of this role, is to do the work of another department and to create a high power job that is not only an armed security guard but also better than a doctor or a paramedic. In practical application, the security medic also allows the security department to bypass balance otherwise built into the division of departments and individual jobs and detracts heavily from role play by wrongfully giving security extended, priority access to medbay mechanics that were never intended.
> 
> Outright removal has additional benefits, such as diminishing role play failures from the security department stemming from reduced penalties for injury or death, and rewarding the actual medical department for their skill and knowledge. It will also do wonders for reducing security department isolation and wrongful self-service.
> 
> The security medic role never should have been created in the first place, and after extended consideration, removal is a much more desirable option than reworking the role to bring it in line with access and power of other jobs on the station. Security is not mechanically prevented from buying their own first aid kits, crew monitor, and requesting additional access, but there are plenty of reasons they should not be given these under the guise of an official position. The security medic role itself is bad for the game, and needs to go.

I think you're failing to realise that they're not given access to much more than the standard security bay equipment which is barebones. Look, the entire point in the medic is to give someone that wants to spend more time in the brig but also doesn't want to spend time being the warden. They're there to care for the prisoners, which, are high risk. There is a reason every single station has a security medbay, it's the place most of the action happens. It's where people generally go to seek refuge. You're making it out as though they have egregious access to overpowered equipment, when, they don't. As you stated, someone needs to do the work of balancing them, so do that instead of removing them.

We're not gonna remove an entire role just because of a few balance concerns that rarely show up. That's not how we do things. If you want to change the role in ways that benefit everyone involved, go ahead. I personally enjoy the role as it gives you a chance to roleplay with prisoners, like in the oldbase, but, without making you mostly medical and in turn being even more independent from security(Brig phys). We had that in the oldbase and no one ever complained. Now that we have something that is less independent from medbay, you are complaining.

Based on this final assessment I'm going to close this PR, feel free to make a new one addressing any BALANCE concerns you have, such as, removing equipment. But as you know, right now, the brigbay is very very very lacklustre. Most people complain about it being UNDER equipped. Due to this split in opinions, removal is not an option.

**Pull request closed without merging**
