### PR TITLE
NRI Raiders "antag" datum

### PR DESCRIPTION
**Pull request by Stalkeros2**
## About The Pull Request
The sooner antags fully become "special roles", the better. Anyways, this PR's meant to finally add antag datums to the NRI Raiders. Also fixes a small bug related to them not receiving languages that they were meant to get.
I'll probably need to modularise their antag file properly at a later date because it became pretty cramped.

## How This Contributes To The Skyrat Roleplay Experience
Admins can track this I think.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

image

</details>

## Changelog

:cl: Stalkeros
add: NRI raiders antag datum.
fix: Fixes NRI raiders not getting the languages they were meant to get.
/:cl:

### CODE REVIEW

**Comment by vinylspiders** [comment]
I already fixed the bug with the languages a couple days ago. https://github.com/Skyrat-SS13/Skyrat-tg/pull/19311

**Comment by Stalkeros2** [comment]
Oh nice.

**Comment by Stalkeros2** [comment]
forgot to draft it brb

**Comment by Stalkeros2** [comment]
oops reflexes

**Pull request closed without merging**
