### PR TITLE
[SEMI-MODULAR] New chaplains can now select a sect, holy weapon, book, have custom religions, etc.

### LINKED ISSUE #11525: New Chaplains Cannot Select a New Sect
Reporting client version: 514.1575

## Round ID:
4515

## Testmerges:
- [[TM-Only] First attempt at stopping tgchat from eating messages](https://github.com/Skyrat-SS13/Skyrat-tg/pull/8842)
- [[TM?][v0.5] MekaNIKA cyborg skinline, AKA Tallborgs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10895)
- [YOU CURRENTLY NEED THIS PR TO RUN THE SERVER WITH A DATABASE CONNECTED ](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10823)
- [[Semi-Modular] Synthetic Rebalance III: A Rope of Sand](https://github.com/Skyrat-SS13/Skyrat-tg/pull/10821)
- [The MODsuit Digital Revolution: Replaces AIs in MODsuits with pAIs](https://github.com/Skyrat-SS13/Skyrat-tg/pull/11135)

## Reproduction: When joining the round as a Chaplain, if a previous one has cryo'd, you cannot select your own Sect (if none has been chosen). You also do not spawn spawn with your original bible, nor the religion you created. 
image
image
image

### PR DESCRIPTION
**Pull request by vinylspiders**
## About The Pull Request

Fixed #11525 Normally only the first chaplain to join the station can create a sect, and from there it is unchangeable.

Now, if the initial chaplain leaves the station via cryopod, the religious data gets reset allowing for any new chaplains who join to be able to customize everything as if they were the first chaplain to arrive.

## How This Contributes To The Skyrat Roleplay Experience

RP rounds can often last a long time, and during that time people may come and go. Effectively being locked out of your role due to the actions of a previous chaplain is frustrating to say the least! No more.

The next chaplain to join after the 'high priest' departs is chosen to be their successor. They will spawn with their own null rod, bible, and be able to change the style of these as well as choose a new sect. Once the successor leaves, the next chaplain to join the round will be chosen as their successor. And so on.

## Proof of Testing

<details>
<summary>First chaplain selects Punishment God</summary>

image

New chaplain arrives and uses their book on the old altar, getting a sect selection menu. 

image

But now, when the new chaplain clicks it with their book they can change it! Note the appearance change to Maintenance God's.

image

</details>

<details>
<summary>New chaplain arrives. Note altar still has the appearance of the punishment god's</summary>

image

</details>

<details>
<summary>Now after setting to Maintenance God the sect is successfully changed and the altar changes appearance</summary>

image

</details>

## Changelog

:cl:
qol: new chaplains can now be chosen as a successor to the previous one if the role has been freed via cryopod, enabling them to change the sect, holy weapon, bible, etc just as the initial chaplain would have been able to.
/:cl:

### CODE REVIEW

**Comment by theselfish** [comment]
I would try this upstream first. Though, I'm not entirely sure this is a fix either way.

**Comment by Iamgoofball** [comment]
We don't have cryo upstream anymore, it's a downstream thing now

**Comment by vinylspiders** [comment]
> I would try this upstream first. Though, I'm not entirely sure this is a fix either way.


Chaplains upstream aren't able to cryo so it is not an issue there, but here if you join a round as chaplain thinking you will get a null rod, a new sect, your customized religion, etc, that just won't happen. Seems like a bug/oversight to me. I can change it to qol though I guess.

**Comment by theselfish** [comment]
> We don't have cryo upstream anymore, it's a downstream thing now



> > I would try this upstream first. Though, I'm not entirely sure this is a fix either way.
> 
> Chaplains upstream aren't able to cryo so it is not an issue there, but here if you join a round as chaplain thinking you will get a null rod, a new sect, your customized religion, etc, that just won't happen. Seems like a bug/oversight to me. I can change it to qol though I guess.

The HoP can still open a new slot if the previous one goes DNR.
Then again that might lead to griefing over the alter.

**Comment by vinylspiders** [comment]
> > We don't have cryo upstream anymore, it's a downstream thing now
> 
> > > I would try this upstream first. Though, I'm not entirely sure this is a fix either way.
> > 
> > 
> > Chaplains upstream aren't able to cryo so it is not an issue there, but here if you join a round as chaplain thinking you will get a null rod, a new sect, your customized religion, etc, that just won't happen. Seems like a bug/oversight to me. I can change it to qol though I guess.
> 
> The HoP can still open a new slot if the previous one goes DNR. Then again that might lead to griefing over the alter.

Yeah, I thought about that. I'd rather not make it more complicated than it has to be. Less work for me to just have it work this way rather than have to create a system for tg, wait 2 months to have it merged, and then port that over here to work for cryopods. They are about to go into a freeze as well.

**Review by tf-4 — APPROVED** [review]

**Pull request merged**
