### PR TITLE
[MOSTLY NON-MODULAR] Hypovials can be printed from ChemMasters and pill presses. 

### PR DESCRIPTION
**Pull request by softcerv**
## About The Pull Request
Lets ChemMasters, along with pill presses, make small hypovials like they could on oldbase.
image
image
 Because of this, small vials have been removed from the autolathe. In order to allow the pill press machines to make hypovials, the buffer capacity on them has been increased to 60 (from 50)

## Why It's Good For The Game
Makes hypovials function closer to how they did on oldbase and hopefully makes them easier to use.

## Changelog
:cl:
del: Removed small hypovials from the autolathe
qol: Hypovials can now be produced by ChemMasters and pill presses, like on oldbase.
balance: Pill presses now have a buffer of 60 to accommodate for hypovials. 
/:cl:

### CODE REVIEW

**Comment by softcerv** [comment]
>code improvement

**Comment by GoldenAlpharex** [comment]
I'd put the change to the pill presses as a balance change more than anything, but likely not a code improvement.

**Comment by softcerv** [comment]
> 
> 
> I'd put the change to the pill presses as a balance change more than anything, but likely not a code improvement.

yeah, that would be better

**Comment by softcerv** [comment]
> 
> 
> I'd put the change to the pill presses as a balance change more than anything, but likely not a code improvement.

wasn't really sure what to put it as in the first place anyways, it's changed now.

**Comment by lyricalpaws** [comment]
+1 I love this feature

**Comment by ZephyrTFA** [comment]
This is nice, but feature freeze

**Comment by Gandalf2k15** [comment]
Do this upstream!

**Comment by softcerv** [comment]
> 
> 
> Do this upstream!

This is specifically relating to the MkII hyposprays that were added in PR https://github.com/Skyrat-SS13/Skyrat-tg/pull/1929. The TG hypospray doesn't use hypovials.

**Pull request merged**
