### PR TITLE
[Non-Modular] Modest Mollusk Bone Banishment

### PR DESCRIPTION
**Pull request by Nerev4r**
## About The Pull Request
Takes out their bones. I thought I did this already in the first PR, guess I forgot to.

## How This Contributes To The Skyrat Roleplay Experience
They're invertebrates, yo.

## Changelog

:cl:
balance: Snails are now invertebrates.
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
Boneless pizza.

**Comment by tf-4** [comment]
Does this just remove their ability to get bone wounds? It needs more justification than "they're invertebrates", i.e justification of the pretty sizeable buff.

**Comment by Nerev4r** [comment]
> Does this just remove their ability to get bone wounds? It needs more justification than "they're invertebrates", i.e justification of the pretty sizeable buff.

Yes.
The primary reason was pretty much just immersion, but they're weak enough in other aspects that I feel this is pretty much okay. They max out at five punch damage, take double burn damage, and move like 8x slower unless they're resting.

**Comment by SpaceVampire** [comment]
Clearly we should remove bones from podpeople and mushpeople as well following the same logic.
You ever heard of plants having bones?

**Comment by Nerev4r** [comment]
> Clearly we should remove bones from podpeople and mushpeople as well following the same logic. You ever heard of plants having bones?

Sounds based, PR it. But podpeople don't have nearly as many drawbacks.

**Review by GoldenAlpharex — COMMENTED** [review]
I'm mostly fine with this.

However, if you're going to make them not have bones, you should mention it as a positive trait on their species description (the little square icons listing advantages and drawbacks).

**Review by GoldenAlpharex — APPROVED** [review]
Nice.

**Pull request merged**
