### PR TITLE
Journey Science fixes and infrastructure adjustments

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Title

## Changelog

:cl:
fix: A few wallmounts on Journey in toxins launch are now mounted on the wall
fix: a few default atmos pipings on Journey around science now make more sense
/:cl:

### CODE REVIEW

**Comment by thestubborn** [comment]
tell me you added moisture traps and all that, IIRC jour don't have em

**Comment by tf-4** [comment]
> 
> 
> tell me you added moisture traps and all that, IIRC jour don't have em

out of scope

**Comment by thestubborn** [comment]
they're a science thing
image
seems in scope to me...

**Comment by tf-4** [comment]
It's not within scope.

**Pull request merged**
