### PR TITLE
[Modular] Removes Hitman bundle from the uplink.

### PR DESCRIPTION
**Pull request by KathrinBailey**
## About The Pull Request
• Simply removes the Hitman bundle.

## Why It's Good For The Game
I have no idea why this wasn't once tested before being pushed into the game.
Making traitors one-man armies isn't good for the game. It's not nuke-ops, it's traitors. Why are we giving nuke-op gear to traitor for dirt cheap?

This also completely ruined a mini-event involving four traitors (one without an uplink) versus a group of six seccies and a miner.
The seccies and miner were completely wiped out and some captured. Only two of the traitors actually did any fighting. Guess what they had? Yeah casual anti-material rifle traitors. Amazing.

## Changelog
:cl:
del: Hitman bundle no longer appears in the traitor uplink.
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Ah yes, the sneaky changes to toolspeed in the middle of the PR :^)

**Comment by KathrinBailey** [comment]
Yeah this PR totally changes toolspeed doesn't it?

**Comment by RatFromTheJungle** [comment]
image

(While we wait for Dragonfruits rework of the bundle)

**Comment by tf-4** [comment]
> Yeah this PR totally changes toolspeed doesn't it?

Chill, it's in the commits

**Comment by dawsonkeyes** [comment]
fun fact again: this and the meta-ops kit were unedited kits that are still ingame for 20tc that you might wanna dunk on as well, because i see you only removed the loadout and not the random kit

**Pull request merged**
