### PR TITLE
[READY] Engineering Reflective Clothing for Muzzles/Digi/Taur

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
As the title says, updates muzzled/vox Atmospherics Helmets as #8796 did, along with working emissives for them; does the same for the firesuits, radsuits, etc for digi and all Taurs (that had the sprites in the first place; I'm not making entire new sprites I'm not a spriter)

Also organizes and updates our modular icons as per the linked mirror PR, including organizing the emissives to be beside the icon and updating a few icons as well.
Does **NOT** move all our winter coats into a separate folder like the linked mirror did ~~as much as I'd like to do that~~

Digi firesuit emissives 
image

Digi atmos firesuit emissives + muzzled emissive atmos hardhat 
image

digi radsuit emissives 
image

vox atmos hardhat
image
image

snake taur emissives
image
image
image

other taur emissives
image
image

i also fixed some of the wack offsets on the taur icons

## How This Contributes To The Skyrat Roleplay Experience
Working reflective stuff for our non-humanoid engineers, as well as probably getting it to work in some places it probably wouldnt have worked. ~~(Merging icons should be less than just copy-pasting the new stuff at the end of the file)~~

## Changelog

:cl: Solgov Station Engineering Safety Association (SESA)
imageadd: New thinklite(tm) brand reflective strips are now included on non-humanoid engineering wear as well! The Association has also updated the non-humanoid Atmospherics Hardhat to be up to spec!
/:cl:

### CODE REVIEW

**Comment by GoldenAlpharex** [comment]
Needs sprite displayed in the PR body, then we can look into it.

**Comment by ghost** [comment]
> 
> 
> Needs sprite displayed in the PR body, then we can look into it.

done!

**Comment by GoldenAlpharex** [comment]
Update from master to pass CI.

**Comment by ghost** [comment]
NO THAT WAS WRONG NEVERMIND

**Comment by ghost** [comment]
@GoldenAlpharex @Gandalf2k15 should be ready as soon as the checks finish up

**Comment by ghost** [comment]
gonna re-open this for review, conflicts will be fixed whenever i get around to it tbh

**Comment by ghost** [comment]
Oh hey more merge conflicts :) I sure do love this mhm mhm

**Comment by ghost** [comment]
> 
> 
> Oh hey more merge conflicts :) I sure do love this mhm mhm

stfu [my mobile account] no one asked you

**Pull request merged**
