### PR TITLE
Removes the salt (Gandalf PR)

### PR DESCRIPTION
**Pull request by Xymec**
## About The Pull Request

Removes Gandalf the blue sparkledog thing.
We were having major codebase issues and after a long amount of time searching, we found out that Zonespace needed to be removed, also, cope.

## How This Contributes To The Skyrat Roleplay Experience

It removes Cobalt from the server to prevent anymore codebase issues.

## Changelog

:cl:
del: Removed Cobalt
del: Removed Herobrine
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
I'm sorry but he's too based to be removed.

**Comment by Zonespace27** [comment]
Overruled.

**Comment by Gandalf2k15** [comment]
Overoverruled.

**Comment by Zonespace27** [comment]
Fuck

**Comment by Zonespace27** [comment]
FUCK

**Comment by CandleJaxx** [comment]
THE GIRLS ARE FIGHTINGGG

**Comment by Xymec** [comment]
HAH

**Comment by Gandalf2k15** [comment]
Banned.

**Comment by GoldenAlpharex** [comment]
thanos-ill-do-it

**Comment by Gandalf2k15** [comment]
IM SORRY GOLDEN APPLES, YOUR TRIAL SUBSCRIPTION TO BEING MAINTAINER HAS RUN OUT.

**Comment by Seris02** [comment]
LMAO
Y'all are nerds

**Pull request closed without merging**
