### PR TITLE
[NOT MODULAR] 😈 lets you plant shrubs faster so duboris stays vaguely sane

### PR DESCRIPTION
**Pull request by RatFromTheJungle**
## About The Pull Request
title

## Why It's Good For The Game

shrubs take a really long time to plant, despite not doing much

## Changelog
:cl:
qol: you can now plant shrubs in a reasonable time with TiDi.
/:cl:

### CODE REVIEW

**Comment by Gandalf2k15** [comment]
Make it 1 second!

**Comment by Gandalf2k15** [comment]
Actually why is there even a delay

**Comment by RatFromTheJungle** [comment]
> 
> 
> Actually why is there even a delay

so people don't mash them because they're /technically/ non-traversable, and don't open a window like putting down glass does

**Comment by Elli-Skala** [comment]
> Actually why is there even a delay

because the tg designed bushes mostly to be a barror, you cant walk or see through them and have to bash them down to get past

**Comment by Gandalf2k15** [comment]
Ah okay, make it 4 seconds

**Comment by RatFromTheJungle** [comment]
@Gandalf2k15 4 second 😈

**Pull request merged**
