### PR TITLE
[MODULAR] Return of Removes Valeborg poster (duplicate) and the other thing

### PR DESCRIPTION
**Pull request by YakumoChen**
## About The Pull Request
Removes a duplicate entry for the valeborg poster.

## How This Contributes To The Skyrat Roleplay Experience
I don't know how the duplicated entry got there but its gone now

## Changelog
none

### CODE REVIEW

**Comment by YakumoChen** [comment]
if you dont merge this btw i will cry because I accidentally commited to master

**Comment by tf-4** [comment]
Committing to master gives you +5 based points

**Comment by ghost** [comment]
removing the icon isnt removing it from the pool, poster/random places subtypes of the poster items. If Upstream removed it, there should have been a mirror blacklisting the lizard poster from being chosen

**Comment by YakumoChen** [comment]
I'm looking into it but I think it's a deal with how "random" posters are selected as far as the gas posters still appearing.

They were removed in a PR though, for sure, from the contraband pool.

**Comment by YakumoChen** [comment]
giving up on the poster thing, just sticking with the duplicate

**Pull request closed without merging**
