### PR TITLE
[Modular] NOT FINISHED YET! Adds possibility to harvest milk from mammary glands

### PR DESCRIPTION
**Pull request by Guidesu**
## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by gonenoculer5** [comment]
So what your saying is.

M i l k e r s?

**Comment by Guidesu** [comment]
> So what your saying is.
> 
> M i l k e r s?

Yes

**Comment by gonenoculer5** [comment]
> > So what your saying is.
> > M i l k e r s?
> 
> Yes

My only question is, does lactate production scale with cupsize.

**Comment by Guidesu** [comment]
> > > So what your saying is.
> > > M i l k e r s?
> > 
> > 
> > Yes
> 
> My only question is, does lactate production scale with cupsize.

Yes

**Comment by Guidesu** [comment]
E.
Anyway this is just mostly an copy from the *Cum* emote but until someone makes an good system i will close it you kno

**Pull request closed without merging**
