### PR TITLE
[DNM] [TM ONLY] Removes Open Space from BlueShifts exterior

### PR DESCRIPTION
**Pull request by Jolly-66**
## About The Pull Request
BlueShift is running into performance issues as of late, and this PR takes a crack at trying to see if we can do anything about it.
This also makes you unable to go up/down a Z level outside the map, just as something to note.

## How This Contributes To The Skyrat Roleplay Experience
Hopefully reduces the amount of server crashes relating to maps.

## Changelog

:cl:
N/A for now.
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
if you're looking for performance issues I suggest you take a good look at the central area of blueshift. I know the whole like, mall aesthetic is one of the defining parts of the map, but I'm willing to wager that's a few thousand active turfs every round whenever some slight atmos change happens there.

**Comment by Jolly-66** [comment]
> Pax

This was just something discussed. I'm willing to take many avenues to see what is a more solid solution that doesn't involve some sort of insanity.

**Comment by Gandalf2k15** [comment]
We already did try this btw.

**Comment by StrangeWeirdKitten** [comment]
> > Pax
> 
> This was just something discussed. I'm willing to take many avenues to see what is a more solid solution that doesn't involve some sort of insanity.

Doesn't blueshift have multiple little Z-level holes throughout maint? So if you vent one area, there's a crap ton of atmos changes.

**Comment by Jolly-66** [comment]
Slapping stale-b-gone until we get BlueShift running for a few rounds.

Currently still disabled as of the time I'm posting this comment.

**Comment by Jolly-66** [comment]
I'll reopen this once we start running BlueShift again. Currently not an active TM.

**Pull request closed without merging**
