### PR TITLE
Adds gun cleaning kits to assault op lockers

### PR DESCRIPTION
**Pull request by Zonespace27**
## About The Pull Request
Assault op armory lockers get a gun cleaning kit.

## How This Contributes To The Skyrat Roleplay Experience
As an assault op, i dirtied my gun so badly it jammed every three shots *twice*, and there's no simple way of getting more.

## Changelog

:cl:
qol: Assault ops now get a gun cleaning kit in their lockers
/:cl:

### CODE REVIEW

**Comment by Stalkeros2** [comment]
I do remember those kits only repairing your gun, with cleaning being done via using cloth.
Which would also be a neat addition to those lockers.

**Comment by Gandalf2k15** [comment]
Salt pr

**Comment by Zonespace27** [comment]
> I do remember those kits only repairing your gun, with cleaning being done via using cloth. Which would also be a neat addition to those lockers.

Nope, the cloth is an unrelated TG feature.

**Comment by Zonespace27** [comment]
> Salt pr

Salt PR.

**Pull request merged**
