### PR TITLE
fake sunglasses

### PR DESCRIPTION
**Pull request by Gandalf2k15**
adds a new donator item, fake sunglasses.

literally just sunglasses without any protection

## Changelog

:cl:
add: Fake sunglasses.
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
While this is a neat idea, isn't its niche covered by the OSI shades?

**Comment by Gandalf2k15** [comment]
> While this is a neat idea, isn't its niche covered by the OSI shades?

they look dumb(in my opinion)

**Comment by Gandalf2k15** [comment]
> While this is a neat idea, isn't its niche covered by the OSI shades?

image
I don't want this little bit at the side

**Comment by tf-4** [comment]
fair

**Review by tf-4 — APPROVED** [review]

**Pull request merged**
