### PR TITLE
[Non-Modular] Removes the RND Console from Ancient Lathes

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
WE CAN'T HAVE NICE THINGS.

## Why It's Good For The Game
we don't need someone researching clown tech round start. I'm sorry, but policy just hasn't cut it for this, I still get complaints near daily about it.

## Changelog
:cl:
fix: Ancient lathes cannot print RND consoles  anymore. Maps that have them keep them, and will unless abused yet more.
/:cl:

### CODE REVIEW

**Comment by Elli-Skala** [comment]
abit upsetting as it takes away the only efficient way for golems to mine

**Comment by Elli-Skala** [comment]
couldnt we remove just the ai board from the lathe and have the same fix with out having to fully remove the exo fab?

the one ruin made for a ai (charlie) gets the stuff for the ai already, while cyber sun, interdyne, golems, and ds1 cant

**Comment by Elli-Skala** [comment]
also looking into this, you haven't actually stopped the building of ais, its still doable as ai boards and posi brains are still both buildable

**Comment by unit0016** [comment]
I updated it, kinda am done. My interest has hit shipstation level "I hate this but I must dress it's mutilated corpse".

**Comment by NullDagaf** [comment]
> WE CAN'T HAVE NICE THINGS.

Took you a bit to realise.

**Pull request closed without merging**
