### PR TITLE
Removes pay modifiers for roundstart species

### PR DESCRIPTION
**Pull request by Seris02**
## About The Pull Request

Removes pay modifiers from roundstart species

## Why It's Good For The Game

Because racism is bad. And because most of the people who play this server don't play humans.

## Changelog
:cl:
del: Removed pay modifiers from roundstart species.
/:cl:

### CODE REVIEW

**Review by atakiya — APPROVED** [review]

**Comment by Gandalf2k15** [comment]
I can see where you're going with this, and I sort of agree. Let's see what the other maintainers think.

**Comment by Azarak** [comment]
IC racism is fine, but as we dont have a proper lore yet, we dont know if any species should actually be recieving less pay. With our variety of species it should probably be a couple species that the NT is favoring for pay, if it's anything we want, but then again.. I dont know if it is.. where is the lore..

**Comment by MLGTASTICa** [comment]
I'd rather keep the IC lore , skyrat is after all a frontier station and NT is always known to care less about alien species.

**Comment by Azarak** [comment]
what lore

**Comment by hugmeorelse** [comment]
> what lore

Soon. Well, soonish.

**Comment by Gandalf2k15** [comment]
I'm closing this until lore is confirmed and sorted, please reopen it once we have a proper background to work with, for now, we'll use NT.

**Pull request closed without merging**
