### PR TITLE
[NON-MODULAR] Nerfs plasma sheet generation in the crystalliser

### PR DESCRIPTION
**Pull request by tf-4**
## About The Pull Request

Increases mols needed per sheet from 25 to 150 plus 15 mols of BZ. Honestly might need to be raised more but we'll see.

## Why It's Good For The Game

Haha gas miner goes brrrr. Free money bad

## Changelog
:cl:
balance: Plasma sheets made in the crystalliser require 150 mols per sheet, up from 25, as well as 15 mols of BZ. 
/:cl:

### CODE REVIEW

**Comment by MLGTASTICa** [comment]
Make it require 150 moles and another gas like BZ / Freon or Water vapor in low quantity , we have gas miners and it will generate infinite plasma , this willl just make it so atmos techs gamer the 300 moles requirement by placing a scrubber ontop of the gas miner , which is hooked to their crystaliizers..

**Comment by tf-4** [comment]
fair dinkums

**Comment by Sethnov** [comment]
i told the developer about this he says he nerf it, after seeing what it like on the tg server

**Comment by YakumoChen** [comment]
Yeah this is a brand new feature, you should wait until several changes are in the pipe before making non-modular PRs that will make merging them harder

**Comment by Ghilker** [comment]
Me looking at this PR 
tenor (6)

**Comment by tf-4** [comment]
> Yeah this is a brand new feature, you should wait until several changes are in the pipe before making non-modular PRs that will make merging them harder

I'll deal with that if it conflicts I guess. But we are *always* gonna need to kneecap it more than upstream cos we have the gas miners

**Pull request merged**
