### PR TITLE
[FUCK][SEMI-MODULAR]Clockwork Cult Port

### PR DESCRIPTION
**Pull request by Vizoplez**
## About The Pull Request
EXTREMELY WIP DRAFT

Ported from Beestation, credits to original authors and committers over there, love you guys.

- [x] Get a majority of code and sprites in
- [x] Get it functional
- [ ] Bugtest and fix 

## Why It's Good For The Game
LETS FUCKING GOOOOOOOOOOOOO

## Changelog
:cl:
code: MASSIVE CLOCKWORK CULT REFACTOR, ALONG WITH UNDERLYING SUBSYSTEMS. WARNING.
add: Clockwork Cult. Credits to Beestation and their various contributors!
/:cl:

### CODE REVIEW

**Comment by Arctaisia** [comment]
Post this Ratvar

**Comment by Vizoplez** [comment]
haha merge issues go brrr

**Comment by KaiserBlackwood** [comment]
OH GOD. THIS MADMAN IS DOING THIS.

**Comment by Vizoplez** [comment]
image

**Comment by Enzoman12** [comment]
I cant wait to see this happen! Good luck! Hopefully this doesnt mean I cant RP as a Ratvar Chaplin though

**Comment by BrotherHangyul** [comment]
wait

this wasn't a dream?

LET'S FUCKING GOOOOOOOOOOOOOOOOOO

**Comment by PowerfulBacon** [comment]
Something important to note is that you probably want our PR that removes the 'Starting game' message which runs before the pregame gamemode. Clockcult takes longer to load than all the other gamemodes due to the need to load Reebe, so having that message makes meta-ing the gamemode particularly easy.
https://github.com/BeeStation/BeeStation-Hornet/pull/2513

**Comment by Vizoplez** [comment]
> Something important to note is that you probably want our PR that removes the 'Starting game' message which runs before the pregame gamemode. Clockcult takes longer to load than all the other gamemodes due to the need to load Reebe, so having that message makes meta-ing the gamemode particularly easy.
> [BeeStation/BeeStation-Hornet#2513](https://github.com/BeeStation/BeeStation-Hornet/pull/2513)

This particularly wont be an issue here due to how we are loading Reebe, compared to your codebase; but thank you for the warning!

**Comment by Vizoplez** [comment]
image

nooo haha sleep() you're so sexy- LINT FAILURE

**Pull request closed without merging**
