### PR TITLE
[DNM] [EVENT CODE IN THE MAKING] Massive automatic map generator for dwarf fortress/deep rock galactic type cave systems, the surface and literal hell soon to come

### PR DESCRIPTION
**Pull request by Paxilmaniac**
## About The Pull Request

tf4 wanted to see the inner workings of this when I showed them the screenshots, and I want to get this testmerged eventually, so might I present:

<details>
<summary>Images from the perspective of a player</summary>

image
image
image
image

</details>

<details>
<summary>Images from the perspective of a ghost with second to max view range</summary>

image
image
</details>

## How This Contributes To The Skyrat Roleplay Experience

I don't think it does yet

## Proof of Testing

Uhhh its all in the sections above

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Paxilmaniac** [comment]
I will be shocked if this passes all the tests

**Comment by RimiNosha** [comment]
Woah

**Comment by Paxilmaniac** [comment]
image

**Comment by Kepteyn** [comment]
shok
It has failed a test, we may suspend our shock.

This looks badass, would be a shame if it was only for an event. Could be a great basis for an entire map.

**Comment by Paxilmaniac** [comment]
If I was gonna make this a real permanent map fr I'd probably have to optimize the generator because I'm fairly certain init times with this monster are a lot longer than they should be

**Comment by Paxilmaniac** [comment]
Actually I really just needed to see if this passed checks or not and which ones it failed, I'll come back with the actual event code later

**Pull request closed without merging**
