### PR TITLE
Interlink APCs and Cyborg Chargers

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Changes The Interlink to be a powered area, and gives it an infinite APC. Functionally its the same as it was, except now admins can access the APC however they want (bugfix and max charge it, turn it off if you need for _some reason idk_) and IPCs can charge off of it. It also adds cyborg rechargers to pair with this, allowing synthetics of all kinds to actually survive on the interlink.

Also, this was done by adding a "Dummy" APC that's invincible, infinite charge, AI-disabled, and locked to admin access only. Might be of use elsewhere eventually.

## Why It's Good For The Game
Now the 'bedridden' crew dont have to come back to the station every time they need to charge, and its even more of a "safezone"
Plus a ton of people were asking anyways

## Changelog
:cl:
add: The Interlink is now more synthetic-friendly, having installed a recharging port and cyborg charging stations for the synthetic crew!
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
> 
> 
> You currently have a negative Fix/Feature pull request delta of -36. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

shut the f
uckup

**Comment by YakumoChen** [comment]
..... question
what's stopping someone from just...
hacking it?

Honestly it might be easier just to add a Magic Power SMES somewhere in the interdyne admin rooms (where the telecomms machine is) and wiring it to that.

**Comment by YakumoChen** [comment]
image
something that is conveniently already in the code in fact.

not that I think your idea is bad but doing this would be a lot more secure then introducing a way to exist and steal an infinite power cell through a method you haven't thought of yet.

**Comment by ZephyrTFA** [comment]
> 
> 
> ..... question
> what's stopping someone from just...
> hacking it?
> 
> Honestly it might be easier just to add a Magic Power SMES somewhere in the interdyne admin rooms (where the telecomms machine is) and wiring it to that.

emag_act is overriden to not work; I'd recommend you actually read the code before criticizing it.

**Comment by YakumoChen** [comment]
> emag_act is overriden to not work; I'd recommend you actually read the code before criticizing it.

I don't appreciate comments like this.

emag_act has nothing to do with using a screwdriver and a multitool on it either.

**Comment by SpaceVampire** [comment]
Hacking it was my first thought as well.
Did you make it unscrewable or something?
On top of that, it does just feel unneeded.
It just makes you hungry if you run out of power, right?
You can still sit around and sex people with no actual downsides.
I'm extra unsure about why cyborg rechargers are needed for that reason.

**Comment by YakumoChen** [comment]
IMO it just works better to map in a magic SMES to a regular APC instead of making a babyproofed infinite-cell-holding APC

**Comment by ghost** [comment]
:^) cool

**Pull request closed without merging**
