### PR TITLE
CME tweaks and fire occurrence reduction

### PR DESCRIPTION
**Pull request by Gandalf2k15**
## About The Pull Request

Removed some unused code, removed the announcements for anyone off station, removed neutralized announcement too.

Closes https://github.com/Skyrat-SS13/Skyrat-tg/pull/4243

## Changelog
:cl:
qol: CME's are no longer as spammy.
/:cl:

### CODE REVIEW

**Comment by YakumoChen** [comment]
@Gandalf2k15 what about the whole "not setting people on fire" part because that's the entire point of the PR you're closing

**Comment by Gandalf2k15** [comment]
> @Gandalf2k15 what about the whole "not setting people on fire" part because that's the entire point of the PR you're closing

That voids any threat they pose. Removing that aspect is dumb.

**Comment by SpaceVampire** [comment]
Yeah, adding onto what Chen said, I don't really see how this PR works to close the other one.
Given that it doesn't seem to be addressing all of the same issues from it.
I mean, I do appreciate the announcement changes.
But I don't think "Fucks you over even if you do it correctly." is great balance.

**Comment by Gandalf2k15** [comment]
> Yeah, adding onto what Chen said, I don't really see how this PR works to close the other one.
> Given that it doesn't seem to be addressing all of the same issues from it.
> I mean, I do appreciate the announcement changes.
> But I don't think "Fucks you over even if you do it correctly." is great balance.

You just need to be wearing protection or have a fire extinguisher.

**Comment by YakumoChen** [comment]
> 
> 
> > @Gandalf2k15 what about the whole "not setting people on fire" part because that's the entire point of the PR you're closing
> 
> That voids any threat they pose. Removing that aspect is dumb.

I thought the primary threat they posed was EMPing the shit out of the station???? The fires they start are extremely minor and don't do anything but fill the station with trace plasma gas, being lit on fire by it is just a big middle finger to the crew.



> 
> 
> > Yeah, adding onto what Chen said, I don't really see how this PR works to close the other one.
> > Given that it doesn't seem to be addressing all of the same issues from it.
> > I mean, I do appreciate the announcement changes.
> > But I don't think "Fucks you over even if you do it correctly." is great balance.
> 
> You just need to be wearing protection or have a fire extinguisher.

neutralizing it hardstuns you and adds a bunch of firestacks. An event shouldn't punish you for trying to mitigate it. You're not even warned it will do this so it basically just kills you for trying to help. 

It adds enough firestacks you can't put it out by rolling and will almost definitely crit you if you're not <s>holding a fire extinguisher.</s> Have a fire extinguisher in your bag because you just drop it if you have it and die

It is EXTREMELY poor design and EXTREMELY unfun.

**Comment by YakumoChen** [comment]
> That voids any threat they pose. Removing that aspect is dumb.

By this logic we should remove neutralizing anomalies and shield sats for meteors because that voids any threat they pose, even if you put in the effort.

**Comment by Elli-Skala** [comment]
> > That voids any threat they pose. Removing that aspect is dumb.
> 
> By this logic we should remove neutralizing anomalies and shield sats for meteors because that voids any threat they pose, even if you put in the effort.

but we dont have shield sats

**Comment by GoldenAlpharex** [comment]
> > > That voids any threat they pose. Removing that aspect is dumb.
> > 
> > 
> > By this logic we should remove neutralizing anomalies and shield sats for meteors because that voids any threat they pose, even if you put in the effort.
> 
> but we dont have shield sats

We do, just not on non-greenshifts.

**Comment by Gandalf2k15** [comment]
Given feedback, I have now removed the fire spawning for anything less than red. Normal CME's will not spawn a fire when neutralized, reds and above will.

**Pull request merged**
