### PR TITLE
[Modular] Lone Infiltrator - Non-Crew Traitor Event.

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Adds a new event, the Lone Infiltrator. This polls ghosts if they want to be a new antagonist and traitor subtype - Also the Lone Infiltrator. Essentially, they're a traitor that spawns how loneops do, and aren't part of the crew. They start with a BRH, Chest Rig, and agent ID at one of the many carp spawnpoints - but have the freedom ambitions offer, like normal traitors.

- [x] ~~Maybe see about warning people that their prefs char will be used?~~ Name is randomized, good enough. They can always ahelp to change it to something else if they want. Plus cripple operatives is pretty funny.
- [ ] Balance adjustments. Maybe swap out the BRH for a normal EVA suit, or decrease starting TC?
- [x] Convert to dynamic midround. Hnghghg

image

## Why It's Good For The Game
Ghostroles already can roll antag midround, for some ungodly reason. This is a more eloquent solution to 'some asshole from cybersun/interdyne/DS-1 is raiding the station with gamer gear because they got lucky'.

## Changelog
:cl:
add: Lone Infiltrators are now on the prowl.
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
Noticing a lot of the ghostrole event weights have been nulled to zero for the main server's benefeit. Doing that here too!

**Comment by Gandalf2k15** [comment]
No they're not set to zero. They're handled by dynamic. Make this a midround ruleset

**Comment by unit0016** [comment]
> No they're not set to zero. They're handled by dynamic. Make this a midround ruleset

Ah hell, I know nothing about dynamic. I'll give it a shot though.

**Comment by Gandalf2k15** [comment]
> > No they're not set to zero. They're handled by dynamic. Make this a midround ruleset
> 
> Ah hell, I know nothing about dynamic. I'll give it a shot though.

Copy lone ops

**Comment by unit0016** [comment]
> > > No they're not set to zero. They're handled by dynamic. Make this a midround ruleset
> > 
> > 
> > Ah hell, I know nothing about dynamic. I'll give it a shot though.
> 
> Copy lone ops

Loneops code is needlessly tied up in other stuff. Space Dragon seems promising, I think I got it working. Here's hoping.

**Comment by unit0016** [comment]
Okay. Think I got that one working. Think. I couldn't actually test it, can't force it.
pain

**Review by Gandalf2k15 — APPROVED** [review]

**Pull request merged**
