### PR TITLE
[MODULAR] Pickle Cube.

### PR DESCRIPTION
**Pull request by SpaceVampire**
## About The Pull Request

This adds an offshoot of monkey cubes called the pickle cube, AKA "brine" cube with the mob taken from Citadel-Station code, fixed and tested to work here. It spawns a pickle, which can tickle.

There is no dedicated way to make a pickle cube, which means the only way to obtain it is through randomization. Essentially only doable with Xenobiology, which is fitting.

The risk of powergame is minimal, because it really can't do much of anything at all. 

## Why It's Good For The Game

Allows Xenobio to get their hands on pickles to research for actual roleplay without having to ask for divine intervention.
This means we get to research something in detail beyond slimes.

The potential is similar to existing tricks with gold core monster spawns and transfer potions, but this requires extra luck with RNG to produce. But unlike gold core monsters, there's a greater degree of dynamics to using this for roleplay.

Given the pickle isn't some feral alien, and is just a friendly brine-based lifeform, you don't have to worry about issues of LRP with people just chilling with it, or dealing with the fallout of something running around that looks like a hostile antag.

## Changelog
:cl:
add: Added a pickle cube from Citadel-Station to randomized food.
/:cl:

### CODE REVIEW

**Comment by gamermomentum** [comment]
firefox_7VxIP5Ihdp
firefox_Fui0pfMQci
hollow

**Comment by SpaceVampire** [comment]
> 
> 
> firefox_7VxIP5Ihdp
> firefox_Fui0pfMQci
> hollow

Self-love is important in this harsh world.

**Comment by Azarak** [comment]
Thank you for your contribution!

**Pull request closed without merging**
