### PR TITLE
[DNM] [WIP] Adds "Brazil Demon" to game! Take care or they will take you to Brazil!

### PR DESCRIPTION
**Pull request by Guidesu**
## About The Pull Request
image
Finally adds the Brazil Demon to game

## Why It's Good For The Game
B-brazil??
It's only admin bus meme it won't impact the game.

## Changelog
:cl:
add: Added the Brazil Demon which behaves like slaughter demon but instead they drag you to brazil! 
/:cl:

### CODE REVIEW

**Comment by Draganfrukts** [comment]
You are coming to Brazil. **We are not asking anymore.**

**Comment by KathrinBailey** [comment]
I'm almost certain I've seen this sprite before, add credit to the server it's from, unless you're porting your own sprite.

**Comment by Guidesu** [comment]
> I'm almost certain I've seen this sprite before, add credit to the server it's from, unless you're porting your own sprite.

The credit was made by a friend with who I don't have more contact since this was going to be used on an old SS13 Brazilian server which is dead.
The Guy doesn't want to be credited but anyhow his name is Paisda

**Comment by NullDagaf** [comment]
how
does this
contribute to a roleplay environment

**Comment by linnpap** [comment]
BASED PR

**Comment by GoldenAlpharex** [comment]
> how
> does this
> contribute to a roleplay environment

It absolutely doesn't.

**Comment by Guidesu** [comment]
> how
> does this
> contribute to a roleplay environment

admin bus.
Simple answer

**Comment by Guidesu** [comment]
Ah btw waiting to the #5665 be merged

**Comment by NullDagaf** [comment]
> admin bus.
> Simple answer

That is not an answer, and I absolutely despise when people use this argument as one.
"ooh, don't worry it's admin only" - well sorry bud, admins abuse things too. They're just ordinary people, put into positions of power - assuming that they're somehow more responsible than everyone else is foolish at best, and ignorant at worst. And it's not a baseless claim either - I've seen them abuse tools given to them more than once, be it by putting themselves in a body of a bloodcrawling, shadowcrawling, fully-armored changeling, or by spawning in a literal clown-ops team.

But disregarding my "mild distaste" for administrative staff, because I'm going mightily off-topic here.
This isn't a bad PR, m'kay? It is good, but it simply doesn't *fit* here. It'd be a good thing to add to TG (please don't no one will revert it here), Fulp, etc. But it's not a good thing to have HERE, on a ROLEPLAY server. Yes, it's "admin bus" exclusive, but it's still not a good thing roleplay-wise. And if it isn't, and admins shouldn't spawn it in - then what's even the point?

---

Also that joke went sour months ago, so there's that.

**Comment by Guidesu** [comment]
> > admin bus.
> > Simple answer
> 
> That is not an answer, and I absolutely despise when people use this argument as one.
> "ooh, don't worry it's admin only" - well sorry bud, admins abuse things too. They're just ordinary people, put into positions of power - assuming that they're somehow more responsible than everyone else is foolish at best, and ignorant at worst. And it's not a baseless claim either - I've seen them abuse tools given to them more than once, be it by putting themselves in a body of a bloodcrawling, shadowcrawling, fully-armored changeling, or by spawning in a literal clown-ops team.
> 
> But disregarding my "mild distaste" for administrative staff, because I'm going mightily off-topic here.
> This isn't a bad PR, m'kay? It is good, but it simply doesn't _fit_ here. It'd be a good thing to add to TG (please don't no one will revert it here), Fulp, etc. But it's not a good thing to have HERE, on a ROLEPLAY server. Yes, it's "admin bus" exclusive, but it's still not a good thing roleplay-wise. And if it isn't, and admins shouldn't spawn it in - then what's even the point?
> 
> Also that joke went sour months ago, so there's that.

e

**Comment by Vizoplez** [comment]
> > admin bus.
> > Simple answer
> 
> That is not an answer, and I absolutely despise when people use this argument as one.
> "ooh, don't worry it's admin only" - well sorry bud, admins abuse things too. They're just ordinary people, put into positions of power - assuming that they're somehow more responsible than everyone else is foolish at best, and ignorant at worst. And it's not a baseless claim either - I've seen them abuse tools given to them more than once, be it by putting themselves in a body of a bloodcrawling, shadowcrawling, fully-armored changeling, or by spawning in a literal clown-ops team.
> 
> But disregarding my "mild distaste" for administrative staff, because I'm going mightily off-topic here.
> This isn't a bad PR, m'kay? It is good, but it simply doesn't _fit_ here. It'd be a good thing to add to TG (please don't no one will revert it here), Fulp, etc. But it's not a good thing to have HERE, on a ROLEPLAY server. Yes, it's "admin bus" exclusive, but it's still not a good thing roleplay-wise. And if it isn't, and admins shouldn't spawn it in - then what's even the point?
> 
> Also that joke went sour months ago, so there's that.

cope

**Comment by Gandalf2k15** [comment]
We dont need more admin spawn bloat. I'm sorry. I need to be more firm here.

**Pull request closed without merging**
