### PR TITLE
[MIRROR] adds atmospheric gloves, small resprite of firefighter gear, repaths stupid glove paths [MDB IGNORE]

### PR DESCRIPTION
**Pull request by SkyratBot**
Original PR: https://github.com/tgstation/tgstation/pull/72736
--------------------
## About The Pull Request
repaths a lot of gloves off /color because they were incredibly stupid
firefighter gear has gotten an update (it doesnt cover hands anymore though, you need something else)
firefighter helmets no longer hide your mask or glasses
image
fixed engine goggles starting with darkness vision
to the atmos lockers adds atmospheric gloves, a pair of thick (chunky fingers) gloves that are fireproof and fire protective, slightly shock resistant and let you fireman carry people faster.
atmospheric firefighter helmets now are a subtype of welding hardhats, you can enable a welding visor.
welding hardhats change mode with right click instead of altclick

## Why It's Good For The Game
im not a good spriter but i think this resprite makes them fit nicer with other engi equipment
lets me firefighter rp

## Changelog
:cl:
add: Atmospheric Gloves, thick gloves that are fully fireproof and fire protective and let you fireman carry people faster.
fix: fixes engine goggles starting with darkness vision
qol: firefighter helmets can now enable a welding visor
qol: welding hardhats change mode with right click instead of altclick
balance: firesuits no longer protect your hands
/:cl:

### CODE REVIEW

**Comment by tf-4** [comment]
Great job Fikou from tg station

**Comment by ghost** [comment]
Suit may need Digi tweaking; atmos 'welding' mask could use muzzle sprites now that it'll be a thing

**Comment by Funce** [comment]
Needs to have its modular sprites updated
`modular_skyrat\master_files\icons\mob\clothing\head_muzzled.dmi`

**Review by GoldenAlpharex — APPROVED** [review]
Should be good, outside of Tramstation's changes which look a little excessive compared to all the other maps.

**Comment by Paxilmaniac** [comment]
Should be good they say with every map CI failing

**Comment by Paxilmaniac** [comment]
> Should be good, outside of Tramstation's changes which look a little excessive compared to all the other maps.

As for tramstation, 
image

IDK this either means something catastrophic has happened, or like no change at all happened.

**Comment by GoldenAlpharex** [comment]
> > Should be good, outside of Tramstation's changes which look a little excessive compared to all the other maps.
> 
> As for tramstation, image
> 
> IDK this either means something catastrophic has happened, or like no change at all happened.

So is that a "yolo" moment then?

**Comment by GoldenAlpharex** [comment]
I looked at it in SDMM and it looks fine, so yolo I guess!

**Pull request merged**
