### PR TITLE
[AutoMapper] icebox touchups

### PR DESCRIPTION
**Pull request by press-mark**
## About The Pull Request
fixes some map problems that bugged me

## How This Contributes To The Skyrat Roleplay Experience

<details>
<summary>fixes doubled up pipes & cabling outside the barbershop</summary>

image

</details>

<details>
<summary>also restores the multi z utility connections in the little maint closet</summary>

image

</details>

## Changelog

:cl:
fix: NT Rep's office is now connected to the power grid / distro on icebox.
fix: There's now a ladder in the HoP's maint closet.
fix: Removed some doubled up pipes & cables next to the barber.
/:cl:

### CODE REVIEW

**Review by Paxilmaniac — APPROVED** [review]
Looks good to me

**Review by Jolly-66 — APPROVED** [review]
The eternal issue has been fixed.
Would've gotten to it myself/sooner but I'm bogged down with college.

**Review by GoldenAlpharex — CHANGES_REQUESTED** [review]
Seems like there's some pipe overlaying happening in your icebox_hop_maint.dmm, that's why the unit tests are crying right now.

**Comment by press-mark** [comment]
> Seems like there's some pipe overlaying happening in your icebox_hop_maint.dmm, that's why the unit tests are crying right now.

fixed, should be good to go now.

**Pull request merged**
